### ISSUE TITLE
[BUG] Test failed with 'error code ELIFECYCLE' due to the long name 

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#10009]
**Context:**
- Playwright Version: 1.16.2
- Operating System: Windows 10
- Node.js version: v14.18.0
- Browser: Chrome
- IDE: Webstorm

**Code Snippet**

The error from the log file

```javascript
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'testInOneBrowser',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.0
4 verbose run-script [ 'pretestInOneBrowser', 'testInOneBrowser', 'posttestInOneBrowser' ]
5 info lifecycle playwright-seatgeek@1.0.0~pretestInOneBrowser: playwright-seatgeek@1.0.0
6 info lifecycle playwright-seatgeek@1.0.0~testInOneBrowser: playwright-seatgeek@1.0.0
7 verbose lifecycle playwright-seatgeek@1.0.0~testInOneBrowser: unsafe-perm in lifecycle true
8 verbose lifecycle playwright-seatgeek@1.0.0~testInOneBrowser: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\projects\sro4\uiAutomation\PlaywrightTest\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Google\Google Apps Sync\;C:\Program Files (x86)\Google\Google Apps Migration\;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Git\cmd;D:\apache-maven-3.6.3\bin;D:\Program Files\Java\jdk1.8.0_151\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\nodejs\;C:\Users\david\AppData\Local\Microsoft\WindowsApps;C:\Users\david\AppData\Local\GitHubDesktop\bin;C:\Users\david\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\david\AppData\Roaming\npm;
9 verbose lifecycle playwright-seatgeek@1.0.0~testInOneBrowser: CWD: D:\projects\sro4\uiAutomation\PlaywrightTest
10 silly lifecycle playwright-seatgeek@1.0.0~testInOneBrowser: Args: [ '/d /s /c', 'npx playwright test --workers=1 --headed' ]
11 silly lifecycle playwright-seatgeek@1.0.0~testInOneBrowser: Returned: code: 1  signal: null
12 info lifecycle playwright-seatgeek@1.0.0~testInOneBrowser: Failed to exec testInOneBrowser script
13 verbose stack Error: playwright-seatgeek@1.0.0 testInOneBrowser: `npx playwright test --workers=1 --headed`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid playwright-seatgeek@1.0.0
15 verbose cwd D:\projects\sro4\uiAutomation\PlaywrightTest
16 verbose Windows_NT 10.0.22000
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "testInOneBrowser" "--scripts-prepend-node-path=auto"
18 verbose node v14.18.0
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error playwright-seatgeek@1.0.0 testInOneBrowser: `npx playwright test --workers=1 --headed`
22 error Exit status 1
23 error Failed at the playwright-seatgeek@1.0.0 testInOneBrowser script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Describe the bug**

It seems like the test failed due to the long name of the 'spec' file:
![image](https://user-images.githubusercontent.com/52656401/140061980-4f2a85b1-6d75-4b00-93df-ca3ae142b69a.png)

After changing the file name to the shorter one - it works as well:
![image](https://user-images.githubusercontent.com/52656401/140062106-3e594c7b-aff0-411c-8815-67107845ba63.png)

From where this limit can come?

**Comment by mxschmitt** [comment]
I tried to reproduce it, but was not able to. Some general questions:

- Could you try executing it without NPM, so `npx playwright test`
- Could you try upgrading your NPM (`npm i -g npm@8`)

If it's still not fixed, would be awesome if you could create a minimum reproducible, since I was not able to repro it on my Windows machine.

**Comment by AlexKomanov** [comment]
@mxschmitt 
I will try to use the commands and will try to reproduce and will inform here.

**Comment by mxschmitt** [comment]
Hmm, could it be that when the question `Terminate batch job (Y/N)?` gets asked, that you press `N` by accident? I could only reproduce it that way.
