### ISSUE TITLE
[BUG] Run in Docker triggers error: Could not find any font: Segoe UI, sans. Falling back to the default

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#10036]
**Context:**
- Playwright Version: 1.16.2
- Operating System: Windows
- Node.js version: 12.4.1
- Browser: Chrome
- Extra: Docker runner

**Code Snippet**

```javascript
browserContext.newPage: Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\CONTAI~1\AppData\Local\Temp\playwright_chromiumdev_profile-CakY4d --remote-debugging-pipe --no-startup-window
<launched> pid=4836
[pid=4836][err] [1103/235840.859:ERROR:network_change_notifier_win.cc(228)] WSALookupServiceBegin failed with: 0
[pid=4836][err] [1103/235840.892:ERROR:platform_font_skia.cc(344)] Could not find any font: Segoe UI, sans. Falling back to the default

```

```javascript
browserContext.newPage: Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\CONTAI~1\AppData\Local\Temp\playwright_chromiumdev_profile-CakY4d --remote-debugging-pipe --no-startup-window
<launched> pid=4836
[pid=4836][err] [1103/235840.859:ERROR:network_change_notifier_win.cc(228)] WSALookupServiceBegin failed with: 0
[pid=4836][err] [1103/235840.892:ERROR:platform_font_skia.cc(344)] Could not find any font: Segoe UI, sans. Falling back to the default
    at Object.page [as fn] (C:\tmp\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\index.js:529:29)
    at Fixture.setup (C:\tmp\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\fixtures.js:74:73)
    at FixtureRunner.setupFixtureForRegistration (C:\tmp\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\fixtures.js:315:5)
    at FixtureRunner.resolveParametersAndRunHookOrTest (C:\tmp\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\fixtures.js:300:23)
    at WorkerRunner._runHooks (C:\tmp\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\workerRunner.js:544:9)
    at WorkerRunner._runBeforeHooks (C:\tmp\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\workerRunner.js:450:7)
    at WorkerRunner._runTestWithBeforeHooks (C:\tmp\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\workerRunner.js:470:32)
```

**Describe the bug**

We started to use Docker containers as runners of our tests. We just use them as a platform to run tests with all required installations. The tests trigger errors in the 'New Page' stage. 

The tests started as well and give output (I get generated Allure report):
![image](https://user-images.githubusercontent.com/52656401/140281919-f4e4f3ad-f1db-4ba4-bad7-03332e59e480.png)

Looks like a font missing. But maybe we need to install something extra?

**Comment by mxschmitt** [comment]
Which docker image are you using? We have an official one which includes all the necessary fonts etc.: https://playwright.dev/docs/docker

**Comment by Liroyal** [comment]
Hi @mxschmitt ,
I’m from @AlexKomanov team.

We use Windows containers (as opposed to Linux containers) as part of Docker Compose, thus cannot use the official images.

Appreciate any guidelines or tips on how to create a corresponding Windows container based image.

**Comment by mxschmitt** [comment]
We don't test it with Windows containers, there you probably have to manually install the fonts somehow. We strongly recommend to use the normal Linux Docker container, since its well tested by us and includes all the needed fonts.

(see probably [here](https://stackoverflow.com/questions/54366537/adding-fonts-in-server-core-2019ltsc-container-image) for fonts, but as I said, we would discourage from using Windows containers with Playwright)

**Comment by Liroyal** [comment]
Thanks @mxschmitt for the prompt response.

**Comment by mxschmitt** [comment]
Closing since Windows Containers are not officially supported by Playwright. Please refer to the official Linux based Docker image: https://playwright.dev/docs/docker
