### ISSUE TITLE
[BUG] Error messages are to verbose and confusing

### ISSUE THREAD

**Issue by DavertMik** [microsoft/playwright#10305]
I took `e2e-examples` of Playwright and changed a line which broke a test (changed `Learn` to `Le1arn`):

```js
await expect(todoList).toHaveText('Le1arn Playwright');
```
The error is very obvious and could be a quick fix. However, when I inspect the output of `line` reporter I see this:

```
    Error: expect(received).toHaveText(expected)

    - Expected string  - 1
    + Received string  + 8

    - Le1arn Playwright
    +
    +
    + 	
    + 		
    + 		Learn Playwright
    + 		
    + 	
    +

    Call log:
      - waiting for selector ".todo-list"
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "
      -   selector resolved to <ul class="todo-list">…</ul>
      -   unexpected value "

    	
    		
    		Learn Playwright
    		
    	
    "


      14 |   await inputBox.fill('Learn Playwright');
      15 |   await inputBox.press('Enter');
    > 16 |   await expect(todoList).toHaveText('Le1arn Playwright');
         |                          ^
      17 | });
      18 |

        at /home/davert/demos/playwright-demo/new-project/e2e-examples/1-getting-started.spec.ts:16:26
        at WorkerRunner._runTestWithBeforeHooks (/home/davert/demos/playwright-demo/new-project/node_modules/@playwright/test/lib/workerRunner.js:478:7)
``` 

As a user, I need to inspect 100 lines of output to fix 1 line of code!

Also, it is unclear what is meant here?

```
    - Expected string  - 1
    + Received string  + 8
```
I expected to see comparison of `Learn Playwright` and `Lea1rn Playwright` and not 1 to 8.... 

My proposal here:

* trim text values in the output
* don't list all retries in output
* make expected/received to actually compare texts from the page

**Comment by DavertMik** [comment]
Things are a bit worse than I thought. This is `error.message` of this error. 
It is bad because:

* it is not related to a reporter, so any reporter will print this
* it contains ANSI codes, so reporters other than CLI will have it incorrectly formatted
* it is 100+ lines long!

```
[2mexpect([22m[31mreceived[39m[2m).[22mtoHaveText[2m([22m[32mexpected[39m[2m)[22m

[32m- Expected string  - 1[39m
[31m+ Received string  + 8[39m

[32m- Le[7m1[27marn Playwright[39m
[31m+[39m
[31m+[39m
[31m+ [43m	[49m[39m
[31m+ [43m		[49m[39m
[31m+ [7m		[27mLearn Playwright[39m
[31m+ [43m		[49m[39m
[31m+ [43m	[49m[39m
[31m+[39m

Call log:
  - [2mwaiting for selector ".todo-list"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m
[2m  -   selector resolved to <ul class="todo-list">…</ul>[22m
[2m  -   unexpected value "[22m

[2m	[22m
[2m		[22m
[2m		Learn Playwright[22m
[2m		[22m
[2m	[22m
[2m"[22m

```

**Comment by yury-s** [comment]
Merging into https://github.com/microsoft/playwright/issues/10370
