### ISSUE TITLE
[BUG] Tests fail when test title is too long and PW fail to create directory

### ISSUE THREAD

**Issue by tymfear** [microsoft/playwright#10361]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.16.3
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] 14.17.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

Error
```
Error: ENAMETOOLONG: name too long, mkdir '/path-to-ptoject/test-results/long name goes here'

    at Object.mkdirSync (fs.js:1009:3)
    at Object.outputPath (/path-to-ptoject/node_modules/@playwright/test/lib/workerRunner.js:273:21)
    at /path-to-ptoject/fixtures/selenoid.fixture.ts:47:24
    at TestTypeImpl._step (/path-to-ptoject/node_modules/@playwright/test/lib/testType.js:214:13)
    at Function.step (/path-to-ptoject/node_modules/@playwright/test/lib/transform.js:133:12)
    at Object.page [as fn] (/path-to-ptoject/fixtures/selenoid.fixture.ts:45:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Fixture.teardown (/path-to-ptoject/node_modules/@playwright/test/lib/fixtures.js:101:7)
    at FixtureRunner.teardownScope (/path-to-ptoject/node_modules/@playwright/test/lib/fixtures.js:272:11)
    at WorkerRunner._runAfterHooks (/path-to-ptoject/node_modules/@playwright/test/lib/workerRunner.js:517:7)
```

So I normally solve this like this
```typescript
const screenshotName = `${title}.png`.slice(- 255);
const screenshotPath = resolve(__dirname, '..', 'test-results', screenshotName);

```

It's not perfect solution, but worked good enough last couple years with AVA.

**Comment by Alban34** [comment]
Hi, 

I'm still facing this issue. Here is my context:

Playwright Version: [what Playwright version do you use?] 1.18.0
Operating System: [e.g. Windows, Linux or Mac] Mac
Node.js version: [e.g. 12.22, 14.6] 16.3.0
Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium, Firefox, WebKit
Extra: [any specific details about your environment] none

Would it be possible that there are multiple locations in the playwright code that is creating those folders with too long names?

Here is my error message:
Error: ENAMETOOLONG: name too long, mkdir [...]

Thanks for your help.

**Comment by otoniel-isidoro** [comment]
which dependency @Alban34 ?
