### ISSUE TITLE
[Question] Attaching playwright to an existing electron window?

### ISSUE THREAD

**Issue by sunmeixia2005** [microsoft/playwright#10369]
Hi guys,

I am new on playwright, currently investigate if playwright can connect to an existing electron application?
I try to some code:
`browser_aut = playwright.chromium.connect("ws://127.0.0.1:8768/devtools/browser/b62e618c-27e9-456a-a0d2-363a27d46755")`

it error when try to execute it, error not special the:

Task exception was never retrieved
future: <Task finished name='Task-11' coro=<Connection.run.<locals>.init() done, defined at C:\Users\sunme\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:174> exception=Error('Playwright connection closed')>
Traceback (most recent call last):
  File "C:\Users\sunme\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 175, in init
    self.playwright_future.set_result(await self._root_object.initialize())
  File "C:\Users\sunme\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 135, in initialize
    await self._channel.send(
  File "C:\Users\sunme\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\sunme\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
  File "C:\Users\sunme\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_browser_type.py", line 203, in connect
    playwright: "Playwright" = next(iter(done)).result()
playwright._impl._api_types.Error: Playwright connection closed

my electron is start with argument --remote-debugging-port=8768, I want to know if playwright has such feature to attach existing electron app? if not, is any plan to support in future?

**Comment by aslushnikov** [comment]
@sunmeixia2005 try using [`chromium.connect_over_cdp`](https://playwright.dev/python/docs/api/class-browsertype/#browser-type-connect-over-cdp) instead

**Comment by sunmeixia2005** [comment]
> @sunmeixia2005 try using [`chromium.connect_over_cdp`](https://playwright.dev/python/docs/api/class-browsertype/#browser-type-connect-over-cdp) instead
Thanks for replying.

I try 3 different ways, all of them give some errors:
a. call connect_over_cdp using http endpoint url, not work, error say: 
playwright._impl._api_types.Error: Protocol error (Browser.setDownloadBehavior): Browser context management is not supported.
`browser_aut = playwright.chromium.connect_over_cdp("http://localhost:8768") `

b. call connect_over_cdp using ws endpoint, not work, error say: 
#playwright._impl._api_types.Error: Protocol error (Browser.setDownloadBehavior): Browser context management is not supported.
   ` browser_aut = playwright.chromium.connect_over_cdp("ws://127.0.0.1:8768/devtools/browser/1e139584-1b76-4533-a41f-1c52e802751b") `

c.  call connect using ws endpoint, also not work, error message is attached in first post, say: 
#playwright._impl._api_types.Error: Playwright connection closed
   `browser_aut = playwright.chromium.connect("ws://127.0.0.1:8768/devtools/browser/1e139584-1b76-4533-a41f-1c52e802751b") `

**Comment by JoelEinbinder** [comment]
Looks like we have a bug when connecting over CDP to electron or android.

**Comment by Sunny1861** [comment]
@JoelEinbinder  Thanks, look forward the version 1.18 out.

**Comment by Sunny1861** [comment]
@dgozman , May I know what kind of feedback want to collect?
We are in research stage for new product UI automation, it is matter for us if playwright support to attach existing electron or not.

**Comment by dgozman** [comment]
@Sunny1861 Electron is not a priority for Playwright, so I don't expect this to be fixed soon. Especially, without a clear repro script. 

> May I know what kind of feedback want to collect?

This means we acknowledge the issue, but we'll prioritize it depending on the amount of feedback/similar requests/thumbs up.

**Comment by J1s0n** [comment]
Hi, 
We are also doing some research on UI automation and how to attach to the exist Electron process and for now if we want to use Playwright we can only use electron.launch("main.js"). Actually it works well but it would be better if Playwright support attach to an existing Electron process. @dgozman  is there any possiable that playwright will spuuort this? it really matter to us, Thanks.

**Comment by 970263611** [comment]
We have the same issue, please give high priority to this issue. Thanks.

**Comment by 970263611** [comment]
> Hi, We are also doing some research on UI automation and how to attach to the exist Electron process and for now if we want to use Playwright we can only use electron.launch("main.js"). Actually it works well but it would be better if Playwright support attach to an existing Electron process. @dgozman is there any possiable that playwright will spuuort this? it really matter to us, Thanks.

We have the same issue, could you leave your email here so that we could discuss about this issue?

**Comment by mr25mr** [comment]
We have the same issue. For us this is a blocker to use playwright framework, because we simply can not connect to an instance over remote debugging port. Can you please deal with it with highest priority? Thanks.

**Comment by Finedas** [comment]
Not being able to attach Playwright to an existing instance of Electron is a blocker for us too. It would be very much appreciated if this was dealt with with more priority. Thanks.

**Comment by luxuncang** [comment]
I don't know how it's going now👍

**Comment by mohghaderi** [comment]
up vote 👍

**Comment by pavelfeldman** [comment]
Could you share with us why this is a blocker? I.e. why the current functionality when we start up app is not working?

**Comment by mohghaderi** [comment]
@pavelfeldman This can be one reason: We needed developers to run E2E on their machines without exiting Electron. Running Electron app takes 1 minute (thanks to awesome Webpack masterpiece design!), and building the app takes several minutes (again thanks to the same tool). 
So, let's say something goes wrong during the test and the developer needs to change E2E or the app to pass the test, it will takes minutes to re-test again. Attaching to the same instance avoid webpack build time and allows using its hot reloading feature and solves this problem. Switching to a faster build tools like Vite is not an option for us at this point.

**Comment by shalak** [comment]
This case is blocking us from introducing playwright, we must be able to connect to standalone electron app.

Are there any workarounds to achieve this as of today?

**Comment by abhinaba-ghosh** [comment]
up vote 👍

**Comment by lindon0390** [comment]
up vote 👍

**Comment by AlexandrDimenko** [comment]
up vote 👍

**Comment by shalak** [comment]
> @Sunny1861 Electron is not a priority for Playwright, so I don't expect this to be fixed soon. Especially, without a clear repro script.

I created the reproduction scripts: https://github.com/shalak/example-electron

Having electron supported is crucial for my company to migrate from Selenium tests. Is there anything else I could do to help with this?

**Comment by shalak** [comment]
> @Sunny1861 Electron is not a priority for Playwright, so I don't expect this to be fixed soon. Especially, without a clear repro script.

@dgozman - I created the reproduction scripts: https://github.com/shalak/example-electron

Having electron supported is crucial for my company to migrate from Selenium tests. Is there anything else I could do to help with this?

**Comment by geo-kurian** [comment]
up vote 👍

**Comment by kyrvlasiuk** [comment]
up vote 👍

**Comment by lixingxing1231** [comment]
Upvote

**Comment by vrknetha** [comment]
Upvote

**Comment by WorldWarriorIII** [comment]
upvote

**Comment by SepOrange** [comment]
upvote

**Comment by neemspees** [comment]
Upvote

**Comment by crazymonkey** [comment]
Upvote

**Comment by teo-anastasiadis** [comment]
Yes, this would be very usefull on our use case as well. I'd be open to contribute.

**Comment by Forguz** [comment]
Up

**Comment by guitarlive722** [comment]
up vote

**Comment by Capricorn25Dec** [comment]
upvote

**Comment by vileoleone** [comment]
upvote

**Comment by ukco** [comment]
upvote

**Comment by lizsGH** [comment]
upvote

**Comment by gechaoye** [comment]
upvote

**Comment by ilyasf** [comment]
upvote

**Comment by webnetweaver** [comment]
upvote

**Comment by sielicki** [comment]
No, it works fine: 

```shell
❯ ( /Applications/<detail>/Contents/MacOS/<detail> 
    --remote-debugging-port=8315
    --remote-allow-origins=http://localhost:8315 2>&1 &) > /dev/null

❯ python3 script.py

❯ python3 --version && 
  python3 -c 'from playwright._repo_version import __version__ ; print(f"playwright: {__version__}")'

Python 3.13.2
playwright: 1.51.0

❯ cat script.py
import asyncio
from playwright.async_api import async_playwright, Playwright

async def run(playwright: Playwright):
    browser = await playwright.chromium.connect_over_cdp("http://localhost:8315")
    default_context = browser.contexts[0]
    page = default_context.pages[2]
    await page.keyboard.type("Hello World!")

async def main():
    async with async_playwright() as playwright:
        await run(playwright)

if __name__ == '__main__':
    asyncio.run(main())
```

I get a successful attachment to the target app and "Hello World" is inserted.

**Comment by marufrasully** [comment]
@sielicki it looks like the issue is resolved now. Test with playwright version `1.51.1`  and worked for me.

**Comment by sielicki** [comment]
> @sielicki it looks like the issue is resolved now. Test with playwright version `1.51.1`  and worked for me.

Was it ever actually broken?
