### ISSUE TITLE
[Question] Support for AWS Amplify test phase

### ISSUE THREAD

**Issue by linosorice** [microsoft/playwright#10439]
I would like to use playwright on AWS Amplify. I tried without success. The following is my build spec.

```yml
version:` 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install lts/fermium
        - nvm use lts/fermium
        - yarn install
    build:
      commands:
        - yarn run build
    
  artifacts:
    baseDirectory: e2e
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  phases:
    preTest:
      commands:
        - yarn playwright install
    test:
      commands:
        - yarn test:e2e
```

This is the log of Amplify test phase:

```
2021-11-19T13:25:45.346Z [WARNING]: [WebServer] Error: Cannot find module '/codebuild/output/src391212811/src/forms_frontend/.next/server/font-manifest.json'
                                    [WebServer] Require stack:
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/require.js
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/load-components.js
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/api-utils.js
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/next-server.js
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/next.js
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/lib/start-server.js
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/cli/next-start.js
                                    [WebServer] - /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/bin/next
                                    [WebServer]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
                                    [WebServer]     at Function.mod._resolveFilename (/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/build/webpack/require-hook.js:96:28)
                                    [WebServer]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
                                    [WebServer]     at Module.require (internal/modules/cjs/loader.js:887:19)
                                    [WebServer]     at require (internal/modules/cjs/helpers.js:74:18)
                                    [WebServer]     at Object.requireFontManifest (/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/require.js:51:26)
                                    [WebServer]     at new Server (/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/next-server.js:105:81)
                                    [WebServer]     at NextServer.createServer (/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/next.js:107:16)
                                    [WebServer]     at async /codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/next.js:119:31 {
                                    [WebServer]   code: 'MODULE_NOT_FOUND',
                                    [WebServer]   requireStack: [
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/require.js',
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/load-components.js',
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/api-utils.js',
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/next-server.js',
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/next.js',
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/server/lib/start-server.js',
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/cli/next-start.js',
                                    [WebServer]     '/codebuild/output/src391212811/src/forms_frontend/node_modules/next/dist/bin/next'
                                    [WebServer]   ]
                                    [WebServer] }
2021-11-19T13:25:45.359Z [WARNING]: [WebServer] error Command failed with exit code 1.
2021-11-19T13:25:47.060Z [INFO]: F
2021-11-19T13:25:47.065Z [INFO]: 
2021-11-19T13:25:47.066Z [INFO]: 
2021-11-19T13:25:47.068Z [INFO]: 1) [Desktop Chrome] › firstStep.spec.ts:4:1 › form asseverazioni =================================
                                 page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:3000/preventivo/assicurazione-asseverazioni
                                 =========================== logs ===========================
                                 navigating to "http://localhost:3000/preventivo/assicurazione-asseverazioni", waiting until "load"
                                 ============================================================
                                 4 | test('form asseverazioni', async ({ page }) => {
                                 5 |   // Start from the index page (the baseURL is set via the webServer in the playwright.config.ts)
                                 > 6 |   await page.goto('/preventivo/assicurazione-asseverazioni', { waitUntil: 'load' })
                                 |              ^
                                 7 |   await muiSelect(page, '[data-test="numeroAsseverazioni"]', '[data-value="1"]')
                                 8 |   await muiSelect(page, '[data-test="massimaleRCRichiesto"]', '[data-value="500000"]')
                                 9 |   await page.click('input[name="sinistri"][value="no"]')
                                 at /codebuild/output/src391212811/src/forms_frontend/e2e/firstStep.spec.ts:6:14
                                 attachment #1: trace (application/zip) ---------------------------------------------------------
                                 test-results/firstStep-form-asseverazioni-Desktop-Chrome/trace.zip
                                 Usage:
                                 npx playwright show-trace test-results/firstStep-form-asseverazioni-Desktop-Chrome/trace.zip
                                 ------------------------------------------------------------------------------------------------
2021-11-19T13:25:47.068Z [INFO]: 1 failed
                                 [Desktop Chrome] › firstStep.spec.ts:4:1 › form asseverazioni ==================================
2021-11-19T13:25:47.082Z [WARNING]: error Command failed with exit code 1.
```

**Comment by JoelEinbinder** [comment]
You have an error in your webserver: `Error: Cannot find module' /codebuild/output/src391212811/src/forms_frontend/.next/server/font-manifest.json'` that has nothing to do with Playwright. I am not sure how to help here.
