### ISSUE TITLE
[BUG] page.screenshot can not execution in Docker

### ISSUE THREAD

**Issue by vctqs1** [microsoft/playwright#10460]
**Context:**
- Playwright Version: mcr.microsoft.com/playwright:v1.13.0-focal
- Operating System: Linux 20.04 LTS
- Node.js version: v14.17.2
- Browser: Chromium

**Code Snippet**

```javascript  
const browser = await chromium.launch({
        headless: true,
        timeout: 30000,
        channel: 'chrome',
        args: [
            '--use-fake-ui-for-media-stream',
            '--use-fake-device-for-media-stream',
            '--unlimited-storage',
            '--full-memory-crash-report',
            '--disable-dev-shm-usage', //[Chrome to crash when rendering large pages](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#tips)
        ],
    });
 const context: BrowserContext = await browser.newContext(contextOptions);
        this.context = context;
        await this.startTraceViewer();
        const page: Page = await context.newPage();

        await this.waitForConnection(this.origin);
        await page.goto(this.origin, {
            waitUntil: 'networkidle',
            timeout: options.timeout, //match with timeout in hook steps
        });

 this.page = page;

await this.page!.screenshot({
       quality: 50,
       type: 'jpeg',
});
```

**Describe the bug**
Everything works well in normal mode, but when I ran it in Docker. page.screenshot can not execution
``` page.screenshot: Timeout 10000ms exceeded.
cucumber       |     at CMS.attachScreenshot (/eibanam/drivers/abstract-driver/abstract-driver.ts:227:43)
cucumber       |     at CMS.instructionDriver (/eibanam/drivers/abstract-driver/abstract-driver.ts:213:24)
cucumber       |     at CMS.instruction (/eibanam/supports/cms-world.ts:591:16)
cucumber       |     at MasterWorld.<anonymous> (/eibanam/step-definitions/credential-account-steps.ts:46:9) ***
cucumber       |   name: 'TimeoutError'
```

This message only appears from last week, without any changes

**Comment by vctqs1** [comment]
same issue here https://github.com/microsoft/playwright/issues/9756

**Comment by vctqs1** [comment]
Still get same issue when update to `FROM mcr.microsoft.com/playwright:v1.16.3-focal`

**Comment by yury-s** [comment]
Thanks for the report! It does look like there is a real bug here, but it is very hard to understand what's going on. The exception you reference is not from Playwright code. Please reopen this bug or file a new one with a repro that we can run locally, otherwise

**Comment by vctqs1** [comment]
@yury-s 
> The exception you reference is not from Playwright code
```
page.screenshot: Timeout 10000ms exceeded.
cucumber       |     at CMS.attachScreenshot (/eibanam/drivers/abstract-driver/abstract-driver.ts:227:43)
cucumber       |     at CMS.instructionDriver (/eibanam/drivers/abstract-driver/abstract-driver.ts:213:24)
cucumber       |     at CMS.instruction (/eibanam/supports/cms-world.ts:591:16)
cucumber       |     at MasterWorld.<anonymous> (/eibanam/step-definitions/credential-account-steps.ts:46:9) ***
cucumber       |   name: 'TimeoutError'
```

This message from playwright, I integrate playwright in cucumber job

**Comment by vctqs1** [comment]
I just downgrade to 1.16.2, fixed

**Comment by scinos** [comment]
I'm seeing the same when running Playwright 1.17.1 + chromium v939194 inside Docker:


## Screenshots

It fails with a timeout when calling `await page.screenshot( { path: fileName } );`. There is no stack trace, only a timeout.

Enabling `DEBUG=pw:*` shows

```
2021-12-03T14:23:38.352Z pw:api => page.screenshot started
2021-12-03T14:23:38.353Z pw:protocol SEND ► {"id":214,"method":"Page.getLayoutMetrics","sessionId":"F47C8CD2B3BDDA99CA745D034F3BE429"}
2021-12-03T14:23:38.354Z pw:protocol ◀ RECV {"id":214,"result":{"layoutViewport":{"pageX":0,"pageY":0,"clientWidth":1280,"clientHeight":720},"visualViewport":{"offsetX":0,"offsetY":0,"pageX":0,"pageY":0,"clientWidth":1280,"clientHeight":720,"scale":1,"zoom":1},"contentSize":{"x":0,"y":0,"width":1280,"height":1829},"cssLayoutViewport":{"pageX":0,"pageY":0,"clientWidth":1280,"clientHeight":720},"cssVisualViewport":{"offsetX":0,"offsetY":0,"pageX":0,"pageY":0,"clientWidth":1280,"clientHeight":720,"scale":1,"zoom":1},"cssContentSize":{"x":0,"y":0,"width":1280,"height":1829}},"sessionId":"F47C8CD2B3BDDA99CA745D034F3BE429"}
2021-12-03T14:23:38.354Z pw:protocol SEND ► {"id":215,"method":"Page.captureScreenshot","params":{"format":"png","clip":{"x":0,"y":0,"width":1280,"height":720,"scale":1}},"sessionId":"F47C8CD2B3BDDA99CA745D034F3BE429"}
2021-12-03T14:24:08.352Z pw:api <= page.screenshot failed
```

(note: there are a bunch of `RECV` that I removed from the log because I believe they belong to the requests that were in flight. I can add them back if required).

## Videos

When calling `await page.video()?.saveAs( destination );` it throws an error:

```
21:47:58       Trace: Error: Page did not produce any video frames
21:47:58           at Video.saveAs (/home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/playwright-core/lib/client/video.js:47:26)
21:47:58           at /home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/hooks.ts:98:5
21:47:58           at /home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/packages/calypso-e2e/src/hooks.ts:101:13
```

## Workarounds

Seems that either Playwright 1.17.1 + chrome and Playwright 1.16.3 + chromium work as expected.
