### ISSUE TITLE
[BUG] Test failing in AfterHook stage (tracing.stopChunk)

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#10473]
**Context:**
- Playwright Version: 1.17.0-rc1
- Operating System: Mac
- Node.js version: 12.22
- Browser: All

**Code Snippet**

```javascript
browserContext.close: tracing.stopChunk: file data stream has unexpected number of bytes
```

**Describe the bug**
All the steps in the test are passing but After Hook is failing with the above error. Seems to be intermittent.

Logs from `pw:api`:

```javascript
 pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +361ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +9ms
  pw:api => browserContext.newPage started +1ms
  pw:api <= browserContext.newPage succeeded +117ms
  pw:api => page.goto started +1ms
  pw:api navigating to "URL", waiting until "load" +4ms
  pw:api   "commit" event fired +5s
  pw:api   navigated to "URL" +0ms
  pw:api   "commit" event fired +702ms
  pw:api   navigated to "about:blank" +0ms
  pw:api   "domcontentloaded" event fired +96ms
  pw:api   "commit" event fired +388ms
  pw:api   navigated to "https://us.tags.newscgp.com/prod/ncg/cookie.html" +0ms
  pw:api   "domcontentloaded" event fired +4ms
  pw:api   "domcontentloaded" event fired +12ms
  pw:api   "commit" event fired +63ms
  pw:api   navigated to "https://98de967663ce39464bb2dcc174468312.safeframe.googlesyndication.com/safeframe/1-0-38/html/container.html" +1ms
  pw:api   "commit" event fired +4ms
  pw:api   navigated to "https://98de967663ce39464bb2dcc174468312.safeframe.googlesyndication.com/safeframe/1-0-38/html/container.html" +0ms
  pw:api   "commit" event fired +6ms
  pw:api   navigated to "https://98de967663ce39464bb2dcc174468312.safeframe.googlesyndication.com/safeframe/1-0-38/html/container.html" +0ms
  pw:api   "commit" event fired +89ms
  pw:api   navigated to "https://www.ncaudienceexchange.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +14ms
  pw:api   navigated to "https://tags.mansionglobal.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +19ms
  pw:api   navigated to "https://tags.barrons.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +3ms
  pw:api   navigated to "https://tags.wsj.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +9ms
  pw:api   navigated to "https://tags.nypost.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +3ms
  pw:api   navigated to "https://tags.decider.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +4ms
  pw:api   navigated to "https://tags.pagesix.com/prod/ncg/cookie.html" +1ms
  pw:api   "commit" event fired +7ms
  pw:api   navigated to "https://tags.penews.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +7ms
  pw:api   navigated to "https://tags.marketwatch.com/prod/ncg/cookie.html" +0ms
  pw:api   "commit" event fired +7ms
  pw:api   navigated to "https://tags.knewz.com/prod/ncg/cookie.html" +0ms
  pw:api   "domcontentloaded" event fired +272ms
  pw:api   "commit" event fired +398ms
  pw:api   navigated to "about:blank" +0ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "commit" event fired +7ms
  pw:api   navigated to "about:blank" +0ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "load" event fired +721ms
  pw:api <= page.goto succeeded +64ms
  pw:api => page.waitForResponse started +1ms
  pw:api => browserContext.close started +2ms
  pw:api <= page.waitForResponse succeeded +24ms
  pw:api <= browserContext.close failed +135ms
```

**Comment by dgozman** [comment]
@Nav-2d What browser do you run? Is this browser-specific?

**Comment by Nav-2d** [comment]
@dgozman - So far experienced on chromium, webkit, iphone12, pixel5.

**Comment by Nav-2d** [comment]
```javascript
at /Users/test/Desktop/Demo/play_demo/node_modules/@playwright/test/lib/index.js:392:21
at Object._contextFactory [as fn] (/Users/test/Desktop/Demo/play_demo/node_modules/@playwright/test/lib/index.js:391:44)
at Fixture.teardown (/Users/test/Desktop/Demo/play_demo/node_modules/@playwright/test/lib/fixtures.js:101:7)
at FixtureRunner.teardownScope (/Users/test/Desktop/Demo/play_demo/node_modules/@playwright/test/lib/fixtures.js:272:11)
at WorkerRunner._runAfterHooks (/Users/test/Desktop/Demo/play_demo/node_modules/@playwright/test/lib/workerRunner.js:538:7)
```
Console trace (if it helps in any way)
