### ISSUE TITLE
[BUG] Firefox emitting console event for unhandled errors

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/playwright#10565]
**Context:**
- Playwright Version: 1.16.3, 1.18.0-alpha-nov-28-2021
- Operating System: Windows 11, Ubuntu 21.04
- Node.js version: 14.18.0 on Windows, 16.13.0 on Linux
- Browser: Firefox 93.0, Firefox 94.0.1
- Extra: Tested both versions on both Windows and Ubuntu (WSL)

**Code Snippet**

```javascript
const playwright = require('playwright');

const highlight = (text) => `\x1b[7m${text}\x1b[0m`;
const red = (text) => `\x1b[41m${text}\x1b[0m`;

['chromium', 'firefox', 'webkit'].reduce(async (last, browserName) => {
  await last;
  console.log(`=== test start ${browserName} ===`);

  const browser = await playwright[browserName].launch();
  const page = await browser.newPage();
  page.on('console', (message) => {
    console.log(red('console event'), message.text());
  });
  page.on('pageerror', (error) => {
    console.log(highlight('pageerror event'), error);
  });

  await page.addScriptTag({
    content: 'throw new Error();',
  });
  await browser.close();

  console.log(`=== test end ${browserName} ===`);
}, Promise.resolve());
```

**Describe the bug**

Running the snippet produces

```log
=== test start chromium ===
pageerror event Error
    at <anonymous>:1:7
    at addScriptContent (eval at evaluate (:3:2389), <anonymous>:9:21)
    at t.default.evaluate (<anonymous>:3:2412)
    at t.default.<anonymous> (<anonymous>:1:44)
=== test end chromium ===
=== test start firefox ===
pageerror event Error:
    at  (about:blank line 9 > injectedScript:1:7)
    at addScriptContent (debugger eval code line 3 > eval:9:21)
    at evaluate (debugger eval code:3:2412)
    at  (debugger eval code:1:44)
    at evaluateFunction (chrome://juggler/content/content/Runtime.js:381:60)
    at callFunction (chrome://juggler/content/content/Runtime.js:103:41)
    at _onMessage (chrome://juggler/content/SimpleChannel.js:165:37)
    at receiveMessage (chrome://juggler/content/SimpleChannel.js:16:42)
console event [JavaScript Error: "Error: " {file: "about:blank line 9 > injectedScript" line: 1}]
@about:blank line 9 > injectedScript:1:7
addScriptContent@debugger eval code line 3 > eval:9:21
evaluate@debugger eval code:3:2412
@debugger eval code:1:44

=== test end firefox ===
=== test start webkit ===
pageerror event Error
    at global code (about:blank:1:18)
    at appendChild ([native code]:0:0)
    at addScriptContent (:9:32)
    at evaluate (:3:2413)
    at unknown (:1:52)
    at callFunctionOn (:42:22)
=== test end webkit ===
```

Firefox emits a console event for the unhandled error while chromium and webkit not.

I'm writing a lib that handles the browser console on the node side and this makes it hard to handle every message exactly once on Firefox. 😕

**Comment by mxschmitt** [comment]
Seems you were hit by this test which is marked as failing:

https://github.com/microsoft/playwright/blob/cd22072685ee2c043a1955bc6b4b57e684565131/tests/page/page-event-pageerror.spec.ts#L49-L58

cc @pavelfeldman who was working on this back then.
