### ISSUE TITLE
[BUG] Tests failing inside Gitlab-runner that works locally

### ISSUE THREAD

**Issue by marian100521** [microsoft/playwright#10583]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Ubuntu / Gitlab-runner
- Node.js version: v14.18.1
- Browser: Electron
- Extra: Electron-Angular-Rust

I've built a Angular-Electron-Rust project based on that repo:
https://github.com/hawkeye2013/angular-rust-electron

I'd like to e2e test the flow of my app. I started to work with Spectron, but I wasn't able to run the tests there properly. 
Then I've found that tutorial: 

https://blog.dangl.me/archive/running-fully-automated-e2e-tests-in-electron-in-a-docker-container-with-playwright/

So, I've copied the way it is running the Electron e2e test, since Spectron wasn't able to do it. 
In my local machine the test are running like a charm:

```
import { BrowserContext, ElectronApplication, Page, _electron as electron } from 'playwright';
import { test, expect } from '@playwright/test';
import * as path from 'path';

test('Launch electron app', async () => {
    const electronApp = await electron.launch({ args: ['--disable_splash_screen', path.join(__dirname, '../')] });
    const windowState: { isVisible: boolean; isDevToolsOpened: boolean; isCrashed: boolean; } = await electronApp.evaluate(async ({ BrowserWindow }) => {
        const mainWindow = BrowserWindow.getAllWindows()[0];

        const getState = () => ({
            isVisible: mainWindow.isVisible(),
            isDevToolsOpened: mainWindow.webContents.isDevToolsOpened(),
            isCrashed: mainWindow.webContents.isCrashed(),
        });

        return new Promise((resolve) => {
            if (mainWindow.isVisible()) {
                resolve(getState());
            } else {
                mainWindow.once('ready-to-show', () => setTimeout(() => resolve(getState()), 0));
            }
        });
    });

    expect(windowState.isVisible).toBeTruthy();
    expect(windowState.isDevToolsOpened).toBeFalsy();
    expect(windowState.isCrashed).toBeFalsy();

    await electronApp.close();
});

test.describe('Check Man Page', async () => {
    let electronApp: ElectronApplication;
    let firstWindow: Page;
    let context: BrowserContext;

    test.beforeAll(async () => {electronApp = await electron.launch({ args: ['--disable_splash_screen', path.join(__dirname, '../')] });
        context = electronApp.context();
        await context.tracing.start({ screenshots: true, snapshots: true });
        firstWindow = await electronApp.firstWindow();
    })

    test('Check title', async () => {
        const title = await firstWindow.title();
        const filePath = path.join(
            __dirname,
            "..",
            "src-exe",
            "log",
            "native",
            "resources",
            "file.log"
        );
        let fileName = "file.log";

        const pageContext = await firstWindow.context();
        const browserWindowHandle = await electronApp.browserWindow(firstWindow);

            const frameName = await browserWindowHandle.evaluateHandle(({ BrowserWindow, webContents }, filePath) => {
                let fileName = "file.log";
                return webContents.send("load-log-binary", filePath, fileName);
              }, filePath);

              const mainTitle = firstWindow.locator('[data-qa-col="1"]');
              const tres = await mainTitle.count();

              await firstWindow.waitForLoadState()
              await expect(tres).toBe(1);
    });

    test.afterAll(async () => {
        await electronApp.close();
    })
})

```

I debbuged the code both in Gitlab-runner and docker locally.

The result of the local docker is that one: 

```
WARNING in 

2021-11-29T11:47:14.090Z pw:api => electron.launch started
2021-11-29T11:47:14.567Z pw:api   navigated to "file:///app/src/dist/index.html"
2021-11-29T11:47:14.572Z pw:api <= electron.launch succeeded
2021-11-29T11:47:14.572Z pw:api => electronApplication.evaluate started
2021-11-29T11:47:14.578Z pw:api <= electronApplication.evaluate succeeded
2021-11-29T11:47:14.582Z pw:api => electronApplication.close started
2021-11-29T11:47:14.602Z pw:api <= electronApplication.close succeeded
  ✓  playruste2e.spec.ts:5:1 › Launch electron app (518ms)
2021-11-29T11:47:14.603Z pw:api => electron.launch started
2021-11-29T11:47:14.944Z pw:api   navigated to "file:///app/src/dist/index.html"
2021-11-29T11:47:14.946Z pw:api <= electron.launch succeeded
2021-11-29T11:47:14.947Z pw:api => tracing.start started
2021-11-29T11:47:15.112Z pw:api <= tracing.start succeeded
2021-11-29T11:47:15.112Z pw:api => electronApplication.firstWindow started
2021-11-29T11:47:15.112Z pw:api <= electronApplication.firstWindow succeeded
2021-11-29T11:47:15.113Z pw:api => page.title started
2021-11-29T11:47:15.195Z pw:api   "domcontentloaded" event fired
2021-11-29T11:47:15.208Z pw:api   navigated to "file:///app/src/dist/"
2021-11-29T11:47:15.220Z pw:api <= page.title succeeded
2021-11-29T11:47:15.220Z pw:api => electronApplication.browserWindow started
2021-11-29T11:47:15.223Z pw:api <= electronApplication.browserWindow succeeded
2021-11-29T11:47:15.223Z pw:api => jSHandle.evaluateHandle started
2021-11-29T11:47:15.225Z pw:api <= jSHandle.evaluateHandle succeeded
2021-11-29T11:47:15.225Z pw:api => locator.count started
2021-11-29T11:47:15.522Z pw:api <= locator.count succeeded
2021-11-29T11:47:15.522Z pw:api => page.waitForLoadState started
2021-11-29T11:47:15.571Z pw:api   "load" event fired
2021-11-29T11:47:15.572Z pw:api <= page.waitForLoadState succeeded
  ✓  playruste2e.spec.ts:47:5 › Check Man Page › Check title (461ms)
2021-11-29T11:47:15.573Z pw:api => electronApplication.close started
2021-11-29T11:47:15.573Z pw:api   "load" event fired
2021-11-29T11:47:15.593Z pw:api <= electronApplication.close succeeded
```

The problem comes when I run the test suite inside Gitlab-runner. 
I'm using exactly the same workflow:
https://blog.dangl.me/archive/running-fully-automated-e2e-tests-in-electron-in-a-docker-container-with-playwright/

And I have that log in the Gitlab-Runner execution: 

```
2021-11-29T11:25:35.928Z pw:api => electron.launch started
2021-11-29T11:25:41.334Z pw:api   navigated to "file:///app/src/dist/index.html"
2021-11-29T11:25:41.341Z pw:api <= electron.launch succeeded
2021-11-29T11:25:41.342Z pw:api => electronApplication.evaluate started
2021-11-29T11:25:41.351Z pw:api <= electronApplication.evaluate succeeded
2021-11-29T11:25:41.356Z pw:api => electronApplication.close started
2021-11-29T11:25:41.412Z pw:api <= electronApplication.close succeeded
  ✓  playruste2e.spec.ts:5:1 › Launch electron app (5s)
2021-11-29T11:25:41.420Z pw:api => electron.launch started
2021-11-29T11:25:42.363Z pw:api   navigated to "file:///app/src/dist/index.html"
2021-11-29T11:25:42.366Z pw:api <= electron.launch succeeded
2021-11-29T11:25:42.367Z pw:api => tracing.start started
2021-11-29T11:25:42.556Z pw:api <= tracing.start succeeded
2021-11-29T11:25:42.558Z pw:api => electronApplication.firstWindow started
2021-11-29T11:25:42.561Z pw:api <= electronApplication.firstWindow succeeded
2021-11-29T11:25:42.569Z pw:api => page.title started
2021-11-29T11:25:42.761Z pw:api   "domcontentloaded" event fired
2021-11-29T11:25:42.830Z pw:api <= page.title succeeded
2021-11-29T11:25:42.831Z pw:api => electronApplication.browserWindow started
2021-11-29T11:25:42.842Z pw:api <= electronApplication.browserWindow succeeded
2021-11-29T11:25:42.844Z pw:api => jSHandle.evaluateHandle started
2021-11-29T11:25:42.849Z pw:api <= jSHandle.evaluateHandle succeeded
2021-11-29T11:25:42.851Z pw:api => locator.count started
2021-11-29T11:25:42.861Z pw:api   navigated to "file:///app/src/dist/"
2021-11-29T11:25:42.875Z pw:api   "load" event fired
2021-11-29T11:25:43.375Z pw:api   "networkidle" event fired
2021-11-29T11:28:12.665Z pw:api => electronApplication.close started
  ✘  playruste2e.spec.ts:47:5 › Check Man Page › Check title (3m)
TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (/app/src/node_modules/playwright-core/lib/server/progress.js:96:26)
    at ElectronApplication.close (/app/src/node_modules/playwright-core/lib/server/electron/electron.js:103:39)
    at ElectronApplicationDispatcher.close (/app/src/node_modules/playwright-core/lib/dispatchers/electronDispatcher.js:88:24)
    at DispatcherConnection.dispatch (/app/src/node_modules/playwright-core/lib/dispatchers/dispatcher.js:350:46)
2021-11-29T11:30:43.261Z pw:api => electron.launch started
2021-11-29T11:30:44.048Z pw:api   navigated to "file:///app/src/dist/index.html"
2021-11-29T11:30:44.078Z pw:api <= electron.launch succeeded
2021-11-29T11:30:44.091Z pw:api => tracing.start started
2021-11-29T11:30:44.261Z pw:api <= tracing.start succeeded
2021-11-29T11:30:44.262Z pw:api => electronApplication.firstWindow started
2021-11-29T11:30:44.263Z pw:api <= electronApplication.firstWindow succeeded
2021-11-29T11:30:44.268Z pw:api => page.title started
2021-11-29T11:30:44.401Z pw:api   "domcontentloaded" event fired
2021-11-29T11:30:44.483Z pw:api   navigated to "file:///app/src/dist/"
2021-11-29T11:30:44.486Z pw:api <= page.title succeeded
2021-11-29T11:30:44.487Z pw:api => electronApplication.browserWindow started
2021-11-29T11:30:44.490Z pw:api <= electronApplication.browserWindow succeeded
2021-11-29T11:30:44.491Z pw:api => jSHandle.evaluateHandle started
2021-11-29T11:30:44.499Z pw:api <= jSHandle.evaluateHandle succeeded
2021-11-29T11:30:44.501Z pw:api => locator.count started
2021-11-29T11:30:44.526Z pw:api   "load" event fired
2021-11-29T11:30:44.973Z pw:api   "networkidle" event fired
2021-11-29T11:33:14.367Z pw:api => electronApplication.close started
  ✘  playruste2e.spec.ts:47:5 › Check Man Page › Check title (3m)
TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (/app/src/node_modules/playwright-core/lib/server/progress.js:96:26)
    at ElectronApplication.close (/app/src/node_modules/playwright-core/lib/server/electron/electron.js:103:39)
    at ElectronApplicationDispatcher.close (/app/src/node_modules/playwright-core/lib/dispatchers/electronDispatcher.js:88:24)
    at DispatcherConnection.dispatch (/app/src/node_modules/playwright-core/lib/dispatchers/dispatcher.js:350:46)
  1) playruste2e.spec.ts:47:5 › Check Man Page › Check title =======================================
    Timeout of 150000ms exceeded.
--- Test output ------------------------------------------------------------------------------------
2021-11-29T11:25:42.569Z pw:api => page.title started
2021-11-29T11:25:42.761Z pw:api   "domcontentloaded" event fired
2021-11-29T11:25:42.830Z pw:api <= page.title succeeded
2021-11-29T11:25:42.831Z pw:api => electronApplication.browserWindow started
2021-11-29T11:25:42.842Z pw:api <= electronApplication.browserWindow succeeded
2021-11-29T11:25:42.844Z pw:api => jSHandle.evaluateHandle started
2021-11-29T11:25:42.849Z pw:api <= jSHandle.evaluateHandle succeeded
2021-11-29T11:25:42.851Z pw:api => locator.count started
2021-11-29T11:25:42.861Z pw:api   navigated to "file:///app/src/dist/"
2021-11-29T11:25:42.875Z pw:api   "load" event fired
2021-11-29T11:25:43.375Z pw:api   "networkidle" event fired
----------------------------------------------------------------------------------------------------
    Retry #1 ---------------------------------------------------------------------------------------
    Timeout of 150000ms exceeded.
--- Test output ------------------------------------------------------------------------------------
2021-11-29T11:30:44.268Z pw:api => page.title started
2021-11-29T11:30:44.401Z pw:api   "domcontentloaded" event fired
2021-11-29T11:30:44.483Z pw:api   navigated to "file:///app/src/dist/"
2021-11-29T11:30:44.486Z pw:api <= page.title succeeded
2021-11-29T11:30:44.487Z pw:api => electronApplication.browserWindow started
2021-11-29T11:30:44.490Z pw:api <= electronApplication.browserWindow succeeded
2021-11-29T11:30:44.491Z pw:api => jSHandle.evaluateHandle started
2021-11-29T11:30:44.499Z pw:api <= jSHandle.evaluateHandle succeeded
2021-11-29T11:30:44.501Z pw:api => locator.count started
2021-11-29T11:30:44.526Z pw:api   "load" event fired
2021-11-29T11:30:44.973Z pw:api   "networkidle" event fired
----------------------------------------------------------------------------------------------------
  Slow test: playruste2e.spec.ts (5m)
  1 failed
    playruste2e.spec.ts:47:5 › Check Man Page › Check title ========================================
  1 passed (10m)
```

It is giving the timeout here: 

```
            const frameName = await browserWindowHandle.evaluateHandle(({ BrowserWindow, webContents }, filePath) => {
                let fileName = "file.log";
                return webContents.send("load-log-binary", filePath, fileName);
              }, filePath);

```

In that part I'm sending the file, and it's been processed by Electron/Rust. 
I think it is not relevant what's going on there, since it's been successful in my local machine, that I'm running with the exact same docker image: 
 
```
docker run -v /app/src/:/app/src \
  --rm \
  --privileged my-e2e-image:dev \
  sh -c "cd /app/src/ && \
    rm -rf node_modules && \
    mkdir node_modules && \
    mount -t tmpfs -o rw,size=5G tmpfs node_modules && \
    rm -rf dist && \
    mkdir dist && \
    mount -t tmpfs -o rw,size=1G tmpfs dist && \
    npm install --no-progress && \
    npm run e2e:docker"
```

The image is being built following that: 

https://gist.githubusercontent.com/GeorgDangl/f2d65986085da494020edf07a5a6b96f/raw/7faf636b9c67e8db36d233ff7edba4d6a5eace28/Dockerfile

It's using that Entrypoint.sh:

https://gist.githubusercontent.com/GeorgDangl/f2d65986085da494020edf07a5a6b96f/raw/7faf636b9c67e8db36d233ff7edba4d6a5eace28/entrypoint.sh

Reading some related issues I added: 

```
              await firstWindow.waitForLoadState()
```

But nothing happens. 

I don't know If that particular error could give a clue to solve my issue: 

```
  ✘  playruste2e.spec.ts:47:5 › Check Man Page › Check title (3m)
TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (/app/src/node_modules/playwright-core/lib/server/progress.js:96:26)
    at ElectronApplication.close (/app/src/node_modules/playwright-core/lib/server/electron/electron.js:103:39)
    at ElectronApplicationDispatcher.close (/app/src/node_modules/playwright-core/lib/dispatchers/electronDispatcher.js:88:24)
    at DispatcherConnection.dispatch (/app/src/node_modules/playwright-core/lib/dispatchers/dispatcher.js:350:46)
  1) playruste2e.spec.ts:47:5 › Check Man Page › Check title =======================================
    Timeout of 150000ms exceeded.
--- Test output ---------------------------------------------------------
```

Both executions are using exactly the same Docker image, with the same Node and Playwright version.

Thanks in advance.

**Comment by pavelfeldman** [comment]
Your reproduction scenario is too big for us to recreate. If you have a small repro script we can try locally, please include it here, otherwise it is unlikely that we can help.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
