### ISSUE TITLE
[BUG] Browserstack integration (via playwright.chromium.connect) throws an error in 1.17.0

### ISSUE THREAD

**Issue by flunderpero** [microsoft/playwright#10613]
**Context:**
- Playwright Version: 1.17.0
## System:
 - OS: macOS 12.0.1
 - Memory: 7.47 GB / 64.00 GB
## Binaries:
 - Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
 - Yarn: 1.22.17 - /opt/homebrew/bin/yarn
 - npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

1.17.0 (has maybe a backwards compatibility bug when used with `playwright.chromium.connect` as the [Browserstack integration](https://www.browserstack.com/docs/automate/playwright) does. 1.16.3 was fine.

Basically we use `playwright.chromium.connect` to obtain a `Browser` instance and use this is our tests:
```
 const bs_browser = await playwright.chromium.connect(
     `wss://cdp.browserstack.com/playwright?caps=` +
     `${encodeURIComponent(JSON.stringify(caps))}`,
)
```

I get this error:
```
Playwright: Connection dispatch error
TypeError: Cannot read property '_object' of undefined
    at Function.from (/Users/pero/src/pero/cling-main/node_modules/playwright-core/lib/client/fetch.js:54:20)
    at new BrowserContext (/Users/pero/src/pero/cling-main/node_modules/playwright-core/lib/client/browserContext.js:97:45)
    at Connection._createRemoteObject (/Users/pero/src/pero/cling-main/node_modules/playwright-core/lib/client/connection.js:274:18)
    at Connection.dispatch (/Users/pero/src/pero/cling-main/node_modules/playwright-core/lib/client/connection.js:189:12)
    at Proxy.<anonymous> (/Users/pero/src/pero/cling-main/node_modules/playwright-core/lib/client/browserType.js:182:22)
    at Proxy.emit (node:events:369:20)
    at Proxy.emit (node:domain:470:12)
    at Connection.dispatch (/Users/pero/src/pero/cling-main/node_modules/playwright-core/lib/client/connection.js:208:21)
    at Immediate._onImmediate (/Users/pero/src/pero/cling-main/node_modules/playwright-core/lib/inProcessFactory.js:50:83)
    at processImmediate (node:internal/timers:464:21)
```

**Comment by pavelfeldman** [comment]
There is no backwards compatibility in connect(). You need a new server to use a new client. You should file this against BrowserStack, it could be that they didn't match your client version.

**Comment by flunderpero** [comment]
Ok, I'll get in touch with Browserstack then. According to their UI they are using Playwright 1.14.1 which worked up until Playwright 1.16.2 (we did not use 1.16.3).
The error message and stack trace do not scream "incompatible server" to me, that's why I filed this issue.

**Comment by flunderpero** [comment]
Just a quick note: It is working again.
