### ISSUE TITLE
[BUG] Page.adoptNode: Cannot find object with id 

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1065]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Windows
- Extra: Firefox

**Describe the bug**

What does this error mean?

```
Protocol error (Page.adoptNode): Cannot find object with id = id-14
    unsafeObject@chrome://juggler/content/content/PageAgent.js:101:11
    adoptNode@chrome://juggler/content/content/PageAgent.js:513:53
    handleMessage@chrome://juggler/content/content/ContentSession.js:47:36
    _onMessage@chrome://juggler/content/content/ContentSession.js:55:33
     _onMessage@chrome://juggler/content/protocol/Dispatcher.js:249:16
    receiveMessage@chrome://juggler/content/protocol/Dispatcher.js:205:41

      37 |   logger.verbose("selectElement: element.select");
      38 | 
    > 39 |   await elementHandle.select(value || "");
         |                       ^
      40 | };
      41 | 

      at ../../browser/node_modules/playwright-core/lib/firefox/ffConnection.js:147:63
      at FFSession.send (../../browser/node_modules/playwright-core/lib/firefox/ffConnection.js:146:16)
      at FFPage.adoptElementHandle (../../browser/node_modules/playwright-core/lib/firefox/ffPage.js:357:44)
      at ../../browser/node_modules/playwright-core/lib/dom.js:41:56
          at Array.map (<anonymous>)
      at FrameExecutionContext._evaluate (../../browser/node_modules/playwright-core/lib/dom.js:38:48)
      at FrameExecutionContext.ExecutionContext.evaluate (../../browser/node_modules/playwright-core/lib/javascript.js:21:25)
      at ElementHandle._evaluateInUtility (../../browser/node_modules/playwright-core/lib/dom.js:107:28)
        -- ASYNC --
      at ElementHandle.<anonymous> (../../browser/node_modules/playwright-core/lib/helper.js:54:23)
      at ../../browser/src/actions/selectElement.ts:39:23
      at fulfilled (../../browser/lib/actions/selectElement.js:5:58)
```

I am getting it [randomly on Firefox Windows](https://github.com/qawolf/qawolf/commit/a94b859965760bcea3a05cd7a06bc942db116a04/checks?check_suite_id=468618332) when trying to call `elementHandle.select`. Should I automatically retry when I get this error?

**Comment by dgozman** [comment]
This could happen when the execution context is gone (e.g. frame has navigated away) at the time you call `elementHandle.select`. The error is not descriptive enough though 😄 Do you have a repro?

**Comment by jperl** [comment]
Ok nvm, this error is expected since page navigations might occur from when we load the element and interact with it. Thanks for the explanation.

**Comment by jperl** [comment]
That all being said I think it would be intuitive for the element handle to automatically retry this sort of error. It could store the original selector, and auto retry to load it similar to the API we are working on https://github.com/qawolf/qawolf/issues/432
