### ISSUE TITLE
[Question] How to inherit multiple pages/contexts among fixtures and tests?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#10676]
Hi, 

I have a test with multiple chained fixtures that run before the test execution. What I want to do is to execute the operations of these fixtures (and finally, of the test) on two pages belonging to two different contexts, one persistent and the other in incognito-mode.

Let's say the first fixture is doing a login operation with two different accounts, which I'd like to be done in these two different context:

```
//login.ts
import { test as base } from '@playwright/test';
import { chromium } from 'playwright';

type LoggedInTestFixtures = {
    loggedIn: string;
    loggedIn2: string;
    signinUrl: string;
    username: string;
    password: string;
    username2: string;
    password2: string;
}

const test_login =  base.extend<LoggedInTestFixtures>({
    signinUrl: ({}, use, testInfo) => use(testInfo.config.projects[0].use['baseURL']),
    username: ({}, use) => use(*username*),
    password: ({}, use) => use(*password), 
    username2: ({}, use, testInfo) => use(testInfo.config.projects[0].use['usr']), //different account
    password2: ({}, use, testInfo) => use(testInfo.config.projects[0].use['pwd']), //different account
    loggedIn: async({signinUrl, username, password}, use) => {

        const context1 = await chromium.launchPersistentContext('C:\\Users\\admin\\AppData\\Local\\Temp',{headless: false});
        const page = await context1.newPage();
        await page.goto(signinUrl);
        // operations on page...
        }
        use(username);        

    },

    loggedIn2: async({signinUrl, username2, password2}, use) => {
        const browser2 = await chromium.launch({headless: false});
        const context2 = await browser2.newContext()
        const page = await context2.newPage();
        await page.goto(signinUrl);

       // operations on the other page....

        use(username2);        
    }

});

export default test_login;

```

Now, I have another fixtures which is linked to this one, for example:

```
// check_lang.ts
import { expect } from '@playwright/test';
import test_login  from '../FIXTURES/login'  

// Even if we don't have anything to express our feature, it's necessary to define at least one variable, at will.  
type CheckLangTestFixtures = {
    check_lang: void;
}

// If we want to make the language functionality depend from the login, we need to extend login fixture, writing "test_login.extend<....>""
const test_lang =  test_login.extend<CheckLangTestFixtures>({ 
    check_lang: async({*****page1, page2****,loggedIn ,loggedIn2}, use) => {

        // here I want to make operations on page1 and page2... how do I recall them?

        //We need to return at least something from the fixture, even "undefined", by using "use()"
        use();
    }
});

export default test_lang;
```

and so on and so forth for other fixture till I arrive to the final test... How can I recall the two pages to make different operation on them? Hope I made myself clear :)

**Comment by pavelfeldman** [comment]
- you don't need to launch browsers for different contexts, `browser.newContext()` is enough.
- `your loggedIn` and `loggedIn2` should be of type Page, so instead of *****page1 you'll use `loggedIn` page.
- don't forget context.close() after await use

**Comment by DvDream** [comment]
> * you don't need to launch browsers for different contexts, `browser.newContext()` is enough.

Even if my contexts are of different nature (persistent and incognito mode)?  I think you mean on loggedIn2 where I define browser2, don"t you? But if I write browser.newContext(), where's browser defined?

> * your `loggedIn` and `loggedIn2` should be of type Page, replace `use(username)` with `use(page)`. And instead of *****page1 you'll use `loggedIn` page.

Ok I will it and I will let you know!

> * don't forget `await context.close()` after `await use` in your fixtures

**Comment by DvDream** [comment]
> * you don't need to launch browsers for different contexts, `browser.newContext()` is enough.
> * your `loggedIn` and `loggedIn2` should be of type Page, replace `use(username)` with `use(page)`. And instead of *****page1 you'll use `loggedIn` page.
> * don't forget `await context.close()` after `await use` in your fixtures

Hi, some updates, I get this error now:

```
    TypeError: locator._expect is not a function

        at C:\Users\admin\Desktop\TEST_REPO\node_modules\@playwright\test\lib\matchers\matchers.js:249:28
        at Object.toMatchText (C:\Users\admin\Desktop\TEST_REPO\node_modules\@playwright\test\lib\matchers\toMatchText.js:58:13)
        at Object.toHaveText (C:\Users\admin\Desktop\TEST_REPO\node_modules\@playwright\test\lib\matchers\matchers.js:245:37)
        at Object.__PWTRAP__[expect.toHaveText] (C:\Users\admin\Desktop\TEST_REPO\node_modules\@playwright\test\lib\expect.js:142:30)
        at __EXTERNAL_MATCHER_TRAP__ (C:\Users\admin\Desktop\TEST_REPO\node_modules\expect\build\index.js:386:30)
        at Object.throwingMatcher [as toHaveText] (C:\Users\admin\Desktop\TEST_REPO\node_modules\expect\build\index.js:387:15)
        at Object.check_lang [as fn] (C:\Users\admin\Desktop\TEST_REPO\FIXTURES\check-lang.ts:28:40)
```

and my locator is the following: 

```
        const lang_locator = loggedIn.locator(':is(user-info-sidebar div ul > li h3:has-text("Lingua"),user-info-sidebar div ul > li h3:has-text("Language"))');

```

which before modifying the page fixture to the Page-typed loggedIn(/loggedIn2) was perfectly working, what can be the problem?

**Comment by DvDream** [comment]
Mybe I almost find a solution. I'm doing in this way:

```
//login.ts
import { test as base } from '@playwright/test';
import { Page } from '@playwright/test';

type LoggedInTestFixtures = {
    loggedIn: Page;
    loggedIn2: Page;
    signinUrl: string;
    username: string;
    password: string;
    username2: string;
    password2: string;
}

const test_login =  base.extend<LoggedInTestFixtures>({
    signinUrl: ({}, use, testInfo) => use(testInfo.config.projects[0].use['baseURL']),
    username: ({}, use) => use(*username*),
    password: ({}, use) => use(*password), 
    username2: ({}, use, testInfo) => use(testInfo.config.projects[0].use['usr']), //different account
    password2: ({}, use, testInfo) => use(testInfo.config.projects[0].use['pwd']), //different account
loggedIn: async({browser, signinUrl, username, password}, use) => {
        
const context1 = await browser.newContext();
        const page = await context1.newPage();
        await page.goto(signinUrl);

        // operations on page...
        }
        use(page);        

    },

loggedIn2: async({browser, signinUrl, username2, password2}, use) => {        

        const context2 = await browser.newContext()
        const page = await context2.newPage();
        await page.goto(signinUrl);

       // operations on the other page....

        use(page2);        
    }

});

export default test_login;
```

```
// check_lang.ts
import { expect } from '@playwright/test';
import test_login  from '../FIXTURES/login'  

// Even if we don't have anything to express our feature, it's necessary to define at least one variable, at will.  
type CheckLangTestFixtures = {
    check_lang: void;
}

// If we want to make the language functionality depend from the login, we need to extend login fixture, writing "test_login.extend<....>""
const test_lang =  test_login.extend<CheckLangTestFixtures>({ 
    check_lang: async({loggedIn ,loggedIn2}, use) => {
         loggedIn.click(....) // WORKS!
         loggedIn2.click(...) // WORKS!

        use();
    }
});

export default test_lang;
```
I figured out that I don't really need a persistent context for my use case (even if it could be good to try to configure it for future use cases), but now:

- I get two contexts opened but also a window with a blank page appears..and I don't understand why
- You said that I need to close my context a the end of each fixture, but in this way the windows get closed and the test fail

**Comment by dgozman** [comment]
> * I get two contexts opened but also a window with a blank page appears..and I don't understand why

Blank page is most likely the default `page` provided by the test runner. If your test or any fixture mentions `{ page }` in the first argument, test runner will create the default page. Remove it from the list if you do not use it, and the page will disappear.

> * You said that I need to close my context a the end of each fixture, but in this way the windows get closed and the test fail

You should close after `await use()` - note the await.

```js
    loggedIn: async({browser, signinUrl, username, password}, use) => {
        const context1 = await browser.newContext();
        const page = await context1.newPage();
        await page.goto(signinUrl);
        // operations on page...

        // Use the page and wait for the test to finish.
        await use(page);

        // Now it is time to cleanup.
        await context1.close();
    },
```
