### ISSUE TITLE
[BUG]  page.waitForRequest & page.waitForResponse: Timeout error doesn't display the timeout value

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#10706]
**Context:**
- Playwright Version: [1.17.1]
- Operating System: [Mac]
- Node.js version: [16.12.0]
- Browser: [All]
- Extra: [N/A]

**Code Snippet**

playwright.config.js
```javascript
// playwright.config.js
// @ts-check

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
    workers: 1,
    reporter: [
        ['list']
    ],
    projects: [
        {
            name: 'Test1',
            testDir: './test/bug',
            testMatch: 'waitforresponse.js',
            retries: 0,
            use: {
                browserName: 'chromium',
                channel: 'chrome',
                headless: false,
                viewport: {width: 1600, height: 825},
                ignoreHTTPSErrors: true,
                trace: "off",
                screenshot: "only-on-failure",
                actionTimeout: 20000
            },
        },
    ]
};
module.exports = config;

```
waitforresponse.js
```javascript
const { test, expect } = require('@playwright/test');

test('test', async ({ page }) => {
    await page.goto('https://www.selenium-tutorial.com/p/angularjs-protractor-tutorial');
    await Promise.all([
        page.waitForResponse(/courses1/),
        page.click('text=All Courses')
    ]);
    await page.click('text=All Courses');
});
```

**Describe the bug**
Running the above mentioned test will throw an error message after 20 seconds of `actionTimeout` set in config file but the error message won't display the `actionTimeout` value set in config file. I would expect the `actionTimeout` value to  be displayed in the error message.

```javascript
Running 1 test using 1 worker

  ✘  [Test1] › test/bug/waitforresponse.js:3:1 › test (23s)

  1) [Test1] › test/bug/waitforresponse.js:3:1 › test ==============================================

    page.waitForResponse: Timeout while waiting for event "response"
    =========================== logs ===========================
    waiting for response /courses1/
    ============================================================

       6 |     await page.goto('https://www.selenium-tutorial.com/p/angularjs-protractor-tutorial');
       7 |     await Promise.all([
    >  8 |         page.waitForResponse(/courses1/),
         |              ^
       9 |         page.click('text=All Courses')
      10 |     ]);
      11 |     /*await Promise.all([

        at /Users/ravuri/Documents/kb-auto-pw-final/test/bug/waitforresponse.js:8:14

    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/waitforresponse.js-test-Test1/test-failed-1.png
    ------------------------------------------------------------------------------------------------

  Slow test file: [Test1] › test/bug/waitforresponse.js (23s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [Test1] › test/bug/waitforresponse.js:3:1 › test ===============================================

```

Noticed same behavior with `page.waitForRequest` also.

```javascript
Running 1 test using 1 worker

  ✘  [Test1] › test/bug/waitforresponse.js:3:1 › test (24s)


  1) [Test1] › test/bug/waitforresponse.js:3:1 › test ==============================================

    page.waitForRequest: Timeout while waiting for event "request"
    =========================== logs ===========================
    waiting for request /courses1/
    ============================================================

      10 |     ]);*/
      11 |     await Promise.all([
    > 12 |         page.waitForRequest(/courses1/),
         |              ^
      13 |         page.click('text=All Courses')
      14 |     ]);
      15 |     /*await Promise.all([

        at /Users/ravuri/Documents/kb-auto-pw-final/test/bug/waitforresponse.js:12:14

    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/waitforresponse.js-test-Test1/test-failed-1.png
    ------------------------------------------------------------------------------------------------

  Slow test file: [Test1] › test/bug/waitforresponse.js (24s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [Test1] › test/bug/waitforresponse.js:3:1 › test ===============================================

```

**Comment by vsravuri** [comment]
@dgozman Will the fix available in 1.18 branch ?

**Comment by mxschmitt** [comment]
> @dgozman Will the fix available in 1.18 branch ?

Yes, everything on the main branch gets included in 1.18

**Comment by vsravuri** [comment]
Thanks @mxschmitt I tested in 1.18 build (^1.18.0-next-alpha-nov-13-2021) and didn't find the changes. Noticed the pull request is merged to master branch. so thought of checking.

**Comment by mxschmitt** [comment]
Your 1.18 build is pretty old, try the latest one: `npm install @playwright/test@next`.

**Comment by vsravuri** [comment]
Thanks @mxschmitt Now i could see the changes. Appreciate your help.
