### ISSUE TITLE
[BUG] Proxying WebSockets with http-proxy not working with firefox and webkit

### ISSUE THREAD

**Issue by Cyrus-d** [microsoft/playwright#1081]
**Context:**
- Playwright Version: [^0.11.1]
- Operating System: [Windows 10]
- Extra: [Using docker to launch playwright server ]

**Code Snippet**

[playwright-docker-server](https://github.com/Cyrus-d/playwright-docker-server)

**Describe the bug**

I am trying to dockerized the playwright to launch a server inside the docker and proxy the socket as follow:

```
import * as httpProxy from 'http-proxy';
import * as playwright from 'playwright';

const proxy = httpProxy.createProxyServer();
http
  .createServer()
  .on('upgrade', async (req, socket, head) => {
    const browser = await playwright['chromium'].launchServer({
      args: ['--no-sandbox'],
    });
    const endPoint = browser.wsEndpoint();
    proxy.ws(req, socket, head, {target: endPoint });
  })
  .on('listening', () => {
    console.log('Server listening...');
  })
  .on('close', () => {
    console.log('http server closed');
  })
  .listen(3000);

```
The above code works well with chrome, however, it won't work with  WebKit and firefox.

It throws following error for firefox:

```
(node:25528) UnhandledPromiseRejectionWarning: Error: WebSocket error: Unexpected server response: 400
    at WebSocket._ws.addEventListener.event (\node_modules\playwright-core\lib\platform.js:288:65)
    at WebSocket.onError (\node_modules\playwright-core\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:194:15)
    at abortHandshake (\node_modules\playwright-core\node_modules\ws\lib\websocket.js:718:15)
    at ClientRequest.req.on (\node_modules\playwright-core\node_modules\ws\lib\websocket.js:595:7)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
(node:25528) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.enable): Target closed.
    at Promise (\node_modules\playwright-core\lib\firefox\ffConnection.js:54:63)
    at new Promise (<anonymous>)
    at FFConnection.send (\node_modules\playwright-core\lib\firefox\ffConnection.js:53:16)
    at Function.connect (\node_modules\playwright-core\lib\firefox\ffBrowser.js:49:26)
    at Firefox.connect (\node_modules\playwright-core\lib\server\firefox.js:132:38)
    at \src\main.ts:5:49
    at Generator.next (<anonymous>)
    at \node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (\node_modules\tslib\tslib.js:106:16)
```

And following error for WebKit:

```
 UnhandledPromiseRejectionWarning: Error: Protocol error (Browser.createContext): Browser has been closed.
    at Promise (\node_modules\playwright-core\lib\webkit\wkConnection.js:99:63)
    at new Promise (<anonymous>)
    at WKSession.send (\node_modules\playwright-core\lib\webkit\wkConnection.js:98:16)
    at WKBrowser.newContext (\node_modules\playwright-core\lib\webkit\wkBrowser.js:57:65)
    at WKBrowser.<anonymous> (\node_modules\playwright-core\lib\helper.js:55:31)
    at \src\main.ts:9:33
    at Generator.next (<anonymous>)
    at fulfilled (\node_modules\tslib\tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
  -- ASYNC --
    at WKBrowser.<anonymous> (\node_modules\playwright-core\lib\helper.js:54:23)
    at \src\main.ts:9:33
    at Generator.next (<anonymous>)
    at fulfilled (\node_modules\tslib\tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Not sure if this problem is related to #810, feel free to close this issue if it's same.

**Comment by pavelfeldman** [comment]
It looks like `http-proxy` appends the path from your client `ws://localhost:3000/` request to the target request `ws://127.0.0.1:64721/06b1cccb-b84d-44cd-bd22-e36ad2b10a37`

As a result, server gets path `/06b1cccb-b84d-44cd-bd22-e36ad2b10a37/` instead of expected `/06b1cccb-b84d-44cd-bd22-e36ad2b10a37` (see the extra trailing slash).

Creating proxy as below works around it.

`const proxy = httpProxy.createProxyServer({ ignorePath: true });`

@indexzero: not sure if this behavior is expected.

**Comment by pavelfeldman** [comment]
Please feel free to reopen if this did not work for you.

**Comment by Cyrus-d** [comment]
@pavelfeldman  thank you for the explanations, setting `ignorePath=true` did solve the problem partially.

Now all browsers are working fine within the host, however, firefox and WebKit still not working inside the docker, both browsers throwing the following error:

```
(node:26) UnhandledPromiseRejectionWarning: Error: Failed to launch browser!


TROUBLESHOOTING: https://github.com/Microsoft/playwright/blob/master/docs/troubleshooting.md

    at onClose (z:\github\playwright-docker-server\node_modules\playwright-core\lib\server\processLauncher.js:139:21)
    at Interface.<anonymous> (z:\github\playwright-docker-server\node_modules\playwright-core\lib\server\processLauncher.js:132:66)
    at Interface.emit (events.js:323:22)
    at Interface.close (readline.js:409:8)
    at Socket.onend (readline.js:187:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
warning.js:32
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
warning.js:32
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections a
```

Using debugger inside the docker show that error thrown somewhere in `processLauncher.js` file in the `waitForLine` method, apparently `waitForLine` promise never get resolved because onClose called to early.

I did follow the troubleshooting.md recommendation for docker with no lock.

Any idea why this error is thrown?

**Comment by arjun27** [comment]
Thanks @cyrus-d for reporting this. This implies that the system dependencies for the browsers are not installed in the docker image. To debug this, you can use `dumpio: true` in the `launch()` method arguments.

On looking at the dockerfile in playwright-docker-server repo, I can see some missing dependencies. You can refer to this [working image for Ubuntu 18.04](https://github.com/arjun27/playwright-github-actions/blob/master/Dockerfile#L8).

We are working on fixing the troubleshooting docs, and adding working dockerfile definitions

**Comment by Cyrus-d** [comment]
@arjun27 thanks for the dockerfile it has solved my problem.
