### ISSUE TITLE
[BUG] timeout fixtures are not applied to Electron

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#10840]
### Discussed in https://github.com/microsoft/playwright/discussions/10809

<div type='discussions-op-text'>

<sup>Originally posted by **evertonlperes** December  8, 2021</sup>
Hi there,
Just facing a weird situation (CI and sometimes locally, but it's rare) where the electron app hangs during the `electronApp.close()` method. All the tests has passed properly though.
We build the project through a script "helper.mjs" that will build (webpack dev mode) and start nuxt to renderer the app before we invoke it on playwright.

Versions:
CI Provider: `Cirrus CI`
Runner: `Ubuntu 20.04`
Electron: `12.0.18`
Nuxt: `2.14.12`
webpack: `4.46.0`
PW: `1.17.0`
@playwright/test: `1.17.0`

Not sure if someone have faced the same behaviour, but looking for some guidance on this :) 

Test result:
```bash
Running 12 tests using 1 worker
Default settings file successfully created on:  /home/ranchertest/.config/rancher-desktop/settings.json
  ✓  kubectl.e2e.spec.ts:44:3 › Rancher Desktop - K8s Deploy Test › should load Rancher Desktop App (1s)
  ✓  kubectl.e2e.spec.ts:50:3 › Rancher Desktop - K8s Deploy Test › should start loading the background services (52ms)
Waiting for services - CI take a while to load...
  ✓  kubectl.e2e.spec.ts:57:3 › Rancher Desktop - K8s Deploy Test › should run Kubernetes on Rancher Desktop (kubectl) (3m)
  ✓  kubectl.e2e.spec.ts:71:3 › Rancher Desktop - K8s Deploy Test › should create a sample namespace (426ms)
  ✓  kubectl.e2e.spec.ts:86:3 › Rancher Desktop - K8s Deploy Test › should deploy sample nginx server (10s)
  ✓  kubectl.e2e.spec.ts:115:3 › Rancher Desktop - K8s Deploy Test › should delete sample namespace (11s)
TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (/home/ranchertest/node_modules/playwright-core/lib/server/progress.js:96:26)
    at ElectronApplication.close (/home/ranchertest/node_modules/playwright-core/lib/server/electron/electron.js:103:39)
    at ElectronApplicationDispatcher.close (/home/ranchertest/node_modules/playwright-core/lib/dispatchers/electronDispatcher.js:88:24)
    at DispatcherConnection.dispatch (/home/ranchertest/node_modules/playwright-core/lib/dispatchers/dispatcher.js:352:46)
```

Looking into the logs:
```bash
2021-12-08T17:24:59.441Z pw:channel:command {
  id: 8,
  guid: 'browser-context@85d0565e84d3271283ae57e597d846ec',
  method: 'tracingStop',
  params: undefined
}
2021-12-08T17:24:59.444Z pw:channel:response { id: 8 }
2021-12-08T17:24:59.444Z pw:api <= tracing.stop succeeded
2021-12-08T17:24:59.445Z pw:api => electronApplication.close started
2021-12-08T17:24:59.445Z pw:channel:command {
  id: 9,
  guid: 'electron-app@50a6034fa1b0dbf2cee0e6fcf6e1b1ff',
  method: 'close',
  params: undefined
}
2021-12-08T17:24:59.447Z pw:protocol SEND ► {"id":4,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"-3779882501978494612.1.1","arguments":[{"objectId":"-3779882501978494612.1.1"},{"value":true},{"value":true},{"value":"({\n      app\n    }) => app.quit()"},{"value":2},{"value":{"h":0}},{"value":{"v":"undefined"}},{"objectId":"-3779882501978494612.1.2"}],"returnByValue":true,"awaitPromise":true,"userGesture":true}}
2021-12-08T17:25:29.465Z pw:test teardown _setupContextOptionsAndArtifacts
2021-12-08T17:25:29.465Z pw:test teardown _combinedContextOptions
2021-12-08T17:25:29.465Z pw:test teardown baseURL
TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (/home/ranchertest/node_modules/playwright-core/lib/server/progress.js:96:26)
    at ElectronApplication.close (/home/ranchertest/node_modules/playwright-core/lib/server/electron/electron.js:103:39)
    at ElectronApplicationDispatcher.close (/home/ranchertest/node_modules/playwright-core/lib/dispatchers/electronDispatcher.js:88:24)
    at DispatcherConnection.dispatch (/home/ranchertest/node_modules/playwright-core/lib/dispatchers/dispatcher.js:352:46)
2021-12-08T17:25:29.468Z pw:test teardown _artifactsDir
2021-12-08T17:25:29.468Z pw:test teardown _browserType
2021-12-08T17:25:29.468Z pw:test teardown _browserOptions
2021-12-08T17:25:29.468Z pw:test teardown browserName
2021-12-08T17:25:29.468Z pw:test teardown playwright
2021-12-08T17:25:29.468Z pw:browser [pid=8000] <kill>
2021-12-08T17:25:29.468Z pw:browser [pid=8000] <will force kill>
2021-12-08T17:25:29.472Z pw:browser [pid=8000] starting temporary directories cleanup
2021-12-08T17:25:29.577Z pw:browser [pid=8000] finished temporary directories cleanup
```
I did notice the protocol never returned the RECV after the close method sent the request... grabbing more logs for that :) 

Even though I have a timeout set in `playwright-config.ts`, it seems to be ignored though :/
```typescript
import * as path from 'path';
import type { Config, PlaywrightTestOptions, PlaywrightWorkerOptions } from '@playwright/test';

const outputDir = path.join(__dirname, '..', 'e2e', 'test-results');
const testDir = path.join(__dirname, '..', '..', 'e2e');

const config: Config< & PlaywrightWorkerOptions & PlaywrightTestOptions> = {
  testDir,
  outputDir,
  timeout:       process.env.CI ? 600_000 : 300_000,
  globalTimeout: 600_000,
  retries:       process.env.CI ? 2 : undefined,
  workers:       1,
  reporter:      'list',
};

export default config;
```

Thank you</div>

**Comment by stoefln** [comment]
Same here. It happens randomly. Sometimes it quits the app, sometimes it hangs. Sometime on test 4 sometimes on test 5.
We call the method from within test.afterAll.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
