### ISSUE TITLE
[Feature] Allow connecting to CEF instances via `browserType.connectOverCDP`

### ISSUE THREAD

**Issue by rajukshetri** [microsoft/playwright#10927]
**Context:**
- Playwright Version: [Version 1.17.1]
- Operating System: [Windows]
- Node.js version: [v12.16.1]
- Browser: [ CEF | 90.6.3+gc53c523+chromium-90.0.4430.93]
- Extra: 
- CEF | 90.6.3+gc53c523+chromium-90.0.4430.93
Chromium | 90.0.4430.93
OS | Windows
WebKit | 537.36 (@4df112c29cfe9a2c69b14195c0275faed4e997a7)
JavaScript | 9.0.257.23
User Agent | Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93; ) Safari/537.36

**Code Snippet**
import { test, expect ,chromium } from '@playwright/test';
  test('my test', async () => {
	  const cdpBrowser1 = await chromium.connectOverCDP({
        wsEndpoint: `ws://localhost:9222/devtools/browser/01582b7e-7cb0-4bed-a8b1-5e211d3a3ab6`,
      });
      });

**Describe the bug**

I have an application that uses the chromium version 90 from CEF as a browser .
when I run the above snippet it throws the following exception:
    browserType.connectOverCDP: Protocol error (Browser.setDownloadBehavior): Browser context management is not supported.
    =========================== logs ===========================
    <ws connecting> ws://localhost:9222/devtools/browser/01582b7e-7cb0-4bed-a8b1-5e211d3a3ab6
    <ws connected> ws://localhost:9222/devtools/browser/01582b7e-7cb0-4bed-a8b1-5e211d3a3ab6
    ============================================================
   > 6 |         const cdpBrowser1 = await chromium.connectOverCDP({
                                    ^
      7 |         wsEndpoint: `ws://localhost:9222/devtools/browser/01582b7e-7cb0-4bed-a8b1-5e211d3a3ab6`,
      8 |       });
      9 |           console.log('connected ');

        at D:\projects\playwright\tests\demo.spec.ts:6:39
        at FixtureRunner.resolveParametersAndRunHookOrTest (D:\projects\\playwright\node_modules\@playwright\test\lib\fixtures.js:306:12)
        at WorkerRunner._runTestWithBeforeHooks (D:\projects\playwright\node_modules\@playwright\test\lib\workerRunner.js:499:7)

same snippet  works fine for the chromium browser 90 when it launched via:
"C:\Users\rakshetri\AppData\Local\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9333 -- "%1"

**Comment by mxschmitt** [comment]
Playwright's latest release does only test against the current stable browsers which are currently 96 (see for that the release notes).

For older versions the compatibility might break, which in your scenario is the case, we recommend to upgrade your browser to a more recent version.

**Comment by mxschmitt** [comment]
Closing since Playwright does not support old Chromium browsers.

**Comment by rajukshetri** [comment]
As we are using CEF :https://en.wikipedia.org/wiki/Chromium_Embedded_Framework that uses the embedded chromium to our application  and we do now upgrade it so frequently. 
Is there any way to use the older library of playwright that support the respective chromium browser .
Is there any workaround ?please suggest any solution here ?  
We already using selenium and for such requirement  with  chromedriver.exe of respective version of chrome. and we are evaluating with playwright as a new tool.    
 

> Closing since Playwright does not support old Chromium browsers.

**Comment by rajukshetri** [comment]
@mxschmitt 
I have tried with CEF that embedded chromium  "Browser": "Chrome/94.0.4606.61",  but issue is same .
Unfortunately we don't have product released  with  CEF which have chrome 96  , but I think this issue is not related to the browser version  since same PW configuration works for the standalone browser chrome version 90 installed at machine.

**Comment by mxschmitt** [comment]
Playwright does not support connecting to CEF instances, since the Chromium Embedded Framework does not expose the `Browser.*` CDP domain - so we are limited by that.

(sorry for the confusion above - so its not possible).

**Comment by rajukshetri** [comment]
@mxschmitt thank you very much I will be highly appreciate your efforts towards this  .
I am eagerly waiting for this support as this is road blocking for our CEF e2e testing with PW.

**Comment by rprabhun-onshape** [comment]
@mxschmitt We also need support for connecting CEF instances for our end to end type of testing.
It will really help if this can be introduced. We can leverage play wright to good extent with all its remaining functionalities.

**Comment by shals-praise** [comment]
@mxschmitt I am evaluating playwright for our automation requirements and so far it seems to be a great e2e testing framework!!..We also need this feature to connect to CEF. Most of the latest testing frameworks do support Chromium Embedded Framework... Waiting to have it supported by playwright soon.!!

**Comment by mxschmitt** [comment]
@rajukshetri @shals-praise please upvote the first comment - thats the way we prioritise feature requests.

**Comment by collin-rogers** [comment]
@mxschmitt I am also evaluating playwright for our current automation requirements. I've been using puppeteer as a temporary solution for our CEF e2e testing, but I would love to be able to use the features of playwright. Hoping this feature comes soon!

**Comment by rprabhun-onshape** [comment]
@collin-rogers please upvote the first comment - thats the way they prioritise feature requests.

**Comment by rprabhun** [comment]
> @mxschmitt I am also evaluating playwright for our current automation requirements. I've been using puppeteer as a temporary solution for our CEF e2e testing, but I would love to be able to use the features of playwright. Hoping this feature comes soon!

@collin-rogers  please upvote the first comment - thats the way they prioritise feature requests.

**Comment by rebajz** [comment]
How use playwright with CEF

tested on playwright 1.33.0 and CEF 110

start app with CEF browser
visit http://localhost:XXXX/json/version

where XXXX is debug port

you see something as:
{
   "Browser": "Chrome/110.0.5481.178",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
   "V8-Version": "11.0.226.16",
   "WebKit-Version": "537.36 (@e9acac08b3d8368c80ef92352d046e924969e9bf)",
   "webSocketDebuggerUrl": "ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e"
}

demo test file
const {chromium} = require('playwright');

test('demo test', async () => {
  const browser = await chromium.connectOverCDP(
    'here copy webSocketDebuggerUrl from json'
  );
  const defaultContext = browser.contexts()[0];
  const myPage = defaultContext.pages()[0];
  await myPage.goto('https://playwright.dev/');
});

When you run this test, you get error something as:
Error: browserType.connectOverCDP: Protocol error (Browser.setDownloadBehavior): Browser context management is not supported.
    =========================== logs ===========================
    <ws connecting> ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e
    <ws connected> ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e
    
    

But, when you do this change in source of playwright:
node_modules\playwright-core\lib\server\chromium\crBrowser.js

lines 297 to 304 delete or do from lines only comments
    if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank') {
      promises.push(this._browser._session.send('Browser.setDownloadBehavior', {
        behavior: this._options.acceptDownloads ? 'allowAndName' : 'deny',
        browserContextId: this._browserContextId,
        downloadPath: this._browser.options.downloadsPath,
        eventsEnabled: true
      }));
    }
    
after change:
    // if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank') {
    //   promises.push(this._browser._session.send('Browser.setDownloadBehavior', {
    //     behavior: this._options.acceptDownloads ? 'allowAndName' : 'deny',
    //     browserContextId: this._browserContextId,
    //     downloadPath: this._browser.options.downloadsPath,
    //     eventsEnabled: true
    //   }));
    // }

run playwright again... you see
 npx playwright test example.spec.ts

Running 1 test using 1 worker
  1 passed (2.1s)

:-) :-) :-)

**Comment by wkyseo** [comment]
> How use playwright with CEF
> 
> tested on playwright 1.33.0 and CEF 110
> 
> start app with CEF browser visit http://localhost:XXXX/json/version
> 
> where XXXX is debug port
> 
> you see something as: { "Browser": "Chrome/110.0.5481.178", "Protocol-Version": "1.3", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36", "V8-Version": "11.0.226.16", "WebKit-Version": "537.36 (@e9acac08b3d8368c80ef92352d046e924969e9bf)", "webSocketDebuggerUrl": "ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e" }
> 
> demo test file const {chromium} = require('playwright');
> 
> test('demo test', async () => { const browser = await chromium.connectOverCDP( 'here copy webSocketDebuggerUrl from json' ); const defaultContext = browser.contexts()[0]; const myPage = defaultContext.pages()[0]; await myPage.goto('https://playwright.dev/'); });
> 
> When you run this test, you get error something as: Error: browserType.connectOverCDP: Protocol error (Browser.setDownloadBehavior): Browser context management is not supported. =========================== logs =========================== ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e
> 
> But, when you do this change in source of playwright: node_modules\playwright-core\lib\server\chromium\crBrowser.js
> 
> lines 297 to 304 delete or do from lines only comments if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank') { promises.push(this._browser._session.send('Browser.setDownloadBehavior', { behavior: this._options.acceptDownloads ? 'allowAndName' : 'deny', browserContextId: this._browserContextId, downloadPath: this._browser.options.downloadsPath, eventsEnabled: true })); }
> 
> after change: // if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank') { // promises.push(this._browser._session.send('Browser.setDownloadBehavior', { // behavior: this._options.acceptDownloads ? 'allowAndName' : 'deny', // browserContextId: this._browserContextId, // downloadPath: this._browser.options.downloadsPath, // eventsEnabled: true // })); // }
> 
> run playwright again... you see npx playwright test example.spec.ts
> 
> Running 1 test using 1 worker 1 passed (2.1s)
> 
> :-) :-) :-)
> 
> edit: when you use this in test, this working too
> 
> const browser = await chromium.connectOverCDP({endpointURL: '[http://localhost:5555'}](http://localhost:5555'%7D));

@rebajz ![image](https://github.com/microsoft/playwright/assets/13041485/700ee2b1-2b62-4137-b4d7-2dbc850134da)

**Comment by ovclara** [comment]
Working on a project where many applications use CEF and CEF versions is not updated always, I wanted to propose - Playwright as a automation tool for this projects, but due to this complexity in connecting CEF seamlessly we are blocked to go ahead.
I see a  post on CEF forum : https://magpcss.org/ceforum/viewtopic.php?f=6&t=19313
Where it seems CEF has no plans to expose Browser.* CPD domain, so we look at PlayWright team to have some easy way to  handle this so that we could user this Awesome tool.

**Comment by zotune** [comment]
> How use playwright with CEF
> 
> tested on playwright 1.33.0 and CEF 110
> 
> start app with CEF browser visit http://localhost:XXXX/json/version
> 
> where XXXX is debug port
> 
> you see something as: { "Browser": "Chrome/110.0.5481.178", "Protocol-Version": "1.3", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36", "V8-Version": "11.0.226.16", "WebKit-Version": "537.36 (@e9acac08b3d8368c80ef92352d046e924969e9bf)", "webSocketDebuggerUrl": "ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e" }
> 
> demo test file const {chromium} = require('playwright');
> 
> test('demo test', async () => { const browser = await chromium.connectOverCDP( 'here copy webSocketDebuggerUrl from json' ); const defaultContext = browser.contexts()[0]; const myPage = defaultContext.pages()[0]; await myPage.goto('https://playwright.dev/'); });
> 
> When you run this test, you get error something as: Error: browserType.connectOverCDP: Protocol error (Browser.setDownloadBehavior): Browser context management is not supported. =========================== logs =========================== ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e ws://localhost:5555/devtools/browser/22501224-0c07-4649-a8e1-3bc94dcddd0e
> 
> But, when you do this change in source of playwright: node_modules\playwright-core\lib\server\chromium\crBrowser.js
> 
> lines 297 to 304 delete or do from lines only comments if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank') { promises.push(this._browser._session.send('Browser.setDownloadBehavior', { behavior: this._options.acceptDownloads ? 'allowAndName' : 'deny', browserContextId: this._browserContextId, downloadPath: this._browser.options.downloadsPath, eventsEnabled: true })); }
> 
> after change: // if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank') { // promises.push(this._browser._session.send('Browser.setDownloadBehavior', { // behavior: this._options.acceptDownloads ? 'allowAndName' : 'deny', // browserContextId: this._browserContextId, // downloadPath: this._browser.options.downloadsPath, // eventsEnabled: true // })); // }
> 
> run playwright again... you see npx playwright test example.spec.ts
> 
> Running 1 test using 1 worker 1 passed (2.1s)
> 
> :-) :-) :-)
> 
> edit: when you use this in test, this working too
> 
> const browser = await chromium.connectOverCDP({endpointURL: '[http://localhost:5555'}](http://localhost:5555'%7D));

Can confirm that this works for html CEF panels in Adobe Premiere.

Playwright team, could we possibly make it an option to disable `setDownloadBehavior` without having to comment out component code in `node_modules`

**Comment by huxiang** [comment]
Cursor gives me a workaround by patching the `crBrowser.js` file in playwright module:
```
PATCH_OLD = "if (this._browser.options.name !== 'clank' && this._options.acceptDownloads !== 'internal-browser-default') {"
PATCH_NEW = "if (this._browser.options.name !== 'clank' && this._options.acceptDownloads !== 'internal-browser-default' && !process.env.PW_CHROMIUM_DISABLE_DOWNLOAD_BEHAVIOR) {"
```

Before connecting to electron app via CDP, set env var `PW_CHROMIUM_DISABLE_DOWNLOAD_BEHAVIOR=1`, then it works.
