### ISSUE TITLE
Firefox Browser Failed to Run Example Code

### ISSUE THREAD

**Issue by pamalite** [microsoft/playwright#11118]
Getting the following timeout errors when the following "p.firefox.launch()" is used:

```
Traceback (most recent call last):
  File "C:\Users\xyz\Documents\Development\playwright_test.py", line 43, in <module>
    main()
  File "C:\Users\xyz\Documents\Development\playwright_test.py", line 38, in main
    page.goto("http://playwright.dev")
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 7278, in goto
    self._sync(
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 466, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 119, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "http://playwright.dev/", waiting until "load"
============================================================
```

The example code:

```python
from playwright.sync_api import sync_playwright

def main():
    with sync_playwright() as p:
        browser = p.firefox.launch()
        page = browser.new_page()
        page.goto("http://playwright.dev")
        print(page.title())
        page.screenshot(path="playwright_example.png")
        browser.close()

main()
```

Same behavior when used with `headless=False`, and async APIs too. 

When `headless=False`, this is what Firefox Nightly shows:

![image](https://user-images.githubusercontent.com/5591/147547867-e00792ab-6bb9-4d54-b3b0-d4f514defb98.png)

System details:
- OS: Windows 10
- Python: 3.10
- Pip:
   - playwright: 1.17.2
   - websockets: 10.1

**Comment by aslushnikov** [comment]
@pamalite I can easily repro on tip of tree with the following script:

```js
// a.mjs
import {firefox} from '@playwright/test';

const browser = await firefox.launch();
const page = await browser.newPage();
await page.goto('http://playwright.dev');
console.log(await page.title());
await browser.close();
```

the issue seems to be in the http -> https redirect; changing URL from `http://playwright.dev` to `https://playwright.dev` makes script work. 

Investigating!

**Comment by aslushnikov** [comment]
This is fixed on tip-of-tree now; will be available in tomorrow's canary release and will be installable with

```sh
npm i @playwright/test@next
```
