### ISSUE TITLE
[BUG] webServer configuration doesn't work on Windows

### ISSUE THREAD

**Issue by gokula-krishna-dev** [microsoft/playwright#11187]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 16.13.1
- Browser: N/A
- Extra: N/A

My `playwright.config,js` config:
```javascript
const { devices } = require('@playwright/test');

const config = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  use: {
    trace: 'on-first-retry',
  },
  webServer: {
    command: 'npm run start',
    port: 3000,
    timeout: 120 * 1000,
    reuseExistingServer: !process.env.CI,
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
};

module.exports = config;
```

When I run `npx playwright test` I get the following error on Windows but **works on Linux**. It works fine if I remove `webServer` block:

```
Using config at D:\github\website\playwright.config.js
[WebServer]
 FATAL  Cannot read properties of undefined (reading 'trim')

  TypeError: Cannot read properties of undefined (reading 'trim')
  at Object.<anonymous> (nuxt.config.js:130:31)
  at Generator.next (<anonymous>)

[WebServer]
   ╭─────────────────────────────────────────────────────────────────────╮
   │                                                                     │
   │   ✖ Nuxt Fatal Error                                                │
   │                                                                     │
   │   TypeError: Cannot read properties of undefined (reading 'trim')   │
   │                                                                     │
   ╰─────────────────────────────────────────────────────────────────────╯

Error: Process from config.webServer was not able to start. Exit code: 1
    at Object.onExit (D:\github\website\node_modules\@playwright\test\lib\webServer.js:95:43)
    at ChildProcess.<anonymous> (D:\github\website\node_modules\playwright-core\lib\utils\processLauncher.js:122:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by pavelfeldman** [comment]
```
TypeError: Cannot read properties of undefined (reading 'trim')
  at Object.<anonymous> (nuxt.config.js:130:31)
  at Generator.next (<anonymous>)
```

This points to a bug in the nuxt config file. Does `npm run start` work for you?

**Comment by gokula-krishna-dev** [comment]
Thanks for the reply @pavelfeldman. The problem was on Nuxt config. Sorry for the trouble
