### ISSUE TITLE
[BUG] playwright scrolls too far and 

### ISSUE THREAD

**Issue by IuliiaBondarieva** [microsoft/playwright#11195]
**Context:**
- Playwright Version: @playwright/test@1.17.1,
- Operating System: Mac
- Node.js version: v14.17.4
- Browser: Chromium
- Extra: failing on CI or by inspect

**Code Snippet**

```javascript
    await infoArea.activateButton.click()
    await modal.form.waitFor()
    await keyboard.down('Escape')
    await expect(modal.form).not.toBeVisible()
```

Logging

```javascript
 Timeout of 60000ms exceeded.

Pending operations:

- locator.waitFor at ../e2e/src/basic.test.mjs:29:37
locator.waitFor: Target closed
=========================== logs ===========================

waiting for selector ".Form" to be visible
============================================================

at TestTypeImpl._step (/home/jenkins/workspace/FE_PRs_Build_and_test_PR-1740/e2e/node_modules/@playwright/test/lib/testType.js:214:7)
at WorkerRunner._runTestWithBeforeHooks (/home/jenkins/workspace/FE_PRs_Build_and_test_PR-1740/e2e/node_modules/@playwright/test/lib/workerRunner.js:499:7)
```

Debugging:

```javascript
pw:api   attempting click action

pw:api   waiting for element to be visible, enabled and stable
pw:api   element is visible, enabled and stable
pw:api   scrolling into view if needed
pw:api   done scrolling
pw:api   checking that element receives pointer events at (559.48,360.67)
pw:api   element does receive pointer events
pw:api   performing click action
pw:api   click action done
pw:api   waiting for scheduled navigations to finish
pw:api   navigations have finished
pw:api <= locator.click succeeded
pw:api => locator.waitFor started
pw:api waiting for selector ".Form" to be visible
pw:api   "networkidle" event fired
pw:api => browserContext.close started
pw:api <= locator.waitFor failed
```

**Describe the bug**

By scrolling to `activateButton` playwright fires `element does receive pointer events` but pointer stops further than element location.

<img width="432" alt="Screenshot 2022-01-05 at 12 29 53" src="https://user-images.githubusercontent.com/33291671/148215174-e8dbbeb4-76da-4a2c-990a-2671e7ada253.png">

I solved this by adding `await infoArea.activateButton.hover()` so it scrolls too far with hover, but after that already finds the right position for click action. It's not the best solution.

Is there any possibility to check if scrolling was completed before checking for pointer events?

**Comment by pavelfeldman** [comment]
Looks like a layout shift to me. Could you set environment variable `PLAYWRIGHT_LAYOUT_SHIFT_CHECK=1` and try it again?

**Comment by IuliiaBondarieva** [comment]
No, it doesn't help. There is also nothing that could shift.

I've also seen the playwright repeat it several times, scrolling up and down, and sometimes he succeeds on the fourth try:

```
<div class="grid grid-flex grid-fill-rows gutter padd…>…</div> intercepts pointer events
retrying click action, attempt #1
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
<div class="grid-item palm-one-whole lap-one-whole de…>…</div> intercepts pointer events
retrying click action, attempt #2
waiting 20ms
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
<img src="/footer.png"/> from <div class="Footer align-center">…</div> subtree intercepts pointer events
retrying click action, attempt #3
waiting 100ms
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
<div class="grid grid-flex grid-fill-rows gutter padd…>…</div> intercepts pointer events
retrying click action, attempt #4
waiting 100ms
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
```

**Comment by dgozman** [comment]
@IuliiaBondarieva Could you please share a repro so that we can debug locally? Not sure what we can do without a repro here.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
