### ISSUE TITLE
[BUG] page.click() is not working

### ISSUE THREAD

**Issue by star-kashyap** [microsoft/playwright#1121]
**Context:**
- Playwright Version: [0.11.1]
- Operating System: [Mac]
- Extra: [Browser : Chrome,  webPage: https://www.hotstar.com/in]

**Code Snippet**

```javascript
 let el = await page.$('.btn-hamburger');
        await el.click();
or 
await page.click('.btn-hamburger'); // also tried this way... faced same error
```

**Describe the bug**
Launching https://www.hotstar.com/in and trying to click on element with class btn-hamburger 
Its throwing Protocol Error. 
 Error: Protocol error (DOM.scrollIntoViewIfNeeded): 'DOM.scrollIntoViewIfNeeded' wasn't found
      at /Users/kashyaps/automation/playwright-tests/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
      at new Promise (<anonymous>)
      at CRSession.send (node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
      at CRPage.scrollRectIntoViewIfNeeded (node_modules/playwright-core/lib/chromium/crPage.js:413:28)
      at ElementHandle._scrollRectIntoViewIfNeeded (node_modules/playwright-core/lib/dom.js:148:36)
      at ElementHandle._performPointerAction (node_modules/playwright-core/lib/dom.js:212:20)
      at ElementHandle.click (node_modules/playwright-core/lib/dom.js:225:21)
      at Context.<anonymous> (tests/player/playabilityTests.js:25:18)

**Comment by star-kashyap** [comment]
Closed this issue as its happening in case of executablePath option set in chromeOptions. Its working incase of bundled chromium.
