### ISSUE TITLE
[bug] Cross-process navigation reliably crashes webkit on MacOS 12 

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#11294]
Cross-process navigation reliably crashes webkit on Macbook Pro 12.1

```js
it.only('cross-process navigation should work', async ({ page, server }) => {
  await page.goto(server.EMPTY_PAGE);
  await page.goto(server.CROSS_PROCESS_PREFIX + '/empty.html');
  await new Promise(r => setTimeout(r, 1000)); // not sure why timeout is important here, but it triggers crash in release.
  console.log(await page.evaluate(() => navigator.userAgent));
});
```

Crash looks like this:

```
0   WebKit                        	       0x102d95928 WebKit::WebsiteDataStore::networkProcess() + 20
1   WebKit                        	       0x102d9ca88 WebKit::WebsiteDataStore::getNetworkProcessConnection(WebKit::WebProcessProxy&, WTF::CompletionHandler<void (WebKit::NetworkProcessConnectionInfo const&)>&&, WebKit::WebsiteDataStore::ShouldRetryOnFailure) + 48
2   WebKit                        	       0x102d9ca88 WebKit::WebsiteDataStore::getNetworkProcessConnection(WebKit::WebProcessProxy&, WTF::CompletionHandler<void (WebKit::NetworkProcessConnectionInfo const&)>&&, WebKit::WebsiteDataStore::ShouldRetryOnFailure) + 48
3   WebKit                        	       0x10303af10 WebKit::WebProcessProxy::didReceiveSyncWebProcessProxyMessage(IPC::Connection&, IPC::Decoder&, WTF::UniqueRef<IPC::Encoder>&) + 304
4   WebKit                        	       0x102aef274 IPC::Connection::dispatchSyncMessage(IPC::Decoder&) + 236
5   WebKit                        	       0x102aef65c IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) + 300
6   WebKit                        	       0x102aec254 IPC::Connection::SyncMessageState::ConnectionAndIncomingMessage::dispatch() + 36
7   WebKit                        	       0x102aec440 IPC::Connection::SyncMessageState::dispatchMessagesAndResetDidScheduleDispatchMessagesForConnection(IPC::Connection&) + 460
8   JavaScriptCore                	       0x10678ab54 WTF::RunLoop::performWork() + 168
9   JavaScriptCore                	       0x10678b528 WTF::RunLoop::performWork(void*) + 36
10  CoreFoundation                	       0x1b2c74bbc CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION + 28
11  CoreFoundation                	       0x1b2c74b08 __CFRunLoopDoSource0 + 208
12  CoreFoundation                	       0x1b2c747f4 __CFRunLoopDoSources0 + 268
13  CoreFoundation                	       0x1b2c73168 __CFRunLoopRun + 820
14  CoreFoundation                	       0x1b2c72694 CFRunLoopRunSpecific + 600
15  HIToolbox                     	       0x1bb7e8990 RunCurrentEventLoopInMode + 292
16  HIToolbox                     	       0x1bb7e8704 ReceiveNextEventCommon + 552
17  HIToolbox                     	       0x1bb7e84c4 _BlockUntilNextEventMatchingListInModeWithFilter + 72
18  AppKit                        	       0x1b57c7aec _DPSNextEvent + 844
19  AppKit                        	       0x1b57c6390 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
20  AppKit                        	       0x1b57b83b0 -[NSApplication run] + 596
21  AppKit                        	       0x1b5789a84 NSApplicationMain + 1064
22  dyld                          	       0x1004950f4 start + 520
```

Asan output:

```
    Error: Browser closed.
    ==================== Browser output: ====================
    <launching> /Users/andreylushnikov/prog/playwright/browser_patches/webkit/pw_run.sh --inspector-pipe --headless --no-startup-window
    <launched> pid=30441
    [pid=30441][err] AddressSanitizer:DEADLYSIGNAL
    [pid=30441][err] =================================================================
    [pid=30441][err] ==30446==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000d0 (pc 0x000114e07eac bp 0x000115be9750 sp 0x00016d570410 T0)
    [pid=30441][err] ==30446==The signal is caused by a UNKNOWN memory access.
    [pid=30441][err] ==30446==Hint: address points to the zero page.
    [pid=30441][err]     #0 0x114e07eac in WTF::RefPtr<WebKit::NetworkProcessProxy, WTF::RawPtrTraits<WebKit::NetworkProcessProxy>, WTF::DefaultRefDerefTraits<WebKit::NetworkProcessProx
y> >::operator!() const RefPtr.h:86
    [pid=30441][err]
    [pid=30441][err] ==30446==Register values:
    [pid=30441][err]  x[0] = 0x00000000000000d0   x[1] = 0x0000000110f0c080   x[2] = 0x000000016d570690   x[3] = 0x0000000000000001
    [pid=30441][err]  x[4] = 0x000000016d570680   x[5] = 0x0000000000000001   x[6] = 0x000000016cd78000   x[7] = 0x0000000000000001
    [pid=30441][err]  x[8] = 0x0000000000000000   x[9] = 0x000000000000001a  x[10] = 0x0000000115be9698  x[11] = 0x000000010fac2e10
    [pid=30441][err] x[12] = 0x00000001b2c72694  x[13] = 0x0000000000000000  x[14] = 0x00000000157b6223  x[15] = 0x0000000000000006
    [pid=30441][err] x[16] = 0x00000001b2bbfe40  x[17] = 0x0000000102eb85c8  x[18] = 0x0000000000000000  x[19] = 0x000000016d570460
    [pid=30441][err] x[20] = 0x0000000000000000  x[21] = 0x0000000000000000  x[22] = 0x00000000000000d0  x[23] = 0x000000016d570690
    [pid=30441][err] x[24] = 0x0000007000020000  x[25] = 0x000000016d570420  x[26] = 0x000000702dace084  x[27] = 0x000000016d5704e0
    [pid=30441][err] x[28] = 0x000000702dace09c     fp = 0x000000016d570410     lr = 0x0000000115be9750     sp = 0x000000016d570410
    [pid=30441][err] AddressSanitizer can not provide additional info.
    [pid=30441][err] SUMMARY: AddressSanitizer: SEGV RefPtr.h:86 in WTF::RefPtr<WebKit::NetworkProcessProxy, WTF::RawPtrTraits<WebKit::NetworkProcessProxy>, WTF::DefaultRefDerefTraits<W
ebKit::NetworkProcessProxy> >::operator!() const
    [pid=30441][err] ==30446==ABORTING
    [pid=30441][err] /Users/andreylushnikov/prog/playwright/browser_patches/webkit/pw_run.sh: line 3: 30446 Abort trap: 6           DYLD_FRAMEWORK_PATH="$DYLIB_PATH" DYLD_LIBRARY_PATH="
$DYLIB_PATH" "$PLAYWRIGHT" "$@"
        at /Users/andreylushnikov/prog/playwright/packages/playwright-core/src/server/webkit/wkConnection.ts:141:57
        at new Promise (<anonymous>)
        at WKSession.send (/Users/andreylushnikov/prog/playwright/packages/playwright-core/src/server/webkit/wkConnection.ts:140:12)
        at WKBrowserContext._doClose (/Users/andreylushnikov/prog/playwright/packages/playwright-core/src/server/webkit/wkBrowser.ts:328:41)
        at WKBrowserContext.close (/Users/andreylushnikov/prog/playwright/packages/playwright-core/src/server/browserContext.ts:307:20)
        at BrowserContextDispatcher.close (/Users/andreylushnikov/prog/playwright/packages/playwright-core/src/dispatchers/browserContextDispatcher.ts:172:5)
        at DispatcherConnection.dispatch (/Users/andreylushnikov/prog/playwright/packages/playwright-core/src/dispatchers/dispatcher.ts:273:22)
```

**Comment by aslushnikov** [comment]
Debug build:

```
  pw:browser <launching> /Users/andreylushnikov/prog/playwright/browser_patches/webkit/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms                                      pw:browser <launched> pid=67236 +4ms
  pw:browser [pid=67236][err] ASSERTION FAILED: m_sessionID +4s                                                                                                                            pw:browser [pid=67236][err] /Volumes/Progged/webkit/Source/WebKit/WebProcess/WebProcess.cpp(1139) : WebKit::NetworkProcessConnection &WebKit::WebProcess::ensureNetworkProcessConnectio
n() +0ms
  pw:browser [pid=67236][err] 1   0x14c848dc4 WTFCrash +4ms
  pw:browser [pid=67236][err] 2   0x11db2dae4 std::__1::optional<JSC::JSValue>::optional<JSC::JSValue, 0>(JSC::JSValue&&) +7ms
  pw:browser [pid=67236][err] 3   0x121ce7f90 WebKit::WebProcess::ensureNetworkProcessConnection() +2ms
  pw:browser [pid=67236][err] 4   0x121235980 WebKit::WebProcess::updateProcessName(WebKit::WebProcess::IsInProcessInitialization) +3ms
  pw:browser [pid=67236][err] 5   0x121234814 WebKit::WebProcess::platformInitializeWebProcess(WebKit::WebProcessCreationParameters&) +2ms
  pw:browser [pid=67236][err] 6   0x121ce4900 WebKit::WebProcess::initializeWebProcess(WebKit::WebProcessCreationParameters&&) +2ms
  pw:browser [pid=67236][err] 7   0x123563eac void IPC::callMemberFunctionImpl<WebKit::WebProcess, void (WebKit::WebProcess::*)(WebKit::WebProcessCreationParameters&&), std::__1::tuple<
WebKit::WebProcessCreationParameters>, 0ul>(WebKit::WebProcess*, void (WebKit::WebProcess::*)(WebKit::WebProcessCreationParameters&&), std::__1::tuple<WebKit::WebProcessCreationParamete
rs>&&, std::__1::integer_sequence<unsigned long, 0ul>) +3ms
  pw:browser [pid=67236][err] 8   0x1235620d8 void IPC::callMemberFunction<WebKit::WebProcess, void (WebKit::WebProcess::*)(WebKit::WebProcessCreationParameters&&), std::__1::tuple<WebK
it::WebProcessCreationParameters>, std::__1::integer_sequence<unsigned long, 0ul> >(std::__1::tuple<WebKit::WebProcessCreationParameters>&&, WebKit::WebProcess*, void (WebKit::WebProces
s::*)(WebKit::WebProcessCreationParameters&&)) +2ms
  pw:browser [pid=67236][err] 9   0x12354e19c void IPC::handleMessage<Messages::WebProcess::InitializeWebProcess, WebKit::WebProcess, void (WebKit::WebProcess::*)(WebKit::WebProcessCrea
tionParameters&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebProcess*, void (WebKit::WebProcess::*)(WebKit::WebProcessCreationParameters&&)) +3ms
  pw:browser [pid=67236][err] 10  0x12354a96c WebKit::WebProcess::didReceiveWebProcessMessage(IPC::Connection&, IPC::Decoder&) +2ms
  pw:browser [pid=67236][err] 11  0x121cec31c WebKit::WebProcess::didReceiveMessage(IPC::Connection&, IPC::Decoder&) +3ms
  pw:browser [pid=67236][err] 12  0x120368658 IPC::Connection::dispatchMessage(IPC::Decoder&) +2ms
  pw:browser [pid=67236][err] 13  0x12036971c IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) +3ms
  pw:browser [pid=67236][err] 14  0x12036af64 IPC::Connection::dispatchOneIncomingMessage() +2ms
  pw:browser [pid=67236][err] 15  0x1203a8414 IPC::Connection::enqueueIncomingMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >)::$_14::operator()() +3
ms
  pw:browser [pid=67236][err] 16  0x1203a82f4 WTF::Detail::CallableWrapper<IPC::Connection::enqueueIncomingMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decod
er> >)::$_14, void>::call() +2ms
  pw:browser [pid=67236][err] 17  0x14c8ae1a4 WTF::Function<void ()>::operator()() const +1ms
  pw:browser [pid=67236][err] 18  0x14ca1b868 WTF::RunLoop::performWork() +2ms
  pw:browser [pid=67236][err] 19  0x14ca25838 WTF::RunLoop::performWork(void*) +1ms

```

**Comment by yury-s** [comment]
I bisected it down to this upstream change: https://trac.webkit.org/changeset/287374/webkit

**Comment by yury-s** [comment]
... and turns out it was reverted in https://trac.webkit.org/changeset/287595/webkit because it triggered some assertion. So next roll should fix it.

**Comment by aslushnikov** [comment]
This is fixed now with the latest roll. 🎉
