### ISSUE TITLE
[Question] Switching to new window failing intermittently

### ISSUE THREAD

**Issue by davidhprotective** [microsoft/playwright#11534]
I am using PW with .Net - xUnit. I am currently working on a Login test where the homepage I navigate to automatically pops-up Okta sign-in window. I need to switch to that window and enter username/password and then switch back to the main window. (Okta window closes automatically after sign in). 

After navigating to the homepage, I am trying to add the new pop-up window to Context and switch to it with the below code:

`public IPage AddSignInWindowToContextAndSwitchToIt(IBrowserContext context)`
        `{`
            `IPage signInWindow = null;`

            //Attempt count to switch to pop up sign in window
            int counter = 0;

            while (signInWindow == null && counter < 6)
            {
                ++counter;
                context.Page += async (_, page) =>
                {
                    page.WaitForLoadStateAsync().Wait();
                    Console.WriteLine(await page.TitleAsync());
                };

                signInWindow = SwitchToSignInWindow(context.Pages);
                Thread.Sleep(1000);
            }
            return signInWindow;
        }

        public IPage SwitchToSignInWindow(IReadOnlyList<IPage> pages)
        {
            foreach (var page in pages)
            {
                if (page.TitleAsync().Result.Contains("Sign in to your account"))
                {
                    return page;
                }
            }
            return null;
        }`

I pass BrowserContext instance from the Test class that calls this method. 

`[Collection("Functional Test Collection")]`
    `public class LoginTests : IDisposable`
    `{`
        `private readonly LoginPageDriver _pageDriver;`
        `private readonly TestConfiguration _config;`
        `private readonly FunctionalTestFixture _fixture;`
        `private readonly IBrowserContext _context;`

        public LoginTests(FunctionalTestFixture fixture)
        {
            this._fixture = fixture;
            this._context = this._fixture.NewContext();
            this._pageDriver = new LoginPageDriver(this._context);
            this._config = new TestConfiguration();
        }

        [Fact]
        public void VerifyLogin()
        {
            _pageDriver.NavigateTo(_config.UiBaseUrl);
            var title = _pageDriver.GetTitle();
            Assert.Equal("Dashboard Experience", title);
            var signInWindow = _pageDriver.AddSignInWindowToContextAndSwitchToIt(this._context);
            _pageDriver.CompleteOktaSignIn(signInWindow, _config.Auth.TestUserName, _config.Auth.TestUserPassword);
            var mainWindow = _pageDriver.SwitchToMainWindow(this._context.Pages);
            var visibility = _pageDriver.IsSearchBoxVisibleAsync(mainWindow);
            Assert.True(visibility, "Search Input not Visible!");
        }

        public void Dispose()
        {
            _context?.DisposeAsync();
        }
    }`

When I run this test, I intermittently get below error:

`---- System.AggregateException : One or more errors occurred. (Execution context was destroyed, most likely because of a navigation)`
`-------- Microsoft.Playwright.PlaywrightException : Execution context was destroyed, most likely because of a navigation`
`---- The following constructor parameters did not have matching fixture data: PoliciesTestFixture fixture`
  `Stack Trace:`

`----- Inner Stack Trace #1 (System.AggregateException) -----`
  ` at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)`
  ` at System.Threading.Tasks.Task`1.get_Result()`
   at AcceptanceTests.Drivers.LoginPageDriver.SwitchToSignInWindow(IReadOnlyList`1 pages) in ..\src\Api\AcceptanceTests\Drivers\LoginPageDriver.cs:line 63
   at AcceptanceTests.Drivers.LoginPageDriver.AddSignInWindowToContextAndSwitchToIt(IBrowserContext context) in ...\src\Api\AcceptanceTests\Drivers\LoginPageDriver.cs:line 52
   at AcceptanceTests.Fixtures.PoliciesTestFixture.LoginToDashboard() in 
...\src\Api\AcceptanceTests\Fixtures\PoliciesTestFixture.cs:line 37
   at AcceptanceTests.Fixtures.PoliciesTestFixture..ctor(FunctionalTestFixture fixture) in ...\src\Api\AcceptanceTests\Fixtures\PoliciesTestFixture.cs:line 24
----- Inner Stack Trace -----
   at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.Transport.Channels.FrameChannel.TitleAsync()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----`

`TestFixture` related error seems like a false flag and being thrown just because another error has occured. The source of the `context was destroyed` error is pointing to the `foreach` loop above.

Any suggestions what I might be doing wrong here?

**Comment by mxschmitt** [comment]
In Playwright there is not something called "switching to a window", you can just use a specific page or frame and it works.
Instead of using `Thread.Sleep(1000);` I would recommend using `await Page.WaitForTimeout(1000)` otherwise the events are not coming in.

What you probably want is BrowserContext.WaitForPage see here: https://playwright.dev/dotnet/docs/next/api/class-browsercontext#browser-context-wait-for-page
