### ISSUE TITLE
[BUG] Old Attachment API Crashes Base Reporter With Undefineds

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#11565]
**Context:**
- Playwright Version: ToT

**Code Snippet**

```ts
test.only('example', ({}, testInfo) => {
  testInfo.attachments.push({
    body: undefined,
    contentType: "text/plain",
    name: "example.txt",
  });

  expect(1).toBe(2);
});
```

**Describe the bug**

If a user explicitly pushes onto the attachments array like above (instead of using the new [async attachments API](https://playwright.dev/docs/api/class-testinfo#test-info-attach) introduced in v1.18), the base reporter currently crashes:

```
…/packages/playwright-test/lib/reporters/base.js:279
            let text = attachment.body.toString();
                                       ^

TypeError: Cannot read property 'toString' of undefined
    at formatFailure (…/packages/playwright-test/lib/reporters/base.js:279:40)
    at LineReporter.onTestEnd (…/packages/playwright-test/lib/reporters/line.js:85:43)
    at Multiplexer.onTestEnd (…/playwright/packages/playwright-test/lib/reporters/multiplexer.js:69:124)
    at Dispatcher._reportTestEnd (…/playwright/packages/playwright-test/lib/dispatcher.js:531:186)
    at Worker.onTestEnd (…/playwright/packages/playwright-test/lib/dispatcher.js:218:12)
    at Worker.emit (events.js:400:28)
    at Worker.emit (domain.js:470:12)
    at ChildProcess.<anonymous> (…/playwright/packages/playwright-test/lib/dispatcher.js:585:12)
    at ChildProcess.emit (events.js:400:28)
```

The new [v1.18 async attachments API](https://playwright.dev/docs/api/class-testinfo#test-info-attach) method handles these cases gracefully (and reports the errors nicely), so the recommendation for user-land code should be to use the new async API (I think).

However, the crash that can be triggered with the older push strategy is undesirable as it crashes the whole test runner, so it might be desirable to have more error handling in the reporter (or elsewhere).

cc: @dgozman What are your thoughts? I'm inclined to say "manually pushing onto the attachments array is deprecated, only use the new [v1.18 async attach API](https://playwright.dev/docs/api/class-testinfo#test-info-attach)" which was introduced to handle the fact that with the manual push onto the array, the state of the world can change by the time the reporter needs to use it, plus pushing onto the array defers possibility of validation until later.

**Comment by rwoll** [comment]
> The new v1.18 async attachments API method handles these cases gracefully (and reports the errors nicely), so the recommendation for user-land code should be to use the new async API (I think).

In this case "gracefully" means the new API fails the test, gives a nice error to the user, and the invalid attachment will not be added to the array, so the test reporter will never see the invalid attachments objects.
