### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liuyazhou1991** [microsoft/playwright#11648]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows
- Node.js version: 12.22, 14.6
- Browser: Chromium
-Python version: 3.8 x86

**Code Snippet**

from playwright.sync_api import sync_playwright

def run(playwright):

    browser = playwright.chromium.connect_over_cdp("http://localhost:9222")
    page = browser.new_page()
    page.goto("http://example.com/")

with sync_playwright() as playwright:
    run(playwright)

**Describe the bug**

Sometimes report mistakes：
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000002674D05BF78>
Traceback (most recent call last):
  File "C:\Python\lib\asyncio\base_subprocess.py", line 127, in __del__
  File "C:\Python\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Python\lib\asyncio\proactor_events.py", line 86, in close
  File "C:\Python\lib\asyncio\base_events.py", line 694, in call_soon
  File "C:\Python\lib\asyncio\base_events.py", line 480, in _check_closed
RuntimeError: Event loop is closed

**Comment by aslushnikov** [comment]
@liuyazhou1991 well, this doesn't share much details. Can you help us reproduce this? We need something that we can run locally and see the error ourselves!

**Comment by liuyazhou1991** [comment]
@aslushnikov Not every run will make mistakes, sometimes. Just run the following code to reproduce. The premise is that it has been connected through chrome devtools protocol：
from playwright.sync_api import sync_playwright
def run(playwright):

    browser = playwright.chromium.connect_over_cdp("http://localhost:9222")
    page = browser.new_page()
    page.goto("http://example.com/")
for i in range(10):
    with sync_playwright() as playwright:
        run(playwright)
