### ISSUE TITLE
[REGRESSION]: test.fail() doesn't work on expectations in listeners

### ISSUE THREAD

**Issue by lukaw3d** [microsoft/playwright#11666]
**Context:**
- GOOD Playwright Version: @playwright/test@1.16.3
- BAD Playwright Version: @playwright/test@1.17.0+
- Operating System: Linux

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test('good in all versions', async ({ page }) => {
  test.fail();
  await page.evaluate(() => console.log(''))
  expect(1).toBe(2);
});

test('bad in 1.17 and 1.18', async ({ page }) => {
  test.fail();
  page.on('console', () => {
    expect(1).toBe(2);
  });
  await page.evaluate(() => console.log(''))
});
```

**Describe the bug**

See test results in different @playwright/test versions https://github.com/lukaw3d/playwright-fail-reproduce/actions/runs/1753794024. When running `npx playwright test` with @playwright/test versions <=1.16.3, the result was `2 passed`. After 1.17.0, second test is causing the test suit to fail with
```
Error: expect(received).toBe(expected) // Object.is equality

Expected: 2
Received: 1

    at Page.<anonymous> (/home/runner/work/playwright-fail-reproduce/playwright-fail-reproduce/expect-fail.spec.ts:12:15)
    at Page.emit (node:events:390:28)
    at Proxy.<anonymous> (/home/runner/work/playwright-fail-reproduce/playwright-fail-reproduce/node_modules/playwright-core/lib/client/page.js:130:16)
    at Proxy.emit (node:events:390:28)
    at Connection.dispatch (/home/runner/work/playwright-fail-reproduce/playwright-fail-reproduce/node_modules/playwright-core/lib/client/connection.js:208:21)
    at Immediate.<anonymous> (/home/runner/work/playwright-fail-reproduce/playwright-fail-reproduce/node_modules/playwright-core/lib/inProcessFactory.js:50:83)
    at processImmediate (node:internal/timers:464:21)

  1 skipped
  1 passed (680ms)
Error: Process completed with exit code 1.
```

**Comment by aslushnikov** [comment]
@lukaw3d Indeed, thanks for filing! Dmitry might do something about this in 1.19.

Meanwhile: this "shape" of test is not very reliable since it implies that the "console" event happens before the `page.evaluate` returns. While this happens to be true for the `'console'` event, this is not guaranteed, so in general the approach should be something like this:

```js
import { test, expect } from '@playwright/test';

test('bad in 1.17 and 1.18', async ({ page }) => {
  test.fail();
  const messages = []; 
  page.on('console', (msg) => messages.push(msg));
  await Promise.all([
    page.evaluate(() => console.log(''),
    page.waitForEvent('console'), // always wait for the event to happen while triggering it!
  ]);
  expect(messages.length).toBe(2);
});
```

**Comment by lukaw3d** [comment]
Yep yep, thanks!
