### ISSUE TITLE
[BUG]Not able to call APIRequest method request.get

### ISSUE THREAD

**Issue by SergeyGorbenko** [microsoft/playwright#11834]
**Context:**
- Playwright Version: 1.18.0
- Operating System: Windows
- Node.js version: 16.13.2
- Browser: All

**Code Snippet**

```javascript
const {test, expect, request} = require('@playwright/test');

test.only('test', async () => {
    const response = await request.get('https://playwright.dev');
})
```
```
TypeError: request.get is not a function


    > 24 |         const response = await request.get('https://playwright.dev');
            |                                        ^


        at C:\Users\*****\WebstormProjects\e2e_tests\tests\registration.spec.js:24:40
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at C:\Users\*****\WebstormProjects\e2e_tests\node_modules\@playwright\test\lib\workerRunner.js:529:7
        at WorkerRunner._runFn (C:\Users\*****\WebstormProjects\e2e_tests\node_modules\@playwright\test\lib\workerRunner.js:575:7)
        at WorkerRunner._runTestWithBeforeHooks (C:\Users\******\WebstormProjects\e2e_tests\node_modules\@playwright\test\lib\workerRunner.js:523:20)
```

**Comment by SergeyGorbenko** [comment]
I'm not write parameter ( request ) in test function
