### ISSUE TITLE
[BUG] @playwright/test@next build from 1.19.0-alpha-feb-2-2022 onwards is bad

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#11841]
**Context:**
- Playwright Version: [1.19.0-alpha-feb-2-2022]
- Operating System: [Mac]
- Node.js version: [v17.2.0]
- Browser: [e.g. All]
- Extra: [Feb-1-2022 builds works correctly]

**Code Snippet**

playwright-config.js
```javascript

```

pw_global_setup_demo.js
```javascript
const fs = require('fs');
const path = require('path');

const delay_time = ms => new Promise(res => setTimeout(res, ms));

module.exports = async () => {
    const opSys = process.platform;
    console.log(opSys);
    process.env.JSONPath = path.resolve('./common/data_config_json/test.json');
    console.log(process.env.JSONPath);
};
```

pw_sample.js
```javascript
const { test, expect } = require('@playwright/test');
const fs = require("fs");
const path = require('path');

console.log('PRINT ENV VARIABLE FROM GLOBAL SETUP ' + process.env.JSONPath);
let JSONPath_Working =  JSON.parse(fs.readFileSync('/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/common/data_config_json/test.json'));
console.log(JSONPath_Working);

let JSONPath_NotWorking =  JSON.parse(fs.readFileSync(process.env.JSONPath));
console.log(JSONPath_NotWorking);

test.describe.serial('suite', () => {

    test('basic test1', async ({ page,browser },testInfo) => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        await expect(title).toHaveText('Playwright');

    });

});
```

**Describe the bug**
It appears something got changed in 1.19.0-alpha-feb-2-2022 build onwards. Environment variables set in global setup are no longer resolved in spec file. In the output you can see the value of file path set by environment variable is undefined.

**Log output - 1.19.0-alpha-feb-2-2022** - Failed Test Case
```javascript
{ test_json: 'playwright' }

Running 0 test using 0 worker

TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/test/demo/pw_sample.js:10:42)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Loader._requireOrImport (/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/node_modules/@playwright/test/lib/loader.js:269:14)
    at Loader.loadTestFile (/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/node_modules/@playwright/test/lib/loader.js:139:18)
    at Runner._runFiles (/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/node_modules/@playwright/test/lib/runner.js:275:44)
    at Runner._run (/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/node_modules/@playwright/test/lib/runner.js:208:23)
    at TimeoutRunner.run (/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/node_modules/playwright-core/lib/utils/async.js:38:14)
    at raceAgainstTimeout (/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/node_modules/playwright-core/lib/utils/async.js:85:15)

=================
 no tests found.
=================

```

**Log output - 1.19.0-alpha-feb-2-2022** - if i comment out the environment variable in spec file to read the JSON file
```javascript
PRINT ENV VARIABLE FROM GLOBAL SETUP undefined
{ test_json: 'playwright' }

Running 1 test using 1 worker

darwin
/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/common/data_config_json/test.json
PRINT ENV VARIABLE FROM GLOBAL SETUP /Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/common/data_config_json/test.json
{ test_json: 'playwright' }
  ✓  [demo1] › test/demo/pw_sample.js:15:5 › suite › basic test1 (3s)

```

**Logout - 1.19.0-alpha-feb-1-2022**
```javascript
darwin
/Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/common/data_config_json/test.json
PRINT ENV VARIABLE FROM GLOBAL SETUP /Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/common/data_config_json/test.json
{ test_json: 'playwright' }

Running 1 test using 1 worker

PRINT ENV VARIABLE FROM GLOBAL SETUP /Users/ravuri/Documents/pw-automation-bitbucket/kb-automation-playwright/common/data_config_json/test.json
{ test_json: 'playwright' }
  ✓  [demo1] › test/demo/pw_sample.js:15:5 › suite › basic test1 (3s)


```

**Comment by yury-s** [comment]
You are setting `WSSComDCPath` in global setup but print `KBAdmComDCPath` in the test, is it a bug or where `KBAdmComDCPath` should come from?

**Comment by vsravuri** [comment]
@yury-s I'll correct the repro steps. Trying to simplify the steps.

**Comment by vsravuri** [comment]
@yury-s I found the root cause. Starting Feb-2 build onwards, Global-Setup is executed after parsing all the spec files. I setup all my environment variables in Global-Setup and access those in Spec files. As the order is changed, my spec files don't have the environment variables defined while parsing the spec files. You can see the difference in output of Feb 1 and Feb2 builds. Kindly let me know if you need more information.

**Comment by yury-s** [comment]
It was broken in https://github.com/microsoft/playwright/pull/11758

**Comment by pavelfeldman** [comment]
@vsravuri thank you for reporting this. We are in fact considering breaking our contract. We'd like to make our operation more efficient and running global setup before we are discovering tests is standing in our way. The current recommendation is to set all environment variables from the config itself, so that you could use them both in your config and in your tests, for example like we do it here:

https://github.com/microsoft/create-playwright/blob/main/assets/playwright.config.ts#L8

Would this work for you?

**Comment by vsravuri** [comment]
@pavelfeldman Is the decision made or still being discussed ? If you confirm, i will start refactoring my code to move environment variables away from Global-Setup in order to be compatible with 1.19.

**Comment by vsravuri** [comment]
@pavelfeldman @yury-s I noticed another change in 1.19 build. globalTeardown is executed before the results are dumped in the output folder. This makes some of the operations i do as part of  globalTeardown failed as the results are not yet created in the output folder. I compress the results folder as part of globalTeardown. If you think i should file a new issue, kindly let me know.

**Comment by pavelfeldman** [comment]
@vsravuri running globalSetup after requiring tests unlocks several interesting features around error reporting, test discovery, etc. We also make global setup/teardown errors show up in the report.

Could you share more about the resources you are missing? test-results should be there by the time globalTeardown runs.

**Comment by vsravuri** [comment]
@pavelfeldman I made adjustments to my framework to accommodate globalSetup changes. I could see the benefit of this  change. I dump test results to outputFolder defined in config file. I enabled html & allure-playwright reporter in config file. I've created a repro.

**I do this in globalTeardown:**
1. Generate Allure Reports from Allure Results folder
2. Compress HTML Reports folder

When the test runs, globalTeardown script doesn't find the Allure Reports and HTML Reports folder in the outputFolder. This is change in behaviour compared to 1.18.1. Kindly suggest me if you have any other approach what i am trying to accomplish in globalTeardown script. My outputFolder is dynamic and unique for each test run.

pw_config_demo.js
```javascript
const fs = require('fs');
const path = require('path');
 /** @type {import('@playwright/test').PlaywrightTestConfig} */
    const config = {
        workers: 1,
        globalTimeout: 0,
        globalSetup: require.resolve('./pw_global_setup.js'),
        globalTeardown: require.resolve('./pw_global_teardown.js'),
        reporter: [
            ['list'],
            ['html', { outputFolder: process.env.PLAYWRIGHT_HTML_REPORT,open: "never" }],
            ['allure-playwright']
        ],
        reportSlowTests: null,
        use: {
            browserName: "chromium",
            channel: 'chrome',
            headless: false,
            viewport: {width: 1600, height: 825},
            ignoreHTTPSErrors: true,
            acceptDownloads: true,
            screenshot: 'only-on-failure',
            retries: 0,
        },
        projects: [
            {
                name: 'demo1',
                testDir: './test/demo',
                testMatch: 'pw_sample.js',
                outputDir: process.env.pwRptDir,
            },
        ]
    };
    module.exports = config;
```

pw_global_setup.js
```javascript
const fs = require('fs');
const path = require('path');
const moment = require('moment');

module.exports = async () => {
    const opSys = process.platform;
    let today = new Date();
    let dateStr = today.getDate() + '_' + (today.getMonth() + 1) + '_' + (today.getFullYear()) + '_' + today.getHours() + '_' + today.getMinutes() + '_' + today.getSeconds();
    process.env.dateStr = dateStr;
   process.env.PLAYWRIGHT_HTML_REPORT = '/tmp/' + process.env.npm_lifecycle_event + 'Rep_' + dateStr + '/html_result';
    process.env.ALLURE_RESULTS_DIR = '/tmp/' + process.env.npm_lifecycle_event + 'Rep_' + dateStr + '/allure_results';
    const pwTestReportDir = process.env.npm_lifecycle_event + 'Rep_' + dateStr + '/screen_video';
    process.env.pwRptDir = path.join('/tmp', pwTestReportDir);
}
```

pw_global_teardown
```javascript
const fs = require('fs');
const path = require('path');
const {exec} = require('child_process');
const zipAFolder = require('zip-a-folder');
module.exports = async () => {
    process.env.allureReportDir = '/tmp/' + process.env.npm_lifecycle_event + 'Rep_' + process.env.dateStr + '/allure_reports';
    let command = 'allure generate ' + process.env.ALLURE_RESULTS_DIR + ' --clean -o ' + process.env.allureReportDir;
    let allureResultsDir = path.resolve(process.env.ALLURE_RESULTS_DIR);
    let htmlResDir = path.resolve(process.env.PLAYWRIGHT_HTML_REPORT);

    if (fs.existsSync(allureResultsDir)) {
        console.log("global_teardown: Allure \"Results\" directory exist. Allure \"Reports\" directory is created");
        console.log('Run this command in current working directory to view \"Allure Report\" : allure open ' + process.env.allureReportDir);
        exec(command, (error, stdout, stderr) => {
            if (error) {
                console.error(`exec error: ${error}`);
                return;
            }
            console.log('Allure Reports Directory: ' + process.env.allureReportDir);
        });
    }
    else {
        console.log("global_teardown: Allure Results directory doesn't exist. Allure Reports directory not created");
    }

    if (fs.existsSync(htmlResDir)) {
        await zipAFolder.zip(htmlResDir,  '/tmp/archive.zip');
        console.log("global_teardown: HTML Results directory exist. HTML Results directory is compressed");
    } else {
        console.log("global_teardown: HTML Results directory doesn't exist. HTML Results directory not compressed");
    }
};
```

pw_sample.js
```javascript
const { test, expect } = require('@playwright/test');
test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const title = page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
});
```

**Comment by pavelfeldman** [comment]
How about you try to add your own reporter that collects results of other reporters on onEnd()?

**Comment by vsravuri** [comment]
@pavelfeldman Thanks for the suggestion, now it works for me. I moved the logic from globalTeardown to custom_reporter onEnd(). Now i wait for the reports to be available before performing the actions which i previously did in globalTeardown.

**Comment by dgozman** [comment]
For the record, [here is a description](https://github.com/microsoft/playwright/issues/12018) of the changes made in v1.19 and possible solutions. Thank you for reporting the issue!
