### ISSUE TITLE
[BUG] Protocol error (Browser.enable): Browser closed.

### ISSUE THREAD

**Issue by karolzlot** [microsoft/playwright#11882]
**Context:**
- Playwright Version: playwright==1.18.2
- Operating System: Windows 10 20H2
- Python version: 3.9.7
- Browser: Chromium works, but Firefox and WebKit stopped working
- Extra: vscode

**Code Snippet**

```python
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.firefox.launch(headless=False)
        # browser = await p.webkit.launch(headless=False)
        # browser = await p.chromium.launch(headless=False)
        
        page = await browser.new_page()
        await page.goto("http://playwright.dev")
        print(await page.title())
        await browser.close()

if __name__ == "__main__":
    asyncio.run(main())
```

**Describe the bug**

Today I started using playwright. I was able to run any browser, but suddenly at some point I stopped being able to run Firefox and Webkit, only Chrome starts.

What is weird that also "my" Firefox (which I had before installing playwright), also stopped working. Not a big issue because it is not my default browser anyway, but still.....

Logs for Firefox mode:

Exception details:
```
Exception has occurred: Error
Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\musli\AppData\Local\ms-playwright\firefox-1313\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\musli\AppData\Local\Temp\playwright_firefoxdev_profile-hCYhh3 -juggler-pipe -silent
<launched> pid=108760
=========================== logs ===========================
<launching> C:\Users\musli\AppData\Local\ms-playwright\firefox-1313\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\musli\AppData\Local\Temp\playwright_firefoxdev_profile-hCYhh3 -juggler-pipe -silent
<launched> pid=108760
============================================================
  File "[C:\moje\programowanie\projekty2022\playwright-project1\app1.py]()", line 6, in main
    browser = await p.firefox.launch(headless=False)
  File "[C:\moje\programowanie\projekty2022\playwright-project1\app1.py]()", line 16, in <module>
    asyncio.run(main())
```

Log with `$env:DEBUG="pw:api,pw:browser*,pw:protocol"`:

```
  pw:browser <launching> C:\Users\musli\AppData\Local\ms-playwright\firefox-1313\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\musli\AppData\Local\Temp\playwright_firefoxdev_profile-hCYhh3 -juggler-pipe -silent 
+0ms
  pw:browser <launched> pid=108760 +300ms
  pw:protocol SEND ► {"id":1,"method":"Browser.enable","params":{"attachToDefaultContext":false}} +0ms
  pw:protocol SEND ► {"id":2,"method":"Browser.getInfo"} +1ms
  pw:browser [pid=108760] <gracefully close start> +210ms
  pw:browser [pid=108760] <kill> +1ms
  pw:browser [pid=108760] <will force kill> +1ms
  pw:browser [pid=108760] taskkill stderr: 
  pw:browser INFO: No tasks running with the specified criteria.
  pw:browser  +489ms
  pw:browser [pid=108760] <process did exit: exitCode=2147483651, signal=null> +1ms
  pw:browser [pid=108760] starting temporary directories cleanup +1ms
  pw:browser [pid=108760] finished temporary directories cleanup +6ms
  pw:browser [pid=108760] <gracefully close end> +0ms
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\musli\.vscode\extensions\ms-python.python-2022.0.1786462952\pythonFiles\lib\python\debugpy\__main__.py", 
line 45, in <module>
    cli.main()
  File "c:\Users\musli\.vscode\extensions\ms-python.python-2022.0.1786462952\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\musli\.vscode\extensions\ms-python.python-2022.0.1786462952\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\moje\programowanie\projekty2022\playwright-project1\app1.py", line 16, in <module>
    asyncio.run(main())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\moje\programowanie\projekty2022\playwright-project1\app1.py", line 6, in main
    browser = await p.firefox.launch(headless=False)
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\async_api\_generated.py", line 11633, in launch
    await self._async(
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\_impl\_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\musli\AppData\Local\ms-playwright\firefox-1313\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\musli\AppData\Local\Temp\playwright_firefoxdev_profile-hCYhh3 -juggler-pipe -silent
<launched> pid=108760
=========================== logs ===========================
<launching> C:\Users\musli\AppData\Local\ms-playwright\firefox-1313\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\musli\AppData\Local\Temp\playwright_firefoxdev_profile-hCYhh3 -juggler-pipe -silent
<launched> pid=108760
============================================================
```

================================

Log from "my" Firefox:

```
AvailablePageFile: 14605176832
AvailablePhysicalMemory: 13270712320
AvailableVirtualMemory: 138531623591936
BackgroundTaskMode: 0
BlockedDllList: 
BuildID: 20220126154723
CrashTime: 1644045677
HeadlessMode: 0
InstallTime: 1643337855
ModuleSignatureInfo: {"Apple Inc.":["mdnsNSP.dll"],"Microsoft Corporation":["msvcp140.dll","VCRUNTIME140.dll","VCRUNTIME140_1.dll"],"Microsoft Windows":["wsock32.dll","DWrite.dll","winrnr.dll","wshbth.dll","pnrpnsp.dll","NapiNSP.dll","webauthn.dll","winmm.dll","npmproxy.dll","dbgcore.dll","dbghelp.dll","version.dll","dhcpcsvc.dll","dhcpcsvc6.DLL","winnsi.dll","nlaapi.dll","propsys.dll","netprofm.dll","uxtheme.dll","kernel.appcore.dll","windows.storage.dll","ntmarta.dll","IPHLPAPI.DLL","dnsapi.dll","mswsock.dll","cryptbase.dll","wldp.dll","msasn1.dll","profapi.dll","wintrust.dll","msvcp_win.dll","crypt32.dll","win32u.dll","bcryptPrimitives.dll","KERNELBASE.dll","ucrtbase.dll","gdi32full.dll","bcrypt.dll","nsi.dll","ole32.dll","SHCore.dll","msvcrt.dll","psapi.dll","gdi32.dll","ws2_32.dll","rpcrt4.dll","shlwapi.dll","advapi32.dll","user32.dll","shell32.dll","combase.dll","kernel32.dll","imm32.dll","clbcatq.dll","oleaut32.dll","sechost.dll","ntdll.dll"],"Mozilla Corporation":["firefox.exe","xul.dll","nss3.dll","mozglue.dll","lgpllibs.dll"]}
MozCrashReason: MOZ_RELEASE_ASSERT(((bool)(__builtin_expect(!!(!NS_FAILED_impl(rv)), 1))))
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 67
StartupCrash: 1
StartupTime: 1644045677
SystemMemoryUsePercentage: 61
ThreadIdNameMapping: 61024:"IPC I/O Parent",53232:"Timer",97692:"Link Monitor #1",45260:"Socket Thread",142704:"Permission",152316:"BackgroundThreadPool #1",
Throttleable: 1
TotalPageFile: 50746175488
TotalPhysicalMemory: 34292613120
TotalVirtualMemory: 140737488224256
URL: 
UptimeTS: 1.735
Vendor: Mozilla
Version: 96.0.3

Zgłoszenie to zawiera ponadto informacje na temat stanu programu w momencie wystąpienia awarii.
```

================================

Logs for Webkit mode:

Exception details:
```
Exception has occurred: Error
Browser closed.
==================== Browser output: ====================
<launching> C:\Users\musli\AppData\Local\ms-playwright\webkit-1596\Playwright.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window
<launched> pid=45408
[pid=45408][err] 1   00007FFB7F151319
[pid=45408][err] 2   00007FFB7F151199
[pid=45408][err] 3   00007FFB7F1CF68C
[pid=45408][err] 4   00007FFB7F178075
[pid=45408][err] 5   00007FFB7F178583
[pid=45408][err] 6   00007FFB7F16C144
[pid=45408][err] 7   00007FFB46EB1140
[pid=45408][err] 8   00007FFB46ECF17E
[pid=45408][err] 9   00007FFB46F434C1
[pid=45408][err] 10  00007FFB93F282C8
[pid=45408][err] 11  00007FF615C72828
[pid=45408][err] 12  00007FF615C72EDA
[pid=45408][err] 13  00007FFBBCE67034
[pid=45408][err] 14  00007FFBBD562651
=========================== logs ===========================
<launching> C:\Users\musli\AppData\Local\ms-playwright\webkit-1596\Playwright.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window
<launched> pid=45408
[pid=45408][err] 1   00007FFB7F151319
[pid=45408][err] 2   00007FFB7F151199
[pid=45408][err] 3   00007FFB7F1CF68C
[pid=45408][err] 4   00007FFB7F178075
[pid=45408][err] 5   00007FFB7F178583
[pid=45408][err] 6   00007FFB7F16C144
[pid=45408][err] 7   00007FFB46EB1140
[pid=45408][err] 8   00007FFB46ECF17E
[pid=45408][err] 9   00007FFB46F434C1
[pid=45408][err] 10  00007FFB93F282C8
[pid=45408][err] 11  00007FF615C72828
[pid=45408][err] 12  00007FF615C72EDA
[pid=45408][err] 13  00007FFBBCE67034
[pid=45408][err] 14  00007FFBBD562651
============================================================
  File "[C:\moje\programowanie\projekty2022\playwright-project1\app1.py]()", line 7, in main
    browser = await p.webkit.launch(headless=False)
  File "[C:\moje\programowanie\projekty2022\playwright-project1\app1.py]()", line 16, in <module>
    asyncio.run(main())
```

Log with `$env:DEBUG="pw:api,pw:browser*,pw:protocol"`:

```
  pw:browser <launching> C:\Users\musli\AppData\Local\ms-playwright\webkit-1596\Playwright.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window +0ms
  pw:browser <launched> pid=45408 +11ms
  pw:protocol SEND ► {"id":1,"method":"Playwright.enable"} +0ms
  pw:browser [pid=45408][err] 1   00007FFB7F151319 +23ms
  pw:browser [pid=45408][err] 2   00007FFB7F151199 +1ms 
  pw:browser [pid=45408][err] 3   00007FFB7F1CF68C +0ms 
  pw:browser [pid=45408][err] 4   00007FFB7F178075 +0ms 
  pw:browser [pid=45408][err] 5   00007FFB7F178583 +0ms 
  pw:browser [pid=45408][err] 6   00007FFB7F16C144 +0ms 
  pw:browser [pid=45408][err] 7   00007FFB46EB1140 +0ms 
  pw:browser [pid=45408][err] 8   00007FFB46ECF17E +0ms 
  pw:browser [pid=45408][err] 9   00007FFB46F434C1 +1ms 
  pw:browser [pid=45408][err] 10  00007FFB93F282C8 +0ms 
  pw:browser [pid=45408][err] 11  00007FF615C72828 +0ms 
  pw:browser [pid=45408][err] 12  00007FF615C72EDA +0ms
  pw:browser [pid=45408][err] 13  00007FFBBCE67034 +0ms
  pw:browser [pid=45408][err] 14  00007FFBBD562651 +1ms
  pw:browser [pid=45408] <gracefully close start> +2ms
  pw:browser [pid=45408] <kill> +0ms
  pw:browser [pid=45408] <will force kill> +1ms
  pw:browser [pid=45408] taskkill stderr: 
  pw:browser INFO: No tasks running with the specified criteria.
  pw:browser  +188ms
  pw:browser [pid=45408] <process did exit: exitCode=3221225477, signal=null> +0ms
  pw:browser [pid=45408] starting temporary directories cleanup +1ms
  pw:browser [pid=45408] finished temporary directories cleanup +3ms
  pw:browser [pid=45408] <gracefully close end> +0ms
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\musli\.vscode\extensions\ms-python.python-2022.0.1786462952\pythonFiles\lib\python\debugpy\__main__.py", 
line 45, in <module>
    cli.main()
  File "c:\Users\musli\.vscode\extensions\ms-python.python-2022.0.1786462952\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\musli\.vscode\extensions\ms-python.python-2022.0.1786462952\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\moje\programowanie\projekty2022\playwright-project1\app1.py", line 16, in <module>
    asyncio.run(main())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\moje\programowanie\projekty2022\playwright-project1\app1.py", line 7, in main
    browser = await p.webkit.launch(headless=False)
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\async_api\_generated.py", line 11633, in launch
    await self._async(
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\_impl\_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "c:\moje\programowanie\projekty2022\playwright-project1\.venv\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Users\musli\AppData\Local\ms-playwright\webkit-1596\Playwright.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window
<launched> pid=45408
[pid=45408][err] 1   00007FFB7F151319
[pid=45408][err] 2   00007FFB7F151199
[pid=45408][err] 3   00007FFB7F1CF68C
[pid=45408][err] 4   00007FFB7F178075
[pid=45408][err] 5   00007FFB7F178583
[pid=45408][err] 6   00007FFB7F16C144
[pid=45408][err] 7   00007FFB46EB1140
[pid=45408][err] 8   00007FFB46ECF17E
[pid=45408][err] 9   00007FFB46F434C1
[pid=45408][err] 10  00007FFB93F282C8
[pid=45408][err] 11  00007FF615C72828
[pid=45408][err] 12  00007FF615C72EDA
[pid=45408][err] 13  00007FFBBCE67034
[pid=45408][err] 14  00007FFBBD562651
=========================== logs ===========================
<launching> C:\Users\musli\AppData\Local\ms-playwright\webkit-1596\Playwright.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window
<launched> pid=45408
[pid=45408][err] 1   00007FFB7F151319
[pid=45408][err] 2   00007FFB7F151199
[pid=45408][err] 3   00007FFB7F1CF68C
[pid=45408][err] 4   00007FFB7F178075
[pid=45408][err] 5   00007FFB7F178583
[pid=45408][err] 6   00007FFB7F16C144
[pid=45408][err] 7   00007FFB46EB1140
[pid=45408][err] 8   00007FFB46ECF17E
[pid=45408][err] 9   00007FFB46F434C1
[pid=45408][err] 10  00007FFB93F282C8
[pid=45408][err] 11  00007FF615C72828
[pid=45408][err] 12  00007FF615C72EDA
[pid=45408][err] 13  00007FFBBCE67034
[pid=45408][err] 14  00007FFBBD562651
============================================================
```

**Comment by karolzlot** [comment]
Something probably not related to playwright, because some other apps also stopped working...

After restart of system it works again ok.
