### ISSUE TITLE
[BUG] Can't execute playwright tests on cloud based browser farm (saucelabs)

### ISSUE THREAD

**Issue by Ivan-Katovich** [microsoft/playwright#12031]
**Context:**
- Playwright Version: [1.18.1]
- Operating System: [Windows 10]
- Node.js version: [v14.17.6]
- Browser: [Chromium, Chrome]
- Extra: [cloud based selenium grid on https://saucelabs.com/]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { test, expect } = require('@playwright/test');

function sleep(timeout) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve();
        }, timeout);
    });
}

test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const title = page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
    await sleep(10000);
});
```
run the tests with:
**npx playwright test --headed**

have such output: 

```
Running 1 test using 1 worker

  x  tests\test.js:11:1 › basic test (4s)


  1) tests\test.js:11:1 › basic test ===============================================================

    browserType.launch: connect ECONNREFUSED 127.0.0.1:49218
    =========================== logs ===========================
    <selenium> using additional capabilities "{"sauce:options": {"username": "ivan_kotovich", "accessKey": "e5512834-00f7-4eac-874e-12fe82489cb1"}}"
    <selenium> connecting to https://ondemand.eu-central-1.saucelabs.com:443/wd/hub/
    <selenium> connected to sessionId=a10f573c4021498a813b90eda5337d71
    <selenium> using selenium v3
    <selenium> retrieved endpoint http://localhost:49218 for sessionId=a10f573c4021498a813b90eda5337d71
    <selenium> unable to resolve endpoint ip for sessionId=a10f573c4021498a813b90eda5337d71, running in standalone?
    <ws preparing> retrieving websocket url from http://localhost:49218/
    <selenium> disconnecting from sessionId=a10f573c4021498a813b90eda5337d71
    <selenium> disconnected from sessionId=a10f573c4021498a813b90eda5337d71
    ============================================================

        at Object.browserWorkerFixture [as fn] (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\index.js:579:38)
        at Fixture.setup (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:78:77)
        at FixtureRunner.setupFixtureForRegistration (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:332:5)
        at Fixture.setup (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:59:19)
        at FixtureRunner.setupFixtureForRegistration (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:332:5)
        at Fixture.setup (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:59:19)
        at FixtureRunner.setupFixtureForRegistration (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:332:5)
        at Fixture.setup (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:59:19)
        at FixtureRunner.setupFixtureForRegistration (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:332:5)
        at FixtureRunner.resolveParametersForFunction (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\fixtures.js:314:23)
        at D:\code\own\pure-playwright\node_modules\@playwright\test\lib\workerRunner.js:524:22
        at WorkerRunner._runFn (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\workerRunner.js:575:7)
        at WorkerRunner._runTestWithBeforeHooks (D:\code\own\pure-playwright\node_modules\@playwright\test\lib\workerRunner.js:523:20)


  1 failed
    tests\test.js:11:1 › basic test ================================================================

```

I use such system variables:
$env:SELENIUM_REMOTE_URL='https://ondemand.eu-central-1.saucelabs.com:443/wd/hub'
$env:SELENIUM_REMOTE_CAPABILITIES='{"sauce:options": {"username": "ivan_abc", "accessKey": "q1w2e3r4t5"}}'

screenshot from saucelabs: 

![0000screenshot](https://user-images.githubusercontent.com/7858279/153620239-9a4f63b0-3db2-4bdb-aa26-84306b5f08ea.png)

**Describe the bug**

The test works fine for local grid but doesn't work for saucelabs grid

Add any other details about the problem here.

Local grid opens 2 browsers and only one of them opens url from the test another one just empty with 'data' word in url line

**Comment by dgozman** [comment]
Judging by the logs, this cloud browser farm exposes Selenium v3.

As explained in the documentation, Selenium v3 does not support the required CDP capability for Playwright to work. Therefore, it is supported in a best-effort manner, in a setup where grid nodes are directly accessible from the machine that runs Playwright. This is most likely not the case with cloud based browser farm.

I don't think we can help here. Sorry! Please comment here if I am mistaken.

**Comment by Unit111** [comment]
[Ivan-Katovich](https://github.com/Ivan-Katovich) did you manage to resolve this issue? I have the exact same problem. Running tests against Moon deployed in Kubernetes. My logs also say "using selenium v3". I would try to Selenium Grid 4 but I don't want to risk breaking my colleagues tests without being sure.
