### ISSUE TITLE
[Feature] Fully Extendable `tsconfig.json`

### ISSUE THREAD

**Issue by nickofthyme** [microsoft/playwright#12043]
I'd like the ability to extend the default playwright `tsconfig.json` beyond just the currently allowed `compilerOptions` of `baseUrl` and `path`.

I am using playwright to test a charting library in a mono repo and I'd like the ability to import constants from the library to facilitate testing. However, any typescript import from outside of the playwright base directory throws a typescript error.

The current [ability](https://playwright.dev/docs/test-typescript) to transpile the tests, and whatever else, before running the playwright tests would work but makes it difficult to store the screenshots in the desired directory.

I'd like the ability to provide a path to a `tsconfig.json` or extend a current `tsconfig.json`. I realize this may open up issues errors when transpiling playwright with an incompatible `tsconfig.json` but there may be a way to safeguard against this.

**Comment by pavelfeldman** [comment]
Could you provide an example of what does not work? You should be able to import the constants without problems.

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by nickofthyme** [comment]
Sorry was on vacay.

Yeah, the issue I have is that the constants are not simple strings and are often not well isolated or not able to be isolated such that they rely on importing other files, which then throws an error. This feels like an edge case but I think the ability to extend the `tsconfig.json` would be a broadly useful feature.

An example error I ran into is reproduced on https://github.com/nickofthyme/elastic-charts/tree/playwright-config-repro. Pull down branch then run...

```
yarn
cd e2e
ENV_URL=https://ech-e2e-ci.web.app/e2e yarn test:playwright legend_stories.test.ts -x
```

This results in the following error. Here `light_theme.ts` file is a transitive dependency of the `Position` constant import file, which thinks [`ColorVariant`](https://github.com/nickofthyme/elastic-charts/blob/9e2566cc9ae057e33a05b65093ba039acbe48442/packages/charts/src/utils/themes/light_theme.ts#L43) is undefined.

```
Using config at /Users/user/elastic-charts/e2e/playwright.config.ts

TypeError: Cannot read properties of undefined (reading 'Series')

    at Object.<anonymous> (/Users/user/elastic-charts/packages/charts/src/utils/themes/light_theme.ts:43:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/user/elastic-charts/e2e/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader (/Users/user/elastic-charts/e2e/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/elastic-charts/packages/charts/src/specs/constants.ts:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/user/elastic-charts/e2e/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader (/Users/user/elastic-charts/e2e/node_modules/p
```

Other duplicated imports in [`/e2e/constants.ts`](https://github.com/nickofthyme/elastic-charts/blob/playwright-config-repro/e2e/constants.ts) cause similar issues for one reason or another.

**Comment by dgozman** [comment]
@nickofthyme Do you have an idea of which particular compiler option causes that? We are hesitant to read all the options from `tsconfig.json`, but perhaps we can enable a few additional ones.

**Comment by nickofthyme** [comment]
@dgozman, I'm really not sure, though I've seen others errors related to the `jsx` option. I would just find a way to fix it on my side than to have you guys allow one or two compiler options.

What is the hesitation with extending the whole `tsconfig.json`? I see this as giving full control knowing people could "shoot themselves in the foot" if not careful.
