### ISSUE TITLE
[Question] After update to 1.19 firefox fails to run

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#12075]
I bumped playwright to 1.19 and updated docker image to point to 1.19
FF started failing with message
```
jenkins.lab.xxx.org/blue/organizations/jenkins/builds%2FOneAgent%2Fxxx/detail/RUM-611-bump-playwright/1/pipeline/#step-241-log-1660)browserType.launch: 

[2022-02-14T10:38:06.279Z]     ╔════════════════════════════════════════════════════════════╗

[2022-02-14T10:38:06.279Z]     ║ Host system is missing a few dependencies to run browsers. ║

[2022-02-14T10:38:06.279Z]     ║ Please install them with the following command:            ║

[2022-02-14T10:38:06.279Z]     ║                                                            ║

[2022-02-14T10:38:06.279Z]     ║     sudo npx playwright install-deps                       ║

[2022-02-14T10:38:06.279Z]     ║                                                            ║

[2022-02-14T10:38:06.279Z]     ║ <3 Playwright Team
```

Is there some upgrade step that I should have done or?
It works fine again if I go back to 1.18.1 for both npm dep and playwright image

**Comment by daddyman** [comment]
I am seeing the same behavior since updating to the v1.19.0-focal Docker image. Chroium is fine and Firefox fails.

I went to see if the documentation changed for running under Docker. At https://playwright.dev/docs/ci there isn't anything special for Docker, but I do see a discrepancy I did not notice before.

In the [Introduction](https://playwright.dev/docs/ci#introduction) it shows running `npm ci` or `npm install` followed by `npx playwright install`. This is what I do in my script that runs under Docker.

Just under that for GitHub actions it shows running `npm ci` followed by `npx playwright install --with-deps`.

Is the new Docker image wrong or should I be adding `--with-deps` to the playwright install command when running under Docker?

**Comment by aslushnikov** [comment]
@Smrtnyk @daddyman I just tried to do the following and it worked:

```bash
aslushnikov@macbook$ docker run --rm -it mcr.microsoft.com/playwright:v1.19.0 /bin/bash
root@20b7d1bfd9c8:/# cd
root@20b7d1bfd9c8:~# npm init -y
Wrote to /root/package.json:

{
  "name": "root",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


root@20b7d1bfd9c8:~# npm i @playwright/test@1.19.0

added 208 packages, and audited 209 packages in 13s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@20b7d1bfd9c8:~# cat <<EOF >a.mjs
> import {firefox} from '@playwright/test';
> const browser = await firefox.launch();
> const page = await browser.newPage();
> console.log(await page.evaluate(() => navigator.userAgent));
> await browser.close();
> EOF
root@20b7d1bfd9c8:~# node a.mjs
Mozilla/5.0 (X11; Linux aarch64; rv:96.0) Gecko/20100101 Firefox/96.0
root@20b7d1bfd9c8:~# exit
```

Our docker tests all pass as well.
Can you please try the same locally? Does it work for you?

Can you also share how exactly do you use docker image? Do you build your own image atop of ours? In this case, could it be that docker caches got stuck? Can you try building with `docker build --pull --no-cache` flags?

**Comment by wwwouter** [comment]
I see the same problem.  I used `npm init playwright` to create the tests.

Running in Gitlab:

```
test browser:
    image: mcr.microsoft.com/playwright:v1.19.0-focal
    script:
        - cd packages/browser-tests
        - npm ci
        - npx playwright test
 ```

```
$ npx playwright test
Running 75 tests using 1 worker
·························××F××F××F××F××F××F××F××F××F××F××F××F××F××F××F××F××F××F×
×F××F××F××F××F××F××F·························
  Slow test file: [webkit] › example.spec.ts (43s)
  Slow test file: [firefox] › example.spec.ts (33s)
  Slow test file: [chromium] › example.spec.ts (20s)
  Consider splitting slow test files to speed up parallel execution
  25 failed
    [firefox] › example.spec.ts:14:3 › New Todo › should allow me to add todo items ================
    [firefox] › example.spec.ts:37:3 › New Todo › should clear text input field when an item is added 
    [firefox] › example.spec.ts:47:3 › New Todo › should append new items to the bottom of the list 
    [firefox] › example.spec.ts:61:3 › New Todo › should show #main and #footer when items added ===
    [firefox] › example.spec.ts:81:3 › Mark all as completed › should allow me to mark all items as completed 
    [firefox] › example.spec.ts:90:3 › Mark all as completed › should allow me to clear the complete state of all items 
    [firefox] › example.spec.ts:99:3 › Mark all as completed › complete all checkbox should update state when items are completed / cleared 
    [firefox] › example.spec.ts:122:3 › Item › should allow me to mark items as complete ===========
    [firefox] › example.spec.ts:144:3 › Item › should allow me to un-mark items as complete ========
    [firefox] › example.spec.ts:164:3 › Item › should allow me to edit an item =====================
    [firefox] › example.spec.ts:190:3 › Editing › should hide other controls when editing ==========
    [firefox] › example.spec.ts:198:3 › Editing › should save edits on blur ========================
    [firefox] › example.spec.ts:212:3 › Editing › should trim entered text =========================
    [firefox] › example.spec.ts:226:3 › Editing › should remove the item if an empty text string was entered 
    [firefox] › example.spec.ts:238:3 › Editing › should cancel edits on escape ====================
    [firefox] › example.spec.ts:247:3 › Counter › should display the current number of todo items ==
    [firefox] › example.spec.ts:265:3 › Clear completed button › should display the correct text ===
    [firefox] › example.spec.ts:270:3 › Clear completed button › should remove completed items when clicked 
    [firefox] › example.spec.ts:278:3 › Clear completed button › should be hidden when there are no items that are completed 
    [firefox] › example.spec.ts:286:3 › Persistence › should persist its data ======================
    [firefox] › example.spec.ts:316:3 › Routing › should allow me to display active items ==========
    [firefox] › example.spec.ts:324:3 › Routing › should respect the back button ===================
    [firefox] › example.spec.ts:348:3 › Routing › should allow me to display completed items =======
    [firefox] › example.spec.ts:355:3 › Routing › should allow me to display all items =============
    [firefox] › example.spec.ts:[36](https://gitlab.com/ZXY-Builders/ZXY-Cloud/-/jobs/2094303564#L36)4:3 › Routing › should highlight the currently applied filter ====
  [50](https://gitlab.com/ZXY-Builders/ZXY-Cloud/-/jobs/2094303564#L50) passed (2m)
Cleaning up project directory and file based variables
```

**Comment by Smrtnyk** [comment]
I am not using docker locally.
Locally I just do npm install and run the playwright like that.
We use docker in CI to run playwright tests.
We use kubernetes and have multiple images.
This is the part of our jenkins file
```ts
pipeline {
    agent {
        kubernetes {
            defaultContainer 'nodejs'
            yamlFile '.ci/k8s/jenkins.yaml'
            customWorkspace calculateWorkspace()
        }
    }
    environment {
        NPM_REGISTRY = <internal artifactory>
    }
    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds(abortPrevious: true)
        timestamps()
        ansiColor('xterm')
    }

    stages {
        stage('npm install') {
            steps {
                sh "cp .npmrc-template .npmrc"
                sh "npm install --unsafe-perm"
            }
        }
        stage('Playwright') {
            parallel {
                stage('smoke') {
                    steps {
                        sh "chmod -R 777 ./"
                        container('playwright') {
                            sh "npm run test:playwright-smoke"
                        }
                    }
                }
                stage('shard-1') {
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            sh "chmod -R 777 ./"
                            container('playwright') {
                                sh "npm run test:playwright-one"
                            }
                        }
                    }
                }
                stage('shard-2') {
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            sh "chmod -R 777 ./"
                            container('playwright') {
                                sh "npm run test:playwright-two"
                            }
                        }
                    }
                }
                stage('shard-3') {
                    steps {
                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                            sh "chmod -R 777 ./"
                            container('playwright') {
                                sh "npm run test:playwright-three"
                            }
                        }
                    }
                }
            }
        }
    }
}
 ```
 and containers are defined like this
 ```yaml
 kind: "Pod"
spec:
  containers:
   ...other containers

    - name: playwright
      image: mcr.microsoft.com/playwright:v1.18.1-focal
      imagePullPolicy: Always
      command:
        - cat
      tty: true
  nodeSelector:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
  securityContext:
    runAsUser: 1000
 ```
 here it is 1.18.1 because with that works
 but if I bump playwright to 1.19 and change the image to 1.19 ff just stops working

**Comment by daddyman** [comment]
I dug around a little bit and added some console.log statements in playwright-core under utils/dependencies.js where it reports this error. The validateDependenciesLinux function now prints this out before the missing deps error message:

TEST: missingPackages
Set(1) { 'libxtst6' }
TEST: missingDeps
Set(0) {}

So it seems to be saying the libxtst6 package is not installed - which it isn't. But it wasn't in the v1.18.1-focal image either. 

From nativeDeps.js it seems to want the library libXtst.so.6 which is part of libxtst6.

**Comment by daddyman** [comment]
I set PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1 when running the docker for Firefox and got this error:

```
Skipping host requirements validation logic because `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS` env variable is set.
2022-02-15T16:08:42.206Z pw:browser <launching> /ms-playwright/firefox-1316/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-M1eGlN -juggler-pipe -silent
2022-02-15T16:08:42.257Z pw:browser <launched> pid=85
2022-02-15T16:08:42.333Z pw:browser [pid=85][err] XPCOMGlueLoad error for file /ms-playwright/firefox-1316/firefox/libxul.so:
2022-02-15T16:08:42.333Z pw:browser [pid=85][err] libXtst.so.6: cannot open shared object file: No such file or directory
2022-02-15T16:08:42.394Z pw:browser [pid=85][err] Couldn't load XPCOM.
2022-02-15T16:08:42.454Z pw:browser [pid=85] <gracefully close start>
2022-02-15T16:08:42.455Z pw:browser [pid=85] <kill>
2022-02-15T16:08:42.455Z pw:browser [pid=85] <will force kill>
2022-02-15T16:08:42.456Z pw:browser [pid=85] <process did exit: exitCode=255, signal=null>
2022-02-15T16:08:42.456Z pw:browser [pid=85] starting temporary directories cleanup
2022-02-15T16:08:42.458Z pw:browser [pid=85] finished temporary directories cleanup
2022-02-15T16:08:42.458Z pw:browser [pid=85] <gracefully close end>

browserType.launch: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/firefox-1316/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-M1eGlN -juggler-pipe -silent
<launched> pid=85
[pid=85][err] XPCOMGlueLoad error for file /ms-playwright/firefox-1316/firefox/libxul.so:
[pid=85][err] libXtst.so.6: cannot open shared object file: No such file or directory
[pid=85][err] Couldn't load XPCOM.
=========================== logs ===========================
<launching> /ms-playwright/firefox-1316/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-M1eGlN -juggler-pipe -silent
<launched> pid=85
[pid=85][err] XPCOMGlueLoad error for file /ms-playwright/firefox-1316/firefox/libxul.so:
[pid=85][err] libXtst.so.6: cannot open shared object file: No such file or directory
[pid=85][err] Couldn't load XPCOM.
============================================================

   at ../../playwright.setup.ts:45

  43 |       return chromium.launch();
  44 |     case 'firefox':
> 45 |       return firefox.launch();
     |                      ^
  46 |     case 'webkit':
  47 |       return webkit.launch();
  48 |     default:

    at createBrowser (/app/playwright.setup.ts:45:22)
    at globalSetup (/app/playwright.setup.ts:17:25)

```

I compared what is in the 2 docker images: 

mcr.microsoft.com/playwright:v1.18.1-focal has firefox-1313. Doing an `ld libxul.so` show these lib files (others excluded):
```
libmozsandbox.so
liblgpllibs.so
libmozsqlite3.so
libmozgtk.so
libmozwayland.so
```

mcr.microsoft.com/playwright:v1.19.0-focal has firefox-1316. Doing an `ld libxul.so` show these lib files (others excluded):
```
libmozsandbox.so
liblgpllibs.so
libmozsqlite3.so
libmozgtk.so
libmozwayland.so
libXtst.so.6
```

So it seems there is at least one new dependency for Firefox that needs to be installed when the docker image is created.

**Comment by daddyman** [comment]
Here is a simple repo:
Running the 1.18.1 docker image (works):
```
c:\dev>docker run -it --rm mcr.microsoft.com/playwright:v1.18.1-focal
root@2260e1d54da6:/# cd ms-playwright/firefox-1313/firefox/
root@2260e1d54da6:/ms-playwright/firefox-1313/firefox# ./firefox
Error: no DISPLAY environment variable specified
root@2260e1d54da6:/ms-playwright/firefox-1313/firefox#
```

Running the 1.19.0 docker image (doesn't work):
```
c:\dev>docker run -it --rm mcr.microsoft.com/playwright:v1.19.0-focal
root@4e8835b13aac:/# cd ms-playwright/firefox-1316/firefox/
root@4e8835b13aac:/ms-playwright/firefox-1316/firefox# ./firefox
XPCOMGlueLoad error for file /ms-playwright/firefox-1316/firefox/libxul.so:
libXtst.so.6: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
root@4e8835b13aac:/ms-playwright/firefox-1316/firefox# exit
```

**Comment by aslushnikov** [comment]
Awesome, I can repro. Thank you folks! We'll fix it quickly.
