### ISSUE TITLE
[BUG]  page.goto: Timeout XXXms exceeded. No load or domcontentloaded event fired

### ISSUE THREAD

**Issue by soloyal** [microsoft/playwright#12182]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Mac
- Node.js version: 16.11.1
- Browser: Firefox
- Extra: 
- executablePath: '/Users/navin/Library/Caches/ms-playwright/firefox-1316/firefox/Nightly.app/Contents/MacOS/firefox',
    headless: false,
    args: [
      '--width=1280',
      '--height=720',
    ],

```javascript
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch({
    headless: false,
    args: [
      '--width=1280',
      '--height=720',
    ],
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  page.setDefaultTimeout(60000);
  // fire async navigation
  await page.goto('https://www.nike.com/', {
    waitUntil: 'load',
  });
  console.log('Done')
  await page.close()
  await browser.close()  
})();
```

Script opens the nike.com url but stuck on goto. No additional requests in the devtool. Visually it stopes the loading, web site  looks correct (with all css/js), but got never finishes
```bash
DEBUG=pw:api node index.js
 pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +4s
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +23ms
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +619ms
  pw:api   navigated to "about:blank" +38ms
  pw:api <= browserContext.newPage succeeded +6ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://www.nike.com/", waiting until "load" +6ms
  pw:api   "commit" event fired +862ms
  pw:api   navigated to "https://www.nike.com/il/" +0ms
  pw:api   "commit" event fired +2s
  pw:api   navigated to "https://unite.nike.com/session.html?appVersion=912&experienceVersion=912" +0ms
  pw:api   "commit" event fired +107ms
  pw:api   navigated to "https://api.nike.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/fp" +0ms
  pw:api   "commit" event fired +23ms
  pw:api   navigated to "https://unite.nike.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/fp" +1ms
  pw:api   "commit" event fired +5s
  pw:api   navigated to "https://www.googletagmanager.com/ns.html?id=GTM-NTF2X45" +0ms
  pw:api   "commit" event fired +828ms
  pw:api   navigated to "about:blank" +0ms

  pw:api   "commit" event fired +17ms
  pw:api   navigated to "about:blank" +1ms

  pw:api   "commit" event fired +51ms
  pw:api   navigated to "https://bid.g.doubleclick.net/xbbe/pixel?d=KAE" +0ms
  pw:api   "commit" event fired +29ms
  pw:api   navigated to "https://tr.snapchat.com/cm/i?pid=20634084-7fa1-4691-8aec-fefe00263e00" +0ms
  pw:api   "commit" event fired +406ms
  pw:api   navigated to "https://www.pinterest.com/ct.html" +0ms
  pw:api <= page.goto failed +49s
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: Timeout 60000ms exceeded.
=========================== logs ===========================
navigating to "https://www.nike.com/", waiting until "load"
============================================================
    at /Users/navin/Downloads/goto/index.js:19:14 {
  name: 'TimeoutError'
}
```

same behavior for waitUntill: domcontentloaded or any other

**Comment by soloyal** [comment]
Ok, but how to solve it?

**Comment by krutoo** [comment]
same problem

**Comment by grdthh** [comment]
I'm also dealing with that problem (firefox)

**Comment by dgattey** [comment]
I'm also getting this on Webkit + Firefox. Here's a run that exhibited this problem: https://github.com/shopcanal/e2e-tests/runs/5682749027?check_suite_focus=true
```
  pw:api <= browserContext.clearCookies succeeded +1ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://develop.shopcanal.com/login", waiting until "load" +1ms
  pw:api   "commit" event fired +219ms
  pw:api   navigated to "https://develop.shopcanal.com/login" +0ms
  pw:api   navigated to "https://develop.shopcanal.com/login" +329ms
  pw:api   navigated to "https://develop.shopcanal.com/login" +193ms
  pw:api   "domcontentloaded" event fired +21ms
  pw:api => browserContext.close started +59s
  pw:api <= page.goto failed +8ms
  pw:api <= browserContext.close succeeded +1ms
```

**Comment by tillschander** [comment]
I have the same problem with Chromium on Ubuntu. So it's not just a Firefox only issue.

Every time i run my tests one or two of them might fail randomly with the same waiting until load error:
```
page.waitForNavigation: Navigation failed because page was closed!
=========================== logs ===========================
waiting for navigation until "load"
============================================================
```
```
page.goto: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "http://localhost:3000/some/url", waiting until "load"
============================================================
```
The corresponding code is nothing fancy. Here are some examples:
```js
await Promise.all([
    page.waitForNavigation({ url: 'login' }),
    page.goto('login')
]);
```
```js
await page.goto('search');
await expect(page.locator('h1')).toContainText('Search');
await page.goto('product/123456');
await expect(page.locator('h1')).toContainText('Product Title');
```

**Comment by liuxingbaoyu** [comment]
Fixed in #13340

**Comment by jatin-karla11** [comment]
@tillschander we are also facing this issue on our Jenkins pipeline jobs, and again this is totally random any test gets error at any time, out of 50 test cases 2-3 fails due to this (2 workers), and if I increase the number of workers gradually then this count keeps increasing. (in all browsers). But if we run tests in local everything works fine.
Any solution for this issue as this is impacting our daily automation build results. @zhanglei4333 @liuxingbaoyu

**Comment by ajayEngProd** [comment]
Hello , we are also facing the same issue with timeouts happening randomly. We are running close to 60k tests across multiple machines in 20 minutes. This problem happens when tests run in a pipeline and not when they are running in local.

OS: windows
playwright version : 1.13.0
Dot net version : 5 and 6

any help in this regard will be very useful @zhanglei4333 @liuxingbaoyu @tillschander .

**Comment by sahil1610** [comment]
Hello,

I am also getting a similar issue with [https://app.vwo.com](https://app.vwo.com) on Chromium, Firefox and Webkit. Post the login, the URL is not getting redirected to the Dashboard and in the network panel, there is no call after the post Login call which gives 200.

Steps:
1. Land on https://app.vwo.com
2. Enter the Username and password and wait for redirection to dashboard page. (For username and password, you can simply create a free trial account on https://vwo.com.

Environment:
1. MacOS
2. Playwright Version 1.22
3. Browser - Chromium, Firefox and Webkit
4. Language binding - Javascript+Typescript

On Chromium, Firefox, and Safari the issue is intermediate, while on the local selenium 4 grid it's consistent.

**Comment by daddyman** [comment]
I turned on DEBUG=pw:api and the failure happens much less often but it did happen a couple of times. Both times while clicking a button to navigate to a new page (using Promise.all with page.waitForNavigation) a silent refresh of the access token occurred . Could this have something to do with the failure?

The attached file has the log output from the test that failed. Near the bottom is a comment "FAILURE STARTS HERE".  The page.waitForNavigation doesn't complete. In another run where this test succeeds, without the token refresh in the middle, there is an extra log line mentioned in the file that says the page.waitForNavigation succeeded.

[silent-refresh.txt](https://github.com/microsoft/playwright/files/8960625/silent-refresh.txt)

**Comment by daddyman** [comment]
I changed by tests to use DEBUG=pw:channel* and caught a test that succeeded once and failed once. In that test there is a page already loaded with a list page when the test starts. During the test:

- The Add button is clicked to navigate to the create page
- Wait for the create page to load 
- Verify the header text and breadcrumb text on the create page
- Click the cancel button on the create page to navigate back to the list page

In the failure case while the breadcrumb text is being verified the refresh token timer fires and the token renewal process starts (same as the previous test I posted about). This seems to cause problems in the last step of navigating back to the list page.

These two files are a successful run of the test and the failed run of the test. I commented the progress of the text.
[mappingdata-fail.txt](https://github.com/microsoft/playwright/files/8968637/mappingdata-fail.txt)
[mappingdata-success.txt](https://github.com/microsoft/playwright/files/8968639/mappingdata-success.txt)

**Comment by daddyman** [comment]
I opened a new issue specific to my case #15084 (a token refresh occurring during a test would add and remove an iframe which caused problems in playwright).

There is a pull request #15812 that fixed my problem when I manually applied it.

**Comment by KayakinKoder** [comment]
We were experiencing the same problem, only in our CI pipelines (tests working locally, failing randomly in pipelines). The following in our playwright config has seemed to fix the problem for us:

````
// limit the number of workers running. start with 1, and if your tests pass reliably, consider increasing to speed up runs
// the new % option may be a good choice, e.g.  workers: '50%'
workers: 1,

// set this to a large number
actionTimeout: 12000,
````

Based on the comments above and our experience, my thought is that the vm that's running our tests in ci pipeline just gets a bit overwhelmed in terms of resources. Tons of workers spawning new tests, all running at once, and one just hangs up a bit because ram and cpu are scarce.

An additional source of this problem could be the fact locally, we're running tests on localhost; in our pipeline, we're running tests on a real staging website. Have ever attempted to load a webpage and had it load a little more slowly than average? Of course. Increasing the actionTimeout may help with that.

**Comment by ChristianUlbrich** [comment]
Just to chime in a little bit on adding some insights, why your tests might fail on CI and seem to be flaky (or blaming Playwright for that matter) - for us, we are using pure ESM modules and if all of your dependencies are native ESM and are optimized for _tree-shaking_ (meaning every tiny function is exposed as ESM module), if you do not bundle anything at all, this easily amounts to crazy amounts of requests being made:
* using `@popperjs/core/lib/popper-lite.js` _roughly_ amounts to 40+ requests (while only tallying ~70kB) 
* using even such simple things like `lodash-es/isEqual.js` amounts to another 30+ requests

In our scenario, where we "just" user 5 components from our UI library, this amounts to +150 requests. Browsers limit the amount of parallel HTTP requests and if HTTPS involved, this is not going to get any faster... So what I am saying is, that even my beefy (sorry veggies!) MacBook takes _roughly_ a second for loading. We limited the Playwright timeouts to 4s and it seems, that hosted AzureDevOps Mac OS agents have pretty bad I/O performance, read by factor 5-10 slower, so this explains for us failed timeouts, because the load event is not triggered in time, because esm modules need to be "resolved" before actual DOM processing can happen.

We might think about using bundles for our tests; but for the time being, we solved this by having a _platform-dependent_ global timeout set for Playwright.

**Comment by lavcraft** [comment]
Same issue in chromium with fresh playwright version 1.31.2 :(

**Comment by swoopgrandchamp** [comment]
Same issue with 1.32.3, out of 7 tests, 1 random one has always this problem.

**Comment by auxsvr** [comment]
This may be caused by https://github.com/jfhbrook/pyee/issues/120. I've seen many cases of lost events with playwright and fixed all of them by patching pyee to keep a reference to the futures corresponding to the events, otherwise they get garbage-collected.

**Comment by saranya-krish** [comment]
Facing similar issue.

Intermittently tests fail only in pipeline while calling page.goto

Using Playwright version 1.31.0.

How to resolve this?

**Comment by jalexakos** [comment]
Facing this issue as well - the tests timeout for some users on their local machine, but not others. I'm curious to see what's going on. It seems like the Playwright trace viewer no longer displays how long network calls took - that would be a great feature to bring back.

**Comment by EugeneMac** [comment]
Similar issue when running on TeamCity agent. Playwright 1.31.1.
Happens mostly in page.WaitForURLAsync() method after clicking Login button and redirecting to homepage (timeout exception: waiting for navigation to "***" until "Load"). Seems like redirecting mechanism somehow affects a current page.
As a result, target page is loaded, but the WaitForURLAsync method fails...

**Comment by fayasfb** [comment]
same issue  Error: page.waitForLoadState: Navigation failed because page was closed!
      =========================== logs ===========================
        "domcontentloaded" event fired
        "networkidle" event fired   please give the solution , its working in local , getting this error in github actions.

**Comment by methaqualon** [comment]
Somewhy from my logs I recognized that my page on vps passes 'load' event after much time, so now in this situation without fix I'm preferring to use this lifehack:
node_modules/playwright-core/lib/client/frame.js
change in function goto default value of waitUntil to smth else from expected values, 'commit' in my case and waitForTimeout with fixed value

in my case there are client-side redirect. First page throws 'load' event fastly, but that where i am redirected is heavy page with some lazyload things, so i'm getting Timeout exceeded shit in 80-85% cases.
It is not a fix at all, but can help people not to waste money now when team is working on it.
Hope team will fix it easily and fastly.

**Comment by 4ayushsinghal** [comment]
> I have the same problem with Chromium on Ubuntu. So it's not just a Firefox only issue.
> 
> Every time i run my tests one or two of them might fail randomly with the same waiting until load error:
> 
> ```
> page.waitForNavigation: Navigation failed because page was closed!
> =========================== logs ===========================
> waiting for navigation until "load"
> ============================================================
> ```
> 
> ```
> page.goto: Navigation failed because page was closed!
> =========================== logs ===========================
> navigating to "http://localhost:3000/some/url", waiting until "load"
> ============================================================
> ```
> 
> The corresponding code is nothing fancy. Here are some examples:
> 
> ```js
> await Promise.all([
>     page.waitForNavigation({ url: 'login' }),
>     page.goto('login')
> ]);
> ```
> 
> ```js
> await page.goto('search');
> await expect(page.locator('h1')).toContainText('Search');
> await page.goto('product/123456');
> await expect(page.locator('h1')).toContainText('Product Title');
> ```


> I am also facing the same issue when I run on linux. I am tryint to use page.setContent with a new page on browser context
> Here is the corresponding code
>```js
>context = await browser.newContext()
>const renderedPage = await context.newPage()
>const frame = await (await this.page.$('iframe')).contentFrame()
>await renderedPage.setContent(await frame.content())
>expect(await renderedPage).toHaveScreenshot('pa-template', { fullPage: true })
>```

>I get the below error:
>```
>Error: page.setContent: Navigation failed because page was closed!
>=========================== logs ===========================
>setting frame content, waiting until "load"
>============================================================
>
>  129 |       expect(await paEmail.subject).toBe(actualSubject)
>  130 |       const renderedPage = await context.newPage()
>> 131 |       await renderedPage.setContent(await paEmail.body)
>     |                          ^
>  132 |       await expect(renderedPage).toHaveScreenshot('pa-email', { fullPage: true })
>  133 |     })
>  134 |   })
>
>    at /home/runner/work/test-automation/test-automation/tests/nextboard/communications.spec.js:131:26
>    at /home/runner/work/test-automation/test-automation/tests/nextboard/communications.spec.js:120:5
```

**Comment by jfuinsure** [comment]
Also inermittenly seeing NS_ERROR_NET_TIMEOUT with Firefox

**Comment by tomdelahaba** [comment]
I have very little to add to this topic, but MAYBE (hopefully?) it will help to someone.

We faced very similar issues just right now, I was pretty clueless why we get such timeouts, when everything is working locally, but on our environment, we faced such a random timeouts as well. Sometime, it was working, sometime it was not. It was very weird. 

Well, TLDR... Most of the providers (mainly cloud ones) have some kind of limiting rules for amount of queries. In such a situation, if playwright will hit this limit (lets say 100 queries per minute), usually the server (to avoid DDOS) serve you 403 or any other page. In such a situation, playwright will be stuck on goto('') or any assertion, because that assertion won't be truthy. For our particular use-case, the situation was as well, that playwright was not rendering anything because of our 403 page...

So keep on mind as well that such a server infrastructure / logic can (potentially) be the problem as well. Mainly if you do not face these problems locally.

**Comment by tgrisley** [comment]
Have also been having this issue within CircleCi, tests intermittently get stuck on `goTo()` and then test will timeout. If i check screenshots / trace view i can see that page the page has loaded correctly. 

<img width="868" alt="Screenshot 2024-01-12 at 14 19 59" src="https://github.com/microsoft/playwright/assets/126177701/8334484a-f2c0-4e92-9d18-959d23560668">

<img width="697" alt="Screenshot 2024-01-12 at 14 21 49" src="https://github.com/microsoft/playwright/assets/126177701/6f18f122-20f7-4d78-80cf-4cdd6300568f">


Using provided MS docker image but have reduced the workers from 2 to 1, still no difference. 

```
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-jammy
```

I can put forward a simply repro if that would help as this still seems to be an issue

**Comment by benskz** [comment]
Not a fix by any means but if anyone needs an emergency hacky workaround this might help:
```
try {
  await page.goto(url, {
    timeout: 5000,
  });
} catch {
  // sometimes goto times out, so try again
  console.log('page.goto timed out, trying again');
  await page.goto(url);
}
};
```

**Comment by gantispam** [comment]
Same issue

**Comment by GerasimovDG** [comment]
**UP!** 
We have the same issue. Everything works well locally, but we get **'navigating to [url] waiting until "load"**' in our CI

**Comment by fredericoo** [comment]
Having this issue to out of nowhere, fixed by adding `{ waitUntil: 'domcontentloaded' }` to the params of the `goto` call. It seems it was just waiting forever. Will look into it deeply but for now just needed something working

**Comment by margarytaD** [comment]
Also time to time see this issue in all browsers

**Comment by test20161010** [comment]
In the case of Firefox, isn't there a problem
where it doesn't accept test instructions correctly
if the window is not in the forefront?

**Comment by oscarm081297** [comment]
Also is happening to me using GitlabCI - Tests were working last week and suddenly I am getting timeout with page.goto()
Locally everything is working fine, I've upgrade and also downgrade the playwright version but issue still persists.
I've enabled the debug mode and this is what I am getting:
```
navigating to ".......", waiting until "load" +2ms
  pw:api   "commit" event fired +1s
  pw:api   navigated to "..........." +0ms
  pw:api   "domcontentloaded" event fired +1s
  pw:api   navigated to "about:blank" +1s
  pw:api   navigated to "about:blank" +2ms
  pw:api   "commit" event fired +305ms
  pw:api   navigated to ".........." +0ms
  pw:api   "domcontentloaded" event fired +696ms
  pw:api   navigated to "about:blank" +1s
  pw:api   navigated to "about:blank" +34ms
  **pw:api <= page.goto failed +2s** 
``` 
I can see in the video recording that the test was able to open the page (page is loading properly) but for some reason it's firing timeout when test is being executed on CI.
Also, I've tried placing the page.goto() in different places (beforeEach, test level, etc) and is throwing timeout always, checked the traces but everything looks good.
This is becoming a blocker since we can not execute any test on CI - every single test is crashing because of the timeout, I tried by increasing it but not working either.

Any insights?

**Comment by StaRenn** [comment]
Also happening when you try to run tests in docker container, with dev server running on host machine, using --network="host" and host.docker.internal as url, had to set timeout to 300s, which is not good

**Comment by xiaoxiaocaiiao** [comment]
playwright 1.33.0, chrome still have this issue

**Comment by dtokarczyk** [comment]
I noticed that it happens only in tests run in a docker container and only if I run a lot of tests. Interestingly Linux users do not report issues, only mac users.

**Comment by jameslporter** [comment]
Can confirm this issue is affect linux users. I was setting up a docker container and trying playwright for the first time. Insanely frustrating. Finally figured out I'm not a total moron but simply a significant regression in playwright itself. I know npx is all the rage these days but it leads to users running the latest version. I was able to get my tests working by using npx playwright@1.43.1 install and then npx playwright@1.43.1 test after also adjusting the package.json dep to specifically 1.43.1 version.

**Comment by kuba-orlik** [comment]
In my case updating Playwright solved the issue, fyi

**Comment by LuvDeluxe** [comment]
This is still present when executed with Docker... Locally I am unable to reproduce... Can someone look at this and investigate it?

**Comment by dtokarczyk** [comment]
I noticed that `docker system prune --volumes` sometimes solve problems

**Comment by JorensM** [comment]
I think this happens because of redirects. Does anyone experiencing this issue have redirects by any chance?

**Comment by lucien-theron** [comment]
I also have this issue using Chrome and Ubuntu (also using official container). The video shows the page freeze or hang a second after opening. This only happens on our tests.

**Comment by vladide** [comment]
I have performed some tests on local vs local docker vs k8s pod

Hence recommend that those who see random TIMEOUTS (Test timeout of 30000ms exceeded) -  check the resource usage

**Comment by JorensM** [comment]
This happens for me on locally on Windows btw, less often on UI mode though. Also happens in GitLab CI with Linux

**Comment by lucien-theron** [comment]
I now also get these locally on Windows but a lot more rarely

**Comment by mateuswolkmer** [comment]
What fixed it for me on Windows was setting `fullyParallel` to `false` in the `PlaywrightTestConfig`, so it runs one test at a time. I guess my machine isn't strong enough for the parallel tests and it load indefinitely, causing the timeout.

**Comment by sdwvit** [comment]
Stuff is way funnier here: 

![Image](https://github.com/user-attachments/assets/93903e26-e411-406c-a69a-50722c5b9797)

**Comment by zijian-bytedance** [comment]
for me, this happens to some url.

**Comment by Mkots** [comment]
I can also reproduce this issue.

I'm using Playwright **v1.51.1** with TypeScript, running both locally and on GitHub Actions (using the official image mcr.microsoft.com/playwright:v1.51.1-noble). But still, the page **sometimes** just doesn't load at all — exactly as described.

To work around it, I even implemented a helper that retries "goto":
https://gist.github.com/Mkots/2e8d9bb7b1417686786d576ec3d962c9
But even with that in place, 5–7 out of 100 tests still fail occasionally.

It seems to be non-deterministic and **not specific to a particular url or page** (because my tests use only one url and page) — any insights or potential fixes would be much appreciated.

**Comment by gund** [comment]
This affects Chrome not just Firefox and happens quite often in CI.
Can this be prioritized please?
People expect E2E tools to not be flaky 🙏

**Comment by shanelavezzo** [comment]
This also affects webkit. Only running into this in container. Please prioritize.

**Comment by noahkaminer** [comment]
I'm also seeing this with webkit in a docker container too. Very annoying and hard to switch browser types for our use case. Please fix this soon!

> This also affects webkit. Only running into this in container. Please prioritize.

**Comment by dgozman** [comment]
Hey folks, we need your help to fix this issue!

If you struggle with this, please file a new issue **with reproduction steps** that we can run locally - fill in the "Bug Report" template and **link to this issue**.

If you **do not have a reproduction** that we can run locally, for example it uses a non-public url, or you cannot share your code, please **do not** file an issue. When in doubt, please refer to the [filing issues guide](https://github.com/microsoft/playwright/blob/main/FILING_ISSUES.md).

Thank you everyone!

**Comment by PAStheLoD** [comment]
Hello,

For anyone running into this and ends up here through a search engine, it's worth a shot to enable "browser" debugging. (I also tried "api", but that did not reveal much.)

Also, I recommend simply adding --retries 2 and use.video: "on-first-retry" to get an idea of what goes wrong.


```
DEBUG=pw:browser ./node_modules/.bin/playwright test --project=...
```

(For us adding `--disable-gpu --disable-software-rasterizer --mute-audio` to launchOptions.args for Chromium helped to get Playwright working in a docker container in a GitLab CI runner using docker executor with "docker service", with the docker:dind-rootless image.)

**Comment by dgozman** [comment]
Closing this issue as there is no actionable repro to address. If you hit this problem, consider filing an issue **with a repro** as described in [this comment](https://github.com/microsoft/playwright/issues/12182#issuecomment-2876402625). Thank you!
