### ISSUE TITLE
[BUG] npx init fails on Win10/Git Bash

### ISSUE THREAD

**Issue by leegee** [microsoft/playwright#12334]
**Context:**
- Playwright Version: [what Playwright version do you use?] latest via npx init playwright
- Operating System: [e.g. Windows, Linux or Mac] Win 10 64-bit
- Node.js version: [e.g. 12.22, 14.6] 7.24.1
- Browser: [e.g. All, Chromium, Firefox, WebKit] via npx init playwright
- Extra: [any specific details about your environment] git bash 4.4.23

```
  System:
    OS: Windows 10 10.0.19043
    Memory: 8.11 GB / 15.94 GB
  Binaries:
    Node: 16.10.0 - L:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - L:\_npm\yarn.CMD
    npm: 7.24.1 - L:\_npm\npm.CMD
  Languages:
    Bash: 4.4.23 - L:\Program Files\Git\usr\bin\bash.EXE
```

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```bash
pm init playwright
```

**Describe the bug**

```bash
leege@studio MINGW64 /l/src/nta/nta-test (master)
$ npm init playwright
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
√ Do you want to use TypeScript or JavaScript? · TypeScript
√ Where to put your end-to-end tests? · .    
√ Add a GitHub Actions workflow? (Y/n) · true
Initializing NPM project (npm init -y)…      
Wrote to L:\src\nta\nta-test\package.json:

{
  "name": "nta-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


Installing Playwright Test (npm install --save-dev @playwright/test)…

added 208 packages, and audited 209 packages in 16s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Downloading browsers (npx playwright install)…
'playwright' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: npx playwright install
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at executeCommands (C:\Users\leege\AppData\Local\npm-cache\_npx\d40a10098bccdd29\node_modules\create-playwright\lib\index.js:1:85854)  
    at Generator.run (C:\Users\leege\AppData\Local\npm-cache\_npx\d40a10098bccdd29\node_modules\create-playwright\lib\index.js:1:80307)    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\leege\AppData\Local\npm-cache\_npx\d40a10098bccdd29\node_modules\create-playwright\lib\index.js:1:79571 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 14608,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path L:\src\nta\nta-test
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-playwright

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\leege\AppData\Local\npm-cache\_logs\2022-02-24T08_58_52_040Z-debug.log
```

**Comment by leegee** [comment]
`PATH` includes `./node_modules/.bin/`
