### ISSUE TITLE
[BUG] Testing electron multi-window app with requestSingleInstanceLock throws errors

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/playwright#12345]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux
- Node.js version: 17.6.0
- Browser: Electron
- Extra: [any specific details about your environment]

**Bug Repository**

https://github.com/SimonSiefke/playwright-electron-multi-window-bug

**Code Snippet**

Electron Code:

```javascript
const { app, BrowserWindow } = require("electron");

const createWindow = () => {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
  });

  win.loadFile("index.html");
};

const main = async () => {
  const hasLock = app.requestSingleInstanceLock();
  if (hasLock) {
    await app.whenReady();
    createWindow();
    app.on("second-instance", createWindow);
  } else {
    app.quit();
  }
};

main();
```

Playwright Code:

```js
import { _electron as electron } from "playwright";

export const launchApp = async () => {
  const electronApp = await electron.launch({
    args: ["index.cjs"],
  });
  return electronApp;
};

const main = async () => {
  console.log("before launch 1");
  const app1 = await launchApp();
  console.log("after launch 1");
  console.log("before launch 2");
  const app2 = await launchApp();
  console.log("after launch 2");
};

main();
```

**Describe the bug**

I'm trying to test a multi-window electron app that has `requestSingleInstanceLock` enabled.

When running the test script, it sometimes works:

```
before launch 1
after launch 1
before launch 2
after launch 2
```

but it often throws errors.

**Error 1:**

```
before launch 1
after launch 1
before launch 2
after launch 2
/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/chromium/crExecutionContext.js:67
    if (exceptionDetails) throw new js.JavaScriptErrorInEvaluate((0, _crProtocolHelper.getExceptionMessage)(exceptionDetails));
                                ^

JavaScriptErrorInEvaluate: illegal access
    at CRExecutionContext.rawEvaluateHandle (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/chromium/crExecutionContext.js:67:33)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async evaluateExpression (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/javascript.js:221:25)
    at async CRSession.<anonymous> (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/electron/electron.js:87:13)
```

**Error 2:**
```
before launch 1
after launch 1
before launch 2
^C/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/electron/electron.js:177
        attemptToGracefullyClose: () => app.close(),
                                            ^

TypeError: Cannot read properties of undefined (reading 'close')
    at Object.attemptToGracefullyClose (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/electron/electron.js:177:45)
    at gracefullyClose (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/utils/processLauncher.js:159:19)
    at process.<anonymous> (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/utils/processLauncher.js:131:7)
    at process.emit (node:events:539:35)

Node.js v17.6.0
```

**Error 3:**

```
before launch 1
after launch 1
before launch 2
after launch 2
/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/chromium/crExecutionContext.js:146
  if (!js.isJavaScriptErrorInEvaluate(error) && !(0, _protocolError.isSessionClosedError)(error)) throw new Error('Execution context was destroyed, most likely because of a navigation.');
                                                                                                        ^

Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/chromium/crExecutionContext.js:146:105)
    at async CRExecutionContext.rawEvaluateHandle (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/chromium/crExecutionContext.js:63:9)
    at async evaluateExpression (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/javascript.js:221:25)
    at async CRSession.<anonymous> (/tmp/playwright-electron-multi-window-bug/node_modules/playwright-core/lib/server/electron/electron.js:87:13)

Node.js v17.6.0
```

**Expected Behaviour**

Ideally it would be so that app1 has 2 windows and that app2 is disposed and has 0 windows.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
