### ISSUE TITLE
[Question] myReport.ts missing SyntaxErrors

### ISSUE THREAD

**Issue by alanbqs** [microsoft/playwright#12383]
I am trying to use my own reporter ("myReporter.ts") with the various onStdOut, onStdErr type functions, but I notice that SyntaxError's are not visible if I use myReporter.ts (but are if I switch to reporter=list).

How do I get the reporter to output those problems too?

**Comment by rwoll** [comment]
`SyntaxError` (from your test files) and other top-level errors are available by implementing the `onError` method in your custom reporter:

```
    onError(error: TestError): void {
        console.log("onError", error)
    }
```

Does that work for you @alanbqs?

**Comment by alanbqs** [comment]
Not seeing the message.

If I run a deliberately broken script with the following command 

```
cd C:\.....\playwright && npx playwright test w3schools_table_test.spec.ts.datamerged.ts --project=chromium --reporter=list
```
then I see the following error:

```
Running 1 test using 1 worker

  x  [chromium] › w3schools_table_test.spec.ts.datamerged.ts:8:7 › Test Group › Test List Screen (485ms)


  1) [chromium] › w3schools_table_test.spec.ts.datamerged.ts:8:7 › Test Group › Test List Screen ===

    ReferenceError: xxxx is not defined

       8 |       test("Test List Screen", async ({ page }, workerInfo) => {
       9 |
    > 10 |       await test.step('Step 1 - goto list screen', async () => {xxxx
         |                                                                 ^
      11 |             await page.goto('https://www.w3schools.com/css/css_table.asp');
      12 |             await expect(page).toHaveURL('https://www.w3schools.com/css/css_table.asp');
```
But if I run with myReport.ts then I do not see that error.

myReport.ts
```
import { Reporter } from '@playwright/test/reporter';

class MyReporter implements Reporter {
  onBegin(config, suite)          { console.log(`*** Starting the run with ${suite.allTests().length} tests`);}
  onTestBegin(test)               { console.log(`*** Starting test ${test.title}`);  }
  onTestEnd(test, result)         { console.log(`*** Finished test ${test.title}: ${result.status}`);  }
  onEnd(result)                   { console.log(`*** Finished the run: ${result.status}`);  }
  onStdOut(chunk)                 { console.log('&gt;         '+chunk);  }
  onStdErr(chunk)                 { console.error('!&gt;       ******ERR: '+chunk);  }
  onError(error: TestError): void { console.log("onError", error); }
  
  
  
  onStepBegin(test, result, step)  {
	  if ( step.location ) console.log(`    STEP BEGIN: ${test.title} / ${step.title} line ${step.location.line}`);
	  else console.log(`    STEP BEGIN: ${test.title} / ${step.title}`);  
  }
  
  
  onStepEnd(test, result, step)  {
	  if ( step.location ) console.log(`    STEP END: ${test.title} / ${step.title} line ${step.location.line} : ${result.status}`); // not sure if result.status is anything but skipped
	  else console.log(`    STEP END: ${test.title} / ${step.title} : ${result.status}`);
  }
  
}
export default MyReporter;
```

**Comment by rwoll** [comment]
Thanks for the repro @alanbqs! In your example it looks like you're hitting a test-level `ReferenceError` and not a `SyntaxError`. There's a subtle distinction between `SyntaxError` and `ReferenceError` and how they surface in the Reporters.

`SyntaxError` as produced via:

```ts
import { expect, test } from "@playwright/test"

test('example', async ({ }) => {
    await test.step('step 1', async () => {
        (  // <- extra parens; will result in SyntaxError in onError
        console.log(1);
    });
});
```

will surface via `onError` since it prevents the tests from even running.

`ReferenceError` will surface in a few places depending on where it occurs.

In your example above, since the `ReferenceError` is contained to a test it will appear in `result.error` (and `result.errors`) of `onTestEnd`:

Reporter Code:
```ts
    onTestEnd(test: TestCase, result: TestResult): void {
        console.log("onTestEnd", result.error)
    }
```

Output:
```
onTestEnd {
  message: 'xxxx is not defined',
  stack: 'ReferenceError: xxxx is not defined\n' +
    '    at /tmp/example/example.spec.ts:5:9\n' +
    '    at /tmp/example/example.spec.ts:4:16'
}
```

Additionally, since in your example it's part of a `step`, it will also appear in `onStepEnd`:

```ts

    onStepEnd(test: TestCase, result: TestResult, step: TestStep): void {
        console.log("onStepEnd", step.error)
    }
```

In the above, it's similar to if you put `expect(1).toBe(2)` where `xxxx` is.

If the `ReferenceError` occurs outside a test, for example at the top-level in the file like so:

```ts
import { expect, test } from "@playwright/test"

yyyyy // <- ReferenceError

test('example', async ({ }) => {
    await test.step('step 1', async () => {
    });
});
```

This will be surfaced in `onError`:

```
onError ReferenceError: yyyyy is not defined
```

Let me know if this helps you with your reporter and you're able to surface the error(s) you're interested in reporting! If so, I'll think about how we can improve the Reporter Docs ([API doc](https://playwright.dev/docs/api/class-reporter) and [Guide Doc](https://playwright.dev/docs/test-reporters)) to make these distinctions more clear. It may also be helpful to look through the [Line Reporter implementation](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/reporters/line.ts) and [Base Reporter Implementation](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/reporters/base.ts) (extended by the Line Reporter).

**Comment by alanbqs** [comment]
Hmm... my experience of 

```
import { expect, test } from "@playwright/test"

test('example', async ({ }) => {
    await test.step('step 1', async () => {
        (  // <- extra parens; will result in SyntaxError in onError
        console.log(1);
    });
});
``` 

and ```onError(error: TestError): void { console.log("SyntaxErrorX:", error); console.info(error); }``` in the reporter.ts is...

```
C:>cd C:\...\playwright && npx playwright test test.spec.ts --project=chromium
*** Starting the run with 1 tests
SyntaxErrorX: {
  message: 'C:\\....\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
    '\n' +
    "\x1B[0m \x1B[90m 4 |\x1B[39m     \x1B[36mawait\x1B[39m test\x1B[33m.\x1B[39mstep(\x1B[32m'step 1'\x1B[39m\x1B[33m,\x1B[39m \x1B[36masync\x1B[39m () \x1B[33m=>\x1B[39m {\x1B[0m\n" +
    '\x1B[0m \x1B[90m 5 |\x1B[39m         (  \x1B[90m// <- extra parens; will result in SyntaxError in onError\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 6 |\x1B[39m         console\x1B[33m.\x1B[39mlog(\x1B[35m1\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m   |\x1B[39m                       \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 7 |\x1B[39m     })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 8 |\x1B[39m })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 9 |\x1B[39m\x1B[0m',
  stack: 'SyntaxError: C:\\....\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
    '\n' +
    "\x1B[0m \x1B[90m 4 |\x1B[39m     \x1B[36mawait\x1B[39m test\x1B[33m.\x1B[39mstep(\x1B[32m'step 1'\x1B[39m\x1B[33m,\x1B[39m \x1B[36masync\x1B[39m () \x1B[33m=>\x1B[39m {\x1B[0m\n" +
    '\x1B[0m \x1B[90m 5 |\x1B[39m         (  \x1B[90m// <- extra parens; will result in SyntaxError in onError\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 6 |\x1B[39m         console\x1B[33m.\x1B[39mlog(\x1B[35m1\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m   |\x1B[39m                       \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 7 |\x1B[39m     })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 8 |\x1B[39m })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 9 |\x1B[39m\x1B[0m\n' +
    '    at Object._raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:150:45)\n' +
    '    at Object.raiseWithData (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:145:17)\n' +
    '    at Object.raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:89:17)\n' +
    '    at Object.unexpected (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:174:16)\n' +
    '    at Object.expect (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:150:28)\n' +
    '    at Object.parseParenAndDistinguishExpression (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1702:14)\n' +
    '    at Object.parseExprAtom (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1122:21)\n' +
    '    at Object.parseExprSubscripts (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:682:23)\n' +
    '    at Object.parseUpdate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:662:21)\n' +
    '    at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:633:23)\n' +
    '    at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\plugins\\typescript\\index.js:3023:22)\n' +
    '    at Object.parseMaybeUnaryOrPrivate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:388:14)\n' +
    '    at Object.parseExprOps (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:398:23)\n' +
    '    at Object.parseMaybeConditional (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:356:23)\n' +
    '    at Object.parseMaybeAssign (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:303:21)'
}
{
  message: 'C:\\....\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
    '\n' +
    "\x1B[0m \x1B[90m 4 |\x1B[39m     \x1B[36mawait\x1B[39m test\x1B[33m.\x1B[39mstep(\x1B[32m'step 1'\x1B[39m\x1B[33m,\x1B[39m \x1B[36masync\x1B[39m () \x1B[33m=>\x1B[39m {\x1B[0m\n" +
    '\x1B[0m \x1B[90m 5 |\x1B[39m         (  \x1B[90m// <- extra parens; will result in SyntaxError in onError\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 6 |\x1B[39m         console\x1B[33m.\x1B[39mlog(\x1B[35m1\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m   |\x1B[39m                       \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 7 |\x1B[39m     })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 8 |\x1B[39m })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 9 |\x1B[39m\x1B[0m',
  stack: 'SyntaxError: C:\\....\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
    '\n' +
    "\x1B[0m \x1B[90m 4 |\x1B[39m     \x1B[36mawait\x1B[39m test\x1B[33m.\x1B[39mstep(\x1B[32m'step 1'\x1B[39m\x1B[33m,\x1B[39m \x1B[36masync\x1B[39m () \x1B[33m=>\x1B[39m {\x1B[0m\n" +
    '\x1B[0m \x1B[90m 5 |\x1B[39m         (  \x1B[90m// <- extra parens; will result in SyntaxError in onError\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 6 |\x1B[39m         console\x1B[33m.\x1B[39mlog(\x1B[35m1\x1B[39m)\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m   |\x1B[39m                       \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 7 |\x1B[39m     })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 8 |\x1B[39m })\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 9 |\x1B[39m\x1B[0m\n' +
    '    at Object._raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:150:45)\n' +
    '    at Object.raiseWithData (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:145:17)\n' +
    '    at Object.raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:89:17)\n' +
    '    at Object.unexpected (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:174:16)\n' +
    '    at Object.expect (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:150:28)\n' +
    '    at Object.parseParenAndDistinguishExpression (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1702:14)\n' +
    '    at Object.parseExprAtom (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1122:21)\n' +
    '    at Object.parseExprSubscripts (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:682:23)\n' +
    '    at Object.parseUpdate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:662:21)\n' +
    '    at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:633:23)\n' +
    '    at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\plugins\\typescript\\index.js:3023:22)\n' +
    '    at Object.parseMaybeUnaryOrPrivate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:388:14)\n' +
    '    at Object.parseExprOps (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:398:23)\n' +
    '    at Object.parseMaybeConditional (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:356:23)\n' +
    '    at Object.parseMaybeAssign (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:303:21)'
}
```

which if you remove the \x1B[ noise reads...
```
C:\>cd C:......\playwright && npx playwright test test.spec.ts --project=chromium
*** Starting the run with 1 tests
SyntaxErrorX: {
message: 'C:\\....\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
'\n' +
" 4 | await test.step('step 1', async () => {\n" +
' 5 | ( // <- extra parens; will result in SyntaxError in onError\n' +
'> 6 | console.log(1);\n' +
' | ^\n' +
' 7 | });\n' +
' 8 | });\n' +
' 9 |',
stack: 'SyntaxError: C:\\....\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
'\n' +
" 4 | await test.step('step 1', async () => {\n" +
' 5 | ( // <- extra parens; will result in SyntaxError in onError\n' +
'> 6 | console.log(1);\n' +
' | ^\n' +
' 7 | });\n' +
' 8 | });\n' +
' 9 |\n' +
' at Object._raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:150:45)\n' +
' at Object.raiseWithData (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:145:17)\n' +
' at Object.raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:89:17)\n' +
' at Object.unexpected (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:174:16)\n' +
' at Object.expect (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:150:28)\n' +
' at Object.parseParenAndDistinguishExpression (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1702:14)\n' +
' at Object.parseExprAtom (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1122:21)\n' +
' at Object.parseExprSubscripts (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:682:23)\n' +
' at Object.parseUpdate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:662:21)\n' +
' at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:633:23)\n' +
' at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\plugins\\typescript\\index.js:3023:22)\n' +
' at Object.parseMaybeUnaryOrPrivate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:388:14)\n' +
' at Object.parseExprOps (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:398:23)\n' +
' at Object.parseMaybeConditional (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:356:23)\n' +
' at Object.parseMaybeAssign (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:303:21)'
}
{
message: 'C:\\....\\playwright\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
'\n' +
" 4 | await test.step('step 1', async () => {\n" +
' 5 | ( // <- extra parens; will result in SyntaxError in onError\n' +
'> 6 | console.log(1);\n' +
' | ^\n' +
' 7 | });\n' +
' 8 | });\n' +
' 9 |',
stack: 'SyntaxError: C:\\....\\playwright\\test.spec.ts: Unexpected token, expected "," (6:22)\n' +
'\n' +
" 4 | await test.step('step 1', async () => {\n" +
' 5 | ( // <- extra parens; will result in SyntaxError in onError\n' +
'> 6 | console.log(1);\n' +
' | ^\n' +
' 7 | });\n' +
' 8 | });\n' +
' 9 |\n' +
' at Object._raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:150:45)\n' +
' at Object.raiseWithData (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:145:17)\n' +
' at Object.raise (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\error.js:89:17)\n' +
' at Object.unexpected (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:174:16)\n' +
' at Object.expect (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\util.js:150:28)\n' +
' at Object.parseParenAndDistinguishExpression (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1702:14)\n' +
' at Object.parseExprAtom (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:1122:21)\n' +
' at Object.parseExprSubscripts (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:682:23)\n' +
' at Object.parseUpdate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:662:21)\n' +
' at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:633:23)\n' +
' at Object.parseMaybeUnary (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\plugins\\typescript\\index.js:3023:22)\n' +
' at Object.parseMaybeUnaryOrPrivate (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:388:14)\n' +
' at Object.parseExprOps (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:398:23)\n' +
' at Object.parseMaybeConditional (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:356:23)\n' +
' at Object.parseMaybeAssign (C:\\....\\playwright\\node_modules\\@babel\\parser\\src\\parser\\expression.js:303:21)'
}
```


which seems to include a lot of \n and '+ and "+ and is definitely not like your suggested example Output

**Comment by rwoll** [comment]
@alanbqs Oops! Pasted some stale code while typing it up in the example. If you're concerned with formatting (and not just dumping the `SyntaxError` out), you'll want to print just the stack and/or message (and possibly even transform/format it further):

```ts
// my-awesome-reporter.ts
import { Reporter, TestCase, TestError, TestResult, TestStep } from '@playwright/test/reporter';

class MyReporter implements Reporter {
…
    onError(error: TestError): void {
        if (error.message && error.stack) {
            console.error(error.message);
            console.error(error.stack);
        } else {
            console.error(error)
        }
    }
}
export default MyReporter;
```

That should yield the following on `@playwright/test@1.19.2`:

```
$ npx playwright test
/tmp/example/example.spec.ts: Unexpected token (7:4)

  5 |     await test.step('step 1', async () => {
  6 |         (
> 7 |     });
    |     ^
  8 | });
SyntaxError: /tmp/example/example.spec.ts: Unexpected token (7:4)

  5 |     await test.step('step 1', async () => {
  6 |         (
> 7 |     });
    |     ^
  8 | });
    at Object._raise (/tmp/example/node_modules/@babel/parser/src/parser/error.js:150:45)
    at Object.raiseWithData (/tmp/example/node_modules/@babel/parser/src/parser/error.js:145:17)
    at Object.raise (/tmp/example/node_modules/@babel/parser/src/parser/error.js:89:17)
    at Object.unexpected (/tmp/example/node_modules/@babel/parser/src/parser/util.js:174:16)
    at Object.parseExprAtom (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:1309:22)
    at Object.parseExprSubscripts (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:682:23)
    at Object.parseUpdate (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:662:21)
    at Object.parseMaybeUnary (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:633:23)
    at Object.parseMaybeUnary (/tmp/example/node_modules/@babel/parser/src/plugins/typescript/index.js:3023:22)
    at Object.parseMaybeUnaryOrPrivate (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:388:14)
    at Object.parseExprOps (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:398:23)
    at Object.parseMaybeConditional (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:356:23)
    at Object.parseMaybeAssign (/tmp/example/node_modules/@babel/parser/src/parser/expression.js:303:21)
    at Object.parseMaybeAssign (/tmp/example/node_modules/@babel/parser/src/plugins/typescript/index.js:2931:22)
    at /tmp/example/node_modules/@babel/parser/src/parser/expression.js:257:12
```

See the built in reporter impl for some examples of error formatting.

**Comment by mxschmitt** [comment]
Closing see the latest reply for the answer.
