### ISSUE TITLE
[BUG] Segmentation fault - core dumped on official docker image

### ISSUE THREAD

**Issue by AmruthPillai** [microsoft/playwright#12568]
**Context:**
- Playwright Version: v1.19.2
- Operating System: Mac M1 Pro
- Node.js version: 16.x
- Browser: Chromium
- Extra: uses npm:playwright-chromium@v1.19.2 on a NestJS server project

**Describe the bug**

Running into this issue (**Segmentation fault**) when running a docker image that was built on top of `mcr.microsoft.com/playwright:focal`.

```
server  | node:internal/process/promises:265
server  |             triggerUncaughtException(err, true /* fromPromise */);
server  |             ^
server  |
server  | browserType.launch: Browser closed.
server  | ==================== Browser output: ====================
server  | <launching> /ms-playwright/chromium-965416/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-bLmxww --remote-debugging-pipe --no-startup-window
server  | <launched> pid=362
server  | [pid=362][err] [0307/221922.577443:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
server  | [pid=362][err] [0307/221922.983630:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
server  | [pid=362][err] [0307/221923.004623:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
server  | [pid=362][err] [0307/221923.026416:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
server  | [pid=362][err] #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006c29790 <unknown>
server  | [pid=362][err] #3 0x004006c2a34e <unknown>
server  | [pid=362][err] #4 0x0040067c9d86 <unknown>
server  | [pid=362][err] #5 0x0040067c4d20 <unknown>
server  | [pid=362][err] #6 0x0040067c5949 <unknown>
server  | [pid=362][err] #7 0x0040067c65bb <unknown>
server  | [pid=362][err] #8 0x0040067c3a24 <unknown>
server  | [pid=362][err] #9 0x0040067c432e <unknown>
server  | [pid=362][err] #10 0x00400681f27a <unknown>
server  | [pid=362][err] #11 0x00400681f133 <unknown>
server  | [pid=362][err] #12 0x00400681dd75 <unknown>
server  | [pid=362][err] #13 0x0040034cd928 <unknown>
server  | [pid=362][err] #14 0x0040034cd839 <unknown>
server  | [pid=362][err] #15 0x00400f0750b3 <unknown>
server  | [pid=362][err] #16 0x0040034cd76a <unknown>
server  | [pid=362][err]
server  | [pid=362][err] [0307/221923.040634:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
server  | [pid=362][err] #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006c29790 <unknown>
server  | [pid=362][err] #3 0x004006c2a34e <unknown>
server  | [pid=362][err] #4 0x0040067c9d86 <unknown>
server  | [pid=362][err] #5 0x0040067c4d20 <unknown>
server  | [pid=362][err] #6 0x0040067c5949 <unknown>
server  | [pid=362][err] #7 0x0040067c65bb <unknown>
server  | [pid=362][err] #8 0x0040067c3a24 <unknown>
server  | [pid=362][err] #9 0x0040067c432e <unknown>
server  | [pid=362][err] #10 0x00400681f27a <unknown>
server  | [pid=362][err] #11 0x00400681f133 <unknown>
server  | [pid=362][err] #12 0x00400681dd75 <unknown>
server  | [pid=362][err] #13 0x0040034cd928 <unknown>
server  | [pid=362][err] #14 0x0040034cd839 <unknown>
server  | [pid=362][err] #15 0x00400f0750b3 <unknown>
server  | [pid=362][err] #16 0x0040034cd76a <unknown>
server  | [pid=362][err]
server  | [pid=362][err] Received signal 6
server  | [pid=362][err] Received signal 6
server  | [pid=362][err] #0 0x004006caf559 #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006caf061 <unknown>
server  | [pid=362][err] #2 0x004006caf061 <unknown>
server  | [pid=362][err] #3 0x00400e34f3c0 <unknown>
server  | [pid=362][err] #3 0x00400e34f3c0 <unknown>
server  | [pid=362][err] #4 0x00400f09418b <unknown>
server  | [pid=362][err] #4 0x00400f09418b <unknown>
server  | [pid=362][err] #5 0x00400f073859 <unknown>
server  | [pid=362][err] #5 0x00400f073859 <unknown><unknown>
server  | [pid=362][err]
server  | [pid=362][err] ##66  0x0x004006cae2e5004006cae2e5  <unknown>
server  | [pid=362][err] #7 0x004006c29c61<unknown>
server  | [pid=362][err] #7 0x004006c29c61 <unknown>
server  | [pid=362][err] #8 0x004006c2a34e <unknown>
server  | [pid=362][err] #8 0x004006c2a34e <unknown>
server  | [pid=362][err] #9 0x0040067c9d86<unknown>
server  | [pid=362][err] #9 0x0040067c9d86 <unknown>
server  | [pid=362][err] #10 0x0040067c4d20 <unknown>
server  | [pid=362][err] #10 0x0040067c4d20 <unknown>
server  | [pid=362][err] #11 0x0040067c5949 <unknown>
server  | [pid=362][err] #11 0x0040067c5949 <unknown>
server  | [pid=362][err] #12 0x0040067c65bb <unknown>
server  | [pid=362][err] #12 0x0040067c65bb <unknown>
server  | [pid=362][err] #13 0x0040067c3a24<unknown>
server  | [pid=362][err] #13 0x0040067c3a24 <unknown>
server  | [pid=362][err] #14 0x0040067c432e <unknown>
server  | [pid=362][err] #14 0x0040067c432e <unknown>
server  | [pid=362][err] #15<unknown> 0x
server  | [pid=362][err] 00400681f27a# 15 0x00400681f27a <unknown>
server  | [pid=362][err] #16 0x00400681f133 <unknown>
server  | [pid=362][err] #16 0x00400681f133 <unknown>
server  | [pid=362][err] #17 0x00400681dd75 <unknown>
server  | [pid=362][err] #17 0x00400681dd75 <unknown>
server  | [pid=362][err] #18 0x0040034cd928 <unknown>
server  | [pid=362][err] #18 0x0040034cd928 <unknown><unknown>
server  | [pid=362][err] #19 0x0040034cd839
server  | [pid=362][err] #19 0x0040034cd839 <unknown><unknown>
server  | [pid=362][err]
server  | [pid=362][err] ##2020  0x0x00400f0750b300400f0750b3  <unknown>
server  | [pid=362][err] #21 0x0040034cd76a <unknown>
server  | [pid=362][err] #21 0x0040034cd76a <unknown>
server  | [pid=362][err]   r8: 0000000000000000  r9: 000000400e2f17d0 r10: 0000000000000008 r11: 000000400f20e780
server  | [pid=362][err]  r12: 00000332003b8000 r13: 00000332003b8018 r14: 00000332003b8010 r15: 0000033200374000
server  | [pid=362][err]   di: 0000000000000002  si: 000000400e2f17d0  bp: 000000400e2f1a20  bx: 00000040103db8c0
server  | [pid=362][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000027  sp: 000000400e2f17d0
server  | [pid=362][err]   ip: 000000400f09418b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
server  | [pid=362][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
server  | [pid=362][err] <unknown>
server  | [pid=362][err]   r8: 0000000000000000  r9: 000000400e2f17f0 r10: 0000000000000008 r11: 000000400f20e780
server  | [pid=362][err]  r12: 00000670003b8000 r13: 00000670003b8018 r14: 00000670003b8010 r15: 0000067000374000
server  | [pid=362][err]   di: 0000000000000002  si: 000000400e2f17f0  bp: 000000400e2f1a40  bx: 00000040103db8c0
server  | [pid=362][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000027  sp: 000000400e2f17f0
server  | [pid=362][err]   ip: 000000400f09418b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
server  | [pid=362][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
server  | [pid=362][err] [end of stack trace]
server  | [pid=362][err] [end of stack trace]
server  | [pid=362][err] qemu: uncaught target signal 6 (Aborted) - core dumped
server  | [pid=362][err] qemu: uncaught target signal 6 (Aborted) - core dumped
server  | [pid=362][err] Received signal 11 SEGV_MAPERR 57d7a07bbfc0d
server  | [pid=362][err] #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006caf061 <unknown>
server  | [pid=362][err] #3 0x00400e34f3c0 <unknown>
server  | [pid=362][err] #4 0x00400754da18 <unknown>
server  | [pid=362][err] #5 0x00400754e1ba <unknown>
server  | [pid=362][err] #6 0x00400755c02c <unknown>
server  | [pid=362][err] #7 0x00400755bf82 <unknown>
server  | [pid=362][err] #8 0x0040075546a1 <unknown>
server  | [pid=362][err] #9 0x00400754af91 <unknown>
server  | [pid=362][err] #10 0x004007550a26 <unknown>
server  | [pid=362][err] #11 0x004007550abe <unknown>
server  | [pid=362][err] #12 0x004007546837 <unknown>
server  | [pid=362][err] #13 0x004007546777 <unknown>
server  | [pid=362][err] #14 0x004007554a71 <unknown>
server  | [pid=362][err] #15 0x004007545c22 <unknown>
server  | [pid=362][err] #16 0x0040075d16f7 <unknown>
server  | [pid=362][err] #17 0x0040047b57bd <unknown>
server  | [pid=362][err] #18 0x00400c0d744d <unknown>
server  | [pid=362][err] #19 0x0040067c55c2 <unknown>
server  | [pid=362][err] #20 0x0040067c6a49 <unknown>
server  | [pid=362][err] #21 0x0040067c65df <unknown>
server  | [pid=362][err] #22 0x0040067c3a24 <unknown>
server  | [pid=362][err] #23 0x0040067c432e <unknown>
server  | [pid=362][err] #24 0x00400681f27a <unknown>
server  | [pid=362][err] #25 0x00400681ef85 <unknown>
server  | [pid=362][err] #26 0x0040034cd928 <unknown>
server  | [pid=362][err] #27 0x0040034cd839 <unknown>
server  | [pid=362][err] #28 0x00400f0750b3 <unknown>
server  | [pid=362][err] #29 0x0040034cd76a <unknown>
server  | [pid=362][err]   r8: 00001ce60039d400  r9: 00001ce6003f4000 r10: 00001ce60039d67a r11: 0000000000000010
server  | [pid=362][err]  r12: 00001ce6003f37a0 r13: 0000000000000008 r14: 00001ce6003f37c0 r15: 0000000000000008
server  | [pid=362][err]   di: 0000000000000020  si: 00000000000003f2  bp: 000000400e2f2860  bx: 52057d7a07bbfc05
server  | [pid=362][err]   dx: 0000000000000004  ax: 0000000000000000  cx: 0000000000000000  sp: 000000400e2f27d0
server  | [pid=362][err]   ip: 000000400754da18 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000004
server  | [pid=362][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: 00057d7a07bbfc0d
server  | [pid=362][err] [end of stack trace]
server  | [pid=362][err] qemu: uncaught target signal 11 (Segmentation fault) - core dumped
server  | =========================== logs ===========================
server  | <launching> /ms-playwright/chromium-965416/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-bLmxww --remote-debugging-pipe --no-startup-window
server  | <launched> pid=362
server  | [pid=362][err] [0307/221922.577443:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
server  | [pid=362][err] [0307/221922.983630:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
server  | [pid=362][err] [0307/221923.004623:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
server  | [pid=362][err] [0307/221923.026416:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
server  | [pid=362][err] #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006c29790 <unknown>
server  | [pid=362][err] #3 0x004006c2a34e <unknown>
server  | [pid=362][err] #4 0x0040067c9d86 <unknown>
server  | [pid=362][err] #5 0x0040067c4d20 <unknown>
server  | [pid=362][err] #6 0x0040067c5949 <unknown>
server  | [pid=362][err] #7 0x0040067c65bb <unknown>
server  | [pid=362][err] #8 0x0040067c3a24 <unknown>
server  | [pid=362][err] #9 0x0040067c432e <unknown>
server  | [pid=362][err] #10 0x00400681f27a <unknown>
server  | [pid=362][err] #11 0x00400681f133 <unknown>
server  | [pid=362][err] #12 0x00400681dd75 <unknown>
server  | [pid=362][err] #13 0x0040034cd928 <unknown>
server  | [pid=362][err] #14 0x0040034cd839 <unknown>
server  | [pid=362][err] #15 0x00400f0750b3 <unknown>
server  | [pid=362][err] #16 0x0040034cd76a <unknown>
server  | [pid=362][err]
server  | [pid=362][err] [0307/221923.040634:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
server  | [pid=362][err] #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006c29790 <unknown>
server  | [pid=362][err] #3 0x004006c2a34e <unknown>
server  | [pid=362][err] #4 0x0040067c9d86 <unknown>
server  | [pid=362][err] #5 0x0040067c4d20 <unknown>
server  | [pid=362][err] #6 0x0040067c5949 <unknown>
server  | [pid=362][err] #7 0x0040067c65bb <unknown>
server  | [pid=362][err] #8 0x0040067c3a24 <unknown>
server  | [pid=362][err] #9 0x0040067c432e <unknown>
server  | [pid=362][err] #10 0x00400681f27a <unknown>
server  | [pid=362][err] #11 0x00400681f133 <unknown>
server  | [pid=362][err] #12 0x00400681dd75 <unknown>
server  | [pid=362][err] #13 0x0040034cd928 <unknown>
server  | [pid=362][err] #14 0x0040034cd839 <unknown>
server  | [pid=362][err] #15 0x00400f0750b3 <unknown>
server  | [pid=362][err] #16 0x0040034cd76a <unknown>
server  | [pid=362][err]
server  | [pid=362][err] Received signal 6
server  | [pid=362][err] Received signal 6
server  | [pid=362][err] #0 0x004006caf559 #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006caf061 <unknown>
server  | [pid=362][err] #2 0x004006caf061 <unknown>
server  | [pid=362][err] #3 0x00400e34f3c0 <unknown>
server  | [pid=362][err] #3 0x00400e34f3c0 <unknown>
server  | [pid=362][err] #4 0x00400f09418b <unknown>
server  | [pid=362][err] #4 0x00400f09418b <unknown>
server  | [pid=362][err] #5 0x00400f073859 <unknown>
server  | [pid=362][err] #5 0x00400f073859 <unknown><unknown>
server  | [pid=362][err]
server  | [pid=362][err] ##66  0x0x004006cae2e5004006cae2e5  <unknown>
server  | [pid=362][err] #7 0x004006c29c61<unknown>
server  | [pid=362][err] #7 0x004006c29c61 <unknown>
server  | [pid=362][err] #8 0x004006c2a34e <unknown>
server  | [pid=362][err] #8 0x004006c2a34e <unknown>
server  | [pid=362][err] #9 0x0040067c9d86<unknown>
server  | [pid=362][err] #9 0x0040067c9d86 <unknown>
server  | [pid=362][err] #10 0x0040067c4d20 <unknown>
server  | [pid=362][err] #10 0x0040067c4d20 <unknown>
server  | [pid=362][err] #11 0x0040067c5949 <unknown>
server  | [pid=362][err] #11 0x0040067c5949 <unknown>
server  | [pid=362][err] #12 0x0040067c65bb <unknown>
server  | [pid=362][err] #12 0x0040067c65bb <unknown>
server  | [pid=362][err] #13 0x0040067c3a24<unknown>
server  | [pid=362][err] #13 0x0040067c3a24 <unknown>
server  | [pid=362][err] #14 0x0040067c432e <unknown>
server  | [pid=362][err] #14 0x0040067c432e <unknown>
server  | [pid=362][err] #15<unknown> 0x
server  | [pid=362][err] 00400681f27a# 15 0x00400681f27a <unknown>
server  | [pid=362][err] #16 0x00400681f133 <unknown>
server  | [pid=362][err] #16 0x00400681f133 <unknown>
server  | [pid=362][err] #17 0x00400681dd75 <unknown>
server  | [pid=362][err] #17 0x00400681dd75 <unknown>
server  | [pid=362][err] #18 0x0040034cd928 <unknown>
server  | [pid=362][err] #18 0x0040034cd928 <unknown><unknown>
server  | [pid=362][err] #19 0x0040034cd839
server  | [pid=362][err] #19 0x0040034cd839 <unknown><unknown>
server  | [pid=362][err]
server  | [pid=362][err] ##2020  0x0x00400f0750b300400f0750b3  <unknown>
server  | [pid=362][err] #21 0x0040034cd76a <unknown>
server  | [pid=362][err] #21 0x0040034cd76a <unknown>
server  | [pid=362][err]   r8: 0000000000000000  r9: 000000400e2f17d0 r10: 0000000000000008 r11: 000000400f20e780
server  | [pid=362][err]  r12: 00000332003b8000 r13: 00000332003b8018 r14: 00000332003b8010 r15: 0000033200374000
server  | [pid=362][err]   di: 0000000000000002  si: 000000400e2f17d0  bp: 000000400e2f1a20  bx: 00000040103db8c0
server  | [pid=362][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000027  sp: 000000400e2f17d0
server  | [pid=362][err]   ip: 000000400f09418b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
server  | [pid=362][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
server  | [pid=362][err] <unknown>
server  | [pid=362][err]   r8: 0000000000000000  r9: 000000400e2f17f0 r10: 0000000000000008 r11: 000000400f20e780
server  | [pid=362][err]  r12: 00000670003b8000 r13: 00000670003b8018 r14: 00000670003b8010 r15: 0000067000374000
server  | [pid=362][err]   di: 0000000000000002  si: 000000400e2f17f0  bp: 000000400e2f1a40  bx: 00000040103db8c0
server  | [pid=362][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000027  sp: 000000400e2f17f0
server  | [pid=362][err]   ip: 000000400f09418b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
server  | [pid=362][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000000000000000
server  | [pid=362][err] [end of stack trace]
server  | [pid=362][err] [end of stack trace]
server  | [pid=362][err] qemu: uncaught target signal 6 (Aborted) - core dumped
server  | [pid=362][err] qemu: uncaught target signal 6 (Aborted) - core dumped
server  | [pid=362][err] Received signal 11 SEGV_MAPERR 57d7a07bbfc0d
server  | [pid=362][err] #0 0x004006caf559 <unknown>
server  | [pid=362][err] #1 0x004006c16973 <unknown>
server  | [pid=362][err] #2 0x004006caf061 <unknown>
server  | [pid=362][err] #3 0x00400e34f3c0 <unknown>
server  | [pid=362][err] #4 0x00400754da18 <unknown>
server  | [pid=362][err] #5 0x00400754e1ba <unknown>
server  | [pid=362][err] #6 0x00400755c02c <unknown>
server  | [pid=362][err] #7 0x00400755bf82 <unknown>
server  | [pid=362][err] #8 0x0040075546a1 <unknown>
server  | [pid=362][err] #9 0x00400754af91 <unknown>
server  | [pid=362][err] #10 0x004007550a26 <unknown>
server  | [pid=362][err] #11 0x004007550abe <unknown>
server  | [pid=362][err] #12 0x004007546837 <unknown>
server  | [pid=362][err] #13 0x004007546777 <unknown>
server  | [pid=362][err] #14 0x004007554a71 <unknown>
server  | [pid=362][err] #15 0x004007545c22 <unknown>
server  | [pid=362][err] #16 0x0040075d16f7 <unknown>
server  | [pid=362][err] #17 0x0040047b57bd <unknown>
server  | [pid=362][err] #18 0x00400c0d744d <unknown>
server  | [pid=362][err] #19 0x0040067c55c2 <unknown>
server  | [pid=362][err] #20 0x0040067c6a49 <unknown>
server  | [pid=362][err] #21 0x0040067c65df <unknown>
server  | [pid=362][err] #22 0x0040067c3a24 <unknown>
server  | [pid=362][err] #23 0x0040067c432e <unknown>
server  | [pid=362][err] #24 0x00400681f27a <unknown>
server  | [pid=362][err] #25 0x00400681ef85 <unknown>
server  | [pid=362][err] #26 0x0040034cd928 <unknown>
server  | [pid=362][err] #27 0x0040034cd839 <unknown>
server  | [pid=362][err] #28 0x00400f0750b3 <unknown>
server  | [pid=362][err] #29 0x0040034cd76a <unknown>
server  | [pid=362][err]   r8: 00001ce60039d400  r9: 00001ce6003f4000 r10: 00001ce60039d67a r11: 0000000000000010
server  | [pid=362][err]  r12: 00001ce6003f37a0 r13: 0000000000000008 r14: 00001ce6003f37c0 r15: 0000000000000008
server  | [pid=362][err]   di: 0000000000000020  si: 00000000000003f2  bp: 000000400e2f2860  bx: 52057d7a07bbfc05
server  | [pid=362][err]   dx: 0000000000000004  ax: 0000000000000000  cx: 0000000000000000  sp: 000000400e2f27d0
server  | [pid=362][err]   ip: 000000400754da18 efl: 0000000000000206 cgf: 002b000000000033 erf: 0000000000000004
server  | [pid=362][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: 00057d7a07bbfc0d
server  | [pid=362][err] [end of stack trace]
server  | [pid=362][err] qemu: uncaught target signal 11 (Segmentation fault) - core dumped
server  | ============================================================
server  |     at PrinterService.onModuleInit (/app/server/dist/printer/printer.service.js:28:61)
server  |     at MapIterator.iteratee (/app/node_modules/.pnpm/@nestjs+core@8.4.0_2e10c1a16efb48b2968dca34c1adcfc4/node_modules/@nestjs/core/hooks/on-module-init.hook.js:22:43)
server  |     at MapIterator.next (/app/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/map.js:13:39)
server  |     at IteratorWithOperators.next (/app/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/iterate.js:21:28)
server  |     at IteratorWithOperators.toArray (/app/node_modules/.pnpm/iterare@1.2.1/node_modules/iterare/lib/iterate.js:180:22)
server  |     at callOperator (/app/node_modules/.pnpm/@nestjs+core@8.4.0_2e10c1a16efb48b2968dca34c1adcfc4/node_modules/@nestjs/core/hooks/on-module-init.hook.js:23:10)
server  |     at Object.callModuleInitHook (/app/node_modules/.pnpm/@nestjs+core@8.4.0_2e10c1a16efb48b2968dca34c1adcfc4/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:23)
server  |     at NestApplication.callInitHook (/app/node_modules/.pnpm/@nestjs+core@8.4.0_2e10c1a16efb48b2968dca34c1adcfc4/node_modules/@nestjs/core/nest-application-context.js:179:27)
server  |     at async NestApplication.init (/app/node_modules/.pnpm/@nestjs+core@8.4.0_2e10c1a16efb48b2968dca34c1adcfc4/node_modules/@nestjs/core/nest-application.js:96:9)
server  |     at async NestApplication.listen (/app/node_modules/.pnpm/@nestjs+core@8.4.0_2e10c1a16efb48b2968dca34c1adcfc4/node_modules/@nestjs/core/nest-application.js:155:33)
server  |     at async bootstrap (/app/server/dist/main.js:25:5) {
server  |   name: 'Error'
server  | }
server  | undefined
server  | /app/server:
server  |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @reactive-resume/server@ start:prod: `node dist/main`
server  | Exit status 1
server  |  ELIFECYCLE  Command failed with exit code 1.
server exited with code 1
```

**Comment by yury-s** [comment]
Please provide an example where it is reproducible

**Comment by AmruthPillai** [comment]
@yury-s I am able to reproduce it on the docker image I've pushed here:
https://hub.docker.com/repository/docker/amruthpillai/reactive-resume
tag: amruthpillai/reactive-resume:server-e96b0909

<img width="1062" alt="Screenshot 2022-03-08 at 12 28 41 AM" src="https://user-images.githubusercontent.com/1134738/157135569-1559823e-6c95-4158-879a-ef8dde169ee0.png">

These are the args passed to playwright:
```
/ms-playwright/chromium-965416/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/playwright_chromiumdev_profile-ssQhMv --remote-debugging-pipe --no-startup-window
```

I know this is not a lot of information. Is there any way I can get more information from the segfault error?

**Comment by yury-s** [comment]
> @yury-s I am able to reproduce it on the docker image I've pushed here:
> https://hub.docker.com/repository/docker/amruthpillai/reactive-resume
> tag: amruthpillai/reactive-resume:server-e96b0909

Can you share dockerfile used to build that image?

**Comment by AmruthPillai** [comment]
@yury-s That would be found at https://github.com/AmruthPillai/Reactive-Resume/blob/v3/server/Dockerfile.

 Thank you again.

**Comment by yury-s** [comment]
Looks like you try to run playwright on an alpine image, this will not work as Chromium binary bundled with playwright is built with glibc while Alpine binaries work with libmusl. You can try installing Chromium compatible with Alpine separately, Playwright officially supports only Ubuntu.

**Comment by AmruthPillai** [comment]
@yury-s No, I'm actually using the official image from playwright. It's a multi-stage build Docker file, and as you can see on line 30, I pull the official image and then install my dependencies again.

**Comment by yury-s** [comment]
Something must be wrong with the build process, I tried installing playwright in the image and it worked without the problem:

```sh
cd
npm init playwright test # didn't install system deps
cd test/
DEBUG=pw:browser npx playwright test --project=chromium

Running 25 tests using 1 worker
[chromium] › example.spec.js:15:3 › New Todo › should allow me to add todo items
  pw:browser <launching> /ms-playwright/chromium-965416/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-pMFqlK --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=453 +7ms
  pw:browser [pid=453][err] [0309/015115.460711:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory +93ms
  pw:browser [pid=453][err] [0309/015115.460936:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory +0ms
  pw:browser [pid=453][err] [0309/015115.465998:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable. +4ms
  pw:browser [pid=453][err] [0309/015115.497757:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process. +33ms
  pw:browser [pid=453] <gracefully close start> +18s
  pw:browser [pid=453] <process did exit: exitCode=0, signal=null> +29ms
  pw:browser [pid=453] starting temporary directories cleanup +0ms
  pw:browser [pid=453] finished temporary directories cleanup +9ms
  pw:browser [pid=453] <gracefully close end> +1ms
  Slow test file: [chromium] › example.spec.js (18s)
  Consider splitting slow test files to speed up parallel execution

  25 passed (19s)

To open last HTML report run:

  npx playwright show-report



```

**Comment by amrsa1** [comment]
@yury-s 

encountering same issue with safari - iphone view port with latest playwright version 1.31.1 in ubuntu system 22.4.2


```
    browserContext.newPage: Browser closed.
    ==================== Browser output: ====================
    <launching> /home/warrior/.cache/ms-playwright/webkit-1792/pw_run.sh --inspector-pipe --no-startup-window
    <launched> pid=171191
    [pid=171191][err] /home/warrior/.cache/ms-playwright/webkit-1792/pw_run.sh: line 21: 171196 Segmentation fault      (core dumped) WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
    [pid=171191] <process did exit: exitCode=139, signal=null>
    [pid=171191] starting temporary directories cleanup
    [pid=171191] finished temporary directories cleanup
```

Seems happening when you have many test cases with relatively short execution time
