### ISSUE TITLE
[BUG] Playwright install fails on windows 7

### ISSUE THREAD

**Issue by qitest** [microsoft/playwright#12766]
Context:

Playwright Version: [1.19.0]
Operating System: [Windows]  win7
java maven version: [1.19.0]
Browser: [e.g. All, Chromium, Firefox,] Chromium

**Code Snippet**
```java
        Playwright.CreateOptions createOptions = new Playwright.CreateOptions();
        Map<String, String> map = new HashMap<>();
        //这个是设置忽略下载浏览器,如果值为0,则下载
        map.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "0");
        createOptions.setEnv(map);
        Playwright playwright = Playwright.create(createOptions);
```
Getting the following error

Caused by: java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
	... 23 common frames omitted
Caused by: java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at com.qic.hr.demo.LagouDemo.getPlaywright(LagouDemo.java:46)
	at com.qic.hr.demo.LagouDemo.<clinit>(LagouDemo.java:33)
	... 30 common frames omitted
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: -1073741511
	at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:74)
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:46)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52)
	... 34 common frames omitted

**Comment by qitest** [comment]
My program works in win 10 but not in windows7

**Comment by mxschmitt** [comment]
Windows 7 is not supported, Windows 8+ but we recommend Windows 10 or 11.
