### ISSUE TITLE
[BUG] TestProject.grep and TestProject.grepInvert not working

### ISSUE THREAD

**Issue by ltsuda** [microsoft/playwright#12775]
**Context:**
- Playwright Version: 1.20
- Operating System: WSL2 Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa) - Windows 11
- Node.js version: 16.13.0
- Browser: None
- Extra: npm 8.1.0

**Describe the bug**
Trying to use the latest feature `TestProject.grep and TestProject.grepInvert`, but it doesn't work. Should this feature work for `test.describe`?

How to reproduce:

```bash
# 1.19 cli --grep/grep-invert works
> git clone https://github.com/ltsuda/playwright-serverest && cd playwright-serverest
> npm install
> npx playwright test --grep '@schema'
# or
> npm run test:schema

# 1.20 bug
> git clone https://github.com/ltsuda/playwright-serverest && cd playwright-serverest
# https://github.com/ltsuda/playwright-serverest/commit/0598772ff12ca08b7190b56bec95cca02e3ead4b
> git switch dev/1.20
> npm install
> npx playwright test --project 'schema'
# or
> npm run test:schema
```

Playwright 1.19.2
```javascript
❯ npx playwright test --grep '@schema'

Running 10 tests using 2 workers

  10 passed (1s)

To open last HTML report run:

  npx playwright show-report test-results
```
Playwright 1.20
```javascript
❯ npx playwright test --project 'schema'
TypeError: Cannot create property 'lastIndex' on string '@schema'
    at /home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/util.js:157:20
    at /home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:340:20
    at ProjectImpl._cloneEntries (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/project.js:96:14)
    at ProjectImpl._cloneEntries (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/project.js:81:19)
    at ProjectImpl.cloneFileSuite (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/project.js:128:17)
    at Runner._runFiles (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:337:34)
    at Runner._run (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:231:12)
    at TimeoutRunner.run (/home/ltsuda/developer/playwright-serverest/node_modules/playwright-core/lib/utils/async.js:38:14)
    at raceAgainstTimeout (/home/ltsuda/developer/playwright-serverest/node_modules/playwright-core/lib/utils/async.js:85:15)
    at Runner.runAllTests (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:188:20)
    at runTests (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/cli.js:184:18)
    at Command.<anonymous> (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/cli.js:79:7)
```

**Comment by ltsuda** [comment]
Actually, the `grep/grepInvert` options in the `projects` configuration even breaks commands without the `--project` parameter.

```bash
❯ npx playwright test
TypeError: Cannot create property 'lastIndex' on string '@schema'
    at /home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/util.js:157:20
    at /home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:340:20
    at ProjectImpl._cloneEntries (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/project.js:96:14)
    at ProjectImpl._cloneEntries (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/project.js:81:19)
    at ProjectImpl.cloneFileSuite (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/project.js:128:17)
    at Runner._runFiles (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:337:34)
    at Runner._run (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:231:12)
    at TimeoutRunner.run (/home/ltsuda/developer/playwright-serverest/node_modules/playwright-core/lib/utils/async.js:38:14)
    at raceAgainstTimeout (/home/ltsuda/developer/playwright-serverest/node_modules/playwright-core/lib/utils/async.js:85:15)
    at Runner.runAllTests (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/runner.js:188:20)
    at runTests (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/cli.js:184:18)
    at Command.<anonymous> (/home/ltsuda/developer/playwright-serverest/node_modules/@playwright/test/lib/cli.js:79:7)
```

**Comment by pavelfeldman** [comment]
Could you share your config, along with the expectations and the actual results?

**Comment by ltsuda** [comment]
Tests directory.
```bash
tests/api/*.spec.js
tests/api/schemas/*.spec.js 
```
All tests in the `schema` directory has something like this  `test.describe.parallel("@schema-endpointX" ...`, so the `schema` project will grep for `@schema` and the `api` project will grepInvert `@schema`, if I understood the feature correctly.


```javascript
# playwright.config.js
const config = {
    testDir: "tests/api",
    retries: 1,
    reporter: process.env.CI
        ? [["dot"], ["html", { outputFolder: "test-results", open: "never" }]]
        : [["line"], ["html", { outputFolder: "test-results", open: "never" }]],
    workers: process.env.CI ? 2 : undefined,

    webServer: {
        command: "npx serverest --nodoc",
        port: 3000,
        timeout: 60 * 1000,
        reuseExistingServer: !process.env.CI,
        cwd: ".",
    },

    use: {
        headless: true,
        baseURL: "http://localhost:3000",
    },

    projects: [
        {
            name: "api",
            outputDir: "../test-results/api/",
            grepInvert: "@schema",
        },
        {
            name: "schema",
            outputDir: "../test-results/schema/",
            grep: "@schema",
        },
    ],
}

module.exports = config
```

**Comment by pavelfeldman** [comment]
<img width="513" alt="Screen Shot 2022-03-15 at 5 18 27 PM" src="https://user-images.githubusercontent.com/883973/158492863-4e6deb19-4e48-4467-b076-b903827b7230.png">

**Comment by awarecan** [comment]
It breaks the compile of my test config
```
test/cmp/cmp.config.ts(16,29): error TS2345: Argument of type '(config: PlaywrightTestConfig<{}, {}>) => void' is not assignable to parameter of type '(value: Project<PlaywrightTestOptions & TssTestOptions, PlaywrightWorkerOptions>, index: number, array: Project<...>[]) => void'.
  Types of parameters 'config' and 'value' are incompatible.
    Type 'Project<PlaywrightTestOptions & TssTestOptions, PlaywrightWorkerOptions>' is not assignable to type 'PlaywrightTestConfig<{}, {}>'.
      Types of property 'grepInvert' are incompatible.
        Type 'RegExp | RegExp[] | null | undefined' is not assignable to type 'RegExp | RegExp[] | undefined'.
          Type 'null' is not assignable to type 'RegExp | RegExp[] | undefined'.
```

My cmp.config.ts
```typescript
import { default as baseConfig } from '../../playwright.config';

baseConfig.projects = [
    {
        name: "Smoke",
        testDir: "./",
        testMatch: "Smoke.spec.ts"
    },
    {
        name: "All",
        testDir: "./",
    }
]

export default baseConfig;
```

My playwright.conifg.ts, redacted version
```typescript
const config: TestConfig<MyTestOptions> = {
  use: {
    browserName: "chromium",
    headless: true,
  }
};
export default config;
```

**Comment by pavelfeldman** [comment]
@[awarecan](https://github.com/awarecan) not sure what you are doing here, but anyways looks unrelated, please file a bug with the repro!

**Comment by anastasiyamazheika** [comment]
Hello!
I try to use `--grep-invert` in the terminal and get "`no tests found`" when there're tests without the provided tag. 

Playwright version: 1.23.3
