### ISSUE TITLE
[BUG] Playwright 1.20.0 Frame load interrupted thrown in Webkit

### ISSUE THREAD

**Issue by thebencourt** [microsoft/playwright#12848]
**Context:**
## System:
 - OS: Linux 5.10 Ubuntu 21.10 21.10 (Impish Indri)
 - Memory: 19.14 GB / 24.84 GB
 - Container: Yes
## Binaries:
 - Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
 - npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/bin/bash

**Code Snippet**

```javascript
import { test } from "@playwright/test";

test("frame load interrupted", async ({ page }) => {
  await page.goto(`https://www.bbc.co.uk`);

  await Promise.all([
    page.waitForNavigation(),
    page.click('a:has-text("Sign in")'),
  ]);
});
```

**Describe the bug**

Following the example [here](https://playwright.dev/docs/api/class-page#page-wait-for-navigation) the test above passes in both chrome and firefox but throws the following error in webkit:

```
  1) [webkit] › example.spec.ts:3:1 › frame load interrupted =======================================

    page.waitForNavigation: Frame load interrupted
    =========================== logs ===========================
    waiting for navigation until "load"
    ============================================================

       8 |
       9 |   await Promise.all([
    > 10 |     page.waitForNavigation(),
         |          ^
      11 |     page.click('a:has-text("Sign in")'),
      12 |   ]);
      13 | });

        at /home/ben/Code/test/tests/example.spec.ts:10:10
        at /home/ben/Code/test/node_modules/@playwright/test/lib/workerRunner.js:388:7
        at TestInfoImpl._runFn (/home/ben/Code/test/node_modules/@playwright/test/lib/testInfo.js:182:7)
        at WorkerRunner._runTestWithBeforeHooks (/home/ben/Code/test/node_modules/@playwright/test/lib/workerRunner.js:363:24)
        at TestInfoImpl._runWithTimeout (/home/ben/Code/test/node_modules/@playwright/test/lib/testInfo.js:154:7)
        at WorkerRunner._runTestOrAllHook (/home/ben/Code/test/node_modules/@playwright/test/lib/workerRunner.js:325:5)
        at WorkerRunner._runSuite (/home/ben/Code/test/node_modules/@playwright/test/lib/workerRunner.js:238:43)
        at WorkerRunner.run (/home/ben/Code/test/node_modules/@playwright/test/lib/workerRunner.js:167:9)
        at process.<anonymous> (/home/ben/Code/test/node_modules/@playwright/test/lib/worker.js:94:5)


  1 failed
    [webkit] › example.spec.ts:3:1 › frame load interrupted ========================================
  2 passed (7s)
```

**Comment by thebencourt** [comment]
I've tried installing `@playwright/test@next` (`1.21.0-alpha-mar-17-2022`) but the result is the same

**Comment by pavelfeldman** [comment]
If you try opening this page with `npx playwright wk https://www.bbc.co.uk`, you'll see that it opens, and then reloads. This is what the user that loads BBC for the first time on Safari observes. This navigation is scheduled while you are attempting to click.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
