### ISSUE TITLE
[BUG] Reusing a single page between tests prevents video from recording

### ISSUE THREAD

**Issue by dossy** [microsoft/playwright#13104]
**Context:**
- Playwright Version: 1.20.0
- Operating System: macOS 11.6.2
- Node.js version: 17.2.0
- Browser: Chromium

**Code Snippet**

```javascript
// package.json

{
  "devDependencies": {
    "@playwright/test": "^1.20.0"
  }
}
```

```javascript
// playwright.config.js

const path = require('path');

const config = {
  testDir: path.join(__dirname, 'tests'),
  outputDir: 'results/',
  use: {
    video: 'on'
  }
};

module.exports = config;
```

```javascript
// tests/working.spec.js

const { test, expect } = require('@playwright/test');

test.describe.configure({ mode: 'serial' });

test.describe(`don't reuse browser page`, async () => {
  test.describe('nested suite', async () => {
    test('first test', async ({ page }) => {
      await page.locator('body').click();

      await expect(page.locator('body')).toHaveCount(1);
    });

    test('second test', async ({ page }) => {
      await page.locator('body').click();

      await expect(page.locator('body')).toHaveCount(1);

      await expect(true).toBe(false);
    });
  });
});
```

```javascript
// tests/broken.spec.js

const { test, expect } = require('@playwright/test');

test.describe.configure({ mode: 'serial' });

test.describe('reuse browser page', async () => {
  test.describe('nested suite', async () => {
    let page;

    test.beforeAll(async ({ browser }) => {
      page = await browser.newPage();
    });

    test.afterAll(async () => {
      await page.close();
    });

    test('first test', async () => {
      await page.locator('body').click();

      await expect(page.locator('body')).toHaveCount(1);
    });

    test('second test', async () => {
      await page.locator('body').click();

      await expect(page.locator('body')).toHaveCount(1);

      await expect(true).toBe(false);
    });
  });
});
```

**Describe the bug**

When [reusing a single page between tests](https://playwright.dev/docs/test-retries#reuse-single-page-between-tests), as in the `tests/broken.spec.js` above, when a test fails, it does not include the video attachment that is configured in `playwright.config.js` using [testOptions.video](https://playwright.dev/docs/api/class-testoptions#test-options-video).

You can observe the issue by running `npx playwright test tests/working.spec.js` and see how when the second test fails, there's a video attached, like this:

```
Running 2 tests using 1 worker

  ✓  working.spec.js:9:5 › don't reuse browser page › nested suite › first test (656ms)
  ✘  working.spec.js:15:5 › don't reuse browser page › nested suite › second test (185ms)


  1) working.spec.js:15:5 › don't reuse browser page › nested suite › second test ==================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      18 |       await expect(page.locator('body')).toHaveCount(1);
      19 |
    > 20 |       await expect(true).toBe(false);
         |                          ^
      21 |     });
      22 |   });
      23 | });

        at /Volumes/Alt-ExternalHD/Users/dossy/Work/ServiceFirstPermits/dev/test/tests/working.spec.js:20:26

    attachment #1: video (video/webm) --------------------------------------------------------------
    results/working-don-t-reuse-browser-page-nested-suite-second-test/video.webm
    ------------------------------------------------------------------------------------------------


  1 failed
    working.spec.js:15:5 › don't reuse browser page › nested suite › second test ===================
  1 passed (1s)
```

But, notice how there's no video attached when running `npx playwright test tests/broken.spec.js` when the second test fails, like this:

```
Running 2 tests using 1 worker

  ✓  broken.spec.js:19:5 › reuse browser page › nested suite › first test (75ms)
  ✘  broken.spec.js:25:5 › reuse browser page › nested suite › second test (26ms)


  1) broken.spec.js:25:5 › reuse browser page › nested suite › second test =========================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      28 |       await expect(page.locator('body')).toHaveCount(1);
      29 |
    > 30 |       await expect(true).toBe(false);
         |                          ^
      31 |     });
      32 |   });
      33 | });

        at /Volumes/Alt-ExternalHD/Users/dossy/Work/ServiceFirstPermits/dev/test/tests/broken.spec.js:30:26


  1 failed
    broken.spec.js:25:5 › reuse browser page › nested suite › second test ==========================
  1 passed (1s)
```

**Comment by rwoll** [comment]
Thanks for your report! This looks like an outstanding issue we still need to address.

---

Debug notes: Move the video bits of `_contextFactory` into the event-based instrumentation hooks that get triggered on `browser.newPage()` invocation.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/9002

**Comment by autTestUser** [comment]
> Thanks for your report! This looks like an outstanding issue we still need to address.
> 
> Debug notes: Move the video bits of `_contextFactory` into the event-based instrumentation hooks that get triggered on `browser.newPage()` invocation.

Any idea when this will be done? I'm facing the same issue on fixtures as well. If I create an automatic fixture and create a page instance in this fixture with a browser instance, videos are not captured.
