### ISSUE TITLE
[BUG] Docker m1 mac crashes Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by davidbielik** [microsoft/playwright#13201]
**Context:**
- Playwright Version: mcr.microsoft.com/playwright:v1.20.0-focal
- Operating System: Mac M1
- Node.js version: v16.14.0
- Browser: Chromium
- Extra: Docker

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // Create pages, interact with UI elements, assert values
  const page = await browser.newPage();
  await page.goto('https://www.google.com');
  console.log(
    await page.evaluate(() => {
      return document.title;
    })
  );
  await browser.close();
})();
```

Dockerfile:
```
FROM --platform=linux/amd64 mcr.microsoft.com/playwright:v1.20.0-focal

RUN groupadd -r crawluser && useradd --uid 999 -r -g crawluser -G audio,video crawluser && \
  mkdir -p /home/crawluser/Downloads && \
  chown -R crawluser:crawluser /home/crawluser

WORKDIR /tmp

COPY package*.json ./
RUN npm ci;
RUN mkdir -p /home/node/app && cp -a /tmp/node_modules /home/node/app/

WORKDIR /home/node/app
COPY . /home/node/app

USER crawluser

CMD ["node", "test.js"];
```

package.json
```
{
  "name": "playwright",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "author": "",
  "license": "ISC",
  "dependencies": {
    "playwright": "^1.20.0"
  }
}
```

docker-compose.yml
```
version: '3'
services:
  playwright:
    build: .
    volumes:
      - './test.js:/home/node/app/test.js'
```

**Describe the bug**

I'm just starting out trying to switch over from puppeteer, have a very basic example but getting this crash. Let me know if there's a more helpful way to share (I can zip up the project if that's easier).

To repro, create the files above and then run: `docker-compose up --build --force-recreate`

**Stack Trace**

```
Attaching to playwright-playwright-1
playwright-playwright-1  | node:internal/process/promises:265
playwright-playwright-1  |             triggerUncaughtException(err, true /* fromPromise */);
playwright-playwright-1  |             ^
playwright-playwright-1  | 
playwright-playwright-1  | browserType.launch: Browser closed.
playwright-playwright-1  | ==================== Browser output: ====================
playwright-playwright-1  | <launching> /ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-h1bYDf --remote-debugging-pipe --no-startup-window
playwright-playwright-1  | <launched> pid=255
playwright-playwright-1  | [pid=255][err] [0331/011938.396274:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
playwright-playwright-1  | [pid=255][err] [0331/011938.799357:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
playwright-playwright-1  | [pid=255][err] [0331/011938.816598:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
playwright-playwright-1  | [pid=255][err] [0331/011938.835086:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
playwright-playwright-1  | [pid=255][err] #0 0x004006f3a369 <unknown>
playwright-playwright-1  | [pid=255][err] #1 0x004006ea08c3 <unknown>
playwright-playwright-1  | [pid=255][err] #2 0x004006eb3650 <unknown>
playwright-playwright-1  | [pid=255][err] #3 0x004006eb41fe <unknown>
playwright-playwright-1  | [pid=255][err] #4 0x004006a57046 <unknown>
playwright-playwright-1  | [pid=255][err] #5 0x004006a51fc0 <unknown>
playwright-playwright-1  | [pid=255][err] #6 0x004006a52be9 <unknown>
playwright-playwright-1  | [pid=255][err] #7 0x004006a5387b <unknown>
playwright-playwright-1  | [pid=255][err] #8 0x004006a50cb4 <unknown>
playwright-playwright-1  | [pid=255][err] #9 0x004006a515ce <unknown>
playwright-playwright-1  | [pid=255][err] #10 0x004006aacc5a <unknown>
playwright-playwright-1  | [pid=255][err] #11 0x004006aacb13 <unknown>
playwright-playwright-1  | [pid=255][err] #12 0x004006aab755 <unknown>
playwright-playwright-1  | [pid=255][err] #13 0x004003571fa8 <unknown>
playwright-playwright-1  | [pid=255][err] #14 0x00400f3270b3 <unknown>
playwright-playwright-1  | [pid=255][err] #15 0x004003571dea <unknown>
playwright-playwright-1  | [pid=255][err] 
playwright-playwright-1  | [pid=255][err] [0331/011938.851308:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
playwright-playwright-1  | [pid=255][err] #0 0x004006f3a369 <unknown>
playwright-playwright-1  | [pid=255][err] #1 0x004006ea08c3 <unknown>
playwright-playwright-1  | [pid=255][err] #2 0x004006eb3650 <unknown>
playwright-playwright-1  | [pid=255][err] #3 0x004006eb41fe <unknown>
playwright-playwright-1  | [pid=255][err] #4 0x004006a57046 <unknown>
playwright-playwright-1  | [pid=255][err] #5 0x004006a51fc0 <unknown>
playwright-playwright-1  | [pid=255][err] #6 0x004006a52be9 <unknown>
playwright-playwright-1  | [pid=255][err] #7 0x004006a5387b <unknown>
playwright-playwright-1  | [pid=255][err] #8 0x004006a50cb4 <unknown>
playwright-playwright-1  | [pid=255][err] #9 0x004006a515ce <unknown>
playwright-playwright-1  | [pid=255][err] #10 0x004006aacc5a <unknown>
playwright-playwright-1  | [pid=255][err] #11 0x004006aacb13 <unknown>
playwright-playwright-1  | [pid=255][err] #12 0x004006aab755 <unknown>
playwright-playwright-1  | [pid=255][err] #13 0x004003571fa8 <unknown>
playwright-playwright-1  | [pid=255][err] #14 0x00400f3270b3 <unknown>
playwright-playwright-1  | [pid=255][err] #15 0x004003571dea <unknown>
playwright-playwright-1  | [pid=255][err] 
playwright-playwright-1  | [pid=255][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
playwright-playwright-1  | [pid=255][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
playwright-playwright-1  | [pid=255][err] Received signal 11 SEGV_MAPERR d0dcd9c901091525
playwright-playwright-1  | [pid=255][err] #0 0x004006f3a369 <unknown>
playwright-playwright-1  | [pid=255][err] #1 0x004006ea08c3 <unknown>
playwright-playwright-1  | [pid=255][err] #2 0x004006f39e71 <unknown>
playwright-playwright-1  | [pid=255][err] #3 0x00400e6033c0 <unknown>
playwright-playwright-1  | [pid=255][err] #4 0x0040077e7ca0 <unknown>
playwright-playwright-1  | [pid=255][err] #5 0x0040077f5bec <unknown>
playwright-playwright-1  | [pid=255][err] #6 0x0040077f5b42 <unknown>
playwright-playwright-1  | [pid=255][err] #7 0x0040077ee251 <unknown>
playwright-playwright-1  | [pid=255][err] #8 0x0040077e4ab1 <unknown>
playwright-playwright-1  | [pid=255][err] #9 0x0040077ea526 <unknown>
playwright-playwright-1  | [pid=255][err] #10 0x0040077ea5be <unknown>
playwright-playwright-1  | [pid=255][err] #11 0x0040077e0357 <unknown>
playwright-playwright-1  | [pid=255][err] #12 0x0040077e0297 <unknown>
playwright-playwright-1  | [pid=255][err] #13 0x0040077ee621 <unknown>
playwright-playwright-1  | [pid=255][err] #14 0x0040077df742 <unknown>
playwright-playwright-1  | [pid=255][err] #15 0x004007873287 <unknown>
playwright-playwright-1  | [pid=255][err] #16 0x00400493e93d <unknown>
playwright-playwright-1  | [pid=255][err] #17 0x00400c36682d <unknown>
playwright-playwright-1  | [pid=255][err] #18 0x004006a52862 <unknown>
playwright-playwright-1  | [pid=255][err] #19 0x004006a53d0f <unknown>
playwright-playwright-1  | [pid=255][err] #20 0x004006a5389f <unknown>
playwright-playwright-1  | [pid=255][err] #21 0x004006a50cb4 <unknown>
playwright-playwright-1  | [pid=255][err] #22 0x004006a515ce <unknown>
playwright-playwright-1  | [pid=255][err] #23 0x004006aacc5a <unknown>
playwright-playwright-1  | [pid=255][err] #24 0x004006aac965 <unknown>
playwright-playwright-1  | [pid=255][err] #25 0x004003571fa8 <unknown>
playwright-playwright-1  | [pid=255][err] #26 0x00400f3270b3 <unknown>
playwright-playwright-1  | [pid=255][err] #27 0x004003571dea <unknown>
playwright-playwright-1  | [pid=255][err]   r8: 00000c400037c000  r9: 000000000000000a r10: aaaaaaaaaaaaaaaa r11: aaaaaaaaaaaaaaaa
playwright-playwright-1  | [pid=255][err]  r12: 0000004001ca83dc r13: 00000c400035faf0 r14: 00000c40002f4000 r15: 00000c4000399c40
playwright-playwright-1  | [pid=255][err]   di: 00000c400037c000  si: 000000000000000a  bp: 000000400e5a95b0  bx: 00000c400039bae0
playwright-playwright-1  | [pid=255][err]   dx: 0000002ece54eb68  ax: d0dcd9c90109151d  cx: 0000000000000008  sp: 000000400e5a9580
playwright-playwright-1  | [pid=255][err]   ip: 00000040077e7ca0 efl: 0000000000000286 cgf: 002b000000000033 erf: 0000000000000004
playwright-playwright-1  | [pid=255][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: d0dcd9c901091525
playwright-playwright-1  | [pid=255][err] [end of stack trace]
playwright-playwright-1  | [pid=255][err] qemu: uncaught target signal 11 (Segmentation fault) - core dumped
playwright-playwright-1  | =========================== logs ===========================
playwright-playwright-1  | <launching> /ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-h1bYDf --remote-debugging-pipe --no-startup-window
playwright-playwright-1  | <launched> pid=255
playwright-playwright-1  | [pid=255][err] [0331/011938.396274:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
playwright-playwright-1  | [pid=255][err] [0331/011938.799357:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
playwright-playwright-1  | [pid=255][err] [0331/011938.816598:ERROR:stack_trace_posix.cc(707)] Failed to parse the contents of /proc/self/maps
playwright-playwright-1  | [pid=255][err] [0331/011938.835086:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
playwright-playwright-1  | [pid=255][err] #0 0x004006f3a369 <unknown>
playwright-playwright-1  | [pid=255][err] #1 0x004006ea08c3 <unknown>
playwright-playwright-1  | [pid=255][err] #2 0x004006eb3650 <unknown>
playwright-playwright-1  | [pid=255][err] #3 0x004006eb41fe <unknown>
playwright-playwright-1  | [pid=255][err] #4 0x004006a57046 <unknown>
playwright-playwright-1  | [pid=255][err] #5 0x004006a51fc0 <unknown>
playwright-playwright-1  | [pid=255][err] #6 0x004006a52be9 <unknown>
playwright-playwright-1  | [pid=255][err] #7 0x004006a5387b <unknown>
playwright-playwright-1  | [pid=255][err] #8 0x004006a50cb4 <unknown>
playwright-playwright-1  | [pid=255][err] #9 0x004006a515ce <unknown>
playwright-playwright-1  | [pid=255][err] #10 0x004006aacc5a <unknown>
playwright-playwright-1  | [pid=255][err] #11 0x004006aacb13 <unknown>
playwright-playwright-1  | [pid=255][err] #12 0x004006aab755 <unknown>
playwright-playwright-1  | [pid=255][err] #13 0x004003571fa8 <unknown>
playwright-playwright-1  | [pid=255][err] #14 0x00400f3270b3 <unknown>
playwright-playwright-1  | [pid=255][err] #15 0x004003571dea <unknown>
playwright-playwright-1  | [pid=255][err] 
playwright-playwright-1  | [pid=255][err] [0331/011938.851308:FATAL:zygote_main_linux.cc(161)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded(). 
playwright-playwright-1  | [pid=255][err] #0 0x004006f3a369 <unknown>
playwright-playwright-1  | [pid=255][err] #1 0x004006ea08c3 <unknown>
playwright-playwright-1  | [pid=255][err] #2 0x004006eb3650 <unknown>
playwright-playwright-1  | [pid=255][err] #3 0x004006eb41fe <unknown>
playwright-playwright-1  | [pid=255][err] #4 0x004006a57046 <unknown>
playwright-playwright-1  | [pid=255][err] #5 0x004006a51fc0 <unknown>
playwright-playwright-1  | [pid=255][err] #6 0x004006a52be9 <unknown>
playwright-playwright-1  | [pid=255][err] #7 0x004006a5387b <unknown>
playwright-playwright-1  | [pid=255][err] #8 0x004006a50cb4 <unknown>
playwright-playwright-1  | [pid=255][err] #9 0x004006a515ce <unknown>
playwright-playwright-1  | [pid=255][err] #10 0x004006aacc5a <unknown>
playwright-playwright-1  | [pid=255][err] #11 0x004006aacb13 <unknown>
playwright-playwright-1  | [pid=255][err] #12 0x004006aab755 <unknown>
playwright-playwright-1  | [pid=255][err] #13 0x004003571fa8 <unknown>
playwright-playwright-1  | [pid=255][err] #14 0x00400f3270b3 <unknown>
playwright-playwright-1  | [pid=255][err] #15 0x004003571dea <unknown>
playwright-playwright-1  | [pid=255][err] 
playwright-playwright-1  | [pid=255][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
playwright-playwright-1  | [pid=255][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
playwright-playwright-1  | [pid=255][err] Received signal 11 SEGV_MAPERR d0dcd9c901091525
playwright-playwright-1  | [pid=255][err] #0 0x004006f3a369 <unknown>
playwright-playwright-1  | [pid=255][err] #1 0x004006ea08c3 <unknown>
playwright-playwright-1  | [pid=255][err] #2 0x004006f39e71 <unknown>
playwright-playwright-1  | [pid=255][err] #3 0x00400e6033c0 <unknown>
playwright-playwright-1  | [pid=255][err] #4 0x0040077e7ca0 <unknown>
playwright-playwright-1  | [pid=255][err] #5 0x0040077f5bec <unknown>
playwright-playwright-1  | [pid=255][err] #6 0x0040077f5b42 <unknown>
playwright-playwright-1  | [pid=255][err] #7 0x0040077ee251 <unknown>
playwright-playwright-1  | [pid=255][err] #8 0x0040077e4ab1 <unknown>
playwright-playwright-1  | [pid=255][err] #9 0x0040077ea526 <unknown>
playwright-playwright-1  | [pid=255][err] #10 0x0040077ea5be <unknown>
playwright-playwright-1  | [pid=255][err] #11 0x0040077e0357 <unknown>
playwright-playwright-1  | [pid=255][err] #12 0x0040077e0297 <unknown>
playwright-playwright-1  | [pid=255][err] #13 0x0040077ee621 <unknown>
playwright-playwright-1  | [pid=255][err] #14 0x0040077df742 <unknown>
playwright-playwright-1  | [pid=255][err] #15 0x004007873287 <unknown>
playwright-playwright-1  | [pid=255][err] #16 0x00400493e93d <unknown>
playwright-playwright-1  | [pid=255][err] #17 0x00400c36682d <unknown>
playwright-playwright-1  | [pid=255][err] #18 0x004006a52862 <unknown>
playwright-playwright-1  | [pid=255][err] #19 0x004006a53d0f <unknown>
playwright-playwright-1  | [pid=255][err] #20 0x004006a5389f <unknown>
playwright-playwright-1  | [pid=255][err] #21 0x004006a50cb4 <unknown>
playwright-playwright-1  | [pid=255][err] #22 0x004006a515ce <unknown>
playwright-playwright-1  | [pid=255][err] #23 0x004006aacc5a <unknown>
playwright-playwright-1  | [pid=255][err] #24 0x004006aac965 <unknown>
playwright-playwright-1  | [pid=255][err] #25 0x004003571fa8 <unknown>
playwright-playwright-1  | [pid=255][err] #26 0x00400f3270b3 <unknown>
playwright-playwright-1  | [pid=255][err] #27 0x004003571dea <unknown>
playwright-playwright-1  | [pid=255][err]   r8: 00000c400037c000  r9: 000000000000000a r10: aaaaaaaaaaaaaaaa r11: aaaaaaaaaaaaaaaa
playwright-playwright-1  | [pid=255][err]  r12: 0000004001ca83dc r13: 00000c400035faf0 r14: 00000c40002f4000 r15: 00000c4000399c40
playwright-playwright-1  | [pid=255][err]   di: 00000c400037c000  si: 000000000000000a  bp: 000000400e5a95b0  bx: 00000c400039bae0
playwright-playwright-1  | [pid=255][err]   dx: 0000002ece54eb68  ax: d0dcd9c90109151d  cx: 0000000000000008  sp: 000000400e5a9580
playwright-playwright-1  | [pid=255][err]   ip: 00000040077e7ca0 efl: 0000000000000286 cgf: 002b000000000033 erf: 0000000000000004
playwright-playwright-1  | [pid=255][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: d0dcd9c901091525
playwright-playwright-1  | [pid=255][err] [end of stack trace]
playwright-playwright-1  | [pid=255][err] qemu: uncaught target signal 11 (Segmentation fault) - core dumped
playwright-playwright-1  | ============================================================
playwright-playwright-1  |     at /home/node/app/test.js:4:34
playwright-playwright-1  |     at Object.<anonymous> (/home/node/app/test.js:14:3) {
playwright-playwright-1  |   name: 'Error'
playwright-playwright-1  | }
playwright-playwright-1 exited with code 1
```

I see https://github.com/microsoft/playwright/issues/7723 or https://github.com/microsoft/playwright/issues/9435 was maybe was meant to address this but didn't see any new instructions or documentation.

**Comment by rwoll** [comment]
In the first line of your Dockerfile, remove `--platform=linux/amd64`. This prevented Docker from picking the proper M1 base image.

Is there a reason you had that line, or is it copy-pasta?

Let us know if that works! (You might also have to force docker-compose to clean some build caches due to running the previously broken bit.)

**Comment by davidbielik** [comment]
Thanks @rwoll! Yes, that was leftover from days and days of struggling to get puppeteer working (shout out to https://github.com/puppeteer/puppeteer/issues/7916). 

Thanks for your help and looking forward to learning more about playwright!

**Comment by Unit111** [comment]
What worked for me was updating my Docker Desktop to a version higher that 4.25. Adding/removing `platform=linux/amd64` made no difference.
