### ISSUE TITLE
[Question] Linux chromium fail to start

### ISSUE THREAD

**Issue by chenshy39** [microsoft/playwright#13295]
Hello, I found something error in my linux e2e test project.  
I use `test.spec.mjs` file and `npx playwright test` to execute my test file, but in the Linux there is an error like: 
```
Running 4 tests using 4 workers
  1) record-101/test-339.spec.mjs:70:1 › notitle =======================================================

    browserType.launch: Failed to launch: Error: spawn /root/.cache/ms-playwright/chromium-978106/chrome-linux/chrome ENOENT
    =========================== logs ===========================
    <launching> /root/.cache/ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-hpomFP --remote-debugging-pipe --no-startup-window
    [pid=N/A] starting temporary directories cleanup
    [pid=N/A] finished temporary directories cleanup
    ============================================================
``` 
but I go for the chromium file and I really get it:
```
~ # cd .cache/ms-playwright/chromium-978106/chrome-linux/
~/.cache/ms-playwright/chromium-978106/chrome-linux # ls
ClearKeyCdm              icudtl.dat               resources.pak
MEIPreload               libEGL.so                swiftshader
chrome                   libGLESv2.so             v8_context_snapshot.bin
chrome-wrapper           libvk_swiftshader.so     vk_swiftshader_icd.json
chrome_100_percent.pak   libvulkan.so.1           xdg-mime
chrome_200_percent.pak   locales                  xdg-settings
chrome_crashpad_handler  product_logo_48.png
chrome_sandbox           resources
```
It's really wired.

I dont know this is playwright error or an system config problem, look for your answer, thanks a lot.

**Comment by mxschmitt** [comment]
Maybe you launch it under different users?

Which Playwright version are you using? Which linux distribution are you using? Whats your architecture?

**Comment by chenshy39** [comment]
there is more informations:
Playwright version: 1.20.1
Node: v14.8.0
Linux distribution: Debian 8.3.0-6, gcc version 8.3.0

**Comment by mxschmitt** [comment]
And which architecture is this, amd64? Keep in mind that only Ubuntu 18.04 and 20.04 are supported officially.

**Comment by mxschmitt** [comment]
this should not be reason. Could you try to execute `file /root/.cache/ms-playwright/chromium-978106/chrome-linux/chrome` to verify the file is there and its the right executable?

**Comment by chenshy39** [comment]
Sorry for the belated reply. I found the problem maybe caused by I do not use dockerfile but use only `npm install` and `npm install playwright`.
But there is a new issue is when i execute:
```
PWDEBUG=1 PLAYWRIGHT_BROWSERS_PATH=../../ms-playwright npx playwright test
```
reply:
```
browserType.launch: Browser closed.
    ==================== Browser output: ====================
    <launching> /appops/ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-SYYvTS --remote-debugging-pipe --no-startup-window
    <launched> pid=535
    [pid=535][err] [535:535:0407/014305.565188:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
    [pid=535][err] [535:535:0407/014305.571205:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
    =========================== logs ===========================
    <launching> /appops/ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-SYYvTS --remote-debugging-pipe --no-startup-window
    <launched> pid=535
    [pid=535][err] [535:535:0407/014305.565188:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
    [pid=535][err] [535:535:0407/014305.571205:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
    ============================================================

        at Object._baseTest.extend.browser.scope [as fn] (/appops/node_modules/@playwright/test/lib/index.js:183:51)
        at /appops/node_modules/@playwright/test/lib/fixtures.js:78:81
```
More Informations: My dockerfile
```
FROM mcr.microsoft.com/playwright:v1.20.1-focal

WORKDIR /appops

COPY *.json /appops/

RUN npm install

RUN PLAYWRIGHT_BROWSERS_PATH=./ms-playwright npx playwright install --with-deps

RUN chmod 4755 ./ms-playwright

COPY . /appops

RUN npm run tsc

CMD npm start
```

**Comment by chenshy39** [comment]
And I execute `file /ms-playwright/chromium-978106/chrome-linux/chrome`
get
```
# file chrome
chrome: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[xxHash]=262b9d5539aef9ae, not stripped
```

**Comment by chenshy39** [comment]
I open an issue for the new problem : https://github.com/microsoft/playwright/issues/13381
