### ISSUE TITLE
[BUG] expect(page).toHaveURL not recognized when running with terminal

### ISSUE THREAD

**Issue by aisabel** [microsoft/playwright#13344]
**Context:**
- Playwright Version: 1.20.1
- Operating System: [e.g. Windows]
- Node.js version: [v16.14.2]
- Browser: [Chromium]
- Extra: [visual studio code]

**Describe the bug**
Create a playwright testcase using _npx playwright codegen myurl.com_
Copy the script from the inspector and visualize automatically includes assertions like: await expect(page).toHaveURL("_mywebpage_")
Save the test as myTest.spec.ts
Run this script using terminal by executing command: _npx playwright test myTest.spec.ts_
Visualize there's an issue with a character _&_

**Note: I have replaced the real urls for confidentiality.

    > 24 |     await expect(page).toHaveURL('https://myurl.com/home&');
         |                        

  1 failed
    [chromium] › validateMenuElements.spec.ts:3:1 › test ===========================================
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9323
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at HttpServer.start (C:\Users\username\Playwright-Sample\node_modules\playwright-core\lib\utils\httpServer.js:85:18)
    at showHTMLReport (C:\Users\username\Playwright-Sample\node_modules\@playwright\test\lib\reporters\html.js:125:26)
    at HtmlReporter.onEnd (C:\Users\username\Playwright-Sample\node_modules\@playwright\test\lib\reporters\html.js:90:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Multiplexer.onEnd (C:\Users\username\Playwright-Sample\node_modules\@playwright\test\lib\reporters\multiplexer.js:74:45)
    at Runner.runAllTests (C:\Users\username\Playwright-Sample\node_modules\@playwright\test\lib\runner.js:202:5)
    at runTests (C:\Users\username\Playwright-Sample\node_modules\@playwright\test\lib\cli.js:184:18)
    at Command.<anonymous> (C:\Users\username\Playwright-Sample\node_modules\@playwright\test\lib\cli.js:79:7)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1357:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 9323
}

**Comment by liuxingbaoyu** [comment]
There is a node process already running, try taskkill

**Comment by aisabel** [comment]
Can you please be more specific and provide more detail? Which other node process is running?
taskill in terminal retrieves 
_ERROR: Invalid syntax. Neither /FI nor /PID nor /IM were specified.
Type "TASKKILL /?" for usage._

**Comment by liuxingbaoyu** [comment]
nodejs httpserver process is running, kill it using process manager

**Comment by aisabel** [comment]
Also when clicking "play" button within the inspector, then those assertions for toHaveUrl fail. 
However they pass if clicking the "step by step" button.

**Comment by mxschmitt** [comment]
In this issue the problem seems more that something is running on the port rather than with toHaveURL itself?

**Comment by aisabel** [comment]
> In this issue the problem seems more that something is running on the port rather than with toHaveURL itself?

There's nothing else more running in the port. I have killed the other task as suggested

**Comment by aslushnikov** [comment]
Does it still reproduce for you? There is a hanging process for sure; could you please try rebooting to make sure all processes are cleared? If it still reproes, can you list the steps to repro this so that we can run it locally and see the issue by ourselves?

**Comment by aslushnikov** [comment]
So far this doesn't look like a Playwright issue; please re-file if this persists and you think we can help you!
