### ISSUE TITLE
[BUG] Unable to open the browser using playwright cli and code. TimeoutError thrown

### ISSUE THREAD

**Issue by some-sh** [microsoft/playwright#13393]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Windows 11
- Node.js version: 17.7.1
- Browser: All
- Extra: [any specific details about your environment]

`playwright open https://www.google.com/ --timeout 30000`

**Code Snippet**
``` Python
from playwright.sync_api import sync_playwright
playwright = sync_playwright().start()
# Use playwright.chromium, playwright.firefox or playwright.webkit
# Pass headless=False to launch() to see the browser UI
browser = playwright.chromium.launch()
page = browser.new_page()
page.goto("http://whatsmyuseragent.org/")
page.screenshot(path="example.png")
browser.close()
playwright.stop()
```

**Describe the bug**
I'm unable to open the browser. Tried to open the browser using `playwright open`. Didn't work. Tried to open using code. Didn't work. 
Defaults browsers installed using `playwright install`

After 30 secs, Timeout error is thrown. 

```
command.<anonymous>: Timeout 30000ms exceeded.
    at Command.listener [as _actionHandler] (E:\somesh\code\py\venv\Lib\site-ackages\playwright\driver\package\node_modules\commander\lib\command.js:488:17) {
  name: 'TimeoutError'
}
```

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Does your system has enterprise policies applied?

Could you try setting the following environment variable? `DEBUG=pw:browser` in powershell something like that might work: `$env:DEBUG="pw:browser"`.

**Comment by some-sh** [comment]
> Does your system has enterprise policies applied?

I'm not exactly sure what that means. My browser like Google Chrome, Firefox, Edge have an extension installed by my company. But that extension is not installed in the browsers installed by playwright

> Debug print:

```
 pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: 'C:\\Users\\somesh\\AppData\\Local\\ms-playwright\\chromium-965416\\chrome-win\\chrome.exe',
  pw:channel:event       name: 'chromium'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@1ab9f411e856c75fbecb3a0805d5ec33'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: 'C:\\Users\\somesh\\AppData\\Local\\ms-playwright\\firefox-1316\\firefox\\firefox.exe',
  pw:channel:event       name: 'firefox'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@af592df61fa46e66e2030cf12eac132d'
  pw:channel:event   }
  pw:channel:event } +12ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: 'C:\\Users\\somesh\\AppData\\Local\\ms-playwright\\webkit-1609\\Playwright.exe',
  pw:channel:event       name: 'webkit'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@d9ab48a506cb7bb276e74e44ca59e751'
  pw:channel:event   }
  pw:channel:event } +2ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Android',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'android@7fd6e039b2064dc4f5ee3fc00ab53b46'
  pw:channel:event   }
  pw:channel:event } +3ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Electron',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'electron@23f8f575717279017b809447fb8d554e'
  pw:channel:event   }
  pw:channel:event } +2ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'LocalUtils',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'localUtils@77fd5c01b5f81efe7d2fb8660375c5a9'
  pw:channel:event   }
  pw:channel:event } +4ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Selectors',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'selectors@272f7f1ebbb728c29df1e18e088a2645'
  pw:channel:event   }
  pw:channel:event } +3ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Playwright',
  pw:channel:event     initializer: {
  pw:channel:event       chromium: [Object],
  pw:channel:event       firefox: [Object],
  pw:channel:event       webkit: [Object],
  pw:channel:event       android: [Object],
  pw:channel:event       electron: [Object],
  pw:channel:event       utils: [Object],
  pw:channel:event       deviceDescriptors: [Array],
  pw:channel:event       selectors: [Object],
  pw:channel:event       preLaunchedBrowser: undefined
  pw:channel:event     },
  pw:channel:event     guid: 'Playwright'
  pw:channel:event   }
  pw:channel:event } +7ms
  pw:api => command.<anonymous> started +0ms
  pw:channel:command {
  pw:channel:command   id: 1,
  pw:channel:command   guid: 'browser-type@af592df61fa46e66e2030cf12eac132d',
  pw:channel:command   method: 'launch',
  pw:channel:command   params: { ignoreAllDefaultArgs: false, headless: false }
  pw:channel:command } +0ms
  pw:channel:response {
  pw:channel:response   id: 1,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: 'Timeout 30000ms exceeded.',
  pw:channel:response       stack: 'TimeoutError: Timeout 30000ms exceeded.\n' +
  pw:channel:response         '    at ProgressController.run (E:\\somesh\\code\\py\\venv\\Lib\\site-packages\\playwright\\driver\\package\\lib\\server\\progress.js:96:26)\n' +
  pw:channel:response         '    at Firefox.launch (E:\\somesh\\code\\py\\venv\\Lib\\site-packages\\playwright\\driver\\package\\lib\\server\\browserType.js:79:38)\n' +
  pw:channel:response         '    at BrowserTypeDispatcher.launch (E:\\somesh\\code\\py\\venv\\Lib\\site-packages\\playwright\\driver\\package\\lib\\dispatchers\\browserTypeDispatcher.js:49:40)\n' +
  pw:channel:response         '    at DispatcherConnection.dispatch (E:\\somesh\\code\\py\\venv\\Lib\\site-packages\\playwright\\driver\\package\\lib\\dispatchers\\dispatcher.js:352:46)',
  pw:channel:response       name: 'TimeoutError'
  pw:channel:response     }
  pw:channel:response   }
  pw:channel:response } +0ms
  pw:api <= command.<anonymous> failed +57s
command.<anonymous>: Timeout 30000ms exceeded.
    at Command.listener [as _actionHandler] (E:\somesh\code\py\venv\Lib\site-packages\playwright\driver\package\node_modules\commander\lib\command.js:488:17) {
  name: 'TimeoutError'
}
```

**Comment by some-sh** [comment]
I was able to open the browser with python script in my WSL environment, but for some reason, the letter 'w' was entered repeatedly onto the chrome URL bar.

**Comment by aslushnikov** [comment]
@some-sh it looks like some enterprise policy is messing up with the browsers. Please reach out to your company system administrators! 

I'll close this since it's unlikely we can do anything about this.
