### ISSUE TITLE
[BUG] `expect(await page.screenshot()).toMatchSnapshot();` not working, `Error: Unrecognized extension: application/octet-string`

### ISSUE THREAD

**Issue by trusktr** [microsoft/playwright#13414]
**Context:**
- Playwright Version:  `playwright@1.20.2`, `@playwright
- Operating System: Windows
- Node.js version: 17.1.0
- Browser: Chromium
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
expect(await page.screenshot()).toMatchSnapshot('autoscale-canvas-panned')
```

**Describe the bug**

```
Error in reporter Error: Unrecognized extension: application/octet-string
    at typeToExtension (C:\Users\jopea\src\nasa+openmct\node_modules\allure-js-commons\src\writers\utils.ts:33:9)
    at buildAttachmentFileName (C:\Users\jopea\src\nasa+openmct\node_modules\allure-js-commons\src\AllureRuntime.ts:12:36)
    at AllureRuntime.writeAttachmentFromPath (C:\Users\jopea\src\nasa+openmct\node_modules\allure-js-commons\src\AllureRuntime.ts:54:22)
    at processSuite (C:\Users\jopea\src\nasa+openmct\node_modules\allure-playwright\src\index.ts:117:34)
    at processSuite (C:\Users\jopea\src\nasa+openmct\node_modules\allure-playwright\src\index.ts:143:9)
    at processSuite (C:\Users\jopea\src\nasa+openmct\node_modules\allure-playwright\src\index.ts:143:9)
    at AllureReporter.onEnd (C:\Users\jopea\src\nasa+openmct\node_modules\allure-playwright\src\index.ts:147:5)
    at C:\Users\jopea\src\nasa+openmct\node_modules\@playwright\test\lib\reporters\multiplexer.js:77:115
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Multiplexer.onEnd (C:\Users\jopea\src\nasa+openmct\node_modules\@playwright\test\lib\reporters\multiplexer.js:74:45)
    at Runner.runAllTests (C:\Users\jopea\src\nasa+openmct\node_modules\@playwright\test\lib\runner.js:194:5)
    at runTests (C:\Users\jopea\src\nasa+openmct\node_modules\@playwright\test\lib\cli.js:175:18)
    at Command.<anonymous> (C:\Users\jopea\src\nasa+openmct\node_modules\@playwright\test\lib\cli.js:74:7)
```

**Reproduction:**

```sh
git clone https://github.com/nasa/openmct
cd openmct
git checkout fix-autoscle-turned-off
npm install
npm start
```
Open `e2e/tests/plugins/plot/autoscale.e2e.spec.js` and uncomment these lines:

```js
        // TODO, snapshot testing not working, https://github.com/microsoft/playwright/issues/13414
        // await Promise.all([
        //     testTicks(page, ['-10', '-5', '0', '5', '10']),
        //     page.screenshot().then((shot) => expect(shot).toMatchSnapshot('autoscale-canvas-prepan'))
        // ]);
```
Then
```sh
npm run test:e2e:local # first run creates snapshots as expected
npm run test:e2e:local # second run fails with the above error
```

**Comment by trusktr** [comment]
I added a reproduction to the OP

**Comment by ltsuda** [comment]
I think this might be a bug with [allure-reporter](https://github.com/allure-framework/allure-js) when there is **no** file extension on the screenshot. I think the `toMatchSnapshot()` expects the name and extension, at least the examples have that.

Disabling the reporter, the test results generates two files without extension, one is the expected from the first run and one is the received which is the second run.

And, with the reporter enabled and with the `.png` extension, the test run works (test fails because of different image results), and generates three images. The expected, the received and the diff one.


There's a similar closed [issue](https://github.com/allure-framework/allure-js/issues/354) in the reporter's repo but the issuer closed without waiting for response.

**Comment by trusktr** [comment]
Thanks! Adding the extension indeed does the trick. Now I need to figure why the difference happens. Is there noise in the screenshot mechanism?
