### ISSUE TITLE
[BUG] [main branch] Firefox tab crash with "playwright._impl._api_types.Error: Target crashed" for some websites

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright#13507]
This issue is a follow-up for https://github.com/microsoft/playwright-python/issues/1242#issuecomment-1097035872 where I've showed a reproducible code sample.

Also, see the https://github.com/microsoft/playwright-python/pull/1249 that tried to address the problem of crashing.

**Comment by AIGeneratedUsername** [comment]
I've wrote here https://github.com/microsoft/playwright-python/issues/1242#issuecomment-1093871004 that I often see the following error in terminal. The error traceback does not point to my code. 
```
Traceback (most recent call last):
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 288, in dispatch
    object._channel.emit(method, self._replace_guids_with_channels(params))
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 113, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 96, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 42, in _emit_run
    self.emit('error', exc)
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/pyee/_asyncio.py", line 40, in _emit_run
    coro = f(*args, **kwargs)
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 186, in <lambda>
    lambda params: self._on_frame_detached(from_channel(params["frame"])),
  File "/home/sam/.cache/pypoetry/virtualenvs/stressor-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 234, in _on_frame_detached
    self._frames.remove(frame)
ValueError: list.remove(x): x not in list
```

### Questions: Is this error related to this issue and will be fixed here or I need to open a separate issue in https://github.com/microsoft/playwright-python?

The most obvious workaround is to suppress the error:
```python
    def _on_frame_detached(self, frame: Frame) -> None:
        with suppress(ValueError):
            self._frames.remove(frame)
```

**Comment by aslushnikov** [comment]
@AIGeneratedUsername file a separate one in playwright-python!

**Comment by aslushnikov** [comment]
I can repro, though it's unclear what's going on. Even debug build doesn't yield much data.

I do see lots of "untracked docshells" in our instrumentation, so something is fishy. This all code is subject to be rewritten with fission refactoring, so I'll postpone further research after the refactoring is landed.
