### ISSUE TITLE
[Question] UnhandledPromiseRejectionWarning exception while Creating test() block inside a callback function

### ISSUE THREAD

**Issue by trainer1234** [microsoft/playwright#13596]
Context:
Playwright Version: 1.21.0
Operating System: Windows 10
Node.js version: 12.16.3]

Hi everyone,

I'm currently stuck while trying to create a set of dynamic test cases from a CSV file.
Below is my package.json
```json
{
  "name": "ebay",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.21.0",
    "csv": "^6.0.5",
    "csv-parse": "^5.0.4",
    "csv-parser": "^3.0.0",
    "csvtojson": "^2.0.10"
  },
  "dependencies": {}
}
```
Below is my code:

```typescript
import fs from 'fs';
import path from 'path';
import { expect, test } from '@playwright/test';
import { parse } from 'csv-parse';

type MangaInfo = {
    test_case: string,
    manga_name: string
};

let records: MangaInfo[] = [];

test.use({
    baseURL: 'https://myanimelist.net/',
})

async function readCSVTestData() {
    const fileContent = fs.readFileSync(path.join(__dirname, 'input.csv'));
    const mangaInfos = await new Promise<MangaInfo[]>((resolve, reject) => {
        parse(fileContent,
            {
                columns: true,
                skipEmptyLines: true,
                delimiter: ','
            },
            (err, result: MangaInfo[]) => {
                if (err) {
                    console.error(err);
                    reject(err);
                }
                // console.log(result);
                resolve(result);
            });
    });
    return mangaInfos;
}

test.beforeEach(async ({ page }) => {
    await page.goto('/');
});

test.describe('Manga Search', async () => {
    records = await readCSVTestData(); // wait until all of the csv data is read
    console.log('Records: ', records);   // The CSV data are logged
    records.forEach(record => {
        console.log(record); // The first CSV data is logged
        // Then it breaks at the test() block
        test(`search for manga: ${record.test_case} `, async ({ page }) => {
            await page.locator('#topSearchText').fill(record.manga_name);
            await page.keyboard.press('Enter');
            const firstMangaElement = await page.locator('[id*=revAreaMangaHover]').first();
            await expect(firstMangaElement.innerText).toContain(`${record.manga_name}`);
            await firstMangaElement.click();
            console.log(record.test_case, record.manga_name);
        });
    })
});
```

In summary, The CSV test data can be read successfully. However, in the next step, when I create a test() block based on the information from the CSV file, the following exception is returned:

```UnhandledPromiseRejectionWarning: Error: tests\data_driven\manga-search.spec.ts:67:9: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependenices in your package.json depends on @playwright/test.
    at errorWithLocation (D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\lib\util.js:222:10)      
    at TestTypeImpl._ensureCurrentSuite (D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\lib\testType.js:79:41)
    at TestTypeImpl._createTest (D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\lib\testType.js:88:24)
    at D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\lib\transform.js:290:12
    at D:\research\automation\playwright\typescript\official_docs\ebay\tests\data_driven\manga-search.spec.ts:67:9
    at Array.forEach (<anonymous>)
    at D:\research\automation\playwright\typescript\official_docs\ebay\tests\data_driven\manga-search.spec.ts:65:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function 
without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)       
(node:19056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not sure if we could define a new test() block inside a callback function from an async test.describe. 

I have also tried to remove the async from the test.describe function, then called the readCSVTestData in a test.beforeAll hook.

```typescript
let records: MangaInfo[] = [];

test.beforeAll(async () => {
    records = await readCSVTestData();
});

test.beforeEach(async ({ page }) => {
    await page.goto('/');
});

test.describe('Manga Search', () => {
    console.log('Records 1: ', records);   
    records.forEach(record => {
        console.log(record);
        test(`search for manga: ${record.test_case} `, async ({ page }) => {
            await page.locator('#topSearchText').fill(record.manga_name);
            await page.keyboard.press('Enter');
            const firstMangaElement = await page.locator('[id*=revAreaMangaHover]').first();
            await expect(firstMangaElement.innerText).toContain(`${record.manga_name}`);
            await firstMangaElement.click();
            console.log(record.test_case, record.manga_name, record.some_other_value);
        });
    })
});
```
For the above code, the exception does not happen but the "records" variable's value inside the test.describe function is an empty array []. It seems that Playwright has to detect if there are test cases inside the file first before executing the beforeAll hook. So when we put the function inside the beforeAll hook, it will not be run - because we haven't read the file yet.

I'm quite new to Playwright and Typescript btw. Could anybody give me some idea to deal with this? Thanks.

**Comment by aslushnikov** [comment]
@trainer1234 the important rule: tests have to be defined synchronously. So your first solution doesn't work as it relies on async CSV parsing, and second tries to declare new tests while the test run already started.

So you can just use the sync version of the `csv-parse` module, and it should work:

```js
import fs from 'fs';
import path from 'path';
import { expect, test } from '@playwright/test';
import { parse } from 'csv-parse/sync';

test.use({
    baseURL: 'https://myanimelist.net/',
})

function readCSVTestData() {
    const fileContent = fs.readFileSync(path.join(__dirname, 'input.csv'));
    return parse(fileContent,
            {
                columns: true,
                skipEmptyLines: true,
                delimiter: ','
            },
    });
}

test.beforeEach(async ({ page }) => {
    await page.goto('/');
});

test.describe('Manga Search', async () => {
    const records = readCSVTestData(); // wait until all of the csv data is read
    console.log('Records: ', records);   // The CSV data are logged
    records.forEach(record => {
        console.log(record); // The first CSV data is logged
        // Then it breaks at the test() block
        test(`search for manga: ${record.test_case} `, async ({ page }) => {
            await page.locator('#topSearchText').fill(record.manga_name);
            await page.keyboard.press('Enter');
            const firstMangaElement = await page.locator('[id*=revAreaMangaHover]').first();
            await expect(firstMangaElement.innerText).toContain(`${record.manga_name}`);
            await firstMangaElement.click();
            console.log(record.test_case, record.manga_name);
        });
    })
});
```

**Comment by trainer1234** [comment]
Thanks for the explanation @aslushnikov , I have tried to use the sync version of csv-parse module.
However, when I ran it, I got the following result:

```
Running 0 test using 0 worker


Error: Cannot find module 'csv-parse/sync'
Require stack:
- D:\research\automation\playwright\typescript\official_docs\ebay\tests\data_driven\manga-search.spec.ts
- D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\lib\loader.js
- D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\lib\runner.js
- D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\lib\cli.js
- D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\node_modules\playwright-core\lib\cli\cli.js
- D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\node_modules\playwright-core\cli.js
- D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\@playwright\test\cli.js

   at data_driven\manga-search.spec.ts:5

  3 | import { expect, test } from '@playwright/test';
  4 | // import csvParser from 'csv-parser';
> 5 | import { parse } from 'csv-parse/sync';
    | ^
  6 |
  7 |
  8 |

    at Object.<anonymous> (D:\research\automation\playwright\typescript\official_docs\ebay\tests\data_driven\manga-search.spec.ts:5:1)
    at Module._compile (D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\pirates\lib\index.js:136:24)
    at Object.newLoader (D:\research\automation\playwright\typescript\official_docs\ebay\node_modules\pirates\lib\index.js:141:7)

```

I had installed the csv-parse and csv module before

I'm not sure what is the problem here. Maybe it's an issue from csv-parse module's side.

**Comment by aslushnikov** [comment]
@trainer1234 The following worked for me (check out the `.mjs` extension on the file)

```js
// a.spec.mjs
import { test, expect } from '@playwright/test';
import { parse } from 'csv-parse/sync';

test('should work', async ({ }) => {
  console.log('!!!');
});
```
