### ISSUE TITLE
[BUG]  see stack trace

### ISSUE THREAD

**Issue by ravi005e** [microsoft/playwright#13599]
**Context:**
- Playwright Version: [latest]
- Operating System: [Windows]
- java version: [11]
- Browser: [Chromium, chrome]

```
[INFO ] 2022-04-17 19:17:07.551 [main] WebBaseTest - setting up browser context
[INFO ] 2022-04-17 19:17:07.679 [main] WebBaseTest - base url: https://www.google.com
[INFO ] 2022-04-17 19:17:07.680 [main] WebBaseTest - navigating to site: https://www.google.com/
[ERROR] 2022-04-17 19:17:09.374 [main] ScreenshotRule - ***** Error googleCheeseExample test has failed *****
Apr 17, 2022 7:17:09 PM org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor lambda$invokeTestWatchers$3
WARNING: Failed to invoke TestWatcher [to.playwright.utils.junit.rules.ScreenshotRule] for method [to.playwright.tests.BasicTestIT#googleCheeseExample()] with display name [googleCheeseExample()]
com.microsoft.playwright.PlaywrightException: Error {
  message='Target page, context or browser has been closed
  name='Error
  stack='Error: Target page, context or browser has been closed
    at DispatcherConnection.dispatch (C:\Users\AppData\Local\Temp\playwright-java-13065673558761624709\package\lib\server\dispatchers\dispatcher.js:248:49)
    at PipeTransport.transport.onmessage (C:\Users\AppData\Local\Temp\playwright-java-13065673558761624709\package\lib\cli\driver.js:61:57)
    at Immediate._onImmediate (C:\Users\AppData\Local\Temp\playwright-java-13065673558761624709\package\lib\protocol\transport.js:89:34)
    at processImmediate (node:internal/timers:464:21)
}
        at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:105)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
        at com.microsoft.playwright.impl.PageImpl.screenshotImpl(PageImpl.java:1049)
        at com.microsoft.playwright.impl.PageImpl.lambda$screenshot$49(PageImpl.java:988)
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
        at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
        at com.microsoft.playwright.impl.PageImpl.screenshot(PageImpl.java:988)
        at com.microsoft.playwright.Page.screenshot(Page.java:5062)
        at to.playwright.utils.junit.rules.ScreenshotRule.captureScreenshot(ScreenshotRule.java:63)
        at to.playwright.utils.junit.rules.ScreenshotRule.testFailed(ScreenshotRule.java:50)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$nodeFinished$15(TestMethodTestDescriptor.java:303)
        at org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor.lambda$invokeTestWatchers$3(MethodBasedTestDescriptor.java:134)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.jupiter.engine.descriptor.MethodBasedTestDescriptor.invokeTestWatchers(MethodBasedTestDescriptor.java:132)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.nodeFinished(TestMethodTestDescriptor.java:294)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.nodeFinished(TestMethodTestDescriptor.java:66)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.reportCompletion(NodeTestTask.java:188)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35) 
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:186)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
        at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:87)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1144)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Target page, context or browser has been closed
  name='Error
  stack='Error: Target page, context or browser has been closed
    at DispatcherConnection.dispatch (C:\Users\AppData\Local\Temp\playwright-java-13065673558761624709\package\lib\server\dispatchers\dispatcher.js:248:49)
    at PipeTransport.transport.onmessage (C:\Users\AppData\Local\Temp\playwright-java-13065673558761624709\package\lib\cli\driver.js:61:57)
    at Immediate._onImmediate (C:\Users\AppData\Local\Temp\playwright-java-13065673558761624709\package\lib\protocol\transport.js:89:34)
    at processImmediate (node:internal/timers:464:21)
}
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:183)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:163)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
        ... 81 more

```
```java
complete junit rule
package to.playwright.utils.junit.rules;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.Path;

import java.time.Instant;
import java.util.regex.Pattern;

import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.TestWatcher;
import to.playwright.WebBaseTest;


public class ScreenshotRule implements TestWatcher  {

    private static String fileSeperator = System.getProperty("file.separator");
    private static final String BUILD_DIRECTORY = System.getProperty("buildDirectory", "target");
    private static final String DIRECTORY = BUILD_DIRECTORY + fileSeperator + "screenshots";
    private static final Pattern PATTERN_ILLEGAL_SCREENSHOT_CHARS = Pattern.compile("[^\\w#]+");
    private static final int MAX_FILE_NAME_LENGTH = 240;
    private static Playwright playwright;

    protected Logger getLogger() {
        return LogManager.getLogger(getClass());
    }

    @Override
    public void testFailed(ExtensionContext extensionContext, Throwable throwable) {
        String testMethodName = extensionContext.getTestMethod().toString().trim();
        String[] tokens = testMethodName.split("\\(")[0].split("\\.");
        String token = tokens[tokens.length-1];

        getLogger().error("***** Error " + token + " test has failed *****");

        String testClassName = extensionContext.getTestClass().toString().trim();
        String[] bits = testClassName.split("\\.");
        String lastOne = bits[bits.length-1].replaceAll("]", "");

        Instant instant = Instant.now();
        String screenShotName = truncateLongName(sanitizeTestName(token +"_"+ instant.toString())) + ".png";
        try {
            captureScreenshot(WebBaseTest.getPage(), screenShotName, lastOne);
    } catch (IOException e) {
      System.out.println("An exception occurred while building image path " + e.getCause());
        }
    }

    private void captureScreenshot(Page page, String filename, String method) {
        Path path = Paths.get(DIRECTORY, "results" + fileSeperator + method, filename);

        if (path == null) {
          getLogger().warn("Test failed but there is no screenshot to save");
          return;
        }
        byte[] screenshot = page.screenshot();
        try {
          Files.write(path, screenshot);
          getLogger().info("Screenshot can be found : " + path);
        } catch (IOException e) {
          getLogger().warn("Can't save screenshot", e.getStackTrace());
        }
    }

    protected static int calculateMaxNameLength(String filename) {
        int maxNameLength = MAX_FILE_NAME_LENGTH - filename.length();
        maxNameLength -= fileSeperator.length();
        maxNameLength -= DIRECTORY.length();
        if (maxNameLength < 0)
            maxNameLength = 0;
        return maxNameLength;
    }

    protected static String truncateLongName(String name) {
        int maxNameLength = calculateMaxNameLength(name);
        if (name.length() > maxNameLength) return name.substring(0, maxNameLength);
        else return name;
    }

    protected static String sanitizeTestName(String rawTestName) {
        return PATTERN_ILLEGAL_SCREENSHOT_CHARS.matcher(rawTestName).replaceAll("_");
    }

}
```

**Comment by aslushnikov** [comment]
Not sure what's going on here. Please re-file with a proper description and why you think we can help you!
