### ISSUE TITLE
[BUG] page.goto: Navigation failed because page crashed!

### ISSUE THREAD

**Issue by kfwebdev** [microsoft/playwright#13598]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Linux Ubuntu 20.04
- Node.js version: 16.13.2
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://www.rtings.com/search?q=sony%20mdrzx110ap%20b')
  
  const results = [];
  const items = await page.locator('.searchbar_results-result .searchbar_results-name');
  for (let i = 0; i < await results.count(); ++i) {
    const item = await results.nth(i);
    results.push({
      title: await item.textContent(),
      url: 'https://www.rtings.com'+ await item.getAttribute('href'),
    });
  }
console.log('results',results);
})();
```

**Describe the bug**

* Making 3 async Playwright calls to get `textContent` from reviews websites.
* The `page.goto` for rtings.com crashes.
* The same code doesn't crash on Windows 10 localhost.

Can anyone share what the `[0418/002018.535727:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory` errors are or how to resolve them?

Would this be avoided by disabling GPU use or calling 1 Playwright instance at a time? 

*Dockerfile* used to deploy the ExpressJS server and install Playwright.

```
FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=America/Los_Angeles
ARG DOCKER_IMAGE_NAME_TEMPLATE="mcr.microsoft.com/playwright:v%version%-focal"

# === INSTALL Node.js ===

RUN apt-get update && \
    # Install node16
    apt-get install -y curl wget && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs && \
    # Feature-parity with node.js base images.
    apt-get install -y --no-install-recommends git openssh-client && \
    npm install -g yarn && \
    # clean apt cache
    rm -rf /var/lib/apt/lists/* && \
    # Create the pwuser
    adduser pwuser

# === BAKE BROWSERS INTO IMAGE ===

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright DEBUG=*browser*

RUN mkdir /ms-playwright && \
    npx playwright install --with-deps && \
    chmod -R 777 /ms-playwright

ARG PORT RAILWAY_STATIC_URL
WORKDIR /app

ENV PORT=$PORT

WORKDIR /app

COPY . .

RUN npm install

COPY . ./app

RUN npm run build

CMD npm run start
```

```
2022-04-18T00:20:18.186Z pw:browser <launching> /ms-playwright/chromium-1000/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-ecPbyU --remote-debugging-pipe --no-startup-window
2022-04-18T00:20:18.198Z pw:browser <launched> pid=842
2022-04-18T00:20:18.202Z pw:browser <launching> /ms-playwright/chromium-1000/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-4IlB5Q --remote-debugging-pipe --no-startup-window
2022-04-18T00:20:18.212Z pw:browser <launched> pid=843
2022-04-18T00:20:18.213Z pw:browser <launching> /ms-playwright/chromium-1000/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-n5q4LS --remote-debugging-pipe --no-startup-window
2022-04-18T00:20:18.221Z pw:browser <launched> pid=844
2022-04-18T00:20:18.537Z pw:browser [pid=843][err] [0418/002018.535727:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:18.537Z pw:browser [pid=843][err] [0418/002018.536209:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:18.537Z pw:browser [pid=844][err] [0418/002018.535714:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:18.538Z pw:browser [pid=844][err] [0418/002018.536251:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:18.538Z pw:browser [pid=842][err] [0418/002018.535733:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:18.538Z pw:browser [pid=842][err] [0418/002018.536267:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:18.550Z pw:browser [pid=842][err] [0418/002018.550623:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
2022-04-18T00:20:18.551Z pw:browser [pid=843][err] [0418/002018.550619:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
2022-04-18T00:20:18.551Z pw:browser [pid=844][err] [0418/002018.550631:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
2022-04-18T00:20:18.596Z pw:browser [pid=844][err] [0418/002018.595876:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
2022-04-18T00:20:18.596Z pw:browser [pid=842][err] [0418/002018.595872:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
2022-04-18T00:20:18.596Z pw:browser [pid=843][err] [0418/002018.595879:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
2022-04-18T00:20:19.396Z pw:browser [pid=842] <gracefully close start>
2022-04-18T00:20:19.412Z pw:browser [pid=842] <process did exit: exitCode=0, signal=null>
2022-04-18T00:20:19.413Z pw:browser [pid=842] starting temporary directories cleanup
2022-04-18T00:20:19.423Z pw:browser [pid=842] finished temporary directories cleanup
2022-04-18T00:20:19.423Z pw:browser [pid=842] <gracefully close end>
2022-04-18T00:20:19.742Z pw:browser [pid=844][err] [0418/002019.741830:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:19.742Z pw:browser [pid=844][err] [0418/002019.741879:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:19.742Z pw:browser [pid=844][err] [0418/002019.741943:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:19.742Z pw:browser [pid=844][err] [0418/002019.741969:WARNING:property.cc(144)] DaemonVersion: GetAndBlock: failed.
2022-04-18T00:20:19.742Z pw:browser [pid=844][err] [0418/002019.742034:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:19.742Z pw:browser [pid=844][err] [0418/002019.742057:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:21.012Z pw:browser [pid=844] <gracefully close start>
2022-04-18T00:20:21.028Z pw:browser [pid=844] <process did exit: exitCode=0, signal=null>
2022-04-18T00:20:21.028Z pw:browser [pid=844] starting temporary directories cleanup
2022-04-18T00:20:21.033Z pw:browser [pid=844] finished temporary directories cleanup
2022-04-18T00:20:21.033Z pw:browser [pid=844] <gracefully close end>
2022-04-18T00:20:21.851Z pw:browser [pid=843] <gracefully close start>
2022-04-18T00:20:21.884Z pw:browser [pid=843] <process did exit: exitCode=0, signal=null>
2022-04-18T00:20:21.885Z pw:browser [pid=843] starting temporary directories cleanup
2022-04-18T00:20:21.888Z pw:browser [pid=843] finished temporary directories cleanup
2022-04-18T00:20:21.888Z pw:browser [pid=843] <gracefully close end>
2022-04-18T00:20:45.432Z pw:browser <launching> /ms-playwright/chromium-1000/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-eJmP9S --remote-debugging-pipe --no-startup-window
2022-04-18T00:20:45.447Z pw:browser <launched> pid=1302
2022-04-18T00:20:45.449Z pw:browser <launching> /ms-playwright/chromium-1000/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-qaNufT --remote-debugging-pipe --no-startup-window
2022-04-18T00:20:45.463Z pw:browser <launched> pid=1303
2022-04-18T00:20:45.465Z pw:browser <launching> /ms-playwright/chromium-1000/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-tFfTcS --remote-debugging-pipe --no-startup-window
2022-04-18T00:20:45.477Z pw:browser <launched> pid=1304
2022-04-18T00:20:45.727Z pw:browser [pid=1302][err] [0418/002045.726953:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:45.727Z pw:browser [pid=1302][err] [0418/002045.727088:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:45.727Z pw:browser [pid=1304][err] [0418/002045.727209:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:45.727Z pw:browser [pid=1304][err] [0418/002045.727344:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:45.727Z pw:browser [pid=1303][err] [0418/002045.727057:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:45.727Z pw:browser [pid=1303][err] [0418/002045.727376:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2022-04-18T00:20:45.734Z pw:browser [pid=1302][err] [0418/002045.734033:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
2022-04-18T00:20:45.734Z pw:browser [pid=1304][err] [0418/002045.734297:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
2022-04-18T00:20:45.734Z pw:browser [pid=1303][err] [0418/002045.734403:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
2022-04-18T00:20:45.764Z pw:browser [pid=1302][err] [0418/002045.761873:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
2022-04-18T00:20:45.765Z pw:browser [pid=1303][err] [0418/002045.762399:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
2022-04-18T00:20:45.776Z pw:browser [pid=1304][err] [0418/002045.762242:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://www.rtings.com/search?q=sony%20mdrzx110ap%20b", waiting until "load"
============================================================
at captureRtingsResultsMatch (/app/.keystone/admin/.next/server/pages/api/__keystone_api_build.js:418:16)
at async findProductReviews (/app/.keystone/admin/.next/server/pages/api/__keystone_api_build.js:437:12)
at async getReviews (/app/.keystone/admin/.next/server/pages/api/__keystone_api_build.js:471:18)
2022-04-18T00:20:46.745Z pw:browser [pid=1302] <kill>
2022-04-18T00:20:46.746Z pw:browser [pid=1302] <will force kill>
2022-04-18T00:20:46.746Z pw:browser [pid=1302] starting temporary directories cleanup
2022-04-18T00:20:46.748Z pw:browser [pid=1302] finished temporary directories cleanup
2022-04-18T00:20:46.748Z pw:browser [pid=1303] <kill>
2022-04-18T00:20:46.748Z pw:browser [pid=1303] <will force kill>
2022-04-18T00:20:46.749Z pw:browser [pid=1303] starting temporary directories cleanup
2022-04-18T00:20:46.750Z pw:browser [pid=1303] finished temporary directories cleanup
2022-04-18T00:20:46.750Z pw:browser [pid=1304] <kill>
2022-04-18T00:20:46.750Z pw:browser [pid=1304] <will force kill>
2022-04-18T00:20:46.751Z pw:browser [pid=1304] starting temporary directories cleanup
2022-04-18T00:20:46.751Z pw:browser [pid=1304] finished temporary directories cleanup
```

**Comment by aslushnikov** [comment]
> Would this be avoided by disabling GPU use or calling 1 Playwright instance at a time?

It should be! Overall, pages crash when there's not enough resources. The best way is to limit resource consumption, so:
- don't run browsers in parallel unless you have plenty of ram
