### ISSUE TITLE
[BUG] Webkit: EGLDisplay Initialization failed: EGL_NOT_INITIALIZED

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#1363]
**Context:**
- Playwright Version: 0.11.1-next.1583993157193
- Operating System: https://github.com/arjun27/playwright-github-actions/blob/84d293f9d7342e1e91a22b67f227923fb436b6b1/Dockerfile
- Extra: (on Heroku via Docker)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const playwright = require("playwright")
(async () => {
  const browser = await playwright.webkit.launch({ });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('http://whatsmyuseragent.org/'); // <-- blocks and error appears here
  await page.screenshot({ path: `example.png` });
  await browser.close();
})();
```

**Describe the bug**

```
2020-03-12T19:30:49.989517+00:00 app[web.1]: EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
2020-03-12T19:30:49.990948+00:00 app[web.1]: 
2020-03-12T19:30:49.990950+00:00 app[web.1]: ** (WPEWebProcess:1880): WARNING **: 19:30:49.990: Error loading the injected bundle (/usr/local/lib/wpe-webkit-1.0/injected-bundle/libWPEInjectedBundle.so): /usr/local/lib/wpe-webkit-1.0/injected-bundle/libWPEInjectedBundle.so: cannot open shared object file: No such file or directory
2020-03-12T19:30:50.561440+00:00 app[web.1]: Fontconfig error: Cannot load default config file
2020-03-12T19:30:50.653410+00:00 app[web.1]: GLib-GIO-Message: 19:30:50.653: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

Maybe related (came up too sometimes)

```
 1   0x7fa07951c299 WTFCrash
 2   0x7fa079545cc5 WTF::Thread::create(char const*, WTF::Function<void ()>&&, WTF::ThreadType)
 3   0x7fa076c2535c WebKit::MemoryPressureMonitor::start()
 4   0x7fa076b16b46 WebKit::WebProcessPool::WebProcessPool(API::ProcessPoolConfiguration&)
 5   0x7fa076b16da7 WebKit::WebProcessPool::create(API::ProcessPoolConfiguration&)
 6   0x7fa076ba50f9 /backend/node_modules/playwright/.local-webkit/linux-1179/minibrowser-wpe/libWPEWebKit-1.0.so.3(+0x234e0f9) [0x7fa076ba50f9]
 7   0x7fa072e5b6d0 /backend/node_modules/playwright/.local-webkit/linux-1179/minibrowser-wpe/libgobject-2.0.so.0(+0x156d0) [0x7fa072e5b6d0]
 8   0x7fa072e5d3c0 g_object_new_valist
 9   0x7fa072e5d739 g_object_new
 10  0x7fa076c22bdd WebKit::InspectorPlaywrightAgentClientGlib::createBrowserContext(WTF::String&)
 11  0x7fa076a98988 WebKit::InspectorPlaywrightAgent::createContext(WTF::String&, WTF::String*)
 12  0x7fa078ccd6ea Inspector::PlaywrightBackendDispatcher::createContext(long, WTF::RefPtr<WTF::JSONImpl::Object, WTF::DumbPtrTraits<WTF::JSONImpl::Object> >&&)
 13  0x7fa078cbe3d7 Inspector::PlaywrightBackendDispatcher::dispatch(long, WTF::String const&, WTF::Ref<WTF::JSONImpl::Object, WTF::DumbPtrTraits<WTF::JSONImpl::Object> >&&)
 14  0x7fa078cfa15b Inspector::BackendDispatcher::dispatch(WTF::String const&, Inspector::BackendDispatcher::Mode, WTF::Function<Inspector::BackendDispatcher::DispatchResult (WTF::RefPtr<WTF::JSONImpl::Object, WTF::DumbPtrTraits<WTF::JSONImpl::Object> > const&)>&&)
 15  0x7fa076a841d2 WebKit::BrowserInspectorController::dispatchMessageFromFrontend(WTF::String const&)
 16  0x7fa0795430c5 WTF::RunLoop::performWork()
 17  0x7fa0795b1d69 /backend/node_modules/playwright/.local-webkit/linux-1179/minibrowser-wpe/libWPEWebKit-1.0.so.3(+0x4d5ad69) [0x7fa0795b1d69]
 18  0x7fa072b779e5 g_main_context_dispatch
 19  0x7fa072b77db0 /backend/node_modules/playwright/.local-webkit/linux-1179/minibrowser-wpe/libglib-2.0.so.0(+0x4ddb0) [0x7fa072b77db0]
 20  0x7fa072b780c2 g_main_loop_run
 21  0x556164bb3ed2 /backend/node_modules/playwright/.local-webkit/linux-1179/minibrowser-wpe/MiniBrowser(+0x6ed2) [0x556164bb3ed2]
 22  0x7fa072093b97 __libc_start_main
 23  0x556164bb436a /backend/node_modules/playwright/.local-webkit/linux-1179/minibrowser-wpe/MiniBrowser(+0x736a) [0x556164bb436a]
 /backend/node_modules/playwright/.local-webkit/linux-1179/pw_run.sh: line 19:  1649 Segmentation fault      GIO_MODULE_DIR="$GIO_DIR" LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LD_PATH" "$MINIBROWSER" "$@"
 Errored request Error: Protocol error (Playwright.createContext): Browser has been closed.
     at /backend/node_modules/playwright-core/lib/webkit/wkConnection.js:99:63
     at new Promise (<anonymous>)
     at WKSession.send (/backend/node_modules/playwright-core/lib/webkit/wkConnection.js:98:16)
     at WKBrowser.newContext (/backend/node_modules/playwright-core/lib/webkit/wkBrowser.js:61:65)
     at WKBrowser.<anonymous> (/backend/node_modules/playwright-core/lib/helper.js:84:31)
     at Object.base.apply (/backend/node_modules/vm2/lib/contextify.js:525:32)
     at vm.js:7:35 {
   message: 'Protocol error (Playwright.createContext): Browser has been closed.'
 }
 Browser was closed because it was not closed in the VM
```

**Comment by mxschmitt** [comment]
See comment here for more information: https://github.com/microsoft/playwright/issues/1364#issuecomment-598496754
