### ISSUE TITLE
[BUG] Firefox: Failed to launch browser!

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#1364]
**Context:**
- Playwright Version: 0.11.1-next.1583993157193
- Operating System: https://github.com/arjun27/playwright-github-actions/blob/84d293f9d7342e1e91a22b67f227923fb436b6b1/Dockerfile
- Extra: (on Heroku via Docker)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
(async () => {
  const browser = await playwright.firefox.launch(); // <-- blocks and errors here
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  await page.screenshot({ path: `example.png` });
  await browser.close();
})();
```

**Describe the bug**

```
Errored request Error: Failed to launch browser!
1584042035124	addons.webextension.doh-rollout@mozilla.org	WARN	Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1584042035677	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1584042035677	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1584042035677	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1584042035677	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
[GFX1-]: Compositor thread not started (true)


TROUBLESHOOTING: https://github.com/Microsoft/playwright/blob/master/docs/troubleshooting.md

    at onClose (/backend/node_modules/playwright-core/lib/server/processLauncher.js:139:20)
    at Interface.<anonymous> (/backend/node_modules/playwright-core/lib/server/processLauncher.js:132:65)
    at Interface.emit (events.js:228:7)
    at Interface.EventEmitter.emit (domain.js:498:23)
    at Interface.close (readline.js:402:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:228:7)
    at Socket.EventEmitter.emit (domain.js:498:23)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

It could be that this and #1363 appears because of limited resources on the host system.

**Comment by mxschmitt** [comment]
Yep, as I though its kinda a resource issue on Heroku. I've moved my setup from https://try.playwright.tech to another hosting provider, now with dedicated cores and it works fine.

Feel free to close it (this one too: #1363), but maybe it should be handled in a better way that the user knows what the issue is. CPU power / RAM / ulimit / whatever

**Comment by aslushnikov** [comment]
>  but maybe it should be handled in a better way that the user knows what the issue is. CPU power / RAM / ulimit / whatever

These we can't guess, unfortunately. There are thousands reasons why browsers might not start in some environments.

Thanks!
