### ISSUE TITLE
[Question] _createHandle

### ISSUE THREAD

**Issue by lupinhex** [microsoft/playwright#1365]
I keep getting this error and getting many timeouts using the screenshot snippet with a list of 20 websites. But just page.goto no screenshot is used. I can browse the whole list by hand with no issues. Any idea of why? @aslushnikov

```js
node:15825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_createHandle' of undefined
    at _page._addConsoleMessage.args.map.arg (/home/lupin/playwright/lib/firefox/ffPage.js:166:69)
    at Array.map (<anonymous>)
    at FFPage._onConsole (/home/lupin/playwright/lib/firefox/ffPage.js:166:50)
    at FFSession.emit (events.js:189:13)
    at Promise.resolve.then (/home/lupin/playwright/lib/firefox/ffConnection.js:145:47)
(node:15825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

```
After some, the for loop start failing with all websites:

```js
(node:15825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'childFrames' of undefined
    at FrameManager.frameCommittedNewDocumentNavigation (/home/lupin/playwright/lib/frames.js:108:35)
    at FFPage._onNavigationCommitted (/home/lupin/playwright/lib/firefox/ffPage.js:140:34)
    at FFSession.emit (events.js:189:13)
    at Promise.resolve.then (/home/lupin/playwright/lib/firefox/ffConnection.js:145:47)
(node:15825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:15825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'childFrames' of undefined
    at FrameManager.frameCommittedNewDocumentNavigation (/home/lupin/playwright/lib/frames.js:108:35)
    at FFPage._onNavigationCommitted (/home/lupin/playwright/lib/firefox/ffPage.js:140:34)
    at FFSession.emit (events.js:189:13)
    at Promise.resolve.then (/home/lupin/playwright/lib/firefox/ffConnection.js:145:47)
(node:15825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:15825) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'childFrames' of undefined
    at FrameManager.frameCommittedNewDocumentNavigation (/home/lupin/playwright/lib/frames.js:108:35)
    at FFPage._onNavigationCommitted (/home/lupin/playwright/lib/firefox/ffPage.js:140:34)
    at FFSession.emit (events.js:189:13)
    at Promise.resolve.then (/home/lupin/playwright/lib/firefox/ffConnection.js:145:47)
(node:15825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```
and this is my timeout and idle
```js
    await page.goto(Url ,{waitUntil: 'networkidle0',  timeout: 30000}).catch(e => console.log(e));;
```
Timeout errors are less important but I wonder why I'm getting those because I'm not using much bw or resources in this server. "Navigation timeout of 30000 ms exceeded"

**Comment by mxschmitt** [comment]
I also faced into this issue.

@lupinhex did you run these screenshots in parallel or synchronously?

On my environment I'd multiple Playwright instances running which sometimes lead to this error.

**Comment by lupinhex** [comment]
> I also faced into this issue.
> 
> @lupinhex did you run these screenshots in parallel or synchronously?
> 
Just using 1 browser Mozilla Firefox and this inside a loop 
```js
const webs = fs.readFileSync('mylist.txt');
..
..
(async () => {
..
for (const web of webs) {
await page.goto(Url ,{web: 'networkidle0',  timeout: 30000}).catch(e => console.log(e));;
}
 await browser.close();
})();
```

**Comment by lupinhex** [comment]
Fixed by using a database

**Comment by tudch** [comment]
How is the issue solved by using a database?

I also get the error when using firefox, but with chromium it does not appear.

The methods are also defined differently and chromium checks that there might be no execution context:

```
    async _onConsoleAPI(event) {
        if (event.executionContextId === 0) {
            // DevTools protocol stores the last 1000 console messages. These
            // messages are always reported even for removed execution contexts. In
            // this case, they are marked with executionContextId = 0 and are
            // reported upon enabling Runtime agent.
            //
            // Ignore these messages since:
            // - there's no execution context we can use to operate with message
            //   arguments
            // - these messages are reported before Playwright clients can subscribe
            //   to the 'console'
            //   page event.
            //
            // @see https://github.com/GoogleChrome/puppeteer/issues/3865
            return;
        }
```
