### ISSUE TITLE
[BUG] The "playwright._impl._api_types.Error: NS_ERROR_NET_PARTIAL_TRANSFER" error happens randomly when calling `page.goto(url)` to open a URL

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright#13653]
# Context
- Playwright Version: 1.20
- Operating System: Lubuntu 20.04
- Python 3.10.4
- Browser: Firefox

# Log

Too large for GitHub to copy/paste, so full DEBUG log is attached as a file [NS_ERROR_NET_PARTIAL_TRANSFER.tar.gz](https://github.com/microsoft/playwright/files/8521395/NS_ERROR_NET_PARTIAL_TRANSFER.tar.gz)

Here is only the end of the log:
```
2022-04-20T11:45:21.234Z pw:browser [pid=217717][err] JavaScript error: https://www.citilink.ru/catalog/videokarty--rtx-3070/ line 488 > injectedScript, line 1: ReferenceError: mindbox is not defined
2022-04-20T11:45:22.371Z pw:browser [pid=217717] <process did exit: exitCode=0, signal=null>
2022-04-20T11:45:22.371Z pw:browser [pid=217717] starting temporary directories cleanup
2022-04-20T11:45:23.465Z pw:browser [pid=217717] finished temporary directories cleanup
2022-04-20T11:45:23.465Z pw:browser [pid=217717] <gracefully close end>
Traceback (most recent call last):
  File "/home/juol/PycharmProjects/client/_local.py", line 47, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/juol/PycharmProjects/client/_local.py", line 25, in main
    await page.goto(url, timeout=120_000)
  File "/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 7581, in goto
    await self._async(
  File "/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/juol/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: NS_ERROR_NET_PARTIAL_TRANSFER
=========================== logs ===========================
navigating to "https://www.citilink.ru/catalog/videokarty--rtx-3070", waiting until "load"
============================================================

Process finished with exit code 1

```

# Steps to reproduce
The error happens randomly for random URLs, so there is no specific URL example.
```python
from playwright.async_api import async_playwright

async with async_playwright() as p:
        browser = await p.firefox.launch()
        page = await browser.new_page()
        for url in my_urls_list:
            await page.goto(url)
        await browser.close()
```

# Expected browser behavior

Handle all errors the same as a regular browser do. I do not see that a real Firefox browser crashes so often for just a URL opening.

**Comment by yury-s** [comment]
This seems very similar to https://github.com/microsoft/playwright/issues/13651, we need a repro (with urls) to act on this.
