### ISSUE TITLE
firefox fails when running in docker container

### ISSUE THREAD

**Issue by Nedilko** [microsoft/playwright#13756]
### Discussed in https://github.com/microsoft/playwright/discussions/13716

<div type='discussions-op-text'>

<sup>Originally posted by **Nedilko** April 24, 2022</sup>
I faced with problem when I run screenshot tests with matching snapshot (`.toMatchSnapshot`).
I'm running tests on Apple M1, and screenshots renders under darwin.
Everything okay, second attempt pf running test passes all tests.
BUT!
The problem when after this I run tests in my ci.
Tests not pass because they run under another file system, and screenshots has different name:
- `screenshot_name-browser-linux` - on CI
- `screenshot_name-browser-darwin` - on Apple M1
So, I tried to use this instructions:
```sh
docker run --rm --network host -v $(pwd):/work/ -w /work/ -it mcr.microsoft.com/playwright:v1.21.0-focal /bin/bash
npm install
npx playwright test --update-snapshots
```
But unfortunately firefox tests fails:
(btw, all firefox tests, not only screenshot tests)
```sh
pw:browser <launching> /ms-playwright/firefox-1322/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-rUXIAt -juggler-pipe -silent +0ms
  pw:browser <launched> pid=371 +3ms
  pw:browser [pid=371][err] *** You are running in headless mode. +424ms
  pw:browser [pid=371][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.658892) [GFX1-]: glxtest: libpci missing +228ms
  pw:browser [pid=371][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.658892) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.658951) [GFX1-]: glxtest: Unable to open a connection to the X server +0ms
  pw:browser [pid=371][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.658892) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.658951) |[2][GFX1-]: glxtest: libEGL initialize failed (t=0.658962) [GFX1-]: glxtest: libEGL initialize failed +0ms
  pw:browser [pid=371][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.658892) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.658951) |[2][GFX1-]: glxtest: libEGL initialize failed (t=0.658962) |[3][GFX1-]: No GPUs detected via PCI (t=0.658971) [GFX1-]: No GPUs detected via PCI +0ms
  pw:browser [pid=371][out]  +194ms
  pw:browser [pid=371][out] Juggler listening to the pipe +0ms
  pw:browser [pid=371][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/playwright_firefoxdev_profile-rUXIAt/search.json.mozlz4", (void 0))) +41ms
```</div>

**Comment by aslushnikov** [comment]
Could you try running with xvfb?

```
xvfb-run npx playwright test --update-snapshots
```

**Comment by Nedilko** [comment]
Thanks for the response!
Actually I was watching video where you was showing new features of playwright v1.20 and noticed I have a reply on this issue form you :)

tests just failed again...
output below:
```bash
root@docker-desktop:/work# xvfb-run npx playwright test --update-snapshots

Running 10 tests using 2 workers

  ✓  [chromium] › homepage.test.js:8:3 › main text › heading has text (10s)
  ✘  [firefox] › homepage.test.js:8:3 › main text › heading has text (30s)
  ✓  [chromium] › homepage.test.js:15:3 › screenshot › homepage (868ms)
/work/e2e/homepage.test.js-snapshots/screenshot-homepage-1-chromium-linux.png is missing in snapshots, writing actual.
  ✓  [webkit] › homepage.test.js:8:3 › main text › heading has text (985ms)
  ✓  [webkit] › homepage.test.js:15:3 › screenshot › homepage (2s)
/work/e2e/homepage.test.js-snapshots/screenshot-homepage-1-webkit-linux.png is missing in snapshots, writing actual.
  ✓  [Mobile Chrome] › homepage.test.js:8:3 › main text › heading has text (488ms)
  ✓  [Mobile Chrome] › homepage.test.js:15:3 › screenshot › homepage (840ms)
/work/e2e/homepage.test.js-snapshots/screenshot-homepage-1-Mobile-Chrome-linux.png is missing in snapshots, writing actual.
  ✓  [Mobile Safari] › homepage.test.js:8:3 › main text › heading has text (829ms)
  ✓  [Mobile Safari] › homepage.test.js:15:3 › screenshot › homepage (934ms)
/work/e2e/homepage.test.js-snapshots/screenshot-homepage-1-Mobile-Safari-linux.png is missing in snapshots, writing actual.
  ✘  [firefox] › homepage.test.js:15:3 › screenshot › homepage (30s)


  1) [firefox] › homepage.test.js:8:3 › main text › heading has text ===============================

    Timeout of 30000ms exceeded in beforeEach hook.

      1 | const { test, expect } = require('@playwright/test')
      2 |
    > 3 | test.beforeEach(async ({ page }) => {
        |      ^
      4 |   await page.goto('/')
      5 | })
      6 |

        at /work/e2e/homepage.test.js:3:6

  2) [firefox] › homepage.test.js:15:3 › screenshot › homepage =====================================

    Timeout of 30000ms exceeded in beforeEach hook.

      1 | const { test, expect } = require('@playwright/test')
      2 |
    > 3 | test.beforeEach(async ({ page }) => {
        |      ^
      4 |   await page.goto('/')
      5 | })
      6 |

        at /work/e2e/homepage.test.js:3:6

  Slow test file: [firefox] › homepage.test.js (1m)
  Consider splitting slow test files to speed up parallel execution

  2 failed
    [firefox] › homepage.test.js:8:3 › main text › heading has text ================================
    [firefox] › homepage.test.js:15:3 › screenshot › homepage ======================================
  8 passed (1m)
```

Maybe it's a good idea to create own container with all needs. e.g. based on ubuntu image with installed all libraries, and of course playwright browsers... maybe something wrong with image which is build on Apple M1... I don't know...
I thought it's a good idea to use VSCode remote development in containers, so that I need to configure docker file and after install all need dependencies and that's it... And then I can configure ci to run e2e tests on exactly same system using same container. But I think the idea of image `mcr.microsoft.com/playwright:v1.21.0-focal` was pretty much same.

**Comment by jvsanten** [comment]
I'm running into (what I assume is) this same issue.

I'm using the docker image to run tests on Jenkins. Chrome and Webkit both work, but Firefox always goes to a 30 second timeout. The same issue occurs with or without xvfb-run.

Logs with xvfb-run:
```
xvfb-run --auto-servernum --server-args=-screen 0 1920x1080x24 npx playwright test --project=firefox

Running 1 test using 1 worker
  pw:browser <launching> /ms-playwright/firefox-1322/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-AuJuOz -juggler-pipe -silent +0ms 
  pw:browser <launched> pid=293 +7ms 
  pw:browser [pid=293][err] *** You are running in headless mode. +34ms 
  pw:browser [pid=293][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.0936868) [GFX1-]: glxtest: libpci missing +51ms 
  pw:browser [pid=293][err] Unable to revert mtime: /ms-playwright/firefox-1322/firefox/fonts +65ms 
  pw:browser [pid=293][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +64ms 
  pw:browser [pid=293][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +4ms 
  pw:browser [pid=293][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +0ms 
  pw:browser [pid=293][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +1ms 
  pw:browser [pid=293][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +6ms 
T pw:browser [pid=293] <kill> +30s 
  pw:browser [pid=293] <will force kill> +0ms 
  pw:browser [pid=293] starting temporary directories cleanup +0ms 
  pw:browser [pid=293] finished temporary directories cleanup +2ms 

 Slow test file: [firefox] › dos.spec.ts (30s)
 Consider splitting slow test files to speed up parallel execution
```

Logs without xvfb-run:
```
npx playwright test --project=firefox

Running 1 test using 1 worker
  pw:browser <launching> /ms-playwright/firefox-1322/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-GyjCum -juggler-pipe -silent +0ms 
  pw:browser <launched> pid=279 +8ms 
  pw:browser [pid=279][err] *** You are running in headless mode. +24ms 
  pw:browser [pid=279][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.0687107) [GFX1-]: glxtest: libpci missing +35ms 
  pw:browser [pid=279][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.0687107) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.0687859) [GFX1-]: glxtest: Unable to open a connection to the X server +0ms 
  pw:browser [pid=279][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.0687107) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.0687859) |[2][GFX1-]: glxtest: libEGL initialize failed (t=0.068797) [GFX1-]: glxtest: libEGL initialize failed +0ms 
  pw:browser [pid=279][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.0687107) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.0687859) |[2][GFX1-]: glxtest: libEGL initialize failed (t=0.068797) |[3][GFX1-]: No GPUs detected via PCI (t=0.0688209) [GFX1-]: No GPUs detected via PCI +0ms 
  pw:browser [pid=279][err] Unable to revert mtime: /ms-playwright/firefox-1322/firefox/fonts +29ms 
  pw:browser [pid=279][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +60ms 
  pw:browser [pid=279][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +1ms 
  pw:browser [pid=279][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +2ms 
  pw:browser [pid=279][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +1ms 
  pw:browser [pid=279][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +7ms 
T pw:browser [pid=279] <kill> +30s 
  pw:browser [pid=279] <will force kill> +0ms 
  pw:browser [pid=279] starting temporary directories cleanup +0ms 
  pw:browser [pid=279] finished temporary directories cleanup +2ms 

 Slow test file: [firefox] › dos.spec.ts (30s)
 Consider splitting slow test files to speed up parallel execution
```

(Had some weird formatting from the Jenkins logs so I've tried to clear that up as best I can)

Running with the same settings on my Linux workstation the image performs flawlessly, but it seems something in the docker image is still dependent on the host when it comes to running Firefox.

**Comment by aslushnikov** [comment]
@jvsanten is this Docker Arm64 or x86_64?

**Comment by SwannG** [comment]
I was running the same isssue, the image has been updated 25 minutes ago and that solved my problem !

**Comment by aslushnikov** [comment]
Tentatively merging this to https://github.com/microsoft/playwright/issues/13732

**Comment by jvsanten** [comment]
> @jvsanten is this Docker Arm64 or x86_64? Overall looks like a dupe of #13732 that I'm investigating

@aslushnikov mine is on x86_64 - still shows the same output (and problem) switching to playwright:next-focal as of today

**Comment by aslushnikov** [comment]
@jvsanten I see; docker image for x86_64 works fine for me with Playwright 1.21. I didn't run it through jenkins though and we don't know much about jenkins - so I don't think we can help much here.

**Comment by Irina-Intuiface** [comment]
I have the same problem - Firefox throwing a timeout when running tests on Jenkins (linux), via Docker, with
```
withDockerContainer('mcr.microsoft.com/playwright:v1.22.2-focal') {
              shx 'npx playwright test --list'
              shx 'npx playwright test'
            }
```
- Chromium and Webkit have no problem
- Running the same configuration, using the same Docker image locally on my Windows PC has no problem
```
docker run --rm --network host -v $(pwd):/work/ -w /work/ -it mcr.microsoft.com/playwright:v1.22.2-focal /bin/bash
npx playwright test --list
npx playwright test
```

**Comment by ereat** [comment]
Any Update on this issue?
