### ISSUE TITLE
[BUG] Having expect timeout specified in config file, single soft assertion failure causes all subsequent soft assertions to be failed

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#13782]
**Context:**
- Playwright Version: [1.19,1.21.TOT]
- Operating System: [Mac]
- Node.js version: [18.0]
- Browser: [Chrome]
- Extra: [N/A]

**Code Snippet**

```javascript

const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/',{waitUntil: "networkidle"});
    const title = await page.locator('.navbar__inner .navbar__title');
    await expect.soft(title).toHaveText('Playwright1');
    await expect.soft(title).toHaveText('Playwright2');
    await expect.soft(title).toHaveText('Playwright');
    await expect.soft(title).toHaveText('Playwright3');
    await expect.soft(title).toHaveText('Playwright');
});

```

**Describe the bug**

**Output without expect in playwright.config**
```javascript

  ✘  [demo1] › test/demo/pw_sample.js:5:1 › basic test (18s)

  1) [demo1] › test/demo/pw_sample.js:5:1 › basic test =============================================

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright1"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"

       6 |     await page.goto('https://playwright.dev/',{waitUntil: "networkidle"});
       7 |     const title = await page.locator('.navbar__inner .navbar__title');
    >  8 |     await expect.soft(title).toHaveText('Playwright1');
         |                              ^
       9 |     await expect.soft(title).toHaveText('Playwright2');
      10 |     await expect.soft(title).toHaveText('Playwright');
      11 |     await expect.soft(title).toHaveText('Playwright3');

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:8:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright2"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"

       7 |     const title = await page.locator('.navbar__inner .navbar__title');
       8 |     await expect.soft(title).toHaveText('Playwright1');
    >  9 |     await expect.soft(title).toHaveText('Playwright2');
         |                              ^
      10 |     await expect.soft(title).toHaveText('Playwright');
      11 |     await expect.soft(title).toHaveText('Playwright3');
      12 |     await expect.soft(title).toHaveText('Playwright');

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:9:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright3"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"

       9 |     await expect.soft(title).toHaveText('Playwright2');
      10 |     await expect.soft(title).toHaveText('Playwright');
    > 11 |     await expect.soft(title).toHaveText('Playwright3');
         |                              ^
      12 |     await expect.soft(title).toHaveText('Playwright');
      13 | });

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:11:30

    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/pw_sample.js-basic-test-demo1/test-failed-1.png
    ------------------------------------------------------------------------------------------------

  1 failed
    [demo1] › test/demo/pw_sample.js:5:1 › basic test ==============================================

To open last HTML report run:

  npx playwright show-report

```

**Output with expect: {timeout: 45000} in playwright.config**

```javascript

  ✘  [demo1] › test/demo/pw_sample.js:5:1 › basic test (30s)

  1) [demo1] › test/demo/pw_sample.js:5:1 › basic test =============================================

    Timeout of 30000ms exceeded.

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright1"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 45000ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"


       6 |     await page.goto('https://playwright.dev/',{waitUntil: "networkidle"});
       7 |     const title = await page.locator('.navbar__inner .navbar__title');
    >  8 |     await expect.soft(title).toHaveText('Playwright1');
         |                              ^
       9 |     await expect.soft(title).toHaveText('Playwright2');
      10 |     await expect.soft(title).toHaveText('Playwright');
      11 |     await expect.soft(title).toHaveText('Playwright3');

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:8:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright2"
    Received string: ""
    Call log:
      - expect.toHaveText with timeout 45000ms
      - waiting for selector ".navbar__inner .navbar__title"


       7 |     const title = await page.locator('.navbar__inner .navbar__title');
       8 |     await expect.soft(title).toHaveText('Playwright1');
    >  9 |     await expect.soft(title).toHaveText('Playwright2');
         |                              ^
      10 |     await expect.soft(title).toHaveText('Playwright');
      11 |     await expect.soft(title).toHaveText('Playwright3');
      12 |     await expect.soft(title).toHaveText('Playwright');

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:9:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright"
    Received string: ""
    Call log:
      - expect.toHaveText with timeout 45000ms
      - waiting for selector ".navbar__inner .navbar__title"


       8 |     await expect.soft(title).toHaveText('Playwright1');
       9 |     await expect.soft(title).toHaveText('Playwright2');
    > 10 |     await expect.soft(title).toHaveText('Playwright');
         |                              ^
      11 |     await expect.soft(title).toHaveText('Playwright3');
      12 |     await expect.soft(title).toHaveText('Playwright');
      13 | });

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:10:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright3"
    Received string: ""
    Call log:
      - expect.toHaveText with timeout 45000ms
      - waiting for selector ".navbar__inner .navbar__title"


       9 |     await expect.soft(title).toHaveText('Playwright2');
      10 |     await expect.soft(title).toHaveText('Playwright');
    > 11 |     await expect.soft(title).toHaveText('Playwright3');
         |                              ^
      12 |     await expect.soft(title).toHaveText('Playwright');
      13 | });

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:11:30

    Pending operations:
      - expect.toHaveText at test/demo/pw_sample.js:8:30


    expect.toHaveText: Target page, context or browser has been closed

      10 |     await expect.soft(title).toHaveText('Playwright');
      11 |     await expect.soft(title).toHaveText('Playwright3');
    > 12 |     await expect.soft(title).toHaveText('Playwright');
         |                              ^
      13 | });

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:12:30

    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/pw_sample.js-basic-test-demo1/test-failed-1.png
    ------------------------------------------------------------------------------------------------


  1 failed
    [demo1] › test/demo/pw_sample.js:5:1 › basic test ==============================================

To open last HTML report run:

  npx playwright show-report

``` 

You can see from the test output, if i specify expect timeout in playwright.config file, after the first assertion fails, all the subsequent assertions also fail.

**Expected**
Soft Assertions should not abort the test
```javascript
await expect.soft(title).toHaveText('Playwright1'); - FAIL
await expect.soft(title).toHaveText('Playwright2'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - PASS
await expect.soft(title).toHaveText('Playwright3'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - PASS
```

**Actual**
```javascript
await expect.soft(title).toHaveText('Playwright1'); - FAIL
await expect.soft(title).toHaveText('Playwright2'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - FAIL
await expect.soft(title).toHaveText('Playwright3'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - FAIL
```

**Comment by pavelfeldman** [comment]
This is expected. The way assertions work is that they wait for condition to be met. So the first one (soft or not) will wait for text to be Playwright1. Test times out because it is set to finish within 5 seconds. You can change it to be:

```js
await expect.soft(title).toHaveText('Playwright1', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright2', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright3', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright', { timeout: 250 });
```

to see how it works, but it does not look like a sensible test, just a demonstration.

**Comment by vsravuri** [comment]
@pavelfeldman 
 
I tested your suggestion, the behavior i see with soft assertion is:

**If i override default timeout 5 seconds either globally (playwright.config) or in the expect statement itself, i see this behavior**

```javascript

await expect.soft(title).toHaveText('Playwright1', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright2', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright3', { timeout: 250 });
await expect.soft(title).toHaveText('Playwright', { timeout: 250 });

await expect.soft(title).toHaveText('Playwright1'); - FAIL
await expect.soft(title).toHaveText('Playwright2'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - FAIL
await expect.soft(title).toHaveText('Playwright3'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - FAIL
```

**If i don't overwrite the default timeout of 5 seconds, the test continues**

 ```javascript
await expect.soft(title).toHaveText('Playwright1'); - FAIL
await expect.soft(title).toHaveText('Playwright2'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - PASS
await expect.soft(title).toHaveText('Playwright3'); - FAIL
await expect.soft(title).toHaveText('Playwright'); - PASS
```

**Output with default timeout 5 seconds orverride**
```javascript
 ✘  [demo1] › test/demo/pw_sample.js:8:1 › basic test (5s)

  1) [demo1] › test/demo/pw_sample.js:8:1 › basic test =============================================

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright1"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 250ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"


       9 |     await page.goto('https://playwright.dev/',{waitUntil: "networkidle"});
      10 |     const title = await page.locator('.navbar__inner .navbar__title');
    > 11 |     await expect.soft(title).toHaveText('Playwright1',{ timeout: 250 });
         |                              ^
      12 |     await expect.soft(title).toHaveText('Playwright2',{ timeout: 250 });
      13 |     await expect.soft(title).toHaveText('Playwright'),{ timeout: 250 };
      14 |     await expect.soft(title).toHaveText('Playwright3',{ timeout: 250 });

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:11:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright2"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 250ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"


      10 |     const title = await page.locator('.navbar__inner .navbar__title');
      11 |     await expect.soft(title).toHaveText('Playwright1',{ timeout: 250 });
    > 12 |     await expect.soft(title).toHaveText('Playwright2',{ timeout: 250 });
         |                              ^
      13 |     await expect.soft(title).toHaveText('Playwright'),{ timeout: 250 };
      14 |     await expect.soft(title).toHaveText('Playwright3',{ timeout: 250 });
      15 |     await expect.soft(title).toHaveText('Playwright',{ timeout: 250 });

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:12:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright3"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 250ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"


      12 |     await expect.soft(title).toHaveText('Playwright2',{ timeout: 250 });
      13 |     await expect.soft(title).toHaveText('Playwright'),{ timeout: 250 };
    > 14 |     await expect.soft(title).toHaveText('Playwright3',{ timeout: 250 });
         |                              ^
      15 |     await expect.soft(title).toHaveText('Playwright',{ timeout: 250 });
      16 | });
      17 |

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:14:30

    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/pw_sample.js-basic-test-demo1/test-failed-1.png
    ------------------------------------------------------------------------------------------------


  1 failed
    [demo1] › test/demo/pw_sample.js:8:1 › basic test ==============================================

To open last HTML report run:

  npx playwright show-report
```

**Output with default timeout 5 seconds**
```javascript
 ✘  [demo1] › test/demo/pw_sample.js:8:1 › basic test (18s)

  1) [demo1] › test/demo/pw_sample.js:8:1 › basic test =============================================

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright1"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"


       9 |     await page.goto('https://playwright.dev/',{waitUntil: "networkidle"});
      10 |     const title = await page.locator('.navbar__inner .navbar__title');
    > 11 |     await expect.soft(title).toHaveText('Playwright1');
         |                              ^
      12 |     await expect.soft(title).toHaveText('Playwright2');
      13 |     await expect.soft(title).toHaveText('Playwright');
      14 |     await expect.soft(title).toHaveText('Playwright3');

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:11:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright2"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"


      10 |     const title = await page.locator('.navbar__inner .navbar__title');
      11 |     await expect.soft(title).toHaveText('Playwright1');
    > 12 |     await expect.soft(title).toHaveText('Playwright2');
         |                              ^
      13 |     await expect.soft(title).toHaveText('Playwright');
      14 |     await expect.soft(title).toHaveText('Playwright3');
      15 |     await expect.soft(title).toHaveText('Playwright');

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:12:30

    Error: expect(received).toHaveText(expected)

    Expected string: "Playwright3"
    Received string: "Playwright"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for selector ".navbar__inner .navbar__title"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"
      -   selector resolved to <b class="navbar__title">Playwright</b>
      -   unexpected value "Playwright"


      12 |     await expect.soft(title).toHaveText('Playwright2');
      13 |     await expect.soft(title).toHaveText('Playwright');
    > 14 |     await expect.soft(title).toHaveText('Playwright3');
         |                              ^
      15 |     await expect.soft(title).toHaveText('Playwright');
      16 | });
      17 |

        at /Users/venkataravuri/pw-automation/kb-automation-playwright/test/demo/pw_sample.js:14:30

    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/pw_sample.js-basic-test-demo1/test-failed-1.png
    ------------------------------------------------------------------------------------------------


  1 failed
    [demo1] › test/demo/pw_sample.js:8:1 › basic test ==============================================

To open last HTML report run:

  npx playwright show-report

```

**Comment by pavelfeldman** [comment]
Everything looks correct to me, I see 3 failures in each.

**Comment by dgozman** [comment]
Closing as per above.
