### ISSUE TITLE
[BUG] can't start in Lambda nodejs 12.x

### ISSUE THREAD

**Issue by und3fined** [microsoft/playwright#1379]
Hi all,

Currently, i'm tested in Lambda but not work, i'm get a errror and, can't start chrome

```
[0313/150422.217745:FATAL:render_process_host_impl.cc(4261)] Check failed: render_process_host->InSameStoragePartition( BrowserContext::GetStoragePartition(browser_context, site_instance, false )). 

... trace

Calling _exit(1). Core file will not be generated.

Error: Protocol error (Target.createTarget): Target closed.
    at /var/task/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
    at new Promise (<anonymous>)
    at CRSession.send (/var/task/node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
    at Object.newPage (/var/task/node_modules/playwright-core/lib/chromium/crBrowser.js:70:57)
    at BrowserContext.newPage (/var/task/node_modules/playwright-core/lib/browserContext.js:62:31)
    at BrowserContext.<anonymous> (/var/task/node_modules/playwright-core/lib/helper.js:55:31)
```

But with puppeteer i'm start chrome and run script successful (both chrome 82 and 80 worked)

Puppeteer not use `BrowserContext` for create new page => it worked
Playwright can't send `Target.createTarget` with context. A bug in chrome 

```
[0313/165806.615915:FATAL:render_process_host_impl.cc(4261)] Check failed: render_process_host->InSameStoragePartition( BrowserContext::GetStoragePartition(browser_context, site_instance, false )).
```

Any help for make playwright work with `BrowserContext` in AWS Lambda?

**Comment by und3fined** [comment]
Update chrome source https://github.com/chromium/chromium/blob/18ca2de542bfa53802639dc5c85762b5e7b5bef6/content/browser/renderer_host/render_process_host_impl.cc#L4334

**Comment by und3fined** [comment]
I'm fixed it
-----
A new chrome patched shared in [here](https://github.com/help-14/playwright-amazon-linux-build/releases)
