### ISSUE TITLE
Bug: DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#14065]
```
(node:88279) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

During `npx playwright install`.

**Comment by eyep-incomm** [comment]
@mxschmitt still seeing this issue after upgrading to latest alphas since you merged this fix. I'm attempting to run playwright tests with 

```npx playwright test --config=playwright.config.ts --project=Chromium```

See details below:

**Context:**
- Playwright Version: [1.23.0-alpha-jun-4-2022 and 1.23.0-alpha-jun-7-2022
- Operating System: Windows 10 21H2
- Node.js version: [16.15.0]
- Browser: [All]
- Extra: [any specific details about your environment]


## System:
 - OS: Windows 10 10.0.19044
 - Memory: 10.86 GB / 31.71 GB
## Binaries:
 - Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD


**Code Snippet**

```(node:355124) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Using ```node --trace-deprecation ....```
```
Error: Cannot find module 'C:\Source\Repos\serve-tst-prod-automation-playwright\tests\...'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
```

**During ```npx playwright test --config=playwright.config.ts --project=Chromium``` this error occurs even after attempting to upgrade to latest alpha build with Merge [PR 14638 fix: hide DeprecationWarning of fd-slicer](https://github.com/microsoft/playwright/pull/14638)*

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Maybe you have multiple versions of playwright installed? On our CI the error is gone which proofs that the main issue is fixed.

**Comment by eyep-incomm** [comment]
Thanks for the quick response. Sorry to be a pest, but I'm quite new to modern typescript and node. How do I check to see if multiple version of playwright are installed? What's the npm command? Trying too google this now.

**Comment by mxschmitt** [comment]
Seems like the deprecation warning which you are getting is a different one. We can nail it down by setting the following environment variable:

```
$Env:NODE_OPTIONS="--trace-deprecation"
npx playwright test --config=playwright.config.ts --project=Chromium
```

it should then print a stack trace next to the deprecation warning.

**Comment by eyep-incomm** [comment]
@mxschmitt Was able to do the following - 

set the environment variable and here's the output:

```
PS C:\Source\Repos\qa-automation-playwright\tests> $Env:NODE_OPTIONS="--trace-deprecation"
PS C:\Source\Repos\qa-automation-playwright\tests> npx playwright test --config=playwright.config.ts --project=Chromium
[TestData] Json TestCaseData: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

Running 7 tests using 6 workers

(node:474972) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at Array.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28644)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:27666
    at oe (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28782)
    at Er (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30427)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:17:10
    at Array.map (<anonymous>)
    at Function.pt [as prepareStackTrace] (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30810)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at extendedTrace (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:68:15)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:25:14
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\for-await.js:10:42)      
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\index.js:16:17)
[TestData] Json TestCaseData: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
     [Chromium] › e2e\e2e-registration.spec.ts:22:9 › Onboarding | Registration › Registration 
[TestData] Json TestCaseData: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
     [Chromium] › e2e\e2e-registration.spec.ts:22:9 › Onboarding | Registration › Registration 
(node:484728) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at Array.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28644)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:27666
    at oe (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28782)
    at Er (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30427)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:17:10
    at Array.map (<anonymous>)
    at Function.pt [as prepareStackTrace] (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30810)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at extendedTrace (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:68:15)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:25:14
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\for-await.js:10:42)      
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\index.js:16:17)
(node:470588) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at Array.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28644)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:27666
    at oe (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28782)
    at Er (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30427)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:17:10
    at Array.map (<anonymous>)
    at Function.pt [as prepareStackTrace] (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30810)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at extendedTrace (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:68:15)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:25:14
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\for-await.js:10:42)      
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\index.js:16:17)
[TestData] Json TestCaseData: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
[TestData] Json TestCaseData: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
     [Chromium] › e2e\e2e-registration.spec.ts:22:9 › Onboarding | Registration › Registration 
     [Chromium] › e2e\e2e-registration.spec.ts:22:9 › Onboarding | Registration › Registration 
(node:493340) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at Array.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28644)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:27666
    at oe (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28782)
    at Er (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30427)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:17:10
    at Array.map (<anonymous>)
    at Function.pt [as prepareStackTrace] (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30810)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at extendedTrace (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:68:15)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:25:14
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\for-await.js:10:42)      
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\index.js:16:17)
(node:449628) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at Array.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28644)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:27666
    at oe (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28782)
    at Er (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30427)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:17:10
    at Array.map (<anonymous>)
    at Function.pt [as prepareStackTrace] (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30810)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at extendedTrace (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:68:15)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:25:14
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\for-await.js:10:42)      
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\index.js:16:17)
[TestData] Json TestCaseData: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
[TestData] Json TestCaseData: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
     [Chromium] › e2e\e2e-registration.spec.ts:22:9 › Onboarding | Registration › Registration 
     [Chromium] › e2e\e2e-registration.spec.ts:22:9 › Onboarding | Registration › Registration 
(node:488108) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at Array.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28644)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:27666
    at oe (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28782)
    at Er (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30427)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:17:10
    at Array.map (<anonymous>)
    at Function.pt [as prepareStackTrace] (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30810)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at extendedTrace (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:68:15)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:25:14
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\for-await.js:10:42)      
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\index.js:16:17)
(node:476512) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:187:11)
    at new Buffer (node:buffer:271:3)
    at Array.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28644)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:27666
    at oe (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:28782)
    at Er (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30427)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:17:10
    at Array.map (<anonymous>)
    at Function.pt [as prepareStackTrace] (C:\Source\Repos\qa-automation-playwright\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:30810)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at extendedTrace (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:68:15)
    at C:\Source\Repos\qa-automation-playwright\node_modules\@babel\template\lib\builder.js:25:14
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\for-await.js:10:42)      
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  ✓  [Chromium] › e2e\e2e-registration.spec.ts:22:9 › Onboarding | Registration › Registration (16s)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Source\Repos\qa-automation-playwright\node_modules\@babel\plugin-proposal-async-generator-functions\lib\index.js:16:17)
```
