### ISSUE TITLE
[BUG]: Playwright v1.22 does not launch Firefox when executablepath is passed

### ISSUE THREAD

**Issue by Sandeepisebauz** [microsoft/playwright#14249]
**Context:**
- Playwright Version: v1.22
- Operating System: Windows 10
- Node.js version: [e.g. 12.22, 14.6]Na, used maven dependency
- Browser: Firefox version 100.0.1
- Extra: passed executable path

**Code Snippet**
browser = playwright.firefox().launch(launchOptions.
					setExecutablePath(spath));

spath is the firefox.exe path, in my case, I have a method to check the browser installed path on my machine and for firefox, binary is preset at--> C:\\Program Files\\Mozilla Firefox\\firefox.exe

Note: This works fine when I shift my browser to chrome and playwright launches the  Chrome browser which is installed on my machine.

Add any other details about the problem here.

com.microsoft.playwright.PlaywrightException: Error {
  message='Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
=========================== logs ===========================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
============================================================
  name='Error
  stack='Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
=========================== logs ===========================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
============================================================
    at C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\ffConnection.js:92:16
    at new Promise (<anonymous>)
    at FFConnection.send (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\ffConnection.js:88:12)
    at Function.connect (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\ffBrowser.js:47:34)
    at Firefox._connectToTransport (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\firefox.js:52:33)
    at Firefox._innerLaunch (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\browserType.js:152:32)
    at async Firefox._innerLaunchWithRetries (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\browserType.js:109:14)
    at async ProgressController.run (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\progress.js:101:22)
    at async Firefox.launch (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\browserType.js:84:21)
    at async BrowserTypeDispatcher.launch (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\dispatchers\browserTypeDispatcher.js:57:21)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:105)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:49)
	at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:41)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:41)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:32)
	at playwright.config.PlaywrightFactory.launchBrowser(PlaywrightFactory.java:54)
	at playwright.scripts.UPPDesktopCCLogin.setUp(UPPDesktopCCLogin.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at automation.runner.internal.statements.RunBeforeMethods.evaluate(RunBeforeMethods.java:47)
	at automation.runner.AutomationRunner.invokeTestUnitStatement(AutomationRunner.java:534)
	at automation.runner.AutomationRunner.run(AutomationRunner.java:346)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
=========================== logs ===========================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
============================================================
  name='Error
  stack='Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
=========================== logs ===========================
<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\VENKAT~1\AppData\Local\Temp\playwright_firefoxdev_profile-47huo8 -juggler-pipe --start-maximized -silent
<launched> pid=21104
============================================================
    at C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\ffConnection.js:92:16
    at new Promise (<anonymous>)
    at FFConnection.send (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\ffConnection.js:88:12)
    at Function.connect (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\ffBrowser.js:47:34)
    at Firefox._connectToTransport (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\firefox\firefox.js:52:33)
    at Firefox._innerLaunch (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\browserType.js:152:32)
    at async Firefox._innerLaunchWithRetries (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\browserType.js:109:14)
    at async ProgressController.run (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\progress.js:101:22)
    at async Firefox.launch (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\browserType.js:84:21)
    at async BrowserTypeDispatcher.launch (C:\Users\VENKAT~1\AppData\Local\Temp\playwright-java-3761578760053020560\package\lib\server\dispatchers\browserTypeDispatcher.js:57:21)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:183)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:163)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
	... 26 more

**Comment by mxschmitt** [comment]
This is expected, using a custom Firefox or WebKit is not supported because Playwright modifies the browser to enables Playwright to automate them.

Only Chromium custom executables are supported. See here: https://playwright.dev/docs/next/browsers
