### ISSUE TITLE
[BUG][Chromium] Page.Events.Popup should work with noopener and url crashes browser

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#1428]
Running the test on Chromium r751656 gives the following:

Failures:
1) [FAIL] Chromium [Driver] Page.Events.Popup should work with noopener and url (popup.spec.js:339:5)
  Message:
    Target closed
  Stack:
    Error: Target closed
        at Page._didDisconnect (/home/yurys/playwright/src/page.ts:204:3)
        at CRSession.<anonymous> (/home/yurys/playwright/src/chromium/crTarget.ts:65:76)
        at Object.onceWrapper (events.js:291:20)
        at CRSession.emit (events.js:203:13)
        at /home/yurys/playwright/src/chromium/crConnection.ts:186:3
      -- ASYNC --
        at Page.<anonymous> (/home/yurys/playwright/src/helper.ts:72:15)
        at /home/yurys/playwright/test/popup.spec.js:344:14
  Output:
    [0319/094823.698525:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
    [0319/094823.698530:ERROR:command_buffer_proxy_impl.cc(123)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
    Received signal 11 SEGV_MAPERR 000000000008
    #0 0x55fa1d96b0d9 base::debug::CollectStackTrace()
    #1 0x55fa1d8cbff3 base::debug::StackTrace::StackTrace()
    #2 0x55fa1d96ac75 base::debug::(anonymous namespace)::StackDumpSignalHandler()
    #3 0x7fd0c0fcc890 (/lib/x86_64-linux-gnu/libpthread-2.27.so+0x1288f)
    #4 0x55fa1b5b39ae content::mojom::DeviceEmulatorProxy::SetDeviceEmulation()
    #5 0x55fa1bcb56c9 content::protocol::EmulationHandler::SetDeviceMetricsOverride()
    #6 0x55fa1bcb58b8 content::protocol::EmulationHandler::SetDeviceMetricsOverride()
    #7 0x55fa1bb06379 content::protocol::Emulation::DispatcherImpl::setDeviceMetricsOverride()
    #8 0x55fa1bafd7b2 content::protocol::BackgroundService::DispatcherImpl::dispatch()
    #9 0x55fa1bb31e03 content::protocol::UberDispatcher::dispatch()
    #10 0x55fa1bc9da91 content::DevToolsSession::HandleCommand()
    #11 0x55fa1bca0596 base::internal::Invoker<>::RunOnce()
    #12 0x55fa2218d8a5 headless::protocol::HeadlessDevToolsSession::HandleCommand()
    #13 0x55fa2218cbfb headless::HeadlessDevToolsManagerDelegate::HandleCommand()
    #14 0x55fa1bc9d94c content::DevToolsSession::DispatchProtocolMessageInternal()
    #15 0x55fa1bc9d689 content::DevToolsSession::DispatchProtocolMessage()
    #16 0x55fa1bc99d60 base::internal::Invoker<>::RunOnce()
    #17 0x55fa1d91631b base::TaskAnnotator::RunTask()
    #18 0x55fa1d926bfe base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
    #19 0x55fa1d926990 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
    #20 0x55fa1d8e1d57 base::(anonymous namespace)::WorkSourceDispatch()
    #21 0x7fd0beee5417 g_main_context_dispatch
    #22 0x7fd0beee5650 (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4+0x4c64f)
    #23 0x7fd0beee56dc g_main_context_iteration
    #24 0x55fa1d8e1bb2 base::MessagePumpGlib::Run()
    #25 0x55fa1d927405 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
    #26 0x55fa1d8ff33e base::RunLoop::Run()
    #27 0x55fa1bc1f534 content::BrowserMainLoop::RunMainMessageLoopParts()
    #28 0x55fa1bc213e2 content::BrowserMainRunnerImpl::Run()
    #29 0x55fa2218b646 headless::HeadlessContentMainDelegate::RunProcess()
    #30 0x55fa1d49d447 content::ContentMainRunnerImpl::RunServiceManager()
    #31 0x55fa1d49d0a7 content::ContentMainRunnerImpl::Run()
    #32 0x55fa1d4ff3f3 service_manager::Main()
    #33 0x55fa1d49b301 content::ContentMain()
    #34 0x55fa1d4fe16d headless::(anonymous namespace)::RunContentMain()
    #35 0x55fa1d4fde6c headless::HeadlessShellMain()
    #36 0x55fa1af0c827 ChromeMain
    #37 0x7fd0ba937b97 __libc_start_main
    #38 0x55fa1af0c66a _start
      r8: 0000000000000000  r9: 0000000000000000 r10: 00000f2b387dbd30 r11: 00007ffc7b9212f4
     r12: 00000f2b387ffdcc r13: 0000000000000000 r14: 0000000000000000 r15: 00007ffc7b9213e0
      di: 00007ffc7b921350  si: 00007ffc7b9213e0  bp: 00007ffc7b921450  bx: 00007ffc7b921350
      dx: 0000000000000008  ax: 000055fa19302cce  cx: 0000000000000000  sp: 00007ffc7b921350
      ip: 000055fa1b5b39ae efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
     trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000008
    [end of stack trace]
    Calling _exit(1). Core file will not be generated.

**Comment by yury-s** [comment]
Filed a bug in Chromium: http://crbug.com/1063063
