### ISSUE TITLE
Issue with component testing / possibly intended behaviour

### ISSUE THREAD

**Issue by Phonesis** [microsoft/playwright#14401]
I have recently set up the experimental component testing feature of Playwright Test 1.22.2

I am using it with a React repo and have noticed some interesting behaviour when you pass in extracted components stored as consts.

Example

This works:

```
const alert = () => (
  <Alert type="info" title={'test'} id="alert" message={'hello'} />
)

test('should work', async ({ mount }) => {
  const component = await mount(alert())
  await expect(component).toContainText(alertMsg)
})
```

This fails:

```
const alert = (
  <Alert type="info" title={'test'} id="alert" message={'hello'} />
)

test('should work', async ({ mount }) => {
  const component = await mount(alert)
  await expect(component).toContainText(alertMsg)
})
```

In both cases the const appears to be a valid JSX.Element? The error is: 

```
undefined: TypeError: Cannot read properties of undefined (reading 'map')
    at render (http://localhost:3100/assets/index.22f7df41.js:2257:84)
    at window.playwrightMount (http://localhost:3100/assets/index.22f7df41.js:2274:19)
    at eval (eval at evaluate (:178:30), <anonymous>:19:25)
    at UtilityScript.evaluate (<anonymous>:180:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at src/components/Alert/Alert.spec.pw.tsx:18:27
```

Interestingly, both of the above work with Cypress component testing. So wondering if Playwright is enforcing something specific here?

**Comment by Phonesis** [comment]
In addition to above, I get a minified error if i try to use a component that uses a sub component: 

```
undefined: Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bkind%2C%20type%2C%20props%2C%20children%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rg (http://localhost:3100/assets/index.22f7df41.js:390:47)
    at A (http://localhost:3100/assets/index.22f7df41.js:394:29)
    at x (http://localhost:3100/assets/index.22f7df41.js:396:133)
    at http://localhost:3100/assets/index.22f7df41.js:400:225
    at fi (http://localhost:3100/assets/index.22f7df41.js:426:171)
    at ck (http://localhost:3100/assets/index.22f7df41.js:521:134)
    at bk (http://localhost:3100/assets/index.22f7df41.js:500:350)
    at ak (http://localhost:3100/assets/index.22f7df41.js:500:279)
    at Tj (http://localhost:3100/assets/index.22f7df41.js:500:138)
    at Lj (http://localhost:3100/assets/index.22f7df41.js:493:164)
    at src/components/Alert/Alert.spec.pw.tsx:19:27
```

Example code: 

```
const alertMsg = 'expected test message'

const Message = () => {
  return <Typography format="bcs">{alertMsg}</Typography>
}

const alert = () => (
  <Alert type="info" title={'test'} id="alert" message={< Message />} />
)

test('should work', async ({ mount }) => {
  const component = await mount(alert())
  await expect(component).toContainText(alertMsg)
})
```

**Comment by craigjennings11** [comment]
I just upgraded to v1.23.0 and am still experiencing the second issue described in this issue - https://github.com/microsoft/playwright/issues/14401#issuecomment-1137175317. Here's my code,

<details>
<summary>Code</summary>

```jsx
// MyComponent.tsx
function MyComponent({ content }: { content: JSX.Element | string }) {
  return <div>{content}</div>;
}

export default MyComponent;

// MyComponent.test.tsx
import { expect, test } from '@playwright/experimental-ct-react';
import MyComponent from './MyComponent';

// Succeeds
test('renders a string prop', async ({ mount }) => {
  const component = await mount(<MyComponent content="Howdy" />);

  await expect(component).toContainText('Howdy');
});

const inner = () => <div>Howdy</div>;

// Fails
test('renders the result of a function', async ({ mount }) => {
  const component = await mount(<MyComponent content={inner()} />);

  await expect(component).toContainText('Howdy');
});

// Fails
test('renders a jsx prop', async ({ mount }) => {
  const component = await mount(<MyComponent content={<div>Howdy</div>} />);

  await expect(component).toContainText('Howdy');
});
```
</details>

<details>
<summary>Error</summary>

> undefined: Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bkind%2C%20type%2C%20props%2C%20children%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
</details>

**Comment by Phonesis** [comment]
@pavelfeldman This is a pretty major issue actually - fyi.

**Comment by trishanthnaidu** [comment]
@pavelfeldman do we have any updates on this ? Really looking for this issue to be resolved.
