### ISSUE TITLE
[BUG] Cannot use .toMatchSnapshot() outside of playwright test runner

### ISSUE THREAD

**Issue by benjefferies** [microsoft/playwright#14539]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Mac
- Node.js version: v16.13.2
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
import { expect } from '@playwright/test';
...
Then('the BEE configuration has rules', function() {
  expect(this.beeConfiguration.rules).toMatchSnapshot(this.cucumberScenarioName); // TODO figure out unique test name for snapshot
});
```

**Describe the bug**

Cucumber doesn't run within the playwright test runner. To use the .toMatchSnapshot() expectation it depends on the currentTestInfo being initialised which isn't outside of the playwright test runner.

```
And the BEE configuration has rules # src/steps/ies-installer/ConfigureBee.ts:120
       Error: toMatchSnapshot() must be called during the test
           at Object.toMatchSnapshot (/Users/benjefferies/source/gitlab/sero-digital/optimised-retrofit/intelligent-energy-systems/playwright/node_modules/@playwright/test/lib/matchers/toMatchSnapshot.js:268:24)
           at __EXTERNAL_MATCHER_TRAP__ (/Users/benjefferies/source/gitlab/sero-digital/optimised-retrofit/intelligent-energy-systems/playwright/node_modules/expect/build/index.js:386:30)
           at Object.throwingMatcher (/Users/benjefferies/source/gitlab/sero-digital/optimised-retrofit/intelligent-energy-systems/playwright/node_modules/expect/build/index.js:387:15)
           at Proxy.<anonymous> (/Users/benjefferies/source/gitlab/sero-digital/optimised-retrofit/intelligent-energy-systems/playwright/node_modules/@playwright/test/lib/expect.js:157:37)
           at World.<anonymous> (/Users/benjefferies/source/gitlab/sero-digital/optimised-retrofit/intelligent-energy-systems/playwright/src/steps/ies-installer/ConfigureBee.ts:121:39)
```

**Comment by benjefferies** [comment]
Relates to https://github.com/microsoft/playwright/issues/11975

**Comment by aslushnikov** [comment]
Let's merge this to https://github.com/microsoft/playwright/issues/11975
