### ISSUE TITLE
Error : This browser does not support WebAssembly (WebKit)

### ISSUE THREAD

**Issue by nssidhu** [microsoft/playwright#14536]
I am trying to test the Blazor WebAssembly project.
It is failing for webkit(mobile & Desktops) with error that browser does not support WebAssembly.

Interestingly when i browse the site from real mobile device it works fine.

What configurations should i have configured to test my Blazor WebAssembly for mobile devices(android & iOS) ?

I am running the test from Visual Studio Code on Windows 11 Machine.

This browser does not support WebAssembly.
Error: This browser does not support WebAssembly.
    at unknown (https://XXXXXXX.net/_framework/blazor.webassembly.js:1:42730)
    at unknown (https://XXXXXXX.net/_framework/blazor.webassembly.js:1:43275)
    at global code (https://XXXXXXnet/:1:42)
    at appendChild ([native code]:0:0)
    at unknown (https://XXXXXXX.net/_framework/blazor.webassembly.js:1:43397)
    at unknown (https://XXXXXX.net/_framework/blazor.webassembly.js:1:43401)
    at Promise ([native code]:0:0)
    at start (https://XXXXXX.net/_framework/blazor.webassembly.js:1:34573)
    at unknown (https://XXXXXX.net/_framework/blazor.webassembly.js:1:59491)
    at asyncFunctionResume ([native code]:0:0)
    at unknown ([native code]:0:0)
    at promiseReactionJobWithoutPromise ([native code]:0:0)
    at promiseReactionJob ([native code]:0:0)

## System:
 - OS: Windows 10 10.0.22000
 - Memory: 11.31 GB / 16.00 GB
## Binaries:
 - Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
 -

**Comment by aslushnikov** [comment]
Windows WebKit doesn't support webassembly - see https://github.com/microsoft/playwright/issues/2876
