### ISSUE TITLE
[BUG] Component tests. Build failed - Rollup failed to resolve import "@emotion/styled"

### ISSUE THREAD

**Issue by pashidlos** [microsoft/playwright#14684]
**Context:**
## System:
 - OS: macOS 11.6.6
 - Memory: 255.63 MB / 16.00 GB
## Binaries:
 - Node: 14.17.0 - /usr/local/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.5.2 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**
https://github.com/pashidlos/pw-component-test-example/tree/import-interface

```javascript
yarn run v1.22.17
$ playwright test -c playwright-ct.config.ts

Running 3 tests using 3 workers

vite v2.9.10 building for production...
✓ 870 modules transformed.
'BreadcrumbsProps' is not exported by src/widget/Breadcrumbs.tsx, imported by src/index.ts
file: /Users/pstrunkin/work/pw-component-test-example/src/index.ts:1:0
1: export { Breadcrumbs, BreadcrumbsProps } from "./widget/Breadcrumbs";
   ^
2: export { TestComponent } from "./TestComponent";

Error: 'BreadcrumbsProps' is not exported by src/widget/Breadcrumbs.tsx, imported by src/index.ts

   at node_modules/rollup/dist/shared/rollup.js:198

  196 | function error(base) {
  197 |     if (!(base instanceof Error))
> 198 |         base = Object.assign(new Error(base.message), base);
      |                              ^
  199 |     throw base;
  200 | }
  201 | function augmentCodeLocation(props, pos, source, id) {

    at error (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:12659:16)
    at Module.getVariableForExportName (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:12814:29)
    at Module.includeAllExports (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:12886:37)
    at Module.includeAllInBundle (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:12903:14)
    at Graph.includeStatements (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:23200:24)
    at Graph.build (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:23105:14)
    at /Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:23769:13
    at catchUnfinishedHookActions (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:23278:20)
    at rollupInternal (/Users/work/pw-component-test-example/node_modules/rollup/dist/shared/rollup.js:23766:5)
    at doBuild (/Users/work/pw-component-test-example/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:41685:24)
    at build (/Users/work/pw-component-test-example/node_modules/vite/dist/node/chunks/dep-9e5491c9.js:41527:16)

TypeError: Cannot read property 'httpServer' of undefined


  3 skipped

To open last HTML report run:

  npx playwright show-report
```

**Describe the bug**
Cant run tests

**Comment by pavelfeldman** [comment]
Use `import type` instead!

**Comment by pashidlos** [comment]
@pavelfeldman thanks !

taking into account that `BreadcrumbsProps` is interface and `Breadcrumbs` is a component
inside `index.ts`
this not working 
```
export { Breadcrumbs, BreadcrumbsProps } from "./widget/Breadcrumbs";
```
this is working
```
export { Breadcrumbs } from "./widget/Breadcrumbs";
export type { BreadcrumbsProps } from "./widget/Breadcrumbs";
```
