### ISSUE TITLE
[BUG] Vue component testing doesn't work with "*.test.mjs"

### ISSUE THREAD

**Issue by nag5000** [microsoft/playwright#14698]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Linux
- Node.js version: 14.19.3
- Browser: All

**Code Snippet**

There are 2 identical test files "tests/e2e/FooBar.test.EXT" with different extensions ".mjs" and ".ts":

```js
import { expect, test } from '@playwright/experimental-ct-vue'
import FooBar from './FooBar.vue'

test('FooBar', async ({ mount, page }) => {
  const component = await mount(FooBar)
  expect(component).toBeTruthy()
})
```

**Describe the bug**

With ".ts" it works:

```
$ npx playwright test -c playwright-ct.config.ts tests/e2e/FooBar.test.ts

Running 1 test using 1 worker

vite v2.7.13 building for production...
✓ 2209 modules transformed.
...
  1 passed (21s)
```

With ".mjs" there is exception:

```
$ npx playwright test -c playwright-ct.config.ts tests/e2e/FooBar.test.mjs

Running 0 test using 0 worker

TypeError [ERR_UNKNOWN_FILE_EXTENSION] [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".vue" for /home/......./tests/e2e/FooBar.vue

    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 1)
    at link (internal/modules/esm/module_job.js:83:9)

=================
 no tests found.
```

**Comment by nag5000** [comment]
No, it's not an ESM module. But this is reproduced in my app regardless of whether I put `"type": "module"` in package.json or not.

**Comment by inthegreenwild** [comment]
Was this released in 1.24.2? I'm facing the same issue on 1.24.2 still

**Comment by nagisaando** [comment]
The issue is still happening. is there any update for this?
