### ISSUE TITLE
[Question] Playwright with Codeceptjs Does Not run on a RedHat Server

### ISSUE THREAD

**Issue by jbergeronjr** [microsoft/playwright#14712]
```bash
> codeceptjs run --plugins allure --grep "localtest"
/root/qa/node_modules/playwright-core/lib/server/recorder/javascript.js:181
      var  test= require("@playwright/test").test;var  expect${options.deviceName ? '= require("@playwright/test").expect${options.deviceName ? ';var  devices' : ''} = require("@playwright/test").devices' : ''};;
                                                                                                                                                 ^

SyntaxError: Unexpected token ';'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions.<computed> [as .js] (/root/qa/node_modules/node-hook/index.js:73:14)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/qa/node_modules/playwright-core/lib/server/recorder/java.js:16:19)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
```
Some details about what I am running.

* CodeceptJS version: ^3.1.1
* Playwright version: ^1.14.1
* NodeJS Version: v18.3.0
* Operating System: Linux RedHat 8

I don't think this is a codecept issue. Seems more on the playwright side. Anyone have any ideas on how this could be fixed or run on Redhat 8?

**Comment by pavelfeldman** [comment]
I don't think it is related to Redhat 8 and it looks like Playwright code is post-processed here, so I'd definitely file it against codeceptjs!
