### ISSUE TITLE
[Question] MS Edge doesn't open when deploying with Intune

### ISSUE THREAD

**Issue by TBatist** [microsoft/playwright#14786]
Hello there,

First of all, I was not sure to mark this issue as a question or a bug, but I didn't feel like this issue is a real bug in Playwright. Therefor, I've marked this issue as a question.

I have successfully wrote program which will automate a process in Microsoft Edge. The desire is to deploy this program with Intune, so the program will run on all device within the company. For this program, I want to use the default browser of the user, so all data created in the Playwright session will be saved. To achieve this, I wrote the following code.

```cs
try
{
    // Kill all running Edge processes as Playwright will fail if there is an instance running already
    await Task.Run(() => Process.GetProcessesByName("msedge")
        .ToList()
        .ForEach(p => p.Kill()));

    var session = await Playwright.CreateAsync();        
    var localAppDataPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
    // %LocalAppData%, i.e. C:\Users\{USER}\AppData\Local

    var context = await session.Chromium.LaunchPersistentContextAsync(
        $"{localAppDataPath}\\Microsoft\\Edge\\User Data", new() { 
            Headless = false,
            Channel = "msedge",
            SlowMo = 500, 
            ExecutablePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
            IgnoreDefaultArgs = new string[] {"--disable-extensions", "--enable-automation", "--no-sandbox"}
    }); 
    return context;
}
catch 
{
    throw new PlaywrightException("Browser could not be started");
}

```

It will stop all currently running Edge processes and then start a new Playwright session. I've done this, because Playwright will fail if I try to start a Playwright context if there is already an Edge process running.

I've tested this code on my local machine, and it runs successful. I also tested this on a test device, on which it also runs successful. Finally, I want to test this program when it is deployed to the same test device, but using Intune for the deployment. I will manually start the program using the Company Portal. 

Unfortunately, the deployment with Intune fails every time. After some more testing, the problem seems to be in creating the context. I have absolutely no clue what the problem can be. Does anybody know what the problem could be?

**Comment by mxschmitt** [comment]
What do you mean that it fails, what kind of exception gets thrown with what error?

Might be the same root cause as https://github.com/microsoft/playwright/issues/13631

**Comment by TBatist** [comment]
So, apart from the error I want to throw, this is the complete error message.

Browser closed.

==================== Browser output: ====================
<launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --user-data-dir=C:\Users\InfrastructureTest\AppData\Local\Microsoft\Edge\User Data --remote-debugging-pipe about:blank
<launched> pid=5756
=========================== logs ===========================
<launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --user-data-dir=C:\Users\InfrastructureTest\AppData\Local\Microsoft\Edge\User Data --remote-debugging-pipe about:blank
<launched> pid=5756
============================================================



at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Playwright.Transport.Connection.<InnerSendMessageToServerAsync>d__34`1.MoveNext() in /_/src/Playwright/Transport/Connection.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Playwright.Core.BrowserType.<LaunchPersistentContextAsync>d__16.MoveNext() in /_/src/Playwright/Core/BrowserType.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at OPBrowserExtension.Playwright_Setup.<GetBrowserContextAsync>d__0.MoveNext() in C:\Users\TimBatist\Documents\Employee Device Automation\OPBrowserExtension\Playwright_Setup.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at OPBrowserExtension.Extension_Setup.<InstallExtionsionToEdge>d__0.MoveNext() in C:\Users\TimBatist\Documents\Employee Device Automation\OPBrowserExtension\Extension_Setup.cs:line 10
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at OPBrowserExtension.Program.<Run>d__21.MoveNext() in C:\Users\TimBatist\Documents\Employee Device Automation\OPBrowserExtension\Program.cs:line 76

**Comment by mxschmitt** [comment]
I don't see any timeout error, could you try running a minimal repro aka this?

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();
await page.GotoAsync("https://playwright.dev/dotnet");
await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });
```

And set the `DEBUG=pw:browser` env var?

**Comment by TBatist** [comment]
I am not exactly sure what you mean with the "``DEBUG=pw:browser`` env var" and where I have to set that.

However, I've tried your code on my local machine, test machine, and test machine using Intune. On both my local machine and the test machine, it works when I run the code manually (i.e. it adds a screenshot of the site to my folder). But when I deploy that code with Intune, it fails. The Windows Event Viewer gives the following stacktrace:

Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Playwright.PlaywrightException
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Playwright.Transport.Connection+<InnerSendMessageToServerAsync>d__34`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Playwright.Transport.Connection+<WrapApiCallAsync>d__46`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at Microsoft.Playwright.Core.BrowserType+<LaunchAsync>d__15.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at OPBrowserExtension.Program+<Run>d__21.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
at OPBrowserExtension.Program+<Main>d__20.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

I also get another error:
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1706, time stamp: 0x458acb5b
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process id: 0x2968
Faulting application start time: 0x01d87f0c0da5d270
Faulting application path: C:\WINDOWS\IMECache\6be85e9a-20cd-45e3-8ba0-0a02bffae81b_12\OPBrowserExtension.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4d3bae9a-ef6d-4475-af38-962faa674b31
Faulting package full name:
Faulting package-relative application ID:

**Comment by TBatist** [comment]
Okay, I don't exactly know what the problem is and why the code does work manually but not with Intune, but I removed the ``IgnoreDefaultArgs = "--enable-automation"`` and now it also works with Intune. Although this could sound logical, I think it is strange that it did work locally, but not with Intune. Anyways, thanks for your time @mxschmitt
