### ISSUE TITLE
[BUG] Error: Failed to download chromium v1000

### ISSUE THREAD

**Issue by lszomoru** [microsoft/playwright#14790]
We have started seeing intermittent issues while trying to download Playwright in our Azure Pipelines:

```
yarn run v1.22.19
$ /__w/1/s/node_modules/.bin/npm-run-all -lp 'electron x64' playwright-install
[electron x64      ] $ node build/lib/electron x64
[playwright-install] $ node build/azure-pipelines/common/installPlaywright.js
[playwright-install] /__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:613
[playwright-install]       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
[playwright-install]             ^
[playwright-install] 
[playwright-install] Error: Failed to download chromium v1000, caused by
[playwright-install] Error: Client network socket disconnected before secure TLS connection was established
[playwright-install]     at connResetException (node:internal/errors:692:14)
[playwright-install]     at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)
[playwright-install]     at TLSSocket.emit (node:events:539:35)
[playwright-install]     at endReadableNT (node:internal/streams/readable:1345:12)
[playwright-install]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[playwright-install]     at /__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:613:13
[playwright-install]     at async Registry._downloadExecutable (/__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:612:5)
[playwright-install]     at async Registry.install (/__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:590:9)
[playwright-install]     at async installBrowsersForNpmInstall (/__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:780:3)
[playwright-install]     at async retry (/__w/1/s/build/azure-pipelines/common/retry.js:12:20)
[playwright-install]     at async install (/__w/1/s/build/azure-pipelines/common/installPlaywright.js:10:5)
[playwright-install] error Command failed with exit code 1.
[playwright-install] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "playwright-install" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Are there any known issues with the infrastructure hosting Playwright? Thank you!

**Comment by bpasero** [comment]
//cc @pavelfeldman

**Comment by pavelfeldman** [comment]
It is saying "Node can't download off Azure", so points at Azure CDN for dropping the connection from Azure Pipelines.
We are already retrying the fetch, DEBUG=pw:install should show all the attempts.

**Comment by lszomoru** [comment]
We are also seeing the same errors in our GitHub Actions.

**Comment by pavelfeldman** [comment]
> We are also seeing the same errors in our GitHub Actions.

Yeah, it is the same thing. Did it resolve? Probably was due to some outage on Azure side.

**Comment by lszomoru** [comment]
Yeah, it looks like the issue has been resolved.

**Comment by lukasholzer** [comment]
I think it is not resolved

**Comment by lukasholzer** [comment]
Now our CI works again. Was there any change?

**Comment by lszomoru** [comment]
Tagging @pavelfeldman to see if he is aware of any platform incidents/changes.

**Comment by pavelfeldman** [comment]
Looks like intermittent Azure outage. We are receiving more reports on it.

**Comment by lszomoru** [comment]
@dgozman, please reopen this issue as this is still happening (see timestamp).

```
2022-06-14T18:46:05.9085906Z [playwright-install] $ node build/azure-pipelines/common/installPlaywright.js
2022-06-14T18:46:24.6886794Z [playwright-install] Request failed, retrying in 233.27479487119004ms...
2022-06-14T18:46:42.2247963Z [playwright-install] Request failed, retrying in 142.13553533540315ms...
2022-06-14T18:46:48.3436536Z [playwright-install] D:\a\_work\1\s\node_modules\playwright-core\lib\server\registry\index.js:613
2022-06-14T18:46:48.3438094Z [playwright-install]       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
2022-06-14T18:46:48.3438951Z [playwright-install]             ^
2022-06-14T18:46:48.3439589Z [playwright-install] 
2022-06-14T18:46:48.3440344Z [playwright-install] Error: Failed to download chromium v1000, caused by
2022-06-14T18:46:48.3441391Z [playwright-install] Error: EPERM: operation not permitted, open 'C:\Users\CLOUDT~1\AppData\Local\Temp\playwright-download-chromium-win64-1000.zip'
2022-06-14T18:46:48.3443173Z [playwright-install]     at D:\a\_work\1\s\node_modules\playwright-core\lib\server\registry\index.js:613:13
2022-06-14T18:46:48.3444728Z [playwright-install]     at async Registry._downloadExecutable (D:\a\_work\1\s\node_modules\playwright-core\lib\server\registry\index.js:612:5)
2022-06-14T18:46:48.3446634Z [playwright-install]     at async Registry.install (D:\a\_work\1\s\node_modules\playwright-core\lib\server\registry\index.js:590:9)
2022-06-14T18:46:48.3448325Z [playwright-install]     at async installBrowsersForNpmInstall (D:\a\_work\1\s\node_modules\playwright-core\lib\server\registry\index.js:780:3)
2022-06-14T18:46:48.3449453Z [playwright-install]     at async retry (D:\a\_work\1\s\build\azure-pipelines\common\retry.js:12:20)
2022-06-14T18:46:48.3450493Z [playwright-install]     at async install (D:\a\_work\1\s\build\azure-pipelines\common\installPlaywright.js:10:5)
2022-06-14T18:46:48.3752712Z [playwright-install] error Command failed with exit code 1.
2022-06-14T18:46:48.3755240Z [playwright-install] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-06-14T18:46:48.3859126Z ERROR: "playwright-install" exited with 1.
2022-06-14T18:46:48.4045967Z error Command failed with exit code 1.
```

**Comment by lszomoru** [comment]
Things are looking stable in the last 24 hours. Closing the issue for now.

**Comment by s-h-a-d-o-w** [comment]
Seems like this is happening again at the moment:
```
Output:
Playwright build of chromium v1000 downloaded to /home/runner/.cache/ms-playwright/chromium-1000
Playwright build of ffmpeg v1007 downloaded to /home/runner/.cache/ms-playwright/ffmpeg-1007
/home/runner/work/[REDACTED]/node_modules/playwright-core/lib/server/registry/index.js:613
      throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
            ^

Error: Failed to download firefox v1322, caused by
Error: read ECONNRESET
```

It seems so basic that I feel silly even asking but... don't you fetch from somewhere that has redundancy across continents?

**Comment by rabellino12** [comment]
Github Actions are failing on our end with similar error for Chromium, we are installing storybook/test-runner which depends on `playwright "^1.14.0"`
The logs:
```
(node:2218) UnhandledPromiseRejectionWarning: Error: Failed to download Chromium 102.0.5005.40 (playwright build v1005), caused by
[94](https://github.com/thesandboxgame/TSB_Marketplace/runs/8234570288?check_suite_focus=true#step:4:95)
Error: read ECONNRESET
```

**Comment by s-h-a-d-o-w** [comment]
As mentioned [here](https://github.com/microsoft/playwright/pull/17196#discussion_r969143053), this probably won't be an issue starting with 1.22.0 anymore.

@rabellino12
At least in their "next" branch, that runner now specifies the following:
```
playwright@^1.14.0:
  version "1.25.2"
```
Might be worthwhile checking whether that version is up to date in your own lockfile.
