### ISSUE TITLE
[Question] First test case would always fail when launching a development web server during tests

### ISSUE THREAD

**Issue by MervLim** [microsoft/playwright#14814]
Hi, i am using playwright v1.22 with macOS and my application is purely front-end(React/TypeScript). I have set up to launch a development web server at my playwright config file. I have 2 test cases and when i run playwright test, the first test case would always fail. This doesn't happen if i start my application from my own terminal and run playwright test. Am i missing anything?

**My code on playwright.config.ts**
```javascript
const config: PlaywrightTestConfig = {
  testDir: "./src/e2e",
  webServer: {
    command: 'npm start',
    port: 3000,
    reuseExistingServer: !process.env.CI,
  },
  use: {
    baseURL: 'http://localhost:3000/',
  },
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },
  ],
};
export default config;
```

**My code for test cases**
```javascript
test.describe("inputs otp interaction test", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/components/input-field/input-otp');
  });

  test("inputs should change focus by tabbing", async ({ page }) => {
    const input1 = page.locator('data-testid=otp-number0').first();
    const input2 = page.locator('data-testid=otp-number1').first();
    const input3 = page.locator('data-testid=otp-number2').first();
    const input4 = page.locator('data-testid=otp-number3').first();
    const input5 = page.locator('data-testid=otp-number4').first();
    const input6 = page.locator('data-testid=otp-number5').first();

    await input1.click();
    await page.keyboard.press('Tab');
    await expect(input2).toBeFocused;
    await page.keyboard.press('Tab');
    await expect(input3).toBeFocused;
    await page.keyboard.press('Tab');
    await expect(input4).toBeFocused;
    await page.keyboard.press('Tab');
    await expect(input5).toBeFocused;
    await page.keyboard.press('Tab');
    await expect(input6).toBeFocused;
  });
  
  test("inputs should be able to filled up and delete correctly", async ({
    page,
  }) => {
    const input1 = page.locator('data-testid=otp-number0').first();
    const input2 = page.locator('data-testid=otp-number1').first();
    const input3 = page.locator('data-testid=otp-number2').first();
    const input4 = page.locator('data-testid=otp-number3').first();
    const input5 = page.locator('data-testid=otp-number4').first();
    const input6 = page.locator('data-testid=otp-number5').first();

    await input1.click();
    await input1.fill('1');
    await expect(input1).toHaveValue('1');
    await expect(input2).toBeFocused;

    await input2.fill('2');
    await expect(input2).toHaveValue('2');
    await expect(input3).toBeFocused;

    await input3.fill('3');
    await expect(input3).toHaveValue('3');
    await expect(input4).toBeFocused;

    await input4.fill('4');90
    await expect(input4).toHaveValue('4');
    await expect(input5).toBeFocused;

    await input5.fill('5');
    await expect(input5).toHaveValue('5');
    await expect(input5).toBeFocused;

    await input6.fill('6');
    await expect(input6).toHaveValue('6');
    await expect(input6).toBeFocused;

    await page.keyboard.press('Backspace');
    await expect(input6).toBeEmpty;
    await expect(input5).toBeFocused;

    await page.keyboard.press('Backspace');
    await expect(input5).toBeEmpty;
    await expect(input4).toBeFocused;

    await page.keyboard.press('Backspace');
    await expect(input4).toBeEmpty;
    await expect(input3).toBeFocused;

    await page.keyboard.press('Backspace');
    await expect(input3).toBeEmpty;
    await expect(input2).toBeFocused;

    await page.keyboard.press('Backspace');
    await expect(input2).toBeEmpty;
    await expect(input1).toBeFocused;
  });
});
```
**Error log**
```
Running 4 tests using 2 workers

[WebServer] Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
     [chromium] › InputOtp.spec.ts:9:3 › inputs otp interaction test › inputs sh
  pw:api => browserType.launch started +0ms
     [webkit] › InputOtp.spec.ts:9:3 › inputs otp interaction test › inputs shou
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +226ms
  pw:api => browser.newContext started +2ms
  pw:api <= browser.newContext succeeded +6ms
  pw:api => tracing.stop started +3ms
  pw:api <= tracing.stop succeeded +2ms
  ✘  [chromium] › InputOtp.spec.ts:9:3 › inputs otp interaction test › inp (30s)
  ✘  [webkit] › InputOtp.spec.ts:9:3 › inputs otp interaction test › input (30s)
  pw:api => browser.newContext started +3ms
  pw:api <= browser.newContext succeeded +38ms
  pw:api => tracing.stop started +4ms
  pw:api <= tracing.stop succeeded +3ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +386ms
  pw:api => page.goto started +3ms
  pw:api navigating to "http://localhost:3000/components/input-field/input-otp", waiting until "load" +3ms
  pw:api <= browserContext.newPage succeeded +370ms
  pw:api => page.goto started +4ms
  pw:api navigating to "http://localhost:3000/components/input-field/input-otp", waiting until "load" +2ms
  pw:api => browserContext.close started +29s
  pw:api <= page.goto failed +9ms
  pw:api <= browserContext.close succeeded +1ms
  pw:api => browserContext.close started +29s
  pw:api => browser.close started +1ms
  pw:api <= page.goto failed +12ms
  pw:api <= browserContext.close succeeded +1ms
  pw:api => browser.close started +1ms
  pw:api <= browser.close succeeded +21ms
  pw:api <= browser.close succeeded +14ms

  1) [chromium] › InputOtp.spec.ts:9:3 › inputs otp interaction test › inputs should change focus by tabbing

    Timeout of 30000ms exceeded in beforeEach hook.

      3 |
      4 | test.describe("inputs otp interaction test", () => {
    > 5 |   test.beforeEach(async ({ page }, testInfo) => {
        |        ^
      6 |     await page.goto('/components/input-field/input-otp');
      7 |   });
      8 |

        at /Users/mervynlimmhj/Projects/inputs/src/e2e/InputOtp.spec.ts:5:8

    page.goto: net::ERR_ABORTED; maybe frame was detached?
    =========================== logs ===========================
    navigating to "http://localhost:3000/components/input-field/input-otp", waiting until "load"
    ============================================================

      4 | test.describe("inputs otp interaction test", () => {
      5 |   test.beforeEach(async ({ page }, testInfo) => {
    > 6 |     await page.goto('/components/input-field/input-otp');
        |                ^
      7 |   });
      8 |
      9 |   test("inputs should change focus by tabbing", async ({ page }) => {

        at /Users/mervynlimmhj/Projects/inputs/src/e2e/InputOtp.spec.ts:6:16
        at FixtureRunner.resolveParametersAndRunFunction (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/fixtures.js:356:12)
        at TestInfoImpl._runAsStep (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/testInfo.js:201:22)
        at WorkerRunner._runEachHooksForSuites (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/workerRunner.js:607:9)
        at /Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/workerRunner.js:376:9
        at TestInfoImpl._runFn (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/testInfo.js:166:7)
        at /Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/workerRunner.js:344:26
        at TimeoutManager.runWithTimeout (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/timeoutManager.js:70:7)
        at TestInfoImpl._runWithTimeout (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/testInfo.js:154:26)
        at WorkerRunner._runTest (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/workerRunner.js:326:5)
        at WorkerRunner.runTestGroup (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/workerRunner.js:195:11)
        at process.<anonymous> (/Users/mervynlimmhj/Projects/inputs/node_modules/@playwright/test/lib/worker.js:94:5)

    Pending operations:
      - page.goto at src/e2e/InputOtp.spec.ts:6:16
```

Any guidance on what i'm doing wrong here would be much appreciated!

Many thanks,
Mervyn

**Comment by np-xavier** [comment]
See the [documentation here](https://playwright.dev/docs/test-advanced#launching-a-development-web-server-during-the-tests), I suspect you need to use the `url` configuration option as well as `baseUrl`. When `webServer.url` is set, it will wait for a 2xx response - currently the tests are executing before the application is ready, I think.

**Comment by MervLim** [comment]
I have tried using the ```url``` option but have gotten a different error.

```
Running 4 tests using 2 workers

[WebServer] Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

Error: Timed out waiting 60000ms from config.webServer.
```

**Comment by np-xavier** [comment]
> I have tried using the `url` option instead of the `port` option but have gotten a different error.
> 
> ```
> Running 4 tests using 2 workers
> 
> [WebServer] Browserslist: caniuse-lite is outdated. Please run:
>   npx browserslist@latest --update-db
>   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
> 
> Error: Timed out waiting 60000ms from config.webServer.
> ```

Can you verify that your entry `webServer.command: 'npm start'` is correct? I'm just wondering if `npm run start` might be better, although `npm start` should find the corresponding task in your `package.json`. At any rate you probably need to verify that Playwright has kicked off the server while the tests wait to hit the 60s timeout.

**Comment by dgozman** [comment]
I suspect that dev server is just slow to start. Using the `url` option should fix the issue where tests start before the dev server is ready. Increasing the timeout for web server should get rid of `Timed out waiting 60000ms from config.webServer`.

```js
const config: PlaywrightTestConfig = {
  webServer: {
    command: 'npm start',
    // Point to the url that returns 200 once dev server is ready.
    url: 'http://localhost:3000/',
    // Give it 120 seconds. Increase/decrease depending on your dev server speed.
    timeout: 120000,
    reuseExistingServer: !process.env.CI,
  },
  use: {
    baseURL: 'http://localhost:3000/',
  },
  // ...the rest of the options...
};
export default config;
```

Let us know if this helps.

**Comment by MervLim** [comment]
Thanks. Increasing the timeout for the web server solves the problem!
