### ISSUE TITLE
[BUG] ECONNRESET on github action

### ISSUE THREAD

**Issue by unional** [microsoft/playwright#14853]
**Context:**
- Playwright Version: 

UnhandledPromiseRejectionWarning: Error: Failed to download Chromium 102.0.5005.40 (playwright build v1005), caused by
.../node_modules/playwright install: Error: read ECONNRESET

- Operating System: ubuntu / github action
- Node.js version: 14

https://github.com/justland/just-web/runs/6875641036?check_suite_focus=true

Seems like some connection issue. GitHub Action is failing

**Comment by Shinigami92** [comment]
I as a Vite contributor can approve this

CI is also partially failing now as well https://github.com/vitejs/vite/runs/6875454608?check_suite_focus=true

Also locally I cannot install our deps anymore

![image](https://user-images.githubusercontent.com/7195563/173520862-64f44fc3-19eb-4def-be47-6b5152c1f506.png)

**Comment by KirProkopchik** [comment]
The same problem with bitbucket CI. 

[5/5] Building fresh packages...
error /opt/atlassian/pipelines/agent/build/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /opt/atlassian/pipelines/agent/build/node_modules/playwright
Output:
BEWARE: your OS is not officially supported by Playwright; downloading Ubuntu build as a fallback.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Downloading Chromium 102.0.5005.40 (playwright build v1005)...
Downloading Chromium 102.0.5005.40 (playwright build v1005)...
Downloading Chromium 102.0.5005.40 (playwright build v1005)...
/opt/atlassian/pipelines/agent/build/node_modules/playwright-core/lib/server/registry/index.js:652
      throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
            ^
Error: Failed to download Chromium 102.0.5005.40 (playwright build v1005), caused by
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
    at /opt/atlassian/pipelines/agent/build/node_modules/playwright-core/lib/server/registry/index.js:652:13
    at async Registry._downloadExecutable (/opt/atlassian/pipelines/agent/build/node_modules/playwright-core/lib/server/registry/index.js:651:5)
    at async Registry.install (/opt/atlassian/pipelines/agent/build/node_modules/playwright-core/lib/server/registry/index.js:626:9)
    at async installBrowsersForNpmInstall (/opt/atlassian/pipelines/agent/build/node_modules/playwright-core/lib/server/registry/index.js:819:3)
