### ISSUE TITLE
[Question] self signed certificate in certificate chain

### ISSUE THREAD

**Issue by boris-meerovich-sp** [microsoft/playwright#15001]
Hi,
I'm trying to install PlayWrite  and got the error:
Failed to install browsers
Error: Failed to download chromium v978106, caused by
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)

Looks like a problem in corporate certificates that can't allow downloading the code from the CDN. When I'm doing the same in my home network, the installation is completed successfully.
Looked at the [issue](https://github.com/microsoft/playwright/issues/4439), but the is not so much info about the solution.

Could you please explain the process of the installation download and maybe supply the exact URL from where the code is downloaded to try to solve it with our IT?

Thanks

**Comment by mxschmitt** [comment]
Did you set up proxy for playwright browser download?

See here for using a proxy when downloading the browsers: https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy

Seems like you need to trust your certificate on the OS level, then Node.js should pick it up.

**Comment by boris-meerovich-sp** [comment]
We don't have proxy defined.
Here's what I get from the debug:
2022-06-21T14:14:32.738Z pw:install downloading Chromium 102.0.5005.40 (playwright build v1005) - attempt #1
Downloading Chromium 102.0.5005.40 (playwright build v1005)...
2022-06-21T14:14:32.738Z pw:install running download:
2022-06-21T14:14:32.738Z pw:install -- from url: https://playwright.azureedge.net/builds/chromium/1005/chromium-win64.zip
2022-06-21T14:14:32.738Z pw:install -- to location: C:\Users\XXXXX\AppData\Local\Temp\playwright-download-chromium-win64-1005.zip
2022-06-21T14:14:32.994Z pw:install attempt #1 - ERROR: self signed certificate in certificate chain
2022-06-21T14:14:32.994Z pw:install FAILED installation Chromium 102.0.5005.40 (playwright build v1005) with error: Error: self signed certificate in certificate chain
Failed to install browsers
Error: Failed to download Chromium 102.0.5005.40 (playwright build v1005), caused by
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:34)
    at TLSSocket.emit (events.js:376:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)


When I try to download the file (https://playwright.azureedge.net/builds/chromium/1005/chromium-win64.zip) in the browser, it works OK.

**Comment by mxschmitt** [comment]
seems like your company is intercepting the traffic, so you need to set the custom certificate via env vars:

`NODE_EXTRA_CA_CERTS=./ssl/mitn.pem npx playwright install`

Either set this env var on the user env settings or when executing the Playwright install command. It works in your browser, because they probably inject it there via GPO policies.


See here: https://nodejs.org/api/cli.html#node_extra_ca_certsfile

**Comment by boris-meerovich-sp** [comment]
Will check with IT what certificate we should use

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by lumtzerm** [comment]
Adding 

> `NODE_EXTRA_CA_CERTS=company/custom/certificate`

to env variables helped me with same error (Error: self signed certificate in certificate chain) for Playwright/Java combo.
