### ISSUE TITLE
[Question] command npm init ...  fails with EPROTO 13768:error:1408F10B:SSL routines:ssl3_get_record:wrong version 

### ISSUE THREAD

**Issue by surfmuggle** [microsoft/playwright#15176]
On Windows 10.0.19042 with node@v14.16.0 and npm@6.14.11 the command `npm init playwright@latest new-project`  resulted in 

`error request to https://registry.npmjs.org/create-playwright failed, reason: write EPROTO 13768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:`

 - The path `c:\ws\deps\openssl\...` does not exist. 
 - On another PC with Windows 10.0.19042 the command `npm init playwright@latest new-project` works without any problems

Has anyone an idea what to do to fix the error?

Below is the content of the log file

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-playwright@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\<user-id>\\AppData\\Roaming\\npm-cache\\_npx\\18124',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose npm-session 5585fb5649b3e7a8
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for create-playwright@latest request to https://registry.npmjs.org/create-playwright failed, reason: write EPROTO 13768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 171ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npmjs.org/create-playwright failed, reason: write EPROTO 13768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
11 verbose stack
11 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:315:20)
11 verbose stack     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:101:9)
11 verbose stack     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:123:5)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
12 verbose cwd C:\Users\VWSNUXP\playtest
13 verbose Windows_NT 10.0.19042
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "create-playwright@latest" "--global" "--prefix" "C:\\Users\\<user-id>\\AppData\\Roaming\\npm-cache\\_npx\\18124" "--loglevel" "error" "--json"
15 verbose node v14.16.0
16 verbose npm  v6.14.11
17 error code EPROTO
18 error errno EPROTO
19 error request to https://registry.npmjs.org/create-playwright failed, reason: write EPROTO 13768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:
20 verbose exit [ 1, true ]
```

**Comment by surfmuggle** [comment]
Good idea. I wrote to my co-worker to test this and will get back to you.

**Comment by rwoll** [comment]
Sounds good—I will close this for now, but when you have more information if it still looks like an issue with Playwright itself, please re-open and include the additional info.

Cheers!

**Comment by surfmuggle** [comment]
The cause is most likely trouble with using npm behind a proxy and ssl-certificate errors. My co-worker used a workaround to solve this problem. For anyone running into something similar this thread [How to fix SSL certificate error when running Npm on Windows?](https://stackoverflow.com/questions/13913941/) on stackoverflow might be usefull
