### ISSUE TITLE
[BUG] Mac M1, Macos Monterey 12.4, Node 18.4, Playwright 1.23.0 CRASHES with unclear logs

### ISSUE THREAD

**Issue by PoiraudVictor** [microsoft/playwright#15218]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Macos Monterey 12.4
- Node.js version: 18.4
- Browser: Chromium/Chrome
- Extra: Mac M1

Hi everyone, shot out to the playwright team for its amazing job. Been using the techno for quite a while now and never had anay major issue like this one. Keep going guys. 

Launching playwright with proxy connection in headless mode crashes : 

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserContext.close: Browser closed.
==================== Browser output: ====================
<launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/80/qsp1h6r10zs8wntby_2h9vph0000gn/T/playwright_chromiumdev_profile-LlZeWb --remote-debugging-pipe --no-startup-window
<launched> pid=8945
[pid=8945][err] objc[8950]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x215d3b808) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/103.0.5060.53/Libraries/libGLESv2.dylib (0x105ff93f8). One of the two will be used. Which one is undefined.
[pid=8945][err] [0629/112028.120519:WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 3
[pid=8945][err] [0629/112028.121270:WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 5
[pid=8945][err] [0629/112028.121281:WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 1
[pid=8945][err] [0629/112028.121287:WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 7
[pid=8945] <gracefully close start>
```

I also encoutered this bug :

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserContext.close: Browser closed.
==================== Browser output: ====================
<launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/80/qsp1h6r10zs8wntby_2h9vph0000gn/T/playwright_chromiumdev_profile-lEaYuR --remote-debugging-pipe --no-startup-window
<launched> pid=1246
[pid=1246][err] objc[1250]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x227c7f808) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/103.0.5060.53/Libraries/libGLESv2.dylib (0x10a6cd3f8). One of the two will be used. Which one is undefined.
[pid=1246][err] [0629/115120.055454:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.055544:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.055711:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.056299:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.056341:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.056453:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.057486:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.057637:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.057772:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246][err] [0629/115120.057998:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[pid=1246] <gracefully close start>
```
Although it at least does not crash right away without headless mode activated, it does so on `page.goto()` by hitting the following url : `chrome-error://chromewebdata/`

Some help would be greatly appriciated 🙏 

Thanks in advance

**Comment by dimkin-eu** [comment]
Just for a note - the 18th node is not _Active_ LTS yet, so 16th is the way so far ( we have some more issues, not connected to PW with the 18th Node)

**Comment by PoiraudVictor** [comment]
It did not fix the bug

**Comment by rwoll** [comment]
Hi, @PoiraudVictor! I created a repository with my attempted reproduction: https://github.com/rwoll/playwright-repro-proxy-issue-15218. However, I was unable to observe a crash. All the tests complete successfully.

Can you run that repo and let me know if it crashes for you in the same way you originally reported, or let me know how to modify it so it does exhibit the same crash behavior?

NB: Since you were still seeing the crash on Node v16 (https://github.com/microsoft/playwright/issues/15218#issuecomment-1170258306), I made my attempt with that same Node version. It was also done on an M1 that matches the OS version you reported. Since I see a path to `/Applications/…Google Chrome` in your error, I'm assuming you are using the `chrome` channel in your test (as opposed to just chromium). Is that correct? 

Thanks!

**Comment by PoiraudVictor** [comment]
Hi @rwoll, Thanks a lot for your answer, I will run your repo and try to twick it so the error pops up. Keep you updated on that. 

Indeed I am runing with chrome channel.

**Comment by PoiraudVictor** [comment]
I have cloned the repo, however I see that u use `@playwright/test`, I am using the `playwright` package instead, maybe it is more error prone... let me know

**Comment by PoiraudVictor** [comment]
I have run your program with my own http proxy settings. It seems to work inconsistently, sometimes pass, sometime the headless test fails with the following error :

```
 vpd@Victors-MacBook-Pro  /Tests/playwright-repro-proxy-issue-15218  npx playwright test

Running 2 tests using 2 workers

  ✓  [headless] › tests/example.spec.ts:3:1 › should work (1s)
  ✘  [headfull] › tests/example.spec.ts:3:1 › should work (30s)


  1) [headfull] › tests/example.spec.ts:3:1 › should work ==========================================

    Timeout of 30000ms exceeded.

    page.goto: net::ERR_ABORTED; maybe frame was detached?
    =========================== logs ===========================
    navigating to "https://example.com/", waiting until "load"
    ============================================================

      2 |
      3 | test('should work', async ({ page }) => {
    > 4 |   await page.goto('https://example.com');
        |              ^
      5 |   await expect(page.locator('body')).toContainText('This domain is for use in');
      6 | });
      7 |

        at /Users/vpd/Desktop/SAHAR/Codebase/Tests/playwright-repro-proxy-issue-15218/tests/example.spec.ts:4:14

    Pending operations:
      - page.goto at tests/example.spec.ts:4:14


  Slow test file: [headfull] › tests/example.spec.ts (30s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [headfull] › tests/example.spec.ts:3:1 › should work ===========================================
  1 passed (30s)
```

**Comment by PoiraudVictor** [comment]
I will try to use `@playwright/test` instead of `playwright` now and see if it goes well.

**Comment by PoiraudVictor** [comment]
Just tried it, and it still fails with the same errors...

**Comment by rwoll** [comment]
> I have cloned the repo, however I see that u use @playwright/test, I am using the playwright package instead, maybe it is more error prone... let me know

@playwright/test wraps the library and code in playwright-core, so for this case that shouldn't matter.

> I have run your program with my own http proxy settings. It seems to work inconsistently, sometimes pass, sometime the headless test fails with the following error :

Since it works with the known-working Proxy (I did a `--repeat-each 500`), but only breaks when using your proxy, it sounds like the proxy you're using might be flaky or broken.

I suggest looking at the the logs of the proxy you are using or debugging within the proxy itself. If everything looks good there, then feel free to re-open this issue and provide a cloneable repo that exhibits the failure in the same way you're seeing (including details on the proxy you are using).

Some 3rd-party proxies rate-limit requests, so you might just be hitting that. In that case, you could try running a smaller worker count with Playwright so you run less tests at once to prevent overwhelming the 3rd party proxy.

Thanks!
