### ISSUE TITLE
[BUG] ffmpeg-linux executable doesn't exist

### ISSUE THREAD

**Issue by OLibutzki** [microsoft/playwright#15265]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows (using Docker Desktop)
- Java version: 17
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: I use the Docker image browserless/chrome:1.53.0-chrome-stable. I do **not** connect via cdp but use the browserless playwright endpoint, see https://docs.browserless.io/docs/playwright.html

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
try ( Playwright playwright = Playwright.create( ) ) {
  final Browser browser = playwright.chromium( ).connect( "ws://" + chromeContainer.getHost( ) + ":" + chromeContainer.getFirstMappedPort( ) + "/playwright" );
  final String baseUrl = String.format( "http://%s:%s", hostname, port );
  try (BrowserContext browserContext = browser.newContext( new Browser.NewContextOptions( ).setRecordVideoDir( screenshotAndVideoPath ) );
  Page page = browserContext.newPage( ) ) {
    [...]
  }
}
```

**Describe the bug**

Without setting the recordvideodir the test passes, but whenever I try to record a video, I run into this error:
```
com.microsoft.playwright.PlaywrightException: Error {
  message='Executable doesn't exist at /usr/src/app/ffmpeg-1007/ffmpeg-linux
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
  name='Error
  stack='Error: Executable doesn't exist at /usr/src/app/ffmpeg-1007/ffmpeg-linux
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at executablePathOrDie (/usr/src/app/node_modules/playwright-core/lib/server/registry/index.js:297:15)
    at Object.executablePathOrDie (/usr/src/app/node_modules/playwright-core/lib/server/registry/index.js:484:43)
    at FrameSession._createVideoRecorder (/usr/src/app/node_modules/playwright-core/lib/server/chromium/crPage.js:1008:68)
    at FrameSession._initialize (/usr/src/app/node_modules/playwright-core/lib/server/chromium/crPage.js:511:18)
    at async CRBrowserContext.newPage (/usr/src/app/node_modules/playwright-core/lib/server/browserContext.js:366:25)
    at async BrowserContextDispatcher.newPage (/usr/src/app/node_modules/playwright-core/lib/server/dispatchers/browserContextDispatcher.js:179:47)
    at async DispatcherConnection.dispatch (/usr/src/app/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:352:22)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:105)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:90)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPageImpl(BrowserContextImpl.java:323)
	at com.microsoft.playwright.impl.BrowserContextImpl.lambda$newPage$12(BrowserContextImpl.java:316)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPage(BrowserContextImpl.java:316)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPage(BrowserContextImpl.java:44)
	at de.libutzki.mailsender.integration.Stage_08_MailSenderApplicationIntegrationTest.testApplication(Stage_08_MailSenderApplicationIntegrationTest.java:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Executable doesn't exist at /usr/src/app/ffmpeg-1007/ffmpeg-linux
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
  name='Error
  stack='Error: Executable doesn't exist at /usr/src/app/ffmpeg-1007/ffmpeg-linux
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at executablePathOrDie (/usr/src/app/node_modules/playwright-core/lib/server/registry/index.js:297:15)
    at Object.executablePathOrDie (/usr/src/app/node_modules/playwright-core/lib/server/registry/index.js:484:43)
    at FrameSession._createVideoRecorder (/usr/src/app/node_modules/playwright-core/lib/server/chromium/crPage.js:1008:68)
    at FrameSession._initialize (/usr/src/app/node_modules/playwright-core/lib/server/chromium/crPage.js:511:18)
    at async CRBrowserContext.newPage (/usr/src/app/node_modules/playwright-core/lib/server/browserContext.js:366:25)
    at async BrowserContextDispatcher.newPage (/usr/src/app/node_modules/playwright-core/lib/server/dispatchers/browserContextDispatcher.js:179:47)
    at async DispatcherConnection.dispatch (/usr/src/app/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:352:22)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:183)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:163)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
	... 79 more
```

**Comment by mxschmitt** [comment]
You need to install ffmpeg when recording, you can do it in Java like this:

`mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install ffmpeg"`

or all the browers:

`mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"`

but you don't need them if you connect to it remotely.

**Comment by OLibutzki** [comment]
The issue is: I do not need ffmpeg locally... ffmpeg needs to be available in the container which provides the browser... in this case it's _browserless/chrome:1.53.0-chrome-stable_.

I looked into the running _browserless/chrome:1.53.0-chrome-stable_ container and an ffmpeg binary is available, but it's not located in the path _/usr/src/app/ffmpeg-1007/ffmpeg-linux_.

Interesting fact: By connecting over CDP with the same docker image recoding videos works...
Maybe this is a browserless issue... I am not sure, to be honest.

**Comment by mxschmitt** [comment]
You are right, if you connect via browserless, ffmpeg needs to be available on their side.

> I looked into the running browserless/chrome:1.53.0-chrome-stable container and an ffmpeg binary is available, but it's not located in the path /usr/src/app/ffmpeg-1007/ffmpeg-linux.

It needs to be under the given location, so when they build the images, they need to install chromium + ffmpeg via the Playwright CLI.

**Comment by OLibutzki** [comment]
`It needs to be under the given location, so when they build the images, they need to install chromium + ffmpeg via the Playwright CLI.`

I see... and when I connect over CDP it does not have to be under this location?

**Comment by rwoll** [comment]
> I see... and if I connect over CDP it does not have to be under this location?

If using `connectOverCDP`, ffmpeg needs to be installed on the machine calling `connectOverCDP` at the location `npx playwright install ffmpeg` installs it to. 

In your case (at some level of absrtaction), things look sort of like:

| | |
| - | - |
| connectOverCDP | <img width="1227" alt="Screen Shot 2022-07-02 at 1 13 58 AM" src="https://user-images.githubusercontent.com/11915034/176992660-54b2e8f7-ee27-486d-bf7e-5c05aadc07c8.png"> |
| connect | <img width="1263" alt="Screen Shot 2022-07-02 at 1 14 27 AM" src="https://user-images.githubusercontent.com/11915034/176992651-f596a26d-d2cb-4f25-8b96-3f4e73600816.png"> |






```js
// @ts-check
const playwright = require('playwright-core');

(async () => {
  const browser = await playwright.chromium.connectOverCDP('ws://browserless:3000/'); // ⚠️ NB: connectOverCDP v. connect
  const context = await browser.newContext({ recordVideo: { dir: './examples' } });
  const page = await context.newPage();
  await page.goto('https://example.com');
  await page.close();
  await page.video()?.saveAs('example.webm');
  await context.close();
  await browser.close();
})()
```

- [`browserType.connect`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-connect) is different from [`browserType.connectOverCDP`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-connect-over-cdp)
- `browserType.connectOverCDP` is used to connect to a remote **_Chromium_** CDP Session/Endpoint. In this case, Playwright (nor its ffmpeg binary) don't even need to be installed in the **Docker** container, but Playwright (including ffmpeg) **MUST** be installed on your **Laptop**. Your Laptop will talk Chromium CDP to the Docker container, and the Playwright Client (and Playwright Server) will both be running directly on your **Laptop**. The Playwright Server is what's doing the `ffmpeg` processing.
- `browserType.connect` is used to connect to a remote **_Playwright_** Server launched via [`browserType.launchServer`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch-server). Your Laptop would be talking the Playwright protocol to the Playwright Server running in Docker, and then within the container the Playwright Server would be talking CDP to the Browser. The Playwright Server would use ffmpeg on the Server/Docker container.

Once you make the following change:

```diff
- const browser = await playwright.chromium.connectOverCDP('ws://browserless:3000/'); // ⚠️ NB: connectOverCDP v. connect
+ const browser = await playwright.chromium.connect('ws://browserless:3000/playwright');
```

ffmpeg needs to be installed in the Docker container. It looks like the Browserless container is missing Playwright's ffmpeg install, but if you build an image from the following Dockerfile:

```dockerfile
FROM browserless/chrome:1.53.0-chrome-stable
RUN npx playwright install ffmpeg
```

and then run it:

```
docker build -t patched-container .
docker run -it --rm -p 3000:3000 patched-container
```

video will work with:

```
await playwright.chromium.connect('ws://browserless:3000/playwright');
```

Let me know if this explains things!

Closing since patching the Browserless Dockerfile/container fixes the original reported issue, and you have filed a bug with them, but feel free to re-open or comment if you have additional questions or follow up is needed. Thanks!

**Comment by OLibutzki** [comment]
Hi @rwoll,

thanks a lot for this detailed explanation. I highly appreciate your efforts.

Maybe you could add this explanation on the Playwright website, because at least for me it was very helpful.

**Comment by rwoll** [comment]
Thanks! Marking as 1.25 so I take some time to add a few more details to the diagram and document either in our repo or the official docs.
