### ISSUE TITLE
[BUG] Switch back and forth between contexts and opening new pages results in an error

### ISSUE THREAD

**Issue by dhavalpowar** [microsoft/playwright#15331]
**Context:** The test run errors out when I switch back and forth between multiple `BrowserContext`s, NOT browser tabs/pages. In essence, I need to do some operations in one `BrowserContext`, then do some operation on the next `BrowserContext`, and THEN GET BACK to do operations on the **initial**  `BrowserContext`. This errors out. A good analogy is a chat app where 2 users communicate in different contexts. 
One caveat although - it works if the we complete ALL operations on one `BrowserContext` BEFORE moving onto another `BrowserContext`.

- Playwright Version: 1.23.1
- Operating System: Mac
- Node.js version: v14.15.4
- Browser: All
- Extra: N/A

**Code Snippet**
SCENARIO 1 - NOT WORKING
```typescript
import { test, expect, type Page } from '@playwright/test';

test('testing my tests', async ({ page, browser, }) => {

  const c1 = await browser.newContext();
  const c2 = await browser.newContext();

  const c1_p1 = await c1.newPage();
  c1_p1.goto('https://www.gmail.com');
  // Do something

  const c2_p1 = await c2.newPage();
  await c2_p1.goto('http://www.ebay.com');
  // Do something

  const c1_p2 = await c1.newPage();
  c1_p2.goto('https://www.gmail.com'); // <------ ERRORS OUT
  // Do something

});
```
```bash
➜ npx playwright test --project=chromium --headed

Running 1 test using 1 worker

  ✘  [chromium] › example.spec.ts:16:3 › default › testing my tests (4s)


  1) [chromium] › example.spec.ts:16:3 › default › testing my tests ==========================

    page.goto: net::ERR_ABORTED; maybe frame was detached?
    =========================== logs ===========================
    navigating to "https://www.gmail.com/", waiting until "load"
    ============================================================

      15 |
      16 |     const c1_p2 = await c1.newPage();
    > 17 |     c1_p2.goto('https://www.gmail.com');
         |           ^
      18 |

        at pw-tests/example.spec.ts:17:11
        at node_modules/@playwright/test/lib/workerRunner.js:388:9
        at TestInfoImpl._runFn (node_modules/@playwright/test/lib/testInfo.js:166:7)
        at node_modules/@playwright/test/lib/workerRunner.js:344:26
        at TimeoutManager.runWithTimeout (node_modules/@playwright/test/lib/timeoutManager.js:70:7)
        at TestInfoImpl._runWithTimeout (node_modules/@playwright/test/lib/testInfo.js:154:26)
        at WorkerRunner._runTest (node_modules/@playwright/test/lib/workerRunner.js:326:5)
        at WorkerRunner.runTestGroup (node_modules/@playwright/test/lib/workerRunner.js:195:11)
        at process.<anonymous> (node_modules/@playwright/test/lib/worker.js:87:5)


  1 failed
    [chromium] › example.spec.ts:3:3 › default › testing my tests ===========================
```

**Describe the bug**
Steps to reproduce:
1. Create new context c1
2. Create new context c2
3. Create new page c1_p1 on context c1 (do something)
4. Create new page c2_p1 on context c2 (do something)
5. Create new page c1_p2 on context 1 <------ ERRORS OUT

Although it works if we move onto context c2 after completing "all" activities on context c1  ie.
1. Create new context c1
2. Create new context c2
3. Create new page c1_p1 on context c1 (do something)
4. Create new page c1_p2 on context c1 <----- WORKS
5. Create new page c2_p1 on context c2 (do something)
6. Create new page c2_p2 on context c2 (do something)  <------ WORKS

Add any other details about the problem here.
SCENARIO 2 - WORKING
```typescript
import { test, expect, type Page } from '@playwright/test';

test('testing my tests', async ({ page, browser, }) => {

  const c1 = await browser.newContext();
  const c2 = await browser.newContext();

  const c1_p1 = await c1.newPage();
  c1_p1.goto('https://www.gmail.com');
  // Do something

  const c1_p2 = await c1.newPage();
  c1_p2.goto('https://www.amazon.com');
  // Do something

  const c2_p1 = await c2.newPage();
  await c2_p1.goto('http://www.ebay.com');
  // Do something
});
```
```bash
➜  npx playwright test --project=chromium --headed -g @prod

Running 1 test using 1 worker

  ✓  [chromium] › example.spec.ts:16:3 › default › testing my tests (3s)


  1 passed (4s)
```

**Can the team verify if this is a known bug or am I using it incorrectly?**

**Comment by aslushnikov** [comment]
@dhavalpowar you should await your navigations - otherwise test finishes too early, and closes pages. In other words, make sure to await all your promises before finishing test!
