### ISSUE TITLE
[BUG] Unhandled promise Rejection: Error: Assertion error

### ISSUE THREAD

**Issue by Mosorathia** [microsoft/playwright#15414]
**Context:**
- Playwright Version: [1.17]
- Operating System: [Windows, Linux]
- Java 8
- Browser: [Chrome version - 103.0.5060.114]

```
Playwright playwright = Playwright.create();
BrowserType browserType = playwright.chromium();
BrowserContext browser = browserType.launchPersistentContext(Paths.get(new CommonMethods().getBrowserPropData("path")), new BrowserType.LaunchPersistentContextOptions().setChannel("chrome").setHeadless(false));
Page page = browser.newPage();
page.navigate("https://www.youtube.com/");
page.close();
browser.close();
```

```

**Getting Unhandled promise Rejection warning when closing the browser.. It was working fine before, but getting an error now**

The error does not occur when i remove page.close(), browser.close() and playwright.close().

Entire error log : 
```
(node:183) UnhandledPromiseRejectionWarning: Error: Assertion error
    at assert (/tmp/playwright-java-13385046620369138077/package/lib/utils/utils.js:347:21)
    at CRSession._onMessage (/tmp/playwright-java-13385046620369138077/package/lib/server/chromium/crConnection.js:222:25)
    at CRConnection._onMessage (/tmp/playwright-java-13385046620369138077/package/lib/server/chromium/crConnection.js:113:26)
    at Immediate.<anonymous> (/tmp/playwright-java-13385046620369138077/package/lib/server/pipeTransport.js:71:42)
    at processImmediate (internal/timers.js:464:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@Mosorathia could you please try with a newer playwright version and see if it works?

**Comment by Mosorathia** [comment]
Thanks, the error is gone when updated to playwright 1.22.0
