### ISSUE TITLE
[BUG] Tests wont run due to reentrant plugin error from babel

### ISSUE THREAD

**Issue by MakingStuffs** [microsoft/playwright#15701]
**Context:**
- Playwright Version: 1.25.0-next
- Operating System: macOS
- Node.js version: 14.17.6
- Npm version: 8.14.0

**Code Snippet**
```
Error: [BABEL]: Reentrant plugin detected trying to load "/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/tsxTransform.js". This module is not ignored and is trying to load itself while compiling itself, leading to a dependency cycle. We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore. (While processing: /Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/tsxTransform.js)
at transformHook (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/transform.js:212:11)
    at _utilsBundle.pirates.addHook.exts (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/transform.js:233:12)
    at Module.A._compile (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/utilsBundleImpl.js:16:936)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.t.<computed>.tu._extensions.<computed> (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/utilsBundleImpl.js:16:1010)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Loader._requireOrImport (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/loader.js:294:14)
    at Loader._requireOrImportDefaultObject (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/loader.js:308:29)
    at Loader.loadConfigFile (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/loader.js:79:31)
    at Runner.loadConfigFromResolvedFile (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/runner.js:96:31)
    at runTests (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/cli.js:153:40)
    at Ai.<anonymous> (/Users/paul/Dev/git-repos/playwright-fork/packages/playwright-test/lib/cli.js:70:7)
```

**Describe the bug**

I tried to fork the repo and initially got errors related to the fact I was using an older version of npm [original question here](https://github.com/microsoft/playwright/issues/15641). I updated and the package now builds. 

However, when I run `npm run test` it gives the error above. I tried adding the specified file path to the ignore list in the babel config in the repo's root folder but it still exhibits the same behaviour. 

Is there something I am missing?

**Comment by yury-s** [comment]
Did you run `npm run watch` or `npm run build`? Also try a fresh checkout and see if the problem persists, if this is just a clone of our repo it should build with no errors (we run the tests all the time on CI and locally).

**Comment by MakingStuffs** [comment]
> Did you run `npm run watch` or `npm run build`? Also try a fresh checkout and see if the problem persists, if this is just a clone of our repo it should build with no errors (we run the tests all the time on CI and locally).

Hi mate, sorry for wasting your time I think this one was because my node version was `14.18.x` and I saw that some of the deps are requiring node `14.20.x` I upgraded node and it now seems as though the tests are actually running etc.

Thank you so much for your patience and regular replies it means a lot.
