### ISSUE TITLE
[BUG] Firefox crash on MacOS

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#15818]
Possibly related to the recent ff init changes?

Reproduces locally with M1:

```bash
  PWTEST_DEBUG=1 DEBUG=pw:browser* npm run ftest -- --headed cli-codegen-2:540 --repeat-each=100 -x
```

Logs:
```log
  pw:browser <launching> /Users/dgozman/Library/Caches/ms-playwright/firefox-1335/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -wait-for-browser -foreground -profile /var/folders/jt/h6fjjh8n74nbgmm0rljrdgq00000gn/T/playwright_firefoxdev_profile-s8GGpF -juggler-pipe -silent +0ms
  pw:browser <launched> pid=47687 +22ms
  pw:browser [pid=47687][err] 2022-07-20 13:22:14.207 plugin-container[47799:9702441] nil host used in call to allowsSpecificHTTPSCertificateForHost +2s
  pw:browser [pid=47687][err] 2022-07-20 13:22:14.212 plugin-container[47799:9702441] nil host used in call to allowsAnyHTTPSCertificateForHost: +0ms
  pw:browser [pid=47687][err] 2022-07-20 13:22:14.253 plugin-container[47799:9702441] nil host used in call to allowsSpecificHTTPSCertificateForHost +40ms
  pw:browser [pid=47687][err] 2022-07-20 13:22:14.253 plugin-container[47799:9702441] nil host used in call to allowsAnyHTTPSCertificateForHost: +0ms
  pw:browser [pid=47687][err] 2022-07-20 13:22:14.255 plugin-container[47799:9702578] nil host used in call to allowsSpecificHTTPSCertificateForHost +2ms
  pw:browser [pid=47687][err] 2022-07-20 13:22:14.255 plugin-container[47799:9702578] nil host used in call to allowsAnyHTTPSCertificateForHost: +0ms
  pw:browser [pid=47687][out]  +195ms
  pw:browser [pid=47687][out] Juggler listening to the pipe +0ms
  pw:browser [pid=47687][err] UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable +2s
  pw:browser [pid=47687][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /var/folders/jt/h6fjjh8n74nbgmm0rljrdgq00000gn/T/playwright_firefoxdev_profile-s8GGpF/search.json.mozlz4", (void 0))) +113ms
  pw:browser [pid=47687][out] console.error: SearchEngineSelector: "Received empty search configuration!" +22ms
  pw:browser [pid=47687][out] console.error: SearchEngineSelector: "Received empty search configuration!" +29ms
  pw:browser [pid=47687][out] console.error: SearchService: "_init: failure initializing search:" ({}) +0ms
  pw:browser [pid=47687][err] Exiting due to channel error. +29ms
  pw:browser [pid=47687][err] Exiting due to channel error. +37ms
  pw:browser [pid=47687][out] Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=0.708333)  +47ms
  pw:browser [pid=47687] <process did exit: exitCode=null, signal=SIGSEGV> +1ms
  pw:browser [pid=47687] starting temporary directories cleanup +0ms
```

**Comment by aslushnikov** [comment]
Debug build trace:

```
Thread 0:: MainThread Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1b6000834 __ulock_wait + 8
1   libsystem_pthread.dylib       	       0x1b603e5a0 _pthread_join + 444
2   XUL                           	       0x11888c9a0 rtc::PlatformThread::Stop() + 64 (platform_thread.cc:123)
3   XUL                           	       0x116bf67c4 webrtc::DesktopCaptureImpl::StopCapture() + 20 (desktop_capture_impl.cc:633) [inlined]
4   XUL                           	       0x116bf67c4 non-virtual thunk to webrtc::DesktopCaptureImpl::StopCapture() + 64
5   XUL                           	       0x118fd2958 mozilla::nsScreencastService::Session::Stop() + 256 (nsScreencastService.cpp:126)
6   XUL                           	       0x118fd2784 mozilla::nsScreencastService::StopVideoRecording(nsTSubstring<char16_t> const&) + 204 (nsScreencastService.cpp:351)
7   XUL                           	       0x113a9beb0 _NS_InvokeByIndex + 96 (xptcinvoke_asm_aarch64.S:74)
8   XUL                           	       0x1144a8f50 CallMethodHelper::Invoke() + 20 (XPCWrappedNative.cpp:1626) [inlined]
9   XUL                           	       0x1144a8f50 CallMethodHelper::Call() + 868 (XPCWrappedNative.cpp:1179)
10  XUL                           	       0x1144a8af8 XPCWrappedNative::CallMethod(XPCCallContext&, XPCWrappedNative::CallMode) + 208 (XPCWrappedNative.cpp:1125)
11  XUL                           	       0x1144aaa18 XPC_WN_CallMethod(JSContext*, unsigned int, JS::Value*) + 728 (XPCWrappedNativeJSOps.cpp:963)
12  XUL                           	       0x1190969c4 CallJSNative(JSContext*, bool (*)(JSContext*, unsigned int, JS::Value*), js::CallReason, JS::CallArgs const&) + 412 (Interpreter.cpp:420)
13  XUL                           	       0x1190961d8 js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) + 1032 (Interpreter.cpp:507)
14  XUL                           	       0x11908dab8 js::CallFromStack(JSContext*, JS::CallArgs const&) + 12 (Interpreter.cpp:578) [inlined]
15  XUL                           	       0x11908dab8 Interpret(JSContext*, js::RunState&) + 26704 (Interpreter.cpp:3314)
16  XUL                           	       0x119086e58 js::RunScript(JSContext*, js::RunState&) + 480 (Interpreter.cpp:389)
17  XUL                           	       0x1190960f4 js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) + 804 (Interpreter.cpp:539)
18  XUL                           	       0x1190975e0 js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>, js::CallReason) + 272 (Interpreter.cpp:605)
19  XUL                           	       0x11916ef6c JS_CallFunctionValue(JSContext*, JS::Handle<JSObject*>, JS::Handle<JS::Value>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>) + 528 (CallAndConstruct.cpp:53)
20  XUL                           	       0x1144a1780 nsXPCWrappedJS::CallMethod(unsigned short, nsXPTMethodInfo const*, nsXPTCMiniVariant*) + 3148 (XPCWrappedJSClass.cpp:981)
21  XUL                           	       0x113a9cc08 PrepareAndDispatch + 968 (xptcstubs_aarch64.cpp:190)
22  XUL                           	       0x113a9bf00 SharedStub + 64 (xptcstubs_asm_aarch64.S:47)
23  XUL                           	       0x118a0aa48 nsWindowMediator::UnregisterWindow(nsWindowInfo*) + 220 (nsWindowMediator.cpp:114)
24  XUL                           	       0x118a0b2a8 nsWindowMediator::UnregisterWindow(nsIAppWindow*) + 104 (nsWindowMediator.cpp:100)
25  XUL                           	       0x118a01a48 nsAppShellService::UnregisterTopLevelWindow(nsIAppWindow*) + 272 (nsAppShellService.cpp:909)
26  XUL                           	       0x1189ed2d4 mozilla::AppWindow::Destroy() + 452 (AppWindow.cpp:589)
27  XUL                           	       0x118a04b6c nsChromeTreeOwner::Destroy() + 12 (nsChromeTreeOwner.cpp:262) [inlined]
28  XUL                           	       0x118a04b6c non-virtual thunk to nsChromeTreeOwner::Destroy() + 20
29  XUL                           	       0x114c5aab4 nsGlobalWindowOuter::ReallyCloseWindow() + 160 (nsGlobalWindowOuter.cpp:6269)
30  XUL                           	       0x114c60c78 nsCloseEvent::Run() + 44 (nsGlobalWindowOuter.cpp:6070)
31  XUL                           	       0x113a77928 mozilla::RunnableTask::Run() + 36 (TaskController.cpp:475)
32  XUL                           	       0x113a52ca0 mozilla::TaskController::DoExecuteNextTaskOnlyMainThreadInternal(mozilla::detail::BaseAutoLock<mozilla::Mutex&> const&) + 1220 (TaskController.cpp:788)
33  XUL                           	       0x113a51bb8 mozilla::TaskController::ExecuteNextTaskOnlyMainThreadInternal(mozilla::detail::BaseAutoLock<mozilla::Mutex&> const&) + 64 (TaskController.cpp:620)
34  XUL                           	       0x113a51e64 mozilla::TaskController::ProcessPendingMTTask(bool) + 92 (TaskController.cpp:398)
35  XUL                           	       0x113a7c9ac mozilla::TaskController::InitializeInternal()::$_0::operator()() const + 20 (TaskController.cpp:124) [inlined]
36  XUL                           	       0x113a7c9ac mozilla::detail::RunnableFunction<mozilla::TaskController::InitializeInternal()::$_0>::Run() + 32 (nsThreadUtils.h:531)
37  XUL                           	       0x113a660a0 nsThread::ProcessNextEvent(bool, bool*) + 1396 (nsThread.cpp:1180)
38  XUL                           	       0x113a62dc4 NS_ProcessPendingEvents(nsIThread*, unsigned int) + 220 (nsThreadUtils.cpp:430)
39  XUL                           	       0x117901100 nsBaseAppShell::NativeEventCallback() + 140 (nsBaseAppShell.cpp:87)
40  XUL                           	       0x117972554 nsAppShell::ProcessGeckoEvents(void*) + 328 (nsAppShell.mm:508)
41  CoreFoundation                	       0x1b6109034 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
42  CoreFoundation                	       0x1b6108f80 __CFRunLoopDoSource0 + 208
43  CoreFoundation                	       0x1b6108c80 __CFRunLoopDoSources0 + 268
44  CoreFoundation                	       0x1b6107600 __CFRunLoopRun + 828
45  CoreFoundation                	       0x1b6106b24 CFRunLoopRunSpecific + 600
46  HIToolbox                     	       0x1bed3f338 RunCurrentEventLoopInMode + 292
47  HIToolbox                     	       0x1bed3f0b4 ReceiveNextEventCommon + 564
48  HIToolbox                     	       0x1bed3ee68 _BlockUntilNextEventMatchingListInModeWithFilter + 72
49  AppKit                        	       0x1b8c6d78c _DPSNextEvent + 860
50  AppKit                        	       0x1b8c6c084 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1328
51  XUL                           	       0x117971898 -[GeckoNSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 132 (nsAppShell.mm:174)
52  AppKit                        	       0x1b8c5e250 -[NSApplication run] + 596
53  XUL                           	       0x117972c94 nsAppShell::Run() + 380 (nsAppShell.mm:800)
54  XUL                           	       0x118e6a1fc nsAppStartup::Run() + 136 (nsAppStartup.cpp:295)
55  XUL                           	       0x118f74c38 XREMain::XRE_mainRun() + 3480 (nsAppRunner.cpp:5746)
56  XUL                           	       0x118f75cb4 XREMain::XRE_main(int, char**, mozilla::BootstrapConfig const&) + 1796 (nsAppRunner.cpp:5940)
57  XUL                           	       0x118f76444 XRE_main(int, char**, mozilla::BootstrapConfig const&) + 164 (nsAppRunner.cpp:6004)
58  firefox                       	       0x1021e1284 do_main(int, char**, char**) + 304 (nsBrowserApp.cpp:227) [inlined]
59  firefox                       	       0x1021e1284 main + 888 (nsBrowserApp.cpp:406)
60  dyld                          	       0x10228908c start + 520
```

**Comment by unlikelyzero** [comment]
FWIW, we're seeing this when running in headed mode. We don't have a reproducer yet and have opted to run within the focal container instead

**Comment by jhyot** [comment]
Seeing this with at least with headed mode (but not always reproducible), Playwright Java 1.22.0, M1 Pro Macbook, macOs 12.4

The crash log seems similar, but not exactly the same:
```
 name='Error
  stack='Error: Protocol error (Browser.removeBrowserContext): Browser closed.
==================== Browser output: ====================
<launching> /Users/jhyoetylae/Library/Caches/ms-playwright/firefox-1323/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -wait-for-browser -foreground -profile /var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright_firefoxdev_profile-OGPtpF -juggler-pipe --disable-dev-shm-usage -silent
<launched> pid=23762
[pid=23762][out] 
[pid=23762][out] Juggler listening to the pipe
[pid=23762][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright_firefoxdev_profile-OGPtpF/search.json.mozlz4", (void 0)))
[pid=23762][err] UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
[pid=23762][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=23762][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 752: TypeError: iStream.tell is not a function
[pid=23762][err] JavaScript error: chrome://juggler/content/NetworkObserver.js, line 752: TypeError: iStream.tell is not a function
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][out] ERROR: got a state changed event for un-tracked docshell!
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][out] ERROR: got a state changed event for un-tracked docshell!
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][out] ERROR: got a state changed event for un-tracked docshell!
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][out] ERROR: got a state changed event for un-tracked docshell!
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][err] JavaScript error: resource://gre/modules/pdfjs.js, line 31: NS_ERROR_FACTORY_NOT_REGISTERED: 
[pid=23762][out] ERROR: got a state changed event for un-tracked docshell!
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][out] console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "http://localhost:4200"
[pid=23762][err] Exiting due to channel error.
[pid=23762][err] Exiting due to channel error.
[pid=23762] <process did exit: exitCode=null, signal=SIGSEGV>
[pid=23762] starting temporary directories cleanup
    at /private/var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright-java-360399487801450024/package/lib/server/firefox/ffConnection.js:92:16
    at new Promise (<anonymous>)
    at FFConnection.send (/private/var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright-java-360399487801450024/package/lib/server/firefox/ffConnection.js:88:12)
    at FFBrowserContext.doClose (/private/var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright-java-360399487801450024/package/lib/server/firefox/ffBrowser.js:439:37)
    at FFBrowserContext.close (/private/var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright-java-360399487801450024/package/lib/server/browserContext.js:344:20)
    at async BrowserContextDispatcher.close (/private/var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright-java-360399487801450024/package/lib/server/dispatchers/browserContextDispatcher.js:248:5)
    at async DispatcherConnection.dispatch (/private/var/folders/l5/mt5xnj_14rn9j4lsnfs5n9b40000gn/T/playwright-java-360399487801450024/package/lib/server/dispatchers/dispatcher.js:352:22)
}
	at app//com.microsoft.playwright.impl.Connection.dispatch(Connection.java:183)
	at app//com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:163)
	at app//com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
```

**Comment by yury-s** [comment]
Latest roll should include the fix.
