### ISSUE TITLE
[Question] Unable to run api testing in dotnet 

### ISSUE THREAD

**Issue by shivshankar93** [microsoft/playwright#15873]
I copied the complete code from the below page but am unable to run the test, I am knew to both C# and Playwright. 
https://playwright.dev/dotnet/docs/api-testing#complete-test-example

The 1st problem I face is that there is no main method to start the program
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	PlaywrightNew	C:\Users\suress\source\repos\PlaywrightNew\PlaywrightNew\CSC	1	Active

I created a class and added a new main method created an object of the TestGitHubAPI  class and then called the SetUpAPITesting()
I get an error where the Playwright object on this is null
Request = await this.Playwright.APIRequest.NewContextAsync

How do I instantiate and use the test apis.

**Comment by shivshankar93** [comment]
Microsoft.Playwright.PlaywrightException
  HResult=0x80131500
  Message=Driver not found: C:\Users\suress\source\repos\PlaywrightNew\PlaywrightNew\.playwright\node\win32_x64\playwright.cmd
  Source=Microsoft.Playwright
  StackTrace:
   at Microsoft.Playwright.Helpers.Driver.GetExecutablePath() in /_/src/Playwright/Helpers/Driver.cs:line 57
   at Microsoft.Playwright.Transport.StdIOTransport.GetProcess() in /_/src/Playwright/Transport/StdIOTransport.cs:line 119
   at Microsoft.Playwright.Transport.StdIOTransport..ctor() in /_/src/Playwright/Transport/StdIOTransport.cs:line 44
   at Microsoft.Playwright.Playwright.<CreateAsync>d__0.MoveNext() in /_/src/Playwright/Playwright.cs:line 44
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Playwright.NUnit.PlaywrightTest.<PlaywrightSetup>d__11.MoveNext() in /_/src/Playwright.NUnit/PlaywrightTest.cs:line 43
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Playwright.TestingHarnessTest.NUnit.TestGitHubAPI.<Main>d__11.MoveNext() in C:\Users\suress\source\repos\PlaywrightNew\PlaywrightNew\Program.cs:line 127

  This exception was originally thrown at this call stack:
    [External Code]
    Playwright.TestingHarnessTest.NUnit.TestGitHubAPI.Main() in Program.cs
