### ISSUE TITLE
[BUG] "Unable to retrieve content because the page is navigating and changing the content." after reload() and content() in sequence

### ISSUE THREAD

**Issue by Mattwmaster58** [microsoft/playwright#16108]
**Context:**
- Playwright Version: 1.24.0 (also observed in 1.21)
- Operating System: Windows, Debian
- Python version: 3.8
- Browser: only Chrome based (both chromium and chrome)
- Extra: does not occur with `reload(wait_until="networkidle")`

**Code Snippet**

```python
import asyncio

from playwright.async_api import async_playwright

async def mvp():
    TRIGGER_URL = "http://www.vs-sm.de/ "
    async with async_playwright() as p:
        b = await p.chromium.launch()

        page = await b.new_page()
        await page.goto(TRIGGER_URL, timeout=30000)
        await page.reload(wait_until="networkidle")
        await page.content()
        print("wait_until=\"networkidle\" works")

        await page.goto(TRIGGER_URL, timeout=30000)
        await page.reload()
        await page.content()


asyncio.run(mvp())
```

**Describe the bug**

```
Traceback (most recent call last):
  File "C:/Users/Matt Marcus/AppData/Roaming/JetBrains/PyCharm2022.2/scratches/scratch_71.py", line 21, in <module>
    asyncio.run(mvp())
  File "C:\Program Files\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "/AppData/Roaming/JetBrains/PyCharm2022.2/scratches/scratch_71.py", line 18, in mvp
    await page.content()
  File "venv\lib\site-packages\playwright\async_api\_generated.py", line 7180, in content
    return mapping.from_maybe_impl(await self._impl_obj.content())
  File "venv\lib\site-packages\playwright\_impl\_page.py", line 479, in content
    return await self._main_frame.content()
  File "venv\lib\site-packages\playwright\_impl\_frame.py", line 400, in content
    return await self._channel.send("content")
  File "venv\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Matt Marcus\Documents\Projects\gdprscan\venv\lib\site-packages\playwright\_impl\_connection.py", line 369, in wrap_api_call
    return await cb()
  File "C:\Users\Matt Marcus\Documents\Projects\gdprscan\venv\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Unable to retrieve content because the page is navigating and changing the content.

Process finished with exit code 1
```
Related: microsoft/playwright-python#1454

**Comment by Mattwmaster58** [comment]
Thanks for verifying with JS as well. My use case is interacting with consent banners dialogs - often it is necessary to reload the page to observe the configuration done was sucessful.

**Comment by dgozman** [comment]
Investigated this in chromium:
- `Page.lifecycleEvent(load)` arrives - `page.goto()` resolves.
- `page.reload()` issues a reload command.
  - `Page.navigatedWithinDocument` arrives because page did a `pushState` - reload resolves the "waitForNavigation" bit.
  - `Page.frameStoppedLoading` from original load arrives - reload get the "load" event and resolves.
- `page.content()` starts and issues an evaluate.
- Meanwhile, page actually starts the reload, issues a network request, gets a response, commits and clears execution contexts.
- `page.content()` fails.

**Comment by jsanonymousfunction** [comment]
Thank you for the quick fix! I'm assuming this will land in 1.26 based on labels here?

**Comment by Mattwmaster58** [comment]
Great to hear this. I'm assuming this is going to land in 1.26 based off the labels?

**Comment by dgtlmoon** [comment]
great work!!
