### ISSUE TITLE
[Question] How to get actual URL instead of 'chrome-error://chromewebdata/' when using page.url()

### ISSUE THREAD

**Issue by hash004** [microsoft/playwright#16160]
I'm trying to get the the URL using `page.url()` after I'm redirected after login. The redirected URL has the user code I need but due to the callback URL being `localhost:3000/**` when I console.log page.url I'm getting `chrome-error://chromewebdata/`. 

The steps:

```
    test.only('Getting the user code', async ({ page }) => {
        await page.goto('https://*******.auth0.com/authorize?*****');
        
        await page.locator('input[name="username"]').click();

        await page.locator('input[name="username"]').fill('*****');

        await page.locator('input[name="password"]').click();

        await page.locator('input[name="password"]').fill('*****');

        await page.locator('button:has-text("Continue")').click();

        console.log(await page.url());

    });
```

![image](https://user-images.githubusercontent.com/2758955/182445403-fd62e3f8-e290-4eea-8248-1fb803fc65c6.png)

**Comment by mxschmitt** [comment]
`chrome-error://chromewebdata/'` means that something went wrong inside the browser when navigating. Are you able to provide a repro for us so we could take a look in more detail?

**Comment by hash004** [comment]
Hey Max,

Thanks for the response. The none existing page is on purpose, as part of auth0 callback whitelisted url. I wanted to use the code the callback returns in the url so I can use it for my other tests.

I've found an alternative way of getting the URL by using `page.on('request'` and ` page.on('response'` to get the URL and extract the code.

**Comment by rahulmr** [comment]
> Hey Max,
> 
> Thanks for the response. The none existing page is on purpose, as part of auth0 callback whitelisted url. I wanted to use the code the callback returns in the url so I can use it for my other tests.
> 
> I've found an alternative way of getting the URL by using `page.on('request'` and ` page.on('response'` to get the URL and extract the code.

I am stuck in same situation could you please post your solution, how you got it using `page.on('request')` and `page.on('response')`

**Comment by rahulmr** [comment]
> Hey Max,
> 
> Thanks for the response. The none existing page is on purpose, as part of auth0 callback whitelisted url. I wanted to use the code the callback returns in the url so I can use it for my other tests.
> 
> I've found an alternative way of getting the URL by using `page.on('request'` and ` page.on('response'` to get the URL and extract the code.

I am stuck in same situation could you please post your solution, how you got it using `page.on('request')` and `page.on('response')`

**Comment by hash004** [comment]
Hey Rahul,

Sure. I used `page.on(request)` to push the requested urls into an array and then filter the requested urls array for the one I wanted (make sure to do this before the action that will make the requests). If you're intending to do this with the responses then use `page.on(response). Example of what I did:

```
//Storing the request urls in array before continue button is pressed
page.on('request', request => {
      requestUrls.push(request.url())
});

await page.locator('button:has-text("Continue")').click();

//Filtering the request URLs for the callback URL I'm looking for
const callBackUrl = requestUrls.filter(element => {
    if (element.includes(`${process.env.REDIRECT_URI}`)) {
        return true;
    }
});
```

Hope that helps.

**Comment by brecke** [comment]
@hash004 thanks friend, works perfectly.

**Comment by WickyNilliams** [comment]
@mxschmitt is there any strong reason for playwright not to offer a more direct way to achieve this? is there any circumstance where you'd _want_ to get `chrome-error://chromewebdata/` in an assertion? it's quite surprising behavior! i expect 99% of people would assume `page.url()` would always give you the value from the address bar, and not an internal, browser-specific url

**Comment by avegancafe** [comment]
@hash004 I know this issue is old, but what did you actually do with the callbackURL after you got it? I'm hitting the same error auth an auth0 login flow and not sure why as the tests work locally but not in CI

**Comment by juvarabrera** [comment]
Is there a way to get the URL if the page is opened on a new page? @hash004's answer seems only to be working for same page requests.

In my case, a link is opened in a new page (same context). I have a new `Page` object that I can use but I can't use `.reload()` since it's a link that's not working

**Comment by budokans** [comment]
Another way around this is to just wait for when it gets stuck and force a reload.

```
await page.waitForLoadState("domcontentloaded");
await page.reload();
```

So hacky. Of course, it would be lovely if we could get an explanation as to why the browser hangs like this! Works fine locally, as others have mentioned.

**Comment by Nekender02** [comment]
Can anyone help me out with **KeyError: 'playwright_page'** 

```
async def errback_close_page(self, failure):
        print(f"===================================================== {failure.request.meta}============================")
        page = failure.request.meta["playwright_page"]
        print(f"xxxxxxxxxxxxxxxxxxxxx {page} is closed xxxxxxxxxxxxxxxxxxxxxxxxxxxx")
        await page.close()

def start_requests(self):
        if not self.start_urls and hasattr(self, "start_url"):
            raise AttributeError(
                "Crawling could not start: 'start_urls' not found "
                "or empty (but found 'start_url' attribute instead, "
                "did you miss an 's'?)"
            )
        for url in self.start_urls:
            npo = self.npos[url]
            logging.info("### crawl: %s", url)
            yield scrapy.Request(
                url, callback=self.my_parse, dont_filter=True, meta=dict(playwright=True, playwright_include_page=True, start_time=datetime.utcnow()), cb_kwargs={"npo": npo}, errback=self.errback_close_page

            )
```

So here is the log with printing meta, as you can see there is no playwright_page in meta for second print

```
2024-06-02 21:13:05 [root] INFO: ### crawl: http://www.hhwf.org
2024-06-02 21:13:05 [root] INFO: ### crawl: http://thekauaimarathon.com
2024-06-02 21:13:05 [root] INFO: ### crawl: http://www.ohiorecruiters.org
2024-06-02 21:13:05 [scrapy-playwright] INFO: Launching browser chromium
2024-06-02 21:13:05 [scrapy-playwright] INFO: Launching browser chromium
2024-06-02 21:13:05 [scrapy-playwright] INFO: Browser chromium launched
2024-06-02 21:13:06 [scrapy-playwright] INFO: Launching browser chromium
2024-06-02 21:13:06 [scrapy-playwright] INFO: Browser chromium launched
2024-06-02 21:13:06 [scrapy-playwright] INFO: Browser chromium launched
2024-06-02 21:13:06 [scrapy.downloadermiddlewares.robotstxt] ERROR: Error downloading <GET http://www.ohiorecruiters.org/robots.txt>: DNS lookup failed: no results for hostname lookup: www.ohiorecruiters.org.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 54, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/twisted/internet/endpoints.py", line 1022, in startConnectionAttempts
    raise error.DNSLookupError(
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.ohiorecruiters.org.
2024-06-02 21:13:06 [scrapy-playwright] INFO: Launching browser chromium
2024-06-02 21:13:07 [scrapy-playwright] INFO: Browser chromium launched
**===================================================== {'playwright': True, 'playwright_include_page': True, 'start_time': datetime.datetime(2024, 6, 2, 21, 13, 5, 727733), 'download_timeout': 180.0, 'download_slot': 'www.ohiorecruiters.org', 'playwright_context': 'default', 'playwright_page': <Page url='chrome-error://chromewebdata/'>}============================**
xxxxxxxxxxxxxxxxxxxxx <Page url='chrome-error://chromewebdata/'> is closed xxxxxxxxxxxxxxxxxxxxxxxxxxxx
2024-06-02 21:13:08 [scrapy.core.engine] INFO: Closing spider (finished)
2024-06-02 21:13:08 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 2,
 'downloader/exception_type_count/playwright._impl._api_types.Error': 1,
 'downloader/exception_type_count/twisted.internet.error.DNSLookupError': 1,
 'downloader/request_bytes': 612,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'elapsed_time_seconds': 8.041216,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 6, 2, 21, 13, 8, 767138),
 'log_count/ERROR': 1,
 'log_count/INFO': 28,
 'memusage/max': 175394816,
 'memusage/startup': 175394816,
 'playwright/context_count': 1,
 'playwright/context_count/max_concurrent': 1,
 'playwright/context_count/persistent/False': 1,
 'playwright/context_count/remote/False': 1,
 'playwright/page_count': 1,
 'playwright/page_count/max_concurrent': 1,
 'playwright/request_count': 1,
 'playwright/request_count/method/GET': 1,
 'playwright/request_count/navigation': 1,
 'playwright/request_count/resource_type/document': 1,
 "robotstxt/exception_count/<class 'twisted.internet.error.DNSLookupError'>": 1,
 'robotstxt/request_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 6, 2, 21, 13, 0, 725922)}
2024-06-02 21:13:08 [scrapy.core.engine] INFO: Spider closed (finished)
2024-06-02 21:13:08 [scrapy-playwright] INFO: Closing download handler
2024-06-02 21:13:08 [scrapy-playwright] INFO: Closing browser
2024-06-02 21:13:09 [scrapy-playwright] INFO: Closing download handler
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/'>
2024-06-02 21:13:11 [scrapy-playwright] INFO: Launching browser chromium
2024-06-02 21:13:11 [scrapy-playwright] INFO: Browser chromium launched
$$$$$$$$$$$$$$$$ able to access page <Page url='https://hhwf.org/'>
2024-06-02 21:13:13 [scrapy.core.engine] INFO: Closing spider (finished)
2024-06-02 21:13:13 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 6612,
 'downloader/request_count': 22,
 'downloader/request_method_count/GET': 22,
 'downloader/response_bytes': 79598,
 'downloader/response_count': 22,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/301': 21,
 'elapsed_time_seconds': 12.589505,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 6, 2, 21, 13, 13, 292754),
 'item_scraped_count': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 50,
 'memusage/max': 174043136,
 'memusage/startup': 174043136,
 'offsite/domains': 2,
 'offsite/filtered': 31,
 'playwright/context_count': 1,
 'playwright/context_count/max_concurrent': 1,
 'playwright/context_count/persistent/False': 1,
 'playwright/context_count/remote/False': 1,
 'playwright/page_count': 1,
 'playwright/page_count/max_concurrent': 1,
 'playwright/request_count': 71,
 'playwright/request_count/method/GET': 70,
 'playwright/request_count/method/POST': 1,
 'playwright/request_count/navigation': 4,
 'playwright/request_count/resource_type/document': 4,
 'playwright/request_count/resource_type/fetch': 2,
 'playwright/request_count/resource_type/font': 9,
 'playwright/request_count/resource_type/image': 12,
 'playwright/request_count/resource_type/other': 2,
 'playwright/request_count/resource_type/ping': 1,
 'playwright/request_count/resource_type/script': 29,
 'playwright/request_count/resource_type/stylesheet': 12,
 'playwright/response_count': 71,
 'playwright/response_count/method/GET': 70,
 'playwright/response_count/method/POST': 1,
 'playwright/response_count/resource_type/document': 4,
 'playwright/response_count/resource_type/fetch': 2,
 'playwright/response_count/resource_type/font': 9,
 'playwright/response_count/resource_type/image': 12,
 'playwright/response_count/resource_type/other': 2,
 'playwright/response_count/resource_type/ping': 1,
 'playwright/response_count/resource_type/script': 29,
 'playwright/response_count/resource_type/stylesheet': 12,
 'request_depth_max': 1,
 'response_received_count': 1,
 'robotstxt/request_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 6, 2, 21, 13, 0, 703249)}
2024-06-02 21:13:13 [scrapy.core.engine] INFO: Spider closed (finished)
2024-06-02 21:13:13 [scrapy-playwright] INFO: Closing download handler
2024-06-02 21:13:13 [scrapy-playwright] INFO: Closing browser
2024-06-02 21:13:13 [scrapy-playwright] INFO: Closing download handler
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/'>
2024-06-02 21:13:14 [scrapy-playwright] INFO: Launching browser chromium
2024-06-02 21:13:14 [scrapy-playwright] INFO: Browser chromium launched
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/support-revere'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/board'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/about-us'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/volunteer'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/cart'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/blog'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/about-us'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=9H2AWXUE4L3M8&source=url&ssrt=1717362812122'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/back-to-school'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news-1/2019-scholarship-awards'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news-1/revere-hall-of-fame-induction-2019'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news-1/community-health-and-wellness-night-2019'>
**===================================================== {'playwright': True, 'playwright_include_page': True, 'start_time': datetime.datetime(2024, 6, 2, 21, 13, 51, 897863), 'depth': 3}============================**
2024-06-02 21:13:52 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.reverefoundation.com/recent-news-1?author=51140743e4b099bd04eedd7d> (referer: https://www.reverefoundation.com/recent-news-1/2019-scholarship-awards)
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1065, in adapt
    extracted = result.result()
  File "/home/ec2-user/SageMaker/grant-crawler/giboo/spiders/npos.py", line 50, in errback_close_page
    page = failure.request.meta["playwright_page"]
KeyError: 'playwright_page'
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/register/marathon-and-half-marathon/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/register/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/the-race/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/register/keiki-run/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/the-race/the-course/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/the-race/expo/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/the-race/race-activities/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/the-race/faqs/'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news-1/see-something-say-something-spring-2019'>
2024-06-02 21:14:00 [scrapy.extensions.logstats] INFO: Crawled 18 pages (at 18 pages/min), scraped 77 items (at 77 items/min)
2024-06-02 21:14:00 [scrapy.extensions.logstats] INFO: Crawled 10 pages (at 10 pages/min), scraped 12 items (at 12 items/min)
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news-1/tag/2019'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news-1/tag/produce'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://www.reverefoundation.com/recent-news-1/tag/protect'>
$$$$$$$$$$$$$$$$ able to access page <Page url='https://thekauaimarathon.com/photos-and-videos/'>
```

**Comment by drik98** [comment]
> @hash004 I know this issue is old, but what did you actually do with the callbackURL after you got it? I'm hitting the same error auth an auth0 login flow and not sure why as the tests work locally but not in CI 

Still getting exactly the same issue.

**Comment by drik98** [comment]
Okay we just fixed this issue on our hand but I have no idea if this applies to everyone but I am still gonna post my fix here. 

## Our setup

We are having a docker-compose file including all of our own services plus a keycloak container for our oauth login.

```yaml
# docker-compose.yaml

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
    command: ["start-dev", "--import-realm"]
    volumes:
      - type: bind
        source: ./keycloak-realm.json
        target: /opt/keycloak/data/import/keycloak-realm.json
    ports:
      - "8080:8080"
```

We spin up the docker containers using `docker-compose up -d` both locally and in our gitlab ci environment. After every service is up and healthy we execute the playwright tests against it.

## The issue

In the CI environment we are using docker-in-docker. That means that the host name is no longer `localhost` as that would reference the container of the build job. Instead we have set ` DOCKER_HOST: tcp://docker:2375` so we can access the containers by `http://docker:<port>/` instead of `http://localhost:<port>/` like you would do locally. We had adjusted all of our environment variables for our frontend to use `docker` instead of `localhost` so everything seemed to be running fine. 

We could access the frontend in the test, would be redirected to the login page of keycloak,

> navigated to "http://docker:8080/realms/my-realm/protocol/openid-connect/auth?client_id=my-client-id&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Foidc-callback&response_type=code&scope=openid+profile&state=31dddea0c0374de4ad4b5c13b7d9b9f9&code_challenge=XLVTEwry1zVgJ5GZWG2XvqEWxkuljf7nqxvTklfxuQk&code_challenge_method=S256&response_mode=query"

could fill out the login form (username and password) and click on login to be wrongly redirected.

>  navigated to "chrome-error://chromewebdata/"

Now I used the trick mentioned [here](https://github.com/microsoft/playwright/issues/16160#issuecomment-1252105629) to see where we were actually getting redirected to and this is where I found the issue:

```json
[
  'http://localhost:8080/realms/my-realm/login-actions/authenticate?session_code=CdTh8jr853VtO2U1RKHDoDG8XuQyWVVyj9ISM3mWenE&execution=e13e986c-b8ce-47a0-bfed-a5df812accca&client_id=my-client-id&tab_id=_XZCDYOhwxs'
]
```

It still referenced `localhost` instead of `docker` here. I did some digging and saw that the `action` on the `<form>` was wrong: 

```html
<form id="kc-form-login" onsubmit="login.disabled = true; return true;" action="http://localhost:8080/realms/my-realm/login-actions/authenticate?session_code=XN2VTvfQ4QU1ziDgrh_7N9eatLeTPMn1x9ksnT0oPF8&amp;execution=e13e986c-b8ce-47a0-bfed-a5df812accca&amp;client_id=my-client-id&amp;tab_id=gw2eLxHz1aM" method="post">
```

## The solution 

In a CI/docker-in-docker environment you have to make sure to actually set the `KC_HOSTNAME` env variable of the keycloak container correctly. 

Example with gitlab CI

```yaml
# docker-compose.yaml

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=${KC_HOSTNAME:-localhost}
    command: ["start-dev", "--import-realm"]
    volumes:
      - type: bind
        source: ./keycloak-realm.json
        target: /opt/keycloak/data/import/keycloak-realm.json
    ports:
      - "8080:8080"
```

and 

```yaml
# gitlab-ci.yml

playwright:
  stage: check
  image:
    name: mcr.microsoft.com/playwright:v1.42.1
    entrypoint: [""]
  services:
    - docker:20.10.22-dind
  variables:
    KC_HOSTNAME: docker
  before_script:
    - docker compose up -d
  script:
    - pnpm playwright test
```


## Conclusion

Like I said in the beginning: This solution is pretty specific to our circumstances of using keycloak in a docker-in-docker environment. But maybe some of you are having the same or at least a similar setup and run into the same issue.

**Comment by citypaul** [comment]
Hi all,

Thanks for the thread above - we managed to solve our issue using this method posted above:

```ts
const requestPromise = page.waitForRequest(getRedirectUri());
await requestPromise;
```

In our instance, we're doing something a little unusual in that we're doing a redirect via a POST submission on a form.

It does confuse me somewhat though that playwright can't do an assertion like:

```ts
await expect(page).toHaveURL(getRedirectUri());
```

Can anybody here please explain why this wasn't possible? I'd just like to understand what the underlying reason for this is if somebody is able to please explain.

Thanks!

**Comment by robme** [comment]
I have exactly the same problem. It's confusing why an internal Chrome URL rather than the actual requested page URL is what `.toHaveURL()` returns. I can't think of any situation where you would want that.

I need to know that a redirect (to an off-site URL) occurs, but the contents of the page or whether it loads is not actually part of the test, since it's an external website that may or may not be accessible when the test runs. I just need to know that the redirect to a particular URL occurred.

Thanks for `waitForRequest()`, I think that does what I need. I did it like this:

```TypeScript
const requestPromise = page.waitForRequest(request =>
  request.url().includes('/some-sso-path'),
);
await home.clickLogin();
await requestPromise;
```
