### ISSUE TITLE
[BUG] test.fail() does not work with test timeouts

### ISSUE THREAD

**Issue by marcosvfranco** [microsoft/playwright#16317]
## Context: ##
Playwright Version: [1.23.1]

**System:**
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 8.39 GB / 19.34 GB
 - Container: Yes

**Binaries:**
 - Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
- Browser: [Chromium]

**Code Snippet**

bug-timeout.spec.ts
```javascript
import { test } from '@playwright/test';

test('Go to Google Page and click an invalid locator @fail', async ({ page }) => {
    // arrange
    test.fail();
    await page.goto('https://www.google.com/');
    await page.locator('id=this-should-fail').click();
});
```

output:
```bash
Running 1 test using 1 worker

  ✘  [chromium] › e2e/bug-timeout.spec.ts:3:1 › Go to Google Page and click an invalid locator @fa (30s)


  1) [chromium] › e2e/bug-timeout.spec.ts:3:1 › Go to Google Page and click an invalid locator @fail 

    Timeout of 30000ms exceeded.

    locator.click: Target closed
    =========================== logs ===========================
    waiting for selector "id=this-should-fail"
    ============================================================

       5 |     test.fail();
       6 |     await page.goto('https://www.google.com/');
    >  7 |     await page.locator('id=this-should-fail').click();
         |                                               ^
       8 | });
       9 |
      10 |

        at /home/cliente//tests/e2e/bug-timeout.spec.ts:7:47

    Pending operations:
      - locator.click at tests/e2e/bug-timeout.spec.ts:7:47


    attachment #1: screenshot (image/png) ----------------------------------------------------------
    test-results/e2e-bug-timeout-Go-to-Google-Page-and-click-an-invalid-locator-fail-chromium/test-failed-1.png
    ------------------------------------------------------------------------------------------------

  Slow test file: [chromium] › e2e/bug-timeout.spec.ts (30s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [chromium] › e2e/bug-timeout.spec.ts:3:1 › Go to Google Page and click an invalid locator @fail 
```

playwright.config.ts
```javascript
// @ts-check
import { PlaywrightTestConfig, devices } from '@playwright/test';
import 'dotenv/config';
/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * @see https://playwright.dev/docs/test-configuration
 * @type {import('@playwright/test').PlaywrightTestConfig}
 */
const config: PlaywrightTestConfig = {
    use: {
        headless: process.env.NOHEADLESS ? false : true,
        viewport: { width: 1280, height: 720 },
        ignoreHTTPSErrors: true,
        video: 'off',
        screenshot: 'only-on-failure',
        trace: 'off',
        launchOptions: {
            slowMo: 50,
        },
        // actionTimeout: 5000,
        // navigationTimeout: 10000,
    },
    
    /* Use Dot Reporter + HTML for CI and list for local runs */
    reporter: process.env.CI ? [
        ['dot'],
        ['html', { open: 'never' }] 
    ] : 'list',
    
    testDir: 'tests',
    workers: 4,

    /* Configure projects for major browsers */
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] },
        },
    ],
};

export default config;
```

**Describe the bug**

It's expected that `test.fail()` should declare that this test will fail but pass my test, but as shown, it's not working this way and it's failing the test when I try to click on some link that does not exist in the page.

In addition:
If I modify the default timeouts of `actionTimeout` and `navigationTimeout`, the function `test.fail()` start working.

Since we have in the documentation that there isn't an Action timeout and Navigation timeout, I guess that the default `Test` timeout is not being caught by the `test.fail()`, and the **action / navigation** timeouts are being caught, but why? The test should fail anyway if I'm telling the runner that will fail.

** Modified `use config` to make test.fail() works: **
```javascript
    use: {
        headless: process.env.NOHEADLESS ? false : true,
        viewport: { width: 1280, height: 720 },
        ignoreHTTPSErrors: true,
        video: 'off',
        screenshot: 'only-on-failure',
        trace: 'off',
        launchOptions: {
            slowMo: 50,
        },
        actionTimeout: 5000,
        navigationTimeout: 10000,
    },
```

**Comment by rwoll** [comment]
Relates https://github.com/microsoft/playwright/issues/9373#issuecomment-938161218

**Comment by rwoll** [comment]
If a test hangs (i.e. without `test.fail` the overall test case times out), this will still be the behavior when `test.fail` is used. Instead, you should use `test.fixme()` for this case. You don't want to slow down CI by 30seconds for nothing.
