### ISSUE TITLE
[BUG] Missing a dependency on docker image which fails webkit

### ISSUE THREAD

**Issue by zlk89** [microsoft/playwright#1636]
**Context:**
- Playwright Version: 0.12.1
- Operating System: Mac (but we use the ubuntu docker specified in doc)
- Extra: We use docker https://github.com/microsoft/playwright/tree/master/docs/docker to run the screenshot test

**Code Snippet**

When you running this script in the ubuntu docker

```javascript
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch({
    dumpio: true,
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://google.com');
  await page.screenshot({path: 'screenshot.png'});
  await browser.close();
})();

```

**Describe the bug**
Seeing:

```
[err] /home/pwuser/app/node_modules/playwright/.local-browsers/webkit/minibrowser-wpe/MiniBrowser: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
(node:630) UnhandledPromiseRejectionWarning: Error: Protocol error (Playwright.createContext): Browser has been closed.
    at /home/pwuser/app/node_modules/playwright-core/lib/webkit/wkConnection.js:100:63
    at new Promise (<anonymous>)
    at WKSession.send (/home/pwuser/app/node_modules/playwright-core/lib/webkit/wkConnection.js:99:16)
    at WKBrowser.newContext (/home/pwuser/app/node_modules/playwright-core/lib/webkit/wkBrowser.js:65:65)
    at WKBrowser.<anonymous> (/home/pwuser/app/node_modules/playwright-core/lib/helper.js:84:31)
    at /home/pwuser/app/src/tests/screenshot/specs/test.js:7:33
```

Basically, it is missing `libglu1` for webkit.
As long as we added `RUN apt-get install -y libglu1`, it is working.

**Comment by aslushnikov** [comment]
@zlk89 interesting, I just tried and it worked fine. Do you use that image as-is, or maybe you "ported" the docker file over a different ubuntu version?

The following worked for me; let me know if it works for you.

1. Run docker image (it's currently published under `aslushnikov/playwright:bionic`).
```bash
docker run --rm -it aslushnikov/playwright:bionic
```

Inside the docher container, I did the following:
```
$ cd $HOME
$ npm i playwright
$ cat << EOF > a.js
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch({
    dumpio: true,
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://google.com');
  await page.screenshot({path: 'screenshot.png'});
  await browser.close();
})();
$ node a.js
```

**Comment by zlk89** [comment]
I tried your image, and run same commands, still seeing the error:

```
pwuser@2a9410085bb2:~$ node a.js
[err]
[err] ** (MiniBrowser:53): CRITICAL **: 21:04:38.968: void webkit_web_context_register_uri_scheme(WebKitWebContext*, const char*, WebKitURISchemeRequestCallback, gpointer, GDestroyNotify): assertion '!g_ascii_strcasecmp(scheme, "ws")' failed
[err] EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
[err]
[err] ** (WPEWebProcess:63): WARNING **: 21:04:39.023: Error loading the injected bundle (/usr/local/lib/wpe-webkit-1.0/injected-bundle/libWPEInjectedBundle.so): /usr/local/lib/wpe-webkit-1.0/injected-bundle/libWPEInjectedBundle.so: cannot open shared object file: No such file or directory
[err] Fontconfig error: Cannot load default config file
[err] GLib-GIO-Message: 21:04:39.331: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

You might want to run on a fresh image?

My env:
Docker version: 19.03.8, build afacb8b
macOS 10.15.4

**Comment by arjun27** [comment]
Thanks for running this @zlk89. At this point, the webkit build throws these errors even on a successful execution, and we should explore means on fixing that. Did the script create a `screenshot.png` file for you? Did that look right? Would be very helpful if you can confirm that.

**Comment by zlk89** [comment]
hmmm, the screenshot looks correct

**Comment by aslushnikov** [comment]
@zlk89 getting back to the original issue - can you help me reproduce this?

**Comment by aslushnikov** [comment]
Let me know if there's anything else we can do to help you; so far it looks like no code changes should be made to Playwright's docker image.
