### ISSUE TITLE
[Question] Unclear error if some files from app used in tests (types, enums) with .ts

### ISSUE THREAD

**Issue by lifeart** [microsoft/playwright#16605]
Hey! This is really hard-to debug thing if you don't know what's going on here:

## Given:

* React App
* Playwright tests

_Both use typescript._

If I import some enum as variable from app into playwright test (in bad case), I could have error like this:

https://gist.github.com/lifeart/b8e760745c03ae17d8b54fc3c2d8518e

Root cause bubbliing from this lines:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/1360552/185070505-8a8c37b5-bf2f-476d-a9db-52aa6ca24dfd.png">

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/1360552/185070596-97939eac-740b-4a2e-9aa2-29601433047c.png">

If app use some deps, and this deps rely on `window` environment, during `eval` we execute within test context, not in browser, and it's cause such errors.

## Soulution for us:
- use only `import type ...` from app namespace
- expose `shared` files as pure, without `side deps`

I don't know how to mention it, to have less devs catching it.

## Search keywords:
ReferenceError: navigator is not defined
Error: Command failed with exit code 1:

**Comment by pavelfeldman** [comment]
> https://gist.github.com/lifeart/b8e760745c03ae17d8b54fc3c2d8518e

I don't seem to have access to this gist, could you make it public?

**Comment by lifeart** [comment]
Hi there! Looks like I removed gist by mistake, but, able to figure out some logs:

```
SyntaxError: Unexpected token '<'

    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1126:15)
    at Module._compile (node:internal/modules/cjs/loader:1162:27)
    at Module.A._compile (/app/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.t.<computed>.tu._extensions.<computed> [as .tsx] (/app/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/app/playwright/tests/spaces/space.mutations.spec.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Module.A._compile (/app/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Object.t.<computed>.tu._extensions.<computed> [as .ts] (/app/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010)
```

**Comment by lifeart** [comment]
@pavelfeldman in short, I able to figure out minimal reproduction case:

// breaking.ts
```ts
import 'draft-js/dist/Draft.css';
export const item = 42;
```

// test.ts
```ts
import { item } from './breaking';

test.describe('it works', () => {
  test('should be number', async () => {
    expect(typeof item).toBe('number');
  })
});
```

<img width="975" alt="image" src="https://github.com/microsoft/playwright/assets/1360552/6474bb10-771b-455f-8519-cf06f67c2c92">


Since playwright.ts is trying to compile imported files, it may contain framework/bundle specific files (such as styles/images/wasm's and cetra), and it cause failure. And if we have failure on 3-5 level's chain, it's REALLY hard to debug it and figure out.

**Comment by pavelfeldman** [comment]
I'm getting this in e2e tests:


```
SyntaxError: Unexpected token '{
   at test.spec.ts:18

  16 |  */
  17 |
> 18 | import './draft.css';
     | ^
  19 | import { test , expect } from '@playwright/test';
```

In the latest version of Playwright, so I'd say the errors message is now more clear.

**Comment by mxschmitt** [comment]
(Closing as per above then, since we provide a better error message and its not possible to require this file from Node.js)
