### ISSUE TITLE
when I run playwright in a subprocess on CentOS, I encountered----- AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'，

### ISSUE THREAD

**Issue by zhangzhuoBYS** [microsoft/playwright#16669]
Context:

    Playwright Version: 1.24
    Operating System: CentOs
    Node.js version: v16.16.0
    Browser: chrome
    Python Version: 3.7.8

When I run playwright alone for screenshot, it works well. However, when I take it as a plug-in and call it by other programs, the problem "AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'"  will occur; When I change it to a command line call, the error reported is as follows:     

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/lib/python3.7.8/lib/python3.7/site-packages/playwright/driver/package/lib/utilsBundleImpl.js:13:22284)
    at /lib/python3.7.8/lib/python3.7/site-packages/playwright/driver/package/lib/utilsBundleImpl.js:36:62363
    at /python3.7.8/lib/python3.7/site-packages/playwright/driver/package/lib/utilsBundleImpl.js:1:222
    at Object.<anonymous> (/lib/python3.7.8/lib/python3.7/site-packages/playwright/driver/package/lib/utilsBundleImpl.js:44:627)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
Traceback (most recent call last):
  File "screen_cmd.py", line 278, in <module>
    timeout=args.timeout
  File "screen_cmd.py", line 174, in get_shot_and_title_sync_v2
    playwright_web = sync_playwright().start()
  File "/lib/python3.7.8/lib/python3.7/site-packages/playwright/sync_api/_context_manager.py", line 94, in start
    return self.__enter__()
  File "/lib/python3.7.8/lib/python3.7/site-packages/playwright/sync_api/_context_manager.py", line 89, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
Task was destroyed but it is pending!
```

**Comment by aslushnikov** [comment]
@zhangzhuoBYS I'm not sure what's going on here since I can't repro it locally. It might be that there's a different playwright client / playwright server versions.

It's really hard to tell without a good repro that we can run locally! Please re-file with something that we can debug & analyze!
