### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by madanankurmalviya** [microsoft/playwright#16716]
**Context:**
- Playwright Version: 1.25.0
- Operating System:  Mac 12.5.1
- Node.js version: v18.7.0.
- Browser: Chromium

**Describe the bug**

Few Links are not intractable.
Exception in thread "main" org.opentest4j.AssertionFailedError: Page URL expected to be: http://the-internet.herokuapp.com/
Received: http://the-internet.herokuapp.com/javascript_alerts

```
Call log:
Locator.expect with timeout 5000ms
waiting for selector ":root"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
  selector resolved to <html lang="en" class="no-js">…</html>
  unexpected value "http://the-internet.herokuapp.com/javascript_alerts"
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:73)
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:50)
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:41)
	at com.microsoft.playwright.impl.PageAssertionsImpl.hasURL(PageAssertionsImpl.java:60)
	at com.microsoft.playwright.assertions.PageAssertions.hasURL(PageAssertions.java:126)
	at PlaywrightThird.main(PlaywrightThird.java:45)

```

**Comment by aslushnikov** [comment]
@madanankurmalviya I don't follow what is the bug; it looks like your tests failed because it expected a different URL. If you want to relax your expectation, feel free to use RegExp instances there!

Please re-file with full details if you still think we can be helpful!
