### ISSUE TITLE
[Question] How to avoid "Execution context was destroyed" when navigating by a timer?

### ISSUE THREAD

**Issue by jhyot** [microsoft/playwright#16720]
We have a test case which tests that the website automatically navigates away after a certain time (auto-logout). In between we periodically check whether we are still logged in, by something like this (Java):
```java
navbar
    .locator(LOGGED_IN_NAVBAR_SELECTOR)
    .locator(ACCOUNT_MENU_BUTTON_SELECTOR)
    .isVisible();
```

Unfortunately, it can happen that the logout timer kicks in exactly when this check is being executed, leading to this kind of error:
```
com.microsoft.playwright.PlaywrightException: Error {
  message='Execution context was destroyed, most likely because of a navigation
=========================== logs ===========================
  checking visibility of "app-navbar >> app-logged-in-navbar >> button:has-text('arrow_drop_down')"
============================================================
  name='Error
  stack='Error: Execution context was destroyed, most likely because of a navigation
=========================== logs ===========================
  checking visibility of "app-navbar >> app-logged-in-navbar >> button:has-text('arrow_drop_down')"
============================================================
    at Frame._contextDestroyed (C:\Windows\playwright\1.23.4\node_modules\playwright\node_modules\playwright-core\lib\server\frames.js:1664:30)
    at FrameSession._onExecutionContextDestroyed (C:\Windows\playwright\1.23.4\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crPage.js:766:19)
    at FrameSession._onExecutionContextsCleared (C:\Windows\playwright\1.23.4\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crPage.js:770:79)
    at CRSession.<anonymous> (C:\Windows\playwright\1.23.4\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crPage.js:482:2095)
    at CRSession.emit (events.js:314:20)
    at C:\Windows\playwright\1.23.4\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crConnection.js:228:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
}
```

Is there a mechanism in Playwright where I can do as described above, but in essence telling it to recover in a benign way from sudden navigations?

**Comment by aslushnikov** [comment]
@jhyot  It looks like you can use web-first assertions: [`assertThat(locator).isVisible()`](https://playwright.dev/java/docs/next/test-assertions#locator-assertions-to-be-visible)

**Comment by jhyot** [comment]
Honestly I did not know that there are also web-first assertions for Java. I never heard them mentioned on your release videos 🙂
I will try it out and report whether that makes a difference.

**Comment by aslushnikov** [comment]
@jhyot ah, we probably forgot to mention them! Thanks for watching!

I'll close this for now; feel free to file a new issue if things don't work for you and you think we can be helpful!
