### ISSUE TITLE
[BUG] baseURL is not applied to page.goto when running in DEBUG mode

### ISSUE THREAD

**Issue by grmmvv** [microsoft/playwright#16956]
**Context:**
- Playwright Version: 1.23.4
- Operating System: Mac
- Node.js version: 14.15.1
- Browser: All
- Extra: Playwright Test for VSCode v0.2.6

**Code Snippet**

```javascript
import {test as base, firefox} from '@playwright/test';
export const test = base.extend({
  page: async ({}, use) => {
    const browser = await firefox.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await use(page);
  },
});

test.use({baseURL: 'http://example.com'});
test('test', async ({page}) => {
  await page.goto('/');
});
```

**Description**

When this snippet started from the VS Code in **DEBUG** mode it will fail with error described below, because `baseURL` variable is not applied ti the `page.goto`.

In case when this script was ran "regularly" (not in DEBUG mode) from the VS Code test will successfully passed.

This snippet will successfully passed if it was ran from the console in any mode.

Looks like there is similar [issue](https://github.com/microsoft/playwright/issues/14691) in the https://github.com/microsoft/playwright repo.

<details><summary>STACKTRACE</summary>
<p>

```javascript
page.goto: Protocol error (Page.navigate): error in channel "content::page": exception while running method "navigate" in namespace "page": Invalid url: "/" _navigate@chrome://juggler/content/content/PageAgent.js:375:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42


    at playwright/bug.spec.ts:13:14
    at node_modules/@playwright/test/lib/workerRunner.js:388:15
    at TestInfoImpl._runFn (/Users/grmmvv/GitHub/net.supplyshift.server/frontend/node_modules/@playwright/test/lib/testInfo.js:166:7)
    at node_modules/@playwright/test/lib/workerRunner.js:344:26
    at TimeoutManager.runWithTimeout (/Users/grmmvv/GitHub/net.supplyshift.server/frontend/node_modules/@playwright/test/lib/timeoutManager.js:70:7)
    at TestInfoImpl._runWithTimeout (/Users/grmmvv/GitHub/net.supplyshift.server/frontend/node_modules/@playwright/test/lib/testInfo.js:154:26)
    at WorkerRunner._runTest (/Users/grmmvv/GitHub/net.supplyshift.server/frontend/node_modules/@playwright/test/lib/workerRunner.js:326:5)
    at WorkerRunner.runTestGroup (/Users/grmmvv/GitHub/net.supplyshift.server/frontend/node_modules/@playwright/test/lib/workerRunner.js:195:11)
Execution log

navigating to "/", waiting until "load"
```
</p>
</details>

**Comment by pavelfeldman** [comment]
I can repro.

**Comment by hallucinogenizer** [comment]
Still facing this issue on `@playwright/test": "^1.40.0`
