### ISSUE TITLE
[Feature] Match JS source-maps against TS source when listing Playwright Test tests

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright#16975]
I tried to use the extension for [Luna Paint](https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint) but test icon doesn't show up in the activity bar. The extension is closed source but I can check diagnostics if helpful.

Playwright Test output channel:

```
2021-08-23T13:34:31.248Z Executing command: node_modules\@playwright\test\lib\cli\cli.js test --reporter=json --list \. 
```

Looks like this is the cause:

```
❯ node node_modules\@playwright\test\lib\cli\cli.js test --reporter=json --list
Error: Cannot find module '../../../../typings/luna.js'
Require stack:
- D:\GitHub\lunapaint\vscode-luna\luna\src\playwright\platform\format\webp.integration.test.ts
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\loader.js
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\runner.js
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\cli.js
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\GitHub\lunapaint\vscode-luna\luna\src\playwright\platform\format\webp.integration.test.ts:4:1) 
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Loader._requireOrImport (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\loader.js:211:18)
    at Loader.loadTestFile (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\loader.js:130:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\src\\playwright\\platform\\format\\webp.integration.test.ts',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\test\\loader.js',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\test\\runner.js',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\test\\cli.js',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\cli\\cli.js'
  ]
}
```

`../../../../typings/luna.d.ts` does exist at that location so not sure why it's failing. Removing `.js` doesn't fix the issue.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
