### ISSUE TITLE
[BUG]Playwright 1.25.0 Frame load interrupted thrown in Webkit but same scenario passes in Chromium

### ISSUE THREAD

**Issue by VishalJain67** [microsoft/playwright#17194]
**Context:**
- Playwright Version: 1.25.0
- Operating System:  Mac
- Node.js version: 16.16.0
- Browser: WebKit
- Language: JAVA version 1.8
- Runner: testNG version 6.14.3
- Using Maven project

**Code Snippet**

```java

import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;

import org.testng.annotations.Test;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Locator.ClickOptions;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.options.WaitUntilState;

public class TestClass {

	@Test
	public void Test1() {
		
		Playwright playwright = Playwright.create();

		Browser browser = playwright.webkit().launch(new BrowserType.LaunchOptions().setHeadless(false));

		BrowserContext context = browser.newContext();

		// Open new page
		Page page = context.newPage();

		page.navigate("https://{baseURL}");

		//FURTHER STEPS--------------------------------------------------
           }
}
```

**Describe the bug**

When I run the above steps, it works fine in Chromium and chrome browser and my test passes. But, when I run the same in safari, it gives me the below error:

**name='Error
  stack='Error: Frame load interrupted**

I am using the standard .navigate method to launch a url in safari. This method is working fine in other browser. Which means I am using it correctly. But for safari it is giving me error.

Also, a point worth noting is - **URL I am using redirects to something like https://{baseURL}/welcome.html/ from https://{baseURL}**

I have to mask the baseURL because it is an org internal url. You can take any other url which redirects to another url as a reference . For example - 

This redirect is perfectly dealt by Chromium but not safari

I am attaching the complete log below:

```
FAILED: Test1
com.microsoft.playwright.PlaywrightException: Error {
  message='Frame load interrupted
=========================== logs ===========================
navigating to "{base URL}", waiting until "load"
============================================================
  name='Error
  stack='Error: Frame load interrupted
=========================== logs ===========================
navigating to "{base URL}", waiting until "load"
============================================================
    at FrameManager.frameAbortedNavigation (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/frames.js:273:14)
    at FrameManager.requestFailed (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/frames.js:369:12)
    at WKPage._onLoadingFailed (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/webkit/wkPage.js:1334:30)
    at WKSession.<anonymous> (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/webkit/wkPage.js:484:2971)
    at WKSession.emit (node:events:527:28)
    at /private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/webkit/wkConnection.js:206:41
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:108)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:100)
	at com.microsoft.playwright.impl.FrameImpl.navigateImpl(FrameImpl.java:401)
	at com.microsoft.playwright.impl.PageImpl.lambda$navigate$32(PageImpl.java:800)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:85)
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:800)
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:41)
	at com.microsoft.playwright.Page.navigate(Page.java:4309)
	at com.tests.test.test(test:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Frame load interrupted
=========================== logs ===========================
navigating to "{base URL}", waiting until "load"
============================================================
  name='Error
  stack='Error: Frame load interrupted
=========================== logs ===========================
navigating to "{base URL}", waiting until "load"
============================================================
    at FrameManager.frameAbortedNavigation (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/frames.js:273:14)
    at FrameManager.requestFailed (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/frames.js:369:12)
    at WKPage._onLoadingFailed (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/webkit/wkPage.js:1334:30)
    at WKSession.<anonymous> (/private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/webkit/wkPage.js:484:2971)
    at WKSession.emit (node:events:527:28)
    at /private/var/folders/r7/ymd4c1yx53186mknnwk5fb0r0000gn/T/playwright-java-12513219344363090081/package/lib/server/webkit/wkConnection.js:206:41
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:190)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:170)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:107)
	... 35 more


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
```

**Comment by dgozman** [comment]
@VishalJain67 Perhaps your page does not actually work in WebKit? Try running `npx playwright wk` and open your page manually in the browser to see how it works.

Unfortunately, we won't be able to help here without a repro we can run locally. Could you share your page/script with us please?

**Comment by VishalJain67** [comment]
> @VishalJain67 Perhaps your page does not actually work in WebKit? Try running `npx playwright wk` and open your page manually in the browser to see how it works.
> 
> Unfortunately, we won't be able to help here without a repro we can run locally. Could you share your page/script with us please?

@dgozman 

I tried to run npx playwright wk and open page manually in the browser to see how it works.
It ran as expected. The script got recorded as well. 

But when I ran the recorded script in eclipse, it again gave me the same error:

**Exception in thread "main" com.microsoft.playwright.PlaywrightException: Error {
  message='Frame load interrupted**

**Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Frame load interrupted**


To launch my url you would need a vpn connection and hence you won't be able to use it even if I shared.

I request you to test on something similar, i.e. any **base url** that upon launching redirects to **base url/welcome.html**

Meanwhile I will also trying to find something similar

**Comment by VishalJain67** [comment]
@dgozman Can we connect via any medium of your choice so that I can reproduce this issue on call? Even if I give you the url, it wouldn't launch in your system because of Authentication checks

**Comment by dgozman** [comment]
@VishalJain67 Unfortunately, we cannot do private debugging sessions. If you could provide a repro, that would be great. In that case, please file a new issue and link to this one.

**Comment by testgitdl** [comment]
We also have problems with webkit 1699 but the same app works perfectly fine with the webkit 1641  (from playwright 1.22.0). In this last one the app UI is just flikkering
