### ISSUE TITLE
Please help how can i set the custom executable path in launch options using JAVA[Question]

### ISSUE THREAD

**Issue by shrinitg** [microsoft/playwright#17211]
I tried this block of code to set the executable path.

```
Playwright playwright = Playwright.create();
BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions();
Path path = Paths.get("~/Library/Caches/ms-playwright/chromium-1019");
launchOptions.setExecutablePath(path);
Browser browser = playwright.chromium().launch(launchOptions);
Page page1 = browser.newPage();
```

But i am getting this error

```
Error {
  message='Failed to launch chromium because executable doesn't exist at ~/Library/Caches/ms-playwright/chromium-1019
  name='Error
  stack='Error: Failed to launch chromium because executable doesn't exist at ~/Library/Caches/ms-playwright/chromium-1019
    at Chromium._launchProcess (/private/var/folders/yp/60ljbq996qxbsf7pl2428b7r0000gn/T/playwright-java-4637668563856404677/package/lib/server/browserType.js:201:71)
    at async Chromium._innerLaunch (/private/var/folders/yp/60ljbq996qxbsf7pl2428b7r0000gn/T/playwright-java-4637668563856404677/package/lib/server/browserType.js:133:9)
    at async Chromium._innerLaunchWithRetries (/private/var/folders/yp/60ljbq996qxbsf7pl2428b7r0000gn/T/playwright-java-4637668563856404677/package/lib/server/browserType.js:111:14)
    at async ProgressController.run (/private/var/folders/yp/60ljbq996qxbsf7pl2428b7r0000gn/T/playwright-java-4637668563856404677/package/lib/server/progress.js:101:22)
    at async Chromium.launch (/private/var/folders/yp/60ljbq996qxbsf7pl2428b7r0000gn/T/playwright-java-4637668563856404677/package/lib/server/browserType.js:86:21)
    at async BrowserTypeDispatcher.launch (/private/var/folders/yp/60ljbq996qxbsf7pl2428b7r0000gn/T/playwright-java-4637668563856404677/package/lib/server/dispatchers/browserTypeDispatcher.js:59:21)
    at async DispatcherConnection.dispatch (/private/var/folders/yp/60ljbq996qxbsf7pl2428b7r0000gn/T/playwright-java-4637668563856404677/package/lib/server/dispatchers/dispatcher.js:397:22)
}
```

**Comment by yury-s** [comment]
You have to manually resolve `~` to the home dir and pass the absolute path. Also the path should point to the executable to to a dir, e.g. /Users/test/Library/Caches/ms-playwright/firefox-1344/firefox/Nightly.app/Contents/MacOS/firefox
