### ISSUE TITLE
[BUG] WaitFor timeout doesn't work, if it bigger than default global timeout

### ISSUE THREAD

**Issue by mila-qa** [microsoft/playwright#17334]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Linux
- Node.js version: v16.14.0
- Browser: Chromium, WebKit
- Extra: Headless and headed mode

**Code Snippet**

```javascript
import {test} from '@playwright/test';

test(`test waiting top limit`, async ({page}) => {
    await page.goto('https://playwright.dev/docs/actionability');
    await page.locator('.search123').waitFor({state: "visible", timeout: 60000})
});
```

**Describe the bug**

`playwright.config.ts` doesn't have any timeout options, so default 30 seconds are taken. 
When I'm setting up a bigger timeout than the default for a single action, the test above waits for 30 seconds instead of the expected 60.

````
Running 1 test using 1 worker
  1) [webkit] › tests/testwaitings.spec.ts:3:1 › test waiting top limit ============================

    Test timeout of 30000ms exceeded.

    locator.waitFor: Target closed
    =========================== logs ===========================
    waiting for selector ".search123" to be visible
    ============================================================

      3 | test(`test waiting top limit`, async ({page}) => {
      4 |     await page.goto('https://playwright.dev/docs/actionability');
    > 5 |     await page.locator('.search123').waitFor({state: "visible", timeout: 60000})
        |                                      ^
      6 | });
      7 |

        at file:///Projects/playwright-tests/tests/testwaitings.spec.ts:5:38

    Pending operations:
      - locator.waitFor at tests/testwaitings.spec.ts:5:38
 ````
   
 
      
### Additional info: 
Debug mode doesn't have above issue. When running the test with PWDEBUG=1, it waits for 60 seconds.

**Comment by mxschmitt** [comment]
This looks expected, the test gets terminated after 30 seconds and waitFor waits up to 60 seconds.

The reason why in your wording "it works as expected" with PWDEBUG is, that we disable the test timeout if PWDEBUG is specified to improve the developer experience and don't close the browser.

**Comment by mila-qa** [comment]
thank you for looking into it. 
What is the way in such a case to create a custom long wait for a single action with playwright waitings?

Default timeout (30 seconds) suits perfectly most of the tests. But in some situations, a longer timeout is required without test run termination. For example, when the test should wait for document uploading to be finished for a minute or even more. 
As soon as the uploading process is finished new element is visible. 

I was following documentation:
````
_Returns when element specified by locator satisfies the state option.
If target element already satisfies the condition, the method returns immediately. Otherwise, waits for up to timeout milliseconds until the condition is met.
const orderSent = page.locator('#order-sent');
await orderSent.waitFor();_
````
 and used `timeout` option for waitFor.

**Comment by rio-ap** [comment]
i think the timeout in config is maximum time the test expected to run. my solution is assign bigger timeout time (like 5 minute). use expect().tobevisible(timeout) to do assertion to check if the locator exist within your custom timeframe. and if the TC is flaky enough or need more time, assign test.slow() or test.setTimeout(timeout) to manually override test case maximum time

**Comment by mxschmitt** [comment]
> What is the way in such a case to create a custom long wait for a single action with playwright waitings?

There are multiple solutions for that, either increase the test timeout in the config or set a smaller timeout inside your test functions, aka. waitFor in your case.

I'd ask yourself in the first place why you need to wait 60 seconds for something to happen inside your test. If your web app does something which is really slow or takes time, then definitely increase the test timeout! I've read file uploads so its reasonable to increase it.

You can also call `test.slow()` inside your test to have an increased timeout for a single test, see here: https://playwright.dev/docs/api/class-test#test-slow-1

**Comment by mila-qa** [comment]
I see your point.  `Config` will update the timeout for all tests. `test.slow()` or `test.setTimeout()` will increase timeout for 1 entire test.
I'm looking for a solution for one action in a test. The situation is when the test has 10 waitings, but only one requires a long timeout. 

For sure it can be updated on a project(config) or test level, but I think it'd be nice don't terminate the test, if there custom timeout. Even though it's longer than the one from the config.

It'll be useful for real tests without debug mode. Could we count this example as a request for enhancement?

**Comment by mila-qa** [comment]
If a function has an option to set maximum timeout it's logical to be able to use it.

````
  /**
   * Returns when element specified by locator satisfies the `state` option.
   *
   * If target element already satisfies the condition, the method returns immediately. Otherwise, waits for up to `timeout`
   * milliseconds until the condition is met.
   *
   * ```js
   * const orderSent = page.locator('#order-sent');
   * await orderSent.waitFor();
   * ```
   *
   * @param options
   */
  waitFor(options?: {
    /**
     * Defaults to `'visible'`. Can be either:
     * - `'attached'` - wait for element to be present in DOM.
     * - `'detached'` - wait for element to not be present in DOM.
     * - `'visible'` - wait for element to have non-empty bounding box and no `visibility:hidden`. Note that element without
     *   any content or with `display:none` has an empty bounding box and is not considered visible.
     * - `'hidden'` - wait for element to be either detached from DOM, or have an empty bounding box or `visibility:hidden`.
     *   This is opposite to the `'visible'` option.
     */
    state?: "attached"|"detached"|"visible"|"hidden";

    /**
     * Maximum time in milliseconds, defaults to 30 seconds, pass `0` to disable timeout. The default value can be changed by
     * using the
     * [browserContext.setDefaultTimeout(timeout)](https://playwright.dev/docs/api/class-browsercontext#browser-context-set-default-timeout)
     * or [page.setDefaultTimeout(timeout)](https://playwright.dev/docs/api/class-page#page-set-default-timeout) methods.
     */
    timeout?: number;
  }): Promise<void>;}
`````

Unfortunately, it's not possible with the current implementation. Decreasing  the waiting time doesn't have logical sense, because `If target element already satisfies the condition, the method returns immediately.`

Anyway, thanks for the suggested workarounds.
