### ISSUE TITLE
[REGRESSION]: Firefox times out on `page.goBack` with `waiting for navigation until "load"`

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#17618]
**Context:**
- GOOD Playwright Version: 1.25.2
- BAD Playwright Version: 1.26.0
- Operating System: Mac, though using the `focal` Docker image
- Extra:

**Code Snippet**

```javascript
import { expect, test } from '@playwright/test'

test('can go back', async ({ page }) => {
  await page.goto('https://sandbox.prereview.org/preprints/doi-10.1101-2022.01.13.476201')
  await page.click('"Write a PREreview"')
  await page.goBack()

  await expect(page.locator('h1')).toHaveText('PREreviews of “The role of LHCBM1 in non-photochemical quenching in Chlamydomonas reinhardtii”')
})
```

**Describe the bug**

Firefox times out on `page.goBack` with `waiting for navigation until "load"`.

Running it with https://github.com/PREreview/prereview.org/blob/7be844c4d0e837106f340b0fdb063d141724cd71/playwright.config.ts (Chrome, Safari and Firefox, with and without JavaScript enabled) I get

```
  ✓  1 [Desktop Chrome] › foo.spec.ts:3:6 › can go back (2s)
  ✓  2 [Desktop Chrome (no JavaScript)] › foo.spec.ts:3:6 › can go back (3s)
  ✓  5 [iPhone 11] › foo.spec.ts:3:6 › can go back (3s)
  ✓  6 [iPhone 11 (no JavaScript)] › foo.spec.ts:3:6 › can go back (2s)
  ✘  3 [Desktop Firefox] › foo.spec.ts:3:6 › can go back (30s)
  ✘  4 [Desktop Firefox (no JavaScript)] › foo.spec.ts:3:6 › can go back (30s)


  1) [Desktop Firefox] › foo.spec.ts:3:6 › can go back =============================================

    Test timeout of 30000ms exceeded.

    page.goBack: Navigation failed because page was closed!
    =========================== logs ===========================
    waiting for navigation until "load"
      navigated to "https://sandbox.prereview.org/preprints/doi-10.1101-2022.01.13.476201"
    ============================================================

      4 |   await page.goto('https://sandbox.prereview.org/preprints/doi-10.1101-2022.01.13.476201')
      5 |   await page.click('"Write a PREreview"')
    > 6 |   await page.goBack()
        |              ^
      7 |
      8 |   await expect(page.locator('h1')).toHaveText(
      9 |     'PREreviews of “The role of LHCBM1 in non-photochemical quenching in Chlamydomonas reinhardtii”',

        at /app/integration/foo.spec.ts:6:14

    Pending operations:
      - page.goBack at integration/foo.spec.ts:6:14


    attachment #1: video (video/webm) --------------------------------------------------------------
    integration-results/foo-can-go-back-Desktop-Firefox/video.webm
    ------------------------------------------------------------------------------------------------

    attachment #2: trace (application/zip) ---------------------------------------------------------
    integration-results/foo-can-go-back-Desktop-Firefox/trace.zip
    Usage:

        npx playwright show-trace integration-results/foo-can-go-back-Desktop-Firefox/trace.zip

    ------------------------------------------------------------------------------------------------

    attachment #3: screenshot (image/png) ----------------------------------------------------------
    integration-results/foo-can-go-back-Desktop-Firefox/test-failed-1.png
    ------------------------------------------------------------------------------------------------

  2) [Desktop Firefox (no JavaScript)] › foo.spec.ts:3:6 › can go back =============================

    Test timeout of 30000ms exceeded.

    page.goBack: Navigation failed because page was closed!
    =========================== logs ===========================
    waiting for navigation until "load"
      navigated to "https://sandbox.prereview.org/preprints/doi-10.1101-2022.01.13.476201"
    ============================================================

      4 |   await page.goto('https://sandbox.prereview.org/preprints/doi-10.1101-2022.01.13.476201')
      5 |   await page.click('"Write a PREreview"')
    > 6 |   await page.goBack()
        |              ^
      7 |
      8 |   await expect(page.locator('h1')).toHaveText(
      9 |     'PREreviews of “The role of LHCBM1 in non-photochemical quenching in Chlamydomonas reinhardtii”',

        at /app/integration/foo.spec.ts:6:14

    Pending operations:
      - page.goBack at integration/foo.spec.ts:6:14


    attachment #1: video (video/webm) --------------------------------------------------------------
    integration-results/foo-can-go-back-Desktop-Firefox-no-JavaScript-/video.webm
    ------------------------------------------------------------------------------------------------

    attachment #2: trace (application/zip) ---------------------------------------------------------
    integration-results/foo-can-go-back-Desktop-Firefox-no-JavaScript-/trace.zip
    Usage:

        npx playwright show-trace integration-results/foo-can-go-back-Desktop-Firefox-no-JavaScript-/trace.zip

    ------------------------------------------------------------------------------------------------

    attachment #3: screenshot (image/png) ----------------------------------------------------------
    integration-results/foo-can-go-back-Desktop-Firefox-no-JavaScript-/test-failed-1.png
    ------------------------------------------------------------------------------------------------


  2 failed
    [Desktop Firefox] › foo.spec.ts:3:6 › can go back ==============================================
    [Desktop Firefox (no JavaScript)] › foo.spec.ts:3:6 › can go back ==============================
  4 passed (40s)
```

Here's one of the traces: [trace.zip](https://github.com/microsoft/playwright/files/9653873/trace.zip)

It shows the browser has gone back, it's just missing the event to say it has done so.

The real test that fails is https://github.com/PREreview/prereview.org/blob/7be844c4d0e837106f340b0fdb063d141724cd71/integration/posting-a-prereview.spec.ts#L933, (latest CI run https://github.com/PREreview/prereview.org/actions/runs/3133794390 from https://github.com/PREreview/prereview.org/pull/321).

**Comment by mxschmitt** [comment]
I can repro on 1.26 and ToT. Bisecting which exact patch caused it.
