### ISSUE TITLE
[BUG] Playwright Tests not running on Browser stack

### ISSUE THREAD

**Issue by PranaliW** [microsoft/playwright#17649]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Windows
- Node.js version:  16.17.0
- Browser: Chromium, Firefox
- Browser stack : 1.0.6
- Cucumber : 7.8.0  
- Java: JavaSE-11

**Code Snippet**
Attaching Sample Project (Please add Browser stack Username and Password while running test)
[sample.zip](https://github.com/microsoft/playwright/files/9661444/sample.zip)

**Describe the bug**
Getting following Exception while creating browsercontext from browser object.

`com.microsoft.playwright.PlaywrightException: Object doesn't exist: request-context@5698adda8629dc43202aae1c9f6c4f6e
	at com.microsoft.playwright.impl.Connection.getExistingObject(Connection.java:151)
	at com.microsoft.playwright.impl.BrowserContextImpl.<init>(BrowserContextImpl.java:86)
	at com.microsoft.playwright.impl.Connection.createRemoteObject(Connection.java:258)
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:201)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:170)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:107)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:108)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:100)
	at com.microsoft.playwright.impl.BrowserImpl.newContextImpl(BrowserImpl.java:206)
	at com.microsoft.playwright.impl.BrowserImpl.lambda$newContext$1(BrowserImpl.java:115)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:85)
	at com.microsoft.playwright.impl.BrowserImpl.newContext(BrowserImpl.java:115)
	at com.microsoft.playwright.impl.BrowserImpl.newContext(BrowserImpl.java:38)
	at com.microsoft.playwright.Browser.newContext(Browser.java:1120)
	at com.sample.DemoTest.i_open_the_url_on(DemoTest.java:47)
	at ✽.I open the URL "url" on "Chrome"(classpath:features/DemoTest.feature:7)`

**Comment by mxschmitt** [comment]
Since Playwright has no affiliation to BrowserStack, we don't have login credentials and are not able to debug that. I'd recommend to file an issue at the BrowserStack support instead.

Usually for such bugs make sure that the Playwright version matches with the Playwright you are requesting on BrowserStack side.
