### ISSUE TITLE
[BUG]Failed to launch webkit with browser SafariForWebkitDevelopment

### ISSUE THREAD

**Issue by wanghongjuan** [microsoft/playwright#17691]
**Context:**
- Playwright Version: 1.26.1
- Operating System: Mac Monterey 12.5.1
- Node.js version: 16.3
- Browser: SafariForWebkitDevelopment and Safari Technology Preview
- Extra: [any specific details about your environment]

**Code Snippet**

Here is my main code

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await webkit.launch({
    // executablePath: "/Applications/Safari Technology.app/Contents/MacOS/SafariForWebKitDevelopment",
    executablePath: "/Applications/Safari\ Technology\ Preview.app/Contents/MacOS/Safari\ Technology\ Preview",
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  
  await page.goto('https://example.com/', {
    waitUntil: 'load',
    timeout: 2000
  })
  
  await browser.close();
})();
```

**Describe the bug**

The browser can be launched, but it exit after 30000ms, doesn't go to the example page, please refer below error info:

```
webpnp@ah13-32-wp2-lbg general$node test-webkit.js 
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

browserType.launch: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /Applications/Safari Technology Preview.app/Contents/MacOS/Safari Technology Preview --inspector-pipe --no-startup-window
<launched> pid=6632
[pid=6632][err] 2022-09-29 16:05:58.117 com.apple.WebKit.WebContent[6633:822595] XType: com.apple.fonts is not accessible.
[pid=6632][err] 2022-09-29 16:05:58.117 com.apple.WebKit.WebContent[6638:822707] XType: com.apple.fonts is not accessible.
[pid=6632][err] 2022-09-29 16:05:58.117 com.apple.WebKit.WebContent[6636:822676] XType: com.apple.fonts is not accessible.
[pid=6632][err] 2022-09-29 16:05:58.117 com.apple.WebKit.WebContent[6633:822595] XType: XTFontStaticRegistry is enabled.
[pid=6632][err] 2022-09-29 16:05:58.117 com.apple.WebKit.WebContent[6638:822707] XType: XTFontStaticRegistry is enabled.
[pid=6632][err] 2022-09-29 16:05:58.117 com.apple.WebKit.WebContent[6636:822676] XType: XTFontStaticRegistry is enabled.
[pid=6632][err] 2022-09-29 16:05:58.123 com.apple.WebKit.WebContent[6633:822634] ApplePersistence=NO
[pid=6632][err] 2022-09-29 16:05:58.123 com.apple.WebKit.WebContent[6636:822679] ApplePersistence=NO
[pid=6632][err] 2022-09-29 16:05:58.123 com.apple.WebKit.WebContent[6638:822710] ApplePersistence=NO
============================================================
    at /Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/test-webkit.js:4:32
    at Object.<anonymous> (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/test-webkit.js:16:3) {
  name: 'TimeoutError'
}
```

I'm not clear the reason, it there something missing in this issue?

**Comment by mxschmitt** [comment]
It's not possible to use a custom Firefox or WebKit since Playwright relies on custom APIs which were added into the browsers directly, so only Playwright's custom builds are compatible with it.
