### ISSUE TITLE
[BUG] Unclear error message from a failed execution

### ISSUE THREAD

**Issue by clairewu0218** [microsoft/playwright#17817]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Linux
- Node.js version: We use .NET 6.0
- Browser: Chromium
- Extra: N/A

**Code Snippet**

These are the Playwright related code snippet

```C#
public async Task AddScriptTagAsync(string scriptTag, string frameName)
{
    ValidatePage();
    if (string.IsNullOrEmpty(frameName))
    {
        await Page.AddScriptTagAsync(new PageAddScriptTagOptions() { Path = scriptTag });
    }
    else
    {
        await Page.Frame(frameName).AddScriptTagAsync(new FrameAddScriptTagOptions() { Path = scriptTag });
    }
}

public async Task<T> RunJavascriptAsync<T>(string jsExpression)
{
    ValidatePage();

    return await Page.EvaluateAsync<T>(jsExpression);
}

private void ValidatePage()
{
    if (Page == null)
    {
        throw new InvalidOperationException("Page is null, make sure to call GoToUrlAsync first");
    }
}

```

**Describe the bug**

Below is the error log we got. It seems Playwright throw the error, but we are not clear on which operation it throws the error. It usually works and this error rarely happens, but we want to understand why to make our software more stable.

----------------------------------------------------------------------------------------------------
Browser configuration: {"Browser":"Chromium","Device":null,"ScreenWidth":null,"ScreenHeight":null,"ConfigName":null}

C:\repo\PowerApps-TestEngine-main\PowerApps-TestEngine-main\src\PowerAppsTestEngine\bin\Debug\net6.0\.playwright\package\lib\server\dispatchers\dispatcher.js:281
      stack: validMetadata.stack,
                           ^

TypeError: Cannot read properties of undefined (reading 'stack')
    at DispatcherConnection.dispatch (C:\repo\PowerApps-TestEngine-main\PowerApps-TestEngine-main\src\PowerAppsTestEngine\bin\Debug\net6.0\.playwright\package\lib\server\dispatchers\dispatcher.js:281:28)
    at PipeTransport.transport.onmessage (C:\repo\PowerApps-TestEngine-main\PowerApps-TestEngine-main\src\PowerAppsTestEngine\bin\Debug\net6.0\.playwright\package\lib\cli\driver.js:61:57)
    at Immediate.<anonymous> (C:\repo\PowerApps-TestEngine-main\PowerApps-TestEngine-main\src\PowerAppsTestEngine\bin\Debug\net6.0\.playwright\package\lib\protocol\transport.js:89:34)
    at processImmediate (node:internal/timers:464:21)
[Error]: Waiting timed out.

[Error]: Connection closed (Process exited)

Unhandled exception. Microsoft.Playwright.PlaywrightException: Connection closed (Process exited)
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 107
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 479
   at Microsoft.Playwright.Core.BrowserContext.CloseAsync() in /_/src/Playwright/Core/BrowserContext.cs:line 175
   ....(calling stack from our software)

**Comment by yury-s** [comment]
Can you provide a minimal test case that we can run locally and reproduce the error?
