### ISSUE TITLE
[BUG] RangeError [ERR_OUT_OF_RANGE]: The value of "msecs" is out of range.

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#18214]
I've got this error while running `npm i` in playwright checkout.
```
npm ERR! Chromium 107.0.5304.36 (playwright build v1030) downloaded to /home/yurys/.cache/ms-playwright/chromium-1030
npm ERR! Downloading FFMPEG playwright build v1007...
npm ERR! Downloading FFMPEG playwright build v1007...                                                                                        
npm ERR! Downloading FFMPEG playwright build v1007... 
npm ERR! RangeError [ERR_OUT_OF_RANGE]: The value of "msecs" is out of range. It must be a non-negative finite number. Received NaN
npm ERR!     at new NodeError (node:internal/errors:388:5)                                                                                   
npm ERR!     at getTimerDuration (node:internal/timers:391:11)                                                                               
npm ERR!     at ClientRequest.setTimeout (node:_http_client:877:11)                                                                          
npm ERR!     at httpRequest (/home/yurys/playwright/packages/playwright-core/lib/common/netUtils.js:111:13)                            
npm ERR!     at downloadFile (/home/yurys/playwright/packages/playwright-core/lib/server/registry/oopDownloadMain.js:39:29)
npm ERR!     at main (/home/yurys/playwright/packages/playwright-core/lib/server/registry/oopDownloadMain.js:129:9)
npm ERR!     at Object.<anonymous> (/home/yurys/playwright/packages/playwright-core/lib/server/registry/oopDownloadMain.js:146:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1112:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:988:32) {
npm ERR!   code: 'ERR_OUT_OF_RANGE'
npm ERR! }                                                                                                                                   
```

**Comment by aslushnikov** [comment]
Looks like incomplete compilation of the source code; closing as won't fix for now.
