### ISSUE TITLE
[REGRESSION]: Open PDF fails in firefox

### ISSUE THREAD

**Issue by unkloud** [microsoft/playwright#18430]
**Context:**
- GOOD Playwright Version: 1.25.2
- BAD Playwright Version: 1.26.0, 1.26.1, 1.27.0, 1.27.1
- Operating System: Microsoft Windows [Version 10.0.19045.2130]
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```python
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.firefox.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://norvig.com/unify-bug.pdf")
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
```

**Describe the bug**

***Result with 1.25.2***
```
Process finished with exit code 0
```

***Result with versions newer than 1.25.2***
```
Traceback (most recent call last):
  File "sample1.py", line 14, in <module>
    run(playwright)
  File "sample1.py", line 8, in run
    page.goto("https://norvig.com/unify-bug.pdf")
  File "site-packages\playwright\sync_api\_generated.py", line 7430, in goto
    self._sync(
  File "site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "site-packages\playwright\_impl\_page.py", line 494, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "site-packages\playwright\_impl\_frame.py", line 136, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "site-packages\playwright\_impl\_connection.py", line 387, in wrap_api_call
    return await cb()
  File "site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Download is starting
=========================== logs ===========================
navigating to "https://norvig.com/unify-bug.pdf", waiting until "load"
============================================================
```

**Comment by aslushnikov** [comment]
@unkloud This was a bug fix. Firefox was never loading PDFs, it was downloading them. We now throw an error indicating this behavior, which aligns with headless Chromium behavior in this usecase.

What are your expectations though?

**Comment by unkloud** [comment]
Hi @aslushnikov , thanks for the reply. 

> @unkloud This was a bug fix. Firefox was never loading PDFs, it was downloading them. 
> We now throw an error indicating this behavior, which aligns with headless Chromium behavior in this usecase. 


Well, the implementation of PDF viewer is very different in those two browsers. In Firefox it was handled by `pdf.js` and rendered as html5. This is the best [article](https://hacks.mozilla.org/2021/10/implementing-form-filling-and-accessibility-in-the-firefox-pdf-viewer/) I can find to describe the internal design, where in chromium everything is handled by the pdf [plugin](https://chromium.googlesource.com/chromium/src/+/main/pdf).

So are the networking behavior, in firefox the payload of the PDF is captured as response body and can be seen from developer tool, where in my edge(sorry I don't have chrome installed), it can not be found in the captured response from developer tool, the body size reported is not the pdf's size either.

To me to force the firefox behave like headless chromium is not only counter-intuitive, but also not very well justified, according to the [implementation](https://github.com/microsoft/playwright-python/blob/main/playwright/sync_api/_generated.py#L3045), `Error` will be thrown when the main resource is failed to load, I'd argue in firefox the PDF resource is loaded and rendered as part of the DOM, hence should have `request`, `response`, and `requestfinished` event emitted, the `download` event is appropriated for chromium as PDF is rendered in a different process, but that's not how firefox handle PDF resource and it shouldn't be forced to align to chromium.

> What are your expectations though?

A stable pdf downloading experience. 

I tested using `download` event with both firefox/chromium, in either headless or non-headless mode it seems that the download randomly fails. For large pdf file it is almost failing every time.

In the contrast, when I am using firefox with version 1.5.2, it is rock solid, I didn't test with chromium though. For me the experience is much better in older version, definitely feels like a regression. Hope it makes sense to you.

```python
from pathlib import Path

from playwright.sync_api import Playwright, sync_playwright, Request, Download, Error


def request_started(request: Request):
    print(f"REQUEST_STARTED: {request.url=}")


def request_finished(request: Request):
    print(f"REQUEST_FINISHED: {request.url=}, {len(request.response().body())=}")


def download_started(download: Download):
    local_pdf = Path(__file__).parent / download.suggested_filename
    print(f"DOWNLOAD_STARTED: {download.url=}, {download.suggested_filename=}, {local_pdf=}")
    download.save_as(local_pdf)


def run(playwright: Playwright, browse_name: str, headless: bool) -> None:
    with getattr(playwright, browse_name).launch(headless=headless) as browser:
        with browser.new_context() as context:
            with context.new_page() as page:
                page.on("request", request_started)
                page.on("requestfinished", request_finished)
                page.on("download", download_started)
                # Please note that the PDF cannot be saved locally with/without the error handling code, in both head/headless mode
                try:
                    page.goto("https://norvig.com/unify-bug.pdf", wait_until="networkidle")
                except Error as error:
                    print(error)


with sync_playwright() as playwright:
    # print("*" * 10 + "firefox (headless)" + "*" * 10)
    # run(playwright, "firefox", headless=True)
    # print("*" * 10 + "firefox" + "*" * 10)
    # print()
    # print("*" * 10 + "chromium(headless)" + "*" * 10)
    # run(playwright, "chromium", headless=True)
    # print("*" * 10 + "chromium" + "*" * 10)
    # print()
    # print("*" * 10 + "firefox" + "*" * 10)
    # run(playwright, "firefox", headless=False)
    # print("*" * 10 + "firefox" + "*" * 10)
    # print()

    print("*" * 10 + "chromium(headless)" + "*" * 10)
    run(playwright, "chromium", headless=True)
    print("*" * 10 + "chromium" + "*" * 10)
    print()
    print("*" * 10 + "chromium" + "*" * 10)
    run(playwright, "chromium", headless=False)
    print("*" * 10 + "chromium" + "*" * 10)
```

**Comment by yury-s** [comment]
The behavior when navigation turns into a download varies between browsers and we have no plans to hide that by unifying the erorrs (see [this test](https://github.com/microsoft/playwright/blob/6d491f928d5a15481228839d14369f006e6d31f1/tests/library/download.spec.ts#L65-L76) for the current behavior).

>A stable pdf downloading experience.
>
> I tested using download event with both firefox/chromium, in either headless or non-headless mode it seems that the download randomly fails. For large pdf file it is almost failing every time.

The reason for that is you wait for the download to finish inside event listener `page.on("download", download_started)` which does not prevent the program from finishing before the download completes. Try changing the code as described in [our docs](https://playwright.dev/python/docs/downloads) so that it blocks until the download is finished:

```py

def run(playwright: Playwright, browse_name: str, headless: bool) -> None:
    with getattr(playwright, browse_name).launch(headless=headless) as browser:
        with browser.new_context() as context:
            with context.new_page() as page:
                page.on("request", request_started)
                page.on("requestfinished", request_finished)
                with page.expect_download() as download_info:
                  try:
                      page.goto("https://norvig.com/unify-bug.pdf", wait_until="networkidle")
                  except Error as error:
                      print(error)
                download = download_info.value
                download_started(download)
```

Here is a javascript code snippet that loads 14Mb+ pdf file without any issues:

```js
import { expect, test } from '@playwright/test';
import fs from 'fs';

test('test', async ({ page }) => {
  const [download, r] = await Promise.all([
    page.waitForEvent('download'),
    page.goto('https://html.spec.whatwg.org/print.pdf').catch(e => e)
  ])
  console.log(r);
  const path = await download.path();
  const stat = await fs.promises.stat(path!);
  expect(stat.size).toBe(14426967);
});
```
