### ISSUE TITLE
[Question] chrome.connect or firefox.connect using public ip address not 127.0.0.1

### ISSUE THREAD

**Issue by ssemrau** [microsoft/playwright#1844]
Hi,

I'm creating firefoxserver

`
const browserServer = await firefox.launchServer({
    headless: false});
`

and then trying to connect to it

`
var browser = await firefox.connect({ 
    wsEndpoint: url });
`

where url is ip address accessible in local network.

I get the following error
`
(node:23188) UnhandledPromiseRejectionWarning: Error: Protocol error (Browser.enable): Target closed.
    at C:\GitHub\remote-browser\node_modules\playwright-core\lib\firefox\ffConnection.js:48:63
    at new Promise (<anonymous>)
    at FFConnection.send (C:\GitHub\remote-browser\node_modules\playwright-core\lib\firefox\ffConnection.js:47:16)
    at Function.connect (C:\GitHub\remote-browser\node_modules\playwright-core\lib\firefox\ffBrowser.js:53:26)
    at C:\GitHub\remote-browser\node_modules\playwright-core\lib\server\firefox.js:123:42
    at WebSocket.<anonymous> (C:\GitHub\remote-browser\node_modules\playwright-core\lib\transport.js:106:78)
    at WebSocket.onOpen (C:\GitHub\remote-browser\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:311:20)
    at WebSocket.setSocket (C:\GitHub\remote-browser\node_modules\ws\lib\websocket.js:170:10)
    at ClientRequest.<anonymous> (C:\GitHub\remote-browser\node_modules\ws\lib\websocket.js:665:15)
(node:23188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id:
1)
(node:23188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

For chrome I get this error
`
(node:28116) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setAutoAttach): Target closed.
    at C:\GitHub\remote-browser\node_modules\playwright-core\lib\chromium\crConnection.js:123:63
    at new Promise (<anonymous>)
    at CRSession.send (C:\GitHub\remote-browser\node_modules\playwright-core\lib\chromium\crConnection.js:122:16)
    at CRSession.<anonymous> (C:\GitHub\remote-browser\node_modules\playwright-core\lib\helper.js:87:31)
    at Function.connect (C:\GitHub\remote-browser\node_modules\playwright-core\lib\chromium\crBrowser.js:59:27)
    at C:\GitHub\remote-browser\node_modules\playwright-core\lib\server\chromium.js:111:42
    at WebSocket.<anonymous> (C:\GitHub\remote-browser\node_modules\playwright-core\lib\transport.js:106:78)
    at WebSocket.onOpen (C:\GitHub\remote-browser\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:311:20)
    at WebSocket.setSocket (C:\GitHub\remote-browser\node_modules\ws\lib\websocket.js:170:10)
  -- ASYNC --
    at CRSession.<anonymous> (C:\GitHub\remote-browser\node_modules\playwright-core\lib\helper.js:66:23)
    at Function.connect (C:\GitHub\remote-browser\node_modules\playwright-core\lib\chromium\crBrowser.js:59:27)
    at C:\GitHub\remote-browser\node_modules\playwright-core\lib\server\chromium.js:111:42
    at WebSocket.<anonymous> (C:\GitHub\remote-browser\node_modules\playwright-core\lib\transport.js:106:78)
    at WebSocket.onOpen (C:\GitHub\remote-browser\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:311:20)
    at WebSocket.setSocket (C:\GitHub\remote-browser\node_modules\ws\lib\websocket.js:170:10)
    at ClientRequest.<anonymous> (C:\GitHub\remote-browser\node_modules\ws\lib\websocket.js:665:15)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketOnData (_http_client.js:510:11)
(node:28116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id:
1)
(node:28116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Any hints? 
I work on Win10
Full repo to reproduce: https://github.com/ssemrau/remote-browser

**Comment by pavelfeldman** [comment]
Which url do you use?

**Comment by ssemrau** [comment]
As you can see in attached repo there are 3 major blocks:
1. browser launched using launchServer which is returning wsEndpoint in format ws://127.0.0.1:port/guid
2. proxy that is routing ws traffic between ws://127.0.0.1:port/guid and ws://192.168.1.171:8001 (this ip is in my case)
3. connector that is using connect({wsEndpoint}) method to connect to url

And the url could be:
1. ws://127.0.0.1:port/guid which works fine, but is not much usefull as browser-as-server and connector are on the same machine
2. ws://12.168.1.171:8001 which throws exception pasted above, and would be very usefull to have possibility to connect connector from machine A to browser-as-server on machine B which is my goal

P.S.
All works fine if I use puppeteer instead of playwright

**Comment by pavelfeldman** [comment]
> proxy that is routing ws traffic between ws://127.0.0.1:port/guid and ws://192.168.1.171:8001 (this ip is in my case)

I was helping someone resolve a similar issue. Make sure you are using the proxy the right way: https://github.com/microsoft/playwright/issues/1081#issuecomment-590960783

> All works fine if I use puppeteer instead of playwright

Puppeteer has no `guid` that serves as a security token in case of Firefox. As a result any web page on the machine can open web socket to `ws://localhost:8001` and gain full control of the browser...

**Comment by ssemrau** [comment]
Indeed adding `ignorePath: true` to my proxy

`
var proxy = await httpProxy
    .createServer({
        target:       wsEndPoint,
        ws:           true,
        localAddress: host,
        ignorePath: true
    }).listen(port);
`

solved the issue, 

@pavelfeldman thanks for help!
