### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'childFrames')

### ISSUE THREAD

**Issue by mybdye** [microsoft/playwright#18489]
**Context:**
- Playwright Version: playwright-1.27.1
- Operating System: Github Action Image: ubuntu-22.04 Version: 20221024.1
- Python version: 3.10.6
- Browser: Firefox
- Extra: [any specific details about your environment]

**Code Snippet**
```python
with sync_playwright() as p:
    browser = p.firefox.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto(xxxx)
```

**Describe the bug**

Happens in Firefox half the time; Chromium and Webkit work fine
Run `xvfb-run python3 ./main.py`

Output here
```
/home/runner/.local/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:392
    for (const child of frame.childFrames()) this._removeFramesRecursively(child);
                              ^
TypeError: Cannot read properties of undefined (reading 'childFrames')
    at FrameManager.removeChildFramesRecursively (/home/runner/.local/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:392:31)
    at FrameManager.frameCommittedNewDocumentNavigation (/home/runner/.local/lib/python3.10/site-packages/playwright/driver/package/lib/server/frames.js:191:10)
    at FFPage._onNavigationCommitted (/home/runner/.local/lib/python3.10/site-packages/playwright/driver/package/lib/server/firefox/ffPage.js:2[12](https://github.com/mybdye/H-W-PlaywrightBase/actions/runs/3365962791/jobs/5581974256#step:5:13):30)
    at FFSession.emit (node:events:5[13](https://github.com/mybdye/H-W-PlaywrightBase/actions/runs/3365962791/jobs/5581974256#step:5:14):28)
    at /home/runner/.local/lib/python3.10/site-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:248:41
```

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.
