### ISSUE TITLE
[BUG] "locator.check: Target closed" occurs when running test in WebKit

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#18552]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac OS (M1 Pro)
- Node.js version: 16.16.0
- Browser: WebKit
- Extra:

**Code Snippet**

I have a demo repo, but it isn't in Github or anything. I can send it through wetransfer.

**Describe the bug**

This demo will run fine in Chrome (it fails in Firefox, but for another reason that I have a separate issue open for), but it will fail in Chrome when trying to check a box. The trace shows the page going blank and the error is: "locator.check: Target closed".
It does not fail when run in headed mode, only headless.

Please let me know what email to send the project file to. Thank you!

Error log that was captured:
```
jeaton@Joes-MBP Bobb % DEBUG=pw:browser npx playwright test --project=webkit

Running 1 test using 1 worker

  pw:browser <launching> /Users/jeaton/Library/Caches/ms-playwright/chromium-1029/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/qc/h9qm30hx48gfflk9qzx1wygm0000gn/T/playwright_chromiumdev_profile-NM482j --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=34517 +4ms
  pw:browser [pid=34517][err] objc[34518]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x24f071b50) and /Users/jeaton/Library/Caches/ms-playwright/chromium-1029/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/107.0.5304.29/Libraries/libGLESv2.dylib (0x10b314230). One of the two will be used. Which one is undefined. +205ms
  pw:browser [pid=34517][err] [1103/152903.476035:ERROR:gl_utils.cc(319)] [.WebGL-0x11800540300]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels +3s
  pw:browser [pid=34517][err] [1103/152904.200550:ERROR:gl_utils.cc(319)] [.WebGL-0x11800540300]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels +724ms
  pw:browser [pid=34517] <gracefully close start> +69ms
  pw:browser [pid=34517] <process did exit: exitCode=0, signal=null> +15ms
  pw:browser [pid=34517] starting temporary directories cleanup +0ms
  pw:browser [pid=34517] finished temporary directories cleanup +1ms
  pw:browser [pid=34517] <gracefully close end> +0ms
     1 [webkit] › test-4.spec.ts:7:1 › Send Document To Review
  pw:browser <launching> /Users/jeaton/Library/Caches/ms-playwright/webkit-1724/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=34534 +5ms
  ✘  1 [webkit] › test-4.spec.ts:7:1 › Send Document To Review (30s)
  pw:browser [pid=34534][err] 2022-11-03 15:29:04.858 com.apple.WebKit.WebContent.Development[34542:3796920] ApplePersistence=NO +114ms
  pw:browser [pid=34534][err] 2022-11-03 15:29:12.221 com.apple.WebKit.WebContent.Development[34547:3797011] ApplePersistence=NO +7s
  pw:browser [pid=34534][err] 2022-11-03 15:29:15.251 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x12386e710> - changing property contentsScale in transform-only layer, will have no effect +3s
  pw:browser [pid=34534][err] 2022-11-03 15:29:15.251 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x12386e710> - changing property rasterizationScale in transform-only layer, will have no effect +1ms
  pw:browser [pid=34534][err] 2022-11-03 15:29:17.994 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x122fb3e30> - changing property contentsScale in transform-only layer, will have no effect +3s
  pw:browser [pid=34534][err] 2022-11-03 15:29:17.994 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x122fb3e30> - changing property rasterizationScale in transform-only layer, will have no effect +0ms
  pw:browser [pid=34534][err] 2022-11-03 15:29:19.848 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x17fb1a9e0> - changing property contentsScale in transform-only layer, will have no effect +2s
  pw:browser [pid=34534][err] 2022-11-03 15:29:19.848 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x17fb1a9e0> - changing property rasterizationScale in transform-only layer, will have no effect +1ms
  pw:browser [pid=34534][err] 2022-11-03 15:29:20.110 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x104d11cc0> - changing property contentsScale in transform-only layer, will have no effect +262ms
  pw:browser [pid=34534][err] 2022-11-03 15:29:20.111 com.apple.WebKit.WebContent.Development[34547:3797007] <CATransformLayer: 0x104d11cc0> - changing property rasterizationScale in transform-only layer, will have no effect +0ms
  pw:browser [pid=34534] <gracefully close start> +15s
  pw:browser [pid=34534] <process did exit: exitCode=0, signal=null> +13ms
  pw:browser [pid=34534] starting temporary directories cleanup +0ms
  pw:browser [pid=34534] finished temporary directories cleanup +16ms
  pw:browser [pid=34534] <gracefully close end> +0ms


  1) [webkit] › test-4.spec.ts:7:1 › Send Document To Review =======================================

    Test timeout of 30000ms exceeded.

    locator.check: Target closed
    =========================== logs ===========================
      waiting for frame "id=WizardPanelPropertiesEdit_Iframe"
      selector resolved to visible <iframe width="100%" height="100%" marginwidth="0" frame…></iframe>
      waiting for frame "id=UserFinderFrame"
      selector resolved to visible <iframe height="" width="100%" align="NotSet" frameborde…></iframe>
    waiting for selector "id=WizardPanelPropertiesEdit_Iframe >> internal:control=enter-frame >> id=UserFinderFrame >> internal:control=enter-frame >> xpath=//div[@title='One, Reviewer']//input[@type='checkbox']"
      waiting for frame "id=WizardPanelPropertiesEdit_Iframe"
    ============================================================

       at ../content.ts:275

      273 |    */
      274 |   async selectReviewerCheckbox(reviewersName: string) {
    > 275 |     await this.propertiesWizardSelectionCheckbox(reviewersName).check();
          |                                                                 ^
      276 |   }
      277 |
      278 |   /**

        at PolicyTechDocumentPage.selectReviewerCheckbox (/Users/jeaton/Desktop/Bobb/content.ts:275:65)
        at /Users/jeaton/Desktop/Bobb/tests/test-4.spec.ts:22:32

    attachment #1: trace (application/zip) ---------------------------------------------------------
    test-results/test-4-Send-Document-To-Review-webkit/trace.zip
    Usage:

        npx playwright show-trace test-results/test-4-Send-Document-To-Review-webkit/trace.zip

    ------------------------------------------------------------------------------------------------

  Slow test file: [webkit] › test-4.spec.ts (30s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [webkit] › test-4.spec.ts:7:1 › Send Document To Review ========================================
```

**Comment by yury-s** [comment]
Did you try collecting traces for headless/headful mode and Chromium/WebKit to see if the DOM is actually the same? It may well be that the server returns different data depending on the browser. I would start with checking that.

You can send the repro to the email in my github profile.

**Comment by eatonjl** [comment]
@yury-s That repo has been sent to you via wetransfer.

**Comment by yury-s** [comment]
> @yury-s That repo has been sent to you via wetransfer.

Thank you. I tried to run it but the config says `baseURL: process.env.BASE_URL,` what URL should I set?

**Comment by eatonjl** [comment]
@yury-s My apologies. That folder should have contained the .env file. I emailed you the contents of the .env file so you can have the URL and login credentials.
