### ISSUE TITLE
[Question] Unable to build Playwright. Any suggestions on what to check?

### ISSUE THREAD

**Issue by EdmundasD** [microsoft/playwright#18673]
Hi folks! Trying to build Playwright locally but continue to encounter issues. Nothing above v1.21.1 works. Any suggestions on what to check if someone has experienced something similar?

```
Node: v16.14.2
NPM: v8.5.0
```

Flow:
```
git clone https://github.com/microsoft/playwright
cd playwright
npm ci
npm run build
```

Error:
```
> utils-bundle@0.0.1 esbuild
> node build.js "--minify"

✘ [ERROR] Could not resolve "colors/safe"

    src/utilsBundleImpl.ts:17:26:
      17 │ import colorsLibrary from 'colors/safe';
         ╵                           ~~~~~~~~~~~~~

  You can mark the path "colors/safe" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "debug"

    src/utilsBundleImpl.ts:20:25:
      20 │ import debugLibrary from 'debug';
         ╵                          ~~~~~~~

  You can mark the path "debug" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "proxy-from-env"

    src/utilsBundleImpl.ts:23:31:
      23 │ export { getProxyForUrl } from 'proxy-from-env';
         ╵                                ~~~~~~~~~~~~~~~~

  You can mark the path "proxy-from-env" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "https-proxy-agent"

    src/utilsBundleImpl.ts:25:32:
      25 │ export { HttpsProxyAgent } from 'https-proxy-agent';
         ╵                                 ~~~~~~~~~~~~~~~~~~~

  You can mark the path "https-proxy-agent" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "jpeg-js"

    src/utilsBundleImpl.ts:27:24:
      27 │ import jpegLibrary from 'jpeg-js';
         ╵                         ~~~~~~~~~

  You can mark the path "jpeg-js" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "proper-lockfile"

    src/utilsBundleImpl.ts:30:28:
      30 │ import lockfileLibrary from 'proper-lockfile';
         ╵                             ~~~~~~~~~~~~~~~~~

  You can mark the path "proper-lockfile" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "mime"

    src/utilsBundleImpl.ts:33:24:
      33 │ import mimeLibrary from 'mime';
         ╵                         ~~~~~~

  You can mark the path "mime" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "minimatch"

    src/utilsBundleImpl.ts:36:29:
      36 │ import minimatchLibrary from 'minimatch';
         ╵                              ~~~~~~~~~~~

  You can mark the path "minimatch" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "ms"

    src/utilsBundleImpl.ts:39:22:
      39 │ import msLibrary from 'ms';
         ╵                       ~~~~

  You can mark the path "ms" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "pngjs"

    src/utilsBundleImpl.ts:42:20:
      42 │ export { PNG } from 'pngjs';
         ╵                     ~~~~~~~

  You can mark the path "pngjs" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "commander"

    src/utilsBundleImpl.ts:44:24:
      44 │ export { program } from 'commander';
         ╵                         ~~~~~~~~~~~

  You can mark the path "commander" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "progress"

    src/utilsBundleImpl.ts:46:28:
      46 │ import progressLibrary from 'progress';
         ╵                             ~~~~~~~~~~

  You can mark the path "progress" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "rimraf"

    src/utilsBundleImpl.ts:49:26:
      49 │ import rimrafLibrary from 'rimraf';
         ╵                           ~~~~~~~~

  You can mark the path "rimraf" as external to exclude it from the bundle, which will remove this
  error.

✘ [ERROR] Could not resolve "socks-proxy-agent"

    src/utilsBundleImpl.ts:52:32:
      52 │ export { SocksProxyAgent } from 'socks-proxy-agent';
         ╵                                 ~~~~~~~~~~~~~~~~~~~

  You can mark the path "socks-proxy-agent" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "stack-utils"

    src/utilsBundleImpl.ts:54:30:
      54 │ import StackUtilsLibrary from 'stack-utils';
         ╵                               ~~~~~~~~~~~~~

  You can mark the path "stack-utils" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "ws"

    src/utilsBundleImpl.ts:58:61:
      58 │ import wsLibrary, { WebSocketServer, Receiver, Sender } from 'ws';
         ╵                                                              ~~~~

  You can mark the path "ws" as external to exclude it from the bundle, which will remove this
  error.

Error: Build failed with 16 errors:
src/utilsBundleImpl.ts:17:26: ERROR: Could not resolve "colors/safe"
src/utilsBundleImpl.ts:20:25: ERROR: Could not resolve "debug"
src/utilsBundleImpl.ts:23:31: ERROR: Could not resolve "proxy-from-env"
src/utilsBundleImpl.ts:25:32: ERROR: Could not resolve "https-proxy-agent"
src/utilsBundleImpl.ts:27:24: ERROR: Could not resolve "jpeg-js"
...
    at failureErrorWithLog (/playwright/node_modules/esbuild/lib/main.js:1624:15)
    at /playwright/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/playwright/node_modules/esbuild/lib/main.js:1179:65)
    at buildResponseToResult (/playwright/node_modules/esbuild/lib/main.js:1264:7)
    at /playwright/node_modules/esbuild/lib/main.js:1377:14
    at /playwright/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/playwright/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/playwright/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "colors/safe"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "debug"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "proxy-from-env"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "https-proxy-agent"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "jpeg-js"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "proper-lockfile"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "mime"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "minimatch"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "ms"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "pngjs"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "commander"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "progress"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "rimraf"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "socks-proxy-agent"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "stack-utils"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "ws"'
    }
  ],
  warnings: []
}

```

**Comment by yury-s** [comment]
Try doing a fresh clone and repeat the steps, it has something to do with your environment (perhaps checkout process was aborted or there are previous artifacts etc). You can we use these steps on our CI (e.g [this run](https://github.com/microsoft/playwright/actions/runs/3430320862/jobs/5717141256)) and works fine.
