### ISSUE TITLE
[Question] offline pc (win7) wanna to install playwright but excepition 

### ISSUE THREAD

**Issue by 1355692540** [microsoft/playwright#18864]
1:my company pc (windows7)  offline ，l want to use playwright  by java 
2:  pom ,already copy jar into company pc's maven repository
<dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.20.0</version>
  </dependency>
3:l need to get binary chronium 。 so l copy the folder(**/local/ms-playwright/*) form my own pc (win10 which can surely start playwright) 

4:here is the code and exception ,what's wrong ?

    public static void main(String[] args) {
        Map<String, String> map = new HashMap();
       
        map.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1");
    
        map.put("PLAYWRIGHT_BROWSERS_PATH", "C:\\Users\\zhangzhongyuan\\AppData\\Local\\ms-playwright");

        Playwright playwright = Playwright.create(new Playwright.CreateOptions().setEnv(map));  // line 28 exception
        Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions());
        BrowserContext browserContext = browser.newContext();
        Page page = browserContext.newPage();
        page.navigate("http://10.69.9.14:1666/");

    }
	
	---
	Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:157)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:105)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
	at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:76)
	at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:138)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:47)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at AutoTest.main(AutoTest.java:28)
Caused by: java.io.EOFException
	at com.microsoft.playwright.impl.ReaderThread.readIntLE(PipeTransport.java:110)
	at com.microsoft.playwright.impl.ReaderThread.readMessage(PipeTransport.java:139)
	at com.microsoft.playwright.impl.ReaderThread.run(PipeTransport.java:125)

**Comment by pavelfeldman** [comment]
Looks like Playwright could not start the browser you copied. There isn't much we can do here since you were manually copying parts of the product over.

**Comment by 1355692540** [comment]
> Playwright 似乎无法启动您复制的浏览器。由于您是手动复制产品的某些部分，因此我们在这里无能为力。

so how can l install chromium offline ?  l can start the chromium if run xx/local/ms-playwright/xx-chromium/chrom-win/chrome.exe 。the problem  seems strange

**Comment by pavelfeldman** [comment]
All we have to say about it is here: https://playwright.dev/docs/next/browsers#managing-browser-binaries

**Comment by mxschmitt** [comment]
Windows 7 is not supported by Playwright, we recommend upgrading to e.g. 8.1, 10 or 11.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
