### ISSUE TITLE
[Question]I got a mistake when I run my python with playwright in the Oracle Cloud.

### ISSUE THREAD

**Issue by tylrr123** [microsoft/playwright#18877]
- Playwright Version: [ 1.27.1 ]
- Operating System: [ Red Hat Enterprise 8.6 (Ootpa) aarch64(Py3.7.8)      ]
- Pythonp version: [Python 3.9.15]
- Browser: [ Chromium]

I got a mistake when I run my python with playwright in the Oracle Cloud.
How should I install the missing dependencies ?
Thanks for your help.

`
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgbm.so.1                                       ║
║     libdrm.so.2                                       ║
║     libasound.so.2                                  ║
╚══════════════════════════════════════════════════════╝ 
 
^CTraceback (most recent call last):
  File "/home/opc/scrape/main.py", line 28, in <module>
    trans_result_list = deepl_playwright.get_translate(f'{i[3]}###{i[5]}').split('###')
  File "/home/opc/scrape/deepl_playwright.py", line 124, in get_translate
    with sync_playwright() as playwright:
  File "/usr/local/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py", line 87, in __enter__
    dispatcher_fiber.switch()
  File "/usr/local/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py", line 67, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

`

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
