### ISSUE TITLE
[Question] TypeError: _test.request.get is not a function

### ISSUE THREAD

**Issue by michelle-choi1** [microsoft/playwright#19012]
related to [#10787](https://github.com/microsoft/playwright/issues/10787), but not sure if it's a bug since it might be my user error-
I wanted to put api calls into a helper function file like this:

```js
import { request } from '@playwright/test'

async function apiCall(type, url, callData) {
    let call;
    if (type === 'get') {
        call = await request.get(url, {
            headers: {'Authorization': process.env.API_AUTHENTICATION}
        });
    } else if (type === 'put') {
        call = await request.put(url, {
            data: callData,
            headers: {'Authorization': process.env.API_AUTHENTICATION}
        });
    } else if (type === 'post') {
        call = await request.post(url, {
            data: callData,
            headers: {'Authorization': process.env.API_AUTHENTICATION}
        });
    } else if (type === 'delete') {
        call = await request.delete(url, {
            headers: {'Authorization': process.env.API_AUTHENTICATION}
        });
    }
    
    console.log(await call.json());
    expect(call.ok()).toBeTruthy();
    expect(call.status()).toBe(200);
    return call;
}
export { apiCall };
```

and call it here in this test file:
```js
import { test, expect } from '@playwright/test'
import { apiCall } from '../../helper-functions'

...

test.only('add-ons load correctly', async ({ page, request }) => {

...

    const getApiCallAddOns = apiCall('get', `${process.env.API_URL}/products/${process.env.STOREID}/?type=addon&status=enabled&sort=`);

...

});
```

and this is the error I'm getting: `TypeError: _test.request.get is not a function`
```
  1) [Staging] › wip-tests/wip-checkout/add-ons.spec.js:10:6 › add-ons load correctly ==============

    TypeError: _test.request.get is not a function

      19 |     
    > 20 |     const getApiCallAddOns = apiCall('get', `${process.env.API_URL}/products/${process.env.STOREID}/?type=addon&status=enabled&sort=`);
         |                              ^
      21 |

        at apiCall (...playwright-tests/helper-functions.js:6:30)
        at ...playwright-tests/wip-tests/wip-checkout/add-ons.spec.js:20:30
        at runMicrotasks (<anonymous>)
        at runNextTicks (node:internal/process/task_queues:61:5)
        at processImmediate (node:internal/timers:437:9)
        at /Users/mchoi/lv-tests/node_modules/@playwright/test/lib/workerRunner.js:426:9
        at TestInfoImpl._runFn (.../node_modules/@playwright/test/lib/testInfo.js:166:7)
        at .../node_modules/@playwright/test/lib/workerRunner.js:376:26
        at TimeoutRunner.run (.../node_modules/playwright-core/lib/utils/timeoutRunner.js:53:14)
        at TimeoutManager.runWithTimeout (.../node_modules/@playwright/test/lib/timeoutManager.js:73:7)
        at TestInfoImpl._runWithTimeout (.../node_modules/@playwright/test/lib/testInfo.js:154:26)
        at WorkerRunner._runTest (.../node_modules/@playwright/test/lib/workerRunner.js:356:5)
        at WorkerRunner.runTestGroup (.../node_modules/@playwright/test/lib/workerRunner.js:218:11)
        at process.<anonymous> (.../node_modules/@playwright/test/lib/worker.js:88:5)
```

is it possibly because of the `await` placements? Or should i be setting up my helper function a little bit differently?

thanks so much!!

**Comment by michelle-choi1** [comment]
hi @dgozman i was hoping you might be able to see this! since you were the one who responded on the similar issue. thanks!!

**Comment by dgozman** [comment]
@michelle-choi1 You import an [`APIRequest`](https://playwright.dev/docs/api/class-apirequest) instance. Instead, you better use the `request` fixture, which is an [`APIRequestContext`](https://playwright.dev/docs/api/class-apirequestcontext) instance that actually has `get` and other methods.

```ts
// Accept "request" parameter in the helper.
async function apiCall(request, type, url, callData) {
  // ...
}
export { apiCall };
```

```ts
import { test, expect } from '@playwright/test'
import { apiCall } from '../../helper-functions'

test.only('add-ons load correctly', async ({ page, request }) => {
    // Pass "request" to the helper.
    const getApiCallAddOns = apiCall(request, 'get', `${process.env.API_URL}/products/${process.env.STOREID}/?type=addon&status=enabled&sort=`);
});
```

Let me know if that helps.

**Comment by michelle-choi1** [comment]
Thank you @dgozman!! that works!!
i made a few changes according to what you suggested:
added expect also to address error `ReferenceError: expect is not defined`—
```js
// Accept "expect", "request" parameter in the helper.
async function apiCall(expect, request, type, url, callData) {
  // ...
}
export { apiCall };
```

added await here too to address error message `apiRequestContext.get: Request context disposed.`—
```js
const getApiCallAddOns = await apiCall(expect, request, 'get', `${process.env.API_URL}/products/${process.env.STOREID}/?type=addon&status=enabled&sort=`);
```

**Comment by michelle-choi1** [comment]
not sure if this is the right procedure, but i'm going to close this issue now as it's been resolved!
