### ISSUE TITLE
[BUG] Protocol error (Page.enable): Browser closed

### ISSUE THREAD

**Issue by MuhammadM1998** [microsoft/playwright#19033]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows 10 10.0.22621
- Node.js version: 14.21.1
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { chromium } from 'playwright-core';
import bundledChromium from 'chrome-aws-lambda';

export default async function playwright(req, res) {
  try {
    // Setup
    const browser = await Promise.resolve(bundledChromium.executablePath).then(
      (executablePath) => {
        if (!executablePath) {
          // local execution
          return chromium.launch({ headless: false });
        }
        return chromium.launch({
          headless: false,
          executablePath,
          args: ['--no-sandbox', '--no-zygote'],
        });
      }
    );

    // Scraping
    const url = 'https://google.com/';
    const page = await browser.newPage();
    await page.goto(url);
    await browser.close();

    // Returning data
    res.status(200).send('Works!');
  } catch (error) {
    console.log(error);
    res.status(500).send(error);
  }
}

```

**Describe the bug**

I'm deploying a playwright minimal starter on vercel (I'm trying to get it working first thenn I'll put the logic) 
I'm following the instructions described here https://github.com/microsoft/playwright/issues/2321#issuecomment-966476038
It seems to work a bit but now I get this error at vercel log

```
Function Status:500
Edge Status:500
Duration:4514.31 ms
Init Duration: 184.41 ms
Memory Used:462 MB
ID:fra1::iad1::kj8sg-1669238499279-b87cc4c1dc5a
User Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0

: Protocol error (Page.enable): Browser closed.
==================== Browser output: ====================
[pid=23][err] #30 0x55996e66e8ac (/tmp/chromium+0x54008ab)
[pid=23][err] #31 0x7f998e5be44b start_thread
[pid=23][err] #32 0x7f998db6756f __GI___clone
[pid=23][err] [pid=23][err] Received signal 6
[pid=23][err] #0 0x55996e65efc9 (/tmp/chromium+0x53f0fc8)
[pid=23][err] #1 0x55996e5daf33 (/tmp/chromium+0x536cf32)
[pid=23][err] #2 0x55996e65eaf1 (/tmp/chromium+0x53f0af0)
[pid=23][err] #3 0x7f998e5c88e0 (/usr/lib64/libpthread-2.26.so+0x118df)
[pid=23][err] #4 0x7f998daabca0 __GI_raise
[pid=23][err] #5 0x7f998daad148 __GI_abort
[pid=23][err] #6 0x55996e65ddb5 (/tmp/chromium+0x53efdb4)
[pid=23][err] #7 0x55996e5ec227 (/tmp/chromium+0x537e226)
[pid=23][err] #8 0x55996d27a6c7 (/tmp/chromium+0x400c6c6)
[pid=23][err] #9 0x55996d27807e (/tmp/chromium+0x400a07d)
[pid=23][err] #10 0x55996d276d03 (/tmp/chromium+0x4008d02)
[pid=23][err] #11 0x55996d2806f2 (/tmp/chromium+0x40126f1)
[pid=23][err] #12 0x55996d2822e4 (/tmp/chromium+0x40142e3)
[pid=23][err] #13 0x55996d10d5ec (/tmp/chromium+0x3e9f5eb)
[pid=23][err] #14 0x55996eefc653 (/tmp/chromium+0x5c8e652)
[pid=23][err] #15 0x55996eed4e7f (/tmp/chromium+0x5c66e7e)
[pid=23][err] #16 0x55996ef00963 (/tmp/chromium+0x5c92962)
[pid=23][err] #17 0x55996ef01ced (/tmp/chromium+0x5c93cec)
[pid=23][err] #18 0x55996eed1a09 (/tmp/chromium+0x5c63a08)
[pid=23][err] #19 0x55996eeea65e (/tmp/chromium+0x5c7c65d)
[pid=23][err] #20 0x55996eeeaa0a (/tmp/chromium+0x5c7ca09)
[pid=23][err] #21 0x55996eee9ec0 (/tmp/chromium+0x5c7bebf)
[pid=23][err] #22 0x55996d716ebb (/tmp/chromium+0x44a8eba)
[pid=23][err] #23 0x55996d716790 (/tmp/chromium+0x44a878f)
[pid=23][err] #24 0x55996d71303f (/tmp/chromium+0x44a503e)
[pid=23][err] #25 0x55996d70a53d (/tmp/chromium+0x449c53c)
[pid=23][err] #26 0x55996d71bf47 (/tmp/chromium+0x44adf46)
[pid=23][err] #27 0x55996e68c040 (/tmp/chromium+0x541e03f)
[pid=23][err] #28 0x55996e7c388d (/tmp/chromium+0x555588c)
[pid=23][err] #29 0x55996e68c2b3 (/tmp/chromium+0x541e2b2)
[pid=23][err] #30 0x55996e636045 (/tmp/chromium+0x53c8044)
[pid=23][err] #31 0x55996e60f5fb (/tmp/chromium+0x53a15fa)
[pid=23][err] #32 0x55996e64c878 (/tmp/chromium+0x53de877)
[pid=23][err] #33 0x55996d1293b0 (/tmp/chromium+0x3ebb3af)
[pid=23][err] #34 0x55996e64ca02 (/tmp/chromium+0x53dea01)
[pid=23][err] #35 0x55996e66e8ac (/tmp/chromium+0x54008ab)
[pid=23][err] #36 0x7f998e5be44b start_thread
[pid=23][err] #37 0x7f998db6756f __GI___clone
[pid=23][err]   r8: 0000000000000000  r9: 00007f998488fb00 r10: 0000000000000008 r11: 0000000000000246
[pid=23][err]  r12: 00007f9984890dc0 r13: 00007f998488fd60 r14: 00007f9984890dd0 r15: aaaaaaaaaaaaaaaa
[pid=23][err]   di: 0000000000000002  si: 00007f998488fb00  bp: 00007f998488fd50  bx: 0000000000000006
[pid=23][err]   dx: 0000000000000000  ax: 0000000000000000  cx: 00007f998daabca0  sp: 00007f998488fb00
[pid=23][err]   ip: 00007f998daabca0 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
[pid=23][err]  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[pid=23][err] [end of stack trace]
    at captureStackTrace (/var/task/node_modules/playwright-core/lib/utils/stackTrace.js:60:17)
    at BrowserContext._wrapApiCall (/var/task/node_modules/playwright-core/lib/client/channelOwner.js:101:58)
    at BrowserContext.newPage (/var/task/node_modules/playwright-core/lib/client/browserContext.js:237:17)
    at Browser.newPage (/var/task/node_modules/playwright-core/lib/client/browser.js:97:32)
    at async playwright (file:///var/task/api/playwright.js:23:18)
    at async Server.<anonymous> (/var/task/___vc/__helpers.js:813:13) {
  name: 'Error'
}
```

**Comment by dgozman** [comment]
@MuhammadM1998 Chromium is crashing for you, but since it's a production build, there are no symbols in the stack trace. I am not really sure how to help you. If we were to have a symbolized stack trace, it could help, but this way it's not particularly useful. Sorry.

**Comment by MuhammadM1998** [comment]
I solved the problem by just setting the `headless` to `true` in production case, or by removing it as it's the default option anyway.

this is the correct setup for anyone with the same problem
```javascript
import { chromium } from 'playwright-core';
import bundledChromium from 'chrome-aws-lambda';

const browser = await Promise.resolve(bundledChromium.executablePath)
.then((executablePath) =>
  !executablePath  
    ? chromium.launch({ headless: false })
    : chromium.launch({ executablePath })
);

const url = 'https://google.com/';
const page = await browser.newPage();
await page.goto(url);
await browser.close();
```
