### ISSUE TITLE
[BUG] Click flakes without waitFor

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#1906]
**Context:**
- Playwright Version: 0.13.0-next.1587493784299 (latest next version)
- Operating System: Mac

**Code Snippet**

Code from [this Twilio blog post](https://www.twilio.com/blog/automated-headless-browser-scripting-in-node-js-with-playwright). Since the click auto-waits for selectors, I removed the `waitFor(duration)` API calls from the code snippet.

```javascript
const playwright = require('playwright');

const run = async () => {
  const browser = await playwright.webkit.launch();
  const page = await browser.newPage();

  const MODAL_BUTTON_SELECTOR = '.modal-footer > button';
  const SEARCH_SELECTOR = 'input[placeholder=Search]';
  const LOCATION_SELECTOR = 'li.active > a';
  const RESULTS_SELECTOR = '.results-tab';

  await page.goto('https://native-land.ca/');
  // await page.waitFor(200);
  await page.click(MODAL_BUTTON_SELECTOR);
  // await page.waitFor(300);

  await page.click(SEARCH_SELECTOR);
  await page.keyboard.type('Philadelphia');
  await page.waitForSelector(LOCATION_SELECTOR);

  await page.click(LOCATION_SELECTOR);
  await page.waitForSelector(`${RESULTS_SELECTOR} > p`);

  const results = await page.$(RESULTS_SELECTOR);
  const text = await results.evaluate(element => element.innerText);
  console.log(text);

  await page.screenshot({path: 'example.png'});

  await browser.close();
};
```

**Describe the bug**

On chrome and webkit, I'm seeing flakes around 50% of the time. Firefox seems to be failing more consistently.

```
TimeoutError: waiting for element to receive pointer events failed: timeout exceeded
    at Function.waitWithDeadline (/Users/arjun/pw-examples/node_modules/playwright-core/lib/helper.js:135:30)
    at ElementHandle._waitForHitTargetAt (/Users/arjun/pw-examples/node_modules/playwright-core/lib/dom.js:372:54)
    at async ElementHandle._performPointerAction (/Users/arjun/pw-examples/node_modules/playwright-core/lib/dom.js:193:13)
    at async Frame._retryWithSelectorIfNotConnected (/Users/arjun/pw-examples/node_modules/playwright-core/lib/frames.js:569:28)
    at async Frame.click (/Users/arjun/pw-examples/node_modules/playwright-core/lib/frames.js:584:9)
    at async run (/Users/arjun/pw-examples/twilio.js:15:3)
    at async /Users/arjun/pw-examples/twilio.js:39:13
```

**Comment by dgozman** [comment]
Looked into this. The `SEARCH_SELECTOR` input jumps up when `loading...` text disappears. That sometimes happens after we ensured the stable position, but before we did the pointer events check. One possible solution is to retry in such a case.

**Comment by arjun27** [comment]
Quick update on this: I added a `waitForSelector` to wait for the `loading...` element to be detached, and it works really well! (Using Playwright 0.14.0)

<details>
<summary>Code snippet</summary>

```js
const playwright = require('playwright');

const run = async () => {
  const browser = await playwright.webkit.launch({ headless: false });
  const page = await browser.newPage();

  const MODAL_BUTTON_SELECTOR = '.modal-footer > button';
  const SEARCH_SELECTOR = 'input[placeholder=Search]';
  const LOCATION_SELECTOR = 'li.active > a';
  const RESULTS_SELECTOR = '.results-tab';

  await page.goto('https://native-land.ca/');
  // await page.waitForSelector('text=loading...', { waitFor: 'detached' });
  await page.waitForSelector('#root > div > div.search > div:nth-child(1) > table > p', { waitFor: 'detached'});

  await page.click(MODAL_BUTTON_SELECTOR);
  await page.click(SEARCH_SELECTOR);
  await page.keyboard.type('Philadelphia');
  await page.waitForSelector(LOCATION_SELECTOR);

  await page.click(LOCATION_SELECTOR);
  await page.waitForSelector(`${RESULTS_SELECTOR} > p`);

  const results = await page.$(RESULTS_SELECTOR);
  const text = await results.evaluate(element => element.innerText);
  console.log(text);

  await page.screenshot({path: 'example.png'});
  await browser.close();
};
```
</details>

However, I noticed a couple of issues:

1. Firefox headful works reliably, but headless times out waiting for the modal. I don't see the map load at all if I try to take some screenshots.

```
error TimeoutError: waiting for selector ".modal-footer > button" failed: timeout exceeded
    at new RerunnableTask (/Users/arjun/pw-examples/node_modules/playwright-core/lib/frames.js:722:30)
    at Frame._scheduleRerunnableTask (/Users/arjun/pw-examples/node_modules/playwright-core/lib/frames.js:660:32)
    at Frame._retryWithSelectorIfNotConnected (/Users/arjun/pw-examples/node_modules/playwright-core/lib/frames.js:566:43)
    at Frame.click (/Users/arjun/pw-examples/node_modules/playwright-core/lib/frames.js:584:20)
    at Frame.<anonymous> (/Users/arjun/pw-examples/node_modules/playwright-core/lib/helper.js:64:31)
    at Page.click (/Users/arjun/pw-examples/node_modules/playwright-core/lib/page.js:306:33)
    at Page.<anonymous> (/Users/arjun/pw-examples/node_modules/playwright-core/lib/helper.js:64:31)
    at run (/Users/arjun/pw-examples/twilio.js:16:14)
    at async /Users/arjun/pw-examples/twilio.js:37:13 
```

2. When I use the `text=loading...` to wait for the detached element, it doesn't work. If I copy over the element selector from Chrome Dev Tools (which is what the snippet above uses), it works. Maybe it's because of how the text is defined in the page markup?

![Screen Shot 2020-04-23 at 11 42 07 AM](https://user-images.githubusercontent.com/284612/80137787-a9c38200-8558-11ea-91c8-558672269278.png)

**Comment by pavelfeldman** [comment]
Fixed
