### ISSUE TITLE
[BUG] Exception is thrown while capturing stack trace

### ISSUE THREAD

**Issue by JonahKK** [microsoft/playwright#19087]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 16.14.0
- Browser: All

**Code Snippet**

```typescript
test('Test', async ({ page }) => {
    await page.goto('https://playwright.dev');
    await expect(page.locator('span')).toHaveCSS('font-size', '60');
  });
```

**Describe the bug**

When there is a strict mode violation, the exception is thrown while capturing the stack trace. This is not the first time I've got error like this, but this is the easiest way to reproduce it.
Stacktrace:
```
[chromium] › testin.e2e.ts:4:3 › testing › Test =====================================

    expect.toHaveCSS: Error: strict mode violation: "span" resolved to 7 elements:
        1) <span class="DocSearch-Button-Container">…</span> aka playwright.$("role=button[name="Search"]")
        2) <span class="DocSearch-Button-Placeholder">Search</span> aka playwright.$("role=button[name="Search"]")
        3) <span class="DocSearch-Button-Keys">…</span> aka playwright.$("role=button[name="Search"]")
        4) <span class="highlight_gXVj">Playwright</span> aka playwright.$("span:has-text("Playwright")")
        5) <span class="github-btn github-stargazers github-btn-l…>…</span> aka playwright.$("text=Star44k+")
        6) <span class="gh-ico" aria-hidden="true"></span> aka playwright.$("role=link[name="Star microsoft/playwright on GitHub"]")
        7) <span class="gh-text">Star</span> aka playwright.$("role=link[name="Star microsoft/playwright on GitHub"]")

    =========================== logs ===========================
    expect.toHaveCSS with timeout 5000ms
    waiting for selector "span"
      strict mode violation: "span" resolved to 7 elements:
        1) <span class="DocSearch-Button-Container">…</span> aka playwright.$("role=button[name="Search"]")
        2) <span class="DocSearch-Button-Placeholder">Search</span> aka playwright.$("role=button[name="Search"]")
        3) <span class="DocSearch-Button-Keys">…</span> aka playwright.$("role=button[name="Search"]")
        4) <span class="highlight_gXVj">Playwright</span> aka playwright.$("span:has-text("Playwright")")
        5) <span class="github-btn github-stargazers github-btn-l…>…</span> aka playwright.$("text=Star44k+")
        6) <span class="gh-ico" aria-hidden="true"></span> aka playwright.$("role=link[name="Star microsoft/playwright on GitHub"]")
        7) <span class="gh-text">Star</span> aka playwright.$("role=link[name="Star microsoft/playwright on GitHub"]")

    ============================================================

       at ../../../node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/util.js:98

       96 |
       97 | function captureStackTrace(customApiName) {
    >  98 |   const stackTrace = (0, _stackTrace.captureStackTrace)();
          |                                                        ^
       99 |   const frames = [];
      100 |   const frameTexts = [];
      101 |
       at captureStackTrace (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/util.js:98:56)
        at Object.toMatchText (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/matchers/toMatchText.js:46:68)
        at Object.toHaveCSS (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/matchers/matchers.js:212:35)
        at Proxy.toHaveCSS (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/expect.js:215:32)
        at /Users/user/Work/Repos/project/test/e2e/spec/testin.e2e.ts:6:40
        at /Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/workerRunner.js:426:9
        at TestInfoImpl._runFn (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/testInfo.js:166:7)
        at /Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/workerRunner.js:376:26
        at TimeoutManager.runWithTimeout (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/timeoutManager.js:73:7)
        at TestInfoImpl._runWithTimeout (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/testInfo.js:154:26)
        at WorkerRunner._runTest (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/workerRunner.js:356:5)
        at WorkerRunner.runTestGroup (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/workerRunner.js:218:11)
        at process.<anonymous> (/Users/user/Work/Repos/project/node_modules/.pnpm/@playwright+test@1.27.1/node_modules/@playwright/test/lib/worker.js:88:5)
```

**Comment by pavelfeldman** [comment]
Assertions in Playwright Test are exceptions and those have stack. We should have filtered our code from it though.

**Comment by Nav-2d** [comment]
@aslushnikov - I see that you changed the status to "collecting-feedback", I wanted to make sure the root cause for this issue is similar to an issue which I logged [here](https://github.com/microsoft/playwright/issues/19083#issuecomment-1329790598) (debugging in codegen has been a fine when I run through assertion steps).

**Comment by aslushnikov** [comment]
> I wanted to make sure the root cause for this issue is similar to an issue which I logged https://github.com/microsoft/playwright/issues/19083#issuecomment-1329790598

@Nav-2d I looked at that issue and I actually doubt that these are the same root cause. This issue was solely due to a different layout of packages in the PNPM package manager, thus some of our stack masking was failing. Your issue seems to be related to some test files.

Would you mind creating a repo with a few files so that I can see how codegen jumps to the `captureStackTrace` there? I'd also appreciate if you file a new issue so that we can keep separate things separately.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
