### ISSUE TITLE
[BUG] custom fixtures not working on beforeEach

### ISSUE THREAD

**Issue by goldylucks** [microsoft/playwright#19093]
**Context:**
- Playwright Version: `"@playwright/test": "^1.28.1"`
- Operating System: Mac
- Node.js version: `v16.18.0`
- Visual Studio Code version: `1.73.1`
- Playwright for VSCode extension version: `v1.0.1`
- Browser: all

```
## System:
 - OS: macOS 13.0.1
 - Memory: 560.73 MB / 32.00 GB
## Binaries:
 - Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
 - Yarn: 1.22.18 - ~/.yarn/bin/yarn
 - npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
```

**Code Snippet**

```
// test.ts
import { test as base } from "@playwright/test"

import TopNav from "./top-nav"

type MyFixtures = {
  topNav: TopNav
}

export const test = base.extend<MyFixtures>({
  topNav: async ({ page }, use) => {
    const topNav = new TopNav(page)
    await use(topNav)
  },
})

export { expect } from "@playwright/test"

// describe-guest.ts
import { ROUTES } from "@nx/constants"

import { test } from "../helpers/test"
import TopNav from "../helpers/top-nav"

import { IDescribeFn } from "./types"

export const describeGuest = describeGuestFn

function describeGuestFn(testSuffix: string, describeFn: IDescribeFn) {
  // eslint-disable-next-line jest/valid-title
  test.describe(...makeDescribeGuestArgs(testSuffix, describeFn))
}

function makeDescribeGuestArgs(testSuffix: string, describeFn: IDescribeFn) {
  const testName = `Guest - ${testSuffix}`

  return [
    testName,
    function () {
      describeFn(prepareGuest)
    },
  ] as const
}

function prepareGuest() {
  test.beforeEach(async ({ page, topNav }) => {
    await page.goto(ROUTES.testFastPage())
    await topNav.assertGuest()
  })
}

```

**Describe the bug**

I created a fixture as per the [docs](https://playwright.dev/docs/test-fixtures), and TS recognizes the `topNav` on the `test.beforeEach` callback:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/6963212/204123318-90047063-8da6-4986-badd-656d67171648.png">

But the test runner crashes:

```
   $ npx playwright test
Error: beforeEach hook has unknown parameter "topNav".
  beforeEach hook defined at e2e/describe/describe-guest.ts:36:8
    at errorWithLocations (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/fixtures.js:435:10)
    at FixturePool.validateFunction (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/fixtures.js:272:32)
    at ProjectSuiteBuilder._buildPool (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/loader.js:322:48)
    at ProjectSuiteBuilder._cloneEntries (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/loader.js:362:29)
    at ProjectSuiteBuilder._cloneEntries (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/loader.js:337:19)
    at ProjectSuiteBuilder.cloneFileSuite (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/loader.js:375:17)
    at Loader.buildFileSuiteForProject (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/loader.js:219:20)
    at Runner._collectTestGroups (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/runner.js:283:43)
    at Runner._run (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/runner.js:357:9)
    at TimeoutRunner.run (/Users/Goldy/breathe/code/node_modules/playwright-core/lib/utils/timeoutRunner.js:45:14)
    at raceAgainstTimeout (/Users/Goldy/breathe/code/node_modules/playwright-core/lib/utils/timeoutRunner.js:89:15)
    at Runner.runAllTests (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/runner.js:138:20)
    at runTests (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/cli.js:165:18)
    at Gi.<anonymous> (/Users/Goldy/breathe/code/node_modules/@playwright/test/lib/cli.js:71:7)
```

Note that this DOES work on the test spec file itself:

```
// home.guest.spec.ts

import { expect } from "@playwright/test"

import { ROUTES } from "@nx/constants"

import { describeGuest } from "../../describe"
import { test } from "../../helpers/test"

describeGuest("Home page", function (prepare) {
  prepare()

  test("goes to intro page", async ({ page, topNav }) => {
    await page.goto(ROUTES.home())
    await topNav.assertGuest() // <-------- Works!

    await page.getByTestId("start").nth(0).click()

    await expect(page).toHaveURL(
      new RegExp(ROUTES.toolNewRecord("ppa-intro-he")),
    )
  })
})


```

**Comment by dgozman** [comment]
@goldylucks I tried to reproduce, but failed. Perhaps some `test` variable is imported from a wrong place? Here are the exact files I tried to reproduce with - let me know if that does not recreate your setup:

```ts
// helper.ts

import { test as base } from "@playwright/test"

type MyFixtures = {
  topNav: string
}

export const test = base.extend<MyFixtures>({
  topNav: async ({ page }, use) => {
    await use('topNav!!')
  },
})

export { expect } from "@playwright/test"
```

```ts
// describe-guest.ts

import { test } from "./helper"

export const describeGuest = describeGuestFn

function describeGuestFn(testSuffix: string, describeFn: Function) {
  // eslint-disable-next-line jest/valid-title
  test.describe(...makeDescribeGuestArgs(testSuffix, describeFn))
}

function makeDescribeGuestArgs(testSuffix: string, describeFn: Function) {
  const testName = `Guest - ${testSuffix}`

  return [
    testName,
    function () {
      describeFn(prepareGuest)
    },
  ] as const
}

function prepareGuest() {
  test.beforeEach(async ({ page, topNav }) => {
    await page.goto('https://playwright.dev')
    console.log('topNav from beforeEach: ', topNav)
  })
}
```

```ts
// example.spec.ts

import { describeGuest } from "./describe-guest"
import { test } from "./helper"

describeGuest("Home page", function (prepare) {
  prepare()

  test("goes to intro page", async ({ page, topNav }) => {
    console.log('topNav from test: ', topNav)
  })
})
```

Output:

```sh
Running 1 test using 1 worker
example.spec.ts:9:7 › Guest - Home page › goes to intro page
topNav from beforeEach:  topNav!!
topNav from test:  topNav!!

  1 passed (2s)
```

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by dacloutier-logmein** [comment]
Unfortunately, can't offer much more details bu tI did reproduce the issue on my side.

I have 2 projects that uses the same _base_ (both project test the same app, but different needs).

One of the project is working just fine, tests can be ran without issue.

The other suffer from a similar issue (in my case, it's an afterEach hook, that can't access browserContext fixtures) if tests are ran via the runner. (pnpm test)

However, if the test are to be started via VSCode's playwright runner in the UI, test function just fine.  I hope this tidbit can help.
