### ISSUE TITLE
[BUG] Can't set baseURL default value in fixture

### ISSUE THREAD

**Issue by Janpot** [microsoft/playwright#19127]
**Context:**
- Playwright Version: 1.28.0
- Operating System: macOS 12.4
- Node.js version: v16.17.0
- Browser: NA

**Code Snippet**

```ts
import { test } from '@playwright/test';

test('initialize baseURL', async ({ baseURL = '' }) => {
  // ...
  console.log(baseURL);
});
```

**Describe the bug**

Running playwright over that fixture produces

```
Error: Test has unknown parameter "baseURL = ''".
  Test defined at test/integration/test.spec.ts:3:6
    at errorWithLocations /node_modules/@playwright/test/lib/fixtures.js:435:10)
    at FixturePool.validateFunction /node_modules/@playwright/test/lib/fixtures.js:272:32)
    at ProjectSuiteBuilder._buildPool /node_modules/@playwright/test/lib/loader.js:325:12)
    at ProjectSuiteBuilder._cloneEntries /node_modules/@playwright/test/lib/loader.js:362:29)
    at ProjectSuiteBuilder.cloneFileSuite /node_modules/@playwright/test/lib/loader.js:375:17)
    at Loader.buildFileSuiteForProject /node_modules/@playwright/test/lib/loader.js:219:20)
    at Runner._collectTestGroups /node_modules/@playwright/test/lib/runner.js:283:43)
    at Runner._run /node_modules/@playwright/test/lib/runner.js:357:9)
    at TimeoutRunner.run /node_modules/playwright-core/lib/utils/timeoutRunner.js:45:14)
    at raceAgainstTimeout /node_modules/playwright-core/lib/utils/timeoutRunner.js:89:15)
    at Runner.runAllTests /node_modules/@playwright/test/lib/runner.js:138:20)
    at runTests /node_modules/@playwright/test/lib/cli.js:165:18)
    at Gi.<anonymous> /node_modules/@playwright/test/lib/cli.js:71:7)
```

**Comment by ltsuda** [comment]
You can change the baseURL through the playwright-config.(js|ts) or I think it is possible to use `test.use()` in the test file like the following:

https://playwright.dev/docs/api/class-testoptions#test-options-base-url

```javascript
test.use({ baseURL: 'www.microsoftcom' });
test('initialize baseURL', async ({ baseURL }) => {
  // ...
  console.log(baseURL);
});
```

or 

https://playwright.dev/docs/api/class-testoptions

**Comment by Janpot** [comment]
@mxschmitt I'm not sure this should be marked as completed. It's perfectly valid javascript, rejected by `playwright`. All @ltsuda proposed is a workaround for the bug that doesn't address the root cause. I propose to reopen this ticket unless there's good reason why `baseURL = ''` can't be accepted by `playwright`.

**Comment by mxschmitt** [comment]
Fair point!
