### ISSUE TITLE
[BUG] Playwright fails to run on Azure Pipelines with the latest version 

### ISSUE THREAD

**Issue by bheemreddy181** [microsoft/playwright#19311]
**Context:**
- Playwright Version: 1.28.
- Operating System: linux
- Node.js version: 18
- Browser: chrome

``` 
  Failed CreateReferenceId [1 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Executable doesn't exist at /home/vsts/.cache/ms-playwright/ffmpeg-1007/ffmpeg-linux
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     pwsh bin\Debug\netX\playwright.ps1 install             ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioStart()
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep() 
```

**Describe the bug**

playwright fails to figure out the path for ffmpeg for latest version on Azure pipelines works fine on 1.27.1

**Comment by bheemreddy181** [comment]
<img width="1091" alt="Screen Shot 2022-12-06 at 4 00 23 PM" src="https://user-images.githubusercontent.com/101338506/206032508-3d10d6af-32e4-4ec3-a55d-65dfec2386b2.png">
ffmpeg is getting downloaded to 1008 path where the run is looking at 1007 only happens on 1.28.1 version

**Comment by bheemreddy181** [comment]
My playwright dotnet version was 1.25 and on my pipeline it was installing the latest 1.28.1 which caused the issue. Closing this.
