### ISSUE TITLE
[BUG] Throws error as net::ERR_NAME_NOT_RESOLVED at <SUT URL> on executing test on saucelab using sauce connect

### ISSUE THREAD

**Issue by NerdishShah** [microsoft/playwright#19481]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Windows 10 
- Node.js version: 16.15.1
- Browser: All
- Extra: AUT is behind Corp firewall, Execution in cloud based selenium grid on https://saucelabs.com/

**DashboardPage.js**

```
export class DashboardPage {
  /**
   * @param {import('@playwright/test').Page} page
   */
  constructor(page) {
    this.page = page;
    this.menu = page.locator("button");
  }

  async goto() {
    await this.page.goto("https://internal-application-under-test.com/dashboard");
  }

  async gotoSearchProduct() {
    await this.menu.click();
    await this.page.locator('div[role="button"]:has-text("Product")').click();
  }
}
```

**Jenkinsfile**

```
stage('Selenium Tests') {
            container('oraclelinux') {
                    sauce('saucelab') {
                     sauceconnect(useGeneratedTunnelIdentifier: true, verboseLogging: true) {
                      try {
                          echo 'Run Sauce Playwright Pipeline Test'
                          sh 'npm install saucectl'
                          sh 'npx saucectl run'
                        } catch (Exception err) {
                          unstable(message: "Tests are unstable")
                        }
                      }
                    }
            }
          }
```
**Jenkins Console Log**

```

[Pipeline] stage
[Pipeline] { (Selenium Tests)
[Pipeline] container
[Pipeline] {
[Pipeline] sauce
[Pipeline] {
[Pipeline] sauceconnect
17:14:01  Starting sauce connect
17:14:04  Sauce Connect Proxy™ opens a secure connection between Sauce Labs and a locally hosted application.
17:14:04  
17:14:04    Find more information at: https://docs.saucelabs.com/dev/cli/sauce-connect-proxy
17:14:04  
17:14:04  Sauce Connect 4.8.1, build 2379 41872ee1 
17:14:04  
17:14:04  WARNING: Outdated version 4.8.1. Please download the latest version from https://saucelabs.com/downloads/sc-4.8.2-linux.tar.gz
17:14:04  
17:14:04  Sauce Connect runtime information:
17:14:04  - Name: feature_2Fpipeline-integration-16-1671110041969
17:14:04  - PID: 219
17:14:04  - PID file: /tmp/sc_client-feature_2Fpipeline-integration-16-1671110041969.pid
17:14:04  - Log file: /tmp/sc-feature_2Fpipeline-integration-16-1671110041969.log
17:14:04  - SCProxy Port: 38587
17:14:04  - Status Port: None
17:14:04  - Selenium listener: 34325
17:14:04  - External proxy: None
17:14:04  - Tunnel proxy: None
17:14:04  - Region: eu-central
17:14:04  
17:14:04  Please wait for 'you may start your tests' to start your tests
17:14:14  Secure remote tunnel provisioned. Tunnel ID: 363445c39b5a410ba66bbfeeed129991
[Pipeline] { (Sauce Connect)
[Pipeline] echo
17:14:16  Run Sauce Playwright Pipeline Test
[Pipeline] sh
17:14:17  + npm install saucectl
17:14:16  
17:14:16  Sauce Connect is up, you may start your tests.
17:14:16  Sauce Connect 4.8.1 now launched for: feature_2Fpipeline-integration-16-1671110041969
17:14:16  Incremented process count for feature_2Fpipeline-integration-16-1671110041969, now 1
17:14:35  
17:14:35  added 147 packages, and audited 157 packages in 18s
17:14:35  
17:14:35  6 packages are looking for funding
17:14:35    run `npm fund` for details
17:14:35  
17:14:35  8 vulnerabilities (3 moderate, 5 high)
17:14:35  
17:14:35  Some issues need review, and may require choosing
17:14:35  a different dependency.
17:14:35  
17:14:35  Run `npm audit` for details.
[Pipeline] sh
17:14:36  + npx saucectl run
17:14:36  Running version 0.116.0
17:14:37  13:14:37 INF Running Playwright in Sauce Labs
17:14:37  
17:14:37                                          (.                          
17:14:37                                         #.                           
17:14:37                                         #.                           
17:14:37                             .####################                    
17:14:37                           #####////////*******/######                
17:14:37                         .##///////*****************###/              
17:14:37                        ,###////*********************###              
17:14:37                        ####//***********************####             
17:14:37                         ###/************************###              
17:14:37                          ######********************###. ##           
17:14:37                             (########################  ##     ##     
17:14:37                                     ,######(#*         ##*   (##     
17:14:37                                 /############*          #####        
17:14:37                             (########(  #########(    ###            
17:14:37                           .#######,    */  ############              
17:14:37                        ,##########  %#### , ########*                
17:14:37                      *### .#######/  ##  / ########                  
17:14:37                     ###   .###########//###########                  
17:14:37                 ######     ########################                  
17:14:37               (#(    *#(     #######.    (#######                    
17:14:37                      ##,    /########    ########                    
17:14:37                             *########    ########                    
17:14:37  
17:14:37     _____        _    _  _____ ______    _____ _      ____  _    _ _____  
17:14:37    / ____|  /\  | |  | |/ ____|  ____|  / ____| |    / __ \| |  | |  __ \ 
17:14:37   | (___   /  \ | |  | | |    | |__    | |    | |   | |  | | |  | | |  | |
17:14:37    \___ \ / /\ \| |  | | |    |  __|   | |    | |   | |  | | |  | | |  | |
17:14:37    ____) / ____ \ |__| | |____| |____  | |____| |___| |__| | |__| | |__| |
17:14:37   |_____/_/    \_\____/ \_____|______|  \_____|______\____/ \____/|_____/
17:14:37  
17:14:37  13:14:37 INF Archive created. durationMs=4 fileCount=13 size=39593
17:14:37  13:14:37 INF Checking if /tmp/saucectl-app-payload-944279166/config.zip has already been uploaded previously
17:14:37  13:14:37 INF Checksum: a65f87cb1c2d3295577bf37b0fa6371e873fa0596be06084d9a30d0c32ffa126
17:14:38  
⠋ Uploading runner config /tmp/saucectl-app-payload-944279166/config.zip 
13:14:38 INF Runner Config uploaded. durationMs=350 storageId=3281cc4d-b4cc-49f8-8075-e61564251cf1
17:14:38  13:14:38 INF Checking if /tmp/saucectl-app-payload-944279166/app.zip has already been uploaded previously
17:14:38  13:14:38 INF Checksum: 9753da66f072d4fd746dff09aa494f83fa93d07bb9703ff0937e61d50fcbd759
17:14:40  
⠙ Uploading project /tmp/saucectl-app-payload-944279166/app.zip 
13:14:39 INF Project uploaded. durationMs=916 storageId=d5f4921f-7cb1-4140-a17e-5a01288760d1
17:14:40  13:14:39 INF Launching workers. concurrency=10
17:14:40  13:14:39 INF Starting suite. region=eu-central-1 suite="Chromium Win"
17:14:43  13:14:43 INF Suite started. browser=chromium platform="Windows 11" suite="Chromium Win" url=https://app.eu-central-1.saucelabs.com/tests/xxxxxxxxxxxxxxxxxxxxxxxx
17:14:50  13:14:49 INF Suites in progress: 1
17:14:59  13:14:59 INF Suites in progress: 1
17:15:09  13:15:09 INF Suites in progress: 1
17:15:14  13:15:13 ERR Suite finished. passed=false suite="Chromium Win" url=https://app.eu-central-1.saucelabs.com/tests/xxxxxxxxxxxxxxxxxxxxxxxx
17:15:14  13:15:13 INF console.log output: 
17:15:14  Preparing npm environment
17:15:14  
17:15:14  Running 3 tests using 1 worker
17:15:14  
17:15:14    x  1 [chromium] › tests\saucelabIntegration.spec.js:16:1 › Checkout single product - deliver same day (616ms)
17:15:14    x  2 [chromium] › tests\saucelabIntegration.spec.js:26:1 › Checkout multiple product - deliver next day (536ms)
17:15:14    x  3 [chromium] › tests\saucelabIntegration.spec.js:36:1 › Checkout multiple product - deliver late (458ms)
17:15:14  
17:15:14  
17:15:14    1) [chromium] › tests\saucelabIntegration.spec.js:16:1 › Checkout single product - deliver same day
17:15:14  
17:15:14      page.goto: net::ERR_NAME_NOT_RESOLVED at https://internal-application-under-test.com/dashboard
17:15:14      =========================== logs ===========================
17:15:14      navigating to "https://application-under-test.com/dashboard", waiting until "load"
17:15:14      ============================================================
17:15:14  
17:15:14         8 | test.beforeEach(async ({ page }) => {
17:15:14         9 |   const dashboardPage = new DashboardPage(page);
17:15:14      > 10 |   await dashboardPage.goto();
17:15:14           |                       ^
17:15:14        11 |   await dashboardPage.gotoSearchProduct();
17:15:14        12 |   productSearchPage = new ProductSearchPage(page);
17:15:14        13 |   productEditPage = new ProductEditPage(page);
17:15:14  
17:15:14          at DashboardPage.goto (D:\sauce-playwright-runner\2.12.0\bundle\__project__\tests\pages\dashboardPage.js:11:21)
17:15:14          at D:\sauce-playwright-runner\2.12.0\bundle\__project__\tests\scheduleEdit.spec.js:10:23

```

**Describe the bug**

The application under test is behind corp firewall due to which its being connected via sauce connect proxy. 

On sauce lab dashboard, tunnel proxy is getting started but on sauce lab machine the browser just opens and closes immediately. 

Console error prints as net::ERR_NAME_NOT_RESOLVED

When the application is manually launched using Website Test menu from saucelab by selecting the jenkins started tunnel, it launched successfully.

![image](https://user-images.githubusercontent.com/31189986/207889657-c8653e1f-e253-4c8a-bdcd-75142702f997.png)

**Comment by yury-s** [comment]
The error clearly says that DNS name 'https://internal-application-under-test.com/dashboard' cannot be resolved to an API address, so this a problem with how the browser accesses the internal web site. This is a question to saucelab and how they route the traffic, please ask in their bug tracker.

**Comment by NullVoxPopuli** [comment]
this happens to me with localhost, too

**Comment by chennabaiganii** [comment]
This happened to me.
