### ISSUE TITLE
[BUG] Failed to run browser with chromium.launchPersistentContext

### ISSUE THREAD

**Issue by sunopar** [microsoft/playwright#19499]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Apple M1 Pro MacOS
- Node.js version: Node.js v18.10.0
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
const { chromium } = require("playwright");

const checkPipeline = async () => {
  const targetUri = "https://github.com";

  // Setup
  const userDataDir = "/Users/user/Library/Application Support/Google/Chrome/";
  const context = await chromium.launchPersistentContext(userDataDir, {
    headless: false,
    channel: "chrome",
    executablePath:
      "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  });
  const page = await context.newPage(targetUri);

  // The actual interesting bit
  await page.goto(targetUri);

  await browser.close();
};

const main = async () => {
  await checkPipeline();
};
main();

```

**Describe the bug**

When I use `nodejs` to run this code, the browser will open a page about: blank and then it will throw an error in the below.

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.launchPersistentContext: Browser closed.
==================== Browser output: ====================
<launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/Users/user/Library/Application Support/Google/Chrome/ --remote-debugging-pipe about:blank
<launched> pid=55911
[pid=55911][err] objc[55922]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x23a295b50) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/108.0.5359.124/Libraries/libGLESv2.dylib (0x10ad0bf38). One of the two will be used. Which one is undefined.
[pid=55911][out] 正在现有的浏览器会话中打开。
=========================== logs ===========================
<launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/Users/user/Library/Application Support/Google/Chrome/ --remote-debugging-pipe about:blank
<launched> pid=55911
[pid=55911][err] objc[55922]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x23a295b50) and /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/108.0.5359.124/Libraries/libGLESv2.dylib (0x10ad0bf38). One of the two will be used. Which one is undefined.
[pid=55911][out] 正在现有的浏览器会话中打开。
============================================================
    at async checkPipeline (/Users/user/code/draft/playwright-test/index.js:8:19)
    at async main (/Users/user/code/draft/playwright-test/index.js:23:3) {
  name: 'Error'
}

Node.js v18.10.0
```

**Comment by mxschmitt** [comment]
This is expected, you need to close your other existing browser session which uses the same user data dir, otherwise it will re-use your previous session.

Also you don't need to specify executablePath, since you already specify channel which internally will do the same.

**Comment by sunopar** [comment]
@mxschmitt Thank you for your prompt response. I have successfully tested the solution and it works without any errors. However, I am looking for a way to automate this process in order to streamline my daily tasks. Is there a more efficient method to achieve this?
The reason I am using the user data dir option is to avoid having to deal with the login process, as I am already logged in on my personal computer and the script will only be run on that device."

**Comment by yury-s** [comment]
> However, I am looking for a way to automate this process in order to streamline my daily tasks. Is there a more efficient method to achieve this?
> The reason I am using the user data dir option is to avoid having to deal with the login process, as I am already logged in on my personal computer and the script will only be run on that device."

Follow our [authentication guide](https://playwright.dev/docs/auth), you can save logged in browser state into a file and use for initializing new ephemeral contexts. 

If you stick with persistent context you'll have to either ensure that no other borwsers are using it at the same time or just use a separate user data dir for your tests.
