### ISSUE TITLE
[BUG] Individual test not run in windows when path includes backslash

### ISSUE THREAD

**Issue by tediroca** [microsoft/playwright#19563]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Windows 11
- Node.js version: 19.3.0
- Browser: All
- Extra: none

```
npx playwright test tests\authentication.spec.js

Running 0 tests using 0 workers
=================
 no tests found.
=================


To open last HTML report run:

  npx playwright show-report
```

```
npx playwright test tests/authentication.spec.js

Running 3 tests using 3 workers
  1) [webkit] › authentication.spec.js:6:5 › ensures a valid user can log in =======================

    Test timeout of 30000ms exceeded.

    locator.fill: Target closed
    =========================== logs ===========================
    waiting for selector "#username"
      selector resolved to hidden <input type="text" autofocus="" id="username" name="use…/>
    elementHandle.fill("")
      waiting for element to be visible, enabled and editable
        element is not visible - waiting...
    ============================================================

      16 |
      17 |             await loginPage.get();
    > 18 |             await loginPage.setUserName(username);
         |                             ^
      19 |             await loginPage.setPassword(password);
      20 |
      21 |             await loginPage.login().then(async function () {

        at LoginPage.setUserName (C:\Users\xxx\TEMP\new-project\helpers\loginPage.js:22:30)
        at C:\Users\xxx\TEMP\new-project\tests\authentication.spec.js:18:29

    Pending operations:
      - locator.fill at helpers\loginPage.js:22:30


  2) [firefox] › authentication.spec.js:6:5 › ensures a valid user can log in ======================

    Test timeout of 30000ms exceeded.

    locator.fill: Target closed
    =========================== logs ===========================
    waiting for selector "#username"
      selector resolved to hidden <input type="text" autofocus="" id="username" name="use…/>
    elementHandle.fill("")
      waiting for element to be visible, enabled and editable
        element is not visible - waiting...
    ============================================================

      16 |
      17 |             await loginPage.get();
    > 18 |             await loginPage.setUserName(username);
         |                             ^
      19 |             await loginPage.setPassword(password);
      20 |
      21 |             await loginPage.login().then(async function () {

        at LoginPage.setUserName (C:\Users\xxx\TEMP\new-project\helpers\loginPage.js:22:30)
        at C:\Users\xxx\TEMP\new-project\tests\authentication.spec.js:18:29

    Pending operations:
      - locator.fill at helpers\loginPage.js:22:30



  2 failed
    [firefox] › authentication.spec.js:6:5 › ensures a valid user can log in =======================
    [webkit] › authentication.spec.js:6:5 › ensures a valid user can log in ========================
  1 passed (32s)

  Serving HTML report at http://127.0.0.1:9323. Press Ctrl+C to quit.
```
**Describe the bug**

The individual test spec runs fine when slash is used to define the path.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
