### ISSUE TITLE
[BUG] Error: ERROR: Playwright does not support chromium on ubuntu18.04

### ISSUE THREAD

**Issue by jhuh0821** [microsoft/playwright#19583]
**Context:**
- Playwright Version: 1.29.0 (and @playwright/test version is also 1.29.0)
- Operating System: Linux
- Node.js version: 16
- Browser: Chromium
- Extra: GitHub Actions

Running `npx playwright install --with-deps` fails on GitHub actions with following message:
```
[5/5] Building fresh packages...
error /home1/irteam/_work/***/***/packages/***/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Directory: /home1/irteam/_work/***/***/packages/***/node_modules/playwright
Output:
/home1/irteam/_work/***/***/node_modules/playwright-core/lib/server/registry/index.js:620
    if (!downloadURLs.length) throw new Error(`ERROR: Playwright does not support ${descriptor.name} on ${_hostPlatform.hostPlatform}`);
                                    ^
Error: ERROR: Playwright does not support chromium on ubuntu18.04
    at Registry._downloadExecutable (/home1/irteam/_work/***/***/node_modules/playwright-core/lib/server/registry/index.js:620:37)
    at Object._install (/home1/irteam/_work/***/***/node_modules/playwright-core/lib/server/registry/index.js:302:28)
    at Registry.install (/home1/irteam/_work/***/***/node_modules/playwright-core/lib/server/registry/index.js:593:26)
    at async installBrowsersForNpmInstall (/home1/irteam/_work/***/***/node_modules/playwright-core/lib/server/registry/index.js:768:3)
Error: Process completed with exit code 1.
```

**Comment by mxschmitt** [comment]
Playwright does not support Ubuntu 18 anymore which was announced in 1.25 and enforced in 1.29.

In your case since its GitHub Actions you need to update the `runs-on` keyword inside your GitHub Actions workflow.

Folding into https://github.com/microsoft/playwright/issues/19548.
