### ISSUE TITLE
[BUG] page.goto: Navigation failed because page crashed!

### ISSUE THREAD

**Issue by Jbsh1999** [microsoft/playwright#19616]
**Context:**
- Playwright Version: "playwright": "^1.29.0"
- Operating System: Mac
- Node.js version: v19.1.0
- Browser Webkit
- Extra: [any specific details about your environment]

**Code Snippet**

```
const { webkit, devices } = require('playwright');
const iPhone = devices['iPhone 6'];

(async () => {
  const browser = await webkit.launch({headless: false});
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www2.hm.com/de_de/login');
  // other actions...
  //await browser.close();
})();

```
**Describe the bug**

```
node test.js
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://www2.hm.com/de_de/login", waiting until "load"
============================================================
    at /Users/xxxx/App/playwright-new/test.js:8:14 {
  name: 'Error'
}
```

**Comment by pavelfeldman** [comment]
This works for me on Playwright 1.29, macOS 13

**Comment by mxschmitt** [comment]
Works for me as well. Could you set the `DEBUG=pw:api,pw:browser` environment variable which will print more debug output while running the script?

**Comment by Jbsh1999** [comment]
```
pw:api => browserType.launch started +0ms
  pw:browser <launching> /Users/jbsh/Library/Caches/ms-playwright/webkit-1751/pw_run.sh --inspector-pipe --no-startup-window +0ms
  pw:browser <launched> pid=26784 +5ms
  pw:api <= browserType.launch succeeded +606ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +31ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +335ms
  pw:api => page.goto started +0ms
  pw:api navigating to "https://www2.hm.com/de_de/login", waiting until "load" +2ms
  pw:api   "commit" event fired +257ms
  pw:api   navigated to "https://www2.hm.com/de_de/login" +0ms
  pw:api <= page.goto failed +653ms
  pw:browser [pid=26784] <kill> +2s
  pw:browser [pid=26784] <will force kill> +0ms
  pw:browser [pid=26784] starting temporary directories cleanup +0ms
  pw:browser [pid=26784] finished temporary directories cleanup +123ms
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://www2.hm.com/de_de/login", waiting until "load"
============================================================
    at /Users/jbsh/App/playwright-new/test.js:8:14 {
  name: 'Error'
}

Node.js v19.3.0

```

**Comment by pavelfeldman** [comment]
Unfortunately this does not help. Please provide the version of your OS and we will keep it hanging here so that others could contribute if they are experiencing the same issue.

**Comment by Jbsh1999** [comment]
Big Sur 11.2.3
Model Name:	Mac mini
  Model Identifier:	Macmini8,1
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	3,1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  System Firmware Version:	1554.60.15.0.0

**Comment by pavelfeldman** [comment]
We have not received any reports like this, so it suggests something is unusual with your setup. Closing as non-actionable.
