### ISSUE TITLE
[BUG] toHaveScreenshot + update-snapshots fails in 1.29.1

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#19679]
**Context:**
- Playwright Version: bumped from 1.28.0 to 1.29.1
- Operating System: mcr.microsoft.com/playwright:v1.29.1-focal
- Node.js version: 16

**Code Snippet**

```javascript
        await expect(page.locator(elementLocator)).toHaveScreenshot(`${filename}.png`)
```

**Describe the bug**

this part if running with `update-snapshots` fails with 

```
    TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
       at ../../.pnp.cjs:43045
      43043 |       this.realFs.writeFileSync(fsNativePath, content, opts);
      43044 |     } else {
    > 43045 |       this.realFs.writeFileSync(fsNativePath, content);
            |                   ^
      43046 |     }
      43047 |   }
      43048 |   async unlinkPromise(p) {
        at NodeFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:43045:19)
        at makeCallSync.subPath.subPath (/builds/frontend/blabla/.pnp.cjs:45287:26)
        at ZipOpenFS.makeCallSync (/builds/frontend/blabla/.pnp.cjs:45514:14)
        at ZipOpenFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:45286:17)
        at VirtualFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:44592:24)
        at PosixFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:44592:24)
        at NodePathFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:44592:24)
        at compareScreenshots (/builds/frontend/blabla/packages/testing/src/utils/utils.ts:63:9)
```

**Comment by dimkin-eu** [comment]
as a note happens only for 

```js
      {
            name: "iPhone 11",
            use: {
                ...devices["iPhone 11"],
            },
        },
        {
            name: "iPhone 13 Mini squeezed",
            use: {
                ...devices["iPhone 13 Mini"],
                viewport: { width: 375, height: 539 },
            },
        },
```

and doesn't for
```js
        {
            name: "Desktop-Chrome",
            use: {
                browserName: "chromium",
                channel: "chrome",
                viewport: { width: 1920, height: 1080 },
                launchOptions: {
                    args: ["--disable-web-security"],
                },
            },
        },
        {
            name: "Desktop-Safari",
            use: {
                browserName: "webkit",
                viewport: { width: 1920, height: 1080 },
            },
        },
        {
            name: "Desktop-Firefox",
            use: {
                browserName: "firefox",
                viewport: { width: 1920, height: 1080 },
            },
        },
        {
            name: "iPhone 11 landscape",
            use: {
                ...devices["iPhone 11 landscape"],
                viewport: { width: 800 - notch, height: 364 },
            },
        },
        {
            name: "iPhone 13 Mini landscape squeezed",
            use: {
                ...devices["iPhone 13 Mini landscape"],
                viewport: { width: 724, height: 234 },
            },
        },
```

**Comment by aslushnikov** [comment]
@dimkin-eu oh, sorry! This issue fell outside of my sight. How do I repro this?

**Comment by dimkin-eu** [comment]
@aslushnikov , not sure how, as it affects always the same 4 tests of 2.5k+ in our storybook tests
1.29.2 didn't help either
The only changes in yarn.lock are playwright 1.28.0 -> 1.29.2 related

**Comment by aslushnikov** [comment]
@dimkin-eu actually, the error stack that you mentioned in your issue does not come from playwright:

```
    TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
       at ../../.pnp.cjs:43045
      43043 |       this.realFs.writeFileSync(fsNativePath, content, opts);
      43044 |     } else {
    > 43045 |       this.realFs.writeFileSync(fsNativePath, content);
            |                   ^
      43046 |     }
      43047 |   }
      43048 |   async unlinkPromise(p) {
        at NodeFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:43045:19)
        at makeCallSync.subPath.subPath (/builds/frontend/blabla/.pnp.cjs:45287:26)
        at ZipOpenFS.makeCallSync (/builds/frontend/blabla/.pnp.cjs:45514:14)
        at ZipOpenFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:45286:17)
        at VirtualFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:44592:24)
        at PosixFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:44592:24)
        at NodePathFS.writeFileSync (/builds/frontend/blabla/.pnp.cjs:44592:24)
        at compareScreenshots (/builds/frontend/blabla/packages/testing/src/utils/utils.ts:63:9)
```

We don't have such code in Playwright.  How do you compare screenshots?

**Comment by dimkin-eu** [comment]
utils.ts:63 is

```js
        await expect(page.locator(elementLocator)).toHaveScreenshot(`${filename}.png`)
```

i have a feeling this is something about yarn v3

**Comment by aslushnikov** [comment]
>utils.ts:63 is
> ```ts
>       await expect(page.locator(elementLocator)).toHaveScreenshot(`${filename}.png`) 
> ```

@dimkin-eu This is a playwright call, but the rest of the error stack you're getting has nothing to do with Playwright. Not sure how this is possible!

> i have a feeling this is something about yarn v3

This will make it a yarn v3 bug then. Could you try with NPM?

**Comment by theKashey** [comment]
> @dimkin-eu This is a playwright call, but the rest of the error stack you're getting has nothing to do with Playwright. Not sure how this is possible!

This is how yarn pnpm works - note mention of `ZipOpenFS.makeCallSync`. pnpm stores all deps as zip archives never unwrapping them into `node_modules`. 

However `yarn3` is not important here - I've got the same problem with yarn3
----
This is the line where `actual` will be `undefined` -
https://github.com/microsoft/playwright/blob/2697e936639cab64faec9e4adfc4f2848e621cc4/packages/playwright-test/src/matchers/toMatchSnapshot.ts#L403-L407

- if there is no error do something
- and if there is an error - save something
- but depending on the error `actual` might be `undefined`, because there was an error.

in my case it was `Timeout 5000ms exceeded`
