### ISSUE TITLE
[BUG] pytest: Firefox fails to run the sample test, shows SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by amittendulkar** [microsoft/playwright#19773]
This issue is similar to #19653

I am using Python 3.8.10 and playwright 1.29.0

The sample test runs fine on Chrome and Webkit but fails on Firefox.

```
(personal) PS D:\personal\playwright_learn> $env:NODE_EXTRA_CA_CERTS                                                          
D:\venv\personal\lib\site-packages\certifi\cacert.pem
(personal) PS D:\personal\playwright_learn> pytest
==================================================== test session starts ====================================================
platform win32 -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0
rootdir: D:\personal\playwright_learn
plugins: base-url-2.0.0, html-3.2.0, metadata-2.0.4, playwright-0.3.0
collected 1 item

test_my_application.py .                                                                                               [100%]

==================================================== 1 passed in 11.55s =====================================================
(personal) PS D:\personal\playwright_learn> pytest --browser webkit
==================================================== test session starts ====================================================
platform win32 -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0
rootdir: D:\personal\playwright_learn
plugins: base-url-2.0.0, html-3.2.0, metadata-2.0.4, playwright-0.3.0
collected 1 item

test_my_application.py .                                                                                               [100%]

===================================================== 1 passed in 9.31s ===================================================== 
(personal) PS D:\personal\playwright_learn> pytest --browser firefox
==================================================== test session starts ====================================================
platform win32 -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0
rootdir: D:\personal\playwright_learn
plugins: base-url-2.0.0, html-3.2.0, metadata-2.0.4, playwright-0.3.0
collected 1 item

test_my_application.py F                                                                                               [100%]

========================================================= FAILURES ========================================================== 
_______________ test_homepage_has_Playwright_in_title_and_get_started_link_linking_to_the_intro_page[firefox] _______________

page = <Page url='about:blank'>

    def test_homepage_has_Playwright_in_title_and_get_started_link_linking_to_the_intro_page(page: Page):
>       page.goto('https://playwright.dev/')

test_my_application.py:5:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
d:\venv\personal\lib\site-packages\playwright\sync_api\_generated.py:8961: in goto
    self._sync(
d:\venv\personal\lib\site-packages\playwright\_impl\_page.py:491: in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
d:\venv\personal\lib\site-packages\playwright\_impl\_frame.py:147: in goto
    await self._channel.send("goto", locals_to_params(locals()))
d:\venv\personal\lib\site-packages\playwright\_impl\_connection.py:44: in send
    return await self._connection.wrap_api_call(
d:\venv\personal\lib\site-packages\playwright\_impl\_connection.py:419: in wrap_api_call
    return await cb()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <playwright._impl._connection.Channel object at 0x000001A7CAE40E50>, method = 'goto'
params = {'url': 'https://playwright.dev/'}, return_as_dict = False

    async def inner_send(
        self, method: str, params: Optional[Dict], return_as_dict: bool
    ) -> Any:
        if params is None:
            params = {}
        callback = self._connection._send_message_to_server(self._guid, method, params)
        if self._connection._error:
            error = self._connection._error
            self._connection._error = None
            raise error
        done, _ = await asyncio.wait(
            {
                self._connection._transport.on_error_future,
                callback.future,
            },
            return_when=asyncio.FIRST_COMPLETED,
        )
        if not callback.future.done():
            callback.future.cancel()
>       result = next(iter(done)).result()
E       playwright._impl._api_types.Error: SEC_ERROR_UNKNOWN_ISSUER
E       =========================== logs ===========================
E       navigating to "https://playwright.dev/", waiting until "load"
E       ============================================================

d:\venv\personal\lib\site-packages\playwright\_impl\_connection.py:79: Error
================================================== short test summary info ================================================== 
FAILED test_my_application.py::test_homepage_has_Playwright_in_title_and_get_started_link_linking_to_the_intro_page[firefox] - playwright._impl._api_types.Error: SEC_ERROR_UNKNOWN_ISSUER
==================================================== 1 failed in 12.32s ===================================================== 
(personal) PS D:\personal\playwright_learn> 
```

Here is the sample test I am running,
```python
import re
from playwright.sync_api import Page, expect

def test_homepage_has_Playwright_in_title_and_get_started_link_linking_to_the_intro_page(page: Page):
    page.goto('https://playwright.dev/')

    expect(page).to_have_title(re.compile("Playwright"))

    get_started = page.get_by_role("link", name="Get Started")

    expect(get_started).to_have_attribute("href", "/docs/intro")

    get_started.click()

    expect(page).to_have_url(re.compile(".*intro"))
```

I confirmed that manually I am able to visit playwright.dev site on Firefox.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/18111340/209935080-ae32303f-23b4-4c9c-9ef9-091ac350f229.png">

Again, I have Zscaler installed and it presents its own certificate chain. I have appended the certificate to the Python virtual env and also set NODE_EXTRA_CA_CERTS variable to refer to the pem file indicated by `python -m certifi`.

**Comment by aslushnikov** [comment]
@amittendulkar Could you please try launching Firefox with `security.enterprise_roots.enabled: true` preference in Firefox using the 
 [`firefox_user_prefs `](https://playwright.dev/python/docs/next/api/class-browsertype#browser-type-launch-option-firefox-user-prefs) option?

**Comment by amittendulkar** [comment]
@aslushnikov with the above setting it is working,

```
(personal) PS C:\Users\amit_tendulkar> python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.sync_api import sync_playwright
>>> playwright = sync_playwright().start()
>>> # Use playwright.chromium, playwright.firefox or playwright.webkit
>>> # Pass headless=False to launch() to see the browser UI
>>> browser = playwright.firefox.launch(headless=False, firefox_user_prefs={"security.enterprise_roots.enabled": True})
>>> page = browser.new_page()
>>> page.goto("https://playwright.dev/")
<Response url='https://playwright.dev/' request=<Request url='https://playwright.dev/' method='GET'>>
```

If I don't use the above argument, it is failing,

```
(personal) PS C:\Users\amit_tendulkar> python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.sync_api import sync_playwright
>>> playwright = sync_playwright().start()
>>> # Use playwright.chromium, playwright.firefox or playwright.webkit
>>> # Pass headless=False to launch() to see the browser UI
>>> browser = playwright.firefox.launch(headless=False)
>>> page = browser.new_page()
>>> page.goto("https://playwright.dev/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\venv\personal\lib\site-packages\playwright\sync_api\_generated.py", line 8961, in goto
    self._sync(
  File "D:\venv\personal\lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "D:\venv\personal\lib\site-packages\playwright\_impl\_page.py", line 491, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "D:\venv\personal\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "D:\venv\personal\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "D:\venv\personal\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "D:\venv\personal\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: SEC_ERROR_UNKNOWN_ISSUER
=========================== logs ===========================
navigating to "https://playwright.dev/", waiting until "load"
============================================================
```

How do I customize the launch argument through `pytest`? Can you please point me to the associated documentation?

**Comment by amittendulkar** [comment]
I will close the issue for now. I will dig into https://playwright.dev/python/docs/test-runners#fixtures. It says using `browser_type_launch_args` under *Customizing fixture options*.

**Comment by amittendulkar** [comment]
The following code worked for me for pytest,

```python
import re
from typing import Dict
from playwright.sync_api import expect, BrowserType

def test_homepage_with_custom_options(browser_type_launch_args: Dict, browser_type: BrowserType):
    browser_type_launch_args['firefox_user_prefs'] = {"security.enterprise_roots.enabled": True}
    browser = browser_type.launch(**browser_type_launch_args)
    page = browser.new_page()
    page.goto('https://playwright.dev/')

    expect(page).to_have_title(re.compile("Playwright"))

    get_started = page.get_by_role("link", name="Get Started")

    expect(get_started).to_have_attribute("href", "/docs/intro")

    get_started.click()

    expect(page).to_have_url(re.compile(".*intro"))
```

Here is the output,
```
(personal) PS D:\personal\playwright_learn> pytest --browser chromium
========================================== test session starts ===========================================      
platform win32 -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0
rootdir: D:\personal\playwright_learn
plugins: base-url-2.0.0, html-3.2.0, metadata-2.0.4, playwright-0.3.0
collected 1 item

test_my_application.py .                                                                            [100%]      

=========================================== 1 passed in 12.13s ===========================================      
(personal) PS D:\personal\playwright_learn> pytest --browser firefox 
============================================= test session starts =============================================
platform win32 -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0
rootdir: D:\personal\playwright_learn
plugins: base-url-2.0.0, html-3.2.0, metadata-2.0.4, playwright-0.3.0
collected 1 item

test_my_application.py .                                                                                 [100%]

============================================= 1 passed in 13.24s ==============================================
(personal) PS D:\personal\playwright_learn> 
```

**Comment by amittendulkar** [comment]
Since the custom launch option is needed in all tests, adding the code for launch options that will be reused across all tests,

```python
import re
from typing import Dict
import pytest
from playwright.sync_api import Page, expect

@pytest.fixture(scope="session", autouse=True)
def launch_with_different_options(browser_type_launch_args: Dict):
    browser_type_launch_args['firefox_user_prefs'] = {"security.enterprise_roots.enabled": True}

def test_homepage_has_Playwright_in_title_and_get_started_link_linking_to_the_intro_page(page: Page):
    page.goto('https://playwright.dev/')

    expect(page).to_have_title(re.compile("Playwright"))

    get_started = page.get_by_role("link", name="Get Started")

    expect(get_started).to_have_attribute("href", "/docs/intro")

    get_started.click()

    expect(page).to_have_url(re.compile(".*intro"))

```
