### ISSUE TITLE
[Question] How to resolve ERR_PACKAGE_PATH_NOT_EXPORTED error from npx playwright test

### ISSUE THREAD

**Issue by capndave** [microsoft/playwright#19867]
Hi. We're getting the below error when running `npx playwright test` from within an Ubuntu container, in a Jenkins CI/CD job. Any idea what the issue could be? It appears that the `test` script from the package is not exported properly. Our project (with the playwright tests) uses node/common-js. We get the same error running without `xvfb-run`

```text
> xvfb-run npx playwright test --debug

Error: Package subpath './test' is not defined by "exports" in /home/jenkins/agent/workspace/c_Jobs_E2ETests_E2E_Test_devTest/node_modules/playwright/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:731:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolveFilename (/home/jenkins/agent/workspace/c_Jobs_E2ETests_E2E_Test_devTest/node_modules/@playwright/test/lib/transform.js:192:36)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jenkins/agent/workspace/c_Jobs_E2ETests_E2E_Test_devTest/playwright.config.js:2:43)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.A._compile (/home/jenkins/agent/workspace/c_Jobs_E2ETests_E2E_Test_devTest/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.t.<computed>.tu._extensions.<computed> (/home/jenkins/agent/workspace/c_Jobs_E2ETests_E2E_Test_devTest/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by mxschmitt** [comment]
Which Node version are you using? `node --version`

Also let us know which Playwright version you are using, you should not have `playwright` inside your package.json, only `@playwright/test`.

**Comment by mxschmitt** [comment]
closing for now, make sure to use Node.js 16+ then it should work as expected.

If you still encounter issues, feel free to re-file.
