### ISSUE TITLE
[REGRESSION]: selenium chrome instance hanging in a blank window

### ISSUE THREAD

**Issue by ngavrish** [microsoft/playwright#19989]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac OS
- Node.js version: v14.18.1
- Browser: Chromium
- Extra: Selenium grid 4.7.2

**Code Snippet**

docker-compose:
```yaml
version: "3"
services:
  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  edge:
    image: selenium/node-edge:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  firefox:
    image: selenium/node-firefox:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

Playwright.config.js
```javascript
// @ts-check
const { devices } = require('@playwright/test');

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();


/**
 * @see https://playwright.dev/docs/test-configuration
 * @type {import('@playwright/test').PlaywrightTestConfig}
 */
const config = {
  testDir: './tests',
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        //headless:false,
        screenshot: `on`,
        video: `on`,
        contextOptions: {recordVideo: { dir: "./videos"}},
        trace: `on`,
      },
    },
    // {
    //   name: `Chrome`,
    //   use: {
    //     browserName: `chromium`,
    //     channel: `chrome`,
    //     headless: false,
    //     viewport: { width: 1720, height: 850 },
    //     screenshot: `only-on-failure`,
    //     video: `retain-on-failure`,
    //     contextOptions: {recordVideo: { dir: "./videos"}},
    //     trace: `retain-on-failure`,
    //   },
    // },
    // {
    //   name: `Firefox`,
    //   use: {
    //     browserName: `firefox`,
    //     viewport: { width: 1720, height: 850 },
    //     ignoreHTTPSErrors: true,
    //     screenshot: `only-on-failure`,
    //     video: `retain-on-failure`,
    //     trace: `retain-on-failure`,
    //     launchOptions: {
    //       slowMo: 200,
    //     },
    //   },
    // },
    // {
    //   name: `Safari`,
    //   use: {
    //     browserName: `webkit`,
    //     viewport: { width: 1720, height: 850 },
    //     ignoreHTTPSErrors: true,
    //     screenshot: `only-on-failure`,
    //     video: `retain-on-failure`,
    //     trace: `retain-on-failure`,
    //   },
    // }
  ],

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  // outputDir: 'test-results/',

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   port: 3000,
  // },
};

module.exports = config;
```

Playwright.config.js
```javascript
// @ts-check
const { devices } = require('@playwright/test');

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();


/**
 * @see https://playwright.dev/docs/test-configuration
 * @type {import('@playwright/test').PlaywrightTestConfig}
 */
const config = {
  testDir: './tests',
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        //headless:false,
        screenshot: `on`,
        video: `on`,
        contextOptions: {recordVideo: { dir: "./videos"}},
        trace: `on`,
      },
    },
    // {
    //   name: `Chrome`,
    //   use: {
    //     browserName: `chromium`,
    //     channel: `chrome`,
    //     headless: false,
    //     viewport: { width: 1720, height: 850 },
    //     screenshot: `only-on-failure`,
    //     video: `retain-on-failure`,
    //     contextOptions: {recordVideo: { dir: "./videos"}},
    //     trace: `retain-on-failure`,
    //   },
    // },
    // {
    //   name: `Firefox`,
    //   use: {
    //     browserName: `firefox`,
    //     viewport: { width: 1720, height: 850 },
    //     ignoreHTTPSErrors: true,
    //     screenshot: `only-on-failure`,
    //     video: `retain-on-failure`,
    //     trace: `retain-on-failure`,
    //     launchOptions: {
    //       slowMo: 200,
    //     },
    //   },
    // },
    // {
    //   name: `Safari`,
    //   use: {
    //     browserName: `webkit`,
    //     viewport: { width: 1720, height: 850 },
    //     ignoreHTTPSErrors: true,
    //     screenshot: `only-on-failure`,
    //     video: `retain-on-failure`,
    //     trace: `retain-on-failure`,
    //   },
    // }
  ],

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  // outputDir: 'test-results/',

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   port: 3000,
  // },
};

module.exports = config;
```

TEST MODULE
```

const { test, expect } = require('@playwright/test');

test('test', async ({ page }) => {

  // Go to https://demo.playwright.dev/todomvc/
  await page.goto('https://demo.playwright.dev/todomvc/');

  // Go to https://demo.playwright.dev/todomvc/#/
  await page.goto('https://demo.playwright.dev/todomvc/#/');

  // Go to https://silverbird.com/
  await page.goto('https://silverbird.com/');

  // Click button[role="button"]:has-text("Accept")
  await page.click('button[role="button"]:has-text("Accept")');

  // Click text=Log In Open Account >> a
  await page.click('text=Log In Open Account >> a');
  // expect(page.url()).toBe('https://sso.silverbird.com/auth/realms/sbcu/protocol/openid-connect/auth?response_type=code&client_id=if-banking&scope=openid%20profile%20email&state=eGnfd7wzSFKQDU0fkv_Yd2GTQl5pdAd01mAm3y0AQ9o%3D&redirect_uri=https://my.silverbird.com/login/oauth2/code/sb-fo&nonce=ZhOz7QGCe3x5We2Te_XjY_HtnXnE2VTmY3mL2QgheYE');

  // Fill input[name="username"]
  await page.fill('input[name="username"]', 'nikita.gavrish@silverbird.com');

  // Press Tab
  await page.press('input[name="username"]', 'Tab');

  // Fill input[name="password"]
  await page.fill('input[name="password"]', 'abc');

  // Press CapsLock
  await page.press('input[name="password"]', 'CapsLock');

  // Fill input[name="password"]
  await page.fill('input[name="password"]', 'abcABC123');

  // Click input:has-text("Sign In")
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://sso.silverbird.com/auth/realms/sbcu/login-actions/authenticate?execution=2dfddc05-0532-488b-bf27-39bbcf6e769e&client_id=if-banking&tab_id=5FG3nwQMVX8' }*/),
    page.click('input:has-text("Sign In")')
  ]);

  // Click text=Invalid username or password.
  await page.click('text=Invalid username or password.');

  // Click text=Back to Main Page
  await page.click('text=Back to Main Page');
  expect(page.url()).toBe('https://silverbird.com/');

  // Click :nth-match(:text("Open Account"), 2)
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://join.silverbird.com/prequalification' }*/),
    page.click(':nth-match(:text("Open Account"), 2)')
  ]);

  // Click button:has-text("Continue")
  await page.click('button:has-text("Continue")');

  // Double click div:nth-child(6) .base-select .message .slide-up-down__container .messageFill__wrapper .messageFill__inner
  await page.dblclick('div:nth-child(6) .base-select .message .slide-up-down__container .messageFill__wrapper .messageFill__inner');

  // Double click :nth-match(:text("This field is required"), 2)
  await page.dblclick(':nth-match(:text("This field is required"), 2)');

  // Double click text=This field is required
  await page.dblclick('text=This field is required');

});
```
**Describe the bug**

docker-compose up -d
DEBUG=pw:browser* SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub npx playwright test

White blank browser just hangs there

Webdriver logs

```
chrome_1        | 11:09:50.883 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
chrome_1        | org.openqa.selenium.WebDriverException: java.lang.IllegalArgumentException: statusCode
chrome_1        | Build info: version: '4.7.2', revision: '4d4020c3b7'
chrome_1        | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '11.0.17'
chrome_1        | Driver info: driver.version: unknown
chrome_1        | 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.send(JdkHttpClient.java:239)
chrome_1        | 	at org.openqa.selenium.netty.server.WebSocketMessageHandler.lambda$channelRead0$0(WebSocketMessageHandler.java:47)
chrome_1        | 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
chrome_1        | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
chrome_1        | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
chrome_1        | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
chrome_1        | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
chrome_1        | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
chrome_1        | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
chrome_1        | 	at java.base/java.lang.Thread.run(Thread.java:829)
chrome_1        | Caused by: java.lang.IllegalArgumentException: statusCode
chrome_1        | 	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendClose(WebSocketImpl.java:301)
chrome_1        | 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.lambda$send$2(JdkHttpClient.java:222)
chrome_1        | 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.send(JdkHttpClient.java:229)
chrome_1        | 	... 9 more
chrome_1        | 11:10:19.985 INFO [LocalNode.stopTimedOutSession] - Session id 27f98116f6bff28477a85b1f44b51994 timed out, stopping...
chrome_1        | 11:10:20.170 INFO [SessionSlot.stop] - Stopping session 27f98116f6bff28477a85b1f44b51994
selenium-hub    | 11:10:20.173 INFO [GridModel.release] - Releasing slot for session id 27f98116f6bff28477a85b1f44b51994
selenium-hub    | 11:10:20.173 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: 27f98116f6bff28477a85b1f44b51994
selenium-hub    | 11:10:20.821 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
selenium-hub    | org.openqa.selenium.WebDriverException: java.io.IOException: Output closed
selenium-hub    | Build info: version: '4.7.2', revision: '4d4020c3b7'
selenium-hub    | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '11.0.17'
selenium-hub    | Driver info: driver.version: unknown
selenium-hub    | 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.send(JdkHttpClient.java:239)
selenium-hub    | 	at org.openqa.selenium.netty.server.WebSocketMessageHandler.lambda$channelRead0$0(WebSocketMessageHandler.java:47)
selenium-hub    | 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
selenium-hub    | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
selenium-hub    | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
selenium-hub    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
selenium-hub    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
selenium-hub    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
selenium-hub    | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
selenium-hub    | 	at java.base/java.lang.Thread.run(Thread.java:829)
selenium-hub    | Caused by: java.io.IOException: Output closed
selenium-hub    | 	at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
selenium-hub    | 	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
selenium-hub    | 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.lambda$send$1(JdkHttpClient.java:218)
selenium-hub    | 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.send(JdkHttpClient.java:229)
selenium-hub    | 	... 9 more
chrome_1        | 11:15:19.764 INFO [LocalNode.stopTimedOutSession] - Session id d022e2ac36615b78fe22f2498b7cbbb0 timed out, stopping...
chrome_1        | 11:15:19.841 INFO [SessionSlot.stop] - Stopping session d022e2ac36615b78fe22f2498b7cbbb0
selenium-hub    | 11:15:19.844 INFO [GridModel.release] - Releasing slot for session id d022e2ac36615b78fe22f2498b7cbbb0
selenium-hub    | 11:15:19.844 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: d022e2ac36615b78fe22f2498b7cbbb0
```

**Comment by aslushnikov** [comment]
@ngavrish you say "regression" - did it use to work?

**Comment by ltsuda** [comment]
it might be similar or the same as https://github.com/microsoft/playwright/issues/18892

I've tried his files just to troubleshoot/repro and got the same issue.

Windows 11 (WSL2 Ubuntu 22.04)
Playwright/Test 1.29.2

I've tried modifying `SE_NODE_GRID_URL=http://localhost:4444/` to `SE_NODE_GRID_URL=http://localhost:4444/wd/hub` but got the issue too.

The only thing I noticed by running in headed mode is there are two browser window open, one empty and the other one navigated to the expected page but timed out to click in the Accept.

![image](https://user-images.githubusercontent.com/3965277/212241490-f5f34865-531d-4e75-a047-bfc2b18b3676.png)

**Comment by aslushnikov** [comment]
Thank you @ltsuda for the help! Indeed seems to be the same as https://github.com/microsoft/playwright/issues/18892. Merging there as a dupe!
