### ISSUE TITLE
[Question] How to transform vue file for component test import into spec file?

### ISSUE THREAD

**Issue by davidAtInleague** [microsoft/playwright#20013]
I have a spec file like
```
import { test, expect } from '@playwright/experimental-ct-vue';
import Foo from "@app/Foo.vue"
test('should work', async ({ mount }) => {
  console.log(Foo);
});
```

When I run `yarn test-ct` I get
```
/...snip.../Foo.vue:1
<template lang="pug">
^

SyntaxError: Unexpected token '<'

    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1094:15)
    at Module._compile (node:internal/modules/cjs/loader:1129:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.t.<computed>.tu._extensions.<computed> [as .js] (/...snip.../node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/...snip.../tests/pwct/xlel.spec.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module.A._compile (/...snip.../node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.t.<computed>.tu._extensions.<computed> [as .ts] (/...snip.../node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1043:32)

```

So it dies on the first character -- am I missing a transformation step? So far all I've done is `yarn create playwright --ct`, make sure all my playwright dependencies are pinned to the same version, and then create this test file.

**Comment by sand4rt** [comment]
Seems like the `vite-plugin-pug` is not defined in `playwright.config.ts`. Playwright does not reuse the Vite configuration yet. For more info see: https://playwright.dev/docs/test-components#q-how-can-i-use-vite-plugins.

Related to: https://github.com/microsoft/playwright/issues/14749

**Comment by davidAtInleague** [comment]
Hm, OK, I need to look into that. My immediate concern is that it fails on the first token, rather than after parsing pug stuff, but yes I see that it could be a pug related plugin issue (and maybe the "real" error indicating that fact got discarded somewhere in the transformation pipeline).

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
