### ISSUE TITLE
[Question] window.stop() makes page.goto never resolve

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#20247]
I am not sure if it is now the correct behavior or not, but
in playwright version 1.25 this worked, after update to 1.29 it stopped working.
A very small repro
```typescript
test.only("load", async ({ page }) => {
        await page.goto("http://127.0.0.1:5500/index.html", { waitUntil: "load" });
    });
```
which visits this html page
```html
<!DOCTYPE html>
<html>
<head>
    <title>Title</title>
</head>
<body>
 <img src="https://picsum.photos/seed/picsum/200/300" />
 
 <script>window.stop();</script>
</body>
</html>
```

in 1.25 this test passes
and in 1.29 this fails with this error
```
 Test timeout of 60000ms exceeded.

    page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "http://127.0.0.1:5500/index.html", waiting until "load"
    ============================================================

      12 |
      13 |     test.only("load", async ({ page }) => {
    > 14 |         await page.goto("http://127.0.0.1:5500/index.html", { waitUntil: "load" });
         |                    ^
      15 |     });
      16 |
      17 |     test("paint timings", async ({ dtPage }) => {

        at file:///C:/workspaces/repositories/abc/packages/playwright-tests/source/tests/stable/modules/9_web-vitals/9_web-vitals.spec.ts:14:20
        at C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\workerRunner.js:376:15
        at TestInfoImpl._runFn (C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\testInfo.js:144:7)
        at C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\workerRunner.js:331:26
        at TimeoutManager.runWithTimeout (C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\timeoutManager.js:62:7)
        at TestInfoImpl._runWithTimeout (C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\testInfo.js:133:26)
        at WorkerRunner._runTest (C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\workerRunner.js:312:5)
        at WorkerRunner.runTestGroup (C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\workerRunner.js:192:11)
        at process.<anonymous> (C:\workspaces\repositories\abc\node_modules\.pnpm\@playwright+test@1.29.2\node_modules\@playwright\test\lib\worker.js:74:5)

```

We have a very exotic test case that used `window.stop();` which started failing with this when we did an update from 1.25 to 1.29.
I opened this issue, not as a bug, but as a question, to verify if this is the correct behavior now or not.
I tested this using `@playwright/test` and `chromium` on `windows`

**Comment by yury-s** [comment]
This behavior was changed by https://github.com/microsoft/playwright/pull/16861. Your page does not fire 'load' event, so `page.goto()` never finishes (prior to that change playwright was firing that event artificially). As a workaround you can pass custom 'waitUntil' option to page.goto.
