### ISSUE TITLE
[BUG] [Java] Cannot find object to call __adopt__" error appears after updating playwright 1.17 to 1.28 

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [microsoft/playwright#20250]
**Context:**
- Playwright Version: 1.28.0 and 1.29.0
- Operating System: Linux
- Browser: Chromium
- Extra: Playwright for java
- Tests executed in parallel mode (10-20 threads)
- 60% of tests area failed due to this bug (28 of 45 tests)

**Describe the bug**

```
com.microsoft.playwright.PlaywrightException: Cannot find object to call __adopt__: page@dc44a43c7246ce63f53bcffd98c83d8e
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:218)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.FrameImpl.waitForSelectorImpl(FrameImpl.java:1064)
	at com.microsoft.playwright.impl.LocatorImpl.lambda$waitForImpl$7(LocatorImpl.java:555)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.LocatorImpl.waitForImpl(LocatorImpl.java:555)
	at com.microsoft.playwright.impl.LocatorImpl.waitFor(LocatorImpl.java:551)
	at com.tradeix.stepdefs.ui.pages.CommonPage.waitPageLoaded(CommonPage.kt:76)
```
```
com.microsoft.playwright.PlaywrightException: Cannot find object to call __adopt__: page@cc95979e5f4752982d4ce66eafc3a1eb
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:218)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:98)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPageImpl(BrowserContextImpl.java:355)
	at com.microsoft.playwright.impl.BrowserContextImpl.lambda$newPage$12(BrowserContextImpl.java:348)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPage(BrowserContextImpl.java:348)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPage(BrowserContextImpl.java:43)
```

as you can see this error raised in different parts of code

**Comment by yury-s** [comment]
We need to be able to reproduce the problem to make this report actionable. Could you share a reproducible example which we could run locally?

**Comment by ocherniavskyi-lohika-tix** [comment]
@yury-s Thanks for feedback, ive added zip file with code example

**Comment by yury-s** [comment]
Thanks for the repro, I can repeat it locally, we'll have a look.
