### ISSUE TITLE
[BUG] Tests are not being discovered by VSCode on Mac

### ISSUE THREAD

**Issue by hrust14** [microsoft/playwright#20311]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 16.19
- Browser: ALL
- Extra: No

## System:
 - OS: macOS 12.5
 - Memory: 84.28 MB / 8.00 GB
## Binaries:
 - Node: 16.19.0 - /opt/homebrew/opt/node@16/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright-test: ^8.1.2 => 8.1.2 
 - 
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```Simply clone [the repo](https://github.com/akshayp7/playwright-typescript-playwright-test) and try it on Mac. Try modifying the test to run something simple. Thanks. 

Run Login.test.ts and input this:
import test from '@lib/BaseTest';

test(`Login`, async ({ loginPage }) => {
    await loginPage.navigateToURL();
    await loginPage.loginToApplication();
});

#In testConfig.ts
change qa to beta and put any URL, because it doesn't matter as it fails beforehand.

```

Try running the test as "npx cross-env ENV=beta npm run test"

Console output shows these:

```
> nrustam@1.0.0 test
> npx playwright test

Error: Cannot find module './global-setup'
Require stack:
- /Users/X/PW/node_modules/@playwright/test/lib/loader.js
- /Users/X/PW/node_modules/@playwright/test/lib/runner.js
- /Users/X/PW/node_modules/@playwright/test/lib/cli.js
- /Users/X/PW/node_modules/playwright-core/lib/cli/cli.js
- /Users/X/PW/node_modules/playwright-core/cli.js
- /Users/X/PW/node_modules/@playwright/test/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at resolveScript (/Users/X/PW/node_modules/@playwright/test/lib/loader.js:574:18)
    at Loader._processConfigObject (/Users/X/PW/node_modules/@playwright/test/lib/loader.js:103:50)
    at Loader.loadConfigFile (/Users/X/PW/node_modules/@playwright/test/lib/loader.js:65:16)
    at Runner.loadConfigFromResolvedFile (/Users/X/PW/node_modules/@playwright/test/lib/runner.js:68:12)
    at runTests (/Users/X/PW/node_modules/@playwright/test/lib/cli.js:153:27)
    at Gi.<anonymous> (/Users/X/PW/node_modules/@playwright/test/lib/cli.js:71:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/X/PW/node_modules/@playwright/test/lib/loader.js',
    '/Users/X/PW/node_modules/@playwright/test/lib/runner.js',
    '/Users/X/PW/node_modules/@playwright/test/lib/cli.js',
    '/Users/X/PW/node_modules/playwright-core/lib/cli/cli.js',
    '/Users/X/PW/node_modules/playwright-core/cli.js',
    '/Users/X/PW/node_modules/@playwright/test/cli.js'
  ]
}
```

**Describe the bug**

On Mac, either on InteliJ or VSCode under Testing it says "Install Additional Test Extensions" and it cannot run tests.

**Comment by pavelfeldman** [comment]
Playwright can't resolve your global setup file. Check that your playwright.config's globalSetup entry points to the existing file.

**Comment by hrust14** [comment]
> Playwright can't resolve your global setup file. Check that your playwright.config's globalSetup entry points to the existing file.

Thank you for a quick reply. This is what I got:

```
import { PlaywrightTestConfig} from '@playwright/test';
import { testConfig } from './testConfig';
const ENV = process.env.ENV;

if (!ENV || ![`beta`, `dev`].includes(ENV)) {
  console.log(`Please provide a correct environment value like "npx cross-env ENV=beta|dev"`);
  process.exit();
}

const config: PlaywrightTestConfig = {
  // testDir: testConfig.testDir,

  //Global Setup to run before all tests
  globalSetup: './global-setup',

  //Global Teardown to run after all tests
  globalTeardown: `./global-teardown`,

  //sets timeout for each test case
  timeout: 120000,

  //number of retries if test case fails
  retries: 0,

  projects: [
    {
      name: `Chrome`,
      use: {
        // Configure the browser to use.
        browserName: `chromium`,

        //Chrome Browser Config
        channel: `chrome`,

        //Picks Base Url based on User input
        baseURL: testConfig[ENV],

        //Browser Mode
        headless: false,

      },
    },
  ],
};
export default config;
```

**Comment by hrust14** [comment]
Thank you. Resolved. Like you said was pointing to the wrong file path.
