### ISSUE TITLE
[BUG] Clicking the checkbox did not change its state

### ISSUE THREAD

**Issue by harikrishna553** [microsoft/playwright#20429]
**Context:**
- Playwright Version: [1.28.1]
- Operating System: [Mac]
- Java version: [1.8]
- Browser: [Chromium]

**Code Snippet**

```java
package com.sample.app.locators;

import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.sample.app.util.FileUtil;

public class CheckOrUncheck {
	private static final String html = "<html>\n"
			+ "\n"
			+ "<body>\n"
			+ "\n"
			+ "	<h1>Multi select demo</h1>\n"
			+ "\n"
			+ "\n"
			+ "	<form onsubmit=\"return false;\">\n"
			+ "		<label for=\"colors\">Choose a color:</label>\n"
			+ "		<select name=\"colors\" id=\"favoriteColors\" multiple>\n"
			+ "			<option value=\"red\">Red</option>\n"
			+ "			<option value=\"green\">Green</option>\n"
			+ "			<option value=\"yellow\">Yellow</option>\n"
			+ "			<option value=\"blue\">blue</option>\n"
			+ "		</select>\n"
			+ "		<br><br>\n"
			+ "		<input type=\"submit\" value=\"Submit\" onclick=\"display()\">\n"
			+ "	</form>\n"
			+ "\n"
			+ "	<p id=\"result\"></p>\n"
			+ "\n"
			+ "	<script>\n"
			+ "		function display() {\n"
			+ "			let options = document.getElementById('favoriteColors').selectedOptions;\n"
			+ "			let values = Array.from(options).map(({value}) => value);\n"
			+ "			let selectedColors = values.join(\"-->\");\n"
			+ "			\n"
			+ "			console.log(values)\n"
			+ "			result.innerHTML = `<b>Selected colors: <br />${selectedColors}</b>`\n"
			+ "		}\n"
			+ "	</script>\n"
			+ "\n"
			+ "\n"
			+ "</body>\n"
			+ "\n"
			+ "</html>";
	
	public static void main(String[] args){
		try (Playwright playwright = Playwright.create()) {

			Browser browser = playwright.chromium()
					.launch(new BrowserType.LaunchOptions().setHeadless(false).setSlowMo(100));

		
			Page page = browser.newPage();
			page.setContent(html);

			page.locator("#favoriteColors").locator("option[value=\"red\"]").setChecked(true);
			page.locator("input[type=\"submit\"]").click();

			String textContent = page.locator("id=result").textContent();
			System.out.println(textContent);

		}
	}
}
```

**Describe the bug**

```java
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Error {
  message='Clicking the checkbox did not change its state
=========================== logs ===========================
waiting for locator("#favoriteColors").locator("option[value=\"red\"]")
  locator resolved to visible <option value="red">Red</option>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
============================================================
  name='Error
  stack='Error: Clicking the checkbox did not change its state
=========================== logs ===========================
waiting for locator("#favoriteColors").locator("option[value=\"red\"]")
  locator resolved to visible <option value="red">Red</option>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
============================================================
    at ElementHandle._setChecked (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/dom.js:673:46)
    at async /private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/frames.js:926:24
    at async Frame.retryWithProgress (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/frames.js:890:24)
    at async /private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/frames.js:1130:29
    at async ProgressController.run (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/progress.js:97:22)
    at async FrameDispatcher.check (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/dispatchers/frameDispatcher.js:258:12)
    at async DispatcherConnection.dispatch (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/dispatchers/dispatcher.js:317:22)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:111)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.FrameImpl.checkImpl(FrameImpl.java:237)
	at com.microsoft.playwright.impl.FrameImpl.setCheckedImpl(FrameImpl.java:720)
	at com.microsoft.playwright.impl.FrameImpl.lambda$setChecked$34(FrameImpl.java:715)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.FrameImpl.setChecked(FrameImpl.java:715)
	at com.microsoft.playwright.impl.LocatorImpl.setChecked(LocatorImpl.java:463)
	at com.microsoft.playwright.Locator.setChecked(Locator.java:3483)
	at com.sample.app.locators.CheckOrUncheck.main(CheckOrUncheck.java:61)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Clicking the checkbox did not change its state
=========================== logs ===========================
waiting for locator("#favoriteColors").locator("option[value=\"red\"]")
  locator resolved to visible <option value="red">Red</option>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
============================================================
  name='Error
  stack='Error: Clicking the checkbox did not change its state
=========================== logs ===========================
waiting for locator("#favoriteColors").locator("option[value=\"red\"]")
  locator resolved to visible <option value="red">Red</option>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
============================================================
    at ElementHandle._setChecked (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/dom.js:673:46)
    at async /private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/frames.js:926:24
    at async Frame.retryWithProgress (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/frames.js:890:24)
    at async /private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/frames.js:1130:29
    at async ProgressController.run (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/progress.js:97:22)
    at async FrameDispatcher.check (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/dispatchers/frameDispatcher.js:258:12)
    at async DispatcherConnection.dispatch (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-3637192182376041728/package/lib/server/dispatchers/dispatcher.js:317:22)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:201)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	... 13 more
```

**Comment by harikrishna553** [comment]
It is working as expected with the checkboxes. previously tried with select element.
