### ISSUE TITLE
[BUG] page.tap() method is not working

### ISSUE THREAD

**Issue by harikrishna553** [microsoft/playwright#20430]
**Context:**
- Playwright Version: [1.28.1
- Operating System: [Mac]
- Node.js version: [1.8]
- Browser: [Chromium]

**Code Snippet**

```java

import java.io.IOException;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;

public class TapElementDemo {
	public static void main(String[] args) throws IOException {
		try (Playwright playwright = Playwright.create()) {

			Browser browser = playwright.chromium()
					.launch(new BrowserType.LaunchOptions().setHeadless(false).setSlowMo(100).setTimeout(5000));

			Page page = browser.newPage();

			page.setContent("<div id='a' style='background: lightblue; width: 50px; height: 50px'>a</div>\n"
					+ "<div id='b' style='background: pink; width: 50px; height: 50px'>b</div>");
			page.tap("#a");

		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

```

**Describe the bug**

```java
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing tap action
waiting for locator("#a")
  locator resolved to visible <div id="a">a</div>
attempting tap action
  waiting for element to be visible, enabled and stable
============================================================
    at ProgressController.run (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-6556649766967446505/package/lib/server/progress.js:93:26)
    at Frame.tap (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-6556649766967446505/package/lib/server/frames.js:982:23)
    at FrameDispatcher.tap (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-6556649766967446505/package/lib/server/dispatchers/frameDispatcher.js:155:30)
    at DispatcherConnection.dispatch (/private/var/folders/4f/521_86pd6sjfkc7qsr4b5_k00000gq/T/playwright-java-6556649766967446505/package/lib/server/dispatchers/dispatcher.js:317:46)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:199)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	... 11 more

```

**Comment by pavelfeldman** [comment]
You need to call [setHasTouch](https://playwright.dev/java/docs/next/api/class-browser#browser-new-context-option-has-touch) when creating the context. It is poorly documented in https://playwright.dev/java/docs/next/api/class-touchscreen, so we should throw when that happens.

**Comment by harikrishna553** [comment]
Thanks, it works
