### ISSUE TITLE
[BUG] Webkit: exposeFunction hangs with devtools opened

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#20535]
**Context:**
- Playwright Version: 1.30.0
- Operating System: MacOS
- Node.js version: v14
- Browser: WebKit

**Code Snippet**

```javascript
import { test, expect } from "@playwright/test";

test("exposed", async ({ page }) => {
  const logs = [];
  await page.on("console", (msg) => logs.push(msg));
  await page.goto(
    "https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_todo_list_beginning"
  );
  await page.exposeFunction("someDummyExposedFunction", () =>
    console.log("someDummyExposedFunction was called")
  );

  for(let i = 0; i < 50; i++) {
    await page.reload();
  }

  expect(logs.length).toBe(0);
});
```

**Describe the bug**

I found this while trying to debug an issue on a website using Webkit.

**Steps to reproduce**
 * Add a breakpoint on the `page.exposeFunction` line.
 * Launch this test using webkit with the debugger enabled.
 * When it hits the breakpoint, open Webkit's devtools.
 * Let the code run.

You will eventually get this error:

```
Error: Target closed

        at /Users/dario/Code/local/playwright-test/node_modules/@playwright/test/node_modules/playwright-core/lib/server/webkit/wkConnection.js:140:16
        at new Promise (<anonymous>)
        at WKSession.send (/Users/dario/Code/local/playwright-test/node_modules/@playwright/test/node_modules/playwright-core/lib/server/webkit/wkConnection.js:136:12)
        at WKPage.exposeBinding (/Users/dario/Code/local/playwright-test/node_modules/@playwright/test/node_modules/playwright-core/lib/server/webkit/wkPage.js:740:19)
        at Page.exposeBinding (/Users/dario/Code/local/playwright-test/node_modules/@playwright/test/node_modules/playwright-core/lib/server/page.js:201:26)
        at PageDispatcher.exposeBinding (/Users/dario/Code/local/playwright-test/node_modules/@playwright/test/node_modules/playwright-core/lib/server/dispatchers/pageDispatcher.js:115:22)
```

It's not something that would break a test, because you wouldn't test with devtools opened. But It's a headache if you need to triage some issues in Webkit, and I also thought that it might uncover some bug in the engine.

**Comment by mxschmitt** [comment]
Looks like its related to https://github.com/microsoft/playwright/issues/17480.

**Comment by dgozman** [comment]
This is a [known limitation](https://playwright.dev/docs/troubleshooting#webkit-web-inspector). Closing in favor of #17480.
