### ISSUE TITLE
[Question] What versions of Node.js does Playwright support?

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#2059]
What version(s) of Node.js does Playwright official support?

See https://github.com/microsoft/playwright/issues/1988 and https://github.com/microsoft/playwright/pull/1989 for related issues/MRs.

If there is an official supported version set, I'll re-open https://github.com/microsoft/playwright/pull/1989; if there's no official set, please mark this issue as closed.

**Comment by mxschmitt** [comment]
Hey, #1988 was a bug in Node.js 14 (which should be normally very rare) and in general Playwright supports Node.js 10.15+ see [here](https://github.com/microsoft/playwright/blob/master/docs/installation.md#system-requirements) which will be also covered soon on the website.

**Comment by rwoll** [comment]
Is it helpful to have the checks in https://github.com/microsoft/playwright/pull/1989 to ensure the compatibility guarantees, or does that mostly just slow down builds without much benefit since #1988 bugs are likely rare?

I also may be missing a CI config where Playwright already does an equivalent build matrix proposed in #1989.

**Comment by aslushnikov** [comment]
We target earliest Active LTS Node.js version - which is currently 10. I wouldn't run all our tests on all node.js versions - that's probably too much, but we can run smoke tests on even node.js versions.

We already have `test-package-installations` tests that verify that playwright installs and runs a simple playwright script. I'd run this on node 14 as well.

@rwoll are you interested in contributing this?

**Comment by rwoll** [comment]
> @rwoll are you interested in contributing this?

Yes, I'll take a look!

**Comment by jevgenijusmarinuskinas** [comment]
Still relevant. I am getting an error when running `npx playwright install` on Node 10.16.3:

`PS C:\Users\t\Documents\Projects\test> npx playwright install
C:\Users\t\Documents\Projects\test\node_modules\@playwright\test\lib\grid\gridServer.js:143
  constructor(capacity = Infinity, creationTimeout = 5 * 60_000) {
                                                         ^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\t\Documents\Projects\test\node_modules\@playwright\test\lib\cli\cli.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)`

**Comment by mxschmitt** [comment]
@jevgenijusmarinuskinas Node.js 12+ is required.
