### ISSUE TITLE
[BUG] Opening links with target="_blank" crashes WebKit

### ISSUE THREAD

**Issue by alexduhanov** [microsoft/playwright#2079]
**Context:**
- Playwright Version: 0.16
- Operating System: MacOS 10.15.4
- Node version: 10.16.3
- Browser: WebKit

Test:
```javascript
await page.waitForSelector('"Click me"');
await page.click('"Click me"');
```
Page:
```html
<a href="http://www.example.com" target="_blank">Click me</a>
```

Error thrown:
```javascript
Error: 

    at Object.assert (/Users/alex/git/playwright-test/node_modules/playwright-core/lib/helper.js:288:15)
    at WKPage._onTargetCreated (/Users/alex/git/playwright-test/node_modules/playwright-core/lib/webkit/wkPage.js:226:22)
    at WKSession.emit (events.js:198:13)
    at Promise.resolve.then (/Users/alex/git/playwright-test/node_modules/playwright-core/lib/webkit/wkConnection.js:131:47)
```

**Describe the bug**

Attempting to open a link with target="_blank" seems to crash WebKit.

I've provided a repo where you should be able to recreate this:

https://github.com/alexduhanov/playwright-test

**Comment by alexduhanov** [comment]
In further testing, I changed the link to a localhost location, and the crash did not occur. Changing it back to a different domain caused the crashing behavior again.

**Comment by bernardobridge** [comment]
Having this issue too!
