### ISSUE TITLE
[BUG] Docker container error: checkExecSyncError

### ISSUE THREAD

**Issue by rafitur2** [microsoft/playwright#20843]
Hi,

I'm trying to run playwright npx test via docker js container, facing the below error (same code is working from windows):

back_end     | Error: Command failed: npx playwright test tests/test3.spec.js
back_end     |     at checkExecSyncError (node:child_process:841:11)
back_end     |     at execSync (node:child_process:912:15)
back_end     |     at /app/app.js:28:17
back_end     |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
back_end     |     at next (/app/node_modules/express/lib/router/route.js:144:13)
back_end     |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
back_end     |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
back_end     |     at /app/node_modules/express/lib/router/index.js:284:15
back_end     |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)

**app. js:** 

const express = require('express')
const app = express()
const port = 3000

app.get('/run',  (req, res) => {
   
const {execSync}  = require('child_process');
const results = execSync('npx playwright test tests/test3.spec.js', {encoding : 'utf8'});
console.log(results);
console.log(testResults);
res.send(testResults)

})
app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})

**Dockerfile:**
FROM mcr.microsoft.com/playwright:v1.24.0-focal
WORKDIR /tests
COPY . .
RUN npm install
RUN npx @playwright/test install

FROM node:16.17.0-slim
WORKDIR /app
RUN npm i -g npm@8.15.0
COPY ./package*.json ./
RUN npm install
COPY . .
CMD [ "node", "app.js" ]

**test file:** 
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

**docker compose yml:**
services:

  back_end:
    image: playwrightbackend:latest
    container_name: back_end
    restart: always
    ports:
      - '3000:3000'

Could you please suggest?

**Comment by rafitur2** [comment]
I managed to fix the dockerfile
