### ISSUE TITLE
Failed to download/install browsers 

### ISSUE THREAD

**Issue by shravanvh** [microsoft/playwright#20863]
When I'm trying to run the 'npx playwright install' command for installing the browsers post setting the HTTPS_PROXY and PLAYWRIGHT_DOWNLOAD_CONNECTION_TIMEOUT. I'm still seeing the below error:

```
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright.azureedge.net/builds/chromium/1045/chromium-win64.zip
Error [ERR_SOCKET_CLOSED]: Socket is closed
    at new NodeError (node:internal/errors:387:5)
    at Socket._writeGeneric (node:net:864:8)
    at Socket._write (node:net:886:8)
    at doWrite (node:internal/streams/writable:410:12)
    at clearBuffer (node:internal/streams/writable:571:7)
    at Socket.Writable.uncork (node:internal/streams/writable:350:7)
    at ClientRequest._flushOutput (node:_http_outgoing:1049:10)
    at ClientRequest._flush (node:_http_outgoing:1018:22)
    at onSocketNT (node:_http_client:869:9)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_SOCKET_CLOSED'
}
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright-akamai.azureedge.net/builds/chromium/1045/chromium-win64.zip
Error [ERR_SOCKET_CLOSED]: Socket is closed
    at new NodeError (node:internal/errors:387:5)
    at Socket._writeGeneric (node:net:864:8)
    at Socket._write (node:net:886:8)
    at doWrite (node:internal/streams/writable:410:12)
    at clearBuffer (node:internal/streams/writable:571:7)
    at Socket.Writable.uncork (node:internal/streams/writable:350:7)
    at ClientRequest._flushOutput (node:_http_outgoing:1049:10)
    at ClientRequest._flush (node:_http_outgoing:1018:22)
    at onSocketNT (node:_http_client:869:9)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_SOCKET_CLOSED'
}
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright-verizon.azureedge.net/builds/chromium/1045/chromium-win64.zip
Error [ERR_SOCKET_CLOSED]: Socket is closed
    at new NodeError (node:internal/errors:387:5)
    at Socket._writeGeneric (node:net:864:8)
    at Socket._write (node:net:886:8)
    at doWrite (node:internal/streams/writable:410:12)
    at clearBuffer (node:internal/streams/writable:571:7)
    at Socket.Writable.uncork (node:internal/streams/writable:350:7)
    at ClientRequest._flushOutput (node:_http_outgoing:1049:10)
    at ClientRequest._flush (node:_http_outgoing:1018:22)
    at onSocketNT (node:_http_client:869:9)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_SOCKET_CLOSED'
}
Failed to install browsers
Error: Failed to download Chromium 110.0.5481.38 (playwright build v1045), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (C:\Users\600012727\Playwright_Automation\node_modules\playwright-core\lib\server\registry\browserFetcher.js:95:16)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by aslushnikov** [comment]
@shravanvh if you have a proxy that you configured with `HTTPS_PROXY` env variable, then it looks like this proxy doesn't let you download browsers. 

Can you download manually from the given URL? E.g. this one - https://playwright.azureedge.net/builds/chromium/1045/chromium-win64.zip ?

**Comment by shravanvh** [comment]
Thanks @aslushnikov . I was able to manually download it from the above URL and place it in the : Playwright_Automation\node_modules\playwright-core\.local-browsers  path. 

Please let me know if I'm correct, if yes do I need to do the same for all the browser binaries?. If yes, Can you please comment the path for them as well. Thanks in advance!

**Comment by aslushnikov** [comment]
@shravanvh as a work-around, you can download & put them at whatever location is convenient for you. You'll need to refer to the binaries using `executablePath` option in the [`browserType.launch()`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch) method.

However, long-term I'd recommend figuring out what exactly aborts automatic download of browser binaries. We won't be able to help much here though since this is specific to your host setup, so I'll have to close this issue.

**Comment by BanKnight** [comment]
> 

same issue here

```bash
Removing unused browser at C:\Users\tufei\AppData\Local\ms-playwright\firefox-1378
Downloading Firefox 109.0 (playwright build v1378) from https://playwright.azureedge.net/builds/firefox/1378/firefox-win64.zip      
79 Mb [====================] 99% 0.1sFailed to install browsers
Error: Failed to download Firefox 109.0 (playwright build v1378), caused by
Error: end of central directory record signature not found
    at D:\myprojects\zhihu-bot\node_modules\playwright-core\lib\zipBundleImpl.js:1:24033
    at D:\myprojects\zhihu-bot\node_modules\playwright-core\lib\zipBundleImpl.js:1:31712
    at D:\myprojects\zhihu-bot\node_modules\playwright-core\lib\zipBundleImpl.js:1:17288
    at FSReqCallback.wrapper [as oncomplete] (node:fs:681:5)
```

**Comment by anandhakrishnanr** [comment]
@BanKnight I am facing the similar issue right now. Did you find any solution for the above issue?

**Comment by michaelcheers** [comment]
> > 
> 
> same issue here
> 
> ```shell
> Removing unused browser at C:\Users\tufei\AppData\Local\ms-playwright\firefox-1378
> Downloading Firefox 109.0 (playwright build v1378) from https://playwright.azureedge.net/builds/firefox/1378/firefox-win64.zip      
> 79 Mb [====================] 99% 0.1sFailed to install browsers
> Error: Failed to download Firefox 109.0 (playwright build v1378), caused by
> Error: end of central directory record signature not found
>     at D:\myprojects\zhihu-bot\node_modules\playwright-core\lib\zipBundleImpl.js:1:24033
>     at D:\myprojects\zhihu-bot\node_modules\playwright-core\lib\zipBundleImpl.js:1:31712
>     at D:\myprojects\zhihu-bot\node_modules\playwright-core\lib\zipBundleImpl.js:1:17288
>     at FSReqCallback.wrapper [as oncomplete] (node:fs:681:5)
> ```



> @BanKnight I am facing the similar issue right now. Did you find any solution for the above issue?

Make a new issue

**Comment by FraneCal** [comment]
I have the same issue and I have downloaded it manually, but where do I store that file. This is how my "Playwright" map looks like.

**Comment by FraneCal** [comment]
I have the same issue and I have download it manually but my "playwright" map only has the following maps (along with couple of files): __pycache__, _impl, async_api, driver and syncs_api. Where should I save it?
