### ISSUE TITLE
[BUG] sync_api.sync_playwright().start() hangs when built using cx_freeze

### ISSUE THREAD

**Issue by OllieParsons-BH** [microsoft/playwright#20947]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Windows 10
- Browser: Chromium
- Extra: pipenv 2022.1.8, Python 3.9.9

**Code Snippet**

```python
class WebDriver(metaclass=_SingletonMeta):
    """Web driver singleton class."""

    def __init__(self) -> None:
        self._pw = sync_api.sync_playwright().start()
        self._browser = self._pw.chromium.launch()
        self._context = self._browser.new_context()
        self._page = self._context.new_page()
```

**Describe the bug**

Code works in python but not when built into exectubales using `cx_freeze`. Program hangs on `sync_api.playwright().start()` indefinitely until keyboard interrupt. Note it does work if built using `pyinstaller`. Traceback shown below.

```
Traceback (most recent call last):
  File "Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
    module_init.run(name + "__main__")
  File "Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
    exec(code, module_main.__dict__)
  File \lib\site-packages\playwright\sync_api\_context_manager.py", line 95, in start
    return self.__enter__()
  File lib\site-packages\playwright\sync_api\_context_manager.py", line 88, in __enter__
    dispatcher_fiber.switch()
  File "lib\site-packages\playwright\sync_api\_context_manager.py", line 67, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "C:\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Python39\lib\asyncio\base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Python39\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
  File "C:\Python39\lib\asyncio\windows_events.py", line 783, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <ProactorEventLoop running=False closed=True debug=False>>Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\base_events.py", line 1771, in call_exception_handler
  File "C:\Python39\lib\logging\__init__.py", line 1475, in error
  File "C:\Python39\lib\logging\__init__.py", line 1589, in _log
  File "C:\Python39\lib\logging\__init__.py", line 1599, in handle
  File "C:\Python39\lib\logging\__init__.py", line 1661, in callHandlers
  File "C:\Python39\lib\logging\__init__.py", line 952, in handle
  File "C:\Python39\lib\logging\__init__.py", line 1186, in emit
  File "C:\Python39\lib\logging\__init__.py", line 1175, in _open
NameError: name 'open' is not defined
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001D22DC3D040>Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\base_subprocess.py", line 125, in __del__
  File "C:\Python39\lib\asyncio\base_subprocess.py", line 70, in __repr__
  File "C:\Python39\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Python39\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D22DC57820>Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Python39\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Python39\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D22DC57820>Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Python39\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Python39\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
```

**Comment by OllieParsons-BH** [comment]
Wrong repo, posted now posted on https://github.com/microsoft/playwright-python
