### ISSUE TITLE
Java Playwright - Cannot run program ... playwright.sh

### ISSUE THREAD

**Issue by mwduncan2018** [microsoft/playwright#21000]
The following error occurs when I run a basic Java Playwright test for the first time. The organization requires that Centos is used. Has anyone experienced this error before and how did you resolve it? Thank you.

Caused by: java.io.IOException: Cannot run program "/tmp/playwright-java-17246735617012366256/playwright.sh": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:45)
	... 27 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 29 more

**Comment by yury-s** [comment]
What are the permissions of `/tmp/playwright-java-17246735617012366256/playwright.sh` ? This file is created everytime you start playwright and is used to run its node.js based driver process. Also note that we officially [support only](https://playwright.dev/java/docs/troubleshooting#linux) Ubuntu and Debian.

**Comment by mwduncan2018** [comment]
Given the file is created every time playwright is started and the permissions are not allowing execution, the organization's security must be automatically setting permissions for things created in the /tmp folder. I will discuss this with my DevOps team member and post back on Feb 21. If I do not post back by Feb 23, please close this issue. Thank you.
