### ISSUE TITLE
[BUG] File download causes waiting until "load" error

### ISSUE THREAD

**Issue by You-Honey** [microsoft/playwright#21038]
**Context:**
- Playwright Version: 1.30
- Operating System: Mac
- Node.js version: 9.20
- Browser: chromium

**Code Snippet**

```
ERROR PlaywrightCrawler: Request failed and reached maximum retries. page.goto: net::ERR_ABORTED at https://mysite.com/?attachment_id=24365
=========================== logs ===========================
navigating to "https://mysite.com/?attachment_id=24365", waiting until "load"
============================================================
    at gotoExtended (/path/to/crawler/node_modules/@crawlee/playwright/internals/utils/playwright-utils.js:153:17)
    at PlaywrightCrawler._navigationHandler (/path/to/crawler/node_modules/@crawlee/playwright/internals/playwright-crawler.js:113:52)
    at PlaywrightCrawler._handleNavigation (/path/to/crawler/node_modules/@crawlee/browser/internals/browser-crawler.js:285:51)
    at async PlaywrightCrawler._runRequestHandler (/path/to/crawler/node_modules/@crawlee/browser/internals/browser-crawler.js:227:13)
    at async PlaywrightCrawler._runRequestHandler (/path/to/crawler/node_modules/@crawlee/playwright/internals/playwright-crawler.js:110:9)
    at async wrap (/path/to/crawler/node_modules/@apify/timeout/index.js:52:21) {"id":"KDiuQfhWBLWsv5N","url":"https://mysite.com/?attachment_id=24365","method":"GET","uniqueKey":"https://mysite.com?attachment_id=24365"}
INFO  PlaywrightCrawler: Request https://mysite.com/?attachment_id=24365 failed too many times.
```

**Describe the bug**

If the link on the website is `<a href='page.html'>link</a>` everything works fine but if it's `<a href='image.png'>link</a>` I get the error above. I think this is related to the download event.

Is it possible to skip all downloads? I tried creating an `on download` event and cancel the download but it didn't work.

**Comment by yury-s** [comment]
You can cancel download by calling [cancel](https://playwright.dev/docs/api/class-download#download-cancel). But it looks like in you case you click on a link which starts navigation and then the navigation turns into a download (based on the resource type) and the navigation fails with and exception. You can detect such navigations changing into downloads and ignore the exception. 

> Is it possible to skip all downloads?

The download is triggered by you clicking on the link. One way to skip it is to detect that such link will result in a download and don't click it. Sometimes it can be detected by looking for [download](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) attribute on the `<a>` element. You can also [fulfill](https://playwright.dev/docs/network#modify-responses) all navigations to non-html elements with a mock response.

Will that work for you?

**Comment by minhphong306** [comment]
Hi @yury-s,
What if we go to a page that triggers the download directly?
For example: https://material.playwrightvn.com

I tried the code below, but it seems it not work!

```
test("Test 1", async ({ page }) => {
    page.on('download', async download => {
        download.saveAs("abc.tx")
    });

    await page.goto("https://material.playwrightvn.com/download_direct.php")
})
```
