### ISSUE TITLE
[BUG] Unable to launch firefox on playwright@next

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2110]
**Context:**
- Playwright Version: 0.17.0-next.1588635118582
- Operating System: macOS 10.15
- Node version: 13.12.0

Tried launching a script with `const { firefox } = require('playwright')`

```
(node:30193) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Users/arjun/Library/Caches/ms-playwright/firefox-1088/cached-profile'
    at Object.readdirSync (fs.js:921:3)
    at Firefox._createTemporaryProfile (/Users/arjun/pw-examples/node_modules/playwright-core/lib/server/firefox.js:159:26)
    at async Firefox._launchServer (/Users/arjun/pw-examples/node_modules/playwright-core/lib/server/firefox.js:71:27)
    at async Firefox.launch (/Users/arjun/pw-examples/node_modules/playwright-core/lib/server/firefox.js:41:58)
    at async /Users/arjun/pw-examples/osm.js:4:21
(node:30193) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30193) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pavelfeldman** [comment]
That's expected! Hang on.
