### ISSUE TITLE
[REGRESSION]: Cannot query selector all when the selector is a set of elements

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#2117]
**Context:**
- GOOD Playwright Version: [v0.13.0]
- BAD Playwright Version: [v0.17.0]
- Operating System: [all]
- Extra: []

**Code Snippet**

jest test:
```javascript
test('should query all elements', async (): Promise<void> => {
    // Given
    browser = await chromium.launch({ headless: true });
    const browserContext = await browser.newContext({ viewport: null });
    const page = await browserContext.newPage();
    const url = `file:${path.join(__dirname, 'get-handles-with-value.test.html')}`;
    await page.goto(url);

    // When
    const elements = await page.$$('[role="row"] select, [role="row"] input');

    // Then
    expect(elements.length).toBe(4);
  });
```

get-handles-with-value.test.html
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />

  <title>Query Selector All from</title>
</head>

<body>
  <table border="1">
    <tr role="row">
      <td>
        <select data-test-id="my-select">
          <option value="1" selected>label 1</option>
          <option value="2">label 2</option>
          <option value="3">label 3</option>
        </select>
      </td>
      <td>row1-cell2</td>
      <td></td>
    </tr>
    <tr role="row">
      <td>
        <select data-test-id="my-select">
          <option value="1">label 1</option>
          <option value="2" selected>label 2 row 2</option>
          <option value="3">label 3</option>
        </select>
      </td>
      <td>row2-cell2</td>
      <td><input type="text" value="2" data-e2e="foobar" /></td>
    </tr>
    <tr role="row">
      <td>
        <select data-test-id="my-select">
          <option value="1">label 1</option>
          <option value="2">label 2</option>
          <option value="3" selected>label 3 row3</option>
        </select>
      </td>
      <td>row3-cell2</td>
      <td>cell3</td>
    </tr>
  </table>
</body>

</html>
```

**Describe the bug**

`page.$$(selector)` throws the exception:

```sh
Evaluation failed: DOMException: Failed to execute 'matches' on 'Element': 'select,' is not a valid selector.

      at matches (__playwright_evaluation_script__:328:21)
      at queryShadowAllInternal (__playwright_evaluation_script__:313:35)
      at Object.queryAll (__playwright_evaluation_script__:276:17)
      at SelectorEvaluator.querySelectorAll (__playwright_evaluation_script__:912:59)
      at __playwright_evaluation_script__:2:57
      at __playwright_evaluation_script__:2:101
      at CRExecutionContext.evaluate (node_modules/playwright-core/lib/chromium/crExecutionContext.js:82:23)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/playwright-core/lib/helper.js:63:23)
      at Page.$$ (node_modules/playwright-core/lib/page.js:150:33)
      at Page.<anonymous> (node_modules/playwright-core/lib/helper.js:64:31)
      at Object.<anonymous>
```

**Comment by DoubleSlashDesign2** [comment]
I have also confirmed the same behavior in Playwright.net 

However I have additional details, 
You are always able to interact with the First item in the collection or as Array or even converting it using GetEnumerator()

Item 0 or the first item always returns an object.
Item 1 and all others will return null.

```
//--this would work - item 0 will always work
IReadOnlyList<IElementHandle> dataArray = await page.QuerySelectorAllAsync(selector);
var href = await dataArray[0].QuerySelectorAsync("h2.vehicle-card-title a");
await href.ClickAsync();


//--this would NOT work because it uses Item 1 - href  would be null
IReadOnlyList<IElementHandle> dataArray = await page.QuerySelectorAllAsync(selector);
var href = await dataArray[1].QuerySelectorAsync("h2.vehicle-card-title a");
await href.ClickAsync();
```
