### ISSUE TITLE
[Question] Debugging Failed Browser Start-up in Docker Container

### ISSUE THREAD

**Issue by bellindj** [microsoft/playwright#2146]
Is there a good way to debug a failed browser launch in a docker container? I have followed the Dockerfile.bionic fairly closely (I’m on pw v1.0.1) although I have a few additional requirements at my organization for certs/proxy/etc so added those. Webkit and Chrome launch fine, but FireFox fails to launch and just times out. I'm not getting anything other than below and I am having a hard time debugging just based on that alone. 

```
TimeoutError: Timed out after 30000 ms while trying to connect to Firefox!
    at Firefox._launchServer (/home/e451/node_modules/playwright-core/lib/server/firefox.js:109:30)
    at Firefox.launch (/home/e451/node_modules/playwright-core/lib/server/firefox.js:41:58)
    at CustomEnvironment.setup (/home/e451/libs/web/environment/jest-env-base.environment.js:27:29)
    at runTestInternal (/home/e451/node_modules/@jest/core/node_modules/jest-runner/build/runTest.js:406:5)
    at runTest (/home/e451/node_modules/@jest/core/node_modules/jest-runner/build/runTest.js:488:34)
    at Object.worker (/home/e451/node_modules/@jest/core/node_modules/jest-runner/build/testWorker.js:171:12) {
  name: 'TimeoutError'
}
```

I did open the container and was able to open FireFox in headless mode and got a few WARN, but didn't see any errors. I am not really sure what to do beyond starting it to verify it works on its own.

```
e451@2add7e295096:~/node_modules/playwright/.local-browsers/firefox-1089/firefox$ ./firefox -headless
*** You are running in headless mode.
1588886082291	addons.webextension.doh-rollout@mozilla.org	WARN	Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1588886082331	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1588886082332	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1588886082332	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1588886082333	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
```

Also under Firefox-1089 I don’t see a cached-profile directory but I believe that was removed in 1.0.0.

**Comment by pavelfeldman** [comment]
Can you set the `DEBUG=pw:browser*` environment variable? It'll likely to complain about something.

**Comment by bellindj** [comment]
@pavelfeldman Thank you! Seems like an issue finding the profile.

`2020-05-08T10:02:09.908Z pw:browser <launching> /home/e451/node_modules/playwright/.local-browsers/firefox-1089/firefox/firefox -no-remote -headless -profile /t
mp/playwright_dev_firefox_profile-vxdW6X -juggler 0 -silent
2020-05-08T10:02:09.930Z pw:browser <launched> pid=172
2020-05-08T10:02:09.933Z pw:browser <launching> /home/e451/node_modules/playwright/.local-browsers/firefox-1089/firefox/firefox -no-remote -headless -profile /t
mp/playwright_dev_firefox_profile-v3btq2 -juggler 0 -silent
2020-05-08T10:02:09.950Z pw:browser <launched> pid=177
2020-05-08T10:02:10.042Z pw:browser <launching> /home/e451/node_modules/playwright/.local-browsers/firefox-1089/firefox/firefox -no-remote -headless -profile /t
mp/playwright_dev_firefox_profile-GK7aF0 -juggler 0 -silent
2020-05-08T10:02:10.050Z pw:browser:err *** You are running in headless mode.
2020-05-08T10:02:10.055Z pw:browser:err *** You are running in headless mode.
2020-05-08T10:02:10.059Z pw:browser <launched> pid=186
2020-05-08T10:02:10.089Z pw:browser:err *** You are running in headless mode.
2020-05-08T10:02:10.800Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
2020-05-08T10:02:10.800Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
2020-05-08T10:02:10.803Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
2020-05-08T10:02:10.815Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
2020-05-08T10:02:10.815Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
2020-05-08T10:02:10.815Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
2020-05-08T10:02:10.825Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
2020-05-08T10:02:10.825Z pw:browser:err JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.`

**Comment by bellindj** [comment]
My only guess is that it is permissions related.. one of the differences between my container and the Dockerfile.bionic here is that permissions are more locked down. I’m running using PLAYWRIGHT_BROWSERS_PATH=0 to co locate the browsers with me node modules.

**Comment by aslushnikov** [comment]
@bellindj can you share a minimal docker container with us so that we can repro this?
