### ISSUE TITLE
[Question] How to use Docker Image with node version 14

### ISSUE THREAD

**Issue by devnigam24** [microsoft/playwright#21678]
Hi I am using the below code to create an image and install dependencies
```
def image = 'docker.<companyName>.com/mcr-rmt/playwright:v1.29.0'

pipeline {
    options {
        buildDiscarder(logRotator(daysToKeepStr: '', numToKeepStr: '30', artifactDaysToKeepStr: '', artifactNumToKeepStr: ''))
        timestamps()
    }

    agent {
        kubernetes {
            yaml """
                apiVersion: v1
                kind: Pod
                spec:
                  containers:
                  - name: main
                    image: ${image}
                    command:
                    - cat
                    tty: true
                    resources:
                      limits:
                        memory: "64Gi"
                        cpu: "16"
                      requests:
                        memory: "8Gi"
                        cpu: "4"
            """
        }
    }

    stages {
        stage('Install Dependencies') {
            steps {
                container('main') {
                    sh('free -h')
                    sh('yarn && yarn install')
                }
            }
        }

        stage('Run PlayWright Tests') {
            steps {
                timeout(30) {
                    container('main') {
                        sh('free -h')
                        sh('yarn test:playwright:remote')
                    }
                }
            }
        }
    }
}
```

### It fails when installing dependencies since looks like its using node version 16. 
```
rror /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-sass: Command failed.
19:08:58  Exit code: 1
19:08:58  Command: node scripts/build.js
19:08:58  Arguments: 
19:08:58  Directory: /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-sass
19:08:58  Output:
19:08:58  Building: /usr/bin/node /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
19:08:58  gyp info it worked if it ends with ok
19:08:58  gyp verb cli [
19:08:58  gyp verb cli   '/usr/bin/node',
19:08:58  gyp verb cli   '/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-gyp/bin/node-gyp.js',
19:08:58  gyp verb cli   'rebuild',
19:08:58  gyp verb cli   '--verbose',
19:08:58  gyp verb cli   '--libsass_ext=',
19:08:58  gyp verb cli   '--libsass_cflags=',
19:08:58  gyp verb cli   '--libsass_ldflags=',
19:08:58  gyp verb cli   '--libsass_library='
19:08:58  gyp verb cli ]
19:08:58  gyp info using node-gyp@3.8.0
19:08:58  gyp info using node@16.18.1 | linux | x64
19:08:58  gyp verb command rebuild []
19:08:58  gyp verb command clean []
19:08:58  gyp verb clean removing "build" directory
19:08:58  gyp verb command configure []
19:08:58  gyp verb check python checking for Python executable "python2" in the PATH
19:08:58  gyp verb `which` failed Error: not found: python2
19:08:58  gyp verb `which` failed     at getNotFoundError (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:13:12)
19:08:58  gyp verb `which` failed     at F (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:68:19)
19:08:58  gyp verb `which` failed     at E (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:80:29)
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:89:16
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/index.js:42:5
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/mode.js:8:5
19:08:58  gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
19:08:58  gyp verb `which` failed  python2 Error: not found: python2
19:08:58  gyp verb `which` failed     at getNotFoundError (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:13:12)
19:08:58  gyp verb `which` failed     at F (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:68:19)
19:08:58  gyp verb `which` failed     at E (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:80:29)
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:89:16
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/index.js:42:5
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/mode.js:8:5
19:08:58  gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
19:08:58  gyp verb `which` failed   code: 'ENOENT'
19:08:58  gyp verb `which` failed }
19:08:58  gyp verb check python checking for Python executable "python" in the PATH
19:08:58  gyp verb `which` failed Error: not found: python
19:08:58  gyp verb `which` failed     at getNotFoundError (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:13:12)
19:08:58  gyp verb `which` failed     at F (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:68:19)
19:08:58  gyp verb `which` failed     at E (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:80:29)
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:89:16
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/index.js:42:5
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/mode.js:8:5
19:08:58  gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
19:08:58  gyp verb `which` failed  python Error: not found: python
19:08:58  gyp verb `which` failed     at getNotFoundError (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:13:12)
19:08:58  gyp verb `which` failed     at F (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:68:19)
19:08:58  gyp verb `which` failed     at E (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:80:29)
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:89:16
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/index.js:42:5
19:08:58  gyp verb `which` failed     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/mode.js:8:5
19:08:58  gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
19:08:58  gyp verb `which` failed   code: 'ENOENT'
19:08:58  gyp verb `which` failed }
19:08:58  gyp ERR! configure error 
19:08:58  gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
19:08:58  gyp ERR! stack     at PythonFinder.failNoPython (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-gyp/lib/configure.js:484:19)
19:08:58  gyp ERR! stack     at PythonFinder.<anonymous> (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-gyp/lib/configure.js:406:16)
19:08:58  gyp ERR! stack     at F (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:68:16)
19:08:58  gyp ERR! stack     at E (/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:80:29)
19:08:58  gyp ERR! stack     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/which/which.js:89:16
19:08:58  gyp ERR! stack     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/index.js:42:5
19:08:58  gyp ERR! stack     at /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/isexe/mode.js:8:5
19:08:58  gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:202:21)
19:08:58  gyp ERR! System Linux 5.4.228-131.415.amzn2.x86_64
19:08:58  gyp ERR! command "/usr/bin/node" "/home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
19:08:58  gyp ERR! cwd /home/jenkins/agent/workspace/Playwright-post-merge/node_modules/node-sass
19:08:58  gyp ERR! node -v v16.18.1
19:08:58  gyp ERR! node-gyp -v v3.8.0
19:08:58  gyp ERR! not ok 
19:08:58  Build failed with error code: 1
```

### In order to fix this I thought of creating a node image from docker and directly installing like below
```
def dockerUrl = 'docker.artifactory.a.<companyName>.com'
def nodeImage = 'node:14'

pipeline {
    options {
        buildDiscarder(logRotator(daysToKeepStr: '', numToKeepStr: '30', artifactDaysToKeepStr: '', artifactNumToKeepStr: ''))
        timestamps()
    }

    agent {
        kubernetes {
            yaml """
                apiVersion: v1
                kind: Pod
                spec:
                  containers:
                  - name: main
                    image: '${dockerUrl}/${nodeImage}'
                    command:
                    - cat
                    tty: true
                    resources:
                      limits:
                        memory: "64Gi"
                        cpu: "16"
                      requests:
                        memory: "8Gi"
                        cpu: "4"
            """
        }
    }

    stages {
        stage('Install Dependencies') {
            steps {
                container('main') {
                    sh('free -h')
                    sh('node -v')
                    sh('yarn && yarn install')
                }
            }
        }

        stage('Run PlayWright Tests') {
            steps {
                timeout(30) {
                    container('main') {
                        sh('free -h')
                        sh('yarn test:playwright:remote')
                    }
                }
            }
        }
    }
}
```
## That successfully installs the deps and browsers but failed to run tests

```
Downloading Webkit 16.4 (playwright build v1751) from https://playwright.azureedge.net/builds/webkit/1751/webkit-ubuntu-20.04.zip
17:43:02  |                                                                                |   0% of 89 Mb
17:43:02  |■■■■■■■■                                                                        |  10% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■                                                                |  20% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 89 Mb
17:43:02  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 89 Mb
17:43:04  Webkit 16.4 (playwright build v1751) downloaded to /root/.cache/ms-playwright/webkit-1751
17:43:04  $ /home/jenkins/agent/workspace/qbo/Playwright-post-merge/node_modules/.bin/playwright test --project=chromium
17:43:05  
17:43:05  Running 26 tests using 10 workers
17:43:12  ××××××××××××××××××××FFFFFFFFFF××××××××××××××××××××FFFFFFFFFF××××××××××××FFFFFF
17:43:12  
17:43:12    1) [chromium] › acquisition/e2e/first-time-users.spec.js:54:5 › should navigate to live bookkeeping and buy a subscription - ACQUISITION - E2E - CRITICAL 
17:43:12  
17:43:12      browserType.launch: 
17:43:12      ╔══════════════════════════════════════════════════════╗
17:43:12      ║ Host system is missing dependencies to run browsers. ║
17:43:12      ║ Missing libraries:                                   ║
17:43:12      ║     libnss3.so                                       ║
17:43:12      ║     libnssutil3.so                                   ║
17:43:12      ║     libsmime3.so                                     ║
17:43:12      ║     libnspr4.so                                      ║
17:43:12      ║     libatk-1.0.so.0                                  ║
17:43:12      ║     libatk-bridge-2.0.so.0                           ║
17:43:12      ║     libcups.so.2                                     ║
17:43:12      ║     libdrm.so.2                                      ║
17:43:12      ║     libdbus-1.so.3                                   ║
17:43:12      ║     libatspi.so.0                                    ║
17:43:12      ║     libXcomposite.so.1                               ║
17:43:12      ║     libXdamage.so.1                                  ║
17:43:12      ║     libXfixes.so.3                                   ║
17:43:12      ║     libXrandr.so.2                                   ║
17:43:12      ║     libgbm.so.1                                      ║
17:43:12      ║     libxkbcommon.so.0                                ║
17:43:12      ║     libasound.so.2                                   ║
17:43:12      ╚══════════════════════════════════════════════════════╝
```

## Please help me with the correct way of running the tests with node version 14
Thanks :pray:

**Comment by mirao** [comment]
Did you install browser dependencies? (https://playwright.dev/docs/cli#install-system-dependencies)

**Comment by mirao** [comment]
I noticed the link https://playwright.dev/docs/cli#install-system-dependencies doesn't work well, it redirects to https://playwright.dev/docs/browsers#install-system-dependencies.
So it's better to get the right page over a search query "system dependencies" on https://playwright.dev.

**Comment by mxschmitt** [comment]
Thats a bug on our side, I deployed a fix so it does not redirect, the link should start working in a few minutes.
