### ISSUE TITLE
[BUG] @playwright/experimental-ct-react component testing not compatible with @sentry/nextjs

### ISSUE THREAD

**Issue by chris13524** [microsoft/playwright#21790]
### System info
- Playwright Version: v1.31.2
- Operating System: macOS 13.2.1
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/chris13524/sentry-nextjs-playwright-broken

**Steps**
- run `npm run test-ct` to reproduce error
- edit `pages/index.tsx` and comment out the call to `addBreadcrumb()`
- run `npm run test-ct` to reproduce no error

**Expected**

I should be able to use the [@sentry/nextjs](https://www.npmjs.com/package/@sentry/nextjs) library in my component and in the helper files that my component calls.

**Actual**

Test times out while mounting the component.

```
chris13524@host sentry-nextjs-playwright-broken % npm run test-ct

> sentry-nextjs-playwright-broken@0.1.0 test-ct
> playwright test -c playwright-ct.config.ts


Running 3 tests using 3 workers
  1) [webkit] › pages/index.spec.tsx:6:5 › should work ─────────────────────────────────────────────

    Test timeout of 10000ms exceeded.

    Target closed

       5 |
       6 | test('should work', async ({ mount }) => {
    >  7 |   const component = await mount(<Home />);
         |                           ^
       8 |   await expect(component).toContainText('Get started');
       9 | });
      10 |

        at /Users/chris13524/git/github.com/chris13524/sentry-nextjs-playwright-broken/pages/index.spec.tsx:7:27

  2) [chromium] › pages/index.spec.tsx:6:5 › should work ───────────────────────────────────────────

    Test timeout of 10000ms exceeded.

    Target closed

       5 |
       6 | test('should work', async ({ mount }) => {
    >  7 |   const component = await mount(<Home />);
         |                           ^
       8 |   await expect(component).toContainText('Get started');
       9 | });
      10 |

        at /Users/chris13524/git/github.com/chris13524/sentry-nextjs-playwright-broken/pages/index.spec.tsx:7:27

  3) [firefox] › pages/index.spec.tsx:6:5 › should work ────────────────────────────────────────────

    Test timeout of 10000ms exceeded.

    Target closed

       5 |
       6 | test('should work', async ({ mount }) => {
    >  7 |   const component = await mount(<Home />);
         |                           ^
       8 |   await expect(component).toContainText('Get started');
       9 | });
      10 |

        at /Users/chris13524/git/github.com/chris13524/sentry-nextjs-playwright-broken/pages/index.spec.tsx:7:27

  3 failed
    [chromium] › pages/index.spec.tsx:6:5 › should work ────────────────────────────────────────────
    [firefox] › pages/index.spec.tsx:6:5 › should work ─────────────────────────────────────────────
    [webkit] › pages/index.spec.tsx:6:5 › should work ──────────────────────────────────────────────

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.

```

**Comment by mxschmitt** [comment]
Investigation note: we don't have a global `global` while Next.js does have it:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/17984549/226301498-8b45fc75-317b-428e-8ab1-07e18f4bd2fb.png">

See [@sentry/nextjs@7.43.0/esm/client/tunnelRoute.js](https://unpkg.com/browse/@sentry/nextjs@7.43.0/esm/client/tunnelRoute.js) line 3. We throw then basically.

**Comment by chris13524** [comment]
Is there a workaround I can apply so that I can use Sentry in production code while still using @playwright/experimental-ct-react?

**Comment by mxschmitt** [comment]
I feel like this could be workarounded by adding a custom vite plugin on the user land which defines this global env var.

cc @sand4rt to confirm.

**Comment by sand4rt** [comment]
@mxschmitt @chris13524 
At a first glance it seems like the Centry Vite plugin has to been passed to Playwright:

- https://docs.sentry.io/platforms/node/guides/connect/sourcemaps/uploading/vite/

- https://playwright.dev/docs/test-components#q-how-can-i-use-vite-plugins

Could investigate this later this week if still needed.

**Comment by mxschmitt** [comment]
I think this Sentry plugin is unrelated, since its not about uploading sourcemaps, its about adding this specify Next.js code to the runtime. Not sure if the plugin does it or if Next.js adds the `global` var.

**Comment by sand4rt** [comment]
@chris13524 I'm still researching it, but as a temporary workaround you could put the code below in `/playwright/index.tsx`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Testing Page</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./index.tsx"></script>
    <script>global = {}</script> <!-- note this part of the code -->
  </body>
</html>
```

**Comment by sand4rt** [comment]
@mxschmitt sounds good!

@chris13524 keep in mind that you probably have to define something in `playwright/index.tsx` or `playwright/index.html` if the component depends on global code and feel free to create an new issue if this does not suffice.

**Comment by chris13524** [comment]
Thanks @sand4rt this fixes the issue for me! Feel free to close the issue.

Would be nice to have better error messages to root out that global was the problem here. Also, nice to add FAQ maybe on the global "workaround"!

Cheers!
