### ISSUE TITLE
[BUG] Cant open page on Opera Browser (CDP-connected) 

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright#21812]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Windows
- Python version: 3.10
- Browser: Chromium-based (in this case Opera)

**Code Snippet**

```python
import subprocess
from playwright.sync_api import sync_playwright
import time
import tempfile

temp_user_data_dir = tempfile.mkdtemp()
browser_path = r"C:\Users\Admin\AppData\Local\Programs\Opera\Launcher.exe"
subprocess.Popen([browser_path, "--remote-debugging-port=9222", f'--user-data-dir={temp_user_data_dir}'])

time.sleep(2)

playwright = sync_playwright().start()
browser = playwright.chromium.connect_over_cdp("http://127.0.0.1:9222")

page = browser.new_page() # Throws Connection Error right here
```

**Describe the bug**

```
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\GitHub\playwright\tests\dev_test.py", line 33, in <module>
    page = browser.new_page()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 14154, in new_page
    self._sync(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_browser.py", line 173, in new_page
    page = await context.new_page()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_browser_context.py", line 238, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.

Process finished with exit code 1
```

The Browser crashed (and Opera reboots). Seems like Opera (and possibly other browsers) dont like the new-page command Playwright is sending.

**Comment by aslushnikov** [comment]
It looks like Opera regressed Chrome DevTools protocol; see https://github.com/microsoft/playwright/issues/20915#issuecomment-1434925729 for the details.
