### ISSUE TITLE
[BUG] Getting browser.newContext: Target page, context or browser has been closed error

### ISSUE THREAD

**Issue by sharm49** [microsoft/playwright#21875]
### System info
- Playwright Version: "1.29.2"
- Operating System: Linux/AMD64
- Browser: Chromium
- java.version: '11.0.17'
- Selenium: Selenium grid 4 with image version:4.8.1-20230221

Code snippet:

```ts
const options: LaunchOptions = {
  args: ['--remote-allow-origins=*'],
  headless: false,
  slowMo: 100,
};

BeforeAll(async () => {
  console.log('starting browser');
  switch (process.env.BROWSER) {
    case 'firefox':
      global.browser = await firefox.launch(options);
      break;
    case 'webkit':
      global.browser = await webkit.launch(options);
      break;
    default:
      global.browser = await chromium.launch(options);
  }
});

AfterAll(async () => {
  await global.browser.close();
  console.log('starting browser');
});

Before(async () => {
  global.context = await global.browser.newContext({ ignoreHTTPSErrors: true });
  global.page = await global.context.newPage();

  const git = simpleGit();
  const branchName = (await git.branch()).current.trim();
  if (branchName !== 'main') {
    console.log(`[E2E] Running regression on feature branch "${branchName}"`);
    await global.page.goto(global.BASE_URL + '/search/form.uri?display=basic#basic');
    await global.page.evaluate('window.microUiOverrides?.clear();');

    const microUis = [

        "List of microUIS here"
    ];

    await Promise.all(
      microUis.map((microUi) => {
        global.page.evaluate(`window.microUiOverrides?.useBranch('${microUi}','${branchName}')`);
      }),
    );
  }
});

After(async function (scenario) {
  if (scenario.result!.status === Status.FAILED) {
    const buffer = await global.page.screenshot({
      path: `../../dist/apps/e2e/${scenario.gherkinDocument.uri}-${scenario.pickle.name}.png`,
      fullPage: true,
    });
    await this.attach(buffer, 'image/png');
  }
  await global.page.close();
  await global.context.close();
});
```

**Steps**
- We are running the playwright testes on selenium grid 4 on EKS and when we run the tests via jenkins we get the below error:

Jenkins error:
```bash

......2023-03-22T13:30:54.390Z pw:browser <ws disconnected> wss://<selenium-url>/session/2c5f661ddb68a0a4e3b9dc4afd4ce612/se/cdp code=1005 reason=
F---2023-03-22T13:30:54.407Z pw:browser <selenium> disconnecting from sessionId=2c5f661ddb68a0a4e3b9dc4afd4ce612
----FF----------FF---2023-03-22T13:30:54.515Z pw:browser <error disconnecting from selenium>: Error: fetch failed: server returned code 404. URL: https://<selenium-url>/wd/hub/session/2c5f661ddb68a0a4e3b9dc4afd4ce612
2023-03-22T13:30:54.529Z pw:browser <selenium> disconnected from sessionId=2c5f661ddb68a0a4e3b9dc4afd4ce612
FF---FF---FF---FF---FF---FF--FF--FF------FF------FF---------------FF---------------Fstarting browser
.......2023-03-22T13:30:58.645Z pw:browser <ws disconnecting> wss://<selenium-url>/session/a07f6e717605940d092e0975b64de72c/se/cdp
2023-03-22T13:30:58.683Z pw:browser <ws disconnected> wss://<selenium-url>/session/a07f6e717605940d092e0975b64de72c/se/cdp code=1005 reason=
2023-03-22T13:30:58.691Z pw:browser <selenium> disconnecting from sessionId=a07f6e717605940d092e0975b64de72c
2023-03-22T13:30:58.743Z pw:browser <error disconnecting from selenium>: Error: fetch failed: server returned code 404. URL: https://<selenium-url>/wd/hub/session/a07f6e717605940d092e0975b64de72c
2023-03-22T13:30:58.743Z pw:browser <selenium> disconnected from sessionId=a07f6e717605940d092e0975b64de72c


Before # ../../shared-e2e/support/hooks.ts:26
        browser.newContext: Target page, context or browser has been closed
            at async World.<anonymous> (/home/jenkins/agent/workspace/e2e-selenium-test-sample/shared-e2e/support/hooks.ts:27:22)


After # ../../shared-e2e/support/hooks.ts:59
        page.screenshot: Target page, context or browser has been closed
            at World.<anonymous> (/home/jenkins/agent/workspace/e2e-selenium-test-sample/shared-e2e/support/hooks.ts:61:42)
```

Selenium hub error:
```
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.lambda$send$2(JdkHttpClient.java:222)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.send(JdkHttpClient.java:229)
	... 9 more
13:27:06.679 INFO [GridModel.release] - Releasing slot for session id e4fc90b85375366c41f665e96db248fe
13:27:06.679 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: e4fc90b85375366c41f665e96db248fe
13:27:07.258 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 499120264588998c705a4b8d05e1df5f 
13:27:07.497 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
org.openqa.selenium.WebDriverException: java.lang.IllegalArgumentException: statusCode
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.228-132.418.amzn2.x86_64', java.version: '11.0.17'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.send(JdkHttpClient.java:239)
	at org.openqa.selenium.netty.server.WebSocketMessageHandler.lambda$channelRead0$0(WebSocketMessageHandler.java:47)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: statusCode
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendClose(WebSocketImpl.java:301)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.lambda$send$2(JdkHttpClient.java:222)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient$5.send(JdkHttpClient.java:229)
	... 9 more
```

**Expected**

- All tests should run without above error.

**Actual**

Failing with above mentioned error

**NOTE**
 If we run the exact same suite on selenium grid running on EC2 instance, it works fine.

**Solutions tried**

- We have already implemented suggestions from here https://github.com/SeleniumHQ/selenium/issues/11408#issuecomment-1345401948
- Tried by increasing session timeout value for sessionqueue and chrome node.
- Tried with selenium hub: 4.5.0 as well.

**Comment by dgozman** [comment]
@sharm49 I am not really sure how to help you without a repro. IIRC, Selenium 4.8 does not have the WebSocket issue you linked to. Our tests pass with 4.4 and 4.8. If you could share a repro that we can run locally, we could take a look.

**Comment by dgozman** [comment]
Merging into #18892.
