### ISSUE TITLE
[BUG] webkit proxies don't work on Windows

### ISSUE THREAD

**Issue by PheonXD** [microsoft/playwright#21954]
### System info
- Playwright Version: v1.31.0
- Operating System: Windows 11
- Browser: All

### Source code

```C#
    var page = await browserContext.NewPageAsync();
    var searchPageResponse = await page.GotoAsync(searchPageUrl, new() { Timeout = _options.RequestTimeout }); //Error appear here
    var content = await searchPageResponse.TextAsync();
```

i'm using proxy server with all browsers. With Chromium and Firefox no problems observed. But when i using webkit i have exception when trying "GotoAsync".
Exception:
```
Message = Failure when receiving data from the peer
navigating to "MY URL" waiting until "load"
	Data = System.Collections.ListDictionaryInternal
	Source = System.Private.CoreLib
	HResult = -2146233088
	StackTrace:
at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary) in /_/src/Playwright/Transport/Connection.cs:line 143
at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 547
```
i know about issue with resedential proxies ([LINK](https://github.com/microsoft/playwright/issues/5321)), but i'm using IP-address
Example:
```C#
    var contextOptions = new BrowserNewContextOptions
    {
        Proxy = new Microsoft.Playwright.Proxy()
        {
            Server = "IP",
            Username = "user",
            Password = "password",
        }
    };
    Browser.NewContextAsync(contextOptions);
```

**Comment by aslushnikov** [comment]
@PheonXD Any chance we can have a small self-contained repro that illustrates the issue?

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.
