### ISSUE TITLE
[REGRESSION]: locator.click never resolves on firefox

### ISSUE THREAD

**Issue by ritz078** [microsoft/playwright#21995]
**Context:**
- GOOD Playwright Version: 1.30.0
- BAD Playwright Version: 1.31.2 (This also exists on 1.32.1)
- Operating System: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
import { test } from '@playwright/test';

test('Firefox issue', async ({ page }) => {
  await page.goto('https://web-examples.pspdfkit.com/hello?mode=standalone');
  const frame = page.mainFrame().childFrames()[0]
  await frame.click('.PSPDFKit-Toolbar-Button-Annotate')
  await frame.click("[title='Text']")
  const canvasLocator = frame.locator(`.PSPDFKit-Page[data-page-index="0"][data-page-is-loaded="true"]`).locator('.PSPDFKit-Text-Canvas')
  await canvasLocator.waitFor()

  // This never resolves for firefox
  await canvasLocator.click({
    position: { x: 50, y: 50 },
  })
});
```

**Describe the bug**

The above test passes 100% on all browsers except firefox. It worked fine on firefox in 1.30.0. I get the following wrror in recent versions:

```
Running 1 test using 1 worker
  1) [firefox] › example.spec.ts:3:5 › Firefox issue ───────────────────────────────────────────────

    Test timeout of 30000ms exceeded.

    locator.click: Target closed
    =========================== logs ===========================
    waiting for locator('.PSPDFKit-Page[data-page-index="0"][data-page-is-loaded="true"]').locator('.PSPDFKit-Text-Canvas')
      locator resolved to <div class="PSPDFKit-4dwy35ce5zzs8fcuzm4z5qyj9j PSPDF…></div>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
    ============================================================

      10 |
      11 |   // This never resolves for firefox
    > 12 |   await canvasLocator.click({
         |                       ^
      13 |     position: { x: 50, y: 50 },
      14 |   })
      15 | });

        at /Users/ritz078/projects/playwright-repro/tests/example.spec.ts:12:23

    Pending operations:
      - locator.click at tests/example.spec.ts:12:23
```

**Comment by mirao** [comment]
It could be related to issues reported in #20993.
