### ISSUE TITLE
[BUG] Click operation doesn't timeout when there is an alert

### ISSUE THREAD

**Issue by zaynetro** [microsoft/playwright#2200]
**Context:**
- Playwright Version: 1.0.1
- Operating System: Linux
- Node version: v10.20.1
- Browser: Chromium (haven't checked others)

**Code Snippet**

Test suite:

```typescript
describe('Dialog', () => {
  it('Alert modal', async () => {
    // newPage creates a new page from suite's browser context
    const page = await newPage(); 
    await page.goto('http://localhost:8090/alert.html');
    await page.click('#btn');
    await page.waitForSelector('text="You clicked"');
  });
});
```

And sample page:

```html
<!doctype>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Alert test page</title>
    </head>
    <body>
        <h1>Alert page</h1>
        <div id="result"></div>
        <button type="button" id="btn">Try me!</button>

        <script type="text/javascript">
         const btn = document.querySelector('#btn');
         const result = document.querySelector('#result');

         btn.addEventListener('click', () => {
             alert('one');
             result.textContent = "You clicked";
         }, false);
        </script>
    </body>
</html>
```
logs:

```
  pw:input (page|frame).click("#btn") +0ms
  pw:input waiting for the selector "#btn" +3ms
  pw:input ...got element for the selector +18ms
  pw:input elementHandle.click() +1ms
  pw:input waiting for element to be displayed and not moving... +0ms
  pw:input ...element is displayed and does not move +8ms
  pw:input scrolling into view if needed... +1ms
  pw:input ...done scrolling +1ms
  pw:input checking that element receives pointer events at (38.33,76.93)... +3ms
  pw:input ...element does receive pointer events, continuing input action +5ms
  pw:input performing "click" action... +0ms
 FAIL  playwright/dialog.test.ts (41.185s)
  ● Dialog › Alert modal

    thrown: "Exceeded timeout of 40000ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      2 | describe('Dialog', () => {
      3 | 
    > 4 |   it('Alert modal', async () => {
        |   ^
      5 |     const page = await newPage();
      6 |     await page.goto('http://localhost:8090/alert.html');
      7 | 

      at describe (playwright/dialog.test.ts:4:3)
      at Object.<anonymous> (playwright/dialog.test.ts:2:1)

(Alert modal) [error] Failed to take a screenshot for page 'default': Timed out in 1000ms.
```

**Describe the bug**

If button click opens a dialog then click does not timeout nor generate any debug messages that could help figure out the cause. 

I was adding a test for software that was written by others and it turned out that when doing things quickly generated an alert. My test was timing out (Jest timeout) and when cleaning up I couldn't take a screenshot also (I guess the page was waiting for an alert to be closed?). I was only able to notice alert when running tests in non-headless mode.

It would help a lot if either click operation would timeout or there will be some other error like: "Alert dialog hasn't been interacted within a timeout".

**Comment by pedrommvv** [comment]
Can you try to replicate this issue locally in latest version  "playwright": "^1.10.0"?
