### ISSUE TITLE
[BUG] Teamcity build fails during installation rfbrowser node dependencies

### ISSUE THREAD

**Issue by amankul** [microsoft/playwright#22042]
### System info
- Playwright Version: 1.31.2
- Operating System: Windows Server 2016
- Browser: N/A
- Other info:

### Source code

- [X ] I provided exact source code that allows reproducing the issue locally.

Teamcity build with the following build steps and a Windows server 2016 build agent. 

```
cinst python3 nodejs.install -y
PATH=%env.Path%;C:\Python39;C:\Program Files\nodejs
python.exe -m pip install --upgrade pip
pip install -U -r ./requirements.txt
rfbrowser init
robot --variable environment:%env.testenvironment%  --variable browser:%env.browser%  ./robot-framework-docker-MyDimensional/tests/%env.testapplication%

```

**Steps**
- Run the build

**Expected**

rfbrowser init should complete without errors. 

**Actual**

```
[15:18:53]
[Step 2/3] 2023-03-28 15:18:53,966 [INFO    ] Downloading Chromium playwright build v1050 from https://playwright.azureedge.net/builds/chromium/1050/chromium-win64.zip
[15:18:53]
[Step 2/3] 
[15:18:54]
[Step 2/3] 2023-03-28 15:18:54,329 [INFO    ] |                                                                                |   0% of 113.3 Mb
[15:18:54]
[Step 2/3] 
[15:18:55]
[Step 2/3] --- Logging error ---
[15:18:55]
[Step 2/3] Traceback (most recent call last):
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\logging\__init__.py", line 1037, in emit
[15:18:55]
[Step 2/3]     stream.write(msg + self.terminator)
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\encodings\cp1252.py", line 19, in encode
[15:18:55]
[Step 2/3]     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
[15:18:55]
[Step 2/3] UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-43: character maps to <undefined>
[15:18:55]
[Step 2/3] Call stack:
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
[15:18:55]
[Step 2/3]     "__main__", mod_spec)
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\runpy.py", line 85, in _run_code
[15:18:55]
[Step 2/3]     exec(code, run_globals)
[15:18:55]
[Step 2/3]   File "C:\Python37\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
[15:18:55]
[Step 2/3]     sys.exit(main())
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\site-packages\Browser\entry.py", line 298, in main
[15:18:55]
[Step 2/3]     runner(command, skip_browsers, trace_file)
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\site-packages\Browser\entry.py", line 240, in runner
[15:18:55]
[Step 2/3]     rfbrowser_init(skip_browsers)
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\site-packages\Browser\entry.py", line 62, in rfbrowser_init
[15:18:55]
[Step 2/3]     _rfbrowser_init(skip_browser_install)
[15:18:55]
[Step 2/3]   File "C:\Python37\lib\site-packages\Browser\entry.py", line 172, in _rfbrowser_init
[15:18:55]
[Step 2/3]     logging.info(output)
[15:18:55]
[Step 2/3] Message: '|\u25a0\u25a0\u25a0\u25a0\u25a0\u25a0\u25a0\u25a0                                                                        |  10% of 113.3 Mb\n'
```

**Comment by yury-s** [comment]
The error stack points at `rfbrowser` code, I don't see any playwright files there. If you think it is a playwright bug, please refile with a complete repro that uses playwright directly.

**Comment by ltsuda** [comment]
You are probably looking for https://github.com/MarketSquare/robotframework-browser#robotframework-browser that is robotframework library for Playwright.

**Comment by amankul** [comment]
Ohk thanks. Since BL uses playwright under the hood, how to differentiate between the two while filing issues?
