### ISSUE TITLE
[REGRESSION] firefox headed refuses to click outside of physical screen

### ISSUE THREAD

**Issue by LeeeJoe** [microsoft/playwright#22082]
### System info
- Playwright Version: [v1.30.0, 1.30.1, 1.32.0]
- Operating System: [Windows 10, CentOS 8]
- Browser: [Firefox]
- Other info:
Starting with version 1.30.0, when viewportsize is larger than the physical dimensions of a computer display, visual elements are active, available, stable, but it is not possible to perform clicks. In version 1.29.0 everything works good.
In my Linux system display resolution is 1280x666.
_Note: This code works correctly in headless mode._

### Source code
```c#
using Microsoft.Playwright;

bool headless = false;
if (!string.IsNullOrEmpty(args[0]) && args[0] == "-headless")
{
    headless = true;
}

Console.WriteLine("Started.");

var playwright = await Playwright.CreateAsync();
IBrowserType browsertype = playwright.Firefox;

Proxy proxy = new() 
{ 
    Server = "111.222.333.444:5555",
    Username = "username",
    Password = "password",
};
List<string> listArgs = new()
{
    "--start-maximized",
};

var launchOptions = new BrowserTypeLaunchOptions()
{
    Headless = headless,
    Proxy = proxy,
    Args = listArgs,
};
var browser = await browsertype.LaunchAsync(launchOptions);

var contextOptions = new BrowserNewContextOptions
{
    ViewportSize = new() { Width = 1920, Height = 1080 },
};
var context = await browser.NewContextAsync(contextOptions);
var page = await context.NewPageAsync();

await page.GotoAsync("https://twitter.com/", new() { WaitUntil = WaitUntilState.Load });

var locator = page.FrameLocator("//iframe[@title='Sign in with Google Dialog']").Locator("//div[@id='close']");
try
{
    Console.WriteLine("Clicking: Close Google Dialog");
    await locator.ClickAsync();
}
catch (Exception ex)
{
    Console.WriteLine($"Error:\n{ex.Message}\n{ex.StackTrace}");
}

locator = page.Locator("//a[@data-testid='login']").Locator("visible=true");
try
{
    await locator.WaitForAsync(new LocatorWaitForOptions() { State = WaitForSelectorState.Visible });
}
catch (Exception ex)
{
    Console.WriteLine($"Error:\n{ex.Message}\n{ex.StackTrace}");
}

try
{
    Console.WriteLine("Clicking: Sign in");
    await locator.ClickAsync(new LocatorClickOptions() { Timeout = 10000 });
}
catch (Exception ex)
{
    Console.WriteLine($"Error:\n{ex.Message}\n{ex.StackTrace}");
}

Console.WriteLine("Finished. Press any key.");
Console.ReadKey();
```

**Config file**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.32.0" />
  </ItemGroup>

</Project>
```

### Steps
Run the app

### Expected
```
Started.
Clicking: Close Google Dialog
Clicking: Sign in
Finished. Press any key.
```

### Actual
```
Started.
Clicking: Close Google Dialog
Error:
Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for FrameLocator("xpath=//iframe[@title='Sign in with Google Dialog']").Locator("xpath=//div[@id='close']")
  locator resolved to <div id="close" tabindex="0" role="button" aria-label…>…</div>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary) in /_/src/Playwright/Transport/Connection.cs:line 180
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 502
   at Program.<Main>$(String[] args) in D:\source\repos\XTestPW\XTestPW\Program.cs:line 47
Clicking: Sign in
Error:
Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for Locator("xpath=//a[@data-testid='login']").Locator("visible=true")
  locator resolved to <a role="link" href="/login" data-testid="login" cl…>…</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary) in /_/src/Playwright/Transport/Connection.cs:line 180
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 502
   at Program.<Main>$(String[] args) in D:\source\repos\XTestPW\XTestPW\Program.cs:line 67
Finished. Press any key.
```

## Also please note the following errors:
```
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary) in /_/src/Playwright/Transport/Connection.cs:line 202
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 508
```

### Thank you

**Comment by yury-s** [comment]
I could not reproduce it with Playwright 1.32.1 neither on Win 11 nor on Ubuntu 22.04 with the following test:

```ts
import { test, expect } from '@playwright/test';

test.use({
    headless: false,
    browserName: 'firefox',
    viewport: {
        width: 5000,
        height: 3000
    }
})

test('twitter login', async ({ page }) => {
    await page.goto('https://twitter.com/');
    console.log('innerwidth = ' + await page.evaluate(() => window.innerWidth));
    console.log('innerHeight = ' + await page.evaluate(() => window.innerHeight));
    const locator = page.frameLocator("//iframe[@title='Sign in with Google Dialog']").locator("//div[@id='close']");
    await locator.click();

    const locator2 = page.locator("//a[@data-testid='login']").locator("visible=true");
    await locator2.click();
});
```

It might be that twitter is serving me a different content. Do you have a self contained page where we can reproduce this?

**Comment by LeeeJoe** [comment]
Hi,
My code easily coped with the width of 5000 and the height of 3000 in the mode headless.
However, in headless=false I got the same errors.
Also, I don't have a particular Twitter page. This is the usual start page in the browser on the desktop.
As you can see, I also use C# in a routine console application.
For the purity of the experiment, I could provide access to the proxy for a while. Maybe some email?
Also please tell me how long it will take you to do this.
Thank you.

**Comment by yury-s** [comment]
Managed to reproduce it on macos. Folding this into https://github.com/microsoft/playwright/issues/20993

**Comment by aslushnikov** [comment]
this might be a separate issue; reopening!

**Comment by aslushnikov** [comment]
For future references: we tried scaling viewport (like in "responsive mode" in DevTools), but it failed since event dispatching in FF requires integers. See the newly added test - https://github.com/microsoft/playwright/commit/2b9b46e260de47645e3e28994d85bcb1fcd6a44f
