### ISSUE TITLE
[BUG] tsconfig loader does not support TS 5.0 "extends"-array

### ISSUE THREAD

**Issue by iffa** [microsoft/playwright#22151]
### System info
- Playwright Version: [v1.32.1]
- Operating System: [All]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/iffa/playwright-tsconfig-extends-array

**Steps**
- npm run test
- Fails

**Expected**

Should successfully parse tsconfig.json and run tests.

**Actual**

Fails to parse tsconfig.json, since it expects `extends` to be a string, when in TypeScript 5.0 it can also be an Array.

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#supporting-multiple-configuration-files-in-extends

```
> playwright-tsconfig-extends-array@1.0.0 test
> npx playwright test

TypeError: The "path" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at loadTsconfig (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js:107:35)
    at loadSyncDefault (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js:60:18)
    at tsConfigLoader (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js:42:22)
    at loadAndValidateTsconfigForFile (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/common/transform.js:56:55)
    at resolveHook (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/common/transform.js:71:20)
    at Function.resolveFilename (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/common/transform.js:179:24)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/playwright-tsconfig-extends-array/playwright.config.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.f._compile (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.i.<computed>.ot._extensions.<computed> (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requireOrImport (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/common/transform.js:163:20)
    at requireOrImportDefaultObject (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/common/configLoader.js:225:53)
    at ConfigLoader.loadConfigFile (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/common/configLoader.js:57:26)
    at runTests (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/cli.js:127:46)
    at ji.<anonymous> (/playwright-tsconfig-extends-array/node_modules/@playwright/test/lib/cli.js:45:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by loynoir** [comment]
```patch
diff --git a/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js b/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js
index 441a9b6..a9f80c6 100644
--- a/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js
+++ b/node_modules/@playwright/test/lib/third_party/tsconfig-loader.js
@@ -95,51 +95,19 @@ function loadTsconfig(configFilePath, existsSync = fs.existsSync, readFileSync =
   if (!existsSync(configFilePath)) {
     return undefined;
   }
-  const configString = readFileSync(configFilePath);
-  const cleanedJson = StripBom(configString);
-  let config = _utilsBundle.json5.parse(cleanedJson);
-  let extendedConfig = config.extends;
-  if (extendedConfig) {
-    if (typeof extendedConfig === "string" && extendedConfig.indexOf(".json") === -1) {
-      extendedConfig += ".json";
-    }
-    const currentDir = path.dirname(configFilePath);
-    let extendedConfigPath = path.join(currentDir, extendedConfig);
-    if (extendedConfig.indexOf("/") !== -1 && extendedConfig.indexOf(".") !== -1 && !existsSync(extendedConfigPath)) {
-      extendedConfigPath = path.join(currentDir, "node_modules", extendedConfig);
-    }
-    const base = loadTsconfig(extendedConfigPath, existsSync, readFileSync) || {};
-
-    // baseUrl should be interpreted as relative to the base tsconfig,
-    // but we need to update it so it is relative to the original tsconfig being loaded
-    if (base.compilerOptions && base.compilerOptions.baseUrl) {
-      const extendsDir = path.dirname(extendedConfig);
-      base.compilerOptions.baseUrl = path.join(extendsDir, base.compilerOptions.baseUrl);
-    }
-    config = {
-      ...base,
-      ...config,
-      compilerOptions: {
-        ...base.compilerOptions,
-        ...config.compilerOptions
-      }
-    };
-  }
-  if (path.basename(configFilePath) === 'jsconfig.json' && ((_config$compilerOptio2 = config.compilerOptions) === null || _config$compilerOptio2 === void 0 ? void 0 : _config$compilerOptio2.allowJs) === undefined) {
-    config.compilerOptions = config.compilerOptions || {};
-    config.compilerOptions.allowJs = true;
-  }
-  return config;
-}
-function StripBom(string) {
-  if (typeof string !== 'string') {
-    throw new TypeError(`Expected a string, got ${typeof string}`);
-  }
-
-  // Catches EFBBBF (UTF-8 BOM) because the buffer-to-string
-  // conversion translates it to FEFF (UTF-16 BOM).
-  if (string.charCodeAt(0) === 0xFEFF) {
-    return string.slice(1);
-  }
-  return string;
+  const ts = require("typescript");
+  const { baseUrl, paths, strict, allowJs } = ts.parseJsonConfigFileContent(
+    ts.readConfigFile(configFilePath, ts.sys.readFile).config,
+    ts.sys,
+    path.dirname(configFilePath),
+  ).options;
+  const ret = {
+    compilerOptions: {
+      ...baseUrl === undefined ? {} : { baseUrl },
+      ...paths === undefined ? {} : { paths },
+      ...strict === undefined ? {} : { strict },
+      ...allowJs === undefined ? {} : { allowJs },
+    },
+  };
+  return ret;
 }
```
