### ISSUE TITLE
[BUG] Object with guid ${arg.guid} was not bound in the connection

### ISSUE THREAD

**Issue by regseb** [microsoft/playwright#22210]
### System info
- Playwright Version: v1.32.2
- Operating System: Windows 10
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**package.json**

```json
{
    "name": "testcase",
    "version": "1.0.0",
    "type": "module",
    "dependencies": {
        "playwright": "1.32.2"
    }
}
```

**Test file (self-contained)**

```js
// index.js
import playwright from "playwright";

for (let i = 0; i < 1000; ++i) {
    console.log(i);
    const browser = await playwright.chromium.launch({ slowMo: 250 });
    const context = await browser.newContext();
    const page = await context.newPage();
    page.on("framenavigated", async (frame) => {
        await frame.locator("span").evaluateAll(() => {});
        await frame.addStyleTag({ content: "div {}" });
    });
    await page.goto("https://playwright.dev/docs/api/class-browser");
    await context.close();
    await browser.close();
}
```

**Steps**
- Unzip [testcase.zip](https://github.com/microsoft/playwright/files/11157402/testcase.zip)
- `npm install`
- `DEBUG=pw:api,pw:channel:command,pw:channel:response node index.js`

**Expected**

No error.

**Actual**

```
0
  pw:api => browserType.launch started +0ms
  pw:channel:command {
  pw:channel:command   id: 1,
  pw:channel:command   guid: 'browser-type@217bc1acf01e8ab60147d89d2aafcd1a',
  pw:channel:command   method: 'launch',
  pw:channel:command   params: { ignoreAllDefaultArgs: false, slowMo: 250 }
  pw:channel:command } +0ms
  pw:channel:response {
  pw:channel:response   id: 1,
  pw:channel:response   result: { browser: { guid: 'browser@457c5f62717d2b86635a9c36c4b2a3a2' } }
  pw:channel:response } +0ms
  pw:api <= browserType.launch succeeded +412ms
  pw:api => browser.newContext started +2ms
  pw:channel:command {
  pw:channel:command   id: 2,
  pw:channel:command   guid: 'browser@457c5f62717d2b86635a9c36c4b2a3a2',
  pw:channel:command   method: 'newContext',
  pw:channel:command   params: { noDefaultViewport: false }
  pw:channel:command } +413ms
  pw:channel:response {
  pw:channel:response   id: 2,
  pw:channel:response   result: {
  pw:channel:response     context: { guid: 'browser-context@c2725438de82db711cab1d84e6966c97' }
  pw:channel:response   }
  pw:channel:response } +11ms
  pw:api <= browser.newContext succeeded +9ms
  pw:api => browserContext.newPage started +1ms
  pw:channel:command {
  pw:channel:command   id: 3,
  pw:channel:command   guid: 'browser-context@c2725438de82db711cab1d84e6966c97',
  pw:channel:command   method: 'newPage',
  pw:channel:command   params: undefined
  pw:channel:command } +10ms
  pw:channel:response {
  pw:channel:response   id: 3,
  pw:channel:response   result: { page: { guid: 'page@b84a8ba8e6e23aa2528953cbf97dc5c3' } }
  pw:channel:response } +155ms
  pw:api <= browserContext.newPage succeeded +153ms
  pw:api => page.goto started +1ms
  pw:channel:command {
  pw:channel:command   id: 4,
  pw:channel:command   guid: 'frame@3ee5e10621a15eaf80cb985dbccb9a28',
  pw:channel:command   method: 'goto',
  pw:channel:command   params: {
  pw:channel:command     url: 'https://playwright.dev/docs/api/class-browser',
  pw:channel:command     waitUntil: 'load'
  pw:channel:command   }
  pw:channel:command } +154ms
  pw:api navigating to "https://playwright.dev/docs/api/class-browser", waiting until "load" +2ms
  pw:api   "commit" event fired +45ms
  pw:api   navigated to "https://playwright.dev/docs/api/class-browser" +1ms
  pw:api => locator.evaluateAll started +3ms
  pw:channel:command {
  pw:channel:command   id: 5,
  pw:channel:command   guid: 'frame@3ee5e10621a15eaf80cb985dbccb9a28',
  pw:channel:command   method: 'evalOnSelectorAll',
  pw:channel:command   params: {
  pw:channel:command     selector: 'span',
  pw:channel:command     expression: '() => {}',
  pw:channel:command     isFunction: true,
  pw:channel:command     arg: { value: [Object], handles: [] }
  pw:channel:command   }
  pw:channel:command } +51ms
  pw:api   "domcontentloaded" event fired +189ms
  pw:api   "load" event fired +117ms
  pw:channel:response { id: 5, result: { value: { v: 'undefined' } } } +512ms
  pw:api <= locator.evaluateAll succeeded +157ms
  pw:api => frame.addStyleTag started +3ms
  pw:channel:command {
  pw:channel:command   id: 6,
  pw:channel:command   guid: 'frame@3ee5e10621a15eaf80cb985dbccb9a28',
  pw:channel:command   method: 'addStyleTag',
  pw:channel:command   params: { content: 'div {}' }
  pw:channel:command } +466ms
  pw:channel:response {
  pw:channel:response   id: 4,
  pw:channel:response   result: { response: { guid: 'response@cab1b2a18575669f02a3fbe57676ad7a' } }
  pw:channel:response } +105ms
  pw:api <= page.goto succeeded +100ms
  pw:api => browserContext.close started +3ms
  pw:channel:command {
  pw:channel:command   id: 7,
  pw:channel:command   guid: 'browser-context@c2725438de82db711cab1d84e6966c97',
  pw:channel:command   method: 'close',
  pw:channel:command   params: undefined
  pw:channel:command } +103ms
  pw:channel:response { id: 7 } +12ms
  pw:api <= browserContext.close succeeded +8ms
  pw:api => browser.close started +1ms
  pw:channel:command {
  pw:channel:command   id: 8,
  pw:channel:command   guid: 'browser@457c5f62717d2b86635a9c36c4b2a3a2',
  pw:channel:command   method: 'close',
  pw:channel:command   params: undefined
  pw:channel:command } +9ms
  pw:channel:response { id: 8 } +38ms
  pw:api <= browser.close succeeded +38ms
1
  pw:api => browserType.launch started +3ms
  pw:channel:command {
  pw:channel:command   id: 9,
  pw:channel:command   guid: 'browser-type@217bc1acf01e8ab60147d89d2aafcd1a',
  pw:channel:command   method: 'launch',
  pw:channel:command   params: { ignoreAllDefaultArgs: false, slowMo: 250 }
  pw:channel:command } +42ms
  pw:channel:response {
  pw:channel:response   id: 6,
  pw:channel:response   result: { element: { guid: 'handle@7833e65f500bd1d978e1450a5459c7bb' } }
  pw:channel:response } +238ms
C:\Users\regseb\dev\testcase\node_modules\playwright-core\lib\client\connection.js:211
      if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);
                   ^

Error: Object with guid handle@7833e65f500bd1d978e1450a5459c7bb was not bound in the connection
    at Connection._tChannelImplFromWire (C:\Users\regseb\dev\testcase\node_modules\playwright-core\lib\client\connection.js:211:26)
    at C:\Users\regseb\dev\testcase\node_modules\playwright-core\lib\protocol\validatorPrimitives.js:129:20
    at C:\Users\regseb\dev\testcase\node_modules\playwright-core\lib\protocol\validatorPrimitives.js:108:21
    at Connection.dispatch (C:\Users\regseb\dev\testcase\node_modules\playwright-core\lib\client\connection.js:170:26)
    at Immediate.<anonymous> (C:\Users\regseb\dev\testcase\node_modules\playwright-core\lib\inProcessFactory.js:46:83)
    at processImmediate (node:internal/timers:466:21)
```

### Additional info

- I add style with `frame.addStyleTag()`.
  - Playwright sends a command to the browser to add style (using a protocol close to [JSON-RPC](https://www.jsonrpc.org/specification)).
    ```javascript
    {
      id: 6,
      guid: 'frame@3ee5e10621a15eaf80cb985dbccb9a28',
      method: 'addStyleTag',
      params: { content: 'div {}' }
    }
    ``` 
- I close the browser.
  - Playwright _removes_ the callbacks from the commands.
- Playwright receives the response from the command.
  ```JavaScript
  {
    id: 6,
    result: { element: { guid: 'handle@7833e65f500bd1d978e1450a5459c7bb' } }
  }
  ```
  - Playwright doesn't find the callback associated with the command and throws an exception.
    https://github.com/microsoft/playwright/blob/ecd0f927f4f0efb396aec1a839b4252b229f8ae0/packages/playwright-core/src/client/connection.ts#L191-L193

### Related issues

- https://github.com/microsoft/playwright/issues/20023
- https://github.com/microsoft/playwright/issues/21210#issuecomment-1477840641

**Comment by pavelfeldman** [comment]
The problem is with this snippet:
```js
page.on("framenavigated", async (frame) => {
        await frame.locator("span").evaluateAll(() => {});
        await frame.addStyleTag({ content: "div {}" });
});
```

Listeners are synchronous in JavaScript, so by the time you reach the second line in this handler, `context.close()` already ran.

**Comment by carlos-dubon** [comment]
This happens a lot... and try catch does't seem to ignore it. It's really annoying when 9986/9999 pages scraped for 10 hours straight and suddenly.

`if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);`

**Comment by regseb** [comment]
- https://github.com/microsoft/playwright/pull/28629

The pull request above (which hasn't yet been released) fixes these two issues:

- https://github.com/microsoft/playwright/issues/28504
- https://github.com/microsoft/playwright/issues/28320

Maybe it also corrects this issue and the others:

- https://github.com/microsoft/playwright/issues/20023
- https://github.com/microsoft/playwright/issues/21210
- https://github.com/microsoft/playwright/issues/27704
- https://github.com/microsoft/playwright/issues/28214

**Comment by mxschmitt** [comment]
I recommend trying out Canary for now to see if it works for your use-case: https://playwright.dev/docs/canary-releases

**Comment by regseb** [comment]
I tested the use-cases https://github.com/microsoft/playwright/issues/22210#issue-1655290697 and https://github.com/microsoft/playwright/issues/21210#issue-1599996576 (with node `v21.0.0`, npm `10.2.0` and chromium).

I reproduce the bug with playwright `1.32.3`. And I have no more bug with playwright `1.33.0`, `1.40.1` and `1.41.0-alpha-dec-21-2023`. My problem was probably corrected in version [`v1.33.0`](https://github.com/microsoft/playwright/releases/tag/v1.33.0). Thanks for the fix.

**Comment by carlos-dubon** [comment]
I got this error with 1.40.x ... so the issue is not closes.. remember this is random.. so maybe you were lucky this time?

**Comment by xisvaldo** [comment]
any updates?

**Comment by yosom** [comment]
C:\Users\Administrator\Desktop\lks.c\node_modules\playwright-core\lib\client\connection.js:214
      if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);
                   ^

Error: Object with guid response@563861c33e81d9b5bcc4bdfb0a4b1337 was not bound in the connection
    at Connection._tChannelImplFromWire (C:\Users\Administrator\Desktop\lks.c\node_modules\playwright-core\lib\client\connection.js:214:26)   
    at C:\Users\Administrator\Desktop\lks.c\node_modules\playwright-core\lib\protocol\validatorPrimitives.js:128:20
    at C:\Users\Administrator\Desktop\lks.c\node_modules\playwright-core\lib\protocol\validatorPrimitives.js:90:12
    at C:\Users\Administrator\Desktop\lks.c\node_modules\playwright-core\lib\protocol\validatorPrimitives.js:107:21
    at Connection.dispatch (C:\Users\Administrator\Desktop\lks.c\node_modules\playwright-core\lib\client\connection.js:175:26)
    at Immediate.<anonymous> (C:\Users\Administrator\Desktop\lks.c\node_modules\playwright-core\lib\inProcessFactory.js:49:83)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v21.6.1
