### ISSUE TITLE
[BUG] Error: Unexpected token "$" while parsing selector "Elemen$/"

### ISSUE THREAD

**Issue by Aroot42** [microsoft/playwright#22303]
### System info
- Playwright Version: [v1.32.2]
- Operating System: [Windows 11]
- Browser: [All]

```
Error: locator.click: Error: Unexpected token "$" while parsing selector "Elemen$/"
    at unexpected (<anonymous>:1175:12)
    at consumeSimpleSelector (<anonymous>:1296:15)
    at consumeComplexSelector (<anonymous>:1233:40)
    at consumeArgument (<anonymous>:1225:12)
    at consumeFunctionArguments (<anonymous>:1209:22)
    at parseCSS (<anonymous>:1309:18)
    at <anonymous>:1327:25
    at Array.map (<anonymous>)
    at parseSelector (<anonymous>:1323:30)
    at InjectedScript.parseSelector (<anonymous>:4365:20)
=========================== logs ===========================
waiting for getByRole('row').filter({ has: getByRole('cell', { name: 'ABC Demonstration Supplier UK', exact: true }) }).locator('a.smallicon-respondrfq')
============================================================
    at unexpected (***\Playwright\<anonymous>:1175:12)
    at consumeSimpleSelector (***\Playwright\<anonymous>:1296:15)
    at consumeComplexSelector (***\Playwright\<anonymous>:1233:40)
    at consumeArgument (***\Playwright\<anonymous>:1225:12)
    at consumeFunctionArguments (***\Playwright\<anonymous>:1209:22)
    at parseCSS (***\Playwright\<anonymous>:1309:18)
    at ***\Playwright\<anonymous>:1327:25
    at parseSelector (***\Playwright\<anonymous>:1323:30)
    at InjectedScript.parseSelector (***\Playwright\<anonymous>:4365:20)
    at unexpected (***\Playwright\<anonymous>:1175:12)
    at consumeSimpleSelector (***\Playwright\<anonymous>:1296:15)
    at consumeComplexSelector (***\Playwright\<anonymous>:1233:40)
    at consumeArgument (***\Playwright\<anonymous>:1225:12)
    at consumeFunctionArguments (***\Playwright\<anonymous>:1209:22)
    at parseCSS (***\Playwright\<anonymous>:1309:18)
    at ***\Playwright\<anonymous>:1327:25
    at parseSelector (***\Playwright\<anonymous>:1323:30)
    at InjectedScript.parseSelector (***\Playwright\<anonymous>:4365:20)
    at ***\Playwright\Pages\Enquiry\EnquiryReviewPage.ts:695:18
    at EnquiryReviewPage.RespondOnBehalfOfSupplierByName (***\Playwright\Pages\Enquiry\EnquiryReviewPage.ts:685:20)
    at ***\Playwright\Pages\Models\EnquiryModel.ts:852:46
    at EnquiryModel.RespondOnBehalfOfSeveralSuppliers (***\Playwright\Pages\Models\EnquiryModel.ts:843:9)
    at ***\Playwright\tests\Enquiries\EnquiriesDraftToOrdered.spec.ts:2777:13
```

**Comment by mxschmitt** [comment]
Can you provide us a reproduction which we can run locally to get your error?

**Comment by mxschmitt** [comment]
Unfortunately we then can't act on it. Closing for now until we have a clear repro, feel free to re-file then with more information so we can reproduce.
