### ISSUE TITLE
[BUG] It always fails at the same point when I execute all tests with the UI mode

### ISSUE THREAD

**Issue by tadashi-aikawa** [microsoft/playwright#22301]
### System info

- Playwright Version: v1.32.2
- Operating System: Windows 11
- Browser: All
- Node.js 18.12.0
- PowerShell 7.3.3

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/tadashi-aikawa/nuxt2-vuetify2-playwright-sandbox.git

**Steps**

#### 1. Clone the repository and run the application

```
git clone https://github.com/tadashi-aikawa/nuxt2-vuetify2-playwright-sandbox.git
cd nuxt2-vuetify2-playwright-sandbox
git checkout 413de5f02e7affb8f301396929ca383dc967696e
npm install
npm run dev
```

#### 2. Open the playwright GUI mode in another shell process

```
cd nuxt2-vuetify2-playwright-sandbox
npx playwright test --ui
```

#### 3. Run all tests

![image](https://user-images.githubusercontent.com/9500018/230776850-6bddb592-22cc-4c39-bc20-54cc0d038784.png)

**Expected**

Success all tests.

**Actual**

Some tests fail as follows.

![image](https://user-images.githubusercontent.com/9500018/230776860-dea31128-a1c0-49ed-bc9f-495b42f9fa60.png)

The terminal that runs "npm run dev" shows errors.

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, stat 'C:\Users\syoum\tmp\nuxt2-vuetify2-playwright-sandbox\test-results\.playwright-artifacts-1\1a98587cb1640f43c20527b24baacb89.zip'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher.emitWithAll (C:\Users\syoum\tmp\nuxt2-vuetify2-playwright-sandbox\node_modules\chokidar\index.js:540:8)
    at awfEmit (C:\Users\syoum\tmp\nuxt2-vuetify2-playwright-sandbox\node_modules\chokidar\index.js:599:14)
    at C:\Users\syoum\tmp\nuxt2-vuetify2-playwright-sandbox\node_modules\chokidar\index.js:714:43
    at FSReqCallback.oncomplete (node:fs:207:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\Users\\syoum\\tmp\\nuxt2-vuetify2-playwright-sandbox\\test-results\\.playwright-artifacts-1\\1a98587cb1640f43c20527b24baacb89.zip'
}

Node.js v18.12.0
```

### Remarks

- Without UI mode, it is always a success (`npx playwright test`)
- It occurs even if set `1` to `workers`
- I confirmed that I could create `C:\Users\syoum\tmp\nuxt2-vuetify2-playwright-sandbox\test-results\.playwright-artifacts-1\1a98587cb1640f43c20527b24baacb89.zip` manually
- It occurs even if I run them as an administrator
- It occurs even if I select firefox or webkit instead of chromium

Please let me know if any information is missing.

Best regards.

P.S. The new feature, UI mode, is very awesome!! It looks like as a cool IDE to e2e test! 😄

**Comment by tadashi-aikawa** [comment]
I got it. Many thanks!
