### ISSUE TITLE
[BUG] Error: Assertion error

### ISSUE THREAD

**Issue by VadymLepishko** [microsoft/playwright#22315]
**Context:**
- Playwright Version: 1.30+
- Operating System: Linux (in Docker)
- Python version: 3.7.
- Browser: Firefox
- Extra: Application is running in Docker (based on ubuntu:focal) with custom settings.

**Code Snippet**
Our custom manager:
```
from playwright.sync_api import sync_playwright


class FirefoxDriver:
    def __init__(self):
        self._manager = sync_playwright()
        self._playwright = self._manager.start()
        proxy_settings = {
                'proxy': {
                    "server": f"***.***.***.***:**",
                    "username": "*******",
                    "password": "*******"
        }}
        self._browser = self._playwright.firefox.launch(
            headless=False,
            **proxy_settings,
        )
        self.page = self._browser.new_page(
            viewport={'width': 1980, 'height': 1280},
            accept_downloads=True
        )
        self.page.context.add_cookies("some cookies")
        self.page.set_default_timeout(90 * 1000)

    def __enter__(self):
        return self

    def __exit__(self):
        self._browser.close()
        self._manager.__exit__()
```
Starting the app:
```
with FirefoxDriver() as driver:
    driver.page.goto('https://www.ups.com/us/en/Home.page?Site=Corporate&cookie=us_en_home&setCookie=yes')
    # some requests (example):
    # driver.page.query_selector(
            '//*[@id="root"]/div/nav/div/div/div').query_selector('text=Billing Center')
    # ...
    driver.page.goto('https://billing.ups.com/home')
```

**Describe the bug**
Sometimes, when Firefox navigates to another page, after a couple of seconds, the browser gives an error that blocks our work:
```
/usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/utils/debug.js:29
  if (!value) throw new Error(message || 'Assertion error');
                    ^

Error: Assertion error
    at assert (/usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/utils/debug.js:29:21)
    at FrameManager.frameAttached (/usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/server/frames.js:103:25)
    at FFPage._onFrameAttached (/usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/server/firefox/ffPage.js:174:30)
    at FFSession.emit (node:events:513:28)
    at /usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:204:41

Node.js v18.15.0
```
What could be the problem here?

**Comment by mxschmitt** [comment]
We need a full reproducible which we can run locally to replicate this issue. If it only reproduces 1/100 it's also fine, but without a reproducible we unfortunately cannot act on it.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since this issue looks stale. Please re-file with more details and a clear repro. Thanks!

**Comment by Darshan972** [comment]
Hello, is this issue solved?
