### ISSUE TITLE
[BUG] launchPersistentContext failed

### ISSUE THREAD

**Issue by icesmartjuan** [microsoft/playwright#22449]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [Ubuntu 22.4, macOS Big Sur 11.7]
- Browser: [Firefox]
- Other info: with args `'--disable-blink-features=AutomationControlled',` 

### Code Snippet

```js
const playwright = require("playwright")

const run = async (url) => {
    let browserContext = await playwright.firefox.launchPersistentContext("", {
        headless: false,
        javaScriptEnabled: true,
        ignoreHTTPSErrors: true,
        args:[
            '--disable-blink-features=AutomationControlled',
        ],
    });

    //get hang on the second launchPersistentContext call and finally crash
    let browserContext2 = await playwright.firefox.launchPersistentContext("", {
        headless: false,
        javaScriptEnabled: true,
        ignoreHTTPSErrors: true,
        args:[
            '--disable-blink-features=AutomationControlled',
        ],
    });

    const page = await browserContext.newPage()
    await page.goto(url)
}

let url ='https://www.sample.com'
run(url)
```
**Steps**
- [Run above code]
- [It will hang on the second `launchPersistentContext` call and finally crash with following info , sometimes even just one `launchPersistentContext` call, the issue still happens, it seems OK if not using `'--disable-blink-features=AutomationControlled',` ]
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

browserType.launchPersistentContext: Timeout 180000ms exceeded.
=========================== logs ===========================
<launching> xx/Library/Caches/ms-playwright/firefox-1391/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -wait-for-browser -foreground -profile /var/folders/q4/pmzpltlj1kx7w9jp15r5mx28395l8m/T/playwright_firefoxdev_profile-YO14HW -juggler-pipe --disable-blink-features=AutomationControlled about:blank
<launched> pid=46488
[pid=46488][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=46488][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=46488][out] console.error: ({})
[pid=46488][out] 
[pid=46488][out] Juggler listening to the pipe
[pid=46488][out] console.error: "Warning: unrecognized command line flag -wait-for-browser\n"
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /var/folders/q4/pmzpltlj1kx7w9jp15r5mx28395l8m/T/playwright_firefoxdev_profile-YO14HW/search.json.mozlz4", (void 0)))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] WARNING: removeEventListener throws SecurityError: Permission denied to access property "removeEventListener" on cross-origin object at addEventListener/<@chrome://juggler/content/Helper.js:49:61
[pid=46488][out] removeListeners@chrome://juggler/content/Helper.js:78:16
[pid=46488][out] _dispose@chrome://juggler/content/content/JugglerFrameChild.jsm:47:12
[pid=46488][out] didDestroy@chrome://juggler/content/content/JugglerFrameChild.jsm:59:10
[pid=46488][out] 
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=46488][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
============================================================
    at async run (.../xx.js:28:27) {
  name: 'TimeoutError'
} ```

**Comment by dgozman** [comment]
@icesmartjuan `'--disable-blink-features=AutomationControlled'` is not a valid Firefox argument. Unfortunately, when launching a persistent context, Firefox treats it as a url to navigate to, and this sometimes breaks Playwright logic that detects that browser has launched successfully. Let me know if this helps.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
