### ISSUE TITLE
[BUG] Exception has occurred: TypeError TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by pipi1007** [microsoft/playwright#2271]
Crash after a few requests:

Exception has occurred: TypeError
TypeError: Cannot read property 'split' of undefined
    at Object.exceptionToError (C:\code\owa-monitoring\ActiveMonitor\AKS\playwrightimp\node_modules\playwright-core\lib\chromium\crProtocolHelper.js:93:36)
    at FrameSession._handleException (C:\code\owa-monitoring\ActiveMonitor\AKS\playwrightimp\node_modules\playwright-core\lib\chromium\crPage.js:536:76)
    at CRSession.<anonymous> (C:\code\owa-monitoring\ActiveMonitor\AKS\playwrightimp\node_modules\playwright-core\lib\chromium\crPage.js:294:105)
    at CRSession.emit (events.js:203:13)

It fails on this line, messageWithStack is undefined:

function exceptionToError(exceptionDetails) {
    const messageWithStack = getExceptionMessage(exceptionDetails);
    const lines = messageWithStack.split('\n');

**Comment by dgozman** [comment]
I can repro this locally, thanks for filing!

**Comment by dgozman** [comment]
This will be fixed in the next 1.1 release.

**Comment by pipi1007** [comment]
Thanks for fixing it!
