### ISSUE TITLE
Trying to lunch test through a node JS IIS

### ISSUE THREAD

**Issue by shani1985** [microsoft/playwright#22734]
Hello,

I am encountering a problem when trying to lunch a test through a node JS IIS.  when i run the code through the cmd inside the folder with "npx playwright test" it passes. but when running the command through the IIS server code i get this output :
 
```
 "output":"\nRunning 1 test using 1 worker\n\n  [31mx[39m  [2m1 [22m[31mtests\\comBTASAutomation.spec.js:12:1 › comBTAS Automation[39m[2m (46ms)[22m\n\n\n[31m  1) tests\\comBTASAutomation.spec.js:12:1 › comBTAS Automation [90m=====================================[31m[39m\n\n    browserType.launch: Executable doesn't exist at C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\ms-playwright\\chromium-1033\\chrome-win\\chrome.exe\n    ╔═════════════════════════════════════════════════════════════════════════╗\n    ║ Looks like Playwright Test or Playwright was just installed or updated. ║\n    ║ Please run the following command to download new browsers:              ║\n    ║                                                                         ║\n    ║     npx playwright install                                              ║\n    ║                                                                         ║\n    ║ <3 Playwright Team                                                      ║\n    ╚═════════════════════════════════════════════════════════════════════════╝\n\n    [2m    at Object._baseTest.extend.browser.scope [as fn] (C:\\Projects\\start.playCombitas\\start.playCombitas\\node_modules\\@playwright\\test\\lib\\index.js:188:51)[22m\n    [2m    at C:\\Projects\\start.playCombitas\\start.playCombitas\\node_modules\\@playwright\\test\\lib\\fixtures.js:95:81[22m\n\n\n[31m  1 failed[39m\n[31m    tests\\comBTASAutomation.spec.js:12:1 › comBTAS Automation [90m======================================[31m[39m\n"
 
```
 code snippet:
```
test file-----
 const testDataCombitas = JSON.parse(fs.readFileSync('./data/combitasData.json', 'utf-8'));
//const test = require('../testFixtures/fixture')
const test = require('../testFixtures/fixtureForConbtas')


//var testDataCombitas = JSON.parse(process.env.MY_VARIABLE_NAME)


test('comBTAS Automation', async ({ comBTASPage }) => {
  test.setTimeout(40000)
  await comBTASPage.loginToCombitass('dannym', '1234')
 }
```

```
server file ----
const express = require('express')
const bodyParser = require('body-parser')
const app = express()
const PORT = process.env.PORT || 3003
let newrequest
const env = Object.create(process.env)
process.env.npm_config_cache = './npm-cache';

app.use(bodyParser.json())

 app.get('/get', (req, res) =>{
 res.send('succesS')
 }) 

app.post('/requestTask', (req, res) => {
  newrequest = req.body
  console.log(newrequest)

  process.env.MY_VARIABLE_NAME = JSON.stringify(newrequest)

  const { exec } = require('node:child_process')

  exec('npx playwright test "comBTASAutomation.spec.js"',{ cwd: 'C:/Projects/start.playCombitas/start.playCombitas', env }, (err, output ,  stderr) => {
    if (err) {
		console.log('Output: \n', output)
		
      const testOutputFailure = { status: 'failure',j: process.env.MY_VARIABLE_NAME , error: stderr, output}
      res.send(testOutputFailure)
      return
    }
  console.log('Output: \n', output) // Add this line to log the output produced by Playwright
  let testOutput = null
  if (output.toString().indexOf('passed') > -1) {
    testOutput = { status: 'succes' }
  }
    res.send(testOutput)
  })
})

app.listen(PORT, () => console.log(`Server listening on port ${PORT}`))
```
thanks in advanced

**Comment by shani1985** [comment]
maybe it was not clear but the playwright is installed on the conuter but only when running it throgh the iis it asks to install again
