### ISSUE TITLE
[BUG] Can't connect to browser on websocket port

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#2287]
**Context:**
- Playwright Version: 1.02
- Operating System: Mac
- Node version: 12
- Browser: Chromium
- Extra: Trying to connect to chrome which is already running with websocket port enabled. It doesn't work properly and throws error.

**Code Snippet**
```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.connect({
    wsEndpoint: `ws://127.0.0.1:60243/devtools/browser/9d9469a6-6547-4ba6-8619-d181657be515`
  });
  // ... 
})();
```

**Describe the bug**
Error log:
```
Error: Protocol error (Browser.setDownloadBehavior): 'Browser.setDownloadBehavior' wasn't found
    at /Users/vikramtiwari/Documents/code/test1/node_modules/playwright-core/lib/chromium/crConnection.js:130:63
    at new Promise (<anonymous>)
    at CRSession.send (/Users/vikramtiwari/Documents/code/test1/node_modules/playwright-core/lib/chromium/crConnection.js:129:16)
    at CRSession.<anonymous> (/Users/vikramtiwari/Documents/code/test1/node_modules/playwright-core/lib/helper.js:64:31)
    at CRBrowserContext._initialize (/Users/vikramtiwari/Documents/code/test1/node_modules/playwright-core/lib/chromium/crBrowser.js:251:36)
    at CRBrowser.newContext (/Users/vikramtiwari/Documents/code/test1/node_modules/playwright-core/lib/chromium/crBrowser.js:95:23)
    at async /Users/vikramtiwari/Documents/code/test1/playwright.js:19:21
  -- ASYNC --
    at CRBrowser.<anonymous> (/Users/vikramtiwari/Documents/code/test1/node_modules/playwright-core/lib/helper.js:63:23)
    at /Users/vikramtiwari/Documents/code/test1/playwright.js:19:35 {
  message: "Protocol error (Browser.setDownloadBehavior): 'Browser.setDownloadBehavior' wasn't found"
}
```

**Comment by pavelfeldman** [comment]
You are trying to connect to the old Chromium. Playwright only works with Firefox and WebKit that it provides or a bleeding edge Chromium (M84+).

**Comment by VikramTiwari** [comment]
@pavelfeldman I understand that latest version of playwright will work with bleeding edge chromium but that shouldn't mean that older versions of playwright won't work with older versions of chromium. I have seen this bug with older versions of playwright as well.
