### ISSUE TITLE
[REGRESSION]: Regular WebKit crashes after specific screenshot steps

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#22903]
Extracted from https://github.com/microsoft/playwright/issues/22790#issuecomment-1534341433

**Context:**
- GOOD Playwright Version: 1.32.3
- BAD Playwright Version: 1.33.0
- Operating System: Docker image
- Extra:

**Code Snippet**

I haven't been able to narrow down a test case, but this can be seen in an actual project (https://github.com/PREreview/prereview.org/pull/885):

```
git clone --no-checkout https://github.com/PREreview/prereview.org
cd prereview.org/
git checkout 883c91c75a2f76d7844b70ad4f42d6e362728a45
make test-integration TEST="--project 'iPhone 11' --grep 'might not authenticate with ORCID in time'"
```

(You'll need Git LFS installed to get the existing snapshots.)

**Describe the bug**

Two tests are regularly failing in WebKit (with JavaScript enabled):

```
Running 2 tests using 2 workers

  ✘  2 [iPhone 11] › publishing-a-prereview.spec.ts:1279:23 › mind not find the pseudonym in time (30.0s)
  ✘  1 [iPhone 11] › publishing-a-prereview.spec.ts:1195:6 › might not authenticate with ORCID in time (30.0s)


  1) [iPhone 11] › publishing-a-prereview.spec.ts:1195:6 › might not authenticate with ORCID in time 

    Test timeout of 30000ms exceeded.

    Error: keyboard.press: Protocol error (Input.dispatchKeyEvent): Page closed [{"code":-32000,"message":"Page closed"}]

      1223 |   await expect(page).toHaveScreenshot()
      1224 |
    > 1225 |   await page.keyboard.press('Tab')
           |                       ^
      1226 |
      1227 |   await expect(page.getByRole('link', { name: 'Skip to main content' })).toBeFocused()
      1228 |   await expect(page).toHaveScreenshot()

        at /app/integration/publishing-a-prereview.spec.ts:1225:23

    Pending operations:
      - keyboard.press at integration/publishing-a-prereview.spec.ts:1225:23


    attachment #1: screenshot (image/png) ──────────────────────────────────────────────────────────
    integration-results/publishing-a-prereview-might-not-authenticate-with-ORCID-in-time-iPhone-11/test-failed-1.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

  2) [iPhone 11] › publishing-a-prereview.spec.ts:1279:23 › mind not find the pseudonym in time ────

    Test timeout of 30000ms exceeded.

    Error: keyboard.press: Protocol error (Input.dispatchKeyEvent): Page closed [{"code":-32000,"message":"Page closed"}]

      1305 |   await expect(page).toHaveScreenshot()
      1306 |
    > 1307 |   await page.keyboard.press('Tab')
           |                       ^
      1308 |
      1309 |   await expect(page.getByRole('link', { name: 'Skip to main content' })).toBeFocused()
      1310 |   await expect(page).toHaveScreenshot()

        at /app/integration/publishing-a-prereview.spec.ts:1307:23

    Pending operations:
      - keyboard.press at integration/publishing-a-prereview.spec.ts:1307:23


    attachment #1: screenshot (image/png) ──────────────────────────────────────────────────────────
    integration-results/publishing-a-prereview-mind-not-find-the-pseudonym-in-time-iPhone-11/test-failed-1.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

  2 failed
    [iPhone 11] › publishing-a-prereview.spec.ts:1195:6 › might not authenticate with ORCID in time 
    [iPhone 11] › publishing-a-prereview.spec.ts:1279:23 › mind not find the pseudonym in time ─────
``` 

I can get some debug info that shows WebKit is crashing, but without any details about _why_ it's crashing:

```
  pw:api => keyboard.press started +2ms
2023-05-04T08:46:09.500Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepBegin","params":{"testId":"79b8dca29434021e61c1-c4864275367836bcbb43","stepId":"pw:api@keyboard.press(Tab)@11","location":{"file":"/app/integration/publishing-a-prereview.spec.ts","line":1936,"column":23},"category":"pw:api","title":"keyboard.press(Tab)","wallTime":1683189969498}}}
2023-05-04T08:46:09.500Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;33;1mpw:channel:command \u001b[0m{\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  id: \u001b[33m15\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  guid: \u001b[32m'page@0054bc02d4deca844a923c6322f48b02'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  method: \u001b[32m'keyboardPress'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  params: { key: \u001b[32m'Tab'\u001b[39m }\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m} \u001b[38;5;33m+142ms\u001b[0m\n"}}}
  pw:channel:command {
  pw:channel:command   id: 15,
  pw:channel:command   guid: 'page@0054bc02d4deca844a923c6322f48b02',
  pw:channel:command   method: 'keyboardPress',
  pw:channel:command   params: { key: 'Tab' }
  pw:channel:command } +142ms
2023-05-04T08:46:09.501Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0m◀ RECV {\"result\":{},\"id\":337,\"browserContextId\":\"8000000000000002\",\"pageProxyId\":\"8\"} \u001b[38;5;34m+84ms\u001b[0m\n"}}}
  pw:protocol ◀ RECV {"result":{},"id":337,"browserContextId":"8000000000000002","pageProxyId":"8"} +84ms
2023-05-04T08:46:09.501Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0m◀ RECV {\"method\":\"Target.dispatchMessageFromTarget\",\"params\":{\"targetId\":\"page-15\",\"message\":\"{\\\"result\\\":{\\\"result\\\":{\\\"type\\\":\\\"undefined\\\"},\\\"wasThrown\\\":false},\\\"id\\\":336}\"},\"browserContextId\":\"8000000000000002\",\"pageProxyId\":\"8\"} \u001b[38;5;34m+0ms\u001b[0m\n"}}}
  pw:protocol ◀ RECV {"method":"Target.dispatchMessageFromTarget","params":{"targetId":"page-15","message":"{\"result\":{\"result\":{\"type\":\"undefined\"},\"wasThrown\":false},\"id\":336}"},"browserContextId":"8000000000000002","pageProxyId":"8"} +0ms
2023-05-04T08:46:09.501Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0m◀ RECV {\"method\":\"Target.targetDestroyed\",\"params\":{\"targetId\":\"page-15\",\"crashed\":true},\"browserContextId\":\"8000000000000002\",\"pageProxyId\":\"8\"} \u001b[38;5;34m+0ms\u001b[0m\n"}}}
  pw:protocol ◀ RECV {"method":"Target.targetDestroyed","params":{"targetId":"page-15","crashed":true},"browserContextId":"8000000000000002","pageProxyId":"8"} +0ms
2023-05-04T08:46:09.502Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0mSEND ► {\"id\":338,\"method\":\"Input.dispatchKeyEvent\",\"params\":{\"type\":\"keyDown\",\"modifiers\":0,\"windowsVirtualKeyCode\":9,\"code\":\"Tab\",\"key\":\"Tab\",\"text\":\"\",\"unmodifiedText\":\"\",\"autoRepeat\":false,\"isKeypad\":false},\"pageProxyId\":\"8\"} \u001b[38;5;34m+1ms\u001b[0m\n"}}}
  pw:protocol SEND ► {"id":338,"method":"Input.dispatchKeyEvent","params":{"type":"keyDown","modifiers":0,"windowsVirtualKeyCode":9,"code":"Tab","key":"Tab","text":"","unmodifiedText":"","autoRepeat":false,"isKeypad":false},"pageProxyId":"8"} +1ms
2023-05-04T08:46:09.503Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;34;1mpw:protocol \u001b[0mSEND ► {\"id\":339,\"method\":\"Input.dispatchKeyEvent\",\"params\":{\"type\":\"keyUp\",\"modifiers\":0,\"key\":\"Tab\",\"windowsVirtualKeyCode\":9,\"code\":\"Tab\",\"isKeypad\":false},\"pageProxyId\":\"8\"} \u001b[38;5;34m+0ms\u001b[0m\n"}}}
  pw:protocol SEND ► {"id":339,"method":"Input.dispatchKeyEvent","params":{"type":"keyUp","modifiers":0,"key":"Tab","windowsVirtualKeyCode":9,"code":"Tab","isKeypad":false},"pageProxyId":"8"} +0ms
2023-05-04T08:46:09.503Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;207;1mpw:channel:event \u001b[0m{\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  guid: \u001b[32m'page@0054bc02d4deca844a923c6322f48b02'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  method: \u001b[32m'crash'\u001b[39m,\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m  params: \u001b[90mundefined\u001b[39m\n  \u001b[38;5;207;1mpw:channel:event \u001b[0m} \u001b[38;5;207m+274ms\u001b[0m\n"}}}
  pw:channel:event {
  pw:channel:event   guid: 'page@0054bc02d4deca844a923c6322f48b02',
  pw:channel:event   method: 'crash',
  pw:channel:event   params: undefined
  pw:channel:event } +274ms
2023-05-04T08:46:34.588Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepBegin","params":{"testId":"79b8dca29434021e61c1-c4864275367836bcbb43","stepId":"hook@After Hooks@12","category":"hook","title":"After Hooks","wallTime":1683189994587}}}
2023-05-04T08:46:34.589Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[32;1mpw:test \u001b[0mon-failure callback started \u001b[32m+30s\u001b[0m\n"}}}
  pw:test on-failure callback started +30s
2023-05-04T08:46:34.589Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepBegin","params":{"testId":"79b8dca29434021e61c1-c4864275367836bcbb43","stepId":"hook@Screenshot on failure@13","parentStepId":"hook@After Hooks@12","category":"hook","title":"Screenshot on failure","wallTime":1683189994588}}}
2023-05-04T08:46:34.592Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;45;1mpw:api \u001b[0m=> page.screenshot started \u001b[38;5;45m+25s\u001b[0m\n"}}}
  pw:api => page.screenshot started +25s
2023-05-04T08:46:34.593Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stepBegin","params":{"testId":"79b8dca29434021e61c1-c4864275367836bcbb43","stepId":"pw:api@page.screenshot@14","parentStepId":"hook@Screenshot on failure@13","category":"pw:api","title":"page.screenshot","wallTime":1683189994592}}}
2023-05-04T08:46:34.593Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;33;1mpw:channel:command \u001b[0m{\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  id: \u001b[33m16\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  guid: \u001b[32m'page@0054bc02d4deca844a923c6322f48b02'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  method: \u001b[32m'screenshot'\u001b[39m,\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m  params: { timeout: \u001b[33m5000\u001b[39m, type: \u001b[32m'png'\u001b[39m, caret: \u001b[32m'initial'\u001b[39m }\n  \u001b[38;5;33;1mpw:channel:command \u001b[0m} \u001b[38;5;33m+25s\u001b[0m\n"}}}
  pw:channel:command {
  pw:channel:command   id: 16,
  pw:channel:command   guid: 'page@0054bc02d4deca844a923c6322f48b02',
  pw:channel:command   method: 'screenshot',
  pw:channel:command   params: { timeout: 5000, type: 'png', caret: 'initial' }
  pw:channel:command } +25s
2023-05-04T08:46:34.595Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;45;1mpw:api \u001b[0mtaking page screenshot \u001b[38;5;45m+2ms\u001b[0m\n"}}}
  pw:api taking page screenshot +2ms
2023-05-04T08:46:34.598Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"stdErr","params":{"text":"  \u001b[38;5;202;1mpw:channel:response \u001b[0m{\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m  id: \u001b[33m16\u001b[39m,\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m  error: {\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m    error: {\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m      message: \u001b[32m'Target crashed\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'=========================== logs ===========================\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'taking page screenshot\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'============================================================'\u001b[39m,\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m      stack: \u001b[32m'Error: Target crashed\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'=========================== logs ===========================\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'taking page screenshot\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'============================================================\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'    at WKSession.send (/app/node_modules/playwright-core/lib/server/webkit/wkConnection.js:127:30)\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'    at WKPage.takeScreenshot (/app/node_modules/playwright-core/lib/server/webkit/wkPage.js:823:40)\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'    at Screenshotter._screenshot (/app/node_modules/playwright-core/lib/server/screenshotter.js:262:47)\\n'\u001b[39m +\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m        \u001b[32m'    at /app/node_modules/playwright-core/lib/server/screenshotter.js:168:22'\u001b[39m,\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m      name: \u001b[32m'Error'\u001b[39m\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m    }\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m  }\n  \u001b[38;5;202;1mpw:channel:response \u001b[0m} \u001b[38;5;202m+25s\u001b[0m\n"}}}
  pw:channel:response {
  pw:channel:response   id: 16,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: 'Target crashed\n' +
  pw:channel:response         '=========================== logs ===========================\n' +
  pw:channel:response         'taking page screenshot\n' +
  pw:channel:response         '============================================================',
  pw:channel:response       stack: 'Error: Target crashed\n' +
  pw:channel:response         '=========================== logs ===========================\n' +
  pw:channel:response         'taking page screenshot\n' +
  pw:channel:response         '============================================================\n' +
  pw:channel:response         '    at WKSession.send (/app/node_modules/playwright-core/lib/server/webkit/wkConnection.js:127:30)\n' +
  pw:channel:response         '    at WKPage.takeScreenshot (/app/node_modules/playwright-core/lib/server/webkit/wkPage.js:823:40)\n' +
  pw:channel:response         '    at Screenshotter._screenshot (/app/node_modules/playwright-core/lib/server/screenshotter.js:262:47)\n' +
  pw:channel:response         '    at /app/node_modules/playwright-core/lib/server/screenshotter.js:168:22',
  pw:channel:response       name: 'Error'
  pw:channel:response     }
  pw:channel:response   }
  pw:channel:response } +25s
```

It seems to crash shortly after an `expect(page).toHaveScreenshot()` step passes (
https://github.com/PREreview/prereview.org/blob/883c91c75a2f76d7844b70ad4f42d6e362728a45/integration/publishing-a-prereview.spec.ts#L1223).

I've not been able to recreate the failure with the screenshot-steps removed, nor with JavaScript disabled.

**Comment by pavelfeldman** [comment]
Thanks for the repro. Your repository looks like a production project with a lot of dependencies that I am hesitant installing locally. Could you provide a reduced test case that demonstrates the issue and nothing but the issue? Ideally it would only use playwright and point at the live version of your app (https://beta.prereview.org/.?)

**Comment by thewilkybarkid** [comment]
Thanks @pavelfeldman, I'm seeing if I can isolate the problem more. The two cases where it fails have mocked errors on the server so can't be recreated using the live service (e.g. https://github.com/PREreview/prereview.org/blob/883c91c75a2f76d7844b70ad4f42d6e362728a45/integration/publishing-a-prereview.spec.ts#L1202-L1218 sets up a HTTP request from the server which will time out). I know the full project is a bit much, but running `make test-integration` should see everything happen inside a container if it helps.

Is there any way of debugging WebKit to discover _why_ it crashes? I've seen Chromium crash previously, and I remember seeing a stack trace in the debug output helping me to see that was related to Playwright's patching. I'm struggling to work out how to produce a reduced test case at the moment...

**Comment by pavelfeldman** [comment]
@pinanks Thanks!

> I tried the canary release 1.34.0-alpha-may-8-2023 which solved my problem. @thewilkybarkid, you may wanna give this a try.

@thewilkybarkid could you give it a try as well?
