### ISSUE TITLE
[BUG] FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by flora8984461** [microsoft/playwright#22937]
### System info
- Playwright Version: "@playwright/experimental-ct-react17": "^1.33.0"
- Operating System: Windows 11
- Browser: All
- Other info: I am using [Experimental: components](https://playwright.dev/docs/test-components)

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/flora8984461/reproduce-jest-failure/tree/reproduce-playwright-out-of-memory

**Steps**
1. clone the repo, checkout branch: reproduce-playwright-out-of-memory, and run `yarn` and then `yarn test-ct`.

**Expected**

Run the test properly. 

Or provide any configs to allow the test run properly.

**Actual**
It crashes during bundle phase with the following error:

```
✓ 1505 modules transformed.

<--- Last few GCs --->

[8908:00000215E683B3A0]    61960 ms: Mark-sweep 4039.1 (4138.8) -> 4036.2 (4138.8) MB, 2008.2 / 0.0 ms  (average mu = 0.560, current mu = 0.050) allocation failure scavenge might not succeed
[8908:00000215E683B3A0]    65264 ms: Mark-sweep 4051.9 (4138.8) -> 4049.5 (4165.3) MB, 3295.0 / 0.0 ms  (average mu = 0.303, current mu = 0.003) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF614B10AAF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+124015
 2: 00007FF614A9C866 v8::internal::wasm::WasmCode::safepoint_table_offset+64182
 3: 00007FF614A9D8E2 v8::internal::wasm::WasmCode::safepoint_table_offset+68402
 4: 00007FF6153D1CE4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF6153BC2AD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF61525F88C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF61525C9A4 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF61525A320 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF61527EEA6 v8::internal::Factory::NewFillerObject+214
10: 00007FF614FB1645 v8::internal::DateCache::Weekday+1797
11: 00007FF61545F9C1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
12: 00000215E89B71FA
error Command failed with exit code 134.
```

**Notes**
There is some open issue in vite and fluentui:
- https://github.com/microsoft/fluentui/issues/25547
- https://github.com/microsoft/fluentui/issues/24952
- https://github.com/vitejs/vite/issues/2433

It happens when I add @fluentui/react-icons. After taking a look at the open issue, seems I can skip generating sourcemap for @fluentui/react-icons. I am not sure if there is an option to set playwright to do that when it bundles.

I am looking for any suggestions to workaround it. Your help is really appreciated 🙏

I notice there are some similar issues but they got closed without any solutions.

**Comment by peterkrieg** [comment]
In case it helps in the interim, I've changed the `test-ct` script to increase the memory allocation for node:  `NODE_OPTIONS=--max-old-space-size=8192 playwright test -c playwright-ct.config.ts`.  Our company project tests some large sections of UI with component tests, and we've had to bump the memory from the beginning.  

I'm curious if the playwright team has suggestions / guidance on "how much UI is too much to component test", or at what point a JS bundle passed around in node could be problematic for performance.  I'm guessing overall the component tests are pretty memory intensive given how the JS bundle is served from node => browser.  In our case, the main JS bundle is 8.8MB  (1.7MB gzipped).

**Comment by flora8984461** [comment]
NODE_OPTIONS=--max-old-space-size does not work well for me. I increased a few numbers but still got the same error. Then I tried a very large number and got:

```
vite v4.3.5 building for production...
✓ 1505 modules transformed.
[vite:build-import-analysis] Invalid string length
RangeError: Invalid string length

    at encode$1 (E:\projects\jest-react-testing-library-forked\node_modules\vite\dist\node\chunks\dep-934dbc7c.js:6213:27)
    at SourceMap (E:\projects\jest-react-testing-library-forked\node_modules\vite\dist\node\chunks\dep-934dbc7c.js:14950:19)
    at MagicString.generateMap (E:\projects\jest-react-testing-library-forked\node_modules\vite\dist\node\chunks\dep-934dbc7c.js:15266:10)
    at Object.renderChunk (E:\projects\jest-react-testing-library-forked\node_modules\vite\dist\node\chunks\dep-934dbc7c.js:45188:32)
    at E:\projects\jest-react-testing-library-forked\node_modules\rollup\dist\es\shared\node-entry.js:24551:40

  3 skipped
```

**Comment by pavelfeldman** [comment]
Works for me:

```sh
> playwright test -c playwright-ct.config.ts


Running 3 tests using 3 workers
  3 passed (4.1s)

To open last HTML report run:

  npx playwright show-report

pfeldman@pfeldman-mac2 reproduce-jest-failure % 
```

**Comment by flora8984461** [comment]
I am surprised it works for you. May I know your OS? Thank you! I increased a lot number for my NODE_OPTIONS, either getting out of heap error or Invalid string length 😢

<img width="1195" alt="image" src="https://github.com/microsoft/playwright/assets/39588094/c719c65f-f966-4f27-809b-52dacd0bb728">


> Works for me:
> 
> ```shell
> > playwright test -c playwright-ct.config.ts
> 
> 
> Running 3 tests using 3 workers
>   3 passed (4.1s)
> 
> To open last HTML report run:
> 
>   npx playwright show-report
> 
> pfeldman@pfeldman-mac2 reproduce-jest-failure % 
> ```

**Comment by flora8984461** [comment]
@pavelfeldman  I asked my teammate to try and he gets out of memo as well. We are on windows

**Comment by pavelfeldman** [comment]
I can keep it open to see if others comment on the issue. It works for me with the default options, no NODE_OPTIONS required.

**Comment by flora8984461** [comment]
A little more info to provide, I tried with my Mac mini (8g or 16g ram?) and gets out of memo still.

**Comment by liting-yes** [comment]
Same problem

env:
macOS: 13.4.1
playwright *: 1.35.1

**Comment by 1049451037** [comment]
Same problem for some specific websites. (But I don't know what website it is, because I'm crawling a lot of websites...)

**Comment by pavankumardmg** [comment]
same problem. 
#
# Fatal error in , line 0
# Fatal process out of memory: Zone
#
#
#
#FailureMessage Object: 0000009B3F3F6190
com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.

**Comment by gauravkhuraana** [comment]
Got the below error and we are using C# dot net with playwright and version 1.39 and this problem is failing the build everytime.

locally everything runs fine.. problem happen in agent 

#
# Fatal error in , line 0
# Fatal process out of memory: Zone
#
#
#
#FailureMessage Object: 00000067569F5790
 1: 00007FF7D28C194F 
 2: 00007FF7D27D6B2F 
 3: 00007FF7D3697142 
 4: 00007FF7D32DD393 
 5: 00007FF7D2E09190 
 6: 00007FF7D36CF9C0 
 7: 00007FF7D37834BA 
 8: 00007FF7D3787A55 
 9: 00007FF7D37F65FD 
10: 00007FF7D37F33BB 
11: 00007FF7D37F401F 
12: 00007FF7D37E114F 
13: 00007FF7D3745A27 
14: 00007FF7D374334C 
15: 00007FF7D373E47A 
16: 00007FF7D325F141 
17: 00007FF7D3232DC4 
18: 00007FF7D323366F 
19: 00007FF7D27D950D 
20: 00007FF7D290DC3D 
21: 00007FF7D3928890 
22: 00007FFADD174DE0 
23: 00007FFADDCDED9B

**Comment by rakeshnambiar** [comment]
I have been using playwright `1.39.0` along with pytest and python. Considering the NODE OPTIONS is out of scope in python, what are the alternatives?

**Comment by AlehYanushkevich** [comment]
The sampe problem for me. I played with different configurations and found, that it stops working correctly from version 1.40 of Playwright. In Task Explorer I see, that memory for Node JS process is growing constantly (such as CPU), and when process is taking a bit more than 4Gb, it aborted. Logs look like:
![image](https://github.com/microsoft/playwright/assets/152842273/293d3541-2421-4cbd-8978-8e621f0a28e6)

### Stacktrace:
![image](https://github.com/microsoft/playwright/assets/152842273/e568a4be-6f79-40ad-a754-2adfeff5212f)

### Env:
OS: Windows 11 / Debian 12.5
Browser: Chrome
Playwright: >= 1.40

**Comment by JoaoPDias** [comment]
![image](https://github.com/microsoft/playwright/assets/19819975/de525138-dbd6-4a90-bf3e-a5c14397dfc7)
I'm having the same issue on Pipeline and locally. 
In version 1.39, I don't have any issues
In version 1.40, I start to get this error
In my investigation, I suspect the main problem is related to a huge array generated with more than 32648 items. You can see the suspect in the video below
https://ingeniousbuild.rewatch.com/video/ejqrdp8bpwsnm4bp-joao-dias-s-screen-recording-09-04-2024

**Comment by AQuarton** [comment]
I am getting the same issue but only on the pipeline - locally is OK
Using version 1.43
Tests run ok for about 10 minutes then

2024-04-11T18:44:47.9316679Z  -> error: Timeout 20000ms exceeded.
2024-04-11T18:44:47.9317222Z  Call log:
2024-04-11T18:44:47.9317764Z    - navigating to "https://www.thepensionsregulator.gov.uk/", waiting until "load" (34.3s)
2024-04-11T19:39:45.8919986Z <--- Last few GCs --->
2024-04-11T19:39:45.8921513Z [13764:00000287D65FB190]  3121142 ms: Scavenge 13.6 (14.8) -> 12.8 (14.8) MB, 0.37 / 0.00 ms  (average mu = 0.999, current mu = 0.996) task; 
2024-04-11T19:39:45.8923745Z [13764:00000287D65FB190]  3180078 ms: Scavenge 13.6 (14.8) -> 12.8 (14.8) MB, 0.35 / 0.00 ms  (average mu = 0.999, current mu = 0.996) task; 
2024-04-11T19:39:45.8924656Z [13764:00000287D65FB190]  3238952 ms: Scavenge 13.6 (14.8) -> 12.8 (14.8) MB, 0.38 / 0.00 ms  (average mu = 0.999, current mu = 0.996) task; 
2024-04-11T19:39:45.8925185Z <--- JS stacktrace --->
2024-04-11T19:39:45.8926342Z FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
2024-04-11T19:39:45.8927257Z ----- Native stack trace -----

**Comment by cvacalares** [comment]
> ![image](https://private-user-images.githubusercontent.com/19819975/320964455-de525138-dbd6-4a90-bf3e-a5c14397dfc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTAyNTMsIm5iZiI6MTcyNTk4OTk1MywicGF0aCI6Ii8xOTgxOTk3NS8zMjA5NjQ0NTUtZGU1MjUxMzgtZGJkNi00YTkwLWJmM2UtYTVjMTQzOTdkZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE3MzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNmNhODVmYjUzMTFkNjdkYmQ0YjIwNGRhMzk1NmZkNmM4N2ZhYzY2OWVkNjUyMTIzZWZiMjVhNzA4OWM1OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qf_E0lnoX5YFtwnDzfSwsvANHV-qrDqsRfT0Jf1v66A) I'm having the same issue on Pipeline and locally. In version 1.39, I don't have any issues In version 1.40, I start to get this error In my investigation, I suspect the main problem is related to a huge array generated with more than 32648 items. You can see the suspect in the video below https://ingeniousbuild.rewatch.com/video/ejqrdp8bpwsnm4bp-joao-dias-s-screen-recording-09-04-2024

I was using 1.38.0 and upgraded to 1.46.0.
I suddenly getting the error message.
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF6BB7E0B6B node::SetCppgcReference+18123
 2: 00007FF6BB7524D8 DSA_meth_get_flags+92504
 3: 00007FF6BC1C9821 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF6BC1B2F78 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF6BC014A20 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF6BC011AA8 v8::Platform::SystemClockTimeMillis+647176
 7: 00007FF6BC026DBA v8::Platform::SystemClockTimeMillis+733978
 8: 00007FF6BC027637 v8::Platform::SystemClockTimeMillis+736151
 9: 00007FF6BC035F2F v8::Platform::SystemClockTimeMillis+795791
10: 00007FF6BBCF6615 v8::CodeEvent::GetFunctionName+116773
11: 00007FF6BC27B1AE v8::PropertyDescriptor::writable+678094
12: 00007FF6BC299988 v8::PropertyDescriptor::writable+802984

I went to 1.39.0. instead and I am not running into that issue anymore.

**Comment by JoaoPDias** [comment]
Hi, aiming to solve it, I removed all the ```.or``` method calls from my source code and replace for .locator("selector, otherSelector, etc"). No problems anymore

**Comment by k3zdev** [comment]
> I was using 1.38.0 and upgraded to 1.46.0. I suddenly getting the error message. <--- JS stacktrace --->
> 
> FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory ----- Native stack trace -----
> 
> 1: 00007FF6BB7E0B6B node::SetCppgcReference+18123 2: 00007FF6BB7524D8 DSA_meth_get_flags+92504 3: 00007FF6BC1C9821 v8::Isolate::ReportExternalAllocationLimitReached+65 4: 00007FF6BC1B2F78 v8::Function::Experimental_IsNopFunction+1336 5: 00007FF6BC014A20 v8::Platform::SystemClockTimeMillis+659328 6: 00007FF6BC011AA8 v8::Platform::SystemClockTimeMillis+647176 7: 00007FF6BC026DBA v8::Platform::SystemClockTimeMillis+733978 8: 00007FF6BC027637 v8::Platform::SystemClockTimeMillis+736151 9: 00007FF6BC035F2F v8::Platform::SystemClockTimeMillis+795791 10: 00007FF6BBCF6615 v8::CodeEvent::GetFunctionName+116773 11: 00007FF6BC27B1AE v8::PropertyDescriptor::writable+678094 12: 00007FF6BC299988 v8::PropertyDescriptor::writable+802984
> 
> I went to 1.39.0. instead and I am not running into that issue anymore.



Hi @JoaoPDias - is this still a known issue inside @playwright/test 1.47.2 ? Recently run into this issue only on pipeline.

**Comment by kristaps-aksjonovs** [comment]
Same issue reproducible in Gitlab CI using Docker image `mcr.microsoft.com/playwright:v1.44.1-jammy` with `--max-old-space-size=4096`

**Comment by FranciscoKnebel** [comment]
I'm having the same memory problem when running a big test that covers a lot of pages (10+ minutes, 100+ pages, health check smoke test) while using [Coverage APIs](https://playwright.dev/docs/api/class-coverage) and extending the test.

```typescript
extendedTest = test.extend({
  coverageFixture: [
    async ({ page }, use, testInfo) => {
      await Promise.all([
        page.coverage.startJSCoverage({
          resetOnNavigation: false,
        }),
        page.coverage.startCSSCoverage({
          resetOnNavigation: false,
        }),
      ]);

      await use('coverageFixture');

      const [jsCoverage, _cssCoverage] = await Promise.all([
        page.coverage.stopJSCoverage(),
        page.coverage.stopCSSCoverage(), // Fails here
      ]);

      const coverageList = [...jsCoverage, ...cssCoverage];
      await addCoverageReport(coverageList, testInfo);
    },
    {
      scope: 'test',
      auto: true,
    },
  ],
});
```

Test fails on command [page.coverage.stopCSSCoverage()](https://playwright.dev/docs/api/class-coverage#coverage-stop-css-coverage) with error `RangeError: Invalid string length`. I am running with `NODE_OPTIONS=--max-old-space-size=8192`, failing both locally and on CI.

**Comment by DetachHead** [comment]
> ![image](https://github.com/microsoft/playwright/assets/19819975/de525138-dbd6-4a90-bf3e-a5c14397dfc7) I'm having the same issue on Pipeline and locally. In version 1.39, I don't have any issues In version 1.40, I start to get this error In my investigation, I suspect the main problem is related to a huge array generated with more than 32648 items. You can see the suspect in the video below https://ingeniousbuild.rewatch.com/video/ejqrdp8bpwsnm4bp-joao-dias-s-screen-recording-09-04-2024

@JoaoPDias i believe i'm encountering the same issue and was able to create a repro. i raised a separate issue for this because this one seems to be full of various unrelated memory issues: #34059

**Comment by diiogocosta** [comment]
We hit this exact issue in a Next.js project with ~60 integration tests using [monocart-reporter](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) for V8 coverage. Memory grew to 4GB+ and crashed around test 28, even with [workers: 1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) and --max-old-space-size=8192.

Root cause
Looking at Playwright's source in crCoverage.ts, the JSCoverage class eagerly calls Debugger.getScriptSource for every script inside _onScriptParsed:

```ts
async _onScriptParsed(event) {
  this._scriptIds.add(event.scriptId);
  if (!event.url && !this._reportAnonymousScripts) return;
  // Fetches source for ALL scripts — webpack runtime, React, polyfills, etc.
  const response = await this._client._sendMayFail(
    'Debugger.getScriptSource',
    { scriptId: event.scriptId }
  );
  if (response)
    this._scriptSources.set(event.scriptId, response.scriptSource);
}
```

In a typical Next.js page, this means 30-60 scripts × 50KB-2MB each = 25-100MB of source text stored in memory per test. Across many tests, this accumulates to several GB because GC cannot reclaim fast enough between test runs.

Workaround: CDP Profiler API with selective getScriptSource
Instead of using page.coverage.startJSCoverage() / stopJSCoverage(), we interact with CDP directly. The key insight: filter scripts by URL before fetching source text, instead of fetching all source text and filtering after.

```ts
import { CDPSession, Page } from '@playwright/test';

async function startCoverage(page: Page, urlFilter: string) {
  const cdp = await page.context().newCDPSession(page);
  const scriptIndex = new Map<string, string>(); // scriptId → url

  // Only track scriptIds for scripts we care about
  cdp.on('Debugger.scriptParsed', (params) => {
    if (params.url.includes(urlFilter)) {
      scriptIndex.set(params.scriptId, params.url);
    }
  });

  await cdp.send('Debugger.enable');
  await cdp.send('Profiler.enable');
  await cdp.send('Profiler.startPreciseCoverage', {
    callCount: true,
    detailed: true,
  });

  return async () => {
    // 1. Get coverage ranges for ALL scripts (cheap — no source text)
    const { result } = await cdp.send('Profiler.takePreciseCoverage');
    await cdp.send('Profiler.stopPreciseCoverage');

    // 2. Filter BEFORE fetching source (the key optimization)
    const relevant = result.filter((e) => e.url.includes(urlFilter));

    // 3. Fetch source ONLY for matching scripts (~2-5 instead of ~50)
    for (const entry of relevant) {
      const scriptId = [...scriptIndex.entries()]
        .find(([, url]) => url === entry.url)?.[0];
      if (scriptId) {
        try {
          const { scriptSource } = await cdp.send(
            'Debugger.getScriptSource', { scriptId }
          );
          (entry as any).source = scriptSource;
        } catch { /* script may have been GC'd */ }
      }
    }

    await cdp.send('Debugger.disable');
    await cdp.send('Profiler.disable');
    await cdp.detach();
    scriptIndex.clear();

    return relevant; // Compatible with V8 coverage format
  };
}

// Usage in a Playwright fixture:
const stopCoverage = await startCoverage(page, 'chunks/pages');
// ... run test ...
const coverage = await stopCoverage();
await addCoverageReport(coverage, test.info()); // works with monocart-reporter
```
Coverage quality is identical because most projects already filter entries in their reporter config (e.g., entryFilter in monocart). We simply apply the same filter before allocating memory rather than after.

Suggested improvement for Playwright
The startJSCoverage API could accept an optional urlFilter parameter to avoid eagerly fetching source for irrelevant scripts:

```ts
// Proposed API change
await page.coverage.startJSCoverage({
  resetOnNavigation: false,
  urlFilter: (url) => url.includes('chunks/pages'), // NEW: skip getScriptSource for non-matching URLs
});
```

This would be a backward-compatible change — when urlFilter is not provided, behavior stays as-is. When provided, _onScriptParsed would skip the getScriptSource call for non-matching URLs.
