### ISSUE TITLE
[BUG] Cannot connect to remote selenium grid 4

### ISSUE THREAD

**Issue by neswine** [microsoft/playwright#23394]
### **What happened?**

I am trying to connect the grid setup in my cloud. I am able to create the session but for some reason, I cant run the tests.
Seems like websocket connection is getting timed out.

I tried to setup in my mac M1 using docker and the tests run fine.

### **Command used to start Selenium Grid with Docker**

SELENIUM_REMOTE_URL=<REMOTE_URL> npx playwright test

### **Relevant log output**

`
browserType.launch: WebSocket error: connect ETIMEDOUT 100.98.0.2:4444
    =========================== logs ===========================
    <selenium> connecting to https://selenium-grid-hub.shopk8sd.int.aws.zooplus.io/
    <selenium> connected to sessionId=f539a10634af5631464e697ce97a4b64
    <selenium> using selenium v4
    <selenium> retrieved endpoint ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp for sessionId=f539a10634af5631464e697ce97a4b64
    <ws connecting> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp
    <ws error> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp error connect ETIMEDOUT 100.98.0.2:4444
    <ws connect error> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp connect ETIMEDOUT 100.98.0.2:4444
    <ws disconnected> ws://100.98.0.2:4444/session/f539a10634af5631464e697ce97a4b64/se/cdp code=1006 reason=
    <selenium> disconnecting from sessionId=f539a10634af5631464e697ce97a4b64
    <selenium> disconnected from sessionId=f539a10634af5631464e697ce97a4b64
`

### **Operating System**
Ubuntu

### **Docker Selenium version (tag)**
4.6.0

**Comment by emouawad** [comment]
Same here

**Comment by adamsjoe** [comment]
@neswine Also interested in any possible solution

**Comment by zhangjunqiang** [comment]
are you using docker-compose deploy selenium grid? the docker-compose return a path your pw cannot connect to

**Comment by Gr1LyA** [comment]
same problem. connected to session but got ws error

**Comment by gc1423** [comment]
same problem ...

**Comment by ManjunathPrabhakar** [comment]
+1 With same problem. 
Followed exactly as it is. https://playwright.dev/docs/next/selenium-grid#hub-and-nodes-mode
To Run HUB : `docker run -d -p 4442-4444:4442-4444 --name selenium-hub-pw selenium/hub:latest`
To Add GRID : `docker run -d --name pw-chromium2 -p 5554:5554 --shm-size="2g" -e SE_EVENT_BUS_HOST=1XX.1X.X.X -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e SE_NODE_GRID_URL="http://1XX.1X.X.X:4444"  selenium/node-chromium:latest`
Then, i can see one node in the hub URL. Below is Test Code i'm executing:

```
import com.microsoft.playwright.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import java.nio.file.Paths;`

public class TestPWD {

    @DisplayName("Demo Test for Docker")
    @Test
    public void demoTest() {

        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
            BrowserContext browserContext = browser.newContext();
            Page page = browserContext.pages().isEmpty() ? browserContext.newPage() : browserContext.pages().get(0);
            page.navigate("http://playwright.dev");
            page.screenshot(new Page.ScreenshotOptions()
                    .setPath(Paths.get("screenshot.png"))
                    .setFullPage(true));
            System.out.println(page.title());
            Thread.sleep(30000); //Just for sake of verifying the Live Session in GRID
            page.close();
            browser.close();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
```

Executed with **SELENIUM_REMOTE_URL=http://localhost:4444** environment variable like below
<img width="739" alt="Image" src="https://github.com/user-attachments/assets/16c95a09-8e10-45e9-bd5b-2c7e568cc310" />

It Opens up like below: 
<img width="650" alt="Image" src="https://github.com/user-attachments/assets/fa987738-8630-4b88-ae0f-3b03e2b5d7a5" />

```
[ERROR] Errors: 
[ERROR]   TestPWD.demoTest:39 Runtime com.microsoft.playwright.PlaywrightException: Error {
  message='WebSocket error: connect ETIMEDOUT 1XX.1X.X.X:4444
=========================== logs ===========================
<selenium> connecting to http://localhost:4444/wd/hub/
<selenium> connected to sessionId=d1760cd434bf314f7fe75a22127f5066
<selenium> using selenium v4
<selenium> retrieved endpoint ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp for sessionId=d1760cd434bf314f7fe75a22127f5066
<ws connecting> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp
<ws error> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp error connect ETIMEDOUT 1XX.1X.X.X:4444
<ws connect error> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp connect ETIMEDOUT 1XX.1X.X.X:4444
<ws disconnected> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp code=1006 reason=
<selenium> disconnecting from sessionId=d1760cd434bf314f7fe75a22127f5066
<selenium> disconnected from sessionId=d1760cd434bf314f7fe75a22127f5066
============================================================
  name='Error
  stack='Error: WebSocket error: connect ETIMEDOUT 1XX.1X.X.X:4444
=========================== logs ===========================
<selenium> connecting to http://localhost:4444/wd/hub/
<selenium> connected to sessionId=d1760cd434bf314f7fe75a22127f5066
<selenium> using selenium v4
<selenium> retrieved endpoint ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp for sessionId=d1760cd434bf314f7fe75a22127f5066
<ws connecting> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp
<ws error> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp error connect ETIMEDOUT 1XX.1X.X.X:4444
<ws connect error> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp connect ETIMEDOUT 1XX.1X.X.X:4444
<ws disconnected> ws://1XX.1X.X.X:4444/session/d1760cd434bf314f7fe75a22127f5066/se/cdp code=1006 reason=
<selenium> disconnecting from sessionId=d1760cd434bf314f7fe75a22127f5066
<selenium> disconnected from sessionId=d1760cd434bf314f7fe75a22127f5066
============================================================
    at i.<anonymous> (C:\Users\USERNAME\AppData\Local\Temp\playwright-java-16132376824233600982\package\lib\server\transport.js:61:16)
    at i.emit (node:events:526:35)
    at of (C:\Users\USERNAME\AppData\Local\Temp\playwright-java-16132376824233600982\package\lib\utilsBundleImpl\index.js:35:36209)
    at ClientRequest.<anonymous> (C:\Users\USERNAME\AppData\Local\Temp\playwright-java-16132376824233600982\package\lib\utilsBundleImpl\index.js:35:34663)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
}
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
