### ISSUE TITLE
[Question] Chromium Error

### ISSUE THREAD

**Issue by mconnol6** [microsoft/playwright#2342]
I'm encountering this issue when I run my tests ....

UI Tests with Playwright › Should load page

Protocol error (Target.setAutoAttach): Target closed.

      at node_modules/playwright-core/lib/chromium/crConnection.js:130:63
      at CRSession.send (node_modules/playwright-core/lib/chromium/crConnection.js:129:16)
      at CRSession.<anonymous> (node_modules/playwright-core/lib/helper.js:64:31)
      at Function.connect (node_modules/playwright-core/lib/chromium/crBrowser.js:62:27)
      at Chromium.launch (node_modules/playwright-core/lib/server/chromium.js:45:53)

I am on a Windows machine and using Bash on Ubuntu on Windows to run.

Can anyone help?

**Comment by mconnol6** [comment]
Nevermind, I was able to fix the issue by installing all dependencies through the VSCode command line instead of Bash on Windows. There must have been an issue with how packages are installed with Bash on Windows. Closing this issue. :)
