### ISSUE TITLE
[BUG] HTML elements with >> break Playwright

### ISSUE THREAD

**Issue by mkawumba** [microsoft/playwright#23540]
### System info
- Playwright Version: [v1.32]
- Operating System: [Windows 11, macOS 13.2]
- Browser: [All]

**Config file**

```js
// playwright.config.ts
import { PlaywrightTestConfig, devices } from '@playwright/test';
import { join } from 'path';
import { isCI } from './utils';
const CI = isCI();

// Use process.env.PORT by default and fallback to port 3000
const PORT = process.env.PORT || 3000;

// Set webServer.url and use.baseURL with the location of the WebServer respecting the correct set port
const baseURL = `http://localhost:${PORT}`;

// Reference: https://playwright.dev/docs/test-configuration
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  timeout: 30 * 1000,
  testDir: join(__dirname, 'tests'),
  forbidOnly: CI,
  retries: 1,
  workers: 1,
  outputDir: 'e2e-results/',
  reporter: [['list'], ['junit', { outputFile: './e2e-results/results.xml' }]],

  use: {
    baseURL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure'
  },

  projects: [
    {
      name: 'API',
      testDir: 'tests/api',
    },
    {
      name: 'Desktop Chrome',
      testDir: 'tests/ui',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'Desktop Safari',
      testDir: 'tests/ui',
      use: {
        ...devices['Desktop Safari'],
      },
    },
    // Test against mobile viewports.
    {
      name: 'Mobile Chrome',
      testDir: 'tests/ui',
      use: {
        ...devices['Pixel 5'],
      },
    },
    {
      name: 'Mobile Safari iPad',
      testDir: 'tests/ui',
      use: devices['iPad (gen 6)'],
    },
    {
      name: 'Mobile Safari iPhone',
      testDir: 'tests/ui',
      use: devices['iPhone 13'],
    },
  ],
};
export default config;

```

**Test file (self-contained)**

```js
```

**Steps**
- Run any test on the page with >> attributes

**Expected**

The HTML elements with any form of >> should works fine with Playwright including:
```js
&gt;&#x200B;&gt;
&gt;&gt; 
```
**Actual**

Any HTML elements with >> break the Playwright parser and make many elements on the page not accessible (not only the ones with >> attributes) Pick locator also does not recognize those elements.
Does not work:
```js
&gt;&#x200B;&gt;
&gt;&gt; 
```
Works fine:
 ```js
&gt; &gt;  (space between) 
&gt;&nbsp;&gt; 
```

**Comment by aslushnikov** [comment]
@mkawumba I tried the following and failed to reproduce.

The following passes for me:

```ts
// a.spec.ts
import { test, expect } from "@playwright/test";

test("Error", async ({ page }) => {
  await page.setContent(`
    &gt;&#x200B;&gt;
    &gt;&gt;
  `);
  await expect(page.locator('html >> body')).toBeVisible();
});
```

Could you please try this as well and see if it works for you? If it works, can you come up with a similar test case that reproduces the issue?

**Comment by mkawumba** [comment]
@aslushnikov
Thanks, I will check it on my side and will back to you.  >> broke only some elements on the page, most of them were still accessible for Playwright, for some of the I's getting an error:
![MicrosoftTeams-image](https://github.com/microsoft/playwright/assets/119596135/96a90f39-dca1-4556-9b3d-05b9639d8292)

**Comment by mkawumba** [comment]
@aslushnikov 
I couldn't reproduce that by setting the page.content in the test body, however, editing the HTML does the job. Please have a look at the attached gif. 
![pw_attr_issue](https://github.com/microsoft/playwright/assets/119596135/34bddbcc-fbb9-47d4-ae6d-9bf6eee715b5)

**Comment by ruifigueira** [comment]
I tried it myself, and also got the following error. It happens in the injected code when inspecting an element with those characters:

```
VM6:1175 Uncaught Error: Unexpected token "$" while parsing selector "break Playwright #23540 mkawumba opened this is$/"
    at unexpected (<anonymous>:1175:12)
    at consumeSimpleSelector (<anonymous>:1296:15)
    at consumeComplexSelector (<anonymous>:1243:56)
    at consumeArgument (<anonymous>:1225:12)
    at consumeFunctionArguments (<anonymous>:1209:22)
    at parseCSS (<anonymous>:1309:18)
    at <anonymous>:1327:25
    at Array.map (<anonymous>)
    at parseSelector (<anonymous>:1323:30)
    at InjectedScript.parseSelector (<anonymous>:4511:20)
```

**Comment by ruifigueira** [comment]
I find out why is can't we test this problem:

```ts
import { test, expect } from "@playwright/test";

test('Error', async ({ page }) => {
  await page.setContent(`<span>Test &gt;&#x200B;&gt; 123</span>`);
  expect.soft(await page.locator('span').innerHTML()).toBe('Test &gt;&#x200B;&gt; 123');
});
```

and I get:

```
Error: expect(received).toBe(expected) // Object.is equality


Expected: "Test &gt;&#x200B;&gt; 123"
Received: "Test &gt;​&gt; 123"
    at tests\a.spec.ts:5:50
```

So, injecting HTML seems to discard that character.

**Comment by ruifigueira** [comment]
Running in chrome console on a `about:blank` tab:

```js
document.body.innerHTML = `<span>Test &gt;&#x200B;&gt; 123</span>`
// prints '<span>Test &gt;&#x200B;&gt; 123</span>'
document.body.innerHTML
// prints '<span>Test &gt;​&gt; 123</span>'
document.body.innerHTML.includes('&#x200B;');
// prints false
(document.body.innerHTML = `<span>Test &gt;&#x200B;&gt; 123</span>`).includes('&#x200B;');
// prints true
document.body.innerHTML.includes('&#x200B;');
// prints false
```

**Comment by aslushnikov** [comment]
@ruifigueira in js, the zero-width space is the `\u200b`. The following test works for me:

```ts
import { test, expect } from "@playwright/test";

test('Error', async ({ page }) => {
  await page.setContent(`<span>Test &gt;&#x200B;&gt; 123</span>`);
  expect(await page.locator('span').innerHTML()).toBe('Test &gt;\u200b&gt; 123');
});
```

> I couldn't reproduce that by setting the page.content in the test body, however, editing the HTML does the job. Please have a look at the attached gif.

@mkawumba I can see the GIF, but I can't reproduce it locally. Would you mind to write down a step-by-step instruction that I can follow to see the error?

**Comment by ruifigueira** [comment]
@aslushnikov you are right, and I think the problem is not related to zero-with space, but with `>>`.

Here is a test that fails:

```ts
import { test, expect } from "@playwright/test";

test('Error', async ({ page }) => {
  await page.setContent('<span>[BUG] HTML elements with &gt;&gt; break Playwright</span>');

  // this one works
  await expect(page.getByText(/Playwright$/)).toHaveText('[BUG] HTML elements with >> break Playwright');
  
  // this one fails:  Unexpected token "$" while parsing selector "break Playwright$/"
  await expect(page.getByText(/HTML elements with >> break Playwright$/)).toHaveText('[BUG] HTML elements with >> break Playwright');
});
```

I was able to track down the problem back to `parseSelector`. Here's a test for it, just place it under `tests/library/selector-parser.spec.ts`:

```ts
import { playwrightTest as it, expect } from '../config/browserTest';
import type { ParsedSelector } from '../../packages/playwright-core/src/utils/isomorphic/selectorParser';
import { parseSelector } from '../../packages/playwright-core/lib/utils/isomorphic/selectorParser';

function parse(selector: string) {
  return (parseSelector(selector) as ParsedSelector).parts.map(({ name, source }) => ({ name, source }));
}

it('should parse selector', async () => {
  // works
  expect(parse(`internal:has-text=/Playwright$/`)).toStrictEqual([
    { name: 'internal:has-text', source: '/Playwright$/' },
  ]);
  // fails with Unexpected token "$" while parsing selector "break Playwright$/"
  expect(parse(`internal:has-text=/HTML elements with >> break Playwright$/`)).toStrictEqual([
    { name: 'internal:has-text', source: '/HTML elements with >> break Playwright$/' },
  ]);
});
```

**Comment by ruifigueira** [comment]
I was naive and though it had an easy fix, but I was wrong...

**Comment by aslushnikov** [comment]
Thanks, I can repro indeed with the following simplified test:

```ts
import { test, expect } from "@playwright/test";

test('Error', async ({ page }) => {
  await page.setContent(`<div>foo &gt;&gt; bar</div>`);
  console.log('locator 1:', await page.locator('div').textContent());
  console.log('locator 2:', await page.getByText(/foo >> bar/).textContent());
});
```

Running this yields the following error:

```
aslushnikov:~/tmp$ npx playwright test

Running 1 test using 1 worker

  ✘  1 a.spec.ts:3:5 › Error (241ms)
locator 1: foo >> bar


  1) a.spec.ts:3:5 › Error ─────────────────────────────────────────────────────────────────────────

    Error: locator.textContent: Unexpected token "/" while parsing selector "bar/"

      4 |   await page.setContent(`<div>foo &gt;&gt; bar</div>`);
      5 |   console.log('locator 1:', await page.locator('div').textContent());
    > 6 |   console.log('locator 2:', await page.getByText(/foo >> bar/).textContent());
        |                                                                ^
      7 | });
      8 |

        at /Users/andreylushnikov/tmp/a.spec.ts:6:64

  1 failed
    a.spec.ts:3:5 › Error ────────
```

**Comment by fs-innonova** [comment]
Hi there I just noticed the same while testing some svg that contains `&nbsp;` and I could also reproduce it on a simple test case, I think is the same issue of this thread.

```
  test('Error', async ({ page }) => {
    await page.setContent(`<span>new&nbsp;text</span>`);
    const textContent = await page.locator('span').textContent();
    expect(textContent).toContain('new text');
  });
```

<img width="540" alt="image" src="https://github.com/microsoft/playwright/assets/93779923/ac24cab8-80ea-483c-8501-34ab68ef4d05">

**Comment by dgozman** [comment]
@fs-innonova You have a different issue. I'd recommend using [`toHaveText()`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text) instead - it will automatically normalize whitespace characters:

```js
await expect(page.locator('span')).toHaveText('new text');
```
