### ISSUE TITLE
[BUG] Browsers do not dowload

### ISSUE THREAD

**Issue by simon-greatrix** [microsoft/playwright#23569]
I am unable to install Playwright. This is what happens:

```
12:25:15 tmp % mkdir playwright
12:25:21 tmp % cd playwright
12:25:22 playwright % uname -a
Darwin IM00276.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

12:25:24 playwright % npm doctor
Check                               Value   Recommendation/Notes
npm ping                            ok
npm -v                              ok      current: v9.6.7, latest: v9.6.7
node -v                             ok      current: v18.16.0, recommended: v18.16.0
npm config get registry             ok      using default registry (https://registry.npmjs.org/)
git executable in PATH              ok      /usr/local/bin/git
global bin folder in PATH           ok      /Users/.../.nvm/versions/node/v18.16.0/bin
Perms check on cached files         ok
Perms check on local node_modules   ok
Perms check on global node_modules  ok
Perms check on local bin folder     ok
Perms check on global bin folder    ok
Verify cache contents               ok      verified 6 tarballs

12:25:32 playwright % npm list -g
/Users/.../.nvm/versions/node/v18.16.0/lib
├── corepack@0.17.0
└── npm@9.6.7

12:25:35 playwright % npm list
/Users/.../tmp/playwright
└── (empty)

12:25:40 playwright % npm install playwright
npm ERR! code 1
npm ERR! path /Users/.../tmp/playwright/node_modules/playwright
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Removing unused browser at /Users/.../Library/Caches/ms-playwright/chromium-1064
npm ERR! Downloading Chromium 114.0.5735.35 (playwright build v1064) from https://playwright.azureedge.net/builds/chromium/1064/chromium-mac.zip
npm ERR! |                                                                                |   0% of 129.1 Mb
npm ERR! |■■■■■■■■                                                                        |  10% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■                                                                |  20% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 129.1 Mb
npm ERR! |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 129.1 Mb
npm ERR! /Users/.../tmp/playwright/node_modules/playwright-core/lib/server/registry/index.js:651
npm ERR!       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
npm ERR!             ^
npm ERR!
npm ERR! Error: Failed to download Chromium 114.0.5735.35 (playwright build v1064), caused by
npm ERR! Error: end of central directory record signature not found
npm ERR!     at /Users/.../tmp/playwright/node_modules/playwright-core/lib/zipBundleImpl.js:1:24033
npm ERR!     at /Users/.../tmp/playwright/node_modules/playwright-core/lib/zipBundleImpl.js:1:31712
npm ERR!     at /Users/.../tmp/playwright/node_modules/playwright-core/lib/zipBundleImpl.js:1:17288
npm ERR!     at FSReqCallback.wrapper [as oncomplete] (node:fs:682:5)
npm ERR!     at /Users/.../tmp/playwright/node_modules/playwright-core/lib/server/registry/index.js:651:13
npm ERR!     at async Registry._downloadExecutable (/Users/.../tmp/playwright/node_modules/playwright-core/lib/server/registry/index.js:650:5)
npm ERR!     at async Registry.install (/Users/.../tmp/playwright/node_modules/playwright-core/lib/server/registry/index.js:614:9)
npm ERR!     at async installBrowsersForNpmInstall (/Users/...tmp/playwright/node_modules/playwright-core/lib/server/registry/index.js:790:3)
npm ERR!
npm ERR! Node.js v18.16.0
```

**Expected**

The browsers should download and install.

**Actual**

The downloaded file is truncated and so the zip file is missing the central directory record.

All browsers are affected. 

The issue repeats every time.

I can download the ZIP files manually without problem.

Running the 'oopDownloadMain.js' file directly produces the same failure.

**Comment by aslushnikov** [comment]
@simon-greatrix this looks like an outage of the CDN in your area. Could you please try running installation again? 

Also, if you can tell me where are you physically located, I can try VPN to that location to reproduce the issue locally.

**Comment by simon-greatrix** [comment]
I am in the UK, in the county of Suffolk. I think you may be right about it being a CDN issue as I discovered yesterday that Cypress also won't install due to a truncated download - the CDN would be a common factor. But so would my machine so maybe something odd on my machine? Also, I can get the full download via a browser wouldn't that hit the same CDN?

Anyway, tried again just now and it failed in the same way.

**Comment by simon-greatrix** [comment]
I note that others have commented on https://github.com/microsoft/playwright/issues/20863 after it was closed with similar issues recently.

**Comment by aslushnikov** [comment]
@simon-greatrix do you have any corporate proxy installed on your machine maybe?

**Comment by simon-greatrix** [comment]
Nope. Also it works on my colleagues' machines.

**Comment by rajivmothilal** [comment]
Hi @aslushnikov we are experiencing the same issue on out CI/CD pipeline since this morning. was working fine for that past few days. We are behind a corporate proxy but this worked fine on the same version for a while. We have our pipeline on AWS servers in eu-central-1 Frankfurt. Any assistance would be greatly appreciated

**Comment by Spielboerg** [comment]
I have the same problem. I do not use a proxy and I am located near Frankfurt. I can't even download the file via the browser as mentioned in #20863 as a workaround.

**Comment by H--o-l** [comment]
Same error here on CI since this morning,

**Comment by mxschmitt** [comment]
@simon-greatrix, @DaveBitter and for future folks who run into it, please try the following which would help us to get more debug logs out of it:

1. Get or [Canary version](https://playwright.dev/docs/canary-releases) via `npm install -D @playwright/test@next`
2. Download browsers there like that with debug logs turned on: `DEBUG=pw:install npx playwright install`

And provide us the output, thanks!

**Comment by aslushnikov** [comment]
All: We added some mitigations that are available in `@playwright/test@next` (which is 1.36-alpha); closing this as per https://github.com/microsoft/playwright/issues/23569#issuecomment-1591350874

Feel free to file new issues if you still experience this, following @mxschmitt's directions.

**Comment by simon-greatrix** [comment]
As this issue is closed without curing the problem, I have opened https://github.com/microsoft/playwright/issues/23729 to continue the investigation.
