### ISSUE TITLE
[BUG] Unable to open browser on Ubuntu 22 server

### ISSUE THREAD

**Issue by kologser** [microsoft/playwright#23633]
### System info
- Playwright Version: [v1.34.0]
- Operating System: [Ubuntu 22]
- Browser: [Chromium]
- Other info: Python 3.10 in use. I've no root access.

### Source code

This is the Python source code which I want to execute on the server:

    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()

**[Describe expected behavior]**

The server should open the headless chromium browser and print the title.

**[Describe actual behavior]**

I get the following error:

```
ssh-yyyy@yyyy:/www/htdocs/yyyy/project/test$ python3 test4.py
Traceback (most recent call last):
  File "/www/htdocs/yyyy/project/test/test4.py", line 4, in <module>
    browser = p.chromium.launch()
  File "/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 14723, in launch
    self._sync(
  File "/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
  File "/.local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /.cache/ms-playwright/chromium-1064/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-5nAUS5 --remote-debugging-pipe --no-startup-window
<launched> pid=3164402
[pid=3164402][err] /.cache/ms-playwright/chromium-1064/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
[pid=3164402] <process did exit: exitCode=127, signal=null>
[pid=3164402] starting temporary directories cleanup
=========================== logs ===========================
<launching> /.cache/ms-playwright/chromium-1064/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-5nAUS5 --remote-debugging-pipe --no-startup-window
<launched> pid=3164402
[pid=3164402][err] /.cache/ms-playwright/chromium-1064/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
[pid=3164402] <process did exit: exitCode=127, signal=null>
[pid=3164402] starting temporary directories cleanup
============================================================
```

**Comment by mxschmitt** [comment]
Looks like not all Browser dependencies are installed. Did you run `python -m playwright install --with-deps` before?

**Comment by aslushnikov** [comment]
@kologser indeed, looks like a missing dependency. Please follow @mxschmitt's advice to install all the required deps!
