### ISSUE TITLE
[BUG] ScrollIntoViewIfNeededAsync does not wait for element to be attached to the DOM

### ISSUE THREAD

**Issue by ManuelEversmeyer** [microsoft/playwright#23758]
### System info
- Playwright Version: [v1.35]
- Operating System: Windows 10
- Browser: Chromium

### Source code

**First approach**

```c#
   private async static Task Prepare(this ILocator locator)
   {
      await locator.ScrollIntoViewIfNeededAsync();
   }
```

**Second approach**

```c#
   private async static Task Prepare(this ILocator locator)
   {
      await locator.WaitForAsync(new() { State = WaitForSelectorState.Attached });

      await locator.WaitForAsync(new() { State = WaitForSelectorState.Visible });

      await locator.ScrollIntoViewIfNeededAsync(new LocatorScrollIntoViewIfNeededOptions() { Timeout = 30000 });
   }
```

**Expected**

The method ScrollIntoViewIfNeededAsync always waits for actionability checks as long as the timeout is not reached.

**Actual**

Sometimes the method ScrollIntoViewIfNeededAsync throws an _Microsoft.Playwright.PlaywrightException : Element is not attached to the DOM_ with the logs and stacktrace below. It seems to behave differently depending on the locator, but maybe its just because the element of the working locator is attached to the DOM earlier.

**locator that seems to throw the exception always**

Page.GetByRole(AriaRole.Combobox).Nth(1)

**locator that seems to not throw the exception**

Page.Locator("dx-select-box").GetByRole(AriaRole.Combobox)

**Logs**

  waiting for element to be  and stable
  element is  and stable

**Stacktrace (relevant part)**

     at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 213
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.Locator.<>c__DisplayClass73_0.<<WithElementAsync>b__0>d.MoveNext() in /_/src/Playwright/Core/Locator.cs:line 405
--- End of stack trace from previous location ---
   at Microsoft.Playwright.Core.Locator.<>c__DisplayClass72_0`1.<<WithElementAsync>b__0>d.MoveNext() in /_/src/Playwright/Core/Locator.cs:line 391
--- End of stack trace from previous location ---
   at Microsoft.Playwright.Core.Locator.<>c__DisplayClass72_0`1.<<WithElementAsync>b__0>d.MoveNext() in /_/src/Playwright/Core/Locator.cs:line 395
--- End of stack trace from previous location ---
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 513
   at Microsoft.Playwright.Core.Locator.WithElementAsync(Func`3 callback, Nullable`1 timeout) in /_/src/Playwright/Core/Locator.cs:line 402
   at UI.FunctionalTests.Administration.Steptypes.Form.Prepare(ILocator locator) in C:\DevOps\ELAM\Cloud\src\Frontend\Ui.FunctionalTests\Administration\Steptypes\StandardForm.cs:line 196

**Comment by yury-s** [comment]
Apparently the element gets detached from DOM after it's visibility check has passed.  If you think there is a bug in Playwright please file a new issue with a self-cotained repro that we could run locally.

**Comment by ManuelEversmeyer** [comment]
Unfortunately, it's not that easy to provide a self-cotained repro that you can run locally since the website we're trying to test isn't public. But to check your guess I changed the code as follows.

```c#
   private async static Task Prepare(this ILocator locator)
   {
      await locator.WaitForAsync(new() { State = WaitForSelectorState.Attached });

      await locator.WaitForAsync(new() { State = WaitForSelectorState.Visible });

      var isAttached = true;

      while (isAttached)
      {
         isAttached = await locator.EvaluateAsync<bool>(
            @"(element) => {
               return element.isConnected;
            }"
         );
      }

      await locator.ScrollIntoViewIfNeededAsync();
   }
```

When I run the test, I can see that the loop is not left. So the element does not get detached from DOM after it's visibility check has passed. So there shouldn't be a reason why the method ScrollIntoViewIfNeededAsync is throwing this exception, or am I missing something?
