### ISSUE TITLE
[Feature] Support Tuxedo OS

### ISSUE THREAD

**Issue by SaimonL** [microsoft/playwright#24013]
Hi I use Tuxedo OS (Ubuntu 22.04 spin off). This operating system is shipped with all Tuxedo Linux computers. When I try to install playwright I get this error "BEWARE: your OS is not officially supported by Playwright". Can you modify the script to see Tuxedo OS as Ubuntu or Kubuntu Linux then check the name of the package. By the way Tuxedo uses Kernal 6.3 

Thanks

Full Error Trace

```
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                          
Hit:3 https://deb.nodesource.com/node_18.x jammy InRelease                                                                                                             
Hit:4 https://www.synaptics.com/sites/default/files/Ubuntu stable InRelease                                                                                            
Hit:5 https://ppa.launchpadcontent.net/agornostal/ulauncher/ubuntu jammy InRelease                                                                                     
Hit:6 https://ppa.launchpadcontent.net/redislabs/redis/ubuntu jammy InRelease                                                                                          
Hit:7 https://plasma.tuxedocomputers.com jammy InRelease                                                                                                               
Hit:8 https://txos.tuxedocomputers.com/ubuntu jammy InRelease                                                   
Hit:9 https://deb.tuxedocomputers.com/ubuntu jammy InRelease                              
Get:10 https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Hit:11 https://txos-extra.tuxedocomputers.com/ubuntu jammy InRelease
Hit:12 https://mirrors.tuxedocomputers.com/ubuntu/mirror/security.ubuntu.com/ubuntu jammy-security InRelease
Hit:13 https://mirrors.tuxedocomputers.com/ubuntu/mirror/archive.ubuntu.com/ubuntu jammy-updates InRelease
Fetched 270 kB in 2s (124 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

E: Package 'ttf-unifont' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libx264-155
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
E: Unable to locate package libvpx6
E: Unable to locate package libwebp6
Failed to install browsers
Error: Installation process exited with code: 100
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn playwright install --with-deps
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at executeCommands (/home/slovell/.config/yarn/global/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/home/slovell/.config/yarn/global/node_modules/create-playwright/lib/index.js:4679:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/slovell/.config/yarn/global/node_modules/create-playwright/lib/index.js:4950:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 23542,
  stdout: null,
  stderr: null
}
error Command failed.
Exit code: 1
```

**Comment by aslushnikov** [comment]
@SaimonL a best-effort workaround has been landed on tip-of-tree, so you should be able to install using `@playwright/test@next`.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by mikob** [comment]
Same issue with Linux Mint 21.1, even with the tip of the tree. 
```
$ NODE_OPTIONS='--max_old_space_size=16000 --max_old_space_size=16000' pnpm dlx create-playwright@next                [6:49:28 PM]
.../share/pnpm/store/v3/tmp/dlx-21401    |   +1 +
.../share/pnpm/store/v3/tmp/dlx-21401    | Progress: resolved 1, reused 0, downloaded 0, added 0
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'                      .../share/pnpm/store/v3/tmp/dlx-21401    | Progress: resolved 1, reused 1, downloa
ded 0, added 1, done TypeScript or JavaScript? …
✔ Do you want to use TypeScript or JavaScript? · TypeScript
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (Y/n) · true
✔ Add common examples which demonstrate Playwright's capabilities? (Y/n) · true
✔ Install Playwright operating system dependencies (requires sudo / root - can be done manually via sudo npx playwright install-dep
s')? (Y/n) · true

Installing Playwright Test (npm install --save-dev @playwright/test)…
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! code ERESOLVE
npm ERR! Invalid string length

npm ERR! A complete log of this run can be found in: /home/mikob/.npm/_logs/2023-07-15T00_50_13_641Z-debug-0.log
Error: Command failed: npm install --save-dev @playwright/test
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at executeCommands (/home/mikob/.local/share/pnpm/store/v3/tmp/dlx-21401/node_modules/.pnpm/create-playwright@1.18.0-alpha-1638
379596000/node_modules/create-playwright/lib/index.js:1:80316)
    at Generator.run (/home/mikob/.local/share/pnpm/store/v3/tmp/dlx-21401/node_modules/.pnpm/create-playwright@1.18.0-alpha-163837
9596000/node_modules/create-playwright/lib/index.js:1:81675)
    at async /home/mikob/.local/share/pnpm/store/v3/tmp/dlx-21401/node_modules/.pnpm/create-playwright@1.18.0-alpha-1638379596000/n
ode_modules/create-playwright/lib/index.js:1:86459 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 21439,
  stdout: null,
  stderr: null
}
 ERROR  Command failed with exit code 1: create-playwright

pnpm: Command failed with exit code 1: create-playwright
    at makeError (/home/mikob/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.3/node_modules/pnpm/dist/pnpm.cjs:24241:17)
    at handlePromise (/home/mikob/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.3/node_modules/pnpm/dist/pnpm.cjs:24812:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/mikob/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.3/node_modules/pnpm/dist/pnpm.cjs:20725
0:7)
    at async /home/mikob/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.3/node_modules/pnpm/dist/pnpm.cjs:216656:21
    at async main (/home/mikob/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.3/node_modules/pnpm/dist/pnpm.cjs:216623:34)
    at async runPnpm (/home/mikob/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.3/node_modules/pnpm/dist/pnpm.cjs:216878:5)
    at async /home/mikob/.local/share/pnpm/global/5/.pnpm/pnpm@8.6.3/node_mo

```
