### ISSUE TITLE
[BUG]Error when running TypeScript with ts-node

### ISSUE THREAD

**Issue by infra403** [microsoft/playwright#24195]
### System info
- Playwright Version: [v1.34.2]
- Operating System: [ macOS 13.2]
- Browser: [Chromium]
- Other info:

### Source code

** tsconfig.json **
```js
{
  "compilerOptions": {
    "skipLibCheck": true,
    "declaration": true,
    "importHelpers": true,
    "outDir": "dist",
    "rootDir": "src",
    "target": "ES2020",
    "strictNullChecks": false,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": [
    "src/**/*",
    "src/**/**/*",
    "src/**/**/**/*",
  ]
}
```

```js
// utils.ts
import {Page, ElementHandle,Browser,chromium, BrowserContext} from 'playwright'



**Steps**
```js
"start": "ts-node src/worker.ts src/config/app.yaml"
```

**Expected**

[Describe expected behavior]

**Actual**

2023-07-12T23:40:33.544Z [ERROR] ERROR in ./node_modules/playwright-core/lib/server/chromium/appIcon.png 1:0
2023-07-12T23:40:33.544Z [ERROR] Module parse failed: Unexpected character '�' (1:0)
2023-07-12T23:40:33.544Z [ERROR] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
2023-07-12T23:40:33.544Z [ERROR] (Source code omitted for this binary file)
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/server/chromium/crApp.js 30:51-83
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/server/trace/viewer/traceViewer.js 13:13-44
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/server/index.js 82:19-56
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/inProcessFactory.js 7:14-33
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/inprocess.js 3:24-53
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/index.js 33:0-43
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/index.mjs 17:0-36 19:24-43 20:23-41 21:22-39 22:25-45 23:23-41 24:22-39 25:23-41 26:25-45 27:24-43 28:15-25
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright/index.mjs 16:0-32 16:0-32 17:0-41 18:15-25
2023-07-12T23:40:33.544Z [ERROR]  @ ./src/playwright/utils.ts 1:0-38 95:26-49 101:26-49
2023-07-12T23:40:33.544Z [ERROR]  @ ./src/playwright/metamask/init.ts 2:0-134 13:28-49 16:18-36 17:18-23 18:36-50 25:46-65 29:22-41 30:45-64 34:22-41 39:47-66 45:48-67 49:22-41 50:44-63 51:51-70 57:50-69 62:54-73 67:53-72 72:50-69 77:50-69 92:18-23
2023-07-12T23:40:33.544Z [ERROR]  @ ./src/playwright/containers.ts 2:0-54 7:47-66
2023-07-12T23:40:33.544Z [ERROR]  @ ./src/tasks/tasks.ts 16:0-55 152:33-55
2023-07-12T23:40:33.544Z [ERROR]  @ ./src/activities.ts 1:0-44 53:23-42 54:22-44
2023-07-12T23:40:33.544Z [ERROR]  @ ./src/workflows.ts 16:0-50 167:26-44
2023-07-12T23:40:33.544Z [ERROR]  @ ./src/workflows-autogenerated-entrypoint.cjs 9:9-116

2023-07-12T23:40:33.544Z [ERROR] ERROR in ./node_modules/playwright-core/lib/webpack/recorder/ sync ^\.\/.*$
2023-07-12T23:40:33.544Z [ERROR] ENOENT: no such file or directory, readdir '/node_modules/playwright-core/lib/webpack/recorder'
2023-07-12T23:40:33.544Z [ERROR] caused by plugins in ContextModule.resolveDependencies
2023-07-12T23:40:33.544Z [ERROR] Error: ENOENT: no such file or directory, readdir '/node_modules/playwright-core/lib/webpack/recorder'
2023-07-12T23:40:33.544Z [ERROR]     at createError (/node_modules/memfs/lib/volume.js:97:19)
2023-07-12T23:40:33.544Z [ERROR]     at Volume.readdirBase (/node_modules/memfs/lib/volume.js:1332:19)
2023-07-12T23:40:33.544Z [ERROR]     at Immediate._onImmediate (/node_modules/memfs/lib/volume.js:631:33)
2023-07-12T23:40:33.544Z [ERROR]     at processImmediate (node:internal/timers:478:21)
2023-07-12T23:40:33.544Z [ERROR]     at process.topLevelDomainCallback (node:domain:161:15)
2023-07-12T23:40:33.544Z [ERROR]     at process.callbackTrampoline (node:internal/async_hooks:128:24)
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/server/recorder/recorderApp.js 63:19-67
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/server/debugController.js 10:19-52
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/server/playwright.js 17:23-51
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/browserServerImpl.js 11:18-48
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/inProcessFactory.js 9:25-55
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/lib/inprocess.js 3:24-53
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/index.js 33:0-43
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright-core/index.mjs 17:0-36 19:24-43 20:23-41 21:22-39 22:25-45 23:23-41 24:22-39 25:23-41 26:25-45 27:24-43 28:15-25
2023-07-12T23:40:33.544Z [ERROR]  @ ./node_modules/playwright/index.mjs 16:0-32 16:0-32 17:0-41 18:15-25

2023-07-12T23:40:33.544Z [ERROR] webpack 5.88.1 compiled with 2 errors and 1 warning in 2532 ms

**Comment by mxschmitt** [comment]
We need a clear reproducible in order to look into this issue. Please re-file with clear steps to reproduce this error, preferrable a small GitHub repository.
