### ISSUE TITLE
[BUG] Running test with grep option not working for OR  (--grep "@fast|@slow")

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#24275]
### System info
- Playwright Version: v1.36.1
- Operating System: Windows 11
- Browser: Chromium
- Other info: New project with default installation with `npm init playwright@latest --yes -- --quiet --browser=chromium`

### Source code 

**Config file**
default

**Test file (example.spec.test)**
default with tags `@fast`, `@slow`
```
import { test, expect } from '@playwright/test';

test('has title @fast', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link @slow', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Steps**
- Run: command from documentation https://playwright.dev/docs/test-annotations#tag-tests
- `npx playwright test --grep "@fast|@slow"`
- tested in powershell and gitbash

**Expected**

Tests are run

**Actual**

powershell
```
PS C:\prj\pw-test-delete> npx playwright test --grep "@fast|@slow"
'slow' is not recognized as an internal or external command,
operable program or batch file.
SyntaxError: C:\prj\pw-test-delete\package.json: Unexpected token / in JSON at position 151
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1324:39)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at folderIsModule (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\util.js:281:10)
    at fileIsModule (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\util.js:275:10)
    at restartWithExperimentalTsEsm (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\cli.js:253:31)
    at runTests (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\cli.js:116:7)
    at qr.<anonymous> (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\cli.js:40:7)
```
gitbash
```
$ npx playwright test --grep "@fast|@slow"
SyntaxError: C:\prj\pw-test-delete\package.json: Unexpected token / in JSON at position 151
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1324:39)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at folderIsModule (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\util.js:281:10)
    at fileIsModule (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\util.js:275:10)
    at restartWithExperimentalTsEsm (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\cli.js:253:31)
    at runTests (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\cli.js:116:7)
    at qr.<anonymous> (C:\prj\pw-test-delete\node_modules\@playwright\test\lib\cli.js:40:7)
```

[Describe actual behavior]
Coppied command form documentation not working in default project

**Comment by mxschmitt** [comment]
You need to escape it in Windows by doing:

```bash
npx playwright test --grep "@fast^|@slow"
```

does this work for you? This should work for PowerShell.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/9667

**Comment by jaktestowac** [comment]
For future reference. Console logs attached was part of problem parsing script form package.json with grep and OR. After fixing it with:
```
"npx playwright test -g \"@fast|@slow\""
```
I was able to execute grep command in terminal: `npx playwright test --grep "@fast|@slow"`

In Git Bash it was working and in Power Shell modification was needed:
```
npx playwright test --grep --% "@fast^|@slow"
```
