### ISSUE TITLE
[BUG] Flaky test between UI and CI

### ISSUE THREAD

**Issue by OSA413** [microsoft/playwright#24281]
### System info
- Playwright Version: [v1.36.1]
- Operating System: [Windows 10]
- Browser: [Chromium, Firefox, WebKit]
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    trace: 'on-first-retry',
  },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
});
```

**Test file (self-contained)**

```js
import {test, expect} from '@playwright/test';

const check = async(page) => {
    await expect(page.getByText(String(null))).toHaveCount(0);
    await expect(page.getByText(String(undefined))).toHaveCount(0);
    await expect(page.getByText(String(0), {exact: true})).toHaveCount(0);
}

test('function', async ({ page }) => {
    await page.goto('https://example.com');
    await expect(page.locator("body > div > h1")).toHaveText("Example Domain");
    check(page);
});

test('direct call', async ({ page }) => {
    await page.goto('https://example.com');
    await expect(page.locator("body > div > h1")).toHaveText("Example Domain");

    await expect(page.getByText(String(null))).toHaveCount(0);
    await expect(page.getByText(String(undefined))).toHaveCount(0);
    await expect(page.getByText(String(0), {exact: true})).toHaveCount(0);
});
```

**Steps**
- Run `playwright test --ui`
- Run `playwright test`

**Expected**

The test results are consistent between UI and CI

**Actual**

the `function` test fails in CI test.

![image](https://github.com/microsoft/playwright/assets/16105352/55cc3f93-c80e-434d-8433-0a39fd5bb9f6)

**Comment by OSA413** [comment]
Oh, my bad, I forgot to add the `await` before the check, I'm closing the issue for now. Other people that run into the same issue should find this.

**Comment by OSA413** [comment]
I'm opening this issue in case if maintainers consider it a bug that the UI doesn't catch such things.

**Comment by aslushnikov** [comment]
@OSA413 Thanks for filing! This is not a bug with playwright though - these kind of race conditions might work differently.

**Comment by OSA413** [comment]
Maybe you can add the open handle leakage (unawaited async tasks) check like Jest has?
https://jestjs.io/docs/cli#--detectopenhandles

**Comment by aslushnikov** [comment]
@OSA413 we actually have it - I assume the error in the headless mode was printing that a pending task is interrupted. Wasn't it the case?

**Comment by OSA413** [comment]
That was NOT the case.

```
> playwright test


×±·

  1) [chromium] › news.spec.ts:9:5 › function ──────────────────────────────────────────────────────

    Error: expect(received).toHaveCount(expected) // deep equality

    Expected: 0
    Received: undefined
    Call log:
      - expect.toHaveCount with timeout 5000ms
      - waiting for getByText('null')


      2 |
      3 | const check = async(page) => {
    > 4 |     await expect(page.getByText(String(null))).toHaveCount(0);
        |                                                ^
      5 |     await expect(page.getByText(String(undefined))).toHaveCount(0);
      6 |     await expect(page.getByText(String(0), {exact: true})).toHaveCount(0);
      7 | }

        at check ([REDACTED]\tests\news.spec.ts:4:48)
        at [REDACTED]\tests\news.spec.ts:12:5

  1 flaky
    [chromium] › news.spec.ts:9:5 › function ───────────────────────────────────────────────────────
  1 passed (4.9s)
```

**Comment by aslushnikov** [comment]
@OSA413 Ah! I actually thought that this is a `locator.check()` method. We only do this for the Playwright API methods.

The feature you refer to in Jest heavily relies on experimental Node APIs. We think that using ESLint rule instead to detect dangling promises is a nicer overall approach: https://playwright.dev/docs/next/best-practices#lint-your-tests
