### ISSUE TITLE
[BUG]Unable to install browser in playwright

### ISSUE THREAD

**Issue by bhagyashriuc25** [microsoft/playwright#24453]
### System info
- Playwright Version: [v18.17.0]
- Operating System: [Windows 11]
- Other info:

I have the the command npm init playwright@latest to install playwright but it is not giving success message and failing to install chromium
Here is the error belo
Failed to install browsers
Error: Failed to download Chromium 115.0.5790.75 (playwright build v1071), caused by
Error: Download failure, C:\Users\BhagyashriChaudari\AppData\Local\ms-playwright\chromium-1071\INSTALLATION_COMPLETE does not exist
    at ChildProcess.<anonymous> (C:\PIP\PlayWright\Practice\node_modules\playwright-core\lib\server\registry\browserFetcher.js:93:14)
    at ChildProcess.emit (node:events:514:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
Error: Command failed: npx playwright install
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at executeCommands (C:\Users\BhagyashriChaudari\AppData\Local\npm-cache\_npx\d352e76cc6b4974c\node_modules\create-playwright\lib\index.js:4519:39)
    at Generator.run (C:\Users\BhagyashriChaudari\AppData\Local\npm-cache\_npx\d352e76cc6b4974c\node_modules\create-playwright\lib\index.js:4679:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\BhagyashriChaudari\AppData\Local\npm-cache\_npx\d352e76cc6b4974c\node_modules\create-playwright\lib\index.js:4950:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13084,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path C:\PIP\PlayWright\Practice
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-playwright

npm ERR! A complete log of this run can be found in:

**Comment by pavelfeldman** [comment]
Please follow the bug template and provide the steps we can reproduce, thanks!
