### ISSUE TITLE
Play wright tests are failing when running test cases through ado pipeline. Error [TypeError: addToCache is not a function  at transformHook]

### ISSUE THREAD

**Issue by KausikPonnapalli7** [microsoft/playwright#24569]
### System info
- Playwright Version: [1.34.3]
- Operating System: [Ubuntu Server]
- Browser: [Chromium]
- Other info:

**Issue**

When I am running the play wright test through an ado pipeline all test cases inside the test suite are failing. This is happening only for the first time pipeline run trigger. When I'm re triggering the same pipeline run this issue is not showing up.

**Error**

```
yarn e2e x.e2e.test.ts --project="Chromium" --headless --retries=2
$ just-scripts e2e X.e2e.test.ts --project=Chromium --headless --retries=2
[12:16:20 PM] ■ started 'e2e'
$ node ../../common/scripts/check-and-build-package.js e2e-tests-utils && just-scripts e2e x.e2e.test.ts --project=Chromium --headless --retries=2
Checking if folder exists at: <Path>\lib
[12:16:35 PM] ■ started 'e2e'
testfileNames are :  [ 'x.e2e.test.ts' ]
[12:16:35 PM] ■ Starting playwright: yarn playwright test  x.e2e.test.ts --project=Chromium --retries=2
$ <Path>\node_modules\.bin\playwright test x.e2e.test.ts --project=Chromium --retries=2

TypeError: addToCache is not a function
    at transformHook (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\common\transform.js:145:13)
    at _utilsBundle.pirates.addHook.exts (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\common\transform.js:182:12)
    at Module.f._compile (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:936)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.i.<computed>.ot._extensions.<computed> (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (<Path>\packages\e2e-tests-utils\lib\src\deleteDocument\deleteFile.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.f._compile (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.i.<computed>.ot._extensions.<computed> (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (<Path>\packages\e2e-tests-utils\lib\src\deleteDocument\index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.f._compile (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.i.<computed>.ot._extensions.<computed> (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (<Path>\packages\e2e-tests-utils\src\index.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.f._compile (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.i.<computed>.ot._extensions.<computed> (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.f._compile (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.i.<computed>.ot._extensions.<computed> (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\common\transform.js:158:20)
    at requireOrImportDefaultObject (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\common\configLoader.js:80:53)
    at ConfigLoader.loadConfigFile (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\common\configLoader.js:53:26)
    at runTests (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\cli.js:120:55)
    at ji.<anonymous> (<Path>\.store\@playwright-test@1.34.3-c2508d9bb26605ef65ad\node_modules\@playwright\test\lib\cli.js:40:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[12:16:39 PM] x Error detected while running '_wrapFunction'
[12:16:39 PM] x ------------------------------------
[12:16:39 PM] x Error: Command failed: yarn playwright test  x.e2e.test.ts --project=Chromium --retries=2
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at _wrapFunction (<Path>\.store\just-task@1.7.0-b3df93bc6f107becc4f2\node_modules\just-task\lib\wrapTask.js:15:36)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (<Path>\.store\async-done@1.3.2-329abeb544b143bfcc20\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[12:16:39 PM] x ------------------------------------
[12:16:39 PM] x finished 'e2e' in 3.87s with errors
[12:16:39 PM] x Error previously detected. See above for error messages.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[12:16:40 PM] x Error detected while running 'e2e'
[12:16:40 PM] x ------------------------------------
[12:16:40 PM] x Error: Command failed: yarn e2e x.e2e.test.ts --project=Chromium --headless --retries=2
   
```

**Comment by yury-s** [comment]
Please share a minimal self-contained project which we could run ourselves with detailed steps how to reproduce the bug (including the pipeline config). With just-scripts and check-and-build-package.js scripts it's hard to tell what your code does.

**Comment by KausikPonnapalli7** [comment]
Hi Yury,
We have started another thread with more details in here. Please find more details in this thread.

https://github.com/microsoft/playwright/issues/24569

**Comment by KausikPonnapalli7** [comment]
Hi Andrey Lushnikov,

I am facing another issue on top of the previous one after using the latest play wright version.

System info
Playwright Version: [1.34.3]
Operating System: [Ubuntu Server]
Browser: [Chromium]
Other info:
Issue

When I am running the play wright test through an ado pipeline all test cases inside the test suite are failing. This is happening only for the first time pipeline run trigger. When I'm re triggering the same pipeline run this issue is not showing up.


 


Starting playwright: yarn playwright test  x.e2e.test.ts --project=Chromium --retries=2

$ D:\data\CHT\134a2915\src\ooui\apps\package\node_modules\.bin\playwright test x.e2e.test.ts --project=Chromium --retries=2

Error: EPERM: operation not permitted, rename 'C:\Users\CLOUDT~1\AppData\Local\Temp\playwright-transform-cache\29\loginToOneDrive_29ce663862f1e.map-b196a7b471565512e04845800wqe3ss' -> 'C:\Users\CLOUDT~1\AppData\Local\Temp\playwright-transform-cache\29\loginToOneDrive_29ce663dc6fd14c0e4a862f1e.map'

    at Object.renameSync (node:fs:980:3)

    at writeFileSyncAtomic (D:\data\CHT\134a2915\src\ooui\.store\playwright-core@1.37.0-0fb057c8ee5a5ab5f173\node_modules\playwright-core\lib\utils\fileUtils.js:72:15)

    at addToCache (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\compilationCache.js:99:47)

    at transformHook (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\transform.js:159:13)

    at _utilsBundle.pirates.addHook.exts (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\transform.js:196:12)

    at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:936)

    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

    at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Module.require (node:internal/modules/cjs/loader:1005:19)

    at require (node:internal/modules/cjs/helpers:102:18)

    at Object.<anonymous> (D:\data\CHT\134a2915\src\ooui\packages\e2e-tests-utils\lib\src\login\index.ts:2:1)

    at Module._compile (node:internal/modules/cjs/loader:1101:14)

    at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)

    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

    at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Module.require (node:internal/modules/cjs/loader:1005:19)

    at require (node:internal/modules/cjs/helpers:102:18)

    at Object.<anonymous> (D:\data\CHT\134a2915\src\ooui\packages\e2e-tests-utils\src\index.ts:2:1)

    at Module._compile (node:internal/modules/cjs/loader:1101:14)

    at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)

    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

    at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Module.require (node:internal/modules/cjs/loader:1005:19)

    at require (node:internal/modules/cjs/helpers:102:18)

    at Object.<anonymous> (D:\data\CHT\134a2915\src\ooui\apps\package\playwright.config.ts:4:1)

    at Module._compile (node:internal/modules/cjs/loader:1101:14)

    at Module.f._compile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)

    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

    at Object.i.<computed>.ut._extensions.<computed> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Module.require (node:internal/modules/cjs/loader:1005:19)

    at require (node:internal/modules/cjs/helpers:102:18)

    at requireOrImport (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\transform\transform.js:172:20)

    at requireOrImportDefaultObject (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\common\configLoader.js:121:53)

    at ConfigLoader.loadConfigFile (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\common\configLoader.js:94:26)

    at runTests (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\cli.js:118:55)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at i.<anonymous> (D:\data\CHT\134a2915\src\ooui\.store\@playwright-test@1.37.0-0188e559cc751398d864\node_modules\@playwright\test\lib\cli.js:40:7) {

  errno: -4048,

  syscall: 'rename',

  code: 'EPERM',

  path: 'C:\\Users\\CLOUDT~1\\AppData\\Local\\Temp\\playwright-transform-cache\\29\\loginToOneDrive_29ce6639e522b8a789bff0dc6fd14c0e4a862f1e.map-b196a7b471565512e04845800de679ec',

  dest: 'C:\\Users\\CLOUDT~1\\AppData\\Local\\Temp\\playwright-transform-cache\\29\\loginToOneDrive_29ce6639e522b8a789bff0dc6fd14c0e4a862f1e.map'

}
