### ISSUE TITLE
[Question] page.evaluate() issues with xpath

### ISSUE THREAD

**Issue by Bharath-Kumar-S** [microsoft/playwright#2556]
On running `document.evaluate('//table[@id="DataTables_Table_2"]//td[contains(text(),"true")]',document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue.click()`  in browser console the particular element is getting clicked correctly.

But not working when used with page.evaluate

`await page.evaluate(`document.evaluate('//table[@id="DataTables_Table_2"]//td[contains(text(),"true")]',document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue.click()`);`

```
Evaluation failed: TypeError: Cannot read property 'click' of null

      at __playwright_evaluation_script__:1:158
      at CRExecutionContext.evaluate (node_modules/playwright-core/lib/chromium/crExecutionContext.js:43:23)
      at FrameManager.waitForSignalsCreatedBy (node_modules/playwright-core/lib/frames.js:81:28)
      at FrameExecutionContext._doEvaluateInternal (node_modules/playwright-core/lib/dom.js:42:16)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/playwright-core/lib/helper.js:63:23)
      at Page.evaluate (node_modules/playwright-core/lib/page.js:253:33)
      at Page.evaluate (node_modules/playwright-core/lib/helper.js:64:31)
      at _callee7$ (__tests__/pages/cox/cox.page.js:78:24)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
        -- ASYNC --
      at Page.evaluate (node_modules/playwright-core/lib/helper.js:63:23)
      at _callee7$ (__tests__/pages/cox/cox.page.js:78:24)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
```

**Comment by mxschmitt** [comment]
You have to pass `page.evaluate` a callback otherwise it would not be executed in your browser's context. So in your case:

```js
await page.evaluate(() => document.evaluate('//table[@id="DataTables_Table_2"]//td[contains(text(),"true")]',document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue.click())
```

**Comment by Bharath-Kumar-S** [comment]
@mxschmitt same error still.

**Comment by Bharath-Kumar-S** [comment]
I am using **document.querySelector** in another test case. Below snippet works fine.

 await page.evaluate(`document.querySelector('[id="startChatLink"]').click()`);

**Comment by arjun27** [comment]
@Bharath-Kumar-S any particular reason why you're not using the `page.click` method? The `page.click` method auto-waits for the element to be visible and ready, and is much safer to use than this approach. In this case, the element was not found in the DOM, and it looks like the element wasn't there. You could potentially add a `page.waitForSelector` before executing `page.evaluate`, but `page.click` would do that for you.

**Comment by Bharath-Kumar-S** [comment]
@arjun27  I have used click mostly in my framework. This is a table in a pop up where normal click did not work so

**Comment by arjun27** [comment]
It might be useful to debug the `page.click` issue by setting `DEBUG=pw:input` as the environment variable so that you can see raw debug logs.

**Comment by dgozman** [comment]
Is there any chance you could provide a repro script? Otherwise, we won't be able to debug.

I _think_ the issue is that element is not present at the time you call `page.evaluate()`. When you do it later in the console, the element is already in the DOM, so everything works. Note that `page.click(selector)` waits for the element, so it should not be a problem there. It would be ideal to see logs from the click, as @arjun27 mentioned.

As a workaround, try something like the snippet below. However, I'd suggest to use `page.click()` and report logs here if that does not work.

```js
// Wait until the element is visible.
await page.waitForSelector('//table[@id="DataTables_Table_2"]//td[contains(text(),"true")]');
await page.evaluate(() => {
  ... your snippet here ...
});
```

**Comment by dgozman** [comment]
Please reopen if the issue persists.
