### ISSUE TITLE
[Question] Valid css selector with attr causes an error: is not a valid selector

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#2607]
Hello
Working on puppeteer to playwright migration.

- Playwright Version: playwright-chromium@1.1.1
- Operating System: Windows 10
- Node version: v12.16.2

I tried to launch my test that worked with no issues with puppeteer & chromium and getting the following error with playwright-chromium@1.1.1. I have a element with complicated data-test-id, but selector is valid - it works fine in puppeteer, in Chromium 85.0.4165.0.

Element:
```
<div data-test-id="Day.month=January.dayOfMonth=1.dayOfWeek=Wednesday.isPrevMonth=false" class="sc-eXEjpC epxLXg">
	<div class="sc-ibxdXY hyTSEx">
		<div class="sc-kfGgVZ Mawfy"/>
		<span>1</span>
	</div>
</div>
```

Selector:
`[data-test-id^="Day.month=January"][data-test-id*="dayOfMonth=1"][data-test-id*="isPrevMonth=false"]> div`
Log:
```
DEBUG PID_80532 Wed, 17 Jun 2020 18:02:40 GMT:  Selecting the day with parameters: month: January, dayOfMonth: 1, dayOfWeek: undefined, isPrevMonth: undefined
DEBUG PID_80532 Wed, 17 Jun 2020 18:02:40 GMT:  Clicking the element with selector "[data-test-id^="Day.month=January"][data-test-id*="dayOfMonth=1"][data-test-id*="isPrevMonth=false"]> div".
  pw:api => page.waitForSelector started +7ms
  pw:api   waiting for selector "[data-test-id^="Day.month=January"][data-test-id*="dayOfMonth=1"][data-test-id*="isPrevMonth=false"]> div" to be visible +0ms
DEBUG PID_80532 Wed, 17 Jun 2020 18:02:40 GMT:  PageError: DOMException: Failed to execute 'matches' on 'Element': '[data-test-id^="Day.month=January"][data-test-id*="dayOfMonth=1"][data-test-id*="isPrevMonth=false"]>' is not a valid selector.
  pw:api <= page.waitForSelector failed +206ms
##teamcity[testFailed name='Calendar 1' message='Evaluation failed: DOMException: Failed to execute |'matches|' on |'Element|': |'|[data-test-id^="Day.month=January"|]|[data-test-id*="dayOfMonth=1"|]|[data-test-id*="isPrevMonth=false"|]>|' is not a valid selector.
    at ancestorsMatch (__playwright_evaluation_script__209:371:21)
    at queryShadowInternal (__playwright_evaluation_script__209:296:39)
    at Object.query (__playwright_evaluation_script__209:268:20)
    at InjectedScript._querySelectorRecursively (__playwright_evaluation_script__209:563:51)
    at InjectedScript.querySelector (__playwright_evaluation_script__209:558:21)
    at eval (__playwright_evaluation_script__508:4:46)
    at onRaf (__playwright_evaluation_script__209:615:33)
    at InjectedScript._pollRaf (__playwright_evaluation_script__209:625:9)
    at __playwright_evaluation_script__209:677:45
    at InjectedScript._runCancellablePoll (__playwright_evaluation_script__209:670:21)
================ page.waitForSelector logs ================
waiting for selector "|[data-test-id^="Day.month=January"|]|[data-test-id*="dayOfMonth=1"|]|[data-test-id*="isPrevMonth=false"|]> div" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.' details='Error: Evaluation failed: DOMException: Failed to execute |'matches|' on |'Element|': |'|[data-test-id^="Day.month=January"|]|[data-test-id*="dayOfMonth=1"|]|[data-test-id*="isPrevMonth=false"|]>|' is not a valid selector.
    at ancestorsMatch (__playwright_evaluation_script__209:371:21)
    at queryShadowInternal (__playwright_evaluation_script__209:296:39)
    at Object.query (__playwright_evaluation_script__209:268:20)
    at InjectedScript._querySelectorRecursively (__playwright_evaluation_script__209:563:51)
    at InjectedScript.querySelector (__playwright_evaluation_script__209:558:21)
    at eval (__playwright_evaluation_script__508:4:46)
    at onRaf (__playwright_evaluation_script__209:615:33)
    at InjectedScript._pollRaf (__playwright_evaluation_script__209:625:9)
    at __playwright_evaluation_script__209:677:45
    at InjectedScript._runCancellablePoll (__playwright_evaluation_script__209:670:21)
================ page.waitForSelector logs ================
waiting for selector "|[data-test-id^="Day.month=January"|]|[data-test-id*="dayOfMonth=1"|]|[data-test-id*="isPrevMonth=false"|]> div" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at CRExecutionContext.evaluateWithArguments (node_modules\playwright-chromium\lib\chromium\crExecutionContext.js:52:19)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
    at InjectedScriptPollHandler.finishHandle (node_modules\playwright-chromium\lib\dom.js:490:28)
    at RerunnableTask.rerun (node_modules\playwright-chromium\lib\frames.js:764:28)
  -- ASYNC --
    at JSHandle.evaluateHandle (node_modules\playwright-chromium\lib\helper.js:64:23)
    at InjectedScriptPollHandler.finishHandle (node_modules\playwright-chromium\lib\dom.js:490:45)
    at RerunnableTask.rerun (node_modules\playwright-chromium\lib\frames.js:764:46)
  -- ASYNC --
    at Frame.waitForSelector (node_modules\playwright-chromium\lib\helper.js:64:23)
    at Page.waitForSelector (node_modules\playwright-chromium\lib\page.js:128:33)
    at Page.waitForSelector (node_modules\playwright-chromium\lib\helper.js:65:31)
    at CalendarPage.click (src\Pages\General\BasePageObject.ts:83:28)
    at CalendarPage.selectDay (src\Pages\Calendar\CalendarPage.ts:261:16)
    at Context.<anonymous> (src\Tests\Calendar\Calendar1Basic.e2e.ts:40:26)' captureStandardOutput='true' flowId='80532']
```

I quickly looked at this article https://playwright.dev/#version=v1.1.1&path=docs%2Fselectors.md&q= 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/26511191/84935144-f9e63d00-b0e0-11ea-99a0-95f12a599cfa.png">

Am I right thinking that I have to rewrite all my complicated selectors with data-test-id to some new format? How should I rewrite wildcard selectors with attributes like ^=, *=?

**Comment by DJ-Glock** [comment]
Update:
I've just found what is the root cause. I replaced **>** with **>>** and selector started working:
```
pw:api => page.waitForSelector started +6ms
pw:api   waiting for selector "[data-test-id^="Day.month=January"][data-test-id*="dayOfMonth=1"][data-test-id*="isPrevMonth=false"]>> div" to be visible +1ms
pw:api     selector resolved to visible <div class="sc-ibxdXY hyTSEx"></div> +314ms
pw:api <= page.waitForSelector succeeded +204ms
```
However this selector with **>>** does not work in Chrome Console. It's not valid CSS selector.
I do not think this is correct behaviour.

**Comment by DJ-Glock** [comment]
Another update:
It looks like the issue with original selector was caused by missing space symbol before ">":
`[data-test-id^="Day.month=January"][data-test-id*="dayOfMonth=1"][data-test-id*="isPrevMonth=false"]> div
`
I tried selector with space and it also works fine:
`[data-test-id^="Day.month=January"][data-test-id*="dayOfMonth=1"][data-test-id*="isPrevMonth=false"] > div`

Anyway there is something that should be corrected I believe. Because it should work with or without spaces. Example from jsoup.org
<img width="822" alt="image" src="https://user-images.githubusercontent.com/26511191/84939440-02da0d00-b0e7-11ea-8dc3-0a77e45289e0.png">

**Comment by mxschmitt** [comment]
Not sure if this is expected or not. I agree, that it's confusing that a typical CSS selector is not working. I made a more minimal example, so its easier to reproduce:
```js
// @ts-check
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  await page.setContent(`<div data-test-id="A">
	<div>
		<span>1</span>
	</div>
</div>`)
  // works
  await page.waitForSelector(`css=[data-test-id="A"] > div`, { timeout: 100  })
  // does not work
  await page.waitForSelector(`css=[data-test-id="A"]> div`, { timeout: 100  })
  // does not work
  await page.waitForSelector(`[data-test-id="A"]> div`, { timeout: 100  })
  await browser.close();
})();
```
Probably something for @dgozman
