### ISSUE TITLE
[Question] Is it possible to run playwright for Electron in headless mode ?

### ISSUE THREAD

**Issue by atali** [microsoft/playwright#2609]
There is 2 flavours of my project, one running on windows and another one running on linux.

Until now for Linux, we use a docker image to run our e2e with Spectron, we switched recently to Playwright but I am wondering if it's possible to run then on Linux.

Our Docker image uses xvfb, do we need something in particular to run electron with playwright in headless mode inside a docker image ?

**Comment by pavelfeldman** [comment]
You don't need anything, Docker + xvfb should work just fine. If you already ran Electron in that docker, it means you have all the dependencies in place.

**Comment by pavelfeldman** [comment]
To clarify, `playwright-electron` will run it headfully. `xvfb-run node test` is what makes it headless.

**Comment by atali** [comment]
Ok thanks a lot @pavelfeldman , let me try and let you know if I have any issue

**Comment by pavelfeldman** [comment]
Lets us know if it worked please! If it all went fine, we will close the issue!

**Comment by atali** [comment]
Yes I will, I have some issue but I trying to investigate what is the real issue.

**Comment by atali** [comment]
inside my docker , when running the following command to run my application directly
```
xvfb-run /home/pwuser/workspace/node_modules/electron/dist/electron --no-sandbox dist/apps/myapp/main.js
```
I got the following output:
```
Showing window...
```
I suppose my electron application is running correctly .

Then I stopped the previous command and then I am trying to run my e2e tests with playwright and I got the following error :

```
 console.log application-wrapper.ts:30
    browser:   <launching> /home/pwuser/workspace/node_modules/electron/dist/electron --inspect=0 --remote-debugging-port=0 --require /home/pwuser/workspace/node_modules/playwright-core/lib/server/electronLoader.js --no-sandbox dist/apps/ev-electron/main.js

  console.log application-wrapper.ts:30
    browser:   <launched> pid=1934

  console.log application-wrapper.ts:30
    browser:err:   Debugger listening on ws://127.0.0.1:35581/ad97929e-238a-4e72-a406-80a97a3b3cb3

  console.log application-wrapper.ts:30
    browser:   <ws connecting> ws://127.0.0.1:35581/ad97929e-238a-4e72-a406-80a97a3b3cb3

  console.log application-wrapper.ts:30
    browser:err:   For help, see: https://nodejs.org/en/docs/inspector

  console.log application-wrapper.ts:30
    browser:   <ws connected> ws://127.0.0.1:35581/ad97929e-238a-4e72-a406-80a97a3b3cb3

  console.log application-wrapper.ts:30
    browser:err:   Debugger attached.

  **console.log application-wrapper.ts:30
    browser:   <process did exit: exitCode=null, signal=SIGSEGV>**

 FAIL  my-test.spec.ts
  Address setting
    ✕ Should load the URL provided by the user (417ms)

  ●  Should load the URL provided by the user

    TypeError: Cannot read property 'message' of null

      at ProgressController.run (../../node_modules/playwright-core/lib/progress.js:85:51)
```

As you can see, it seems that the debugger is connected correctly but the browser crash

**Comment by atali** [comment]
I added --enable-logging as a new parameter
```
    this.app = await electron.launch(electronPath, {
      args: ['--no-sandbox', '--enable-logging', applicationPath],
      env: this.envs
      logger: {
        isEnabled: (name, severity) => true,
        log: (name, severity, message, args) => console.log(`${name}: ${message}`)
      }
    })
  }
```

and I got the following error

```
  console.log application-wrapper.ts:30
    browser:err:   [2128:0618/204237.452921:ERROR:browser_main_loop.cc(1473)] Unable to open X display.
```

**Comment by atali** [comment]
I am wondering if it's not related to the function` async function launchProcess(options)` from the lib/server/processLauncher.js.

**Comment by pavelfeldman** [comment]
I would try a couple of things:
- use `xvfb-run` as an electronPath and pass actual electron path as a first argument
- check to see if environment was indeed inherited and you are passing the DISPLAY via `this.envs` into the spawned process.

**Comment by atali** [comment]
Hey @pavelfeldman ,

I can't use xvfb-run first because of the order of parameters :

```
xvfb-run  --inspect=0 --remote-debugging-port=0 --require /home/pwuser/workspace/node_modules/playwright-core/lib/server/electronLoader.js /home/pwuser/workspace/node_modules/electron/dist/electron main.js
```
instead of 
```
xvfb-run /home/pwuser/workspace/node_modules/electron/dist/electron --inspect=0 --remote-debugging-port=0 --require /home/pwuser/workspace/node_modules/playwright-core/lib/server/electronLoader.js main.js
```


The second option helps (expose DISPLAY via this.envs) but was not enough.
We noticed xvfb-run quit before the test start maybe because of our layer of launchers :

```
gradle -> npx -> typescript -> playwright-electron -> electron launcher.
```

we end up using :
```
export DISPLAY=:99
Xvfb $DISPLAY -screen 0 1920x1080x24 &
```
and then start the e2e tests. it works well.

That's being said, xvfb-run was running well with Spectron. I don't know exactly why xvfb-run behave differently with Playwright.

Thanks again for your help. We now run our e2e tests on Linux in docker (headless) and on Windows (headfully).

**Comment by zhex900** [comment]
Hi,

I am to rewrite Spectron tests to Playwright. I can get the sample Playwright to run. But I can't get the test to run headless. 
```
export DISPLAY=:99
Xvfb $DISPLAY -screen 0 1920x1080x24 &
```
This does not work for me. 

```
  electronApp = await electron.launch({
    args: ["---no-sandbox", ".webpack/main/index.js"],
  });
```

````
pw:browser <launching> /home/jake/Code/pam-kiosk-app/packages/kiosk-app/node_modules/electron/dist/electron --inspect=0 --remote-debugging-port=0 ---no-sandbox .webpack/main/index.js +0ms
  pw:browser <launched> pid=19636 +6ms
  pw:browser [pid=19636][err] Debugger listening on ws://127.0.0.1:45031/30c70c79-6037-4706-b5dd-ab481322a47e +58ms
  pw:browser [pid=19636][err] For help, see: https://nodejs.org/en/docs/inspector +0ms
  pw:browser <ws connecting> ws://127.0.0.1:45031/30c70c79-6037-4706-b5dd-ab481322a47e +1ms
  pw:browser <ws connected> ws://127.0.0.1:45031/30c70c79-6037-4706-b5dd-ab481322a47e +6ms
  pw:browser [pid=19636][err] Debugger attached. +0ms
  pw:browser [pid=19636][out] kiosk-app-node argv [ +202ms
  pw:browser [pid=19636][out]   [ +0ms
  pw:browser [pid=19636][out]     '/home/jake/Code/pam-kiosk-app/packages/kiosk-app/node_modules/electron/dist/electron', +0ms
  pw:browser [pid=19636][out]     '--inspect=0', +0ms
  pw:browser [pid=19636][out]     '--remote-debugging-port=0', +0ms
  pw:browser [pid=19636][out]     '---no-sandbox', +1ms
  pw:browser [pid=19636][out]     '.webpack/main/index.js' +0ms
  pw:browser [pid=19636][out]   ] +0ms
  pw:browser [pid=19636][out] ] +0ms
  pw:browser [pid=19636][err] Waiting for the debugger to disconnect... +154ms
  pw:channel:response {
  pw:channel:response   id: 1,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: 'Timeout 30000ms exceeded.',
  pw:channel:response       stack: 'TimeoutError: Timeout 30000ms exceeded.\n' +
  pw:channel:response         '    at ProgressController.run (/home/jake/Code/pam-kiosk-app/packages/kiosk-app/node_modules/playwright/lib/server/progress.js:84:26)\n' +
  pw:channel:response         '    at Electron.launch (/home/jake/Code/pam-kiosk-app/packages/kiosk-app/node_modules/playwright/lib/server/electron/electron.js:152:23)\n' +
  pw:channel:response         '    at ElectronDispatcher.launch (/home/jake/Code/pam-kiosk-app/packages/kiosk-app/node_modules/playwright/lib/dispatchers/electronDispatcher.js:39:52)\n' +
  pw:channel:response         '    at DispatcherConnection.dispatch (/home/jake/Code/pam-kiosk-app/packages/kiosk-app/node_modules/playwright/lib/dispatchers/dispatcher.js:330:46)',
  pw:channel:response       name: 'TimeoutError'
  pw:channel:response     }
  pw:channel:response   }
  pw:channel:response } +0ms
  pw:api <= electron.launch failed +30s
  pw:browser [pid=19636] <process did exit: exitCode=null, signal=SIGTERM> +30s
  pw:browser [pid=19636] starting temporary directories cleanup +0ms
 FAIL   browser: chromium  tests/test.test.js (30.922 s)
  ✕ basic test (30024 ms)

  ● basic test

    electron.launch: Timeout 30000ms exceeded.

      22 | test("basic test", async () => {
      23 |   deviceId = await getDeviceId();
    > 24 |   electronApp = await electron.launch({
         |                                ^
      25 |     args: ["---no-sandbox", ".webpack/main/index.js"],
      26 |   });
      27 |   const window = await electronApp.firstWindow();

      at Object.<anonymous> (tests/test.test.js:24:32)

````

**Comment by zhex900** [comment]
@atali can you show the Dockerfile you use to run Playwright tests headless?

**Comment by zhex900** [comment]
I can't get the playwright tests to run in docker. 

I tried 
```
export DISPLAY=:99
Xvfb $DISPLAY -screen 0 1920x1080x24 &
```

`xvfb-run playwright test` this does work either

this is my error log

````
  pw:browser <launching> /app/packages/kiosk-app/node_modules/electron/dist/electron --inspect=0 --remote-debugging-port=0 .webpack/main/index.js --enable-logging --ignore-certificate-errors --ignore-ssl-errors --disable-dev-shm-usage --mockDeviceId test_fd485024-fa36-481e-a252-c16b611a837d --no-sandbox +0ms
  pw:browser <launched> pid=1621 +6ms
  pw:browser [pid=1621][err] Debugger listening on ws://127.0.0.1:34211/c3b19f4d-c66b-4833-ad20-d238ab48c623 +194ms
  pw:browser [pid=1621][err] For help, see: https://nodejs.org/en/docs/inspector +0ms
  pw:browser <ws connecting> ws://127.0.0.1:34211/c3b19f4d-c66b-4833-ad20-d238ab48c623 +1ms
  pw:browser <ws connected> ws://127.0.0.1:34211/c3b19f4d-c66b-4833-ad20-d238ab48c623 +6ms
  pw:browser [pid=1621][err] Debugger attached. +1ms
  pw:browser [pid=1605][err] [1605:0813/131926.008991:ERROR:browser_main_loop.cc(1402)] Unable to open X display. +
````

**Comment by JoCa96** [comment]
Hi, we are running 
`xvfb-run --auto-servernum --server-args='-screen 0, 1920x1080x24' npm run jest:ci`
in the docker image `mcr.microsoft.com/playwright:focal`.
We are always getting an `electron.launch: Process failed to launch!electron.launch: Process failed to launch!` error.
But we only have this issue when trying to run it headless on Azure Pipelines, locally it works.

Our code looks like this:
```typescript
beforeAll(async () => {
  electronApp = await _electron.launch({
    args: [
      "--disable_splash_screen",
      "--no-sandbox",
      "--enable-logging",
      path.join(__dirname, ".."),
    ],
  });
});

afterAll(async () => {
  if (electronApp) {
    return electronApp.close();
  }
});
```

Any suggestions on how to fix this issue or how to get a more extensive error message?

**Comment by gilles-yvetot** [comment]
@pavelfeldman I tried both things:

> I would try a couple of things:
> 
> * use `xvfb-run` as an electronPath and pass actual electron path as a first argument

I got `electron.launch: Process failed to launch!`

> * check to see if environment was indeed inherited and you are passing the DISPLAY via `this.envs` into the spawned process.

I tried checking if `process.env.DISPLAY` was set (it was) and then passing it down through `env` but I still have `Unable to open X display`
