### ISSUE TITLE
Docker - Playwright with Jest Errors on  (Works out of the container locally)

### ISSUE THREAD

**Issue by Shenbury** [microsoft/playwright#2611]
When i install as a root user, 
it appears to install the node_modules elsewhere, 

when i install as pwuser it gives lack of permissions, has anyone found a work around?

few of the Errors
```
 FAIL dist/tests/hangfire.test.js (30.881 s)
playwrightintegration_1  |   ● Console
playwrightintegration_1  |
playwrightintegration_1  |     console.error
playwrightintegration_1  |       Unhandled error
playwrightintegration_1  |
playwrightintegration_1  |       at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:248:21)
playwrightintegration_1  |
playwrightintegration_1  |     console.error
playwrightintegration_1  |       TypeError: Cannot read property 'close' of null
playwrightintegration_1  |           at Object.<anonymous> (/app/framework/tests/hangfire.test.ts:70:21)
playwrightintegration_1  |           at /app/node_modules/jest-jasmine2/build/queueRunner.js:47:12
playwrightintegration_1  |           at new Promise (<anonymous>)
playwrightintegration_1  |           at mapper (/app/node_modules/jest-jasmine2/build/queueRunner.js:30:19)
playwrightintegration_1  |           at /app/node_modules/jest-jasmine2/build/queueRunner.js:77:41
playwrightintegration_1  |           at processTicksAndRejections (internal/process/task_queues.js:97:5)
playwrightintegration_1  |           at Object.fn (/app/node_modules/jest-jasmine2/build/treeProcessor.js:43:7)
playwrightintegration_1  |
playwrightintegration_1  |       at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)
playwrightintegration_1  |
playwrightintegration_1  |   ● (chromium): UI Tests for Hangfire › (chromium): Should load page
playwrightintegration_1  |
playwrightintegration_1  |     Error: Protocol error (Target.setAutoAttach): Target closed.
playwrightintegration_1  |     =================== chromium.launch logs ===================
playwrightintegration_1  |     <launching> /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-sIPLyo --remote-debugging-pipe --no-sandbox --no-startup-window
playwrightintegration_1  |     <launched> pid=37
playwrightintegration_1  |     /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
playwrightintegration_1  |     <process did exit: exitCode=127, signal=null>
playwrightintegration_1  |     ============================================================
playwrightintegration_1  |     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
playwrightintegration_1  |
playwrightintegration_1  |       43 |         );
playwrightintegration_1  |       44 |       } catch (error) {
playwrightintegration_1  |     > 45 |         throw Error(error);
playwrightintegration_1  |          |               ^
playwrightintegration_1  |       46 |       }
playwrightintegration_1  |       47 |     }, 30000);
playwrightintegration_1  |       48 |
playwrightintegration_1  |
playwrightintegration_1  |       at Object.<anonymous> (framework/tests/hangfire.test.ts:45:15)
```

Dockerfile

```
################################################
# Compile with:
#     sudo docker build -t microsoft/playwright:bionic -f Dockerfile.bionic .
#
# Run with:
#     sudo docker run -d -p --rm --name playwright microsoft/playwright:bionic
#
#################################################

FROM ubuntu:bionic

# 1. Install node12
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs

# 3. Install Chromium dependencies

RUN apt-get install -y libnss3 \
    libxss1 \
    libasound2 \
    fonts-noto-color-emoji


WORKDIR /app

# Bundle app source
COPY . .

RUN npm install

ENV PORT=3000:8080

RUN set DEBUG=pw:api

CMD [ "npm", "run", "hangfire" ]
```

Npm command

    "hangfire": "tsc && jest --env node -i ./dist/tests/hangfire.test.js"`

Thanks in advance

**Comment by arjun27** [comment]
> when i install as pwuser it gives lack of permissions
Can you share more details on which permissions? What is the error message?

When running as root, are you running Chrome with the `--no-sandbox`?

```js
chromium.launch({ args: ['--no-sandbox'] })
```
