### ISSUE TITLE
[BUG] importing expect from @playwright/test messes up with the typescript stacktrace

### ISSUE THREAD

**Issue by Konubinix** [microsoft/playwright#26346]
### System info
- Playwright Version: v1.36.2
- Operating System: Debian GNU/Linux trixie/sid
- Browser: Not Applicable
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

Here is a very small project to highlight the issue.

[dummy.zip](https://github.com/microsoft/playwright/files/12291791/dummy.zip)

This project contains a single file `index.ts` that throws an error at line 4.
Its content is
```typescript
// import { expect } from "@playwright/test";
// let a = expect;
class A {}
throw new Error();
```

It comes with a package.json telling the needed dependencies to run this code, `ts-node` and `@playwright/test` (I simply ran yarn add @playwright/test && yarn add ts-node && yarn add typescript)

```json
{
  "dependencies": {
    "@playwright/test": "^1.36.2",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6"
  }
}
```

Finally, it also contains a yarn.lock file so that you can see the exact versions that were installed at the time I issued the bug report.

**Link to the GitHub repository with the repro**

N/A

**Config file**

N/A

**Test file (self-contained)**

N/A

**Steps**

1. run `yarn` to install the dependencies
2. run `./node_module/.bin/ts-node index.ts`
The stack trace correctly shows the error at line 4.
```
./node_modules/.bin/ts-node index.ts 
/home/sam/test/dummy/index.ts:4
throw new Error();
      ^
Error
    at Object.<anonymous> (/home/sam/test/dummy/index.ts:4:7)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/home/sam/test/dummy/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sam/test/dummy/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/home/sam/test/dummy/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/home/sam/test/dummy/node_modules/ts-node/src/bin.ts:95:10)
```
3. uncomment the first two lines
4. run `./node_module/.bin/ts-node index.ts` again
the stack trace now shows the error at line 7
```
./node_modules/.bin/ts-node index.ts 
Error: 
    at Object.<anonymous> (/home/sam/test/dummy/index.ts:7:7)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/home/sam/test/dummy/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sam/test/dummy/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/home/sam/test/dummy/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/home/sam/test/dummy/node_modules/ts-node/src/bin.ts:95:10)
    at main (/home/sam/test/dummy/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/home/sam/test/dummy/node_modules/ts-node/src/bin.ts:800:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Expected**

After starting to use playwright/test, I expected to still see the typescript stacktrace with the error at line 4.

**Actual**

After starting using @playwright/test, the stack trace was messed up.

**Other information**
Transpiling index.ts shows that the Error is not at line 7, so this looks like something more subtle than a sourcemap issue.

```
yarn exec tsc index.ts && cat -n index.js | grep Error
yarn exec v1.22.19
warning package.json: No license field
Done in 6.72s.
     8  throw new Error();
```

Lastly, this project shows the issue when importing `expect`. You can also try importing any variable, like `test` or `firefox` to trigger it. On the other hand, importing a type like `Expect` or `Browser` does not trigger it.

**Comment by dgozman** [comment]
@Konubinix This is because Playwright supports TypeScript out of the box, and `ts-node` does the same. Since both projects use the same internal node hooks to achieve this, there is a conflict. There is no known workaround today. If you are running tests with Playwright, do not use `ts-node`.

**Comment by Konubinix** [comment]
For your information, I [analysed how ts-node and playwright behave](https://konubinix.eu/blog/posts/c47e70d1-a159-416b-8319-0a2fa00d28f9/?title=playwright_test_ts_node_wrong_stack_traces).

This led me to find a workaround.

When using ts-node, use `--require ./ts-node-register-woraround-playwright.js` instead of `--require ts-node/register` and put this file in your project with the following content.

```javascript
require("@playwright/test/lib/transform/compilationCache");
require("ts-node").register();
```

That way, the stack trace hook being set up by playwright will be overriden by the one of ts-node.
