### ISSUE TITLE
[BUG] playwright._impl._api_types.Error: Browser closed. - Playwright not functional on Ubuntu after fresh install

### ISSUE THREAD

**Issue by blevlabs** [microsoft/playwright#26433]
### System info
- Playwright Version: [v1.36.0]
- Operating System: Ubuntu 22.10
- Browser: Chromium
- Other info:
- This is on a fresh install of playwright. I installed through pip, playwright install, and the  `python -m playwright install --with-deps` command, and installed chrome on ubuntu, but the code doesn't work. It works on another laptop I have with a Conda env but not this computer.
### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
from playwright.sync_api import sync_playwright
browser = (
            sync_playwright()
            .start()
            .chromium.launch(
                headless=False,
            )
        )
page = browser.new_page(extra_http_headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'})
```

**Steps**
- Run the code

**Expected**

A browser window opens

**Actual**

This traceback appears:
```
Traceback (most recent call last):
  File "/home/blabs/Companion/test.py", line 9, in <module>
    page = browser.new_page(extra_http_headers={
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 14446, in new_page
    self._sync(
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_browser.py", line 178, in new_page
    return await self._connection.wrap_api_call(inner)
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_browser.py", line 173, in inner
    page = await context.new_page()
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 270, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 477, in wrap_api_call
    return await cb()
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /home/blabs/.cache/ms-playwright/chromium-1071/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-syFiPn --remote-debugging-pipe --no-startup-window
<launched> pid=12040
[pid=12040][err] [12040:12040:0811/102340.980397:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[pid=12040][err] [0811/102341.013779:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=12040][err] [0811/102341.013826:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=12040][err] [0811/102341.013842:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[pid=12040][err] Received signal 11 SEGV_MAPERR 000000000148
[pid=12040][err] #0 0x5634e1d2d302 base::debug::CollectStackTrace()
[pid=12040][err] #1 0x5634e1d1a753 base::debug::StackTrace::StackTrace()
[pid=12040][err] #2 0x5634e1d2cd91 base::debug::(anonymous namespace)::StackDumpSignalHandler()
[pid=12040][err] #3 0x7f3ecd842520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
[pid=12040][err] #4 0x5634dda99670 base::ObserverList<>::AddObserver()
[pid=12040][err] #5 0x5634e7569375 AvatarMenu::AvatarMenu()
[pid=12040][err] #6 0x5634e7565dff DbusAppmenu::Initialize()
[pid=12040][err] #7 0x5634e7568296 DbusAppmenuRegistrar::InitializeMenu()
[pid=12040][err] #8 0x5634e7568aa3 DbusAppmenuRegistrar::OnNameOwnerChanged()
[pid=12040][err] #9 0x5634dda8c4f1 base::internal::Invoker<>::Run()
[pid=12040][err] #10 0x5634de280911 base::internal::Invoker<>::RunOnce()
[pid=12040][err] #11 0x5634e1cbd1c4 base::TaskAnnotator::RunTaskImpl()
[pid=12040][err] #12 0x5634e1cd752f base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
[pid=12040][err] #13 0x5634e1cd6fa9 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=12040][err] #14 0x5634e1cd7a05 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
[pid=12040][err] #15 0x5634e1d40e14 base::MessagePumpGlib::Run()
[pid=12040][err] #16 0x5634e1cd7d79 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
[pid=12040][err] #17 0x5634e1c9de66 base::RunLoop::Run()
[pid=12040][err] #18 0x5634dfc80fa3 content::BrowserMainLoop::RunMainMessageLoop()
[pid=12040][err] #19 0x5634dfc82aa2 content::BrowserMainRunnerImpl::Run()
[pid=12040][err] #20 0x5634dfc7e616 content::BrowserMain()
[pid=12040][err] #21 0x5634e1123088 content::RunBrowserProcessMain()
[pid=12040][err] #22 0x5634e11249e4 content::ContentMainRunnerImpl::RunBrowser()
[pid=12040][err] #23 0x5634e11247d6 content::ContentMainRunnerImpl::Run()
[pid=12040][err] #24 0x5634e1121d90 content::RunContentProcess()
[pid=12040][err] #25 0x5634e1121fbd content::ContentMain()
[pid=12040][err] #26 0x5634dd8ea309 ChromeMain
[pid=12040][err] #27 0x7f3ecd829d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
[pid=12040][err] #28 0x7f3ecd829e40 __libc_start_main
[pid=12040][err] #29 0x5634dd8ea02a _start
[pid=12040][err]   r8: 00007f3ece8e2000  r9: 0000000000000000 r10: 00005634e8713b80 r11: 00007f3ecc848988
[pid=12040][err]  r12: 00005634e865a000 r13: 00001b5c00f30450 r14: 00001b5c00f30410 r15: 00001b5c00f30428
[pid=12040][err]   di: 0000000000000148  si: 00001b5c00f30410  bp: 00007ffc9acfec70  bx: 0000000000000148
[pid=12040][err]   dx: 00005634dba08b20  ax: 0000000000000000  cx: 00000000e8063401  sp: 00007ffc9acfec20
[pid=12040][err]   ip: 00005634dda99670 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
[pid=12040][err]  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000148
[pid=12040][err] [end of stack trace]
[pid=12040][err] [12073:12092:0811/102341.131778:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -3
[pid=12040][err] [12073:12092:0811/102341.132256:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -3
```

**Comment by blevlabs** [comment]
When I use it in headless=True mode it appears to work, but the headless=False mode causes the error above

**Comment by dgozman** [comment]
@blevlabs Do you have a `DISPLAY` env variable set? Is window server running? Perhaps you should [run with `xvfb`](https://playwright.dev/docs/ci#running-headed)?

**Comment by blevlabs** [comment]
I have never run with xvfb before - the script always seemed to work on my systems. For the DISPLAY env variable, what should that be set to?

**Comment by blevlabs** [comment]
Also strange, on Firefox when I initialize it like so:
```
self.browser = sync_playwright().start().chromium.launch(headless=False)
```
The browser pulls up but I eventually run into a CDP problem:
```
File "/home/blabs/Companion/libraries/webagent/src/webagent_testing.py", line 4, in <module>
    crawl.go_to_page("https://www.google.com/")
  File "/home/blabs/Companion/libraries/webagent/src/crawler/crawler.py", line 29, in go_to_page
    self.client = self.page.context.new_cdp_session(self.page)
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 13897, in new_cdp_session
    return mapping.from_impl(self._sync(self._impl_obj.new_cdp_session(page=page)))
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_browser_context.py", line 585, in new_cdp_session
    return from_channel(await self._channel.send("newCDPSession", params))
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/home/blabs/anaconda3/envs/companioncore/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: CDP session is only available in Chromium
```
I would prefer firefox to work so if there is an alternative to the cdp session shown here advice would be great!
```
    def go_to_page(self, url):
        self.page.goto(url=url if "://" in url else "http://" + url, wait_until="domcontentloaded")
        # run for firefox since cdp is not supported
        self.client = self.page.context.new_cdp_session(self.page)
        self.page_element_buffer = {}
        # wait until page is loaded
        self.page.wait_for_load_state("load")
        time.sleep(1.5)
```

**Comment by blevlabs** [comment]
By the way, unsure if this is related but Firefox seems to pull up fine:
```
from playwright.sync_api import sync_playwright


def test_playwright():
    # Open the Playwright context
    with sync_playwright() as p:
        # Define the browser to use
        browser = p.firefox.launch(headless=False)
        # Create a new browser context
        context = browser.new_context()
        # Open a new page
        page = context.new_page()

        # Go to the specified webpage
        page.goto("http://google.com/")
        page.wait_for_load_state("load")
        # find input fields
        print(page.query_selector_all("input"))
        # page.fill("input[name='q']", "playwright github")
        # Take a screenshot of the webpage
        page.screenshot(path="example.png")
        # Print the page title
        print(page.title())

        # Close the page and browser after the test
        page.close()
        browser.close()


# Run the function
test_playwright()
```

**Comment by dgozman** [comment]
@blevlabs 

- Since Firefox launches in headed mode, this is not about `DISPLAY` or `xvfb`.
- Firefox does not have CDP or an equivalent.
- This looks like an upstream bug in Chromium, I'll ask around there.

**Comment by blevlabs** [comment]
Also, this might need another ticket but since this might be related to Chromium I wanted to share - whenever I try to do a page.mouse.click() and have a specific set of coordinates I know relate to a clickable object, I can send the request to the function, but nothing happens.
```
self.page = self.browser.new_page()

element ={'node_index': '337', 'backend_node_id': 342, 'node_name': 'a', 'node_value': None, 'node_meta': [], 'is_clickable': True, 'origin_x': 1111, 'origin_y': 1033, 'center_x': 1145, 'center_y': 1056} # example I pulled from my crawler



x = element.get("center_x")
y = element.get("center_y")
print("Clicking at: " + str(x) + ", " + str(y) + "...")
self.page.mouse.click(x, y)
```
It sends it to the click function with no error, but nothing happens on the site.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by NiharR027** [comment]
+ 1
