### ISSUE TITLE
Firefox, when opened, opens a warning

### ISSUE THREAD

**Issue by el9in** [microsoft/playwright#26538]
Firefox, when opened, opens a warning, and if you do not click it, the bot will not start and will give an error.
```
browserType.launchPersistentContext: Timeout 180000ms exceeded.
=========================== logs ===========================
<launching> ...\AppData\Local\ms-playwright\firefox-1422\firefox\firefox.exe -no-remote -headless -profile ./cache/gfg7e8lj -juggler-pipe --disable-blink-features=AutomationControlled about:blank
<launched> pid=7052
[pid=7052][err] *** You are running in headless mode.
[pid=7052][out] console.warn: services.settings: Ignoring preference override of remote settings server
[pid=7052][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[pid=7052][out] console.error: ({})
[pid=7052][out]
[pid=7052][out] Juggler listening to the pipe
[pid=7052][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=5.09821) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
[pid=7052][out] console.error: (new SyntaxError("The URI is malformed.", (void 0), 133))
[pid=7052][out] console.error: Region.sys.mjs: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", "chrome://juggler/content/NetworkObserver.js", 418))
[pid=7052][out] console.error: Region.sys.mjs: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.sys.mjs", 411))
[pid=7052][err] JavaScript warning: resource://gre/modules/UpdateService.sys.mjs, line 3853: unreachable code after return statement
[pid=7052][out] console.error: "DEPRECATION WARNING: Calling FileUtils.getDir(..., ..., true) causes main thread I/O and should be avoided especially during startup/shutdown\nYou may find more details about this deprecation at: https://bugzilla.mozilla.org/show_bug.cgi?id=921157\nresource://gre/modules/FileUtils.sys.mjs 62 FileUtils_getDir\nresource://gre/modules/UpdateService.sys.mjs 1054 getUpdateDirCreate\nresource://gre/modules/UpdateService.sys.mjs 1093 getUpdateFile\nresource://gre/modules/UpdateService.sys.mjs 4442 UM__loadXMLFileIntoArray\nresource://gre/modules/UpdateService.sys.mjs 4276 UpdateManager\nresource://gre/modules/XPCOMUtils.sys.mjs 137 defineLazyServiceGetter/<\nresource://gre/modules/UpdateService.sys.mjs 3374 get _pingSuffix\nresource://gre/modules/UpdateService.sys.mjs 3407 AUS__checkForBackgroundUpdates\nresource://gre/modules/UpdateService.sys.mjs 3362 AUS_notify\nresource://gre/modules/UpdateTimerManager.sys.mjs 199 TM_notify/</<\nresource:///modules/BrowserGlue.sys.mjs 1271 BG__beforeUIStartup\nresource:///modules/BrowserGlue.sys.mjs 959 BG_observe\n"
[pid=7052][out] console.error: (new Error("Polling for changes failed: The URI is malformed..", "resource://services-settings/remote-settings.sys.mjs", 324))
[pid=7052][out] console.error: Region.sys.mjs: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", "chrome://juggler/content/NetworkObserver.js", 418))
[pid=7052][out] console.error: Region.sys.mjs: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.sys.mjs", 411))
============================================================
    at async Proxy.launchPersistentContext (....node_modules\playwright-extra\dist\index.cjs.js:703:25)
    at async ramblerRuZenoWright (...:70:13)    at async threadStart (...\OneDrive\Desktop\AutoReger\index_ds.js:174:22) {
  name: 'TimeoutError'
}
```

**Comment by mxschmitt** [comment]
Closing for now since this issue does not follow the bug template. Please re-file with more information, especially a repro script and details about your OS.
