### ISSUE TITLE
[BUG] Code coverage can't be collected in screenshots tests

### ISSUE THREAD

**Issue by Skipi0007** [microsoft/playwright#26832]
Right now we have similar flaky problem in all screenshots tests, that sometimes it can't collect coverage from pages

### System info
- Playwright Version: 1.36.1
- Operating System: macOS 13.2
- Browser: All

### Source code

Right now we collecting coverage by this script:

```js
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import type { Browser, BrowserContext, Page, test } from '@playwright/test';
import { readFile } from 'fs/promises';
import { dirname } from 'path';
import { cwd } from 'process';
import v8toIstanbul from 'v8-to-istanbul';

const ROOT = fs.realpathSync(process.cwd());
const coverageResultsTempDir = path.join(ROOT, '.nyc_output');

function UUID() {
	return crypto.randomBytes(16).toString('hex');
}

function saveCoverage(result: string) {
	if (!fs.existsSync(coverageResultsTempDir)) {
		fs.mkdirSync(coverageResultsTempDir);
	}
	fs.writeFileSync(path.join(coverageResultsTempDir, `playwright-${UUID()}-coverage.json`), result);
}

async function getSourcemap(source: string, url: string): Promise<string | void> {
	const sourcemapName = source.match(/sourceMappingURL=(.*)/)?.[1];
	if (!sourcemapName) return undefined;
	const { pathname } = new URL(url);
	const sourcemapPath = `build/client${dirname(pathname)}/${sourcemapName}`;
	const sourcemap = JSON.parse(String(await readFile(sourcemapPath)));
	if (!sourcemap.sources.length) return undefined;
	sourcemap.sources = sourcemap.sources.map((s: string) => s.replace(/(..\/)+/, cwd() + '/'));
	return sourcemap;
}

const knownContexts = new WeakSet();
const knownBrowsers = new WeakSet();
const knownPages = new WeakSet();
const pagesWithEnabledCoverage = new WeakSet();

export function captureCoverage(
	testConstructor: typeof test,
	options = {
		reportAnonymousScripts: false,
		resetOnNavigation: false,
	}
) {
	if (
		process.env.CI_PIPELINE_SOURCE !== 'schedule' ||
		process.env.CI_JOB_NAME?.includes('screen')
	) {
		return;
	}
	async function stopCodeCoverage(page: Page) {
		if (!pagesWithEnabledCoverage.has(page)) return;
		const jsCoverage = await page.coverage.stopJSCoverage();
		for (const entry of jsCoverage) {
			try {
				if (!entry.source) {
					throw new Error('Source is undefined');
				}
				const sourcemap = await getSourcemap(entry.source, entry.url);

				if (!sourcemap) {
					continue;
				}

				const converter = v8toIstanbul(
					'',
					0,
					{
						source: entry.source,
						sourceMap: { sourcemap },
					},
					(path) => !path.includes('/src/') || path.includes('node_modules')
				);
				await converter.load();
				converter.applyCoverage(entry.functions);
				const result = converter.toIstanbul();
				const keys = Object.keys(result);

				if (keys.length) {
					saveCoverage(JSON.stringify(result));
				}
			} catch (e) {
				console.error(`Unable to process coverage for ${entry.scriptId}:${entry.url}`);
			}
		}

		pagesWithEnabledCoverage.delete(page);
	}
	async function startCodeCoverage(page: Page) {
		if (pagesWithEnabledCoverage.has(page)) return;
		pagesWithEnabledCoverage.add(page);
		// https://playwright.dev/docs/api/class-coverage#coverage-start-js-coverage-option-reset-on-navigation
		// we assume that we testing our SPA, and there is no needs to reset coverage between page navigations
		await page.coverage.startJSCoverage(options);
	}

	function patchPageClose(page: Page) {
		if (knownPages.has(page)) return page;
		const originalClose = page.close.bind(page);
		page.close = async function () {
			await stopCodeCoverage(page);
			return await originalClose();
		};
		knownPages.add(page);
		return page;
	}

	function patchNewPage(context: BrowserContext) {
		if (knownContexts.has(context)) return;
		const originalCreatePage = context.newPage.bind(context);
		context.newPage = async function () {
			const page = await originalCreatePage();
			knownContexts.add(page.context());
			page.on('load', async () => {
				await startCodeCoverage(page);
			});
			return patchPageClose(page);
		};
		knownContexts.add(context);
	}

	function patchNewContext(browser: Browser) {
		if (knownBrowsers.has(browser)) return;
		const originalCreateContext = browser.newContext.bind(browser);
		browser.newContext = async function () {
			const context = await originalCreateContext();
			patchNewPage(context);
			knownContexts.add(context);
			return context;
		};
		knownBrowsers.add(browser);
	}

	testConstructor.beforeEach(async ({ browser }) => {
		if (browser.browserType().name() !== 'chromium') {
			// Skipping coverage for non-chromium browsers
			return;
		}
		// check for browser type
		patchNewContext(browser);
		browser.contexts().forEach((context) => {
			patchNewPage(context);
			context.pages().forEach((page) => {
				patchPageClose(page);
			});
		});
	});

	testConstructor.afterEach(async ({ context, browser }) => {
		if (browser.browserType().name() !== 'chromium') {
			return;
		}
		for (const page of context.pages()) {
			await stopCodeCoverage(page);
		}
	});
}
```

and executing them in fixtures, after export of "test"

```
type TestFixtures = {
	lkMainPage: LkMainPage;
};

const test = base.extend<TestFixtures>({
	lkMainPage: async ({ page }, use) => {
		const lkMainPage = new LkMainPage(page);
		await use(lkMainPage);
	},
});

export default test;
captureCoverage(test);
```

**Test file (self-contained)**
```js
async checkClosingBannerScreenshot(): Promise<void> {
		await test.step(`take a screenshot`, async () => {
			await expect(this.closingBanner).toHaveScreenshot();
		});
	}
```

```js
test('make screenshot @screen', async ({ lkMainPage }) => {
			await lkMainPage.checkClosingBannerScreenshot();
		});
```

**Expected**

Coverage collected

**Actual**

```
Test timeout of 30000ms exceeded while running "afterEach" hook.
       at helpers/captureCoverage.ts:146
      144 | 	});
      145 |
    > 146 | 	testConstructor.afterEach(async ({ context, browser }) => {
          | 	                ^
      147 | 		if (browser.browserType().name() !== 'chromium') {
      148 | 			return;
      149 | 		}
        at /builds/ob/albuss-ng/tests/helpers/captureCoverage.ts:146:18
    Error: coverage.stopJSCoverage: Target closed
       at helpers/captureCoverage.ts:50
      48 | 	async function stopCodeCoverage(page: Page) {
      49 | 		if (!pagesWithEnabledCoverage.has(page)) return;
    > 50 | 		const jsCoverage = await page.coverage.stopJSCoverage();
         | 		                                       ^
      51 | 		for (const entry of jsCoverage) {
      52 | 			try {
      53 | 				if (!entry.source) {
        at stopCodeCoverage (/builds/ob/albuss-ng/tests/helpers/captureCoverage.ts:50:42)
        at /builds/ob/albuss-ng/tests/helpers/captureCoverage.ts:151:10
```

**Comment by dgozman** [comment]
@Skipi0007 

> Right now we have similar flaky problem in all screenshots tests

I am not sure how screenshots may affect this. Since we cannot run this partial repro, our options are pretty limited.

There are a few issues here:
- You cannot call `beforeEach`/`afterEach` from a shared fixtures file. The way I see it above, these hooks will be registered only for the first test file that imports the fixtures file, but not in any other tests.
- Instead of wrapping and overriding methods, I'd recommend overriding the `page` or `context` fixture. That's unless you use multiple contexts in your tests.
- Most likely, the error you see is because you try to collect coverage on the closed context. For example, playwright internally calls `context.close()` on the default context. This is just a guess though.

**Comment by Skipi0007** [comment]
ok thanks, i will try it and describe my results

**Comment by dgozman** [comment]
@Skipi0007 Any luck with the above?

**Comment by Skipi0007** [comment]
Keep working with it

**Comment by aslushnikov** [comment]
@Skipi0007 I'll close this since the discussion has stalled. If you think we still can be helpful, then please file another issue!

**Comment by Skipi0007** [comment]
ок
