### ISSUE TITLE
[BUG] Does playwright test component support NextJS?

### ISSUE THREAD

**Issue by PedroReyes** [microsoft/playwright#26983]
### System info
- Playwright Version: [v1.37.0]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:
- "react": "18.2.0",
- "next": "13.4.9",

### Source code

I receive quite a lot of errors and doesn't seem to identify the component I am trying to import:

![image](https://github.com/microsoft/playwright/assets/4096108/74ecd17d-c824-4d42-b628-81b03327f587)

As you can see in the image I am using the new folder `app` from Next JS and the split of `page` & `layout`

Thanks in advanced for any help on this regard ✌

Best regards,
Pedro Reyes.

**Comment by PedroReyes** [comment]
Hello,

I was placing my test within the test folder instead of right close to the component.tsx file. Now, that I am doing so, I am finding the next issue:

```
$ npm run test-ct

> my-app@0.1.0 test-ct
> playwright test -c playwright-ct.config.ts
Error: Requiring @playwright/test second time, 
First:
Error:

   at playwright-ct.config.ts:1

> 1 | import { defineConfig, devices } from '@playwright/experimental-ct-react';
    | ^
  2 |
  3 | /**
  4 |  * See https://playwright.dev/docs/test-configuration.

    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\index.js:60:33)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\index.js:17:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\index.js:17:81)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-react\index.js:17:71)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\playwright-ct.config.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.f._compile (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .ts] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\transform\transform.js:172:20)
    at requireOrImportDefaultObject (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\common\configLoader.js:121:53)
    at ConfigLoader.loadConfigFile (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\common\configLoader.js:94:26)
    at runTests (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\cli.js:118:55)
    at i.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\cli.js:40:7)

Second:
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\index.js:17:81)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-react\index.js:17:71)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\playwright-ct.config.ts:1:1)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\test\lib\index.js:55:11)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\test\index.js:17:13)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\tests\models\pages\HomePage.ts:7:13)     
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\tests\TestHierarchy.spec.ts:6:17)        

Error: Requiring @playwright/test second time,
First:
Error:

   at playwright-ct.config.ts:1

> 1 | import { defineConfig, devices } from '@playwright/experimental-ct-react';
    | ^
  2 |
  3 | /**
  4 |  * See https://playwright.dev/docs/test-configuration.

    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\index.js:60:33)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\index.js:17:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\index.js:17:81)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-react\index.js:17:71)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\playwright-ct.config.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.f._compile (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .ts] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\transform\transform.js:172:20)
    at requireOrImportDefaultObject (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\common\configLoader.js:121:53)
    at ConfigLoader.loadConfigFile (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\common\configLoader.js:94:26)
    at runTests (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\cli.js:118:55)
    at i.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\cli.js:40:7)

Second:
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\index.js:17:81)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-react\index.js:17:71)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\playwright-ct.config.ts:1:1)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\test\lib\index.js:55:11)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\test\index.js:17:13)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\tests\models\pages\HomePage.ts:7:13)     
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\tests\TestHome.spec.ts:6:17)

Error: Requiring @playwright/test second time,
First:
Error:

   at playwright-ct.config.ts:1

> 1 | import { defineConfig, devices } from '@playwright/experimental-ct-react';
    | ^
  2 |
  3 | /**
  4 |  * See https://playwright.dev/docs/test-configuration.

    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\index.js:60:33)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\index.js:17:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\index.js:17:81)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-react\index.js:17:71)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\playwright-ct.config.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.f._compile (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .ts] (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireOrImport (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\transform\transform.js:172:20)
    at requireOrImportDefaultObject (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\common\configLoader.js:121:53)
    at ConfigLoader.loadConfigFile (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\common\configLoader.js:94:26)
    at runTests (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\cli.js:118:55)
    at i.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\node_modules\@playwright\test\lib\cli.js:40:7)

Second:
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-core\index.js:17:81)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\experimental-ct-react\index.js:17:71)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\playwright-ct.config.ts:1:1)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\test\lib\index.js:55:11)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\node_modules\@playwright\test\index.js:17:13)
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\tests\models\pages\HomePage.ts:7:13)     
    at Object.<anonymous> (C:\blockchain\tutorial-projects\audit\client\tests\TestProfile.spec.ts:6:17)




To open last HTML report run:

  npx playwright show-report

```

Any idea why this is happening in a NextJS project?

Thanks in advanced for any help on this regard ✌

Best regards,
Pedro Reyes.

**Comment by dgozman** [comment]
@PedroReyes Most likely, you have both `@playwright/experimental-ct-react` and `@playwright/test` dependencies in your project, and they probably resolve to different versions. Make sure you have both packages with the exactly same version. You can run `npm ls @playwright/test` and `npm ls @playwright/experimental-ct-react`.

Also, it seems like `tests\models\pages\HomePage.ts` imports `@playwright\test` instead of `@playwright/experimental-ct-react`.

Overall, if you provide a repro that we can run locally, we would be able to help with confidence instead of just guessing.

**Comment by PedroReyes** [comment]
Hello,

Thanks for taking the time to reply @dgozman . You might be certainly right, I had:

```
"@playwright/experimental-ct-react": "1.37.1",
"@playwright/test": "1.37.0"
```

Now I have a different issue related to constants but that seems to be a known limitation for what I saw in the docs:

```
$ npm run test-ct

> my-app@0.1.0 test-ct
> playwright test -c playwright-ct.config.ts


Running 51 tests using 4 workers

vite v4.4.9 building for production...
components/atoms/Hierarchy/NimbusOrganigram.tsx (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of 
error.
✓ 5 modules transformed.
✓ built in 9.19s
[vite]: Rollup failed to resolve import "@/shared/types/users" from "C:/blockchain/tutorial-projects/audit/client/components/atoms/Hierarchy/NimbusOrganigram.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
Error: [vite]: Rollup failed to resolve import "@/shared/types/users" from "C:/blockchain/tutorial-projects/audit/client/components/atoms/Hierarchy/NimbusOrganigram.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

    at viteWarn (C:\blockchain\tutorial-projects\audit\client\node_modules\vite\dist\node\chunks\dep-df561101.js:48142:27)
    at onwarn (C:\blockchain\tutorial-projects\audit\client\node_modules\@vitejs\plugin-react\dist\index.mjs:238:9)
    at onRollupWarning (C:\blockchain\tutorial-projects\audit\client\node_modules\vite\dist\node\chunks\dep-df561101.js:48171:9)
    at onwarn (C:\blockchain\tutorial-projects\audit\client\node_modules\vite\dist\node\chunks\dep-df561101.js:47902:13)
    at C:\blockchain\tutorial-projects\audit\client\node_modules\rollup\dist\es\shared\node-entry.js:24271:13
    at Object.logger (C:\blockchain\tutorial-projects\audit\client\node_modules\rollup\dist\es\shared\node-entry.js:25945:9)
    at ModuleLoader.handleInvalidResolvedId (C:\blockchain\tutorial-projects\audit\client\node_modules\rollup\dist\es\shared\node-entry.js:24857:26)
    at C:\blockchain\tutorial-projects\audit\client\node_modules\rollup\dist\es\shared\node-entry.js:24817:26

  51 skipped
components/atoms/Hierarchy/Hierarchy.tsx (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error. 
transforming (15) node_modules\react\cjs\react-jsx-runtime.production.min.js
To open last HTML report run:

  npx playwright show-report
```

I will close this ticket since this seems to be solved using ViteConfig. It would be great if the docs are improved with an example instead of an empty one:

![image](https://github.com/microsoft/playwright/assets/4096108/dff3c704-a33b-4110-9ea4-50c7878146bf)

I also saw that might be a "quick-way" to do the resolves of paths by using [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths). 

Also adding `npm init playwright@latest -- --ct` a small script to check whether or not the playwright versions are compatible might be a boost in the usage of the library.

Thanks for your help @dgozman , wish you a good day.

Best regards,
Pedro Reyes.

**Comment by kishoreGleniseOfficial** [comment]
Hey @PedroReyes , sorry to bother you, I have a question. I initially just used the `@playwright/test`, later I installed the `@playwright/experimental-ct-react`, So now I have two config files, one for playwright/test & one for the other respectively. So does this cause any conflict?? And also is it working fine in Nextjs?

**Comment by PedroReyes** [comment]
Hello @kishoreGleniseOfficial ,

Its been a long time I don't work on this project already but according to my comments here it seems it worked. Finally for my small projects I am using just playwright E2E testing and not components testing. In any case, I have setup independently in different projects playwright E2E and component testing and I think thats the best approach:

📁 App name folder with NextJS: you run here the application and do the component testing setup here as described without having any conflict.
📁 E2E folder with Playwright for E2E testing: once you run NextJs you are good to go or you can tell playwright the command for executing the server. 

This should work.
