### ISSUE TITLE
[BUG] Getting "MaxListenersExceededWarning: Possible EventEmitter memory leak detected"  Error while using await browser.stopTracing();

### ISSUE THREAD

**Issue by mustafasahin0** [microsoft/playwright#26998]
### System info
- Playwright Version: 1.37.1
- Operating System: [ macOS 13.5.1]
- Browser: [Chromium]
- Other info:

### Source code

```import {expect} from '@playwright/test';
import {DateTime} from 'luxon';
import data from "XXXXXX"
import fs from 'fs';
import { test } from '../fixtureProd';


let testTempId = "";

data.forEach(data => {
test(`Loyalty-Round-Trip ${data.testId}`, async ({ vPage, vContext, vBrowser }, testInfo) => {

        const page = vPage;
        const context = vContext;
        const browser = vBrowser;

        await browser.startTracing(page, {path: 'playwright/.trace/trace.json', screenshots: true});

        
        testTempId = data.testId;
        const client = await page.context().newCDPSession(page);

        await client.send('Performance.enable');
        await client.send('Overlay.setShowFPSCounter', {show: true});


        await page.goto(data.debugging);
        await page.locator('.automation-username').fill(data.username);
        await page.locator('.automation-password').fill(data.password);
        await page.locator('.automation-submit').click();

        await page.goto(data.tools);
        await page.locator("#xml").clear();
        const xmlContent = fs.readFileSync('XXXXX', 'utf8');
        await page.locator("#xml").fill(xmlContent)
        await page.locator(".automation-testProfile").click();
        



        const testId = test.info().title;

        await page.locator(".automation-searchAir").click();
        // await page.locator('.automation-oneWay').click();
        await page.locator('.automation-departure .automation-basic-typeahead-input').fill(data.departure);
        await page.getByText(`(${data.departure})`).click();
        await page.locator('.automation-destination .automation-basic-typeahead-input').fill(data.arrival);
        await page.getByText(`(${data.arrival})`).click();
        await page.locator('.automation-startDate').focus();
        await page.locator('.automation-startDate ').fill(futureDate(6, 0, data.datePattern));

        await page.waitForTimeout(200);
        await page.locator('.automation-submitSearch').click();


        await page.waitForURL(/.+\/search-results\/air\/.+/);
        await page.waitForLoadState('domcontentloaded');

        await page.locator('.automation-addToTrip').first().isVisible();

        await browser.stopTracing();
        await testInfo.attach(`trace-${data.testId}`, { path: 'playwright/.trace/trace.json' } )
        });
})

export function futureDate(months: number, days: number, format: string = 'MM/dd/yy'): string {
    return DateTime.now().plus({ months, days }).toFormat(format)
}```

<!-- For simple cases, please provide a self-contained test file along with the config file -->
<!-- For larger cases, you can provide a GitHub repo you created for this issue -->
<!-- If we can not reproduce the problem locally, we won't be able to act on it -->
<!-- You can still file without the exact code and we will try to help, but if we can't repro, it will be closed -->

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['html'], ['json', {  outputFile: 'test-results.json' }]],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'https://travel.americanexpress.com.au',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on',
  },
  // testMatch: ['airOneWayWithAirport.test.ts', 'airOneWayWithCity.test.ts','airRoundTripWithAirport.test.ts', 'airRoundTripWithCity.test.ts'],
  testMatch: ['airRoundTripWithAirportProdFITAAVacations.test.ts'],
  repeatEach: 20,
  timeout: 200000,

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], launchOptions: {args: ['--start-maximized'], headless: false}, contextOptions: {recordHar: {path: 'playwright/.har/testHar.har', mode: "full"}}},
    },
    // {
    //   name: 'browserless',
    //   use: { ...devices['Desktop Chrome'], launchOptions: {args: ['--start-maximized']}, contextOptions: {recordHar: {path: 'playwright/.har/testHar.har'}}},
    // }
    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'], launchOptions: {args: ['--start-maximized']} },
    // },

    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'], launchOptions: {args: ['--start-maximized']} },
    // },

    // /* Test against mobile viewports. */
    //  {
    //    name: 'Mobile Chrome',
    //    use: { ...devices['Pixel 5'] },
    //  },
    //  {
    //    name: 'Mobile Safari',
    //    use: { ...devices['iPhone 12'] },
    //  },

    //  /* Test against branded browsers. */
    //  {
    //    name: 'Microsoft Edge',
    //    use: { ...devices['Desktop Edge'], channel: 'msedge' },
    //  },
    //  {
    //    name: 'Google Chrome',
    //    use: { ...devices['Desktop Chrome'], channel: 'chrome', headless: false,  },
    //  },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
```

**Test file (self-contained)**

**Steps**
- Run the above test
- Observe that on the IDE console user is getting below errors: 
- `(node:19512) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(Use node --trace-warnings ... to show where the warning was created)
(node:19512) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit`

**Expected**

User should not get any MaxListenersExceededWarning errors while using browser.stopTacing() method.

**Actual**

User is getting MaxListenersExceededWarning errors while using browser.stopTracing() method.

**Comment by mxschmitt** [comment]
Do you mind setting the `NODE_OPTIONS= --trace-warnings` env var, while you run your repro? so we can see exactly where the error got thrown? This would help a ton, thanks!

**Comment by mustafasahin0** [comment]
Sure 

> Do you mind setting the `NODE_OPTIONS="--trace-warnings"` env var, while you run your repro? so we can see exactly where the error got thrown? This would help a ton, thanks!

Sure I will do that now

**Comment by mustafasahin0** [comment]
Here is the output with NODE_OPTIONS="--trace-warnings"

`(node:93114) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:585:17)
    at ReadStream.addListener (node:events:603:10)
    at ReadStream.Readable.on (node:internal/streams/readable:895:35)
    at ReadStream.once (node:events:647:8)
    at /Users/mustafasahin/dev/repos/playwright-performance/node_modules/playwright-core/lib/server/dispatchers/streamDispatcher.js:45:16
    at new Promise (<anonymous>)
    at StreamDispatcher.read (/Users/mustafasahin/dev/repos/playwright-performance/node_modules/playwright-core/lib/server/dispatchers/streamDispatcher.js:43:13)
    at DispatcherConnection.dispatch (/Users/mustafasahin/dev/repos/playwright-performance/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:313:46)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:449:9)
(node:93114) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:585:17)
    at ReadStream.addListener (node:events:603:10)
    at ReadStream.Readable.on (node:internal/streams/readable:895:35)
    at ReadStream.once (node:events:647:8)
    at /Users/mustafasahin/dev/repos/playwright-performance/node_modules/playwright-core/lib/server/dispatchers/streamDispatcher.js:46:16
    at new Promise (<anonymous>)
    at StreamDispatcher.read (/Users/mustafasahin/dev/repos/playwright-performance/node_modules/playwright-core/lib/server/dispatchers/streamDispatcher.js:43:13)
    at DispatcherConnection.dispatch (/Users/mustafasahin/dev/repos/playwright-performance/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:313:46)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:449:9)`
