### ISSUE TITLE
[BUG] Playwright test failing for chromium on mac os m1

### ISSUE THREAD

**Issue by Akshay090** [microsoft/playwright#26990]
### System info
- Playwright Version: [v1.XX] - latest
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.] - macOS 12.6.7
- Browser: [All, Chromium, Firefox, WebKit] chromium
- Other info:

### Source code

default source code from - npm init playwright@latest

and npx playwright test

Error Log 
```
Error: browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /Users/user-system/Library/Caches/ms-playwright/chromium-1076/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --use-angle --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/98/r5vwpp2971jf3k7h0qrdx7d40000gq/T/playwright_chromiumdev_profile-Q9XM2R --remote-debugging-pipe --no-startup-window
<launched> pid=72838
[pid=72838] <process did exit: exitCode=null, signal=SIGKILL>
[pid=72838] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/user-system/Library/Caches/ms-playwright/chromium-1076/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --use-angle --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/98/r5vwpp2971jf3k7h0qrdx7d40000gq/T/playwright_chromiumdev_profile-Q9XM2R --remote-debugging-pipe --no-startup-window
<launched> pid=72838
[pid=72838] <process did exit: exitCode=null, signal=SIGKILL>
[pid=72838] starting temporary directories cleanup
============================================================



```

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]

  npm init playwright@latest
  
  and npx playwright test

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by sapcik** [comment]
I'm having that same problem with the firefox.

Playwright 1.37.1, NodeJS v18.16.0, MacBook Pro with M2 Pro.

`=========================== logs ===========================
<launching> /Users/xxx/Work/xxx/xxx/browsers/firefox-1422/firefox/Nightly.app/Contents/MacOs/firefox -no-remote -headless -profile /var/folders/62/z7932sdn0m7g4m5f8gk669z00000gn/T/playwright_firefoxdev_profile-4RA9dT -juggler-pipe -silent
<launched> pid=2721
[pid=2721][err] *** You are running in headless mode.
[pid=2721] <process did exit: exitCode=1, signal=null>
[pid=2721] starting temporary directories cleanup
============================================================
    at module.exports (/Users/xxx/Work/xxx/xxx/app/firefox.js:10:33)
    at IpcMainImpl.<anonymous> (/Users/xxx/Work/xxx/xxx/index.js:87:50) {
  name: 'Error'
}`

**Comment by dgozman** [comment]
@Akshay090 Try running the browser manually - perhaps there is a configuration issue on your system?

```sh
/Users/user-system/Library/Caches/ms-playwright/chromium-1076/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --use-angle --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/98/r5vwpp2971jf3k7h0qrdx7d40000gq/T/playwright_chromiumdev_profile-Q9XM2R --no-startup-window
```

**Comment by Akshay090** [comment]
@dgozman tried it, it's failing with this error 
```
[0912/085152.607317:ERROR:headless_content_main_delegate.cc(181)] Remote debugging pipe file descriptors are not open.
```

**Comment by dgozman** [comment]
@Akshay090 Make sure to copy the command line from my comment, I've removed `--remote-debugging-pipe` and `--headless` flags.

**Comment by roylen-john** [comment]
Hi @dgozman. I am working on the same issue. Running the command gives me this error:
```
[1]    72818 killed
```

Tried this on a machine with a similar configuration and it's running fine. Is there any way to get more logs on why the chromium instance is being killed?

**Comment by dgozman** [comment]
@roylen-john @Akshay090 Perhaps the Chromium executable has the different architecture? You can check that by running:

```sh
# prints your architecture
arch
# prints architecture of the executable
file /Users/user-system/Library/Caches/ms-playwright/chromium-1076/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```

**Comment by Akshay090** [comment]
@dgozman thanks for looking into this, 
this issue is resolved for me, it was due to configuration issue with the system, 
i'm closing this issue 👍

**Comment by abourget** [comment]
@akshay090 care to share how you solved it? I'm hitting the same thing.

**Comment by JamisonDong** [comment]
> @dgozman thanks for looking into this, this issue is resolved for me, it was due to configuration issue with the system, i'm closing this issue 👍

Can u share your configuration issue, I had the same problem but it wasn't solved.
