### ISSUE TITLE
[BUG] launchPersistentContext failed

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#2710]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Linux
- Node version: 10.19.0
- Browser: Firefox
- Extra: -

**Code Snippet**

```javascript
const { firefox } = require('playwright');

(async () => {

  const userDataDir = 'profile';
  const browser = await firefox.launchPersistentContext(userDataDir,{
    headless: false
  });
  const page = await browser.newPage();
  await page.goto('https://www.yahoo.com/', {timeout: 60000});

  await browser.close();
})();
```

**Describe the bug**

First time I run the code it's ok, but all other tries fails with

```
(node:16252) UnhandledPromiseRejectionWarning: TimeoutError: Timeout 60000ms exceeded during page.goto.
====================== page.goto logs ======================
navigating to "https://www.yahoo.com/", waiting until "load"
navigated to "https://www.yahoo.com/"
"domcontentloaded" event fired
"load" event fired
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at ProgressController.run (/home/port/projects/PlacerAnalytics/bunraku/node_modules/playwright/lib/progress.js:72:30)
    at Frame.goto (/home/port/projects/PlacerAnalytics/bunraku/node_modules/playwright/lib/frames.js:284:35)
    at Frame.goto (/home/port/projects/PlacerAnalytics/bunraku/node_modules/playwright/lib/helper.js:65:31)
    at Page.goto (/home/port/projects/PlacerAnalytics/bunraku/node_modules/playwright/lib/page.js:191:33)
    at Page.goto (/home/port/projects/PlacerAnalytics/bunraku/node_modules/playwright/lib/helper.js:65:31)
    at /home/port/projects/PlacerAnalytics/bunraku/test_firefox_profile.js:10:14
(node:16252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``` 

but I see the page is already loaded.

**Comment by dgozman** [comment]
Maybe the website does not fire load event in a subframe? Could you please try with domcontentloaded and tell us whether that helps?

```js
await page.goto('https://www.yahoo.com/', {timeout: 60000, waitUntil: 'domcontentloaded'});
```

**Comment by Pooort** [comment]
Thanks for info. The same issue:
```
(node:13448) UnhandledPromiseRejectionWarning: TimeoutError: Timeout 60000ms exceeded during page.goto.
====================== page.goto logs ======================
navigating to "https://www.yahoo.com/", waiting until "domcontentloaded"
navigated to "https://www.yahoo.com/"
"domcontentloaded" event fired
```

It seems like issue related to user data because the first run with empty user data folder is completely ok. It filled with data after the first run and the second time it's always failed.

**Comment by aslushnikov** [comment]
@Pooort This indeed happens for me on v1.1.1, but works just fine on playwright@next (i tried with 1.1.0-next.1593455070108). Looks like it's been fixed already on tip-of-tree!

**Comment by Pooort** [comment]
@aslushnikov Thank you. You're right. It works!
