### ISSUE TITLE
[BUG] - TypeError: Cannot read property 'push' of undefined - When restarting tests

### ISSUE THREAD

**Issue by mwhebert** [microsoft/playwright#2730]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Windows,
- Node version: 10.20.1
- Browser: Chromium
- Extra: using with jest-playwright

**Code Snippet**

I don't have a short code snippet but do have a stacktrace (below)

**Describe the bug**

I will run a set of tests and then "npm run test" again will 'sometimes' cause the exception below.

```
F:\Dev\pw_test\node_modules\playwright-core\lib\server\chromium.js:225
            session.queue.push(parsedMessage);
                          ^

TypeError: Cannot read property 'push' of undefined
    at WebSocket.socket.on (F:\Dev\pw_test\node_modules\playwright-core\lib\server\chromium.js:225:27)        
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (F:\Dev\pw_test\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (F:\Dev\pw_test\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (F:\Dev\pw_test\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (F:\Dev\pw_test\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (F:\Dev\pw_test\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)

```

**Comment by aslushnikov** [comment]
@pavelfeldman: I'm confused. Maybe you have any ideas?

**Comment by mxschmitt** [comment]
@mwhebert can you try the latest beta version? `npm install playwright@next`

Seems to be related to this issue: https://github.com/playwright-community/jest-playwright/issues/158 and will be fixed in the next release.

**Comment by mwhebert** [comment]
Not seeing this after using latest - Thanks!
