### ISSUE TITLE
[Question] Invalid cookie fields error causing the app to crash

### ISSUE THREAD

**Issue by ClaudiuDan** [microsoft/playwright#27473]
I've pasted the error. I am not sure how to debug this, and I am open to suggestions. This happens with Playwright 1.33.0 Python, and it causes all the contexts to crash with the error `Exception('Connection closed while reading from the driver')`.   

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ProtocolError: Protocol error (Storage.setCookies): Invalid cookie fields
    at /home/Traffic/venv/lib/python3.10/site-packages/playwright/driver/package/lib/server/chromium/crConnection.js:169:16
    at new Promise (<anonymous>)
    at CRSession.send (/home/Traffic/venv/lib/python3.10/site-packages/playwright/driver/package/lib/server/chromium/crConnection.js:165:12)
    at CRBrowserContext.addCookies (/home/Traffic/venv/lib/python3.10/site-packages/playwright/driver/package/lib/server/chromium/crBrowser.js:359:34)
    at BrowserContextAPIRequestContext._addCookies (/home/Traffic/venv/lib/python3.10/site-packages/playwright/driver/package/lib/server/fetch.js:400:25)
    at ClientRequest.<anonymous> (/home/Traffic/venv/lib/python3.10/site-packages/playwright/driver/package/lib/server/fetch.js:213:40)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
  sessionClosed: false
}
```

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.
