### ISSUE TITLE
[BUG] Misleading error message on locator timeout

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#27534]
When a test fails to resolve the locator in time, playwright reports, that `Page closed` which is very misleading, because one can understand, that the page was closed in the previous step, and due to that click failed. Yes, there is some `Pending operations` but it is very far away from the first line of error

### System info
- Playwright Version: [v1.3x] - cant say, but appeared in some last versions

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import {defineConfig} from '@playwright/test';

export default defineConfig({
    testDir: './tests',
    forbidOnly: !!process.env.CI,

    workers: process.env.CI ? 1 : undefined,
    reporter: [["list"], ["html", {open: "never"}]],
    use: {
        // headless: false,
        ignoreHTTPSErrors: true,
        screenshot: "off",
        video: "off",
        trace: "retain-on-failure",
        contextOptions: {
            bypassCSP: true,
        },
    },

    projects: [
        {
            name: "Desktop-Chrome",
            use: {
                browserName: "chromium",
                channel: "chrome",
                viewport: {width: 1920, height: 1080},
                launchOptions: {
                    args: ["--disable-web-security"],
                },
            },
        },
    ],

});

```

**Test file (self-contained)**

```js
import { test } from '@playwright/test';

test('bad locator', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  await page.locator("[foo=bar]").click();
});

```

**Steps**
- [Run the test]
- [observe error message]

**Expected**

```
Error: locator.click: Locator not resolved 
```
or something like that

**Actual**

```
Test timeout of 30000ms exceeded.
Error: locator.click: Page closed
=========================== logs ===========================
waiting for locator('[foo=bar]')
============================================================
Pending operations:
  - locator.click at tests/example.spec.ts:6:35
```

**Comment by pavelfeldman** [comment]
Here is what it is now:

```
Test timeout of 30000ms exceeded.
Error: locator.click: Test timeout of 30000ms exceeded.
Call log:
  - waiting for locator('[foo=bar]')


  150 |   await page.goto('https://playwright.dev/');
  151 |
> 152 |   await page.locator('[foo=bar]').click();
      |                                   ^
  153 | });

    at /home/pfeldman/code/playwright/tests/page/page-check.spec.ts:152:35
```

As far as Playwright is concerned, the locator was not resolved because there was not enough time (the element could have appeared in a second). So instead of Page closed you'll see Test timeout exceeded (again :man_shrugging:)

**Comment by pavelfeldman** [comment]
I'll close it as fixed for now.
