### ISSUE TITLE
[BUG] "TypeError: fetch failed" missing cause in @playwright/test output

### ISSUE THREAD

**Issue by WestonThayer** [microsoft/playwright#27577]
### System info
- Playwright Version: 1.38.1
- Operating System: macOS, but shouldn't matter
- Browser: N/A
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({});
```

**Test file (self-contained)**

```js
it('attempts fetch', async () => {
  await fetch("http://127.0.0.1:1337/non-existent");
});
```

**Steps**
- Run the test

**Expected**

The useful details of the `TypeError` are logged:

```
npx playwright test foo

Running 1 test using 1 worker
  1) foo.spec.mjs:6:1 › attempts fetch ────────────────────────────────────────────────────────────────────────

    TypeError: fetch failed
      cause: Error: connect ECONNREFUSED 127.0.0.1:1337
          at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
        errno: -61,
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 1337

       5 |
       6 | it("attempts fetch", async () => {
    >  7 |   await fetch("http://127.0.0.1:1337/non-existent");
         |   ^
       8 | });

        at /foo.spec.mjs:7:3

  1 failed
    foo.spec.mjs:6:1 › it attempts fetch ─────────────────────────────────────────────────────────────────────────

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
```

**Actual**

```
npx playwright test foo

Running 1 test using 1 worker
  1) foo.spec.mjs:6:1 › attempts fetch ────────────────────────────────────────────────────────────────────────

    TypeError: fetch failed

       5 |
       6 | it("attempts fetch", async () => {
    >  7 |   await fetch("http://127.0.0.1:1337/non-existent");
         |   ^
       8 | });

        at /foo.spec.mjs:7:3

  1 failed
    foo.spec.mjs:6:1 › it attempts fetch ─────────────────────────────────────────────────────────────────────────

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
```

## Notes

Workaround is to `try/catch` and `console.log(error)` yourself, then re-throw.

**Comment by dgozman** [comment]
Merging into #26848. Please upvote #26848 to help us prioritize.
