### ISSUE TITLE
[REGRESSION]: Unexpected token '<' when importing SVGs & React is not defined in CRA

### ISSUE THREAD

**Issue by SetupCoding** [microsoft/playwright#27727]
**Context:**
- GOOD Playwright Version: @playwright/test v1.31.2
- BAD Playwright Version: @playwright/test v1.33.0
- Operating System: Mac
- Extra: Project bootstrapped with create react app (**not** ejected)

**Code Snippet**
```typescript
// App.tsx

import { ReactComponent as SomeSVGIcon } from './icons/some.svg';

export const App = () => {  
  return (
    <div>      
      <SomeSVGIcon />      
    </div>
  );
};
```
```typescript
// sitemap.tsx
import { Navigate } from 'react-router-dom';
import type { RouteObject } from 'react-router-dom';
import { App } from './App';
import { SubRouteComponent } from './SubRouteComponent';

type Route = RouteObject & { displayName: string };

export const DEFAULT_ROUTE = '/a';

export const paths = {
  a: '/a',
  ...
};

export const sitemap: Route[] = [
  {
    path: paths.a,
    element: <SubRouteComponent />,
    displayName: 'SubRouteComponent',
  },
  ...
];

export const routes: RouteObject[] = [
  {
    path: '/',
    element: <App />,
    children: [
      ...sitemap.map(({ path, element }) => ({ path, element: <AuthGuard>{element}</AuthGuard> })),
    ],
  },
  // Redirect all other paths to App
  {
    path: '*',
    element: <Navigate to={'/'} />,
  },
];
```

```typescript
// App.spec.ts
import type { Page } from '@playwright/test';
import { environment } from '../src/environments';
import { paths } from '../src/sitemap';
...
```

```typescript
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: './tests',
  timeout: 120 * 1000,
  expect: {
    timeout: 5000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: 'list',
  use: {
    actionTimeout: 0,
    baseURL: process.env.URL || 'http://localhost:3000',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        permissions: ['clipboard-read', 'clipboard-write'],
      },
    },
  ],
  webServer: {
    command: 'REACT_APP_STAGE=playwright npm start',
    port: 3000,
    timeout: 480 * 1000,
    reuseExistingServer: true,
  },
};

export default config;
```

**Describe the bug**

If I try to run `npx playwright test` on version 1.33.0 the following error occurs:
```jsx
SyntaxError: Unexpected token '<'

   at ../src/App.tsx:1

> 1 | import { ReactComponent as SomeSVGIcon } from './icons/some.svg';
    | ^
  2 |
  3 | export const App = () => {  
  4 |   return (

    at Object.<anonymous> (/PRIVATE/project/src/App.tsx:1:1)
    at Object.<anonymous> (/PRIVATE/project/src/sitemap.tsx:3:1)
    at Object.<anonymous> (/PRIVATE/project/tests/App.spec.ts:3:1)
```

If I remove the svg to get rid of the first error I also have to manually import `import React from 'react';` in the sitemap.tsx file, otherwise I get the following error running `npx playwright test`:

```jsx
ReferenceError: React is not defined

   at ../src/sitemap.tsx:24

  22 |   {
  23 |     path: paths.a,
> 24 |     element: <SubRouteComponent />,
     |              ^
  25 |     displayName: 'SubRouteComponent',
  26 |   },
  27 |   {

    at Object.<anonymous> (/PRIVATE/project/src/sitemap.tsx:24:14)
    at Object.<anonymous> (/PRIVATE/project/tests/App.spec.ts:3:1)
```

**Comment by yury-s** [comment]
This problem is that ` <SubRouteComponent />` is instantiated when sitemap.tsx is being loaded and `const sitemap` is being initialized. Folding this into https://github.com/microsoft/playwright/issues/19320

**Comment by SetupCoding** [comment]
What about the first issue of playwright not handling imported svgs correctly?

**Comment by lorenzo-del-rosario** [comment]
@yury-s I can still reproduce the same issue importing SVGs in `1.42.1`.
In a Remix project:
```
import favicon from '~/../public/favicon.svg';
...
export const links: LinksFunction = () => {
  return [
    {rel: 'icon', type: 'image/svg+xml', href: favicon},
   ...
  ];
};
```

```
import footerFlowerSvg from '../../public/footer-flower.svg';
...
<img src={footerFlowerSvg} alt="Logo" />
```
