### ISSUE TITLE
[Question] An error occurs when refreshing at a certain interval in the loop within an asynchronous function and cannot be caught.

### ISSUE THREAD

**Issue by PracticeofEno** [microsoft/playwright#27908]
### System info
- Playwright Version: [v1.39.0
- Operating System: [ Ubuntu 22.04.3 in Docker in Windows 10 ]
- Browser: [ Chromium ]
- Language : python 3.10.12

First of all, I apologize for not being familiar with English.
I'm trying to do web parsing using playwright.
Because it is used within fastapi, it is used in asynchronous form.
playwright was created in the form below.
```python
apw = await async_playwright().start()
self.browser = await apw.chromium.launch(headless=False)
context = await self.browser.new_context(
    viewport={"width": 1500, "height": 900}, 
    locale="ko-KR",
)
self.page = await context.new_page()
await self.page.goto("some page")
```
After that, it receives the request and asynchronously calls a function that repeats infinitely.
```python
asyncio.create_task(loop2())
```
The loop2 function simply calls the class that has playwright as a property every 10 seconds to parse from playwright.
```python
async def loop2():
    while True:
        await my_class.parse_function()
        await asyncio.sleep(10)
```

The parse_function() function performs the following actions:
When a bookmark request comes in to fastapi, the bookmark request is made using playwright appropriately.
After calling the backend API to compare the lists and extract the desired list,
Call the response API.
I wanted to do this at 10 second intervals.
```python
try:
      print("[start night watch] - BookMark Start")
      for book_mark_id in self.bookmark_list:
          await self.set_book_mark(book_mark_id, True)
          await asyncio.sleep(0.1)
      self.bookmark_list.clear()
      print("[start night watch] - get_user_status")
      idle_users, live_users = await self.get_user_status()
      print("[start night watch] - Api Calls")
      backend_live_users = requests.get(
          url=f"http://{self.backend_url}:{self.backend_port}/user?mode=playing",
          timeout=5,
      ).json()
      backend_idle_users = requests.get(
          f"http://{self.backend_url}:{self.backend_port}/user?mode=idle",
          timeout=5,
      ).json()
      print("[start night watch] - filter_dict_by_list")
      wanted_play_list = self.filter_dict_by_list(live_users, backend_idle_users)
      wanted_stop_list = self.filter_dict_by_list(idle_users, backend_live_users)
      print(f"watned play lsit = {wanted_play_list}")
      print(f"watend stop list = {wanted_stop_list}")
      if len(wanted_play_list) > 0:
          requests.post(
              url=f"http://{self.backend_url}:{self.backend_port}/resource/task",
              json={"ids": wanted_play_list},
              timeout=5,
          )
      if len(wanted_stop_list) > 0:
          requests.delete(
              url=f"http://{self.backend_url}:{self.backend_port}/resource/task",
              json={"ids": wanted_stop_list},
              timeout=5,
          )
      await asyncio.sleep(5)
      print("[start night watch] - refresh start")
      await self.refresh()
      print("[start night watch] - refresh ended")
      await asyncio.sleep(5)
      print("[start night watch] - ENDED")
except Exception as e:  # pylint: disable=W0718
            print(e)
            print("awfpjfpajfpojofawepojfawepjofawepofpao")

async def refresh(self):
        """refresh"""
        await self.page.reload()
```

It works well at first, but over time, at some point, the operation stops with the error message below.
```
[start night watch] - refresh start
[start night watch] - refresh ended
[start night watch] - ENDED
[start night watch] - BookMark Start
[start night watch] - get_user_status
[start night watch] - Api Calls
[start night watch] - filter_dict_by_list
watned play lsit = []
watend stop list = []
[start night watch] - refresh start
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Connection.run() done, defined at /root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_connection.py:267> exception=AttributeError("'dict' object has no attribute '_object'")>
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 276, in run
    await self._transport.run()
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_transport.py", line 163, in run
    self.on_message(obj)
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 235, in <lambda>
    self._transport.on_message = lambda msg: self.dispatch(msg)
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 393, in dispatch
    self._create_remote_object(
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 443, in _create_remote_object
    result = self._object_factory(parent, type, guid, initializer)
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_object_factory.py", line 67, in create_remote_object
    return Frame(parent, type, guid, initializer)
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 78, in __init__
    self._parent_frame = from_nullable_channel(initializer.get("parentFrame"))
  File "/root/.local/share/virtualenvs/localServer-8gKvcJZF/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 513, in from_nullable_channel
    return channel._object if channel else None
AttributeError: 'dict' object has no attribute '_object'
```
The above error occurs frequently enough to be seen more than 6 times a day, and when I logged it to find the location of the error, it seemed to always occur on refresh.
Because I added the await keyword in front of refresh, I attempted to catch the exception and handle it appropriately when an error occurred, but I was unable to catch it. My guess is that the error occurs in the part that uses asynchrony in the refresh function.
What did I use wrong? How can I fix it?
Thank you for your help and for reading.

**Comment by pavelfeldman** [comment]
This does not look like a bug report or a feature request for Playwright, hence closing.
