### ISSUE TITLE
[BUG] Unknown type ConsoleMessage when using remote server with Java client

### ISSUE THREAD

**Issue by orange-buffalo** [microsoft/playwright#27972]
### System info
- Playwright Version: v1.39.0
- Operating System: All
- Browser: Chromium (maybe others as well)

### Source code

Consider a server launched from Node.js:
```js
const browserServer = await browserType.launchServer(config);
const wsEndpoint = browserServer.wsEndpoint();
...
```

Then Java client connecting to this remote server:
```java
var chromiumBrowser = playwright.chromium().connect(wsEndpoint);
```

Then try opening a page using this remote browser:
```java
var page = chromiumBrowser.newPage();
page.navigate("https://github.com/microsoft/playwright");
```

A full-fledged reproducer can be found in [testcontainers-playwright project](https://github.com/orange-buffalo/testcontainers-playwright/blob/dependabot/gradle/com.microsoft.playwright-playwright-1.39.0/src/test/kotlin/io/orangebuffalo/testcontainers/playwright/PlaywrightExtensionTest.kt#L27). If it is not possible to find the issue analytically, I can try preparing a confined reproducer, but it will take some time.

**Expected**

Page is opened in the remote browser.

**Actual**

Exception:
```
com.microsoft.playwright.PlaywrightException: Unknown type ConsoleMessage
	at com.microsoft.playwright.impl.Connection.createRemoteObject(Connection.java:364)
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:237)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:206)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:118)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106)
	at com.microsoft.playwright.impl.FrameImpl.navigateImpl(FrameImpl.java:463)
	at com.microsoft.playwright.impl.PageImpl.lambda$navigate$45(PageImpl.java:827)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89)
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:827)
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:42)
	at com.microsoft.playwright.Page.navigate(Page.java:5282)
```

**Notes**
This worked without issues in `1.38.0`

**Comment by mxschmitt** [comment]
Your Docker server version, probably this one: https://github.com/orange-buffalo/testcontainers-playwright/blob/757d14c6771a71c96d21ed1c48363a3a2bcdd39b/src/main/docker/Dockerfile#L4

needs to align with the Playwright for Java client version. Otherwise it won't work.

Starting from the next version, we'll throw a better reasonable error to prevent errors like this.

**Comment by orange-buffalo** [comment]
Thank you for the feedback. We are aware about this limitation and have auto-detect functionality that selects a proper version of Docker image based on classpath Java client. However, we had a bug in Docker image that did not properly propagate the Playwright version and used the default one. We now fixed it and the problem is resolved.

Sorry for bothering you with this issue, and thanks for the help.
