### ISSUE TITLE
Uploading  Files is not working on Selenium grid 

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#28081]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Linux]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

```java
public void uploadDocument() {
   
        String filename="/src/test/resources/testData/UploadFiles/sampleTest.pdf";
        Path pathToFile = Paths.get(filename);
        System.out.println(pathToFile.toAbsolutePath());
        page.locator(idDocumentBtn).setInputFiles(pathToFile.toAbsolutePath());
        page.locator(validCloseBtn).click();
}

*
```

*

**Steps**
- [Run the test]
- [...]
-    

**Expected**

  We expected to upl;oad files succesffully on selenium grid . Some how our script is passing locally but unfortunately when we try to run the scripts on grid we get below error 

```java
com.microsoft.playwright.PlaywrightException: Cannot get file size.
	at com.microsoft.playwright.impl.Utils.hasLargeFile(Utils.java:185)
	at com.microsoft.playwright.impl.FrameImpl.setInputFilesImpl(FrameImpl.java:764)
	at com.microsoft.playwright.impl.FrameImpl.lambda$setInputFiles$35(FrameImpl.java:760)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.FrameImpl.setInputFiles(FrameImpl.java:760)
	at com.microsoft.playwright.impl.FrameImpl.setInputFiles(FrameImpl.java:746)
	at com.microsoft.playwright.impl.LocatorImpl.setInputFiles(LocatorImpl.java:526)
	at com.microsoft.playwright.Locator.setInputFiles(Locator.java:4741)
	at pages.IRIS.IdDocStep.uploadDocument(IdDocStep.java:91)
	at stepdefinitions.IrisSteps.iFillOutTheCustomerIdentificationDetails(IrisSteps.java:254)
	at ✽.I fill out the customer identification details for the country "xx"(file:///tcpBase/src/test/resources/features/x/xx.feature:13)
Caused by: java.nio.file.NoSuchFileException: /src/test/resources/testData/UploadFiles/sampleTest.pdf
```

is there any feature in playwright like setFileDectector  to set remote file detector? 
**Actual**

[Describe actual behavior]

**Comment by yury-s** [comment]
> `java.nio.file.NoSuchFileException: /src/test/resources/testData/UploadFiles/sampleTest.pdf`

There is no such file on the machine where you are running playwright test. Make sure to copy the file at the specified location.

> is there any feature in playwright like setFileDectector to set remote file detector?

No. We expect the files so be on the same machine where you run playwright client. Alternatively, you can pass `FilePayload` with the file data.

**Comment by mridiniveni** [comment]
Thanks for checking , actually on my local machine its working the path i mentioned is correct and its perfectly working , only i see issue on grid some how its not finding the path the grid is on container. 

    I tried with with Filepayload with below code and i see the size of the file is Zero bytes , am i doing anything wrong?can u please suggest most of the scenarios we use upload functionality apparantely they were failing now on grid :(

**Comment by mxschmitt** [comment]
This should be fixed in 1.40. I recommend waiting until we released 1.40 in a few days and retrying there again.

**Comment by mridiniveni** [comment]
perfect thanks will wait for the version 1.40

**Comment by mridiniveni** [comment]
Hi I tried with 1.40  version now i see the size of the file is 46 KB  but some how its unable to upload the file please check below screenshot
page.locator(locator).setInputFiles(new FilePayload("sampleTest.pdf","application/pdf","this is sample pdf ;".getBytes(StandardCharsets.UTF_8)));


<img width="566" alt="image" src="https://github.com/microsoft/playwright/assets/113676808/81cbcd7b-8df8-4d01-805a-780e67523bb9">
