### ISSUE TITLE
[BUG] initializationError com.microsoft.playwright.PlaywrightException:  and Caused by: com.microsoft.playwright.impl.DriverException: Error {   message='

### ISSUE THREAD

**Issue by tejaswikommineni** [microsoft/playwright#28130]
### System info
- Playwright Version: [v1.39.0] java
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: the below error occurs when we have deployed the "mcr.microsoft.com/playwright/java:v1.38.0-jammy" image in the openshift and try to run the playwright javatest in the jenkins pipeline.

### sourcecode:

public static void initiateBrowser() {
        playwright = Playwright.create();
        {
            browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));

            BrowserContext context = browser.newContext(new Browser.NewContextOptions()
                    .setIgnoreHTTPSErrors(true));
            // Create a new page in a pristine context.
            context.setDefaultTimeout(60000);
            page = context.newPage();

        }

### error: Failed tests
initializationError
com.microsoft.playwright.PlaywrightException: Error {
  message='
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libnss3.so                                       ║
║     libnssutil3.so                                   ║
║     libsmime3.so                                     ║
║     libnspr4.so                                      ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libdrm.so.2                                      ║
║     libdbus-1.so.3                                   ║
║     libxcb.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libatspi.so.0                                    ║
║     libX11.so.6                                      ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
║     libasound.so.2                                   ║
╚══════════════════════════════════════════════════════╝
  name='Error
  stack='Error: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libnss3.so                                       ║
║     libnssutil3.so                                   ║
║     libsmime3.so                                     ║
║     libnspr4.so                                      ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libdrm.so.2                                      ║
║     libdbus-1.so.3                                   ║
║     libxcb.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libatspi.so.0                                    ║
║     libX11.so.6                                      ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
║     libasound.so.2                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/tmp/playwright-java-1664140527048938675/package/lib/server/registry/dependencies.js:216:9)
    at async Registry._validateHostRequirements (/tmp/playwright-java-1664140527048938675/package/lib/server/registry/index.js:628:43)
    at async Chromium._launchProcess (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:167:7)
    at async Chromium._innerLaunch (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:103:9)
    at async Chromium._innerLaunchWithRetries (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:84:14)
    at async ProgressController.run (/tmp/playwright-java-1664140527048938675/package/lib/server/progress.js:92:22)
    at async Chromium.launch (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:61:21)
    at async BrowserTypeDispatcher.launch (/tmp/playwright-java-1664140527048938675/package/lib/server/dispatchers/browserTypeDispatcher.js:35:21)
    at async DispatcherConnection.dispatch (/tmp/playwright-java-1664140527048938675/package/lib/server/dispatchers/dispatcher.js:346:22)
}
	at app//com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
	at app//com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:120)
	at app//com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
	at app//com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106)
	at app//com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:50)
	at app//com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:42)
	at app//com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at app//com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89)
	at app//com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:42)
	at app//com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:35)
	at app//se.swedbank.uitests.pages.InstantiatePage.initiateBrowser(InstantiatePage.java:14)
	at app//se.swedbank.uitests.PlaywrightPageTest.preconditionTestCaseLevel(PlaywrightPageTest.java:11)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$9(ClassBasedTestDescriptor.java:384)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:382)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:196)
	at app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base@17.0.3/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.3/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libnss3.so                                       ║
║     libnssutil3.so                                   ║
║     libsmime3.so                                     ║
║     libnspr4.so                                      ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libdrm.so.2                                      ║
║     libdbus-1.so.3                                   ║
║     libxcb.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libatspi.so.0                                    ║
║     libX11.so.6                                      ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
║     libasound.so.2                                   ║
╚══════════════════════════════════════════════════════╝
  name='Error
  stack='Error: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libnss3.so                                       ║
║     libnssutil3.so                                   ║
║     libsmime3.so                                     ║
║     libnspr4.so                                      ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libdrm.so.2                                      ║
║     libdbus-1.so.3                                   ║
║     libxcb.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libatspi.so.0                                    ║
║     libX11.so.6                                      ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
║     libasound.so.2                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/tmp/playwright-java-1664140527048938675/package/lib/server/registry/dependencies.js:216:9)
    at async Registry._validateHostRequirements (/tmp/playwright-java-1664140527048938675/package/lib/server/registry/index.js:628:43)
    at async Chromium._launchProcess (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:167:7)
    at async Chromium._innerLaunch (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:103:9)
    at async Chromium._innerLaunchWithRetries (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:84:14)
    at async ProgressController.run (/tmp/playwright-java-1664140527048938675/package/lib/server/progress.js:92:22)
    at async Chromium.launch (/tmp/playwright-java-1664140527048938675/package/lib/server/browserType.js:61:21)
    at async BrowserTypeDispatcher.launch (/tmp/playwright-java-1664140527048938675/package/lib/server/dispatchers/browserTypeDispatcher.js:35:21)
    at async DispatcherConnection.dispatch (/tmp/playwright-java-1664140527048938675/package/lib/server/dispatchers/dispatcher.js:346:22)
}
	at app//com.microsoft.playwright.impl.Connection.dispatch(Connection.java:226)
	at app//com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:206)
	at app//com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:118)

**Comment by mxschmitt** [comment]
How does your Jenkinsfile look like?

**Comment by tejaswikommineni** [comment]
@Library(['
        'jenkins-shared-library']) _

pipeline {
    agent {
        kubernetes {
            cloud ''
            inheritFrom ''
            yamlMergeStrategy merge()
            yamlFile 'application.pod'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: "5"))
        disableConcurrentBuilds()
        timestamps()
    }

    stages {
        stage('Notify bitbucket') {
            steps {
                script {
                    bitbucketHandler.notifyBuildStart([
                            displayName   : "${env.JOB_NAME}",
                            displayMessage: "Build ${env.BUILD_ID} started at ${env.BUILD_TIMESTAMP}.",
                            branchName    : "${env.BRANCH_NAME}"
                    ])
                }
            }
        }
        stage('UI Tests') {
            steps {
                container('gradle') {
                      sh("sleep 5m")
                      sh ("gradle Tests")
                }
            }
            post{
                always{
                    container('gradle') {
                                                 archiveArtifacts allowEmptyArchive: true, artifacts: 'build/reports/tests/**/*.png', followSymlinks: false
                                                 archiveArtifacts allowEmptyArchive: true, artifacts: 'build/reports/tests/**/*.html', followSymlinks: false
                                                 junit '**/test-results/*.xml'
                                             }
                }
            }
        }
    }
    post {
        success{
            script {
                bitbucketHandler.notifyBuildSuccess([
                        displayName   : "${env.JOB_NAME}",
                        displayMessage: "Build ${env.BUILD_ID} completed at ${env.BUILD_TIMESTAMP}.",
                        branchName: "${env.BRANCH_NAME}"
                ])
            }
        }
        failure{
            sendEmail([
                    to: '', //get it on our jira board as opportunity
                    subject: "Test execution failed: ${env.JOB_NAME}",
                    body: "See ${env.BUILD_URL} for more details",
            ])
            script {
            bitbucketHandler.notifyBuildFail([
                    displayName   : "${env.JOB_NAME}",
                    displayMessage: "Build ${env.BUILD_ID} failed at ${env.BUILD_TIMESTAMP}.",
                    branchName: "${env.BRANCH_NAME}"
            ])
            }
        }
        always{
            cleanWs()
        }
    }
}

**Comment by mxschmitt** [comment]
Looks like you are not running inside the Playwright Docker container as per https://playwright.dev/docs/ci#jenkins

**Comment by mxschmitt** [comment]
Looks like you are not using an Linux which has all the dependencies satisfied. We either recommend [installing them](https://playwright.dev/docs/browsers#install-system-dependencies) or using our [Docker image](https://playwright.dev/docs/docker (see [here for via Jenkins](https://playwright.dev/docs/ci#jenkins)).

**Comment by tejaswikommineni** [comment]
we use openshift where we try to deploy the playwright image.only the difference is we try to use gradle.
