### ISSUE TITLE
[BUG] Won't launch Chromium inside Node Alpine Docker container 

### ISSUE THREAD

**Issue by jaequery** [microsoft/playwright#2826]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Dockerized Alpine Linux
- Node version: 12.14
- Browser: Chromium
- Extra: Docker node:12.14-alpine

**Code Snippet**

Dockerfile
```
FROM node:12.14-alpine

# Install dependencies (i.e. for compiling bcrypt)
RUN apk --no-cache add --virtual native-deps g++ gcc libgcc libstdc++ linux-headers autoconf automake make nasm python git chromium                                          && \
  npm install --quiet node-gyp -g
```

Code:
```javascript
const browser = await playwright.chromium.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
});
```

**Describe the bug**

Playwright is working fine on our local machines (OSX) but once we deploy it to our staging environment, which is in Docker, we get this error complaining can't launch browser:

```

2020-07-02T15:25:03.614-07:00 | [31m[Nest] 32   - [39m07/02/2020, 10:25:03 PM   [38;5;3m[ExceptionsHandler] [39m[31mFailed to launch browser: Error: spawn /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome ENOENT
-- | --
  | 2020-07-02T15:25:03.614-07:00 | =================== chromium.launch logs ===================
  | 2020-07-02T15:25:03.614-07:00 | <launching> /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-LahnmC --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --no-sandbox --disable-setuid-sandbox --no-startup-window
  | 2020-07-02T15:25:03.614-07:00 | ============================================================
  | 2020-07-02T15:25:03.614-07:00 | Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.[39m[38;5;3m +851342ms[39m
  | 2020-07-02T15:25:03.614-07:00 | Error: Failed to launch browser: Error: spawn /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome ENOENT
  | 2020-07-02T15:25:03.614-07:00 | =================== chromium.launch logs ===================
  | 2020-07-02T15:25:03.614-07:00 | <launching> /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-LahnmC --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --no-sandbox --disable-setuid-sandbox --no-startup-window
  | 2020-07-02T15:25:03.614-07:00 | ============================================================
  | 2020-07-02T15:25:03.614-07:00 | Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
  | 2020-07-02T15:25:03.614-07:00 | at ChildProcess.<anonymous> (/usr/app/node_modules/playwright/lib/server/processLauncher.js:51:20)
  | 2020-07-02T15:25:03.614-07:00 | at Object.onceWrapper (events.js:313:26)
  | 2020-07-02T15:25:03.614-07:00 | at ChildProcess.emit (events.js:223:5)
  | 2020-07-02T15:25:03.614-07:00 | at ChildProcess.EventEmitter.emit (domain.js:475:20)
  | 2020-07-02T15:25:03.614-07:00 | at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
  | 2020-07-02T15:25:03.614-07:00 | at onErrorNT (internal/child_process.js:456:16)
  | 2020-07-02T15:25:03.614-07:00 | at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Please help! Thank you.

**Comment by aslushnikov** [comment]
@jaequery I see the following in your log: 

```
Error: Failed to launch browser: Error: spawn /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome ENOENT
```

It looks like Playwright didn't download browser inside of your docker container. Did you run `npm install` inside your docker?

**Comment by jaequery** [comment]
@aslushnikov i did, here's the reset of the Dockerfile

```
FROM node:12.14-alpine

# Install dependencies (i.e. for compiling bcrypt)
RUN apk --no-cache add --virtual native-deps \
  g++ gcc libgcc libstdc++ linux-headers autoconf automake make nasm python git chromium                                          && \
  npm install --quiet node-gyp -g

WORKDIR /usr/app

ARG NPM_TOKEN
COPY package.json .
COPY docker/.npmrc .
COPY docker/start-script.sh .
RUN chmod a+x ./start-script.sh
RUN npm install --loglevel=error --production
RUN node ./node_modules/playwright/install.js
RUN rm -f .npmrc
RUN apk del native-deps

# Pass in the NODE_ENV variable or default to `development`
ARG NODE_ENV=development
ENV NODE_ENV ${NODE_ENV}

COPY build ./
RUN npm install pm2 -g --loglevel=error

EXPOSE 3000

CMD ["./start-script.sh"]
```

**Comment by aslushnikov** [comment]
Ah, it's alpine! I missed it.

Playwright executables won't run on Alpine - we currently build for Debian only. Can you base off our official docker image instead?

- `FROM mcr.microsoft.com/playwright:bionic`

**Comment by jaequery** [comment]
oh, shucks, that'd be a problem then. Is there a way to execute playwright remotely (separate server / container)?

**Comment by aslushnikov** [comment]
@jaequery yes, we have a concept of [`browserServer`](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=class-browserserver)

- server could be launched with [`browserType.launchServer()`](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypelaunchserveroptions) method
- once server is launched, use [`browserServer.wsEndpoint()`](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browserserverwsendpoint) to get the websocket endpoint to connect
- you can use the `wsEndpoint` later to connect to the server using [`browserType.connect()`](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypeconnectoptions)

**Comment by jaequery** [comment]
okay thanks. any idea when you guys will have support for Alpine?

**Comment by aslushnikov** [comment]
It's not planned as of today. Chromium doesn't bake continuous builds for Alpine, so this is something that would not be coming any time soon.

**Comment by jaequery** [comment]
@aslushnikov are you aware of this? https://github.com/Zenika/alpine-chrome#how-to-use-with-playwright
Looks like they have an Alpine based Docker container for running Playwright.

I haven't tried this yet but I'm wondering if you are aware of this and if this would work?

**Comment by aslushnikov** [comment]
> are you aware of this? https://github.com/Zenika/alpine-chrome#how-to-use-with-playwright
Looks like they have an Alpine based Docker container for running Playwright.

@jaequery This looks very nice! Thank you for pointing it here!
