### ISSUE TITLE
[Question] Need info for Error Handling and Debug log collections

### ISSUE THREAD

**Issue by kdivekar** [microsoft/playwright#2829]
Hi,

I am looking to add more logs and error handling in my automation framework.

1. Since I updated playwright to 1.1.0 , DEBUG=pw:input stopped working, has this changed?
2. Is there way I collect these logs only when there is a failure? like only in Catch block?
3. Right now I use TimeoutError to catch the timeouts like below, are there any other error classes available to catch api exception? Could not find any other in Document.
 catch (err) {
if ( err instanceof playwright.errors.TimeoutError ) {
 console.log(err)
} 
}

Regards,
-KD.

**Comment by aslushnikov** [comment]
> Since I updated playwright to 1.1.0 , DEBUG=pw:input stopped working, has this changed?

@kdivekar This is renamed into `pw:api` now.

> Is there way I collect these logs only when there is a failure? like only in Catch block?

Currently all exceptions that Playwright throws also include a block with debugging info. Here's an example of a timeout for `page.click()` method:

```sh
(node:36731) UnhandledPromiseRejectionWarning: TimeoutError: Timeout 100ms exceeded during page.click.
===================== page.click logs =====================
[api] waiting for selector "foobar"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at ProgressController.run (/Users/aslushnikov/prog/playwright/lib/progress.js:73:30)
    at Object.runAbortableTask (/Users/aslushnikov/prog/playwright/lib/progress.js:29:23)
    at Page._runAbortableTask (/Users/aslushnikov/prog/playwright/lib/page.js:86:27)
    at Frame._retryWithSelectorIfNotConnected (/Users/aslushnikov/prog/playwright/lib/frames.js:604:27)
    at Frame.click (/Users/aslushnikov/prog/playwright/lib/frames.js:627:20)
    at Frame.click (/Users/aslushnikov/prog/playwright/lib/helper.js:79:31)
    at /Users/aslushnikov/prog/playwright/lib/page.js:363:61
    at Page._attributeToPage (/Users/aslushnikov/prog/playwright/lib/page.js:356:20)
    at Page.click (/Users/aslushnikov/prog/playwright/lib/page.js:363:21)
    at Page.click (/Users/aslushnikov/prog/playwright/lib/helper.js:79:31)
  -- ASYNC --
    at Frame.click (/Users/aslushnikov/prog/playwright/lib/helper.js:78:23)
    at /Users/aslushnikov/prog/playwright/lib/page.js:363:61
    at Page._attributeToPage (/Users/aslushnikov/prog/playwright/lib/page.js:356:20)
    at Page.click (/Users/aslushnikov/prog/playwright/lib/page.js:363:21)
    at Page.click (/Users/aslushnikov/prog/playwright/lib/helper.js:79:31)
    at /Users/aslushnikov/prog/playwright/a.js:8:14
```

> Right now I use TimeoutError to catch the timeouts like below, are there any other error classes available to catch api exception?

Not yet! But we expect them to appear over time. 

Hope this helps!
