### ISSUE TITLE
[BUG]Object with guid ${arg.guid} was not bound in the connection

### ISSUE THREAD

**Issue by leodoi3** [microsoft/playwright#28320]
### System info
- Playwright Version: 1.40.0
- Operating System: Windows, Ubuntu
- Browser: Chromium
- Other info:

### Source code
test.js
```
const { chromium } = require('playwright')
chromium.launch({ headless: false}).then(async (/** @type {import("playwright-core").Browser } */ browser) => {
        let page = await browser.newPage()
        for(let i = 0; i < 10000; i++) {
            console.log(`Running ${i + 1}`)
            await page.goto('https://youtube.com', { waitUntil: 'domcontentloaded', timeout: 60000 })
        }
        await browser.close()
})
```

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

// playwright.config.ts

```
// @ts-check
const { defineConfig, devices } = require('@playwright/test');

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * @see https://playwright.dev/docs/test-configuration
 */
module.exports = defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
```

**Steps**
- Run node test.js
- Wait for the loop to reach about 1000

**Expected**

I shouldn't get any errors. 

**Actual**

I get this error

Uncaught Error Error: Object with guid frame@deace9a6164e8df96a984cda471e3c88 was not bound in the connection
    at _tChannelImplFromWire (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/client/connection.js:207:26)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:129:20)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:91:12)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:108:21)
    at _createRemoteObject (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/client/connection.js:218:19)
    at dispatch (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/client/connection.js:175:12)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/inProcessFactory.js:48:83)
    at processImmediate (node:internal/timers:471:21)
    at callbackTrampoline (node:internal/async_hooks:130:17)
    --- Immediate ---
    at init (node:internal/inspector_async_hook:25:19)
    at emitInitNative (node:internal/async_hooks:202:43)
    at emitInitScript (node:internal/async_hooks:505:3)
    at initAsyncResource (node:internal/timers:159:5)
    at Immediate (node:internal/timers:615:5)
    at setImmediate (node:timers:302:10)
    at dispatcherConnection.onmessage (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/inProcessFactory.js:48:47)
    at _sendMessageToClient (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:201:10)
    at sendCreate (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:172:10)
    at Dispatcher (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:70:40)
    at FrameDispatcher (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/dispatchers/frameDispatcher.js:42:5)
    at from (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/dispatchers/frameDispatcher.js:34:22)
    at _onFrameAttached (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/dispatchers/pageDispatcher.js:280:47)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/dispatchers/pageDispatcher.js:76:75)
    at emit (node:events:513:28)
    at frameAttached (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/frames.js:107:18)
    at _onFrameAttached (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/chromium/crPage.js:549:30)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/chromium/crPage.js:380:373)
    at emit (node:events:513:28)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/chromium/crConnection.js:166:14)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:442:9)
    at callbackTrampoline (node:internal/async_hooks:130:17)
    --- Promise.then ---
    at _onMessage (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/chromium/crConnection.js:164:25)
    at _onMessage (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/chromium/crConnection.js:76:26)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/pipeTransport.js:77:44)
    at processImmediate (node:internal/timers:471:21)
    at callbackTrampoline (node:internal/async_hooks:130:17)
    --- Immediate ---
    at init (node:internal/inspector_async_hook:25:19)
    at emitInitNative (node:internal/async_hooks:202:43)
    at emitInitScript (node:internal/async_hooks:505:3)
    at initAsyncResource (node:internal/timers:159:5)
    at Immediate (node:internal/timers:615:5)
    at setImmediate (node:timers:302:10)
    at _dispatch (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/pipeTransport.js:76:12)
    at <anonymous> (file:///C:/Users/matte/Repos/playwright/node_modules/playwright-core/lib/server/pipeTransport.js:37:40)
    at emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at onStreamRead (node:internal/stream_base_commons:190:23)
    at callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by mtsarev** [comment]
I have the very same issue. For me, it crashes after exactly 143 visited pages constantly.

**Comment by mirao** [comment]
I had similar error on a page with thousands elements in a drop down menu: #27704
A difference is that in my case the error message was about "handle", whereas an error message in this bug is about "frame"

**Comment by mxschmitt** [comment]
I can repro after 498 iterations.

**Comment by bmax** [comment]
I also am having this issue, is it not because of a not-awaited promise, or, an promise that resolves after the connection is done? The issue is mentioned [here](https://github.com/microsoft/playwright/issues/21210) as well.

I have a page.on('download') (need to figure out how to make this not trigger after page close) and am getting this error around 63 iterations

**Comment by I116M** [comment]
Creating and closing a browser repeatedly can be slow and inefficient, but it might resolve the issue.

```javascript
const { chromium } = require("playwright");

(async () => {
    for (let i = 0; i < 10000; i++) {
        const browser = await chromium.launch({ headless: false });
        const page = await browser.newPage();
        await page.goto("https://youtube.com", { waitUntil: "domcontentloaded", timeout: 60000 });
        console.log(`Running ${i + 1}`);
        await browser.close();
    }
})();
