### ISSUE TITLE
[BUG]vscode+playwirght plugin, run test is ok, debug with error: playwright\lib\transform\babelBundleImpl.js:37:3587

### ISSUE THREAD

**Issue by bi-kai** [microsoft/playwright#28347]
### System info
- Playwright Version: "@playwright/test": "^1.39.0",
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:
![image](https://github.com/microsoft/playwright/assets/15070379/a52c5730-4532-480d-b29a-dc34dc2f3e9f)
run test with 1，is ok. But run with debug mode with error:
```
发生异常: Error
  at DA (D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:37:3587)
    at Function.statement (D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:37:2847)
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:41:1113
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:1:222
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:65:1678
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:1:222
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:65:38013
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:1:222
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:65:40602
    at D:\coding\1.codehub\bikai-CloudSOP-IV\GUIAutomation\BeiDouGUITestWebsite\node_modules\playwright\lib\transform\babelBundleImpl.js:1:222
```

![image](https://github.com/microsoft/playwright/assets/15070379/aa1b0d20-aa3a-4c53-babe-beeff84215f7)

**Comment by RoiMesh** [comment]
hi , any chance you remember what solved the issue ? (i am facing it too and cant find any solution)

**Comment by phramusca** [comment]
Hi @bi-kai Could you please let us know how you solved this issue ?

**Comment by SESA18621** [comment]
I am in the same situation. Anyone found a solution ?
