### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vikramdaruru** [microsoft/playwright#28425]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

I am trying to install playwright using eclipse and java and running into following error. I am having zscaler installed. But, not sure where to import azure certificate. can you please help?

Downloading Chromium 120.0.6099.28 (playwright build v1091)[2m from https://playwright.azureedge.net/builds/chromium/1091/chromium-win64.zip[22m
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1070:8)
    at ssl.onhandshakedone (node:_tls_wrap:856:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
Downloading Chromium 120.0.6099.28 (playwright build v1091)[2m from https://playwright-akamai.azureedge.net/builds/chromium/1091/chromium-win64.zip[22m
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1070:8)
    at ssl.onhandshakedone (node:_tls_wrap:856:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
Downloading Chromium 120.0.6099.28 (playwright build v1091)[2m from https://playwright-verizon.azureedge.net/builds/chromium/1091/chromium-win64.zip[22m
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1070:8)
    at ssl.onhandshakedone (node:_tls_wrap:856:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
Failed to install browsers
Error: Failed to download Chromium 120.0.6099.28 (playwright build v1091), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (C:\Users\irgjkf\AppData\Local\Temp\playwright-java-2535512173812987436\package\lib\server\registry\browserFetcher.js:91:16)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
Exception in thread "main" java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
	at com.microsoft.playwright.Playwright.create(Playwright.java:114)
	at InitialTest.main(InitialTest.java:16)
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 1
	at com.microsoft.playwright.impl.driver.jar.DriverJar.installBrowsers(DriverJar.java:100)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:69)
	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
	... 6 more

**Comment by pavelfeldman** [comment]
This issue does not seem to be related to Playwright.
