### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by asdf23** [microsoft/playwright#28493]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 10]
- Browser: Not related
- Other info: Example crashes out of the box

### Source code

https://playwright.dev/docs/api/class-reporter

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

Follow code on https://playwright.dev/docs/api/class-reporter

**Steps**
Create cusotm reporter following directions
Run the test crash

**Expected**

Custom reporter console.logging to screen

**Actual**

TypeError: r is not iterable
    at createReporters (C:\vc\PlaywrightWebAutomation\node_modules\playwright\lib\runner\reporters.js:55:25) 
    at Runner.runAllTests (C:\vc\PlaywrightWebAutomation\node_modules\playwright\lib\runner\runner.js:65:127)
    at runTests (C:\vc\PlaywrightWebAutomation\node_modules\playwright\lib\cli.js:130:106)
    at t.<anonymous> (C:\vc\PlaywrightWebAutomation\node_modules\playwright\lib\cli.js:40:7)

**Comment by asdf23** [comment]
Changing playwwright.config.ts to

...snip..
reporter: ['./my-awesome-reporter.ts', { customOption: 'some value' }],
....snip...

to 
...snip..
reporter: [['./my-awesome-reporter.ts', { customOption: 'some value' }]],
....snip...

resolves the issue
