### ISSUE TITLE
[BUG]       if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#28504]
source code:

```
import * as playwright from 'playwright-chromium'
import path from 'path'
import {promises as fs} from 'fs'
import os from 'os'

const context = await playwright.chromium.launchPersistentContext(await fs.mkdtemp(path.join(os.tmpdir(), 'pal')), {channel:'chrome', args:['--disable-blink-features=AutomationControlled', '--start-maximized'], headless:false, recordVideo:{dir:'videos'}, viewport:null})
const page = await context.newPage()
await page.goto('https://www.dailymotion.com/video/x87ytjz')
```

often get the following error: (about 15min to 30min)
```
/home/vsts/work/1/s/node_modules/playwright-core/lib/client/connection.js:207
      if (!object) throw new Error(`Object with guid ${arg.guid} was not bound in the connection`);
                   ^

Error: Object with guid frame@8a92bb1756f311c737fc3f3651b19832 was not bound in the connection
    at Connection._tChannelImplFromWire (/home/vsts/work/1/s/node_modules/playwright-core/lib/client/connection.js:207:26)
    at /home/vsts/work/1/s/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:128:20
    at /home/vsts/work/1/s/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:90:12
    at /home/vsts/work/1/s/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:107:21
    at Connection._createRemoteObject (/home/vsts/work/1/s/node_modules/playwright-core/lib/client/connection.js:218:19)
    at Connection.dispatch (/home/vsts/work/1/s/node_modules/playwright-core/lib/client/connection.js:177:12)
    at Immediate.<anonymous> (/home/vsts/work/1/s/node_modules/playwright-core/lib/inProcessFactory.js:48:83)
    at process.processImmediate (node:internal/timers:478:21)
```

I see there are similar errors in the playwright issues, But there are no solution for this situation.

I want to ask whether there is any way to goto 'https://www.dailymotion.com/video/x87ytjz' when the above error happen. I try:
```
import * as playwright from 'playwright-chromium'
import path from 'path'
import {promises as fs} from 'fs'
import os from 'os'

const context = await playwright.chromium.launchPersistentContext(await fs.mkdtemp(path.join(os.tmpdir(), 'pal')), {channel:'chrome', args:['--disable-blink-features=AutomationControlled', '--start-maximized'], headless:false, recordVideo:{dir:'videos'}, viewport:null})
const page = await context.newPage()
while (true)
{
    try
    {
        await page.goto('https://www.dailymotion.com/video/x87ytjz')
        await page.waitForTimeout(1000 * 60 * 30)
    }
   catch {}
}
```
But this way I have to set time explicitly.

I also try page.on('pageerror', async _ => await page.goto('https://www.dailymotion.com/video/x87ytjz')) I get net::err_aborted

Is there any elegant way to reload the page aka goto https://www.dailymotion.com/video/x87ytjz again when the new Error(`Object with guid ${arg.guid} was not bound in the connection`); happen?

**Comment by dgozman** [comment]
Folding into #28320.

**Comment by fancy45daddy** [comment]
Is there any temporary way to reload the page aka goto https://www.dailymotion.com/video/x87ytjz again when the new Error(Object with guid ${arg.guid} was not bound in the connection); happen?
