### ISSUE TITLE
Chromium install bar breaking in CI gihub workflow

### ISSUE THREAD

**Issue by albizeqollari** [microsoft/playwright#28517]
I use this command in github workflow CI :RUN dotnet PlaywrightInstaller.dll
 And i get this error
 Any idea?
 
 
 Downloading Chromium 115.0.5790.24 (playwright build v1067) from https://artifacts.rbi.tech/ui/native/rbal-retail-services-docker-host/builds/chromium/1067/chromium-linux.zip
#18 28.41 /src/PlaywrightInstaller/linux/.playwright/package/lib/server/registry/oopDownloadMain.js:101
#18 28.41       console.log(`|${'■'.repeat(row * stepWidth)}${' '.repeat((totalRows - row) * stepWidth)}| ${percentageString}% of ${toMegabytes(totalBytes)}`);
#18 28.41                           ^
#18 28.41 
#18 28.41 RangeError: Invalid count value
#18 28.41     at String.repeat (<anonymous>)
#18 28.41     at /src/PlaywrightInstaller/linux/.playwright/package/lib/server/registry/oopDownloadMain.js:101:27
#18 28.41     at IncomingMessage.onData (/src/PlaywrightInstaller/linux/.playwright/package/lib/server/registry/oopDownloadMain.js:65:5)
#18 28.41     at IncomingMessage.emit (node:events:525:35)
#18 28.41     at Readable.read (node:internal/streams/readable:539:10)
#18 28.41     at flow (node:internal/streams/readable:1023:34)
#18 28.41     at resume_ (node:internal/streams/readable:1004:3)
#18 28.41     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by mxschmitt** [comment]
Could you try setting the `DEBUG=pw:install` env var while you run `dotnet PlaywrightInstaller.dll`?

This should yield more output to understand why this happens.

**Comment by albizeqollari** [comment]
Thanks! Now i have a clear understanding of what is happening
