### ISSUE TITLE
[BUG] Gitlab CI job fails in WebKit at  Page.waitForRequest and  Page.waitForResponse

### ISSUE THREAD

**Issue by adragich** [microsoft/playwright#2860]
**Context:**
- Playwright Version: ^1.0.2
- Operating System: Linux
- Node version: 12
- Browser: WebKit
- Extra: running tests in Gitlab CI, docker image qawolf/playwright-ci:v1.0.0 (it's an image built from official Playwright Dockerfile extended with `yarn`)

**Code Snippet**

I run simple page in node server in background, where ajax request is triggered after some time and I want to test if it's triggered:

```
import { webkit } from 'playwright';

describe('waitForRequest() / waitForResponse()', () => {
    test('It should wait for request', async () => {
        const browser = await webkit.launch();

        const context = await browser.newContext();
        const page = await context.newPage();
        const request = await page.goto('http://localhost:4444/ajax.html');

        expect(request.status()).toBe(200);
    });
...
});
```

**Describe the bug**

When I run the test on my mac or locally in Docker container built from the same image - it passes (same test succeeds in Chrome and Firefox, locally and in Gitlab CI), but it fails in Gitlab CI in Webkit browser with following log (from `DEBUG=pw:protocol`):

```
$ jest --config jest.integration.config.js --runInBand packages/chauffeur/tests/integration/playwright/PageObject/ez.test.ts
 2020-07-07T14:36:36.500Z pw:protocol SEND ► {"id":1,"method":"Playwright.enable"} []
 FAIL tests/integration/playwright/PageObject/ez.test.ts
   waitForRequest() / waitForResponse()
     ✕ It should wait for response and request using url (55ms)
   ● waitForRequest() / waitForResponse() › It should wait for response and request using url
     Protocol error (Playwright.enable): Browser has been closed.
     ================= browserType.launch logs =================
     [browser] <launching> /root/.cache/ms-playwright/webkit-1301/pw_run.sh --inspector-pipe --headless --no-startup-window
     [browser] <launched> pid=580
     [browser] /root/.cache/ms-playwright/webkit-1301/minibrowser-wpe/MiniBrowser: error while loading shared libraries: libgstreamer-1.0.so.0: cannot open shared object file: No such file or directory
     [browser] <process did exit: exitCode=127, signal=null>
     ============================================================
     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.Protocol error (Playwright.enable): Browser has been closed.
     ================= browserType.launch logs =================
     [browser] <launching> /root/.cache/ms-playwright/webkit-1301/pw_run.sh --inspector-pipe --headless --no-startup-window
     [browser] <launched> pid=580
     [browser] /root/.cache/ms-playwright/webkit-1301/minibrowser-wpe/MiniBrowser: error while loading shared libraries: libgstreamer-1.0.so.0: cannot open shared object file: No such file or directory
     [browser] <process did exit: exitCode=127, signal=null>
     ============================================================
     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.Error:
       3 | describe('waitForRequest() / waitForResponse()', () => {
       4 |     test('It should wait for response and request using url', async () => {
     > 5 |         const browser = await webkit.launch();
         |                         ^
       6 | 
       7 |         const context = await browser.newContext();
       8 |         const page = await context.newPage();
       at ../../node_modules/playwright/lib/webkit/wkConnection.js:103:63
       at WKSession.send (../../node_modules/playwright/lib/webkit/wkConnection.js:102:16)
       at Function.connect (../../node_modules/playwright/lib/webkit/wkBrowser.js:51:37)
       at WebKit._connectToTransport (../../node_modules/playwright/lib/server/webkit.js:32:38)
       at WebKit._innerLaunch (../../node_modules/playwright/lib/server/browserType.js:84:36)
       at ProgressController.run (../../node_modules/playwright/lib/progress.js:77:28)
       at WebKit.launch (../../node_modules/playwright/lib/server/browserType.js:58:25)
       at Object.<anonymous> (tests/integration/playwright/PageObject/ez.test.ts:5:25)
 Test Suites: 1 failed, 1 total
 Tests:       1 failed, 1 total
```

I am not sure if it's Playwright bug, or I have to fix my environment somehow, I've checked Dockerfile and gstreamer is installed there. 

I've created docker container locally from Playwright Dockerfile and checked manually if the missing file is here - it lives under `/usr/lib/x86_64-linux-gnu` directory.

I'd appreciate your help, this issue is blocking using Playwright for me.

**Comment by adragich** [comment]
Noticed I haven't updated my image with latest webkit bugfix, gonna debug and re-open if bug still happens
