### ISSUE TITLE
Test fails, because I'm asked to update my playwright version

### ISSUE THREAD

**Issue by andreas942** [microsoft/playwright#28667]
### System info
- Playwright Version: playwright/dotnet:v1.39.0-jammy
- Operating System: Ubuntu 20
- Browser: Chromium
- Other info:

we run in our Jenkins CI/CD pipeline some test within docker image
playwright/dotnet:v1.39.0-jammy
when dotnet test is executed we are getting the message 

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed SDQMPIsOpenedOnMainPage [1 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Executable doesn't exist at /ms-playwright/chromium-1091/chrome-linux/chrome
╔════════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just updated to 1.40.0.              ║
║ Please update docker image as well.                            ║
║ -  current: mcr.microsoft.com/playwright/dotnet:v1.99.99-jammy ║
║ - required: mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy  ║
║                                                                ║
║ <3 Playwright Team                                             ║
╚════════════════════════════════════════════════════════════════╝
  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwnerBase object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 209
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 63
   at Microsoft.Playwright.NUnit.BrowserService.CreateBrowser(IBrowserType browserType) in /_/src/Playwright.NUnit/BrowserService.cs:line 55
   at Microsoft.Playwright.NUnit.BrowserService.<>c__DisplayClass5_0.<<Register>b__0>d.MoveNext() in /_/src/Playwright.NUnit/BrowserService.cs:line 45
--- End of stack trace from previous location ---
   at Microsoft.Playwright.NUnit.WorkerAwareTest.RegisterService[T](String name, Func`1 factory) in /_/src/Playwright.NUnit/WorkerAwareTest.cs:line 55
   at Microsoft.Playwright.NUnit.BrowserTest.BrowserSetup() in /_/src/Playwright.NUnit/BrowserTest.cs:line 46
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

But we don't want to switch to v1.40, because it supprts NET 8 only

**Comment by MindaugasMateika** [comment]
Not familiar with dotnet but that happens if you don't pin exact dependency versions in node. Maybe that's also the case in dotnet?

**Comment by mxschmitt** [comment]
> But we don't want to switch to v1.40, because it supports NET 8 only

We recommend creating your own Docker image if you want to use a different .NET version. There is also ubuntu-focal which still uses .NET 6.

Would that work for you?

The 1.99.99 error is going to be fixed in the next release 1.41.

**Comment by andreas942** [comment]
Dear Max, Itried it with 
playwright/dotnet:v1.33.0-focal
but got the same error 
╔════════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just updated to 1.40.0.              ║
║ Please update docker image as well.                            ║
║ -  current: mcr.microsoft.com/playwright/dotnet:v1.99.99-focal ║
║ - required: mcr.microsoft.com/playwright/dotnet:v1.40.0-focal  ║
║                                                                ║
║ <3 Playwright Team                                             ║
╚════════════════════════════════════════════════════════════════╝
too. Do you fix it in focal too? Otherwise I create my own docker image as recommended.

**Comment by mxschmitt** [comment]
The error message will be more clear. Yes.

It means that you are using 1.40 Playwright while your Docker image does not match. You should use `mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy` Docker container so it matches.

Both need to match. Have you tried that?

**Comment by andreas942** [comment]
ok I changed to playwright/dotnet:v1.40.0-focal, which is working fine. Thus we can close the issue. Thanks a lot
