### ISSUE TITLE
[REGRESSION]: Install from GitHub errors on test start

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#2868]
**Context:**
- GOOD Playwright Version: ?
- BAD Playwright Version: 0c80c227165c608430eac02ad75739ed7f144b72
- Operating System: macOS 10.15.5
- Extra: Node v14.5.0 (and v14.1.0)

**Code Snippet**

```
$ git clone git@github.com:microsoft/playwright.git
Cloning into 'playwright'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20753 (delta 5), reused 9 (delta 3), pack-reused 20732
Receiving objects: 100% (20753/20753), 13.46 MiB | 6.01 MiB/s, done.
Resolving deltas: 100% (15809/15809), done.

$ cd playwright/

$ npm i

> fsevents@1.2.13 install /Users/pw/code/playwright/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@3.6.5 postinstall /Users/pw/code/playwright/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@9.0.4 postinstall /Users/pw/code/playwright/node_modules/electron
> node install.js


> playwright-internal@1.2.0-post prepare /Users/pw/code/playwright
> node install-from-github.js

Rebuilding installer...
Downloading browsers...
Done. Use "npm run watch" to compile.
Failed to process descriptor at /Users/pw/Desktop/pw
Failed to process descriptor at /Users/pw/Desktop/playwright
Removing unused browser at /Users/pw/Library/Caches/ms-playwright/firefox-1118
Removing unused browser at /Users/pw/Library/Caches/ms-playwright/webkit-1298
added 663 packages from 437 contributors and audited 664 packages in 15.212s

23 packages are looking for funding
  run `npm fund` for details

found 9 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

$ npm test

> playwright-internal@1.2.0-post test /Users/pw/code/playwright
> cross-env BROWSER=all node --unhandled-rejections=strict test/test.js

internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module '../lib/rpc/server/dispatcher'
Require stack:
- /Users/pw/code/playwright/test/environments.js
- /Users/pw/code/playwright/test/test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/pw/code/playwright/test/environments.js:23:34)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pw/code/playwright/test/environments.js',
    '/Users/pw/code/playwright/test/test.js'
  ]
}
npm ERR! Test failed.  See above for more details.
```

**Describe the bug**

Follow the instructions from CONTRIBUTING.md to get started and run tests. Observe tests do not run. These same install instructions had worked a few weeks ago so the issue might be my environment. I can reproduce on my machine, but not sure if it's the same for others doing a fresh install on macOS.

**Comment by rwoll** [comment]
FWIW, the following works:

```
$ git clone git@github.com:microsoft/playwright.git
$ cd playwright
$ npm i
$ npm run build # 💥 NEW!!!
$ npm test
```
