### ISSUE TITLE
[BUG] Getting "Error: browserType.launch: EPERM: operation not permitted, mkdir '<playwright-directory>/test-results/.playwright-artifacts-0/traces'

### ISSUE THREAD

**Issue by surajsahu8** [microsoft/playwright#28710]
### System info
Playwright Version: [v1.38.x, v1.39.x, v1.40.0, v1.40.1, v1.41.0-alpha-nov-23-2023]
Operating System: Ubuntu
Browser: [Chromium]
Node Version: v18.17.1
Browser Image: mcr.microsoft.com/playwright:v<Playwright Version>-focal

### Source code
```
// playwright.config.ts

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  globalSetup: require.resolve('./global-setup'),
  globalTeardown: require.resolve('./global-teardown'),
  outputDir: 'test-results',
  testDir: 'tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  timeout: process.env.TEST_TIMEOUT,
  expect: { timeout: 15 * 1000 }, // 15 seconds
  retries: process.env.RETRIES,
  workers: process.env.WORKERS,
  repeatEach: process.env.REPEAT_EACH,

  use: {
    baseURL: process.env.BASE_URL,
    headless: true,
    viewport: { width: process.env.BROWSER_WIDTH, height: process.env.BROWSER_HEIGHT },
    ignoreHTTPSErrors: true,
    defaultBrowserType: 'chromium',
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
    permissions: ['clipboard-read', 'clipboard-write'],
    storageState: <customized storage state>,
    actionTimeout: process.env.ACTION_TIMEOUT,
    navigationTimeout: process.env.NAVIGATION_TIMEOUT,
  },

  reporter: [
    ['list'],
    [
      'allure-playwright',
      {
        suiteTitle: true,
        environmentInfo: {
          NODE_VERSION: process.version,
          OS: process.platform,
          IS_HEADLESS: process.env.HEADLESS,
          BROWSER: process.env.BROWSER,
        },
      },
    ],
    ['json', { outputFile: 'test-results.json' }],
    ['junit', { outputFile: 'test-results.xml' }],
    ['html', { open: 'never' }],
    ['./summaryReporter'],
  ],

  projects: [
    {
      name: 'chromium',
      use: '{ browserName: 'chromium' }',
    },
  ],
});
```

**Steps**
- Running test on docker machine with ubuntu image.

**Actual**

- Seeing below error.
```
Error: browserType.launch: EPERM: operation not permitted, mkdir '<playwright-directory>/test-results/.playwright-artifacts-0/traces'

       at ../global-setup.ts:61

      59 |     });
      60 |   }
    > 61 |   const browser = await chromium.launch({ headless: config.HEADLESS });
         |                                  ^
      62 |   const context = await browser.newContext({ ignoreHTTPSErrors: true });
      63 |   const page = await context.newPage();
      64 |   try {

        at createSession (/home/admin/thoughtspot/blink-playwright/global-setup.ts:61:34)
        at Object.exports.test._test.test.extend.autoWorkerFixture.scope (<playwright-directory>/fixtures/blink.ts:462:26)
```

**Comment by yury-s** [comment]
Are you running under a user that doesn't have write permission in the mentioned directory? If that's not the case, please provide a repro that we could try locally.

**Comment by surajsahu8** [comment]
Are you running under a user that doesn't have write permission in the mentioned directory? - No
It is not happening for all the tests. And randomly it is happening to few tests in each run. 
Currently we are using playwright v1.24.0, where we have not seen this issue. But we are trying to upgrade the version and blocked due to this.

**Comment by yury-s** [comment]
Can you create such directory manually in the docker under the same user with `mkdir -p` when the test is failing?

We'll need a self contained repro that fails in our 1.40 docker container to take an action on this. Could you extract one of the failing tests in a self-contained example that we could run locally in the docker?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
