### ISSUE TITLE
[BUG] net::ERR_ABORTED when downloading large files

### ISSUE THREAD

**Issue by rlenferink** [microsoft/playwright#28729]
### System info
- Playwright Version: v1.40
- Python version: 3.11.4
- Operating System: Fedora 38
- Browser: At least Chromium and Firefox
- Other info: I put up an example file on https://pictures.stcaeciliageesteren.nl/example.mp4 for making the issue reproducible.

The `.htaccess` on pictures.stcaeciliageesteren.nl contains the following to force a download of MP4 files:

```htaccess
<FilesMatch "\.(mp4|avi)$" >
    ForceType application/octet-stream
    Header add Content-Disposition "attachment"
</FilesMatch>
```

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
#!/usr/bin/env python

import os

from playwright.sync_api import Page, sync_playwright


class FileChecker:

    def __init__(self):
        # Directory for storing data files
        self.data_dir = os.path.join(os.getcwd(), 'data')

    def download_file(self, page: Page, url: str, file_name: str):
        # Start waiting for the download
        with page.expect_download() as download_info:
            # Perform the action that initiates download
            page.goto(url)

        download = download_info.value

        # Wait for the download process to complete and save the downloaded file somewhere
        download.save_as(f"{self.data_dir}/{file_name}")


if __name__ == "__main__":
    print("Starting ...")

    data_tmp = os.path.join(os.getcwd(), 'data_tmp')
    os.makedirs(data_tmp, exist_ok=True)

    with sync_playwright() as pw:
        browser = pw.chromium.launch(
            downloads_path=data_tmp,
            headless=False
        )

        page = browser.new_page()
        page.goto(f"https://pictures.stcaeciliageesteren.nl")

        page.wait_for_timeout(2000)

        # Start file checker
        checker = FileChecker()
        checker.download_file(page, "https://pictures.stcaeciliageesteren.nl/example.mp4", "example.mp4")

        # Wait a bit and then exit
        page.wait_for_timeout(2000)
        browser.close()

    print("Finished ...")
```

**Steps**
- Save the above to a file , e.g. `ReproDownloadExample.py`
- Ensure the file can be executed
- Execute the file with `./ReproDownloadExample.py`

**Expected**

The MP4 to be saved to the `data` folder.

**Actual**

Playwright fails with the following stacktrace:

```
/usr/bin/python3 /mnt/stcaecilia/Download_scripts/0_PlaywrightDownloader/ReproDownloadExample.py 
Starting ...
Traceback (most recent call last):
  File "/mnt/stcaecilia/Download_scripts/0_PlaywrightDownloader/ReproDownloadExample.py", line 45, in <module>
    checker.download_file(page, "https://pictures.stcaeciliageesteren.nl/example.mp4", "example.mp4")
  File "/mnt/stcaecilia/Download_scripts/0_PlaywrightDownloader/ReproDownloadExample.py", line 18, in download_file
    page.goto(url)
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 9312, in goto
    self._sync(
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/_impl/_page.py", line 475, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 139, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: net::ERR_ABORTED at https://pictures.stcaeciliageesteren.nl/example.mp4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/stcaecilia/Download_scripts/0_PlaywrightDownloader/ReproDownloadExample.py", line 32, in <module>
    with sync_playwright() as pw:
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/sync_api/_context_manager.py", line 90, in __exit__
    self._connection.stop_sync()
  File "/home/rlenferink/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 282, in stop_sync
    self._loop.run_until_complete(self._transport.wait_until_stopped())
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 629, in run_until_complete
    self._check_running()
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 588, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
sys:1: RuntimeWarning: coroutine 'PipeTransport.wait_until_stopped' was never awaited

Process finished with exit code 1
```

**Comment by yury-s** [comment]
You navigate the page to 'https://pictures.stcaeciliageesteren.nl/example.mp4',  the navigation gets converted into a download and the navigation get aborted, but the download continues. This is working as expected, you just need to catch the error from `page.goto()`.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by rlenferink** [comment]
@yury-s Thanks! That's what I figured as well. I updated the download snippet to the following:

```python
    def download_file(self, page: Page, url: str, file_name: str):
        # Start waiting for the download
        with page.expect_download() as download_info:
            # Perform the action that initiates download
            page.get_by_text("example.mp4").click()

        download = download_info.value
```

(instead of a `page.goto()` a `click()` action)

After that the failure remains, but when running in headed mode and viewing the 'Downloads' section of chromium, it seems that Chromium blocks the download when it is on a network share. It shortly starts the download (1 second) and will quickly abort it. Since the connection is simply interrupted playwright will fail with the `ERR_ABORTED` error.

Maybe that is intended, but that is what I found after some debugging.

**Comment by yury-s** [comment]
If it's a network folder, you need to mount it, see https://github.com/microsoft/playwright/issues/15149. If it doesn't work, please file a separate issue as it's different the from the original problem with navigation converted into download.
