### ISSUE TITLE
[BUG] using a different .env file with the Playwright for VSCode extension

### ISSUE THREAD

**Issue by Antoine-Regembal** [microsoft/playwright#28734]
**Context:**
- Playwright Version: @playwright/test": "^1.38.1"
- Operating System: Mac
- Node.js version: v18.17.0
- Visual Studio Code version: 1.85.1
- Playwright for VSCode extension version: v1.0.20
- Browser: Chromium
- Extra: running a Remix application

**Code Snippet**

`package.json scripts`
```json
{
   "test:playwright": "dotenv -e .env.test -- playwright test"
}
```

**Describe the bug**

Hello people of Playwright,

In my application I need to use a different .env file for testing my application.
I use the `dotenv` package to define a `.env.test` (as you can see in the code snippet) file that my application should use to launch for testing.
When I launch tests with CLI it works perfectly, but the Playwright for VSCode extension doesn't follow this script obviously and I was not able to find a way to ask Playwright for VSCode extension to launch tests with the `.env.test` file instead of the `.env` for the environment variables.

Is there any way to achieve that ? That would be great for me to be able to launch tests with the extension

Cheers 🥖

**Comment by gofr** [comment]
Does your dotenv have to be specified in the package.json? I load my dotenv at the top of my `playwright.config.ts`. Would that work for you? See https://stackoverflow.com/questions/70861292/playwright-tests-using-variable-from-env-file.

**Comment by Antoine-Regembal** [comment]
Hi @gofr

I updated my `playwright.config.ts` file like so:

```js
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env.test") });

....
```

It works well, I didn't think about it

Thank you 🥂

**Comment by Mwalek** [comment]
This was a helpful thread, thanks!

**Comment by mindplay-dk** [comment]
> You can also now natively achieve the same

How? This does not work for me with the current version of Playwright.

If I so much as touch `import.meta` in `playwright.config.ts` the process dies - even a line like:

    const lol = import.meta.dirname

With this in the config file, I get:

```
> playwright test screenshots --project=chromium

ReferenceError: exports is not defined in ES module scope
    at file:///home/rasmus.schultz/workspace/staff-frontend/playwright.config.ts:3:23
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:534:37)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:366:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1648:24)
    at Module._compile (node:internal/modules/cjs/loader:1813:5)
    at Module.newCompile2 (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1971:10)
    at Object.newLoader2 [as .ts] (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1552:32)
    at Module._load (node:internal/modules/cjs/loader:1354:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1575:12)
    at require (node:internal/modules/helpers:191:16)
    at requireOrImport (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/transform/transform.js:225:18)
    at loadUserConfig (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/common/configLoader.js:107:89)
    at loadConfig (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/common/configLoader.js:119:28)
    at loadConfigFromFile (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/common/configLoader.js:331:10)
    at runTests (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/program.js:197:18)
    at i.<anonymous> (/home/rasmus.schultz/workspace/staff-frontend/node_modules/playwright/lib/program.js:70:7)
```

The line number doesn't even make sense, it's as though the syntax itself isn't even supported.

I tried with Node 24 and 25, latest versions, neither works.

I had to use `__dirname`, which is odd, in a `.ts` module, in a project with `"type": "module"` in `package.json`.

Something seems really broken here. 🤔
