### ISSUE TITLE
[BUG] Test host process crashed : Unhandled exception. Microsoft.Playwright.PlaywrightException

### ISSUE THREAD

**Issue by gauravkhuraana** [microsoft/playwright#28843]
## System info
- Playwright Version: [v1.40]
- Operating System: [Ubuntu]
- Browser: [Chromium]
- Other info: Issue comes when test are run in Azure dev ops pipeline with ubuntu agent 

# **Problem** - 

When we run a test on ubuntu in pipeline with dotnet test command, it crashes with the error of element not visible. It does not happen for all test. IT does not happen if we run from test explorer

public ILocator CustomeSymbol=> _Page.Locator("//*[local-name()='svg' and @data-icon=\"hexagon-xmark\"]");

## line of failure below while it tries to check visibility of the above element ** 
 
            await Expect(CustomeSymbol).ToBeVisibleAsync(new() { Timeout = 15000 });
 
- It happens when run from command line using dotnet test in ubuntu

## Error we see in pipeline

`    Microsoft (R) Test Execution Command Line Tool Version 17.7.2 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
**The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Microsoft.Playwright.PlaywrightException:** **Locator expected to be visible** 
Call log:
  - LocatorAssertions.ToBeVisibleAsync with timeout 10000ms
  - waiting for Locator("//*[local-name()='svg' and @data-icon=\"hexagon-xmark\"]")
   at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, FrameExpectOptions expectOptions, Object expected, String message) in /_/src/Playwright/Core/AssertionsBase.cs:line 84
   at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue[] expectedText, Object expected, String message, FrameExpectOptions options) in /_/src/Playwright/Core/AssertionsBase.cs:line 64
   at PlaywrightTestsCsNunit.Pages.Accounts.ValidateForm() in /home/vsts/work/1/s/src/PlaywrightTestsCS/PlaywrightTestsCsNunit/Pages/Test.cs:line 1546
   at PlaywrightTestsCsNunit.StepDefinitions.CEPAccountsFlowTestsStepDefinition.ThenIValidateTheUserIsAbleToSendEmailToCustomerCareFillingAllDetails() in /home/vsts/work/1/s/src/PlaywrightTestsCS/PlaywrightTestsCsNunit/StepDefinitions/StepDefintion.cs:line 204
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
`

# Expected

Whether we run from test explorer or with dotnet test command behavior should be same

**Comment by mxschmitt** [comment]
This issue is not following the bug template, feel free to re-file attaching clear reproduction steps, which we need in order to look into issues like this. Thanks for your understanding.
