### ISSUE TITLE
[BUG]I have installed Python 3.10 environment with Anaconda and then installed Playwright. However, when activating the Playwright environment in the command prompt (powershell) and trying to run the playwright command, there is no response. Additionally, when running a Playwright demo script (demo.py), you encounter the following error:

### ISSUE THREAD

**Issue by libp** [microsoft/playwright#28890]
### System info
- Playwright Version: [playwright==1.40.0]
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
(playwright) PS C:\Users\peng\git\playwright> python demo.py
Traceback (most recent call last):
  File "C:\Users\peng\git\playwright\demo.py", line 3, in <module>
    with sync_playwright() as p:
  File "C:\Users\peng\.conda\envs\playwright\lib\site-packages\playwright\sync_api\_context_manager.py", line 79, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running at C:\Users\peng\.conda\envs\playwright\lib\site-packages\playwright\_impl\_connection.py:273> wait_for=<Future finished result=None> cb=[ProtocolCallback.__init__.<locals>.cb() at C:\Users\peng\.conda\envs\playwright\lib\site-packages\playwright\_impl\_connection.py:194]>
Future exception was never retrieved
future: <Future finished exception=Exception('Connection closed while reading from the driver')>
Exception: Connection closed while reading from the driver
Future exception was never retrieved
future: <Future finished exception=BrokenPipeError(32, '管道正在被关闭。', None, 232, None)>
Traceback (most recent call last):
  File "C:\Users\peng\.conda\envs\playwright\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Users\peng\.conda\envs\playwright\lib\asyncio\windows_events.py", line 548, in send
    ov.WriteFile(conn.fileno(), buf)
BrokenPipeError: [WinError 232] 管道正在被关闭。

### Source code
from playwright.sync_api import Playwright,sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(channel='chrome', headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto('https://baidu.com')
    page.wait_for_load_state('networkidle')
    page.screenshot(path='example.png')
    browser.close()

**Comment by libp** [comment]
![image](https://github.com/microsoft/playwright/assets/16248888/fb12ef07-f2a0-43c0-845f-d0d7ac698721)

**Comment by libp** [comment]
![image](https://github.com/microsoft/playwright/assets/16248888/247cf544-7301-47bf-b895-fadc90e164a7)

**Comment by libp** [comment]
![image](https://github.com/microsoft/playwright/assets/16248888/c8e87b1f-cf75-4a62-9b46-f4beb6437ed3)

**Comment by mxschmitt** [comment]
Can you try if this reproduces also with the [Pypi](https://pypi.org/project/playwright/) package (so its not conda)?
Does `playwright --version` print anything?
What does `chcp` print?
