### ISSUE TITLE
[BUG] Allow configuring default JSON serializer options

### ISSUE THREAD

**Issue by shravan2x** [microsoft/playwright#28946]
### System info
- Playwright Version: v1.40.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Steps**
- Go to any webpage
- `JsonElement someResult = await _page.MainFrame.EvaluateAsync<JsonElement>("<script to generate recursive objects with depth 100 or 1000>");`
- `someResult.Deserialize<MyType>(new JsonSerializerOptions() { MaxDepth = 256 })!;`

**Expected**

It doesn't seem practical to allow infinite depth, so the ideal solution seems to be to allow developers to configure the JSON serializer defaults.

**Actual**

```
Microsoft.Playwright.TargetClosedException: The maximum configured depth of 64 has been exceeded. Cannot read next JSON object. Path: $.result | LineNumber: 0 | BytePositionInLine: 25123.
```

**Comment by mxschmitt** [comment]
I'll close it for now as per above. Feel free to re-file if this doesn't work for you!

**Comment by ficho-hun** [comment]
I know that is already closed, but still happening, in a simple query too.

Failed to query element (css=.alert): Microsoft.Playwright.TargetClosedException: The maximum configured depth of 64 has been exceeded. Cannot read next JSON array. Path: $.result | LineNumber: 0 | BytePositionInLine: 576656.
 ---> System.Text.Json.JsonException: The maximum configured depth of 64 has been exceeded. Cannot read next JSON array. Path: $.result | LineNumber: 0 | BytePositionInLine: 576656.
 ---> System.Text.Json.JsonReaderException: The maximum configured depth of 64 has been exceeded. Cannot read next JSON array. LineNumber: 0 | BytePositionInLine: 576656.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.StartArray()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.TryParseValue(Utf8JsonReader& reader, JsonDocument& document, Boolean shouldThrow, Boolean useArrayPools)
   at System.Text.Json.Serialization.Converters.JsonElementConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at Microsoft.Playwright.Playwright.<>c__DisplayClass0_0.<CreateAsync>b__0(Object _, Byte[] message) in /_/src/Playwright/Playwright.cs:line 47
   at Microsoft.Playwright.Transport.StdIOTransport.ProcessStream(CancellationToken token) in /_/src/Playwright/Transport/StdIOTransport.cs:line 251
   at Microsoft.Playwright.Transport.StdIOTransport.GetResponseAsync(CancellationToken token) in /_/src/Playwright/Transport/StdIOTransport.cs:line 210
   --- End of inner exception stack trace ---
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwnerBase object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 231
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.Frame.QuerySelectorAsync(String selector, FrameQuerySelectorOptions options) in /_/src/Playwright/Core/Frame.cs:line 606

**Comment by neonVoice** [comment]
In C# I needed to use CDPSession and enable async call stacks like this:
```c#
ConfigurePlaywrightJsonSerializerOptions();

using var playwright = await Playwright.CreateAsync();

// other initialization code

var page = await context.NewPageAsync();
var cdpSession = await page.Context.NewCDPSessionAsync(page);

// other set up code

await cdpSession.SendAsync("Debugger.enable", new Dictionary<string, object> { { "enabled", true } });
await cdpSession.SendAsync("Debugger.setAsyncCallStackDepth", new Dictionary<string, object> { { "maxDepth", 64 } });

// other code

await page.GotoAsync(testUrl);
```

I ended up using this workaround - needs to be called before any work with playwright is done:
```c#
private static void ConfigurePlaywrightJsonSerializerOptions(int maxDepth = 128)
{
    var assembly = typeof(Playwright).Assembly;

    var jsonExtensionsType = assembly.GetType("Microsoft.Playwright.Helpers.JsonExtensions") ?? throw new InvalidOperationException("Type JsonExtensions not found.");
    var jsonOptionsProperty = jsonExtensionsType.GetProperty("DefaultJsonSerializerOptions", BindingFlags.Static | BindingFlags.Public) ?? throw new InvalidOperationException("DefaultJsonSerializerOptions not found.");
    var options = jsonOptionsProperty.GetValue(null) as JsonSerializerOptions ?? throw new InvalidOperationException("Property Options not found.");

    options.MaxDepth = maxDepth;
}
```
