### ISSUE TITLE
[BUG] page.wait_for_function report error: playwright._impl._errors.Error: TypeError: kHoverHitTargetInterceptorEvents is not iterable

### ISSUE THREAD

**Issue by bingal** [microsoft/playwright#29164]
### System info
- Playwright Version: [v1.41.0]
- Operating System: [macOS 14.2.1]
- Browser: [Chromium, Edge]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
# test-wait-function.py
import asyncio
from playwright.async_api import async_playwright, Playwright

async def run(playwright: Playwright):
    edge = playwright.chromium
    browser = await edge.launch(channel="msedge", headless=False)
    page = await browser.new_page()
    await page.goto("https://www.pcauto.com.cn/hj/")
    await page.evaluate("window.x = 0; setTimeout(() => { window.x = 100 }, 1000);")
    a = await page.wait_for_function("() => window.x > 0")
    print(a)
    await browser.close()

async def main():
    async with async_playwright() as playwright:
        await run(playwright)
asyncio.run(main())
```

**Steps**
- Run the code `python ./test-wait-function.py`

**Expected**

Waiting the function and then echo `true` in console

**Actual**
Report the following error, and the same code works fine on other pages, but it throws an error only on this specific webpage https://www.pcauto.com.cn/hj/.
```
Traceback (most recent call last):
  File "/Users/ben/Downloads/test-wait-function.py", line 17, in <module>
    asyncio.run(main())
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ben/Downloads/test-wait-function.py", line 16, in main
    await run(playwright)
  File "/Users/ben/Downloads/test-wait-function.py", line 10, in run
    a = await page.wait_for_function("() => window.x > 0")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 11874, in wait_for_function
    await self._impl_obj.wait_for_function(
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/playwright/_impl/_page.py", line 990, in wait_for_function
    return await self._main_frame.wait_for_function(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 779, in wait_for_function
    return from_channel(await self._channel.send("waitForFunction", params))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 495, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/ben/opt/anaconda3/envs/py311/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: TypeError: kHoverHitTargetInterceptorEvents is not iterable
    at <anonymous>:5888:66
    at <anonymous>:6021:11
```

**Comment by mxschmitt** [comment]
If the site overrides the `globalThis.Set` implementation, we unfortunately cannot do anything. Closing as a won't fix.
