### ISSUE TITLE
[BUG] Can't open Webkit from executable path

### ISSUE THREAD

**Issue by Sneaky-Bot-Dev-Team** [microsoft/playwright#2923]
**Context:**
- Playwright Version: 1.1.1
- Operating System: MacOS Catalina 10.15.4
- Node version: [e.g. 10.12, 10.14]
- Browser: Webkit
- Extra: Downloaded webkit from : https://playwright.azureedge.net/builds/webkit/1269/minibrowser-mac-10.15.zip

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
let browserOption = { headless: false }
 browserOption.executablePath = '/Users/myname/Downloads/minibrowser-mac-10.15/Playwright.app'
 let browser = await webkit.launch(browserOption);
```
**Error**

```
[1] (node:85186) UnhandledPromiseRejectionWarning: Error: Failed to launch browser: Error: spawn /Users/myName/Downloads/minibrowser-mac-10.15/Playwright.app EACCES
[1] ==================== webkit.launch logs ====================
[1] <launching> /Users/myName/Downloads/minibrowser-mac-10.15/Playwright.app --inspector-pipe --no-startup-window
[1] ============================================================
[1] Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
[1]     at ChildProcess.<anonymous> (/Users/myName/Documents/Coding_Projects/myProjectName/node_modules/playwright/lib/server/processLauncher.js:51:20)
[1]     at Object.onceWrapper (events.js:313:26)
[1]     at ChildProcess.emit (events.js:223:5)
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
[1]     at onErrorNT (internal/child_process.js:456:16)
[1]     at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by aslushnikov** [comment]
@Sneaky-Bot-Dev-Team we ship a `pw_run.sh` with the minibrowser to run it. Use it as an executable path:

```js
browserOption.executablePath = '/Users/myname/Downloads/minibrowser-mac-10.15/pw_run.sh'
```

**Comment by Sneaky-Bot-Dev-Team** [comment]
Worked thanks !
