### ISSUE TITLE
[BUG] Error encountered when merged blob reports to generate allure-playwright report

### ISSUE THREAD

**Issue by ck-singh** [microsoft/playwright#29279]
Encountered below error when tried using merge-reports feature of playwright to merge blob reports, from an execution that used 2 shards, and generate an allure report.
Please note that the same blob reports can be merged to generate an HTML report without any issue.

> TypeError: Cannot read properties of undefined (reading 'repeatEach')

### System info
- Playwright Version: [v1.41.1]
- Operating System: [All]
- Browser: [chrome]
- Other info: 
  - allure-playwright: [2.11.1]
  - allure-commandline: [2.26.0]

### Source code

`npx playwright merge-reports --reporter allure-playwright ./all-blob-reports`

**Steps**
- Download attached blob reports (report-1.zip and report-2.zip) generated using sharding.
 [report-1.zip](https://github.com/microsoft/playwright/files/14119155/report-1.zip)
[report-2.zip](https://github.com/microsoft/playwright/files/14119156/report-2.zip)
- copy the downloaded blob reports (report-1.zip and report-2.zip) to `all-blob-reports` folder
- RUN: `npx playwright merge-reports --reporter allure-playwright ./all-blob-reports`

**Expected**
- No error is observed
- Result files are populated in ### `allure-results` directory

**Actual**
- Below error is encountered
- No result files are populated in `allure-results` directory

`merging reports from /builds/XXXX/playwright/all-blob-reports
extracting: all-blob-reports/report-1.zip
extracting: all-blob-reports/report-2.zip
merging events
processing test events
**Error in reporter TypeError: Cannot read properties of undefined (reading 'repeatEach')**
    at AllureReporter.onTestBegin (/builds/XXXX/playwright/node_modules/allure-playwright/src/index.ts:107:17)
    at ReporterV2Wrapper.onTestBegin (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/reporterV2.js:55:157)
    at /builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:38:65
    at wrap (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:86:5)
    at Multiplexer.onTestBegin (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:38:45)
    at TeleReporterReceiver._onTestBegin (/builds/XXXX/playwright/node_modules/playwright/lib/isomorphic/teleReceiver.js:140:157)
    at TeleReporterReceiver.dispatch (/builds/XXXX/playwright/node_modules/playwright/lib/isomorphic/teleReceiver.js:63:12)
    at dispatchEvents (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/merge.js:53:22)
    at createMergedReport (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/merge.js:67:11)
    at mergeReports (/builds/XXXX/playwright/node_modules/playwright/lib/cli.js:181:3)
    at t.<anonymous> (/builds/XXXX/playwright/node_modules/playwright/lib/cli.js:95:7)
Error in reporter TypeError: Cannot read properties of undefined (reading 'repeatEach')
    at AllureReporter.onTestBegin (/builds/XXXX/playwright/node_modules/allure-playwright/src/index.ts:107:17)
    at ReporterV2Wrapper.onTestBegin (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/reporterV2.js:55:157)
    at /builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:38:65
    at wrap (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:86:5)
    at Multiplexer.onTestBegin (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:38:45)
    at TeleReporterReceiver._onTestBegin (/builds/XXXX/playwright/node_modules/playwright/lib/isomorphic/teleReceiver.js:140:157)
    at TeleReporterReceiver.dispatch (/builds/XXXX/playwright/node_modules/playwright/lib/isomorphic/teleReceiver.js:63:12)
    at dispatchEvents (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/merge.js:53:22)
    at createMergedReport (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/merge.js:67:11)
    at mergeReports (/builds/XXXX/playwright/node_modules/playwright/lib/cli.js:181:3)
    at t.<anonymous> (/builds/XXXX/playwright/node_modules/playwright/lib/cli.js:95:7)
building final report
Error in reporter TypeError: Cannot read properties of undefined (reading 'repeatEach')
    at AllureReporter.onTestBegin (/builds/XXXX/playwright/node_modules/allure-playwright/src/index.ts:107:17)
    at /builds/XXXX/playwright/node_modules/allure-playwright/src/index.ts:221:12
    at Array.forEach (<anonymous>)
    at AllureReporter.addSkippedResults (/builds/XXXX/playwright/node_modules/allure-playwright/src/index.ts:220:22)
    at AllureReporter.onEnd (/builds/XXXX/playwright/node_modules/allure-playwright/src/index.ts:246:10)
    at ReporterV2Wrapper.onEnd (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/reporterV2.js:91:165)
    at /builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:51:56
    at wrapAsync (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:79:18)
    at Multiplexer.onEnd (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/multiplexer.js:51:31)
    at TeleReporterReceiver._onEnd (/builds/XXXX/playwright/node_modules/playwright/lib/isomorphic/teleReceiver.js:199:159)
    at TeleReporterReceiver.dispatch (/builds/XXXX/playwright/node_modules/playwright/lib/isomorphic/teleReceiver.js:86:41)
    at dispatchEvents (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/merge.js:53:22)
    at createMergedReport (/builds/XXXX/playwright/node_modules/playwright/lib/reporters/merge.js:69:9)
    at mergeReports (/builds/XXXX/playwright/node_modules/playwright/lib/cli.js:181:3)
    at t.<anonymous> (/builds/XXXX/playwright/node_modules/playwright/lib/cli.js:95:7)
finished building report`

**Comment by pavelfeldman** [comment]
> Cannot read properties of undefined (reading 'repeatEach')** at AllureReporter.onTestBegin (/builds/XXXX/playwright/node_modules/allure-playwright/src/index.ts:107

Since the error originates from the allure plugin, I'd recommend filing this bug in their repo. They will be able to follow up with us if they think the error originates from Playwright.

**Comment by pavelfeldman** [comment]
Closing as per above.
