### ISSUE TITLE
[Bug]: Download canceled in headless mode

### ISSUE THREAD

**Issue by FANGOD** [microsoft/playwright#29355]
### Version

1.40.0

### Steps to reproduce

Download this URL got error `playwright._impl._errors.Error: canceled` in headless mode, headless is false and can be downloaded.
url = "https://www.gov.il/BlobFolder/reports/alert_1629d/he/ALERT-INCD-IL-C-1692D.pdf"

### Expected behavior

download file success

### Actual behavior

```
Exception in callback SyncBase._sync.<locals>.<lambda>(<Task finishe...r('canceled')>) at /home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_sync_base.py:111
handle: <Handle SyncBase._sync.<locals>.<lambda>(<Task finishe...r('canceled')>) at /home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_sync_base.py:111>
Traceback (most recent call last):
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 111, in <lambda>
    task.add_done_callback(lambda _: g_self.switch())
                                     ^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_page.py", line 161, in <lambda>
    self._channel.on("download", lambda params: self._on_download(params))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_page.py", line 283, in _on_download
    self.emit(
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/base.py", line 208, in emit
    handled = self._call_handlers(event, args, kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/base.py", line 184, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/asyncio.py", line 53, in _emit_run
    self.emit("error", exc)
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/base.py", line 211, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/base.py", line 169, in _emit_handle_potential_error
    raise error
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pyee/asyncio.py", line 51, in _emit_run
    coro: Any = f(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
           ^^^^^^^^
  File "/mnt/c/Users/test/Desktop/test3.py", line 175, in <lambda>
    page.on("download", lambda download: print(111111, download.save_as("download/" + download.suggested_filename)))
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 7408, in save_as
    return mapping.from_maybe_impl(self._sync(self._impl_obj.save_as(path=path)))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_download.py", line 61, in save_as
    await self._artifact.save_as(path)
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_artifact.py", line 40, in save_as
    stream = cast(Stream, from_channel(await self._channel.send("saveAsStream")))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.5/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: canceled
```

### Additional context
test code
```
# coding: utf-8
import os
import json

from loguru import logger
from playwright.sync_api import sync_playwright, Error as PWError


def download_file(page, urls=[], tmp_file_name='tmp_download.html'):
    html_links = [f'<a href="{url}">{url}</a>' for url in urls]
    tmp_html = f"""<html><body>{''.join(html_links)}</body></html>"""

    file = os.path.realpath(__file__)
    tmp_dir = os.path.dirname(os.path.realpath(file)) + "cache/"
    if not os.path.exists(tmp_dir):
        os.mkdir(tmp_dir)
    tmpfile_path = tmp_dir + tmp_file_name
    with open(tmpfile_path, 'w', encoding='utf8') as f:
        f.write(tmp_html)
    page.goto("file://" + tmpfile_path)

    for link in page.query_selector_all('//a'):
        url = link.get_attribute('href')
        with page.expect_download() as download_info:
            link.click(modifiers=["Alt", ])

        download = download_info.value
        download_url = download.url
        file_name = "download/" + download.suggested_filename
        download.save_as(file_name)
    return file_name, download_url


def main(download=False, headless=True):
    url = "https://www.gov.il/BlobFolder/reports/alert_1629d/he/ALERT-INCD-IL-C-1692D.pdf"
    proxy = None
    data = {
        "content": None,
        "status_code": None,
        "filename": None
    }

    with sync_playwright() as p:
        try:
            browser = page = None
            browser = getattr(p, "chromium").launch(headless=headless)
            context_kwargs = {
                "ignore_https_errors": True,
                "locale": "en-US",
                "viewport": {"width": 1920, "height": 1080}
            }
            if proxy:
                context_kwargs["proxy"] = {"server": proxy}
            context = browser.new_context(**context_kwargs)
            page = context.new_page()
            # same error
            # page.on("download", lambda download: print(111111, download.save_as("download/" + download.suggested_filename)))
            if download:
                data["download"] = download
                data["filename"], data["download_url"] = download_file(page, [url])
                return data
        except Exception as e:
            logger.exception(f"Unknow error:")
        finally:
            if page:
                page.close()
            if browser:
                browser.close()


if __name__ == '__main__':
    main(True)
```

### Environment

```shell
ubuntu wsl2
```

**Comment by dgozman** [comment]
@FANGOD We need more information to act on this issue. Could you please provide a self-contained repro that we can run locally? Unfortunately, I cannot run the provided snippet, because it is not the full self-contained script.

**Comment by FANGOD** [comment]
> @FANGOD We need more information to act on this issue. Could you please provide a self-contained repro that we can run locally? Unfortunately, I cannot run the provided snippet, because it is not the full self-contained script.

Updated the complete test script.

**Comment by dgozman** [comment]
Closing as per above. If you still believe there is a bug in Playwright, please file a new issue by filling in the "Bug Report" template.

**Comment by robinp** [comment]
Drive-by comment (since I faced something similar with 'cancelled' but not quite the same - not involving headless mode or differing upstream response):

In the block

```
        with page.expect_download() as download_info:
            link.click(modifiers=["Alt", ])

        download = download_info.value
        download_url = download.url
        file_name = "download/" + download.suggested_filename
        download.save_as(file_name)
```
it seems indentation is off. The `download_info` is created in the `with` block, but used outside of the block after. This can cause (IIUC) expect_download to cancel its context or whatever after the block is exited.

In my case it fixed the cancelling long download to put those following ops in the with block. Not sure why I had that way (and this issue's writer too), maybe it is some doc bug somewhere.

**Comment by gradder26** [comment]
I am facing the same issue:

playwright._impl._errors.Error: canceled


running in local is working fine, running in selenium grid is not working
