### ISSUE TITLE
[Feature] documenting `offline` with a usable example

### ISSUE THREAD

**Issue by jamesbraza** [microsoft/playwright#29360]
I am using `playwright==1.41.1` and am trying to use `offline=True` to force cache usage like so:

```python
import pathlib

from playwright.sync_api import sync_playwright

CACHE_DIR = pathlib.Path(__file__).parent / "cache"

with (
    sync_playwright() as p,
    p.chromium.launch(
        headless=False, args=[f"--disk-cache-dir={CACHE_DIR!s}"]
    ) as browser,
):
    # Run once to cache the results
    with browser.new_context(
        extra_http_headers={"Cache-Control": f"max-age={60*60*24*30}"},
    ) as context:
        page = context.new_page()
        page.goto("https://example.com/")
        page.wait_for_load_state(state="networkidle")
    # Run many times during unit testing, loading from disk cache
    with browser.new_context(offline=True) as context:
        page = context.new_page()
        page.goto("https://example.com/")
```

However, it doesn't work, I am getting:

```none
Traceback (most recent call last):
  File "/Users/user/code/play/a.py", line 23, in <module>
    page.goto("https://example.com/")
  File "/Users/user/code/repo/venv/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 9327, in goto
    self._sync(
  File "/Users/user/code/repo/venv/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.12/site-packages/playwright/_impl/_page.py", line 484, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 149, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/user/code/repo/venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 495, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: net::ERR_INTERNET_DISCONNECTED at https://example.com/
```

This issue is halfway a question, and halfway a feature request (that I am happy to contribute): how can one get an `offline` context to actually work?

I would like to add an example to the documentation

**Comment by dgozman** [comment]
@jamesbraza Offline does not guarantee that the page is served from the cache. Browsers have complex logic that controls this behavior. The offline feature is usually useful to test that your service worker handles offline pretty well.
