### ISSUE TITLE
[Bug]: Playwright crashes reliably accessing storage state on Chrome Web Store domain

### ISSUE THREAD

**Issue by shravan2x** [microsoft/playwright#29492]
### Version

1.41.2

### Steps to reproduce

Run this code:

```
string url = "https://chromewebstore.google.com/";
using var playwright = await Playwright.CreateAsync();
BrowserTypeLaunchOptions browserOptions = new BrowserTypeLaunchOptions()
{
    Channel = "chrome",
    Headless = false,
};
await using var browser = await playwright.Chromium.LaunchAsync(browserOptions);
await using var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
await page.GotoAsync(url);
await page.WaitForLoadStateAsync(LoadState.Load);
await context.StorageStateAsync();
```

### Expected behavior

No crashes.

### Actual behavior

The browser crashes with this exception:

```
Unhandled exception. Microsoft.Playwright.TargetClosedException: Target page, context or browser has been closed
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 207
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 537
   at Microsoft.Playwright.Core.BrowserContext.CloseAsync(BrowserContextCloseOptions options) in /_/src/Playwright/Core/BrowserContext.cs:line 322
...
```

### Additional context

Interestingly, the error doesn't seem to repro when running in headless mode.

### Environment

```Text
- Operating System: [Windows 11]
- CPU: [x86_64]
- Browser: Chromium
- .NET Version (TFM): [net8.0]
- Other info:
```

**Comment by mxschmitt** [comment]
I can reproduce with Puppeteer:

```ts
import puppeteer from 'puppeteer';

(async () => {
  const browser = await puppeteer.launch({
    channel: 'chrome',
    headless: false,
    dumpio: true,
  });
  const page = await browser.newPage();
  await page.goto('https://chromewebstore.google.com/');
  await page.setRequestInterception(true);
  page.on('request', interceptedRequest => interceptedRequest.respond({
      body: 'Hello, World!',
      status: 200,
      contentType: 'text/plain'
  }));
  await page.goto('https://chromewebstore.google.com/');

  await browser.close();
})();
```

**Comment by RuanAlesi** [comment]
> I can reproduce with Puppeteer:
> 
> ```ts
> import puppeteer from 'puppeteer';
> 
> (async () => {
>   const browser = await puppeteer.launch({
>     channel: 'chrome',
>     headless: false,
>     dumpio: true,
>   });
>   const page = await browser.newPage();
>   await page.goto('https://chromewebstore.google.com/');
>   await page.setRequestInterception(true);
>   page.on('request', interceptedRequest => interceptedRequest.respond({
>       body: 'Hello, World!',
>       status: 200,
>       contentType: 'text/plain'
>   }));
>   await page.goto('https://chromewebstore.google.com/');
> 
>   await browser.close();
> })();
> ```
> 
> Filed upstream as https://issues.chromium.org/u/1/issues/325103515.

@mxschmitt I have the same issue with Firefox. Did you try it as well?

**Comment by mxschmitt** [comment]
@RuanAlesi your issue looks different, I recommend to file a separate bug report.

**Comment by shravan2x** [comment]
@mxschmitt I'm unable to access the upstream issue link, it just says Access Denied. Do you know why?

**Comment by mxschmitt** [comment]
Yes, Google treats crash reports as sensitive hence you don't have access.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
