### ISSUE TITLE
[Bug]: closing all pages of `launchPersistentContext` causes crash

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright#29726]
### Version

1.42.0

### Steps to reproduce

run 
```js
const { chromium } = require("playwright")

const main = async () => {
    const context = await chromium.launchPersistentContext('.', {headless: false});
    context.on("close", () => {
        console.log("closed context")
    })
    await context.pages()[0].close()
    console.log("closed page")
    await context.newPage()
    await context.pages()[0].close()
}
main()
```

### Expected behavior

no error. And if there was an error, I expect the contexts `on('close'` to be executed.

### Actual behavior

A bug happened:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserContext.newPage: Protocol error (Target.createTarget): Failed to open a new tab
    at main (C:\Users\AMONGUS\projects\test-pw\index.js:10:19) {
  name: 'Error'
}
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11500H @ 2.90GHz
    Memory: 4.05 GB / 31.20 GB
  Binaries:
    Node: 19.7.0 - ~\AppData\Roaming\node\node.EXE
    npm: 9.5.0 - ~\AppData\Roaming\node\npm.CMD
  IDEs:
    VSCode: 1.86.2 - C:\Users\AMONGUS\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    playwright: ^1.42.0 => 1.42.0
```

**Comment by dev-jonghoonpark** [comment]
I tested using my devices

## in macOS
just still alived without error throw.  
but, context close event not triggered

```
  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 332.84 MB / 16.00 GB
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1 
    playwright: ^1.42.1 => 1.42.1 
```

## in windows
throw error

```
C:\project\palywright-playground\src\chromium.ts:10
    await context.newPage()
                  ^
browserContext.newPage: Target page, context or browser has been closed
```

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) N100
    Memory: 8.72 GB / 15.78 GB
  Binaries:
    Node: 21.6.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  IDEs:
    VSCode: 1.87.0 - C:\Users\jonghoon\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
    playwright: ^1.42.1 => 1.42.1
```

## in ubuntu
throw error

```
/home/jonghoonpark/playwright-playground/chromium.ts:10
    await context.newPage()
                  ^
browserContext.newPage: Protocol error (Target.createTarget): Failed to open a new tab
    at main (/home/jonghoonpark/playwright-playground/chromium.ts:10:19) {
  name: 'Error'
}
```

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 18.45 GB / 31.27 GB
    Container: Yes
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    playwright: ^1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
