### ISSUE TITLE
[Bug]: Basic component crashes when mounting

### ISSUE THREAD

**Issue by cristinallamas** [microsoft/playwright#29802]
### Version

1.42.1

### Steps to reproduce

React version: 16.9.0
Playwright CT version: 1.42.1

Component file

```
import React from "react";

const Spinner = ({ children }) => (
  <div className="opt-loader-container">
    <span className="bc-loader bc-loader-is-loading bc-loader--large"></span>
    {children}
  </div>
);

export default Spinner;

```

-----------------------------
Test File 

```
import { test, expect} from "@playwright/experimental-ct-react17";
import Spinner from "../src/components/Spinner/Spinner";


test("should render Timer", async ({ mount }) => {
  let component = await mount(<Spinner />);
});
```

-----------------------------

Error:
```
> playwright test -c playwright-ct.config.js


Running 1 test using 1 worker

vite v5.1.4 building for production...
✓ 5 modules transformed.
Error: [vite]: Rollup failed to resolve import "react/jsx-runtime" from "/Users/cristinallamas/BC/online-placement-test/src/components/Spinner/Spinner.jsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

    at viteWarn (/myproject/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67078:27)
    at onwarn (/myproject/node_modules/@vitejs/plugin-react/dist/index.mjs:250:9)
    at onRollupWarning (/myproject/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67103:9)
    at onwarn (/myproject/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:66810:13)
    at /myproject/node_modules/rollup/dist/es/shared/node-entry.js:18308:13
    at Object.logger (/myproject/node_modules/rollup/dist/es/shared/node-entry.js:19965:9)
    at ModuleLoader.handleInvalidResolvedId (/myproject/node_modules/rollup/dist/es/shared/node-entry.js:18909:26)
    at /myproject/node_modules/rollup/dist/es/shared/node-entry.js:18867:26
  1 did not run
transforming (6) ../node_modules/react/node_modules/object-assign/index.js
To open last HTML report run:

  npx playwright show-report
```

### Expected behavior

I expect to see no errors and the test to run 

### Actual behavior

I the test crashes when I mount a component `mount(<Component />)`, the test doesn't crash when I run `mount(<h1>hello</h1>)`

### Environment

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 19.13 MB / 16.00 GB
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/experimental-ct-react17: ^1.42.1 => 1.42.1
```

**Comment by dgozman** [comment]
@cristinallamas We would need a full self-contained repro to work on this. The two snippets you've shared are not enough for me to be able to reproduce the issue, unfortunately.

**Comment by cristinallamas** [comment]
the repos have sensitive information, but maybe you can tell me what this error means? I was unable to find any info anywhere related to this

**Comment by dgozman** [comment]
@cristinallamas Searching on the internet, there could be plenty of reasons. Given that error is produced by playwright's dependency vite, I am not sure how to help you without looking at the repro.

**Comment by mxschmitt** [comment]
Looks like you are using React 16 and Playwright does not support React 16. We only support 17/18.
