### ISSUE TITLE
[Bug]: Playwright Test for VSCode doesn't work with Yarn workspaces

### ISSUE THREAD

**Issue by massimopalmieri** [microsoft/playwright#29848]
### Version

1.42.1

### Steps to reproduce

- clone my repo at https://github.com/massimopalmieri/monorepo 
- run `yarn` to install the dependencies
- open the project in vscode
- go to the testing tab
- select "show browser"
- click on run tests

### Expected behavior

the browser should start and the test should be executed

### Actual behavior

the browser doesn't start and 

### Environment

```shell
System:
  OS: macOS Sonoma 14.1.1 
Binaries:
  Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
  yarn: 4.1.1 - ~/.nvm/versions/node/v20.10.0/bin/yarn
npmPackages:
  @playwright/test: 1.41.1
```

**Comment by dgozman** [comment]
I can repro. This is probably related to `pnp` mode. Extension tries to reach into `node_modules` that does not exist.

```
[error] TypeError: Cannot read properties of undefined (reading 'setAutoClose')
    at Fe.willRunTests (/Users/dgozman/.vscode/extensions/ms-playwright.playwright-1.0.22/out/extension.js:21:484)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Me.runTests (/Users/dgozman/.vscode/extensions/ms-playwright.playwright-1.0.22/out/extension.js:16:4858)
    at je.runTests (/Users/dgozman/.vscode/extensions/ms-playwright.playwright-1.0.22/out/extension.js:92:3305)
    at $e._runTest (/Users/dgozman/.vscode/extensions/ms-playwright.playwright-1.0.22/out/extension.js:97:177)
    at $e._runMatchingTests (/Users/dgozman/.vscode/extensions/ms-playwright.playwright-1.0.22/out/extension.js:93:9685)
    at Timeout._onTimeout (/Users/dgozman/.vscode/extensions/ms-playwright.playwright-1.0.22/out/extension.js:93:8825)
```

**Comment by dgozman** [comment]
Merging into #18931, which has the same cause.

**Comment by massimopalmieri** [comment]
@dgozman not sure of it helps, but when "show browser" in not checked the tests run and when "show traceview" is checked the browser doesn't start but the tests still run
