### ISSUE TITLE
[Bug]: Error: page.goto: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by costa-collibra** [microsoft/playwright#29874]
### Version

1.42.0

### Steps to reproduce

This is really hard to reproduce as the test passes locally for me. This issue is consistently failing when running in our Jenkins pipeline.

I can share our code though.

Its a basic function really

```typescript
const visit = async (path: string): Promise<void> => {
    await page.goto(path);
    await closePendo();
  };
```

The error is related to this line

`await page.goto(path);`

The test file calls visit like this

`await assetPage.visit(resources.asset.id);`

And the resource is created in the fixture

```typescript
resources: async ({}, use) => {
    const community = await createCommunity();
    const assetType = await createAssetType(BUSINESS_ASSET_ASSET_TYPE_ID);
    await addBasicGlobalAssignment(assetType.id);
    const domain = await createDomain(community.id, BUSINESS_ASSET_DOMAIN_TYPE_ID);
    await assignDomainTypeToAssetTypeWithId(faker.string.uuid(), assetType.id, domain.type.id);
    const asset = await createAsset(domain.id, assetType.id);

    await use({ asset, domain, community });
  },
```

Basically in the fixture we call some rest apis to generate some data, part of this data is used to navigate to the correct page.

### Expected behavior

I expect the page to open as it does locally.

### Actual behavior

I see the following error

```
Error: page.goto: Target page, context or browser has been closed
Call log:
  - navigating to "https://k8s-lib-ns-ygrqfjrqyf.dev.cp.collibra.dev/asset/018e2be9-6f87-7805-84bd-c27e58de085b", waiting until "load"


   at ../pages/common/createCommonPage.ts:35

  33 |    */
  34 |   const visit = async (path: string): Promise<void> => {
> 35 |     await page.goto(path);
     |                ^
  36 |     await closePendo();
  37 |   };
  38 |

    at Object.visit (/usr/dgc-playwright/pages/common/createCommonPage.ts:35:16)
    at Object.visit (/usr/dgc-playwright/pages/asset/createAssetPage.ts:56:22)
    at /usr/dgc-playwright/tests/asset-management/at-a-glance-sidebar/articulationscore.test.ts:40:25
    at /usr/dgc-playwright/tests/asset-management/at-a-glance-sidebar/articulationscore.test.ts:22:7
```

### Additional context

Iv never seen this error in Chromium whether it be locally or in the pipeline but this issue us a big concern for us.

### Environment

```shell
System:                                                                                                                  
    OS: Linux 5.4 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)                                                         
CPU: (16) x64 AMD EPYC 7571                                                                                            
    Memory: 59.03 GB / 61.70 GB                                                                                            
    Container: Yes                                                                                                         
Binaries:                                                                                                                
    Node: 20.11.1 - /usr/bin/node                                                                                          
    Yarn: 1.22.21 - /usr/bin/yarn                                                                                          
    npm: 10.2.4 - /usr/bin/npm                                                                                             
Languages:                                                                                                               
    Bash: 5.1.16 - /usr/bin/bash                                                                                           
npmPackages:                                                                                                             
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by Horsty80** [comment]
Hum, have you try to downgrade version of playwright to see if it's related to a specific version ? 

I'm looking for something, because i have this kind of error only on my jenkins pipeline too

**Comment by costa-collibra** [comment]
@Horsty80 not yet as only upgraded last week but it is certainly an option for us to try.

Maybe it is related to running Linux, im going to see if I can replicate manually on current version first, so I can share more details if I find them

**Comment by Horsty80** [comment]
I run my test on Linux too and pipeline on jenkins 
I try to revert version and use firefox
But very tricky issue

**Comment by costa-collibra** [comment]
@Horsty80 have you been able to replicate it manually yet using docker for example?

**Comment by Horsty80** [comment]
No i can not replicate manually

**Comment by costa-collibra** [comment]
@mxschmitt I will try replicate it tomorrow and feed back, thanks for the tip

**Comment by costa-collibra** [comment]
@mxschmitt here are some extra logs are any of these useful?

```
pw:browser <launching> /ms-playwright/firefox-1440/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-ghcPys -juggler-pipe -silent +0ms
  pw:browser <launched> pid=147 +5ms
  pw:browser [pid=147][err] *** You are running in headless mode. +27ms
  pw:browser [pid=147][out] console.warn: services.settings: Ignoring preference override of remote settings server +149ms
  pw:browser [pid=147][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment +0ms
  pw:browser [pid=147][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.4653) [GFX1-]: glxtest: libpci missing +286ms
  pw:browser [pid=147][out] console.error: ({}) +48ms
  pw:browser [pid=147][out]  +33ms
  pw:browser [pid=147][out] Juggler listening to the pipe +0ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=anti-tracking-url-decoration&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +266ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=query-stripping&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=fingerprinting-protection-overrides&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +0ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=partitioning-exempt-urls&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +785ms
  pw:browser [pid=147][out] console.error: ({}) +181ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=hijack-blocklists&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +250ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=doh-providers&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +2ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=search-telemetry-v2&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=search-config&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +59ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=search-config-overrides&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=top-sites&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +330ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=doh-config&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +181ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=message-groups&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1s
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=cfr&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +12ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=message-groups&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +26ms
  pw:browser [pid=147][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=url-classifier-skip-urls&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +3s
  pw:browser [pid=147][err] JavaScript warning: resource://gre/modules/UpdateService.sys.mjs, line 3858: unreachable code after return statement +24s
  pw:browser [pid=147][out] console.error: (new Error("Polling for changes failed: XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?_expected=0' is not a valid URL..", "resource://services-settings/remote-settings.sys.mjs", 324)) +38ms
  pw:browser [pid=147][out]  +27s
  pw:browser [pid=147][out]         ERROR: Component returned failure code: 0x804b001b (NS_ERROR_INVALID_CONTENT_ENCODING) [nsIStreamListener.onDataAvailable] convertString@chrome://juggler/content/NetworkObserver.js:921:13 +1ms
  pw:browser [pid=147][out] getBase64EncodedResponse@chrome://juggler/content/NetworkObserver.js:830:18 +0ms
  pw:browser [pid=147][out] getResponseBody@chrome://juggler/content/NetworkObserver.js:91:34 +0ms
  pw:browser [pid=147][out] Network.getResponseBody@chrome://juggler/content/protocol/PageHandler.js:260:30 +0ms
  pw:browser [pid=147][out] dispatch@chrome://juggler/content/protocol/Dispatcher.js:132:39 +0ms
  pw:browser [pid=147][out] _dispatch@chrome://juggler/content/protocol/Dispatcher.js:69:36 +0ms
  pw:browser [pid=147][out] receiveMessage@chrome://juggler/content/components/Juggler.js:117:20 +0ms
  pw:browser [pid=147][out]  +0ms
  pw:browser [pid=147][err] Exiting due to channel error. +5s
  pw:browser [pid=147][err] Exiting due to channel error. +1ms
  pw:browser [pid=147] <process did exit: exitCode=null, signal=SIGSEGV> +40ms
  pw:browser [pid=147] starting temporary directories cleanup +1ms
  pw:browser [pid=147][out]        +100ms
  pw:browser [pid=147] finished temporary directories cleanup +79ms
```

**Comment by costa-collibra** [comment]
This below is from a passing test from the same test run

```
pw:browser <launching> /ms-playwright/firefox-1440/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-DqCPPV -juggler-pipe -silent +0ms
  pw:browser <launched> pid=188 +7ms
  pw:browser [pid=188][err] *** You are running in headless mode. +31ms
  pw:browser [pid=188][out] console.warn: services.settings: Ignoring preference override of remote settings server +132ms
  pw:browser [pid=188][out] console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment +1ms
  pw:browser [pid=188][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.446727) [GFX1-]: glxtest: libpci missing +286ms
  pw:browser [pid=188][out] console.error: ({}) +42ms
  pw:browser [pid=188][out]  +34ms
  pw:browser [pid=188][out] Juggler listening to the pipe +0ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=anti-tracking-url-decoration&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +275ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=query-stripping&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=fingerprinting-protection-overrides&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +0ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=partitioning-exempt-urls&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +779ms
  pw:browser [pid=188][out] console.error: ({}) +171ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=hijack-blocklists&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +213ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=doh-providers&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +15ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=search-telemetry-v2&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=search-config&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +30ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=search-config-overrides&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=top-sites&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +358ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=doh-config&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +196ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=message-groups&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +1s
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=cfr&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +9ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=message-groups&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +3ms
  pw:browser [pid=188][out] console.error: (new SyntaxError("XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?collection=url-classifier-skip-urls&bucket=main&_expected=0' is not a valid URL.", (void 0), 133)) +5s
  pw:browser [pid=188][out] console.error: (new Error("Polling for changes failed: XMLHttpRequest.open: '/buckets/monitor/collections/changes/changeset?_expected=0' is not a valid URL..", "resource://services-settings/remote-settings.sys.mjs", 324)) +22s
  pw:browser [pid=188][err] JavaScript warning: resource://gre/modules/UpdateService.sys.mjs, line 3858: unreachable code after return statement +34ms
```

**Comment by mxschmitt** [comment]
`<process did exit: exitCode=null, signal=SIGSEGV>` is a Firefox crash. In order for us triage this issue further, we need reproduction steps. Would it be possible from your side to try to reduction them, so you have something which you can share? Having something which fails sometimes would be already helpful for us in order to investigate.

**Comment by costa-collibra** [comment]
@mxschmitt I am going to spend some time later this afternoon to try reproduce for you

**Comment by costa-collibra** [comment]
Im still seeing this issue but having issues reproducing locally im still working on it

**Comment by yury-s** [comment]
We need to be able to reproduce the problem to make this report actionable. Please file a new issue when you have a reproduction.

**Comment by murilozilli** [comment]
also having this issue whilst on lambda

**Comment by nikhilrizal** [comment]
> also having this issue whilst using playwright v1.41.2 on lambda

did you found solutions

**Comment by cereallarceny** [comment]
> also having this issue whilst using playwright v1.41.2 on lambda

Same

**Comment by Tushar-Tilwani** [comment]
See the same issue but there are no traces generated. It is most prominent in firefox.

**Comment by HamzaMiz** [comment]
i have the same issue on chromium also from 50 test there's 3 that have that issue not always the same tests tho

**Comment by shriyashfinov8** [comment]
getting the same issue when running on lambda, if anyone has the solution please help!

**Comment by mxschmitt** [comment]
Please file a separate issue, so we can take a look with a reproduction. Thank you!
