### ISSUE TITLE
[Question]: Unable to Run Component Testing on Component with an embeded Child Component

### ISSUE THREAD

**Issue by HTMansuri** [microsoft/playwright#29988]
### Version

1.42.1

### Steps to reproduce

1. Clone https://github.com/HTMansuri/Playwright-Component-Testing.git
2. npm run test-ct

### Expected behavior

Expected to Get Tests passed

### Actual behavior

When running component test on AppHeader.tsx component, which have a ContactPhoneLink component embeded, the build fails with [Vite]: Rollup failed error:
```
> proj0318@1.0.0 test-ct
> playwright test -c playwright-ct.config.ts


Running 6 tests using 6 workers

vite v5.1.6 building for production...
✓ 6 modules transformed.
Error: [vite]: Rollup failed to resolve import "@/ContactLink" from "C:/Users/609559/projects/Playwright-Component-Testing/MyComponentTesting/src/AppHeader.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

    at viteWarn (C:\Users\609559\projects\Playwright-Component-Testing\node_modules\vite\dist\node\chunks\dep-jvB8WLp9.js:67190:27)
    at onwarn (C:\Users\609559\projects\Playwright-Component-Testing\node_modules\@vitejs\plugin-react\dist\index.mjs:250:9)
    at onRollupWarning (C:\Users\609559\projects\Playwright-Component-Testing\node_modules\vite\dist\node\chunks\dep-jvB8WLp9.js:67215:9)
    at onwarn (C:\Users\609559\projects\Playwright-Component-Testing\node_modules\vite\dist\node\chunks\dep-jvB8WLp9.js:66922:13)
    at C:\Users\609559\projects\Playwright-Component-Testing\node_modules\rollup\dist\es\shared\node-entry.js:18303:13
    at Object.logger (C:\Users\609559\projects\Playwright-Component-Testing\node_modules\rollup\dist\es\shared\node-entry.js:19950:9)
    at ModuleLoader.handleInvalidResolvedId (C:\Users\609559\projects\Playwright-Component-Testing\node_modules\rollup\dist\es\shared\node-entry.js:18893:26)
    at C:\Users\609559\projects\Playwright-Component-Testing\node_modules\rollup\dist\es\shared\node-entry.js:18851:26
  6 did not run
transforming (14) ..\node_modules\react\jsx-runtime.js
To open last HTML report run:

  npx playwright show-report
``` 

### Additional context

Build and Test for just ContactLink.tsx component Succeeds, if AppHeader.tsx file is not imported.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 39.67 GB / 63.78 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.87.2 - C:\Users\609559\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/experimental-ct-react: ^1.42.1 => 1.42.1
    @playwright/test: ^1.42.1 => 1.42.1
```

Thank you for your help !

**Comment by yury-s** [comment]
You need to [specify](https://playwright.dev/docs/test-components#i-have-a-project-that-already-uses-vite-can-i-reuse-the-config) alias mapping for '@' in `playwright-ct.config.ts`:

```diff
diff --git a/playwright-ct.config.ts b/playwright-ct.config.ts
index e97bdf1..11c9a6a 100644
--- a/playwright-ct.config.ts
+++ b/playwright-ct.config.ts
@@ -1,4 +1,5 @@
 import { defineConfig, devices } from '@playwright/experimental-ct-react';
+import { resolve } from 'path';
 
 /**
  * See https://playwright.dev/docs/test-configuration.
@@ -26,6 +27,14 @@ export default defineConfig({
 
     /* Port to use for Playwright component endpoint. */
     ctPort: 3100,
+
+    ctViteConfig: {
+      resolve: {
+        alias: {
+          '@': resolve(__dirname, './MyComponentTesting/src'),
+        },
+      },
+    }
   },
 
   /* Configure projects for major browsers */
```

**Comment by HTMansuri** [comment]
Thank you so much for your perfect response. Also, looking forward to get [#29854](https://github.com/microsoft/playwright/issues/29854) resolved.

Thank you!

Best,
Huzaif
