### ISSUE TITLE
[Regression]: Playwright hangs during test

### ISSUE THREAD

**Issue by eelco** [microsoft/playwright#30307]
### Last Good Version

1.38.1

### First Bad Version

1.39.0

### Steps to reproduce

I don’t have a way to minimally reproduce this issue, but I’m happy to help debug this.

When upgrading Playwright I found that it hangs on a “harmless” piece of code. This fails:
```
if (value instanceof SafeJS) {
    return String(value)
}
```

The test is running with an `await page.waitForFunction(…)`.

I tried debugging with the good old `console.log` and to my suprise I found that that actually “fixes” the hang… (although not in 1.39.0, only with 1.41.2?)
```
if (value instanceof SafeJS) {
    console.log("anything…")
    return String(value)
}
```

Some more details:
- This only happens with Chromium, running the same test in WebKit or Firefox works.
- I’ve renamed some directory in the cache to test with two different versions of Chromium (build 1080 and 1084) with two different versions of Playwright (1.38.1 and 1.39.0). The problem does _not_ appear to be Chromium, as the test gets stuck only with Playwright 1.39.0 and with both versions of Chromium.
- While the logs don’t print as Chromium hangs, as soon as the timeout triggers, it _does_ log, suggesting that the code ran?

### Expected behavior

The tests does not hang.

### Actual behavior

The test hangs.

### Additional context

The unstructured details can be found on Discord: https://discord.com/channels/807756831384403968/1224377950384947200

The CPU / operating system environment is not relevant. This happened both on macOS (arm) and Linux (x64).

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 52.25 MB / 16.00 GB
  Binaries:
    Node: 20.12.0 - /usr/local/bin/node
    Yarn: 4.1.1 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
We unfortunately need a reproducible in order to look into issues like this. Something we can run locally which works in some Playwright version but does not work in the other version. Would it be possible to provide one? Otherwise we can't act on it.

**Comment by eelco** [comment]
I understand, but I hope you can also understand that extracting a minimal reproducible issue for this is a significant amount of work and the [diff](https://github.com/microsoft/playwright/compare/v1.38.1...v1.39.0) is not even that big (most is documentation and typos). (And we don’t use the runner, so this is just in the library, reducing the surface further.)

I’ve been asking for help debugging this on Discord multiple times, with no real response. Luckily your development process is pretty straightforward (and really fast ❤️), so been diving in further myself. I’ve bisected to find the exact commit that is causing the issue and it’s this one: https://github.com/microsoft/playwright/commit/1857a3fb5653acde8bebd032d32c82d6b433b5d7

It seems that with the `try/catch`, `innerSerialize` can get stuck in an infinite loop (before it would just exit because it throws). This is on us, we were indeed logging something that had loops in it, but I would expect Playwright to recognize and not hang on that. I forgot that this was the case, because I had changed that log line in the process of debugging the more mysterious bug above.

Looking further, it seems that there is _also_ a log line after the the place where Playwright seems to hang that contains an object with loops. So indeed, the point that I thought it was hanging was _just_ before it actually hangs.

The only thing I can’t explain is why adding a console.log before it hangs “solves” it. Something odd is happening, where each character of the log is separated by a space (e.g. first it repeated logs `foo` and then it turns into `f o o`). I also don’t understand why it only happens with Chromium.

Here are the DEBUG logs (I should definitely have tried those sooner too…) where it crashes:
```
  pw:error Error: Target crashed
  pw:error     at Frame._invalidateNonStallingEvaluations (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:441:19)
  pw:error     at FrameManager._invalidateNonStallingEvaluations [as dispose] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:72:13)
  pw:error     at Page.dispose [as _didCrash] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/page.js:167:24)
  pw:error     at FrameSession._didCrash [as _onTargetCrashed] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:737:16)
  pw:error     at CRSession._onTargetCrashed (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:387:134)
  pw:error     at CRSession.emit (node:events:518:28)
  pw:error     at emit (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:190:14) +5s
  pw:error Error: Target crashed
  pw:error     at Frame._invalidateNonStallingEvaluations (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:441:19)
  pw:error     at FrameManager._invalidateNonStallingEvaluations [as dispose] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:72:13)
  pw:error     at Page.dispose [as _didCrash] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/page.js:167:24)
  pw:error     at FrameSession._didCrash [as _onTargetCrashed] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:737:16)
  pw:error     at CRSession._onTargetCrashed (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:387:134)
  pw:error     at CRSession.emit (node:events:518:28)
  pw:error     at emit (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:190:14) +12ms
  pw:error Error: Target crashed
  pw:error     at Frame._invalidateNonStallingEvaluations (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:441:19)
  pw:error     at FrameManager._invalidateNonStallingEvaluations [as dispose] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:72:13)
  pw:error     at Page.dispose [as _didCrash] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/page.js:167:24)
  pw:error     at FrameSession._didCrash [as _onTargetCrashed] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:737:16)
  pw:error     at CRSession._onTargetCrashed (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:387:134)
  pw:error     at CRSession.emit (node:events:518:28)
  pw:error     at emit (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:190:14) +0ms
  pw:error Error: Target crashed
  pw:error     at Frame._invalidateNonStallingEvaluations (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:441:19)
  pw:error     at FrameManager._invalidateNonStallingEvaluations [as dispose] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:72:13)
  pw:error     at Page.dispose [as _didCrash] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/page.js:167:24)
  pw:error     at FrameSession._didCrash [as _onTargetCrashed] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:737:16)
  pw:error     at CRSession._onTargetCrashed (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crPage.js:387:134)
  pw:error     at CRSession.emit (node:events:518:28)
  pw:error     at emit (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:190:14) +0ms
  pw:channel:event {
  pw:channel:event   guid: 'page@cd38ee85d4ea0cc7106798b67114dd7c',
  pw:channel:event   method: 'crash',
  pw:channel:event   params: undefined
  pw:channel:event } +444ms
  pw:channel:response {
  pw:channel:response   id: 124,
  pw:channel:response   result: {
  pw:channel:response     value: {
  pw:channel:response       s: 'T14:26:41.862Z debug: [CodeGenerationStore] serializeComponent'
  pw:channel:response     }
  pw:channel:response   }
  pw:channel:response } +428ms
  pw:api <= jsHandle.evaluateExpression succeeded +429ms
  pw:error Error: Target crashed
  pw:error     at CRSession.send (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:161:30)
  pw:error     at CRExecutionContext.send [as rawEvaluateJSON] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crExecutionContext.js:42:28)
  pw:error     at FrameExecutionContext.rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/javascript.js:52:61)
  pw:error     at rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:459:22)
  pw:error     at Frame.cb [as raceAgainstEvaluationStallingEvents] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:450:34)
  pw:error     at Frame.raceAgainstEvaluationStallingEvents [as nonStallingRawEvaluateInExistingMainContext] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:456:17)
  pw:error     at nonStallingRawEvaluateInExistingMainContext (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:98:32)
  pw:error     at Array.map (<anonymous>)
  pw:error     at Snapshotter.map [as captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:97:37)
  pw:error     at Tracing.captureSnapshot [as _captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:280:29)
  pw:error     at Tracing._captureSnapshot [as onAfterCall] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:313:17)
  pw:error     at Proxy.call (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/instrumentation.js:57:157)
  pw:error     at DispatcherConnection.dispatch (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/dispatchers/dispatcher.js:327:7) +28s
  pw:error Error: Target crashed
  pw:error     at CRSession.send (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:161:30)
  pw:error     at CRExecutionContext.send [as rawEvaluateJSON] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crExecutionContext.js:42:28)
  pw:error     at FrameExecutionContext.rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/javascript.js:52:61)
  pw:error     at rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:459:22)
  pw:error     at Frame.cb [as raceAgainstEvaluationStallingEvents] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:450:34)
  pw:error     at Frame.raceAgainstEvaluationStallingEvents [as nonStallingRawEvaluateInExistingMainContext] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:456:17)
  pw:error     at nonStallingRawEvaluateInExistingMainContext (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:98:32)
  pw:error     at Array.map (<anonymous>)
  pw:error     at Snapshotter.map [as captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:97:37)
  pw:error     at Tracing.captureSnapshot [as _captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:280:29)
  pw:error     at Tracing._captureSnapshot [as onAfterCall] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:313:17)
  pw:error     at Proxy.call (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/instrumentation.js:57:157)
  pw:error     at DispatcherConnection.dispatch (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/dispatchers/dispatcher.js:327:7) +10ms
  pw:error Error: Target crashed
  pw:error     at CRSession.send (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:161:30)
  pw:error     at CRExecutionContext.send [as rawEvaluateJSON] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crExecutionContext.js:42:28)
  pw:error     at FrameExecutionContext.rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/javascript.js:52:61)
  pw:error     at rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:459:22)
  pw:error     at Frame.cb [as raceAgainstEvaluationStallingEvents] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:450:34)
  pw:error     at Frame.raceAgainstEvaluationStallingEvents [as nonStallingRawEvaluateInExistingMainContext] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:456:17)
  pw:error     at nonStallingRawEvaluateInExistingMainContext (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:98:32)
  pw:error     at Array.map (<anonymous>)
  pw:error     at Snapshotter.map [as captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:97:37)
  pw:error     at Tracing.captureSnapshot [as _captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:280:29)
  pw:error     at Tracing._captureSnapshot [as onAfterCall] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:313:17)
  pw:error     at Proxy.call (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/instrumentation.js:57:157)
  pw:error     at DispatcherConnection.dispatch (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/dispatchers/dispatcher.js:327:7) +0ms
  pw:error Error: Target crashed
  pw:error     at CRSession.send (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crConnection.js:161:30)
  pw:error     at CRExecutionContext.send [as rawEvaluateJSON] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/chromium/crExecutionContext.js:42:28)
  pw:error     at FrameExecutionContext.rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/javascript.js:52:61)
  pw:error     at rawEvaluateJSON (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:459:22)
  pw:error     at Frame.cb [as raceAgainstEvaluationStallingEvents] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:450:34)
  pw:error     at Frame.raceAgainstEvaluationStallingEvents [as nonStallingRawEvaluateInExistingMainContext] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:456:17)
  pw:error     at nonStallingRawEvaluateInExistingMainContext (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:98:32)
  pw:error     at Array.map (<anonymous>)
  pw:error     at Snapshotter.map [as captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/snapshotter.js:97:37)
  pw:error     at Tracing.captureSnapshot [as _captureSnapshot] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:280:29)
  pw:error     at Tracing._captureSnapshot [as onAfterCall] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/trace/recorder/tracing.js:313:17)
  pw:error     at Proxy.call (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/instrumentation.js:57:157)
  pw:error     at DispatcherConnection.dispatch (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/dispatchers/dispatcher.js:327:7) +1ms
  pw:channel:response {
  pw:channel:response   id: 118,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: 'Timeout 30000ms exceeded.',
  pw:channel:response       stack: 'TimeoutError: Timeout 30000ms exceeded.\n' +
  pw:channel:response         '    at ProgressController.run (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/progress.js:88:26)\n' +
  pw:channel:response         '    at Frame.run [as _waitForFunctionExpression] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/frames.js:1295:23)\n' +
  pw:channel:response         '    at FrameDispatcher._waitForFunctionExpression [as waitForFunction] (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/dispatchers/frameDispatcher.js:276:102)\n' +
  pw:channel:response         '    at DispatcherConnection.dispatch (/Users/eelco/Projects/playwright/packages/playwright-core/lib/server/dispatchers/dispatcher.js:313:46)',
  pw:channel:response       name: 'TimeoutError'
  pw:channel:response     }
  pw:channel:response   }
  pw:channel:response } +28s
  pw:api <= page.waitForFunction failed +28s
```

**Comment by mxschmitt** [comment]
Great job with bisecting! This seems to work as expected if the code goes into an infinite loop? Do you expect something else?

If you are able to provide us a repro, we can look into it.

**Comment by eelco** [comment]
I would not expect Playwright to crash due to a simple log statement where `toJSON` errors. I would expect `innerSerialize` to detect loops and not hang. The logs in the browser work fine but just print `"[Object: …]"`

**Comment by mxschmitt** [comment]
Since you were debugging the code, did you find out which evaluate is causing it / what kind of object you were serialising? Ideally we can construct a similar object and write a test for it.

**Comment by eelco** [comment]
It’s logging a really (really) big object, that also has loops in it. I’ve tried reproducing, but I failed by doing so with a simple object with a loop. That makes my earlier conclusion a bit shaky (although it could just be a failure in reproducing the right test setup). 

This is the reproduction I’ve tried:
```
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch();

  const page = await browser.newPage();

  page.on("console", async (msg) => {
    const values = await Promise.all(
      msg.args().map((arg) => arg.evaluate((obj) => obj))
    ).catch(() => msg.text());
    console.log(...values);
  });

  await page.evaluate(() => {
    const aap = {};
    const mies = { aap };
    aap["noot"] = mies;
    console.log(aap);
  });
})();
```
Running this with `node` works and just shows `<ref *1> { noot: { aap: [Circular *1] } }`

This code mimics the setup we use to show the logs of the page while running the test. It does not really run code on the page though, but instead uses `evaluate`. I’ve tested with loading the same code on a HTML page, but it behaves the same, so this setup should be sufficient.

I’ve been trying to debug the `utilityScriptSerializers`, but I only then realized that this is not internal code, but rather part of a script that gets injected in the page? I’m not sure what the best way to debug it is? (I’ve tried adding `console.log` to it, but that does not show up?)

Some other possible explainations of the hang:

-  It’s trying to process an object that is really huge, so it’s actuall busy and just times out? I don’t see any CPU that’s busy when running the test, so not sure if this is the case.

- It hits some bad `toJSON` code (in our codebase) that is an infinite producer. I’ve tested that with the following code, but that just logs `undefined`(?)
```
 await page.evaluate(() => {
    class Aap {
      toJSON() {
        return new Aap();
      }
    }
    const aap = new Aap();
    console.log(aap);
  });
```

The key part that I still don’t understand the role of the `try/catch`: effectively it does _not_ get stuck, as long as it’s allowed to fail on a bad `toJSON` and even though it seems the evalution stops when it catches (in the new code), that still causes a hang?!

I would _really_ appreciate some help debugging this further. I’m sure that someone familiar with this code or with debugging Playwright in general can give me some pointers that will lead to a quick solution.

**Comment by mxschmitt** [comment]
> I’ve been trying to debug the utilityScriptSerializers, but I only then realized that this is not internal code, but rather part of a script that gets injected in the page? I’m not sure what the best way to debug it is? (I’ve tried adding console.log to it, but that does not show up?)

Console.log should show up in the browser logs, also Chrome DevTools debugging should work (setting breakpoints or using the `debugger` keyword).

**Comment by mxschmitt** [comment]
Closing as part of the triaging process, since this is not actionable for us. Feel free to re-file with a reproduction, thanks for your understanding!
