### ISSUE TITLE
[Bug]: No tests passing for a simple component (component testing)

### ISSUE THREAD

**Issue by jrmarqueshd** [microsoft/playwright#30375]
### Version

1.43.1

### Steps to reproduce

I'm using `node 20.11.0` with `npm 10.5.0`.

1. clone my repo https://github.com/jrmarqueshd/testing-playwright
2. run `npm install`
3. run `npm run test-ct`

### Expected behavior

I expect to see 3 tests passing.

### Actual behavior

I'm receiving 3 errors in my console, but it is not the correct because the 3 tests are true.

![image](https://github.com/microsoft/playwright/assets/45169502/b8115ee7-eff3-4857-932f-8e8029e617ea)
![image](https://github.com/microsoft/playwright/assets/45169502/a0738a83-c7d1-4e4e-8385-2f43badd1f7c)
![image](https://github.com/microsoft/playwright/assets/45169502/542455a3-764a-4f8c-869f-a63d6f1b06dd)

Here is my full console response when I ran `npm run test-ct`
```
Error: expect(locator).toHaveAttribute(expected)

Locator: locator('#root').locator('internal:control=component')
Expected string: "submit"
Received string: ""
Call log:
  - expect.toHaveAttribute with timeout 5000ms
  - waiting for locator('#root').locator('internal:control=component')


Failed worker ran 1 test:
[chromium] › src/button.spec.tsx:9:1 › should work too

   at src/button.spec.tsx:11

   9 | test('should work too', async ({ mount }) => {
  10 | 	const component = await mount(<Button>teste</Button>);
> 11 |   expect(component).toHaveAttribute('type', 'submit');
     |                     ^
  12 | });
  13 |
  14 | test('should work also', async ({ mount }) => {

    at ./src/button.spec.tsx:11:21
Error: expect(locator).toContainText(expected)

Locator: locator('#root').locator('internal:control=component')
Expected string: "teste"
Received string: ""
Call log:
  - expect.toContainText with timeout 5000ms
  - waiting for locator('#root').locator('internal:control=component')


Failed worker ran 1 test:
[chromium] › src/button.spec.tsx:4:1 › should work

   at src/button.spec.tsx:6

  4 | test('should work', async ({ mount }) => {
  5 | 	const component = await mount(<Button>teste</Button>);
> 6 | 	expect(component).toContainText('teste');
    | 	                  ^
  7 | });
  8 |
  9 | test('should work too', async ({ mount }) => {

    at ./src/button.spec.tsx:6:20
Error: expect(locator).toHaveAttribute(expected)

Locator: locator('#root').locator('internal:control=component')
Expected string: "button"
Received string: ""
Call log:
  - expect.toHaveAttribute with timeout 5000ms
  - waiting for locator('#root').locator('internal:control=component')


Failed worker ran 1 test:
[chromium] › src/button.spec.tsx:14:1 › should work also

   at src/button.spec.tsx:16

  14 | test('should work also', async ({ mount }) => {
  15 | 	const component = await mount(<Button type="button">teste</Button>);
> 16 |   expect(component).toHaveAttribute('type', 'button');
     |                     ^
  17 | });
  18 |

    at ./src/button.spec.tsx:16:21
Error: expect(locator).toHaveAttribute(expected)

Locator: locator('#root').locator('internal:control=component')
Expected string: "button"
Received string: ""
Call log:
  - expect.toHaveAttribute with timeout 5000ms
  - waiting for locator('#root').locator('internal:control=component')


Failed worker ran 1 test:
[webkit] › src/button.spec.tsx:14:1 › should work also

   at src/button.spec.tsx:16

  14 | test('should work also', async ({ mount }) => {
  15 | 	const component = await mount(<Button type="button">teste</Button>);
> 16 |   expect(component).toHaveAttribute('type', 'button');
     |                     ^
  17 | });
  18 |

    at ./src/button.spec.tsx:16:21
```

### Environment

```shell
System:
    OS: macOS 12.7.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.29 GB / 36.00 GB
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
  IDEs:
    VSCode: 1.88.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/experimental-ct-react: ^1.43.1 => 1.43.1
```

**Comment by jrmarqueshd** [comment]
Oh! I so sorry because I forgot to put await before the expect execution. My bad.

My code now is:
```
test('should work', async ({ mount }) => {
    const component = await mount(<Button>teste</Button>);
    await expect(component).toContainText('teste');
});
```
