### ISSUE TITLE
[Question] - What's the best way to handle multiple URL's in page.goto

### ISSUE THREAD

**Issue by ajaykhobragade** [microsoft/playwright#3042]
I have a list of URL(s) that keeps changing and hence want to maintain it separately in some kinda text\excel file, which i can somehow call into my script through page.goto options, so i don't have to keep updating script often.

I see there is "Referer" option & "page.setExtraHTTPHeaders" but it still require to mention url in script itself.
Is there a better way to handle if i want to maintain url(s) independently out of actual script?

**Comment by arjun27** [comment]
Hi @ajaykhobragade, I would imagine you could manage these URLs in a different JS files and import it in your test file to use with `page.goto`. That way your tests will not need to change if the URL changes. Let me know if I did not understand this correctly :) 

```js
const { APP_URL } = require('./urls');
// ...
await page.goto(APP_URL);
```

**Comment by ajaykhobragade** [comment]
Great, do i also need to specify the directory path? Currently i have the urls.js file (attached) located at the same folder where the test script is located at but i am getting an error below, and it never gets to open url >>> Any idea what am i missing?

(node:24253) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
====================== page.goto logs ======================
[api] navigating to "undefined", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Function.completeUserURL (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/helper.js:171:23)
    at /Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/frames.js:293:35
    at ProgressController.run (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/progress.js:76:29)
    at runNavigationTask (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/frames.js:961:23)
    at Frame.goto (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/frames.js:284:16)
    at Frame.goto (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/helper.js:79:31)
    at /Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/page.js:203:61
    at Page._attributeToPage (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/page.js:356:20)
    at Page.goto (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/page.js:203:21)
    at Page.goto (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/helper.js:79:31)
  -- ASYNC --
    at Frame.goto (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/helper.js:78:23)
    at /Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/page.js:203:61
    at Page._attributeToPage (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/page.js:356:20)
    at Page.goto (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/page.js:203:21)
    at Page.goto (/Users/khobraj/Playwright/STPlaywright/node_modules/playwright/lib/helper.js:79:31)
    at /Users/khobraj/Playwright/STPlaywright/test/Advertising/Sprint29/ADV-239.js:27:15
(node:24253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24253) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by arjun27** [comment]
Thanks @ajaykhobragade. The urls would need to be exported from the other file. Assuming the urls and playwright script are in the same folder:

```js
// Save as urls.js
module.exports = {
  APP_URL: 'https://github.com'
}
```

```js
// Save as script.js
const { APP_URL } = require('./urls');
await page.goto(APP_URL);
```

**Comment by ajaykhobragade** [comment]
Awesome, works perfect!
Thanks @arjun27
