### ISSUE TITLE
[Question] Playwright server on Firefox can't be initialised

### ISSUE THREAD

**Issue by D0zee** [microsoft/playwright#30436]
Hi everyone! All was is okay while I didn't decided to change the user to non-root in my Dockerfile. I moved `.cache` folder where browsers are kept in non-root user's folder. After this Chrome and Webkit are working, but I get an exception in the case with Firefox. It seems that playwright server can't find some dependency or cache. I've already gave permission to `/tmp` folder with firefox profile, but it hasn't helped. Below I attached part of my Dockerfile and stack trace of the exception. Could you please look at it and say what I should do to fix that? Thank you in advance!

```Dockerfile
WORKDIR /app
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

COPY server.mjs package.json ./
RUN npm install express && \
    npm install @playwright/test@$VERSION && \
    npx playwright install $BROWSER && \
    npx playwright install-deps $BROWSER && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*
    
USER 1024:65534    
```

Stack trace of Exception:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TimeoutError: Timeout 180000ms exceeded. Failed to launch browser.
<launching> /home/crescent/.cache/ms-playwright/firefox-1438/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-vJxugB -juggler-pipe -silent
<launched> pid=236
[pid=236][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.217869) [GFX1-]: glxtest: libpci missing
[pid=236][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.217869) |[1][GFX1-]: glxtest: libEGL missing (t=0.217869) [GFX1-]: glxtest: libEGL missing
[pid=236][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
[pid=236][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
[pid=236][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
[pid=236][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
[pid=236][err] [Parent 236, Main Thread] WARNING: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme Yaru: 'glib warning', file /home/pwuser/firefox/toolkit/xre/nsSigHandlers.cpp:187
[pid=236][err] 
[pid=236][err] (firefox-default:236): Gtk-WARNING **: 18:55:52.255: Error loading theme icon 'dialog-warning' for stock: Icon 'dialog-warning' not present in theme Yaru
[pid=236][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 60: Error: Can't find profile directory.
    at ProgressController.run (/app/node_modules/playwright-core/lib/server/progress.js:87:26)
    at Firefox.launch (/app/node_modules/playwright-core/lib/server/browserType.js:61:38)
    at BrowserServerLauncherImpl.launchServer (/app/node_modules/playwright-core/lib/browserServerImpl.js:48:57)
    at async BrowserType.launchServer (/app/node_modules/playwright-core/lib/client/browserType.js:82:12)
    at async launchBrowserServer (file:///app/server.mjs:8:20)

```

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.

**Comment by D0zee** [comment]
@yury-s It seems that playwright can't find some dependencies or something like that when a non-root user tries to raise pw server on firefox. But I can't get what is wrong and what is required. Also it seems like something obvious that I didn't take into consideration. Could somebody help with it?

**Comment by julienloizelet** [comment]
Hello @D0zee, 
By any chance, were you able to solve your problem? 
Because I think I'm in the same case: Firefox (only) fails, non-root Docker user, same kind of error messages.
Thanks !

**Comment by D0zee** [comment]
@julienloizelet Hi, yes, I solved the problem this way:

```Dockerfile
USER non-root
# install node in an user's home directory

USER root
# install dependencies and playwright library

USER non-root
# install Playwright browser

USER root
# install dependencies from Playwright 

USER non-root
ENTRYPOINT 
```

I'm not sure that it is your case, but if it helps you I will be glad.
