### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pik528** [microsoft/playwright#30750]
### Version

1.43.0

### Steps to reproduce

! [erro] (https://github.com/microsoft/playwright/assets/164969699/995338e7-02d0-4995-95f0-d066d10f5245)
I want to connect to a local browser, the given port is 9222 but access port 50215
! [Uploading erro.jpg…] ()
, check through cmd that the computer does not have this port open

### Expected behavior

Correctly connect the specified port

### Actual behavior

Traceback (most recent call last):
  File "F:\test\playwrigh.py", line 61, in <module>
    get_cookies()
  File "F:\test\playwrigh.py", line 17, in get_cookies
    browser = p.chromium.connect_over_cdp("http://localhost:6666")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pachong\Lib\site-packages\playwright\sync_api\_generated.py", line 14275, in connect_over_cdp
    self._sync(
  File "E:\pachong\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "E:\pachong\Lib\site-packages\playwright\_impl\_browser_type.py", line 172, in connect_over_cdp
    response = await self._channel.send_return_as_dict("connectOverCDP", params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pachong\Lib\site-packages\playwright\_impl\_connection.py", line 64, in send_return_as_dict
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pachong\Lib\site-packages\playwright\_impl\_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.connect_over_cdp: connect ECONNREFUSED 127.0.0.1:50215
Call log:
<ws preparing> retrieving websocket url from http://localhost:6666

### Environment

```shell
Windows 10
pycharm2024.1
```

**Comment by pik528** [comment]
Port 6666 and port 9299 are the same, the error is the same as 50215, the rest

**Comment by mxschmitt** [comment]
This does not sound like an issue we can act on. The error suggests there is nothing running on the port.

Feel free to re-file with more details / steps for us to reproduce this issue. Thanks for your understanding.
