### ISSUE TITLE
[Bug]: Playwright extension not working in VSCode

### ISSUE THREAD

**Issue by takeshi-yanagita** [microsoft/playwright#30781]
### Version

v1.36.1

### Steps to reproduce

Ever since my VSCode updated, I'm no longer able to run tests from my Playwright Test for VSCode.
First, my tests don't show up in the extension menu.
When I try doing a run all, the following error pops:
```

Running 1 test using 1 worker

  ✓  1 [setup] › setup/login.setup.ts:6:6 › authenticate (7.8s)

  1 passed (8.4s)
/Users/takeshiyanagita/.vscode/extensions/ms-playwright.playwright-1.1.1/out/oopReporter.js:1975
        startTime: e.startTime.getTime(),
                               ^

TypeError: Cannot read properties of undefined (reading 'getTime')
    at Ue.onEnd (/Users/takeshiyanagita/.vscode/extensions/ms-playwright.playwright-1.1.1/out/oopReporter.js:7:2326)
    at Ue.onEnd (/Users/takeshiyanagita/.vscode/extensions/ms-playwright.playwright-1.1.1/out/oopReporter.js:7:5679)
    at /Users/takeshiyanagita/Documents/GitHub/mx_web/node_modules/@playwright/test/lib/reporters/multiplexer.js:50:76
    at wrapAsync (/Users/takeshiyanagita/Documents/GitHub/mx_web/node_modules/@playwright/test/lib/reporters/multiplexer.js:75:11)
    at Multiplexer.onEnd (/Users/takeshiyanagita/Documents/GitHub/mx_web/node_modules/@playwright/test/lib/reporters/multiplexer.js:50:51)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at InternalReporter.onEnd (/Users/takeshiyanagita/Documents/GitHub/mx_web/node_modules/@playwright/test/lib/reporters/internalReporter.js:65:5)
    at Runner.runAllTests (/Users/takeshiyanagita/Documents/GitHub/mx_web/node_modules/@playwright/test/lib/runner/runner.js:79:5)
    at runTests (/Users/takeshiyanagita/Documents/GitHub/mx_web/node_modules/@playwright/test/lib/cli.js:132:93)
    at qr.<anonymous> (/Users/takeshiyanagita/Documents/GitHub/mx_web/node_modules/@playwright/test/lib/cli.js:40:7)

Node.js v18.16.0
```

### Expected behavior

Tests should show in UI, and be able to run them via UI.

### Actual behavior

No play button showing

### Environment

```shell
System:
    OS: macOS 13.4
    Memory: 386.95 MB / 32.00 GB
  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by kosteklvp** [comment]
Please check if you have any project selected in Projects section in "TESTING: PLAYWRIGHT" view. That was the problem in my case.

**Comment by takeshi-yanagita** [comment]
I don't know what did it, but I upgraded to v1.44.0, and then reverted to 1.36.1.
This didn't do it but when I ran the following, it now works.
```
npm uninstall playwright
  npm install -D @playwright/test
  ```

**Comment by takeshi-yanagita** [comment]
I don't know what did it, but I upgraded to v1.44.0, and then reverted to 1.36.1.
This didn't do it but when I ran the following, it now works.
```
npm uninstall playwright
npm install -D @playwright/test
  ```
