### ISSUE TITLE
[Bug]: .toBeHidden ignores timeout

### ISSUE THREAD

**Issue by sergtimosh** [microsoft/playwright#30953]
### Version

1.43.1

### Steps to reproduce

The case - filtering the list with search input 
1. Open list with items
2. Type non-existing value
3. Assert no list items are visible

Test code:

```ts
await test.step('#3 - type non-existing value', async () => {
            const nonExistingSearchKey = 'non_existing';
            await attachmentsPanel.searchInput.fill(nonExistingSearchKey);
            const start = Date.now();

            await expect(attachmentsPanel.attachmentCard, 'no attachments should be visible')
                .toBeHidden({ timeout: 55000 })
                .catch((e) => console.log(e));

            console.log('timeout', Date.now() - start);
            
            await expect(attachmentsPanel.container, 'no results message is displayed').toContainText(
                attachmentsPanel.EMPTY_STATE_NO_RESULTS
            );
        });
```

Output:
```bash

ExpectError: no attachments should be visible

no attachments should be visible: Error: strict mode violation: locator('.rc-dialog-content').filter({ hasText: 'Attachments' }).getByTestId('attachments-fileCard') resolved to 4 elements:
    1) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').first()
    2) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(1)
    3) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(2)
    4) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(3)

Call log:
  - no attachments should be visible with timeout 55000ms
  - waiting for locator('.rc-dialog-content').filter({ hasText: 'Attachments' }).getByTestId('attachments-fileCard')

    {
  matcherResult: undefined,
  [Symbol(step)]: {
    stepId: 'expect@84',
    category: 'expect',
    title: 'no attachments should be visible',
    params: { expected: [Object] },
    wallTime: 1716376130266,
    infectParentStepsWithError: undefined,
    boxedStack: undefined,
    location: {
      file: '/src/_tests_/Forms/Attachments Panel/attachments_panel_search.spec.ts',
      line: 61,
      column: 18,
  ✓  1 [main] › Forms/Attachments Panel/attachments_panel_search.spec.ts:14:10 › Attachments Panel Search › Search by Text Containing in the Attachments (23.4s)
    },
    steps: [],
    complete: [Function: complete],
    endWallTime: 1716376132212,
    error: {
      message: 'Error: no attachments should be visible\n' +
        '\n' +
        "no attachments should be visible: Error: strict mode violation: locator('.rc-dialog-content').filter({ hasText: 'Attachments' }).getByTestId('attachments-fileCard') resolved to 4 elements:\n" +
        `    1) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').first()\n` +
        `    2) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(1)\n` +
        `    3) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(2)\n` +
        `    4) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(3)\n` +
        '\n' +
        'Call log:\n' +
        '  \x1B[2m- no attachments should be visible with timeout 55000ms\x1B[22m\n' +
        "\x1B[2m  - waiting for locator('.rc-dialog-content').filter({ hasText: 'Attachments' }).getByTestId('attachments-fileCard')\x1B[22m\n",
      stack: 'Error: no attachments should be visible\n' +
        '\n' +
        "no attachments should be visible: Error: strict mode violation: locator('.rc-dialog-content').filter({ hasText: 'Attachments' }).getByTestId('attachments-fileCard') resolved to 4 elements:\n" +
        `    1) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').first()\n` +
        `    2) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(1)\n` +
        `    3) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(2)\n` +
        `    4) <div data-test-id="attachments-fileCard" class="Flex-…>…</div> aka getByTestId('attachments-fileCard').nth(3)\n` +
        '\n' +
        'Call log:\n' +
        '  \x1B[2m- no attachments should be visible with timeout 55000ms\x1B[22m\n' +
        "\x1B[2m  - waiting for locator('.rc-dialog-content').filter({ hasText: 'Attachments' }).getByTestId('attachments-fileCard')\x1B[22m\n" +
        '\n' +
        '    at /src/_tests_/Forms/Attachments Panel/attachments_panel_search.spec.ts:61:18\n' +
        '    at /src/_tests_/Forms/Attachments Panel/attachments_panel_search.spec.ts:55:9'
    }
  }
}
timeout 1948

  1 passed (25.5s)

To open last HTML report run:

  npx playwright show-report

```

### Expected behavior

toBeHidden should wait given timeout

### Actual behavior

just ~2 seconds awaited.

### Additional context

This probably has something to do with strict mode violation rules

### Environment

```shell
ystem:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 70.67 MB / 16.00 GB
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    bun: 0.1.1 - ~/.bun/bin/bun
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by sergtimosh** [comment]
The temporary workaround is to set element index .nth(0) to avoid strictModeViolation check
```ts
await expect(attachmentsPanel.attachmentCard.nth(0), 'no attachments should be visible').toBeHidden();
```

**Comment by pavelfeldman** [comment]
Please use BUG template to file something we can reproduce locally!

**Comment by sergtimosh** [comment]
> Please use BUG template to file something we can reproduce locally!

It's pretty straighforward. Here is repro script

```
import { test, expect } from '@playwright/test';

test.describe('Bugs repro', () => {
    test('"toBeHidden" does not wait', async ({ page }) => {
        await page.goto('https://playwright.dev/');
        await page.getByLabel('Search').click();
        await page.locator('#docsearch-input').fill(`test`);
        await page.waitForTimeout(2000); // wait for the search results to appear

        const timeout = 10000;
        const start = Date.now();
        await expect(page.locator('[role="option"]'))
        .toBeHidden({ timeout: timeout })
        .catch(e => console.log(e));
        
        //now test "toBeHidden" actual timeout
        expect(Date.now() - start).toBeGreaterThanOrEqual(timeout);
    });
});
```

**Comment by jwalkerinterpres** [comment]
Why was this closed?  It's still an issue.

**Comment by jwalkerinterpres** [comment]
In a related ticket I opened [pavelfeldman](https://github.com/pavelfeldman) provided this explanation for why the ticket is closed:

> I can see strict mode violation exceptions. Locators must be strict. You can add .first() if you want to opt out of strictless. https://playwright.dev/docs/locators#strictness
