### ISSUE TITLE
[Bug]: Playwright Extension versions 1.1.1 to 1.1.6 cannot see tests in test files

### ISSUE THREAD

**Issue by qwertie** [microsoft/playwright#31013]
### Version

1.1.6

### Steps to reproduce

I thought you should know that the Playwright Test extension for VSCode has been broken for the last week, although I don't have time to develop a "minimal reproduction" from our proprietary codebase so we're just going to use v1.0.22. Symptoms:

1. It sees the test files but cannot detect any test cases
2. It is able to run a test suite via the "Run test" button, but it cannot detect when the tests have completed.
3. The "Cancel Test Run" button doesn't work
4. There is a timer that counts up forever; see screenshot

![image](https://github.com/microsoft/playwright/assets/720717/aa67acaf-c8a6-4174-ac33-c08484851c40)

### Expected behavior

It can display a list of test cases, detect completion and stop test runs

### Actual behavior

The list of test cases is missing and it cannot detect completion or stop test runs

### Environment

```shell
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
  Memory: 8.42 GB / 31.93 GB
Binaries:
  Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
IDEs:
  VSCode: 1.89.1 - C:\Users\Family\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
Languages:
  Bash: 4.4.20 - C:\Windows\system32\bash.EXE
npmPackages:
  @playwright/test: 1.33.0 => 1.33.0
```

**Comment by mxschmitt** [comment]
Have you tried updating Playwright to the latest version? This should fix it.

**Comment by gersona** [comment]
I also had the same issue with the same extension version `1.1.6` (latest so far) and playwright Version 1.32.3 but it was solved after I upgraded to playwright 1.41

I would get the following error messages though, if it helps to identify the initial cause
```
Error in reporter TypeError: The "from" argument must be of type string. Received undefined
    at new NodeError (/Users/username/path_to_project/frontend/lib/internal/errors.js:399:5)
    at validateString (/Users/username/path_to_project/frontend/lib/internal/validators.js:163:11)
    at Object.relative (/Users/username/path_to_project/frontend/lib/path.js:1191:5)
    at Ue._relativePath (/Users/username/.vscode/extensions/ms-playwright.playwright-1.1.6/out/oopReporter.js:7:4232)
    at Ue._relativeLocation (/Users/username/.vscode/extensions/ms-playwright.playwright-1.1.6/out/oopReporter.js:7:4171)
    at Ue._serializeStepStart (/Users/username/.vscode/extensions/ms-playwright.playwright-1.1.6/out/oopReporter.js:7:4022)
    at Ue.onStepBegin (/Users/username/.vscode/extensions/ms-playwright.playwright-1.1.6/out/oopReporter.js:7:1725)
    at /Users/username/path_to_project/frontend/node_modules/@playwright/test/lib/reporters/multiplexer.js:124:122
    at wrap (/Users/username/path_to_project/frontend/node_modules/@playwright/test/lib/reporters/multiplexer.js:137:5)
    at Multiplexer.onStepBegin (/Users/username/path_to_project/frontend/node_modules/@playwright/test/lib/reporters/multiplexer.js:122:45)
    at WorkerHost.onStepBegin (/Users/username/path_to_project/frontend/node_modules/@playwright/test/lib/runner/dispatcher.js:269:159)
    at WorkerHost.emit (/Users/username/path_to_project/frontend/lib/events.js:513:28)
    at ChildProcess.<anonymous> (/Users/username/path_to_project/frontend/node_modules/@playwright/test/lib/runner/processHost.js:93:16)
    at ChildProcess.emit (/Users/username/path_to_project/frontend/lib/events.js:513:28)
    at emit (/Users/username/path_to_project/frontend/lib/internal/child_process.js:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {code: 'ERR_INVALID_ARG_TYPE', stack: 'TypeError: The "from" argument must be of typ…ons (node:internal/process/task_queues:83:21)', message: 'The "from" argument must be of type string. Received undefined', toString: ƒ, Symbol(kIsNodeError): true}
```

**Comment by mxschmitt** [comment]
@pschroeder89 this is expected, see here: https://github.com/microsoft/playwright/issues/30882#:~:text=Q%3A%20My%20working%20directory%20is%20now%20workspace%20folder.%20Why%3F

We recommend using `__dirname`. We adjusted the docs in https://github.com/microsoft/playwright/pull/31149, so the `.env` files will consider `__dirname` as well.

**Comment by mxschmitt** [comment]
We recommend using latest Playwright version.
