### ISSUE TITLE
[Bug]: page.screenshot failed

### ISSUE THREAD

**Issue by zhq745w** [microsoft/playwright#31034]
### Version

1.42.1

### Steps to reproduce

Sometimes when the tests are running they crash with an error at the point of taking screenshots

```
2024-05-27T14:52:46.405Z pw:api taking page screenshot
2024-05-27T14:52:46.405Z pw:protocol SEND ► {"id":89,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"-874399810264861986.4.2","arguments":[{"objectId":"-874399810264861986.4.2"},{"value":false},{"value":true},{},{"value":"(function inPagePrepareForScreenshots(screenshotStyle, hideCaret, disableAnimations, syncAnimations) {\n  // In WebKit, sync the animations.\n  if (syncAnimations) {\n    const style = document.createElement('style');\n    style.textContent = 'body {}';\n    document.head.appendChild(style);\n    document.documentElement.getBoundingClientRect();\n    style.remove();\n  }\n  if (!screenshotStyle && !hideCaret && !disableAnimations) return;\n  const collectRoots = (root, roots = []) => {\n    roots.push(root);\n    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);\n    do {\n      const node = walker.currentNode;\n      const shadowRoot = node instanceof Element ? node.shadowRoot : null;\n      if (shadowRoot) collectRoots(shadowRoot, roots);\n    } while (walker.nextNode());\n    return roots;\n  };\n  const roots = collectRoots(document);\n  const cleanupCallbacks = [];\n  if (screenshotStyle) {\n    for (const root of roots) {\n      const styleTag = document.createElement('style');\n      styleTag.textContent = screenshotStyle;\n      if (root === document) document.documentElement.append(styleTag);else root.append(styleTag);\n      cleanupCallbacks.push(() => {\n        styleTag.remove();\n      });\n    }\n  }\n  if (hideCaret) {\n    const elements = new Map();\n    for (const root of roots) {\n      root.querySelectorAll('input,textarea,[contenteditable]').forEach(element => {\n        elements.set(element, {\n          value: element.style.getPropertyValue('caret-color'),\n          priority: element.style.getPropertyPriority('caret-color')\n        });\n        element.style.setProperty('caret-color', 'transparent', 'important');\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const [element, value] of elements) element.style.setProperty('caret-color', value.value, value.priority);\n    });\n  }\n  if (disableAnimations) {\n    const infiniteAnimationsToResume = new Set();\n    const handleAnimations = root => {\n      for (const animation of root.getAnimations()) {\n        if (!animation.effect || animation.playbackRate === 0 || infiniteAnimationsToResume.has(animation)) continue;\n        const endTime = animation.effect.getComputedTiming().endTime;\n        if (Number.isFinite(endTime)) {\n          try {\n            animation.finish();\n          } catch (e) {\n            // animation.finish() should not throw for\n            // finite animations, but we'd like to be on the\n            // safe side.\n          }\n        } else {\n          try {\n            animation.cancel();\n            infiniteAnimationsToResume.add(animation);\n          } catch (e) {\n            // animation.cancel() should not throw for\n            // infinite animations, but we'd like to be on the\n            // safe side.\n          }\n        }\n      }\n    };\n    for (const root of roots) {\n      const handleRootAnimations = handleAnimations.bind(null, root);\n      handleRootAnimations();\n      root.addEventListener('transitionrun', handleRootAnimations);\n      root.addEventListener('animationstart', handleRootAnimations);\n      cleanupCallbacks.push(() => {\n        root.removeEventListener('transitionrun', handleRootAnimations);\n        root.removeEventListener('animationstart', handleRootAnimations);\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const animation of infiniteAnimationsToResume) {\n        try {\n          animation.play();\n        } catch (e) {\n          // animation.play() should never throw, but\n          // we'd like to be on the safe side.\n        }\n      }\n    });\n  }\n  window.__pwCleanupScreenshot = () => {\n    for (const cleanupCallback of cleanupCallbacks) cleanupCallback();\n    delete window.__pwCleanupScreenshot;\n  };\n})(undefined, true, false, false)"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.405Z pw:protocol SEND ► {"id":90,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"3790603894794579575.2.1","arguments":[{"objectId":"3790603894794579575.2.1"},{"value":false},{"value":true},{},{"value":"(function inPagePrepareForScreenshots(screenshotStyle, hideCaret, disableAnimations, syncAnimations) {\n  // In WebKit, sync the animations.\n  if (syncAnimations) {\n    const style = document.createElement('style');\n    style.textContent = 'body {}';\n    document.head.appendChild(style);\n    document.documentElement.getBoundingClientRect();\n    style.remove();\n  }\n  if (!screenshotStyle && !hideCaret && !disableAnimations) return;\n  const collectRoots = (root, roots = []) => {\n    roots.push(root);\n    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);\n    do {\n      const node = walker.currentNode;\n      const shadowRoot = node instanceof Element ? node.shadowRoot : null;\n      if (shadowRoot) collectRoots(shadowRoot, roots);\n    } while (walker.nextNode());\n    return roots;\n  };\n  const roots = collectRoots(document);\n  const cleanupCallbacks = [];\n  if (screenshotStyle) {\n    for (const root of roots) {\n      const styleTag = document.createElement('style');\n      styleTag.textContent = screenshotStyle;\n      if (root === document) document.documentElement.append(styleTag);else root.append(styleTag);\n      cleanupCallbacks.push(() => {\n        styleTag.remove();\n      });\n    }\n  }\n  if (hideCaret) {\n    const elements = new Map();\n    for (const root of roots) {\n      root.querySelectorAll('input,textarea,[contenteditable]').forEach(element => {\n        elements.set(element, {\n          value: element.style.getPropertyValue('caret-color'),\n          priority: element.style.getPropertyPriority('caret-color')\n        });\n        element.style.setProperty('caret-color', 'transparent', 'important');\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const [element, value] of elements) element.style.setProperty('caret-color', value.value, value.priority);\n    });\n  }\n  if (disableAnimations) {\n    const infiniteAnimationsToResume = new Set();\n    const handleAnimations = root => {\n      for (const animation of root.getAnimations()) {\n        if (!animation.effect || animation.playbackRate === 0 || infiniteAnimationsToResume.has(animation)) continue;\n        const endTime = animation.effect.getComputedTiming().endTime;\n        if (Number.isFinite(endTime)) {\n          try {\n            animation.finish();\n          } catch (e) {\n            // animation.finish() should not throw for\n            // finite animations, but we'd like to be on the\n            // safe side.\n          }\n        } else {\n          try {\n            animation.cancel();\n            infiniteAnimationsToResume.add(animation);\n          } catch (e) {\n            // animation.cancel() should not throw for\n            // infinite animations, but we'd like to be on the\n            // safe side.\n          }\n        }\n      }\n    };\n    for (const root of roots) {\n      const handleRootAnimations = handleAnimations.bind(null, root);\n      handleRootAnimations();\n      root.addEventListener('transitionrun', handleRootAnimations);\n      root.addEventListener('animationstart', handleRootAnimations);\n      cleanupCallbacks.push(() => {\n        root.removeEventListener('transitionrun', handleRootAnimations);\n        root.removeEventListener('animationstart', handleRootAnimations);\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const animation of infiniteAnimationsToResume) {\n        try {\n          animation.play();\n        } catch (e) {\n          // animation.play() should never throw, but\n          // we'd like to be on the safe side.\n        }\n      }\n    });\n  }\n  window.__pwCleanupScreenshot = () => {\n    for (const cleanupCallback of cleanupCallbacks) cleanupCallback();\n    delete window.__pwCleanupScreenshot;\n  };\n})(undefined, true, false, false)"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.405Z pw:protocol SEND ► {"id":91,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"3790603894794579575.4.1","arguments":[{"objectId":"3790603894794579575.4.1"},{"value":false},{"value":true},{},{"value":"(function inPagePrepareForScreenshots(screenshotStyle, hideCaret, disableAnimations, syncAnimations) {\n  // In WebKit, sync the animations.\n  if (syncAnimations) {\n    const style = document.createElement('style');\n    style.textContent = 'body {}';\n    document.head.appendChild(style);\n    document.documentElement.getBoundingClientRect();\n    style.remove();\n  }\n  if (!screenshotStyle && !hideCaret && !disableAnimations) return;\n  const collectRoots = (root, roots = []) => {\n    roots.push(root);\n    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);\n    do {\n      const node = walker.currentNode;\n      const shadowRoot = node instanceof Element ? node.shadowRoot : null;\n      if (shadowRoot) collectRoots(shadowRoot, roots);\n    } while (walker.nextNode());\n    return roots;\n  };\n  const roots = collectRoots(document);\n  const cleanupCallbacks = [];\n  if (screenshotStyle) {\n    for (const root of roots) {\n      const styleTag = document.createElement('style');\n      styleTag.textContent = screenshotStyle;\n      if (root === document) document.documentElement.append(styleTag);else root.append(styleTag);\n      cleanupCallbacks.push(() => {\n        styleTag.remove();\n      });\n    }\n  }\n  if (hideCaret) {\n    const elements = new Map();\n    for (const root of roots) {\n      root.querySelectorAll('input,textarea,[contenteditable]').forEach(element => {\n        elements.set(element, {\n          value: element.style.getPropertyValue('caret-color'),\n          priority: element.style.getPropertyPriority('caret-color')\n        });\n        element.style.setProperty('caret-color', 'transparent', 'important');\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const [element, value] of elements) element.style.setProperty('caret-color', value.value, value.priority);\n    });\n  }\n  if (disableAnimations) {\n    const infiniteAnimationsToResume = new Set();\n    const handleAnimations = root => {\n      for (const animation of root.getAnimations()) {\n        if (!animation.effect || animation.playbackRate === 0 || infiniteAnimationsToResume.has(animation)) continue;\n        const endTime = animation.effect.getComputedTiming().endTime;\n        if (Number.isFinite(endTime)) {\n          try {\n            animation.finish();\n          } catch (e) {\n            // animation.finish() should not throw for\n            // finite animations, but we'd like to be on the\n            // safe side.\n          }\n        } else {\n          try {\n            animation.cancel();\n            infiniteAnimationsToResume.add(animation);\n          } catch (e) {\n            // animation.cancel() should not throw for\n            // infinite animations, but we'd like to be on the\n            // safe side.\n          }\n        }\n      }\n    };\n    for (const root of roots) {\n      const handleRootAnimations = handleAnimations.bind(null, root);\n      handleRootAnimations();\n      root.addEventListener('transitionrun', handleRootAnimations);\n      root.addEventListener('animationstart', handleRootAnimations);\n      cleanupCallbacks.push(() => {\n        root.removeEventListener('transitionrun', handleRootAnimations);\n        root.removeEventListener('animationstart', handleRootAnimations);\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const animation of infiniteAnimationsToResume) {\n        try {\n          animation.play();\n        } catch (e) {\n          // animation.play() should never throw, but\n          // we'd like to be on the safe side.\n        }\n      }\n    });\n  }\n  window.__pwCleanupScreenshot = () => {\n    for (const cleanupCallback of cleanupCallbacks) cleanupCallback();\n    delete window.__pwCleanupScreenshot;\n  };\n})(undefined, true, false, false)"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.405Z pw:protocol SEND ► {"id":92,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"-874399810264861986.6.1","arguments":[{"objectId":"-874399810264861986.6.1"},{"value":false},{"value":true},{},{"value":"(function inPagePrepareForScreenshots(screenshotStyle, hideCaret, disableAnimations, syncAnimations) {\n  // In WebKit, sync the animations.\n  if (syncAnimations) {\n    const style = document.createElement('style');\n    style.textContent = 'body {}';\n    document.head.appendChild(style);\n    document.documentElement.getBoundingClientRect();\n    style.remove();\n  }\n  if (!screenshotStyle && !hideCaret && !disableAnimations) return;\n  const collectRoots = (root, roots = []) => {\n    roots.push(root);\n    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);\n    do {\n      const node = walker.currentNode;\n      const shadowRoot = node instanceof Element ? node.shadowRoot : null;\n      if (shadowRoot) collectRoots(shadowRoot, roots);\n    } while (walker.nextNode());\n    return roots;\n  };\n  const roots = collectRoots(document);\n  const cleanupCallbacks = [];\n  if (screenshotStyle) {\n    for (const root of roots) {\n      const styleTag = document.createElement('style');\n      styleTag.textContent = screenshotStyle;\n      if (root === document) document.documentElement.append(styleTag);else root.append(styleTag);\n      cleanupCallbacks.push(() => {\n        styleTag.remove();\n      });\n    }\n  }\n  if (hideCaret) {\n    const elements = new Map();\n    for (const root of roots) {\n      root.querySelectorAll('input,textarea,[contenteditable]').forEach(element => {\n        elements.set(element, {\n          value: element.style.getPropertyValue('caret-color'),\n          priority: element.style.getPropertyPriority('caret-color')\n        });\n        element.style.setProperty('caret-color', 'transparent', 'important');\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const [element, value] of elements) element.style.setProperty('caret-color', value.value, value.priority);\n    });\n  }\n  if (disableAnimations) {\n    const infiniteAnimationsToResume = new Set();\n    const handleAnimations = root => {\n      for (const animation of root.getAnimations()) {\n        if (!animation.effect || animation.playbackRate === 0 || infiniteAnimationsToResume.has(animation)) continue;\n        const endTime = animation.effect.getComputedTiming().endTime;\n        if (Number.isFinite(endTime)) {\n          try {\n            animation.finish();\n          } catch (e) {\n            // animation.finish() should not throw for\n            // finite animations, but we'd like to be on the\n            // safe side.\n          }\n        } else {\n          try {\n            animation.cancel();\n            infiniteAnimationsToResume.add(animation);\n          } catch (e) {\n            // animation.cancel() should not throw for\n            // infinite animations, but we'd like to be on the\n            // safe side.\n          }\n        }\n      }\n    };\n    for (const root of roots) {\n      const handleRootAnimations = handleAnimations.bind(null, root);\n      handleRootAnimations();\n      root.addEventListener('transitionrun', handleRootAnimations);\n      root.addEventListener('animationstart', handleRootAnimations);\n      cleanupCallbacks.push(() => {\n        root.removeEventListener('transitionrun', handleRootAnimations);\n        root.removeEventListener('animationstart', handleRootAnimations);\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const animation of infiniteAnimationsToResume) {\n        try {\n          animation.play();\n        } catch (e) {\n          // animation.play() should never throw, but\n          // we'd like to be on the safe side.\n        }\n      }\n    });\n  }\n  window.__pwCleanupScreenshot = () => {\n    for (const cleanupCallback of cleanupCallbacks) cleanupCallback();\n    delete window.__pwCleanupScreenshot;\n  };\n})(undefined, true, false, false)"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.405Z pw:protocol SEND ► {"id":93,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"3790603894794579575.6.1","arguments":[{"objectId":"3790603894794579575.6.1"},{"value":false},{"value":true},{},{"value":"(function inPagePrepareForScreenshots(screenshotStyle, hideCaret, disableAnimations, syncAnimations) {\n  // In WebKit, sync the animations.\n  if (syncAnimations) {\n    const style = document.createElement('style');\n    style.textContent = 'body {}';\n    document.head.appendChild(style);\n    document.documentElement.getBoundingClientRect();\n    style.remove();\n  }\n  if (!screenshotStyle && !hideCaret && !disableAnimations) return;\n  const collectRoots = (root, roots = []) => {\n    roots.push(root);\n    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);\n    do {\n      const node = walker.currentNode;\n      const shadowRoot = node instanceof Element ? node.shadowRoot : null;\n      if (shadowRoot) collectRoots(shadowRoot, roots);\n    } while (walker.nextNode());\n    return roots;\n  };\n  const roots = collectRoots(document);\n  const cleanupCallbacks = [];\n  if (screenshotStyle) {\n    for (const root of roots) {\n      const styleTag = document.createElement('style');\n      styleTag.textContent = screenshotStyle;\n      if (root === document) document.documentElement.append(styleTag);else root.append(styleTag);\n      cleanupCallbacks.push(() => {\n        styleTag.remove();\n      });\n    }\n  }\n  if (hideCaret) {\n    const elements = new Map();\n    for (const root of roots) {\n      root.querySelectorAll('input,textarea,[contenteditable]').forEach(element => {\n        elements.set(element, {\n          value: element.style.getPropertyValue('caret-color'),\n          priority: element.style.getPropertyPriority('caret-color')\n        });\n        element.style.setProperty('caret-color', 'transparent', 'important');\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const [element, value] of elements) element.style.setProperty('caret-color', value.value, value.priority);\n    });\n  }\n  if (disableAnimations) {\n    const infiniteAnimationsToResume = new Set();\n    const handleAnimations = root => {\n      for (const animation of root.getAnimations()) {\n        if (!animation.effect || animation.playbackRate === 0 || infiniteAnimationsToResume.has(animation)) continue;\n        const endTime = animation.effect.getComputedTiming().endTime;\n        if (Number.isFinite(endTime)) {\n          try {\n            animation.finish();\n          } catch (e) {\n            // animation.finish() should not throw for\n            // finite animations, but we'd like to be on the\n            // safe side.\n          }\n        } else {\n          try {\n            animation.cancel();\n            infiniteAnimationsToResume.add(animation);\n          } catch (e) {\n            // animation.cancel() should not throw for\n            // infinite animations, but we'd like to be on the\n            // safe side.\n          }\n        }\n      }\n    };\n    for (const root of roots) {\n      const handleRootAnimations = handleAnimations.bind(null, root);\n      handleRootAnimations();\n      root.addEventListener('transitionrun', handleRootAnimations);\n      root.addEventListener('animationstart', handleRootAnimations);\n      cleanupCallbacks.push(() => {\n        root.removeEventListener('transitionrun', handleRootAnimations);\n        root.removeEventListener('animationstart', handleRootAnimations);\n      });\n    }\n    cleanupCallbacks.push(() => {\n      for (const animation of infiniteAnimationsToResume) {\n        try {\n          animation.play();\n        } catch (e) {\n          // animation.play() should never throw, but\n          // we'd like to be on the safe side.\n        }\n      }\n    });\n  }\n  window.__pwCleanupScreenshot = () => {\n    for (const cleanupCallback of cleanupCallbacks) cleanupCallback();\n    delete window.__pwCleanupScreenshot;\n  };\n})(undefined, true, false, false)"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"95D1214B226CBE788FC116F84F36AAB5"}
2024-05-27T14:52:46.405Z pw:protocol ◀ RECV {"id":88,"result":{},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.405Z pw:protocol ◀ RECV {"id":90,"result":{"result":{"type":"undefined"}},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.405Z pw:protocol ◀ RECV {"id":91,"result":{"result":{"type":"undefined"}},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.406Z pw:protocol ◀ RECV {"id":93,"result":{"result":{"type":"undefined"}},"sessionId":"95D1214B226CBE788FC116F84F36AAB5"}
2024-05-27T14:52:46.407Z pw:protocol ◀ RECV {"id":89,"result":{"result":{"type":"undefined"}},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.407Z pw:protocol ◀ RECV {"id":92,"result":{"result":{"type":"undefined"}},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.407Z pw:api waiting for fonts to load...
2024-05-27T14:52:46.407Z pw:protocol SEND ► {"id":94,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"-874399810264861986.4.2","arguments":[{"objectId":"-874399810264861986.4.2"},{"value":false},{"value":true},{},{"value":"document.fonts.ready"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.407Z pw:protocol SEND ► {"id":95,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"3790603894794579575.2.1","arguments":[{"objectId":"3790603894794579575.2.1"},{"value":false},{"value":true},{},{"value":"document.fonts.ready"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.407Z pw:protocol SEND ► {"id":96,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"3790603894794579575.4.1","arguments":[{"objectId":"3790603894794579575.4.1"},{"value":false},{"value":true},{},{"value":"document.fonts.ready"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.407Z pw:protocol SEND ► {"id":97,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"-874399810264861986.6.1","arguments":[{"objectId":"-874399810264861986.6.1"},{"value":false},{"value":true},{},{"value":"document.fonts.ready"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.407Z pw:protocol SEND ► {"id":98,"method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(utilityScript, ...args) => utilityScript.evaluate(...args)","objectId":"3790603894794579575.6.1","arguments":[{"objectId":"3790603894794579575.6.1"},{"value":false},{"value":true},{},{"value":"document.fonts.ready"},{"value":1},{"value":{"v":"undefined"}}],"returnByValue":true,"awaitPromise":true,"userGesture":true},"sessionId":"95D1214B226CBE788FC116F84F36AAB5"}
2024-05-27T14:52:46.408Z pw:protocol ◀ RECV {"id":95,"result":{"result":{"type":"object","value":{"o":[],"id":1}}},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.408Z pw:protocol ◀ RECV {"id":96,"result":{"result":{"type":"object","value":{"o":[],"id":1}}},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.408Z pw:protocol ◀ RECV {"id":94,"result":{"result":{"type":"object","value":{"o":[],"id":1}}},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.408Z pw:protocol ◀ RECV {"id":97,"result":{"result":{"type":"object","value":{"o":[],"id":1}}},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.671Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"9B695867C1694416D6E52985C80D7FDD","loaderId":"B5AE9FC67C8379F0EF06157CF446962C","name":"networkAlmostIdle","timestamp":28921.166496},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.671Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"9B695867C1694416D6E52985C80D7FDD","loaderId":"B5AE9FC67C8379F0EF06157CF446962C","name":"networkIdle","timestamp":28921.166496},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.795Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"FEBF3FB5F8EAEBC6B9C2B963C5FA95C8","loaderId":"C48061292184E5FA09ED980650FE34AE","name":"networkAlmostIdle","timestamp":28921.253099},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.795Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"FEBF3FB5F8EAEBC6B9C2B963C5FA95C8","loaderId":"C48061292184E5FA09ED980650FE34AE","name":"firstMeaningfulPaint","timestamp":28921.17644},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.796Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"FEBF3FB5F8EAEBC6B9C2B963C5FA95C8","loaderId":"C48061292184E5FA09ED980650FE34AE","name":"networkIdle","timestamp":28921.37924},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.796Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"3E3D8D9BB766A4B70A8D9E3836091863","loaderId":"2FC67F817F8E66F78F1DDD6F9E8C41C1","name":"networkAlmostIdle","timestamp":28921.36886},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.796Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"3E3D8D9BB766A4B70A8D9E3836091863","loaderId":"2FC67F817F8E66F78F1DDD6F9E8C41C1","name":"networkIdle","timestamp":28921.36886},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:46.799Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"691361044EC1C3872FC5A8CE7EC9BF5A","loaderId":"B2248F258E6138D2C0F70B4CFCFC7F51","name":"networkIdle","timestamp":28921.550066},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:52:46.896Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"2EB66B68353C2100939D69EF0FCA24ED","loaderId":"3038090848AD3A55F0A5275DA0EF3E0C","name":"networkAlmostIdle","timestamp":28921.651386},"sessionId":"95D1214B226CBE788FC116F84F36AAB5"}
2024-05-27T14:52:46.896Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"2EB66B68353C2100939D69EF0FCA24ED","loaderId":"3038090848AD3A55F0A5275DA0EF3E0C","name":"networkIdle","timestamp":28921.668453},"sessionId":"95D1214B226CBE788FC116F84F36AAB5"}
2024-05-27T14:52:46.903Z pw:api   "networkidle" event fired
2024-05-27T14:52:50.977Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"FEBF3FB5F8EAEBC6B9C2B963C5FA95C8","loaderId":"C48061292184E5FA09ED980650FE34AE","name":"InteractiveTime","timestamp":28926.253551},"sessionId":"D8F0C41FF73B7369C3B665BC0C2DCE2C"}
2024-05-27T14:52:51.173Z pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"691361044EC1C3872FC5A8CE7EC9BF5A","loaderId":"B2248F258E6138D2C0F70B4CFCFC7F51","name":"InteractiveTime","timestamp":28926.449326},"sessionId":"002B90276323A829D38EF312233A2555"}
2024-05-27T14:53:16.404Z pw:channel <RECV {"id":16,"error":{"error":{"message":"Timeout 30000ms exceeded.","stack":"TimeoutError: Timeout 30000ms exceeded.\n    at ProgressController.run (/ssd/projects/e2e_sports/node_modules/playwright-core/lib/server/progress.js:78:26)\n    at Page.screenshot (/ssd/projects/e2e_sports/node_modules/playwright-core/lib/server/page.js:475:23)\n    at PageDispatcher.screenshot (/ssd/projects/e2e_sports/node_modules/playwright-core/lib/server/dispatchers/pageDispatcher.js:201:32)\n    at PageDispatcher._handleCommand (/ssd/projects/e2e_sports/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:94:40)\n    at DispatcherConnection.dispatch (/ssd/projects/e2e_sports/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:365:39)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at process.processImmediate (node:internal/timers:449:9)","name":"TimeoutError"}},"log":["taking page screenshot","waiting for fonts to load..."]}
2024-05-27T14:53:16.405Z pw:api <= page.screenshot failed
```

The logs show that there is a SEND {"id":98 ... }, but there is no RECV when loading fonts

There are no problems with the network. I don't understand how to get more information about the problem to figure out how to fix it. Any ideas?

### Expected behavior

page.screenshot success

### Actual behavior

-

### Environment

```shell
OS Kubuntu 24.04
node v20.13.1
```

**Comment by mxschmitt** [comment]
We unfortunately need clear reproduction steps in order to triage issues like this. Even if it only happens 1/100 it is already helpful. Without a reproduction test we can't act on it. Thanks for your understanding.

**Comment by zhq745w** [comment]
There is no possibility to reproduce for you, as it is reproduced in our closed sector =(
Are there any ways to get more logs about the problematic request?

**Comment by mxschmitt** [comment]
Unfortunately not. I'll close it in the meantime then. Feel free to re-file if you have something you can share with us.
