### ISSUE TITLE
Playwright debian not working[BUG]

### ISSUE THREAD

**Issue by spidyhackx** [microsoft/playwright#3106]
hey guys,when i run the screenshot snippet code,it returns no images.what's wrong
- Playwright Version: 1.2.1
- Operating System: Linux
- Node version: 10.21.0
- Browser: All

**Code Snippet**

```const playwright = require('playwright');

    (async () => {
        for (const browserType of ['chromium', 'firefox', 'webkit']) {
          const browser = await playwright[browserType].launch();
          const context = await browser.newContext();
          const page = await context.newPage();
          await page.goto('http://whatsmyuseragent.org/');
          await page.screenshot({ path: `example-${browserType}.png` });
          await browser.close();
        }
      })();
```

**Response log**

```(node:25622) UnhandledPromiseRejectionWarning: Protocol error (Target.setAutoAttach): Target closed.
================= browserType.launch logs =================
[browser] <launching> /home/spidy/.cache/ms-playwright/chromium-782078/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-hbehtE --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --no-startup-window
[browser] <launched> pid=25633
[browser] [0723/093359.917007:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
[browser] #0 0x564934fb2239 base::debug::CollectStackTrace()
[browser] #1 0x564934f2e0f3 base::debug::StackTrace::StackTrace()
[browser] #2 0x564934f3ed70 logging::LogMessage::~LogMessage()
[browser] #3 0x5649367b56fe service_manager::ZygoteHostImpl::Init()
[browser] #4 0x564934aee447 content::ContentMainRunnerImpl::Initialize()
[browser] #5 0x564934b4fbaa service_manager::Main()
[browser] #6 0x564934aeca61 content::ContentMain()
[browser] #7 0x564934b4e8cd headless::(anonymous namespace)::RunContentMain()
[browser] #8 0x564934b4e5cc headless::HeadlessShellMain()
[browser] #9 0x564932422427 ChromeMain
[browser] #10 0x7f76b6cbbe0b __libc_start_main
[browser] #11 0x56493242226a _start
[browser] 
[browser] Received signal 6
[browser] #0 0x564934fb2239 base::debug::CollectStackTrace()
[browser] #1 0x564934f2e0f3 base::debug::StackTrace::StackTrace()
[browser] #2 0x564934fb1dd5 base::debug::(anonymous namespace)::StackDumpSignalHandler()
[browser] #3 0x7f76b8c24110 (/usr/lib/x86_64-linux-gnu/libpthread-2.30.so+0x1410f)
[browser] #4 0x7f76b6cd0781 gsignal
[browser] #5 0x7f76b6cba55b abort
[browser] #6 0x564934fb0d35 base::debug::BreakDebugger()
[browser] #7 0x564934f3f210 logging::LogMessage::~LogMessage()
[browser] #8 0x5649367b56fe service_manager::ZygoteHostImpl::Init()
[browser] #9 0x564934aee447 content::ContentMainRunnerImpl::Initialize()
[browser] #10 0x564934b4fbaa service_manager::Main()
[browser] #11 0x564934aeca61 content::ContentMain()
[browser] #12 0x564934b4e8cd headless::(anonymous namespace)::RunContentMain()
[browser] #13 0x564934b4e5cc headless::HeadlessShellMain()
[browser] #14 0x564932422427 ChromeMain
[browser] #15 0x7f76b6cbbe0b __libc_start_main
[browser] #16 0x56493242226a _start
[browser]   r8: 0000000000000000  r9: 00007ffed04d2030 r10: 0000000000000008 r11: 0000000000000246
[browser]  r12: 00007ffed04d3300 r13: 00007ffed04d2290 r14: 00007ffed04d3310 r15: aaaaaaaaaaaaaaaa
[browser]   di: 0000000000000002  si: 00007ffed04d2030  bp: 00007ffed04d2280  bx: 00007f76b5754d80
[browser]   dx: 0000000000000000  ax: 0000000000000000  cx: 00007f76b6cd0781  sp: 00007ffed04d2030
[browser]   ip: 00007f76b6cd0781 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
[browser]  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[browser] [end of stack trace]
[browser] Calling _exit(1). Core file will not be generated.
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.Error
    at Promise (/home/spidy/Desktop/SpidySys./automate/node_modules/playwright/lib/chromium/crConnection.js:131:63)
    at new Promise (<anonymous>)
    at CRSession.send (/home/spidy/Desktop/SpidySys./automate/node_modules/playwright/lib/chromium/crConnection.js:130:16)
    at CRSession.send (/home/spidy/Desktop/SpidySys./automate/node_modules/playwright/lib/helper.js:79:31)
    at Function.connect (/home/spidy/Desktop/SpidySys./automate/node_modules/playwright/lib/chromium/crBrowser.js:54:27)
    at Chromium._connectToTransport (/home/spidy/Desktop/SpidySys./automate/node_modules/playwright/lib/server/chromium.js:51:38)
    at Chromium._innerLaunch (/home/spidy/Desktop/SpidySys./automate/node_modules/playwright/lib/server/browserType.js:84:36)
(node:25622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by yury-s** [comment]
Are you running the snippet in Docker or as a root user? Chromium fails to start because of a sandbox issue, see [this section](https://github.com/microsoft/playwright/blob/c0d9ccfebf023d04a033cddcacc4a5fd47d520e0/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) for troubleshooting instructions.

We recently made some changes in that area which should be helpful, can you try your snippet with Playwright `@next` instead of `1.2.1` and see if it resolves the problem?

**Comment by spidyhackx** [comment]
Thanks bud,enabling user namespace cloning via `sudo sysctl -w kernel.unprivileged_userns_clone=1` fixed the issue.
