### ISSUE TITLE
[internal] Error in reporter RangeError: Invalid time value

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#31203]
After 826343b8a032eddb5e4a492625b0c35ec50ef775 a lot of checks fail with:

```
Error in reporter RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at JSONReporter._serializeTestResult (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:190:35)
    at /Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:173:43
    at Array.map (<anonymous>)
    at JSONReporter._serializeTest (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:173:29)
    at JSONReporter._serializeTestSpec (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:161:20)
    at /Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:151:43
    at Array.map (<anonymous>)
    at JSONReporter._serializeSuite (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:151:26)
    at /Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:147:51
    at Array.map (<anonymous>)
    at JSONReporter._serializeSuite (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:147:33)
    at JSONReporter._mergeSuites (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:97:33)
    at JSONReporter._serializeReport (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:76:20)
    at JSONReporter.onEnd (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/json.js:54:29)
    at /Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/multiplexer.js:51:56
    at wrapAsync (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/multiplexer.js:79:18)
    at Multiplexer.onEnd (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/multiplexer.js:51:31)
    at InternalReporter.onEnd (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/reporters/internalReporter.js:69:12)
    at Runner.runAllTests (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/runner/runner.js:78:28)
    at runTests (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/program.js:207:[85](https://github.com/microsoft/playwright-browsers/actions/runs/9408895160/job/25917771302#step:10:86))
    at t.<anonymous> (/Users/runner/work/playwright-browsers/playwright-browsers/packages/playwright/lib/program.js:54:7)
```

**Comment by mxschmitt** [comment]
Issue seems to be this test:

https://github.com/microsoft/playwright/blob/dd3a41287e8edaf537481e72316a3dead548b645/tests/library/clock.spec.ts#L1736-L1740

That we install, keep the "broken Date.now()" reference and restore it on install.
