### ISSUE TITLE
[Bug]: Firefox is unable to launch if the $HOME folder isn't owned by the current user.

### ISSUE THREAD

**Issue by mbUSC** [microsoft/playwright#31652]
### Version

1.45.0

### Steps to reproduce

Steps to reproduce:
1. `sudo su`
2. Run the example code:
```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium, p.firefox, p.webkit]:
        browser = browser_type.launch()
        page = browser.new_page()
        page.goto('http://playwright.dev')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

### Expected behavior

Example code runs successfully

### Actual behavior

```
root@m:/home/m# python testplaywright.py 
Traceback (most recent call last):
  File "/home/m/testplaywright.py", line 13, in <module>
    run(playwright)
  File "/home/m/testplaywright.py", line 5, in run
    browser = playwright.firefox.launch(headless=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/sync_api/_generated.py", line 14155, in launch
    self._sync(
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_browser_type.py", line 94, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: BrowserType.launch: Target page, context or browser has been closed
Browser logs:

\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557
\u2551 Firefox is unable to launch if the $HOME folder isn't owned by the current user. \u2551
\u2551 Workaround: Set the HOME=/root environment variable when running Playwright.     \u2551
\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d
Call log:
<launching> /root/.cache/ms-playwright/firefox-1454/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-XXXXXX3ThOaG -juggler-pipe -silent
  - <launched> pid=124801
  - [pid=124801][err] Running Nightly as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/.mutter-Xwaylandauth.5Q84P2 which is owned by m.)
  - [pid=124801] <process did exit: exitCode=1, signal=null>
  - [pid=124801] starting temporary directories cleanup
```

### Additional context

The suggested workaround (setting the HOME=/root environment variable when running Playwright) does not work

### Environment

```Text
- Operating System: Ubuntu 24.04 LTS
- CPU: arm64
- Browser: Firefox
- Python Version: 3.12
- Other info:
```

**Comment by yury-s** [comment]
How can we reproduce it?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by mbUSC** [comment]
> How can we reproduce it? If there is no `/root` directory in your environment you may need to point HOME to the actual root's home location.

Hi @yury-s! Thank you for looking into this!
The `/root` directory does exist on my system (Ubuntu Server). 
What additional information can I provide to make it easier to troubleshoot?
