### ISSUE TITLE
[Bug]: .chromium.connect_over_cdp ，Timeout 2000ms exceeded

### ISSUE THREAD

**Issue by tdRPA** [microsoft/playwright#31697]
### Version

1.45.0

### Steps to reproduce

1. connect to Chrome
2. after several hours connect again
3. timeout error

### Expected behavior

be able to connect to Chrome

### Actual behavior

Timeout 2000ms exceeded

### Additional context

```
>>> from playwright.sync_api import sync_playwright
>>> play=sync_playwright()
>>> 
>>> playAPI=play.start()

>>> currentBrowser=playAPI.chromium.connect_over_cdp('http://127.0.0.1:%s' % '9222',timeout=2000)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    currentBrowser=playAPI.chromium.connect_over_cdp('http://127.0.0.1:%s' % '9222',timeout=2000)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_api\_generated.py", line 14516, in connect_over_cdp
    self._sync(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_browser_type.py", line 172, in connect_over_cdp
    response = await self._channel.send_return_as_dict("connectOverCDP", params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 64, in send_return_as_dict
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: BrowserType.connect_over_cdp: Timeout 2000ms exceeded.
Call log:
<ws preparing> retrieving websocket url from http://127.0.0.1:9222
   <ws connecting> ws://127.0.0.1:9222/devtools/browser/8f24caea-3a04-4b66-860d-a8d8e2d10927
   <ws connected> ws://127.0.0.1:9222/devtools/browser/8f24caea-3a04-4b66-860d-a8d8e2d10927

```
### Environment

```Text
- Operating System: [win 2016 server]
- CPU: [amd64]
- Browser: [Chrome 126.0.6478.127]
- Python Version: [3.8.10]
- Other info:
```

**Comment by dgozman** [comment]
@tdRPA Unfortunately, it's impossible for us to fix the problem without being able to reproduce. Given the steps above, I don't think we'll be able to reliably reproduce an issue that requires waiting for "several hours".

I'd recommend to come up with a repro that is more reliable and does not require such a long time, and file a new issue by filling in the "Bug Report" template. Closing this issue for now as non-reproducible.
