### ISSUE TITLE
[Bug]: Timeout only on GitHub Actions with lazy loaded images and `.all()` usage

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#31737]
### Version

1.45.2

### Steps to reproduce

Reproduction repo: https://github.com/karlhorky/repro-playwright-next-js-lazy-images-all-timeout

1. Review [test code](https://github.com/karlhorky/repro-playwright-next-js-lazy-images-all-timeout/blob/main/tests/lazyVisibleImages.spec.ts) and [React Client Component code](https://github.com/karlhorky/repro-playwright-next-js-lazy-images-all-timeout/blob/main/app/ClientComponent.tsx)
2. View GitHub Actions test results below ([original workflow run](https://github.com/karlhorky/repro-playwright-next-js-lazy-images-all-timeout/actions/runs/9978031183/job/27574007806))

```
pnpm exec playwright test
  pnpm exec playwright test
  shell: /usr/bin/bash -e {0}
  
[WebServer]   ▲ Next.js 14.2.5
[WebServer]   - Local:        http://localhost:3000
 ✓ Starting...
[WebServer]  ✓ Ready in 290ms
Running 1 test using 1 worker
T
  1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Test timeout of 30000ms exceeded.
    Error: locator.scrollIntoViewIfNeeded: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for locator('img[loading="lazy"]:visible').nth(36)
       6 |
       7 |   for (const lazyImage of lazyImages) {
    >  8 |     await lazyImage.scrollIntoViewIfNeeded();
         |                     ^
       9 |     await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
      10 |   }
      11 | });
        at /home/runner/work/repro-playwright-next-js-lazy-images-all-timeout/repro-playwright-next-js-lazy-images-all-timeout/tests/lazyVisibleImages.spec.ts:8:21
  Slow test file: [chromium] › lazyVisibleImages.spec.ts (30.0s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
Error:   1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Test timeout of 30000ms exceeded.
Error:   1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Error: locator.scrollIntoViewIfNeeded: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for locator('img[loading="lazy"]:visible').nth(36)


       6 |
       7 |   for (const lazyImage of lazyImages) {
    >  8 |     await lazyImage.scrollIntoViewIfNeeded();
         |                     ^
       9 |     await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
      10 |   }
      11 | });

        at /home/runner/work/repro-playwright-next-js-lazy-images-all-timeout/repro-playwright-next-js-lazy-images-all-timeout/tests/lazyVisibleImages.spec.ts:8:21
Warning: [chromium] › lazyVisibleImages.spec.ts took 30.0s
Notice:   1 failed
    [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
Error: Process completed with exit code 1.
```

### Expected behavior

I was expecting that the error message would more clearly guide me towards what the issue is (that `locator('img[loading="lazy"]:visible').nth(36)` is no longer available, because it is now invisible, thanks to the `useEffect()`)

I'm aware that [usage docs of `all()`](https://playwright.dev/docs/api/class-locator#locator-all) has a note, which is relevant here:

> [locator.all()](https://playwright.dev/docs/api/class-locator#locator-all) does not wait for elements to match the locator, and instead immediately returns whatever is present in the page. When the list of elements changes dynamically, [locator.all()](https://playwright.dev/docs/api/class-locator#locator-all) will produce unpredictable and flaky results. When the list of elements is stable, but loaded dynamically, wait for the full list to finish loading before calling [locator.all()](https://playwright.dev/docs/api/class-locator#locator-all).

Concretely, this error message could be improved to say:

1. 30s is the default test timeout (with docs link)
2. make "waiting" in the message more expressive - maybe something about "endless"?
3. list out some common errors that can cause endless waiting for elements (with docs links)

### Actual behavior

The error message seemed to communicate:

1. generic 30s timeout occurred
   1. user questions / thought process: why 30s? did I set this value? I don't remember setting it
2. something about "waiting for" a locator
   1. user questions / thought process: what does waiting mean? what are common errors that could cause endless waiting for an element? what is the relevance of 36?

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.46 GB / 15.61 GB
    Container: Yes
  Binaries:
    Node: 20.15.1 - /opt/hostedtoolcache/node/20.15.1/x64/bin/node
    npm: 10.7.0 - /opt/hostedtoolcache/node/20.15.1/x64/bin/npm
    pnpm: 9.5.0 - /usr/local/bin/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.45.2 => 1.45.2
```

**Comment by karlhorky** [comment]
## Workaround 1: Assert length of selector

Verify stability of the images count before loading:

```ts
const lazyImagesLocator = page.locator('img[loading="lazy"]:visible');

// Assert on length to wait for all images to be streamed to
// the browser and present in the DOM
//
await expect(lazyImagesLocator).toHaveCount(13);

const lazyImages = await lazyImagesLocator.all();

for (const lazyImage of lazyImages) {
  await lazyImage.scrollIntoViewIfNeeded();
  await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
}
```

**Comment by dgozman** [comment]
@karlhorky Thank you for the issue!

> 30s is the default test timeout (with docs link)

This "test timeout of XXXms exceeded" is the most common Playwright error. For most of the users its clear that test has a timeout of XXXms and it took longer to run the test. If not, searching on the internet immediately leads to the [timeouts guide](https://playwright.dev/docs/test-timeouts). I don't think we should make the error message longer and pollute it with extra information that will bury the more relevant details like the log.

> make "waiting" in the message more expressive - maybe something about "endless"?

This is a stylistic choice. It is not endless though, it ends after the action timeout, if any, or after the test timeout.

> list out some common errors that can cause endless waiting for elements (with docs links)

Again, this will only help someone learning Playwright, but will regress the experience of all other users. I don't think we should be aiming at the new-comer, and instead should rely on them reading the docs.

So far, I don't see how we can meaningfully improve the error. If you have a specific suggestion for the error text, please share and we'll consider it.

**Comment by karlhorky** [comment]
> I don't think we should make the error message longer and pollute it with extra information

Thanks for dedication to this goal! I also don't want it to be endlessly long.

What is your feeling on something like this (URL could be shorter too, if Playwright has a shortener domain):

```diff
pnpm exec playwright test
  pnpm exec playwright test
  shell: /usr/bin/bash -e {0}
  
[WebServer]   ▲ Next.js 14.2.5
[WebServer]   - Local:        http://localhost:3000/
 ✓ Starting...
[WebServer]  ✓ Ready in 290ms
Running 1 test using 1 worker
T
  1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
-   Test timeout of 30000ms exceeded.
+   Test timeout of 30000ms exceeded. https://playwright.dev/docs/test-timeouts
    Error: locator.scrollIntoViewIfNeeded: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for locator('img[loading="lazy"]:visible').nth(36)
       6 |
```

> Again, this will only help someone learning Playwright, but will regress the experience of all other users. I don't think we should be aiming at the new-comer, and instead should rely on them reading the docs.

Working with beginners almost every day, I disagree pretty strongly with this approach. In my opinion, across the industry, minimalism cannot outweigh potential user benefits, especially in situations which are hard to debug, vague, generic. Even though these issues are often about new users, it also affects experienced users from time to time, so it's worth a few log lines to be helpful.

I think having a short list (2-4 items) of the most common reasons for "waiting" timeouts would outweigh the space usage downsides:

```diff
pnpm exec playwright test
  pnpm exec playwright test
  shell: /usr/bin/bash -e {0}
  
[WebServer]   ▲ Next.js 14.2.5
[WebServer]   - Local:        http://localhost:3000
 ✓ Starting...
[WebServer]  ✓ Ready in 290ms
Running 1 test using 1 worker
T
  1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Test timeout of 30000ms exceeded.
    Error: locator.scrollIntoViewIfNeeded: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for locator('img[loading="lazy"]:visible').nth(36)
       6 |
       7 |   for (const lazyImage of lazyImages) {
    >  8 |     await lazyImage.scrollIntoViewIfNeeded();
         |                     ^
       9 |     await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
      10 |   }
      11 | });
        at /home/runner/work/repro-playwright-next-js-lazy-images-all-timeout/repro-playwright-next-js-lazy-images-all-timeout/tests/lazyVisibleImages.spec.ts:8:21
  Slow test file: [chromium] › lazyVisibleImages.spec.ts (30.0s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
Error:   1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Test timeout of 30000ms exceeded.
Error:   1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Error: locator.scrollIntoViewIfNeeded: Test timeout of 30000ms exceeded.
    Call log:
-      - waiting for locator('img[loading="lazy"]:visible').nth(36)
+      - waiting for locator('img[loading="lazy"]:visible').nth(36) (possibly endless)
+          
+   Common causes for timeouts waiting for locators (https://example.com/abc):
+      - <common cause 1>
+      - <common cause 2>
+      - <common cause 3>

       6 |
       7 |   for (const lazyImage of lazyImages) {
    >  8 |     await lazyImage.scrollIntoViewIfNeeded();
         |                     ^
       9 |     await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
      10 |   }
      11 | });

        at /home/runner/work/repro-playwright-next-js-lazy-images-all-timeout/repro-playwright-next-js-lazy-images-all-timeout/tests/lazyVisibleImages.spec.ts:8:21
Warning: [chromium] › lazyVisibleImages.spec.ts took 30.0s
Notice:   1 failed
    [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
Error: Process completed with exit code 1.
```

However, this could also be hidden behind a link, if that's unacceptable:


```diff
pnpm exec playwright test
  pnpm exec playwright test
  shell: /usr/bin/bash -e {0}
  
[WebServer]   ▲ Next.js 14.2.5
[WebServer]   - Local:        http://localhost:3000
 ✓ Starting...
[WebServer]  ✓ Ready in 290ms
Running 1 test using 1 worker
T
  1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Test timeout of 30000ms exceeded.
    Error: locator.scrollIntoViewIfNeeded: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for locator('img[loading="lazy"]:visible').nth(36)
       6 |
       7 |   for (const lazyImage of lazyImages) {
    >  8 |     await lazyImage.scrollIntoViewIfNeeded();
         |                     ^
       9 |     await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
      10 |   }
      11 | });
        at /home/runner/work/repro-playwright-next-js-lazy-images-all-timeout/repro-playwright-next-js-lazy-images-all-timeout/tests/lazyVisibleImages.spec.ts:8:21
  Slow test file: [chromium] › lazyVisibleImages.spec.ts (30.0s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
Error:   1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Test timeout of 30000ms exceeded.
Error:   1) [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
    Error: locator.scrollIntoViewIfNeeded: Test timeout of 30000ms exceeded.
    Call log:
-      - waiting for locator('img[loading="lazy"]:visible').nth(36)
+      - waiting for locator('img[loading="lazy"]:visible').nth(36) (possibly endless)
+          
+   Common causes for timeouts waiting for locators: https://example.com/abc

       6 |
       7 |   for (const lazyImage of lazyImages) {
    >  8 |     await lazyImage.scrollIntoViewIfNeeded();
         |                     ^
       9 |     await expect(lazyImage).not.toHaveJSProperty('naturalWidth', 0);
      10 |   }
      11 | });

        at /home/runner/work/repro-playwright-next-js-lazy-images-all-timeout/repro-playwright-next-js-lazy-images-all-timeout/tests/lazyVisibleImages.spec.ts:8:21
Warning: [chromium] › lazyVisibleImages.spec.ts took 30.0s
Notice:   1 failed
    [chromium] › lazyVisibleImages.spec.ts:3:5 › scroll to lazy visible images and wait for loading 
Error: Process completed with exit code 1.
```

**Comment by dgozman** [comment]
@karlhorky Thank you for the suggestions, we'll discuss them with the team.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by karlhorky** [comment]
@dgozman since it's been a while, I wanted to check in again, about the discussions with the team.

What did the team think about my suggestions to improve the clarity and actionability of the terminal output? Or if they didn't like my specific suggestions, were there any other ideas explored to make the messages less vague and generic?
