### ISSUE TITLE
[Bug]: AddInitScript not injecting Script correctly

### ISSUE THREAD

**Issue by mpmartins** [microsoft/playwright#31864]
### Version

1.45.*

### Steps to reproduce

1. Clone repo https://github.com/mpmartins/playwright-issue-report
2. Execute org.example.App#main

### Expected behavior

Output should be "Some script".

### Actual behavior

You will get the following exception:

```
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Error {
  message='ReferenceError: definition is not defined
    at eval (eval at evaluate (:226:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
  name='Error
  stack='Error: ReferenceError: definition is not defined
    at eval (eval at evaluate (:226:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at CRExecutionContext.evaluateWithArguments (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/chromium/crExecutionContext.js:92:33)
    at async LongStandingScope._race (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/utils/manualPromise.js:96:14)
    at async Object.evaluateExpression (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/javascript.js:242:12)
    at async Frame.evaluateExpression (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/frames.js:598:19)
    at async FrameDispatcher.evaluateExpression (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/dispatchers/frameDispatcher.js:91:55)
    at async LongStandingScope._race (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/utils/manualPromise.js:96:14)
    at async FrameDispatcher._handleCommand (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/dispatchers/dispatcher.js:96:14)
    at async DispatcherConnection.dispatch (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/dispatchers/dispatcher.js:361:22)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:56)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:120)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:130)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106)
	at com.microsoft.playwright.impl.FrameImpl.evaluateImpl(FrameImpl.java:304)
	at com.microsoft.playwright.impl.PageImpl.lambda$evaluate$23(PageImpl.java:722)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89)
	at com.microsoft.playwright.impl.PageImpl.evaluate(PageImpl.java:722)
	at com.microsoft.playwright.Page.evaluate(Page.java:4467)
	at org.example.App.main(App.java:23)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='ReferenceError: definition is not defined
    at eval (eval at evaluate (:226:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
  name='Error
  stack='Error: ReferenceError: definition is not defined
    at eval (eval at evaluate (:226:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at CRExecutionContext.evaluateWithArguments (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/chromium/crExecutionContext.js:92:33)
    at async LongStandingScope._race (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/utils/manualPromise.js:96:14)
    at async Object.evaluateExpression (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/javascript.js:242:12)
    at async Frame.evaluateExpression (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/frames.js:598:19)
    at async FrameDispatcher.evaluateExpression (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/dispatchers/frameDispatcher.js:91:55)
    at async LongStandingScope._race (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/utils/manualPromise.js:96:14)
    at async FrameDispatcher._handleCommand (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/dispatchers/dispatcher.js:96:14)
    at async DispatcherConnection.dispatch (/private/var/folders/r0/qr9djvvd6n39q6zqkzvrhtdm0000gn/T/playwright-java-15488121008208938513/package/lib/server/dispatchers/dispatcher.js:361:22)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:259)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:211)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:118)
	... 9 more
``` 

### Additional context

The issue happens only on 1.45.* versions. 
If you try 1.44.0, you will see that the code works correctly.

### Environment

- Operating System: [MacOS]
- CPU: [arm64]
- Browser: [Chromium]
- Java Version: [11]

**Comment by pavelfeldman** [comment]
In your snippet,
```js
console.log(await page.evaluate(() => foo));
```

resolves to

```js
console.log(await page.evaluate(() => window.foo));
```

So instead of 
```js
const foo = 'bar'
```

you should add init script as 

```js
window.foo = 'bar'
```

if you want it to work. It did work as const = by accident before we wrapped it in additional scope.
