### ISSUE TITLE
[Bug]: Browser.new_page: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by brkydnc** [microsoft/playwright#31950]
### Version

1.45.1

### Steps to reproduce

1. `virtualenv venv`
2. `source venv/bin/activate`
3. `pip install playwright===1.45.1`
4. `playwright install --with-deps chromium`
5. `python main.py # Run the minimal reproduction example`

### Expected behavior

A headed browser window to show up with the following MRE in the [official documentation](https://playwright.dev/python/docs/api/class-browser) (Although the documentation uses Firefox, I use **Chromium**):

```py
from playwright.sync_api import sync_playwright, Playwright

def run(playwright: Playwright):
    browser = playwright.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://example.com")
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```

### Actual behavior

Playwright (or, most probably Chromium) crashed with the following error messages

The error **without** `DEBUG=pw:browser`:
```
Traceback (most recent call last):
  File "/Users/berkay/pw/main.py", line 10, in <module>
    run(playwright)
  File "/Users/berkay/pw/main.py", line 5, in run
    page = browser.new_page()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 13868, in new_page
    self._sync(
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/_impl/_browser.py", line 178, in new_page
    return await self._connection.wrap_api_call(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Browser.new_page: Target page, context or browser has been closed
Browser logs:

<launching> /Users/berkay/Library/Caches/ms-playwright/chromium-1124/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/46/n19qmc196sqg5c23z9fqmgvh0000gn/T/playwright_chromiumdev_profile-xdyZTBAOnaFR --remote-debugging-pipe --no-startup-window
<launched> pid=13870
[pid=13870][err] Received signal 10 BUS_ADRALN 00000bad4007
[pid=13870][err]  [0x00011c81da58]
[pid=13870][err]  [0x00011c811ac8]
[pid=13870][err]  [0x00011c81d9a8]
[pid=13870][err]  [0x000197217584]
[pid=13870][err]  [0x0001a1d6a4ec]
[pid=13870][err]  [0x0001a1d62844]
[pid=13870][err]  [0x0001a1d6260c]
[pid=13870][err]  [0x0001a1d5ffac]
[pid=13870][err]  [0x0001a1d5f880]
[pid=13870][err]  [0x0001a1d5f79c]
[pid=13870][err]  [0x0001a1d5f640]
[pid=13870][err]  [0x00019ac12f6c]
[pid=13870][err]  [0x00019ac12dec]
[pid=13870][err]  [0x00019ad2a63c]
[pid=13870][err]  [0x00019ad29f0c]
[pid=13870][err]  [0x00011d92193c]
[pid=13870][err]  [0x00011b5d3ac4]
[pid=13870][err]  [0x00011c27c6e0]
[pid=13870][err]  [0x0001182f58ac]
[pid=13870][err]  [0x00011a9f6244]
[pid=13870][err]  [0x00011a9ed950]
[pid=13870][err]  [0x00011a98c024]
[pid=13870][err]  [0x00011abfba68]
[pid=13870][err]  [0x00011abf0a68]
[pid=13870][err]  [0x000121868798]
[pid=13870][err]  [0x000121867e80]
[pid=13870][err]  [0x00011f41f4d4]
[pid=13870][err]  [0x00011f4290b8]
[pid=13870][err]  [0x000119d042b4]
[pid=13870][err]  [0x00011f3bd0d0]
[pid=13870][err]  [0x00011f3bb1b8]
[pid=13870][err]  [0x00011a674790]
[pid=13870][err]  [0x00011a6742b0]
[pid=13870][err]  [0x00011a655f28]
[pid=13870][err]  [0x00011a6703b8]
[pid=13870][err]  [0x00011c7c58d0]
[pid=13870][err]  [0x00011c7dd954]
[pid=13870][err]  [0x00011c7dd500]
[pid=13870][err]  [0x00011c8286d4]
[pid=13870][err]  [0x00011c823eb4]
[pid=13870][err]  [0x00011c827ec0]
[pid=13870][err]  [0x0001972c64d8]
[pid=13870][err]  [0x0001972c646c]
[pid=13870][err]  [0x0001972c61dc]
[pid=13870][err]  [0x0001972c4dc8]
[pid=13870][err]  [0x0001972c4434]
[pid=13870][err]  [0x0001a1a6819c]
[pid=13870][err]  [0x0001a1a67fd8]
[pid=13870][err]  [0x0001a1a67d30]
[pid=13870][err]  [0x00019ab23d68]
[pid=13870][err]  [0x00019b319808]
[pid=13870][err]  [0x00011c25a848]
[pid=13870][err]  [0x00011c823eb4]
[pid=13870][err]  [0x00011c25a790]
[pid=13870][err]  [0x00019ab1709c]
[pid=13870][err]  [0x00011c828dd0]
[pid=13870][err]  [0x00011c827864]
[pid=13870][err]  [0x00011c7ddfc8]
[pid=13870][err]  [0x00011c7ab610]
[pid=13870][err]  [0x00011a5d71e0]
[pid=13870][err]  [0x00011a5d89dc]
[pid=13870][err]  [0x00011a5d4ae8]
[pid=13870][err]  [0x00011bcb73a0]
[pid=13870][err]  [0x00011bcb8668]
[pid=13870][err]  [0x00011bcb826c]
[pid=13870][err]  [0x00011bcb6928]
[pid=13870][err]  [0x00011bcb6d30]
[pid=13870][err]  [0x0001181a9430]
[pid=13870][err]  [0x0001045ec988]
[pid=13870][err]  [0x000196e5e0e0]
[pid=13870][err] [end of stack trace]
[pid=13870][err] [0801/132055.206348:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x104a74000, 0x8000): (os/kern) invalid address (1)
[pid=13870][err] [0801/132055.206862:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x104a74000, 0x8000): (os/kern) invalid address (1)
[pid=13870][err] [0801/132055.207059:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x104a74000, 0x8000): (os/kern) invalid address (1)
[pid=13870][err] [0801/132055.207330:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x104a74000, 0x8000): (os/kern) invalid address (1)
[pid=13870][err] [0801/132055.207548:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x104a74000, 0x8000): (os/kern) invalid address (1)
[pid=13870][err] [0801/132055.207749:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x104a74000, 0x8000): (os/kern) invalid address (1)
[pid=13870][err] [0801/132055.207932:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x104a74000, 0x8000): (os/kern) invalid address (1)
[pid=13870][err] [0801/132055.302646:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
[pid=13870][err] [13878:259:0801/132055.304124:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[pid=13870][err] [13876:259:0801/132055.304123:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[pid=13870][err] [13879:259:0801/132055.304124:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[pid=13870][err] [13877:259:0801/132055.304214:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
```
The error with `DEBUG=pw:browser`:
```
  pw:browser <launching> /Users/berkay/Library/Caches/ms-playwright/chromium-1124/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/46/n19qmc196sqg5c23z9fqmgvh0000gn/T/playwright_chromiumdev_profile-fgjAZgprOrVD --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=13764 +2ms
  pw:browser [pid=13764][err] Received signal 10 BUS_ADRALN 00000bad4007 +439ms
  pw:browser [pid=13764][err]  [0x00011c559a58] +1ms
  pw:browser [pid=13764][err]  [0x00011c54dac8] +0ms
  pw:browser [pid=13764][err]  [0x00011c5599a8] +0ms
  pw:browser [pid=13764][err]  [0x000197217584] +0ms
  pw:browser [pid=13764][err]  [0x0001a1d6a4ec] +0ms
  pw:browser [pid=13764][err]  [0x0001a1d62844] +0ms
  pw:browser [pid=13764][err]  [0x0001a1d6260c] +0ms
  pw:browser [pid=13764][err]  [0x0001a1d5ffac] +0ms
  pw:browser [pid=13764][err]  [0x0001a1d5f880] +0ms
  pw:browser [pid=13764][err]  [0x0001a1d5f79c] +0ms
  pw:browser [pid=13764][err]  [0x0001a1d5f640] +0ms
  pw:browser [pid=13764][err]  [0x00019ac12f6c] +0ms
  pw:browser [pid=13764][err]  [0x00019ac12dec] +0ms
  pw:browser [pid=13764][err]  [0x00019ad2a63c] +0ms
  pw:browser [pid=13764][err]  [0x00019ad29f0c] +0ms
  pw:browser [pid=13764][err]  [0x00011d65d93c] +0ms
  pw:browser [pid=13764][err]  [0x00011b30fac4] +0ms
  pw:browser [pid=13764][err]  [0x00011bfb86e0] +0ms
  pw:browser [pid=13764][err]  [0x0001180318ac] +0ms
  pw:browser [pid=13764][err]  [0x00011a732244] +0ms
  pw:browser [pid=13764][err]  [0x00011a729950] +1ms
  pw:browser [pid=13764][err]  [0x00011a6c8024] +0ms
  pw:browser [pid=13764][err]  [0x00011a937a68] +0ms
  pw:browser [pid=13764][err]  [0x00011a92ca68] +0ms
  pw:browser [pid=13764][err]  [0x0001215a4798] +1ms
  pw:browser [pid=13764][err]  [0x0001215a3e80] +0ms
  pw:browser [pid=13764][err]  [0x00011f15b4d4] +0ms
  pw:browser [pid=13764][err]  [0x00011f1650b8] +0ms
  pw:browser [pid=13764][err]  [0x000119a402b4] +0ms
  pw:browser [pid=13764][err]  [0x00011f0f90d0] +0ms
  pw:browser [pid=13764][err]  [0x00011f0f71b8] +0ms
  pw:browser [pid=13764][err]  [0x00011a3b0790] +0ms
  pw:browser [pid=13764][err]  [0x00011a3b02b0] +0ms
  pw:browser [pid=13764][err]  [0x00011a391f28] +0ms
  pw:browser [pid=13764][err]  [0x00011a3ac3b8] +0ms
  pw:browser [pid=13764][err]  [0x00011c5018d0] +0ms
  pw:browser [pid=13764][err]  [0x00011c519954] +0ms
  pw:browser [pid=13764][err]  [0x00011c519500] +0ms
  pw:browser [pid=13764][err]  [0x00011c5646d4] +0ms
  pw:browser [pid=13764][err]  [0x00011c55feb4] +0ms
  pw:browser [pid=13764][err]  [0x00011c563ec0] +0ms
  pw:browser [pid=13764][err]  [0x0001972c64d8] +0ms
  pw:browser [pid=13764][err]  [0x0001972c646c] +0ms
  pw:browser [pid=13764][err]  [0x0001972c61dc] +0ms
  pw:browser [pid=13764][err]  [0x0001972c4dc8] +0ms
  pw:browser [pid=13764][err]  [0x0001972c4434] +0ms
  pw:browser [pid=13764][err]  [0x0001a1a6819c] +0ms
  pw:browser [pid=13764][err]  [0x0001a1a67fd8] +0ms
  pw:browser [pid=13764][err]  [0x0001a1a67d30] +0ms
  pw:browser [pid=13764][err]  [0x00019ab23d68] +0ms
  pw:browser [pid=13764][err]  [0x00019b319808] +0ms
  pw:browser [pid=13764][err]  [0x00011bf96848] +0ms
  pw:browser [pid=13764][err]  [0x00011c55feb4] +0ms
  pw:browser [pid=13764][err]  [0x00011bf96790] +0ms
  pw:browser [pid=13764][err]  [0x00019ab1709c] +0ms
  pw:browser [pid=13764][err]  [0x00011c564dd0] +0ms
  pw:browser [pid=13764][err]  [0x00011c563864] +0ms
  pw:browser [pid=13764][err]  [0x00011c519fc8] +0ms
  pw:browser [pid=13764][err]  [0x00011c4e7610] +0ms
  pw:browser [pid=13764][err]  [0x00011a3131e0] +0ms
  pw:browser [pid=13764][err]  [0x00011a3149dc] +0ms
  pw:browser [pid=13764][err]  [0x00011a310ae8] +0ms
  pw:browser [pid=13764][err]  [0x00011b9f33a0] +0ms
  pw:browser [pid=13764][err]  [0x00011b9f4668] +0ms
  pw:browser [pid=13764][err]  [0x00011b9f426c] +0ms
  pw:browser [pid=13764][err]  [0x00011b9f2928] +0ms
  pw:browser [pid=13764][err]  [0x00011b9f2d30] +0ms
  pw:browser [pid=13764][err]  [0x000117ee5430] +0ms
  pw:browser [pid=13764][err]  [0x000104328988] +1ms
  pw:browser [pid=13764][err]  [0x000196e5e0e0] +0ms
  pw:browser [pid=13764][err] [end of stack trace] +0ms
  pw:browser [pid=13764][err] [0801/131909.772439:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1) +101ms
  pw:browser [pid=13764][err] [0801/131909.772972:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1) +1ms
  pw:browser [pid=13764][err] [0801/131909.773190:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1) +0ms
  pw:browser [pid=13764][err] [0801/131909.773482:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1) +0ms
  pw:browser [pid=13764][err] [0801/131909.773712:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1) +0ms
  pw:browser [pid=13764][err] [0801/131909.773914:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1) +0ms
  pw:browser [pid=13764][err] [0801/131909.774113:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1) +1ms
  pw:browser [pid=13764][err] [0801/131909.872681:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5) +98ms
  pw:browser [pid=13764][err] [13774:259:0801/131909.874114:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?) +2ms
  pw:browser [pid=13764][err] [13772:259:0801/131909.874098:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?) +0ms
  pw:browser [pid=13764][err] [13773:259:0801/131909.874115:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?) +1ms
  pw:browser [pid=13764][err] [13775:259:0801/131909.874201:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?) +1ms
  pw:browser [pid=13764] <process did exit: exitCode=null, signal=SIGBUS> +5ms
  pw:browser [pid=13764] starting temporary directories cleanup +0ms
Traceback (most recent call last):
  File "/Users/berkay/pw/main.py", line 10, in <module>
    run(playwright)
  File "/Users/berkay/pw/main.py", line 5, in run
    page = browser.new_page()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 13868, in new_page
    self._sync(
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/_impl/_browser.py", line 178, in new_page
    return await self._connection.wrap_api_call(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/berkay/pw/ven/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Browser.new_page: Target page, context or browser has been closed
Browser logs:

<launching> /Users/berkay/Library/Caches/ms-playwright/chromium-1124/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/46/n19qmc196sqg5c23z9fqmgvh0000gn/T/playwright_chromiumdev_profile-fgjAZgprOrVD --remote-debugging-pipe --no-startup-window
<launched> pid=13764
[pid=13764][err] Received signal 10 BUS_ADRALN 00000bad4007
[pid=13764][err]  [0x00011c559a58]
[pid=13764][err]  [0x00011c54dac8]
[pid=13764][err]  [0x00011c5599a8]
[pid=13764][err]  [0x000197217584]
[pid=13764][err]  [0x0001a1d6a4ec]
[pid=13764][err]  [0x0001a1d62844]
[pid=13764][err]  [0x0001a1d6260c]
[pid=13764][err]  [0x0001a1d5ffac]
[pid=13764][err]  [0x0001a1d5f880]
[pid=13764][err]  [0x0001a1d5f79c]
[pid=13764][err]  [0x0001a1d5f640]
[pid=13764][err]  [0x00019ac12f6c]
[pid=13764][err]  [0x00019ac12dec]
[pid=13764][err]  [0x00019ad2a63c]
[pid=13764][err]  [0x00019ad29f0c]
[pid=13764][err]  [0x00011d65d93c]
[pid=13764][err]  [0x00011b30fac4]
[pid=13764][err]  [0x00011bfb86e0]
[pid=13764][err]  [0x0001180318ac]
[pid=13764][err]  [0x00011a732244]
[pid=13764][err]  [0x00011a729950]
[pid=13764][err]  [0x00011a6c8024]
[pid=13764][err]  [0x00011a937a68]
[pid=13764][err]  [0x00011a92ca68]
[pid=13764][err]  [0x0001215a4798]
[pid=13764][err]  [0x0001215a3e80]
[pid=13764][err]  [0x00011f15b4d4]
[pid=13764][err]  [0x00011f1650b8]
[pid=13764][err]  [0x000119a402b4]
[pid=13764][err]  [0x00011f0f90d0]
[pid=13764][err]  [0x00011f0f71b8]
[pid=13764][err]  [0x00011a3b0790]
[pid=13764][err]  [0x00011a3b02b0]
[pid=13764][err]  [0x00011a391f28]
[pid=13764][err]  [0x00011a3ac3b8]
[pid=13764][err]  [0x00011c5018d0]
[pid=13764][err]  [0x00011c519954]
[pid=13764][err]  [0x00011c519500]
[pid=13764][err]  [0x00011c5646d4]
[pid=13764][err]  [0x00011c55feb4]
[pid=13764][err]  [0x00011c563ec0]
[pid=13764][err]  [0x0001972c64d8]
[pid=13764][err]  [0x0001972c646c]
[pid=13764][err]  [0x0001972c61dc]
[pid=13764][err]  [0x0001972c4dc8]
[pid=13764][err]  [0x0001972c4434]
[pid=13764][err]  [0x0001a1a6819c]
[pid=13764][err]  [0x0001a1a67fd8]
[pid=13764][err]  [0x0001a1a67d30]
[pid=13764][err]  [0x00019ab23d68]
[pid=13764][err]  [0x00019b319808]
[pid=13764][err]  [0x00011bf96848]
[pid=13764][err]  [0x00011c55feb4]
[pid=13764][err]  [0x00011bf96790]
[pid=13764][err]  [0x00019ab1709c]
[pid=13764][err]  [0x00011c564dd0]
[pid=13764][err]  [0x00011c563864]
[pid=13764][err]  [0x00011c519fc8]
[pid=13764][err]  [0x00011c4e7610]
[pid=13764][err]  [0x00011a3131e0]
[pid=13764][err]  [0x00011a3149dc]
[pid=13764][err]  [0x00011a310ae8]
[pid=13764][err]  [0x00011b9f33a0]
[pid=13764][err]  [0x00011b9f4668]
[pid=13764][err]  [0x00011b9f426c]
[pid=13764][err]  [0x00011b9f2928]
[pid=13764][err]  [0x00011b9f2d30]
[pid=13764][err]  [0x000117ee5430]
[pid=13764][err]  [0x000104328988]
[pid=13764][err]  [0x000196e5e0e0]
[pid=13764][err] [end of stack trace]
[pid=13764][err] [0801/131909.772439:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1)
[pid=13764][err] [0801/131909.772972:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1)
[pid=13764][err] [0801/131909.773190:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1)
[pid=13764][err] [0801/131909.773482:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1)
[pid=13764][err] [0801/131909.773712:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1)
[pid=13764][err] [0801/131909.773914:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1)
[pid=13764][err] [0801/131909.774113:WARNING:process_memory_mac.cc(94)] mach_vm_read(0x1047b0000, 0x8000): (os/kern) invalid address (1)
[pid=13764][err] [0801/131909.872681:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
[pid=13764][err] [13774:259:0801/131909.874114:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[pid=13764][err] [13772:259:0801/131909.874098:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[pid=13764][err] [13773:259:0801/131909.874115:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
[pid=13764][err] [13775:259:0801/131909.874201:ERROR:shared_memory_switch.cc(244)] Mach rendezvous failed, terminating process (parent died?)
```

### Additional context

This is probably related to Chromium. Maybe this can be avoided by using a newer version of Chromium.

### Environment

```shell
`playwright install --with-deps` command installs the following versions of Chroimum and FFMPEG:

- Chromium 127.0.6533.17 (playwright build v1124)
- FFMPEG playwright build v1009 from https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-mac-arm64.zip

---

The output of `npx envinfo --preset playwright` is the following:

System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 1.17 GB / 16.00 GB
Binaries:
  Node: 22.5.1 - /opt/homebrew/bin/node
  npm: 10.8.2 - /opt/homebrew/bin/npm
IDEs:
  VSCode: 1.91.1 - /opt/homebrew/bin/code
Languages:
  Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
Do you mind running the following and providing us the output?

    file ~/Library/Caches/ms-playwright/chromium-1124/chrome-mac/Chromium.app/Contents/MacOS/Chromium

This should help us to find out if the right browser for your arch is installed.

My suspect is that you are running in a Rosetta emulated terminal, so the output of `arch` would be helpful as well.

Looks related to https://github.com/microsoft/playwright/issues/31064 - maybe you could check for this env var as well.

**Comment by brkydnc** [comment]
This is interesting, #31064 really worked out, but I don't know the reason. Why would deleting an env var prevent Chromium from crashing? Anyway, here is the output:

```
/Users/berkay/Library/Caches/ms-playwright/chromium-1124/chrome-mac/Chromium.app/Contents/MacOS/Chromium: Mach-O 64-bit executable arm64
```

Deleting `DYLD_LIBRARY_PATH` env variable solved the issue.

**Comment by mxschmitt** [comment]
Do you also have this env in your zshrc/bashrc? Maybe a different program put it there.

Your output from `file` looks good!

**Comment by brkydnc** [comment]
Hey @mxschmitt, actually, I put the env variable there. The reason is because some libraries installed with homebrew are not recognized by the dynamic linker.

```
export DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH
``` 

Removing it solved the problem.

**Comment by mxschmitt** [comment]
Closing as per above! Thank you for confirming!
