### ISSUE TITLE
[Bug]: Using headless: true results in an "Invalid login" error for Microsoft Login.

### ISSUE THREAD

**Issue by balajitoverto** [microsoft/playwright#32034]
### Version

1.46.0

### Steps to reproduce

In global-setup.ts file by giving headless as true getting a Microsoft login as an invalid login
```
browser = await chromium.launch({ headless: true });
    context = await browser.newContext();
    const page = await context.newPage();
```

### Expected behavior

By giving  headless as false the console we got
```
csrapp@0.0.0 e2e
> playwright test

Navigated to http://localhost:4200
Login button clicked and new window opened
Trying to find input with placeholder: someone@example.com
Found input placeholder: someone@example.com
Email filled
Password filled
Sign in button clicked
Yes button clicked
New window fully loaded
Authentication state saved
```

### Actual behavior

When we give headless as true
```
un e2eUsers\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp>      

> csrapp@0.0.0 e2e
> playwright test

Navigated to http://localhost:4200
Login button clicked and new window opened
Trying to find input with placeholder: someone@example.com
Input with placeholder someone@example.com not found, trying next
Trying to find input with placeholder: Email, phone, or Skype        
Input with placeholder Email, phone, or Skype not found, trying next 
Trying to find input with placeholder: someone@example.com
Input with placeholder someone@example.com not found, trying next
Error: Error: Input field with the expected placeholders not found
    at waitForInputField (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\e2e\utils\global-setup.ts:19:9)
    at globalSetup (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\e2e\utils\global-setup.ts:50:31)
    at Object.setup (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\node_modules\playwright\lib\runner\tasks.js:173:39)      
    at taskLoop (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\node_modules\playwright\lib\runner\taskRunner.js:81:11)      
    at TaskRunner.runDeferCleanup (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\node_modules\playwright\lib\runner\taskRunner.js:98:5)
    at TaskRunner.run (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\node_modules\playwright\lib\runner\taskRunner.js:53:9) 
    at Runner.runAllTests (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\node_modules\playwright\lib\runner\runner.js:73:24)
    at runTests (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\node_modules\playwright\lib\program.js:210:85)
    at t.<anonymous> (C:\Users\balajitirupathi\Documents\GitHub\LoyaltyHub.CSRApp\node_modules\playwright\lib\program.js:54:7)
Error: Invalid login!

   at ..\utils\global-setup.ts:87
```

### Additional context

Golbal-setup.ts file

```
import { chromium, FullConfig, Page } from '@playwright/test';
import { environment } from './environment';

const user_email = environment.testUserEmail || '';
const user_password = environment.testUserPassword || '';

const placeholders = ['someone@example.com', 'Email, phone, or Skype', 'someone@example.com'];

async function waitForInputField(page: Page, placeholders: string[], timeout = 50000) {
  for (const placeholder of placeholders) {
    try {
      console.log(`Trying to find input with placeholder: ${placeholder}`);
      await page.waitForSelector(`input[placeholder="${placeholder}"]`, { timeout });
      return placeholder; // Return the placeholder that was found
    } catch (error) {
      console.log(`Input with placeholder ${placeholder} not found, trying next`);
    }
  }
  throw new Error('Input field with the expected placeholders not found');
}

async function globalSetup(config: FullConfig) {
  let browser;
  let context;
  let newWindow: Page;

  try {
    // Launch browser in headless mode
    browser = await chromium.launch({ headless: true });
    context = await browser.newContext();
    const page = await context.newPage();

    const baseURL = config.projects[0].use.baseURL ?? '';
  
    // Navigate to the URL
    await page.goto(baseURL);
    console.log(`Navigated to ${baseURL}`);
  
    // Wait for the login button and click it
    const [newPage] = await Promise.all([
      context.waitForEvent('page'),
      page.getByRole('button', { name: 'Log in' }).click()
    ]);
    console.log('Login button clicked and new window opened');
  
    newWindow = newPage;
    await newWindow.waitForLoadState('domcontentloaded');

    // Determine the input placeholder based on the environment
    const input_placeholder = await waitForInputField(newWindow, placeholders);
    console.log(`Found input placeholder: ${input_placeholder}`);
    
    // Wait for the input field to be visible and interact with it
    await newWindow.getByPlaceholder(input_placeholder).click();
    await newWindow.getByPlaceholder(input_placeholder).fill(user_email);
    console.log('Email filled');
  
    // Wait for the "Next" button and click it
    await newWindow.getByRole('button', { name: 'Next' }).click();
  
    // Wait for the password field to be visible and interact with it
    await newWindow.getByPlaceholder('Password').click();
    await newWindow.getByPlaceholder('Password').fill(user_password);
    console.log('Password filled');
  
    // Wait for the "Sign in" button and click it
    await newWindow.getByRole('button', { name: 'Sign in' }).click();
    console.log('Sign in button clicked');
  
    // Wait for the "Yes" button and click it
    await newWindow.getByRole('button', { name: 'Yes' }).click();
    console.log('Yes button clicked');
  
    // Wait for the page to fully load
    await newWindow.waitForLoadState('load');
    console.log('New window fully loaded');
  
    // Save the authentication state
    await context.storageState({ path: 'e2e/auth.json' });
    console.log('Authentication state saved');
  
    // Close the browser
    await browser.close();
  } catch (err) {
    console.log('Error:', err);
    if (browser) await browser.close(); // Ensure the browser is closed on error
    throw new Error('Invalid login!');
  }
}

export default globalSetup;
```

### Environment

```shell
Environment
- OS: Windows
- Node.js Version: 20.14.11
- Playwright Version: 1.46.0
```

**Comment by yury-s** [comment]
It might be that the server doesn't like that it accessed by an automation tool and returns different page based on user agent/other headers in headless mode. Please provide full self-contained reproduction which we could run locally, if you think this is a Playwright bug.
