### ISSUE TITLE
[Bug]: Playwright Unable to Navigate/Switch to PDF Window in Headless Mode

### ISSUE THREAD

**Issue by chik145** [microsoft/playwright#32116]
### Version

1.46.0

### Steps to reproduce
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(true).setChannel("chrome"));

            BrowserContext context = browser.newContext();
            context.setDefaultTimeout(Duration.ofMinutes(1).toMillis());
            context.setDefaultNavigationTimeout(Duration.ofMinutes(1).toMillis());

            Page page = context.newPage();
            page.navigate("https://icseindia.org/document/sample.pdf");
            System.out.println(page.url());
        }

### Expected behavior

I expect to fetch the pdf URL from pdf window after navigating or switching into it.
Issue comes only in headless mode where in headed mode its working fine

### Actual behavior
getting Below Exception

Exception in thread "main" com.microsoft.playwright.PlaywrightException: Error {
  message='net::ERR_ABORTED at https://icseindia.org/document/sample.pdf
  name='Error
  stack='Error: net::ERR_ABORTED at https://icseindia.org/document/sample.pdf
    at FrameSession._navigate (C:\Users\Z0044AUB\AppData\Local\Temp\playwright-java-3568037739963406314\package\lib\server\chromium\crPage.js:515:35)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:454:9)
    at async Frame._gotoAction (C:\Users\Z0044AUB\AppData\Local\Temp\playwright-java-3568037739963406314\package\lib\server\frames.js:534:28)
}
Call log:
- navigating to "https://icseindia.org/document/sample.pdf", waiting until "load"

	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:56)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:120)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:130)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106)
	at com.microsoft.playwright.impl.FrameImpl.navigateImpl(FrameImpl.java:463)
	at com.microsoft.playwright.impl.PageImpl.lambda$navigate$46(PageImpl.java:932)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89)
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:932)
	at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:42)
	at com.microsoft.playwright.Page.navigate(Page.java:5446)
	at tests.Demo.main(Demo.java:19)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='net::ERR_ABORTED at https://icseindia.org/document/sample.pdf
  name='Error
  stack='Error: net::ERR_ABORTED at https://icseindia.org/document/sample.pdf
    at FrameSession._navigate (C:\Users\Z0044AUB\AppData\Local\Temp\playwright-java-3568037739963406314\package\lib\server\chromium\crPage.js:515:35)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:454:9)
    at async Frame._gotoAction (C:\Users\Z0044AUB\AppData\Local\Temp\playwright-java-3568037739963406314\package\lib\server\frames.js:534:28)
}

### Environment

```shell
System:
Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
RAM 32 GB
```

**Comment by pavelfeldman** [comment]
Playwright is a tool for testing web content. PDF is not web content, navigating to PDF url does not result in a web page being opened, so it is outside of scope for Playwright. You can use any fetch library to download the pdf file and one of the pdf libraries to analyze it instead.

**Comment by pirate** [comment]
How can you force playwright to download the PDF if the PDF downlaod is generated by some frontend JS on-the-fly and is not available via URL.
