### ISSUE TITLE
[Bug]: getting a "PlaywrightException: Playwright connection closed" in the middle of my test for no apparent reason

### ISSUE THREAD

**Issue by AmitZ01** [microsoft/playwright#32419]
### Version

1.46.0

### Steps to reproduce

I am using Playwright Java with JUnit and Spring framework and am running the following java code on a web application:

in the BaseTest class:

    @BeforeEach
    public void innit() {
        applicationContext = new AnnotationConfigApplicationContext(AUTOMATION_BASE_PACKAGE);
        pageNavigator = applicationContext.getBean(PageNavigator.class);
        reportGenerator = applicationContext.getBean(ReportGenerator.class);
        testProps = applicationContext.getBean(TestPropsConfig.class);
        loginInfo = applicationContext.getBean(LoginInfo.class);
        applicationContext.getBean(BrowserContext.class).tracing().start();

        pageNavigator.getPage().onDialog(dialog -> {
                dialog.accept();
            });

        enterApp(loginInfo.user1);
    }

    @AfterEach
    public void breakDown(TestInfo testInfo) {
        Video video = pageNavigator.getPage().video();

        attachLogFileToReport();
        pageNavigator.getPage().close();
        applicationContext.close();
        renameVideo(video, testInfo.getDisplayName());
    }

in the actual test class:

   @Order(1)
    @Test
    public void givenWorkspace_whenMeetingCreated_thenItAppearsInMeetingsTable() {
        MeetingsPage meetingsPage = pageNavigator.navigateToPage(MeetingsPage.class);
        assertThat(meetingsPage.getMeetingsTable().getMeetingRowByText(MEETING_NAME)).isAttached();
    }

    @Order(2)
    @Test
    public void givenMeeting_whenAddingTaskToMeeting_thenItAppearsInTasksPage() {
        Task taskToAdd = Task.builder()
                .meetingTitle(MEETING_NAME)
                .meetingDescription(getRandomUUID())
                .supervisor("מנהל סביבה")
                .endDate(getCurrentDate().plusDays(1))
                .workfield(Workfield.TRAINING)
                .build();

        MeetingsPage meetingsPage = pageNavigator.navigateToPage(MeetingsPage.class);
        meetingsPage.chooseWorkspace(workspaceTitle);
        meetingsPage.getMeetingsTable().getMeetingRowByText(MEETING_NAME).click();

        AddTaskPopup addTaskPopup = meetingPage.openAddTaskPopup();
        TasksSteps.createTaskFromMeeting(addTaskPopup, taskToAdd).getSaveButton().click();

        IncomingMailPage incomingMailPage = pageNavigator.navigateToPage(IncomingMailPage.class);
        assertThat(incomingMailPage.getIncomingMailTable().getIncomingMailRowByText(taskToAdd.getMeetingTitle())).isAttached();
    }

when running each test on its own it runs fine but when running them consecutively I'm getting the following exception:

com.microsoft.playwright.PlaywrightException: Playwright connection closed

	at com.microsoft.playwright.impl.PipeTransport.send(PipeTransport.java:50)
	at com.microsoft.playwright.impl.Connection.internalSendMessage(Connection.java:168)
	at com.microsoft.playwright.impl.Connection.sendMessageAsync(Connection.java:134)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:130)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106)
	at com.microsoft.playwright.impl.FrameImpl.clickImpl(FrameImpl.java:252)
	at com.microsoft.playwright.impl.FrameImpl.lambda$click$8(FrameImpl.java:243)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.FrameImpl.click(FrameImpl.java:243)
	at com.microsoft.playwright.impl.LocatorImpl.click(LocatorImpl.java:160)
	at automation.elements.Button.click(Button.java:16)
	at automation.pages.MeetingPage.openAddTaskPopup(MeetingPage.java:123)
	at tests.MeetingsPageTests.givenMeeting_whenAddingTaskToMeeting_thenItAppearsInTasksPage(MeetingsPageTests.java:47)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

At no point am I closing the Playwright connection in this test, which makes me think that the connection is closing because of some bug. Could this be a Playwright bug or perhaps a JUnit bug?

### Expected behavior

The tests should run fine when I'm running them consecutively.

### Actual behavior

The tests fail because of the exception I mentioned.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 757.41 MB / 15.63 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - ~\node_modules\.bin\npm.CMD
  Managers:
    Maven: 3.8.6 - C:\apache-maven-3.8.6\bin\mvn.CMD
    pip3: 24.0 - C:\Python312\Scripts\pip3.EXE
  Utilities:
    Git: 2.39.0.
    Curl: 8.8.0 - C:\Windows\system32\curl.EXE
  Virtualization:
    Docker: 20.10.21 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
    Docker Compose: 2.13.0 - C:\Program Files\Docker\Docker\resources\bin\docker-compose.EXE
  IDEs:
    VSCode: 1.92.2 - C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.20 - C:\Windows\system32\bash.EXE
    Java: 20.0.1
    Python: 3.12.3
  Browsers:
    Chrome: 128.0.6613.114
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
```

**Comment by kebroncdl-cell** [comment]
playwrightproject


MCP error -32000: Connection closed
