### ISSUE TITLE
[Bug]: Error: EPERM

### ISSUE THREAD

**Issue by Klindt1** [microsoft/playwright#32926]
### Version

v1.47.2  

### Steps to reproduce

I write the the command in the terminal and gets an error.

### Expected behavior

The test goes as usual

### Actual behavior

After the new update i get this error
  ^

Error: EPERM: operation not permitted, watch 'C:\Users\klindt001\Application Data'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2473:36)
    at il (C:\Users\klindt001\node_modules\playwright\lib\utilsBundleImpl.js:52:7900)
    at hp (C:\Users\klindt001\node_modules\playwright\lib\utilsBundleImpl.js:52:8169)
    at bs._watchWithNodeFs (C:\Users\klindt001\node_modules\playwright\lib\utilsBundleImpl.js:52:9584)
    at bs._handleDir (C:\Users\klindt001\node_modules\playwright\lib\utilsBundleImpl.js:52:12230)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async bs._addToNodeFs (C:\Users\klindt001\node_modules\playwright\lib\utilsBundleImpl.js:52:12873)
Emitted 'error' event on Fr instance at:
    at Fr._handleError (C:\Users\klindt001\node_modules\playwright\lib\utilsBundleImpl.js:52:26920)
    at bs._addToNodeFs (C:\Users\klindt001\node_modules\playwright\lib\utilsBundleImpl.js:52:13404)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\Users\\klindt001\\Application Data',
  filename: 'C:\\Users\\klindt001\\Application Data'
}

Node.js v20.11.1

### Additional context

I contacted my IT department at my work, and after the newest update Playwright want to get acces to Application Data, which doesnt make sense. Not %Appdata" but "Application Data" which they dont even have permission to look at?

### Environment

```shell
S C:\Users\klindt001> npx envinfo --preset playwright 

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 4.99 GB / 15.68 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.92.2 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
    playwright: ^1.47.2 => 1.47.2

PS C:\Users\klindt001>
```

**Comment by Skn0tt** [comment]
Hi! To me, this looks like Playwright is spawning a file watcher that then tries to access `Application Data`, which is forbidden. What's the specific Playwright command you're running, and in what directory are you executing it?

**Comment by Klindt1** [comment]
Hi Skn0tt i managed to fix this by change the directory. But took a while

But i just simply tried to run npx playwright test. In the correct cd, etc as i always has.

**Comment by Skn0tt** [comment]
Good to hear you managed to fix this. I don't think there's a bug in Playwright then. Closing!
