### ISSUE TITLE
MaxListenersExceededWarning when running fetch tests

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#32951]
```
tests/async/test_fetch_global.py::test_should_json_stringify_body_when_content_type_is_application_json[chromium-serialization2] (node:21485) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 lookup listeners added to [Socket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:593:17)
    at Socket.addListener (node:events:611:10)
    at Readable.on (node:internal/streams/readable:1126:35)
    at ClientRequest.<anonymous> (/Users/maxschmitt/Developer/playwright-python/playwright/driver/package/lib/server/fetch.js:396:16)
    at ClientRequest.emit (node:events:531:35)
    at tickOnSocket (node:_http_client:850:7)
    at onSocketNT (node:_http_client:913:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(node:21485) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 secureConnect listeners added to [Socket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at _addListener (node:events:593:17)
    at Socket.addListener (node:events:611:10)
    at Readable.on (node:internal/streams/readable:1126:35)
    at ClientRequest.<anonymous> (/Users/maxschmitt/Developer/playwright-python/playwright/driver/package/lib/server/fetch.js:402:16)
    at ClientRequest.emit (node:events:531:35)
    at tickOnSocket (node:_http_client:850:7)
    at onSocketNT (node:_http_client:913:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

When running the Python fetch tests: `pytest --browser chromium tests/async/test_fetch_browser_context.py tests/async/test_fetch_global.py`

Leaks here: 

```
        socket.on('lookup', () => {
          dnsLookupAt = (0, _utils.monotonicTime)();
        });
```

**Comment by Skn0tt** [comment]
I've used https://github.com/microsoft/playwright-python/pull/2584 to test `1.49.0-alpha-2024-10-07` vs `1.49.0-alpha-2024-10-08`, which contains https://github.com/microsoft/playwright/pull/32956. The test confirmed that it fixes the `MaxListenersExceededWarning`.
