### ISSUE TITLE
[Bug]: Play wright test cases are failing intermittently when PW version is upgraded to "@playwright/test": "^1.47.2" . cloud  test win32.

### ISSUE THREAD

**Issue by KausikPonnapalli7** [microsoft/playwright#33024]
### Version

1.47.2

### Steps to reproduce

1) Run a sample e2e test with basic functionality with PW 1.47.2 version in cloud test env. 
2) We'll observe few set of tests randomly fail with the below mentioned error.

### Expected behavior

Play wright test cases are failing with below error when we are upgrading PW version to "@playwright/test": "^1.47.2"

D:\data\CHT\4fb5ab6c\JWD_d9ecde6e>cd D:\data\CHT\4fb5ab6c 

D:\data\CHT\4fb5ab6c>cmd /c ""C:\Program Files\Git\bin\bash.exe" -- .\e2eWin32-_<repo>_x.sh" 
+ node 'D:\data\CHT\4fb5ab6c/cloudtest-tools/dist/index.js' test-runner --workingDirectory ooui --artifactFolders screenshots perfReports --packageName @1x/e2e-tests --hash 3db65da8633e878f9437ce5412d788ec38699545 --managedIdentityClientId 6cd6af56-9fda-4841-b7eb-3d6dc57f9140 --command ''\''e2e:ci:Test'\'''
new test file in test runner: D:\data\CHT\4fb5ab6c\NewFiles.json
Args -  @<repo>/<app>-e2e-tests e2e:ci:Tables:Test D:\data\CHT\4fb5ab6c\src\ooui
Script:  yarn run e2e:ci:Tables:Test
Working Directory:  D:\data\CHT\4fb5ab6c\src\ooui\apps\<app>-e2e-tests
Running C:\Program Files\Git\bin\bash.exe with params --noprofile --norc C:\Users\CLOUDT~1\AppData\Local\Temp\728cd3b9.sh at location D:\data\CHT\4fb5ab6c\src\ooui\apps\<app>-e2e-tests
pathUtils::e2eTestUtilsPath D:\data\CHT\4fb5ab6c\src\x\
[6:32:21 PM] ■ started 'e2e'
wacE2ETest::e2e-task::Running with params: &
wacE2ETest::e2e-task:: TestfileNames are :  [ 'Test.e2e.test.ts' ]
Starting playwright: yarn playwright test  Test.e2e.test.ts --project=Chromium --retries=1
pathUtils::e2eTestUtilsPath D:\data\CHT\4fb5ab6c\src\ooui\packages\e2e-tests-utils\
TypeError: (0 , _e2eTestsUtils.getBasePlaywrightConfig) is not a function
    at Object.<anonymous> (D:\data\CHT\4fb5ab6c\src\ooui\apps\<app>-e2e-tests\playwright.config.ts:28:56)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.f._compile (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .ts] (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requireOrImport (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\transform\transform.js:204:18)
    at loadUserConfig (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\common\configLoader.js:94:83)
    at loadConfig (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\common\configLoader.js:105:28)
    at loadConfigFromFileRestartIfNeeded (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\common\configLoader.js:273:10)
    at runTests (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\program.js:203:18)
    at t.<anonymous> (D:\data\CHT\4fb5ab6c\src\ooui\.store\playwright@1.47.2-df7b6902f38733389323\node_modules\playwright\lib\program.js:55:7)
[6:32:24 PM] x Error previously detected. See above for error messages.
[6:32:24 PM] x Error detected while running 'e2e'
[6:32:24 PM] x ------------------------------------
[6:32:24 PM] x Error: Command failed: yarn playwright test  Test.e2e.test.ts --project=Chromium --retries=1
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at wacE2ETest (D:\data\CHT\4fb5ab6c\src\ooui\packages\e2e-tests-utils\src\tasks\wacE2ETest.ts:207:5)
    at _wrapFunction (D:\data\CHT\4fb5ab6c\src\ooui\.store\just-task@1.9.0-f3e21528b9a55d0802d4\node_modules\just-task\lib\wrapTask.js:15:36)
    at taskWrapper (D:\data\CHT\4fb5ab6c\src\ooui\.store\undertaker@1.3.0-638a8333fcb2bde48015\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (D:\data\CHT\4fb5ab6c\src\ooui\.store\async-done@1.3.2-329abeb544b143bfcc20\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
[6:32:24 PM] x ------------------------------------
[6:32:24 PM] x Error previously detected. See above for error messages.
Test exited with err Error: Command failed: C:\Program Files\Git\bin\bash.exe --noprofile --norc C:\Users\CLOUDT~1\AppData\Local\Temp\728cd3b9.sh
___IGNORE___: error while replacing secrets [Error: EBUSY: resource busy or locked, open 'D:\data\CHT\4fb5ab6c\UserLogs\d9ecde6e\TestResults\exeTestConsoleLogs\e2eWin32-_<repo>_<app>_e2e_tests_e2e_ci_Test_106.out'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'D:\\data\\CHT\\4fb5ab6c\\UserLogs\\d9ecde6e\\TestResults\\exeTestConsoleLogs\\e2eWin32-_<repo>_<app>_e2e_tests_e2e_ci_tables_Test_106.out'
}
Error: Command failed: C:\Program Files\Git\bin\bash.exe --noprofile --norc C:\Users\CLOUDT~1\AppData\Local\Temp\72ddddd9.sh
    at checkExecSyncError (node:child_process:885:11)
    at execFileSync (node:child_process:921:15)
    at runExeFile (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:67158:53)
    at Object.handler (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:260351:11)
    at Object.handler (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:264006:31)
    at Object.handler (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:264076:31)
    at Object.runCommand (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:31060:44)
    at Object.parseArgs [as _parseArgs] (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:33203:47)
    at Object.get [as argv] (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:33160:26) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6468,
  stdout: null,
  stderr: null
}
Error: Command failed: C:\Program Files\Git\bin\bash.exe --noprofile --norc C:\Users\CLOUDT~1\AppData\Local\Temp\728cd3b9.sh
    at checkExecSyncError (node:child_process:885:11)
    at execFileSync (node:child_process:921:15)
    at runExeFile (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:67158:53)
    at Object.handler (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:260351:11)
    at Object.handler (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:264006:31)
    at Object.handler (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:264076:31)
    at Object.runCommand (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:31060:44)
    at Object.parseArgs [as _parseArgs] (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:33203:47)
    at Object.get [as argv] (D:\data\CHT\4fb5ab6c\cloudtest-tools\dist\index.js:33160:26) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6468,
  stdout: null,
  stderr: null
}

### Actual behavior

Test cases should ideally pass without intermittent issues.

### Environment

Win32 (CloudTest)

**Comment by pavelfeldman** [comment]
No idea what's happening there. We need to be able to reproduce issues to fix them. Try 1.48 just in case? It has a newer browser.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
