### ISSUE TITLE
[Bug]: Custom Reporter not usable

### ISSUE THREAD

**Issue by broehl-ptc** [microsoft/playwright#33041]
### Version

1.48

### Steps to reproduce

1. Create usual playwright test project.
2. Create custom reporter "myjunit.ts" in "reporter" directory of project.
3. Define custom reporter in `playwright.config.ts` file: `reporter: "./reporter/myjunit.ts"`
4. Run `playwright test`

### Expected behavior

The tests are run and reported in my junit format.

### Actual behavior

Error: Package subpath './' is not defined by "exports" in C:\GIT\git\my.playwright.testproject\node_modules\playwright\package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:592:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:669:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
    at Function.resolveFilename [as _resolveFilename] (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\transform\transform.js:250:36)
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\GIT\git\my.playwright.testproject\reporter\myjunit.ts:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.f._compile (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\utilsBundleImpl.js:16:994)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .ts] (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at requireOrImport (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\transform\transform.js:231:18)
    at requireOrImportDefaultFunction (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\runner\loadUtils.js:285:51)
    at loadReporter (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\runner\loadUtils.js:294:10)
    at createReporters (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\runner\reporters.js:68:69)
    at Runner.runAllTests (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\runner\runner.js:61:60)
    at runTests (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\program.js:211:31)
    at t.<anonymous> (C:\GIT\git\my.playwright.testproject\node_modules\playwright\lib\program.js:54:7) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
    Memory: 8.72 GB / 31.62 GB
  Binaries:
    Node: 20.16.0 - C:\Applications\nodejs\current\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.3.0 - ~\AppData\Roaming\npm\npm.CMD
  IDEs:
    VSCode: 1.93.1 - C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.21 - C:\cygwin64\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.47.0 => 1.47.0
    playwright: ^1.48.0 => 1.48.0

**Comment by pavelfeldman** [comment]
Hard to guess what is wrong without the exact source and ability to repro. Try examining your code, looking at other's reporters and asking question on Discord.
