### ISSUE TITLE
[Bug]: button click timeout (headless WebKit on Ubuntu 24.04.1 LTS)

### ISSUE THREAD

**Issue by johnnygerard** [microsoft/playwright#33057]
### Version

1.48.0

### Steps to reproduce

1. Launch a fresh instance of Ubuntu 24.04.1 LTS (see **Additional context** for details)
2. Run [bug-playwright-button-click/init.sh](https://github.com/johnnygerard/bug-playwright-button-click/blob/main/init.sh) (uses [nodesource](https://github.com/nodesource/distributions?tab=readme-ov-file#using-ubuntu-nodejs-20) instructions for Node.js 20 installation)

### Expected behavior

All tests should pass.

### Actual behavior

Some tests fail:

```
/usr/bin/npm run e2e

> bug-playwright-button-click@1.0.0 e2e
> playwright test


Running 9 tests using 4 workers
  1) [webkit] › button-user-interactions.spec.ts:12:7 › Button user interactions › Click ───────────

    Test timeout of 5000ms exceeded.

    Error: locator.click: Test timeout of 5000ms exceeded.
    Call log:
      - waiting for getByLabel(/light mode/i)
      -   locator resolved to <button disabled type="button" aria-live="polite" class="clean-btn toggleButton_gllP toggleButtonDisabled_aARS" title="Switch between dark and light mode (currently dark mode)" aria-label="Switch between dark and light mode (currently dark mode)">…</button>
      - attempting click action
      -   waiting for element to be visible, enabled and stable


      11 |
      12 |   test("Click", async ({ page }) => {
    > 13 |     await button.click();
         |                  ^
      14 |   });
      15 |
      16 |   test("Press enter", async ({ page }) => {

        at ~/bug-playwright-button-click/tests/button-user-interactions.spec.ts:13:18

  2) [webkit] › button-user-interactions.spec.ts:20:7 › Button user interactions › Tap ─────────────

    Test timeout of 5000ms exceeded.

    Error: locator.tap: Test timeout of 5000ms exceeded.
    Call log:
      - waiting for getByLabel(/light mode/i)
      -   locator resolved to <button disabled type="button" aria-live="polite" class="clean-btn toggleButton_gllP toggleButtonDisabled_aARS" title="Switch between dark and light mode (currently dark mode)" aria-label="Switch between dark and light mode (currently dark mode)">…</button>
      - attempting tap action
      -   waiting for element to be visible, enabled and stable


      19 |
      20 |   test("Tap", async ({ page }) => {
    > 21 |     await button.tap();
         |                  ^
      22 |   });
      23 | });
      24 |

        at ~/bug-playwright-button-click/tests/button-user-interactions.spec.ts:21:18

  2 failed
    [webkit] › button-user-interactions.spec.ts:12:7 › Button user interactions › Click ────────────
    [webkit] › button-user-interactions.spec.ts:20:7 › Button user interactions › Tap ──────────────
  7 passed (9.9s)

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.


```

### Additional context

The tests only fail in specific conditions: only WebKit in `--headless` or `--ui` mode in Ubuntu 24.04.1 LTS (on my current machine and also on a fresh install).

I tried various combinations:

- Tests pass on Ubuntu 22 LTS but fail on Ubuntu 24 LTS.
- CI tests pass with GitHub Actions (ubuntu-latest still uses Ubuntu 22 LTS).
- Tests always pass when run in `--headed` mode regardless of Ubuntu version.
- Tests pass when running on [WSL](https://ubuntu.com/desktop/wsl) and [multipass](https://multipass.run/) with Ubuntu 24.04.1 LTS (maybe because of the lack of a desktop environment or differences in the installed packages).

A simple workaround is to use `button.press("Enter")` instead of `button.click()` and `button.tap()`.

### Environment

  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 10.36 GB / 15.24 GB
    Container: Yes
  Binaries:
    Node: 20.18.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm
    pnpm: 9.12.1 - /usr/bin/pnpm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.48.0 => 1.48.0

**Comment by jaugustin** [comment]
We have similar issue on our tests suite, most tests fail with ubuntu 24.04 when it works on 22.04 or mac.

**Comment by dgozman** [comment]
@johnnygerard Thank you for the detailed repro! I tried to reproduce this on `Ubuntu 24.04 LTS` (I don't have 24.04.1 readily available),`@playwright/test@1.48.0` and `node v20.15.0`. Unfortunately, all tests pass for me in all browsers, with and without `--headed` or `--ui`, running multiple times. Any ideas on what could be different? Anything specific in your setup?

**Comment by johnnygerard** [comment]
I got the same test results on `ubuntu-24.04-desktop-amd64.iso`.
@dgozman Did you use a different Ubuntu image?

**Comment by dgozman** [comment]
@johnnygerard One idea I have is this could be related to `prefers-color-scheme` support. Trace shows that "light/dark mode switch" is `disabled`, perhaps because docusaurus failed to detect default color scheme? Does this webkit problem reproduce with other tests, not on `playwright.dev`?

**Comment by johnnygerard** [comment]
@dgozman I updated [bug-playwright-button-click](https://github.com/johnnygerard/bug-playwright-button-click) to test a noop button from GitHub Pages. I get the same results.

**Comment by dgozman** [comment]
@johnnygerard Thank you! Could you also run with `DEBUG=pw:protocol` and share the report please? Something is definitely stuck there, perhaps rafs are not firing? I hope that protocol log would help.

**Comment by johnnygerard** [comment]
@dgozman [playwright-report.zip](https://github.com/user-attachments/files/17466623/playwright-report.zip) with `DEBUG=pw:protocol`

**Comment by mxschmitt** [comment]
I tried to reproduce on amd and arm64 Ubuntu 24.04.1

    docker run -it mcr.microsoft.com/playwright:v1.48.1-noble /bin/bash

but was not able to.

**Comment by dgozman** [comment]
After looking at the logs, it seems like the issue is with rafs not firing, specific to WPE webkit headless backend. There's been similar issues with WPE, for example this one https://bugs.webkit.org/show_bug.cgi?id=255682. Let's see what can be done upstream.

**Comment by client-side96** [comment]
Can confirm this issue, too.

Running on both `mcr.microsoft.com/playwright:v1.49.1-noble` and `mcr.microsoft.com/playwright:v1.49.1-jammy` in a Github Action. The tests for `chromium` succeed, the tests for `webkit` fail.

```ts
  await page.getByRole("button", { name: "My button text" }).click();

  // waitForURL hangs forever
  await page.waitForURL("**/user");
```

**Comment by iam-peter** [comment]
We get the same issue on Ubuntu 24.04.1 with Python 3.12.3 and Playwright 1.49.1.

The same test runs without issues on Ubuntu 22.04.5 LTS with Python 3.10.12 and Playwright 1.47.0. 
The issue can be resolved by using the `force` argument in `page.locator(".some_class").click(force=True)`, but I would rather avoid enforcing it.

**Comment by R-Sandor** [comment]
I am also noticing this issue using Pop!_OS 22.04 LTS

**Comment by annagrigoryevaCT** [comment]
experiencing same issue on 1.49.1 and browser-webkit

**Comment by PupilTong** [comment]
Hi folks, this solution works for me :
https://github.com/microsoft/playwright/issues/32151#issuecomment-2305354421

**Comment by ftepes** [comment]
I'm noticing the same issue while running Playwright 1.45 under Debian 11 in AWS Lambda. Running the docker container locally works. I tried with and without `LIBGL_ALWAYS_SOFTWARE=true` but it doesn't work. It seems to get stuck at the element waiting to be stable.

**Comment by MillerSvt** [comment]
Setting `LIBGL_ALWAYS_SOFTWARE=true` considerably slows down tests in all browsers. Instead of completing in two seconds, they now take over 20 seconds.
