### ISSUE TITLE
[Feature]: Get the count of available frames in a FrameLocator

### ISSUE THREAD

**Issue by DashwoodIce9** [microsoft/playwright#33101]
### 🚀 Feature Request

Request to add a method to `FrameLocator` class to get the number of frames matching the given locator.

### Example

```java
// Returns the count of all frames matching the given locator.
page.frameLocator("#someElement iframe").count();
```

Would be great if we can just get a `List` to iterate over. Something like -
```java
// Returns List<FrameLocator>
page.frameLocator("#someElement iframe").list();
```

### Motivation

I have a use case where I want to test a website with a rough structure like the following -

```html
<body>
    <div id="buttonContainer">
        <iframe name="dynamicParentNamexx1123">
            <iframe name="dynamicChildNamexxyyzz123"></iframe>
            <iframe name="dynamicChildNamexxyyzz345"></iframe>
            <iframe name="dynamicChildNamexxyyzz678"></iframe>   
        </iframe>
    </div>
</body>
```

There are a bunch of elements in between and the names of `iframe`s are generated dynamically. I want to iterate over the children `iframe`s and perform some operations. My code currently looks somewhat like this -

```java
FrameLoctor parentIframe = page.frameLocator("#buttonContainer iframe");
for(int i = 0; i < 3; i++) {
    // do something with this
    parentIframe.frameLocator("iframe").nth(i);
}
```

This logic breaks if children `iframe` are dynamically generated and do not have a fixed count.

**Comment by DashwoodIce9** [comment]
Unfortunately it doesn't. I am guessing that's got something to do with the dynamic addition of the `iframe` elements on the web page.

```java
// returns 0
page.locator("#someElement iframe").count();
// returns empty String
page.locator("#someElement iframe").innerHTML();
// returns empty String
page.locator("#someElement iframe").elementHandle().innerHTML();
// returns 0
page.frameLocator("#someElement iframe").locator("iframe").count();
```

```java
// works and has the intended effect on the web page.
page.frameLocator("#someElement iframe").frameLocator("iframe").nth(0).locator("#someElementInsideFirstIframe").click();
```

```java
// Interestingly doesn't work and throws an exception. Expected to get 1 in output.
/*
 * Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Failed to find frame for selector "#someElement iframe >> internal:control=enter-frame >> iframe >> nth=0 >> internal:control=enter-frame >> #someElementInsideFirstIframe"
  name='Error
  stack='Error: Failed to find frame for selector "#someElement iframe >> internal:control=enter-frame >> iframe >> nth=0 >> internal:control=enter-frame >> #someElementInsideFirstIframe"
    at FrameSelectors.queryCount (/tmp/playwright-java-17468186945677309369/package/lib/server/frameSelectors.js:73:26)
    at async Frame.queryCount (/tmp/playwright-java-17468186945677309369/package/lib/server/frames.js:742:12)
    at async FrameDispatcher.queryCount (/tmp/playwright-java-17468186945677309369/package/lib/server/dispatchers/frameDispatcher.js:134:14)
    at async LongStandingScope._race (/tmp/playwright-java-17468186945677309369/package/lib/utils/manualPromise.js:96:14)
    at async FrameDispatcher._handleCommand (/tmp/playwright-java-17468186945677309369/package/lib/server/dispatchers/dispatcher.js:96:14)
    at async DispatcherConnection.dispatch (/tmp/playwright-java-17468186945677309369/package/lib/server/dispatchers/dispatcher.js:361:22)
}
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:259) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:211) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:118) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:130) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.FrameImpl.queryCount(FrameImpl.java:1116) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.LocatorImpl.count(LocatorImpl.java:165) ~[playwright-1.46.0.jar:1.46.0]
 */
page.frameLocator("#someElement iframe").frameLocator("iframe").nth(0).locator("#someElementInsideFirstIframe").count();
```

```java
// Doesn't work. Throws the following exception.
/*
 * Caused by: com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 10000ms exceeded.
  name='TimeoutError
  stack='TimeoutError: Timeout 10000ms exceeded.
    at ProgressController.run (/tmp/playwright-java-12775836096288264113/package/lib/server/progress.js:78:26)
    at Frame.click (/tmp/playwright-java-12775836096288264113/package/lib/server/frames.js:1007:23)
    at FrameDispatcher.click (/tmp/playwright-java-12775836096288264113/package/lib/server/dispatchers/frameDispatcher.js:157:30)
    at FrameDispatcher._handleCommand (/tmp/playwright-java-12775836096288264113/package/lib/server/dispatchers/dispatcher.js:94:40)
    at DispatcherConnection.dispatch (/tmp/playwright-java-12775836096288264113/package/lib/server/dispatchers/dispatcher.js:361:39)
}
Call log:
- waiting for locator("#someElement iframe").locator("iframe").locator("#someElementInsideFirstIframe")

        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:254) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:211) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:118) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:130) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.FrameImpl.clickImpl(FrameImpl.java:252) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.FrameImpl.lambda$click$8(FrameImpl.java:243) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.FrameImpl.click(FrameImpl.java:243) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.LocatorImpl.click(LocatorImpl.java:160) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.Locator.click(Locator.java:2406) ~[playwright-1.46.0.jar:1.46.0]
 */
page.locator("#someElement iframe").locator("iframe").locator("#someElementInsideFirstIframe").click();
```

### Your suggestion

```java
// throws the following exception
/*
 Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Failed to find frame for selector "#someElement iframe >> internal:control=enter-frame >> iframe"
  name='Error
  stack='Error: Failed to find frame for selector "#someElement iframe >> internal:control=enter-frame >> iframe"
    at FrameSelectors.queryCount (/tmp/playwright-java-14735299061311550720/package/lib/server/frameSelectors.js:73:26)
    at async Frame.queryCount (/tmp/playwright-java-14735299061311550720/package/lib/server/frames.js:742:12)
    at async FrameDispatcher.queryCount (/tmp/playwright-java-14735299061311550720/package/lib/server/dispatchers/frameDispatcher.js:134:14)
    at async LongStandingScope._race (/tmp/playwright-java-14735299061311550720/package/lib/utils/manualPromise.js:96:14)
    at async FrameDispatcher._handleCommand (/tmp/playwright-java-14735299061311550720/package/lib/server/dispatchers/dispatcher.js:96:14)
    at async DispatcherConnection.dispatch (/tmp/playwright-java-14735299061311550720/package/lib/server/dispatchers/dispatcher.js:361:22)
}
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:259) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:211) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:118) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:130) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.FrameImpl.queryCount(FrameImpl.java:1116) ~[playwright-1.46.0.jar:1.46.0]
        at com.microsoft.playwright.impl.LocatorImpl.count(LocatorImpl.java:165) ~[playwright-1.46.0.jar:1.46.0]
 */
page.locator("#someElement iframe").contentFrame().locator('iframe').count(); 
```

**Comment by dgozman** [comment]
@DashwoodIce9 Unfortunately, I did not really understand your last comment. Could you please show the exact frameLocator that you'd call the `.count()` or `.list()` upon?

For any `frameLocator`, you can use `frameLocator.owner().count()` to get the number of iframes that match your frame locator. Same goes for list. Alternatively, you can always replace the last part of your `.frameLocator('iframe')` with `locator('iframe')` and call `count()/list()` on that. Let me know whether that works for you.

**Comment by DashwoodIce9** [comment]
I want to call `count()` on the second `FrameLocator` so that I can set an upper bound my `for` loop defined in this feature request.

> ```java
> FrameLoctor parentIframe = page.frameLocator("#buttonContainer iframe");
> for(int i = 0; i < 3; i++) {
>     // do something with this
>     parentIframe.frameLocator("iframe").nth(i);
> }
> ```

Like so - `page.frameLocator("#buttonContainer iframe").frameLocator("iframe").count()`.

I have tried calling `frameLocator.owner().count()` and it did not work. It throws an exception similar to the one I shared above.

**Comment by dgozman** [comment]
@DashwoodIce9 Thank you for the explanation. The problem is that there are zero such iframes, and so Playwright cannot do `owner().count()` unfortunately. However, you can do the following instead:

```
FrameLoctor parentIframe = page.frameLocator("#buttonContainer iframe");
for(int i = 0; i < parentIframe.locator("iframe").count(); i++) {
    // do something with this
    parentIframe.frameLocator("iframe").nth(i);
}
```

Note that I replaced the last `frameLocator()` with `locator()` and can now call `count()` or `all()`. Let me know whether this helps.

**Comment by DashwoodIce9** [comment]
Hi @dgozman, I tried that. Unfortunately `parentIframe.locator("iframe").count()` returns 0 for some reason. Refer the 4th example in my [comment above](https://github.com/microsoft/playwright/issues/33101#issuecomment-2412849920).

> ```java
> // returns 0
> page.frameLocator("#someElement iframe").locator("iframe").count();
> ```

**Comment by dgozman** [comment]
@DashwoodIce9 That means there are zero iframes at the time you call this method. Note that if your page dynamically adds/removes iframes, this technique will be unreliable. We recommend using auto-waiting assertions instead.

**Comment by DashwoodIce9** [comment]
Of course!

Absolute brain fart on my end. Yep. waiting and then checking the count does work.

Sorry for the trouble, all is okay. Thanks for the help!
