### ISSUE TITLE
老版本系统如何使用playwright

### ISSUE THREAD

**Issue by hrj5032188** [microsoft/playwright#33130]
windows server 2008R2 
how to use playwright

Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: -1073741511
	at com.microsoft.playwright.impl.driver.jar.DriverJar.installBrowsers(DriverJar.java:99)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:68)
	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction in the english language, which we can run locally to reproduce your issue. Thanks for your understanding!
