### ISSUE TITLE
[Bug]: UI crashed

### ISSUE THREAD

**Issue by drupal-spider** [microsoft/playwright#33141]
### Version

1.48.1

### Steps to reproduce

npx playwright test --ui

UI open without any issue.

Run small amount of tests, no issue.

Run 2000+ visual comparison test. 

### Expected behavior

Finish all tests without error and UI should not crash.

### Actual behavior

The UI crashed before showing the report at the end with the following errors:

/node_modules/playwright-core/lib/server/chromium/crConnection.js:129
    if (this._crashed || this._closed || this._connection._closed || this._connection._browserDisconnectedLogs) throw new _protocolError.ProtocolError(this._crashed ? 'crashed' : 'closed', undefined, this._connection._browserDisconnectedLogs);
                                                                                                                      ^

ProtocolError: 
    at CRSession.send (/private/var/www/automated-test/node_modules/playwright-core/lib/server/chromium/crConnection.js:129:119)
    at CRPage.bringToFront (/private/var/www/automated-test/node_modules/playwright-core/lib/server/chromium/crPage.js:185:42)
    at Page.bringToFront (/private/var/www/automated-test/node_modules/playwright-core/lib/server/page.js:385:26)
    at CRBrowserContext.<anonymous> (/private/var/www/automated-test/node_modules/playwright-core/lib/server/launchApp.js:51:20)
    at CRBrowserContext.emit (node:events:519:28)
    at Page.emitOnContext (/private/var/www/automated-test/node_modules/playwright-core/lib/server/page.js:128:26)
    at Page.reportAsNew (/private/var/www/automated-test/node_modules/playwright-core/lib/server/page.js:111:10)
    at CRPage._reportAsNew (/private/var/www/automated-test/node_modules/playwright-core/lib/server/chromium/crPage.js:129:16)
    at /private/var/www/automated-test/node_modules/playwright-core/lib/server/chromium/crPage.js:118:12 {
  type: 'crashed',
  method: undefined,
  logs: undefined
}

Node.js v22.9.0

### Additional context

The same tests can run inside of the VS code with Playwright extension without any error. 

### Environment

macOS 15.0.1 
CPU: Apple M1 Max
Memory: 32 GB
Store: 929.95 GB available

Node.js v22.9.0
NPM 10.8.3
Chromium Version 130.0.6723.31 (Developer Build) (arm64)

**Comment by dgozman** [comment]
Tentatively merging into #33086.
