### ISSUE TITLE
[BUG] Fails on start - WS url is undefined

### ISSUE THREAD

**Issue by AleF83** [microsoft/playwright#3315]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: Mac
- Node.js version: 14.5.0
- Browser: All
- Extra: Fails on tests start

**Code Snippet**

```typescript
import { chromium, Page, Browser } from 'playwright-chromium';

const browser = await chromium.launch();

```

**Describe the bug**
Fails on start:
```bash
 TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    ================= browserType.connect logs =================
    [browser] <ws connecting> undefined
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

      at initAsClient (node_modules/ws/lib/websocket.js:484:27)
      at new WebSocket (node_modules/ws/lib/websocket.js:70:7)
      at new WebSocketTransport (node_modules/playwright-chromium/lib/transport.js:79:20)
      at Function.connect (node_modules/playwright-chromium/lib/transport.js:106:27)
      at node_modules/playwright-chromium/lib/server/browserType.js:106:68
      at ProgressController.run (node_modules/playwright-chromium/lib/progress.js:76:29)
      at Object.runAbortableTask (node_modules/playwright-chromium/lib/progress.js:29:23)
      at Chromium.connect (node_modules/playwright-chromium/lib/server/browserType.js:105:27)
```

**Comment by pavelfeldman** [comment]
Your snippet is saying `launch`, but your stack trace is saying `connect`. As if you were calling `connect` without parameters. Could it be that you did not recompile TS and your JS file still has connect?

**Comment by AleF83** [comment]
I figured out the problem. 
I'm using `playwright` in `jest` tests. I set `preset = 'jest-playwright-preset'` and `runner = 'my-custom-runner'`.
So my runner overwrote the PlaywrightRunner.
I've changed my runner to inherit from PlaywrightRunner and now it works.
Thank you.
