### ISSUE TITLE
[Bug]: context|page.add_init_script stopped working after 1.44 in chromium

### ISSUE THREAD

**Issue by starenka** [microsoft/playwright#33320]
### Version

1.48.0

### Steps to reproduce

```
starenka /tmp/pbug % mktmpenv                                                               
created virtual environment CPython3.12.6.final.0-64 in 308ms
  creator CPython3Posix(dest=/data/.envs/tmp-d4e2064a5b3772b, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/starenka/.local/share/virtualenv)
    added seed packages: pip==24.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d4e2064a5b3772b/bin/predeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d4e2064a5b3772b/bin/postdeactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d4e2064a5b3772b/bin/preactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d4e2064a5b3772b/bin/postactivate
virtualenvwrapper.user_scripts creating /data/.envs/tmp-d4e2064a5b3772b/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
```

```
(tmp-d4e2064a5b3772b) starenka /d/./tmp-d4e2064a5b3772b % pip install playwright; playwright install chromium
Collecting playwright
  Using cached playwright-1.48.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Collecting greenlet==3.1.1 (from playwright)
  Downloading greenlet-3.1.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting pyee==12.0.0 (from playwright)
  Using cached pyee-12.0.0-py3-none-any.whl.metadata (2.8 kB)
Collecting typing-extensions (from pyee==12.0.0->playwright)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Using cached playwright-1.48.0-py3-none-manylinux1_x86_64.whl (38.2 MB)
Downloading greenlet-3.1.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (613 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.1/613.1 kB 7.5 MB/s eta 0:00:00
Using cached pyee-12.0.0-py3-none-any.whl (14 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: typing-extensions, greenlet, pyee, playwright
Successfully installed greenlet-3.1.1 playwright-1.48.0 pyee-12.0.0 typing-extensions-4.12.2

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Downloading Chromium 130.0.6723.31 (playwright build v1140) from https://playwright.azureedge.net/builds/chromium/1140/chromium-linux.zip
164.5 MiB [====================] 100% 0.0s
Chromium 130.0.6723.31 (playwright build v1140) downloaded to /home/starenka/.cache/ms-playwright/chromium-1140
Downloading FFMPEG playwright build v1010 from https://playwright.azureedge.net/builds/ffmpeg/1010/ffmpeg-linux.zip
2.3 MiB [====================] 100% 0.0s
FFMPEG playwright build v1010 downloaded to /home/starenka/.cache/ms-playwright/ffmpeg-1010
```

```
(tmp-d4e2064a5b3772b) starenka /tmp/pbug % cat bugreport.py 
import asyncio
from pathlib import Path
from playwright.async_api import async_playwright


async def run(playwright):
    chromium = playwright.chromium
    browser = await chromium.launch()
    context = await browser.new_context()
    payload = Path(__file__).resolve().parent / 'test.js'
    with open(payload, 'w') as sf:
        sf.write('function foo() { return 1 }')

    await context.add_init_script(path=payload)
    page = await context.new_page()

    await page.goto('about:chromium')
    print(await page.evaluate('foo()'))

    await browser.close()


async def main():
    async with async_playwright() as playwright:
        await run(playwright)
asyncio.run(main())
```

```
(tmp-d4e2064a5b3772b) starenka /tmp/pbug % python bugreport.py
Traceback (most recent call last):
  File "/tmp/pbug/bugreport.py", line 26, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/pbug/bugreport.py", line 25, in main
    await run(playwright)
  File "/tmp/pbug/bugreport.py", line 18, in run
    await page.evaluate('foo()')
  File "/data/.envs/tmp-d4e2064a5b3772b/lib/python3.12/site-packages/playwright/async_api/_generated.py", line 8491, in evaluate
    await self._impl_obj.evaluate(
  File "/data/.envs/tmp-d4e2064a5b3772b/lib/python3.12/site-packages/playwright/_impl/_page.py", line 469, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/.envs/tmp-d4e2064a5b3772b/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 278, in evaluate
    await self._channel.send(
  File "/data/.envs/tmp-d4e2064a5b3772b/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/.envs/tmp-d4e2064a5b3772b/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.evaluate: ReferenceError: foo is not defined
    at eval (eval at evaluate (:234:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:234:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

### Expected behavior

to not die and call the function injected

### Actual behavior

the script is not injected/is not accessible

### Additional context

works in 1.44, any newer version fails to exec the code

### Environment

- Operating System: [Debian testing]
- CPU: [x86]
- Browser: [Chromium]
- Python Version: [3.12]

**Comment by mxschmitt** [comment]
Looks similar to https://github.com/microsoft/playwright/issues/31864

**Comment by Skn0tt** [comment]
Agree, looks similar. Try following the advice in https://github.com/microsoft/playwright/issues/31864#issuecomment-2251521999. If you think there's a bug in Playwright, open another issue and follow the bug report template. Make sure to include a reproduction example, we need that to investigate locally.

**Comment by starenka** [comment]
cheers.

the example is right there, mate. with all steps to reproduce.

if the stuff need to be set on window from now on, maybe this should be
mentioned in the docs, cause it is a breaking change, from my point of view.
