### ISSUE TITLE
[Regression]: While Upgrading from .Net 6 to .Net 8  (.NET)

### ISSUE THREAD

**Issue by 1987rishabhjain** [microsoft/playwright#33543]
### Last Good Version

Playwright Version 1.34.0 and .NET 6

### First Bad Version

Playwright Version 1.34.0 and .NET 8

### Steps to reproduce

While upgrading Playwright solution from .NET 6.0 to .NET 8.0.  Test cases are breaking on GIT Hup Pipeline during all test cases execution. throwing timeout error. Few test cases are running successfully and after some time rest of  test cases are breaking with timeout error. Below is a error details 

Below is a 
  OneTimeSetUp: System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
Setup failed for test fixture XXXXX.XXX
System.NullReferenceException : Object reference not set to an instance of an object.
StackTrace:    at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 150
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserContext.NewPageAsync() in /_/src/Playwright/Core/BrowserContext.cs:line 341
   at Microsoft.Playwright.Core.Browser.<>c__DisplayClass31_0.<<NewPageAsync>b__0>d.MoveNext() in /_/src/Playwright/Core/Browser.cs:line 176
--- End of stack trace from previous location ---
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.Browser.NewPageAsync(BrowserNewPageOptions options) in /_/src/Playwright/Core/Browser.cs:line 174
   at XXX.E2E.UI.SetupWithLogin.HomepageWithAuthenticationAsync() in F:\actions-runner\_work\ccat-e2e-test\ccat-e2e-test\XXX.E2E.UI\SetupWithLogin.cs:line 40
   at XXX.E2E.UI.SetupWithLogin.HomepageWithAuthenticationAsync() in F:\actions-runner\_work\XXX\XXX-test\XXX.E2E.UI\SetupWithLogin.cs:line 55
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()

### Expected behavior

Code should run on GIT hub pipeline after .NET 6 to .NET 8 Migration

### Actual behavior

Test cases are failing on GIT HUB pipeline.

### Additional context

Upgraded code is not working on GIT hub pipeline

### Environment

```shell
System-
OS-WINDOW 10
Playwright Version-1.34.0
Upgraded from .NET Framework 6.0 to .NET Framework 8.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding! 

We strongly recommend latest Playwright when filing bugs against Playwright: https://www.nuget.org/packages/microsoft.playwright
