### ISSUE TITLE
[Bug]: debug mode in Playwrigt VSCode extension does not work

### ISSUE THREAD

**Issue by ngocdd** [microsoft/playwright#33582]
### Version

1.48.2

### Steps to reproduce

when I select any test and run debug I get the error as below:
/usr/local/opt/node@20/bin/node node_modules/@playwright/test/cli.js test-server -c playwright.config.ts
![Image](https://github.com/user-attachments/assets/5a717923-ce4d-46d4-8fcb-14795ce4163b)

### Expected behavior

The debug mode should run without any error

### Actual behavior
```
Exception has occurred: Error
  at FA (/Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:38:3570)
    at Function.statement (/Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:38:2830)
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:42:1082
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:1:222
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:66:1678
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:1:222
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:66:36005
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:1:222
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:66:38569
    at /Users/ngocdd/Documents/source_code/playwright-ts-full/node_modules/playwright/lib/transform/babelBundleImpl.js:1:222
```

### Environment

```shell
MacOS: 15.1 (Intel Based)
VSCode Version: Version: 1.95.2 (Universal)
Playwright: 1.48.2
Node: 20LTS
```

**Comment by pavelfeldman** [comment]
Please follow the BUG template to file something we can reproduce.
