### ISSUE TITLE
[Bug]: "Error ENOENT: no such file or directory, scandir '/…/firefox'" in `executablePath()`

### ISSUE THREAD

**Issue by MurakamiShinyu** [microsoft/playwright#33749]
### Version

1.49.0

### Steps to reproduce

Example code: pwtest.js

```js
import { registry } from 'playwright-core/lib/server';

for (const exe of registry.executables()) {
  console.log("--- " + exe.name + " ---");
  const exePath = exe.executablePath();
  console.log(exePath);
}
```

Example steps:
1. Run `npm install playwright-core`
2. Run `node pwtest.js`

### Expected behavior

No error occurs.

### Actual behavior

```
…
--- bidi-firefox-stable ---
node:fs:1502
  const result = binding.readdir(
                         ^

Error: ENOENT: no such file or directory, scandir '/Users/shinyu/pwtest/firefox'
    at Object.readdirSync (node:fs:1502:26)
    at executablePath (/Users/shinyu/pwtest/node_modules/playwright-core/lib/server/registry/index.js:688:36)
    at Object.executablePath (/Users/shinyu/pwtest/node_modules/playwright-core/lib/server/registry/index.js:702:38)
    at file:///Users/shinyu/pwtest/pwtest.js:5:23
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/shinyu/pwtest/firefox'
}
```

### Additional context

It seems that the problem was introduced in Playwright v1.48.0, with the change in the following pull request:

- https://github.com/microsoft/playwright/pull/32527

`fs.readdirSync(folder)` added in this PR causes the error if `folder` is not found.

### Environment

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1
    Memory: 108.47 MB / 16.00 GB
  Binaries:
    Node: 22.11.0 - ~/.n/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - ~/.n/bin/npm
    pnpm: 8.10.4 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.95.3 - /usr/local/bin/code
  Languages:
    Bash: 5.2.21 - /opt/homebrew/bin/bash
  npmPackages:
    playwright-core: ^1.49.0 => 1.49.0
```

**Comment by mxschmitt** [comment]
We don't consider playwright-core/lib/server a part of our public API - I recommend to use an alternative API which we consider stable. We tend to change internals and this would break you.

See https://playwright.dev/docs/api/class-playwright for our API documentation.
