### ISSUE TITLE
[Bug]: browser instance closes down when you throw an error in server request

### ISSUE THREAD

**Issue by AnzeKop** [microsoft/playwright#33872]
### Version

1.49.0

### Steps to reproduce

We have a fastify server where certain endpoints open up a headless browser to do some automation and for that we have this BrowserManager class that is resposible for having 1 persistant instance of the browser on the server that handles contextes.

```ts
import { Browser, BrowserContext, chromium } from "playwright";
import { browserConfig } from "./config";

export class BrowserManager {
  private static instance: BrowserManager;
  private browser!: Browser;
  private contexts: Map<
    string,
    {
      context: BrowserContext;
      lastUsed: number;
      isActive: boolean;
    }
  > = new Map();

  private readonly CONTEXT_CLEANUP_INTERVAL = 15 * 60 * 1000; // 15 minutes
  private readonly CONTEXT_MAX_IDLE_TIME = 15 * 60 * 1000; // 15 minutes

  private constructor() {
    console.log("BrowserManager constructor");
    // Start cleanup interval
    setInterval(() => this.cleanupIdleContexts(), this.CONTEXT_CLEANUP_INTERVAL);
  }

  public async init() {
    console.log("Initializing BrowserManager");
    this.browser = await chromium.launch(browserConfig);
  }

  public static async getInstance(): Promise<BrowserManager> {
    if (!BrowserManager.instance) {
      BrowserManager.instance = new BrowserManager();
      await BrowserManager.instance.init();
    }
    return BrowserManager.instance;
  }

  private async ensureBrowser(): Promise<Browser> {
    if (!this.browser) {
      throw new Error("Browser not initialized");
    }
    return this.browser;
  }

  async createContext(id: string): Promise<BrowserContext> {
    const browser = await this.ensureBrowser();
    console.log("Creating context", id);
    const context = await browser.newContext();

    this.contexts.set(id, {
      context,
      lastUsed: Date.now(),
      isActive: true,
    });

    return context;
  }

  async getContext(id: string): Promise<BrowserContext> {
    const existing = this.contexts.get(id);
    if (existing && existing.isActive) {
      existing.lastUsed = Date.now();
      return existing.context;
    }
    return this.createContext(id);
  }

  async releaseContext(id: string) {
    console.log("Releasing context", id);
    const contextData = this.contexts.get(id);
    if (contextData) {
      contextData.isActive = false;
      contextData.lastUsed = Date.now();
    }
  }

  private async cleanupIdleContexts() {
    console.log("Cleaning up idle contexts");
    const now = Date.now();

    for (const [id, { context, lastUsed, isActive }] of this.contexts.entries()) {
      if (!isActive && now - lastUsed > this.CONTEXT_MAX_IDLE_TIME) {
        await context.close();
        this.contexts.delete(id);
      }
    }
  }

  async shutdown() {
    console.log("Shutting down BrowserManager");
    // Close all contexts
    for (const { context } of this.contexts.values()) {
      await context.close();
    }
    this.contexts.clear();

    // // Close browser
    // if (this.browser) {
    //   await this.browser.close();
    // }
  }
}

export async function getBrowserManager(): Promise<BrowserManager> {
  return await BrowserManager.getInstance();
}

```

On the surfice this seems fine but in some cases we have expected errors thrown in the app that stop the automation which is ok, the problem then comes that on the next request we get this error saying that:

"Target page, context or browser has been closed"

```plaintext
Browser logs:

<launching> /Users/anze/Library/Caches/ms-playwright/chromium_headless_shell-1148/chrome-mac/headless_shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,ThirdPartyStoragePartitioning,LensOverlay,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --enable-use-zoom-for-dsf=false --use-angle --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-gpu --disable-dev-shm-usage --disable-software-rasterizer --disable-extensions --no-sandbox --single-process --user-data-dir=/var/folders/zb/hgzc5jv96xg8sjcm44y344yw0000gn/T/playwright_chromiumdev_profile-W8Cz0p9tkW8s --remote-debugging-pipe --no-startup-window
<launched> pid=13433
[pid=13433][err] [1204/140344.549627:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
[pid=13433][err] [1204/140344.575595:ERROR:cv_display_link_mac.mm(165)] CVDisplayLinkCreateWithCGDisplay failed. CVReturn: -6670
```

and we need to forcibly recreate the this.browser with a new chromium.launch() call even though the if(this.browser) check passes.

To reproduce this try creating an express/fastify server where you throw an error while having the browser open and then try making a 2nd call

### Expected behavior

The browser is persistant on the server and can manage contextes independatiy without the need to reinitialize the browser on each call

### Actual behavior

Described above

### Environment

```shell
Linux and Mac, node 20
```

**Comment by Skn0tt** [comment]
Hi! There's a lot of non-Playwright stuff in this report, that we'd prefer to not debug. Could you provide a self-contained minimal reproduction, which we can run locally to reproduce your issue. And please elaborate on what you think Playwright is doing wrong. Thanks!

**Comment by AnzeKop** [comment]
@Skn0tt made it here, you can reproduce this by starting the server with tsx and then trying to do multiple requests

https://github.com/AnzeKop/playwright-issue-33872

you will see this error

```plaintext
TargetClosedError: Target page, context or browser has been closed
    at FrameSession.dispose (/Users/anze/Documents/Work/Clients/Dietier/tvva-test/node_modules/playwright-core/lib/server/chromium/crPage.js:497:52)
    at CRPage.didClose (/Users/anze/Documents/Work/Clients/Dietier/tvva-test/node_modules/playwright-core/lib/server/chromium/crPage.js:162:60)
    at CRBrowser._didDisconnect (/Users/anze/Documents/Work/Clients/Dietier/tvva-test/node_modules/playwright-core/lib/server/chromium/crBrowser.js:218:57)
    at CRConnection.<anonymous> (/Users/anze/Documents/Work/Clients/Dietier/tvva-test/node_modules/playwright-core/lib/server/chromium/crBrowser.js:95:81)
    at CRConnection.emit (node:events:519:28)
    at /Users/anze/Documents/Work/Clients/Dietier/tvva-test/node_modules/playwright-core/lib/server/chromium/crConnection.js:81:39

```

**Comment by Skn0tt** [comment]
`--single-process` is causing it. Custom browser args are not supported, see https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-args.
