### ISSUE TITLE
[Bug]: Page crashes occassionaly mid test run

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#33881]
### Version

1.49.0

### Steps to reproduce

Unfortunately, i don't have a sure reproduce scenario, occasionally, in different test types, we've receiving 'page' crash.
I've turned on `DEBUG=pw:browser` and attaching the results below, I would appreciate if you could have a look and might help me take a step towards the root cause.

**Attached logs from 2 different tests below**
**Printed `npx envinfo --preset playwright` from the CI machine that runs the test**

### Expected behavior

Page keep alive till end of test

### Actual behavior

Page crash mid test

### Test 1:
```
  pw:browser <launching> /ms-playwright/ffmpeg-1010/ffmpeg-linux -loglevel error -f image2pipe -avioflags direct -fpsprobesize 0 -probesize 32 -analyzeduration 0 -c:v mjpeg -i pipe:0 -y -an -r 25 -c:v vp8 -qmin 0 -qmax 50 -crf 8 -deadline realtime -speed 8 -b:v 1M -threads 1 -vf pad=800:450:0:0:gray,crop=800:450:0:0 /codefresh/volume/playwright/test-results/.playwright-artifacts-2/90a3f8a82e58dcf574e7f8509ab91e49.webm +2s
  pw:browser <launched> pid=921 +12ms
  pw:browser [pid=99][err] [1205/101044.706738:INFO:peer_connection_dependency_factory.cc(744)] Running WebRTC with a combined Network and Worker thread. +3s
  pw:browser [pid=99][err] [1205/101044.793793:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0601D004C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +87ms
  pw:browser [pid=99][err] [1205/101044.802823:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0901D004C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +9ms
  pw:browser [pid=99][err] [1205/101045.439847:ERROR:web_contents_delegate.cc(283)] WebContentsDelegate::CheckMediaAccessPermission: Not supported. +640ms
  pw:browser [pid=99][err] [1205/101045.439873:ERROR:web_contents_delegate.cc(283)] WebContentsDelegate::CheckMediaAccessPermission: Not supported. +0ms
  pw:browser [pid=99][err] [1205/101045.854620:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0C032014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +414ms
  pw:browser [pid=99][err] [1205/101045.869416:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0F032014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +13ms
  pw:browser [pid=99][err] [1205/101045.929281:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A02033014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +59ms
  pw:browser [pid=99][err] [1205/101045.982781:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A05033014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +54ms
  pw:browser [pid=99][err] [1205/101046.055783:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0801E014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +73ms
  pw:browser [pid=99][err] [1205/101046.199815:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0B01E014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +144ms
  pw:browser [pid=99][err] [1205/101046.239745:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0E01E014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +40ms
  pw:browser [pid=99][err] [1205/101046.296755:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A05033014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +57ms
  pw:browser [pid=99][err] [1205/101046.337985:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0901D004C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +41ms
  pw:browser [pid=99][err] [1205/101046.401929:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0601D004C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +64ms
  pw:browser [pid=99][err] [1205/101046.502216:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0C032014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +100ms
  pw:browser [pid=99][err] [1205/101046.590636:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A02033014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +88ms
  pw:browser [pid=99][err] [1205/101046.635396:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0801E014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +45ms
  pw:browser [pid=99][err] [1205/101046.710320:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0101F014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +75ms
  pw:browser [pid=99][err] [1205/101046.782258:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A000F1014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +72ms
  pw:browser [pid=99][err] [1205/101046.816886:ERROR:gles2_cmd_decoder_passthrough.cc(933)] ContextResult::kFatalFailure: fail_if_major_perf_caveat + swiftshader +35ms
  pw:browser [pid=99][err] [1205/101047.160226:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A030F1014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +343ms
  pw:browser [pid=99][err] [1205/101047.310564:ERROR:socket_manager.cc(147)] Failed to resolve address for ec2-52-23-111-175.compute-1.amazonaws.com., errorcode: -105 +150ms
  pw:browser [pid=99][err] [1205/101047.541618:WARNING:stun_port.cc(442)] Port[8c5d000:0:1:0:host:Net[any:0:0:0:x:x:x:x:x/0:Wildcard:id=0]]: StunPort: stun host lookup received error -1 +231ms
  pw:browser [pid=99][err] [1205/101048.026972:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0F032014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +490ms
  pw:browser [pid=99][err] [1205/101049.707657:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A060F1014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +2s
  pw:browser [pid=99][err] [1205/101049.712872:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A090F1014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +6ms
  pw:browser [pid=99][err] [1205/101049.727072:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0C003014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +15ms
  pw:browser [pid=99][err] [1205/101049.775102:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0F003014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +47ms
  pw:browser [pid=99][err] [1205/101049.800492:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A02004014C0D0000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +25ms
  pw:browser [pid=99][err] [1205/101051.276274:ERROR:render_process_host_impl.cc(5499)] Terminating render process for bad Mojo message: Received bad user message: Unexpected request: Interest groups may only be joined or left when feature join-ad-interest-group is enabled by Permissions Policy +1s
  pw:browser [pid=99][err] [1205/101051.276321:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 123 +1ms
  pw:browser [pid=99][err] [1205/101051.375792:WARNING:sync_reader.cc(199)] SyncReader::Read timed out, audio glitch count=10 +98ms
  pw:browser [pid=99][err] [1205/101051.377271:WARNING:sync_reader.cc(176)] ASR: No room in socket buffer.: Broken pipe (32) +1ms
  pw:browser [pid=921] <gracefully close start> +884ms
  pw:browser Closing stdin... +0ms
  pw:browser ffmpeg finished input. +0ms
  pw:browser [pid=921] <process did exit: exitCode=0, signal=null> +72ms
  pw:browser ffmpeg onkill exitCode=0 signal=null +0ms
  pw:browser [pid=921] starting temporary directories cleanup +0ms
  pw:browser [pid=921] finished temporary directories cleanup +0ms
  pw:browser [pid=921] <gracefully close end> +0ms
  pw:browser [pid=99] <gracefully close start> +23ms
  pw:browser [pid=99] <process did exit: exitCode=0, signal=null> +35ms
  pw:browser [pid=99] starting temporary directories cleanup +1ms
  pw:browser [pid=99] finished temporary directories cleanup +5ms
  pw:browser [pid=99] <gracefully close end> +0ms

```

### Test 2:
```
  pw:browser <launching> /ms-playwright/ffmpeg-1010/ffmpeg-linux -loglevel error -f image2pipe -avioflags direct -fpsprobesize 0 -probesize 32 -analyzeduration 0 -c:v mjpeg -i pipe:0 -y -an -r 25 -c:v vp8 -qmin 0 -qmax 50 -crf 8 -deadline realtime -speed 8 -b:v 1M -threads 1 -vf pad=800:450:0:0:gray,crop=800:450:0:0 /codefresh/volume/playwright/test-results/.playwright-artifacts-0/972efce4eabfd61ab9c0d7d22245e557.webm +110ms
  pw:browser <launched> pid=559 +4ms
  pw:browser [pid=97][err] [1205/101753.290854:INFO:peer_connection_dependency_factory.cc(744)] Running WebRTC with a combined Network and Worker thread. +1s
  pw:browser [pid=97][err] [1205/101753.317176:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0601D0034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +26ms
  pw:browser [pid=97][err] [1205/101753.326030:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0901D0034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +9ms
  pw:browser [pid=97][err] [1205/101753.388373:ERROR:web_contents_delegate.cc(283)] WebContentsDelegate::CheckMediaAccessPermission: Not supported. +62ms
  pw:browser [pid=97][err] [1205/101753.388392:ERROR:web_contents_delegate.cc(283)] WebContentsDelegate::CheckMediaAccessPermission: Not supported. +0ms
  pw:browser [pid=97][err] [1205/101753.405088:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A040E20034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +17ms
  pw:browser [pid=97][err] [1205/101753.424896:ERROR:gles2_cmd_decoder_passthrough.cc(933)] ContextResult::kFatalFailure: fail_if_major_perf_caveat + swiftshader +20ms
  pw:browser [pid=97][err] [1205/101753.426954:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A070E20034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +2ms
  pw:browser [pid=97][err] [1205/101753.550126:ERROR:socket_manager.cc(147)] Failed to resolve address for ec2-52-23-111-175.compute-1.amazonaws.com., errorcode: -105 +123ms
  pw:browser [pid=97][err] [1205/101753.572673:WARNING:stun_port.cc(442)] Port[44fb000:0:1:0:host:Net[any:0:0:0:x:x:x:x:x/0:Wildcard:id=0]]: StunPort: stun host lookup received error -1 +23ms
  pw:browser [pid=97][err] [1205/101753.843289:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A040E20034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +270ms
  pw:browser [pid=97][err] [1205/101753.851707:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A040E20034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +9ms
  pw:browser [pid=97][err] [1205/101753.860126:ERROR:gl_utils.cc(426)] [.WebGL-0x2ef4000cd500]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels +8ms
  pw:browser [pid=97][err] [1205/101753.883146:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A040E20034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +23ms
  pw:browser [pid=97][err] [1205/101753.889360:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A040E20034140000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content. +6ms
  pw:browser [pid=97][err] [1205/101759.088523:ERROR:render_process_host_impl.cc(5499)] Terminating render process for bad Mojo message: Received bad user message: Unexpected request: Interest groups may only be joined or left when feature join-ad-interest-group is enabled by Permissions Policy +5s
  pw:browser [pid=97][err] [1205/101759.088551:ERROR:bad_message.cc(29)] Terminating renderer for bad IPC message, reason 123 +0ms
  pw:browser [pid=97][err] [1205/101759.154722:WARNING:sync_reader.cc(176)] ASR: No room in socket buffer.: Broken pipe (32) +67ms
waitForURL failed: page.waitForURL: Navigation failed because page crashed!
=========================== logs ===========================
waiting for navigation to "/app/welcome" until "load"
============================================================
    at /codefresh/volume/playwright/test/specs/signup/signupUtmTest.spec.ts:61:28 {
  [Symbol(step)]: {
    stepId: 'pw:api@28',
    location: {
      file: '/codefresh/volume/playwright/test/specs/signup/signupUtmTest.spec.ts',
      line: 61,
      column: 28,
      function: undefined
    },
    category: 'pw:api',
    title: 'page.waitForURL',
    apiName: 'page.waitForURL',
    params: { info: [Object] },
    boxedStack: undefined,
    steps: [],
    complete: [Function: complete],
    endWallTime: 1733422679194,
    error: {
      message: 'Error: page.waitForURL: Navigation failed because page crashed!\n' +
        '=========================== logs ===========================\n' +
        'waiting for navigation to "/app/welcome" until "load"\n' +
        '============================================================',
      stack: 'Error: page.waitForURL: Navigation failed because page crashed!\n' +
        '=========================== logs ===========================\n' +
        'waiting for navigation to "/app/welcome" until "load"\n' +
        '============================================================\n' +
        '    at /codefresh/volume/playwright/test/specs/signup/signupUtmTest.spec.ts:61:28',
      cause: undefined
    }
  }
}
```

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (32) x64 AMD EPYC 7R13 Processor
    Memory: 55.18 GB / 61.53 GB
    Container: Yes
  Binaries:
    Node: 22.11.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.9.0 - /usr/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
```

**Comment by Skn0tt** [comment]
The error message "Terminating render process for bad Mojo message: Received bad user message: Unexpected request: Interest groups may only be joined or left when feature join-ad-interest-group is enabled by Permissions Policy" seems to be the core here. Looks like that was recently added to Chromium: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/interest_group/ad_auction_service_impl.cc;l=854-856?q=join-ad-interest-group&ss=chromium%2Fchromium%2Fsrc

**Comment by mxschmitt** [comment]
@ValorHeart would it be possible to share a reproducible with us? The logs are already helpful! Does it happen all the time or just sometimes? I filed it in the meantime as https://issues.chromium.org/u/1/issues/382786767.

**Comment by ValorHeart** [comment]
Hi @mxschmitt, The issue happens at about 1 out of 5 test runs but is inconsistent.
Unfortunately, I couldn't create a reproducible project; our tests run behind a firewall, and I couldn't find another web app that reproduced the issue.
If there are more debug flags to open, I'll be happy to do so.

Thanks!

**Comment by mxschmitt** [comment]
This has been fixed upstream - should be in upstream Chrome Canary soon and takes around 1-2 months to be in Playwright. I'll close it by that since its not actionable by us anymore.
