### ISSUE TITLE
[Bug]: Status code 404 gives net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by D4Vinci** [microsoft/playwright#33962]
### Version

1.49.1

### Steps to reproduce

Example steps (replace with your own):
1. save this code as a script and run it
```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    res = page.goto('http://httpbin.org/status/404')
    html = page.content()
    page.close()
```
2. Run the script and it will crash once it reaches the page.

### Expected behavior

I expect to get a response with error code 404 as before the last update

### Actual behavior

I get this error:
```
Traceback (most recent call last):
  File "/Users/karim/rebrowser.py", line 7, in <module>
    res = page.goto('http://httpbin.org/status/404')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karim/.venv/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 9006, in goto
    self._sync(
  File "/Users/karim/.venv/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/karim/.venv/lib/python3.12/site-packages/playwright/_impl/_page.py", line 551, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karim/.venv/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/karim/.venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karim/.venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_HTTP_RESPONSE_CODE_FAILURE at http://httpbin.org/status/404
Call log:
  - navigating to "http://httpbin.org/status/404", waiting until "load"
```

### Additional context

This happens only with pages that give the error 404 without an HTML response. It didn't happen before 1.49; I just noticed it because I use httpbin in my unit tests.

### Environment

```Text
- Operating System: MacOS 15.1.1
- CPU: M1
- Browser: Chromium
- Python Version: 3.12.7
```

**Comment by yury-s** [comment]
This only reproduces in Chrome headed and it is consistent with the headed browser behavior where 404 page without content is displayed as a network error. Headless and other browsers don't have this issue.

**Comment by D4Vinci** [comment]
@yury-s If I don't specify the browser channel then it happens with headful only but if I specify the channel to `chromium` or `chrome` then it happens in both headless/headfull

**Comment by D4Vinci** [comment]
Any updates about this?

**Comment by D4Vinci** [comment]
Hi @yury-s any updates about this?

**Comment by denizkenan** [comment]
> Hi [@yury-s](https://github.com/yury-s) any updates about this?

Sorry, you are left out. Just catch the error and handle it yourself. page object is still live so you can recover from this.

**Comment by D4Vinci** [comment]
> > Hi [@yury-s](https://github.com/yury-s) any updates about this?
> 
> Sorry, you are left out. Just catch the error and handle it yourself. page object is still live so you can recover from this.

Sorry what? And how can I know if this is a legitimate error or because playwright crashes like this!?

**Comment by denizkenan** [comment]
look. let's be honest it sucks. but directing your anger to me is not gonna solve your problem.

Catch the error. then do:
```python
status_code = browser.evaluate("window.performance.getEntries()[0].responseStatus")
```
and get underlying status code and that would be it.

I don't maintain this. I am trying to help instead of mocking your skill issues. How does it feel?

**Comment by D4Vinci** [comment]
> look. let's be honest it sucks. but directing your anger to me is not gonna solve your problem.
> 
> Catch the error. then do:
> ```python
> status_code = browser.evaluate("window.performance.getEntries()[0].responseStatus")
> ```
> and get underlying status code and that would be it.
> 
> I don't maintain this. I am trying to help instead of mocking your skill issues. How does it feel?

Sorry mate, I thought you are one of the maintainers, I don't know who work on this. Your solution looks neat I will try it. Thanks for looking into it.

Sorry again

**Comment by denizkenan** [comment]
No worries mate, all good. I hope it helps.

**Comment by yury-s** [comment]
> And how can I know if this is a legitimate error or because playwright crashes like this!?

You can check if the error message starts with "error Page.goto: net::ERR_HTTP_RESPONSE_CODE_FAILURE at http://httpbin.org/status/404". You can also listen to "requestfailed" events and see if they are main frame navigation events by checking `request.frame` and `request.resource_type` prorperties, but that's likely an overkill for your scenario.

> Any updates about this?

Chromium likes to fail on empty response, e.g. see https://issues.chromium.org/u/1/issues/371021302. Given that this is an edge case and it aligns with headed behavior, this behavior is unlikely to change.

**Comment by D4Vinci** [comment]
Thanks @yury-s

**Comment by stevenh** [comment]
Updated and just started to see this behaviour meaning it fails a bunch of tests.

How come this isn't considered a regression? In our case it was a 429, no reason it should throw an exception instead of returning the status code?

**Comment by stevenh** [comment]
I tried the workaround suggested but it seemed unreliable, due to timing:
```python
status_code = browser.evaluate("window.performance.getEntries()[0].responseStatus")
```

What seemed to work well for me is setting the Page on response handler:
```python
async def on_response(self, response: Response) -> None:
      """Store the response so its available for exception handling."""
      self._response = response

page.on("response", on_response)
```

**Comment by D4Vinci** [comment]
> I tried the workaround suggested but it seemed unreliable, due to timing:
> 
> status_code = browser.evaluate("window.performance.getEntries()[0].responseStatus")
> What seemed to work well for me is setting the Page on response handler:
> 
> async def on_response(self, response: Response) -> None:
>       """Store the response so its available for ."""
>       self._response = response
> 
> page.on("response", on_response)

That's a nice idea. I stopped testing for 404 to avoid this crash.
