### ISSUE TITLE
[BUG] Chromium doesn't work in the playwright:bionic Docker image

### ISSUE THREAD

**Issue by MrDiggles2** [microsoft/playwright#3607]
**Context:**
- Playwright Version: 1.3.0
- Operating System: Linux (CentOS 7)
- Node.js version: 12.18.3
- Browser: Chromium
- Extra: Docker version 19.03.11

**Code Snippet**

```
$> wget https://raw.githubusercontent.com/microsoft/playwright/master/docs/docker/seccomp_profile.json
$> docker run -it --rm --security-opt seccomp=./seccomp_profile.json mcr.microsoft.com/playwright:bionic bash
pwuser@0144135bbdad:/$ cd ~
pwuser@0144135bbdad:~$ npm i playwright

> playwright@1.3.0 install /home/pwuser/node_modules/playwright
> node install.js

Failed to process descriptor at /home/pwuser/tmp/node_modules/playwright
npm WARN saveError ENOENT: no such file or directory, open '/home/pwuser/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pwuser/package.json'
npm WARN pwuser No description
npm WARN pwuser No repository field.
npm WARN pwuser No README data
npm WARN pwuser No license field.

+ playwright@1.3.0
added 34 packages from 79 contributors and audited 34 packages in 2.149s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

pwuser@0144135bbdad:~$ node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> require("playwright").chromium.launch().then(console.log)
Promise { <pending> }
> (node:42) UnhandledPromiseRejectionWarning: browserType.launch: Chromium sandboxing failed!
================================
To workaround sandboxing issues, do either of the following:
  - (preferred): Configure environment to support sandboxing: https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md
  - (alternative): Launch Chromium without sandbox using 'chromiumSandbox: false' option
================================
Error
    at /home/pwuser/node_modules/playwright/lib/chromium/crConnection.js:131:63
    at new Promise (<anonymous>)
    at CRSession.send (/home/pwuser/node_modules/playwright/lib/chromium/crConnection.js:130:16)
    at CRSession.send (/home/pwuser/node_modules/playwright/lib/helper.js:80:31)
    at Function.connect (/home/pwuser/node_modules/playwright/lib/chromium/crBrowser.js:55:39)
    at Chromium._connectToTransport (/home/pwuser/node_modules/playwright/lib/server/chromium.js:53:38)
    at Chromium._innerLaunch (/home/pwuser/node_modules/playwright/lib/server/browserType.js:90:36)
    at async ProgressController.run (/home/pwuser/node_modules/playwright/lib/progress.js:75:28)
    at async Chromium.launch (/home/pwuser/node_modules/playwright/lib/server/browserType.js:62:25)
(node:42) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:42) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Describe the bug**

I am running playwright through Docker using the recommended settings but Chromium doesn't seem to work. I keep getting an "unable to sandbox" error. Webkit and Firefox are working as expected.

I have also tried this with the 1.2.1 version and am getting the same result.

**Comment by MrDiggles2** [comment]
For now, I am working around this by using the top-level "chromiumSandbox: false" option.

**Comment by mxschmitt** [comment]
In Docker when you are using the root user you have to use the `chromiumSandbox: false` option in the launch options.

**Comment by MrDiggles2** [comment]
@mxschmitt - In the example I provided above, node is being run as `pwuser`, the user that comes shipped with the Docker image.

Can you only run Chromium in the Docker image with the `chromiumSandbox: false` option?

**Comment by mxschmitt** [comment]
Yep as far as I know the Chromium sandbox is not available in the Docker container. Alternatively you can use this setup to use it with sandbox support: https://github.com/microsoft/playwright/tree/master/docs/docker#run-the-image

We might should add that to the docs.

**Comment by MrDiggles2** [comment]
I've run the image with the seccomp profile provided on that page and I still run into the same issue.
