### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createHandle'/'childframes' of undefined

### ISSUE THREAD

**Issue by BennyPayn** [microsoft/playwright#3692]
**Context:**
- Playwright Version: v1.3.0
- Operating System: Linux 5.4 Ubuntu 20.04.1 LTS
- Node.js version: 10.19
- Browser: Firefox

**Code Snippet**
I have no way to reproducing this.

**Describe the bug**
It throws this error every randomly, sometimes my scripts works perfectly fine on some runs, and on other runs it throws this error. I do not have a single script that consistently throws this error on every run. Even though I get these errors, most of time, the execution of the script does not stop. It only messes up some infinite loop scripts when the error skips all the other lines in the loop and goes back to the start of the loop, which kind of messes up the script. I have no idea what causes this because I have tried to use try{} catch(e){console.log(e)} on multiple scripts and I redirected all of the logs into a text file using node test.js > test.txt. The logs worked fine, but I was still getting these errors on the console instead of the text file.

Errors:
```
(node:14846) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'childFrames' of undefined
    at FrameManager.removeChildFramesRecursively (/home/main/Desktop/test/node_modules/playwright/lib/frames.js:214:35)
    at FrameManager.frameCommittedNewDocumentNavigation (/home/main/Desktop/test/node_modules/playwright/lib/frames.js:121:14)
    at FFPage._onNavigationCommitted (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffPage.js:128:34)
    at FFSession.emit (events.js:198:13)
    at Promise.resolve.then (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffConnection.js:158:47)
(node:14846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:14846) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createHandle' of undefined
    at _page._addConsoleMessage.args.map.arg (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffPage.js:155:69)
    at Array.map (<anonymous>)
    at FFPage._onConsole (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffPage.js:155:50)
    at FFSession.emit (events.js:198:13)
    at Promise.resolve.then (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffConnection.js:158:47)
(node:14846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14846) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createHandle' of undefined
    at _page._addConsoleMessage.args.map.arg (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffPage.js:155:69)
    at Array.map (<anonymous>)
    at FFPage._onConsole (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffPage.js:155:50)
    at FFSession.emit (events.js:198:13)
    at Promise.resolve.then (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffConnection.js:158:47)
(node:14846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14846) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createHandle' of undefined
    at _page._addConsoleMessage.args.map.arg (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffPage.js:155:69)
    at Array.map (<anonymous>)
    at FFPage._onConsole (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffPage.js:155:50)
    at FFSession.emit (events.js:198:13)
    at Promise.resolve.then (/home/main/Desktop/test/node_modules/playwright/lib/firefox/ffConnection.js:158:47)
(node:14846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by yuis-ice** [comment]
same here.

**Comment by arjun27** [comment]
Thanks for the report! Might be related to with #3086 (cc @JoelEinbinder and @dgozman) - although this is Firefox. @yuis-ice - are you also seeing this in Firefox? @BennyPayn - Would it be worth trying with Playwright v1.4.1?

**Comment by dgozman** [comment]
@BennyPayn do you have a page url that triggers this issue? That would be much appreciated.

@aslushnikov FYI, something is wrong with Firefox frames sometimes.

**Comment by pavelfeldman** [comment]
Closing since iframes were reimplemented in FF.

**Comment by ingvar-nikiforov** [comment]
@pavelfeldman I have the same issue with Chromium.
* Playwright Version: v1.5.1
* Operating System: Mac OS 10.15.7
* Node.js version: 14.12.0
* Browser: Chromium

```
(node:18997) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'childFrames' of undefined
    at FrameManager.removeChildFramesRecursively (/Users/scoutgaming/Projects/e2e-tests/node_modules/playwright/lib/server/frames.js:229:35)
    at FrameManager.frameCommittedNewDocumentNavigation (/Users/scoutgaming/Projects/e2e-tests/node_modules/playwright/lib/server/frames.js:117:14)
    at FrameSession._onFrameNavigated (/Users/scoutgaming/Projects/e2e-tests/node_modules/playwright/lib/server/chromium/crPage.js:444:34)
    at CRSession.<anonymous> (/Users/scoutgaming/Projects/e2e-tests/node_modules/playwright/lib/server/chromium/crPage.js:288:97)
    at CRSession.emit (events.js:314:20)
    at /Users/scoutgaming/Projects/e2e-tests/node_modules/playwright/lib/server/chromium/crConnection.js:151:22
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
```

The page I am working with is the inbox page on temporary email service https://www.mailforspam.co/ .
I am loading the page in a loop until I see 2 emails in the inbox.

Here is quick code snippet from my codebase. 
```javascript
const sleep = async ms => new Promise(resolve => setTimeout(resolve, ms))

const retryUntilTimeout = async ({ func, timeout, delay }) => {
  timeout = timeout || 500
  delay = delay || 250

  const startTime = new Date()
  const timedOut = () => timeout - (new Date() - startTime) <= 0

  while (true) {
    try {
      const result = await func()
      return result
    } catch (err) {
      if (timedOut()) {
        throw err
      }
    }

    await sleep(delay)
  }
}

// example url
// const url = 'https://www.mailforspam.com/mail/reegeagi'
await retryUntilTimeout({
  func: async () => {
    await emailProvider.openAccountPage() // uses page.goto() method

    const listOfEmails = await emailProvider.getListOfEmails()

    assert.equal(await listOfEmails.getItemsCount(), 2, 'emails count')
  },
  timeout: 20_000
})
```

Let me know if you need a separate ticket and fully working code.
