### ISSUE TITLE
[Question] why getVideoPlaybackQuality function returns undefined for HTMLVideoElement?

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#3789]
Hi, I'm trying to check in my test that video is playing.
I decided to call [getVideoPlaybackQuality](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/getVideoPlaybackQuality) function and get [totalVideoFrames](https://developer.mozilla.org/en-US/docs/Web/API/VideoPlaybackQuality/totalVideoFrames) from VideoPlaybackQuality object.

My code is:
```javascript
const videoStreamSelector = '//sd-webcam-player/sd-video-stream';
await adminPage.waitForSelector(videoStreamSelector);
const videoStream = await adminPage.$(videoStreamSelector);

const width = await videoStream.$eval('video', (node) => (node as HTMLVideoElement).videoWidth);
const quality = await videoStream.$eval(
    'video',
    (node) => (node as HTMLVideoElement).getVideoPlaybackQuality
);

console.log(JSON.stringify(width));
console.log(JSON.stringify(quality));
```

The result is:
```
pw:api waiting for selector "//sd-webcam-player/sd-video-stream" to be visible [] +1ms
pw:api   selector resolved to visible <sd-video-stream muted="true" class="ng-isolate-scope" stream="$c…>…</sd-video-stream> [] +19ms
pw:api <= page.waitForSelector succeeded +18ms
640
undefined
```
So there is result for videoWidth property and no result for getVideoPlaybackQuality function.

I'm using Firefox with 
```javascript
"media.navigator.streams.fake": true,
"media.navigator.permission.disabled": true,
"media.gstreamer.enabled": false,
"media.mediasource.enabled": true,
```
What I'm doing wrong? Why the result is undefined?
Can I maybe use another approach for this check?

Thanks!

Version:
"playwright": "^1.3.0"

**Comment by pavelfeldman** [comment]
Did you try calling it in DevTools? Also, in the snippet you don't call the function, you return it instead.

**Comment by viraxslot** [comment]
@pavelfeldman Thanks for the quick response. In DevTools@Firefox works fine:
```javascript
let videoTag = $x('//sd-webcam-player/sd-video-stream/video')[0]
undefined
videoTag.videoWidth
640
videoTag.getVideoPlaybackQuality()
VideoPlaybackQuality {creationTime: 237927.68500000238, totalVideoFrames: 5160, droppedVideoFrames: 1495, corruptedVideoFrames: 0}
corruptedVideoFrames: 0
creationTime: 237927.68500000238
droppedVideoFrames: 1495
totalVideoFrames: 5160
__proto__: VideoPlaybackQuality
```

I didn't call function getVideoPlaybackQuality because of [this example](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=elementhandleevalselector-pagefunction-arg). But now I realize that "innerText" is a property in that context.

If I call the function
```javascript
const width = await videoStream.$eval('video', (node) => (node as HTMLVideoElement).videoWidth);
const quality = await videoStream.$eval('video', (node) =>
    (node as HTMLVideoElement).getVideoPlaybackQuality()
);
```
then the result is:

```
  pw:api waiting for selector "//sd-webcam-player/sd-video-stream" to be visible [] +1ms
  pw:api   selector resolved to visible <sd-video-stream muted="true" class="ng-isolate-scope" stream="$c…>…</sd-video-stream> [] +11ms
  pw:api <= page.waitForSelector succeeded +26ms
640
{}
```

**Comment by viraxslot** [comment]
Example with available resource:
```javascript
 it('video test', async function () {
    const leftVideo = '#leftVideo';
    await page.goto('https://webrtc.github.io/samples/src/content/capture/video-video/');
    await page.waitForSelector('text=WebRTC samples');
    await page.click(leftVideo);

    const video = await page.$(leftVideo);
    const width = await video.evaluate((node) => (node as HTMLVideoElement).videoWidth);
    const quality = await video.evaluate((node) => (node as HTMLVideoElement).getVideoPlaybackQuality());
    console.log(width);
    console.log(quality);
});
```

Result
```
  pw:api waiting for selector "#leftVideo" [] +0ms
  pw:api   selector resolved to visible <video loop="" muted="" controls="" id="leftVideo" play…>…</video> [] +21ms
  pw:api attempting click action [] +9ms
  pw:api   waiting for element to be visible, enabled and not moving [] +1ms
  pw:api   element is visible, enabled and does not move [] +30ms
  pw:api   scrolling into view if needed [] +0ms
  pw:api   done scrolling [] +2ms
  pw:api   checking that element receives pointer events at (389,236.03) [] +3ms
  pw:api   element does receive pointer events [] +4ms
  pw:api   performing click action [] +0ms
  pw:api   click action done [] +17ms
  pw:api   waiting for scheduled navigations to finish [] +0ms
  pw:api   navigations have finished [] +0ms
  pw:api <= page.click succeeded +1ms
480
{}
    ✓ video test (2322ms)
```

**Comment by dgozman** [comment]
This is because `VideoPlaybackQuality` is not a regular JavaScript object. Try the following in Developer Tools:

```js
const x = {... videoTag.getVideoPlaybackQuality() };
const y = JSON.stringify(videoTag.getVideoPlaybackQuality());
const z = Object.keys(videoTag.getVideoPlaybackQuality());
```

The only way I've found to access all the properties is the `in` operator. We are not using this currently.
```js
for (const key in videoTag.getVideoPlaybackQuality())
  console.log(key);
```

**Comment by viraxslot** [comment]
@dgozman sorry, but I still don't understand how to get the values in code. I think I tried all the variants :)
I succeed with the same task in cypress thank to [this comment](https://github.com/cypress-io/cypress/issues/8519#issuecomment-688854185).

Could you please give me the similar example? I used _.pick here but with no result.

**Comment by viraxslot** [comment]
@dgozman ok, got it :) this example works fine:
```javascript
const quality = await video.evaluate(function (node) {
    const res = (node as HTMLVideoElement).getVideoPlaybackQuality();
    return {
        creationTime: res?.creationTime,
        totalVideoFrames: res?.totalVideoFrames,
        droppedVideoFrames: res?.droppedVideoFrames,
    };
});
```
lodash.pick() doesn't work inside the evaluate function.
```
Error: Evaluation failed: lodash_1 is not defined
@__playwright_evaluation_script__56:3:13
callFunction@__playwright_evaluation_script__19:305:28
@__playwright_evaluation_script__57:1:44
at checkException (node_modules/playwright/lib/firefox/ffExecutionContext.js:86:15)
at FFExecutionContext.evaluateWithArguments (node_modules/playwright/lib/firefox/ffExecutionContext.js:49:9)
at evaluateExpression (node_modules/playwright/lib/javascript.js:164:16)
at Context.<anonymous> (test/rep/test.spec.ts:13:25)
-- ASYNC --
at ElementHandle.evaluate (node_modules/playwright/lib/helper.js:79:23)
at Context.<anonymous> (test/rep/test.spec.ts:13:37)
```

**Comment by dgozman** [comment]
@viraxslot The snippet you posted is how I would do it 😄 
lodash will work as long as the page already uses it. However, if you reference lodash from the function passed to `evaluate()`, it won't appear in the page. Learn more about execution contexts [here](https://playwright.dev/#version=v1.3.0&path=docs%2Fcore-concepts.md&q=execution-contexts-nodejs-and-browser).

Overall, I meant that we'll think about making this work out of the box. There are tradeoffs to be considered around own properties, but perhaps we can make it better.
