### ISSUE TITLE
[BUG] ffmpeg dependency check breaks on Linux even if screencast is not used

### ISSUE THREAD

**Issue by anthonychu** [microsoft/playwright#3846]
**Context:**
- Playwright Version: 1.4.0
- Operating System: Linux (Azure Functions Linux Consumption plan)
- Node.js version: 12.x
- Browser: Chromium
- Extra: [any specific details about your environment]

The new ffmpeg dependency check is a breaking change on Linux because it now expects ffmpeg in the path. Is it possible to only run the check when video recording is activated?

**Code Snippet**

This app, with the playwright version bumped to 1.4.0. https://github.com/anthonychu/functions-headless-chromium/tree/main/playwright

```
Exception: Error: browserType.launch: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install ffmpeg


Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
Stack: browserType.launch: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install ffmpeg


Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at BrowserType._wrapApiCall (/home/site/wwwroot/node_modules/playwright-chromium/lib/client/channelOwner.js:76:15)
    at BrowserType.launch (/home/site/wwwroot/node_modules/playwright-chromium/lib/client/browserType.js:48:21)
    at module.exports (/home/site/wwwroot/screenshot/index.js:5:37)
    at WorkerChannel.invocationRequest (/azure-functions-host/workers/node/worker-bundle.js:18518:26)
    at ClientDuplexStream.<anonymous> (/azure-functions-host/workers/node/worker-bundle.js:18324:30)
    at ClientDuplexStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at ClientDuplexStream.Readable.push (_stream_readable.js:212:10)
    at Object.onReceiveMessage (/azure-functions-host/workers/node/worker-bundle.js:22785:19)
```

@arjun27

**Comment by anthonychu** [comment]
Dupe of #3845 (got an error from GitHub after first try)
