### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: page.goto: Timeout 30000ms exceeded

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/playwright#3952]
**Context:**
- Playwright Version: 1.4.1
- Operating System: Ubuntu 18.04
- Node.js version: 12.6
- Browser: Chromium 

**Code Snippet**

```node 

const playwright = require('playwright');

var fs = require("fs");
var sleep = require('sleep');

async function main() {

    const browser = await playwright.chromium.launch({
        headless: false
    });

    const page = await browser.newPage();




    // error here, randomly; in the log, /home/yuis/pg/playwright/tmp.js:27 is here
    await page.goto('https://www.coingecko.com/en/');

    // lots of more script here 
    // lots of more script here 
    // lots of more script here 

    await browser.close();
}

main();
```

**Describe the bug**

following error log message I get sometimes, usually at a first "page.goto" line. 
there is no suspicious code in my scripts. seems the error happens very randomly. 

```
(node:10230) UnhandledPromiseRejectionWarning: page.goto: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.coingecko.com/en/", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Frame._wrapApiCall (/home/yuis/pg/playwright/node_modules/playwright/lib/client/channelOwner.js:78:15)
    at Frame.goto (/home/yuis/pg/playwright/node_modules/playwright/lib/client/frame.js:78:21)
    at /home/yuis/pg/playwright/node_modules/playwright/lib/client/page.js:246:60
    at Page._attributeToPage (/home/yuis/pg/playwright/node_modules/playwright/lib/client/page.js:181:20)    
    at Page.goto (/home/yuis/pg/playwright/node_modules/playwright/lib/client/page.js:246:21)
    at main (/home/yuis/pg/playwright/tmp.js:27:16)
(node:10230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by arjun27** [comment]
Thanks @yuis-ice. Because the page is loading multiple dependent scripts, I suspect one of them does not finish loading in the 30 sec time frame, causing the `load` event to not be fired. I would recommend trying to use `domcontentloaded` to see if that helps.

```js
await page.goto('https://www.coingecko.com/en/', {waitUntil: 'domcontentloaded'});
```

**Comment by arjun27** [comment]
I'll close this for now since it doesn't seem to be a Playwright bug. We can continue the discussion here or feel free to create a  new issue.

**Comment by yuis-ice** [comment]
I don't think it's takes more than 30 seconds to load the page so randomly (they usually can be loaded within 3 seconds or so) either way. 
I added `{waitUntil: 'domcontentloaded'}` to the goto and still I get the same result.

**Comment by arjun27** [comment]
Thanks. Can you set the `DEBUG=pw:api` environment variable to get more logs?

**Comment by yuis-ice** [comment]
okay, here: 

```
// more logs here
// more logs here
// more logs here

  pw:api => page.goto started +1ms
  pw:api navigating to "https://www.coingecko.com/en/coins/ontology", waiting until "domcontentloaded" +0ms
  pw:api   navigated to "https://acdn.adnxs.com/ib/static/usersync/v3/async_usersync.html" +276ms
  pw:api   navigated to "https://public.servenobid.com/sync.html" +18ms
  pw:api   navigated to "https://jp-u.openx.net/w/1.0/pd?plm=6&ph=626fe778-b2ca-415b-a3f6-584fd2ac5ec0&gdpr=0" +3ms
  pw:api   "domcontentloaded" event fired +19ms
  pw:api   navigated to "https://eus.rubiconproject.com/usync.html" +33ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   navigated to "https://eb2.3lift.com/sync?" +27ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   navigated to "https://www.coingecko.com/en/coins/ontology" +224ms
  pw:api   navigated to "about:blank" +1s
  pw:api   "domcontentloaded" event fired +525ms
  pw:api <= page.goto succeeded +0ms
  pw:api   navigated to "about:blank" +6ms
  pw:api   "domcontentloaded" event fired +2ms
  pw:api   "load" event fired +330ms
  pw:api   navigated to "about:blank" +471ms
  pw:api   "load" event fired +0ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   navigated to "https://s.amazon-adsystem.com/iu3?cm3ppd=1&d=dtb-pub&csif=t&dl=r1u_dm" +575ms
  pw:api   "load" event fired +11ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   "load" event fired +3s
  pw:api   "load" event fired +115ms
  pw:api   navigated to "https://www.coingecko.com/en/coins/ontology" +205ms
  pw:api   navigated to "https://public.servenobid.com/sync.html" +49ms
  pw:api   navigated to "https://eus.rubiconproject.com/usync.html" +6ms
  pw:api   navigated to "https://acdn.adnxs.com/ib/static/usersync/v3/async_usersync.html" +2ms
  pw:api   navigated to "https://jp-u.openx.net/w/1.0/pd?plm=6&ph=626fe778-b2ca-415b-a3f6-584fd2ac5ec0&gdpr=0" +3ms
  pw:api   navigated to "about:blank" +3ms
  pw:api   navigated to "https://googleads.g.doubleclick.net/xbbe/pixel?d=CIielwEQ2_PQAhjF0oCQATAB&v=APEucNV8URzrilCL2VqZc5C4GWWPawzXy2c3Ixv53b5fycuFaKC4cLgS_1aBedhcVWHKfo1vIqaxpEVcStZEDg3f-Eg6G_vMbQ" +7ms
  pw:api   navigated to "https://eb2.3lift.com/sync?" +91ms
  pw:api   "domcontentloaded" event fired +69ms
  pw:api   navigated to "https://g2.gumgum.com/usync/13926?gdpr=0&gdpr_consent=&us_privacy=1---&r=https%3A%2F%2Fads.servenobid.com%2Fsync%3Fpid%3D309%26cd%3D6458%26uid%3D" +56ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   navigated to "https://eus.rubiconproject.com/usync.html?&geo=au&co=jp" +221ms
  pw:api   navigated to "https://cm.g.doubleclick.net/pixel?google_nid=gumgum_dbm&google_hm=YV9jNTg1ODM3Yy00NzgxLTRiZTAtYjk4Ny1mYzU2MzljZWFlZjI=&gdpr=0&gdpr_consent=" 
+4ms
  pw:api   navigated to "https://rtb.gumgum.com/usersync?b=emx&i=6491901430455768446brt24941601004834344884d8" +72ms
  pw:api   navigated to "https://tpc.googlesyndication.com/sodar/Enqz_20U.html" +30ms
  pw:api   "domcontentloaded" event fired +30ms
  pw:api   navigated to "https://s0.2mdn.net/8018828/1599532205998/300x250/PayPal_rest_assured_300x250.html" +44ms
  pw:api   navigated to "https://de.tynt.com/deb/?m=xch&rt=html&id=0010b00002Mq2FYAAZ&ru=https%3A%2F%2Fads.servenobid.com%2Fsync%3Fpid%3D304%26cd%3D896%26uid%3D33XUSERID33X" +9ms
  pw:api   navigated to "https://rtb.gumgum.com/usersync?b=snc&i=" +32ms
  pw:api   "domcontentloaded" event fired +25ms
  pw:api   "load" event fired +0ms
  pw:api   navigated to "about:blank" +72ms
  pw:api   "domcontentloaded" event fired +2ms
  pw:api   navigated to "https://tpc.googlesyndication.com/sodar/sodar2/216/runner.html" +18ms
  pw:api   "domcontentloaded" event fired +2ms
  pw:api   "load" event fired +0ms
  pw:api   navigated to "about:blank" +94ms
  pw:api   "load" event fired +0ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   "networkidle" event fired +863ms
  pw:api => page.waitForFunction started +2s
  pw:api <= page.waitForFunction succeeded +13ms
  pw:api => page.$$eval started +0ms
  pw:api <= page.$$eval succeeded +24ms
[
  {
    title: 'Ontology (ONT)',
    progress: '56%',
    likes: '6,361 people like this'
  }
]
  pw:api => page.goto started +0ms
  pw:api navigating to "https://www.coingecko.com/en/coins/true-usd", waiting until "domcontentloaded" +1ms
  pw:api   navigated to "https://www.coingecko.com/en/coins/true-usd" +661ms
  pw:api   "networkidle" event fired +1s
  pw:api   "domcontentloaded" event fired +309ms
  pw:api <= page.goto succeeded +0ms
  pw:api   navigated to "about:blank" +60ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   navigated to "about:blank" +155ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   "networkidle" event fired +500ms
  pw:api   "load" event fired +3s
  pw:api   navigated to "about:blank" +328ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   navigated to "https://s.amazon-adsystem.com/iu3?cm3ppd=1&d=dtb-pub&csif=t&dl=r1u_dm" +144ms
  pw:api   "load" event fired +10ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   "networkidle" event fired +490ms
  pw:api   navigated to "https://c83938fa5c7089f706c21a9e277928fc.safeframe.googlesyndication.com/safeframe/1-0-37/html/container.html" +222ms
  pw:api   "domcontentloaded" event fired +41ms
  pw:api   navigated to "about:blank" +25ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   navigated to "https://googleads.g.doubleclick.net/xbbe/pixel?d=CIielwEQ2_PQAhj24ICQATAB&v=APEucNVu_3bQvH9gv9kZTHZPa7Bz0wdIlJ5u4Oaj4DC_D8pEBSY1Js2wFosG3qYBAc9fsf67pWBXXfyu0H6I67NARiqWx3Oy3A" +82ms
  pw:api   "load" event fired +9ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   navigated to "https://pagead2.googlesyndication.com/pagead/s/cookie_push_onload.html#aHR0cHM6Ly9jMS5hZGZvcm0ubmV0L3NlcnZpbmcvY29va2llL21hdGNoLz9wYXJ0eT0xJmdvb2dsZV9naWQ9Q0FFU0VKam1OS2NvSjFfY2dpS2VBUG5rcGNBJmdvb2dsZV9jdmVyPTEmZ29vZ2xlX3B1c2g9QVF2aXRVSVVSZGtkSVZXbUNubFZLY2hEcFB5dnpRZGd3VGtUZ0VpTGVRTEhNWERNdnMwU2NpS1Jja2RqSk9ESzc5cUt4dlFDR3oxYTYzR09FQzkxQWdsSkt1dlJsblUyeHVZ,aHR0cHM6Ly9zMC4ybWRuLm5ldC9kb3QuZ2lmP2dvb2dsZV9naWQ9Q0FFU0VQVFJQSG5TUHlRa29Gbnd6VTZJbW9rJmdvb2dsZV9jdmVyPTEmZ29vZ2xlX3B1c2g9QVF2aXRVSzliZ041QUs4X19XSXh1c3pvczl3dnpNOHpLVlFWRVpaT2c5RTI5UjN3b0hzQVh1cDd4OGpYaUJRSTdjUTBLZ2pIZFMzU2FnUllBQ3RpbkNpUGNrdVlkSE5rbHV6Sg==,aHR0cHM6Ly9jbS5nLmRvdWJsZWNsaWNrLm5ldC9waXhlbC9hdHRyP2Q9QUhORjEzSXk3VkFTWEh2alZFcFBKVklHVVdkV25DMUYtU2s5OUZXbEtrdVU=" +105ms
  pw:api   navigated to "about:blank" +51ms
  pw:api   navigated to "https://tpc.googlesyndication.com/sodar/Enqz_20U.html" +50ms
  pw:api   "domcontentloaded" event fired +35ms
  pw:api   navigated to "about:blank" +7ms
  pw:api   "domcontentloaded" event fired +16ms
  pw:api   navigated to "https://s0.2mdn.net/8018828/1599531964760/728x90/PayPal_adaptable_728x90.html" +5ms
  pw:api   "domcontentloaded" event fired +6ms
  pw:api   navigated to "about:blank" +23ms
  pw:api   "domcontentloaded" event fired +2ms
  pw:api   navigated to "https://eb2.3lift.com/sync?max=10&cb=51631" +61ms
  pw:api   "domcontentloaded" event fired +18ms
  pw:api   navigated to "https://tpc.googlesyndication.com/sodar/sodar2/216/runner.html" +23ms
  pw:api   "load" event fired +9ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   navigated to "about:blank" +298ms
  pw:api   "load" event fired +1ms
  pw:api   "domcontentloaded" event fired +4ms
  pw:api   navigated to "about:blank" +665ms
  pw:api   "load" event fired +0ms
  pw:api   "domcontentloaded" event fired +17ms
  pw:api   navigated to "about:blank" +132ms
  pw:api   "domcontentloaded" event fired +5ms
  pw:api   navigated to "about:blank" +116ms
  pw:api   "domcontentloaded" event fired +4ms
  pw:api   "load" event fired +5ms
  pw:api   navigated to "https://acdn.adnxs.com/ib/static/usersync/v3/async_usersync.html" +801ms
  pw:api   navigated to "https://eus.rubiconproject.com/usync.html" +0ms
  pw:api   navigated to "https://public.servenobid.com/sync.html" +7ms
  pw:api   navigated to "https://jp-u.openx.net/w/1.0/pd?plm=6&ph=626fe778-b2ca-415b-a3f6-584fd2ac5ec0&gdpr=0" +0ms
  pw:api   "domcontentloaded" event fired +27ms
  pw:api   navigated to "https://eb2.3lift.com/sync?" +39ms
  pw:api   "domcontentloaded" event fired +11ms
  pw:api   navigated to "https://g2.gumgum.com/usync/13926?gdpr=0&gdpr_consent=&us_privacy=1---&r=https%3A%2F%2Fads.servenobid.com%2Fsync%3Fpid%3D309%26cd%3D9800%26uid%3D" +77ms
  pw:api   "domcontentloaded" event fired +56ms
  pw:api   navigated to "https://cm.g.doubleclick.net/pixel?google_nid=gumgum_dbm&google_hm=YV9jNTg1ODM3Yy00NzgxLTRiZTAtYjk4Ny1mYzU2MzljZWFlZjI=&gdpr=0&gdpr_consent=" 
+78ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   navigated to "https://rtb.gumgum.com/usersync?b=emx&i=6491901430455768446brt24941601004834344884d8" +47ms
  pw:api   "domcontentloaded" event fired +2ms
  pw:api => page.waitForFunction started +29ms
  pw:api   navigated to "https://rtb.gumgum.com/usersync?b=snc&i=" +86ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "load" event fired +26ms
  pw:api   navigated to "https://de.tynt.com/deb/?m=xch&rt=html&id=0010b00002Mq2FYAAZ&ru=https%3A%2F%2Fads.servenobid.com%2Fsync%3Fpid%3D304%26cd%3D7012%26uid%3D33XUSERID33X" +3ms
  pw:api   "domcontentloaded" event fired +11ms
  pw:api   "load" event fired +301ms
  pw:api <= page.waitForFunction failed +30s
(node:29471) UnhandledPromiseRejectionWarning: page.waitForFunction: Timeout 30000ms exceeded.
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Frame._wrapApiCall (/home/yuis/pg/playwright/node_modules/playwright/lib/client/channelOwner.js:78:15)
    at Frame.waitForFunction (/home/yuis/pg/playwright/node_modules/playwright/lib/client/frame.js:322:21)
    at /home/yuis/pg/playwright/node_modules/playwright/lib/client/page.js:421:60
    at Page._attributeToPage (/home/yuis/pg/playwright/node_modules/playwright/lib/client/page.js:181:20)
    at Page.waitForFunction (/home/yuis/pg/playwright/node_modules/playwright/lib/client/page.js:421:21)
    at main (/home/yuis/pg/playwright/tmp.js:178:20)
(node:29471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29471) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
