### ISSUE TITLE
[BUG] Chrome fails to launch with a TLS error

### ISSUE THREAD

**Issue by robeving** [microsoft/playwright#4053]
**Context:**
- Playwright Version: Version shipped in the latest Docker build `docker pull mcr.microsoft.com/playwright`
- Operating System: Linux Docker container
- Node.js version: v12.18.4
- Browser: Chromium
- Extra: Running on Azure as a Container Instance

```
npx: installed 1 in 1.515s

  System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    Memory: 10.16 GB / 15.64 GB
    Container: Yes
  Binaries:
    Node: 12.18.4 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.6 - /usr/bin/npm
  Languages:
    Bash: 4.4.20 - /bin/bash
```

**Code Snippet**

Run this code a few hundred times on the same instance

```	    for (const browserType of ['chromium']) {
            const browser = await playwright[browserType].launch({ args: ['--ignore-certificate-errors', '--no-sandbox'], headless: true });
            const context = await browser.newContext({ ignoreHTTPSError: true });
```

**Describe the bug**

```
Error in XYZ occurred:  browserType.launch: Protocol error (Browser.getVersion): Target closed.
=========================== logs ===========================
[browser] <launching> /root/.cache/ms-playwright/chromium-792639/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-kqZqqO --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --ignore-certificate-errors --no-sandbox --no-startup-window
[browser] <launched> pid=23581
[browser] [0924/063842.906968:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[browser] Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.Error
    at /root/node_modules/playwright/lib/chromium/crConnection.js:131:63
    at new Promise (<anonymous>)
    at CRSession.send (/root/node_modules/playwright/lib/chromium/crConnection.js:130:16)
    at CRSession.send (/root/node_modules/playwright/lib/helper.js:80:31)
    at Function.connect (/root/node_modules/playwright/lib/chromium/crBrowser.js:55:39)
    at Chromium._connectToTransport (/root/node_modules/playwright/lib/server/chromium.js:53:38)
    at Chromium._innerLaunch (/root/node_modules/playwright/lib/server/browserType.js:90:36)
    at async ProgressController.run (/root/node_modules/playwright/lib/progress.js:75:28)
    at async Chromium.launch (/root/node_modules/playwright/lib/server/browserType.js:62:25)
    at async /root/app.js:262:29
```

Add any other details about the problem here.

**Comment by yury-s** [comment]
I've just run the following snippet 1500 times without any issues. It is with playwright 1.6.0 though. Please reopen if you can reproduce the issue with the latest playwright.

```js
const playwright = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch({ args: ['--ignore-certificate-errors', '--no-sandbox'] });
    const context = await browser.newContext({ ignoreHTTPSError: true });
    await browser.close();
})();
  
```

**Comment by robeving** [comment]
I will, you may have to increase the number of times you run
