### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: browserType.launch: Host system is missing dependencies!

### ISSUE THREAD

**Issue by bityob** [microsoft/playwright#4056]
**Context:**
- Playwright Version: playwright@1.4.2
- Operating System: Windows
- Node.js version: v14.13.0
- Browser: Chromium
- Extra: Running from WSL 1

```
 System:
    OS: Linux 4.4 Ubuntu 16.04.3 LTS (Xenial Xerus)
    Memory: 2.03 GB / 15.92 GB
    Container: Yes
  Binaries:
    Node: 14.13.0 - ~/.n/bin/node
    npm: 6.14.8 - ~/.n/bin/npm
  Languages:
    Bash: 4.3.48 - /bin/bash
```

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // Create pages, interact with UI elements, assert values
  await browser.close();
})();
```

**Describe the bug**

Fails to launch chrome with this trace 

```
pw:api => browserType.launch started +0ms
Promise { <pending> }
pw:api <= browserType.launch failed +283ms
(node:1778) UnhandledPromiseRejectionWarning: browserType.launch: Host system is missing dependencies!

  Missing libraries are:
      libnss3.so
      libnssutil3.so
      libsmime3.so
      libnspr4.so
      libatk-1.0.so.0
      libatk-bridge-2.0.so.0
      libx11-xcb.so.1
      libxcb-dri3.so.0
      libxcomposite.so.1
      libxdamage.so.1
      libxfixes.so.3
      libcups.so.2
      libxrandr.so.2
      libgbm.so.1
      libasound.so.2
      libpangocairo-1.0.so.0
      libpango-1.0.so.0
      libcairo.so.2
      libatspi.so.0
      libgtk-3.so.0
      libgdk-3.so.0
      libgdk_pixbuf-2.0.so.0

Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at BrowserType._wrapApiCall (/mnt/c/Users/yobitton/Documents/Code/AutomatedIR.E2ETests/node_modules/playwright/lib/client/channelOwner.js:78:15)
    at BrowserType.launch (/mnt/c/Users/yobitton/Documents/Code/AutomatedIR.E2ETests/node_modules/playwright/lib/client/browserType.js:49:21)
    at REPL21:2:34
    at REPL21:5:3
    at Script.runInThisContext (vm.js:132:18)
    at REPLServer.defaultEval (repl.js:479:29)
    at bound (domain.js:430:14)
    at REPLServer.runBound [as eval] (domain.js:443:12)
    at REPLServer.onLine (repl.js:811:10)
    at REPLServer.emit (events.js:326:22)
(node:1778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by bityob** [comment]
I read again the system requirements, and since I'm using WSL, I need to install manually all the needed packages.

![image](https://user-images.githubusercontent.com/20026896/95106337-10bca800-0741-11eb-9354-28351d8e3d8d.png)

My current ubuntu version is 16.04. I'll upgrade the release and then will try to install the dependencies from the docker file.

https://github.com/microsoft/playwright/blob/v1.4.2/docs/docker/Dockerfile.bionic

**Comment by bityob** [comment]
I'm able to run now chrome after upgrading the ubuntu of WSL to 18.04 and installing the packages from the docker file.

Another source of errors in WSL with chrome -
https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-linuxwsl
