### ISSUE TITLE
[Question] Error when using wireguard vpn?

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#4193]
I am on wireguard vpn but the problem is browser spawned by chromium doesn't work . And after sometime it closes without giving anywarning error

However if i use Debug=* it gives me following error.

```
 pw:browser [err] [1020/121911.133203:WARNING:crash_report_exception_handler.cc(240)] UniversalExceptionRaise: (os/kern) failure (5) +188ms
  pw:error Error: write EPIPE
  pw:error     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) +0ms
  pw:error Protocol error (Page.createIsolatedWorld): Target closed.Error
  pw:error     at /Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/server/chromium/crConnection.js:131:63
  pw:error     at new Promise (<anonymous>)
  pw:error     at CRSession.send (/Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/server/chromium/crConnection.js:130:16)
  pw:error     at CRSession._sendMayFail (/Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/server/chromium/crConnection.js:135:21)
  pw:error     at /Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/server/chromium/crPage.js:325:34
  pw:error     at runMicrotasks (<anonymous>)
  pw:error     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  pw:error     at runNextTicks (internal/process/task_queues.js:62:3)
  pw:error     at processImmediate (internal/timers.js:434:9)
  pw:error     at async Promise.all (index 1)
  pw:error     at async FrameSession._initialize (/Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/server/chromium/crPage.js:402:9) +6ms
  pw:browser <process did exit: exitCode=null, signal=SIGTRAP> +60ms
  pw:channel:event {
  pw:channel:event   guid: 'CDPSession@320574eb3c04844867f5ebcc527b3d5d',
  pw:channel:event   method: '__dispose__',
  pw:channel:event   params: {}
  pw:channel:event } +11s
  pw:channel:event {
  pw:channel:event   guid: 'Page@799e8d6939fd59ea0ede661f6d201ddd',
  pw:channel:event   method: 'close',
  pw:channel:event   params: {}
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: 'BrowserContext@bef29a9bb71b6dfb57bdd2cb6848d9f2',
  pw:channel:event   method: 'close',
  pw:channel:event   params: {}
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: 'BrowserContext@bef29a9bb71b6dfb57bdd2cb6848d9f2',
  pw:channel:event   method: '__dispose__',
  pw:channel:event   params: {}
  pw:channel:event } +1ms
  pw:channel:event {
  pw:channel:event   guid: 'Browser@4712abf3effe63f36db87bd57ae72490',
  pw:channel:event   method: 'close',
  pw:channel:event   params: {}
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: 'Browser@4712abf3effe63f36db87bd57ae72490',
  pw:channel:event   method: '__dispose__',
  pw:channel:event   params: {}
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: 'BrowserContext@bef29a9bb71b6dfb57bdd2cb6848d9f2',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Frame',
  pw:channel:event     initializer: {
  pw:channel:event       url: 'chrome://new-tab-page/',
  pw:channel:event       name: '',
  pw:channel:event       parentFrame: undefined,
  pw:channel:event       loadStates: []
  pw:channel:event     },
  pw:channel:event     guid: 'Frame@ac22d9f93b4a079f0fd0a2ce588abfaa'
  pw:channel:event   }
  pw:channel:event } +52ms
/Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/client/connection.js:138
            throw new Error(`Cannot find parent object ${parentGuid} to create ${guid}`);
            ^

Error: Cannot find parent object BrowserContext@bef29a9bb71b6dfb57bdd2cb6848d9f2 to create Frame@ac22d9f93b4a079f0fd0a2ce588abfaa
    at Connection._createRemoteObject (/Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/client/connection.js:138:19)
    at Connection.dispatch (/Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/client/connection.js:105:18)
    at Immediate.<anonymous> (/Users/shirshak/Desktop/code/jest-test/internals/node_modules/playwright/lib/inprocess.js:40:85)
    at processImmediate (internal/timers.js:461:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by shirshak55** [comment]
nvm the window shouldn't have closed without giving explicit error its probably dns issue.
