### ISSUE TITLE
[Test] Ubuntu: browsercontext-proxy.spec.ts:128:1 › should exclude patterns crashes webkit

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#4326]
```
#0  0x00007f06b5a6e837 in __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:93
#1  0x00007f06b809c413 in g_strdup () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f06b809deb5 in g_strdupv () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f06c176d22a in WebKit::InspectorPlaywrightAgentClientGlib::createBrowserContext(WTF::String&, WTF::String const&, WTF::String const&) () at /home/pfeldman/.cache/ms-playwright/webkit-1373/minibrowser-wpe/lib/libWPEWebKit-1.0.so.3
#4  0x00007f06c15cd3b0 in WebKit::InspectorPlaywrightAgent::createContext(WTF::String const&, WTF::String const&) () at /home/pfeldman/.cache/ms-playwright/webkit-1373/minibrowser-wpe/lib/libWPEWebKit-1.0.so.3
#5  0x00007f06c15cd51d in non-virtual thunk to WebKit::InspectorPlaywrightAgent::createContext(WTF::String const&, WTF::String const&) () at /home/pfeldman/.cache/ms-playwright/webkit-1373/minibrowser-wpe/lib/libWPEWebKit-1.0.so.3
#6  0x00007f06c42e6ab1 in Inspector::PlaywrightBackendDispatcher::createContext(long, WTF::RefPtr<WTF::JSONImpl::Object, WTF::RawPtrTraits<WTF::JSONImpl::Object>, WTF::DefaultRefDerefTraits<WTF::JSONImpl::Object> >&&) ()
```

**Comment by pavelfeldman** [comment]
Fixed now
