### ISSUE TITLE
[BUG] Chromium: browser.close failed - Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#4423]
**Context:**
- Playwright Version: 1.5.2
- Operating System: Windows
- Node.js version: 12.18.3
- Browser: Chromium

**Description:**
Faced another issue with browser closure. It’s not a permanent problem, happens rarely.
But I would like to understand the root cause. Can we understand what happened using this trace?
```
[05:04:32] :	 [Step 1/1]  [36mdev_1  | [0m  [1;32m2020-11-11 10:04:32.499 UTC [30]:  [1;36mBootstrap: Shutting down playwright.  [0m
[05:04:32] :	 [Step 1/1]  [36mdev_1  | [0m  [1;32m2020-11-11 10:04:32.499 UTC [30]:  [1;36mBootstrap: Closing opened tabs.  [0m
[05:04:32] :	 [Step 1/1]  [36mdev_1  | [0m  [1;32m2020-11-11 10:04:32.500 UTC [30]:  [1;35m api:info => page.close started  [0m
[05:04:32] :	 [Step 1/1]  [36mdev_1  | [0m  [1;32m2020-11-11 10:04:32.587 UTC [30]:  [1;35m api:info <= page.close succeeded  [0m
[05:04:32] :	 [Step 1/1]  [36mdev_1  | [0m  [1;32m2020-11-11 10:04:32.587 UTC [30]:  [1;36mBootstrap: Shutting down browser.  [0m
[05:04:32] :	 [Step 1/1]  [36mdev_1  | [0m  [1;32m2020-11-11 10:04:32.587 UTC [30]:  [1;35m api:info => browser.close started  [0m
[05:04:32] :	 [Step 1/1]  [36mdev_1  | [0m 2020-11-11T10:04:32.597Z pw:browser <gracefully close start>
Protocol error (Runtime.callFunctionOn): Target closed.: 
    at Connection.sendMessageToServer (node_modules/playwright-chromium/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (node_modules/playwright-chromium/lib/client/channelOwner.js:54:53)
    at JSHandle.jsonValue (node_modules/playwright-chromium/lib/client/jsHandle.js:49:49)
    at /e2e/src/Generic/Generic.ts:196:67
    at Array.forEach (<anonymous>)
    at Page.<anonymous> (src/Generic/Generic.ts:195:18)
    at Proxy.<anonymous> (node_modules/playwright-chromium/lib/client/page.js:72:59)
    at Connection.dispatch (node_modules/playwright-chromium/lib/client/connection.js:118:25)
[05:04:33] :	 [Step 1/1]  [36mdev_1  | [0m  [1;32m2020-11-11 10:04:33.658 UTC [30]:  [1;35m api:info <= browser.close failed  [0m
```
Regarding these lines:
```
at Page.<anonymous> (src/Generic/Generic.ts:195:18)
at /e2e/src/Generic/Generic.ts:196:67
```
It’s just an observer:
```
 public static enableBrowserConsoleLogging(page: Page) {
    Generic.logToConsole(`Bootstrap: Enabling logging of browser console errors and alerts.`);
    page.on('console', msg =>
      msg.args().forEach(async arg => {. // Line number 195
        Generic.logToConsole(`Console: ${JSON.stringify(await arg.jsonValue())}`); // Line number 196
      })
    );
    page.on('pageerror', error => {
      Generic.logToConsole(`PageError: ${error.message}`);
    });
    page.on('requestfailed', request => {
      const failure = request.failure();
      if (failure) {
        Generic.logToConsole(`RequestFailed: ${failure.errorText} | ${request.url()}`);
      }
    });
  }
```
Should I turn off page event observers before calling browser closure to avoid this?

**Comment by yury-s** [comment]
There is a race between `page.close()` and `arg.jsonValue()`. Calling methods on `JSHandle` from closed page is unsafe as its corresponding object is unreachable, evaluating in closed page will normally cause 'Target closed.' or similar error.

> Should I turn off page event observers before calling browser closure to avoid this?

You should avoid calling async methods (they go to the browser to get the result) or catch the target closed error, calling methods like `ConsoleMessage.text()` is fine as they won't throw even if the page has been closed already.
