### ISSUE TITLE
[BUG] Error when using PM2 process manager in cluster mode

### ISSUE THREAD

**Issue by rtrag** [microsoft/playwright#4461]
**Context:**
- Playwright Version: 1.6.1
- Operating System: Linux and Mac
- Node.js version: v15.2.0
- Browser: Chromium

**Code Snippet**

```javascript

const browser_args = [
    "--disable-gpu",
    "--disable-web-security",
    "--disable-dev-shm-usage",
    "--disable-setuid-sandbox",
    "--no-first-run",
    "--no-sandbox",
    "--no-zygote",
    "--ignore-certificate-errors",
    "--ignore-certificate-errors-spki-list",
    "--enable-features=NetworkService",
]

 const browserServer = await playwright.chromium.launchServer({ headless: true, ignoreHTTPSErrors: true, args: browser_args })
```

**Describe the bug**

Getting error when using PM2 process manager in cluster mode, but works fine when using node to run

1|www  | TypeError: Cannot read property 'port' of null
1|www  |     at new BrowserServerImpl (../node_modules/playwright/lib/browserServerImpl.js:52:108)
1|www  |     at BrowserServerLauncherImpl.launchServer (..node_modules/playwright/lib/browserServerImpl.js:41:16)

**Comment by aslushnikov** [comment]
@rtag what do I do to reproduce this locally? I tried just running browser server and launching it with

```sh
$ npx pm2 start a.js -i max
```

and this ran just fine.

**Comment by rtrag** [comment]
can I get your a.js @aslushnikov

**Comment by rtrag** [comment]
Not sure why but under PM2 **address** is null


node_modules/playwright/lib/browserServerImpl.js

```javascript
 this._server = new ws.Server({ port });
 const **address** = this._server.address();
```

**Comment by rtrag** [comment]
What i found is if you fork it breaks ws

```javascript
const http = require('http');
const playwright = require('playwright');
const cluster = require('cluster')

const browser_args = [
    "--disable-gpu",
    "--disable-web-security",
    "--disable-dev-shm-usage",
    "--disable-setuid-sandbox",
    "--no-first-run",
    "--no-sandbox",
    "--no-zygote",
    "--ignore-certificate-errors",
    "--ignore-certificate-errors-spki-list",
    "--enable-features=NetworkService",
]

const { chromium } = require('playwright');  // Or 'webkit' or 'firefox'.

const server = http.createServer(async  (req, res) => {

    const browserServer = await chromium.launchServer({ headless: true, ignoreHTTPSErrors: true, args: browser_args });
    const wsEndpoint = await browserServer.wsEndpoint();
    console.log(wsEndpoint);
    // Use web socket endpoint later to establish a connection.
    const browser = await chromium.connect({ wsEndpoint });
    const context = await browser.newContext();
    console.log("Number of contexts currently running in this browser: " + browser.contexts().length);

});


if (cluster.isMaster) {
    console.log(`Master ${process.pid} is running`);

    // Fork workers.
    for (let i = 0; i < 4; i++) {
        cluster.fork();
    }

    cluster.on('exit', (worker, code, signal) => {
        console.log(`worker ${worker.process.pid} died`);
    });
} else {
    // Workers can share any TCP connection
    // In this case it is an HTTP server
    server.listen(4000);

}

console.log('Node.js web server at port 4000 is running..')


```

**Comment by dgozman** [comment]
I can repro this, thank you for the script.
