### ISSUE TITLE
[BUG] Cannot launch webkit on apple silicon

### ISSUE THREAD

**Issue by jrieken** [microsoft/playwright#4533]
**Context:**
- Playwright Version: 1.6.2
- Operating System: macOS 11.0.1
- Node.js version: 15.3.0
- Browser:  WebKit
- Extra: Using Apple Silicon

**Code Snippet**

* run on apple silicon
* use vscode project (https://github.com/Microsoft/vscode)
* run `yarn && yarn compile`
* run `yarn test-browser --browser webkit`, you see the error below

```
jrieken@joh-13m1 vscode % yarn test-browser --browser webkit  
yarn run v1.22.5
$ node test/unit/browser/index.js --browser webkit
browserContext.newPage: Protocol error (Page.setScreenSizeOverride): The page has been closed.
    at Connection.sendMessageToServer (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/channelOwner.js:54:53)
    at /Users/jrieken/Code/vscode/node_modules/playwright/lib/client/browserContext.js:91:58
    at BrowserContext._wrapApiCall (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/channelOwner.js:80:34)
    at BrowserContext.newPage (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/browserContext.js:88:21)
    at runTestsInBrowser (/Users/jrieken/Code/vscode/test/unit/browser/index.js:139:29)
    at async /Users/jrieken/Code/vscode/test/unit/browser/index.js:243:11
    at async Promise.all (index 0)
    at async /Users/jrieken/Code/vscode/test/unit/browser/index.js:252:19
error Command failed with exit code 1.

```

**Comment by pavelfeldman** [comment]
👋 jrieken, congrats on getting your hands on a new device! Still waiting for ours to give it a try and make it work 😄 .

Setting the `DEBUG=pw:browser*` env variable will probably tell you when and how thr browser crashed.

**Comment by jrieken** [comment]
Not much extra info

```
jrieken@joh-13m1 vscode % yarn test-browser --browser webkit
yarn run v1.22.5
$ node test/unit/browser/index.js --browser webkit
  pw:browser <launching> /Users/jrieken/Library/Caches/ms-playwright/webkit-1383/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=44117 +9ms
browserContext.newPage: Protocol error (Page.setScreenSizeOverride): The page has been closed.
    at Connection.sendMessageToServer (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/channelOwner.js:54:53)
    at /Users/jrieken/Code/vscode/node_modules/playwright/lib/client/browserContext.js:91:58
    at BrowserContext._wrapApiCall (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/channelOwner.js:80:34)
    at BrowserContext.newPage (/Users/jrieken/Code/vscode/node_modules/playwright/lib/client/browserContext.js:88:21)
    at runTestsInBrowser (/Users/jrieken/Code/vscode/test/unit/browser/index.js:139:29)
    at async /Users/jrieken/Code/vscode/test/unit/browser/index.js:243:11
    at async Promise.all (index 0)
    at async /Users/jrieken/Code/vscode/test/unit/browser/index.js:252:19
  pw:browser <kill> +497ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by aslushnikov** [comment]
This is fixed with https://github.com/microsoft/playwright/commit/1d90d7a92532d51047745a544a78df5b87f08270

It is already available if installing `playwright@next` and will be in our next release.
