### ISSUE TITLE
[BUG] page.evaluate: Evaluation failed: TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by dartandrevinsky** [microsoft/playwright#4746]
**Context:**
- Playwright Version: 1.7.0
- Operating System: Mac, 11.0.1
- Node.js version: 12.18.3
- npm version: 6.14.6
- Browser: Chromium
- Extra:   Languages:
    Bash: 3.2.57 - /bin/bash
  
**Code Snippet**

following the script described [here](https://twitter.com/johnlindquist/status/1339276254864756737)

```javascript
//headlines.js
const { select } = await simplify("playwright")

const url = await arg('Enter url:')
const selector = await arg('Enter selector:')

const headlines = await select(url, selector)

const curated = await prompt({
  message: 'Select headlines:',
  type: 'checkbox',
  choices: headlines
})

const fileName = url + '-' + selector + '.json'

writeFile(fileName, JSON.stringify(curated.value, null, '\t'))

edit(fileName)
```

**Describe the bug**

The execution of the script outputs this error:

```txt
andrew@Andrews-MBP dev % headlines

headlines wants to download the npm package playwright
playwright has had 136949 downloads from npm in the past week

Read more about playwright here: https://npmjs.com/package/playwright

? Do you trust playwright? Yes
Installing playwright and re-running.

added 24 packages, and audited 200 packages in 1m

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
? Enter url: engadget.com
? Enter selector: h2
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

page.evaluate: Evaluation failed: TypeError: Cannot read property 'reduce' of undefined
    at eval (eval at callFunction (:304:29), <anonymous>:5:11)
    at Array.map (<anonymous>)
    at eval (eval at callFunction (:304:29), <anonymous>:4:5)
    at UtilityScript.callFunction (<anonymous>:305:24)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Connection.sendMessageToServer (/Users/andrew/.simple/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/andrew/.simple/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /Users/andrew/.simple/node_modules/playwright/lib/client/frame.js:157:48
    at Frame._wrapApiCall (/Users/andrew/.simple/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.evaluate (/Users/andrew/.simple/node_modules/playwright/lib/client/frame.js:156:21)
    at /Users/andrew/.simple/node_modules/playwright/lib/client/page.js:341:60
    at Page._attributeToPage (/Users/andrew/.simple/node_modules/playwright/lib/client/page.js:202:20)
    at Page.evaluate (/Users/andrew/.simple/node_modules/playwright/lib/client/page.js:341:21)
    at select (file:///Users/andrew/.simple/src/simplify/playwright.js:20:28)
    at runNextTicks (node:internal/process/task_queues:58:5)

```

**Comment by aslushnikov** [comment]
@dartandrevinsky this does look like a problem on the "simplified" end; I'm not sure what it is though, but I'd recommend filing it over to them.

- I see there are some mentions of esm in the stack. Historically, there were some issues with esm - maybe this context will help: https://github.com/puppeteer/puppeteer/issues/3382.
- In case there's some transpilation involved, please check out the [troubleshooting section](https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md#code-transpilation-issues)

**Comment by dartandrevinsky** [comment]
@aslushnikov Andrey, before going any further I have to say that prior to filing this issue I contacted the author of simplified and heard the same words from him (i.e. 'it's on the other end'). So I'd like to clear things out for me. And perhaps, you can help me. First off, the top five frames of the reported callstack - can you tell me where are they coming from? The first identifiable frame is from 'playwright' (`playwright/lib/client/connection.js:69:15`). How come you conclude it's coming from the 'simplified' end?
