### ISSUE TITLE
[Question][webkit]page.reload crush session

### ISSUE THREAD

**Issue by fet202** [microsoft/playwright#4999]
If  ` await page.reload({waitUntil: 'networkidle'});` added to `beforeEach `
for Chromium and Firefox works properly

```
(node:6433) UnhandledPromiseRejectionWarning: page.waitForSelector: Protocol error (Runtime.evaluate): The page has been closed.
=========================== logs ===========================
waiting for selector "[data-qa="input_autocomplete_query"]" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: 
    at Connection.sendMessageToServer /playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> /node_modules/playwright/lib/client/channelOwner.js:44:61)
IdeaProjects/ui_tests/node_modules/playwright/lib/client/frame.js:180:48
    at Frame._wrapApiCall node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.waitForSelector (/node_modules/playwright/lib/client/frame.js:175:21)
    at (/ui_tests/node_modules/playwright/lib/client/page.js:212:60
    at Page._attributeToPage (/ui_tests/node_modules/playwright/lib/client/page.js:202:20)
    at Page.waitForSelector (/ui_tests/node_modules/playwright/lib/client/page.js:212:21)
    at BasePage.navigateToInput (/ui_tests/Locators/basePage.js:64:16)
    at Object.<anonymous> (/ui_tests/__tests__/tests/Mobilleiot.test.js:115:20)
(node:6433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6433) UnhandledPromiseRejectionWarning: page.reload: Navigation failed because page was closed!
=========================== logs ===========================
waiting for navigation until "networkidle"
  navigated to "URL"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: 
    at Connection.sendMessageToServer (/IdeaProjects/ui_tests/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /playwright/lib/client/page.js:272:73
    at Page._wrapApiCall (/playwright/lib/client/channelOwner.js:72:34)
    at Page.reload (node_modules/playwright/lib/client/page.js:270:21)
    at Object.<anonymous> (/tests/Mobilleiot.test.js:24:14)
    at Object.asyncJestLifecycle /node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:58:37)
    at //node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (/ui_tests/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
(node:6433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

**Comment by yury-s** [comment]
Looks like problem with jest, can you add the test snippet and logs printed when running the test with `DEBUG=pw:api`?

**Comment by fet202** [comment]
> Looks like problem with jest, can you add the test snippet and logs printed when running the test with `DEBUG=pw:api`?

pw:api => browserType.connect started +0ms
  pw:api <= browserType.connect succeeded +12ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +38ms
  pw:api => browserContext.newPage started +1ms
  pw:api <= browserContext.newPage succeeded +321ms
  pw:api => browserContext.grantPermissions started +835ms
  pw:api <= browserContext.grantPermissions succeeded +2ms
  pw:api => browserContext.setGeolocation started +1ms
  pw:api <= browserContext.setGeolocation succeeded +1ms
  pw:api => page.goto started +0ms
  pw:api navigating to "/tmap2/mobileiot/", waiting until "domcontentloaded" +2ms
  pw:api   navigated to "tmap2/mobileiot/" +142ms
  pw:api   "domcontentloaded" event fired +2s
  pw:api <= page.goto succeeded +42ms
  pw:api => page.reload started +3ms
  pw:api waiting for navigation until "networkidle" +2ms
  pw:api => page.waitForSelector started +41ms
  pw:api => browser.close started +30ms
  pw:api waiting for selector "[data-qa="input_autocomplete_query"]" to be visible +4ms
  pw:api   navigated to "tmap2/mobileiot/" +5ms
  pw:api   navigated to "/tmap2/mobileiot/" +0ms
  pw:api <= page.waitForSelector failed +29ms
(node:10522) UnhandledPromiseRejectionWarning: page.waitForSelector: Protocol error (Runtime.evaluate): The page has been closed.
=========================== logs ===========================
waiting for selector "[data-qa="input_autocomplete_query"]" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: 
    at Connection.sendMessageToServer (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/frame.js:180:48
    at Frame._wrapApiCall (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.waitForSelector (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/frame.js:175:21)
    at /Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/page.js:212:60
    at Page._attributeToPage (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/page.js:202:20)
    at Page.waitForSelector (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/page.js:212:21)
    at BasePage.navigateToInput (/Users/saymyname/IdeaProjects/ui_tests/Locators/basePage.js:64:16)
    at Object.<anonymous> (/Users/saymyname/IdeaProjects/ui_tests/__tests__/tests/Mobilleiot.test.js:115:20)
(node:10522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10522) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  pw:api <= page.reload failed +5ms
(node:10522) UnhandledPromiseRejectionWarning: page.reload: Navigation failed because page was closed!
=========================== logs ===========================
waiting for navigation until "networkidle"
  navigated to "tmap2/mobileiot/"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: 
    at Connection.sendMessageToServer (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/page.js:272:73
    at Page._wrapApiCall (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Page.reload (/Users/saymyname/IdeaProjects/ui_tests/node_modules/playwright/lib/client/page.js:270:21)
    at Object.<anonymous> (/Users/saymyname/IdeaProjects/ui_tests/__tests__/tests/Mobilleiot.test.js:24:14)
    at Object.asyncJestLifecycle (/Users/saymyname/IdeaProjects/ui_tests/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:58:37)
    at /Users/saymyname/IdeaProjects/ui_tests/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (/Users/saymyname/IdeaProjects/ui_tests/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
(node:10522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
  pw:api <= browser.close succeeded +4ms

**Comment by yury-s** [comment]
Yeah, someone calls `browser.close()` (pw:api => browser.close started +30ms)  while you are waiting for `page.reload()` to finish and this triggers the exception.

**Comment by fet202** [comment]
> Yeah, someone calls `browser.close()` (pw:api => browser.close started +30ms) while you are waiting for `page.reload()` to finish and this triggers the exception.

Yes, you are right. The problem was solved by changing jest.config. Thank you
