### ISSUE TITLE
[REGRESSION]: Install of chromium with playwright@next fails starting with 1.8.0-next-1610946580000

### ISSUE THREAD

**Issue by kyen99** [microsoft/playwright#5056]
**Context:**
- INSTALL SUCCESSFULLY DOWNLOADS CHROMIUM Playwright Version: 1.8.0-next-1610946580000
- INSTALL FAILS TO DOWNLOAD CHROMIUM Playwright Version: 1.8.0-next-1610946580000
- MacOS 11.1 arm64 Apple M1 Silicon
- Latest Macbook Air

**Code Snippet**

```yarn install playwright@1.8.0-next-1610946580000```

**Describe the bug:**

It seems the problem is simply that the install package it's looking for does not exist at:
```https://playwright.azureedge.net/builds/chromium/844399/chromium-mac-arm64.zip```

Full error message:
```
error /Users/kyen/Projects/radius/ig-runner/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/kyen/Projects/radius/ig-runner/node_modules/playwright
Output:
(node:56101) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
Error: Download failed: server returned code 404. URL: https://playwright.azureedge.net/builds/chromium/844399/chromium-mac-arm64.zip
    at /Users/kyen/Projects/radius/ig-runner/node_modules/playwright/lib/install/browserFetcher.js:190:27
    at ClientRequest.requestCallback (/Users/kyen/Projects/radius/ig-runner/node_modules/playwright/lib/install/browserFetcher.js:235:13)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at /Users/kyen/Projects/radius/ig-runner/node_modules/playwright/lib/install/installer.js:102:19
    at async validateCache (/Users/kyen/Projects/radius/ig-runner/node_modules/playwright/lib/install/installer.js:101:9)
    at async installBrowsersWithProgressBar (/Users/kyen/Projects/radius/ig-runner/node_modules/playwright/lib/install/installer.js:60:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
This is fixed now.
