### ISSUE TITLE
[Feature]Socket connect timeout should be confiugrable

### ISSUE THREAD

**Issue by wispxjtu** [microsoft/playwright#5062]
I have set the the navigate timeout and default timeout to 3 min

`              page.setDefaultNavigationTimeout(180000);
                page.setDefaultTimeout(180000);
                let response = await page.goto(naviUrl, {timeout: 180000, waitUntil: "domcontentloaded"});
`
But I still see such error "page.goto: net::ERR_TIMED_OUT" after 30s

=========================== logs ===========================
navigating to "https://xxx", waiting until "domcontentloaded"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/app/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/app/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /app/node_modules/playwright/lib/client/frame.js:80:71
    at Frame._wrapApiCall (/app/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at Frame.goto (/app/node_modules/playwright/lib/client/frame.js:78:21)
    at /app/node_modules/playwright/lib/client/page.js:267:60
    at Page._attributeToPage (/app/node_modules/playwright/lib/client/page.js:202:20)
    at Page.goto (/app/node_modules/playwright/lib/client/page.js:267:21)
    at Object.<anonymous> (/app/built/lib/crawl/crawl.js:254:47)
    at Generator.next (<anonymous>)

**Comment by pavelfeldman** [comment]
That's what would happen in the real browser. You give the `goto` action a 3minute time budget. But it fails with the network error sooner than that, after the first 30 seconds Chrome's network stack gives up with net::ERR_TIMED_OUT and will no longer be establishing the connection. The error you get is not a `TimeoutError` that suggests that the budget is over, it is rather an `Error` that suggests that the script failed.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open new requests if this did not address the issue in full.
