### ISSUE TITLE
[BUG] yarn install results in `Error: unexpected end of file` during archive extraction (Zlib.zlibOnError)

### ISSUE THREAD

**Issue by jgehrcke** [microsoft/playwright#5066]
```
[2021-01-20T12:15:19Z] yarn --frozen-lockfile
yarn install v1.22.10
[1/5] Validating package.json...
...
[5/5] Building fresh packages...
 
 
error /build/node_modules/playwright: Command failed.
[2021-01-20T12:17:18Z] Exit code: 1
[2021-01-20T12:17:18Z] Command: node install.js
[2021-01-20T12:17:18Z] Arguments:
[2021-01-20T12:17:18Z] Directory: /build/node_modules/playwright
[2021-01-20T12:17:18Z] Output:
[2021-01-20T12:17:18Z] chromium v833159 downloaded to /build/.cache/ms-playwright/chromium-833159
[2021-01-20T12:17:18Z]
[2021-01-20T12:17:18Z] firefox v1221 downloaded to /build/.cache/ms-playwright/firefox-1221
[2021-01-20T12:17:18Z]
[2021-01-20T12:17:18Z] (node:1704) UnhandledPromiseRejectionWarning: Error: unexpected end of file
[2021-01-20T12:17:18Z]     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
 ```

```
± cat yarn.lock | grep playwright
playwright@1.7.0:
  resolved "https://registry.yarnpkg.com/playwright/-/playwright-1.7.0.tgz#72a836dcdfa5a99cc36981eb2e86abafd9a30ce3"
```

Was reproducible, retrying did not help.

Trying 1.7.1 now.

**Comment by jgehrcke** [comment]
Not sure if that was really the solution or pure coincidence, but after bumping to playwright 1.7.1 the problem seems to be gone: https://github.com/opstrace/opstrace/pull/276.

**Comment by jgehrcke** [comment]
Seen again:

```
[2021-05-06T08:07:52Z] Command: node install.js
[2021-05-06T08:07:52Z] Arguments:
[2021-05-06T08:07:52Z] Directory: /build/node_modules/playwright
[2021-05-06T08:07:52Z] Output:
[2021-05-06T08:07:52Z] (node:1965) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
[2021-05-06T08:07:52Z] Error: unexpected end of file
[2021-05-06T08:07:52Z]     at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
[2021-05-06T08:07:52Z]     at /build/node_modules/playwright/lib/install/installer.js:130:19
[2021-05-06T08:07:52Z]     at async validateCache (/build/node_modules/playwright/lib/install/installer.js:129:9)
[2021-05-06T08:07:52Z]     at async installBrowsersWithProgressBar (/build/node_modules/playwright/lib/install/installer.js:80:9)
```
With 1.10.0.
