### ISSUE TITLE
Timeouts until `npm install` is run again

### ISSUE THREAD

**Issue by caramdache** [microsoft/playwright#5112]
I have this weird behaviour that also affected me with Puppeteer before I made the switch to Playwright.

When I come back to my centOS host after several hours, generally the next morning, my Playwright scripts (previously Puppeteer scripts) are no longer working. They timeout when trying to open the first page, and that page is well accessible through a standard browser. No matter how hard I try to run the script again, the timeout always fires...

... until I rerun `npm install`. Nothing else changes, the venv, cookies, `user_data_dir` are still intact and suddenly the scripts start working again. `npm install` seems to be the singlest command that makes everything workable again. Previously, I had discovered by trial and error, and thought that I had to remove the `node_modules` directory and run `npm install` again, but that former step seems unnecessary.

It's weird, but reproducible. The weirdest thing is that `npm install` does not seem to download or update anything:

```bash
$ npm install
npm install
npm WARN xxx@1.0.0 No description

audited 85 packages in 2.282s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Here is what the `package.json` file looks like:
```json
{
  "name": "xxx",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "reset": "rm -f package-lock.json && rm -rf node_modules && npm install"
  },
  "repository": {
    "type": "git",
    "url": "git@xxx.git"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "adm-zip": "^0.5.1",
    "child_process": "^1.0.2",
    "colors": "^1.4.0",
    "mysql2": "^2.2.5",
    "nodemailer": "^6.4.17",
    "playwright": "^1.8.0",
    "puppeteer": "^5.5.0",
    "tmp": "^0.2.1"
  }
}
```

Any idea of what the problem could be?

**Comment by caramdache** [comment]
I came accross the issue again today, after a week-end with no action.

Before running `npm install`:

```bash
DEBUG=pw:api test.py
Starting...
  pw:api => browser_type.launch_persistent_context started
  pw:api <= browser_type.launch_persistent_context succeded
Loading cookies...
  pw:api => browser_context.add_cookies started
  pw:api <= browser_context.add_cookies succeded
  pw:api => browser_context.route started
  pw:api <= browser_context.route succeded
Opening https://someurl
  pw:api => page.goto started
  pw:api navigating to "https://someurl", waiting until "load" +0ms
  pw:api => route.continue_ started
  pw:api <= route.continue_ succeded
  pw:api   navigated to "https://someurl" +30ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   "load" event fired +0ms
  pw:api <= page.goto succeded
  pw:api => page.wait_for_selector started
  pw:api waiting for selector "#someselector" to be visible +2ms
  pw:api   "networkidle" event fired +498ms
  pw:api <= page.wait_for_selector failed
Traceback (most recent call last):
  <...>
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 5807, in wait_for_selector
    raise e
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 5797, in wait_for_selector
    self._sync(
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 90, in _sync
    return future.result()
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_page.py", line 353, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 250, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#someselector" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

**Comment by caramdache** [comment]
Running `npm install --verbose`:

```bash
npm install -verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-verbose' ]
npm info using npm@6.14.6
npm info using node@v12.18.3
npm verb npm-session dc55e893dfc8e08c
npm info lifecycle myapp@1.0.0~preinstall: myapp@1.0.0
npm timing stage:loadCurrentTree Completed in 125ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 63ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 71ms
npm timing stage:loadIdealTree Completed in 158ms
npm timing stage:generateActionsToTake Completed in 8ms
npm verb correctMkdir /home/myself/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/myself/.npm/_locks/staging-ff1708e4b99fd89a.lock for /var/www/django/myapp/npm/node_modules/.staging
npm verb unlock done using /home/myself/.npm/_locks/staging-ff1708e4b99fd89a.lock for /var/www/django/myapp/npm/node_modules/.staging
npm timing stage:executeActions Completed in 75ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm info linkStuff myapp@1.0.0
npm info lifecycle myapp@1.0.0~install: myapp@1.0.0
npm info lifecycle myapp@1.0.0~postinstall: myapp@1.0.0
npm info lifecycle myapp@1.0.0~prepublish: myapp@1.0.0
npm info lifecycle myapp@1.0.0~prepare: myapp@1.0.0
npm timing stage:runTopLevelLifecycles Completed in 422ms
npm verb saving []
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN myapp@1.0.0 No description

npm timing audit submit Completed in 826ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 826ms
npm timing audit body Completed in 1ms
audited 85 packages in 1.174s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 1495ms
npm info ok
```

**Comment by caramdache** [comment]
And now, as a result of `npm install`, and only that, it's all working again, strangely:

```bash
DEBUG=pw:api test.py
Starting...
  pw:api => browser_type.launch_persistent_context started
  pw:api <= browser_type.launch_persistent_context succeded
Loading cookies...
  pw:api => browser_context.add_cookies started
  pw:api <= browser_context.add_cookies succeded
  pw:api => browser_context.route started
  pw:api <= browser_context.route succeded
Fetching extensions for 85662832...
Opening https://someurl
  pw:api => page.goto started
  pw:api navigating to "https://someurl", waiting until "load" +0ms
  pw:api => route.continue_ started
  pw:api <= route.continue_ succeded
  pw:api   navigated to "https://someurl" +2s
  pw:api => route.abort started
  <...>
  pw:api <= route.abort succeded
  pw:api   "domcontentloaded" event fired +5s
  pw:api => route.abort started
  <...>
  pw:api <= route.abort succeded
  pw:api   "load" event fired +39ms
  pw:api <= page.goto succeded
  pw:api => page.wait_for_selector started
  pw:api => route.abort started
  pw:api waiting for selector "#someselector" to be visible +4ms
  pw:api   selector resolved to visible <table class="rgMasterTable rgClipCells" id="someselector>…</table> +21ms
  pw:api <= page.wait_for_selector succeded
Closing...
Saving cookies...
  pw:api => browser_context.cookies started
  pw:api <= browser_context.cookies succeded
  pw:api => browser_context.close started
  pw:api <= browser_context.close succeded
```

**Comment by caramdache** [comment]
I should add that the same code running on:

- Win10
- Python 3.8.7
- npm@6.13.4
- node@v12.14.1

has no such issue.

**Comment by aslushnikov** [comment]
(sorry for the long reply - we missed this in the incoming flow of bugs).

@caramdache One thing to check though is that you run the same node.js/npm/python version on windows and on your centOS. 

Other than that, I'm not sure how we can help here - this doesn't look to be related to Playwright per se.
