### ISSUE TITLE
[BUG] Chromium fails with error Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#5214]
**Context:**
- Playwright Version: playwright-chromium 1.8.0
- Operating System: CentOS Linux, version 3.10.0-1160.11.1.el7.x86_64
- Node.js version: 14.15.4
- Browser: Chromium
- Extra: playwright:v1.8.0-bionic, Docker 20.10.1, Docker-compose 1.25.5

**Description:**
During one of test runs we faced an issue when browser crashed with an error. It was run in Docker in TeamCity agent with CentOS using official PW image.
Log below:

```
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m  [1;32m2021-01-29 07:10:43.598 UTC [1044]:  [1;36mBootstrap: NodeJS version v14.15.4  [0m
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m  [1;32m2021-01-29 07:10:43.598 UTC [1044]:  [1;36mBootstrap: Setting up global variables.  [0m
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m  [1;32m2021-01-29 07:10:43.598 UTC [1044]:  [1;36mBootstrap: Launching browser.  [0m
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m  [1;32m2021-01-29 07:10:43.599 UTC [1044]:  [1;36m{"timeout":60000,"args":["--start-maximized","--window-size=1920,1080","--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--enable-logging"],"logger":{}}  [0m
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m  [1;32m2021-01-29 07:10:43.599 UTC [1044]:  [1;35m api:info => browserType.launch started  [0m
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.721Z pw:browser <launching> /root/.cache/ms-playwright/chromium-844399/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-gfFxEi --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --start-maximized --window-size=1920,1080 --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --enable-logging --no-startup-window
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.735Z pw:browser <launched> pid=2128
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.832Z pw:browser [err] [0129/071043.831738:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.833Z pw:browser [err] Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.839Z pw:browser <gracefully close start>
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.839Z pw:browser <kill>
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.842Z pw:browser <process did exit: exitCode=127, signal=null>
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m 2021-01-29T07:10:43.842Z pw:browser <gracefully close end>
[07:10:43] :	 [Step 1/3]  [36me2e_1  | [0m  [1;32m2021-01-29 07:10:43.842 UTC [1044]:  [1;35m api:info <= browserType.launch failed  [0m
```

**Comment by aslushnikov** [comment]
@DJ-Glock we stumbled upon this awhile ago: https://github.com/puppeteer/puppeteer/issues/2207

And this seems to be a glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=19329

We might be able to add retries when launching browser since this one is a pure race condition.

**Comment by petersolopov** [comment]
Great! Can we wait for this fix in 1.8.2 version?

**Comment by mxschmitt** [comment]
@petersolopov the latest master version should already contain the fix. You can install it with `npm install playwright@next`.

**Comment by Innos** [comment]
Hello, I am running an old version of the playwright-chromium package (v 1.9.2) and rarely, but I'm getting this error. From what I can see in the Stack trace, the error originates from launch() call on the client (https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/client/browserType.ts), not the server (https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/browserType.ts) that this issue addressed.

I want to ask if this been fixed in a version above 1.9.2, i.e. would upgrading to a newer version fix this for me? Or if not, should an issue be opened/reopened for this?

Stacktrace:
```
"stack": "browserType.launch: Protocol error (Browser.getVersion): Browser closed.\n==================== Browser output: ====================\n<launching> /root/.cache/ms-playwright/chromium-854489/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-UiOZOG --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window\n<launched> pid=14575\n[err] [0401/064045.858585:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n[err] Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!\n=========================== logs ===========================\n<launching> /root/.cache/ms-playwright/chromium-854489/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-UiOZOG --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window\n<launched> pid=14575\n[err] [0401/064045.858585:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n[err] Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!\n============================================================\nNote: use DEBUG=pw:api environment variable to capture Playwright logs.Error\n    at Object.captureStackTrace (/libraries-path/js/node_modules/playwright-chromium/lib/utils/stackTrace.js:48:19)\n    at Connection.sendMessageToServer (/libraries-path/js/node_modules/playwright-chromium/lib/client/connection.js:69:48)\n    at Proxy.<anonymous> (/libraries-path/js/node_modules/playwright-chromium/lib/client/channelOwner.js:64:61)\n    at /libraries-path/js/node_modules/playwright-chromium/lib/client/browserType.js:64:67\n    at BrowserType._wrapApiCall (/libraries-path/js/node_modules/playwright-chromium/lib/client/channelOwner.js:77:34)\n    at BrowserType.launch (/libraries-path/js/node_modules/playwright-chromium/lib/client/browserType.js:55:21)\n    at Context.<anonymous> (/tmp/ExecutionStrategies/neusor5m.hzo/test/288932.js:82:33)\n    at processImmediate (internal/timers.js:461:21)",
```

**Comment by mxschmitt** [comment]
@Innos We would strongly recommend upgrading! We don't support such old versions. We can't guarantee that this specific was fixed, but e.g. Chromium has made ten-thousands of commits during this timespan so most likely things have changed!

If you experience an issue with a recent Playwright version, feel free to file an issue and we'll look into it.

**Comment by aslushnikov** [comment]
@Innos we landed a workaround for the upstream issue, so if you upgrade, then your tests should work just fine

**Comment by Innos** [comment]
Thank you very much for the replies, I will look into upgrading to the newest version then.
