### ISSUE TITLE
[BUG] Anyway to silence 'childFrames' of undefined

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#5224]
**Context:**
- Playwright Version:  "playwright": "^1.9.0-next-1611855200000"
- Operating System: Mac
- Node.js version:v15.6.0
- Browser: Firefox
- Extra: [any specific details about your environment]

On internal websites while page is loading if we write some code like this:

```js
await page.evaluate(()=>{
// ...
})
```

It gives some pesky error

```
ignoring uncaught exception TypeError: Cannot read property 'childFrames' of undefined
    at FrameManager.removeChildFramesRecursively (/Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/frames.js:234:35)
    at FrameManager.frameCommittedNewDocumentNavigation (/Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/frames.js:122:14)
    at FFPage._onNavigationCommitted (/Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/firefox/ffPage.js:154:34)
    at FFSession.emit (node:events:379:20)
    at /Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/firefox/ffConnection.js:164:47
TypeError: Cannot read property 'childFrames' of undefined
    at FrameManager.removeChildFramesRecursively (/Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/frames.js:234:35)
    at FrameManager.frameCommittedNewDocumentNavigation (/Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/frames.js:122:14)
    at FFPage._onNavigationCommitted (/Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/firefox/ffPage.js:154:34)
    at FFSession.emit (node:events:379:20)
    at /Users/sb/Desktop/code/chat-app/node_modules/playwright/lib/server/firefox/ffConnection.js:164:47
 ```
 
 The problem is app is so huge and error doesn't make any sense as it doesn't show from where it came. I did try console logging and it seems it can happen on any page evaluation.
 
 Is there at least any way to silence this error? I think this error comes from website that has two or more iframes.
 
 Others: I do have following code but it also doesn't work
 ```
 process.on("uncaughtException", (e) => {
    console.log("ignoring uncaught exception", e)
})
```

**Comment by aslushnikov** [comment]
@shirshak55 this is a bug in Playwright. Can you please share a `DEBUG=*protocol*` log of the run with this error?

**Comment by shirshak55** [comment]
closing it till i can reproduce the issue.
