### ISSUE TITLE
[BUG] page.evaluate: Evaluation failed: ReferenceError: __read is not defined

### ISSUE THREAD

**Issue by zhq745w** [microsoft/playwright#5395]
**Context:**
- Playwright Version: 1.8.0
- Operating System: Ubuntu 20.04
- Node.js version: 14.15
- Browser: Chromium
- TypeScript 4.1

**Code Snippet**
```javascript
await page.evaluate(([selector]) => {
      const element = document.querySelector(selector)
      element.scrollIntoView({block: 'center'})
    }, [this._selector])
```

**Describe the bug**
If I use the above code then I get the error
`page.evaluate: Evaluation failed: ReferenceError: __read is not defined
    at eval (eval at callFunction (:307:29), <anonymous>:2:38)
    at UtilityScript.callFunction (<anonymous>:308:24)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
      at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:69:15)
      at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:44:61)
      at /hdd/projects/e2e_sports/node_modules/playwright/lib/client/frame.js:157:48
      at Frame._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:72:34)
      at Frame.evaluate (node_modules/playwright/lib/client/frame.js:156:21)
      at /hdd/projects/e2e_sports/node_modules/playwright/lib/client/page.js:344:60
      at Page._attributeToPage (node_modules/playwright/lib/client/page.js:205:20)
      at Page.evaluate (node_modules/playwright/lib/client/page.js:344:21)
      at UIElement.<anonymous> (app/elements/element.ts:44:22)
      at step (app/elements/element.ts:33:23)
      at Object.next (app/elements/element.ts:14:53)
      at /hdd/projects/e2e_sports/app/elements/element.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (app/elements/element.ts:4:12)
      at UIElement.scrollIntoView (app/elements/element.ts:114:16)
      at Suite.<anonymous> (app/specs/mainpage/mainMobile.ts:47:30)
      at step (app/specs/mainpage/mainMobile.ts:33:23)
      at Object.next (app/specs/mainpage/mainMobile.ts:14:53)
      at /hdd/projects/e2e_sports/app/specs/mainpage/mainMobile.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (app/specs/mainpage/mainMobile.ts:4:12)
      at Context.<anonymous> (app/specs/mainpage/mainMobile.ts:46:38)
      at processImmediate (internal/timers.js:461:21)`

page.evaluate doesn't work with any code

**Comment by zhq745w** [comment]
It was resolved: it was necessary to replace "target": "es5" with "target": "es6" in tsconfig.json
