### ISSUE TITLE
[Question] NW.js crashes when used by Playwright

### ISSUE THREAD

**Issue by TheJaredWilcurt** [microsoft/playwright#5404]
NW.js is a modified chromium browser with Node.js built in. The NW.js API is built in to this modified browser. To test NW.js projects, the code must run within the NW.js environment. This issue was also posted here: https://github.com/nwjs/nw.js/issues/7663.

**NW.js Version:** 0.51.0-sdk
**Operating System:** Win 10

### Expected behavior

Run playwright with custom path pointing to NW.js executable.

### Actual behavior

Crashes.

debug log states:
```
[0124/233623.899:ERROR:resource_bundle.cc(960)] Failed to load C:\Users\wilcurtj\Desktop\playwright2\node_modules\nw\nwjs\chrome_100_percent.pak
Some features may not be available.
[0124/233623.900:ERROR:resource_bundle.cc(960)] Failed to load C:\Users\wilcurtj\Desktop\playwright2\node_modules\nw\nwjs\chrome_200_percent.pak
Some features may not be available.
[0124/233638.941:INFO:child_thread_impl.cc(838)] ChildThreadImpl::EnsureConnected()
```

### How to reproduce

Run playwright and point it to NW.js

```js
const path = require('path');
const { chromium } = require('playwright');

try {
  (async () => {
    const browser = await chromium.launch({
      executablePath: path.resolve(__dirname, 'node_modules/nw/nwjs/nw.exe')
    });
    const page = await browser.newPage();
    // await page.goto('https://nwjs.io');
    await page.screenshot({ path: 'example.png' });

    await browser.close();
  })();
} catch (err) {
  console.log(err);
}
```

**Reproduction attached.**

* [nw-playwright.zip](https://github.com/nwjs/nw.js/files/5864269/nw-playwright.zip)
  * `npm install && npm start` - Runs the desktop app
  * `npm install && npm run play` - Attempts to launch Playwright pointed to NW.js

**Full command line output from reproduction:**

```
(node:14844) UnhandledPromiseRejectionWarning: browserContext.newPage: Protocol error (Target.createTarget): Browser closed.
==================== Browser output: ====================
<launching> C:\nw-playwright\node_modules\nw\nwjs\nw.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=C:\Users\owner\AppData\Local\Temp\playwright_chromiumdev_profile-Ijx831 --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
<launched> pid=10888
[err] [0124/235308.371:ERROR:resource_bundle.cc(960)] Failed to load C:\nw-playwright\node_modules\nw\nwjs\chrome_100_percent.pak
[err] Some features may not be available.
[err] [0124/235308.372:ERROR:resource_bundle.cc(960)] Failed to load C:\nw-playwright\node_modules\nw\nwjs\chrome_200_percent.pak
[err] Some features may not be available.
    at Connection.sendMessageToServer (C:\nw-playwright\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (C:\nw-playwright\node_modules\playwright\lib\client\channelOwner.js:44:61)
    at C:\nw-playwright\node_modules\playwright\lib\client\browserContext.js:95:58
    at ChromiumBrowserContext._wrapApiCall (C:\nw-playwright\node_modules\playwright\lib\client\channelOwner.js:72:34)
    at ChromiumBrowserContext.newPage (C:\nw-playwright\node_modules\playwright\lib\client\browserContext.js:92:21)
    at ChromiumBrowser.newPage (C:\nw-playwright\node_modules\playwright\lib\client\browser.js:58:36)
    at async C:\nw-playwright\play.js:9:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
We *might* look into this later on, but I don't think we have many clients using NW.js, so this is pretty low-pri for us.

**Comment by TheJaredWilcurt** [comment]
I don't think it's currently possible to use it with NW.js, so you wouldn't have anyone using it.

This would unlock the potential *for* people to use it.

This request was on behalf of GitHub user @rkarroll that requested it in the NW.js Gitter chatroom.

**Comment by abflow** [comment]
As mentioned into the NW.js repo, NW.js does not seem to handle well stdio. Thus, the "--remote-debugging-pipe" used by Playwright is not working.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
