### ISSUE TITLE
[BUG] Camera permission throws error for firefox and webkit

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#5445]
**Context:**
- Playwright Version: v1.8.1
- Operating System: Mac
- Node.js version: v14.15.1
- Browser: Firefox and WebKit

**Code Snippet**

```javascript
const { firefox } = require("playwright");

(async () => {
  const browser = await firefox.launch({ headless: false });
  const context = await browser.newContext({ permissions: ["camera"] });
  const page = await context.newPage();

  await page.goto(
    "https://webrtc.github.io/samples/src/content/getusermedia/gum/"
  );
})();
```

```javascript
const { webkit } = require("playwright");

(async () => {
  const browser = await webkit.launch({ headless: false });
  const context = await browser.newContext({ permissions: ["camera"] });
  const page = await context.newPage();

  await page.goto(
    "https://webrtc.github.io/samples/src/content/getusermedia/gum/"
  );
})();
```

**Describe the bug**

```
(node:21866) UnhandledPromiseRejectionWarning: browser.newContext: Unknown permission: camera
    at Connection.sendMessageToServer (/Users/jon/dev/examples/pw-core/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/jon/dev/examples/pw-core/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /Users/jon/dev/examples/pw-core/node_modules/playwright/lib/client/browser.js:43:87
    at async FirefoxBrowser._wrapApiCall (/Users/jon/dev/examples/pw-core/node_modules/playwright/lib/client/channelOwner.js:72:28)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
(node:22049) UnhandledPromiseRejectionWarning: Error: Unknown permission: camera
    at /Users/jon/dev/examples/pw-core/node_modules/playwright/lib/server/webkit/wkPage.js:869:23
    at Array.map (<anonymous>)
    at WKPage._grantPermissions (/Users/jon/dev/examples/pw-core/node_modules/playwright/lib/server/webkit/wkPage.js:866:38)
    at WKPage._initializePageProxySession (/Users/jon/dev/examples/pw-core/node_modules/playwright/lib/server/webkit/wkPage.js:90:22)
    at WKPage._onTargetCreated (/Users/jon/dev/examples/pw-core/node_modules/playwright/lib/server/webkit/wkPage.js:257:26)
    at WKSession.emit (events.js:315:20)
    at /Users/jon/dev/examples/pw-core/node_modules/playwright/lib/server/webkit/wkConnection.js:138:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jperl** [comment]
Related to https://github.com/microsoft/playwright/issues/4959 (this just also notes that Firefox is affected)

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by rahulvramesh** [comment]
am still having this issue.
