### ISSUE TITLE
[Question] I'm trying to open a browser but couldn't

### ISSUE THREAD

**Issue by RamrajSekar** [microsoft/playwright#5584]
Below is my piece of code:

```
from playwright.sync_api import sync_playwright

def run(playwright):
    firefox = playwright.firefox
    browser = firefox.launch()
    page = browser.new_page()
    page.goto("https://example.com")
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```

Error:
```
F:\pyplaywright>C:/Users/ram/AppData/Local/Programs/Python/Python38/python.exe f:/pyplaywright/test.py
Traceback (most recent call last):
  File "C:\Users\ram\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_browser_type.py", line 70, in launch
    return from_channel(await self._channel.send("launch", params))
  File "C:\Users\ram\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 36, in send     
    return await self.inner_send(method, params, False)
  File "C:\Users\ram\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: Failed to launch firefox because executable doesn't exist at C:\Users\ram\AppData\Local\ms-playwright\firefox-1225\firefox\firefox.exe
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:/pyplaywright/test.py", line 11, in <module>
    run(playwright)
  File "f:/pyplaywright/test.py", line 5, in run
    browser = firefox.launch()
  File "C:\Users\ram\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_api\_generated.py", line 10174, in launch
    raise e
  File "C:\Users\ram\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_api\_generated.py", line 10150, in launch
    self._sync(
  File "C:\Users\ram\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_sync_base.py", line 90, in _sync     
    return future.result()
  File "C:\Users\ram\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_browser_type.py", line 73, in launch 
    raise not_installed_error(f'"{self.name}" browser was not found.')
Exception:
================================================================================
"firefox" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================
```

**Comment by RamrajSekar** [comment]
I found the root cause is to mention the execute_path
