### ISSUE TITLE
[BUG] Error: Duplicate target when trying to connectOverCDP next time

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#5648]
Great work on `connectOverCDP` 👍 I am loving the ability to connect to an existing instance rather than launch a new chrome every time.

**Context:**
- Playwright Version: 1.9.1
- Operating System: Mac
- Node.js version: 12.x
- Browser: Chromium

**Code Snippet**

```javascript

const { chromium } = require("playwright");

(async () => {
	const browser = await chromium.connectOverCDP({
                // NOTE: change this with ws URL by launching chrome with CDP
		wsEndpoint: `ws://127.0.0.1: 56685/devtools/browser/a5d5af82-e168-4ebb-8b87-199c3e5dc260`,
	});
	const contexts = browser.contexts();
	const browserContext = contexts[0];
	const page = await browserContext.newPage();
	await page.goto("https://playwright.dev");
})();
```

**Describe the bug**
Error log:

```
[1] app: 2021-02-28T03:57:53.593Z app:debug 1614484673593 -> Chrome Endpoint: ws://127.0.0.1:56685/devtools/browser/a5d5af82-e168-4ebb-8b87-199c3e5dc260
[1] app: 2021-02-28T03:57:53.643Z app:warn 1614484673641 -> Error: Duplicate target 3E6BA14AC5D3C8825FC23623D1B55050
[1] app:     at Object.assert (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/utils/utils.js:80:15)
[1] app:     at CRBrowser._onAttachedToTarget (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crBrowser.js:152:17)
[1] app:     at CRSession.emit (events.js:315:20)
[1] app:     at CRSession.EventEmitter.emit (domain.js:483:12)
[1] app:     at /Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crConnection.js:157:22
[1] app:     at runNextTicks (internal/process/task_queues.js:62:5)
[1] app:     at processImmediate (internal/timers.js:429:9) Promise { <rejected> Error: Duplicate target 3E6BA14AC5D3C8825FC23623D1B55050 at Object.assert (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/utils/utils.js:80:15) at CRBrowser._onAttachedToTarget (/Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crBrowser.js:152:17) at CRSession.emit (events.js:315:20) at CRSession.EventEmitter.emit (domain.js:483:12) at /Users/vikramtiwari/Documents/code/app/packages/node_modules/playwright/lib/server/chromium/crConnection.js:157:22 at runNextTicks (internal/process/task_queues.js:62:5) at processImmediate (internal/timers.js:429:9) }
```

First time connection works properly but next time I try to connect to same WS URL, I see this error.

**Comment by pavelfeldman** [comment]
What do you mean by next time? Is it the same Node program, same Playwright or you run this program twice?

**Comment by VikramTiwari** [comment]
My bad on the description.

I launch chrome with CDP enabled, get the websocket URL and and connect to it using the script in the issue. Then I stop the script and try to reconnect. I haven't stopped running chrome, I haven't changed the websocket URL either.

Essentially I am trying to recreate a scenario of a user connecting to an always up chrome instance on a WS URL.

**Comment by pavelfeldman** [comment]
How do you run Chromium? (which version do you use)

**Comment by VikramTiwari** [comment]
Ah! Could it be happening with chrome and not Chromium? I am using Chrome 88. 

Here's how I launch it:
```bash
'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --remote-debugging-port=56685
```

**Comment by pavelfeldman** [comment]
1.9.1 is saying it uses Chromium 90.0.4421.0

**Comment by pavelfeldman** [comment]
Added a test, closing the bug! Please open a new one in case you have a test / repro!

**Comment by VikramTiwari** [comment]
Fantastic test! I will try to repro it and reopen if need be. Thanks!

**Comment by VikramTiwari** [comment]
Hey @pavelfeldman I have the script which is similar to the test and reproduces the bug.

I launch Chromium 90 with:
```bash
'/Users/vikramtiwari/Library/Caches/ms-playwright/chromium-854489/chrome-mac/Chromium.app/Contents/MacOS/Chromium' --remote-debugging-port=46666
```

Then I run this script

``` js
const { chromium } = require("playwright");

(async () => {
  // change this with WS endpoint that you get by running Chromium with websocket port enabled
  const wsEndpoint = `ws://localhost:46666/devtools/browser/ad6195ca-2177-4cc0-8337-c411a3ead9e9`;

  // create first browser connection
  const cdpBrowser1 = await chromium.connectOverCDP({
    wsEndpoint,
  });
  const contexts1 = cdpBrowser1.contexts();
  const browserContext1 = contexts1[0];
  const page1 = await browserContext1.newPage();
  await page1.goto("https://playwright.dev?page=1");
  cdpBrowser1.close();

  // the script will work if I have next line of code enabled, but will fail if it's disabled
  //   await new Promise((resolve) => setTimeout(resolve, 1000 * 30));

  // create second connection
  const cdpBrowser2 = await chromium.connectOverCDP({
    wsEndpoint,
  });
  const contexts2 = cdpBrowser2.contexts();
  const browserContext2 = contexts2[0];
  const page2 = await browserContext2.newPage();
  await page2.goto("https://playwright.dev?page=2");
})();

```

This script with break if you run it as is. However it works if I enabled that wait time for 30 seconds.

I can't wrap my head around why. Could it be that when the recently added tests launch chromium with `browserType.launchServer` they are passing some flag to force flush some connection data. And if I launch chromium manually then this flush happens at some timeout after disconnect.

**Comment by VikramTiwari** [comment]
Hey @pavelfeldman Can I help with more repro steps here? Or maybe should I open this as a new issue?

**Comment by pavelfeldman** [comment]
I can repro this. It looks like we are attaching to SW twice:

- once as a part of the browser targets discovery
- second time upon page's Target.setAutoAttach

**Comment by selang** [comment]
The bug still exist.
I have found the reason.
If the main page nest iframe.The bugger will be tirggered.
Here's another sample: #5701 .
