### ISSUE TITLE
[BUG] Firefox is failing while testing.

### ISSUE THREAD

**Issue by Xezed** [microsoft/playwright#5684]
**Context:**
- Playwright Version: 1.9.1
- Operating System: Linux
- Browser: All but fails only in Firefox
- Extra: jest-playwright

**Code Snippet**

```javascript
describe('Dashboard', () => {
  it('opens login page', async () => {
    await page.goto('localhost:8080');

    await page.click('text=LOG IN');
  });
});
```

**Describe the bug**

All other browsers except Firefox are working just fine.

```
 FAIL   browser: firefox  tests/login.test.js (5.092 s)
  Dashboard
    ✕ opens login page (3122 ms)

  ● Dashboard › opens login page

    page.click: Protocol error (Runtime.evaluate): Target closed.
    ==================== Browser output: ====================
    <launching> /home/aleksandr/.cache/ms-playwright/firefox-1234/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-2vskIF -juggler-pipe -silent
    <launched> pid=66880
    [out] 
    [out] Juggler listening to the pipe
    [out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
    =========================== logs ===========================
    waiting for selector "text=LOG IN"
    ============================================================
    Note: use DEBUG=pw:api environment variable to capture Playwright logs.Error:

       9 |     await page.goto('localhost:8080');
      10 |
    > 11 |     await page.click('text=LOG IN');
         |                ^
      12 |   });
      13 | });
      14 |

      at Object.captureStackTrace (node_modules/playwright/lib/utils/stackTrace.js:48:19)
      at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:69:48)
      at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:64:61)
      at node_modules/playwright/lib/client/frame.js:279:34
      at Frame._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:77:34)
      at Frame.click (node_modules/playwright/lib/client/frame.js:278:21)
      at node_modules/playwright/lib/client/page.js:447:60
      at Page._attributeToPage (node_modules/playwright/lib/client/page.js:231:20)
      at Page.click (node_modules/playwright/lib/client/page.js:447:21)
      at Object.<anonymous> (tests/login.test.js:11:16)

```

**Comment by pavelfeldman** [comment]
Try debugging: `PWDEBUG=1 npm run test`

**Comment by Xezed** [comment]
I've tried. It's just not allowing to interact with anything. It can just execute `page.goto()` without errors. And after this step `.fill()` or even `click()` causing error. 
Yesterday it just worked like a miracle on a page with same layout but different styles. So weird.

How would you debug it? I'm new to playwright but I'm really excited about this project this is the reason I've pushed my team into adopting it over Cypress :smile: Would like to see more conference participation from you guys where you would explain the internals if it's possible. Watched all of Andrey Lushnikov's meetups on this matter so far :)
Thank you for efforts.

**Comment by pavelfeldman** [comment]
And under PWDEBUG, if you enter `text=LOG IN` into the `Explore` field, the right element will highlight? Playwright can't find 'LOG IN' attached to the DOM. Could you share that part of the DOM hierarchy? Is LOG IN a single text node? (screenshot from DevTools)

**Comment by aslushnikov** [comment]
Closing this due to lack of feedback. If the problem still happens, please re-file the issue with more information so that we can debug this!

**Comment by Xezed** [comment]
I have problems with Nightly again. Maybe your experience can help?

```
describe('Opportunities tests', function () {
  it('should work properly', async () => {
    await page.waitForTimeout(50000000)
  });
});
```

```
aleksandr@aleksandr-desktop:~/work/acceptance_tests$ DEBUG=pw:api npm run test
> acceptance_tests@ test /home/aleksandr/work/acceptance_tests
> jest --forceExit --maxWorkers=2

  pw:api => browserType.connect started +0ms
  pw:api <= browserType.connect succeeded +10ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +7ms
  pw:api => browserContext.newPage started +0ms
  pw:api   navigated to "about:blank" +691ms
  pw:api   navigated to "about:blank" +43ms
  pw:api <= browserContext.newPage succeeded +4ms
  pw:api => page.waitForTimeout started +1s
  pw:api   navigated to "http://localhost:8080/log-in" +12s
  pw:api   "domcontentloaded" event fired +1s
  pw:api   "load" event fired +447ms

 RUNS   browser: firefox  tests/opportunities.test.js
```
I go manually to `localhost:8080` it loads some html and fails. Browser is crushing. How to debug? Other engines are fine.
