### ISSUE TITLE
[BUG] codegen window fails to appear on window as non admin

### ISSUE THREAD

**Issue by gshields** [microsoft/playwright#5802]
*** issue 1
the following command fails:
npx playwright codegen --device="iPhone 11" open wikipedia.org

Here is the output:
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: Couldn't resolve host name
=========================== logs ===========================
navigating to "http://open", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.Error
    at Object.captureStackTrace (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\utils\stackTrace.js:48:19)
    at Connection.sendMessageToServer (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\connection.js:69:48)
    at Proxy.<anonymous> (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\channelOwner.js:64:61)
    at C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\frame.js:102:65
    at Frame._wrapApiCall (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\channelOwner.js:77:34)
    at Frame.goto (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\frame.js:100:21)
    at C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\page.js:296:60
    at Page._attributeToPage (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\page.js:231:20)
    at Page.goto (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\client\page.js:296:21)
    at openPage (C:\Users\f164520\scoop\persist\nodejs\bin\node_modules\playwright\lib\cli\cli.js:283:20)
**** issue 2
the following command does not show the codegen window:
npx playwright codegen --viewport-size 800,600 wikipedia.org

this does work to create python file:
npx playwright codegen --target=python -o pltest.py wikipedia.org

 npx envinfo:
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 9.82 GB / 15.72 GB
  Binaries:
    Node: 15.11.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 7.6.0 - ~\scoop\apps\nodejs\current\npm.CMD
  Managers:
    pip3: 21.0.1 - ~\scoop\apps\python\current\Scripts\pip3.EXE
  Utilities:
    Git: 2.30.2.
  IDEs:
    VSCode: 1.54.1 - C:\Users\f164520\scoop\shims\code.CMD
  Languages:
    Python: 3.9.2
    Python3: 3.9.2
  Browsers:
    Chrome: 89.0.4389.82
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1

**Comment by yury-s** [comment]
Can you check command line you use to launch codegen in the first case as it is trying to navigate to `http://open` rather than wikipedia.org. I could reproduce it only with this line:
```sh
npx playwright codegen --device="iPhone 11" http://open wikipedia.org
```

The second issue sounds similar to #5696, are you also using second monitor by any chance?

**Comment by gshields** [comment]
Yes 2 monitors

**Comment by gshields** [comment]
With and Without "OPEN http:// " both fail with same message.

**Comment by pavelfeldman** [comment]
You should not use `codegen` and `open` in the same command line, they are two independent commands, use either open to open or codegen to codegen.

**Comment by yury-s** [comment]
Closing as the comment above resolves issue 1 and issue 2 is already tracked in #5696
