### ISSUE TITLE
Playwright blocks Event loop

### ISSUE THREAD

**Issue by singamcet** [microsoft/playwright#587]
I am trying an example project with Playwright and Express.js 
My code : 
```
const express = require('express');
const blocked = require('blocked-at');
const app = express();
const PORT = 3000;
const URL = "https://www.cmegroup.com/confluence/pages/viewpage.action?navigatingVersions=true&pageId=78459756"
let browser;

app.get('/execute', async  (req, res) =>{
    console.log("Recieved req")
    let context = await browser.newContext();
    page = await context.newPage();
    await page.goto(URL);
    res.send('Completed')
});
app.listen(PORT, async () => {
    console.log("Starting playwright server")
    browser = await playwright.launch();
   console.log("Started playwright server")
    return;
})
blocked((time, stack, {type, resource}) => {
 console.log(`Blocked for ${time}ms, operation started here:`, stack,"TYPE :",type)
}, {resourcesCap: 100})
```

When I run the code and send 20 concurrent requests with JMeter to the `http://localhost:3000/execute`, I have got the following error 
```
Blocked for 43.53386000061035ms, operation started here: [ '    at Socket.connect (net.js:912:7)',
  '    at Object.connect (net.js:156:17)',
  '    at Object.netConnect [as createConnection] (/home/lenovo/scripts/node_modules/ws/lib/websocket.js:684:14)',
  '    at new ClientRequest (_http_client.js:255:33)',
  '    at request (http.js:42:10)',
  '    at get (http.js:46:13)',
  '    at initAsClient (/home/lenovo/scripts/node_modules/ws/lib/websocket.js:555:31)',
  '    at new WebSocket (/home/lenovo/scripts/node_modules/ws/lib/websocket.js:70:7)',
  '    at Promise (/home/lenovo/scripts/node_modules/playwright-core/lib/platform.js:271:38)',
  '    at new Promise (<anonymous>)',
  '    at Object.createWebSocketTransport (/home/lenovo/scripts/node_modules/playwright-core/lib/platform.js:270:12)',
  '    at createTransport (/home/lenovo/scripts/node_modules/playwright-core/lib/webkit/wkBrowser.js:192:36)',
  '    at Function.connect (/home/lenovo/scripts/node_modules/playwright-core/lib/webkit/wkBrowser.js:43:33)',
  '    at WKBrowserServer.connect (/home/lenovo/scripts/node_modules/playwright-core/lib/server/wkPlaywright.js:42:53)',
  '    at WKBrowserServer.<anonymous> (/home/lenovo/scripts/node_modules/playwright-core/lib/helper.js:55:31)',
  '    at WKPlaywright.launch (/home/lenovo/scripts/node_modules/playwright-core/lib/server/wkPlaywright.js:68:23)' ] TYPE : TCPWRAP
```

After 20 concurrent requests, the next request is queued by the server and take a long time to get the response.
I am running this code on 
* Ubuntu 18
*  node v10.15.1

I've tried switching between firefox, chromium, and WebKit. The same issue happens in all of these browsers, hoping maybe someone can help me out of this.

Thanks in Advance.

**Comment by pavelfeldman** [comment]
From your stack it looks like Node spends more than 50ms establishing the network connection in `net.js`. I'm not familiar with the net.js implementation and why it might block, but there is a fair amount of I/O happening upon connecting to the browser, so establishing 20 connections on the same thread might make Node struggle.

I don't think there is anything actionable for the Playwright in this use case.
