### ISSUE TITLE
[BUG] : Codegen on loading a new page showing error - attaching Video

### ISSUE THREAD

**Issue by Sonu5555** [microsoft/playwright#5915]
**Context:**
- Playwright Version: [1.9.2]
- Operating System: [Windows,]
- Node.js version: [14.15.4]
- Browser: [ Chromium]
- Extra: [11th gen intel,14 inch asus laptop connected to 27 inch screen]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

Below is the error

PS C:\Users\Sonu\Desktop\test> npx playwright codegen letcode.in
(node:18716) UnhandledPromiseRejectionWarning: page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "http://letcode.in", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.Error
    at Object.captureStackTrace (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\utils\stackTrace.js:48:19)       
    at Connection.sendMessageToServer (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\connection.js:69:48)
    at Proxy.<anonymous> (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\channelOwner.js:64:61)
    at C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\frame.js:102:65
    at Frame._wrapApiCall (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\channelOwner.js:77:34)
    at Frame.goto (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\frame.js:100:21)
    at C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\page.js:296:60
    at Page._attributeToPage (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\page.js:231:20)
    at Page.goto (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\client\page.js:296:21)
    at openPage (C:\Users\Sonu\Desktop\test\node_modules\playwright\lib\cli\cli.js:283:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

ISSUE : The above error is found while executing the command itself. Kindly find the attached video. Kindly rename the video to extension .avi
![Untitled 1](https://user-images.githubusercontent.com/76145288/112139323-a2897600-8bf8-11eb-8e79-216ee7aaffa7.gif)

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/5916
