### ISSUE TITLE
[BUG] Firefox browser.close throws `Protocol error (Browser.removeBrowserContext): Browser closed`

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#6020]
**Context:**
- Playwright Version: 1.10, 1.9, ...
- Operating System: Mac, Linux
- Node.js version: 14
- Browser: Firefox
- Original issue: https://github.com/playwright-community/jest-playwright/issues/661

**Code Snippet**

Minimal reproducible:

```javascript
const playwright = require("playwright");

// 1. Install code-server `npm install code-server` and run locally: `npx code-server`
// 2. node test.js

(async () => {
  const browserServer = await playwright.firefox.launchServer()
  const browser = await playwright.firefox.connect({
    wsEndpoint: browserServer.wsEndpoint()
  })
  const context = await browser.newContext();
  const page = await context.newPage()

  await page.goto("http://localhost:8080")
  const title = await page.title()
  console.log({ title })
  try {
    await browser.close()
  } catch(err) {
    console.log("yes here: ↓")
    console.log(err)
  }
  await browserServer.close()
})()
```

This throws at the `browser.close()` statement around 5 of 10 times the following:

```
browser.close: Protocol error (Browser.removeBrowserContext): Browser closed.
==================== Browser output: ====================
<launching> /Users/temporaryadmin/Library/Caches/ms-playwright/firefox-1238/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -headless -profile /var/folders/q8/c1b5lsw56474bw7wrmy0wqw80000gp/T/playwright_firefoxdev_profile-sSHRZ9 -juggler-pipe -silent
<launched> pid=50412
[pid=50412][err] *** You are running in headless mode.
[pid=50412][out] 
[pid=50412][out] Juggler listening to the pipe
[pid=50412][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[pid=50412][out] Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=0.808932) [GFX1-]: Receive IPC close with reason=AbnormalShutdown
[pid=50412][err] Exiting due to channel error.
[pid=50412][out] Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=1.14308) [GFX1-]: Receive IPC close with reason=AbnormalShutdown
[pid=50412][err] Exiting due to channel error.
Error
    at Object.captureStackTrace (/Users/temporaryadmin/development/jest-playwright-repro/node_modules/playwright/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/Users/temporaryadmin/development/jest-playwright-repro/node_modules/playwright/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/Users/temporaryadmin/development/jest-playwright-repro/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/temporaryadmin/development/jest-playwright-repro/node_modules/playwright/lib/client/browser.js:69:31
    at FirefoxBrowser._wrapApiCall (/Users/temporaryadmin/development/jest-playwright-repro/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at FirefoxBrowser.close (/Users/temporaryadmin/development/jest-playwright-repro/node_modules/playwright/lib/client/browser.js:68:24)
    at /Users/temporaryadmin/development/jest-playwright-repro/test.js:18:19
```

**Comment by mxschmitt** [comment]
@Tallyb is it reproducible? Yours sounds more like a Chromium crash and by that a different issue.

**Comment by Tallyb** [comment]
@mxschmitt - it is constant. happened on 2 separate machines (both macs). it is consistent. should I open a separate issue?

**Comment by mxschmitt** [comment]
@Tallyb  yeah would be awesome!

**Comment by pavelfeldman** [comment]
This is still very important, but is not a regression. Looks like this happens if the browser is closed immediately after opening.

**Comment by aslushnikov** [comment]
@mxschmitt Interestingly, I cannot reproduce this on playwright@next - looks like firefox roll has fixed this. Can you please confirm?

**Comment by jsjoeio** [comment]
Using playwright@next, I couldn't reproduce either. I ran it 10 times as well and 10/10 showed expected results.

## Video

https://user-images.githubusercontent.com/3806031/113614857-ecfeef80-9607-11eb-8fb5-8f0d616db986.mov

**Comment by mxschmitt** [comment]
@aslushnikov I can verify that I can't repro on tip-of-tree anymore, seems fixed upstream. Tested 20 times and all worked well.

**Comment by aslushnikov** [comment]
awesome, glad to hear!
