### ISSUE TITLE
electron import playwirght error

### ISSUE THREAD

**Issue by wuyingfeng1992** [microsoft/playwright#6066]
[main:stderr] (node:15416) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\project\browsers.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8643)
    at new Registry (webpack://electrontemplate/./node_modules/playwright-core/lib/utils/registry.js?:215:54)
    at new Playwright (webpack://electrontemplate/./node_modules/playwright-core/lib/server/playwright.js?:46:23)
    at Object.createPlaywright (webpack://electrontemplate/./node_modules/playwright-core/lib/server/playwright.js?:59:12)
    at setupInProcess (webpack://electrontemplate/./node_modules/playwright-core/lib/inprocess.js?:24:37)
    at eval (webpack://electrontemplate/./node_modules/playwright-core/lib/inprocess.js?:42:18)
    at Object../node_modules/playwright-core/lib/inprocess.js (D:\project\electron-vue3-master\dist\main.bundle.js:2413:1)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:15416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pavelfeldman** [comment]
What is your playwright version and how do you use it? I see no such error with Playwright 1.10.

**Comment by pavelfeldman** [comment]
(I was following this doc: https://playwright.dev/docs/api/class-electron)

**Comment by dgozman** [comment]
Closing since we lack the repro scenario. Please comment here if you have repro steps that we can follow.
