### ISSUE TITLE
hello, how I can goto the "https" network, use the codegen，the cert is invalid

### ISSUE THREAD

**Issue by freechenh** [microsoft/playwright#6093]
```
Traceback (most recent call last):
  File "F:/licode/play_wright_demo/demo.py", line 39, in <module>
    run(playwright)
  File "F:/licode/play_wright_demo/demo.py", line 21, in run
    page.goto("https://xxx/#/login")
  File "F:\Program Files (x86)\python3.7\lib\site-packages\playwright\sync_api\_generated.py", line 5777, in goto
    url=url, timeout=timeout, waitUntil=wait_until, referer=referer
  File "F:\Program Files (x86)\python3.7\lib\site-packages\playwright\_impl\_sync_base.py", line 103, in _sync
    return task.result()
  File "F:\Program Files (x86)\python3.7\lib\site-packages\playwright\_impl\_page.py", line 464, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "F:\Program Files (x86)\python3.7\lib\site-packages\playwright\_impl\_frame.py", line 117, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "F:\Program Files (x86)\python3.7\lib\site-packages\playwright\_impl\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "F:\Program Files (x86)\python3.7\lib\site-packages\playwright\_impl\_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: net::ERR_CERT_AUTHORITY_INVALID at "https://xxx/#/login":
=========================== logs ===========================
navigating to ""https://xxx/#/login"/#/login", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Comment by JoelEinbinder** [comment]
Can you explain the steps that you performed to reproduce this issue? Thanks.

You can use [ignoreHTTPSErrors](https://playwright.dev/python/docs/test-runners?_highlight=httpse#ignore-https-errors) to silence any certificate errors.
