### ISSUE TITLE
Google Earth can detect playwright somehow

### ISSUE THREAD

**Issue by defineapoorv** [microsoft/playwright#6209]
I'm trying to get Google Earth to open in headless mode. It works fine in headed mode. But while trying in headless the only time it works is when I run below code in my Mac and only with webkit. It doesn't work with firefox or chromium on my Mac. And it doesn't work at all even with webkit in the docker container of the official playwright image. 

This code works(only in Mac, not in the docker container)
```
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch({
      headless: true
	});
  var link = 'https://earth.google.com/web/@33.83405747,-117.89835255,51.77456494a,140.84823168d,35y,0h,0t,0r'
  console.log(link);
  const page = await browser.newPage();

  await page.goto(link, { waitUntil: 'networkidle' });
  await page.screenshot({ path: 'example.png' });
  splash_screen_xpath = "xpath=//*[@id='splash-screen-frame']"
  await page.waitForSelector(splash_screen_xpath, {state: 'hidden'});
  console.log("WORKED!!");
  await browser.close();
})();
```
In this case the logs are
```
  pw:api waiting for selector "xpath=//*[@id='splash-screen-frame']" to be hidden +4ms
  pw:api   selector resolved to visible <iframe id="splash-screen-frame" src="splashscreen_min.h…></iframe> +60ms
  pw:api   "load" event fired +60ms
  pw:api   navigated to "https://earth.google.com/web/@0,0,0a,22251752.77375655d,35y,0h,0t,0r" +10s
  pw:api   navigated to "https://earth.google.com/web/@0,0,0a,22251752.77375655d,35y,0h,0t,0r" +1s
  pw:api   navigated to "https://earth.google.com/web/@33.83405747,-117.89835255,51.77456494a,140.84823168d,35y,0h,0t,0r" +28ms
  pw:api <= page.waitForSelector succeeded +2s
WORKED!!
```

This code doesn't work anywhere(The chromium doesn't work either)
```
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch({
      headless: true
	});
  var link = 'https://earth.google.com/web/@33.83405747,-117.89835255,51.77456494a,140.84823168d,35y,0h,0t,0r'
  console.log(link);
  const page = await browser.newPage();

  await page.goto(link, { waitUntil: 'networkidle' });
  await page.screenshot({ path: 'example_sand.png' });
  splash_screen_xpath = "xpath=//*[@id='splash-screen-frame']"
  await page.waitForSelector(splash_screen_xpath, {state: 'hidden'});
  console.log("WORKED!!");
  await browser.close();
})();

```
In this the case the logs are
```
 pw:api => page.waitForSelector started +0ms
  pw:api waiting for selector "xpath=//*[@id='splash-screen-frame']" to be hidden +5ms
  pw:api   selector resolved to visible <iframe id="splash-screen-frame" src="splashscreen_min.h…></iframe> +1s
  pw:api <= page.waitForSelector failed +29s
node:internal/process/promises:218
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "xpath=//*[@id='splash-screen-frame']" to be hidden
  selector resolved to visible <iframe id="splash-screen-frame" src="splashscreen_min.h…></iframe>
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/Users/apoorv/node_modules/playwright/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/Users/apoorv/node_modules/playwright/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/Users/apoorv/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/apoorv/node_modules/playwright/lib/client/frame.js:202:42
    at Frame._wrapApiCall (/Users/apoorv/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at Frame.waitForSelector (/Users/apoorv/node_modules/playwright/lib/client/frame.js:197:21)
    at /Users/apoorv/node_modules/playwright/lib/client/page.js:241:60
    at Page._attributeToPage (/Users/apoorv/node_modules/playwright/lib/client/page.js:231:20)
    at Page.waitForSelector (/Users/apoorv/node_modules/playwright/lib/client/page.js:241:21)
    at /Users/apoorv/Documents/housable/google_earth_scraper/test.js:14:14 {
  name: 'TimeoutError'
}

```

Is there any way to bypass this headless browser detection by Google Earth.

**Comment by osolomin90** [comment]
When browser is in headless mode user-agent contains 'headless'.

**Comment by dgozman** [comment]
@defineapoorv It is easy to detect headless browsers. For example, the user agent string is different. It is up to the page to behave differently in this case. If Google Earth chooses to do so, we consider that totally fine.

As @osolomin90 mentions, you can try to use a different user agent string. However, depending on the page, this might not be sufficient.

Playwright is focused on web testing, and we assume that the app under test does not block Playwright 😄 

Does this answer your question?

**Comment by defineapoorv** [comment]
@osolomin90 and @dgozman. Thank you. Yes it does answer it.
