### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by johnsonsamuel** [microsoft/playwright#622]
```js
(node:22062) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
(node:22062) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at stripFragmentFromUrl (/Users/jo20066698/Documents/playwright-project/node_modules/playwright-core/lib/network.js:63:20)
    at new Request (/Users/jo20066698/Documents/playwright-project/node_modules/playwright-core/lib/network.js:82:21)
    at new WKInterceptableRequest (/Users/jo20066698/Documents/playwright-project/node_modules/playwright-core/lib/webkit/wkInterceptableRequest.js:43:24)
    at WKPage._onRequestWillBeSent (/Users/jo20066698/Documents/playwright-project/node_modules/playwright-core/lib/webkit/wkPage.js:493:25)
    at WKSession._sessionListeners.helper_1.helper.addEventListener.e (/Users/jo20066698/Documents/playwright-project/node_modules/playwright-core/lib/webkit/wkPage.js:166:100)
    at emitOne (events.js:116:13)
    at WKSession.emit (events.js:211:7)
    at Promise.resolve.then (/Users/jo20066698/Documents/playwright-project/node_modules/playwright-core/lib/webkit/wkConnection.js:127:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

My code from the actual website used as reference.
```js
const pw = require('playwright');

(async () => {
  const browser = await pw.webkit.launch(); // or 'chromium', 'firefox'
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://www.apple.com/');
  await page.screenshot({ path: 'example2.png' });

  await browser.close();
})();
```

Any help would be appreciated.

**Comment by cbyad** [comment]
```ts
try {  
  await page.goto('https://www.apple.com/');
  await page.screenshot({ path: 'example2.png' });
}
catch(e){
// do something 
}
```

**Comment by JoelEinbinder** [comment]
What version of node are you running?

**Comment by johnsonsamuel** [comment]
> What version of node are you running?

v8.11.2

**Comment by johnsonsamuel** [comment]
> ```ts
> try {  
>   await page.goto('https://www.apple.com/');
>   await page.screenshot({ path: 'example2.png' });
> }
> catch(e){
> // do something 
> }
> ```

Tried that already but no luck :/

**Comment by JoelEinbinder** [comment]
> > What version of node are you running?
> 
> v8.11.2

We currently support node 10 and up. If you upgrade, everything should work. Node 8 has been EOL for about a month now.
