### ISSUE TITLE
[BUG] page.evaluate broken on site

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#6233]
**Context:**
- BAD Playwright Version: 1.10.0
- Operating System: Mac
- Node.js version: 14.15.1
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto("https://mailchimp.com");
  await page.click('[data-behavior="search-overlay"]');
  await page.fill("#actionable-search-bar-input", "audience");
  await page.press("#actionable-search-bar-input", "Enter");
  await page.waitForFunction(() => document.body.innerText.includes("Feedback"));
  await browser.close();
})();
```

**Describe the bug**

```
(node:5377) UnhandledPromiseRejectionWarning: page.waitForFunction: Evaluation failed: TypeError: result.finally is not a function
    at Object.run (<anonymous>:1739:27)
    at eval (eval at evaluate (:303:29), <anonymous>:1:14)
    at UtilityScript.evaluate (<anonymous>:305:22)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
Error
    at Object.captureStackTrace (/Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/frame.js:398:42
    at Frame._wrapApiCall (/Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at Frame.waitForFunction (/Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/frame.js:395:21)
    at /Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/page.js:516:60
    at Page._attributeToPage (/Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/page.js:231:20)
    at Page.waitForFunction (/Users/jon/dev/qawolf/qawolf/node_modules/playwright/lib/client/page.js:516:21)
    at /Users/jon/dev/qawolf/qawolf/repro.js:11:14
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5377) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
Interesting! Cannot reproduce this. Could it be a geolocation-specific issue? Also, did it work for you before in 1.9?

**Comment by jperl** [comment]
Hmm sorry I forgot one line `await browser.close()` at the end which is required for me to repro consistently.

**Comment by jperl** [comment]
This issue exists in 1.10, 1.9 and 1.8

https://user-images.githubusercontent.com/1136652/115298785-24e35800-a11b-11eb-8a93-6ea0c54dc32f.mov

**Comment by dgozman** [comment]
`https://mailchimp.com` overrides `Promise` that is probably missing `finally`. I don't think we can do anything good here, since `waitForFunction` must evaluate in the. page. In this particular case, you can probably use `page.waitForSelector('text=Feedback')` - that will avoid using overridden `Promise`.

**Comment by jperl** [comment]
That makes sense. Thank you

**Comment by rinogo** [comment]
Ah, I figured it out. The site overrides `Promise` with its own object that doesn't provide `Promise.all`.
