### ISSUE TITLE
Running Playwright in Heroku

### ISSUE THREAD

**Issue by diervo** [microsoft/playwright#634]
Today we are running pupeteer in Heroku by using this buildpack:
https://github.com/jontewks/puppeteer-heroku-buildpack

When trying to deploy with playwright with the trivial webkit example (the one described in this repo) I get the following error:

```
(node:4) UnhandledPromiseRejectionWarning: Error: WebKit revision is not downloaded. Run "npm install" or "yarn install"
2020-01-24T19:39:52.135779+00:00 app[web.1]:     at WKPlaywright.launchServer (/app/node_modules/playwright-core/lib/server/wkPlaywright.js:94:23)
2020-01-24T19:39:52.135781+00:00 app[web.1]:     at async WKPlaywright.launch (/app/node_modules/playwright-core/lib/server/wkPlaywright.js:67:24)
2020-01-24T19:39:52.135788+00:00 app[web.1]:     at async /app/index.js:5:19
2020-01-24T19:39:52.135801+00:00 app[web.1]:   -- ASYNC --
2020-01-24T19:39:52.135809+00:00 app[web.1]:     at WKPlaywright.<anonymous> (/app/node_modules/playwright-core/lib/helper.js:54:23)
2020-01-24T19:39:52.135811+00:00 app[web.1]:     at WKPlaywright.launch (/app/node_modules/playwright-core/lib/server/wkPlaywright.js:67:35)
2020-01-24T19:39:52.135813+00:00 app[web.1]:     at WKPlaywright.<anonymous> (/app/node_modules/playwright-core/lib/helper.js:55:31)
2020-01-24T19:39:52.135815+00:00 app[web.1]:     at /app/index.js:5:35
2020-01-24T19:39:52.135823+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:19:3)
2020-01-24T19:39:52.135830+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
2020-01-24T19:39:52.135837+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
2020-01-24T19:39:52.135840+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:811:32)
2020-01-24T19:39:52.135842+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
2020-01-24T19:39:52.135844+00:00 app[web.1]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
2020-01-24T19:39:52.135846+00:00 app[web.1]:   -- ASYNC --
2020-01-24T19:39:52.135848+00:00 app[web.1]:     at WKPlaywright.<anonymous> (/app/node_modules/playwright-core/lib/helper.js:54:23)
2020-01-24T19:39:52.135850+00:00 app[web.1]:     at /app/index.js:5:35
2020-01-24T19:39:52.135852+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:19:3)
2020-01-24T19:39:52.135853+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
2020-01-24T19:39:52.135855+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
2020-01-24T19:39:52.135857+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:811:32)
2020-01-24T19:39:52.135859+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
2020-01-24T19:39:52.135861+00:00 app[web.1]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
2020-01-24T19:39:52.135863+00:00 app[web.1]:     at internal/main/run_main_module.js:17:11
```

Certainly node_modules dependencies are installed otherwise the error would be different. Any ideas what would be missing?

I will keep debugging, but any hint might be useful.

**Comment by JoelEinbinder** [comment]
Does firefox or chromium work?

**Comment by diervo** [comment]
All of them seem to fail.

**Comment by diervo** [comment]
Seems that the root cause is due to the lazy install that playwright does. Without debbuging further seems that heroku will not allow outbound network request at build time.

I assume that the pre-bundling  and coupling on the binaries is something that you guys don't want to do.

**Comment by diervo** [comment]
Final update:

Error: Failed to launch browser! [0124/222837.654075:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox. #0 0x55eb2554a8e9 base::debug::CollectStackTrace() #1 0x55eb254ade13 base::debug::StackTrace::StackTrace() #2 0x55eb254bff45 logging::LogMessage::~LogMessage() #3 0x55eb26f09c1e service_manager::ZygoteHostImpl::Init() #4 0x55eb250a68d0 content::ContentMainRunnerImpl::Initialize() #5 0x55eb250f515a service_manager::Main() #6 0x55eb250a4ed1 content::ContentMain() #7 0x55eb250f3f75 headless::(anonymous namespace)::RunContentMain() #8 0x55eb250f3c1d headless::HeadlessShellMain() #9 0x55eb22be90a7 ChromeMain #10 0x7ff541226b97 __libc_start_main #11 0x55eb22be8eea _start Received signal 6 #0 0x55eb2554a8e9 base::debug::CollectStackTrace() #1 0x55eb254ade13 base::debug::StackTrace::StackTrace() #2 0x55eb2554a431 base::debug::(anonymous namespace)::StackDumpSignalHandler() #3 0x7ff547297890 (/lib/x86_64-linux-gnu/libpthread-2.27.so+0x1288f) #4 0x7ff541243e97 gsignal #5 0x7ff541245801 abort #6 0x55eb25549235 base::debug::BreakDebugger() #7 0x55eb254c03e4 logging::LogMessage::~LogMessage() #8 0x55eb26f09c1e service_manager::ZygoteHostImpl::Init() #9 0x55eb250a68d0 content::ContentMainRunnerImpl::Initialize() #10 0x55eb250f515a service_manager::Main() #11 0x55eb250a4ed1 content::ContentMain() #12 0x55eb250f3f75 headless::(anonymous namespace)::RunContentMain() #13 0x55eb250f3c1d headless::HeadlessShellMain() #14 0x55eb22be90a7 ChromeMain #15 0x7ff541226b97 __libc_start_main #16 0x55eb22be8eea _start r8: 0000000000000000 r9: 00007ffd366f70d0 r10: 0000000000000008 r11: 0000000000000246 r12: 00007ffd366f8398 r13: 00007ffd366f7370 r14: 00007ffd366f83a0 r15: aaaaaaaaaaaaaaaa di: 0000000000000002 si: 00007ffd366f70d0 bp: 00007ffd366f7320 bx: 00007ffd366f7394 dx: 0000000000000000 ax: 0000000000000000 cx: 00007ff541243e97 sp: 00007ffd366f70d0 ip: 00007ff541243e97 efl: 0000000000000246 cgf: 0000000000000033 erf: 0000000000000000 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000 [end of stack trace] Calling _exit(1). Core file will not be generated. TROUBLESHOOTING: https://github.com/Microsoft/playwright/blob/master/docs/troubleshooting.md

**Comment by aslushnikov** [comment]
@diervo The https://github.com/jontewks/puppeteer-heroku-buildpack is doing some magic, like installing dependencies. However, webkit requires a different set of dependencies to run, e.g. check out [our github workflow](https://github.com/microsoft/playwright/blob/master/.github/workflows/webkit.yml).

My bet would be that there's a need for a new `playwright-heroku-buildpack` that adds all the dependencies necessary for all three browsers. 

> I ssh in the dyno and all dependencies and paths seems to be there (playwright-core/.local-chromium/linux-733125/chrome-linux)

Also, can you check that there's also `playwright-core/.local-webkit` and `playwright-core/.local-firefox` folders with binaries? Can you also try running binaries there? (for webkit, please run `pw_run.sh --headless`)

**Comment by pavelfeldman** [comment]
Folding this into #581 and #1085

**Comment by peter** [comment]
@diervo I tried out your testing-heroku-playwright repo and it works awesomely well with Playwright 0.9 but unfortunately it doesn't work with newer versions, i.e. 0.11 and 0.12.1. Currently this is a blocking me from deploying Playwright. I'm hoping to not need to revert back to Puppeteer. Any pointers would be greatly appreciated for deploying Playwright in the cloud, on Heroku or otherwise. The error I get is "Protocol error (Target.setDiscoverTargets): Target closed" cc @aslushnikov 

```
Error: Protocol error (Target.setDiscoverTargets): Target closed.
2020-03-26T13:41:13.423047+00:00 app[web.1]: at /app/node_modules/playwright-core/lib/chromium/crConnection.js:124:63
2020-03-26T13:41:13.423048+00:00 app[web.1]: at new Promise (<anonymous>)
2020-03-26T13:41:13.423049+00:00 app[web.1]: at CRSession.send (/app/node_modules/playwright-core/lib/chromium/crConnection.js:123:16)
2020-03-26T13:41:13.423049+00:00 app[web.1]: at CRSession.<anonymous> (/app/node_modules/playwright-core/lib/helper.js:84:31)
2020-03-26T13:41:13.423049+00:00 app[web.1]: at Function.connect (/app/node_modules/playwright-core/lib/chromium/crBrowser.js:60:21)
2020-03-26T13:41:13.423050+00:00 app[web.1]: at Chromium.launch (/app/node_modules/playwright-core/lib/server/chromium.js:44:53)
2020-03-26T13:41:13.423050+00:00 app[web.1]: at async /app/index.js:23:21 {
```

**Comment by arjun27** [comment]
@peter - the underlying buildpack being used is probably out of date. Specifically, this bit around [system packages](https://github.com/jontewks/puppeteer-heroku-buildpack/blob/master/bin/compile#L34) will need to be updated. The list of updated packages is available in [our docker setup](https://github.com/microsoft/playwright/tree/master/docs/docker). Another option that can be explored is to move away from the buildpack and our docker image directly, since Heroku can work with docker directly.

**Comment by peter** [comment]
@arjun27 thanks, yeah, both of those suggestions make sense. I tried deploying to Heroku with your Dockerfile but couldn't immediately get that to work. I'm not clear on the interplay between Heroku and Docker and my Docker skills are limited in the first place. As far as the second approach of updating packages in the Buildpack I'm confused though. Your official Dockerfile for Playwright only lists three packages as Chromium dependencies (libnss3, libxss1, and libasound2) and they are all included in the Puppeteer buildpack. I don't need Firefox/Webkit for now, just trying to get Chromium to run. The only thing I see missing is nodejs 12, but I think have that covered in my app as I am using two buildpacks for my app:

```
1. heroku/nodejs
2. https://github.com/jontewks/puppeteer-heroku-buildpack
```

**Comment by peter** [comment]
@arjun27 an interesting point of reference is that my tests run just fine without customization on Travis and they appear to be using Ubuntu 14 (Trusty) whereas Heroku defaults to 18 (Bionic) but Ubuntu 16 is available as an alternative. Not sure if that is relevant here. Unfortunately Travis doesn't fit my use case as they can only schedule jobs to run once a day.

**Comment by peter** [comment]
> Folding this into #581 and #1085

@pavelfeldman I think this issue should be re-opened or should I create a New issue? Playwright not working on Heroku (even with Chromium) isnt really covered by the issues you reference, or at least that has to be verified if that is the case.
