### ISSUE TITLE
[Question]  "should download large binary.zip"  not passed when use `npm run test` ?

### ISSUE THREAD

**Issue by RFC2109** [microsoft/playwright#6357]
@yury-s @mxschmitt
I ran the test  "should download large binary.zip" with tip-of-tree.
https://github.com/microsoft/playwright/blob/560bea5f8df79ad2e4c0782af438397ff433e59d/tests/download.spec.ts#L438
When I use `npm run test`, one or two of the tests will fail.
When I use `npm run ctest` , `npm run wtest` or `npm run ftest`, the test passed.
Is this as it should be?

https://github.com/microsoft/playwright/pull/6351
https://github.com/microsoft/playwright/issues/6286
os: windows
log
```
npm run test

> playwright-internal@1.11.0-next test
> folio --config=tests/config/default.config.ts


Running 3 tests using 2 workers
  1) download.spec.ts:438:6 › [chromium] download event should download large binary.zip ===========

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: 1048576
    Received: 262144

      461 |       stream.on('end', () => fulfill(Buffer.concat(bufs)));
      462 |     });
    > 463 |     expect(data.byteLength).toBe(content.byteLength);
          |                             ^
      464 |     expect(data.equals(content)).toBe(true);
      465 |     await page.close();
      466 |   });

        at Spec.fn (E:\projects\playwright\tests\download.spec.ts:463:29)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at WorkerRunner._runTestWithBeforeHooks (E:\projects\playwright\node_modules\folio\out\workerRunner.js:299:13)

download.spec.ts - [webkit] download event should download large binary.zip
_onDownloadCreated {
  pageProxyId: '6',
  frameId: '8.3',
  uuid: '82320d72-d897-4f48-98ea-0e26bab1de54',
  url: 'http://localhost:8913/empty.html'
}
_onDownloadFilenameSuggested {
  uuid: '82320d72-d897-4f48-98ea-0e26bab1de54',
  suggestedFilename: 'binary.zip'
}
_onDownloadFinished { uuid: '82320d72-d897-4f48-98ea-0e26bab1de54', error: '' }
  2) download.spec.ts:438:6 › [firefox] download event should download large binary.zip ============

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: 1048576
    Received: 65536

      461 |       stream.on('end', () => fulfill(Buffer.concat(bufs)));
      462 |     });
    > 463 |     expect(data.byteLength).toBe(content.byteLength);
          |                             ^
      464 |     expect(data.equals(content)).toBe(true);
      465 |     await page.close();
      466 |   });

        at Spec.fn (E:\projects\playwright\tests\download.spec.ts:463:29)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at WorkerRunner._runTestWithBeforeHooks (E:\projects\playwright\node_modules\folio\out\workerRunner.js:299:13)

  1 passed (8s)
  2 failed     
    download.spec.ts:438:6 › [chromium] download event should download large binary.zip ============
    download.spec.ts:438:6 › [firefox] download event should download large binary.zip =============
```

**Comment by RFC2109** [comment]
passed after build
