### ISSUE TITLE
[Question] Will Playwright support Ubuntu 21.04?

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#6405]
Hello, will Playwright support Ubuntu 21.04?
After the update, there are issues with linux packages dependencies, e.g.

> Protocol error (Playwright.enable): Browser closed.
==================== Browser output: ====================
<launching> /home/radek/.cache/ms-playwright/webkit-1446/pw_run.sh --inspector-pipe --no-startup-window
<launched> pid=9568
[pid=9568][err] /home/radek/.cache/ms-playwright/webkit-1446/minibrowser-gtk/bin/MiniBrowser: error while loading shared libraries: libicui18n.so.66: cannot open shared object file: No such file or directory
[pid=9568] <process did exit: exitCode=127, signal=null>Error
    at /home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/server/webkit/wkConnection.js:105:63
    at new Promise (<anonymous>)
    at WKSession.send (/home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/server/webkit/wkConnection.js:104:16)
    at Function.connect (/home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/server/webkit/wkBrowser.js:72:37)
    at WebKit._connectToTransport (/home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/server/webkit/webkit.js:32:38)
    at WebKit._innerLaunch (/home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/server/browserType.js:131:36)
    at async ProgressController.run (/home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/server/progress.js:79:28)
    at async WebKit.launch (/home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/server/browserType.js:78:25)
    at async BrowserServerLauncherImpl.launchServer (/home/radek/Projects/tesena/easy_poc/node_modules/playwright/lib/browserServerImpl.js:58:25)
    at async PlaywrightRunner.launchServer (/home/radek/Projects/tesena/easy_poc/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:68:44)

I tried to use:

`npx playwright install-deps` but received `Cannot install dependencies for this linux distribution!`

Best

RB

**Comment by aslushnikov** [comment]
Yeah that's unfair that we fail here. Let me add a support for this shortly.

Note, however, that we're only validating Playwright on LTS versions of Ubuntu (which are even numbers), so this will be a "best effort"; please reach back to us if things break!

**Comment by aslushnikov** [comment]
The patch is in and will be available tomorrow in the `playwright@next` channel. However, please note that our build of webkit requires a few libraries that aren't available out-of-the box on Ubuntu 21.04, so you'll need to get them somewhere.

Both Chromium & Firefox work fine though.

**Comment by radekBednarik** [comment]
Thanks alot @aslushnikov you guys are great 👍
