### ISSUE TITLE
[BUG] Unable to install playwright

### ISSUE THREAD

**Issue by purificant** [microsoft/playwright#6414]
**Context:**
- Playwright Version: 1.10.0
- Operating System: Linux 5.8 Ubuntu 21.04 (Hirsute Hippo)
- Node.js version: v14.16.1
- Browser: All

Using the [recommended](https://playwright.dev/docs/intro/#installation) way to install playwright fails.
```
npm i -D playwright
```

Failure when installing playwright.
```
npm i -D playwright
npm ERR! code 1
npm ERR! path /home/user/projects/test/node_modules/playwright
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-05-05-debug.log
```
Contents of log file:
```
0 verbose cli [
0 verbose cli   '/snap/node/4150/bin/node',
0 verbose cli   '/home/user/.local/bin/npm',
0 verbose cli   'i',
0 verbose cli   '-D',
0 verbose cli   'playwright'
0 verbose cli ]
1 info using npm@7.11.2
2 info using node@v14.16.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/user/.local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/user/projects/test/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/user/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/user/.local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 11ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 9ms
30 timing idealTree:userRequests Completed in 2ms
31 silly idealTree buildDeps
32 silly fetch manifest playwright@*
33 http fetch GET 304 https://registry.npmjs.org/playwright 212ms (from cache)
34 silly placeDep ROOT playwright@1.10.0 OK for: test@1.0.0 want: *
35 silly fetch manifest commander@^6.1.0
36 silly fetch manifest debug@^4.1.1
37 silly fetch manifest extract-zip@^2.0.1
38 silly fetch manifest https-proxy-agent@^5.0.0
39 silly fetch manifest jpeg-js@^0.4.2
40 silly fetch manifest mime@^2.4.6
41 silly fetch manifest pngjs@^5.0.0
42 silly fetch manifest progress@^2.0.3
43 silly fetch manifest proper-lockfile@^4.1.1
44 silly fetch manifest proxy-from-env@^1.1.0
45 silly fetch manifest rimraf@^3.0.2
46 silly fetch manifest stack-utils@^2.0.3
47 silly fetch manifest ws@^7.3.1
48 http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 62ms (from cache)
49 http fetch GET 304 https://registry.npmjs.org/extract-zip 128ms (from cache)
50 http fetch GET 304 https://registry.npmjs.org/mime 134ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/proxy-from-env 137ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/pngjs 140ms (from cache)
53 http fetch GET 304 https://registry.npmjs.org/rimraf 146ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/commander 153ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/progress 154ms (from cache)
56 http fetch GET 304 https://registry.npmjs.org/proper-lockfile 154ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/ws 152ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/jpeg-js 158ms (from cache)
59 http fetch GET 304 https://registry.npmjs.org/debug 163ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/stack-utils 159ms (from cache)
61 timing idealTree:#root Completed in 402ms
62 silly fetch manifest bufferutil@^4.0.1
63 http fetch GET 304 https://registry.npmjs.org/bufferutil 53ms (from cache)
64 silly fetch manifest utf-8-validate@^5.0.2
65 http fetch GET 304 https://registry.npmjs.org/utf-8-validate 109ms (from cache)
66 silly placeDep ROOT commander@6.2.1 OK for: playwright@1.10.0 want: ^6.1.0
67 silly placeDep ROOT debug@4.3.1 OK for: playwright@1.10.0 want: ^4.1.1
68 silly placeDep ROOT extract-zip@2.0.1 OK for: playwright@1.10.0 want: ^2.0.1
69 silly placeDep ROOT https-proxy-agent@5.0.0 OK for: playwright@1.10.0 want: ^5.0.0
70 silly placeDep ROOT jpeg-js@0.4.3 OK for: playwright@1.10.0 want: ^0.4.2
71 silly placeDep ROOT mime@2.5.2 OK for: playwright@1.10.0 want: ^2.4.6
72 silly placeDep ROOT pngjs@5.0.0 OK for: playwright@1.10.0 want: ^5.0.0
73 silly placeDep ROOT progress@2.0.3 OK for: playwright@1.10.0 want: ^2.0.3
74 silly placeDep ROOT proper-lockfile@4.1.2 OK for: playwright@1.10.0 want: ^4.1.1
75 silly placeDep ROOT proxy-from-env@1.1.0 OK for: playwright@1.10.0 want: ^1.1.0
76 silly placeDep ROOT rimraf@3.0.2 OK for: playwright@1.10.0 want: ^3.0.2
77 silly placeDep ROOT stack-utils@2.0.3 OK for: playwright@1.10.0 want: ^2.0.3
78 silly placeDep ROOT ws@7.4.5 OK for: playwright@1.10.0 want: ^7.3.1
79 silly fetch manifest ms@2.1.2
80 silly fetch manifest @types/yauzl@^2.9.1
81 silly fetch manifest get-stream@^5.1.0
82 silly fetch manifest yauzl@^2.10.0
83 silly fetch manifest agent-base@6
84 silly fetch manifest graceful-fs@^4.2.4
85 silly fetch manifest retry@^0.12.0
86 silly fetch manifest signal-exit@^3.0.2
87 silly fetch manifest glob@^7.1.3
88 silly fetch manifest escape-string-regexp@^2.0.0
89 http fetch GET 304 https://registry.npmjs.org/ms 55ms (from cache)
90 http fetch GET 304 https://registry.npmjs.org/graceful-fs 63ms (from cache)
91 http fetch GET 304 https://registry.npmjs.org/retry 66ms (from cache)
92 http fetch GET 304 https://registry.npmjs.org/signal-exit 66ms (from cache)
93 http fetch GET 304 https://registry.npmjs.org/agent-base 77ms (from cache)
94 http fetch GET 304 https://registry.npmjs.org/glob 76ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/yauzl 81ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/@types%2fyauzl 92ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/get-stream 94ms (from cache)
98 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 93ms (from cache)
99 timing idealTree:node_modules/playwright Completed in 278ms
100 timing idealTree:node_modules/commander Completed in 0ms
101 silly placeDep ROOT ms@2.1.2 OK for: debug@4.3.1 want: 2.1.2
102 timing idealTree:node_modules/debug Completed in 1ms
103 silly placeDep ROOT @types/yauzl@2.9.1 OK for: extract-zip@2.0.1 want: ^2.9.1
104 silly placeDep ROOT get-stream@5.2.0 OK for: extract-zip@2.0.1 want: ^5.1.0
105 silly placeDep ROOT yauzl@2.10.0 OK for: extract-zip@2.0.1 want: ^2.10.0
106 silly fetch manifest @types/node@*
107 silly fetch manifest pump@^3.0.0
108 silly fetch manifest fd-slicer@~1.1.0
109 silly fetch manifest buffer-crc32@~0.2.3
110 http fetch GET 304 https://registry.npmjs.org/pump 48ms (from cache)
111 http fetch GET 304 https://registry.npmjs.org/buffer-crc32 50ms (from cache)
112 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 72ms (from cache)
113 http fetch GET 304 https://registry.npmjs.org/fd-slicer 139ms (from cache)
114 timing idealTree:node_modules/extract-zip Completed in 143ms
115 silly placeDep ROOT @types/node@15.0.2 OK for: @types/yauzl@2.9.1 want: *
116 timing idealTree:node_modules/@types/yauzl Completed in 1ms
117 timing idealTree:node_modules/@types/node Completed in 0ms
118 silly placeDep ROOT pump@3.0.0 OK for: get-stream@5.2.0 want: ^3.0.0
119 silly fetch manifest end-of-stream@^1.1.0
120 silly fetch manifest once@^1.3.1
121 http fetch GET 304 https://registry.npmjs.org/once 53ms (from cache)
122 http fetch GET 304 https://registry.npmjs.org/end-of-stream 55ms (from cache)
123 timing idealTree:node_modules/get-stream Completed in 57ms
124 silly placeDep ROOT agent-base@6.0.2 OK for: https-proxy-agent@5.0.0 want: 6
125 timing idealTree:node_modules/https-proxy-agent Completed in 1ms
126 timing idealTree:node_modules/agent-base Completed in 0ms
127 timing idealTree:node_modules/jpeg-js Completed in 0ms
128 timing idealTree:node_modules/mime Completed in 0ms
129 timing idealTree:node_modules/ms Completed in 0ms
130 timing idealTree:node_modules/pngjs Completed in 0ms
131 timing idealTree:node_modules/progress Completed in 0ms
132 silly placeDep ROOT graceful-fs@4.2.6 OK for: proper-lockfile@4.1.2 want: ^4.2.4
133 silly placeDep ROOT retry@0.12.0 OK for: proper-lockfile@4.1.2 want: ^0.12.0
134 silly placeDep ROOT signal-exit@3.0.3 OK for: proper-lockfile@4.1.2 want: ^3.0.2
135 timing idealTree:node_modules/proper-lockfile Completed in 2ms
136 timing idealTree:node_modules/graceful-fs Completed in 0ms
137 timing idealTree:node_modules/proxy-from-env Completed in 0ms
138 silly placeDep ROOT end-of-stream@1.4.4 OK for: pump@3.0.0 want: ^1.1.0
139 silly placeDep ROOT once@1.4.0 OK for: pump@3.0.0 want: ^1.3.1
140 silly fetch manifest wrappy@1
141 http fetch GET 304 https://registry.npmjs.org/wrappy 56ms (from cache)
142 timing idealTree:node_modules/pump Completed in 61ms
143 timing idealTree:node_modules/end-of-stream Completed in 0ms
144 silly placeDep ROOT wrappy@1.0.2 OK for: once@1.4.0 want: 1
145 timing idealTree:node_modules/once Completed in 1ms
146 timing idealTree:node_modules/retry Completed in 0ms
147 silly placeDep ROOT glob@7.1.6 OK for: rimraf@3.0.2 want: ^7.1.3
148 silly fetch manifest fs.realpath@^1.0.0
149 silly fetch manifest inflight@^1.0.4
150 silly fetch manifest inherits@2
151 silly fetch manifest minimatch@^3.0.4
152 silly fetch manifest path-is-absolute@^1.0.0
153 http fetch GET 304 https://registry.npmjs.org/inflight 53ms (from cache)
154 http fetch GET 304 https://registry.npmjs.org/inherits 61ms (from cache)
155 http fetch GET 304 https://registry.npmjs.org/fs.realpath 68ms (from cache)
156 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 67ms (from cache)
157 http fetch GET 304 https://registry.npmjs.org/minimatch 83ms (from cache)
158 timing idealTree:node_modules/rimraf Completed in 87ms
159 silly placeDep ROOT fs.realpath@1.0.0 OK for: glob@7.1.6 want: ^1.0.0
160 silly placeDep ROOT inflight@1.0.6 OK for: glob@7.1.6 want: ^1.0.4
161 silly placeDep ROOT inherits@2.0.4 OK for: glob@7.1.6 want: 2
162 silly placeDep ROOT minimatch@3.0.4 OK for: glob@7.1.6 want: ^3.0.4
163 silly placeDep ROOT path-is-absolute@1.0.1 OK for: glob@7.1.6 want: ^1.0.0
164 silly fetch manifest brace-expansion@^1.1.7
165 http fetch GET 304 https://registry.npmjs.org/brace-expansion 49ms (from cache)
166 timing idealTree:node_modules/glob Completed in 55ms
167 timing idealTree:node_modules/fs.realpath Completed in 0ms
168 timing idealTree:node_modules/inflight Completed in 0ms
169 timing idealTree:node_modules/inherits Completed in 0ms
170 silly placeDep ROOT brace-expansion@1.1.11 OK for: minimatch@3.0.4 want: ^1.1.7
171 silly fetch manifest balanced-match@^1.0.0
172 silly fetch manifest concat-map@0.0.1
173 http fetch GET 304 https://registry.npmjs.org/concat-map 45ms (from cache)
174 http fetch GET 304 https://registry.npmjs.org/balanced-match 48ms (from cache)
175 timing idealTree:node_modules/minimatch Completed in 49ms
176 silly placeDep ROOT balanced-match@1.0.2 OK for: brace-expansion@1.1.11 want: ^1.0.0
177 silly placeDep ROOT concat-map@0.0.1 OK for: brace-expansion@1.1.11 want: 0.0.1
178 timing idealTree:node_modules/brace-expansion Completed in 1ms
179 timing idealTree:node_modules/balanced-match Completed in 0ms
180 timing idealTree:node_modules/concat-map Completed in 0ms
181 timing idealTree:node_modules/path-is-absolute Completed in 0ms
182 timing idealTree:node_modules/signal-exit Completed in 0ms
183 silly placeDep ROOT escape-string-regexp@2.0.0 OK for: stack-utils@2.0.3 want: ^2.0.0
184 timing idealTree:node_modules/stack-utils Completed in 0ms
185 timing idealTree:node_modules/escape-string-regexp Completed in 0ms
186 timing idealTree:node_modules/wrappy Completed in 0ms
187 timing idealTree:node_modules/ws Completed in 0ms
188 silly placeDep ROOT buffer-crc32@0.2.13 OK for: yauzl@2.10.0 want: ~0.2.3
189 silly placeDep ROOT fd-slicer@1.1.0 OK for: yauzl@2.10.0 want: ~1.1.0
190 silly fetch manifest pend@~1.2.0
191 http fetch GET 304 https://registry.npmjs.org/pend 46ms (from cache)
192 timing idealTree:node_modules/yauzl Completed in 49ms
193 timing idealTree:node_modules/buffer-crc32 Completed in 0ms
194 silly placeDep ROOT pend@1.2.0 OK for: fd-slicer@1.1.0 want: ~1.2.0
195 timing idealTree:node_modules/fd-slicer Completed in 1ms
196 timing idealTree:node_modules/pend Completed in 0ms
197 timing idealTree:buildDeps Completed in 1193ms
198 timing idealTree:fixDepFlags Completed in 1ms
199 timing idealTree Completed in 1207ms
200 timing reify:loadTrees Completed in 1207ms
201 timing reify:diffTrees Completed in 2ms
202 silly reify moves {}
203 timing reify:retireShallow Completed in 0ms
204 timing reify:createSparse Completed in 11ms
205 timing reify:loadBundles Completed in 0ms
206 timing reifyNode:node_modules/buffer-crc32 Completed in 214ms
207 timing reifyNode:node_modules/path-is-absolute Completed in 214ms
208 timing reifyNode:node_modules/brace-expansion Completed in 214ms
209 timing reifyNode:node_modules/inflight Completed in 214ms
210 timing reifyNode:node_modules/wrappy Completed in 214ms
211 timing reifyNode:node_modules/end-of-stream Completed in 213ms
212 timing reifyNode:node_modules/once Completed in 214ms
213 timing reifyNode:node_modules/@types/yauzl Completed in 214ms
214 timing reifyNode:node_modules/ms Completed in 214ms
215 timing reifyNode:node_modules/pend Completed in 217ms
216 timing reifyNode:node_modules/escape-string-regexp Completed in 216ms
217 timing reifyNode:node_modules/inherits Completed in 216ms
218 timing reifyNode:node_modules/stack-utils Completed in 216ms
219 timing reifyNode:node_modules/minimatch Completed in 217ms
220 timing reifyNode:node_modules/balanced-match Completed in 217ms
221 timing reifyNode:node_modules/fs.realpath Completed in 218ms
222 timing reifyNode:node_modules/signal-exit Completed in 217ms
223 timing reifyNode:node_modules/extract-zip Completed in 218ms
224 timing reifyNode:node_modules/pump Completed in 220ms
225 timing reifyNode:node_modules/get-stream Completed in 220ms
226 timing reifyNode:node_modules/yauzl Completed in 222ms
227 timing reifyNode:node_modules/graceful-fs Completed in 222ms
228 timing reifyNode:node_modules/rimraf Completed in 222ms
229 timing reifyNode:node_modules/concat-map Completed in 224ms
230 timing reifyNode:node_modules/progress Completed in 222ms
231 timing reifyNode:node_modules/debug Completed in 222ms
232 timing reifyNode:node_modules/proxy-from-env Completed in 224ms
233 timing reifyNode:node_modules/fd-slicer Completed in 225ms
234 timing reifyNode:node_modules/glob Completed in 225ms
235 timing reifyNode:node_modules/proper-lockfile Completed in 225ms
236 timing reifyNode:node_modules/mime Completed in 224ms
237 timing reifyNode:node_modules/jpeg-js Completed in 225ms
238 timing reifyNode:node_modules/https-proxy-agent Completed in 225ms
239 timing reifyNode:node_modules/agent-base Completed in 226ms
240 timing reifyNode:node_modules/commander Completed in 225ms
241 timing reifyNode:node_modules/retry Completed in 227ms
242 timing reifyNode:node_modules/ws Completed in 228ms
243 timing reifyNode:node_modules/@types/node Completed in 240ms
244 timing reifyNode:node_modules/pngjs Completed in 241ms
245 timing reifyNode:node_modules/playwright Completed in 274ms
246 timing reify:unpack Completed in 277ms
247 timing reify:unretire Completed in 0ms
248 timing build:queue Completed in 2ms
249 timing build:link:node_modules/extract-zip Completed in 2ms
250 timing build:link:node_modules/playwright Completed in 2ms
251 timing build:link:node_modules/rimraf Completed in 2ms
252 timing build:link:node_modules/mime Completed in 2ms
253 timing build:link Completed in 2ms
254 info run playwright@1.10.0 install node_modules/playwright node install.js
255 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 398ms
256 timing auditReport:getReport Completed in 399ms
257 timing auditReport:init Completed in 0ms
258 timing reify:audit Completed in 399ms
259 info run playwright@1.10.0 install { code: 1, signal: null }
260 timing reify:rollback:createSparse Completed in 52ms
261 timing reify:rollback:retireShallow Completed in 0ms
262 timing command:install Completed in 38619ms
263 verbose stack Error: command failed
263 verbose stack     at ChildProcess.<anonymous> (/home/user/.local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
263 verbose stack     at ChildProcess.emit (events.js:315:20)
263 verbose stack     at maybeClose (internal/child_process.js:1048:16)
263 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
264 verbose pkgid playwright@1.10.0
265 verbose cwd /home/user/projects/test
266 verbose Linux 5.8.0-50-generic
267 verbose argv "/snap/node/4150/bin/node" "/home/user/.local/bin/npm" "i" "-D" "playwright"
268 verbose node v14.16.1
269 verbose npm  v7.11.2
270 error code 1
271 error path /home/user/projects/test/node_modules/playwright
272 error command failed
273 error command sh -c node install.js
274 verbose exit 1

```

**Comment by purificant** [comment]
This issue appears to be triggered when installing nodejs on ubuntu via the recommended method through snap.
Switching to a nodesource deb package for nodejs does not produce this issue.

**Comment by purificant** [comment]
Solution: Install nodejs on Ubuntu 21.04 (Hirsute Hippo) via https://github.com/nodesource/distributions
instead of snap. This issue can be closed.
