### ISSUE TITLE
[BUG] Headful Firefox not even open any page

### ISSUE THREAD

**Issue by THE-GAME-YOU-LOST** [microsoft/playwright#6682]
**Context:**
- Playwright Version: playwright 1.11.1
- Operating System: Linux Ubuntu 20.04
- Node.js version: 14.17.0
- Browser: Firefox (Mozilla Firefox 88.0.1)
- Extra: Trying to run headful

**Code Snippet**

```javascript
const { firefox } = require('playwright');

(async () => {
    const browser = await firefox.launch({ headless: false, executablePath:'/usr/bin/firefox' });
    const context = await browser.newContext({viewport:{width:1280, height:720}});
    const page = await context.newPage();
    await page.goto('https://example.com/');
    console.log(JSON.stringify(await context.cookies()));
    await page.waitForTimeout(100000)
    await browser.close();
})();
```

**Describe the bug**

Just trying to open an headful firefox browser but it doesn't work.
Here is the full error log in case anyone needs it:
<details>
<summary>
last error message is glxtest: libEGL missing

CLICK FOR FULL ERROR LOG
</summary>

```
2021-05-20T16:43:24.622Z pw:channel:event {
  guid: '',
  method: '__create__',
  params: {
    type: 'BrowserType',
    initializer: {
      executablePath: '/root/.cache/ms-playwright/chromium-878941/chrome-linux/chrome',
      name: 'chromium'
    },
    guid: 'browser-type@a1cf320baf8d5d7a045a891b0c708196'
  }
}
2021-05-20T16:43:24.625Z pw:channel:event {
  guid: '',
  method: '__create__',
  params: {
    type: 'BrowserType',
    initializer: {
      executablePath: '/root/.cache/ms-playwright/firefox-1250/firefox/firefox',
      name: 'firefox'
    },
    guid: 'browser-type@4e6b5be632b3a10af168848ddc72680b'
  }
}
2021-05-20T16:43:24.625Z pw:channel:event {
  guid: '',
  method: '__create__',
  params: {
    type: 'BrowserType',
    initializer: {
      executablePath: '/root/.cache/ms-playwright/webkit-1472/pw_run.sh',
      name: 'webkit'
    },
    guid: 'browser-type@d788e5c05557a02135f5a1c8af84b0de'
  }
}
2021-05-20T16:43:24.625Z pw:channel:event {
  guid: '',
  method: '__create__',
  params: {
    type: 'Android',
    initializer: {},
    guid: 'android@5e65411d810c33d924337c416280178e'
  }
}
2021-05-20T16:43:24.626Z pw:channel:event {
  guid: '',
  method: '__create__',
  params: {
    type: 'Electron',
    initializer: {},
    guid: 'electron@ecc119665c9f1a27f8e223f02d779e52'
  }
}
2021-05-20T16:43:24.627Z pw:channel:event {
  guid: '',
  method: '__create__',
  params: {
    type: 'Selectors',
    initializer: {},
    guid: 'selectors@af469a0a10bedd127ccb7b08f40b1059'
  }
}
2021-05-20T16:43:24.629Z pw:channel:event {
  guid: '',
  method: '__create__',
  params: {
    type: 'Playwright',
    initializer: {
      chromium: [Object],
      firefox: [Object],
      webkit: [Object],
      android: [Object],
      electron: [Object],
      deviceDescriptors: [Array],
      selectors: [Object],
      preLaunchedBrowser: undefined
    },
    guid: 'Playwright'
  }
}
2021-05-20T16:43:24.631Z pw:api => browserType.launch started
2021-05-20T16:43:24.634Z pw:channel:command {
  id: 1,
  guid: 'browser-type@4e6b5be632b3a10af168848ddc72680b',
  method: 'launch',
  params: {
    executablePath: '/usr/bin/firefox',
    ignoreAllDefaultArgs: false,
    headless: false,
    slowMo: 50
  }
}
2021-05-20T16:43:24.646Z pw:browser <launching> /usr/bin/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-qsta22 -juggler-pipe -silent
2021-05-20T16:43:24.656Z pw:browser <launched> pid=105173
2021-05-20T16:43:24.668Z pw:protocol SEND â–º {"id":1,"method":"Browser.enable","params":{"attachToDefaultContext":false}}
2021-05-20T16:43:24.669Z pw:protocol SEND â–º {"id":2,"method":"Browser.getInfo"}
2021-05-20T16:43:34.837Z pw:browser [pid=105173][out] [GFX1-]: glxtest: libEGL missing
2021-05-20T16:43:34.838Z pw:browser [pid=105173][out] [GFX1-]: glxtest: libEGL missing
2021-05-20T16:43:47.590Z pw:browser [pid=105173] <gracefully close start>
2021-05-20T16:43:47.591Z pw:browser [pid=105173] <kill>
2021-05-20T16:43:47.592Z pw:browser [pid=105173] <will force kill>
2021-05-20T16:43:47.597Z pw:error Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)
2021-05-20T16:43:47.599Z pw:browser [pid=105173] <process did exit: exitCode=0, signal=null>
2021-05-20T16:43:47.638Z pw:browser [pid=105173] <gracefully close end>
2021-05-20T16:43:47.640Z pw:channel:response {
  id: 1,
  error: {
    error: {
      message: 'Protocol error (Browser.enable): Browser closed.\n' +
        '==================== Browser output: ====================\n' +
        '<launching> /usr/bin/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-qsta22 -juggler-pipe -silent\n' +
        '<launched> pid=105173\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '=========================== logs ===========================\n' +
        '<launching> /usr/bin/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-qsta22 -juggler-pipe -silent\n' +
        '<launched> pid=105173\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '============================================================\n' +
        'Note: use DEBUG=pw:api environment variable to capture Playwright logs.',
      stack: 'Protocol error (Browser.enable): Browser closed.\n' +
        '==================== Browser output: ====================\n' +
        '<launching> /usr/bin/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-qsta22 -juggler-pipe -silent\n' +
        '<launched> pid=105173\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '=========================== logs ===========================\n' +
        '<launching> /usr/bin/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-qsta22 -juggler-pipe -silent\n' +
        '<launched> pid=105173\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '[pid=105173][out] [GFX1-]: glxtest: libEGL missing\n' +
        '============================================================\n' +
        'Note: use DEBUG=pw:api environment variable to capture Playwright logs.Error\n' +
        '    at /root/.br/node_modules/playwright/lib/server/firefox/ffConnection.js:55:63\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at FFConnection.send (/root/.br/node_modules/playwright/lib/server/firefox/ffConnection.js:54:16)\n' +
        '    at Function.connect (/root/.br/node_modules/playwright/lib/server/firefox/ffBrowser.js:66:24)\n' +
        '    at Firefox._connectToTransport (/root/.br/node_modules/playwright/lib/server/firefox/firefox.js:65:38)\n' +
        '    at Firefox._innerLaunch (/root/.br/node_modules/playwright/lib/server/browserType.js:133:36)\n' +
        '    at async ProgressController.run (/root/.br/node_modules/playwright/lib/server/progress.js:76:28)\n' +
        '    at async Firefox.launch (/root/.br/node_modules/playwright/lib/server/browserType.js:78:25)\n' +
        '    at async BrowserTypeDispatcher.launch (/root/.br/node_modules/playwright/lib/dispatchers/browserTypeDispatcher.js:30:25)\n' +
        '    at async DispatcherConnection.dispatch (/root/.br/node_modules/playwright/lib/dispatchers/dispatcher.js:232:22)',
      name: 'Error'
    }
  }
}
2021-05-20T16:43:47.640Z pw:api <= browserType.launch failed
(node:105162) UnhandledPromiseRejectionWarning: browserType.launch: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /usr/bin/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-qsta22 -juggler-pipe -silent
<launched> pid=105173
[pid=105173][out] [GFX1-]: glxtest: libEGL missing
[pid=105173][out] [GFX1-]: glxtest: libEGL missing
=========================== logs ===========================
<launching> /usr/bin/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-qsta22 -juggler-pipe -silent
<launched> pid=105173
[pid=105173][out] [GFX1-]: glxtest: libEGL missing
[pid=105173][out] [GFX1-]: glxtest: libEGL missing
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/root/.br/node_modules/playwright/lib/utils/stackTrace.js:50:19)
    at Connection.sendMessageToServer (/root/.br/node_modules/playwright/lib/client/connection.js:65:48)
    at Proxy.<anonymous> (/root/.br/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /root/.br/node_modules/playwright/lib/client/browserType.js:60:67
    at BrowserType._wrapApiCall (/root/.br/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at BrowserType.launch (/root/.br/node_modules/playwright/lib/client/browserType.js:51:21)
    at /root/.br/test3.js:4:35
    at Object.<anonymous> (/root/.br/test3.js:14:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:105162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:105162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

</details>

**Comment by mxschmitt** [comment]
Could you try running if `npx playwright install-deps` fixes your problem? This will install all neccersary dependencies, see here for the docs: https://playwright.dev/docs/cli#install-system-dependencies

**Comment by THE-GAME-YOU-LOST** [comment]
Sorry, I don't know if my mistake, but, the error is that I was specifying the firefox executablePath which was installed by apt-get, removing the executablePath option and using the default playwright was successful.
