### ISSUE TITLE
Error 404 minibrowser-mac-10.13.zip

### ISSUE THREAD

**Issue by nalmeida** [microsoft/playwright#669]
I am facing a error while installing it on mac. The https://playwright2.blob.core.windows.net/builds/webkit/1106/minibrowser-mac-10.13.zip  seems to be returning 404 error. Running the `curl`
```
$ curl -I https://playwright2.blob.core.windows.net/builds/webkit/1106/minibrowser-mac-10.13.zip
HTTP/1.1 404 The specified blob does not exist.
Transfer-Encoding: chunked
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 373aaf99-c01e-004f-0417-d5304a000000
x-ms-version: 2009-09-19
Date: Mon, 27 Jan 2020 13:41:27 GMT

```
## Install log
```
$ npm install playwright

> playwright@0.9.21 install /Users/nicalmei/Work/playwright-teste/node_modules/playwright
> node install.js

Downloading chromium 733125 - 119.2 Mb [====================] 100% 0.0s 
chromium downloaded to /Users/nicalmei/Work/playwright-teste/node_modules/playwright-core/.local-chromium/mac-733125
Downloading firefox 1016 - 67.2 Mb [====================] 100% 0.0s 
firefox downloaded to /Users/nicalmei/Work/playwright-teste/node_modules/playwright-core/.local-firefox/mac-1016
(node:81100) UnhandledPromiseRejectionWarning: Error: Download failed: server returned code 404. URL: https://playwright2.blob.core.windows.net/builds/webkit/1106/minibrowser-mac-10.13.zip
    at response (/Users/nicalmei/Work/playwright-teste/node_modules/playwright-core/lib/server/browserFetcher.js:117:27)
    at ClientRequest.requestCallback (/Users/nicalmei/Work/playwright-teste/node_modules/playwright-core/lib/server/browserFetcher.js:170:13)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
(node:81100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN playwright-teste@1.0.0 No description
npm WARN playwright-teste@1.0.0 No repository field.

+ playwright@0.9.21
added 47 packages from 40 contributors and audited 54 packages in 284.109s
found 0 vulnerabilities
```

**Comment by pavelfeldman** [comment]
We only support macOS 10.14 and 10.15 at the moment. Adding a check into the install script.
