### ISSUE TITLE
[BUG] request.headers() is flaky in Chromium

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#6690]
Looks like `Network.requestWillBeSentExtraInfo` sometimes comes too late and `response.request().headers()` returns incomplete headers.
```
  1) page/page-network-request.spec.ts:84:4 › [chromium] should get the same headers as the server =

    Error: expect(received).toEqual(expected) // deep equality

    - Expected  - 9
    + Received  + 0

      Object {
    -   "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    -   "accept-encoding": "gzip, deflate, br",
    -   "cache-control": "max-age=0",
    -   "connection": "keep-alive",
    -   "host": "localhost:8907",
    -   "sec-fetch-dest": "document",
    -   "sec-fetch-mode": "navigate",
    -   "sec-fetch-site": "none",
    -   "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4500.0 Safari/537.36",
      }

      93 |     const response = await page.goto(server.PREFIX + '/empty.html');
      94 |     // console.log(serverRequest.headers);
    > 95 |     expect(response.request().headers()).toEqual(serverRequest.headers);
         |                                          ^
      96 |     console.log(i + ' - done');
      97 |   }
      98 | });

        at /home/yurys/playwright/tests/page/page-network-request.spec.ts:95:42
        at WorkerRunner._runTestWithBeforeHooks (/home/yurys/playwright/node_modules/folio/out/workerRunner.js:275:13)
```

**Comment by yury-s** [comment]
From the protocol log of a failing run:

```
2021-05-20T22:57:48.833Z pw:protocol ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"CC0A4F44429283E5EDFF539364CD7A21","loaderId":"CC0A4F44429283E5EDFF539364CD7A21","documentURL":"http://localhost:9000/empty.html","request":{"url":"http://localhost:9000/empty.html","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4500.0 Safari/537.36"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"timestamp":771338.547708,"wallTime":1621551468.832934,"initiator":{"type":"other"},"type":"Document","frameId":"6D86FEF1E42168BE24F214A87B0252F6","hasUserGesture":false},"sessionId":"693518446D6F85B95BBCB76B2C24A73F"}
2021-05-20T22:57:48.838Z pw:protocol ◀ RECV {"method":"Network.responseReceived","params":{"requestId":"CC0A4F44429283E5EDFF539364CD7A21","loaderId":"CC0A4F44429283E5EDFF539364CD7A21","timestamp":771338.55244,"type":"Document","response":{"url":"http://localhost:9000/empty.html","status":200,"statusText":"OK","headers":{"Date":"Thu, 20 May 2021 22:57:48 GMT","Transfer-encoding":"chunked"},"headersText":"HTTP/1.1 200 OK\r\nDate: Thu, 20 May 2021 22:57:48 GMT\r\nTransfer-encoding: chunked\r\n\r\n","mimeType":"text/plain","requestHeaders":{"Host":"localhost:9000","Connection":"keep-alive","Cache-Control":"max-age=0","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4500.0 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","Sec-Fetch-Site":"none","Sec-Fetch-Mode":"navigate","Sec-Fetch-User":"?1","Sec-Fetch-Dest":"document","Accept-Encoding":"gzip, deflate, br"},"requestHeadersText":"GET /empty.html HTTP/1.1\r\nHost: localhost:9000\r\nConnection: keep-alive\r\nCache-Control: max-age=0\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4500.0 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nSec-Fetch-Site: none\r\nSec-Fetch-Mode: navigate\r\nSec-Fetch-User: ?1\r\nSec-Fetch-Dest: document\r\nAccept-Encoding: gzip, deflate, br\r\n","connectionReused":true,"connectionId":11,"remoteIPAddress":"127.0.0.1","remotePort":9000,"fromDiskCache":false,"fromServiceWorker":false,"fromPrefetchCache":false,"encodedDataLength":84,"timing":{"requestTime":771338.549233,"proxyStart":-1,"proxyEnd":-1,"dnsStart":-1,"dnsEnd":-1,"connectStart":-1,"connectEnd":-1,"sslStart":-1,"sslEnd":-1,"workerStart":-1,"workerReady":-1,"workerFetchStart":-1,"workerRespondWithSettled":-1,"sendStart":0.379,"sendEnd":0.484,"pushStart":0,"pushEnd":0,"receiveHeadersEnd":0.928},"responseTime":1621551468835.28,"protocol":"http/1.1","securityState":"secure"},"frameId":"6D86FEF1E42168BE24F214A87B0252F6"},"sessionId":"693518446D6F85B95BBCB76B2C24A73F"}
...
2021-05-20T22:57:48.840Z pw:protocol ◀ RECV {"method":"Network.requestWillBeSentExtraInfo","params":{"requestId":"CC0A4F44429283E5EDFF539364CD7A21","associatedCookies":[],"headers":{"Host":"localhost:9000","Connection":"keep-alive","Cache-Control":"max-age=0","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/92.0.4500.0 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","Sec-Fetch-Site":"none","Sec-Fetch-Mode":"navigate","Sec-Fetch-User":"?1","Sec-Fetch-Dest":"document","Accept-Encoding":"gzip, deflate, br"}},"sessionId":"693518446D6F85B95BBCB76B2C24A73F"}
2021-05-20T22:57:48.840Z pw:protocol ◀ RECV {"method":"Network.responseReceivedExtraInfo","params":{"requestId":"CC0A4F44429283E5EDFF539364CD7A21","blockedCookies":[],"headers":{"Date":"Thu, 20 May 2021 22:57:48 GMT","Transfer-encoding":"chunked"},"resourceIPAddressSpace":"Local","headersText":"HTTP/1.1 200 OK\r\nDate: Thu, 20 May 2021 22:57:48 GMT\r\nTransfer-encoding: chunked\r\n\r\n"},"sessionId":"693518446D6F85B95BBCB76B2C24A73F"}

```

**Comment by mxschmitt** [comment]
We also experienced this flake in Python.

**Comment by yury-s** [comment]
Yeah, in java it fails almost every run on the bots.

**Comment by yury-s** [comment]
Given extra implementation complexity we decided to wait for customer reports of the problem and revisit it later if need be.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by dr3adx** [comment]
how can MAJOR issue like this go unnoticed? Where are all the developers that dont give a fuck????

imagine not being able to record proper REQ with software made for TESTING!
LMFAO! I dont need to imagine, @pavelfeldman maybe read an issue next time and use your neurons before u teabag an issue
