### ISSUE TITLE
[BUG] playwright failed to install in CI with proxy configured

### ISSUE THREAD

**Issue by d-koppenhagen** [microsoft/playwright#6739]
**Context:**
- Playwright Version: 1.11.1
- Operating System: linux based VM (Cypress base image with node 14)
- Node.js version: 14
- Browser: Chromium
- Extra: -

** Description **

Executing `npm ci` errors when it comes to the playwright installation process.
I checked my proxy settings which are configured correctly using `HTTP_PROXY` / `HTTPS_PROXY` environment variables.

**Code Snippet - .gilab-ci.yml**

Here is the relevant part in my `.gitlab-ci.yml` file:

```javascript
automatic_test_run:
  image: cypress/base:14
  variables:
    npm_config_cache: '$CI_PROJECT_DIR/.npm'
    HTTP_PROXY: 'http://my-company-proxy:8080'
    HTTPS_PROXY: 'http://my-company-proxy:8080'
    CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
  script:
    - export CYPRESS_BASE_URL=$(cat ${APPLICATION_URL_FILE})
    - npm ci
    - npm run cy:run
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
      - cache/Cypress
      - node_modules
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
```

**Describe the bug**

```
$ npm ci
> fsevents@1.2.13 install /cdaas/build/my-app/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js
Skipping 'fsevents' build as platform linux is not supported
> core-js@3.12.0 postinstall /cdaas/build/my-app/node_modules/@angular-devkit/build-angular/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> core-js@3.11.0 postinstall /cdaas/build/my-app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> playwright@1.11.1 install /cdaas/build/my-app/node_modules/playwright
> node install.js
(node:59) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
Error: connect ETIMEDOUT 13.107.213.45:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
    at /cdaas/build/my-app/node_modules/playwright/lib/install/installer.js:130:19
    at async validateCache (/cdaas/build/my-app/node_modules/playwright/lib/install/installer.js:129:9)
    at async installBrowsersWithProgressBar (/cdaas/build/my-app/node_modules/playwright/lib/install/installer.js:80:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playwright@1.11.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the playwright@1.11.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /cdaas/build/my-app/.npm/_logs/2021-05-25T14_11_56_600Z-debug.log
```

**Comment by yury-s** [comment]
Setting `HTTPS_PROXY` env var to your proxy should work. Can you try running the installation with `DEBUG=https-proxy-agent:*`, maybe [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) that we use internally for downloads via proxy will print something useful.

**Comment by pavelfeldman** [comment]
We need answer to the above in order to address the issue. Please file a new bug and link this one if this still is a problem!
