### ISSUE TITLE
[BUG] browser.newPage() never fulfill or reject

### ISSUE THREAD

**Issue by regseb** [microsoft/playwright#6796]
### System
 - OS: Linux 4.19 OSMC (Open Source Media Center) November 2020 (based on Debian 10.9)
 - Memory: 65.52 MB / 746.71 MB
 - Container: Yes
 - Raspberry Pi 2 Model B Rev 1.1
### Binaries
 - Node: 16.2.0 - /usr/bin/node
 - npm: 7.15.0 - /usr/bin/npm
### Languages
 - Bash: 5.0.3 - /bin/bash
### Browser
 - Chromium: 90.0.4430.212 built on Debian 10.9, running on Debian 10.9 - /usr/bin/chromium
### npmPackages
 - playwright: ^1.11.1 => 1.11.1 

## Code Snippet

```JavaScript
const { chromium } = require('playwright');

(async () => {
    try {
        for (let i = 0; i < 100; ++i) {
            console.log(new Date(), i);
            const browser = await chromium.launch({
                executablePath: '/usr/bin/chromium',
            });
            const page = await browser.newPage();
            await page.close();
            await browser.close();
        }
    } catch (err) {
        console.log(new Date(), err);
    }
})();
```

## Describe the bug

When executing the code snippet, randomly the `browser.newPage()` method never finishes (the promise is neither fulfilled nor rejected). It's the [`await Promise.all(promises);`](https://github.com/microsoft/playwright/blob/v1.11.1/src/server/chromium/crPage.ts#L534) (_server/chromium/crPage.ts_: `FrameSession._initialize()`) line that waits.

I added two `console.log()` before and after:

```JavaScript
console.log("before await Promise.all(promises);", promises);
await Promise.all(promises);
console.log("after await Promise.all(promises);");
```

Here is the result of the command `DEBUG=pw:api node index.js`:

```shell
2021-05-29T14:01:44.540Z 0
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +2s
  pw:api => browser.newContext started +6ms
  pw:api <= browser.newContext succeeded +77ms
  pw:api => browserContext.newPage started +5ms
before await Promise.all(promises); [
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { undefined }, Promise { undefined },
  Promise { <pending> }, Promise { undefined },
  Promise { undefined }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> }
]
after await Promise.all(promises);
  pw:api <= browserContext.newPage succeeded +417ms
  pw:api => page.close started +2ms
  pw:api => browserContext.close started +45ms
  pw:api <= browserContext.close succeeded +31ms
  pw:api <= page.close succeeded +1ms
  pw:api => browser.close started +1ms
  pw:api <= browser.close succeeded +131ms
2021-05-29T14:01:47.775Z 1
...
2021-05-29T14:01:50.751Z 2
...
2021-05-29T14:01:53.728Z 3
  pw:api => browserType.launch started +3ms
  pw:api <= browserType.launch succeeded +2s
  pw:api => browser.newContext started +2ms
  pw:api <= browser.newContext succeeded +31ms
  pw:api => browserContext.newPage started +2ms
before await Promise.all(promises); [
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { undefined }, Promise { undefined },
  Promise { <pending> }, Promise { undefined },
  Promise { undefined }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> }
]
```

When I press _Ctrl+C_:

```
  pw:api <= browserContext.newPage failed +27m
2021-05-29T14:29:12.790Z browserContext.newPage: Protocol error (Page.enable): Target closed.
Error
    at Object.captureStackTrace (/home/osmc/dev/testcase/node_modules/playwright/lib/utils/stackTrace.js:50:19)
    at Connection.sendMessageToServer (/home/osmc/dev/testcase/node_modules/playwright/lib/client/connection.js:65:48)
    at Proxy.<anonymous> (/home/osmc/dev/testcase/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /home/osmc/dev/testcase/node_modules/playwright/lib/client/browserContext.js:140:52
    at BrowserContext._wrapApiCall (/home/osmc/dev/testcase/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at BrowserContext.newPage (/home/osmc/dev/testcase/node_modules/playwright/lib/client/browserContext.js:137:21)
    at Browser.newPage (/home/osmc/dev/testcase/node_modules/playwright/lib/client/browser.js:58:36)
    at async /home/osmc/dev/testcase/index.js:10:26
```

Do you have a tip on how to find out which promise is still pending?

I don't have the problem on another more powerful PC running Ubuntu. I think the problem is that RPI2 has trouble launching Chromium. Playwright would have to reject the promise when the page fails to open (or add a timeout).

**Comment by yury-s** [comment]
> Do you have a tip on how to find out which promise is still pending?

Try running with `DEBUG=pw:protocol,pw:browser` to see which CDP command hangs and whether the browser prints and error to the terminal.

**Comment by pavelfeldman** [comment]
Sorry, Pi is not among the supported platforms currently.

**Comment by regseb** [comment]
@pavelfeldman I don't think it's specific to Raspberry Pi because I also reproduce the bug with an [old laptop](https://support.hp.com/us-en/document/c04937771) running Debian Buster.

I kept searching, but I didn't find anything interesting. After one minute stuck, 13 promises are still pending:

```Shell
[
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { undefined }, Promise { undefined },
  Promise { undefined }, Promise { undefined },
  Promise { undefined }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> }
]
```

Chromium doesn't report any errors that seem to be related to the problem:

```Shell
[0601/225302.625190:INFO:cpu_info.cc(53)] Available number of cores: 4
[0601/225302.625190:INFO:cpu_info.cc(53)] Available number of cores: 4
[0601/225302.626101:VERBOSE1:zygote_main_linux.cc(217)] ZygoteMain: initializing 0 fork delegates
[0601/225302.626101:VERBOSE1:zygote_main_linux.cc(217)] ZygoteMain: initializing 0 fork delegates
[0601/225302.687369:VERBOSE1:webrtc_internals.cc(118)] Could not get the download directory.
[0601/225302.704366:VERBOSE1:configured_proxy_resolution_service.cc(851)] PAC support disabled because there is no system implementation
[0601/225302.719261:VERBOSE1:gpu_init.cc(366)] gl::init::InitializeStaticGLBindingsOneOff failed
[0601/225302.736081:VERBOSE1:configured_proxy_resolution_service.cc(851)] PAC support disabled because there is no system implementation
[0601/225302.745626:VERBOSE1:device_data_manager_x11.cc(216)] X Input extension not available
[0601/225302.759051:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[0601/225302.827307:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
[0601/225302.859764:VERBOSE1:device_data_manager_x11.cc(216)] X Input extension not available
```

@yury-s Here are the logs with the option `DEBUG=pw:protocol,pw:browser`:

```Shell
  pw:browser <launching> /usr/bin/chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/tmp/playwright_chromiumdev_profile-qqJWwf --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window +12ms
  pw:browser <launched> pid=8625 +18ms
  pw:protocol SEND ► {"id":1,"method":"Browser.getVersion"} +120ms
  pw:protocol ◀ RECV {"id":1,"result":{"protocolVersion":"1.3","product":"HeadlessChrome/90.0.4430.212","revision":"@e3cd97fc771b893b7fd1879196d1215b622c2bed","userAgent":"Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/90.0.4430.212 Safari/537.36","jsVersion":"9.0.257.29"}} +2s
  pw:protocol SEND ► {"id":2,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true}} +1ms
  pw:protocol ◀ RECV {"id":2,"result":{}} +4ms
  pw:protocol SEND ► {"id":3,"method":"Target.createBrowserContext","params":{"disposeOnDetach":true}} +9ms
  pw:protocol ◀ RECV {"id":3,"result":{"browserContextId":"255E028F85356ACE648D811D0C231D92"}} +5ms
  pw:protocol SEND ► {"id":4,"method":"Browser.setDownloadBehavior","params":{"behavior":"deny","browserContextId":"255E028F85356ACE648D811D0C231D92","downloadPath":"/tmp/playwright_downloads-rguBu8"}} +3ms
  pw:protocol ◀ RECV {"id":4,"result":{}} +19ms
  pw:protocol SEND ► {"id":5,"method":"Target.createTarget","params":{"url":"about:blank","browserContextId":"255E028F85356ACE648D811D0C231D92"}} +10ms
  pw:protocol ◀ RECV {"method":"Target.attachedToTarget","params":{"sessionId":"B15F53B4DDB1BA549B6D028D187A487C","targetInfo":{"targetId":"29333AAF821DED33345D7B7BC8EDBAC9","type":"page","title":"","url":"","attached":true,"canAccessOpener":false,"browserContextId":"255E028F85356ACE648D811D0C231D92"},"waitingForDebugger":true}} +16ms
  pw:protocol SEND ► {"id":6,"method":"Browser.getWindowForTarget","sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +3ms
  pw:browser [pid=8625][err] [0601/231022.535721:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization +2s
  pw:protocol ◀ RECV {"id":5,"result":{"targetId":"29333AAF821DED33345D7B7BC8EDBAC9"}} +36ms
  pw:protocol ◀ RECV {"id":6,"result":{"windowId":1,"bounds":{"left":0,"top":0,"width":800,"height":600,"windowState":"normal"}},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +7ms
  pw:protocol SEND ► {"id":7,"method":"Page.enable","sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +4ms
  pw:protocol SEND ► {"id":8,"method":"Page.getFrameTree","sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +3ms
  pw:protocol SEND ► {"id":9,"method":"Log.enable","params":{},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":10,"method":"Page.setLifecycleEventsEnabled","params":{"enabled":true},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +3ms
  pw:protocol SEND ► {"id":11,"method":"Runtime.enable","params":{},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":12,"method":"Page.addScriptToEvaluateOnNewDocument","params":{"source":"","worldName":"__playwright_utility_world__"},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":13,"method":"Network.enable","sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":14,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":15,"method":"Emulation.setFocusEmulationEnabled","params":{"enabled":true},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":16,"method":"Emulation.setDeviceMetricsOverride","params":{"mobile":false,"width":1280,"height":720,"screenWidth":1280,"screenHeight":720,"deviceScaleFactor":1,"screenOrientation":{"angle":90,"type":"landscapePrimary"}},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":17,"method":"Browser.setWindowBounds","params":{"windowId":1,"bounds":{"width":1280,"height":720}},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":18,"method":"Emulation.setEmulatedMedia","params":{"media":"","features":[{"name":"prefers-color-scheme","value":"light"}]},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +2ms
  pw:protocol SEND ► {"id":19,"method":"Runtime.runIfWaitingForDebugger","sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +3ms
before await Promise.all(promises); [
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { undefined }, Promise { undefined },
  Promise { <pending> }, Promise { undefined },
  Promise { undefined }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> }
]
  pw:browser [pid=8625][err] [0601/231022.597450:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled +81ms
  pw:protocol ◀ RECV {"id":17,"result":{},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +18ms
```

When I press _Ctrl+C_:

```Shell
pw:browser [pid=8625] <gracefully close start> +2m
  pw:protocol ◀ RECV {"id":-9999,"result":{}} +2m
  pw:protocol ◀ RECV {"id":14,"result":{},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +5ms
  pw:protocol ◀ RECV {"method":"Network.loadingFailed","params":{"requestId":"CBA32B04DB6ABD83E02270FAD3706A12","timestamp":356572.156746,"type":"Document","errorText":"net::ERR_ABORTED","canceled":true},"sessionId":"B15F53B4DDB1BA549B6D028D187A487C"} +5ms
  pw:protocol ◀ RECV {"method":"Target.detachedFromTarget","params":{"sessionId":"B15F53B4DDB1BA549B6D028D187A487C","targetId":"29333AAF821DED33345D7B7BC8EDBAC9"}} +6ms
2021-06-01T21:12:05.624Z browserContext.newPage: Protocol error (Page.enable): Target closed.
Error
    at Object.captureStackTrace (/home/osmc/dev/testcase/node_modules/playwright/lib/utils/stackTrace.js:50:19)
    at Connection.sendMessageToServer (/home/osmc/dev/testcase/node_modules/playwright/lib/client/connection.js:65:48)
    at Proxy.<anonymous> (/home/osmc/dev/testcase/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /home/osmc/dev/testcase/node_modules/playwright/lib/client/browserContext.js:140:52
    at BrowserContext._wrapApiCall (/home/osmc/dev/testcase/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at BrowserContext.newPage (/home/osmc/dev/testcase/node_modules/playwright/lib/client/browserContext.js:137:21)
    at Browser.newPage (/home/osmc/dev/testcase/node_modules/playwright/lib/client/browser.js:58:36)
    at async /home/osmc/dev/testcase/index.js:11:26
  pw:browser [pid=8625] <process did exit: exitCode=0, signal=null> +108ms
  pw:browser [pid=8625] <gracefully close end> + 
```

The system doesn't seem to lack RAM, but the CPU is busy. Here are two snapshots, when Playwright works normally:

```Shell
top - 23:15:35 up 4 days,  3:06,  2 users,  load average: 1,86, 1,34, 1,17
Tasks: 117 total,   3 running, 113 sleeping,   0 stopped,   1 zombie
%Cpu(s): 37,5 us, 13,7 sy,  0,6 ni, 47,8 id,  0,1 wa,  0,0 hi,  0,2 si,  0,0 st
MiB Mem :    746,7 total,     94,8 free,    428,4 used,    223,5 buff/cache
MiB Swap:      0,0 total,      0,0 free,      0,0 used.    258,5 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
10024 osmc      20   0  240144  69288  61780 S  34,3   9,1   0:01.04 chromium
  376 osmc      20   0  847728 270892  15936 S  22,4  35,4   1233:44 kodi.bin
 9678 osmc      20   0  156664  44520  29124 S  17,8   5,8   0:06.03 node
10037 osmc      20   0  216772  12424  10816 R   8,9   1,6   0:00.27 chromium
10038 osmc      20   0  216772  12472  10868 R   8,9   1,6   0:00.27 chromium
...
```

And when promises are blocked:

```Shell
top - 23:18:46 up 4 days,  3:09,  2 users,  load average: 0,97, 1,05, 1,07
Tasks: 119 total,   2 running, 116 sleeping,   0 stopped,   1 zombie
%Cpu(s): 26,3 us,  6,6 sy,  0,4 ni, 66,6 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
MiB Mem :    746,7 total,     72,6 free,    450,5 used,    223,6 buff/cache
MiB Swap:      0,0 total,      0,0 free,      0,0 used.    236,3 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 8906 osmc      20   0  346900  52348  42680 R  85,9   6,8   0:21.28 chromium
 8868 osmc      20   0  386624  82912  74536 S  26,6  10,8   0:07.96 chromium
  376 osmc      20   0  847728 270892  15936 S  20,1  35,4   1233:04 kodi.bin
...
```
