### ISSUE TITLE
[BUG] page.goto: Timeout exceeded on the first test case when running tests in Github Actions CI

### ISSUE THREAD

**Issue by thecodrr** [microsoft/playwright#6804]
**Context:**
- Playwright Version: 1.11.1
- Operating System: Linux
- Node.js version: 16.x
- Browser: All
- Extra: Github CI

**Code Snippet**

I don't think it is an issue in my code because all tests pass consistently on my own machine.

`jest-playwright.config.js:`

```js
module.exports = {
  launchOptions: {
    headless: true,
    timeout: 10000,
  },
  serverOptions: {
    command: `yarn debug`,
    port: 3000
  },
  browsers: ["chromium", "firefox", "webkit"],
};
```

**Describe the bug**

When running playwright tests in Github Actions, the first one always fails with `page.goto: Timeout 30000ms exceeded.`

Do note that this is a React app and the tests are run using `jest-playwright`. I also tried removing the `--runInBand` flag; no difference. The first test case always results in this error.

Github Action Log:
```
2021-05-31T03:17:50.4605239Z yarn run v1.22.10
2021-05-31T03:17:50.5210267Z $ REACT_APP_CI=true BROWSER= jest --runInBand -c jest.e2e.config.js
2021-05-31T03:17:51.5130823Z 
2021-05-31T03:17:51.5133280Z Jest dev-server output:
2021-05-31T03:17:51.7193737Z [Jest Process Manager] $ BROWSER=none react-scripts start
2021-05-31T03:17:53.2643822Z (node:4342) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/runner/work/notesnook-web/notesnook-web/node_modules/postcss-safe-parser/node_modules/postcss/package.json.
2021-05-31T03:17:53.2646313Z Update this package.json to use a subpath pattern like "./*".
2021-05-31T03:17:53.2648163Z (Use `node --trace-deprecation ...` to show where the warning was created)
2021-05-31T03:17:53.6449330Z [Jest Process Manager] [34mℹ[39m [90m｢wds｣[39m: Project is running at http://10.1.1.18/
2021-05-31T03:17:53.6454495Z [Jest Process Manager] [34mℹ[39m [90m｢wds｣[39m: webpack output is served from 
2021-05-31T03:17:53.6456632Z [34mℹ[39m [90m｢wds｣[39m: Content not from webpack is served from /home/runner/work/notesnook-web/notesnook-web/public
2021-05-31T03:17:53.6458897Z [34mℹ[39m [90m｢wds｣[39m: 404s will fallback to /
2021-05-31T03:17:53.6460309Z [Jest Process Manager] Starting the development server...
2021-05-31T03:17:53.6461082Z 
2021-05-31T03:18:57.5252498Z [Jest Process Manager] Compiled successfully!
2021-05-31T03:18:57.5253637Z [Jest Process Manager] 
2021-05-31T03:18:57.5254626Z You can now view notesnook in the browser.
2021-05-31T03:18:57.5255287Z 
2021-05-31T03:18:57.5256365Z [Jest Process Manager]   Local:            http://localhost:3000
2021-05-31T03:18:57.5257685Z   On Your Network:  http://10.1.1.18:3000
2021-05-31T03:18:57.5258677Z [Jest Process Manager] 
2021-05-31T03:18:57.5259745Z Note that the development build is not optimized.
2021-05-31T03:18:57.5261041Z [Jest Process Manager] To create a production build, use yarn build.
2021-05-31T03:18:57.5261785Z 
2021-05-31T03:20:25.7770723Z FAIL browser: chromium __e2e__/notes.test.js (149.18 s)
2021-05-31T03:20:25.7776720Z   ● run tests independently › create a note
2021-05-31T03:20:25.7784646Z 
2021-05-31T03:20:25.7785994Z     page.goto: Timeout 30000ms exceeded.
2021-05-31T03:20:25.7787670Z     =========================== logs ===========================
2021-05-31T03:20:25.7789034Z     navigating to "http://localhost:3000/", waiting until "load"
2021-05-31T03:20:25.7790328Z     ============================================================
2021-05-31T03:20:25.7792314Z     Note: use DEBUG=pw:api environment variable to capture Playwright logs.
2021-05-31T03:20:25.7793284Z 
2021-05-31T03:20:25.7794264Z       189 |       await page.close();
2021-05-31T03:20:25.7795377Z       190 |       page = await browser.newPage();
2021-05-31T03:20:25.7796589Z     > 191 |       await page.goto("http://localhost:3000/");
2021-05-31T03:20:25.7797664Z           |                  ^
2021-05-31T03:20:25.7798532Z       192 |     } else {
2021-05-31T03:20:25.7799544Z       193 |       // only navigate to Home if we are not at home
2021-05-31T03:20:25.7800966Z       194 |       if ((await page.textContent(getTestId("routeHeader"))) !== "Notes")
2021-05-31T03:20:25.7801838Z 
2021-05-31T03:20:25.7803158Z       at Object.captureStackTrace (node_modules/playwright/lib/utils/stackTrace.js:50:19)
2021-05-31T03:20:25.7805056Z       at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:65:48)
2021-05-31T03:20:25.7806860Z       at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:64:61)
2021-05-31T03:20:25.7808266Z       at node_modules/playwright/lib/client/frame.js:102:65
2021-05-31T03:20:25.7809949Z       at Frame._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:77:34)
2021-05-31T03:20:25.7811774Z       at Frame.goto (node_modules/playwright/lib/client/frame.js:100:21)
2021-05-31T03:20:25.7813171Z       at node_modules/playwright/lib/client/page.js:303:60
2021-05-31T03:20:25.7814632Z       at Page._attributeToPage (node_modules/playwright/lib/client/page.js:238:20)
2021-05-31T03:20:25.7816148Z       at Page.goto (node_modules/playwright/lib/client/page.js:303:21)
2021-05-31T03:20:25.7817469Z       at Object.<anonymous> (__e2e__/notes.test.js:191:18)
2021-05-31T03:20:25.7818741Z 
2021-05-31T03:22:16.3339365Z PASS browser: firefox __e2e__/notes.test.js (110.504 s)
2021-05-31T03:24:22.8995576Z PASS browser: webkit __e2e__/notes.test.js (126.526 s)
2021-05-31T03:24:47.3802895Z PASS browser: chromium __e2e__/notebooks.test.js (24.464 s)
2021-05-31T03:25:16.8933547Z PASS browser: firefox __e2e__/notebooks.test.js (29.486 s)
2021-05-31T03:25:52.5709755Z PASS browser: webkit __e2e__/notebooks.test.js (35.67 s)
2021-05-31T03:25:58.0881968Z PASS browser: chromium __e2e__/navigation.test.js (5.501 s)
2021-05-31T03:26:06.3362603Z PASS browser: firefox __e2e__/navigation.test.js (8.23 s)
2021-05-31T03:26:13.1844521Z PASS browser: webkit __e2e__/navigation.test.js (6.834 s)
2021-05-31T03:26:13.4845736Z 
2021-05-31T03:26:13.4858507Z Test Suites: 1 failed, 8 passed, 9 of 3 total
2021-05-31T03:26:13.4859926Z Tests:       1 failed, 9 skipped, 119 passed, 129 total
2021-05-31T03:26:13.4861221Z Snapshots:   51 passed, 51 total
2021-05-31T03:26:13.4862309Z Time:        499.698 s
2021-05-31T03:26:13.4863341Z Ran all test suites.
2021-05-31T03:26:13.6261126Z error Command failed with exit code 1.
2021-05-31T03:26:13.6262827Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-05-31T03:26:13.6326133Z ##[error]Process completed with exit code 1.
```

**Comment by pavelfeldman** [comment]
Please file this against https://github.com/playwright-community/jest-playwright. jest-playwright is a community-driven project. Also note, that with 1.12 we are going to be releasing our own e2e test runner that was designed specifically for e2e testing with Playwright in mind. Stay tuned.
