### ISSUE TITLE
[Question] Can't launch specific Safari on Mac

### ISSUE THREAD

**Issue by wanghongjuan** [microsoft/playwright#7007]
Hi all,

I don't know how to resolve this problem, please help me, many thanks.

**Context:**
- Playwright Version: 1.11.1
- Operating System: Mac
- Node.js version: 16.1.0
- Browser: Safari v14.1

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await webkit.launch({
    headless: false,
    viewport: null,
    executablePath: '/Applications/Safari.app/Contents/MacOS/Safari'
  });
  const page = await browser.newPage();
  page.goto("https://playwright.dev/docs/browsers/#webkit")
})();
```

**Describe the bug**
The browser cannot open the url and throws a "TimeourError" error. Please refer to the log below. If I start Safari separately from the terminal, the same error log marked as `[pid=11654][err]` will be output, but the browser Can work normally:

```
webpnp@webpnps-MBP general % node main.js

browserType.launchPersistentContext: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /Applications/Safari.app/Contents/MacOS/Safari --inspector-pipe --user-data-dir=/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/userData about:blank
<launched> pid=11654
[pid=11654][err] objc[11654]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f1979160) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1506682b8). One of the two will be used. Which one is undefined.
[pid=11654][err] objc[11654]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f19791b0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x150668308). One of the two will be used. Which one is undefined.
[pid=11654][err] 2021-06-09 15:47:27.661 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:27.661 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:27.668 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:27.668 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:29.090 Safari[11654:397828] +[NSSavePanel _warmUp] attempted warmup
[pid=11654][err] 2021-06-09 15:47:47.757 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:47.757 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:47.815 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:47.815 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:51.399 Safari[11654:397828] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/utils/stackTrace.js:50:19)
    at Connection.sendMessageToServer (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/connection.js:65:48)
    at Proxy.<anonymous> (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/channelOwner.js:64:61)
    at /Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/browserType.js:82:42
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BrowserType._wrapApiCall (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/channelOwner.js:77:28) {
  name: 'TimeoutError'
}
[W24.3] Auto test failed on Mac-Apple M1
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

browserType.launchPersistentContext: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /Applications/Safari.app/Contents/MacOS/Safari --inspector-pipe --user-data-dir=/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/userData about:blank
<launched> pid=11654
[pid=11654][err] objc[11654]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f1979160) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1506682b8). One of the two will be used. Which one is undefined.
[pid=11654][err] objc[11654]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f19791b0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x150668308). One of the two will be used. Which one is undefined.
[pid=11654][err] 2021-06-09 15:47:27.661 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:27.661 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:27.668 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:27.668 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:29.090 Safari[11654:397828] +[NSSavePanel _warmUp] attempted warmup
[pid=11654][err] 2021-06-09 15:47:47.757 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:47.757 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:47.815 Safari[11654:397828] nil host used in call to allowsSpecificHTTPSCertificateForHost
[pid=11654][err] 2021-06-09 15:47:47.815 Safari[11654:397828] nil host used in call to allowsAnyHTTPSCertificateForHost:
[pid=11654][err] 2021-06-09 15:47:51.399 Safari[11654:397828] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/utils/stackTrace.js:50:19)
    at Connection.sendMessageToServer (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/connection.js:65:48)
    at Proxy.<anonymous> (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/channelOwner.js:64:61)
    at /Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/browserType.js:82:42
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BrowserType._wrapApiCall (/Users/webpnp/hj/frameworks.web.pnp.tools.web-pnp-automation/general/node_modules/playwright-webkit/lib/client/channelOwner.js:77:28) {
  name: 'TimeoutError',
  code: 'ESTREAM',
  command: 'API'
}

```

**Comment by mxschmitt** [comment]
It's not possible to use Safari with Playwright since Playwright has a custom WebKit build to make the automation possible. The same for Firefox.
Internally Safari is based on WebKit, so using WebKit should be fine in most use-cases.

**Comment by wanghongjuan** [comment]
OK, many thanks for your clarification @mxschmitt
