### ISSUE TITLE
globalSetup doesn't run before all tests

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/playwright#7029]
## Description

`globalSetup` should run before any tests run. However, it seems like `@playwright/test` is running the test (or checking the code) before running the test. This means that even though I define `globalSetup` in my `config.ts` file then set `process.env.STORAGE` and try to use it in a test, playwright thinks it's undefined and exits the runner. 

## Reproduction 

Here is the [repo](https://github.com/jsjoeio/playwright-test-repro). 

1. `git clone https://github.com/jsjoeio/playwright-test-repro.git`
2. `yarn`
3. `yarn test`

### Expected

Global setup should run _then_ tests should run 

### Actual

`@playwright/test` runs tests first:
```js
Error while reading /Users/jp/Dev/playwright-test-repro/hello.test.ts:
Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/jp/Dev/playwright-test-repro/hello.test.ts:8:29
    at describe (/Users/jp/Dev/playwright-test-repro/node_modules/folio/out/spec.js:127:9)
    at Object.<anonymous> (/Users/jp/Dev/playwright-test-repro/hello.test.ts:3:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/Users/jp/Dev/playwright-test-repro/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .ts] (/Users/jp/Dev/playwright-test-repro/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Loader.loadTestFile (/Users/jp/Dev/playwright-test-repro/node_modules/folio/out/loader.js:60:13)
    at runTests (/Users/jp/Dev/playwright-test-repro/node_modules/folio/out/cli.js:130:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
```

**Comment by mxschmitt** [comment]
Closing for now. Small summary: Yes in your case it runs multiple times. its because in your global setup, you have 

`import { PASSWORD } from "./constants"`

which will call the constants.ts

The `constants.ts` gets also called in the tests. Once you call it via the `globalSetup.ts`, it does not have the storage environment variable set. Thats why you end up in getting an error that `process.env.STORAGE` is not set.
