### ISSUE TITLE
[BUG] Getting no video frame error for mobile chrome

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#7058]
**Context:**
- Playwright Version: 1.12.1
- Operating System: Mac
- Node.js version: 12.20
- Browser: Chromium
- Extra: Pixel 2 emulation

**Code Snippet**

```javascript
// foo.spec.js
test('Find a title (desktop only)', async ({ page, isMobile }) => {
  if (isMobile) {
    // This feature does not exist in mobile browsers
    return;
  }
};
```
```javascript
// playwright.config.js
projects: [
    {
      name: 'Pixel 2',
      use: {
        browserName: 'chromium',
        ...devices['Pixel 2'],
      },
    },
    {
      name: 'iPhone 11',
      use: {
        browserName: 'webkit',
        ...devices['iPhone 11'],
      },
    },
  ]
```

**Describe the bug**
I have a test where I want to skip execution if the device is a mobile. Using device like `Pixel 2`, `Pixel 4`, the test returns an error `Error: Page did not produce any video frames` while it just passes on `iPhone 11` device

![Screen Shot 2021-06-10 at 6 51 42 PM](https://user-images.githubusercontent.com/22205721/121619164-f8fa9980-ca1c-11eb-9b78-d932ad8d92a9.png)
Add any other details about the problem here.
```javascript
// logs

Error: Page did not produce any video frames

      1 | const { test, expect } = require('@playwright/test');
      2 |
      3 | test('Find a title(desktop only)', async ({ page, isMobile }) => {

        at Video.path (/Users/test/test/test/test/node_modules/@playwright/test/lib/client/video.js:40:19)
        at /test/test/test/test/test/node_modules/@playwright/test/lib/test/index.js:174:35
        at async Promise.all (index 0)
        at Object.context [as fn] (/test/test/test/test/test/node_modules/@playwright/test/lib/test/index.js:170:13)
        at Fixture.teardown (/test/test/test/test/test/node_modules/@playwright/test/lib/test/fixtures.js:96:13)
        at FixtureRunner.teardownScope (/test/test/test/test/test/node_modules/@playwright/test/lib/test/fixtures.js:219:17)
        at WorkerRunner._runAfterHooks (/test/test/test/test/test/node_modules/@playwright/test/lib/test/workerRunner.js:320:13)
```

**Comment by pavelfeldman** [comment]
I can't reproduce this, but I see how this can happen. While I'm fixing it, a couple of hints for your files:

1. You don't need to pass `browserName` since you already pass the device, it'll pick the right engine
1. Use test.skip
```js
test("basic test", async ({ page, isMobile }) => {
  test.skip(isMobile);
});
```

**Comment by pavelfeldman** [comment]
I can reproduce with `video: 'retain-on-failure'`

**Comment by Nav-2d** [comment]
Thank you. `test.skip` fits my use-case.
