### ISSUE TITLE
[BUG][firefox] page loading issue after navigating 

### ISSUE THREAD

**Issue by Paramesh82** [microsoft/playwright#7078]
**Context:**
- Playwright Version: 1.12.1
- Operating SystemWindows
- Node.js version: 
- Browser: Firefox
- 
page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-id='GridRoot'] [data-id='CommandBar']" to be visible
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\utils\stackTrace.js:51:19)
at Connection.sendMessageToServer (D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\connection.js:69:48)
at Proxy.<anonymous> (D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\channelOwner.js:64:61)
at D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\frame.js:193:42
at Frame._wrapApiCall (D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\channelOwner.js:77:34)
at Frame.waitForSelector (D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\frame.js:188:21)
at D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\page.js:212:60
at Page._attributeToPage (D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\page.js:202:20)
at Page.waitForSelector (D:\a_work\1\s\node_modules.pnpm\playwright@1.12.1\node_modules\playwright\lib\client\page.js:212:21)
at Object.waitForGridHomePageLoad (D:\a_work\1\s\src\pages\grid\integration-tests\gridUtils.ts:186:13)
at Object.<anonymous> (D:\a_work\1\s\src\pages\apps\integration-tests\appModule.test.ts:36:3)>

This used to work on 1.11.1version but started failing in 1.12.1

**Comment by mxschmitt** [comment]
Would it be possible that you can create a small reproducible for us? Otherwise its hard to support you. See here how to debug it: https://playwright.dev/docs/debug

Also using the `DEBUG=pw:api` environment variable would help you to find out why it does not find the element.

**Comment by Paramesh82** [comment]
Above issue got resolved. it could be related to below issue once updated  from 1.12.1 to 1.12.2 
https://github.com/microsoft/playwright/issues/7015
