### ISSUE TITLE
[BUG] Async function passed to page.waitForFunction throws

### ISSUE THREAD

**Issue by TC-mSundaram** [microsoft/playwright#7187]
**Context:**
- Playwright Version: 1.12.2
- Operating System: Mac
- Node.js version: v12.18.3
- Browser: Chromium
- Extra: -

**Code Snippet**

```javascript
const profileURL = 'localhost:3000/profile';
const { chromium } = playwright;

const browser = await chromium.launch();
const context = await browser.newContext();
const page = await context.newPage();

(async () => {
  await page.goto(profileURL);
  await page.waitForFunction(async () => {
    const profileName = await page.innerText('[aria-label="profile name"]');
    return !profileName.includes('Loading');
  });
})();
```

**Describe the bug**

When using the above async function as the argument to `page.watiForFunction` I am getting the following error

```
    page.waitForFunction: Evaluation failed: ReferenceError: __awaiter is not defined

      at eval (eval at predicate (eval at evaluate (:303:29)), <anonymous>:1:16)
      at predicate (eval at evaluate (:303:29), <anonymous>:5:30)
      at eval (eval at evaluate (:303:29), <anonymous>:18:78)
      at onRaf (<anonymous>:1667:37)
      at Object.run (<anonymous>:1735:28)
      at eval (eval at evaluate (:303:29), <anonymous>:1:14)
      at UtilityScript.evaluate (<anonymous>:305:22)
      at UtilityScript.<anonymous> (<anonymous>:1:44)page.waitForFunction: Evaluation failed: ReferenceError: __awaiter is not defined
      at eval (eval at predicate (eval at evaluate (:303:29)), <anonymous>:1:16)
      at predicate (eval at evaluate (:303:29), <anonymous>:5:30)
      at eval (eval at evaluate (:303:29), <anonymous>:18:78)
      at onRaf (<anonymous>:1667:37)
      at Object.run (<anonymous>:1735:28)
      at eval (eval at evaluate (:303:29), <anonymous>:1:14)
      at UtilityScript.evaluate (<anonymous>:305:22)
      at UtilityScript.<anonymous> (<anonymous>:1:44)
      at Object.captureStackTrace (node_modules/playwright/lib/utils/stackTrace.js:51:19)
      at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:69:48)
      at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:64:61)
      at node_modules/playwright/lib/client/frame.js:389:42
      at Frame._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:77:34)
      at Frame.waitForFunction (node_modules/playwright/lib/client/frame.js:386:21)
      at node_modules/playwright/lib/client/page.js:491:60
      at Page._attributeToPage (node_modules/playwright/lib/client/page.js:202:20)
      at Page.waitForFunction (node_modules/playwright/lib/client/page.js:491:21)
      at test/e2e/userLogin.spec.ts:12:24
      at step (test/e2e/userLogin.spec.ts:33:23)
      at Object.next (test/e2e/userLogin.spec.ts:14:53)
      at fulfilled (test/e2e/userLogin.spec.ts:5:58)
```

Is there something wrong with my setup, or is this a bug? The type definition for `PageFunction` as the first argument to `page.waitForFunction` has the following signature:

```ts
// playwright/types/structs.d.ts
export type PageFunction<Arg, R> = string | ((arg: Unboxed<Arg>) => R | Promise<R>);
```

So it seems that it should accept an async function there.

**Comment by pavelfeldman** [comment]
What's inside your `waitForFunction` runs inside the page, similarly to evaluate in [this doc](https://playwright.dev/docs/core-concepts#execution-contexts-playwright-and-browser). So in the end you are trying to evaluate

```js
const profileName = await page.innerText('[aria-label="profile name"]')
```
inside your page, which does not exist.

Another issue is this __awaiter. It looks like your ES compilation target is older than async/await (really old). So it ends up compiling async/await into plain old JavaScript. And then it is sent to the browser for execution w/o the definition for this __awaiter. Solution to this is to use a modern compilation target, like `"target": "ES2019"` in your tsconfig.

**Comment by TC-mSundaram** [comment]
@pavelfeldman Thanks very much! Both your points got me onto the right track.
