### ISSUE TITLE
[BUG]page.goto: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Paramesh82** [microsoft/playwright#7290]
**Context:**
- Playwright Version: 1.12.2
- Operating System:  Windows
- Node.js version: 
- Browser:  Chromium,
- Extra: [any specific details about your environment]

```
page.goto: net::ERR_NAME_NOT_RESOLVED at http://AuroraVXXXXX.AuroraVXXXXXdom.extest.microsoft.com/apps
=========================== logs ===========================
navigating to "http://AuroraVXXXXX.AuroraVXXXXXdom.extest.microsoft.com/apps", waiting until "networkidle"
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error:
at Object.captureStackTrace (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\utils\stackTrace.js:51:19)
at Connection.sendMessageToServer (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\connection.js:69:48)
at Proxy.<anonymous> (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\channelOwner.js:64:61)
at C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\frame.js:100:65
at Frame._wrapApiCall (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\channelOwner.js:77:34)
at Frame.goto (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\frame.js:98:21)
at C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\page.js:267:60
at Page._attributeToPage (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\page.js:202:20)
at Page.goto (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.12.2\node_modules\playwright\lib\client\page.js:267:21)
at navigateToUrl (C:\Playwright-31_work\6\s\src\integration-tests\utils\appUtils.ts:203:13)
at getAppInfo (C:\Playwright-31_work\6\s\src\integration-tests\utils\appUtils.ts:121:8)
at getAppLink (C:\Playwright-31_work\6\s\src\integration-tests\utils\appUtils.ts:106:28)
at Object.navigateToApp (C:\Playwright-31_work\6\s\src\integration-tests\utils\appUtils.ts:289:24)
at Object.<anonymous> (C:\Playwright-31_work\6\s\src\features\settings\integration-tests\personalSetting.test.ts:32:9)
at Promise.then.completed (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\utils.js:316:28)
at new Promise (<anonymous>)
at callAsyncCircusFn (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\utils.js:241:10)
at _callCircusTest (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\run.js:218:40)
at _runTest (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\run.js:155:3)
at _runTestsForDescribeBlock (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\run.js:90:7)
at _runTestsForDescribeBlock (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\run.js:60:9)
at run (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\run.js:25:3)
at runAndTransformResultsToJestFormat (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:166:21)
at jestAdapter (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@27.0.4\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:82:19)
at runTestInternal (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-runner@27.0.4\node_modules\jest-runner\build\runTest.js:389:16)
at runTest (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-runner@27.0.4\node_modules\jest-runner\build\runTest.js:481:34)

```

**Code Snippet**

```ts
export async function navigateToUrl(page: Page, navigationUrl: string, waitToLoadDomContent = true): Promise {
// Navigate to the required URL.
const loadState = isOnPremiseEnvironment ? LoadState.NetworkIdle : LoadState.Load;
await page.goto(navigationUrl, { waitUntil: loadState, timeout: 0 });

// Wait until dom-content is loaded successfully upto max 1 minute.
if (waitToLoadDomContent) await waitForDomContentLoad(page);
}

```

**Describe the bug**

The issue is reproducing only for Playwright runs but not for selenium runs in the pipeline.

During Playwright tests pipeline run, tests are running sequentially one by one & the issue does not occur for all the tests. At first, some of the tests are passed and then some of the tests failed with this issue and again other remaining tests are passed. It's an intermittent issue and not occurred for each pipeline run.

We have collected the Playwright runtime logs for the failed test run as below 

```
Comment [6/21/2021 1:20:01 PM]: Navigate to the required URL - http://XXXXXXXXXXXX.XXXXXXXXXXXXdom.XXXXXX.microsoft.com/apps
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: SEND ► {"id":136746,"method":"Runtime.evaluate","params":{"expression":"window[\"__playwright_snapshot_streamer_9f66f2bc6b383a720a00e1cf56d80907\"].captureSnapshot(\"before@call@36\")","contextId":1,"returnByValue":true},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"id":136746,"result":{"result":{"type":"object","value":{"html":["HTML",{},["HEAD",{},["BASE",{"href":"about:blank"}]],["BODY"]],"resourceOverrides":[],"viewport":{"width":1280,"height":800},"url":"about:blank","timestamp":177.79999999981374,"collectionTime":0.900000000372529}}},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: SEND ► {"id":136747,"method":"Page.navigate","params":{"url":"http://XXXXXXXXXXXX.XXXXXXXXXXXXdom.XXXXXX.microsoft.com/apps","frameId":"DA76C27F23C53A969D2D3263CC4AAF41"},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"8376CB42178FB1BADF097EFED37C5724","loaderId":"8376CB42178FB1BADF097EFED37C5724","documentURL":"http://XXXXXXXXXXXX.XXXXXXXXXXXXdom.XXXXXX.microsoft.com/apps","request":{"url":"http://XXXXXXXXXXXX.XXXXXXXXXXXXdom.XXXXXX.microsoft.com/apps","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4530.0 Safari/537.36"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"timestamp":5747.492808,"wallTime":1624281601.032203,"initiator":{"type":"other"},"type":"Document","frameId":"DA76C27F23C53A969D2D3263CC4AAF41","hasUserGesture":false},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.screencastFrame","params":{"data":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//9k=","metadata":{"offsetTop":0,"pageScaleFactor":1,"deviceWidth":1280,"deviceHeight":800,"scrollOffsetX":0,"scrollOffsetY":0,"timestamp":1624281601.022877},"sessionId":1},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: SEND ► {"id":136748,"method":"Page.screencastFrameAck","params":{"sessionId":1},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"method":"Fetch.requestPaused","params":{"requestId":"interception-job-12500.0","request":{"url":"http://XXXXXXXXXXXX.XXXXXXXXXXXXdom.XXXXXX.microsoft.com/apps","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4530.0 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"},"initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"DA76C27F23C53A969D2D3263CC4AAF41","resourceType":"Document","networkId":"8376CB42178FB1BADF097EFED37C5724"},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: SEND ► {"id":136749,"method":"Fetch.continueRequest","params":{"requestId":"interception-job-12500.0"},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"id":136748,"result":{},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"id":136749,"result":{},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.screencastFrame","params":{"data":"//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//9k=","metadata":{"offsetTop":0,"pageScaleFactor":1,"deviceWidth":1280,"deviceHeight":800,"scrollOffsetX":0,"scrollOffsetY":0,"timestamp":1624281601.039796},"sessionId":1},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: SEND ► {"id":136750,"method":"Page.screencastFrameAck","params":{"sessionId":1},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"id":136750,"result":{},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"5EC696EEC16CCBB33EF89FB14A0D4101","loaderId":"80363830E3AD9358F4394A633A821C4E","name":"networkAlmostIdle","timestamp":5747.029653},"sessionId":"900ADB90C70CCA2C0C80CA9CFAD019F0"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"5EC696EEC16CCBB33EF89FB14A0D4101","loaderId":"80363830E3AD9358F4394A633A821C4E","name":"firstMeaningfulPaint","timestamp":5747.057777},"sessionId":"900ADB90C70CCA2C0C80CA9CFAD019F0"}
Comment [6/21/2021 1:20:01 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"5EC696EEC16CCBB33EF89FB14A0D4101","loaderId":"80363830E3AD9358F4394A633A821C4E","name":"networkIdle","timestamp":5747.029653},"sessionId":"900ADB90C70CCA2C0C80CA9CFAD019F0"}
Comment [6/21/2021 1:20:02 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"DA76C27F23C53A969D2D3263CC4AAF41","loaderId":"1650BDCD226E59714351A7477A7A0E8E","name":"networkAlmostIdle","timestamp":5747.447032},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:02 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"DA76C27F23C53A969D2D3263CC4AAF41","loaderId":"1650BDCD226E59714351A7477A7A0E8E","name":"networkIdle","timestamp":5747.447032},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:05 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"3C68EB74339D19EFFE543B4BE04D75BA","loaderId":"90D16C87EC405B0051A56E6E88645AE2","name":"InteractiveTime","timestamp":5751.544482},"sessionId":"0A7AE514499CF931CC4ABEEAE02B45A9"}
Comment [6/21/2021 1:20:05 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"5EC696EEC16CCBB33EF89FB14A0D4101","loaderId":"80363830E3AD9358F4394A633A821C4E","name":"InteractiveTime","timestamp":5752.060195},"sessionId":"900ADB90C70CCA2C0C80CA9CFAD019F0"}
### **Comment [6/21/2021 1:20:12 PM]: Name: protocol, Message: ◀ RECV {"method":"Network.loadingFailed","params":{"requestId":"8376CB42178FB1BADF097EFED37C5724","timestamp":5758.535837,"type":"Document","errorText":"net::ERR_NAME_NOT_RESOLVED","canceled":false},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:12 PM]: Name: protocol, Message: ◀ RECV {"id":136747,"result":{"frameId":"DA76C27F23C53A969D2D3263CC4AAF41","loaderId":"8376CB42178FB1BADF097EFED37C5724","errorText":"net::ERR_NAME_NOT_RESOLVED"},"sessionId":"12130EE2049522E70947A74B48219FA4"}**
Comment [6/21/2021 1:20:12 PM]: Name: protocol, Message: SEND ► {"id":136751,"method":"Runtime.evaluate","params":{"expression":"window[\"__playwright_snapshot_streamer_9f66f2bc6b383a720a00e1cf56d80907\"].captureSnapshot(\"after@call@36\")","contextId":1,"returnByValue":true},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:12 PM]: Name: protocol, Message: ◀ RECV {"method":"Runtime.executionContextsCleared","params":{},"sessionId":"12130EE2049522E70947A74B48219FA4"}
Comment [6/21/2021 1:20:12 PM]: Name: protocol, Message: ◀ RECV {"method":"Page.frameStartedLoading","params":{"frameId":"DA76C27F23C53A969D2D3263CC4AAF41"},"sessionId":"12130EE2049522E70947A74B48219FA4"}
```

**Comment by aslushnikov** [comment]
@Paramesh82 so for some reason, the URL you're navigating to is not accessible for Chromium. Could it be that sometimes the service is down?

**Comment by mxschmitt** [comment]
Closing since the issue seems stale. Please create a new issue if you still face any issues.

**Comment by Sammeeey** [comment]
I'm getting the same error after requesting similar URLs of the same domain subsequently (5-15 times).
At some point Chrome (or something from the *target* site) seems to deny the requests.
If I request the same URL after the script stopped (due to the error), the site is available again.

**Comment by Gamma-Software** [comment]
@Sammeeey +1

**Comment by eifcgn24** [comment]
Strange, I just crated a project with 1.47.0 Playwright and tried to run example tests and "chromium" had this error, "firefox" did not. Now they both show the same error trying to access "https://playwright.dev/". But I can access this link with my own browsers...

**Comment by cheese0409** [comment]
same here, encountered this error after running 80 cases during test, the following cases are failed. But I can access the website using my local browser.

**Comment by karneaud** [comment]
+1
