### ISSUE TITLE
win10 After running the playwright codegen command, run it again and report an error

### ISSUE THREAD

**Issue by 000xiaoxiao000** [microsoft/playwright#7293]
playwright version 1.12.1
ms-playwright\chromium-888113
ms-playwright\firefox-1271
ms-playwright\webkit-1492
ms-playwright\ffmpeg-1005

```
playwright codegen baidu.com
browserType.launch: Host system is missing dependencies!

Full list of missing libraries:
    msvcp90.dll
    msvcr90.dll

Error
    at Object.captureStackTrace (d:\Python39\Lib\site-packages\playwright\driver\package\lib\utils\stackTrace.js:51:19)
    at Connection.sendMessageToServer (d:\Python39\Lib\site-packages\playwright\driver\package\lib\client\connection.js:69:48)
    at Proxy.<anonymous> (d:\Python39\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:64:61)
    at d:\Python39\Lib\site-packages\playwright\driver\package\lib\client\browserType.js:59:67
    at BrowserType._wrapApiCall (d:\Python39\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:77:34)
    at BrowserType.launch (d:\Python39\Lib\site-packages\playwright\driver\package\lib\client\browserType.js:50:21)
    at launchContext (d:\Python39\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:314:39)
    at codegen (d:\Python39\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:415:62)
    at Command.<anonymous> (d:\Python39\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:98:5)
    at Command.listener [as _actionHandler] (d:\Python39\Lib\site-packages\playwright\driver\package\node_modules\commander\index.js:426:31)
    at Command._parseCommand (d:\Python39\Lib\site-packages\playwright\driver\package\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (d:\Python39\Lib\site-packages\playwright\driver\package\node_modules\commander\index.js:953:18)
    at Command._parseCommand (d:\Python39\Lib\site-packages\playwright\driver\package\node_modules\commander\index.js:970:12)
    at Command.parse (d:\Python39\Lib\site-packages\playwright\driver\package\node_modules\commander\index.js:801:10)
    at Object.<anonymous> (d:\Python39\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:285:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by aslushnikov** [comment]
It looks like you need to install Visual C++ redistributable packages from here: 
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by 000xiaoxiao000** [comment]
> It looks like you need to install Visual C++ redistributable packages from here:
> https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

The problem is not solved

**Comment by 000xiaoxiao000** [comment]
python -m playwright codegen baidu.com
page.goto: net::ERR_EMPTY_RESPONSE at http://baidu.com
=========================== logs ===========================
navigating to "http://baidu.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\utils\stackTrace.js:51:19)
    at Connection.sendMessageToServer (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\connection.js:69:48)
    at Proxy.<anonymous> (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:64:61)
    at D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\frame.js:100:65
    at Frame._wrapApiCall (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:77:34)
    at Frame.goto (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\frame.js:98:21)
    at D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\page.js:267:60
    at Page._attributeToPage (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\page.js:202:20)
    at Page.goto (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\page.js:267:21)
    at openPage (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:397:20)
    at async codegen (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:425:5)

**Comment by aslushnikov** [comment]
I saw your recent bug - did you make it work?

**Comment by 000xiaoxiao000** [comment]
> I saw your recent bug - did you make it work?
msvcp90.dll, msvcr90.dll, What is the working directory of these two files?
It is very strange that after "python -m playwright install" command execution, the first time to execute the "playwright codegen baidu.com" command can record normally, the second time to execute the "playwright codegen baidu.com" will report the above said wrong.

**Comment by 000xiaoxiao000** [comment]
(node:17004) UnhandledPromiseRejectionWarning: browserType.launch: Host system is missing dependencies!

Full list of missing libraries:
    msvcp90.dll
    msvcr90.dll

Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (C:\snapshot\playwright-cli\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (C:\snapshot\playwright-cli\node_modules\playwright\lib\client\channelOwner.js:44:61)
    at C:\snapshot\playwright-cli\node_modules\playwright\lib\client\browserType.js:61:73
    at BrowserType._wrapApiCall (C:\snapshot\playwright-cli\node_modules\playwright\lib\client\channelOwner.js:72:34)
    at BrowserType.launch (C:\snapshot\playwright-cli\node_modules\playwright\lib\client\browserType.js:52:21)
    at launchContext (C:\snapshot\playwright-cli\lib\cli.js:177:39)
    at codegen (C:\snapshot\playwright-cli\lib\cli.js:315:75)
    at Command.<anonymous> (C:\snapshot\playwright-cli\lib\cli.js:82:5)
    at Command.listener [as _actionHandler] (C:\snapshot\playwright-cli\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\snapshot\playwright-cli\node_modules\commander\index.js:1002:14)
(node:17004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without
a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI f
lag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termi
nate the Node.js process with a non-zero exit code.

**Comment by 000xiaoxiao000** [comment]
You need to copy these two files msvcp90.dll and msvcr90.dll to C:\Windows\System32.

**Comment by 000xiaoxiao000** [comment]
You need to copy these two files msvcp90.dll and msvcr90.dll to C:\Windows\System32.
