### ISSUE TITLE
page.goto: net::ERR_EMPTY_RESPONSE at http://baidu.com

### ISSUE THREAD

**Issue by 000xiaoxiao000** [microsoft/playwright#7314]
playwright version 1.12.1
ms-playwright\chromium-888113
ms-playwright\firefox-1271
ms-playwright\webkit-1492
ms-playwright\ffmpeg-1005

```
python -m playwright codegen baidu.com
page.goto: net::ERR_EMPTY_RESPONSE at http://baidu.com
=========================== logs ===========================
navigating to "http://baidu.com", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\utils\stackTrace.js:51:19)
    at Connection.sendMessageToServer (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\connection.js:69:48)
    at Proxy.<anonymous> (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:64:61)
    at D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\frame.js: 100:65
    at Frame._wrapApiCall (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:77:34)
    at Frame.goto (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\frame.js:98:21)
    at D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\page.js:267:60
    at Page._attributeToPage (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\page.js:202:20)
    at Page.goto (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\client\page.js:267:21)
    at openPage (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:397:20)
    at async codegen (D:\Python\Python37\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:425:5)
```

**Comment by aslushnikov** [comment]
@000xiaoxiao000 It looks like `baidu.com` is not reachable from your network. Could you please try navigating to `baidu.com` from your browser ?

**Comment by akshayp7** [comment]
1. Are you using correct proxies?
2. Are you using await before page.goto()?
