### ISSUE TITLE
Toggle Firefox to report an error  

### ISSUE THREAD

**Issue by 000xiaoxiao000** [microsoft/playwright#7401]
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        for browser_type in [p.firefox, p.webkit]:
            browser = await browser_type.launch(headless=False)
            page = await browser.new_page()
            await page.goto('https://www.baidu.com/')
            await page.screenshot(path=f'example-{browser_type.name}.png')
            print(await page.title())
            await browser.close()

Traceback (most recent call last):
  File "D:\Anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:/pythonProject/playwright-test/testcase/OWPC/product_list_test.py", line 9, in main
    page = await browser.new_page()
  File "C:\Users\xxx\AppData\Local\pypoetry\Cache\cache\virtualenvs\playwright-test-IPShjk7t-py3.8\lib\site-packages\playwright\async_api\_generated.py", line 9217, in new_page
    await self._async(
  File "C:\Users\xxx\AppData\Local\pypoetry\Cache\cache\virtualenvs\playwright-test-IPShjk7t-py3.8\lib\site-packages\playwright\_impl\_browser.py", line 149, in new_page
    context = await self.new_context(**params)
  File "C:\Users\xxx\AppData\Local\pypoetry\Cache\cache\virtualenvs\playwright-test-IPShjk7t-py3.8\lib\site-packages\playwright\_impl\_browser.py", line 111, in new_context
    channel = await self._channel.send("newContext", params)
  File "C:\Users\xxx\AppData\Local\pypoetry\Cache\cache\virtualenvs\playwright-test-IPShjk7t-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\xxx\AppData\Local\pypoetry\Cache\cache\virtualenvs\playwright-test-IPShjk7t-py3.8\lib\site-packages\playwright\_impl\_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Browser.setReducedMotion): ERROR: method 'Browser.setReducedMotion' is not supported _dispatch@chrome://juggler/content/protocol/Dispatcher.js:64:15
receiveMessage@jar:file:///C:/Users/xxx/AppData/Local/ms-playwright/firefox-1221/firefox/omni.ja!/components/juggler.js:89:18

Process finished with exit code 1

**Comment by JoelEinbinder** [comment]
@mxschmitt it looks like we are sending `Browser.setReducedMotion` to a version of firefox that can't support it. Is there a way that the firefox version could get out of date with the driver version here?

**Comment by mxschmitt** [comment]
@000xiaoxiao000 which version of Playwright Python are you using? Is this reproducible after re-installing Playwright for Python?

**Comment by 000xiaoxiao000** [comment]
> @000xiaoxiao000 which version of Playwright Python are you using? Is this reproducible after re-installing Playwright for Python?
> 
> (we have tests and it seems to work for us)

playwright version 1.12.1

**Comment by mxschmitt** [comment]
Could you try re-installing? Maybe create a new venv. It seems like on your Anaconda/poetry setup the update did not replace some of our internal files.

My guess is that you've upgraded from e.g. 1.11 to 1.12 and the upgrade did not replace all of our files, need to check if I can reproduce this with Anaconda/poetry to dig more into it.

**Comment by 000xiaoxiao000** [comment]
I've already cut python interpreter to the virtual environment, but I don't know how to use anaconda environment.

I run it using PyCharm.
Virtual environment configured in PyCharm, through the terminal using the installation command npm install playwright, python - m playwright install.   

Is it too unfriendly to reinstall the ms-playwright browser driver every time?

**Comment by 000xiaoxiao000** [comment]
> Could you try re-installing? Maybe create a new venv. It seems like on your Anaconda/poetry setup the update did not replace some of our internal files.
> 
> My guess is that you've upgraded from e.g. 1.11 to 1.12 and the upgrade did not replace all of our files, need to check if I can reproduce this with Anaconda/poetry to dig more into it.

I've already cut python interpreter to the virtual environment, but I don't know how to use anaconda environment.

I run it using PyCharm.
Virtual environment configured in PyCharm, through the terminal using the installation command npm install playwright, python - m playwright install.

Is it too unfriendly to reinstall the ms-playwright browser driver every time?
