### ISSUE TITLE
EACESS error when I use playwright into a Docker image with scrapy

### ISSUE THREAD

**Issue by thekage91** [microsoft/playwright#7460]
Hi, 
I'm trying to start playwright under a Docker image to deploy it on Zyte. 
The main purpose is use playwright to load html pages to scrape. 

I'm using scrapy as Scraping Framework and I build my scraper in a custom Docker image. The is the part when I install and compile playwright 

```
RUN mkdir -p /app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
# COPY ./.env /app/.env
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install chromium # I only need chromium for now

RUN mkdir /ms-playwright
RUN chmod -Rf 777 /ms-playwright
RUN mv /root/.cache/ms-playwright/chromium-* /ms-playwright/chromium # default installation is /root/.cache 

COPY . /app
RUN python setup.py install
```

Because the default installation is in /root/.cache I prefer move chromium under another directory and pass it to my scraper  through ` executable_path`  , see code below

```
browsers = {
    "chromium": "/ms-playwright/chromium",
}

PLAYWRIGHT_BROWSER_TYPE = "chromium"
PLAYWRIGHT_LAUNCH_OPTIONS = {"executable_path": browsers[PLAYWRIGHT_BROWSER_TYPE]}
```

The building process is ok, the image is created successfully but If I try to run the container with a specific scrapy commands, the process return me this error:

```
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
2021-07-04 18:13:03 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x7f727c1cdf70>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 837, in adapt
    extracted = result.result()
  File "/usr/local/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 104, in _launch_browser
    self.browser = await browser_launcher(**self.launch_options)
  File "/usr/local/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 9485, in launch
    await self._async(
  File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    raise e
  File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 86, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Failed to launch: Error: spawn /ms-playwright/chromium EACCES
=========================== logs ===========================
```

I think that I have problems with permissions under the chromium directory but any attempts to resolve it is failed.

Anyone here can help me? 

Thank you very much

**Comment by mxschmitt** [comment]
Are you using the official docker image? EACCES is a permission error, so are you running it under a non-root user? If so, you need to give the user access to that folder. It seems also that the executable path is wrong, since it needs the actual path to the Chromium binary/executable and not to the directory.

**Comment by thekage91** [comment]
Hi @mxschmitt , thank you very much for the response. No, I'm not using the official image but scrapinghub/scrapinghub-stack-scrapy image that has the whole stack to run scrapy inside a container. 

After your message I have launched `ls -l` inside the container to see if the permissions was ok and yes, everything is ok.
Inside the container the user is root
```
$ docker run scraper ls -l /ms-playwright/chromium/chrome-linux
total 334076
drwxr-xr-x 3 root root      4096 Jul  4 17:56 ClearKeyCdm
drwxr-xr-x 2 root root      4096 Jul  4 17:56 MEIPreload
-rwxr-xr-x 1 root root 295596816 Jul  4 17:56 chrome
-rwxr-xr-x 1 root root      5087 Jul  4 17:56 chrome-wrapper
-rw-r--r-- 1 root root    811496 Jul  4 17:56 chrome_100_percent.pak
-rw-r--r-- 1 root root   1409711 Jul  4 17:56 chrome_200_percent.pak
-rwxr-xr-x 1 root root    330608 Jul  4 17:56 chrome_sandbox
-rwxr-xr-x 1 root root   1691424 Jul  4 17:56 crashpad_handler
-rw-r--r-- 1 root root  10144432 Jul  4 17:56 icudtl.dat
-rwxr-xr-x 1 root root    360312 Jul  4 17:56 libEGL.so
-rwxr-xr-x 1 root root  10008072 Jul  4 17:56 libGLESv2.so
-rwxr-xr-x 1 root root   5848536 Jul  4 17:56 libvk_swiftshader.so
drwxr-xr-x 2 root root      4096 Jul  4 17:56 locales
-rwxr-xr-x 1 root root   4218624 Jul  4 17:56 nacl_helper
-rwxr-xr-x 1 root root      9848 Jul  4 17:56 nacl_helper_bootstrap
-rwxr-xr-x 1 root root   4893148 Jul  4 17:56 nacl_helper_nonsfi
-rw-r--r-- 1 root root      2531 Jul  4 17:56 product_logo_48.png
drwxr-xr-x 3 root root      4096 Jul  4 17:56 resources
-rw-r--r-- 1 root root   6463345 Jul  4 17:56 resources.pak
drwxr-xr-x 2 root root      4096 Jul  4 17:56 swiftshader
-rw-r--r-- 1 root root    164251 Jul  4 17:56 v8_context_snapshot.bin
-rw-r--r-- 1 root root       107 Jul  4 17:56 vk_swiftshader_icd.json
-rwxr-xr-x 1 root root     37394 Jul  4 17:56 xdg-mime
-rwxr-xr-x 1 root root     33273 Jul  4 17:56 xdg-settings
```

The problem was the path!! 
Thank you very much for the help, after some hours of test I was tired. I wrongly pointed the path to the root folder instead of to the actual browser instance. 
I have changed this 
```
browsers = {
    "chromium": "/ms-playwright/chromium",
}
```

to this 

```
browsers = {
    "chromium": "/ms-playwright/chromium/chrome-linux/chrome",
}
```

and everything works correctly. 
If you want, you can close the issue :)
