### ISSUE TITLE
Electron waiting for selector "[data-tid=locationTitleElement]" to be visible - Randomly failed

### ISSUE THREAD

**Issue by sytolk** [microsoft/playwright#7478]
**Context:**
- Playwright Version: [^1.12.3]
- Operating System: [Mac]
- Node.js version: [v12.13.0]
- Browser: [Electron]
- Extra: [https://playwright.dev/docs/api/class-electron]

## System:
 - OS: macOS 11.4
 - Memory: 6.64 GB / 32.00 GB
## Binaries:
 - Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
 - Yarn: 1.22.10 - ~/IdeaProjects/tagspaces/node_modules/.bin/yarn
 - npm: 5.1.0 - ~/IdeaProjects/tagspaces/node_modules/.bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.12.3 => 1.12.3
 
**Code Snippet**

```javascript
(async () => {
  
const { _electron: electron } = require('playwright');
    // Launch Electron app.
    global.app = await electron.launch({
      args: [pathLib.join(__dirname, '..', '..', 'app', 'main.prod.js')]
    });

    // Get the first window that the app opens, wait if necessary.
    global.client = await global.app.firstWindow();
    await global.client.waitForLoadState('networkidle'); //'domcontentloaded');
   // Direct Electron console to Node terminal.
    global.client.on('console', console.log);

  // fix for $$ selector dont work without waitForSelector
  await global.client.waitForSelector('[data-tid=locationTitleElement]', {
    // state: 'attached',
    timeout: 20000
  });
  const locationList = await global.client.$$(
    '[data-tid=locationTitleElement]'
  );
  if(locationList.lenght > 0){...}

})();
```

**Describe the bug**
I've try to migrate tests from [spectron](https://github.com/electron-userland/spectron) but there is a problem with selector I can see in web dev tools that it exist in HTML but sometimes cannot be selected from playwright

  ```
console.log
    2021-07-06T13:54:14.792Z DEBUG devtools:puppeteer:   pw:api waiting for selector "[data-tid=locationTitleElement]" to be visible
 console.log
    2021-07-06T13:54:34.798Z DEBUG devtools:puppeteer:   pw:api <= page.waitForSelector failed
...
 waiting for selector "[data-tid=locationTitleElement]" to be visible
    ============================================================
    Note: use DEBUG=pw:api environment variable to capture Playwright logs.

      331 |     '//!*[@data-tid="locationList"]/div'
      332 |   );*/
    > 333 |   await global.client.waitForSelector('[data-tid=locationTitleElement]', {
          |                       ^
      334 |     // state: 'attached',
      335 |     timeout: 20000
      336 |   });

      at Object.captureStackTrace (../node_modules/playwright/lib/utils/stackTrace.js:51:19)
      at Connection.sendMessageToServer (../node_modules/playwright/lib/client/connection.js:73:48)
      at Proxy.<anonymous> (../node_modules/playwright/lib/client/channelOwner.js:64:61)
      at ../node_modules/playwright/lib/client/frame.js:193:42
      at Frame._wrapApiCall (../node_modules/playwright/lib/client/channelOwner.js:77:34)
      at Frame.waitForSelector (../node_modules/playwright/lib/client/frame.js:188:21)
      at ../node_modules/playwright/lib/client/page.js:212:60
      at Page._attributeToPage (../node_modules/playwright/lib/client/page.js:202:20)
      at Page.waitForSelector (../node_modules/playwright/lib/client/page.js:212:21)
      at getPwLocationTid (e2e/location.helpers.js:333:23)
      at createPwLocation (e2e/location.helpers.js:94:33)
      at Object.<anonymous> (e2e/fileopener.pw.e2e.js:34:13)
```

**Comment by sytolk** [comment]
Next text run test Succeed...

```
 console.log
    2021-07-06T14:20:37.048Z DEBUG devtools:puppeteer:   pw:api => page.waitForSelector started

      at ../node_modules/@wdio/logger/build/node.js:76:9

  console.log
    2021-07-06T14:20:37.059Z DEBUG devtools:puppeteer:   pw:api waiting for selector "[data-tid=locationTitleElement]" to be visible

      at ../node_modules/@wdio/logger/build/node.js:76:9

  console.log
    2021-07-06T14:20:37.073Z DEBUG devtools:puppeteer:   pw:api   selector resolved to visible <span data-tid="locationTitleElement" class="MuiTypogr…>supported-filestypes</span>

      at ../node_modules/@wdio/logger/build/node.js:76:9

  console.log
    2021-07-06T14:20:37.079Z DEBUG devtools:puppeteer:   pw:api <= page.waitForSelector succeeded

      at ../node_modules/@wdio/logger/build/node.js:76:9
```

**Comment by avodovnik** [comment]
Can you provide us with a bit more logs (see [here](https://playwright.dev/docs/debug/)) to help us troubleshoot? You can also try doing a trace, for a failed test...

Are you _also_ using puppeteer (or webdriver) anywhere in the project? I'm trying to understand the mentions of it in the logs above.

**Comment by sytolk** [comment]
@avodovnik you mean `/node_modules/@wdio` and this in log `devtools:puppeteer` its interesting.. 
yes I have dependency to spectron@^13.0.0 which have transitive dependency to webdriverio@^6.9.1 -> puppeteer-core" "^5.4.0". 
I wll try to remove spectron tommorow.

**Comment by sytolk** [comment]
[Trace Viewer](https://playwright.dev/docs/trace-viewer/) works with chromium. But not with electron:
```javascript
global.app = await electron.launch({
      args: [pathLib.join(__dirname, '..', '..', 'app', 'main.prod.js')]
    });

global.context = await global.app.newContext(); // -> failed here
```

**Comment by sytolk** [comment]
I have removed spectron and now debugger log looks different:
```
Debugger attached.
  pw:api => electron.launch started +0ms
  pw:api <= electron.launch succeeded +583ms
  pw:api => electronApplication.firstWindow started +1ms
  pw:api <= electronApplication.firstWindow succeeded +0ms
  pw:api => page.waitForLoadState started +1ms
  pw:api   "domcontentloaded" event fired +276ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "load" event fired +10ms
  pw:api   "load" event fired +8ms
  pw:api   "domcontentloaded" event fired +157ms
  pw:api   "load" event fired +1ms
  pw:api   "networkidle" event fired +352ms
  pw:api <= page.waitForLoadState succeeded +1ms
  pw:api => page.bringToFront started +0ms
  pw:api   "networkidle" event fired +1ms
  pw:api <= page.bringToFront succeeded +2ms
  pw:api => page.$$ started +3ms
  pw:api <= page.$$ succeeded +29ms

```
The main problem with Electron testing is that never select this:
```
const locationList = await global.client.$$(
    '[data-tid=locationTitleElement]'
  );
```
If I add waitForSelector before it will select it but somethimes:
```
await global.client.waitForSelector('[data-tid=locationTitleElement]', {
    // state: 'attached',
    timeout: 20000
  });
```

**Comment by sytolk** [comment]
The same issue happened with other selectors the common thing is that always happened on the first selector in test. 

To run playwright electron tests:
https://github.com/tagspaces/tagspaces/blob/TSN692---Evaluate-playwright-test-framework/package.json#L93

The same test works without problem in web browser - cromium
https://github.com/tagspaces/tagspaces/blob/TSN692---Evaluate-playwright-test-framework/package.json#L94

**Comment by sytolk** [comment]
Maybe this issue is connected with Electron  Content-Security-Policy
if I match the failed with successed log this appears on failed:

```
pw:api <= page.waitForLoadState succeeded +2ms
  pw:api => page.click started +1ms
  pw:api   "load" event fired +3ms
  pw:api waiting for selector "[data-tid=nextStepOnboarding]" +3ms
  console.log
    %cElectron Security Warning (Insecure Content-Security-Policy) font-weight: bold; This renderer process has either no Content Security
        Policy set or a policy with "unsafe-eval" enabled. This exposes users of
        this app to unnecessary security risks.
    
    For more information and help, consult
    https://electronjs.org/docs/tutorial/security.
    This warning will not show up
    once the app is packaged.

      at Proxy.<anonymous> (../node_modules/playwright/lib/client/page.js:73:59)
```

[successed.txt](https://github.com/microsoft/playwright/files/6778649/successed.txt)
[failed.txt](https://github.com/microsoft/playwright/files/6778645/failed.txt)

**Comment by dgozman** [comment]
@sytolk In the failed logs I see the following line:
```log
pw:api   navigated to "file:///Users/sytolk/IdeaProjects/tagspaces/app/splash.html" +616ms
```

Could it be that sometimes you open a splash page, and sometimes you don't? This could explain why element with a particular selector is not there, since the page is different. Similarly, the splash page probably does not have Content-Security-Policy set, so you get the warning.

**Comment by sytolk** [comment]
@dgozman good catch this was the issue thanks!
