### ISSUE TITLE
Playwright Docker throwing UnhandledPromiseRejectionWarning: Error: Page closed

### ISSUE THREAD

**Issue by budsee** [microsoft/playwright#7492]
### Playwright version

1.12.1

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Hi 

I'm using playwright docker image here  => https://hub.docker.com/_/microsoft-playwright

I encounter an issue where if I run playwright in the docker, I would have the below error

(node:97) UnhandledPromiseRejectionWarning: Error: Page closed
    at CRSession.<anonymous> (/usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/chromium/crPage.js:341:60)
    at Object.onceWrapper (events.js:420:28)
    at CRSession.emit (events.js:326:22)
    at /usr/local/lib/python3.8/dist-packages/playwright/driver/package/lib/server/chromium/crConnection.js:177:43
(node:97) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

It run fine in my own machine (macOS m1). I research and saw that it is related to browser.close too early. However, I'm using pytest and is using playwright as sync and not async function since pytest has fixture which can yield the page and then do a browser close later. E.g code below:

@pytest.fixture
def page():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        yield page
        browser.close()

Do we. know why the same code run fine in my local machine but not in playwright docker?

**Comment by mxschmitt** [comment]
Hi, would be great if you could provide us more logs using the `DEBUG=pw:api` environment variable, there we should see the API calls.

Also I'm curious why you are not using the official Pytest plugin for Playwright: https://github.com/microsoft/playwright-pytest

**Comment by budsee** [comment]
Hi

The logs are huge, so I pipe to a file and attached here => [logs.txt](https://github.com/microsoft/playwright/files/6776050/logs.txt)


Ah it's because I'm using pytest-bdd. to be exact. playwright-pytest does not seems to work with pytest-bdd

**Comment by mxschmitt** [comment]
From a short investigation, this looks like a Docker bug. See the following related issues:
- https://github.com/cypress-io/cypress-docker-images/issues/431
- https://github.com/cypress-io/cypress-docker-images/issues/488#issuecomment-843841488
- https://github.com/docker/for-mac/issues/5321

Also it seems you can workaround it by passing `args=["--disable-gpu"]` when launching the browser or we would need to create Docker images for the `ARM64` architecture.

Another workaround which might work is using the Docker image `ubuntu:focal` instead and installing Playwright in there manually and the dependencies via `playwright install` and `playwright install-deps`. See [here](https://playwright.dev/docs/cli#install-system-dependencies) for docs.

**Comment by budsee** [comment]
Thanks for checking using `args=["--disable-gpu"]` does not help. 
Please find the attached logs for this => [logs.txt](https://github.com/microsoft/playwright/files/6778038/logs.txt)

I tried` ubuntu:focal `docker image before but I have the below playwright version  install error where I can't install the latest version and stuck with 0.162.2 only

`=> ERROR [ 9/12] RUN pip install playwright==1.12.1                                                                                                                                                 1.3s
------
 > [ 9/12] RUN pip install playwright==1.12.1:
#12 1.281 ERROR: Could not find a version that satisfies the requirement playwright==1.12.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.7.0, 0.7.1, 0.8.0, 0.140.0, 0.142.0, 0.142.1, 0.142.2, 0.142.3, 0.150.0, 0.151.0, 0.151.1, 0.152.0, 0.162.0, 0.162.1, 0.162.2)
#12 1.282 ERROR: No matching distribution found for playwright==1.12.1`

**Comment by mxschmitt** [comment]
Could you provide us the output of `pip debug --verbose`?

**Comment by budsee** [comment]
Here it is. What does this mean? This also only happen in docker only.

`pip debug --verbose
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/debug.py", line 11, in <module>
    from pip._vendor.certifi import where
ModuleNotFoundError: No module named 'pip._vendor.certifi'`

**Comment by mxschmitt** [comment]
Seems like the PIP installation inside the Docker container (also the official image) seems broken. Could you try executing this beforehand inside the container?

`curl -sS https://bootstrap.pypa.io/get-pip.py | python`

**Comment by budsee** [comment]
Does not seem to help

`root@db8d954583cc:/# curl -sS https://bootstrap.pypa.io/get-pip.py | python3
Collecting pip
  Using cached pip-21.1.3-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3
Successfully installed pip-21.1.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@db8d954583cc:/# pip install playwright==1.21.1
ERROR: Could not find a version that satisfies the requirement playwright==1.21.1 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.7.0, 0.7.1, 0.8.0, 0.140.0, 0.142.0, 0.142.1, 0.142.2, 0.142.3, 0.150.0, 0.151.0, 0.151.1, 0.152.0, 0.162.0, 0.162.1, 0.162.2)
ERROR: No matching distribution found for playwright==1.21.1`

**Comment by mxschmitt** [comment]
And what is the output for `pip debug --verbose` there?

Background: pip debug will log the supported architectures, based on that we can see where the problem is.

**Comment by budsee** [comment]
It's the same as previous

```root@d9b06f736f9e:/# pip debug --verbose
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip')()
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/debug.py", line 11, in <module>
    from pip._vendor.certifi import where
ModuleNotFoundError: No module named 'pip._vendor.certifi'```
