### ISSUE TITLE
[Bug]: page.click: cssParser_1.parseCSS is not a function

### ISSUE THREAD

**Issue by ayartsev7** [microsoft/playwright#7501]
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.9.0",
    "babel-loader": "8.0.6",
    "babel-plugin-react-transform": "1.1.1",
    "bamboo-jest-reporter": "1.0.3",
    "compression-webpack-plugin": "3.0.1",
    "css-loader": "0.28.4",
    "dotenv": "8.2.0",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "enzyme-to-json": "3.6.2",
    "eslint": "6.8.0",
    "eslint-loader": "3.0.3",
    "eslint-plugin-react": "7.18.0",
    "eslint-plugin-typescript": "0.14.0",
    "fancy-log": "1.3.3",
    "file-loader": "5.0.2",
    "gulp": "4.0.2",
    "html-loader": "0.4.4",
    "imports-loader": "0.6.3",
    "isomorphic-fetch": "3.0.0",
    "jest": "24.9.0",
    "jest-mock-extended": "1.0.10",
    "jest-playwright-preset": "1.7.0",
    "jest-sonar-reporter": "2.0.0",
    "less": "2.7.2",
    "less-loader": "4.0.4",
    "minimist": "1.2.5",
    "pdfjs-dist": "2.0.943",
    "playwright": "1.12.3",
    "plugin-error": "1.0.1",
    "raw-loader": "4.0.0",
    "react-test-renderer": "16.12.0",
    "style-loader": "1.0.0",
    "ts-jest": "26.4.1",
    "ts-loader": "8.0.3",
    "typescript": "4.1.3",
    "url-loader": "2.1.0",
    "uuid": "8.3.2",
    "webpack": "4.41.0",
    "webpack-dev-server": "3.8.1"

### What happened? / Describe the bug

Hi!
I am new to playwright, wrote a simple jest + playwright test but failed to get it work.
The following minimal test crashes on page.click call with the following error:

`TypeError: page.click: cssParser_1.parseCSS is not a functionpage.click: cssParser_1.parseCSS is not a function`

### Code snippet to reproduce your bug

```shell
import regeneratorRuntime from 'regenerator-runtime';
import { chromium } from 'playwright';

test('test', async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://playwright.dev');
  await page.click('button:has-text("Get started")');
  await page.close();
  await browser.close();
});
```

### Relevant log output

```shell
TypeError: page.click: cssParser_1.parseCSS is not a functionpage.click: cssParser_1.parseCSS is not a function

      at Object.captureStackTrace (node_modules/playwright/lib/utils/stackTrace.js:51:19)
      at Connection.captureStackTrace (node_modules/playwright/lib/client/connection.js:73:48)
      at call (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.tryCatch [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator._invoke [as next] (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/playwright/lib/client/connection.js:24:103)
      at _next (node_modules/playwright/lib/client/connection.js:26:194)
      at node_modules/playwright/lib/client/connection.js:26:364
      at Connection.<anonymous> (node_modules/playwright/lib/client/connection.js:26:97)
      at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:258:37)
      at Proxy.sendMessageToServer (node_modules/playwright/lib/client/channelOwner.js:64:61)
      at click (node_modules/playwright/lib/client/frame.js:270:34)
      at call (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.tryCatch [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator._invoke [as next] (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/playwright/lib/client/frame.js:27:103)
      at _next (node_modules/playwright/lib/client/frame.js:29:194)
      at node_modules/playwright/lib/client/frame.js:29:364
      at node_modules/playwright/lib/client/frame.js:29:97
      at node_modules/playwright/lib/client/frame.js:269:16
      at Frame.func (node_modules/playwright/lib/client/channelOwner.js:77:34)
      at call (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.tryCatch [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator._invoke [as next] (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/playwright/lib/client/channelOwner.js:20:103)
      at _next (node_modules/playwright/lib/client/channelOwner.js:22:194)
      at node_modules/playwright/lib/client/channelOwner.js:22:364
```

**Comment by JoelEinbinder** [comment]
It looks like you are babeling your code into es5. This doesn't work with playwright. Try to turn off all of the transformations.

**Comment by ayartsev7** [comment]
@JoelEinbinder thanks for your response!

I disabled all transformations that affected test, now my jest transformations look like
```
    "transform": {
      "\\.raw\\.js$": "<rootDir>/jest/rawLoader.js",
      "\\.raw\\.less$": "<rootDir>/jest/rawLoader.js",
      "@ast\\\\magma.*\\.js$": "babel-jest",
      "\\.(jsx|ts|tsx)$": "ts-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!@ast/magma)"
    ],

```

test name is playwrightMY.test.js, I know the test is not transformed because regeneratorRuntime is not needed anymore and imports are not allowed so the test now looks like
```

//import regeneratorRuntime from "regenerator-runtime";
//import { chromium } from 'playwright';

const { chromium } = require('playwright');

test('test', async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 550 });
  const page = await browser.newPage();
  await page.goto('https://playwright.dev');
  await page.click('div:has-text("Get started")');
  await page.close();
  await browser.close();
});

```

The error persist :(

New stack trace:
```
    TypeError: page.click: cssParser_1.parseCSS is not a functionpage.click: cssParser_1.parseCSS is not a function

       8 |   const page = await browser.newPage();
       9 |   await page.goto('https://playwright.dev');
    > 10 |   await page.click('div:has-text("Get started")');
         |              ^
      11 |   await page.close();
      12 |   await browser.close();
      13 | });

      at Object.captureStackTrace (node_modules/playwright/lib/utils/stackTrace.js:51:19)
      at Connection.sendMessageToServer (node_modules/playwright/lib/client/connection.js:73:48)
      at Proxy.<anonymous> (node_modules/playwright/lib/client/channelOwner.js:64:61)
      at node_modules/playwright/lib/client/frame.js:270:34
      at Frame._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:77:34)
      at Frame.click (node_modules/playwright/lib/client/frame.js:269:21)
      at node_modules/playwright/lib/client/page.js:422:60
      at Page._attributeToPage (node_modules/playwright/lib/client/page.js:202:20)
      at Page.click (node_modules/playwright/lib/client/page.js:422:21)
      at Object.<anonymous> (src/admin_v3/playwrightMY.test.js:10:14)
```

**Comment by ayartsev7** [comment]
Found the root of the issue: there was another silly transformation in jests "moduleNameMapper" section. Sorry for the noise.
