### ISSUE TITLE
[Feature]: Add source map support to page.on("pageerror") event

### ISSUE THREAD

**Issue by doctorpangloss** [microsoft/playwright#7524]
### Playwright version

1.12.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

 1. Create a static site with minified Javascript content and source maps.
 2. Throw an exception in the minified code.
 3. Observe `page.on('pageerror')`'s argument provides a stack trace that does not use the source map references. It should.

For example, this is the error text I receive:

```
ReferenceError: XXX is not defined
    at XXX._callee3$ (http://localhost:10099/9184b63e343b96a0057607d65c936392555f6b9d-3ee78f1e3480363494d9.js:6753:460)
    at tryCatch (http://localhost:10099/9184b63e343b96a0057607d65c936392555f6b9d-3ee78f1e3480363494d9.js:7305:40)
    at Generator.invoke [as _invoke] (http://localhost:10099/9184b63e343b96a0057607d65c936392555f6b9d-3ee78f1e3480363494d9.js:7535:22)
    at Generator.next (http://localhost:10099/9184b63e343b96a0057607d65c936392555f6b9d-3ee78f1e3480363494d9.js:7360:21)
    at asyncGeneratorStep (http://localhost:10099/9184b63e343b96a0057607d65c936392555f6b9d-3ee78f1e3480363494d9.js:12:24)
    at _next (http://localhost:10099/9184b63e343b96a0057607d65c936392555f6b9d-3ee78f1e3480363494d9.js:34:9)
```

Ideally the stack trace is given with source maps resolved.

### Code snippet to reproduce your bug

```shell
I use Playwright for Java, let me know if the description isn't clear enough.
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
