### ISSUE TITLE
[Bug]: Browser downloads failing in CI

### ISSUE THREAD

**Issue by wupaz** [microsoft/playwright#7566]
### Playwright version

1.12.3 

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

npm/6.14.13
node/v14.17.1 win32 x64

Azure Pipeline : Agent Windows-2019

In package.json 
    "@playwright/test": "^1.12.3",
    "playwright": "^1.12.3",

### What happened? / Describe the bug

Install fail when task NPM Install run on a AzurePipeline (DevOps) 

> playwright@1.12.3 install D:\a\1\s\Fusion\node_modules\playwright
npm ERR! errno 1
npm ERR! playwright@1.12.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the playwright@1.12.3 install script.

### Code snippet to reproduce your bug

```shell
Nothing special just NPM Install on a pipeline on Devops
```

### Relevant log output

```shell
(node:7020) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
    at D:\a\1\s\Fusion\node_modules\playwright\lib\install\installer.js:124:19
    at async validateCache (D:\a\1\s\Fusion\node_modules\playwright\lib\install\installer.js:123:9)
    at async installBrowsersWithProgressBar (D:\a\1\s\Fusion\node_modules\playwright\lib\install\installer.js:74:9)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by mskelton** [comment]
My company is also experiencing this.  We are running our tests from Buildkite and experiencing the same bug.  Also, it would appear we are not alone as Playwright itself is experiencing this:

https://github.com/microsoft/playwright/runs/3048916469

**Comment by mskelton** [comment]
@wupaz Could you update your issue title to provide a better description of the issue?  Something like this perhaps: "Browser downloads failing in CI"

**Comment by mxschmitt** [comment]
### Update from Playwright side:

There is currently an outage on GitHub Actions -> Azure CDN. We keep you updated about this.

**Comment by wupaz** [comment]
It weird sometime Pipeline pass ...

**Comment by matks** [comment]
> It weird sometime Pipeline pass ...

Agreed, sometimes it works

> There currently is a partial outage on the GitHub Actions -> Azure CDN side. We'll keep you updated.

Maybe some of the Azure network behavior is correct and other parts are failing

**Comment by wupaz** [comment]
It seem fixed ... last 10 npm install I didn't have any issue, but I hit an issue juste after ;( 

```
2021-07-13T07:05:52.2141082Z ##[section]Starting: Run Playwright Test 
2021-07-13T07:05:52.2269329Z ==============================================================================
2021-07-13T07:05:52.2269774Z Task         : Command Line
2021-07-13T07:05:52.2270129Z Description  : Run a command line with arguments
2021-07-13T07:05:52.2270470Z Version      : 1.1.3
2021-07-13T07:05:52.2270788Z Author       : Microsoft Corporation
2021-07-13T07:05:52.2271265Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2021-07-13T07:05:52.2271854Z ==============================================================================
2021-07-13T07:05:52.2303972Z ##[debug]Working directory: 'C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e'
2021-07-13T07:05:52.2304983Z ##[debug]Fail on standard error: 'False'
2021-07-13T07:05:52.2305225Z ##[debug]Modify environment: 'False'
2021-07-13T07:05:52.2305486Z ##[debug]C:\windows\system32\cmd.exe /c "npx playwright test"
2021-07-13T07:05:52.2305712Z ##[command]npx playwright test
2021-07-13T07:05:53.7549455Z Error: Error while reading C:\AzurePiplinesAgent_Extension\_work\r4\a\GMaster\DevDrop\test_e2e\e2e\playwright\use-case\add-new-patient.uctest.spec.ts:
2021-07-13T07:05:53.7550824Z describe() can only be called in a test file
2021-07-13T07:05:53.8917205Z ##[error]Process completed with exit code 1.
2021-07-13T07:05:53.8920702Z ##[debug]System.Exception: Process completed with exit code 1.
```
