### ISSUE TITLE
[Bug]: Unable to launch any browser on macOS 12 beta

### ISSUE THREAD

**Issue by madebysid** [microsoft/playwright#7624]
### Playwright version

1.12.3

### Operating system

MacOS

### Other information

OS: macOS 12 Beta 3
Node version: v14.17.0

### What happened? / Describe the bug

When I try to run a simple Playwright script on the latest macOS beta, Playwright errors out (error trace down below)

I'm not too familiar with Playwright's codebase, but when I manually go into my `node_modules/playwright/lib/utils/registry.js` and add `mac12` keys to all browsers, Playwright launches just fine. (I just copied the `mac11` key values)

I understand that macOS 12 is still in beta, so if it is deliberately "unsupported", please feel free to close this issue. Otherwise, I'm more than happy to create a PR to try and fix this if you'd like.

### Code snippet to reproduce your bug

```shell
// This is the default playwright script from https://playwright.dev/docs/intro/#usage

const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // Create pages, interact with UI elements, assert values
  await browser.close();
})();
```

### Relevant log output

```shell
browserType.launch: No executable path is specified. Pass "executablePath" option directly.
(node:59532) UnhandledPromiseRejectionWarning: browserType.launch: No executable path is specified. Pass "executablePath" option directly.
Error
    at Object.captureStackTrace (/Users/siddhant/Code/pw/node_modules/playwright/lib/utils/stackTrace.js:51:19)
    at Connection.sendMessageToServer (/Users/siddhant/Code/pw/node_modules/playwright/lib/client/connection.js:73:48)
    at Proxy.<anonymous> (/Users/siddhant/Code/pw/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/siddhant/Code/pw/node_modules/playwright/lib/client/browserType.js:59:67
    at BrowserType._wrapApiCall (/Users/siddhant/Code/pw/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at BrowserType.launch (/Users/siddhant/Code/pw/node_modules/playwright/lib/client/browserType.js:50:21)
    at /Users/siddhant/Code/pw/index.js:4:34
    at Object.<anonymous> (/Users/siddhant/Code/pw/index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by mxschmitt** [comment]
This should be fixed in the next release of Playwright. (`npm install playwright@next`)

**Comment by madebysid** [comment]
Oh awesome!

Although I should note that in my case, there was no issue downloading browsers during `npm install`, only running them failed. 

Nevertheless, I'll wait for the next release!

**Comment by madebysid** [comment]
Awesome, thanks! I can confirm that the `next` version does not exhibit this problem anymore
