### ISSUE TITLE
[Bug]: Can not execute show trace with local browser binary

### ISSUE THREAD

**Issue by mailtogagan** [microsoft/playwright#7633]
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

>node -v
v14.17.3
> npm -v
6.14.13

### What happened? / Describe the bug

I am skipping the binaries download during installation. Now when I am trying to run show-trace command (with generated trace.zip during scenario execution), then its failing as its still looking for default binary for chromium.

Can we use the trace-viewer with local browser (like chromium) rather than the default binary inside playwright? I think it can be achieved if somehow we can pass on `executablePath` argument to `show-trace`.

CC: @dgozma

### Relevant log output

```shell
PS C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example> npx playwright show-trace .\test-results\tests-example-Core-Concepts-table-of-contents-chromium\trace.zip
Error: Failed to launch chromium because executable doesn't exist at C:\Users\meet_\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome.exe
Try re-installing playwright with "npm install playwright"
    at Chromium._launchProcess (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example\node_modules\@playwright\test\lib\server\browserType.js:168:19)
    at Chromium._innerLaunch (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example\node_modules\@playwright\test\lib\server\browserType.js:108:61)
    at ProgressController.run (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example\node_modules\@playwright\test\lib\server\progress.js:76:28)
    at Chromium.launchPersistentContext (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example\node_modules\@playwright\test\lib\server\browserType.js:86:25)
    at TraceViewer.show (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example\node_modules\@playwright\test\lib\server\trace\viewer\traceViewer.js:136:25)
    at showTraceViewer (C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example\node_modules\@playwright\test\lib\cli\cli.js:555:5)
PS C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example>
PS C:\Users\meet_\OneDrive\Desktop\Work\Playwright\PlaywrightTest-TestFixtures-Example>
```

**Comment by pavelfeldman** [comment]
that's already addressed. trace viewer will use locally installed Chrome or Edge starting with v1.13
