### ISSUE TITLE
[Bug]:  stop tracing failed with ENOENT: no such file or directory

### ISSUE THREAD

**Issue by xuanzhaopeng** [microsoft/playwright#7729]
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

```
 public class mycontroller {
      private contexts: BrowserContext[] = []

      public async newContext() {
			const context = await this.browser.newContext()
			// start trace
			await context.tracing.start({ screenshots: true, snapshots: true });
			const page = await context.newPage()
			await page.goto('https://google.com.com')
			this.preparePage(page)
			this.contexts.push(context)
      }

     public async clean() {
		console.log('[Driver service] Clean start')
		// stop trace
		for(let i = 0; i < this.contexts.length; i++) {
			await this.contexts[i].tracing.stop({path: `mytrace-${i}.zip`})
		}
		await Promise.all(this.contexts.map(c => c.close()))
		this.contexts = []
		console.log('[Driver service] Clean done')
     }
}
```

Failed when stop tracing: 
```
node:94375) UnhandledPromiseRejectionWarning: tracing.stop: ENOENT: no such file or directory, open '/var/folders/rd/56nfp88n75s89x2yv7pg2f480000gn/T/playwright-artifacts-OAy2Uk/resources/7648ef477591612d7cf8708cbbe9d0151b90f095'
Error: 
    at Object.captureStackTrace (.../node_modules/playwright-chromium/lib/utils/stackTrace.js:51:19)
    at Connection.sendMessageToServer (.../node_modules/playwright-chromium/lib/client/connection.js:73:48)
    at Proxy.<anonymous> (.../node_modules/playwright-chromium/lib/client/channelOwner.js:64:61)
    at .../node_modules/playwright-chromium/lib/client/tracing.js:34:46
    at BrowserContext._wrapApiCall (.../node_modules/playwright-chromium/lib/client/channelOwner.js:77:28)
    at Tracing.stop (.../node_modules/playwright-chromium/lib/client/tracing.js:30:9)
    at DriverService.clean (.../lib/services/driver.service.ts:70:13)
```

I was at first thinking maybe it because of multiple contexts, but even I use single context, it still can be reproduced. 

Some facts,  when I do following:
```
			await context.tracing.start({ screenshots: false, snapshots: false });
```

or 
```
			await context.tracing.start({ screenshots: false, snapshots: true });
```

**Then I can get trace zip, but no screenshot,  once I enabled screenshots/snapshots, it start throw exception.**

**Comment by xuanzhaopeng** [comment]
When I change trace folder:
```
		launchOptions: {
			tracesDir: './output/trace/'
		},
```

Then I get following errors:
```
.../node_modules/playwright-chromium/lib/client/connection.js:157
            throw new Error(`Cannot find parent object ${parentGuid} to create ${guid}`);
            ^

Error: Cannot find parent object browser-context@4fa6de29db2e06a855bd7ba2274b7668 to create artifact@ddfbd13aad7af248e020ab7b81984d31
    at Connection._createRemoteObject (.../node_modules/playwright-chromium/lib/client/connection.js:157:19)
    at Connection.dispatch (.../node_modules/playwright-chromium/lib/client/connection.js:110:18)
    at Immediate.<anonymous> (.../node_modules/playwright-chromium/lib/inprocess.js:37:85)
    at processImmediate (internal/timers.js:461:21)
error Command failed with exit code 1.
```

**Comment by pavelfeldman** [comment]
I tried following and it works just fine. I wonder what else you are doing in your program.
Btw, there is no point in creating several contexts at a time unless you are testing a chat app w/ two different logged in users.


```js
const { chromium } = require('playwright');

(async () => {
  const contexts = [];
  const browser = await chromium.launch();

  const create = async () => {
    const context = await browser.newContext();
    await context.tracing.start({ screenshots: true, snapshots: true });
    const page = await context.newPage();
    await page.goto('https://google.com');

    // Start typing
    (async () => {
      try {
        while (true) {
          await page.keyboard.type('A');
          await new Promise(f => setTimeout(f, 250));
        }
      } catch (e) {
        // page closed
      }
    })();
  };

  const close = async () => {
    for(let i = 0; i < contexts.length; i++) {
      await contexts[i].tracing.stop({path: `mytrace-${i}.zip`})
    }
    await Promise.all(contexts.map(c => c.close()));
  }

  for (let i = 0; i < 10; ++i)
    await create();
  await close();
  await browser.close();
})();
```

**Comment by xuanzhaopeng** [comment]
Hmm super wired, I start the browser/context from Jest environment. 

Do you know is there Log I can check?

**Comment by xuanzhaopeng** [comment]
Hey @pavelfeldman ,  I can reproduce it every time, can you pls have a look again?

https://github.com/xuanzhaopeng/pw-test

**Comment by xuanzhaopeng** [comment]
nvm, stupid issue, forget to add `await`, then get this error
