### ISSUE TITLE
[Bug]: Firefox tests not working - target is undefined newPage@chrome

### ISSUE THREAD

**Issue by TonyPatterson** [microsoft/playwright#7827]
### Playwright version

1.13

### Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### Other information

Also seen on 1.12

### What happened? / Describe the bug

Tests fail on Firefox with the error: browserContext.newPage: Protocol error (Browser.newPage): target is undefined newPage@chrome://juggler/content/TargetRegistry.js:329:5

This appears to be due to locked-down nature of my company laptop, it works fine on my home machine. If it cannot be fixed it would at least be nice to have a more helpful error message. Probably relates to #4922.

Otherwise everything works fine and I really like Playwright.

### Code snippet to reproduce your bug

```shell
// PlaywrightNavTest.spec.ts
import { test, expect } from '@playwright/test';

test('Playwright Navigation Test', async ({ page }) => {
    await page.goto('https://playwright.dev/docs/intro/');

    expect(page.url()).toBe('https://playwright.dev/docs/intro/');
});

// npx playwright test --browser all -g PlaywrightNavTest
```

### Relevant log output

```shell
2021-07-24T18:20:37.972Z pw:api => browserType.launch started
2021-07-24T18:20:38.354Z pw:api => browserType.launch started
2021-07-24T18:20:38.788Z pw:api => browserType.launch started
2021-07-24T18:20:39.468Z pw:api <= browserType.launch succeeded
2021-07-24T18:20:39.470Z pw:api => browser.newContext started
2021-07-24T18:20:39.477Z pw:api <= browser.newContext succeeded
2021-07-24T18:20:39.479Z pw:api => browserContext.newPage started
2021-07-24T18:20:39.637Z pw:api <= browserContext.newPage succeeded
2021-07-24T18:20:39.638Z pw:api => page.goto started
2021-07-24T18:20:39.640Z pw:api navigating to "https://playwright.dev/docs/intro/", waiting until "load"
2021-07-24T18:20:39.818Z pw:api   navigated to "https://playwright.dev/docs/intro/"
2021-07-24T18:20:40.133Z pw:api <= browserType.launch succeeded
2021-07-24T18:20:40.135Z pw:api => browser.newContext started
2021-07-24T18:20:40.173Z pw:api <= browser.newContext succeeded
2021-07-24T18:20:40.175Z pw:api => browserContext.newPage started
2021-07-24T18:20:40.244Z pw:api   "domcontentloaded" event fired
2021-07-24T18:20:40.430Z pw:api <= browserContext.newPage succeeded
2021-07-24T18:20:40.433Z pw:api => page.goto started
2021-07-24T18:20:40.434Z pw:api navigating to "https://playwright.dev/docs/intro/", waiting until "load"
2021-07-24T18:20:40.527Z pw:api   navigated to "https://playwright.dev/docs/intro/"
2021-07-24T18:20:40.789Z pw:api   "networkidle" event fired
2021-07-24T18:20:40.820Z pw:api   "load" event fired
2021-07-24T18:20:40.821Z pw:api <= page.goto succeeded
2021-07-24T18:20:40.824Z pw:api => browserContext.close started
2021-07-24T18:20:40.835Z pw:api <= browserContext.close succeeded
[2K[0G[32m  ok [39m[90m[chromium] › tests\PlaywrightNavTest.spec.ts:3:1 › Playwright Navigation Test[39m[2m (3s)[22m
2021-07-24T18:20:40.929Z pw:api   "domcontentloaded" event fired
2021-07-24T18:20:41.120Z pw:api <= browserType.launch succeeded
2021-07-24T18:20:41.122Z pw:api => browser.newContext started
2021-07-24T18:20:41.133Z pw:api <= browser.newContext succeeded
2021-07-24T18:20:41.135Z pw:api => browserContext.newPage started
2021-07-24T18:20:41.609Z pw:api   "networkidle" event fired
2021-07-24T18:20:41.640Z pw:api <= browserContext.newPage failed
2021-07-24T18:20:41.641Z pw:api => browserContext.close started
2021-07-24T18:20:41.666Z pw:api <= browserContext.close succeeded
[2K[0G[31m  x  1) [firefox] › tests\PlaywrightNavTest.spec.ts:3:1 › Playwright Navigation Test[39m[2m (3s)[22m
2021-07-24T18:20:41.668Z pw:api => browser.close started
2021-07-24T18:20:41.825Z pw:api   "load" event fired
2021-07-24T18:20:41.826Z pw:api <= page.goto succeeded
2021-07-24T18:20:41.830Z pw:api => browserContext.close started
2021-07-24T18:20:41.838Z pw:api <= browserContext.close succeeded
[2K[0G[32m  ok [39m[90m[webkit] › tests\PlaywrightNavTest.spec.ts:3:1 › Playwright Navigation Test[39m[2m (3s)[22m
2021-07-24T18:20:41.841Z pw:api => browser.close started
2021-07-24T18:20:41.841Z pw:api => browser.close started
2021-07-24T18:20:41.863Z pw:api <= browser.close succeeded
2021-07-24T18:20:41.885Z pw:api <= browser.close succeeded
2021-07-24T18:20:42.299Z pw:api <= browser.close succeeded


[31m  1) [firefox] › tests\PlaywrightNavTest.spec.ts:3:1 › Playwright Navigation Test [90m==================[31m[39m

    browserContext.newPage: Protocol error (Browser.newPage): target is undefined newPage@chrome://juggler/content/TargetRegistry.js:329:5


    [2m    at Object.page [as fn] (C:\Users\TPatterson\MyRepos\Miscellany\ContentSecurityPolicyBuilder\ContentSecurityPolicyBuilder\UiTest\node_modules\@playwright\test\lib\test\index.js:274:29)[22m
    [2m    at Fixture.setup (C:\Users\TPatterson\MyRepos\Miscellany\ContentSecurityPolicyBuilder\ContentSecurityPolicyBuilder\UiTest\node_modules\@playwright\test\lib\test\fixtures.js:73:73)[22m
    [2m    at FixtureRunner.setupFixtureForRegistration (C:\Users\TPatterson\MyRepos\Miscellany\ContentSecurityPolicyBuilder\ContentSecurityPolicyBuilder\UiTest\node_modules\@playwright\test\lib\test\fixtures.js:296:5)[22m
    [2m    at FixtureRunner.resolveParametersAndRunHookOrTest (C:\Users\TPatterson\MyRepos\Miscellany\ContentSecurityPolicyBuilder\ContentSecurityPolicyBuilder\UiTest\node_modules\@playwright\test\lib\test\fixtures.js:283:23)[22m
    [2m    at WorkerRunner._runTestWithBeforeHooks (C:\Users\TPatterson\MyRepos\Miscellany\ContentSecurityPolicyBuilder\ContentSecurityPolicyBuilder\UiTest\node_modules\@playwright\test\lib\test\workerRunner.js:390:7)[22m


[31m  1 failed[39m
[31m    [firefox] › tests\PlaywrightNavTest.spec.ts:3:1 › Playwright Navigation Test [90m===================[31m[39m
[32m  2 passed[39m[2m (5s)[22m
```

**Comment by dgozman** [comment]
@TonyPatterson I assume a repro script will not help us? Since this problem only happens on your laptop, but not on the home computer, it seems to be environment specific.

Could you record a trace and send it to us? That might give us some information. See here for tracing docs: https://playwright.dev/docs/api/class-tracing

Or you could also run with `DEBUG=pw:browser*` environment variable and send us the logs.

**Comment by mxschmitt** [comment]
Closing since the issue seems stale, please create a new issue if you still encounter issues.
