### ISSUE TITLE
[Bug]: Importing `.ts` files with a `.js` extension doesn't work

### ISSUE THREAD

**Issue by matheus23** [microsoft/playwright#7855]
### Playwright version

1.13.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

### Other information

Typescript v 4.3.2 (in case it's a peer dependency)

### What happened? / Describe the bug

We're writing all our tests in typescript. One of the tests looks like this:

```ts
import { test, expect } from "@playwright/test"
import { loadWebnativePage } from "../helpers/page"


test("the filesystem provides appPath", async ({ page }) => {
  await loadWebnativePage(page)
  // ... actual test
});
```

As you can see, I have to import `../helpers/page`. However, typescript allows you to import typescript (`.ts`) files with a `.js` extension, for [a somewhat good reason](https://github.com/microsoft/TypeScript/issues/16577#issuecomment-703190339) (Fact 1 in that comment states that what I describe actually works. See the issue itself for the root problem this solves).

If I use `import '../helpers/page.js'`, I get this error:
```
Error: Cannot find module '../helpers/page.js'
```

### Code snippet to reproduce your bug

```shell
import { test, expect } from "@playwright/test"
// Make sure to place a file at `../helpers/page.ts` <- (TS Extension!)
import { loadWebnativePage } from "../helpers/page.js"


test("the filesystem provides appPath", async ({ page }) => {
  // await loadWebnativePage(page)
  expect(true).toBe(true)
});
```

### Relevant log output

```shell
Error: Cannot find module '../helpers/page.js'
Require stack:
- /home/philipp/work/fission/webnative/main/tests/fs/appPath.browser.test.ts
- /home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/loader.js
- /home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/runner.js
- /home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/cli.js
- /home/philipp/work/fission/webnative/main/node_modules/playwright/lib/cli/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/philipp/work/fission/webnative/main/tests/fs/appPath.browser.test.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module._compile (/home/philipp/work/fission/webnative/main/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.newLoader (/home/philipp/work/fission/webnative/main/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Loader._requireOrImport (/home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/loader.js:211:18)
    at Loader.loadTestFile (/home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/loader.js:130:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/philipp/work/fission/webnative/main/tests/fs/appPath.browser.test.ts',
    '/home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/loader.js',
    '/home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/runner.js',
    '/home/philipp/work/fission/webnative/main/node_modules/@playwright/test/lib/test/cli.js',
    '/home/philipp/work/fission/webnative/main/node_modules/playwright/lib/cli/cli.js'
  ]
}
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
