### ISSUE TITLE
Bug: playwright tests fail inside some step logic

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#8050]
### Feature request

Reference: https://github.com/microsoft/playwright/pull/8047/checks?check_run_id=3264310272

error:
```
/Users/runner/work/playwright/playwright/tests/config/test-runner/node_modules/@playwright/test/lib/test/dispatcher.js:300
      step.duration = params.wallTime - step.startTime.getTime();
                                             ^

TypeError: Cannot read property 'startTime' of undefined
    at Worker.<anonymous> (/Users/runner/work/playwright/playwright/tests/config/test-runner/node_modules/@playwright/test/lib/test/dispatcher.js:300:46)
    at Worker.emit (events.js:314:20)
    at Worker.EventEmitter.emit (domain.js:483:12)
    at ChildProcess.<anonymous> (/Users/runner/work/playwright/playwright/tests/config/test-runner/node_modules/@playwright/test/lib/test/dispatcher.js:409:12)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at emit (internal/child_process.js:877:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

**Comment by aslushnikov** [comment]
This is fixed with #8063
