### ISSUE TITLE
electron.launch: The "file" argument must be of type string. Received an instance of Object[Bug]: 

### ISSUE THREAD

**Issue by razr001** [microsoft/playwright#8073]
### Playwright version

1.12.3

### Operating system

Windows

### Other information

Node.js: v14.17.3
Typescript: 4.3.2
Electron: 13.1.1

### What happened? / Describe the bug

Error
    at Object.captureStackTrace (E:\node_modules\playwright-chromium\lib\utils\stackTrace.js:51:19)
    at Connection.sendMessageToServer (E:\node_modules\playwright-chromium\lib\client\connection.js:73:48)
    at Proxy.<anonymous> (E:\node_modules\playwright-chromium\lib\client\channelOwner.js:64:61)
    at E:\node_modules\playwright-chromium\lib\client\electron.js:43:60
    at Electron._wrapApiCall (E:\node_modules\playwright-chromium\lib\client\channelOwner.js:77:34)
    at Electron.launch (E:\node_modules\playwright-chromium\lib\client\electron.js:35:21)

### Code snippet to reproduce your bug

```shell
import { _electron as electron } from "playwright-chromium";
...
const electronApp = await electron.launch();
...
```

**Comment by mxschmitt** [comment]
To use Electron, you need to provide an entry point of your application, see here: https://playwright.dev/docs/api/class-electron

Passed as the `args` argument when launching electron.
