### ISSUE TITLE
[Bug]: Going to the fidelity statements page in headless mode times out

### ISSUE THREAD

**Issue by kdar** [microsoft/playwright#8085]
### Playwright version

1.14.0-next-alpha-aug-8-2021

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

OS: Windows 10
Node: v16.5.0

### What happened? / Describe the bug

When going to https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList in headless mode, page.goto() just times out. Works in headful mode or with firefox.

### Code snippet to reproduce your bug

```shell
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch({ headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList');
  console.log("done");
})();
```

### Relevant log output

```shell
npx cross-env DEBUG=pw:api node .\index.js
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +2s
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +7ms
  pw:api <= browserContext.newPage succeeded +205ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList", waiting until "load" +2ms     
  pw:api <= page.goto failed +30s
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList", waiting until "load"
============================================================
    at C:\Users\kdar\Desktop\dev\fidelity-test\index2.js:7:14 {
  name: 'TimeoutError'
}

-------------------------

npx cross-env DEBUG=pw:protocol node .\index2.js
  pw:protocol SEND ► {"id":1,"method":"Browser.getVersion"} +0ms
  pw:protocol ◀ RECV {"id":1,"result":{"protocolVersion":"1.3","product":"HeadlessChrome/93.0.4576.0","revision":"@665cd03e414ff1bbaab1d939259ab3ac7b860648","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4576.0 Safari/537.36","jsVersion":"9.3.344"}} +366ms
  pw:protocol SEND ► {"id":2,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true}} +1ms
  pw:protocol ◀ RECV {"id":2,"result":{}} +1ms
  pw:protocol SEND ► {"id":3,"method":"Target.createBrowserContext","params":{"disposeOnDetach":true}} +3ms
  pw:protocol ◀ RECV {"id":3,"result":{"browserContextId":"40D6282B02A963DE7F826E5BEEF7F788"}} +1ms
  pw:protocol SEND ► {"id":4,"method":"Browser.setDownloadBehavior","params":{"behavior":"deny","browserContextId":"40D6282B02A963DE7F826E5BEEF7F788","downloadPath":"C:\\Users\\kdar\\AppData\\Local\\Temp\\playwright-artifacts-kZ1RUo","eventsEnabled":true}} +2ms
  pw:protocol ◀ RECV {"id":4,"result":{}} +3ms
  pw:protocol SEND ► {"id":5,"method":"Target.createTarget","params":{"url":"about:blank","browserContextId":"40D6282B02A963DE7F826E5BEEF7F788"}} +4ms
  pw:protocol ◀ RECV {"method":"Target.attachedToTarget","params":{"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED","targetInfo":{"targetId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","type":"page","title":"","url":"","attached":true,"canAccessOpener":false,"browserContextId":"40D6282B02A963DE7F826E5BEEF7F788"},"waitingForDebugger":true}} +3ms
  pw:protocol SEND ► {"id":6,"method":"Browser.getWindowForTarget","sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +4ms
  pw:protocol ◀ RECV {"id":5,"result":{"targetId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D"}} +1ms
  pw:protocol ◀ RECV {"id":6,"result":{"windowId":1,"bounds":{"left":0,"top":0,"width":800,"height":600,"windowState":"normal"}},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":7,"method":"Page.enable","sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":8,"method":"Page.getFrameTree","sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":9,"method":"Log.enable","params":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol SEND ► {"id":10,"method":"Page.setLifecycleEventsEnabled","params":{"enabled":true},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":11,"method":"Runtime.enable","params":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms        
  pw:protocol SEND ► {"id":12,"method":"Page.addScriptToEvaluateOnNewDocument","params":{"source":"","worldName":"__playwright_utility_world__"},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":13,"method":"Network.enable","sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol SEND ► {"id":14,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":15,"method":"Emulation.setFocusEmulationEnabled","params":{"enabled":true},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol SEND ► {"id":16,"method":"Emulation.setDeviceMetricsOverride","params":{"mobile":false,"width":1280,"height":720,"screenWidth":1280,"screenHeight":720,"deviceScaleFactor":1,"screenOrientation":{"angle":90,"type":"landscapePrimary"}},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":17,"method":"Browser.setWindowBounds","params":{"windowId":1,"bounds":{"width":1280,"height":720}},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":18,"method":"Emulation.setEmulatedMedia","params":{"media":"","features":[{"name":"prefers-color-scheme","value":"light"},{"name":"prefers-reduced-motion","value":"no-preference"}]},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":19,"method":"Runtime.runIfWaitingForDebugger","sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol ◀ RECV {"id":17,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +2ms
  pw:protocol ◀ RECV {"id":14,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +190ms
  pw:protocol ◀ RECV {"id":7,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"id":8,"result":{"frameTree":{"frame":{"id":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","url":"about:blank","domainAndRegistry":"","securityOrigin":"://","mimeType":"text/html","adFrameStatus":{"adFrameType":"none"},"secureContextType":"InsecureScheme","crossOriginIsolatedContextType":"NotIsolated","gatedAPIFeatures":[]}}},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":20,"method":"Page.createIsolatedWorld","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","grantUniveralAccess":true,"worldName":"__playwright_utility_world__"},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +3ms
  pw:protocol ◀ RECV {"id":9,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","name":"commit","timestamp":129021.836403},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms       
  pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","name":"DOMContentLoaded","timestamp":129021.836485},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","name":"load","timestamp":129021.836784},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","name":"networkAlmostIdle","timestamp":129021.83712},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","name":"networkIdle","timestamp":129021.83712},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms   
  pw:protocol ◀ RECV {"id":10,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"://","name":"","uniqueId":"-5960875677719846964.-8046914385427468556","auxData":{"isDefault":true,"type":"default","frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D"}}},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"id":11,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +2ms
  pw:protocol ◀ RECV {"id":12,"result":{"identifier":"1"},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"id":13,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"id":15,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol ◀ RECV {"id":16,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"id":18,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +0ms
  pw:protocol ◀ RECV {"id":19,"result":{},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol SEND ► {"id":21,"method":"Page.navigate","params":{"url":"https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList","frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D"},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +4ms
  pw:protocol ◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":2,"origin":"","name":"__playwright_utility_world__","uniqueId":"-1857257589039972278.4928657319854127281","auxData":{"isDefault":false,"type":"isolated","frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D"}}},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +3ms
  pw:protocol ◀ RECV {"id":20,"result":{"executionContextId":2},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol ◀ RECV {"method":"Network.requestWillBeSent","params":{"requestId":"03C801E78E1B32D4BFA35016BB54BFDF","loaderId":"03C801E78E1B32D4BFA35016BB54BFDF","documentURL":"https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList","request":{"url":"https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4576.0 Safari/537.36"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin","isSameSite":true},"timestamp":129021.858966,"wallTime":1628468873.241557,"initiator":{"type":"other"},"type":"Document","frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","hasUserGesture":false},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms
  pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","name":"networkAlmostIdle","timestamp":129021.83712},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +2s
  pw:protocol ◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"554E3EDCAF431C6B3D2BA7B7B7E09C0D","loaderId":"F5DB6655FC23E07D77E97AE31C5AB20E","name":"networkIdle","timestamp":129021.83712},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +1ms   
  pw:protocol ◀ RECV {"method":"Network.requestWillBeSentExtraInfo","params":{"requestId":"03C801E78E1B32D4BFA35016BB54BFDF","associatedCookies":[],"headers":{"Host":"statements.fidelity.com","Connection":"keep-alive","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4576.0 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","Sec-Fetch-Site":"none","Sec-Fetch-Mode":"navigate","Sec-Fetch-User":"?1","Sec-Fetch-Dest":"document","Accept-Encoding":"gzip, deflate, br"}},"sessionId":"6AB2601090F691AFFD881E8BDE7F95ED"} +436ms
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://statements.fidelity.com/ftgw/fbc/ofstatements/getStatementsList", waiting until "load"
============================================================
    at C:\Users\kdar\Desktop\dev\fidelity-test\index2.js:7:14 {
  name: 'TimeoutError'
}
```

**Comment by aslushnikov** [comment]
@kdar it looks like this website employs some anti-automation techniques so it is not happy with Headless Chrome as a user agent.

We don't suggest any workarounds in this case, so I'll have to close this.
