### ISSUE TITLE
[BUG] Firefox shows Big Error Protocol error 

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#8136]
Windows 10
version:  "playwright":  "^1.13.1",

```
  pw:api => page.evaluate started +9ms
  pw:api <= page.evaluate succeeded +1ms
  pw:api   "networkidle" event fired +1s
  pw:api => page.evaluate started +601ms
  pw:api <= page.evaluate succeeded +1ms
  pw:api => page.evaluate started +2s
  pw:api <= page.evaluate succeeded +1ms
  pw:api => page.evaluate started +2s
  pw:api <= page.evaluate succeeded +1ms
  pw:api   navigated to "https://pages.redacted/wow/i/sg/LandingPage/flashsale-h5?wx_navbar_transparent=true&hybrid=1&data_prefetch=true&use_cache=true&scm=1003.4.icms-zebra-5000357-2586299.OTHER_5996314224_5288858&prefetch_replace=1" +1s
  pw:api   "domcontentloaded" event fired +165ms
  pw:api => page.evaluate started +554ms
  pw:api <= page.evaluate succeeded +1ms
  pw:api => page.evaluate started +2s
  pw:api <= page.evaluate succeeded +2ms
  pw:api   "load" event fired +938ms
  pw:api   "networkidle" event fired +832ms
  pw:api => page.evaluate started +240ms
  pw:api <= page.evaluate succeeded +1ms
  pw:api   navigated to "https://pages.redacted/wow/i/sg/LandingPage/page-flashsale-soldout?wh_weex=true&itemId=684340133&sellerId=100066885&shopId=90096&timeslotId=product_fs_campaign_sg_en_1628611200000&new_api=true&spm=a211g0.flashsale.item.0" +554ms
  pw:api   "domcontentloaded" event fired +192ms
  pw:api => page.evaluate started +1s
  pw:api <= page.evaluate succeeded +1ms
  pw:api   "load" event fired +640ms
  pw:api   navigated to "https://pages.redacted/wow/i/sg/LandingPage/flashsale-h5?wx_navbar_transparent=true&hybrid=1&data_prefetch=true&use_cache=true&scm=1003.4.icms-zebra-5000357-2586299.OTHER_5996314224_5288858&prefetch_replace=1" +248ms
  pw:api   "domcontentloaded" event fired +84ms
  pw:api => page.evaluate started +1s
  pw:api <= page.evaluate succeeded +2ms
  pw:api => page.evaluate started +2s
  pw:api <= page.evaluate succeeded +1ms
Big Error Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
Error:
    at C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:224:16
    at new Promise (<anonymous>)
    at FFSession.send (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:220:12)
    at RawKeyboardImpl.keydown (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffInput.js:59:24)
    at Keyboard.down (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:54:21)
    at Keyboard.press (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:127:24)
    at PageDispatcher.keyboardPress (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\pageDispatcher.js:216:31)
    at DispatcherConnection.dispatch (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\dispatcher.js:330:46)
  pw:api   "load" event fired +2s
Big Error Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
Error:
    at C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:224:16
    at new Promise (<anonymous>)
    at FFSession.send (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:220:12)
    at RawKeyboardImpl.keydown (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffInput.js:59:24)
    at Keyboard.down (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:54:21)
    at Keyboard.press (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:127:24)
    at PageDispatcher.keyboardPress (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\pageDispatcher.js:216:31)
    at DispatcherConnection.dispatch (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\dispatcher.js:330:46)
  pw:api   "networkidle" event fired +2s
Big Error Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
Error:
    at C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:224:16
    at new Promise (<anonymous>)
    at FFSession.send (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:220:12)
    at RawKeyboardImpl.keydown (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffInput.js:59:24)
    at Keyboard.down (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:54:21)
    at Keyboard.press (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:127:24)
    at PageDispatcher.keyboardPress (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\pageDispatcher.js:216:31)
    at DispatcherConnection.dispatch (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\dispatcher.js:330:46)
Big Error Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
Error:
    at C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:224:16
    at new Promise (<anonymous>)
    at FFSession.send (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:220:12)
    at RawKeyboardImpl.keydown (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffInput.js:59:24)
    at Keyboard.down (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:54:21)
    at Keyboard.press (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:127:24)
    at PageDispatcher.keyboardPress (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\pageDispatcher.js:216:31)
    at DispatcherConnection.dispatch (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\dispatcher.js:330:46)
Big Error Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
Error:
    at C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:224:16
    at new Promise (<anonymous>)
    at FFSession.send (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffConnection.js:220:12)
    at RawKeyboardImpl.keydown (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\firefox\ffInput.js:59:24)
    at Keyboard.down (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:54:21)
    at Keyboard.press (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\server\input.js:127:24)
    at PageDispatcher.keyboardPress (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\pageDispatcher.js:216:31)
    at DispatcherConnection.dispatch (C:\Users\quantum\Desktop\projects\redacted\redacted\node_modules\playwright\lib\dispatchers\dispatcher.js:330:46)
 ```
 
 This code that might be responsible
 
 
 ```
   try {
            if (times % 300 === 0) {
                for (let i = 0; i <= 5; i++) {
                    await page.keyboard.down("Shift")
                    await page.keyboard.press("Space")
                    await page.keyboard.up("Shift")
                    await delay(100)
                }
            }

            await page.keyboard.press("Space")
            await page.keyboard.press("Space")
            await page.keyboard.press("Space")
            await page.keyboard.press("Space")
            await page.keyboard.press("Space")
            
            ....
```

**Comment by aslushnikov** [comment]
@shirshak55 This is the same as #5460

If you have a [good repro](https://github.com/microsoft/playwright/issues/5460#issuecomment-840845770), please post it there! I'd be happy to fix it as soon as I can repro this locally!

**Comment by shirshak55** [comment]
@aslushnikov i can send you repo but privately
