### ISSUE TITLE
[Feature] XPath staring with "(//" should be detected as such

### ISSUE THREAD

**Issue by rangeoshun** [microsoft/playwright#817]
**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage('http://whatsmyuseragent.org/');

  await page.$('(//div)[1]');
  await browser.close();
})();
```

**Current behaviour**

The xPath is not recognised as such and is evaluated as a css selector as which it is not valid.

```
(node:31883) UnhandledPromiseRejectionWarning: Error: Evaluation failed: '(//div)[1]' is not a valid selector
query@debugger eval code:171:21
querySelector@debugger eval code:251:33
@debugger eval code:1:42

    at checkException (/Users/avarga/Documents/pro/wp-pro-web-tests-playwright/node_modules/playwright-core/lib/firefox/ffExecutionContext.js:157:19)
    at FFExecutionContext.evaluate (/Users/avarga/Documents/pro/wp-pro-web-tests-playwright/node_modules/playwright-core/lib/firefox/ffExecutionContext.js:92:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/avarga/Documents/pro/wp-pro-web-tests-playwright/node_modules/playwright-core/lib/helper.js:54:23)
    at Page.$ (/Users/avarga/Documents/pro/wp-pro-web-tests-playwright/node_modules/playwright-core/lib/page.js:123:33)
    at Page.<anonymous> (/Users/avarga/Documents/pro/wp-pro-web-tests-playwright/node_modules/playwright-core/lib/helper.js:55:31)
    at /Users/avarga/Documents/pro/wp-pro-web-tests-playwright/bug.js:9:16
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behaviour**

I know that using `xpath=` would work, but I think a regex starting with `(//` could be handled as xPaths as well without any obvious conflict with simple selectors.

**Comment by aslushnikov** [comment]
> XPath staring with "(//" should be detected as such

@rangeoshun it actually is! But selector should actually start with `//` - in your case, it starts with opening parenthesis :)

The following works for me:

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage('http://whatsmyuseragent.org/');

  await page.$('//div[1]');
  await browser.close();
})();
```

**Comment by abelvarga** [comment]
@aslushnikov, `//div[1]` and `(//div)[1]` means something else. While the first means the `div` that's the first child of its parent, the later means the first of the elements that matches `//div`.

<img width="506" alt="Screenshot 2020-02-03 at 21 16 03" src="https://user-images.githubusercontent.com/40273848/73687678-dfc83700-46ca-11ea-929a-e369b1b292f6.png">

If you add something meaningful, like a class match: `(//div[contains(@class,"col-md-8")])[1]`, you'll be able to find the second `.col-md-8` element in the document.

Sorry for making the snippet ambiguous. After reading the document I changed it to a feat request instead.

**Comment by rangeoshun** [comment]
Also, it is not recognised as xPath, hence the error `... is not a valid selector`.

**Comment by aslushnikov** [comment]
@rangeoshun ah! Interesting! Now I see what you mean!
