### ISSUE TITLE
[BUG] HAR recording throws when favicon is served with a redirect

### ISSUE THREAD

**Issue by cjsheets** [microsoft/playwright#8177]
**Context:**
- Playwright Version: v1.13.1
- Operating System: Windows
- Node.js version: v14.17.0
- Browser: Chromium

We use Playwright to integration test a site that serves a hashed favicon by redirecting (302) /favicon.ico to /favicon-[hash].ico.

Playwright HAR recorder filters out the first favicon request and then throws a TypeError when attempting to attach the first requests url to the redirected request (which is not detected as a favicon).

> TypeError: Cannot read property 'request' of undefined
>
>  at HarTracer._onResponse (node_modules/playwright/lib/server/supplements/har/harTracer.js:183:18)
>  at CRBrowserContext.<anonymous> (node_modules/playwright/lib/server/supplements/har/harTracer.js:68:88)
>  at FrameManager.requestReceivedResponse (node_modules/playwright/lib/server/frames.js:238:36)
>  at CRNetworkManager._onResponseReceived (node_modules/playwright/lib/server/chromium/crNetworkManager.js:314:34)
>  at node_modules/playwright/lib/server/chromium/crConnection.js:158:22
>      at runMicrotasks (<anonymous>)

**Comment by cjsheets** [comment]
Proposing resolution with #8176
