### ISSUE TITLE
[BUG] Cannot launch Webkit on CI (`browserType.launch: Protocol error (Playwright.enable): Browser closed)

### ISSUE THREAD

**Issue by alexvdovichenko** [microsoft/playwright#8224]
**Context**

- Playwright Version:  1.13.1
 - Operating System: Ubuntu 20.04.2 LTS
 - Node: v14.17.5
 - Browser: Webkit
 - Other: CI Jenkins, I have tired using both mcr.microsoft.com/playwright:focal and mcr.microsoft.com/playwright:bionic images

**Describe the bug**

Hello guys, I cannot launch my tests on Webkit browser (on Chromium all works fine) on CI (Jenkins) with mcr.microsoft.com/playwright:focal image, As a test runner I am using @playwright/test maybe some one could help me figure out how to battle it or can point on my mistake. I have tried different ways, with installation of browsers separately and tried using the ones that are in the image itself, but I always get the same error :( Thanks :) 

PS: I was trying to add a comment in this [thread](https://github.com/microsoft/playwright/issues/1935), but I couldn't do that, that's why I have created a new issue

PPS: I couldn't see this [page](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) nor [this](https://github.com/microsoft/playwright/tree/master/docs/docker) one, I get 404. Those pages were suggested to figure out missing dependencies in the thread mentioned in PS section.

**Jenkinsfile**:
`pipeline {
   agent { docker { 
      image 'mcr.microsoft.com/playwright:focal'
      args '-u root'
      } }
   stages {
      stage('e2e-tests') {
         steps {
            dir('_autotests') {
                sh 'yarn install'
                sh "npx playwright install-deps chromium"
                sh "npx playwright install-deps webkit"
                sh "npx playwright install webkit"
                sh "npx playwright install chromium"
                sh "DEBUG=pw:browser* npx playwright test"
            }
         }
      }
   }
}`

**Error message:**

`+ DEBUG=pw:browser* npx playwright test
2021-08-16T14:44:36.771Z pw:browser <launching> /ms-playwright/webkit-1516/pw_run.sh --inspector-pipe --no-startup-window
2021-08-16T14:44:36.777Z pw:browser <launched> pid=956
2021-08-16T14:44:36.900Z pw:browser [pid=956][err] Unable to init server: Could not connect: Connection refused
2021-08-16T14:44:36.900Z pw:browser [pid=956][err] 
2021-08-16T14:44:36.900Z pw:browser [pid=956][err] (MiniBrowser:961): Gtk-WARNING **: 14:44:36.899: cannot open display: 
2021-08-16T14:44:36.932Z pw:browser [pid=956] <gracefully close start>
2021-08-16T14:44:36.932Z pw:browser [pid=956] <kill>
2021-08-16T14:44:36.933Z pw:browser [pid=956] <will force kill>
2021-08-16T14:44:36.933Z pw:browser [pid=956] starting temporary directories cleanup
2021-08-16T14:44:36.936Z pw:browser [pid=956] <process did exit: exitCode=1, signal=null>
2021-08-16T14:44:36.936Z pw:browser [pid=956] starting temporary directories cleanup
2021-08-16T14:44:36.937Z pw:browser [pid=956] finished temporary directories cleanup
2021-08-16T14:44:36.937Z pw:browser [pid=956] finished temporary directories cleanup
2021-08-16T14:44:36.937Z pw:browser [pid=956] <gracefully close end>
F2021-08-16T14:44:37.674Z pw:browser <launching> /ms-playwright/webkit-1516/pw_run.sh --inspector-pipe --no-startup-window
2021-08-16T14:44:37.681Z pw:browser <launched> pid=1143
2021-08-16T14:44:37.718Z pw:browser [pid=1143][err] Unable to init server: Could not connect: Connection refused
2021-08-16T14:44:37.718Z pw:browser [pid=1143][err] 
2021-08-16T14:44:37.719Z pw:browser [pid=1143][err] (MiniBrowser:1148): Gtk-WARNING **: 14:44:37.718: cannot open display: 
2021-08-16T14:44:37.725Z pw:browser [pid=1143] <gracefully close start>
2021-08-16T14:44:37.725Z pw:browser [pid=1143] <kill>
2021-08-16T14:44:37.726Z pw:browser [pid=1143] <will force kill>
2021-08-16T14:44:37.726Z pw:browser [pid=1143] starting temporary directories cleanup
2021-08-16T14:44:37.729Z pw:browser [pid=1143] <process did exit: exitCode=1, signal=null>
2021-08-16T14:44:37.729Z pw:browser [pid=1143] starting temporary directories cleanup
2021-08-16T14:44:37.729Z pw:browser [pid=1143] finished temporary directories cleanup
2021-08-16T14:44:37.730Z pw:browser [pid=1143] finished temporary directories cleanup
2021-08-16T14:44:37.730Z pw:browser [pid=1143] <gracefully close end>`

`browserType.launch: Protocol error (Playwright.enable): Browser closed.
    ==================== Browser output: ====================
    <launching> /ms-playwright/webkit-1516/pw_run.sh --inspector-pipe --no-startup-window
    <launched> pid=956
    [pid=956][err] Unable to init server: Could not connect: Connection refused
    [pid=956][err] 
    [pid=956][err] (MiniBrowser:961): Gtk-WARNING **: 14:44:36.899: cannot open display: 
    =========================== logs ===========================
    <launching> /ms-playwright/webkit-1516/pw_run.sh --inspector-pipe --no-startup-window
    <launched> pid=956
    [pid=956][err] Unable to init server: Could not connect: Connection refused
    [pid=956][err] 
    [pid=956][err] (MiniBrowser:961): Gtk-WARNING **: 14:44:36.899: cannot open display: 
    ============================================================

        at Object._baseTest.extend.browser.scope [as fn] (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/index.js:85:51)
        at Fixture.setup (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
        at FixtureRunner.setupFixtureForRegistration (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/fixtures.js:296:5)
        at Fixture.setup (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/fixtures.js:296:5)
        at Fixture.setup (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/fixtures.js:296:5)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/fixtures.js:283:23)
        at WorkerRunner._runHooks (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/workerRunner.js:439:9)
        at WorkerRunner._runTestWithBeforeHooks (/var/jenkins_home/workspace/Tests/e2e_js/_autotests/node_modules/@playwright/test/lib/test/workerRunner.js:375:7)
`
Thanks in advance!

**Comment by alexvdovichenko** [comment]
Sorry, it's my bad :) I have been so focused on this error for a couple of days, that It hasn't dawned on me to check the config file and it turned out that I was trying to run my tests in the headed mode on CI  (facepalm :))
