### ISSUE TITLE
[BUG] ERROR	page.goto: net::ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by BrunoQuaresma** [microsoft/playwright#8239]
I'm using the following code to access the TikTok video URL and get the video source.

```typescript
const browser = await playwright.launchChromium();
const context = await browser.newContext();
const page = await context.newPage();
await page.goto(
  "https://www.tiktok.com/@comedydynamics/video/6996824421063232774"
);
await page.waitForSelector("video");
const videoElement = await page.$("video");
const videoSrc = await videoElement.getAttribute("src");
console.log(videoSrc)
```

It works as expected locally, but when I get it deployed to prod on Vercel, I see the following error:
```bash
2021-08-16T23:36:35.577Z pw:api => browserType.launch started
2021-08-16T23:36:35.654Z pw:api <= browserType.launch succeeded
2021-08-16T23:36:35.654Z pw:api => browser.newContext started
2021-08-16T23:36:35.671Z pw:api <= browser.newContext succeeded
2021-08-16T23:36:35.672Z pw:api => browserContext.newPage started
2021-08-16T23:36:35.794Z pw:api <= browserContext.newPage succeeded
2021-08-16T23:36:35.794Z pw:api => page.goto started
2021-08-16T23:36:35.796Z pw:api navigating to "https://www.tiktok.com/@comedydynamics/video/6996824421063232774", waiting until "load"
2021-08-16T23:36:35.952Z pw:api <= page.goto failed
2021-08-16T23:36:35.953Z	e18f862d-d09b-4753-bfa5-f751f45a1997	ERROR	page.goto: net::ERR_INVALID_RESPONSE at https://www.tiktok.com/@comedydynamics/video/6996824421063232774
=========================== logs ===========================
navigating to "https://www.tiktok.com/@comedydynamics/video/6996824421063232774", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/var/task/node_modules/playwright-core/lib/utils/stackTrace.js:51:19)
    at Connection.sendMessageToServer (/var/task/node_modules/playwright-core/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/var/task/node_modules/playwright-core/lib/client/channelOwner.js:64:61)
    at /var/task/node_modules/playwright-core/lib/client/frame.js:100:65
    at Frame._wrapApiCall (/var/task/node_modules/playwright-core/lib/client/channelOwner.js:77:34)
    at Frame.goto (/var/task/node_modules/playwright-core/lib/client/frame.js:98:21)
    at /var/task/node_modules/playwright-core/lib/client/page.js:267:60
    at Page._attributeToPage (/var/task/node_modules/playwright-core/lib/client/page.js:202:20)
    at Page.goto (/var/task/node_modules/playwright-core/lib/client/page.js:267:21)
    at getVideoUrl (/var/task/.next/server/pages/api/download/tiktok.js:47:16)
    at async tiktokDownloadHandler (/var/task/.next/server/pages/api/download/tiktok.js:87:20)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:760:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:651:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:205:32)
    at async Server.run (/var/task/node_modules/next/dist/server/next-server.js:825:29)
    at async Server.handleRequest (/var/task/node_modules/next/dist/server/next-server.js:292:20)
    at async Server.<anonymous> (/var/task/___next_launcher.js:32:9)
2021-08-16T23:36:35.954Z pw:api => browser.close started
2021-08-16T23:36:35.973Z pw:api   navigated to "chrome-error://chromewebdata/"
2021-08-16T23:36:35.974Z pw:api   "load" event fired
2021-08-16T23:36:35.974Z pw:api   "domcontentloaded" event fired
2021-08-16T23:36:36.026Z pw:api <= browser.close succeeded
```

To run this on Vercel I'm using:
- playwright-aws-lambda 0.7.0
- playwright-core 1.12.2

Thank you in advance.

**Comment by pavelfeldman** [comment]
Looks like Tiktok doesn't like receiving requests from the cloud. Spam detection? In either case does not look Playwright-related.

**Comment by BrunoQuaresma** [comment]
Ahhh, I see. Thank you.
