### ISSUE TITLE
[BUG] chromium emit 'crash' event when page.goto(somepage) on macos

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#8257]
### Playwright version

1.14.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Run the following code:
```
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({
        headless: false
    });
    console.log(`${new Date().toLocaleString()}: chromium-v${browser.version()}`);
    const context = await browser.newContext();
    const page = await context.newPage();
    page.once('crash', _ => {
        console.log(`${new Date().toLocaleString()}: crash event emitted.`);
    })
    await page.goto('https://www.ig.com.br/');
})();
```
The page would emit a 'crash' event after evaluating the code above about 2~3 min later.
```
» node test.js
2021/8/17 下午9:02:08: chromium-v93.0.4530.0
2021/8/17 下午9:02:23: crash event emitted.
```
Note that URL https://www.apple.com would not emit the 'crash' event.

### What happened? / Describe the bug

page.once('crash') catchs a 'crash' event when evaluating this code.

**Comment by JoelEinbinder** [comment]
Hi. Thanks for the report. Can you run it again with `DEBUG=pw:browser node test.js` to see if we get a stack trace? Thanks!

**Comment by zyscoder** [comment]
> Hi. Thanks for the report. Can you run it again with `DEBUG=pw:browser node test.js` to see if we get a stack trace? Thanks!

```
» DEBUG=pw:browser node test.js 
  pw:browser <launching> /Users/zys/Library/Caches/ms-playwright/chromium-888113/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/var/folders/7_/m35llp2s3_l3k8yghlv4md3r0000gn/T/playwright_chromiumdev_profile-D1IB2k --remote-debugging-pipe --no-sandbox --no-startup-window +0ms
  pw:browser <launched> pid=53773 +4ms
2021/8/17 下午9:09:19: chromium-v93.0.4530.0
  pw:browser [pid=53773][err] 2021-08-17 21:09:23.264 Chromium Helper (Renderer)[53790:5509526] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:]. +5s
  pw:browser [pid=53773][err] 2021-08-17 21:09:23.264 Chromium Helper (Renderer)[53790:5509526] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug. +0ms
  pw:browser [pid=53773][err] 2021-08-17 21:09:25.355 Chromium Helper (Renderer)[53790:5509526] CoreText note: Client requested name ".AppleSymbolsFB", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:]. +2s
  pw:browser [pid=53773][err] Received signal 11 SEGV_MAPERR 0000000003f0 +11s
  pw:browser [pid=53773][err]  [0x000117b70089] +0ms
  pw:browser [pid=53773][err]  [0x000117ac3123] +0ms
  pw:browser [pid=53773][err]  [0x000117b6ffe1] +0ms
  pw:browser [pid=53773][err]  [0x7fff6f0775fd] +0ms
  pw:browser [pid=53773][err]  [0x00011eccf5b8] +0ms
  pw:browser [pid=53773][err]  [0x00011bd4be7f] +0ms
  pw:browser [pid=53773][err]  [0x00011c562453] +0ms
  pw:browser [pid=53773][err]  [0x00011c1daf34] +0ms
  pw:browser [pid=53773][err]  [0x00011c1dc619] +0ms
  pw:browser [pid=53773][err]  [0x00011c1de5d9] +0ms
  pw:browser [pid=53773][err]  [0x00011c17eff3] +0ms
  pw:browser [pid=53773][err]  [0x00011c179aca] +0ms
  pw:browser [pid=53773][err]  [0x00011cdfc462] +0ms
  pw:browser [pid=53773][err]  [0x00011bfd73ec] +0ms
  pw:browser [pid=53773][err]  [0x00011bf52f18] +0ms
  pw:browser [pid=53773][err]  [0x00011bf32f11] +0ms
  pw:browser [pid=53773][err]  [0x00011d8cd4d3] +0ms
  pw:browser [pid=53773][err]  [0x000114f99dc1] +0ms
  pw:browser [pid=53773][err]  [0x00011827b53a] +0ms
  pw:browser [pid=53773][err]  [0x00011827f5e9] +0ms
  pw:browser [pid=53773][err]  [0x00011827c916] +0ms
  pw:browser [pid=53773][err]  [0x000118b12e35] +1ms
  pw:browser [pid=53773][err]  [0x000118b105ea] +0ms
  pw:browser [pid=53773][err]  [0x000117b29833] +0ms
  pw:browser [pid=53773][err]  [0x000117b3e233] +0ms
  pw:browser [pid=53773][err]  [0x000117b3df3a] +0ms
  pw:browser [pid=53773][err]  [0x000117b838d1] +0ms
  pw:browser [pid=53773][err]  [0x000117b7db32] +0ms
  pw:browser [pid=53773][err]  [0x000117b8327f] +0ms
  pw:browser [pid=53773][err]  [0x7fff34dde832] +0ms
  pw:browser [pid=53773][err]  [0x7fff34dde7d1] +0ms
  pw:browser [pid=53773][err]  [0x7fff34dde5eb] +0ms
  pw:browser [pid=53773][err]  [0x7fff34ddd31a] +0ms
  pw:browser [pid=53773][err]  [0x7fff34ddc91e] +0ms
  pw:browser [pid=53773][err]  [0x7fff374781a8] +0ms
  pw:browser [pid=53773][err]  [0x000117b83e0e] +0ms
  pw:browser [pid=53773][err]  [0x000117b82dc3] +0ms
  pw:browser [pid=53773][err]  [0x000117b3e885] +0ms
  pw:browser [pid=53773][err]  [0x000117b07aeb] +0ms
  pw:browser [pid=53773][err]  [0x00011d900a30] +0ms
  pw:browser [pid=53773][err]  [0x000117a440ca] +0ms
  pw:browser [pid=53773][err]  [0x000117a42be9] +0ms
  pw:browser [pid=53773][err]  [0x000117a433dd] +0ms
  pw:browser [pid=53773][err]  [0x000114244875] +0ms
  pw:browser [pid=53773][err]  [0x00010efac4da] +0ms
  pw:browser [pid=53773][err]  [0x7fff6ee7ecc9] +0ms
  pw:browser [pid=53773][err] [end of stack trace] +0ms
  pw:browser [pid=53773][err] [0817/210936.245589:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee0c56000, 0x2000): (os/kern) invalid address (1) +4ms
2021/8/17 下午9:09:36: crash event emitted.
```

**Comment by JoelEinbinder** [comment]
I am unable to reproduce this locally, but my goal is to figure out if Chromium just crashes on this website or if something about playwright causes the crash. If you run `/Users/zys/Library/Caches/ms-playwright/chromium-888113/chrome-mac/Chromium.app/Contents/MacOS/Chromium` and open the web page manually does it still crash? If not, can you try passing [`ignoreDefaultArgs: true`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-ignore-default-args) into launch and see if it crashes? Thanks!

**Comment by zyscoder** [comment]
@JoelEinbinder
 /Users/zys/Library/Caches/ms-playwright/chromium-888113/chrome-mac/Chromium.app/Contents/MacOS/Chromium and open the web page manually it would not crash.

try passing ignoreDefaultArgs: true into the launch and it always timeout:
```
» DEBUG=pw:browser node test.js 
  pw:browser <launching> /Users/zys/Library/Caches/ms-playwright/chromium-888113/chrome-mac/Chromium.app/Contents/MacOS/Chromium  +0ms
  pw:browser <launched> pid=55152 +5ms
  pw:browser [pid=55152] <gracefully close start> +30s
  pw:browser [pid=55152] <kill> +3ms
  pw:browser [pid=55152] <will force kill> +0ms
  pw:browser [pid=55152] starting temporary directories cleanup +1ms
  pw:browser [pid=55152] finished temporary directories cleanup +11ms
  pw:browser [pid=55152] <process did exit: exitCode=null, signal=SIGKILL> +15ms
  pw:browser [pid=55152] starting temporary directories cleanup +1ms
  pw:browser [pid=55152] finished temporary directories cleanup +0ms
  pw:browser [pid=55152] <gracefully close end> +0ms
(node:55150) UnhandledPromiseRejectionWarning: browserType.launch: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /Users/zys/Library/Caches/ms-playwright/chromium-888113/chrome-mac/Chromium.app/Contents/MacOS/Chromium 
<launched> pid=55152
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
Error
    at Object.captureStackTrace (/Users/zys/node_modules/playwright/lib/utils/stackTrace.js:51:19)
    at Connection.sendMessageToServer (/Users/zys/node_modules/playwright/lib/client/connection.js:73:48)
    at Proxy.<anonymous> (/Users/zys/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Users/zys/node_modules/playwright/lib/client/browserType.js:59:67
    at BrowserType._wrapApiCall (/Users/zys/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at BrowserType.launch (/Users/zys/node_modules/playwright/lib/client/browserType.js:50:21)
    at /Users/zys/Desktop/test.js:4:36
    at Object.<anonymous> (/Users/zys/Desktop/test.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:55150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:55150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pavelfeldman** [comment]
`npx playwright install chromium-with-symbols`

then pass it to the `channel` or `executablePath` as you launch it.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
