### ISSUE TITLE
[BUG][Electron] filechooser event not emitted when dialog.show(Open|Save)Dialog is called

### ISSUE THREAD

**Issue by OiNutter** [microsoft/playwright#8278]
Duplicate of #5013. Full details and repro steps available there.

Opening new issue as requested by maintainers on original issue.

This is definitely a blocker for our integration tests as we need to test open and save functionality in our app and we're not able to select the files in the dialogs.

**Comment by tgdcat** [comment]
I'm also having trouble with showOpenDialogSync and showSaveDialogSync because the test stopped.   
Is there any workaround?

**Comment by wsw0108** [comment]
I have create a test repo to trying to mock electron dialog like `spectron-fake-dialog` does, but failed.

https://github.com/wsw0108/electron-playwright-test/blob/master/test/test.js

Does anyone may have time to help to find out why?

**Comment by Daveiano** [comment]
I am also having this issue and have been looking for a solution. 

@wsw0108 I am quite new to JS testing, but I will have a look into your code if I get some time. Please report back!

**Comment by wsw0108** [comment]
@Daveiano I have found the fail cause, it's the async thing of electron ipc. The mock works actually.

**Comment by wsw0108** [comment]
Based on spectron-fake-dialog, I wrote a little library to fake electron dialog for playwright/electron, 
https://github.com/wsw0108/playwright-fake-dialog

**Comment by MikeJerred** [comment]
> Based on spectron-fake-dialog, I wrote a little library to fake electron dialog for playwright/electron, https://github.com/wsw0108/playwright-fake-dialog

Awesome! Can actually simplify this and just do:

```typescript
const electronApp = await playwright._electron.launch({ args: ['./main.js']});

// ...

// in test:
electronApp.evaluate(
  async({ dialog }, filePaths) => {
    dialog.showOpenDialog = () => Promise.resolve({ canceled: false, filePaths });
  },
  ['file.txt']
);
```

**Comment by wsw0108** [comment]
@MikeJerred Elegant solution. 

Can I use your idea to update my repo?

**Comment by MikeJerred** [comment]
> @MikeJerred Elegant solution.
> 
> Can I use your idea to update my repo?

Yep of course

**Comment by Daveiano** [comment]
@wsw0108 I am getting this error when using playwright-fake-dialog

```
page.evaluate: ReferenceError: require is not defined
    at eval (eval at evaluate (:3:2389), <anonymous>:2:31)
    at t.default.evaluate (<anonymous>:3:2412)
    at t.default.<anonymous> (<anonymous>:1:44)

    at ipcRendererSendSyncAsync (/var/www/weather-data-center-electron-forge/node_modules/playwright-fake-dialog/index.js:12:15)
    at mock (/var/www/weather-data-center-electron-forge/node_modules/playwright-fake-dialog/index.js:22:10)
    at /var/www/weather-data-center-electron-forge/src/main/renderer-empty.test.ts:93:13
    at fulfilled (/var/www/weather-data-center-electron-forge/src/main/renderer-empty.test.ts:5:58)
```

Setup is the following:

```
import { _electron as electron } from "playwright-core";
const { launch, mock } = require('playwright-fake-dialog')

...

beforeAll(async () => {
  // Launch Electron app.
  electronApp = await launch(electron, {
    args: [
      '.'
    ],
    env: {
      ...process.env
    },
  });

  // Get the first window that the app opens, wait if necessary.
  page = await electronApp.firstWindow();

  // Wait for frame actually loaded.
  await page.waitForSelector('main');

  // Direct Electron console to Node terminal.
  page.on('console', console.log);
});

...

it('should import new data', async () => {
  await mock(page, [
    {
      method: 'showOpenDialog',
      value: {
        filePaths: [`${__dirname.replace('src/main', '')}tests/data/upload-data-start-16-08-21-30-09-21-1196-records.csv`]
      }
    }
  ]);

  await page.click('button#import');
});
```

Any help and suggestions would be very appreciated!

**Comment by wsw0108** [comment]
https://github.com/wsw0108/electron-playwright-test/blob/e3c6ff53d9d71360270ddd37305b188b8273d2c5/app/main/index.js#L43

using 0.1.0 needs above lines in your electron main.js.

**Comment by Daveiano** [comment]
Ah, got you, thank you! 

I got it working now with the snippet from @MikeJerred, many thanks for that!

**Comment by FomerMay** [comment]
H, i need some help to use the playwright-fake-dialog, do i need any code from "test/preload.js"?(https://github.com/wsw0108/electron-playwright-test/blob/master/test/preload.js).

This is my code

 ```
 await mock(electronApp, [
    {
      method: 'showOpenDialog',
      value: {
        filePaths: [join(__dirname, 'minimal.pdf')]
      }
    }
  ])
  await newPage.click('[e2e-id="action-bar-create"]');
```

"fs.api.selectFilesWithOpenDialog (id 46189c0c) - failed due to error: n.a.dialog.showOpenDialog is not a function"

Our Application uses Electron 9, could that be a problem?

**Comment by dquak** [comment]
> > Based on spectron-fake-dialog, I wrote a little library to fake electron dialog for playwright/electron, https://github.com/wsw0108/playwright-fake-dialog
> 
> Awesome! Can actually simplify this and just do:
> 
> ```ts
> const electronApp = await playwright._electron.launch({ args: ['./main.js']});
> 
> // ...
> 
> // in test:
> electronApp.evaluate(
>   async({ dialog }, filePaths) => {
>     dialog.showOpenDialog = () => Promise.resolve({ canceled: false, filePaths });
>   },
>   ['file.txt']
> );
> ```

best method, you can also control dialogs like so:
```
const dialogControlHandler = electronApp.evaluateHandler(() => {
  let resolve;
  const promise = new Promise(res => { resolve = res; });
  
  return {promise, resolve};
});


const dialogOptions = await electronApp.evaluate(
 async({ dialog },{ dialogControlHandler }) => {
   return new Promise(res => {
     dialog.showMessageBox = (options) => {
       res(options);
       return dialogControlHandler.promise;
     };
   });
  },
 { dialogControlHandler }
);

//Now you have the dialog options avaliable at `dialogOptions` (eg: dialogOptions.title)

//Choose how to resolve the dialog:
dialogControlHandler.evaluate( ({ resolve }) => resolve({response: 1, checkboxchecked: false}) );

**Comment by mxschmitt** [comment]
Investigation:
- Upstream Electron method [ShowOpenDialog](https://github.com/electron/electron/blob/193e162ec6efbb688de2a0fd533c87ab0666d133/shell/browser/api/electron_api_dialog.cc#L65) calls immediately OS APIs
- When dealing with normal file pickers, upstream its a noop when intercepted like [here in this cp](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/file_system_access/global_file_system_access.cc;l=257?q=language:cpp%20FileChooserOpened%20-file:out&ss=chromium%2Fchromium%2Fsrc)
- Probably a new event should be introduced so Electron can wait for it and return the value once emitted. Since Electron API would be different. event -> path[] all the time. It's never a file content etc.
- Similar / different request is about setInputFiles should set path property. There we should extend 'DOM.setFileInputFiles' so it sets the path. https://github.com/microsoft/playwright/issues/10527

**Comment by 1103837067** [comment]
it works for me.it can be a refrence
```javascript

  /**
   * 处理文件选择和上传
   * @param clickCallback 点击按钮的回调函数，将在模拟对话框设置后执行
   * @param filePath 文件路径
   */
  async handleSelectFile(clickCallback: () => Promise<void>, filePath: string): Promise<void> {
    await test.step(`选择文件: ${filePath}`, async () => {
      try {
        // 获取Electron应用实例
        const electronApp = AppMainManager.getAppMain();
        if (!electronApp) {
          throw new Error('未找到Electron应用实例');
        }
        
        // 替换Electron的文件对话框函数
        await electronApp.evaluate(({ dialog }, filePaths) => {
          if (dialog.showOpenDialog) {
            // 替换异步方法
            dialog.showOpenDialog = () => Promise.resolve({
              canceled: false,
              filePaths: Array.isArray(filePaths) ? filePaths : [filePaths]
            });
          }
          
        }, filePath);
       
 
        // 执行点击回调，触发应用中的文件选择逻辑
        await clickCallback();
        
        console.log('文件选择完成');
      } catch (error) {
        console.error("模拟文件选择对话框失败:", error);
        throw error;
      }
    });
  }
```
