### ISSUE TITLE
[BUG] webkit crashes intermittently: "file data stream has an unexpected number of bytes"

### ISSUE THREAD

**Issue by keevie** [microsoft/playwright#8287]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Linux/docker container: mcr.microsoft.com/playwright:v1.14.0-focal 
- Node.js version: [14.16.1]
- Browser: WebKit

Webkit crashes intermittently with the following stack trace -- I'm not sure how to reproduce consistently, but it doesn't seem to have anything to do with my specific tests?

```
browserContext.close: browserContext.close: file data stream has unexpected number of bytes
    at Object.context [as fn] (/usr/src/app/node_modules/@playwright/test/lib/test/index.js:338:19)
    at Fixture.teardown (/usr/src/app/node_modules/@playwright/test/lib/test/fixtures.js:98:7)
    at FixtureRunner.teardownScope (/usr/src/app/node_modules/@playwright/test/lib/test/fixtures.js:269:11)
    at WorkerRunner._runAfterHooks (/usr/src/app/node_modules/@playwright/test/lib/test/workerRunner.js:457:7)
```

**Comment by pavelfeldman** [comment]
Looks like a tracing-related regression. @dgozman: empty zip?

**Comment by keevie** [comment]
I have tracing set to retain-on-failure in my playwright.config.ts, for what it's worth.

**Comment by dgozman** [comment]
Cherry-picked to v1.14.1 in #8317.
