### ISSUE TITLE
[BUG]  browserType.launch: Chromium distribution 'chrome'

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8321]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Windows
- Browser:  Chromium
- Extra: GitLab Runner

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const config: PlaywrightTestConfig = {
  retries: 1,
  timeout: 180000,
  globalTimeout: 300000,
  reporter: [["./my-reporter.ts"], ["list"], ["junit", { outputFile: "reports/test-results.xml" }]],
  use: {
    trace: 'on',
    screenshot: 'on',
    video: {
      mode: "on",
      size: {
        width: 1920,
        height: 1080
      }
    },
    contextOptions: {
      viewport: { width: 1920, height: 1080 },
    },
    // Browser options   
    launchOptions: {     
      channel: 'chrome', //Changed back to chromium due to the issue with chrome on CI
      headless: false,
      //args: ['--start-maximized']
    },
    //slowMo: 0,
  },
};

export default config;

```

**Describe the bug**

I try to run with Playwright on the GitLab Runner. I run successfully with Chromium, but can't run with Chrome. The log of the issue:

```
@playwright/test@1.14.0 install C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test
 node install.js
  
  
  playwright@1.14.0 install C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\playwright
  node install.js
  
  Playwright build of chromium v907428 downloaded to C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\chromium-907428
  Playwright build of ffmpeg v1005 downloaded to C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\ffmpeg-1005
  Playwright build of firefox v1281 downloaded to C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\firefox-1281
  Playwright build of webkit v1530 downloaded to C:\Windows\system32\config\systemprofile\AppData\Local\ms-playwright\webkit-1530
  npm notice created a lockfile as package-lock.json. You should commit this file.
  npm WARN playwright-seatgeek@1.0.0 No description
  npm WARN playwright-seatgeek@1.0.0 No repository field.
  
  added 189 packages from 195 contributors and audited 189 packages in 41.749s
  
  13 packages are looking for funding
    run `npm fund` for details
  
  found 0 vulnerabilities
  
  After NPM Install
  npm run test:1
  
  > playwright-seatgeek@1.0.0 test:1 C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest
  > npx playwright test --workers=1
  
  Starting the run with 2 tests
  
  Starting test Login with correct credentials
    x  unify\tests\loginTest.test.ts:30:8 › Login Test Feature Login with correct credentials (16ms)
  Starting test Navigate between all categories
    x  unify\tests\modulesNavigation.test.ts:29:8 › Navigation Feature Navigate between all categories (17ms)
  Starting test Login with correct credentials
    x  unify\tests\loginTest.test.ts:30:8 › Login Test Feature Login with correct credentials (16ms)
  Starting test Navigate between all categories
    x  unify\tests\modulesNavigation.test.ts:29:8 › Navigation Feature Navigate between all categories (19ms)
  Finished the run: failed
  
  
    1) unify\tests\loginTest.test.ts:30:8 › Login Test Feature Login with correct credentials ========
  
      browserType.launch: Chromium distribution 'chrome' is not found at C:\Windows\system32\config\systemprofile\AppData\Local\Google\Chrome\Application\chrome.exe
      Run "npx playwright install chrome"
  
          at Object._baseTest.extend.browser.scope [as fn] (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\index.js:117:40)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:73:73)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at FixtureRunner.resolveParametersAndRunHookOrTest (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:297:23)
          at WorkerRunner._runHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:484:9)
          at WorkerRunner._runBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:405:7)
          at WorkerRunner._runTestWithBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:420:32)
  
      Retry #1 ---------------------------------------------------------------------------------------
  
      browserType.launch: Chromium distribution 'chrome' is not found at C:\Windows\system32\config\systemprofile\AppData\Local\Google\Chrome\Application\chrome.exe
      Run "npx playwright install chrome"
  
          at Object._baseTest.extend.browser.scope [as fn] (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\index.js:117:40)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:73:73)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at FixtureRunner.resolveParametersAndRunHookOrTest (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:297:23)
          at WorkerRunner._runHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:484:9)
          at WorkerRunner._runBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:405:7)
          at WorkerRunner._runTestWithBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:420:32)
  
    2) unify\tests\modulesNavigation.test.ts:29:8 › Navigation Feature Navigate between all categories 
  
      browserType.launch: Chromium distribution 'chrome' is not found at C:\Windows\system32\config\systemprofile\AppData\Local\Google\Chrome\Application\chrome.exe
      Run "npx playwright install chrome"
  
          at Object._baseTest.extend.browser.scope [as fn] (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\index.js:117:40)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:73:73)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at FixtureRunner.resolveParametersAndRunHookOrTest (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:297:23)
          at WorkerRunner._runHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:484:9)
          at WorkerRunner._runBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:405:7)
          at WorkerRunner._runTestWithBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:420:32)
  
      Retry #1 ---------------------------------------------------------------------------------------
  
      browserType.launch: Chromium distribution 'chrome' is not found at C:\Windows\system32\config\systemprofile\AppData\Local\Google\Chrome\Application\chrome.exe
      Run "npx playwright install chrome"
  
          at Object._baseTest.extend.browser.scope [as fn] (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\index.js:117:40)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:73:73)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at Fixture.setup (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:58:19)
          at FixtureRunner.setupFixtureForRegistration (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:310:5)
          at FixtureRunner.resolveParametersAndRunHookOrTest (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\fixtures.js:297:23)
          at WorkerRunner._runHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:484:9)
          at WorkerRunner._runBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:405:7)
          at WorkerRunner._runTestWithBeforeHooks (C:\builds\j-hmRMFE\0\sro\sro4\uiAutomation\PlaywrightTest\node_modules\@playwright\test\lib\test\workerRunner.js:420:32)
  
  
    2 failed
      unify\tests\loginTest.test.ts:30:8 › Login Test Feature Login with correct credentials =========
      unify\tests\modulesNavigation.test.ts:29:8 › Navigation Feature Navigate between all categories 
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! playwright-seatgeek@1.0.0 test:1: `npx playwright test --workers=1`
  npm ERR! Exit status 1


```

**Comment by mxschmitt** [comment]
On your system there is no Chrome installation. You can install it using `npx playwright install chrome` as the logs say.

**Comment by AlexKomanov** [comment]
Thanks @mxschmitt , I thought it performs the command. 
Just to understand, in this case, I need to run `npx playwright install chrome` command before I'll run the tests and the installation process will install the chrome browser to the particular path that expected by runner?

**Comment by mxschmitt** [comment]
Exactly. Chrome does not get installed when using `npx playwright install`. It just installs Chromium, Firefox, and WebKit by default.

**Comment by AlexKomanov** [comment]
Thanks @mxschmitt 
Works perfect!!!

![image](https://user-images.githubusercontent.com/52656401/130178121-7622aeaf-f71e-46df-bd18-76295e5eba94.png)
