### ISSUE TITLE
test() can only be called in a test file

### ISSUE THREAD

**Issue by kdawg1981** [microsoft/playwright#8345]
I'm needing some help with playwright. I started a new project and created one test to make sure that it was working, but I'm getting the following error message: 
`Error: tests\test.spec.js:3:1: test() can only be called in a test file
    at errorWithLocation (C:\Users\kevin.morales\source\repos\playwright_bridge\node_modules\@playwright\test\lib\test\util.js:220:10)
    at TestTypeImpl._createTest (C:\Users\kevin.morales\source\repos\playwright_bridge\node_modules\@playwright\test\lib\test\testType.js:76:51)
    at C:\Users\kevin.morales\source\repos\playwright_bridge\node_modules\@playwright\test\lib\test\transform.js:133:12
    at Object.<anonymous> (C:\Users\kevin.morales\source\repos\playwright_bridge\tests\test.spec.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Loader._requireOrImport (C:\Users\kevin.morales\Source\Repos\Playwright_Bridge\node_modules\@playwright\test\lib\test\loader.js:211:18)
    at Loader.loadTestFile (C:\Users\kevin.morales\Source\Repos\Playwright_Bridge\node_modules\@playwright\test\lib\test\loader.js:130:18)
    at Runner._run (C:\Users\kevin.morales\Source\Repos\Playwright_Bridge\node_modules\@playwright\test\lib\test\runner.js:210:59)`

I have done a uninstall and reinstall of playwright on my system through NPM and I'm not sure what is going on here. Any help would be greatly appreciated. 

Thank you, 

Kevin Morales

**Comment by mxschmitt** [comment]
You could provide us your `tests\test.spec.js` or even better a small repro in form of a GithHub repository?

**Comment by kdawg1981** [comment]
`const { test, expect } = require('@playwright/test');

test('basic test', async({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});`

Now this is just the basic test that playwright gives you on the page.

**Comment by JoelEinbinder** [comment]
You run this file via `npx playwright test` after saving it something like `foo.test.js`.

It looks like you are trying to run it directly via `node foo.test.js`

**Comment by JoelEinbinder** [comment]
I'm suspicious of the change from uppercase to lowercase letters in your stack trace. Maybe node is reinitializing the test runner with the new casing.

Otherwise I'd say theres another error being swallowed somewhere, and this is just masking it.

**Comment by kazurayam** [comment]
When I did
```
$ node dist/foo.test.js
```
I got
```
$ node dist/foo.test.js 
/Users/kazuakiurayama/github/PlaywrightGettingStarted/node_modules/@playwright/test/lib/test/testType.js:76
    if (!suite) throw (0, _util.errorWithLocation)(location, `test() can only be called in a test file`);
                ^

Error: dist/foo.test.js:43:17: test() can only be called in a test file
    at errorWithLocation (/Users/kazuakiurayama/github/PlaywrightGettingStarted/node_modules/@playwright/test/lib/test/util.js:220:10)
    at TestTypeImpl._createTest (/Users/kazuakiurayama/github/PlaywrightGettingStarted/node_modules/@playwright/test/lib/test/testType.js:76:51)
    at /Users/kazuakiurayama/github/PlaywrightGettingStarted/node_modules/@playwright/test/lib/test/transform.js:133:12
    at Object.<anonymous> (/Users/kazuakiurayama/github/PlaywrightGettingStarted/dist/foo.test.js:43:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

When I did:
```
$ npx playwright test
```
I got this:
```
Running 1 test using 1 worker

  ✓  tests/foo.test.ts:6:1 › basic test (3s)


  1 passed (3s)
```

**Comment by asdf23** [comment]
double check the directory spelling (I mean does a `pwd ` show the correct case. As well as the command you are typing if it contains a file name.
