### ISSUE TITLE
[BUG] Firefox - Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by nikolay-yankov** [microsoft/playwright#8375]
**Context:**
- Playwright Version: [1.10.0]
- Operating System: [Windows]
- Node.js version: [14.15.4]
- Browser: [Firefox]

**Code Snippet**

```javascript
const { firefox } = require("playwright-firefox");

const browser = await firefox.launch({
      headless: false,
      firefoxUserPrefs: {
        "layers.acceleration.disabled": true,
        "media.navigator.streams.fake": true,
        "dom.webnotifications.enabled": false,
      },
    });
const context = await browser.newContext({})
const page = await context.newPage();
await page.goto("mywebsite.com");
await page.$(`xpath=//div[contains(text(), "Some Text")]`)
```

**Describe the bug**

I get the following error occasionally:
```javascript
page.$: Execution context was destroyed, most likely because of a navigation.
```

It occurs when trying to execute:
```javascript
page.$(`xpath=//div[contains(text(), "Some Text")]`)
```

Stack trace:
```javascript
Error
    at Object.captureStackTrace (node_modules\playwright-firefox\lib\utils\stackTrace.js:48:19)
    at Connection.sendMessageToServer (node_modules\playwright-firefox\lib\client\connection.js:69:48)
    at Proxy.<anonymous> (node_modules\playwright-firefox\lib\client\channelOwner.js:64:61)
    at node_modules\playwright-firefox\lib\client\frame.js:192:42
    at Frame._wrapApiCall (node_modules\playwright-firefox\lib\client\channelOwner.js:77:34)
    at Frame.$ (node_modules\playwright-firefox\lib\client\frame.js:191:21)
    at node_modules\playwright-firefox\lib\client\page.js:238:60
    at Page._attributeToPage (node_modules\playwright-firefox\lib\client\page.js:231:20)
    at Page.$ (node_modules\playwright-firefox\lib\client\page.js:238:21)
```

Unfortunately, I cannot find a pattern when and why this happens exactly.

**Comment by JoelEinbinder** [comment]
Your page is navigating multiple times, and sometimes that races with `page.$`. Try using `page.waitForSelector` instead.

**Comment by nikolay-yankov** [comment]
@JoelEinbinder Thanks mate!
