### ISSUE TITLE
[Feature] connect() and connectOverCDP do not support https://

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#8593]
As a follow up to https://github.com/microsoft/playwright-java/issues/496

I think our usecase is similar to the person who filed that issue: we host a containerized version of chrome in an enterprise environment.

apache is configured with basic authentication as a reverse proxy in front of a CDP interface (specifically browserless.io)

In our infrastructure, we use playwright (or puppeteer) to drive a secure chrome instance for automated performance measurements from the browser. 

We can SSH tunnel to accomplish this from our local dev machines, but, like the original issue, don't have the capability to do that from our jenkins/CI user due to permission issues on the internal network.

I could help create the necessary docker-compose.yaml to help you implement this when this feature is prioritized.

**Comment by YusukeIwaki** [comment]
Please let me share that I already use connectOverCDP with Python client for connecting to `wss://` endpoint (browserless.io).
Is this Java-specific issue?

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.connect_over_cdp(
        'wss://chrome.browserless.io?token=YOUR_TOKEN')
    page = browser.new_page()
    page.goto('https://github.com/YusukeIwaki')
    page.pdf(path='YusukeIwaki.pdf')
    browser.close()
```

This code successfully generates PDF.

**Comment by unlikelyzero** [comment]
@YusukeIwaki that is a great distinction, thank you. Playwright throws an error:


`browserType.connectOverCDP: Protocol "https:" not supported. Expected "http:"`

When running the following:
```
const pw = require('playwright');

(async () => {

    const browser = await pw.chromium.connectOverCDP({
        endpointURL: 'https://url',
        headers: {
            'Authorization': 'Basic pass'
        }
    });

    const page = await browser.newPage();

    try {
        await page.goto('https://browserless.io', { waitUntil: 'networkidle' });
        await page.screenshot({ path: './browserless.png' });
        browser.close();
    } catch (error) {
        console.error({ error }, 'Something happened!');
        browser.close();
    }
})();

**Comment by YusukeIwaki** [comment]
@unlikelyzero It seems WebSocket doesn't accept https URL, and probably this issue is not Playwright-specific.
![image](https://user-images.githubusercontent.com/11763113/131762489-b3ba1568-d9ed-4e42-89a6-07ae76c238c2.png)

So why not specify URL with the scheme `wss://` instead of `https://` ?

**Comment by yury-s** [comment]
@unlikelyzero what is the URL you do you pass to `connect()` ? I just checked and 
```js
browserType.browserType.connect({
  wsEndpoint: `wss://localhost:8907/ws`
})
```
works just fine, can you confirm that it already works for you with `wss://` urls? Passing `https:` url to `connectOverCDP` needs a fix, I'll do that.

**Comment by unlikelyzero** [comment]
@yury-s I can confirm that wss:// works for me! https:// does not :(

**Comment by unlikelyzero** [comment]
@yury-s  I'm still seeing the same error with `.connectOverCDP()`, but not with `.connect()`

**Comment by yury-s** [comment]
Hmm, can you share your snippet and logs when you run it with `DEBUG=pw:browser` ?

**Comment by unlikelyzero** [comment]
@yury-s 

```
DEBUG=* node ./e2e/perf/perf.remote.spec.js

  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: '/Users/<hidden>/Library/Caches/ms-playwright/chromium-917400/chrome-mac/Chromium.app/Contents/MacOS/Chromium',
  pw:channel:event       name: 'chromium'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@18b516850167ae8f80f933fd069c3294'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: '/Users/<hidden>/Library/Caches/ms-playwright/firefox-1290/firefox/Nightly.app/Contents/MacOS/firefox',
  pw:channel:event       name: 'firefox'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@9aa6a895cebbc722ca0a533e9dfae488'
  pw:channel:event   }
  pw:channel:event } +3ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: '/Users/<hidden>/Library/Caches/ms-playwright/webkit-1540/pw_run.sh',
  pw:channel:event       name: 'webkit'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@a8abf67b08ab5df13a88b4a6e2c2b1f6'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Android',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'android@bbdb3c36d5754bb6540bfa552cb3fa16'
  pw:channel:event   }
  pw:channel:event } +1ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Electron',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'electron@f9efa656dcdeea8f076e20fbe7b5c1ef'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Selectors',
  pw:channel:event     initializer: {},
  pw:channel:event     guid: 'selectors@f3aea2f9951fc45897eefe27e7a34d82'
  pw:channel:event   }
  pw:channel:event } +0ms
  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Playwright',
  pw:channel:event     initializer: {
  pw:channel:event       chromium: [Object],
  pw:channel:event       firefox: [Object],
  pw:channel:event       webkit: [Object],
  pw:channel:event       android: [Object],
  pw:channel:event       electron: [Object],
  pw:channel:event       deviceDescriptors: [Array],
  pw:channel:event       selectors: [Object],
  pw:channel:event       preLaunchedBrowser: undefined
  pw:channel:event     },
  pw:channel:event     guid: 'Playwright'
  pw:channel:event   }
  pw:channel:event } +1ms
  pw:api => browserType.connectOverCDP started +0ms
  pw:channel:command {
  pw:channel:command   id: 1,
  pw:channel:command   guid: 'browser-type@18b516850167ae8f80f933fd069c3294',
  pw:channel:command   method: 'connectOverCDP',
  pw:channel:command   params: {
  pw:channel:command     endpointURL: 'https://<hidden>browserless',
  pw:channel:command     headers: [ [Object] ]
  pw:channel:command   }
  pw:channel:command } +0ms
  pw:channel:response {
  pw:channel:response   id: 1,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: 'Protocol "https:" not supported. Expected "http:"',
  pw:channel:response       stack: 'TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"\n' +
  pw:channel:response         '    at new ClientRequest (_http_client.js:152:11)\n' +
  pw:channel:response         '    at request (http.js:46:10)\n' +
  pw:channel:response         '    at Object.get (http.js:50:15)\n' +
  pw:channel:response         '    at json (/Users/<hidden>/github/<hidden>/node_modules/playwright/lib/server/chromium/chromium.js:198:19)\n' +
  pw:channel:response         '    at new Promise (<anonymous>)\n' +
  pw:channel:response         '    at urlToWSEndpoint (/Users/<hidden>/github/<hidden>/node_modules/playwright/lib/server/chromium/chromium.js:197:22)\n' +
  pw:channel:response         '    at controller.run._timeoutSettings.TimeoutSettings.timeout.timeout.timeout (/Users/<hidden>/github/<hidden>/node_modules/playwright/lib/server/chromium/chromium.js:75:91)\n' +
  pw:channel:response         '    at async ProgressController.run (/Users/<hidden>/github/<hidden>/node_modules/playwright/lib/server/progress.js:89:22)\n' +
  pw:channel:response         '    at async BrowserTypeDispatcher.connectOverCDP (/Users/<hidden>/github/<hidden>/node_modules/playwright/lib/dispatchers/browserTypeDispatcher.js:62:21)\n' +
  pw:channel:response         '    at async DispatcherConnection.dispatch (/Users/<hidden>/github/<hidden>/node_modules/playwright/lib/dispatchers/dispatcher.js:340:22)',
  pw:channel:response       name: 'TypeError'
  pw:channel:response     }
  pw:channel:response   },
  pw:channel:response   log: undefined
  pw:channel:response } +0ms
  pw:api <= browserType.connectOverCDP failed +6ms
(node:76981) UnhandledPromiseRejectionWarning: browserType.connectOverCDP: Protocol "https:" not supported. Expected "http:"
    at /Users/<hidden>/github/<hidden>/e2e/perf/perf.remote.spec.js:5:39
    at Object.<anonymous> (/Users/<hidden>/github/<hidden>/e2e/perf/perf.remote.spec.js:19:3)
(node:76981) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:76981) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yury-s** [comment]
I looks like you keep are not using `@next` version, look at the 
 code of `urlToWSEndpoint` function around `/Users/<hidden>/github/<hidden>/node_modules/playwright/lib/server/chromium/chromium.js:198`, it should be something like this:

```js
async function urlToWSEndpoint(endpointURL) {
  if (endpointURL.startsWith('ws')) return endpointURL;
  const httpURL = endpointURL.endsWith('/') ? `${endpointURL}json/version/` : `${endpointURL}/json/version/`;
  const request = endpointURL.startsWith('https') ? _https.default : _http.default;
...
```

**Comment by unlikelyzero** [comment]
@yury-s you're right, sorry about that; I switched and cleaned branches between attempts.

Now, I'm just dealing with ```browserType.connect: unable to verify the first certificate```
