### ISSUE TITLE
[Question] crashes in headless mode, but ok in non-headless mode

### ISSUE THREAD

**Issue by playgithub** [microsoft/playwright#8620]
An application that utilizes `playwright` to turn wifi on / off
It works when `headless=False`
Just modify `headless=False` to `headless=True`, it crashes

`wifi_switch.py`
```python
import asyncio
import time

from playwright.async_api import async_playwright


class wifi_switch():

    def __init__(self):
        self.__wifi_page = None
        self.__exit_flag = False

    async def init_browser(self):
        p = await async_playwright().start()
        self.__browser = await p.chromium.launch(headless=False)

    async def init_context(self):
        self.__context = await self.__browser.new_context()

    async def init_wifi_page(self):
        if (self.__wifi_page is None):
            self.__wifi_page = await self.__context.new_page()

        await self.__wifi_page.goto('http://192.168.1.1')

        await self.__wifi_page.fill('#userpassword', 'fake-password')
        await self.__wifi_page.click('#loginbtn')
        await self.__wifi_page.click('xpath=//*[@id="wifi"]/div[2]/div')

    async def get_wifi_switch_btn(self):
        wifi_switch_btn = await self.__wifi_page.wait_for_selector('xpath=/html/body/div[2]/div/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div/div',
                                                                   strict=True,
                                                                   timeout = 3000)
        return wifi_switch_btn

    # return on / off / invalid
    async def get_wifi_status(self):
        btn = await self.get_wifi_switch_btn()
        id = await btn.get_property('id')
        id = str(id)

        if (id == 'wifiOn2G_btnId'):
            return 'on'
        elif (id == 'wifiOff2G_btnId'):
            return 'off'
        else:
            return 'invalid'

    async def action(self, is_wifi_on: bool):
        if (is_wifi_on):
            print('Wifi Status: On\n(1) Turn Off (Default)\n(q) Quit')
            user_input = input("Please select: ")
            if (user_input == '' or user_input == '1'):
                await self.turn_off_wifi()
        else:
            print('Wifi Status: Off\n(1) Turn On (Default)\n(q) Quit')
            user_input = input("Please select: ")
            if (user_input == '' or user_input == '1'):
                await self.turn_on_wifi()

        if (user_input == 'q'):
            self.__exit_flag = True

    async def turn_on_wifi(self):
        status = await self.get_wifi_status()
        if (status == 'off'):
            await self.toggle_wifi_status()
            await self.__wifi_page.wait_for_selector('xpath=//*[@id="wifiOn2G_btnId"]')
        elif (status == 'on'):
            return
        else:
            raise Exception("invalid wifi status")

    async def turn_off_wifi(self):
        status = await self.get_wifi_status()
        if (status == 'on'):
            await self.toggle_wifi_status()
            await self.__wifi_page.wait_for_selector('xpath=//*[@id="wifiOff2G_btnId"]')
        elif (status == 'off'):
            return
        else:
            raise Exception("invalid wifi status")

    async def toggle_wifi_status(self):
        btn = await self.get_wifi_switch_btn()
        await btn.click()

    async def run(self):
        await self.init_browser()
        await self.init_context()
        await self.init_wifi_page()
        
        while True:

            wifi_status = await self.get_wifi_status()

            if (wifi_status == 'on'):
                await self.action(True)
            elif (wifi_status == 'off'):
                await self.action(False)
            else:
                await self.init_wifi_page()

            print('\n')

            if (self.__exit_flag):
                break

try:
    ws = wifi_switch()
    asyncio.run(ws.run())
except TimeoutError as e:
    print(e.strerror)
except Exception:
    print("unknown exception caught")
finally:
    pass
```

**Comment by yury-s** [comment]
What is the error that you get?

**Comment by playgithub** [comment]
```shell
Traceback (most recent call last):
  File "/home/user/tool/wifi_switch/source/wifi_switch.py", line 110, in <module>
    asyncio.run(ws.run())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/user/tool/wifi_switch/source/wifi_switch.py", line 97, in run
    await self.action(True)
  File "/home/user/tool/wifi_switch/source/wifi_switch.py", line 54, in action
    await self.turn_off_wifi()
  File "/home/user/tool/wifi_switch/source/wifi_switch.py", line 77, in turn_off_wifi
    await self.toggle_wifi_status()
  File "/home/user/tool/wifi_switch/source/wifi_switch.py", line 86, in toggle_wifi_status
    await btn.click()
  File "/home/user/.local/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 1611, in click
    await self._async(
  File "/home/user/.local/lib/python3.9/site-packages/playwright/_impl/_element_handle.py", line 124, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/home/user/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/home/user/.local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (525,305.48)
  <div data-ember-action="6" class="want_devicecontrol"></div> from <div class="clearboth">…</div> subtree intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (525,305.48)
  <div data-ember-action="6" class="want_devicecontrol"></div> from <div class="clearboth">…</div> subtree intercepts pointer events
retrying click action, attempt #2
  waiting 20ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (525,305.48)
  <div data-ember-action="6" class="want_devicecontrol"></div> from <div class="clearboth">…</div> subtree intercepts pointer events
retrying click action, attempt #3
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (525,13.48)
  <div data-ember-action="6" class="want_devicecontrol"></div> from <div class="clearboth">…</div> subtree intercepts pointer events
(many retries)
```

**Comment by yury-s** [comment]
From the log it is clear that this `<div data-ember-action="6"...` prevents you from clicking the wifi switch button, looks like there is a race that occurs more often in headless. You can take a screenshot of the page when it times out and see what's going on. Also to make it less racy you can do 
```py
await self.__wifi_page.click('xpath=/html/body/div[2]/div/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div/div',
                                                                   strict=True,
                                                                   timeout = 3000)
```

Instead of wait_for_selector and click.

**Comment by playgithub** [comment]
> From the log it is clear that this `<div data-ember-action="6"...` prevents you from clicking the wifi switch button, looks like there is a race that occurs more often in headless. You can take a screenshot of the page when it times out and see what's going on. Also to make it less racy you can do
> 
> ```python
> await self.__wifi_page.click('xpath=/html/body/div[2]/div/div/div/div/div[2]/div/div/div/div/div[1]/div[2]/div/div',
>                                                                    strict=True,
>                                                                    timeout = 3000)
> ```
> 
> Instead of wait_for_selector and click.

`Page.wait_for_selector` is buggy, isn't it?
For I've to get wifi status from the button, I have to wait until it available.

**Comment by playgithub** [comment]
@yury-s so it seems like a bug, doesn't it?
