### ISSUE TITLE
[BUG] Whole Browser Context shouldn't be closed for error on single page.

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#8655]
Playwright:        "^1.14.1",
Browser: Firefox | Chromium | Edge

My whole browser contexts gets killed when single page encouters some error due to weird proxy errors. I don't think if single page has error whole browser context should be closed.

```
  pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +984ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +3ms
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +191ms
  pw:api   navigated to "about:blank" +325ms
  pw:api <= browserContext.newPage succeeded +2ms
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +137ms
  pw:api   navigated to "about:blank" +26ms
  pw:api <= browserContext.newPage succeeded +1ms
[REQ] 1 of 17576 : https://jsonip.com
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +113ms
  pw:api   navigated to "about:blank" +11ms
  pw:api <= browserContext.newPage succeeded +1ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://jsonip.com/", waiting until "load" +0ms
  pw:api <= page.goto failed +4s
  pw:api => browserContext.newPage started +506ms
  pw:api <= browserContext.newPage failed +1ms
```

Whats happening here is I open page the page fails now whole contexts gets removed and i can't call context.newPage on existing context. If I do it it throws this error:
```
browserContext.newPage: Target page, context or browser has been closed
    at newPage (file:///C:/Users/quantum/Desktop/projects/mike/tm-did/dist/scrapper_utils/browser.js:83:30)
    at do_it (file:///C:/Users/quantum/Desktop/projects/mike/tm-did/dist/main.js:48:20) {
  name: 'Error'
 ```
 
 The code is normal looking context.newPage so I am not posting here.

**Comment by shirshak55** [comment]
```

const browser = await playwright[browserType].launch(proxy: {
                    server: `http://${pxyy.url}:${pxyy.port}`,
                    username: pxyy.username,
                    password: pxyy.password,
                },);
const context = await browser.newContext(proxy: {
                    server: `http://${pxyy.url}:${pxyy.port}`,
                    username: pxyy.username,
                    password: pxyy.password,
                },);
const page = await context.newPage();
await page.goto('http://whatsmyuseragent.org/').catch(e=>undefined); // This fails 
await context.newPage() // now i can't do this because context is closed idk why
```

By the way this happens only on firefox. Chromium/edge don't show this error.

**Comment by yury-s** [comment]
> when single page encouters some error due to weird proxy errors.

Can you paste the error log here? Also run it with `DEBUG=pw:browser`

**Comment by shirshak55** [comment]
@yury-s I already pasted. Pasting it here again

```
 pw:api => browserType.launch started +0ms
  pw:api <= browserType.launch succeeded +984ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +3ms
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +191ms
  pw:api   navigated to "about:blank" +325ms
  pw:api <= browserContext.newPage succeeded +2ms
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +137ms
  pw:api   navigated to "about:blank" +26ms
  pw:api <= browserContext.newPage succeeded +1ms
[REQ] 1 of 17576 : https://jsonip.com
  pw:api => browserContext.newPage started +1ms
  pw:api   navigated to "about:blank" +113ms
  pw:api   navigated to "about:blank" +11ms
  pw:api <= browserContext.newPage succeeded +1ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://jsonip.com/", waiting until "load" +0ms
  pw:api <= page.goto failed +4s
  pw:api => browserContext.newPage started +506ms
  pw:api <= browserContext.newPage failed +1ms
  ```

**Comment by shirshak55** [comment]
basically once we see failed on page.goto

  pw:api <= page.goto failed +4s
  
  the windows gets closed 
  
  And calling newPage on browserContext fails.

**Comment by shirshak55** [comment]
https://user-images.githubusercontent.com/8097377/131877963-9e1923a2-9d21-4e4f-86b7-c7721cd26135.mp4

**Comment by shirshak55** [comment]
@yury-s anything else required. let me know otherwise I go to sleep. Thanks.

**Comment by yury-s** [comment]
> @yury-s I already pasted. Pasting it here again
> 
This is `DEBUG=pw:api` whereas we need `DEBUG=pw:browser` which will hopefully contain some helpful output from the browser.

**Comment by shirshak55** [comment]
@yury-s Thanks 

Here is the debug info


```
➜ tm-did git:(main) yarn start
yarn run v1.22.5
$ node dist/main
  pw:browser <launching> C:\Users\quantum\AppData\Local\ms-playwright\firefox-1281\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\quantum\AppData\Local\Temp\playwright_firefoxdev_profile-yrM6Zt -juggler-pipe -silent +0ms
  pw:browser <launched> pid=6892 +3ms
  pw:browser [pid=6892][out]  +239ms
  pw:browser [pid=6892][out] Juggler listening to the pipe +0ms
  pw:browser [pid=6892][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\quantum\\AppData\\Local\\Temp\\playwright_firefoxdev_profile-yrM6Zt\\search.json.mozlz4", (void 0))) +32ms
  pw:browser [pid=6892][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. +567ms
  pw:browser [pid=6892][out] console.error: Region.jsm: "Error fetching region" (new Error("TIMEOUT", "resource://gre/modules/Region.jsm", 772)) +4s
  pw:browser [pid=6892][out] console.error: Region.jsm: "Failed to fetch region" (new Error("TIMEOUT", "resource://gre/modules/Region.jsm", 419)) +0ms
  pw:browser [pid=6892][err] Exiting due to channel error. +838ms
  pw:browser [pid=6892] <process did exit: exitCode=3221225477, signal=null> +21ms
  pw:browser [pid=6892] starting temporary directories cleanup +0ms
browserContext.newPage: Target page, context or browser has been closed
    at main1 (file:///C:/Users/quantum/Desktop/projects/mike/tm-did/dist/main.js:131:19) {
  name: 'Error'
}
  pw:browser [pid=6892] finished temporary directories cleanup +15ms
  ```

**Comment by yury-s** [comment]
`JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory` looks suspicious, looks like it fails to load the profile and exits because of that. It's hard to tell why though. Doe it also happen in headless mode? Also does navigation other sites trigger same issue?

**Comment by shirshak55** [comment]
@yury-s yes it happens on headless too. It happens with other website too.

**Comment by aslushnikov** [comment]
@shirshak55 would you mind sharing your code with me?

**Comment by shirshak55** [comment]
@aslushnikov 

I simply opened browser using browser.launch and context.newPage() and manually went to gmail to login. Obviously i am not going to write more if its not going to work.


https://user-images.githubusercontent.com/8097377/132517293-ff65f5da-e072-417e-aeef-78927c586a69.mp4

**Comment by shirshak55** [comment]
@aslushnikov its a simple code not very hard to reproduce so I am leaving my code here.

```
import { firefox } from "playwright"
import { readProxy, shouldEnableProxy } from "./proxies.js"

async function main() {
    let launchArgs = {
        headless: false,
        proxy: {
            server: "per-context",
        },
    }
    let browser = await firefox.launch(launchArgs)

    let pxy = readProxy()
    let pxyy = pxy[0 % pxy?.length]

    let context = await browser.newContext({
        proxy: {
            server: `http://${pxyy.url}:${pxyy.port}`,
            username: pxyy.username,
            password: pxyy.password,
        },
    })

    let page = await context.newPage()
    await page.goto("https://www.mangadex.com").catch((e) => undefined)
    await context.newPage()
    console.log("HELLO")
}

main()

```

https://user-images.githubusercontent.com/8097377/132611309-18d85d17-d1ab-4a9d-acb4-e072a64c4de6.mp4


I don't think context should be closed just because 1-2 page has some issue with proxies or something which is what this issue is about.

**Comment by aslushnikov** [comment]
@shirshak55 I didn't find your e-mail; would you mind sending one more time? Also, I'd need the `proxies.js` file so that I can actually run your snippet locally

**Comment by shirshak55** [comment]
@aslushnikov Hey I have sent it again check it out.

May be its in your spam. I have sent it using shirshak55 at protonmail.com

**Comment by aslushnikov** [comment]
@shirshak55 sorry, I dropped the ball on this one, and outlook removed the file. 

However, we fixed a very similar bug a few days ago in Firefox. Could you please check if this is still an issue when using playwright@next?

I'll close this bug for now. I'll appreciate if you refile if things still don't work!
