### ISSUE TITLE
[BUG] webkit does not isolate (session) cookies when newContext is invoked

### ISSUE THREAD

**Issue by aesyondu** [microsoft/playwright#868]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Mac OS X - 10.14.6
- Extra: node@11.15.0

**Code Snippet**

```javascript
const path = require("path");
const fs = require("fs");
const playwright = require("playwright");
const { devices: descriptors } = playwright;

// edit as necessary to test specific browser
const browserTypes = [
  // "firefox",
  "chromium",
  // "webkit",
];
const macBook = {
  name: "Apple MacBook Pro 13-inch (Retina display)",
  alias: "lg",
  viewport: {
    width: 2560 / 2,
    height: 1600 / 2,
    deviceScaleFactor: 2,
    isMobile: false,
  }
};
const devices = [
  // { alias: "sm", ...descriptors["iPhone X"] },
  { alias: "md", ...descriptors["iPad Pro 11"] },
  // macBook,
];

const screenshotPath = path.join(
  __dirname,
  ".tmp",
  `${path.basename(__filename).split(".")[0]}`,
);

const baseUrl = "http://localhost:3000";

(async () => {
  await fs.promises.mkdir(screenshotPath, { recursive: true })

  for (browserType of browserTypes) {
    const browser = await playwright[browserType].launch({ headless: false })

    for (device of devices) {
      const context = await browser.newContext({ ...device })
      try {
        const page = await context.newPage(baseUrl)

        await page.waitForLoadState()
        await Promise.all([
          page.waitForNavigation(),
          new Promise(async (resolve, reject) => {
            try {
              if (device.viewport.isMobile) {
                await page.click('.burger')
                await page.click('"Login"')
              } else {
                await page.click('"Login"')
              }

              resolve()
            } catch (e) {
              reject(e)
            }
          })
        ])

        await page.fill("#user_username", "myusername")
        await page.fill("#user_password", "mypassword")
        await Promise.all([
          page.waitForNavigation(),
          page.click('input[value="Log in"]'),
        ])

        if (page.coverage) {
          await Promise.all([
            page.coverage.startJSCoverage(),
            page.coverage.startCSSCoverage(),
            page.goto(baseUrl + "/change-password")
          ])
          const [jsCoverage, cssCoverage] = await Promise.all([
            page.coverage.stopJSCoverage(),
            page.coverage.stopCSSCoverage(),
          ])
        } else {
          await page.goto(baseUrl + "/change-password")
        }
        await page.screenshot({
          path: path.join(screenshotPath, `${browserType}-${device.alias}-default.png`),
          fullPage: true,
        })

        console.log(`Ok: Device ${device.name}, Browser ${browserType}`)
      } catch (e) {
        console.log(`Err: Device ${device.name}, Browser ${browserType}`)
        console.error(e)
      }
    }

    await browser.close()
  } 
})();
```

**Describe the bug**

Cookies (session) for **webkit** is retained even when newContext is invoked. **'firefox'** and **'chromium'** are fine. Backend is `rails`, authentication managed by `devise` gem.

**Comment by aesyondu** [comment]
First run (webkit only): everything works.
```shell
Ok: Device iPhone X, Browser webkit
Ok: Device iPad Pro 11, Browser webkit
Ok: Device Apple MacBook Pro 13-inch (Retina display), Browser webkit
```
Second run (webkit only): first failure appears, however, the failure also cleared the cookies for the subsequent runs
```shell
Err: Device iPhone X, Browser webkit
{ TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/Users/aes/projects/amber/node_modules/playwright-core/lib/frames.js:898:25)
    at runNextTicks (internal/process/task_queues.js:52:5)
    at listOnTimeout (internal/timers.js:505:9)
    at processTimers (internal/timers.js:479:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/aes/projects/amber/node_modules/playwright-core/lib/helper.js:54:23)
    at Page.waitForNavigation (/Users/aes/projects/amber/node_modules/playwright-core/lib/page.js:223:33)
    at Page.<anonymous> (/Users/aes/projects/amber/node_modules/playwright-core/lib/helper.js:55:31)
    at /Users/aes/projects/amber/test/e2e/expired-password.spec.js:48:16
    at processTicksAndRejections (internal/process/task_queues.js:86:5) name: 'TimeoutError' }
Ok: Device iPad Pro 11, Browser webkit
Ok: Device Apple MacBook Pro 13-inch (Retina display), Browser webkit
```
Third run: Err, ok, ok pattern repeats itself
```shell
{ TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/Users/aes/projects/amber/node_modules/playwright-core/lib/frames.js:898:25)
  -- ASYNC --
    at Frame.<anonymous> (/Users/aes/projects/amber/node_modules/playwright-core/lib/helper.js:54:23)
    at Page.waitForNavigation (/Users/aes/projects/amber/node_modules/playwright-core/lib/page.js:223:33)
    at Page.<anonymous> (/Users/aes/projects/amber/node_modules/playwright-core/lib/helper.js:55:31)
    at /Users/aes/projects/amber/test/e2e/expired-password.spec.js:48:16
    at processTicksAndRejections (internal/process/task_queues.js:86:5) name: 'TimeoutError' }
Ok: Device iPad Pro 11, Browser webkit
Ok: Device Apple MacBook Pro 13-inch (Retina display), Browser webkit
```

When I add clearCookies() everything works fine.
```javascript
    // ...
    for (device of devices) {
      const context = await browser.newContext({ ...device })
      await context.clearCookies()

      try {
      // ...
```

**Comment by aesyondu** [comment]
When I comment out the iPhone X device/context/viewport, the problem moves over to the iPad device. Visually verified via `headless: false`
```shell
Err: Device iPad Pro 11, Browser webkit
{ TimeoutError: Navigation timeout of 30000 ms exceeded
    at Promise.then (/Users/aes/projects/amber/node_modules/playwright-core/lib/frames.js:898:25)
  -- ASYNC --
    at Frame.<anonymous> (/Users/aes/projects/amber/node_modules/playwright-core/lib/helper.js:54:23)
    at Page.waitForNavigation (/Users/aes/projects/amber/node_modules/playwright-core/lib/page.js:223:33)
    at Page.<anonymous> (/Users/aes/projects/amber/node_modules/playwright-core/lib/helper.js:55:31)
    at /Users/aes/projects/amber/test/e2e/expired-password.spec.js:48:16
    at processTicksAndRejections (internal/process/task_queues.js:86:5) name: 'TimeoutError' }
Ok: Device Apple MacBook Pro 13-inch (Retina display), Browser webkit
```

**Comment by pavelfeldman** [comment]
Thanks for your report. I added a bunch of cookies isolation tests in https://github.com/microsoft/playwright/commit/5152540f47c6f4ba1375e0586a17abc11722211d. While I could not repro your particular use case, I could repro concurrent access to persistent cookies leaking and I'm looking into it. I _think_ it has the same nature as the bug you are observing.
