### ISSUE TITLE
[BUG] does not work with electron sample

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#8727]
**Context:**
- Playwright Version: `1.14.1`
- Operating System: macOS ARM
- Node.js version: `v16`
- Browser: Electron
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript

(async () => {
    const { _electron } = require('playwright');
    
    // Launch Electron app.
    const electronApp = await _electron.launch({ args: ['main.js'] });

    // Evaluation expression in the Electron context.
    const appPath = await electronApp.evaluate(async ({ app }) => {
        // This runs in the main Electron process, parameter here is always
        // the result of the require('electron') in the main app script.
        return app.getAppPath();
    });
    console.log(appPath);

    // Get the first window that the app opens, wait if necessary.
    const window = await electronApp.firstWindow();
    // Print the title.
    console.log(await window.title());
    // Capture a screenshot.
    await window.screenshot({ path: 'intro.png' });
    // Direct Electron console to Node terminal.
    window.on('console', console.log);
    // Click button.
    await window.click('text=Click me');
    // Exit app.
    await electronApp.close();
})();
```

**Describe the bug**

Output:

```
~/Desktop/playwright> node index.js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

electron.launch: Cannot find module 'electron/index.js'
Require stack:
- /Users/bpasero/Desktop/playwright/node_modules/playwright/lib/server/electron/electron.js
- /Users/bpasero/Desktop/playwright/node_modules/playwright/lib/server/playwright.js
- /Users/bpasero/Desktop/playwright/node_modules/playwright/lib/inprocess.js
- /Users/bpasero/Desktop/playwright/node_modules/playwright/index.js
- /Users/bpasero/Desktop/playwright/index.js
    at /Users/bpasero/Desktop/playwright/index.js:5:41
    at Object.<anonymous> (/Users/bpasero/Desktop/playwright/index.js:27:3)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  name: 'Error'
}
```

**Comment by mxschmitt** [comment]
The electron NPM package needs to be installed manually when using Electron via `npm install electron`, does this work for you?

**Comment by bpasero** [comment]
@mxschmitt if we were to use `playwright` to test VSCode (desktop - we use it for web already), we would somehow need to be able to use the Electron version we bundle within VSCode itself and not the standard GH one. Is that possible?

**Comment by pavelfeldman** [comment]
👋 @bpasero: I would try passing https://playwright.dev/docs/api/class-electron#electron-launch-option-executable-path, it might just work!

**Comment by LucasSantosSilva** [comment]
I used the same example, when execute `npx playwright test` return no tests found. What I need do?

**Comment by bpasero** [comment]
> But yeah we should add it maybe to the docs since the error is not self explaining.

Please do, I hit this again and forgot about this.
