### ISSUE TITLE
Getting ERR_CONNECTION_RESET when test run with headless:true in centos 

### ISSUE THREAD

**Issue by Tejareddy1** [microsoft/playwright#8746]
As we cant run headful mode in centos, I am trying to run the tests in headless mode. I am getting this exception while running.
I tried below options while context creation:

await this.playwrightbrowser.newContext({ recordVideo: { dir: 'reports\\videos' },userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36', viewport: null});

Please help me if any other options I should set
page.goto: net::ERR_CONNECTION_RESET at http://224.225.224.224:9191/
       =========================== logs ===========================
       navigating to "http://224.225.224.224:9191/", waiting until "load"
       ============================================================
       Note: use DEBUG=pw:api environment variable to capture Playwright logs.
       Error: 
           at Object.captureStackTrace (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/utils/stackTrace.js:50:19)
           at Connection.sendMessageToServer (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/connection.js:65:48)
           at Proxy.<anonymous> (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/channelOwner.js:64:61)
           at /dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/frame.js:102:65
           at Frame._wrapApiCall (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/channelOwner.js:77:34)
           at Frame.goto (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/frame.js:100:21)
           at /dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/page.js:303:60
           at Page._attributeToPage (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/page.js:238:20)
           at Page.goto (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/node_modules/playwright/lib/client/page.js:303:21)
           at PegaSUT.<anonymous> (/dsk01/apps/playwrightrepo/playwright/playwright-base-ui-framework/src/base/PegaSUT.ts:106:40)

**Comment by pavelfeldman** [comment]
Looks like browser can't establish the connection. CentOS is not among the supported platforms, so we don't have a test coverage for that platform. So we can't event tell if this is a problem with your network environment or with Playwright. I'll close this issue to set the expectations of core team not working on fixing this. But others will come here and if they share this issue they can post comments and help each other.

**Comment by Tejareddy1** [comment]
@pavelfeldman , the Same issue occuring in Ubuntu VM 18.0.4. I have tried to launch the browser in ubuntu VM and also tried to launch the browser with docker container(which is also a ubuntu container).

Tried to launch ubuntu container in cent OS machine as well and getting the same issue.

Tried to launch ubuntu container from **MAC OS, worked fine without any issue**

**Comment by Wilhop** [comment]
@Tejareddy1 did you manage to solve your problem eventually? I have my own issue in Azure Pipelines where I get the same kind of error: https://github.com/microsoft/playwright/issues/16749
