### ISSUE TITLE
[BUG] Typescript Playwright file can't get read in @playwright/test npm module.

### ISSUE THREAD

**Issue by andrewgremlich** [microsoft/playwright#8757]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Linux
- Node.js version: 14.17.5
- Browser: Chromium

```
## System:
 - OS: Linux 5.10 Manjaro Linux
 - Memory: 2.06 GB / 15.62 GB
 - Container: Yes
## Binaries:
 - Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.5/bin/yarn
 - npm: 7.20.6 - ~/.nvm/versions/node/v14.17.5/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.14.1 => 1.14.1 
```

```typescript
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  use: {
    headless: false,
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
    video: "on-first-retry",
    baseURL: "http://localhost:3000/",
  },
};

export default config;

```

**Describe the bug**

A simple playwright typescript config file in the root of my project can't get read.

I've tried multiple things, and it doesn't change.

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION] [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/andrewg/Documents/work_projects/native-playwright-testing/playwright.config.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)
    at Loader._requireOrImport (/home/andrewg/Documents/work_projects/native-playwright-testing/node_modules/@playwright/test/lib/test/loader.js:214:52)
    at Loader.loadConfigFile (/home/andrewg/Documents/work_projects/native-playwright-testing/node_modules/@playwright/test/lib/test/loader.js:67:18)
    at loadConfig (/home/andrewg/Documents/work_projects/native-playwright-testing/node_modules/@playwright/test/lib/test/cli.js:123:28)
    at loadConfigFromDirectory (/home/andrewg/Documents/work_projects/native-playwright-testing/node_modules/@playwright/test/lib/test/cli.js:135:11)
    at runTests (/home/andrewg/Documents/work_projects/native-playwright-testing/node_modules/@playwright/test/lib/test/cli.js:155:16)
    at Command.<anonymous> (/home/andrewg/Documents/work_projects/native-playwright-testing/node_modules/@playwright/test/lib/test/cli.js:79:7) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```
It seems like the `loader.js` file as an `eval` function for a dynamic import, but that isn't reading the TS file.

My `package.json` file looks like this...

```json
{
  "dependencies": {
    "@playwright/test": "^1.14.1",
    "dotenv": "^10.0.0",
    "fs-extra": "^10.0.0",
    "node-fetch": "^3.0.0",
    "playwright": "^1.14.1"
  },
  "devDependencies": {
    "@types/fs-extra": "^9.0.12",
    "@types/node-fetch": "^3.0.3",
    "@typescript-eslint/eslint-plugin": "^4.30.0",
    "@typescript-eslint/parser": "^4.30.0",
    "eslint": "^7.32.0",
    "typescript": "^4.4.2"
  },
  "scripts": {
    "test": "npx playwright test",
    "debug": "PWDEBUG=1 npx playwright test"
  }
}
```

My `tsconfig.json` is the default generated from running `npx tsc --init`

**Comment by pavelfeldman** [comment]
Try with a fresh folder, call

```
npm init -y
npm i @playwright/test
```

And put your config there, see if it works.

**Comment by andrewgremlich** [comment]
@pavelfeldman , that did work. I did some exploring and here is what I found. I was trying out to get auth state from another script that uses the `playwright` library. That script would be imported into the configuration. The script that was using playwright seemed to cause that error.

**Comment by pavelfeldman** [comment]
Ok, please file it if you think this is a bug on our side!
