### ISSUE TITLE
[BUG] Java, null pointer exception on first navigate call when using connectOverCDP()

### ISSUE THREAD

**Issue by gigitalz** [microsoft/playwright#8868]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Winsows 10
- Browser: Chrome 93
- Extra: Started chrome from custom link like this "C:\Program Files\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\chrome_instance" --restore-last-session --remote-debugging-port=9999

**Code Snippet**
```
    // This is kotlin code, but you can turn it into Java rather easily
    private var page: Page? = null
    private fun initBrowser() {
        val playwright = Playwright.create()
        val context = playwright.chromium().connectOverCDP("http://127.0.0.1:9999").contexts().first()
        context.onClose {
            page = null
        }
        context.setDefaultNavigationTimeout(10000.0)
        page = context.pages().first()
        page!!.setViewportSize(1014, 1039)
    }

// then somewhere else simply nagivate to any url
page!!.navigate("any url")
```

**Describe the bug**

I open a browser instance from command line with the parameters specified above, then i take control of the page by connecting to it.
I get a null pointer exception upon first navigation, but the page is successfully navigated with no issues, except for the exception trace. It seems to be an issue in your code. Subsequent nagivations work well without exceptions so it could be something related to the first call to navigate().
```
Exception of type class java.lang.NullPointerException
java.lang.NullPointerException: null
        at com.microsoft.playwright.impl.PageImpl.handleEvent(PageImpl.java:183)
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:258)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:212)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:109)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
        at com.microsoft.playwright.impl.FrameImpl.navigateImpl(FrameImpl.java:395)
        at com.microsoft.playwright.impl.PageImpl.lambda$navigate$32(PageImpl.java:791)
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
        at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
        at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:790)
        at com.microsoft.playwright.impl.PageImpl.navigate(PageImpl.java:41)
        at com.microsoft.playwright.Page.navigate(Page.java:3145)
```

**Comment by yury-s** [comment]
What is the page loaded in the browser when you connect to it?

**Comment by yury-s** [comment]
I can reproduce it. We receive `frameDetached` message without a frame: `{"guid":"page@97df346e01965af155be6155ab4bff56","method":"frameDetached","params":{}}`, it's clearly a bug.

**Comment by gigitalz** [comment]
> What is the page loaded in the browser when you connect to it?

Not sure I understood the question, do you want to know which page that is?

**Comment by yury-s** [comment]
> Not sure I understood the question, do you want to know which page that is?

Yes, I wanted to know what was in the page when you connected to it. Nevermind, I figured it out, it just has to be a page with iframes.
