### ISSUE TITLE
[BUG] Error: page.goto: Navigation failed because page crashed!

### ISSUE THREAD

**Issue by web-padawan** [microsoft/playwright#8873]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Mac OS 11.5.2, Linux (GitHub Actions)
- Node.js version: v12.22, v14
- Browser: WebKit

**Steps to reproduce**

1. `git clone https://github.com/vaadin/web-components`
2. `yarn`
3. `yarn test:webkit --group vaadin-combo-box`

Try the above command several times, it doesn't fail consistently.
At the time of writing it failed 3 times in a row and passed once.

**Describe the bug**

At first glance the issue seems to be specific to one test suite (packages/vaadin-combo-box/test/lazy-loading.test.js).

Seems that if we remove all other test files, it never crashes, so could be a memory thing.
But I don't have a clear understanding how to debug this and pinpoint the problem.

```
 ❌ Error: page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "about:blank", waiting until "load"
============================================================
    page.goto: Navigation failed because page crashed!
    =========================== logs ===========================
    navigating to "about:blank", waiting until "load"
    ============================================================
        at PlaywrightLauncherPage.stopSession (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncherPage.js:33:35)
        at PlaywrightLauncher.stopSession (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:89:35)
        at TestScheduler.stopSession (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:135:92)
        at EventEmitter.<anonymous> (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:26:28)
        at EventEmitter.emit (events.js:326:22)
        at EventEmitter.emit (domain.js:483:12)
        at TestSessionManager.emit (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-core/dist/utils/EventEmitter.js:16:24)
        at TestSessionManager.updateStatus (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-core/dist/test-session/TestSessionManager.js:32:14)
        at TestRunnerApiPlugin._setSessionFailed (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-core/dist/server/plugins/api/testRunnerApiPlugin.js:206:23)
        at TestRunnerApiPlugin._waitForDisconnect (/Users/serhii/vaadin/web-components/node_modules/@web/test-runner-core/dist/server/plugins/api/testRunnerApiPlugin.js:197:18)
```

**Comment by web-padawan** [comment]
Note, I have tried `1.15.0-next-alpha-sep-13-2021` and it seems to help (tests pass with this version).

**Comment by dgozman** [comment]
Thanks for the report! It does look like there is a real bug here, but it is very hard to understand what's going on. We often spend days on these kinds of bugs that involve digging into large codebases. Do you have a smaller repro script that shows the issue?

**Comment by dgozman** [comment]
Closing because we cannot repro. Feel free to open a new issue with a smaller repro script.
