### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: TypeError: browser.newPage is not a function

### ISSUE THREAD

**Issue by arturi** [microsoft/playwright#890]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Mac
- Node: 10.15.0

**Code Snippet**
```javascript
const { chromium, firefox, webkit } = require('playwright');

(async () => {
  const browser = await chromium.launch();  // Or 'firefox' or 'webkit'.
  const page = await browser.newPage('http://example.com');
  // other actions...
  await browser.close();
})();

```

**Describe the bug**

```
~/Desktop/playwright 59s
❯ node test.js
(node:38001) UnhandledPromiseRejectionWarning: TypeError: browser.newPage is not a function
    at /Users/artur/Desktop/playwright/test.js:5:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:38001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38001) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks for the awesome project! Very excited about this. Stumbling into this issue after `npm install playwright` and trying a simple test script from the readme examples.

**Comment by mmarkelov** [comment]
@arturi I suppose this is because this https://github.com/microsoft/playwright/pull/840
Cause it isn't released yet, you should use context:
```js
const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium', 'firefox', 'webkit']) {
    const browser = await playwright[browserType].launch();
    const context = await browser.newContext();
    const page = await context.newPage('http://example.com');
    await page.screenshot({ path: `example-${browserType}.png` });
    await browser.close();
  }
})();
```

**Comment by arturi** [comment]
@mmarkelov thank you! ❤️ works like a charm ✨

**Comment by arturi** [comment]
Side note: couldn’t get other examples, like the geo screenshot, to work — complains there’s no text “your location” to click.

**Comment by sframpton** [comment]
Looks like the example in the `README.md` around setting up screenshots is *also* missing the context line from  @mmarkelov 's example. It's caught one of my colleagues out this morning as we've been investigating Playwright

**Comment by arturi** [comment]
@sframpton I did add context though, so it’s probably something else.

**Comment by mmarkelov** [comment]
@arturi try like this:
```js
const { chromium, devices } = require('playwright');
const pixel2 = devices['Pixel 2'];

(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext({
        viewport: pixel2.viewport,
        userAgent: pixel2.userAgent,
        geolocation: { longitude: 12.492507, latitude: 41.889938 },
        permissions: { 'https://www.google.com': ['geolocation'] }
    });

    const page = await context.newPage('https://maps.google.com');
    await page.click('text="Где я?"');
    await page.waitForRequest(/.*pwa\/net.js.*/);
    await page.screenshot({ path: 'colosseum-android.png' });
    await browser.close();
})();
```

I advice you to try examples from [npm readme](https://www.npmjs.com/package/playwright)

**Comment by pavelfeldman** [comment]
We will be bringing back `browser.newPage` in 0.11, but for now please use `newContext` as suggested in the docs and above.
