### ISSUE TITLE
[Question]  Is it possible to import function from js into playwright .mjs config ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#8995]
I have tried several ways to import js files into the playwright config file but so far nothing works for me due to incompatibility between module and commonjs 

so is there a way around to overcome this issue?

```
// @ts-check
// /** @type {import('@playwright/test').PlaywrightTestConfig} */

import configList from "./configlist.js"


const project = function () {
    if (configList.crossBrowser == 'chrome' || configList.crossBrowser == 'false' || configList.crossBrowser == null) {
        return [{ name: 'Desktop Chromium', use: { browserName: 'chromium' } }]
    }  else {
        throw new Error("No valid parameter has been set for crossBrowser!");
    }
}

const config = {

    workers: configList.workers,
    use: {
        headless: configList.headless,
        viewport: configList.viewport,
        baseURL: configList.baseURL
    },
    projects: project(),
    testDir: configList.testDir,
    reporter: configList.reporter,
};
```

```
const configs = {
    workers: 1,
    headless: 'true',
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    baseURL: 'ww',
    crossBrowser:'true' ,
    testDir: 'src/tests',
    reporter: 'list',
    timeout: 20000,
    retries: 0,
};
export default configs
```

json file type set as module
  "type": "module",

currently, I'm getting the following error

```
ReferenceError: module is not defined in ES module scope
    at file:///home/s/Desktop/s/playwright.config.mjs:37:1
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at Loader.import (internal/modules/esm/loader.js:178:24)
```

**Comment by dgozman** [comment]
cc @JoelEinbinder

**Comment by Amrkamel1** [comment]
Only one way i have used as work around is to change playwright config from .js to .cjs and the other js file to .cjs as well.

Set type:"module" in package json 

And change tests spec file from js to mjs.


But even this solution will put some limitations to import some data from json file for e.g

**Comment by Amrkamel1** [comment]
@dgozman 

solved by setting type: "module"
and use export default config instead of module.export
