### ISSUE TITLE
[BUG] importing 'node-fetch' crashes playwright

### ISSUE THREAD

**Issue by alvipeo** [microsoft/playwright#9016]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows 10 x64
- Node.js version: 14.17.6
- Browser: doesn't matter
- Extra: node-fetch 3.0.0

**Code Snippet**

I need to run an HTTP request, so I thought I'd use `node-fetch`. But when I just import it:

```javascript
import fetch from "node-fetch";
```

**Describe the bug**

That single line crashes the test run. So when I do `npx playwright test` I get the following:

>Using config at <project>\playwright.config.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION] [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for <project>\e2e\src\mytest.spec.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)
    at Loader._requireOrImport (<project>\node_modules\@playwright\test\lib\test\loader.js:214:52)
    at Loader.loadTestFile (<project>\node_modules\@playwright\test\lib\test\loader.js:130:7)
    at Runner._run (<project>\node_modules\@playwright\test\lib\test\runner.js:210:40) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Why is that?

Removing the line gets it working again.

**Comment by mxschmitt** [comment]
@alvipeo would it be possible that you could create a small repro repository which fails for you, so we can run it ourselves?

I tried to import `node-fetch` which was working for me. E.g. [here](https://github.com/mxschmitt/try-playwright/blob/master/e2e/tests/api.spec.ts).

**Comment by tekener** [comment]
@mxschmitt in the referenced repo you are using node-fetch 2.x. It stopped working with node-fetch 3.0.0

**Comment by weyert** [comment]
@tekener yeah, v3 moved to ESM packages which causes a lot of issues. Personally, I have downgraded back to v2. 

I am not sure what why packages like to move to ESM-only packages while ESM appears to be still experimental in Node.js

**Comment by Bessonov** [comment]
@JoelEinbinder I don't think closing this issue is the right way to handle it. Playwright is the only component in my setup, which isn't compatible with node-fetch@3. TBH, I don't know if there is a way for playwright to support both systems, but I see different tools handle both versions. And I thought that loading cjs from esm isn't an issue.

> This is an example of node-fetch breaking the world.

Different projects suffered with that change. And node-fetch isn't alone. But from my point of view, it's _the right move_ and helps consolidating the eco-system.

> But we can't change the defaults without breaking even more people.

Does it make sense to publish an esm compatible version of playwright? I mean then you can gather feedback on esm and prepare the playwright's eco-system? Furthermore, playwright is an update blocker now, which is very bad for security.

Anyway, I propose to reopen this issue until there is a solution.

**Comment by Bessonov** [comment]
I've discovered the [documentation changes on esm](https://playwright.dev/docs/test-typescript#typescript-with-esm). Now I'm in transition to esm and nearly everything works. Only the trace viewer doesn't match source code lines and I will create a new issue for that.
