### ISSUE TITLE
[BUG/Question] exception  no such file or directory, chmod '/node_modules/playwright-internal/lib/cli/cli.js' occurred in custom focal dockerimage

### ISSUE THREAD

**Issue by vranky** [microsoft/playwright#9043]
I have tried to replace python with ruby inside following docker configuration https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.focal 

**custom Dockerfile**

```
FROM ubuntu:focal
# === INSTALL Node.js ===
ARG PLAYWRIGHT_VERSION=1.14.1
# Install node14
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y tzdata -y nodejs

# Feature-parity with node.js base images.
RUN apt-get update && apt-get install -y --no-install-recommends git ssh && \
    npm install -g yarn

# Create the pwuser (we internally create a symlink for the pwuser and the root user)
RUN adduser pwuser

# Install Ruby 2.6

RUN apt -y update && apt -y install software-properties-common && apt-add-repository -y ppa:brightbox/ruby-ng && apt -y install ruby2.6


# === BAKE BROWSERS INTO IMAGE ===

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# 1. Add tip-of-tree Playwright package to install its browsers.
#    The package should be built beforehand from tip-of-tree Playwright.

RUN apt-get update && apt-get install -y wget default-jdk \
    && wget -qO /tmp/playwright.tar.gz https://github.com/microsoft/playwright/archive/refs/tags/v"$PLAYWRIGHT_VERSION".tar.gz \
    && tar -xf /tmp/playwright.tar.gz --directory=/tmp/


# 2. Install playwright and then delete the installation.
#    Browsers will remain downloaded in `/ms-playwright`.
#    Note: make sure to set 777 to the registry so that any user can access
#    registry.
RUN mkdir /ms-playwright

RUN mkdir /tmp/pw
RUN cd /tmp/pw
RUN npm init -y
RUN ls -la /tmp/
RUN npm i /tmp/playwright.tar.gz
RUN DEBIAN_FRONTEND=noninteractive npx playwright install-deps
RUN rm -rf /tmp/pw
RUN rm /tmp/playwright.tar.gz
RUN chmod -R 777 /ms-playwright


WORKDIR /workspace

COPY . /workspace

RUN bundle install

CMD ["/bin/bash"]
```

**Describe the bug**
When I have tried to build Dockerfile after run npm i /tmp/playwright.tar.gz, exception below occurred.

```
Step 14/22 : RUN npm i /tmp/playwright.tar.gz
 ---> Running in d8df7ffd946d
npm WARN @1.0.0 No description
npm WARN @1.0.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /node_modules/playwright-internal/lib/cli/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/node_modules/playwright-internal/lib/cli/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-21T11_45_07_551Z-debug.log

```

**Comment by mxschmitt** [comment]
I would recommend to open an issue in the Ruby port of Playwright: https://github.com/YusukeIwaki/playwright-ruby-client/issues

Normally when using a language binding, it consumes the driver which takes care about installing. For your specific case in Ruby `npx playwright@1.14.1 install --with-deps` should be enough. This installs the browsers and the OS dependencies.

**Comment by vranky** [comment]
Thanks for fast answer!
I have tried to run npx playwright@1.14.1 install --with-deps but exception below occurred.
```
Step 9/22 : RUN npx playwright@"$PLAYWRIGHT_VERSION" install --with-deps
 ---> Running in 137869d54c7c
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/8/lib/node_modules/playwright/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playwright@1.14.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the playwright@1.14.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-21T12_18_01_179Z-debug.log
Install for [ 'playwright@1.14.1' ] failed with code 1
```

**Comment by mxschmitt** [comment]
This is unfortunately a NPM bug. You can workaround it by upgrading to npm 7 before executing this command: `npm install -g npm@7`.

(gets fixed in https://github.com/microsoft/playwright/pull/8915)

**Comment by vranky** [comment]
After your workaround, I got `Tracker "idealTree" already exists`, see trace below.

```
Step 13/24 : RUN npm -v
 ---> Running in 36211976fdbf
6.14.15
Removing intermediate container 36211976fdbf
 ---> 8d45419abc8a
Step 14/24 : RUN npm i -g npm@7
 ---> Running in d0bc45fbb597
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@7.24.0
added 70 packages from 27 contributors, removed 250 packages and updated 187 packages in 13.681s
Removing intermediate container d0bc45fbb597
 ---> dcc4e994299a
Step 15/24 : RUN npm -v
 ---> Running in 01d40a112ccd
7.24.0
Removing intermediate container 01d40a112ccd
 ---> 113b440269f9
Step 16/24 : RUN npm i /tmp/playwright.tar.gz
 ---> Running in a68dacac58db
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-21T14_14_59_832Z-debug.log
The command '/bin/sh -c npm i /tmp/playwright.tar.gz' returned a non-zero code: 1

```
