### ISSUE TITLE
[BUG] browser.close() fails on windows with assert error from rimraf

### ISSUE THREAD

**Issue by jkanchelov** [microsoft/playwright#909]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Windows
- Extra: https://github.com/jkanchelov/browser-screenshot-taker

Error with the browser.close() api when running tests. The browser shuts but the test fails with the error below. 

```javascript
assert(received)

    Expected value to be equal to:
      true
    Received:
      false

      at fixWinEPERM (node_modules/rimraf/rimraf.js:175:5)
      at node_modules/rimraf/rimraf.js:160:15
```

**Comment by jkanchelov** [comment]
I saw it relates to #808 and it's kinda duplicated so I am closing it
