### ISSUE TITLE
Button with aria-disabled="false"

### ISSUE THREAD

**Issue by jersonjunior** [microsoft/playwright#9139]
I've tried it in several ways but I can't perform the button action:

Below is the Outer HTML:

```
<button id="ResultPanePlaceHolder_ButtonsPanel_btnCommit" data-control="Button" data-command="{SaveCommand, Mode=OneWay}" data-visible="{IsReadOnly, Mode=OneWay, ConvertTo=ValueConverter.Not}" aria-labelledby="" aria-disabled="false">OK</button>
```

**Logs of playwrigth:**

```
waiting for selector "text=OK"
  selector resolved to visible <button aria-labelledby="" data-control="Button" aria-di…>OK</button>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (608.36,554.48)
  element does receive pointer events
  performing click action
```

**Logs of python:**

```
Traceback (most recent call last):
  File ".\Migration.py", line 179, in <module>
    run(playwright)
  File ".\Migration.py", line 119, in run
    page2.click("text=OK")
  File "C:\Users\jerso\anaconda3\lib\site-packages\playwright\sync_api\_generated.py", line 7813, in click
    self._sync(
  File "C:\Users\jerso\anaconda3\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "C:\Users\jerso\anaconda3\lib\site-packages\playwright\_impl\_page.py", line 624, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "C:\Users\jerso\anaconda3\lib\site-packages\playwright\_impl\_frame.py", line 448, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\jerso\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\jerso\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 57, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target closed
```

**Comment by mxschmitt** [comment]
Would it be possible that you can provide us a repro for that? HTML/CSS + Python code in that case.

**Comment by friendyou1** [comment]
Okay

**Comment by aslushnikov** [comment]
Unfortunately this is not actionable without a repro; please re-file with a repro so that we can debug this!
