### ISSUE TITLE
[BUG] browserType.launch: Chromium distribution 'msedge' is not supported on linux

### ISSUE THREAD

**Issue by udit0802** [microsoft/playwright#9197]
**Context:**
- Playwright Version: 1.15.0
- Operating System: CentOS Linux 7 (Core)
- Node.js version: 14.16.1
- Browser: Edge
- Extra: It's our Jenkins CI environment 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test.describe("Login Suite", () => {
  var loginPage: LoginPage;
  var utilsPage: UtilsPage;
  var context: BrowserContext;
  var page: Page;
  var brow;

  test.beforeAll(async ({ browser }) => {
    brow = browser;
  });

  test.beforeEach(async ({}) => {
    context = await brow.newContext();
    page = await context.newPage();
    loginPage = new LoginPage(page);
    utilsPage = new UtilsPage(page);
  });

  test(`Login to AEM`, async ({ page }) => {
    await loginPage.login();
  });

  test.afterEach(async () => {
    await utilsPage.closePage();
    await context.close();
  });
});
```

**Describe the bug**

Trying to launch test on the above mentioned environment.
Getting the following error:

```
browserType.launch: Chromium distribution 'msedge' is not supported on linux
[2021-09-28T13:04:55.120Z] 
[2021-09-28T13:04:55.120Z]         at Object._baseTest.extend.browser.scope [as fn] (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/index.js:127:40)
[2021-09-28T13:04:55.120Z]         at Fixture.setup (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.setupFixtureForRegistration (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.resolveParametersAndRunHookOrTest (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
[2021-09-28T13:04:55.121Z]         at WorkerRunner._runTestWithBeforeHooks (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)
```
This error is not specific to test, as getting same error for all the tests.
How do we resolve the issue?

**Comment by aslushnikov** [comment]
@udit0802 stable channel hasn't been released on Linux yet; you can use `msedge-dev` and `msedge-beta` instead.

**Comment by udit0802** [comment]
> @udit0802 stable channel hasn't been released on Linux yet; you can use `msedge-dev` and `msedge-beta` instead.

Sure will try out, which one would be more preferable dev or beta?

**Comment by udit0802** [comment]
I have tried out with msedge-beta but facing the following error : 
```
browserType.launch: Chromium distribution 'msedge-beta' is not found at /opt/microsoft/msedge-beta/msedge
Run "npx playwright install msedge-beta"
```

**Comment by rogerprz** [comment]
> @udit0802 stable channel hasn't been released on Linux yet; you can use `msedge-dev` and `msedge-beta` instead.

I've tried both of your suggestions but no resolution. Any other options?

**Comment by MasterGru** [comment]
why this ticket ist closed?
