### ISSUE TITLE
[BUG]Error launching test in webkit browser on centos7

### ISSUE THREAD

**Issue by udit0802** [microsoft/playwright#9198]
**Context:**
- Playwright Version: 1.15.0
- Operating System: CentOS Linux 7 (Core)
- Node.js version: 14.16.1
- Browser: WebKit
- Extra: It's our Jenkins CI environment

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test.describe("Login Suite", () => {
  var loginPage: LoginPage;
  var utilsPage: UtilsPage;
  var context: BrowserContext;
  var page: Page;
  var brow;

  test.beforeAll(async ({ browser }) => {
    brow = browser;
  });

  test.beforeEach(async ({}) => {
    context = await brow.newContext();
    page = await context.newPage();
    loginPage = new LoginPage(page);
    utilsPage = new UtilsPage(page);
  });

  test(`Login to AEM`, async ({ page }) => {
    await loginPage.login();
  });

  test.afterEach(async () => {
    await utilsPage.closePage();
    await context.close();
  });
});
```

**Describe the bug**

Trying to launch test on the above mentioned environment.
Getting the following error:
```
browserType.launch: Host system is missing dependencies!
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z]       Install missing packages with:
[2021-09-28T13:04:55.121Z]           sudo apt-get install gstreamer1.0-libav
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z]       Missing libraries we didn't find packages for:
[2021-09-28T13:04:55.121Z]           libnotify.so.4
[2021-09-28T13:04:55.121Z]           libopus.so.0
[2021-09-28T13:04:55.121Z]           libwoff2dec.so.1.0.2
[2021-09-28T13:04:55.121Z]           libharfbuzz-icu.so.0
[2021-09-28T13:04:55.121Z]           libgcrypt.so.20
[2021-09-28T13:04:55.121Z]           libgstapp-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstbase-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstreamer-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstpbutils-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstaudio-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgsttag-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstvideo-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstgl-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstcodecparsers-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstfft-1.0.so.0
[2021-09-28T13:04:55.121Z]           libjpeg.so.8
[2021-09-28T13:04:55.121Z]           libpng16.so.16
[2021-09-28T13:04:55.121Z]           libopenjp2.so.7
[2021-09-28T13:04:55.121Z]           libwebpdemux.so.2
[2021-09-28T13:04:55.121Z]           libwebp.so.6
[2021-09-28T13:04:55.121Z]           libenchant.so.1
[2021-09-28T13:04:55.121Z]           libsecret-1.so.0
[2021-09-28T13:04:55.121Z]           libhyphen.so.0
[2021-09-28T13:04:55.121Z]           libicui18n.so.66
[2021-09-28T13:04:55.121Z]           libicuuc.so.66
[2021-09-28T13:04:55.121Z]           libevdev.so.2
[2021-09-28T13:04:55.121Z]           libGLESv2.so.2
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z]         at Object._baseTest.extend.browser.scope [as fn] (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/index.js:127:40)
[2021-09-28T13:04:55.121Z]         at Fixture.setup (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.setupFixtureForRegistration (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.resolveParametersAndRunHookOrTest (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
[2021-09-28T13:04:55.121Z]         at WorkerRunner._runTestWithBeforeHooks (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)
```
This error is not specific to test, as getting same error for all the tests.
How do we resolve the issue?
Any help would be appreciated.

**Comment by aslushnikov** [comment]
CentOS is not officially supported; thank you for filing the feature request #9199! Closing in favor of it.

**Comment by udit0802** [comment]
> CentOS is not officially supported; thank you for filing the feature request #9199! Closing in favor of it.

Hope this will be provided soon, waiting for this feature :)
