### ISSUE TITLE
[Feature] Support CentOS

### ISSUE THREAD

**Issue by udit0802** [microsoft/playwright#9199]
**Edit by maintainers**

Hey everybody!

There's now an experimental support for all linux distributions using our browser container image  `mcr.microsoft.com/playwright`.
If you can run this container image on your linux distribution, then you can instruct `@playwright/test` to connect to it and run browsers inside the container.

Please give it a try and let us know what you think here: https://github.com/microsoft/playwright/issues/26482

---

We have our CI machines setup on centos7.
I am trying to integrate in our integration tests which runs on jenkins on centos machines.
Able to run tests using chrome but facing issues with following browsers:

<h2>Chromium :</h2> 

```
<launching> /home/centos/.cache/ms-playwright/chromium-920619/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/tmp/playwright_chromiumdev_profile-GyWOJw --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
[2021-09-28T13:04:55.123Z]     <launched> pid=20094
[2021-09-28T13:04:55.123Z]     [pid=20094][err] /home/centos/.cache/ms-playwright/chromium-920619/chrome-linux/chrome: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/centos/.cache/ms-playwright/chromium-920619/chrome-linux/chrome)
[2021-09-28T13:04:55.123Z]     [pid=20094] <process did exit: exitCode=1, signal=null>
[2021-09-28T13:04:55.123Z]     [pid=20094] starting temporary directories cleanup
```
This issue was earlier reported on [1].

<h2>Edge :</h2> 

```
browserType.launch: Chromium distribution 'msedge' is not supported on linux
[2021-09-28T13:04:55.120Z] 
[2021-09-28T13:04:55.120Z]         at Object._baseTest.extend.browser.scope [as fn] (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/index.js:127:40)
[2021-09-28T13:04:55.120Z]         at Fixture.setup (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.setupFixtureForRegistration (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.resolveParametersAndRunHookOrTest (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
[2021-09-28T13:04:55.121Z]         at WorkerRunner._runTestWithBeforeHooks (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)
```
Issue reported earlier on [2]

<h2>Webkit:</h2>

```
browserType.launch: Host system is missing dependencies!
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z]       Install missing packages with:
[2021-09-28T13:04:55.121Z]           sudo apt-get install gstreamer1.0-libav
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z]       Missing libraries we didn't find packages for:
[2021-09-28T13:04:55.121Z]           libnotify.so.4
[2021-09-28T13:04:55.121Z]           libopus.so.0
[2021-09-28T13:04:55.121Z]           libwoff2dec.so.1.0.2
[2021-09-28T13:04:55.121Z]           libharfbuzz-icu.so.0
[2021-09-28T13:04:55.121Z]           libgcrypt.so.20
[2021-09-28T13:04:55.121Z]           libgstapp-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstbase-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstreamer-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstpbutils-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstaudio-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgsttag-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstvideo-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstgl-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstcodecparsers-1.0.so.0
[2021-09-28T13:04:55.121Z]           libgstfft-1.0.so.0
[2021-09-28T13:04:55.121Z]           libjpeg.so.8
[2021-09-28T13:04:55.121Z]           libpng16.so.16
[2021-09-28T13:04:55.121Z]           libopenjp2.so.7
[2021-09-28T13:04:55.121Z]           libwebpdemux.so.2
[2021-09-28T13:04:55.121Z]           libwebp.so.6
[2021-09-28T13:04:55.121Z]           libenchant.so.1
[2021-09-28T13:04:55.121Z]           libsecret-1.so.0
[2021-09-28T13:04:55.121Z]           libhyphen.so.0
[2021-09-28T13:04:55.121Z]           libicui18n.so.66
[2021-09-28T13:04:55.121Z]           libicuuc.so.66
[2021-09-28T13:04:55.121Z]           libevdev.so.2
[2021-09-28T13:04:55.121Z]           libGLESv2.so.2
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z] 
[2021-09-28T13:04:55.121Z]         at Object._baseTest.extend.browser.scope [as fn] (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/index.js:127:40)
[2021-09-28T13:04:55.121Z]         at Fixture.setup (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.setupFixtureForRegistration (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
[2021-09-28T13:04:55.121Z]         at FixtureRunner.resolveParametersAndRunHookOrTest (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/fixtures.js:297:23)
[2021-09-28T13:04:55.121Z]         at WorkerRunner._runTestWithBeforeHooks (/apps/jnkn/workspace/EvergreenShoots-CMgt_PR-1560/main/integration-tests/playwright-e2e/node_modules/@playwright/test/lib/test/workerRunner.js:449:7)
```
Issue reported earlier on [3]

As many organizations like ours uses centos machines as their infrastructure, this feature will have a wider impact and will help many developers.
Request playwright team to have a look at this request.

Thanks!!

[1]: https://github.com/microsoft/playwright/issues/9194
[2]: https://github.com/microsoft/playwright/issues/9197
[3]: https://github.com/microsoft/playwright/issues/9198

**Comment by kumaraditya303** [comment]
Fyi, I have got chromium and firefox working on CentOS 8 and created a dockerfile here https://github.com/kumaraditya303/playwright-centos/blob/master/Dockerfile only WebKit is not working.
Linking https://github.com/microsoft/playwright/issues/6219

**Comment by udit0802** [comment]
> https://github.com/kumaraditya303/playwright-centos/blob/master/Dockerfile

Awesome, i was expecting OOTB support for the same.

**Comment by jasonparallel** [comment]
GLIBC_2.18 ticket for chromium https://bugs.chromium.org/p/chromium/issues/detail?id=1253967&q=glibc&can=2

**Comment by cnmade** [comment]
+1 , we would like using Playwright on our production server, it runs CentOS 8

**Comment by y-chen** [comment]
+1

**Comment by FreezeSoul** [comment]
+1

**Comment by bbhxwl** [comment]
+1
chromium-930007    ./chrome: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./chrome)

**Comment by bbhxwl** [comment]
+10

**Comment by aslushnikov** [comment]
For the record: only issue **upvoting** counts as a vote

**Comment by irharrier2** [comment]
> For the record: only issue **upvoting** counts as a vote

By issue upvoting, do you mean liking the first post in this thread?

**Comment by canfeng11** [comment]
+10

**Comment by anastasiyamazheika** [comment]
+1

**Comment by rinogo** [comment]
What version(s) should we revert to for CentOS support? We were previously using `^1.9.2` successfully on our CentOS machine. When we updated to `^1.18.1`, we started having problems. I see that @vigneshshanmugam reverted to `1.14.0`. Will that enable us to use `chrome` on CentOS?

**Comment by andrewvc** [comment]
@rinogo I think you may be confused between the versioning of https://github.com/elastic/synthetics which uses `playwright` and this repo which is for the playwright project itself. We have resolved our issue by moving our base image to centos FWIW.

**Comment by rinogo** [comment]
Thanks for your feedback, @andrewvc ! I was referring to [this](https://github.com/elastic/synthetics/pull/402/commits/9c5bbfaf3982149c54f08a143b097bdfddd7dfe8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R48); maybe I'm misunderstanding, though!

Regardless, our environment is unfortunately not containerized, so switching platforms is a lot more challenging. Hoping something can come of this for us and the community - lots of legacy CentOS-hosted apps are still out there!

If I find some other kind of workaround, I'll post back here.

**Comment by ECIAP** [comment]
+1

**Comment by drawdy** [comment]
+1

**Comment by azarudeena** [comment]
++!

**Comment by tranngoclam** [comment]
+1

**Comment by Rvtea** [comment]
+1

**Comment by digiscape-bnu** [comment]
+1 (Rocky Linux)

**Comment by ToanNguyen97** [comment]
+1

**Comment by royteeuwen** [comment]
+1

**Comment by sanderlenaerts** [comment]
+1

**Comment by BryanEdClark** [comment]
+1

**Comment by rhwong** [comment]
+1

**Comment by Sanady** [comment]
+1

**Comment by baart1989** [comment]
+ 1

**Comment by eugeniodevv** [comment]
+1

**Comment by abadfox233** [comment]
+1

**Comment by theniceangel** [comment]
+1

**Comment by kght6123** [comment]
+1 CentOS！

**Comment by noraroxette** [comment]
+1 CentOS, Rhel ! The lack of support for these platforms is so frustrating :( Our CI/CD runs on RHEL and there's no way for us to change unfortunately.

**Comment by jglick** [comment]
I got Firefox working in a UBI-based CI container image roughly as follows:

```dockerfile
FROM mcr.microsoft.com/playwright/java:v1.30.0-focal as playwright
FROM registry.access.redhat.com/ubi8
RUN dnf update -y && \
    dnf install -y \
        libX11-xcb \
        mesa-libGL \
        pciutils-libs \
        `# other stuff…` && \
    dnf -y clean all
COPY --from=playwright /ms-playwright /ms-playwright
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
```
Did not check other browsers, which likely require additional libraries.

**Comment by phyesix** [comment]
I am using Almalinux. I would be glad if you can support.

**Comment by baiyyee** [comment]
+1

**Comment by jasonparallel** [comment]
@aslushnikov The recent move to node 18 broke centos 7 support. Was this intentional? See https://github.com/nodejs/node/issues/43246

**Comment by aslushnikov** [comment]
@jasonparallel we never supported CentOS, so i'm not sure what broke exactly. The move to node 18 was since 18 is the current LTS.

**Comment by yesid-lopez** [comment]
+1

**Comment by DexterIA** [comment]
+1 CentoOS support needed for our CI

**Comment by gskierk** [comment]
+1

**Comment by dulestar** [comment]
+1

**Comment by tustman** [comment]
+1 for centos

**Comment by vasthan** [comment]
+1

**Comment by Johnson-You** [comment]
+1

**Comment by aslushnikov** [comment]
Hey everybody!

There's now an experimental support for all linux distributions using our browser container image  `mcr.microsoft.com/playwright`.
If you can run this container image on your linux distribution, then you can instruct `@playwright/test` to connect to it and run browsers inside the container.

Please give it a try and let us know what you think here: https://github.com/microsoft/playwright/issues/26482

**Comment by jonasz9** [comment]
+1

**Comment by abinba** [comment]
+1

**Comment by tov324** [comment]
+1

**Comment by 1ManSmoking** [comment]
Managed to run playwright 1.39.0 on CentOs 7 with firefox browser by building glibc-2.28 from sources, patchelf and adding some missing libraries.
But chromium (also patched with patchelf) fails -
PlaywrightException: Failed to read message from driver, pipe closed.

Guess its some kind of driver issue.
Did anyone do something similar and can assist?
Thanks a lot!

**Comment by Knowledge-Labz** [comment]
Heads up, since the solution quoted in [here](https://github.com/kumaraditya303/playwright-centos/blob/master/Dockerfile) installs a static version, turns out we could make playwright with chromium work without a problem on our Rocky8 servers with a simplification of @kumaraditya303 fantastic answer! This command replaces _playwright install-deps_ .

<code>dnf install -y alsa-lib \\
    at-spi2-atk \\
    at-spi2-core \\
    atk \\
    bash \\
    cairo \\
    cups-libs \\
    dbus-libs \\
    expat \\
    flac-libs \\
    gdk-pixbuf2 \\
    glib2 \\
    glibc \\
    gtk3 \\
    libX11 \\
    libXcomposite \\
    libXdamage \\
    libXext \\
    libXfixes \\
    libXrandr \\
    libXtst \\
    libcanberra-gtk3 \\
    libdrm \\
    libgcc \\
    libstdc++ \\
    libxcb \\
    libxkbcommon \\
    libxshmfence \\
    libxslt \\
    mesa-libgbm \\
    nspr \\
    nss \\
    nss-util \\
    pango \\
    policycoreutils \\
    policycoreutils-python-utils \\
    zlib</code>

**Comment by chrisdavies** [comment]
To add to @knowledge-labz answer, I had to also install `[dbus-glib](https://fedora.pkgs.org/39/fedora-x86_64/dbus-glib-0.112-6.fc39.x86_64.rpm.html) in order for Firefox to work.

**Comment by mario16** [comment]
> Heads up, since the solution quoted in [here](https://github.com/kumaraditya303/playwright-centos/blob/master/Dockerfile) installs a static version, turns out we could make playwright with chromium work without a problem on our Rocky8 servers with a simplification of @kumaraditya303 fantastic answer! This command replaces _playwright install-deps_ .
> 
> `dnf install -y alsa-lib \ at-spi2-atk \ at-spi2-core \ atk \ bash \ cairo \ cups-libs \ dbus-libs \ expat \ flac-libs \ gdk-pixbuf2 \ glib2 \ glibc \ gtk3 \ libX11 \ libXcomposite \ libXdamage \ libXext \ libXfixes \ libXrandr \ libXtst \ libcanberra-gtk3 \ libdrm \ libgcc \ libstdc++ \ libxcb \ libxkbcommon \ libxshmfence \ libxslt \ mesa-libgbm \ nspr \ nss \ nss-util \ pango \ policycoreutils \ policycoreutils-python-utils \ zlib`

This works for an Amazon Linux 2 image on AWS (with yum package manager instead of dnf).
Thanks!

**Comment by hafiz031** [comment]
I tried running my `scrapy-playwright` project and faced similar issue. I managed to run my project in `CentOS 7` by dockarising the it under `Ubuntu 20.04` base image. I could not use Ubuntu 22.04 (current latest LTS) due to the following error: `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ...`

**Comment by yeyuchen198** [comment]
真是可惜官方不支持Cent OS，虽然网上有一些魔法可以使用，但也多多少少有些问题。
最后我还是用Docker算了：docker pull mcr.microsoft.com/playwright/python:v1.32.0-focal
亲测这个镜像可以正常使用，但是有些镜像是坏的！

注意：不要使用docker pull mcr.microsoft.com/playwright/python:v1.40.0-jammy
实际测试，这个镜像是坏的，里面没有playwright，连pip install xxx也报错！！！
千万不要安装这个镜像！！！！！！

**Comment by bbhxwl** [comment]
> 真是可惜官方不支持Cent OS，虽然网上有一些魔法可以使用，但也多多少少有些问题。 最后我还是用Docker算了：docker pull mcr.microsoft.com/playwright/python:v1.32.0-focal 亲测这个镜像可以正常使用，但是有些镜像是坏的！
> 
> 注意：不要使用docker pull mcr.microsoft.com/playwright/python:v1.40.0-jammy 实际测试，这个镜像是坏的，里面没有playwright，连pip install xxx也报错！！！ 千万不要安装这个镜像！！！！！！

我一直不能在docker 里面运行，不知道为什么。

**Comment by sksharma0** [comment]
I was having issues with using playwright on aws lambda inside a centos python docker image, was able to solve with the help of @kumaraditya303 using below dockerfile: 
https://github.com/sksharma0/playwright-on-centos/blob/master/dockerfile
putting it here for reference

**Comment by watio0o** [comment]
+1

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/26482

**Comment by juanfrilla** [comment]
I have a workaround for all of you guys, use playwright with selenium grid, i have a video of how to connect both tools, you only need to configure the selenium grid with a docker-compose and in case you are using python, install selenium and playwright packages and you dont need to excecute the `playwright install` command since it will not take the browsers from the host machine but from the selenium grid infrastructure.
https://www.youtube.com/watch?v=OT06-RDFkrI
