### ISSUE TITLE
issue after install new version of playwright 

### ISSUE THREAD

**Issue by rintaroSukuna** [microsoft/playwright#9225]
Hi, after install nw version of playwright, when I'm running test, terminal throwing this error -->

node_modules/@playwright/test/lib/grid/gridServer.js:143

 constructor(capacity = Infinity, creationTimeout = 5 * 60_000) {
                                                         ^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/qa/workspace/playwright-test/node_modules/@playwright/test/lib/cli/cli.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

**Comment by mxschmitt** [comment]
You need Node.js 12+

**Comment by rintaroSukuna** [comment]
but Node.js v12.0.0

**Comment by mxschmitt** [comment]
You need 12.5.0+ 

https://nodejs.org/en/download/

**Comment by aslushnikov** [comment]
@JoelEinbinder Joel, can we compile our typescript down to 12.0.0?
