### ISSUE TITLE
[BUG] Intermittent fails on tear-down

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#9231]
**Context:**
- Playwright Version: 1.15
- running using image: mcr.microsoft.com/playwright:focal

**Code Snippet**

```javascript
2021-09-30T08:31:45.006Z pw:api => browserContext.close started
  1) [Desktop Safari] › src/__tests__/zz.spec.ts:21:5 › local run should blabla
    Timeout of 42000ms exceeded.
2021-09-30T08:31:53.427Z pw:api => tracing.stopChunk started
2021-09-30T08:31:53.429Z pw:api <= tracing.stopChunk failed
tracing.stopChunk: Must start tracing before stopping
    at .../.yarn/unplugged/@playwright-test-npm-1.15.0-7cc1587cea/node_modules/@playwright/test/lib/test/index.js:329:48
    at Object._baseTest.extend._setupContextOptionsAndArtifacts.auto [as fn] (....yarn/unplugged/@playwright-test-npm-1.15.0-7cc1587cea/node_modules/@playwright/test/lib/test/index.js:328:40)
    at Fixture.teardown (.../.yarn/unplugged/@playwright-test-npm-1.15.0-7cc1587cea/node_modules/@playwright/test/lib/test/fixtures.js:98:7)
    at Fixture.teardown (.../.yarn/unplugged/@playwright-test-npm-1.15.0-7cc1587cea/node_modules/@playwright/test/lib/test/fixtures.js:91:40)
    at Fixture.teardown (....yarn/unplugged/@playwright-test-npm-1.15.0-7cc1587cea/node_modules/@playwright/test/lib/test/fixtures.js:91:40)
    at FixtureRunner.teardownScope (.../.yarn/unplugged/@playwright-test-npm-1.15.0-7cc1587cea/node_modules/@playwright/test/lib/test/fixtures.js:269:11)
    at.../.yarn/unplugged/@playwright-test-npm-1.15.0-7cc1587cea/node_modules/@playwright/test/lib/test/workerRunner.js:91:7
```

**Describe the bug**

after the test is succeeded, browserContext.close took at least 8 seconds ( when usually it takes less than a second )
which triggered some fixture error + timeout

not sure about reproducing the issue, but as a hint - there were some network issues and/or some hanging http/ws requests ( which didn't affect the test run )

**Comment by aslushnikov** [comment]
@dimkin-eu could you please share you `playwright.config.ts` ? Do you have a timeout of 42 seconds for tests?

**Comment by dimkin-eu** [comment]
@aslushnikov yes, 42 secs are there, because sometimes 30 is not enough, and funny values are added, for easier findings - is it mine timeouts or not :)
```javascript
import type {PlaywrightTestConfig} from "@playwright/test"

const config: PlaywrightTestConfig = {
    use: {
        // headless: false,
        ignoreHTTPSErrors: true,
        screenshot: "on",
        video: "retain-on-failure",
        trace: "retain-on-failure",
        launchOptions: {
            // slowMo: 1000,
        },
    },

    projects: [
        {
            name: "Desktop Chromium",
            use: {
                browserName: "chromium",
                viewport: {width: 1920, height: 1080}
            },
        },
        {
            name: "Desktop Safari",
            use: {
                browserName: "webkit",
                viewport: {width: 1920, height: 1080},
            }
        },
    ],
    reporter: [["line"], ["allure-playwright"]],
    workers: 1,
    timeout: 42000,
    globalTimeout: 146000
}
export default config
```

**Comment by mxschmitt** [comment]
@dimkin-eu  do you have a full repro for us? Otherwise its hard for us to guess/investigate.
