### ISSUE TITLE
[BUG] - Loading amazon apstag.js script tag crashes the Firefox browser

### ISSUE THREAD

**Issue by hallzy** [microsoft/playwright#9268]
**Context:**
- Playwright Version: 1.15.1
- Operating System: Linux
- Node.js version: 14.10.0
- Browser: Firefox
- Extra: We are running playwright with web-test-runner

**Code Snippet**

```javascript
it
(
	'x',
	done =>
	{
		function onLoad()
		{
			done();
		}
		function onError(e)
		{
			done('onError');
		}

		const script = document.createElement('script');
		script.src = 'https://c.amazon-adsystem.com/aax2/apstag.js';

		script.addEventListener('load',onLoad);
		script.addEventListener('error',onError);
		document.head.appendChild(script);
	},
);
```

**Describe the bug**

The above test crashes the Firefox browser that playwright uses, but if you open this test manually in a system installed firefox browser it works fine.

The issue comes down to the src being used. It was [added as a shim by mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1713698). In a normal firefox browser the shim is used and a console warnings appears "Amazon Transparent Ad Marketplace is being shimmed by Firefox". `apstag.js` also does not appear in the network tab as it isn't doing a network request because the file is being loaded locally by firefox.

In the firefox window that playwright starts, the whole browser crashes before I am able to seen anything in the console or network tab.

This is the error I get:

```
source/stn-player/features/LoopPlaylist.test.js:

 ❌ Tests were interrupted because the browser disconnected.

 ❌ Error: Session fm-qVJtDHlIu5YgxaYMtm is already stopped
    Error: Session fm-qVJtDHlIu5YgxaYMtm is already stopped
        at PlaywrightLauncher.stopSession (/path/to/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:87:19)
        at TestScheduler.stopSession (/path/to/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:135:92)
        at EventEmitter.<anonymous> (/path/to/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:26:28)
        at EventEmitter.emit (events.js:326:22)
        at TestSessionManager.emit (/path/to/node_modules/@web/test-runner-core/dist/utils/EventEmitter.js:16:24)
        at TestSessionManager.updateStatus (/path/to/node_modules/@web/test-runner-core/dist/test-session/TestSessionManager.js:32:14)
        at TestRunnerApiPlugin._setSessionFailed (/path/to/node_modules/@web/test-runner-core/dist/server/plugins/api/testRunnerApiPlugin.js:206:23)
        at TestRunnerApiPlugin._waitForDisconnect (/path/to/node_modules/@web/test-runner-core/dist/server/plugins/api/testRunnerApiPlugin.js:197:18)
```

The only workaround I have so far is to disable the shim in the browser launcher:

```
firefoxUserPrefs: {
    'extensions.webcompat.enable_shims': false,
}
```

Adding this launch option fixes the test, and it will pass, but I suspect there is something wrong somewhere which is causing the browser to crash with shims enabled in the first place.

After looking at the code change for [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1713698) for firefox, I tried out a bunch of other URLs that were being shimmed as well and found that these URLs are also causing a browser crash:

```
https://webcompat-addon-testbed.herokuapp.com/shims_test.js
https://example.com/browser/browser/extensions/webcompat/tests/browser/shims_test.js
https://example.com/browser/browser/extensions/webcompat/tests/browser/shims_test_3.js
https://c.amazon-adsystem.com/aax2/apstag.js
https://cdn.adsafeprotected.com/iasPET.1.js
```

There are a number of shimmed URLs though that don't cause a crash.

I did also check the firefox browser webcompat extension (this is the built in firefox extension that adds the shims) that playwright installed at `~/.cache/ms-playwright/firefox/1295/firefox/browser/features/webcompat@mozilla.org.xpi`.

I unzipped it and found that the shimmed file and other related changes appear to be there, so the installation of firefox seems to have been fine.

**Comment by hallzy** [comment]
I got an email notification saying that you think this is an upstream Firefox bug, not sure where that message went (maybe someone removed it).

Just wanted to reiterate that this issue does not happen when using a system installed version of Firefox (the same exact version in fact), so whatever the issue happens to be, it seems like it only happens when running the tests with the firefox that is used by playwright.

Maybe that issue is with Firefox itself and not playwright but this seemed like the logical place to start given what I have seen.

**Comment by hallzy** [comment]
Yeah, above I have a small test script using web-test-runner.

I also just made this script that only uses playwright:

```js
const { firefox } = require('playwright');

(async () => {
    const browser = await firefox.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('about:blank');

    const promise = page.evaluate(() => {
        return new Promise(resolve => {
            function onLoad() {
                resolve('Loaded');
            }
            function onError(e) {
                resolve('Failed to Load');
            }

            const script = document.createElement('script');
            script.src = 'https://c.amazon-adsystem.com/aax2/apstag.js';

            script.addEventListener('load',onLoad);
            script.addEventListener('error',onError);
            document.head.appendChild(script);
        });
    });

    try
    {
        const ret = await promise;
        console.log("Resolved", ret);
    }
    catch(e)
    {
        console.error("Rejected", e);
    }

    await browser.close();
})();
```

So it should resolve regardless of if the script loads or the loading errors, but it gets rejected:

```
Rejected page.evaluate: Target closed
    at /path/to/test.js:9:26 {
  name: 'Error'
}
```
