### ISSUE TITLE
[BUG] Unable to wait for alert or get text

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#9277]
**Context:**
- Playwright Version: 1.15.1
- Operating System: Linux
- Node.js version: 14
- Browser: any

**Code Snippet**

```
    async getAlertText() {
        const dialogPromise = await this.page.waitForEvent('dialog');
        const dialog = await dialogPromise;
        console.log(dialog.message());
        return dialog.message()
    }
```
or 

```
    async acceptAlert() {
        await this.page.on('dialog', async (dialog) => {
            await dialog.accept();
        });
    }
```
or 
```
    async acceptAlert() {
        const dialogPromise = await this.page.waitForEvent('dialog');
        const dialog = await dialogPromise;
        dialog.accept()
        return this;
    }
```

    test.only('1.ant', async ({page}) => {
        const p = new test1(page);
        await p.test(D.schoolName, D.lastname, D.schoolEmail)
        await p.getAlertText()
    })
```

**Describe the bug**
Im unable to interact with the alert dialog due to the following error 
```
    Timeout of 20000ms exceeded.

    Error: Page closed
    =========================== logs ===========================
    waiting for event "dialog"
    ============================================================

        at Page._waitForEvent (/home/amrka/Desktop/owlo/node_modules/@playwright/test/lib/client/page.js:474:100)
        at Page.waitForEvent (/home/amrka/Desktop/owlo/node_modules/@playwright/test/lib/client/page.js:461:17)
        at School.getAlertText (file:///home/amrka/Desktop/owlo/src/pages/schoolsPage.js:120:47)
        at file:///home/amrka/Desktop/owlo/src/specs/3.Schools.test.js:41:17
        at WorkerRunner._runTestWithBeforeHooks (/home/amrka/Desktop/owlo/node_modules/@playwright/test/lib/test/workerRunner.js:466:7)
```

**Comment by JoelEinbinder** [comment]
The issue you are having is that you are waiting for the dialog before running your test which causes the dialog to appear. Something like:

1. Wait for a dialog to appear
2. Get the dialog text
3. Run the test that causes the dialog.

You are stuck on step 1 because nothing has caused the dialog to appear yet.

Instead create the dialog promise without awaiting it, then run the test, then await the dialog promise.

```js
test.only('1.ant', async ({page}) => {
    const p = new test1(page);
    const dialogPromise = page.waitForEvent('dialog').then(async d => {
      console.log('A dialog was created');
      await d.accept();
      return d.message();
    });
    await p.test(D.schoolName, D.lastname, D.schoolEmail)
    const text = await dialogPromise;
    console.log('The dialog text is', text);
});
```

**Comment by Amrkamel1** [comment]
@JoelEinbinder gotcha, its worling, however the method I have provided was working as well before with mocha,

it seems that waitForEvent should be trigger before the action and its listening until the dialog is fired

**Comment by Amrkamel1** [comment]
it would be better if there is a better solution, where I can just call one method a
fter the action is done so it can wait for the alert, accept/dismiss or get text, something similar to what we cypress/ wdio has
```
await browser.waitUntil(() => {
            try {
                    browser.acceptAlert();
                    return true;
            } catch (err) {
                console.log(`Failed to perform the task: ${err}`)
                return false;
            }
        });
```
