### ISSUE TITLE
[Question] How to use log4js with Playwright runner?

### ISSUE THREAD

**Issue by StanislavKhvalinskyiDevPro** [microsoft/playwright#9366]
Hello! We're migrating from the Jest to the Playwright runner. We were using log4js and now I wondering whether we can use it with Playwright? I know about Playwright Logger... but is it possible to make migration less painful?
Thanks for any help in advance.

Our log4js config:
```
export const createLogger = (name: string, id: string): log4js.Logger => {
  const logger = log4js.getLogger(`[${name.padStart(10, '-')}]`);
  logger.addContext('id', id);
  return logger;
};
```

**Comment by aslushnikov** [comment]
@StanislavKhvalinskyiDevPro I assume that you use log4js for some of your logging inside tests. This should just work straight away.

So what exactly doesn't work with Playwright Test?

**Comment by StanislavKhvalinskyiDevPro** [comment]
Maybe smth is wrong with imports. In some cases Playwright cannot instantiate a class. E.g.:
```
import { BaseElementHandle } from '../../../controls/base/elementHandle/baseElementHandle';

export class CalendarEvent extends BaseElementHandle {
....
}
```
```
...
export class BaseElementHandle extends LazyElement{

  constructor(...) {
    ...
  }
```
When I try to run a test, Playwright throws
```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/ui-tests/src/page-objects/pages/deal-details/calendar/calendarEvent.fragment.ts:6:36)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module._compile (/ui-tests/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.newLoader (/ui-tests/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/ui-tests/src/page-objects/pages/deal-details/calendar/eventsList.fragment.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module._compile (/ui-tests/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Object.newLoader (/ui-tests/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
```

BTW it looks like Playwright also does not respect import aliases based on the npm workspaces...

I suppose that problem with logger may also be related to imports...

**Comment by StanislavKhvalinskyiDevPro** [comment]
Yep, we're using TypeScript. If I understood the [manual](https://playwright.dev/docs/test-typescript/) right we have to compile TS before running tests. Is it really so?
