### ISSUE TITLE
[BUG] Firefox - waiting for event "popup" timeout error when the popup event is fired from frame element.

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#9412]
**Context:**
- Playwright Version: [tot]
- Operating System: [Mac]
- Node.js version: [16.9.1]
- Browser: [Firefox]
- Extra: [Issue reproducible only in Firefox]

**Code Snippet**
Below code is generated using Playwright Inspector.

```javascript
const { test, expect } = require('@playwright/test');
test('test', async ({ page }) => {
    await page.goto('https://www.way2automation.com/way2auto_jquery/frames-and-windows.php');
    // Click text=Open Seprate New Window
    await page.click('text=Open Seprate New Window');
    // Click text=Open New Seprate Window
    const [page1] = await Promise.all([
        page.waitForEvent('popup'),
        page.frame({
            url: 'https://www.way2automation.com/way2auto_jquery/frames-windows/defult2.html'
        }).click('text=Open New Seprate Window')
    ]);
});

```

**Describe the bug**
I noticed this issue in my application while running the test in Firefox. When the popup event is fired from frame element, Firefox waits for popup event and eventually times out.

The same code works smoothly in Chrome and Webkit.

To simplify the issue, i created a reproducible code. Kindly let me know if you need more information.

Here is the output from Terminal.

```javascript
✘  [Test] › test/pw1.test.spec.js:7:1 › test (30s)

  1) [Test] › test/pw1.test.spec.js:7:1 › test =====================================================

    Timeout of 30000ms exceeded.

    Error: Page closed
    =========================== logs ===========================
    waiting for event "popup"
    ============================================================

      12 |     // Click text=Open New Seprate Window
      13 |     const [page1] = await Promise.all([
    > 14 |         page.waitForEvent('popup'),
         |              ^
      15 |         page.frame({
      16 |             url: 'https://www.way2automation.com/way2auto_jquery/frames-windows/defult2.html'
      17 |         }).click('text=Open New Seprate Window')

        at Page._waitForEvent (/kb-auto-pw/node_modules/@playwright/test/lib/client/page.js:471:100)
        at Page.waitForEvent (/kb-auto-pw/node_modules/@playwright/test/lib/client/page.js:458:17)
        at /kb-auto-pw/test/pw1.test.spec.js:14:14
        at WorkerRunner._runTestWithBeforeHooks (/kb-auto-pw/node_modules/@playwright/test/lib/test/workerRunner.js:466:7)

  1 failed
    [Test] › test/pw1.test.spec.js:7:1 › test ======================================================
```

**Comment by vsravuri** [comment]
Appreciate if you could take a look at this issue, i am blocked running my tests in Firefox

**Comment by yury-s** [comment]
I can reproduce it, it's a bug.

**Comment by vsravuri** [comment]
@yury-s The workaround is working. Thanks.
