### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lschricke** [microsoft/playwright#9467]
**Context:**
***System:***
 - OS: Linux 4.4 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 342.80 MB / 5.83 GB
 - Container: Yes

***Binaries:***
 - Node: 14.18.0 - /usr/bin/node
 - Yarn: 1.22.15 - /usr/bin/yarn
 - npm: 6.14.15 - /usr/bin/npm

***Languages:***
 - Bash: 5.0.17 - /usr/bin/bash

***npmPackages:***
 - playwright: ^1.15.2 => 1.15.2 

**Code Snippet**

I'm using the trace configuration below:

```javascript
retries: 1,
use: {
    trace: "on-first-retry",
    //...
}
```

I'm not sharing the actual test code snippet as I experienced the same error with unrelated test codes, so I'm not sure it's the relevant part here.

**Describe the bug**

First, congratulations for this awesome e2e test platform, it's really great! 

About the bug: I'm having the following error from time to time. It happens when retrying a test after a first failure. It seems related to Playwright but I'm not sure. 

```
tracing.startChunk: Must start tracing before starting a new chunk
    at onDidCreateContext (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/index.js:235:31)
    at Object._baseTest.extend._setupContextOptionsAndArtifacts.auto [as fn] (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/index.js:290:40)
    at Fixture.setup (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/fixtures.js:73:73)
    at FixtureRunner.setupFixtureForRegistration (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/fixtures.js:312:5)
    at FixtureRunner.resolveParametersAndRunHookOrTest (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/fixtures.js:284:45)
    at WorkerRunner._runHooks (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/workerRunner.js:516:9)
    at WorkerRunner._runBeforeHooks (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/workerRunner.js:422:7)
    at WorkerRunner._runTestWithBeforeHooks (/usr/src/tests/e2e/node_modules/@playwright/test/lib/test/workerRunner.js:442:32)
```

Would happen to have any clue of what may cause this?

Thanks! :)

**Comment by Nav-2d** [comment]
I am seeing this issue intermittently as well. In my scenario, I was running around 80+ tests on Docker and for mobile emulation (iPhone 11), I saw the following error twice and the log indicated that the test ran for (4m) although my timeout is set to 2m.

```
tracing.stopChunk: Tracing is already stopping

    at /app/node_modules/@playwright/test/lib/test/index.js:332:48
    at Object._baseTest.extend._setupContextOptionsAndArtifacts.auto [as fn] (/app/node_modules/@playwright/test/lib/test/index.js:331:40)
    at Fixture.teardown (/app/node_modules/@playwright/test/lib/test/fixtures.js:98:7)
    at Fixture.teardown (/app/node_modules/@playwright/test/lib/test/fixtures.js:91:40)
    at FixtureRunner.teardownScope (/app/node_modules/@playwright/test/lib/test/fixtures.js:269:11)
    at /app/node_modules/@playwright/test/lib/test/workerRunner.js:91:7
```
