### ISSUE TITLE
[BUG] Lock file is already being held

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#9574]
```
npm ERR! code 1
npm ERR! path /Users/pfeldman/code/playwright/packages/playwright-webkit
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/pfeldman/code/playwright/node_modules/proper-lockfile/lib/lockfile.js:68
npm ERR!                 return callback(Object.assign(new Error('Lock file is already being held'), { code: 'ELOCKED', file }));
npm ERR!                                               ^
npm ERR! 
npm ERR! Error: Lock file is already being held
npm ERR!     at /Users/pfeldman/code/playwright/node_modules/proper-lockfile/lib/lockfile.js:68:47
npm ERR!     at callback (/Users/pfeldman/code/playwright/node_modules/graceful-fs/polyfills.js:299:20)
npm ERR!     at FSReqCallback.oncomplete (node:fs:199:5) {
npm ERR!   code: 'ELOCKED',
npm ERR!   file: '/Users/pfeldman/Library/Caches/ms-playwright'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pfeldman/.npm/_logs/2021-10-17T18_02_49_591Z-debug.log
```

**Comment by pavelfeldman** [comment]
Re-running `npx playwright install` resolves the issue, but the error message could have been more clear.
