### ISSUE TITLE
[BUG] Error while launching Browser in remote machine after connecting to Selenium Grid

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#9758]
**Context:**
- Playwright Version: [1.16]
- Operating System: [Windows, Mac]
- Node.js version: [16.12.0]
- Browser: [Chrome]
- Extra: [N/A]

**Code Snippet**

playwright.config
```javascript

    const config = {
        workers: 1,
        globalTimeout: 0,
        reporter: [
            ['list']
        ],
        projects: [{
            name: 'Test',
            testDir: './test',
            testMatch: 'pw1*.test.spec.js',
            retries: 0,
            timeout: 0,
            use: {
                browserName: 'chromium',
                channel: 'chrome',
                headless: false,
                viewport: {width: 1600, height: 825},
                ignoreHTTPSErrors: true,
            }
            }]
    };
    module.exports = config;

```

spec.js
```javascript
const { test, expect } = require('@playwright/test');
test('test2', async ({ page }) => {
    await page.goto('https://playwright.dev/docs/test-retries#serial-mode',{waitUntil:"networkidle"});
    await delay_time(60000);
});

```

**Describe the bug**
**Playwright is able to connect to Selenium Grid and run the test successfully** if both Playwright and Selenium Grid are running on same machine. Please see the output. You will notice after connecting to Selenium Grid, Playwright is using **localhost:56284**

```javascript

SELENIUM_REMOTE_URL=http://x.x.x.x:4444/wd/hub DEBUG=pw:browser* playwright test --config=./pw-config-demo.js --workers 1

  pw:browser <connecting to selenium> http://x.x.x.x:4444/wd/hub/ +0ms
  pw:browser <connected to selenium> sessionId=9ab65f1fa67076ea28f001afe600b676 +2s
  pw:browser <ws connecting> ws://localhost:56284/devtools/browser/5c8afa33-8281-4a07-824b-3ebaee8c7715 +26ms
  pw:browser <ws connected> ws://localhost:56284/devtools/browser/5c8afa33-8281-4a07-824b-3ebaee8c7715 +3ms
  pw:browser <ws disconnecting> ws://localhost:56284/devtools/browser/5c8afa33-8281-4a07-824b-3ebaee8c7715 +7s
  pw:browser <ws disconnected> ws://localhost:56284/devtools/browser/5c8afa33-8281-4a07-824b-3ebaee8c7715 +1ms
  pw:browser <disconnecting from selenium> sessionId=9ab65f1fa67076ea28f001afe600b676 +1ms
  pw:browser <disconnected from selenium> sessionId=9ab65f1fa67076ea28f001afe600b676 +59ms

```

**Playwright is able to connect to Selenium Grid but **UNABLE** to run the test successfully** if both Playwright and Selenium Grid are running on different machines. Please see the output. You will notice after connecting to Selenium Grid, Playwright is using **127.0.0.1:63660** on remote machine. Chrome is opened on remote machine with blank page, nothing happens after that.

```javascript

SELENIUM_REMOTE_URL=http://x.x.x.x:4444/wd/hub DEBUG=pw:browser* playwright test --config=./pw-config-demo.js --workers 1

  ✘  [Test] › test/pw1.test.spec.js:20:1 › test1 (1s)
  pw:browser <connecting to selenium> http://x.x.x.x:4444/wd/hub/ +0ms
  pw:browser <connected to selenium> sessionId=723e9c25f1bbeab2c2ffa96c9635bfd6 +1s


  1) [Test] › test/pw1.test.spec.js:20:1 › test1 ===================================================

    browserType.launch: connect ECONNREFUSED 127.0.0.1:63660
    =========================== logs ===========================
    <connecting to selenium> http://x.x.x.x:4444/wd/hub/
    <connected to selenium> sessionId=723e9c25f1bbeab2c2ffa96c9635bfd6
    ============================================================

        at Object._baseTest.extend.browser.scope [as fn] (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/index.js:221:40)
        at Fixture.setup (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/fixtures.js:74:73)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at FixtureRunner.setupFixtureForRegistration (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/fixtures.js:315:5)
        at Fixture.setup (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/fixtures.js:315:5)
        at Fixture.setup (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/fixtures.js:58:19)
        at FixtureRunner.setupFixtureForRegistration (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/fixtures.js:315:5)
        at FixtureRunner.resolveParametersAndRunHookOrTest (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/fixtures.js:300:23)
        at WorkerRunner._runTestWithBeforeHooks (/Users/testuser/Documents/kb-auto-pw/node_modules/@playwright/test/lib/workerRunner.js:478:7)

--- Test output ------------------------------------------------------------------------------------

  pw:browser <connecting to selenium> http://x.x.x.x:4444/wd/hub/ +0ms
  pw:browser <connected to selenium> sessionId=723e9c25f1bbeab2c2ffa96c9635bfd6 +1s

----------------------------------------------------------------------------------------------------
```

**Comment by namilkimfree** [comment]
In the same local, it works normally, but when I run it after configuring the remote VM, it doesn't work.

**Comment by namilkimfree** [comment]
@aslushnikov 
this issue release to v1.8 ?

**Comment by mxschmitt** [comment]
Version 1.18 includes fixes for Selenium 3 and 4. See [here](https://playwright.dev/docs/selenium-grid) for documentation and please file new bug reports if you still encounter bugs.

**Comment by Ivan-Katovich** [comment]
I still have the issue connecting to any cloud browser farms such as saucelabs ( https://saucelabs.com/ ) and experitest using connection through selenium https://playwright.dev/docs/selenium-grid
have such output: 
```
browserType.launch: connect ECONNREFUSED 127.0.0.1:49217
=========================== logs ===========================
<selenium> using additional capabilities "{"sauce:options": {"username": "ivan_kotovich", "accessKey": "e5512834-00f7-4eac-874e-12fe82489cb1"}}"
<selenium> connecting to https://ondemand.eu-central-1.saucelabs.com:443/wd/hub/
<selenium> connected to sessionId=4942dc5035af47cb9e1404cf03317a32
<selenium> using selenium v3
<selenium> retrieved endpoint http://localhost:49217 for sessionId=4942dc5035af47cb9e1404cf03317a32
<selenium> unable to resolve endpoint ip for sessionId=4942dc5035af47cb9e1404cf03317a32, running in standalone?
<ws preparing> retrieving websocket url from http://localhost:49217/
<selenium> disconnecting from sessionId=4942dc5035af47cb9e1404cf03317a32
<selenium> disconnected from sessionId=4942dc5035af47cb9e1404cf03317a32
============================================================
```
Do you have any workeraunds for playwright which is used as library?

**Comment by mxschmitt** [comment]
@Ivan-Katovich please file a new issue for this.

**Comment by oussamadz** [comment]
@Ivan-Katovich have you found a workaround for this error ? 
i am stuck at the same problem where playwright running on ubuntu 22.04 and selenium grid on windows 11.
